### ISSUE TITLE
nixos: After upgrading from 20.03 to 20.09, mysql no longer starts

### ISSUE THREAD

**Issue by jeremypenner** [NixOS/nixpkgs#100177]
**Describe the bug**
In nixpkgs 20.09:
- `mysql-pre-start` tests for the existence of `/var/lib/mysql/mysql`; if it doesn't exist, it initializes mysql and creates `/var/lib/mysql/mysql_init`
- `mysqld` is started
- `mysql-post-start` tests for the existence of `/var/lib/mysql/mysql_init`; if it exists, it creates a new mysql superuser called `mysql` and deletes `/var/lib/mysql/mysql_init`.
- after this, `mysql-post-start` attempts to create any users defined in `services.mysql.ensureUsers` using the `mysql` user

In nixos 20.03, the `root` user is used for ensuring users and the `mysql` user is never created.

This means that after upgrading in-place, `mysql-post-start` attempts to create users, but can't connect and fails. This failure causes the `mysql` service to fail and `mysqld` to shut down.

This can be worked around by running `touch /var/lib/mysql/mysql_init` and restarting the service.

**To Reproduce**
1. Enable mysql on NixOS 20.03, with users configured in `services.mysql.ensureUsers`
2. Upgrade in place to NixOS 20.09

**Expected behavior**
`mysql` service starts cleanly.

**Notify maintainers**
@aanderse 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.69, NixOS, 20.09beta992.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.03.2141.8b071be7512"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment]
Hi @jeremypenner thanks for your report. I'm hoping you can help me with some wording. You aren't the first person to run into this issue and I fear you won't be the last.

From the `20.09` release notes:
> A dedicated non <literal>root</literal>
      super user account is required for operation. This means users with an existing MySQL or MariaDB database server are required to run the following SQL statements
      as a super admin user before upgrading:
```
CREATE USER IF NOT EXISTS 'mysql'@'localhost' identified with unix_socket;
GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' WITH GRANT OPTION;
```

https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2009.xml#L129-L139

Can you please suggest some better wording to emphasize that **no matter what** if you run `mysql` and are upgrading to `20.09` you **have to** run the above statements **before** upgrading?

**Comment by jeremypenner** [comment]
To be perfectly honest, this is the first time I have done a NixOS upgrade and I didn't think to look for release notes. I will know better where to look for answers next time. (I actually had a lot of trouble finding the manual at all, since https://nixos.org/manual/nixos/stable/ still points at 20.03 and https://nixos.org/manual/nixos/unstable/ points at 21.03. I'm not 100% certain why I assumed 20.09 was fully released - possibly just because it showed up in https://search.nixos.org/ ? Looking stuff up from that site is how I do the vast majority of my work with NixOS.)

If I'd come across that message I think it would have been clear to me that I should roll back my system and perform that step. The rest of the upgrade experience was very helpful, with multiple warnings pointing out deprecated options and updated ways of doing things, so perhaps that lulled me into a false sense of security that there'd be some warning about this as well. (Of course now that I understand what the problem is, I understand that it's not really possible to validate it as part of the nix build process.)

**Comment by aanderse** [comment]
@jeremypenner so after reading the release notes do you think this issue should be closed, or is there something you would like to see added to the release notes?

**Comment by jeremypenner** [comment]
I don't see a need to add anything to the release notes, no.

**Comment by aanderse** [comment]
OK cool.

... so we can close this, right?

**Comment by aanderse** [comment]
Thanks!

**Comment by joseph-long** [comment]
This bit me recently. A breaking change that can make your database service not start seems like it should be rolled out incrementally: opt-in to hardening with a required attribute `useHardenedServiceConfig = true;` in 20.09 and then have a removed option error in 21.03 to indicate that this is the new default. (Still wouldn't help you if you jumped from 20.03 to 21.03, I guess.)

On the whole, I'm not too mad, since this is the first time a major NixOS upgrade has had *any* such surprises. On the other hand, unsurprising-ness is my favorite feature of NixOS :)

The thing missing for me from the docs is what to fix after foolishly upgrading without reviewing all the release notes. For me, it was: comment out any `ensureUsers` and `ensureDatabases`, then switch to the new config, run `sudo /nix/store/...store path../bin/mysql -u root` and paste the commands from above:

```
$ sudo /nix/store/xvmrwjlfbidh4izn1lnvhdv72lxc8lzl-mariadb-server-10.4.17/bin/mysql -u root -N
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 16
Server version: 10.4.17-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> CREATE USER IF NOT EXISTS 'mysql'@'localhost' identified with unix_socket;
Query OK, 0 rows affected (0.002 sec)

MariaDB [(none)]> GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' WITH GRANT OPTION;
Query OK, 0 rows affected (0.001 sec)
```

**Comment by aanderse** [comment]
@joseph-long I agree that surprises are bad! What specifically can we do to improve the release notes? Are you able to draft up some changes and we can discuss?

And **always** read the release notes :smile:

**Comment by joseph-long** [comment]
> And always read the release notes 😄

That would be a good thing to add to the ["Upgrading NixOS" chapter](https://nixos.org/manual/nixos/stable/index.html#sec-upgrading), which does not include the words "release notes" at all, so one could hopefully be forgiven for underestimating their importance to upgrading NixOS.

**Comment by aanderse** [comment]
Wow! I can't believe it doesn't say that! That should definitely be added.

**Comment by joseph-long** [comment]
The damage is done at this point, but there is a variable in the default `configuration.nix`:

```
  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "YY.MM"; # Did you read the comment?
```

You could use that to determine what version the MySQL/MariaDB instance was set up with and adjust the configuration based on that.

**Comment by aanderse** [comment]
The change was made for security. I like changes that introduce better security, especially when the release notes tell you exactly what to do before you upgrade to avoid breakage.

In my opinion the only problems here are that you weren't told to read the release notes (ouch...), and the release notes weren't clear enough that they shouldn't be ignored, as some people did.

I'm not sure what other compelling arguments I can make beyond that.

**Comment by joseph-long** [comment]
If this mitigation is for a particular vulnerability, please point me to the relevant issue or discussion on the NixOS security Discourse.

As far as I can tell, you made a change without respecting system.stateVersion that broke working configurations in order to.. very slightly tweak the privilege separation of the pre-start scripts? This hardly seems like an emergency vulnerability mitigation, but again, if there's something I'm missing here, I'm open to learning why this was worth breaking users' existing configurations.

**Comment by joseph-long** [comment]
This is exactly the sort of churn I am trying to *avoid* by using NixOS. It's possible that scanning the release notes for breaking changes is not a step listed in the upgrade documentation because it's not typically necessary. Using the language features of Nix and nixpkgs has, in my experience, provided the "if it builds, it works" behavior I've come to rely on.

Breaking a working configuration should not be done lightly. I'm not yet convinced that "malicious pre-start script" is a threat I need to defend against.

**Comment by joseph-long** [comment]
I'm looking through the PR that made these changes and I see concerns were raised (e.g. https://github.com/NixOS/nixpkgs/pull/86900/files#r422963713) but evidently didn't go beyond the release notes. Which, of course, are not exactly prominent in the documentation. I'm not asking for you or the other maintainers to take a particular action going forward, except to consider that there may be more to performing breaking changes than noting "we broke your setup" in the release notes.

I find myself in agreement with @flokli :

> "It doesn't work anymore, but if I change it to $this, it works again" isn't a sufficient explanation, sorry.
> 
> We need to assess the changes and the implications this has on people making use of it, and giving an appropriate heads-up in the release notes at least. If the tests needed updates, it's likely users configuration need changes, too.

**Comment by aanderse** [comment]
You should get in the habit of reading release notes. NixOS won't solve this problem for you. Specific to your case, here is why you **need** to read release notes:
- You run MariaDB (or MySQL).
- MariaDB requires users to run `mysql_upgrade` after major upgrades (ie. `10.3` to `10.4`)
- Subtle yet painful-to-track-down breakage is likely to occur if you do not run `mysql_upgrade` after a major upgrade.
- NixOS will not run `mysql_upgrade` for you, ever, because it is a "dangerous" operation (can lead to data corruption) and users are **strongly** advised (by MariaDB upstream) to backup their database before running `mysql_upgrade`.

NixOS is also unable to take care of [incompatible Changes Between 10.3 and 10.4](https://mariadb.com/kb/en/upgrading-from-mariadb-103-to-mariadb-104/#incompatible-changes-between-103-and-104) for you, even if we use `stateVersion`. We mention that users of the `mysql` module should read these notes before upgrading because it is important.

---

This post hasn't solved any of your problems, but I hope it has illustrated to you why it is important to read release notes regardless of the change we're discussing here.

**Comment by wjjunyor** [comment]
I hadn't read the release notes and now, rollingback didn't worked :(

**Comment by wjjunyor** [comment]
> This bit me recently. A breaking change that can make your database service not start seems like it should be rolled out incrementally: opt-in to hardening with a required attribute `useHardenedServiceConfig = true;` in 20.09 and then have a removed option error in 21.03 to indicate that this is the new default. (Still wouldn't help you if you jumped from 20.03 to 21.03, I guess.)
> 
> On the whole, I'm not too mad, since this is the first time a major NixOS upgrade has had _any_ such surprises. On the other hand, unsurprising-ness is my favorite feature of NixOS :)
> 
> The thing missing for me from the docs is what to fix after foolishly upgrading without reviewing all the release notes. For me, it was: comment out any `ensureUsers` and `ensureDatabases`, then switch to the new config, run `sudo /nix/store/...store path../bin/mysql -u root` and paste the commands from above:
> 
> ```
> $ sudo /nix/store/xvmrwjlfbidh4izn1lnvhdv72lxc8lzl-mariadb-server-10.4.17/bin/mysql -u root -N
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> Your MariaDB connection id is 16
> Server version: 10.4.17-MariaDB MariaDB Server
> 
> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> MariaDB [(none)]> CREATE USER IF NOT EXISTS 'mysql'@'localhost' identified with unix_socket;
> Query OK, 0 rows affected (0.002 sec)
> 
> MariaDB [(none)]> GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' WITH GRANT OPTION;
> Query OK, 0 rows affected (0.001 sec)
> ```
> 
> Then it's safe to uncomment the `ensureUsers` and `ensureDatabases` attributes and rebuild and mysql should start.

I am dealing with my recklessly upgrade

And wandering if it: [mariadb.nix](https://github.com/Program-Learning/nix-shell-dev_env/blob/361ca3343735b08b13dfe8fb139d6b5f5ded629c/mariadb.nix ) could solve our issues
