### ISSUE TITLE
buildGoModules: switch runVend flag don't rebuild vendor derivation

### ISSUE THREAD

**Issue by yihuang** [NixOS/nixpkgs#100680]
**Describe the bug**
Since the vendor-ed dependencies are included in a fixed-output derivation, if the output is cached then changing the build input (like switch runVend flag or change go.mod) won't cause rebuild automatically.
I'm very surprised when I first encounter this issue and though it's a bug, then I read [this article](https://blog.eigenvalue.net/nix-rerunning-fixed-output-derivations/) to know the detail of the issue. I still think it should be fixed, how do you think the solution proposed in that article?

**To Reproduce**
1. build a go package without `runVend` option or `runVend = false;`
2. change to `runVend = true;`
3. build again

**Expected behavior**
build failed `vendorSha256` mismatch error

**Comment by doronbehar** [comment]
That's the caveat of fixed output derivations - they don't attempt rebuilding them if it's already in the cache. The real `src` that `buildGoModule` needs to build, gets the modified value of `runVend` but it doesn't care about it since if the hash is the same, nix concludes there shouldn't be a need to rebuild it.

**Comment by yihuang** [comment]
We recently switched to [gomod2nix](https://github.com/tweag/gomod2nix).
