### ISSUE TITLE
Unstable channel hasn't updated for 3+ weeks

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#100849]
https://github.com/NixOS/nixpkgs-channels is stuck at 84d74ae9c9cbed73274b8e4e00be14688ffc93fe. According to https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents, there has been at least one successful jobset recently, 128426402, but it doesn't appear to have made it into the channel. Does anyone know what is going on there?

**Comment by cole-h** [comment]
https://status.nixos.org/ reports green across the board at the time of writing. I remember reading somewhere (maybe IRC?) that `nixpkgs-channels` is deprecated -- could be that it finally stopped being pushed to? If this is the case, maybe the repo should be archived, though.

All the release branches now exist in this repo (`nixpkgs`), so you can see that `nixos-unstable` points to the same revision as s.no.o (and indeed clicking on the revision links to here instead of `nixpkgs-channels`).

**Comment by pbogdan** [comment]
This is the relevant issue I believe https://github.com/NixOS/nixpkgs/issues/99257

**Comment by primeos** [comment]
From https://github.com/NixOS/nixpkgs/issues/99257#issuecomment-703607739:
> Step 1 is done. So nixpkgs-channels doesn't contain branches for nixos-20.09.
> I'll set the milestone for this issue to 21.03 as a reminder to archive the repo around then.

I guess we should additionally do one of the following regarding the `nixpkgs-channels` repository then:
- Delete the `nixos-unstable` branch
- Keep updating the `nixos-unstable` branch until the repo is archived (21.03)
  - And delete the `nixos-unstable` branch before archiving so that scripts hopefully fail noticeably (vs. silently do nothing)?

(cc @edolstra)
