### ISSUE TITLE
go: multiple package outputs(?) undocumented

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#10149]
(Title is my best guess. Please change it to something better once you understand what the real issue is.)

I'm trying to to set up a dev environment using `nix-shell` on `nixos-version` = `16.03pre69463.68bd8e4 (Emu)`. This is my `default.nix`:

``` nix
with import <nixpkgs> {};

goPackages.buildGoPackage rec {
  name = "yourproject";
  buildInputs = [ gdb mercurial
    goPackages.net
    goPackages.grpc
    goPackages.go-sqlite3
    goPackages.protobuf
    protobuf3_0
];
  goPackagePath = "quotedb";
  shellHook = "export GOPATH=`pwd`:$GOPATH; export PATH=`pwd`/bin:$PATH";
}
```

Having run `nix-shell` I try to run `protoc-gen-go`. I get the response that

```
The program ‘protoc-gen-go’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.go14Packages.protobuf
  nix-env -iA nixos.go15Packages.protobuf
```

That's weird since it's clearly in the buildInputs. Examining the `$GOPATH` I see that protobuf pkgs is  under `/nix/store/4ajzfbg3mgmwgmqghhrcj5iv8g23qc6c-go1.5-protobuf-2015-08-23/`. There is no `/bin` under that path, however.

After running `nix-env -iA goPackages.protobuf` `protoc-gen-go` does become available. Apparently it is under `/nix/store/4xxf2rpwiajk5ksh9c4jhj5srp1vlqp5-go1.5-protobuf-2015-08-23-bin/`.
1. Is this behavior documented somewhere? Why is there this split? I couldn't find it in the Nixpkgs Contributors Guide and didn't see when skimming `pkgs/top-level/go-packages.nix` either.
2. How DO I get the `protoc-gen-go` binary into my path? `goPackages.protobuf` ∈ `buildInputs` doesn't seem to be the way.

**Comment by globin** [comment]
Adding `goPackages.protobuf.bin` should be enough. And yes it's happening due to multiple build outputs, happens afair in builGoPackage. The changes were made by @wkennington AFAIK he can probably explain the background and give more information.

**Comment by wkennington** [comment]
The behavior was not documented but the idea is this. Go deals with
sources, objects, and resulting binaries. The sources and objects are
needed together usually as dependencies for libraries and applications /
servers. Rarely, as is the case with protobuf, the builder needs the native
executable output. buildGoPackage optimizes for the common case, presenting
the output to be used as a buildInput by other applications as the majority
of gopackages are libraries. Unfortunately this means that in order to get
the resulting binaries, you need to explicitly specify that you want the
bin derivation and not the default out. To also address the question of why
the outputs are [ out bin ] and not [ dev out ], its simply because
propagatedBuildInputs are hardcoded to work with "out" but not dev, and we
always want to propagate sources not binaries as the output binaries are
almost never needed in the builds. As for why all-packages contains entries
like goPackages.xxx.bin // { output = [ "bin" ]; }. We want to make sure
end users get the binaries but also make sure that their environments don't
depend on sources / objects as environments pull in all outputs in the
outputs attribute.

**Comment by copumpkin** [comment]
@wkennington is there not a way to not include source of dependencies in Go? What if someone were to write a closed-source library?

**Comment by wkennington** [comment]
Maybe, if go could output shared libraries. Interestingly this isn't a
focus of the language as Google is really only concerned with static
linking. Maybe you could write a shell source file and store some object
files for the real version and include that.

**Comment by zimbatm** [comment]
Where does that kind of documentation go, should I add it to the buildGoPackage derivation ?

**Comment by Profpatsch** [comment]
triage: was the documentation updated?

**Comment by tomberek** [comment]
close?

**Comment by kamilchm** [comment]
I wrote a word about outputs some time ago https://github.com/NixOS/nixpkgs/commit/7d02cc1dd50766058b2ec2c6d3a741d96db5d27b but nothing about sharing libs.
