### ISSUE TITLE
IPython notebook, no longer working

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#10169]
IPython notebook have stopped working here (16.03pre69463.68bd8e4 (Emu)). It was working ~3 months ago.

Error: ImportError: No module named notebook.notebookapp. Log is here:
https://gist.github.com/anonymous/16a0b40030de97595c59

@FRidh @geerds @bjornfor

**Comment by FRidh** [comment]
I guess you installed only `python27Packages.ipython` and not `python27Packages.notebook`. Since IPython 4.0 IPython has been split in multiple packages. The notebook is now in  `python27Packages.notebook`. If you want to have the notebook, and run Python in it, you need to install both, e.g. `nix-shell -p python27Packages.ipython python27Packages.notebook`

**Comment by FRidh** [comment]
if there are no circular dependencies we might actually make the `qtconsole` and `notebook` dependencies of `ipython`, easing the transition.

**Comment by joelmo** [comment]
Ah that's it. Maybe it's better to keep it as is, or create a meta package that includes both. I'm closing because you solved my problem, thanks!
