### ISSUE TITLE
ruby, bundix: bundlerEnv-based packages installs Gemfiles in ~/.nix-profile

### ISSUE THREAD

**Issue by aespinosa** [NixOS/nixpkgs#10177]
Hi,

I noticed when installing bundlerEnv packages that symlinks are also generated for Gemfile and Gemfile.lock files in ~/.nix-profile. This is harmless if you only installed a single ruby-based package. But then conflicts will happen after the second package is made.

```
nix-env -i bundix -i sup
Installing ‘bundix’
installing ‘sup-0.20.0’
building path(s) ‘/nix/store/hxwri0hrl64fy07bv0f12ii9rwxhz32d-user-environment’
Wide character in die at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
collision between ‘/nix/store/9ww27zrsxbqrh66vhf76ahbkpsqnrpvn-bundix-bundle/Gemfile’ and ‘/nix/store/4vax7fw9rflsgzjlnanbbn9286sn2pnn-sup-0.20.0-bundle/Gemfile’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/0iv85dkvgvannw5a8k2b14lcg03pwj2m-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/0iv85dkvgvannw5a8k2b14lcg03pwj2m-user-environment.drv’ failed
```

cc @cstrahan

**Comment by cransom** [comment]
I also noticed this one recently. I'm not sure why it's valid that gemfiles are installed in my .nix-profile as I won't ever call on them directly (I don't think).  

I'd be interested in knowing if there was a better solution rather than my naive attempt referenced, which just renames the installed Gemfiles to Gemfile-${name}, which avoids the conflict.

**Comment by aespinosa** [comment]
The file is actually being referenced  in the bin/script-name. But I'm also not sure if its needed at the nix-profile.

Maybe do something similar to goPackages where the outputs are out (for dependencies) and bin for actual binaries.

**Comment by cransom** [comment]
I spent a little time looking over bundlerEnv and there's a lot going on in here.

The method you mention for goPackages I don't think applies here because when a go binary is installed, it's static and doesn't rely on anything else.

bundix/bundlerEnv, on the other hand, relies on the $package-bundle completely and the -bin is just a stub to run the bundle. The gemfile has to exist in order to actually run the app, but it doesn't need to be Gemfile, as my referenced patch shows.

Ever since the ruby packaging was switched over to bundix, this existed and I haven't seen it addressed anywhere else.

**Comment by cstrahan** [comment]
I have a PR open that will fix this: https://github.com/NixOS/nixpkgs/pull/8612

I hope to merge it into staging this weekend.

**Comment by cransom** [comment]
Nice. Thanks @cstrahan. I'll keep an eye out for the extra fixes and then give it a whirl myself.

**Comment by jagajaga** [comment]
Closing via https://github.com/NixOS/nixpkgs/pull/8612
