### ISSUE TITLE
GHCJS LTS package sets

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#10215]
It's awesome that we have LTS package sets now, but they only work for GHC. Stackage supports/is-about-to-support using LTS with ghcjs, so it would be nice if we had ghcjs LTS package sets too.

**Comment by peti** [comment]
51 additional package sets?

**Comment by Ericson2314** [comment]
Hah. In the short term, I believe there exists versions of ghcjs for only more recent LTSs.

In the long term, yes I suppose it will double the number of package sets. Is that a problem though? We don't need to cache every package set. And since the LTS has the same packages for GHC or GHCJS, it shouldn't actually require more cabal2nix scraping, just generating a `compiler -> package set` expression to be instantiated with the correct version of ghcjs and ghc.

**Comment by Ericson2314** [comment]
I'd be fine overwriting the compiler manually. @bennofs wrote an expression to do that, but it tripped an assertion.

**Comment by peti** [comment]
Can you share the expression? Maybe the assertion is harmless and can be fixed.

**Comment by bennofs** [comment]
All the LTS package set configurations  have an assert on ghc.name, which fails with ghcjs

**Comment by Ericson2314** [comment]
For the record, @bennof's expression was
```nix
haskell.packages.ghcjs.override {
  packageSetConfig = callPackage
    <nixpkgs/development/haskell-modules/configuration-lts-3.6.nix>
    {};
}

**Comment by peti** [comment]
The assert is gone in 2ff1ebc619037a2978dc4f88643e9347952ee261.

**Comment by Ericson2314** [comment]
Sweet thanks! The other part of the issue is to make sure that built-in libraries match the LTS versions. [I suppose this technically affects GHC too, but is less of a practical problem there.]

Tagging @ryantrinckle and @k0001 who know more about that problem then I.

**Comment by peti** [comment]
I am sorry for being dull, but what does it mean to "make sure that built-in libraries match the LTS versions"?

**Comment by k0001** [comment]
@peti @Ericson2314 to be honest, it might be a bit premature to talk about (Stackage) LTS support yet. Let me clarify.

There are two different issues here:

1. When we speak about “LTS” we mean “Stackage LTS”, that is, a package set that pins each Haskell library to particular version. As of today there isn't a Stackage LTS version intended to work well with GHCJS, mainly because there hasn't been any public release of GHCJS in Hackage. So, for that reason, talking about having a package set for GHCJS based on Stackage LTS is a bit premature. 

2. The other issue is that, when working on a project intended to build both with GHC and GHCJS, it is desirable to pin the Haskell libraries that are used in the package sets for both compilers to the same version. This is desirable because otherwise the behavior of your project may be different depending on which compiler it was used. For example, if our project involves an HTTP server compiled with GHC and an HTTP client compiled with GHCJS, one wants to ensure that the version of `aeson` used in both applications is the same, so as to guarantee that JSON encoding and decoding between the two programs is compatible and predictable.

Personally, I think it is too early to try and solve problem 1, as there hasn't been an official Stackage LTS release designed to work well GHCJS. Nevertheless, there has been some progress on that front upstream anticipating an upcoming release of GHCJS, so I might be worth trying to keep up with those ongoing efforts: https://github.com/commercialhaskell/stack/issues/337

Regarding point 2: That is desirable with our without Stackage LTS, and it can exist today. For example, we can have a package set named `ghc7102_for_ghcjsHEAD` (or similar names) that would be just like `ghc7102` but with the versions of the packages offered matching those in `ghcjsHEAD`. Notice that this is useful even in light of an official Stackage LTS release, as Stackage LTS usually runs a bit behind the latest versions of some packages in Hackage, and more often than not, when one wants to work on a new version of a package, the versions offered in Stackage LTS are not new enough. 

I have been meaning to send a pull request creating the `ghc7102_for_ghcjsHEAD` package suggested above, but I haven't had the time to do so yet. 

/cc @mayhewluke

**Comment by peti** [comment]
Thank you for the clarification. The `ghc7102_for_ghcjsHEAD` package set you've described, how would that differ from `haskell.packages.ghcjs`? Why do you we need an additional package set?

**Comment by k0001** [comment]
@peti the package set in `haskell.packages.ghcjs` is intended to be compiled with GHCJS. What we need is a package set that contains the same versions of the packages as `haskell.packages.ghcjs` but is intended to be compiled with whatever GHC compiler GHCJS expects (as of today, ghc7102). In another words, what I propose as `haskell.packages.ghc7102_for_ghcjsHEAD` is `ghc7102` but with some packages restricted to exactly the same versions that GHCJS uses, which means that `ghc7102_for_ghcjsHEAD` and `ghc7102` will share most package definitions, so there won't be a need to recompile every derivation in this package set if we already have compiled it for `ghcj7102`.

Remember: the goal here is to be able to ensure that, for projects that need to be compiled with both GHC and GHCJS we can pick two package sets that provide the same versions of Haskell libraries. In this way we can be certain in cases such as the HTTP client/server example I gave before that we are using the same version of libraries both in the server and the client, which leads to a predictable interaction between the client and the server. 

_Minor note about the nomenclature I am using: What is now called `haskell.packages.ghcjs` should probably have been called `haskell.packages.ghcjsHEAD`, but it is not worth changing it now. I am using the name `ghcjsHEAD` here to make explicit the fact that we are talking about an unreleased version of GHCJS. Eventually, when official releases are available, we will have `haskell.packages.ghcjs020`, `haskell.packages.ghc7102_for_ghc020` and the like._

@peti does this make sense to you?

**Comment by k0001** [comment]
Correction from my previous comment: 

> whatever GHC compiler GHCJS expects (as of today, ghc7102)

Actually, for this particular case, it is not true that GHCJS expects a particular compiler (at least not today). In theory we could have, say, `haskell.packages.ghc7102_for_ghcjsHEAD` and `haskell.packages.ghc784_for_ghcjsHEAD`, but there is no need to add every possible combination of GHC version and GHCJS version right away; it can be done as the need for it arises.

**Comment by peti** [comment]
I believe that it would be best to prepare a PR so that this whole subject can be evaluated looking at a concrete implementation. I think I understand your description. I'm just not sure yet what the best is to implement it. I'm not particularly fond of the idea of defining lots of "duplicated" package sets. It would be great if we'd find an elegant way to avoid that.

**Comment by k0001** [comment]
@peti thanks for your feedback. Sure, don't worry, I'll send a pull request
for this myself. I just wanted to explain what was in my mind and why this
is needed so that we are all in the same page.
Il 05/ott/2015 02:55 PM, "Peter Simons" <notifications@github.com> ha
scritto:

**Comment by mayhewluke** [comment]
Here's another approach: handle things at the `ghcjs.withPackages` level. Then there wouldn't be a need to have another package set.

**The Problem:** GHCJS hardcodes a bunch of packages into itself. In order to avoid having `nix` derivations conflicting with that, `configuration-ghcjs.nix` [defines the packages as null](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-ghcjs.nix#L16), effectively defaulting to the built-in versions. However, that then causes the problem that `nixpkgs` has no information on the package versions and thus they can't be matched on the GHC side of things.

**The Idea:** So what if instead `configuration-ghcjs.nix` *did* define derivations for the versions of all the packages built in to GHCJS? Then if any of those packages were passed to `ghcjs.withPackages` it would just ignore them (or print an error/warning). This way the `haskell.packages.ghcjs` package set would appear to contain the exact same packages to both GHC and GHCJS but under the hood it'd be using the GHCJS built-in packages when the compiler is GHCJS. Essentially to ensure compatibility between GHC and GHCJS you'd just use the same package set for both, which would hopefully be intuitive rather than confusing.

I'm in the middle of switching over to NixOS right now so I don't have a working development setup yet (and therefore can't prepare a PR right now) but here's a **(psuedo-code)** example:

```
# configuration-ghcjs.nix
...
aeson = overrideCabal super.aeson (drv: {
  version = "0.9.0.1";
  ...
});

withPackages = packages:
  let pkgs = filterOutGhcjsBuiltins packages
  in super.withPackages pkgs
```

```
# /home/user/project/server.nix
...
haskellPackages.mkDerivation {
  ...
  buildDepends = with haskell.packages.ghcjs; [
    aeson
    ...
  ];
}
```

```
# /home/user/project/client.nix
...
haskell.packages.ghcjs.mkDerivation {
  ...
  buildDepends = with haskell.packages.ghcjs; [
    aeson
    ...
  ];
}
```

**Comment by Ericson2314** [comment]
@mayhewluke that actually sounds pretty good to me if `ghcjs.withpackages` could assert that the version is correct before it ignores it.

**Comment by ryantrinkle** [comment]
Maybe the packages can explicitly indicate, somehow, that they're supposed to be built-in?  I would definitely find it very confusing if, e.g., an override to add a patch was silently ignored.

**Comment by peti** [comment]
Why not define the builtin packages conditionally, depending on the value of `ghc.isGhcjs`? 

~~~~
self: super: {
  # core packages provided by ghcjs
  foo = if ghc.isGhcjs then null else self. foo_1_2_3;
  ...
}
~~~~

**Comment by mayhewluke** [comment]
@peti That seems like a much cleaner way to do things. It does carry one downside, however - I don't see a way to provide a warning/error to users who try to supply their own version of one of the built-in packages. This then results in the package choice being silently ignored, which would be confusing, as @ryantrinkle points out.

**Comment by peti** [comment]
@mayhewluke, the attribute name `foo` always refers to the version of `foo` that `ghcjs` has, too, so if someone runs the build with another version,

**Comment by peti** [comment]
@mayhewluke, the attribute name `foo` always refers to the version of foo that `ghcjs` has, too, so if someone runs the build with another version, she must provide that version explicitly, i.e. by passing `foo_2_0` to the build environment. If someone does this, then I'd assume that they know what they are doing.

IMHO, it's perfectly fine for those versions to not match. It's just that they *should match* by default.

**Comment by mayhewluke** [comment]
@peti I've tested declaring the built-in packages that way, but it doesn't seem to work:

```
# configuration-ghcjs.nix
aeson = if self.ghc.isGhcjs then null else overrideCabal super.aeson (drv: {
  version = "0.9.0.1";
  sha256 = "1g7qdq7zpyvqwmh4sfhizqpb51cg24lrcj9vq5msz8k896y7vfcj";
})
```

When trying to use this version of `aeson` with the GHC side of my project (eg. `buildTools = [ haskell.packages.ghcjs.aeson ];`) it still receives `null`, not the derivation. I think this is because `self.ghc` is actually defined when the package set is defined, not when the package gets passed to a compiler ([pkgs/top-level/haskell-packages.nix#L107](https://github.com/NixOS/nixpkgs/blob/b2588adb6eb20dfab266e8804123b5f8b6b1128d/pkgs/top-level/haskell-packages.nix#L107)). This would make the conditional always return the same result.

**Comment by mayhewluke** [comment]
To be honest, I'm not convinced this problem can be solved with the way things currently work unless we want to create another package set.

Ultimately what we're looking for is a way to compile the same package with two (or more) different compilers. This way we can be sure we're using the same package version with both compilers. However, a Haskell derivation can only contain one set of build information (`buildDepends`, `libraryHaskellDepends`, etc.). This becomes a problem when different compilers require different build information - in this case the derivation will only work with one of them. The only way around that is to create a second derivation with the build information overridden. But then in order to use the same package versions across two different compilers we'd need to have two different package sets. In the case of GHCJS + GHC, this would be along the lines of @k0001's `ghc7102_for_ghcjsHEAD` suggestion.

While I think that seems like the best bet in the short term, it would definitely add extra maintenance overhead in the long term, and I think that it covers up an issue with the current infrastructure - the current Haskell derivation format can't support the growing complexity of the Haskell world.

A Haskell package at a single version point may be capable of being compiled by multiple different compilers - either through inherent compatibility or through having specific instructions for each compiler (eg. `if impl(ghc < 7.8.4) ...`). Nix's Haskell derivations, on the other hand, tightly couple the derivation and version to the build implementation (and compiler). That is, if you need different build information for different compilers then you need different derivations. In fact, if you want to use different compilers at all (even with the exact same derivations) you'll need different package sets, since the compiler is [hardcoded into the package set itself](https://github.com/NixOS/nixpkgs/blob/7d3ffc5bf857b8db0af3c5b8f54216c6993b2ce5/pkgs/top-level/haskell-packages.nix#L107).

An alternative would be if each derivation could contain build information for different compilers, just as the `.cabal` file can. The derivation would then be evaluated against the compiler at the point it is instantiated, rather than having that hardcoded into the package set. We'd then be able to do something like the following:

```nix
let
  hPkgs = pkgs.haskellPackages;
  ghcPkgs = hPkgs.lts-3_8 // hPkgs.ghc;
  ghcDrv = ghcPkgs.mkDerivation {
    # ...
    buildDepends = with ghcPkgs; [
      # ...
    ];
  };
  ghcjsPkgs = hPkgs.lts-3_8 // hPkgs.ghcjs;
  ghcjsDrv = ghcjsPkgs.mkDerivation {
    # ...
    buildDepends = with ghcjsPkgs; [
      # ...
    ];
  };
```

Basically, GHC and GHCJS are using the same package set, since any special build information needed to build a package with either compiler would already be contained within the packages in the set. They'd also be able to include the packages that are built-in to either compiler, since those packages could just return `null` for that compiler. `haskellPackages.ghc` and `haskellPackages.ghcjs` would presumably contain any overrides for package versions (the overrides for build information would be part of the packages themselves). Admittedly I haven't had the time to really think this through too hard yet so it may have some flaws, but I think that it works to address the direction Haskell is heading, with more and more use of alternate compilers (and it also introduces some nice separation of concerns, hopefully).

**Comment by Ericson2314** [comment]
@k0001 Sorry, but what exactly about ghcjs getting a haskell release is relevant? Not sure I saw anything of note here, https://github.com/ghcjs/ghcjs/wiki/Hackage-release-checklist but maybe I am missing something, or it has to do with the release process itself. You've mentioned that we are stuck until next release, and I trust you have a good reason for that, but what is it? :)

@mayhewluke Actually the package sets are already defined to be compiler agnostic, check out `pkgs/development/haskell-modules/configuration-lts-3.6.nix`. It's just that currently they are only exposed applied to ghc, hence the big long `<...>` in bennof's script to find the original file. Just exposing the originals to avoid the `<...>` would I suppose to be a step in the right direction. Conversely, a derivation by definition has all dependencies resolves exactly--it's an exact plan for building something.

**Comment by k0001** [comment]
Sorry, I haven't paid attention to this thread since the last time I wrote as I have been busy with other things. 

> Sorry, but what exactly about ghcjs getting a haskell release is relevant?

@Ericson2314, about this, I might have made a typo somewhere, I wanted to say “Hackage release”, not “Haskell release”. What I was trying to say is that for as long as there isn't a release of GHCJS in Hackage we would be playing catch-up trying to mix and match different versions of different packages in the package sets until they can compile together. Once there is a Hackage release people will start trying to make their libraries compile using that precise version. Well, I hope. 

I'll catch-up with the rest of the comments tomorrow, sorry!

**Comment by peti** [comment]
@mayhewluke, 

> I've tested declaring the built-in packages that way, but it doesn't seem to work.

you are right, the `haskell.packages.ghcjs` package set is built with `ghcjs`, not `ghc`. We'll need a variant of that package set that uses `ghc` instead. For testing purposes, you can simply define such a package set by overriding the `ghc` argument to `haskell.packages.ghcjs`.

**Comment by mayhewluke** [comment]
@peti 

> We'll need a variant of that package set that uses ghc instead.

Understood. This is essentially what @k0001 was suggesting with the `ghc7102_for_ghcjsHEAD` idea, I think. However, you raised an understandable concern at that time, though:

> I'm not particularly fond of the idea of defining lots of "duplicated" package sets. It would be great if we'd find an elegant way to avoid that.

That's where my previous comment comes in. Although admittedly a long read, it was an attempt to propose a (hopefully) elegant solution - something that I think is starting to become increasingly important with GHCJS complicating the Nix/Haskell ecosystem.

> For testing purposes, you can simply define such a package set by overriding the `ghc` argument to `haskell.packages.ghcjs`.

Just as a minor clarification - one would also have to override the packages that have GHCJS-specific build information (eg. `ghcjs-dom`, `reflex`, etc.)

**Comment by mayhewluke** [comment]
@Ericson2314

> Actually the package sets are already defined to be compiler agnostic, check
> out `pkgs/development/haskell-modules/configuration-lts-3.6.nix`. It's just
> that currently they are only exposed applied to ghc, hence the big long <...>
> in bennof's script to find the original file.

I see a couple caveats with that:

- The LTS configuration sets don't actually define versions for all of the
  packages. They seem to be designed to be applied against a specific package
set (hence why they're only exposed after being applied to one, I suppose), and
they function as diffs between the versions in that package set and the versions
in the LTS version. That is, they only define package versions when the
package set they're designed for deviates from the LTS version. Otherwise they
reuse the same package version as is in the set they're applied to. If you apply
the LTS configuration to a different package set than the one it's intended for,
you're likely to end up with a set of packages that don't actually match the LTS
version after all.
- You still have to have **at minimum** a package set per compiler version, **plus** the
  LTS package set (ie. the version set). There are two reasons for this:
  - The LTS package set only defines versions, not build instructions, so you
    still have to have a compiler package set in order to define the build
instructions. You'd have to have one of these sets per compiler since each
compiler can end up needing different build instructions.
  - The compiler is defined when the package set is created. You can override it
    (`ghcjsPkgs = haskell.packages.ghcjs.override { ghc = haskellPackages.ghc; }`)
but that doesn't change the derivations in the package set, which will still
have the build instructions for the original compiler. Now, it'd seem like you
could get around this using the LTS sets since you could just apply the same set
of LTS version overrides to both compiler sets. This way the package sets would
keep the appropriate build instructions but have the versions overridden to use
the same versions. The problem there is with the diffing behaviour of the LTS
sets - some of the package versions could differ in each compiler set and the
LTS might not define a version override. Thus you'd get different versions
between the sets.

------

> a derivation by definition has all dependencies resolves exactly--it's an
> exact plan for building something.

Right. I think perhaps my wording was a bit vague and/or incorrect. As a concrete
example, what if package sets weren't sets of derivations but rather sets of
functions that took a compiler and returned a derivation based on that compiler?

```nix
let pkgs = {
  aeson = compiler:
    if compiler.pname == ghcjs then
      null
    else
      mkDerivation {
        # ...
       }
    ;
  ghcjs-dom = compiler:
    if compiler.pname == ghcjs then
      mkDerivation {
        # ...
        buildDepends = [ self.base self.mtl self.text self.ghcjs-base ];
      }
    else
      mkDerivation {
        # ...
        libraryHaskellDepends = [ base glib gtk3 text transformers webkitgtk3 ];
      }
    ;
```

Obviously the logic code could be improved (and maybe there's a better way to do
this than using functions), but it allows building a package against multiple
compilers (and tries to avoid violating the definition of a derivation!) Passing
in the compiler could obviously be automated by `mkDerivation` as well, for ease
of use.

IMHO it makes sense for a package set to be responsible for package versions and
the items in the set to be the ones responsible for actually getting the package
built. It seems like a better separation of concerns, which could be easier to
maintain and could allow for greater extensibility for future needs.

**Comment by Ericson2314** [comment]
@k0001 Sorry the haskell/hackage typo was entirely my own. Sounds like you are saying until ghcjs makes a release, everybody is going to be using a commit du jour off master. But once a version is released, if it's builtin libraries are somewhat odd versions we still have trouble.

**Comment by Ericson2314** [comment]
I opened https://github.com/ghcjs/ghcjs/issues/442 which I believe should assist with this.

**Comment by Profpatsch** [comment]
Since we’re getting rid of the normal LTS packagesets anyway, is this issue still relevant?

**Comment by peti** [comment]
It's certainly an issue that nobody seems to be working on. I'm closing it for now, particularly since the ball appears to be on ghcjs' court.

**Comment by Ericson2314** [comment]
The ball is indeed in their court. 

>Since we’re getting rid of the normal LTS packagesets anyway...

Woah, is there something to read about this?

**Comment by peti** [comment]
See 641fc0e683a9abf6f128983490a85d9f635b3a32.
