### ISSUE TITLE
vim: usable defaults

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#10233]
vim should have usable default settings like Ubuntu and maybe every other Linux Distribution.

i can't use the arrow keys and delete characters for example...

**Comment by copumpkin** [comment]
:+1:

**Comment by cleverca22** [comment]
it also doesn't load /etc/vim/vimrc so you cant just set defaults in configuration.nix

**Comment by davidak** [comment]
i don't know what is the best practice for the configuration files of nixpkgs. @edolstra 

ubuntu has this files for example:
/etc/vim/vimrc:
https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/vim/vivid/view/head:/debian/runtime/vimrc
/usr/share/vim/vim74/debian.vim:
https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/vim/vivid/view/head:/debian/runtime/debian.vim.in

**Comment by edolstra** [comment]
Why doesn't upstream vim provide usable defaults?

**Comment by davidak** [comment]
@edolstra actual there is only `<nixstore>/share/vim/vim74/vimrc_example.vim` and no vimrc.
@lovek323 we should `cp vimrc_example.vim vimrc` and maybe change some values.
i can make a PR for that.

**Comment by matthiasbeyer** [comment]
@edolstra Upstream vim does provide defaults: The default is that the user has to configure vim to fit his needs and that's exactly the reason why I **strongly vote against a default-vimrc**.

Vim is a tool that users have to configure to their very specific needs. There are people out there (for example me) that do not even share their vim configuration because they consider it as something really private and intimate.

I'd go the archlinux-kindof way here: `default vimrc == empty vimrc`!

**Comment by davidak** [comment]
@matthiasbeyer we have ~200 ubuntu-servers and only use the default config for vim. it works for us.

i think programs should have usable default configurations. vim is not usable without a vimrc (at least for me).

**Comment by copumpkin** [comment]
@matthiasbeyer I don't understand why you would intentionally raise the bar for usage of vim. Tons of users are casual users who just need to change the occasional config file on a server with it and don't care about setting up custom key bindings and commands. Why make life difficult for them, especially when it doesn't make life any more difficult for vim power users? It's not as if the default config can't be overridden, or as if power users need to jump through more hoops to install their custom configuration if a default is in place.

**Comment by matthiasbeyer** [comment]
@copumpkin Because

1. We would need to agree on sane defaults. Hard enough.
2. Others made this effort already, for example tpope with vim-sensible
3. It would be effort for us. Investing the manpower elsewhere would benefit us much more
4. It is not the task of the packagers to add "sane defaults" for package configurations. If you argue against this, I propose to add a `.gitconfig` default - same issue, but nobody argued on "lets add some default aliases for git" by now... you see my point?

**Comment by copumpkin** [comment]
I thought we were just proposing adopting another distro's default file? All I want is to not have to tell folks that they need to jump through a hoop to make their arrow and delete keys behave sensibly in vim. We don't need anything fancy, but I does anyone ever actually want capital letters to show up instead of arrow keys?

**Comment by jagajaga** [comment]
I agree with @matthiasbeyer. We must not provide any defaults except the ones that program do provide. Vim do not provide `default.vimrc`, it has an example. So users have to look at example and create their own (or copy the example).
If you need to manage your vim configuration we have https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/vim-utils.nix#L281. Check this for example https://github.com/jagajaga/my_configs/blob/master/.nixpkgs/common.nix#L28

**Comment by aneeshusa** [comment]
As an alternative, I just switched to neovim entirely. It comes with sensible defaults baked in without the need to ship a default file. I would propose using neovim as a default editor instead of vim, as they have put in the effort to ship good defaults and we would not have to do that.

On-topic, I would recommend providing sane defaults for vim. This is already done for zsh with programs.zsh.enable and I don't see why vim should be any different. Also, Arch Linux actually does ship a defaults file in the vim-runtime package in /usr/share/vim/vimfiles/archlinux.vim - it's only 5 or 6 settings, but they make vim considerably more user-friendly. I definitely missed them when switching.

Failing that, I think it would be wise to at least have a programs.vim.enable option that sets up sane defaults, and just copy defaults from another distro (e.g. Arch), for users that just want vim to work without creating a complex configuration.

**Comment by matthiasbeyer** [comment]
@aneeshusa How did you configure nvim with plugins? I used the nixos infrastructure for vim plugins, which should also work for nvim, but doesn't for me. I guess that's another topic, though.

On topic: An option like `vim.enable` would also set `$EDITOR` to `vim` right? I am not sure what my opinion is on this, though I think: We shouldn't ship defaults but if someone wants to maintain a set of defaults and provide options to auto-set them (not setting them as default but having an option to enable them), I personally wouldn't mind. I still think that the time spend for approaching this could be put into other things which are considerably more relevant.

**Comment by aneeshusa** [comment]
To be honest, I don't use any plugins so I don't know about the existing NixOS infrastructure, but I also think that (n)vim plugins should be per-user and managed by a [nixuser](https://github.com/NixOS/nixpkgs/pull/9250) type system. Any extensive configuration like that is likely to be personal and I don't see the value in managing that at a system (NixOS) level.

```programs.zsh.enable``` is different from ```users.defaultUserShell```, which sets the default shell, and ```users.users.<name?>.useDefaultShell```. Similarly, IMO a ```programs.vim.enable``` would default to false, would provide sane defaults (to be clear, change 5-6 settings and no plugins) if enabled, and would not set $EDITOR or $VISUAL; each user can do that individually if they want. I think this is a small enough scope to be valuable to add to NixOS; if this is something we are interested in, I would be willing to maintain that.

**Comment by davidak** [comment]
yesterday i installed 2 VMs and can't use vim on the live cd :(

i don't want to configure anything in an installation environment.

it are basically this two setting:

```
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start
```

**Comment by copumpkin** [comment]
Radical!

**Comment by zimbatm** [comment]
@davidak care to make a PR that imports either the defaults from Arch or just your two lines ?

**Comment by jagajaga** [comment]
@zimbatm I'm against this PR. Read my opinion above please.

**Comment by zimbatm** [comment]
@jagajaga how will it affect you if we merge a change like this ?

From what I've read it seems like you value upstream purity over convenience, is that correct ? If that's the way I would agree with you in principle, unless upstream is not willing to make any changes. That's certainly the case with vim (hence neovim).

Overall I don't think that changing the defaults to a vim-sensible equivalent would hurt anyone and would actually make the out-of-the-box experience nicer.

**Comment by joachifm** [comment]
The settings proposed by @davidak really are required for vim, to the point that providing vim without them out of the box borders on misleading. Speaking for myself, I'm always startled when running `vim` and being treated to the authentic vi experience instead. It's like taking a drink thinking you're getting cola but then it turns out to be milk.

If authentic vi is desired, it makes more sense to me to provide a separate package, e.g., using heirloom vi or nvi.

**Comment by copumpkin** [comment]
Curious if any of the :-1:  wants to respond to this point I made earlier:

> I thought we were just proposing adopting another distro's default file? **All I want is to not have to tell folks that they need to jump through a hoop to make their arrow and delete keys behave sensibly in vim**. We don't need anything fancy, but **does anyone ever actually want capital letters to show up instead of arrow keys?**

**Comment by zimbatm** [comment]
Here is a version that imports the vimrc from archlinux: https://github.com/NixOS/nixpkgs/pull/13486
I made the default configurable in case you *really* want that vi mode.

**Comment by nyarly** [comment]
I see this is closed already, but I found that installing 'vimNox' as opposed to simply 'vim' was a bang-up-good solution to this. Looking at it's expression (in vim_configurable), it also looks like what you'd want to use if you wanted to set up a particular local compilation of vim. Hope this helps someone in the future.
