### ISSUE TITLE
docker-compose leaks python in PATH

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#102468]
**Describe the bug**
docker-compose leaks the python binary so when I create a shell with docker-compose and a poetry environment, I get in PATH the python from docker-compose and not from my python environment.

**To Reproduce**
```
let
  # replace this with a poetry env/python.withPackages of your own
  myPythonEnv = import ./nix/pyEnv.nix { inherit nixpkgs; };

  nixpkgs = import <nixpkgs> {};

  # last nixpkgs with docker 1.25.0
  # (to avoid the bug https://github.com/docker/compose/issues/7127)
 # I checked against master and the package hasn't changed
  old = import (fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/3223730c3d202f34f3833e37caeab875c85621a6.tar.gz";
    sha256 = "05z9lfm3sz8c4ffah5xhc1gcv52b7dhkzmby4lmla7dpq4zsj3gm";
  }) {};

in
nixpkgs.mkShell {
  name = "platform";
  buildInputs = with nixpkgs; [
    old.docker-compose
    myPythonEnv
  ];

}
```
then type python in the shell, you will notice that you get python from docker-compose. if you swap the two buildInputs, then you get myPythonEnv's python in PATH first. That's how I fixed it for now.
@Frostman 

**Expected behavior**
I would prefer docker-compose to not propagate python in PATH.. Is that necessary ?

**Comment by kisik21** [comment]
docker-compose is built using `buildPythonApplication`, I'd expect that it would create a wrapper script launching the app with the right PATH so it wouldn't leak Python.

The problem isn't reproducible if I take the docker-compose out of latest unstable (at moment of writing: flake `github:NixOS/nixpkgs-channels/84d74ae9c9cbed73274b8e4e00be14688ffc93fe`), but it is reproducible if I take python out of latest Nixpkgs and docker-compose out of the tarball provided, which leads me to think that the commit mentioned in the URL of the tarball needs to be investigated.

**Comment by FRidh** [comment]
Python is always propagated by products of `buildPython*`. While undesirable in situations like these, it is not really possible to get rid of.

Note `mkShell` is a hack, that in the end is just `stdenv.mkDerivation` and is thus for build-time, not run-time. The reason it works is because it runs hooks, which is also the reason you encounter this issue.

In a way, it would be nice if you could say "now I need a run-time shell, don't use propagation". That would work, however, it likely means your `$PATH` is not constructed either. What we need is to become better at distinguishing between run-time and build-time hooks, and have Nix support that (with the new `nix shell` and `nix develop`).

**Comment by kisik21** [comment]
Maybe using something like `symlinkJoin` or whatever is used to construct `system-path` in NixOS with `nix shell` will achieve the needed result?

**Comment by teto** [comment]
thank you all for the details, I will try bumping see if that changes the behavior (and report back). For my usage, it was enough to swap both in the buildInputs, to:
```  
buildInputs = with nixpkgs; [
    myPythonEnv
   old.docker-compose
    
  ];
```
so that myPythonEnv's appears in PATH first. closing.
