### ISSUE TITLE
Add CELPA to Emacs package lists

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#103047]
**Project description**

_Celpa is the Conao's Elpa_

**Metadata**

* homepage URL: https://celpa.conao3.com/
* source URL: https://github.com/conao3/celpa
* license: gpl3+ 
* platforms: emacs :)

**Comment by adisbladis** [comment]
This should be easy enough. I wonder where in the priority order of the merged sets it should go though?

**Comment by AndersonTorres** [comment]
I would put it first. It has a smaller number of packages and they are newer than the others.

**Comment by akirak** [comment]
> I would put it first. It has a smaller number of packages and they are newer than the others.

 I am personally against this. It [overrides the recipe of yasnippet](https://github.com/conao3/celpa/blob/master/recipes/yasnippet) to use conao3's fork, which means it is not 100% compliant with the current ELPA/MELPA/etc. ecosystem. Yasnippet seems to be inactive now, but it has received one bugfix commit which is unavailable in his fork yet. This can happen in other packages too.

Because he is creating another Emacs world, how about creating another [overlay](https://github.com/nix-community/emacs-overlay) for CELPA?

**Comment by AndersonTorres** [comment]
@akirak fine to me.

**Comment by adisbladis** [comment]
Because of the incompatibilities with CELPA I'm going to close this.
