### ISSUE TITLE
beets: Include patch or change replaygain backend

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#10376]
In the current version, the replaygain backend used by nixpkgs has a bug that crashes beets.

A fix is available [here](https://github.com/sampsyo/beets/commit/225ba282cdcf57b62a4659857f16e319118c961d) and needs to be cherry-picked.
Bear in mind that this patch doesn’t handle the error, it only skips the files where it happens.

Alternatively it might make sense to switch to a different backend, there are others available, documented in https://beets.readthedocs.org/en/latest/plugins/replaygain.html 

cc @aszlig @pjones @domenkozar

**Comment by pjones** [comment]
Sounds like we should switch to GStreamer.

**Comment by Profpatsch** [comment]
@aszlig friendly reminder that https://github.com/sampsyo/beets/commit/225ba282cdcf57b62a4659857f16e319118c961d is not yet fixed, the error is only caught and logged.
We should either fix the error upstream or switch to a different backend.

**Comment by aszlig** [comment]
Mhm, we have `bs1770gain` since 7ab8dde5113fb25d3bd3da2f8feb71098b1f8b6b, so it might make sense to switch to it as the default backend instead. Especially since the upstream project maintainer [tends to move away from `audiotools`](https://github.com/sampsyo/beets/issues/1342#issuecomment-86807500).
