### ISSUE TITLE
Firefox won't let me install add-ons. Now what?

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#105987]
I tried to install an ad blocker extension into my Firefox browser (which comes from a current version of `nixos-unstable`), but the browser won't let me. It says that installing add-ons has been disabled by my admin and that I'm supposed to use Nix to install them.

Now, how do I install a Firefox add-on with Nix?

**Comment by doronbehar** [comment]
Me TOO... Not only that, the worse news is that even after you'll fix it by merging https://github.com/NixOS/nixpkgs/pull/105796 to you local nixpkgs, you'll see all of your extensions' settings got removed.

**Comment by doronbehar** [comment]
Let's keep this open for other users as well.

**Comment by zyansheep** [comment]
Same... and it synced to my other computer as well so now everything is gone :sob:

**Comment by hexop** [comment]
As a temporary workaround, you can install firefox-bin, I found a relevant post in this [thread](https://discourse.nixos.org/t/reenabling-firefox-plugins-in-nixos-unstable/10348).
I hope that we'll get soon get proper documentation on how to declare add-ons. This breaking change has really affected the workflow of many users, including me. 
On the bright side, I've improved my add-ons settings backup practices.

**Comment by alexameen** [comment]
This fully sucks. Not only were my extensions removed but they were removed from my account, so they also got deleted on my non-NixOS machines... Not cool.

**Comment by sumnerevans** [comment]
Yep, and a lot of the data that I had in each plugin was removed. Luckily I was able to boot up a different device and get it off the network before the deletions got synced and I exported some stuff from there, but I didn't get everything.

Definitely not cool. Is there a way that this can be prevented in the future?

**Comment by doronbehar** [comment]
> Definitely not cool. Is there a way that this can be prevented in the future?

All rages are justified, but human make mistakes..

**Comment by peti** [comment]
Well, prohibiting Nix users from installing any and all add-ons with Firefox is a pretty authoritarian move. That's a controversial decision, to put it mildly, even it hadn't resulted in everyone's installation being destroyed as an unintended consequence. I'm kinda surprised that this change got past the reviewers at all.

**Comment by doronbehar** [comment]
> Well, prohibiting Nix users from installing any and all add-ons with Firefox is a pretty authoritarian move. That's a controversial decision, to put it mildly, even if it hadn't resulted in everyone's installation being destroyed as an unintended consequence. I'm kinda surprised that this change got past the reviewers at all.

I agree. I also admit I misinterpreted the history of PRs, comments & reviews in https://github.com/NixOS/nixpkgs/pull/91724. It goes like this:

1. https://github.com/NixOS/nixpkgs/pull/91724#event-4066069639 was merged.
2. On the same day [@taku0 commented](https://github.com/NixOS/nixpkgs/pull/91724#issuecomment-738017791) that it's problematic that existing extensions will be removed for ever for users not aware of this change.
3. 2 Days ago the fix was merged: https://github.com/NixOS/nixpkgs/pull/105796#event-4073604843

And we have fallen right in the middle :/. Tough luck I guess for us, but indeed there is a lesson here for us.

**Comment by 7c6f434c** [comment]
>Well, prohibiting Nix users from installing any and all add-ons with Firefox is a pretty authoritarian move.

Well, forcing the installation of add-ons to go through Nix-level cofiguration is not, and while still controversial, way less out of character for what is oftten done in Nixpkgs.

(I am not saying that mispredicting the interactions with existing installations is a desirable outcome)

**Comment by sumnerevans** [comment]
> All rages are justified, but human make mistakes..

I fully understand this, and I don't want to point any fingers, I'm just wondering if there is something in the process that can be improved from this experience.

I understand that this is one of the perils with running the `unstable` channel, but it still just feels like something can be learned and improvements can be made. (Sorry if this is out of place to suggest, still new

**Comment by doronbehar** [comment]
> Well, forcing the installation of add-ons to go through Nix-level configuration is not, and while still controversial, way less out of character for what is often done in Nixpkgs.

Personally, when I use a piece of software on my machine, I evaluate whether I need Nix to configure it or not, by considering how many paths to the Nix store does the configuration need. That's why (I might be a minority in the community) most of my configs (Vim's configs included) are not managed via home-manager and such because they don't require anything that can't leave outside the store forever - no compiled files are needed.

The Vim and Neovim wrappers don't do the equivalent of deleting your existing configs. People here are upset I think because their browser configuration is "imperative" and they never felt like Nix configuration level is what's missing to them in this space - probably because it doesn't involve compiling files (only putting a few javascript files in the right place). Also, it updates by itself thanks to Mozilla's infrastructure - probably better and faster then we will ever succeed, considering the delay of channel updating etc.

I'm not saying that the whole change is not useful for some users, but for most of us it's not.

**Comment by 7c6f434c** [comment]
>> Well, forcing the installation of add-ons to go through Nix-level configuration is not, and while still controversial, way less out of character for what is often done in Nixpkgs.
>I'm not saying that the whole change is not useful for some users, but for most of us it's not.

I with you agree about the preferable choice of defaults, I just objected to an overstatement.

**Comment by NorfairKing** [comment]
Could it be possible to deal with addons in a similar way as we deal with system user accounts: with a `declarativeAddons = true;` to mean "only allow addons defined in Nix".

**Comment by 7c6f434c** [comment]
@NorfairKing I am not sure there is a clean solution for adding extensions while also allowing further manual additions (which is the default mode for use management).

**Comment by NorfairKing** [comment]
@7c6f434c I'm not familiar with the details, but if it's an XOR situation then at least let the user choose

**Comment by 7c6f434c** [comment]
>@7c6f434c I'm not familiar with the details, but if it's an XOR situation then at least let the user choose.

This how the version in master is believed to work now after some fixes, with choice being driven by empty/non-empty extension list, and with an option to enforce the lack of extensions in the former case.

**Comment by ehmry** [comment]
The least disruptive fix for aarch64 unstable NixOS is to build from bf5da4bbd4af4ad5750091897d59bbf6b65c8f31.

**Comment by d4g** [comment]
To be honest, the whole process is just plain wrong and #1436 should be reverted.

Extensions are managed in profiles. Each user can have multiple profiles for multiple purposes and those profiles have different add-ons that are required/wanted. Just because the regular user only uses firefox with one profile, does not mean that this is the default for everyone.

So this whole change was breaking, broke working configurations, caused users to use settings on machines that are not managed by nixos. I think this is what a lessons learned should be for and in the future the approvers of a PR for a complex application like firefox should really consider the impact of those changes before pushing them.

**Comment by taku0** [comment]
Users can install multiple firefox with different extensions. That is how Nix works.

**Comment by alexameen** [comment]
I agree with @d4g I think this should be reverted. The disruptions I experienced were annoying, but ultimately that's on me for using `nixos-unstable`; having said that we definitely should not subject other users to this, especially on such a popular package.

**Comment by doronbehar** [comment]
Closing as there's nothing to do here. Current nixos-unstable has a firefox that allows you to install extensions unless specified otherwise.
