### ISSUE TITLE
Nix-shell start bash

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#10619]
```nix
users.defaultUserShell = "/run/current-system/sw/bin/zsh";
programs.zsh.enable = true;
```
But `nix-shell` start `bash`. Why?

**Comment by puffnfresh** [comment]
I think this issue belongs in the https://github.com/NixOS/nix repository.

nix-shell is coded to start bash or whatever you set in `NIX_BUILD_SHELL`. You can't use `NIX_BUILD_SHELL` to set to zsh because nix-shell uses flags which zsh doesn't support and also creates an rcfile which zsh won't understand.

I would like to work on a nix-shell which works with zsh.

**Comment by gebner** [comment]
I have a PR for that at nixos/nix#345.  The main thing that doesn't work is running `unpackPhase`, `configurePhase`, etc., from zsh as those are bash functions and not easily portable.  However if you just want to `nix-shell -p some-package`, then it works great.

**Comment by Pitometsu** [comment]
@gebner ok, functions like `unpackPhase` can be wrapped into bash invocations. ZSH awesome because of interactive in first case.

**Comment by vcunat** [comment]
Closing, as it's in incorrect repo and we have a PR anyway...
