### ISSUE TITLE
reach back to upstream on .pc file breakage from systemd/systemd#17009

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#106351]
We merged https://github.com/NixOS/nixpkgs/pull/106044 effectively reverting systemd/systemd#17009.

We should reach back to upstream that this is indeed a problem.

**Comment by flokli** [comment]
Breadcrumbs on why keeping `${prefix}` in `.pc` files, and paths relative starting from here: https://github.com/NixOS/nixpkgs/pull/105850#issuecomment-739323829

**Comment by jtojnar** [comment]
Opened https://github.com/systemd/systemd/issues/18082.

**Comment by arianvp** [comment]
The specific issue in question is caused by: https://gitlab.gnome.org/GNOME/tracker/-/blob/master/meson.build#L217-218

It sets `prefix` but because `systemd.pc` doesn't interpolate `prefix` anymore not much interesting happens and it tries to install the unit files in `/usr/lib/systemd` as a result.

But to be honest the `systemd.pc` file was lying before as the source-code of `systemd` hardcodes `/usr/lib` by default anyway. And things mostly worked by luck. 

In the old scenario:

`prefix=$out`
`

This caused the systemd unit to be installed in `$out/lib/systemd/system/blah.service`

This then gets added to `systemd.packages = [ pkgs.blah ]` in the NixOS module system

This then gets exposed as `/etc/systemd/system/blah.service` on the actual NixOS system.

and systemd happens to look both in in `/usr/lib/systemd`  and `/etc/systemd` (both hardcoded) and thus everything works kind of by accident.

All of this is a bit of a hack as systemd wasn't looking in `$prefix` to begin with but in `/usr/lib` (and it can't; as it's different per package). it was looking in `/etc/systemd` instead, which we synthesize on the spot.


Question now is; how many of the upstream packages that make use of `system.packages` actually utilise the `systemd.pc` file? Or do they just install in `$out/lib/systemd/system` ?

We could configure our systemd package to not generate the `systemd.pc` file at all by setting `-Dpkgconfigdatadir=no` and then we can deal with the fallout   as the `systemd.pc` file is kind of nonsensical anyway.

(These: https://github.com/NixOS/nixpkgs/search?q=systemd.packages+%3D)

**Comment by arianvp** [comment]
Given the prevelance of `--with-systemdsystemunitdir` through nixpkgs being manually set all over the place;

https://github.com/NixOS/nixpkgs/search?q=systemdsystemunitdir

and given  https://gitlab.gnome.org/GNOME/tracker/-/commit/ac3eeb8b730eb6959240c4c236385152bb04143c was only introduced very recently;

I wonder If the `systemd.pc` discovery mechanism actually worked before. If it did; why are so many packages manually overriding this option?

Note that the `tracker` library that broke in https://github.com/NixOS/nixpkgs/pull/105850  only started shipping `systemd` unitdir support in `3.0.0` (https://gitlab.gnome.org/GNOME/tracker/-/commit/ac3eeb8b730eb6959240c4c236385152bb04143c) and we only merged that change rather recently (https://github.com/NixOS/nixpkgs/commit/d8d4cdc496777f91263a517fd832abb300e82ce4). So maybe it was more coincidental that things started breaking instead of things actually being broken.

If we  add a `--with-systemdsystemunitdir` call to the `tracker` derivation instead it would build again.

Would there be a good way to find out how many packages in nixpkgs actually depend on `systemd.pc` instead of setting `systemdsystemunitdir` explicitly?

**Comment by jtojnar** [comment]
It worked just fine before. `pkg-config` is explicitly designed with this use case and Meson also supports it. See also “Using variables from pkg-config files” section in https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/ for more information about this practice.

In my experience when working on pkg-config files with upstreams and reading various issues and discussions on GNOME and Freedesktop projects, there are two main reasons why options are introduced:

- wanting to allow builds without the pkg-config file installed, especially when the project only depends on the package 
- less often, not being aware of the pkg-config’s `--define-variable` flag

**Comment by jtojnar** [comment]
Opened https://github.com/systemd/systemd/pull/18118 after [upstream discussion](https://github.com/systemd/systemd/issues/18082#issuecomment-753413564).

**Comment by arianvp** [comment]
I see... the usecase of "let's not pull in Systemd just for a pkg-configs file" didn't cross my mind. And it makes sense as you might want to avoid rebuild in those cases. Didn't think of that.

Thanks for the clarification. It's clear to me now.

**Comment by flokli** [comment]
I poked upstream for a backport in https://github.com/systemd/systemd/pull/18118#issuecomment-775107941, now tracked in https://github.com/systemd/systemd-stable/issues/88. Our patch still is necessary for [247.3](https://github.com/NixOS/nixpkgs/pull/111786)
