### ISSUE TITLE
ppx_deriving incompatible with dune 2

### ISSUE THREAD

**Issue by joprice** [NixOS/nixpkgs#106907]
**Describe the bug**

When using ppx_deriving with dune 2, builds fail with errors like `Error: Ppx dependency on a non-ppx library "ppx_deriving.std"`. This is due to a missing line in the META file of ppx_deriving, `library_kind = "ppx_deriver"`, which is only generated if the package is built with dune 2. This is similar to an issue identified outside the scope of nix https://github.com/ocaml/dune/issues/3057#issuecomment-744044831.

**To Reproduce**
1. Clone https://github.com/joprice/ocaml-scratch
2. Run `nix-shell --run "dune build bin/main.exe"`
3. Witness an error as below

```
File "lib/dune", line 4, characters 19-35:
4 |   (preprocess (pps ppx_deriving.std ppx_sexp_conv))
                       ^^^^^^^^^^^^^^^^
Error: Ppx dependency on a non-ppx library "ppx_deriving.std". If
"ppx_deriving.std" is in fact a ppx rewriter library, it should have (kind
ppx_rewriter) in its dune file.
Done: 0/0 (jobs: 0)%
```

**Expected behavior**
The build should complete without errors

**Notify maintainers**
@maurer 

**Metadata**

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.1.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.9`
 - channels(josephprice): `"home-manager, nixpkgs-21.03pre257989.f1f9a55fb4b"`
 - nixpkgs: `/Users/josephprice/.nix-defexpr/channels/nixpkgs
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by sternenseemann** [comment]
This is because our `ppx_deriving` is too old. We currently have 4.5, but the new dune meta information seems to only be properly generated for 5.0 and above.

I've tested your project with an upgraded version of `ppx_deriving` and dune 2 and it works just fine.

I'll try and see whether I can make my local branch into an update, but I'm a bit scared to see what it all breaks, since the whole development in the ppx department recently tends to just break everything (we are having trouble with updating ocaml-migrate-parsetree and ppxlib).

**Comment by sternenseemann** [comment]
If you want to try it out yourself: [This is my branch](https://github.com/sternenseemann/nixpkgs/tree/ppx_deriving-5.2). It breaks a lot of other stuff currently, however.

**Comment by sternenseemann** [comment]
Feel free to check out and test #108137, it should resolve your issue!

**Comment by joprice** [comment]
Tried it out and it's working! Thank you!
