### ISSUE TITLE
Error on executing binary file: No such file or directory

### ISSUE THREAD

**Issue by phenax** [NixOS/nixpkgs#107375]
**Describe the bug**
I am unable to execute binary files directly. It throws a "No such file or directory" error even though the file does exist. I'd like to know if Im missing something.

```
./node_modules/gentype/gentype.exe: No such file or directory
```

**To Reproduce**
Steps to reproduce the behavior with `gentype` npm package (in a preferably empty directory):
1. Install gentype - `npm install gentype`
2. The file exists - `ls -l ./node_modules/gentype/gentype.exe`
3. Execute to get the error - `./node_modules/gentype/gentype.exe`

**Expected behavior**
Expected the binary to execute without issues.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257780.e9158eca70a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"home-manager, nixos-21.03pre257780.e9158eca70a"`
 - channels(imsohexy): `"home-manager, nixos-21.03pre257780.e9158eca70a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sternenseemann** [comment]
This is because NixOS avoids global state and therefore doesn't install the binary interpreter `ld-linux.so` and generally libraries to the default locations as on other Linux distribution. This means that dynamically linked binaries built elsewhere won't run out of the box, however: The behavior you are experiencing is expected and not a bug.

You can use [patchelf](https://github.com/NixOS/patchelf) to get foreign binaries to work on NixOS.

You can show the interpreter of the binary like this:

```
nix-shell -p patchelf --run "patchelf --print-interpreter ./node_modules/gentype/gentype.exe
```

For binaries properly built and packaged for NixOS, you'll see that the correct interpreter version from `/nix/store` is used:

```
$ nix-shell -p patchelf --run "patchelf --print-interpreter \$(which mkdir)"
/nix/store/9l06v7fc38c1x3r2iydl15ksgz0ysb82-glibc-2.32/lib/ld-linux-x86-64.so.2
```

Note that using `--set-interpreter` might not do the trick altogether. Depending on what you are trying to achieve it's probably best to write a nix expression building and [fixing up the binary](https://nixos.org/manual/nixpkgs/stable/#ssec-fixup-phase) you have, since its `rpath` will probably also need to be adjusted to use libraries from `/nix/store/`.

Unfortunately I don't know that much about how to best package node.js packages with distributed binaries and `nodePackages` doesn't contain `gentype`, but you could maybe achieve your goal with the help of [`node2nix`](https://github.com/svanderburg/node2nix).

**Comment by quinn-dougherty** [comment]
I work with the information in this issue a lot! It was extremely helpful. See my [solution for setting up rescript, ppx, and gentype](https://github.com/quantified-uncertainty/squiggle/blob/develop/nixos.sh) 

One thing I can't do in a particular [flake](https://github.com/quinn-dougherty/squiggle/blob/develop/flake.nix) is when I get `> patchelf: missing ELF header`. Any idea what's going on here? There isn't much when you google.
