### ISSUE TITLE
Use different repo for ankisyncd

### ISSUE THREAD

**Issue by abvbv** [NixOS/nixpkgs#107526]
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Currently ankisyncd [package](https://github.com/NixOS/nixpkgs/blob/e9158eca70ae59e73fae23be5d13d3fa0cfc78b4/pkgs/servers/ankisyncd/default.nix) uses [tsudoko/anki-sync-server](https://github.com/tsudoko/anki-sync-server) repository (latest version 2.1.0), but there's another more active repo [ankicommunity/anki-sync-server](https://github.com/ankicommunity/anki-sync-server). It doesn't have a tagged version, so I'm not sure what to do now.

There's [an issue](https://github.com/ankicommunity/anki-sync-server/issues/42) addressing the version problem. @VikashKothary or @AntonOfTheWoods plan to release version 2.2.0.

`nix search` name: ankisyncd
current version: https://github.com/tsudoko/anki-sync-server/tree/2.1.0
desired version: https://github.com/ankicommunity/anki-sync-server

maintainers: @matt-snider

**Comment by matt-snider** [comment]
For reference, the maintainer goes over the history of the repo and its connection to the original from dsnopek, and the fork from tsudoku in [this comment](https://github.com/ankicommunity/anki-sync-server/issues/33#issuecomment-711421178).

The lack of a tag isn't a deal breaker, since we can use a specific commit hash instead, but it does make it more difficult to know when a particular branch is considered to be in a working state. Do you know if there is process here? (e.g. master should always be working). If they are planning to start tagging releases, then it might make sense to just wait for that.

The only other issue I see is testing to make sure everything still works when switching to the new repository. Someone would have to test it out a bit.

**Comment by VikashKothary** [comment]
Hi @abvbv and @matt-snider,

Thanks for notifying me of this issue. I can help with that. 

I've released 2.2.0 which is the latest from the tsudoko's branch. There's is also a version 2.3.0 in process. See: https://github.com/ankicommunity/anki-sync-server/pull/65. 

I hope that should resolve your blocker.

**Comment by bqv** [comment]
Been using the up-to-date version myself for a long time.

https://github.com/bqv/nixrc/blob/live/overlays/ankisyncd.nix
https://github.com/bqv/nixrc/blob/live/flake.nix#L82

**Comment by matt-snider** [comment]
@VikashKothary @bqv @abvbv Thank you for your input and bringing this up. I opened #111755. For now it's a draft since I just switched over myself. I'd like to wait a bit and see if I run into any issues.

**Comment by orbekk** [comment]
This appears to be resolved by Matt's pull patch.
