### ISSUE TITLE
Package request: GameConqueror

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#107650]
**Project description**
GameConqueror is the graphical (GTK) frontend for scanmem, a memory scanner.
Scanmem is already packaged for NixOS.

**Metadata**
* homepage URL: https://github.com/scanmem/scanmem
* source URL: https://github.com/scanmem/scanmem
* license: GPL3
* platforms: linux

**Comment by mehlon** [comment]
Here is Arch Linux's package for GameConqueror: https://archlinux.org/packages/community/x86_64/gameconqueror/

**Comment by neonfuz** [comment]
I'll give this a try

**Comment by tengkuizdihar** [comment]
Any news for this one? Scanmem fortunately already in the library, don't know about this one.

**Comment by tengkuizdihar** [comment]
@neonfuz sorry for tagging, but any news on this package? No pressure, I also want to try it, might be nice if you have a base that I could work on

**Comment by jgonyea** [comment]
Whenever I try to build gameconquerer, I keep getting:

```
Traceback (most recent call last):
  File "/nix/store/64ffx4937mw9506x7myfa534ixdy11bd-scanmem-0.17/share/gameconqueror/GameConqueror.py", line 34, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

I'm very new to nixpkgs, so any pointers to help make this work would be welcome.

**Comment by davidak** [comment]
@jgonyea the error means a dependency is missing.

When searching the error message in nixpkgs, i found this commit: https://github.com/NixOS/nixpkgs/commit/88f749545c8a3299bdf6f856285c32058063f6cf

Maybe you should also use `buildPythonApplication`.

The use of `python3` and `python310Packages` might lead to mixing different python versions and cause issue.

**Comment by jgonyea** [comment]
I found how to wrap the python package in the `buildInputs` stage, but now I'm running into gtk issues:

```
Traceback (most recent call last):
  File "/nix/store/9gd22ly8hyq7z7zirycgyrc73frsn48n-gameconqueror-0.17/share/gameconqueror/GameConqueror.py", line 35, in <module>
    gi.require_version('Gtk', '3.0')
  File "/nix/store/kwsw90jz5adz7swvr58k8gi9pkgz6v4l-python3-3.10.9-env/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

I have `gtk` in the `buildInputs` stage, as well as `wrapGAppsHook` in the`nativeBuildInputs`, but nothing else I try seems to make it get past the error above when I attempt to run the application.  My latest attempt is at the link above

**Comment by tengkuizdihar** [comment]
@jgonyea based on this PR https://github.com/NixOS/nixpkgs/pull/189505/files , I think you need to add `gobject-introspection` to `nativeBuildInputs`.

**Comment by Melechtna** [comment]
Any progress on this?

**Comment by Melechtna** [comment]
I've dug into this, and the problem seems to stem from 2 things, as I can get it to compile, but not fully run. The first problem is that the program seems to still be running on Python2, which NixOS already ree's at when you try to install it. The second problem is that, if you use a newer version of python, it complains about name spaces, which is a common issue when pygobject is running on a version of python that is "too new".

The solutions seem to be to either, patch out the check for gtk3, but patch files are voodoo magic to me, I do not understand how they work, and this seems like a terrible idea. Or to make a pipx venv within the nix profile, and just add everything needed for python 2.7, and it should theoretically work just fine from there, but I'm unsure if the pyvenv would create issues with sandboxing. Regardless, attached is the modifications I've made to the existing scanmem Nix Package, to get gameconqueror to compile and install.

It does install and compile it, but the above issues are where the roadblock comes in.
[default.nix.zip](https://github.com/NixOS/nixpkgs/files/12065628/default.nix.zip)

You can install it and see the result yourself using
nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
In a terminal, but make sure the terminal is in the same directory when you extract it.

**Comment by Melechtna** [comment]
https://github.com/NixOS/nixpkgs/pull/244030

**Comment by melvyn2** [comment]
As the PR is merged, GC works as expected in unstable. Unless someone wants to request a backport, this issue can probably be closed.
