### ISSUE TITLE
Feature Request: easily build flatpaks and/or appimages

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#108103]
## Feature description
We can use dockerTools.buildImage to easily take an existing package and turn it into a docker app. Can we make something similar for Flatpak or AppImage?

The use-case is: I'm making an app, and building it with nix. Now, once I'm done I want to make it available on other linux distros (without having to install nix). Wouldn't it be nice to just wrap it in flatpakTools.buildFlatpak call and have something portable?

## Questions

I'm happy to do some work on this, but I'm not very familiar with the systems involved, so I figured i would also post something here to ask: 
- Am I understanding how these systems work and what they're for correctly? 
- Would this be outside the scope of what nixpkgs does? 
- How much work would this end up being? dockerTools.buildImage seems quite complicated.

**Comment by andersk** [comment]
I don’t think this is realistic. Binaries built with Nix are full of hard-coded references to `/nix/store` paths for the dynamic loader, libraries, and any other data the package needs. Unlike Docker containers, which have their own filesystem, a Flatpak or AppImage can’t (and/or shouldn’t) just put stuff in `/nix/store`.

Depending on the application, you may be able to link everything statically, and then you don’t need further help from Nix to package it in whatever format you want. Otherwise, you’ll probably need to set up a more traditional build using the upstream Flatpak or AppImage toolchain.

**Comment by jtojnar** [comment]
Flatpak has a notion of runtime (mounted to `/usr` inside the sandbox) and an app (mounted to `/app`). Each app has one runtime associated. So you would have to decide if you want to build your runtime or choose some tiny one and stuff everything into the app bundle.

Since you can only use `/usr` or `/app` prefix, you would also need to modify the store paths. For example, in Flatpak tests, we build the test runtime by replacing `/nix/store` with `/usr/store`: https://github.com/NixOS/nixpkgs/blob/5bcc26338d42c8bc53cf9ed4bc2ae7c28ab66f69/pkgs/development/libraries/flatpak/fix-test-paths.patch

https://github.com/flatpak/flatpak-builder might be also interesting.

**Comment by danieldk** [comment]
[nix-bundle](https://github.com/matthewbauer/nix-bundle) supports building AppImage executables. I have used this for distributing two applications and it works fine so far.

**Comment by Radvendii** [comment]
Thanks so much y'all. I'm looking into nix-bundle right now, which seems to be exactly what I'm looking for. It's also accessible directly using nix via something like:
```
(import "${nix-bundle}/share/nix-bundle { nixpkgs = import <nixpkgs> { }; }).nix-bootstrap {
  target = import ./default.nix;
  run = "/bin/command";
}
```

It's not currently working for me, but in theory this is what I wanted.

I still think it'd be worth integrating more closely with nix (importing a nix file from a derivation feels kind of janky to me), but I'm fine with closing this.

**Comment by Radvendii** [comment]
nix-bundle works for this, and flakes makes it quite convenient for my purposes. Closing.
