### ISSUE TITLE
Shiori systemd service fails - `cannot set up thread-local storage: cannot set %fs base address for thread-local storage`

### ISSUE THREAD

**Issue by aswan89** [NixOS/nixpkgs#108146]
## Issue description

Systemd unit `shiori.service` fails with error  `cannot set up thread-local storage: cannot set %fs base address for thread-local storage` after `nixos-rebuild switch` when `services.shiori.enable` is set to true.

### Steps to reproduce

1. Edit `configuration.nix` to include `services.shiori.enable = true;`
2. `nixos-rebuild switch`
3. `journalctl -u shiori`

## Technical details

The strange part is that I can add `pkgs.shiori` to `environment.systemPackages` and run `shiori serve` manually without encountering the error which makes me suspect something about the service configuration.

Mentioning @minijackson since they contributed the shiori module.

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03pre260232.733e537a8ad (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre260232.733e537a8ad"`
 - channels(andrew): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by minijackson** [comment]
I managed to reprodruce it using the nixos test, and bisected it. It seems that commit 22148780509c003bf5288bba093051a50e738ce9 broke the shiori service.

The solution seems simple: removing the "~@process" and "~@ipc" system call filters seems to make it work again.

I am not sure why it broke, since doing `systemd-analyze syscall-filter "@ipc" "@process"` doesn't seem to have any meaningful differences between master, and what is on my server.

Reading the [libseccomp changelog](https://github.com/seccomp/libseccomp/releases/tag/v2.5.1) also makes me think that there shouldn't be anything that is affecting us...

But anyway, it seems that we have a fix, so I'll make a PR.
