### ISSUE TITLE
KDE will stuck when logging in again after using Firefox

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#108234]
**Describe the bug**
KDE will stuck when logging in after using Firefox

Restarting the `display-manager` service does not workaround the issue.

Additionally, powering down through a terminal will stuck at "stopping X11 server".

**To Reproduce**
1. Install KDE (plasma5 and sddm) and Firefox
2. Reboot
3. Log in
4. Open Firefox
5. Close Firefox
5. Log out
6. Try to log in again

**Expected behavior**

KDE should start normally

**Notify maintainers**

@ttuegel @nyanloutre 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 21.03pre260232.733e537a8ad (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(eduardosm): `""`
 - channels(root): `"nixos-21.03pre260232.733e537a8ad"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by taku0** [comment]
`rm -rf ~/.cache/fontconfig/` may fix this. I don't know why.

**Comment by ttuegel** [comment]
It would help if I could see the log of a stuck session (`journalctl -t xsession`).

**Comment by geier1993** [comment]
I'm experiencing the same issues for firefox with KDE (and Krohnkite extension).

Removing `~/.cache/fontconfig/` did not help.

`journalctl -t xsession -r` is not very helpful - the following lines have been logged after having firefox opened for a while and then trying to use it (i.e. scrolling on a page - then it stucks):

`Feb 18 14:54:55 jimmy xsession[5708]: [02/18/21, 14:54:55:068] info: [FOCUS-EVENT] Client window blurred
Feb 18 14:54:55 jimmy xsession[2251]: qml: loadLayout MonocleLayout [TileLayout,MonocleLayout]
Feb 18 14:54:55 jimmy xsession[2251]: qml: loadLayout MonocleLayout [TileLayout,MonocleLayout]
Feb 18 14:54:54 jimmy xsession[5708]: [02/18/21, 14:54:54:793] info: [CHECK-UNREADS] (T4SK62KHP) Not marking C4T9PHKPC because last_read >= latest && channel is read
Feb 18 14:54:54 jimmy xsession[5708]: [02/18/21, 14:54:54:791] info: [CHECK-UNREADS] (T4SK62KHP) Checking unreads after window became focused
Feb 18 14:54:54 jimmy xsession[5708]: [02/18/21, 14:54:54:655] info: [FOCUS-EVENT] Client window focused
Feb 18 14:54:54 jimmy xsession[2251]: qml: loadLayout MonocleLayout [TileLayout,MonocleLayout]
Feb 18 14:54:54 jimmy xsession[2251]: qml: loadLayout MonocleLayout [TileLayout,MonocleLayout]
Feb 18 14:54:53 jimmy xsession[2251]: qml: loadLayout MonocleLayout [TileLayout,MonocleLayout]
Feb 18 14:54:49 jimmy xsession[2251]: qml: loadLayout MonocleLayout [TileLayout,MonocleLayout]
Feb 18 14:54:31 jimmy xsession[2279]: file:///nix/store/1qzy6laf389wqq6vhpv7238yjwg7g85y-plasma-pa-5.20.5/share/kpackage/kcms/kcm_pulseaudio/contents/ui/StreamListItem.qml:3>
`

The "TileLayout.MonoclLayout" messages origin from the Krohnkite extension

The lines 
`
Feb 18 14:54:54 jimmy xsession[5708]: [02/18/21, 14:54:54:793] info: [CHECK-UNREADS] (T4SK62KHP) Not marking C4T9PHKPC because last_read >= latest && channel is read
Feb 18 14:54:54 jimmy xsession[5708]: [02/18/21, 14:54:54:791] info: [CHECK-UNREADS] (T4SK62KHP) Checking unreads after window became focused
`
occur very often .... but not only in relation to firefox.

Moreover somewhere in the log, GTK related messages like 
`
Feb 18 14:57:39 jimmy xsession[9587]: Gtk-Message: 14:57:39.142: Failed to load module "appmenu-gtk-module"
`
occur.

**Comment by geier1993** [comment]
I don't know if i am experiencing the same problem as @eduardosm, but similar issues occur for Thunderbird and some other applications using GTK
