### ISSUE TITLE
gitAndTools.git-annex-metadata-gui fails to build on latest master

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#108588]
**Describe the bug**

gitAndTools.git-annex-metadata-gui fails to build on latest master.

[Build log](https://github.com/NixOS/nixpkgs/files/5776346/build-log.txt)

**Notify maintainers**

@dotlambda

**Comment by dotlambda** [comment]
It seems like git-annex-metadata-gui is incompatible with the JSON interface of the most recent version of git-annex. You should file an upstream issue and then we could mark the package as broken in Nixpkgs. I doubt this will be fixed since @alpernebbi is not working on git-annex-metadata-gui anymore.

**Comment by alpernebbi** [comment]
Thanks for mentioning me, I wasn't aware. Looks like the tests broke again because they check git-annex behaviour too strictly, but things actually still work. Should be fixed with https://github.com/alpernebbi/git-annex-adapter/commit/6c210d828e8a57b12c716339ad1bf15c31cd4a55 (pushed to master).

**Comment by dotlambda** [comment]
Thanks a lot @alpernebbi!
