### ISSUE TITLE
webbrowser-29.0.0rc1 fails to build on master

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#108615]
**Describe the bug**
webbrowser-29.0.0rc1 fails to build on master.

[Build log](https://github.com/NixOS/nixpkgs/files/5778268/build-log.txt)

**Notify maintainers**

@TheBrainScrambler @MetaDark

**Comment by TheBrainScrambler** [comment]
Hello, I don't know why you mentioned the other person, since I'm the only maintainer, but know that I do not maintain this derivation anymore.
And the version is outdated, there are now release versions out (https://git.nuegia.net/webbrowser.git/ version 29.1.1).

Someone should take maintainership and update it, or delete it.

**Comment by MetaDark** [comment]
I submitted a change that removes ccache as a build dependency, but I'm not a maintainer.

**Comment by thiagokokada** [comment]
@TheBrainScrambler @eduardosm Maybe it would be better to simply remove this derivation? Seems like there is some alternatives if you want an "old school Firefox" (like Pale Moon) that are better maintained. And it seems there isn't much interest in maintaining it.

**Comment by flokli** [comment]
marked as broken in https://github.com/NixOS/nixpkgs/pull/108700, let's close this.
