### ISSUE TITLE
ugly font rendering in GTK apps when using xdg-desktop-portal

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#108855]
**Describe the bug**
After enabling xdg-desktop-portal, GTK apps don't have font anti-aliasing and it looks quite unbearable.

**To Reproduce**
1. build a vm with the following config:
```
{ pkgs, ... }:

{
  users.users.pbb = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
  };
  security.sudo.wheelNeedsPassword = false;
  services.getty.autologinUser = "pbb";
  programs.sway.enable = true;
  systemd.user.services.xdg-desktop-portal.wantedBy = [ "default.target" ];
  systemd.user.services.xdg-desktop-portal-wlr.wantedBy = [ "default.target" ];
  xdg.portal.enable = true;
  xdg.portal.gtkUsePortal = true;
  xdg.portal.extraPortals = with pkgs; [ xdg-desktop-portal-wlr ];
  environment.variables.GTK_USE_PORTAL = "1";
  environment.variables.GDK_BACKEND = "wayland";
  environment.systemPackages = with pkgs; [
    termite
    dino
    wofi
  ];
  programs.bash.loginShellInit = ''
    if [ "$(tty)" == "/dev/tty1" ]; then
      exec sway
    fi
  '';
}
```

2. Start a GTK application (Super+Enter for terminal -> dino)
3. Observe the ugly font

**Expected behavior**
Fonts should look the same as before / good.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3250809/104092899-4c5a9700-5287-11eb-94e8-5cfb2450ea63.png)

**Additional context**
I need the xdg-desktop-portal for desktop recording.

**Notify maintainers**
@jtojnar  @minijackson @worldofpeace 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- xdg-desktop-portal
- gtk3
# a list of nixos modules affected by the problem
module:
- xdg.portal
```

**Comment by minijackson** [comment]
So, I had some time to do some testing / investigation, and it seems that when GTK is using portals, it will communicate with the portal to get some information like font settings ([source](https://github.com/flatpak/flatpak/issues/2861)). So, the quick fix I have right now is to modify your config in two places:

```nix
{ pkgs, config, ... }:

{
  # ----8<----

  # Added the GTK portal which seems to be always needed for GTK applications
  xdg.portal.extraPortals = with pkgs; [ xdg-desktop-portal-wlr xdg-desktop-portal-gtk ];

  # Make xdg-desktop-portal aware of each portals (should be upstreamed)
  systemd.user.services.xdg-desktop-portal.environment = {
    XDG_DESKTOP_PORTAL_DIR = config.environment.variables.XDG_DESKTOP_PORTAL_DIR;
  };

  #  ----8<----
}
```

Then, when sway starts, I often see xdg-desktop-portal-gtk failing, I think because it is started before the display is up. I just restart it with `systemctl --user restart xdg-desktop-portal-gtk.service` and with that Dino seems to have proper fonts :tada: 

I think we also should be looking at `systemctl --user import-environment` with variables like `XDG_CURRENT_DESKTOP`, and maybe link the portals to `graphical-session.target` to avoid starting them too early?

I don't think this issue is completely a NixOS issue, but I do agree that the amount of research to make to have a working sway desktop with portals is a bit overboard.

On an unrelated note, it seems that the wlroots portal crashes. It's true that I'm the official maintainer of the package, but I haven't had the time to switch my desktop to Pipewire, so I am not using it actively yet :confused:. I'll try to find where the crash comes from, but I definitely wouldn't mind a helping hand.

**Comment by petabyteboy** [comment]
Thanks for taking a look! I can confirm after adding the gtk portal, fiddling around and making sure all of the services are running, I get proper font rendering :tada: 
On my 'real' setup I use the home-manager sway module, so that takes care of the `systemctl --user import-environment` for me. I am now trying to figure out what `wantedBy` and `after` settings I need for each service to make it not crash.

**Comment by worldofpeace** [comment]
cc @NixOS/gnome

**Comment by Artturin** [comment]
Closing as this has been solved
