### ISSUE TITLE
vmware-horizon-client crashes upon attempting to connect

### ISSUE THREAD

**Issue by notgne2** [NixOS/nixpkgs#109312]
**Describe the bug**

`vmware-horizon-client` fails upon clicking connect, it will log something like this:

```
/nix/store/0ffypyakn16q8a79wii1bac37054mcwc-vmwareHorizonClientFiles/bin/vmware-view: line 88: 118107 Trace/breakpoint trap   (core dumped) "$binPath/bin/$binFile" "$@"
```

This appears to happen on any version of it, using the nixpkgs commit where it was first added still reproduces this issue when running on an up-to-date `nixos-unstable` system.

**To Reproduce**
1. `nix-shell -p vmware-horizon-client --run vmware-view`
2. Double-click "Add Server" or click "New Server"
3. Type anything into the name field
4. Click connect

**Expected behavior**

The client succesfully connects to the remote

**Additional context**

The issue may exist outside of the packaging, as it is reproducible using the nixpkgs commit where it was first added.

**Notify maintainers**
@buckley310 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 21.03.20210109.257cbbc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(notgne2): `"nixos-21.03pre255377.11b75530a1f"`
 - channels(root): `"home-manager, nixos-21.03pre255377.11b75530a1f, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - vmware-horizon-client
# a list of nixos modules affected by the problem
module:
```

**Comment by buckley310** [comment]
What kind of desktop environment are you running? I can debug it if i can recreate the issue. I did notice at one point that it doesn't launch under `sway` but i didn't pay it much mind since I've seen other things have issues there as well.

**Comment by notgne2** [comment]
I've tested it in X11 KDE Plasma5, and in plain i3 (also X)

**Comment by buckley310** [comment]
Can you give this a try on your system and let me know how it works for you?
https://github.com/buckley310/nixpkgs/tree/vmwareview
Vmware-view appears to be hardcoded to look for the proxy setting from GTK/GNOME when connecting and dies if it can't find it.

**Comment by notgne2** [comment]
@buckley310 that works! I think I trained myself to always ignore that error/warning so assumed it must be unrelated to the crash. Thanks.

**Comment by notgne2** [comment]
I've found another somewhat awkward issue though, it can't launch `chromium` for authentication. Both of the `LD_LIBRARY_PATH` overrides make it fail with an error like this:
```
/nix/store/sz86qyrx35xf1bidsfyvi5c5qvd822sc-chromium-unwrapped-87.0.4280.88/libexec/chromium/chromium: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```
or this:
```
/nix/store/sz86qyrx35xf1bidsfyvi5c5qvd822sc-chromium-unwrapped-87.0.4280.88/libexec/chromium/chromium: symbol lookup error: /nix/store/sz86qyrx35xf1bidsfyvi5c5qvd822sc-chromium-unwrapped-87.0.4280.88/libexec/chromium/chromium: undefined symbol: jpeg_crop_scanline, version LIBJPEG_6.2
```

**Comment by notgne2** [comment]
Firefox however seems to work fine, and `xdg-open 'https://example.com'` within the environment fails to launch `chromium` and goes for `firefox` next, but `vmware-view` does no such thing, making having Firefox installed as a backup browser not so helpful.

**Comment by buckley310** [comment]
Hmmm, yeah that is unfortunate. Firefox and Brave work, but Chromium does not. It appears that chromium depends on a newer version of libjpeg then vmware-view has bundled in (and exports with LD_LIBRARY_PATH). I'll play with it to see if there is an elegant solution. I can think of a couple inelegant solutions.

**Comment by buckley310** [comment]
Well that was easy, I just deleted libjpeg.so from the vmware files :)
I also realized that they released a new version two weeks ago, so I bumped the version.
Give my branch a try now and see if it resolves everything for you. If it does, I'll PR it.

**Comment by notgne2** [comment]
Everything I can test seems to work, I don't actually have access to a server where I can test browser based authentication, I was just trying to test that as far as I could as I was trying to get this packaged fixed for a friend and wasn't sure how his authentication worked.

**Comment by buckley310** [comment]
Good enough for me, it should be better than before at least. I actually only have credentials to a non-browser-login server.

**Comment by 06kellyjac** [comment]
I'm getting a crash on signin, shall I open a new issue?

```
2021-02-15 13:24:17.818+00:00: vmware-view 26105| Failed to open file “/etc/vmware/udpProxy/config”: No such file or directory
2021-02-15 13:24:17.891+00:00: vmware-view 26105| cdk_window_set_multi_monitors Invalid desktop.
2021-02-15 13:24:17.945+00:00: vmware-view 26105| CdkConnection_CheckPeerReachabilityImpl: peer reachability check returns 1 with error 0.
2021-02-15 13:24:17.946+00:00: vmware-view 26105| udpProxyLib: FECHostSocket_Specialise: failed to get desired receive bufsize: 425984, errno 115

2021-02-15 13:24:17.946+00:00: vmware-view 26105| udpProxyLib: socket 101 transition to state SYN_SENT, reason FECSocketDoConnect refCount 4

2021-02-15 13:24:18.014+00:00: vmware-view 26105| udpProxyLib: socket 101 transition to state CLOSED, reason FECSocketDoClose refCount 6

2021-02-15 13:24:18.014+00:00: vmware-view 26105| udpProxyLib: FECSocketDestroy: Destroying listen socket 101

2021-02-15 13:24:18.161+00:00: vmware-view 26105| IP protocol type is unknown: 0
2021-02-15 13:24:18.161+00:00: vmware-view 26105| IP protocol type is unknown: 0
2021-02-15 13:24:18.870+00:00: vmware-view 26105| IP protocol type is unknown: 0
munmap_chunk(): invalid pointer
/nix/store/ncycm3f0kw49hyd2bl7rvrk5gvcffr19-vmwareHorizonClientFiles/bin/vmware-view: line 86: 26105 Aborted                 (core dumped) "$binPath/bin/$binFile" "$@"
```

**Comment by buckley310** [comment]
@06kellyjac are you on 20.09 or unstable?

**Comment by 06kellyjac** [comment]
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.4, NixOS, 21.03pre261422.1a57d96edd1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"home-manager, nixos-21.05pre269929.ff96a0fa563, nixos-hardware"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by buckley310** [comment]
I'm not sure how you're getting it to crash, can you describe your setup briefly (WM/DE, default browser, type of login supported on the server you're using) and ill see if it happens on my end?

**Comment by 06kellyjac** [comment]
Sorry for the delayed response. I've been using a lightweight VM to run vmware-horizon-client and it's been surprisingly swift actually but it'd be nice to get it working natively.
Especially since I'm now doing nixos -> arco vm -> vware horizon windows vm -> xrdp to linux vm :sweat_smile: 

My WM is i3, my DE is none, I'm using picom

I've tried again and it works as long as I dont move my mouse/window focus away from the window (image below) while I enter my details, if I do it crashes
It also crashes if I click the dropdown to change the domain but it works fine if I tab to it and type it out by hand

Here's the log

```
vmware-view -s SERVER -u USERNAME -t USERNAME -q -d DOMAIN --save
Using log file /tmp/vmware-usernamehere/vmware-horizon-client-1982.log
2021-03-16 17:52:00.194+00:00: vmware-view 1982| access fail
2021-03-16 17:52:00.246+00:00: vmware-view 1982| Failed to open file “/etc/vmware/udpProxy/config”: No such file or directory
2021-03-16 17:52:00.333+00:00: vmware-view 1982| cdk_window_set_multi_monitors Invalid desktop.
2021-03-16 17:52:00.407+00:00: vmware-view 1982| CdkConnection_CheckPeerReachabilityImpl: peer reachability check returns 1 with error 0.
2021-03-16 17:52:00.407+00:00: vmware-view 1982| udpProxyLib: FECHostSocket_Specialise: failed to get desired receive bufsize: 425984, errno 115

2021-03-16 17:52:00.407+00:00: vmware-view 1982| udpProxyLib: socket 101 transition to state SYN_SENT, reason FECSocketDoConnect refCount 4

2021-03-16 17:52:00.506+00:00: vmware-view 1982| udpProxyLib: socket 101 transition to state CLOSED, reason FECSocketDoClose refCount 6

2021-03-16 17:52:00.506+00:00: vmware-view 1982| udpProxyLib: FECSocketDestroy: Destroying listen socket 101

2021-03-16 17:52:00.649+00:00: vmware-view 1982| IP protocol type is unknown: 0
2021-03-16 17:52:00.664+00:00: vmware-view 1982| IP protocol type is unknown: 0
2021-03-16 17:52:01.239+00:00: vmware-view 1982| IP protocol type is unknown: 0
# < working fine up to here
free(): invalid pointer
/nix/store/kxh0kb4yawf4wz3c2450420zmjzgqjpl-vmwareHorizonClientFiles/bin/vmware-view: line 86:  1982 Aborted                 (core dumped) "$binPath/bin/$binFile" "$@"
```

---

Additional notes:

The cli login my colleague is using is: `vmware-view -s desktop.place.name.com -u USERNAME -t USERNAME -q -d sample.something.net`

If I just use the UI the first popup is:
Username
Password

The username is always the same (USERNAME), the password here is a TOTP code

Next is:
Server (not an input)
Username
Password
Domain

Server is desktop.place.name.com
Username is the same
Password is my actual password
Domain is sample.something.net

(see censored image)

![vmware](https://user-images.githubusercontent.com/9866621/111355582-677ac600-867f-11eb-9a41-9a7eaa783583.png)

---

My issue now is the nixos native connection looks really fuzzy compared to it running within my arco openbox vm on nixos

It's not related to the crashing but I'll leave some details below, I can open a new issue for it if you'd like but the arco vm is working ok

nixos host:
![vmware_native](https://user-images.githubusercontent.com/9866621/111358332-20420480-8682-11eb-9bd1-5ce5b8b0db01.png)

arco openbox vm using libvirt on nixos host:
![vmware_withinvm](https://user-images.githubusercontent.com/9866621/111358404-351e9800-8682-11eb-8175-eedff811acb0.png)

On the VM looking at the display settings it's exactly 1920x1080 in full screen and a tiny bit less in window mode but both look fine

I have a keybind to make a window 1920x1080 in i3 and this is the resolution it's making it within the vmware connection:

![image](https://user-images.githubusercontent.com/9866621/111359152-0f45c300-8683-11eb-8b48-1e816c55e179.png)

Even including the space lost by the toolbar and my tiny border 1672x918 isn't very close to to 1920x1080

![image](https://user-images.githubusercontent.com/9866621/111359407-60ee4d80-8683-11eb-8abe-f48e157c5d17.png)

I've made sure they both use the VMWare blast H.265 decoding option

Maybe it's an i3 or me problem and it'd be fine using openbox or something

**Comment by buckley310** [comment]
I've recreated the crash on my machine as well. I also go through two login prompts to sign in, and if i click away from the login prompt on the second screen, it crashes. Clicking away on the first screen is fine. I guess I've never clicked away on the second prompt before. I'll look into this.

I'm willing to bet that display scale issue is because vmware thinks you're running with high DPI. if `xdpyinfo | grep dots` says you're not at 96x96 that could be the cause. That probably belongs in a separate github issue though.

**Comment by buckley310** [comment]
@06kellyjac if you get a chance, give the above PR a test. It fixes the crashing issue for me.

**Comment by buckley310** [comment]
I think all of the crash bugs identified here have been sorted.
