### ISSUE TITLE
Unable to run tests for neovim

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#11009]
In order to run `make` in the neovim tree one must first add `libtool`, `autoconf`, and `automake` and `unzip` to the build dependencies.

Running `make test` fails with [this](https://gist.github.com/anonymous/8a9cc3585ddef62c58d0) output.

**Comment by vcunat** [comment]
I'm not sure what you mean. The expression doesn't run tests. I assume you want to run tests by default?

**Comment by expipiplus1** [comment]
Sorry,

I'm unable to manually run the tests for neovim when building in an environment generated by nix-shell.

**Comment by domenkozar** [comment]
A lot of times the derivation doesn't have all development tools available. You have to add them yourself

**Comment by teto** [comment]
I am looking into this. Appending path towards lua libraries in ".deps" in `LUA_PATH` improves the situation a bit (e.g., export LUA_PATH="$LUA_PATH;.deps/usr/share/lua/5.1"), yet I am stuck on:

```
-- Output to stderr:
/home/teto/neovim/.deps/usr/bin/luajit: /home/teto/neovim/.deps/usr/share/lua/5.1/pl/path.lua:30: pl.path requires LuaFileSystem
stack traceback:
	[C]: in function 'error'
	/home/teto/neovim/.deps/usr/share/lua/5.1/pl/path.lua:30: in main chunk
	[C]: in function 'require'
	/home/teto/neovim/.deps/usr/share/lua/5.1/busted/runner.lua:3: in main chunk
	[C]: in function 'require'
	...deps/usr/lib/luarocks/rocks/busted/2.0.rc12-1/bin/busted:3: in main chunk
	[C]: at 0x00404490
```
aka the tests fail to find luafilesystem. 
```
local res,lfs = _G.pcall(_G.require,'lfs')
if res then
    attributes = lfs.attributes
    currentdir = lfs.currentdir
    link_attrib = lfs.symlinkattributes
else
    error("pl.path requires LuaFileSystem")
end
```
One needs to modify LUA_CPATH for that one but I haven't succeded (yet) to load the correct lfs.so. Also I note that I have some strange paths in my generated LUA_CPATH as it mixes "5.1" with "5.2" as in "hhla5nzzkdv608j0a6djxkw8h1abma49-lua5.1-filesystem-1.6.2/share/lua/5.2/?.so;". Dunno if that's normal :s

**Comment by teto** [comment]
mostly commenting for myself but after dropping in a shell `nix-shell -A neovim $HOME/nixpkgs2`, I do
```
cmakeConfigurePhase
export LUA_PATH="$LUA_PATH;$HOME/neovim/.deps/usr/share/lua/5.1/?.lua"
export LUA_CPATH="$HOME/neovim/.deps/usr/lib/lua/5.1/?/core.so;$HOME/neovim/.deps/usr/lib/lua/5.1/?.so;$LUA_CPATH"
 TEST_FILE=./test/functional/api/highlight_spec.lua make functionaltest VERBOSE=1
```
which still fails here because neovim default's.nix sets       `"-DLUA_PRG=${luaPackages.lua}/bin/lua"` to lua 5.2 but neovim itself always downloads luajit packages, see BuildLuarocks.cmake:
```
 BuildLuarocks(
    CONFIGURE_COMMAND ${DEPS_BUILD_DIR}/src/luarocks/configure
      --prefix=${HOSTDEPS_INSTALL_DIR} --force-config ${LUAROCKS_OPTS}
      --lua-suffix=jit
    INSTALL_COMMAND ${MAKE_PRG} bootstrap)
```
so there is a mismatch when loading libraries (for instance lfs.so = luafilesystem.so) because each interpreter needs its own library. In my case, neovim/.deps has luajit libraries while my interpreter is lua5.2. 
Overall the neovim package feels weird, like a mix of native nixos  and bundled packages. I don't mind  packaging the missing dependancies if it makes sense; some are already available on luarocks, I don't know if doing anything in nixos is needed (if nixos plans to automatically generate the packages from luarocks etc). For those interested in neovim-dev, it might be necessary to maintain a separate neovim-dev.nix I guess ?

**Comment by teto** [comment]
I have the tests working in https://github.com/NixOS/nixpkgs/pull/33903 . It might take some time but we are getting there.

**Comment by teto** [comment]
`functionaltest` for neovim can now be run in nixos-unstable, there is a doCheck setting set to false by default so we can close this.

**Comment by expipiplus1** [comment]
@teto Thanks! closing!

**Comment by teto** [comment]
as a complement, I have 3 tests failing in nix-shell, the xclip one (I suppose it wouid succeed in a --pure environment) and 2 TERM related ones. But the tests can be run :)
