### ISSUE TITLE
nix-shell -p cargo --command "cargo help" does not work

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#11053]
as per the title, running 'nix-shell -p cargo --command "cargo help"' fails with "Could not execute process `rustc -vV` (never executed)". There seems to be an unaccounted for runtime dependency of cargo on rustc.

**Comment by wizeman** [comment]
Good catch!

Wow, I think this calls for a complete refactoring of the rust build system.

Since `cargo` implicitly depends on `rustc`, perhaps it doesn't make sense to have `rust*Platform` anymore, and instead make all Rust builds simply depend on `cargo` (which would itself depend on the stable `rustc`), or `cargoMaster` (which would depend on `rustcMaster`).

Although the name `cargoMaster` could be a bit misleading, because it would not be a version of `cargo` taken from the master branch, it would be a stable version of `cargo` that calls into a version of `rustc` taken from the master branch... so I'm not sure if that would be the best way to name it...

**Comment by wizeman** [comment]
This should be fixed now. Thanks for reporting!
