### ISSUE TITLE
Assert when no window manager nor desktop manager are enabled.

### ISSUE THREAD

**Issue by nbp** [NixOS/nixpkgs#11064]
The goal is to ensure that NixOS users do not forget to enable a window manager or a desktop manager when they enable the X server.  As soon as we have a didactic message, we can change the default value of `services.xserver.desktopManager.default` to replace it by `"none"` and change the example value to be more talkative.

To do that, we should add an `assertions` or a `warning` into display-managers/default.nix module [1] which checks the sessions options of the desktop manager [2] and the session option of the window manager [3] and report if these are empty.

[1] https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/default.nix 
[2] https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/default.nix#L29
[3] https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/window-managers/default.nix#L36

**Comment by vcunat** [comment]
Sounds nice. "good-first-bug" is supposed to mean it's suitable for nix-inexperienced people? (reminds me of "trivial" tag also)

**Comment by nbp** [comment]
> Sounds nice. "good-first-bug" is supposed to mean it's suitable for nix-inexperienced people?

Yes, this means for users (frequently new) which would gain more experience by solving this issue.

**Comment by TimoMeijer** [comment]
@nbp Could I pick this up to gain some experience with NixOS and contributing?

**Comment by vcunat** [comment]
@TimoMeijer: why not, take it. I would make you the Assignee formally, but it seems github only allows people with commit rights in there.

**Comment by TimoMeijer** [comment]
There seems to be no proper way to make this assertion, because:
1. As @lethalman pointed out, the User could have a custom ~/.xsession file that starts their environment, even if no window- or desktopmanager has been enable. This can not be checked during the build, as we can't access the user home to check for this file. This could be overcome by making the ~/.xsession more integrated into our configuration, but that would be a separate issue.
2. The User could change the "systemd.services.display-manager.preStart" option, to change the behaviour of the displayManager entirely. This implies that even if the xserver is enabled, the displayManager doesn't have to be, and thus, the assertion could break an otherwise valid configuration.

**Comment by Profpatsch** [comment]
(triage) I’m not sure if it’s a good idea to limit the users with an assert. How about inserting a warning and calling it a day?
