### ISSUE TITLE
Fixed hostId on installation media

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#11085]
This line: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/base.nix#L53 fixes the hostId when booting from the LiveCDs.

Should this be fixed statically or randomly generated? I thought the hostid should be unique across machines.

Also for the first time when setting up ZFS, I needed a unique hostId, so I had to use `networking.hostId = pkgs.lib.mkForce "insert host id"` in the `configuration.nix`. However this resulted in another problem where `nixos-rebuild switch` failed on the LiveCD.

**Comment by wizeman** [comment]
It could be randomly generated, but then if you reboot and boot again from the LiveCD without having exported your ZFS pool, ZFS would complain that the pool might be in user from another system.

ZFS uses the `hostId` to prevent a ZFS pool from being imported at the same time on 2 different machines, which can lead to catastrophic loss of data. Personally, I think this is unlikely this would happen when booting from a LiveCD. I find the above scenario of ZFS thinking that your machine has changed simply because you rebooted, is more likely to happen and it can lead to user confusion, but I'd be happy to reconsider if anyone feels strongly about this issue.

Can you post the output of the failed `nixos-rebuild switch` after having set `networking.hostId`?

**Comment by CMCDragonkai** [comment]
I suppose the right way to do this, is to generate the a unique hostid manually prior setting up ZFS. This should be documented better and the fact that you need to override using `mkForce`.

@wizeman the error for nixos-rebuild is at here: https://github.com/NixOS/nixpkgs/issues/11091

It's more general than just the hostId. It affects the live cd entirely and that means something is seriously broken if I can't do something as fundamental as nixos-rebuild.

By the way if the hostId does change, is there a way to make ZFS refresh its hostid cache?

**Comment by nbp** [comment]
> I suppose the right way to do this, is to generate the a unique hostid manually prior setting up ZFS. This should be documented better and the fact that you need to override using `mkForce`.

Instead of documenting that the user has to use `mkForce`, we should change [1] to use `mkDefault`.

[1] https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/base.nix#L53

**Comment by CMCDragonkai** [comment]
That's a good idea, perhaps I can submit a pull-request with it changed to `mkDefault`?

**Comment by nbp** [comment]
@CMCDragonkai sure :) Don't forget to mention this issue to get a cross-reference.

**Comment by CMCDragonkai** [comment]
@nbp Here it is: https://github.com/NixOS/nixpkgs/pull/11185

**Comment by nbp** [comment]
@CMCDragonkai Thanks, as you know more about the details, it would be good to provide additional documentation, such that users do not keep the default value when they use it the same way as you did, in order to avoid surprises.

**Comment by ttuegel** [comment]
Closing because this seems to be fixed by the pull request mentioned above.
