### ISSUE TITLE
haskellPackages documentation recursive dependency example simplification

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#11101]
The example seems to be overly complicated. So is the `super` argument shadowed once and the outer `self` is not even used.

```nix
# old
  {
    packageOverrides = super: let self = super.pkgs; in
    {
      haskellPackages = super.haskellPackages.override {
        overrides = self: super: {
          foo = self.callPackage ../src/foo {};
          bar = self.callPackage ../src/bar {};
        };
      };
    };
  }

# new
  {
    packageOverrides = oldPkgs:
    {
      haskellPackages = oldPkgs.haskellPackages.override {
        overrides = self: super: {
          foo = self.callPackage ../src/foo {};
          bar = self.callPackage ../src/bar {};
        };
      };
    };
  }
```

@peti

**Comment by peti** [comment]
I have mixed feelings about this change. When I show `packageOverrides` configurations to anyone, I always include the `super: let self = super.pkgs; in { ... }` idiom to advertise the fact that overrides have access to both `self` and `super`. People need to be aware of that, IMHO, and it's not obvious unless someone tells you (or shows you). In the same spirit, I always use that code snippet in the Haskell documentation, too, just because this feels like the right way to structure your overrides.

On the other hand, I realize that the code examples from the manual actually don't need to distinguish between `self` and `super` and thus are unnecessarily complicated.

How about the following compromise: personally, I won't make the change outlined above, but if anyone submits a PR for it, then I'll merge it.

**Comment by Profpatsch** [comment]
Ah, I missed that you are using the idiom in nearly every example.

Then what’s missing is probably an explanation of the idiom. The only place I‘ve found is in the description of pkgs.overridePackages; maybe a more in-depth description at the beginning of the haskell section?

**Comment by peti** [comment]
Does that explanation belong into the Haskell section?

**Comment by Profpatsch** [comment]
Depends on whether other parts of nixpkgs use it in the same manner I’d say.

**Comment by peti** [comment]
Well, I'd be happy to review a PR that improves the current situation.

**Comment by peti** [comment]
The current situation feels sufficiently non-harmful to stick with it. :-)
