### ISSUE TITLE
haskellPackages.hnix fails to build on macOS

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#111562]
**Describe the bug**
Fails to build to do a failing system call in the tests

**To Reproduce**
```
$  nix build -f. haskellPackages.hnix           
Failed to find a machine for remote build!
derivation: 5k8f28jw1q9wgzr7vv24pza2xbqw85gv-hnix-store-core-0.4.1.0.drv
required (system, features): (x86_64-darwin, )
1 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
(x86_64-linux, 1, big-parallel, kvm, )
error: builder for '/nix/store/5k8f28jw1q9wgzr7vv24pza2xbqw85gv-hnix-store-core-0.4.1.0.drv' failed with exit code 1;
       last 10 log lines:
       >     create test files (0.43s)
       >       readCreateProcess: ls "/proc/65598/fd" (exit 2): failed
       >   golden
       >     derivation roundtrip of tests/samples/example0.drv:                                                        OK
       >     derivation roundtrip of tests/samples/example1.drv:                                                        OK
       >
       > 1 out of 36 tests failed (0.82s)
       > Test suite format-tests: FAIL
       > Test suite logged to: dist/test/hnix-store-core-0.4.1.0-format-tests.log
       > 0 of 1 test suites (0 of 1 test cases) passed.
       For full logs, run 'nix log /nix/store/5k8f28jw1q9wgzr7vv24pza2xbqw85gv-hnix-store-core-0.4.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/cwzn25xbc8aw8s333d1r6n3bdshgvr31-hnix-0.12.0.1.drv' failed to build
```
**Expected behavior**
hnix should build

**Notify maintainers**
@peti

**Comment by cdepillabout** [comment]
@siraben There are unfortunately not that many people fixing up things on MacOS, but if you're interested in figuring out a fix and sending a patch (and possibly reporting upstream if necessary), it would be great to get this working.

**Comment by peti** [comment]
Ping @Anton-Latukha. Can you help, maybe?

**Comment by Anton-Latukha** [comment]
Yes.

HNix-Store-Core project test suite uses `/proc`, and macOS has no `/proc` https://github.com/haskell-nix/hnix-store/issues/109.

Lets say, HNix-Store-* is still improving the maintenance situation in it: https://matrix.hackage.haskell.org/#/package/hnix-store-core.
Need some time how to carefully figure out how to unwrap the human nature situation in it.

Sorry for the current response: figuring-out the situation in the project is more important than to running-in and hotfixing the current bug and pretend to be a weekend hero that saves the day to everyone. Because then we (I) would keep pinging the maintainers to maintain the project and make releases, and they would keep "saving the day", when that is their responsibility to solve things before this or ASAP fix them by themselves. Upstream maintenance is aware of this bug for 1.5 month, and so far nothing was done. So I'm thinking about how to fix the whole of the situation properly. How to address the situation so that `HNix-Store-*` expands to get responsible people.

Probably, really start to prefer merging `HNix-Store-*` in to `HNix` to form 1 monorepo.

Would be with relevant news in a couple of days.

**Comment by Anton-Latukha** [comment]
I walked and thought and started to crank the situation from the Stackage.

`hnix-store-core` a year ago was published by ... to the `stackage` and submitted to `stackage` LTS.

And the person that submitted it there - never after done anything to maintain it.

Which, you know. https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=hnix-store-core

So unwrapping the situation from the Stackage: https://github.com/commercialhaskell/stackage/issues/5872, so the Haskell-Nix & Nixpkgs maintainers have an easier time to releasing and supporting the release.

After that again would discuss the expansion of the release team.

After that - we can do & more importantly *release* & ship the macOS support properly.

**Comment by Anton-Latukha** [comment]
So.

In that timeframe.

Managed to pull old release from Stackage Nightly. But it is in LTS, which I thing Nixpkgs does not inherit from. And Stackage promises to delete our old project release (and package at all) from next major LTS release.
Pulling-of which was a quest.

So in this timeframe Nixpkgs closures simplified.

Just made a new release with macOS support.
So far *idk* for Nixpkgs build, but made a CI Cabal macOS build and the project passed it.
For `hnix-store-remote` is other story, it uses `linux-headers`.

`hnix-store-core` closures got cleaned-up, sadly without mine participation, so thank you to the people and to `pety`.

So on Hackage update the project would start working.
