### ISSUE TITLE
How to find Latex packages with the new TexLive integration in nix.

### ISSUE THREAD

**Issue by svenkeidel** [NixOS/nixpkgs#11170]
Hi,

Recent efforts have split up the whole monolithic TexLive distribution into multiple small nix packages. Now the problem arrises how one can find a latex package within the distribution. In particular I want to find the package that contains the tikz.sty file. Can someone explain how to explore those packages?

Best,
Sven

**Comment by vcunat** [comment]
I wonder how other TeX/Linux distributions do this. I think I actually saw one which automagically downloaded missing files during compilation (after asking for confirmation).

ATM the easiest way occurring to me is to search in <ftp://tug.ctan.org/pub/tex/historic/systems/texlive/2015/tlnet-final/tlpkg/texlive.tlpdb> . In `tikz.sty` case it looks like `pgf`.

Of course, having a database of produced files is an issue independent of TeX. We currently have it only for `bin/*` stuff, accessible via the `command-not-found` hook.

**Comment by svenkeidel** [comment]
I have tried pgf:

```nix
pkgs.texFunctions.runLaTeX {
  rootFile = ./zeromq-infrastructure.tex;
  packages = [
    env
    (pkgs.texlive.combine {
      inherit (pkgs.texlive) scheme-small pgf;
    })
  ];
}
```

```tex
\documentclass{minimal}
\usepackage{pgf}
\begin{document}
\end{document}
```

But `\usepackage{tikz}` still does not work.

**Comment by peti** [comment]
The file lives in `share/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty`, which is definitely part of the `pgf` package. The fact that your build won't succeed seems related to the `runLaTeX` function rather than LaTeX itself, i.e. the following command translates your `example.tex` file just fine:

~~~
nix-shell --pure -p "texlive.combine { inherit (pkgs.texlive) scheme-small pgf; }" --run "pdflatex example.tex"
~~~

**Comment by svenkeidel** [comment]
Oh you are right. But this was the function Elco showed as an example on NixCon...

Anyway. thanks a lot for the help.
