### ISSUE TITLE
Dwarf Fortress 0.47.04 -> 0.47.05

### ISSUE THREAD

**Issue by IGJoshua** [NixOS/nixpkgs#112698]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: dwarf-fortress

current version: 0.47.04
desired version: 0.47.05

###### Notify maintainers

maintainers: @a1russell @robbinch @roconnor @the-kenny @abbradar @numinit 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by Olical** [comment]
I would quite like to help with this if possible, will it just (hah, _just_) involve bumping versions and hashes as well as making sure everything builds and runs okay? Or is there a lot more to it than that? I'll try to read up on contributing to nixpkgs in the mean time!

**Comment by Olical** [comment]
So I ended up tinkering over lunch and got v0.47.05 to run (with dfhack, twbt etc too) and the core game seems okay. `dwarftherapist` doesn't seem to like the memory map which is a little concerning, but that _seems_ to be the only issue so far (despite being a bad one).

```
Using /home/ollie/.local/share/dwarftherapist as Dwarf Therapist overlay directory.
2021-Feb-24 13:49:25.963 INFO	core	Dwarf Therapist "41.2.1" starting normally. [../src/dwarftherapist.cpp:211] (setup_logging)
2021-Feb-24 13:49:25.963 INFO	core	Runtime QT Version 5.15.2 [../src/dwarftherapist.cpp:212] (setup_logging)
2021-Feb-24 13:49:25.964 INFO	core	opening layout "/home/ollie/.local/share/dwarftherapist/memory_layouts/linux/v0.47.05_linux64.ini" [../src/memorylayoutmanager.cpp:59] (reload)
2021-Feb-24 13:49:25.965 INFO	core	adding valid layout "v0.47.05 linux64" checksum: "0x7c59bfe5" SHA: "ff50f95ca989270cf70202e90b6a7103ba16ff1f" [../src/memorylayoutmanager.cpp:70] (reload)
2021-Feb-24 13:49:25.965 INFO	core	opening layout "/home/ollie/.nix-profile/share/dwarftherapist/memory_layouts/linux/v0.47.05_linux64.ini" [../src/memorylayoutmanager.cpp:59] (reload)
2021-Feb-24 13:49:25.966 INFO	core	adding valid layout "v0.47.05 linux64" checksum: "0x7c59bfe5" SHA: "ff50f95ca989270cf70202e90b6a7103ba16ff1f" [../src/memorylayoutmanager.cpp:70] (reload)
fish: “dwarftherapist” terminated by signal SIGSEGV (Address boundary error)
```

My main question is: If I can solve this issue and everything is working okay, should I submit multiple PRs for each component or just one PR for the entire dwarf fortress directory?

I feel like one PR makes sense since these modules depend on each other pretty tightly.

**Comment by Olical** [comment]
Worked out the Dwarf Therapist crash! I needed to use the qt `mkDerivation` as opposed to the `stdenv` one! Just like this https://github.com/NixOS/nixpkgs/pull/96184 which I _think_ is related to the issues mentioned at the bottom of this page https://nixos.wiki/wiki/Qt

I hope that helps future people! Strike the Earth!

Now everything seems to be working for me but in one super commit since everything in here seems to depend on each other... submitting PR now!

**Comment by Olical** [comment]
Ah, now I'm stuck on stonesense / soundsense I think... when I enable them (I have them disabled normally) I get `“dwarf-fortress” terminated by signal SIGSEGV (Address boundary error)` at startup. Back to the drawing board.

**Comment by Olical** [comment]
The segfault goes away if I run as sudo :thinking: so it's trying to perform an [mmap](https://linux.die.net/man/2/mmap) that it doesn't have access to when I have sound enabled... how odd. Not sure how to proceed, but I guess since the update it's trying to access a sound thing it doesn't have access to. Maybe this is specific to my local user on NixOS? It works fine in the previous version :thinking:
