### ISSUE TITLE
Haskell package helm-0.7.1 fails to build in NixOS

### ISSUE THREAD

**Issue by wvhulle** [NixOS/nixpkgs#11345]
My nixos version is 15.09.706.45128de (Dingo). Executing `nix-env -iA nixos.haskellPackages.helm
` gives the following:

```
Preprocessing library helm-0.7.1...

src/FRP/Helm.hs:44:18:
    Could not find module ‘Graphics.UI.SDL’
    Use -v to see a list of the files searched for.
builder for ‘/nix/store/5wdg2pn5cf27n8qh6xifpspcn3xb42va-helm-0.7.1.drv’ failed with exit code 1
error: build of ‘/nix/store/5wdg2pn5cf27n8qh6xifpspcn3xb42va-helm-0.7.1.drv’ failed
```

**Comment by peti** [comment]
We cannot build `helm` in Nixpkgs, because the package required on old versions of its dependencies that we don't provide: http://packdeps.haskellers.com/feed?needle=helm. Generally speaking, it seems like this package has never been ported to ghc 7.10.x. You might have more luck building it with an older compiler, but this is a problem that should be reported upstream, IMHO.

**Comment by wvhulle** [comment]
Thanks. I'll try to figure out how to compile using an older compiler within nixos then. I wonder why the older deps are not provided?

**Comment by peti** [comment]
http://lists.science.uu.nl/pipermail/nix-dev/2015-November/018672.html might be relevant.
