### ISSUE TITLE
Syncthing relies on insecure version of go

### ISSUE THREAD

**Issue by jabranham** [NixOS/nixpkgs#113906]
**Describe the bug**
Syncthing refuses to install from the unstable channel

**To Reproduce**
1. nix-shell -p syncthing

`error: Package ‘go-1.14.15’ in /nix/store/pspr3icn3frvzv0nnqikcsd0qw22vpk9-nixos-20.09.3223.38eaa62f283/nixos/pkgs/development/compilers/go/1.14.nix:247 is marked as insecure, refusing to evaluate.`

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.97, NixOS, 20.09.3160.5c53c720ff6 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3223.38eaa62f283, nixos-unstable-21.03pre249162.1dc37370c48"`
 - channels(alex): `"unstable-21.05pre271444.9816b99e71c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

@peterhoeg @andrew-d

**Comment by seqizz** [comment]
Hmm, I'm getting the same issue on release actually:

[error.txt](https://github.com/NixOS/nixpkgs/files/6017924/error.txt)

System info:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.60, NixOS, 20.09.3157.95ce0f52ec1 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3223.38eaa62f283"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 - ```

There was a [recent merge](https://github.com/NixOS/nixpkgs/pull/113809) which I hoped it'd fix the 20.09 at least, apparently not.

**Comment by sternenseemann** [comment]
This is because the NixOS 20.09 channel hasn't advanced to that version yet. Presumably it is waiting for some rebuilds to finish and be published to the binary cache.

You can see where the channel is at on the [nixos-20.09 branch](https://github.com/nixos/nixpkgs/tree/nixos-20.09) and the [changes yet to hit the channel using the GitHub compare feature](https://github.com/NixOS/nixpkgs/compare/nixos-20.09...release-20.09).

I briefly checked on Hydra and the synctest builds are green again for `release-20.09`, so syncthing should be working again when the channel advances.

All in all this backport caused unfortunate evaluation errors which could have been prevented for little gain as there were no actual known Vulnerabilities for Go 1.14 (afaik at least), so there was no immediate necessety to get it of people's machines.

**Comment by mohe2015** [comment]
IMHO it was correct to update the go version as soon as it got unsupported. I would assume that security tests are not done against EOL versions as much as against supported versions.

**Comment by sternenseemann** [comment]
> IMHO it was correct to update the go version as soon as it got unsupported. I would assume that security tests are not done against EOL versions as much as against supported versions.

Fair enough, but it should not be done if it breaks evaluation of packages on NixOS stable. The correct way to implement that change would've been to patch/update packages that depend on Go 1.14 _first_ and then remove / mark as insecure Go 1.14, so there is no intermittent breakage for stable users.

**Comment by adisbladis** [comment]
I see this as a larger failure in the maintenance of the Go package itself.
We _know_ that only the two latest Go releases are supported and we roughly know the release schedule of Go so I think this could have been entirely prevented by having a process at NixOS release branch-off.

**Comment by dotlambda** [comment]
The channel has since advanced, so this issue can be closed.
