### ISSUE TITLE
nixpkg-provided OpenBLAS seems completely broken

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#114056]
**Describe the bug**
Any program trying to use OpenBLAS seems to fail spectacularly.

**To Reproduce**
I made a reproduction repository [here](https://github.com/Fuuzetsu/broken-nix-openblas/tree/bcc7568096dd82f7a5463ade7383424de465c5ac). Please see the README.

Roughly:
1. Write any program that uses libopenblas.so: I proved a trivial fortran program in the repro to avoid any FFI weirdness.
2. Try run it, get strange result or segfault.
3. Build your own libopenblas.so, run the exact same program with it instead (via LD_LIBRARY_PATH): get the expected result.

**Expected behavior**
No segfault, no strange behaviour.

**Additional context**
I have tried building the nixpkgs-defined OpenBLAS myself when I tried adding debug symbols and the result was the same: so perhaps it is not a hydra problem or anything like that but the definition problem.

**Notify maintainers**
@ttuegel 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05.git.6739ee70216 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-17.09.3269.14f9ee66e63"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I have also tried on an Ubuntu bionic system with nix-provided OpenBLAS with the exact same result. I have initially found the issue on OpenBLAS 0.3.10. After updating to 0.3.13 (most recent) via newer nixpkgs, no improvement. The issue was initially found through a completely different program that was found to work well on MacOS, Ubuntu, Debian but failed with nixpkgs-provided OpenBLAS.

Maintainer information:
```yaml
- openblas
```

**Comment by markuskowa** [comment]
What is your default integer size?

**Comment by Fuuzetsu** [comment]
> What is your default integer size?

I'm... not sure? I assume 64-bit? I don't think we're setting anything non-default anywhere... I suspect the code in the build expression:
```nix
  blas64 =
    if blas64_ != null
      then blas64_
      else hasPrefix "x86_64" stdenv.hostPlatform.system;
```

sets blas64 to true here... I could try explicitly changing it and see if that gives a different result.

Indeed if I do `openblas.override { blas64 = false; }` in the repro repository linked in the original issue, the code succeeds... I'm not sure what this means for me though...

**Comment by Fuuzetsu** [comment]
Does this mean the default should just be 32-bit like the rest of the packaging world?

**Comment by markuskowa** [comment]
This is primarily a Fortran issue, which becomes a [packaging issue](https://github.com/NixOS/nixpkgs/issues/35208): Fortran's default integer size is 32 bit (integer4) if not specified otherwise. This can be changed by using  the `-fdefault-integer-8`  compiler switch to select 64 bit. The BLAS/LAPACK and interfaces do not explicitly specify the type of integer, but it is traditionally assumed to be 32 bit (see also ILP64 vs. LP64: https://en.wikipedia.org/wiki/64-bit_computing).
The big problem is that the compiler can can not see what a library expects (and simply crashes at run time if mismatched, as you have noticed).

There are the following options to solve your problem:
- Use `openblasCompat` instead of `openblas` to get a 32 bit interface.
- Use the `-fdefault-integer-8` switch to compile your program together with `openblas`.
- Use the `blas` and `lapack` derivations. They are wrappers pointing to `openblasCompat`. Here you can check to the `isILP64` attributes to make sure you are building against the right version (see also https://nixos.org/manual/nixpkgs/stable/#sec-overlays-alternatives-blas-lapack).

**Comment by Fuuzetsu** [comment]
Hm, it seems the documentation at https://nixos.org/manual/nixpkgs/stable/#sec-overlays-alternatives-blas-lapack is wrong/out of date. It says:

>The Nixpkgs attribute is openblas for ILP64 (integer width = 64 bits) and openblasCompat for LP64 (integer width = 32 bits). openblasCompat is the default. 

which is not true:
```
  openblas = callPackage ../development/libraries/science/math/openblas { };

  # A version of OpenBLAS using 32-bit integers on all platforms for compatibility with
  # standard BLAS and LAPACK.
  openblasCompat = openblas.override { blas64 = false; };
```

Perhaps 32-bit used to be the default at some point...

For our case, I simply set `openblas.override { blas64 = false; };` and this works for us (I suppose I should just say `openblasCompat`. I think we can close this in favour of #35208.

Thank you for the help.

**Comment by markuskowa** [comment]
> Hm, it seems the documentation at https://nixos.org/manual/nixpkgs/stable/#sec-overlays-alternatives-blas-lapack is wrong/out > of date. It says:

>>    The Nixpkgs attribute is openblas for ILP64 (integer width = 64 bits) and openblasCompat for LP64 (integer width = 32 bits). >> openblasCompat is the default.

The documentation is correct in the sense that `openblasCompat` is the default provider for the `blas` and `lapack` packages. The recommendation is to use `blas` and `lapack` instead of using the `openblas`/`openblasCompat` packages directly as they provide an easy switch mechanism (i.e. if you want to try MKL or some other implementation).
