### ISSUE TITLE
programs.sqlite for darwin

### ISSUE THREAD

**Issue by maxxk** [NixOS/nixpkgs#11406]
Database for command-not-found is currently generated only for nixos (https://github.com/NixOS/nixos-channel-scripts/blob/master/mirror-nixos-branch.sh#L94). 
Is it possible to generate it for nixpkgs and for darwin platform to use command-not-found there?

**Comment by jagajaga** [comment]
cc @copumpkin @vcunat

**Comment by vcunat** [comment]
Well, that command currently outputs suggestions of type `nix-env -iA nixos.foo`, so I assume that's why it's only generated on the "nixos" channels. Note that darwin might have a nontrivially different set of executable names, so it should probably get a separate database file.

BTW, @edolstra seems to have rewritten the script in the meantime. I know rather little about these personally.

**Comment by matthewbauer** [comment]
"nix-index" is now available and works on Linux and macOS systems. You have to generate the database yourself for now, but hopefully in the future we can bundle it in channels like programs.sqlite does now.

https://github.com/bennofs/nix-index
