### ISSUE TITLE
How to set up PPPoE?

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#11438]
Maybe not the most popular use case, but I'm trying to build a router with NixOS. I need to use PPPoE to connect to my ISP, but if I'm not mistaken there is no way to configure it? I found wvdial, which doesn't look like the right tool. Then there's rp-pppoe, but I have no clue how to set that one up. It doesn't come with a service or anything.

Can anyone help? Thanks!

**Comment by osmano807** [comment]
A long time ago I make a service ppp.nix for my home server: https://github.com/osmano807/nixpkgs/blob/9caf0f8f0e70ce37fa5ea400b722a4d44c5e4038/nixos/modules/services/networking/ppp.nix

It worked, but I think I changed it a little and didn't update the github version (made it create a .service file for each connection, instead of using ppp@.service).

**Comment by jgillich** [comment]
@osmano807 Thanks, that's exactly what I'm looking for! IMHO, this belongs in the core.

**Comment by cleverca22** [comment]
i also recently got pppoe-server working on my router (complex story) so you could now use that to test out the pppoe clients

**Comment by jgillich** [comment]
Closing because the original question got answered. Will do a PR at some point..

**Comment by mweinelt** [comment]
@jgillich Are you still planning to do the PR? *poke*
