### ISSUE TITLE
mikutter: update to 4.1.2

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#114440]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: nixpkgs.mikutter (mikutter)

current version: 4.0.0
desired version: 4.1.4

###### Notify maintainers

maintainers: @alyssais (last update, marking the package as broken)

###### Note for maintainers

The mikutter package is currently broken. Upstream provides AppImage and I will migrate to that in my spare time. Feel free to submit a PR if you have done earlier than me though, of course! Please tag this issue in your PR.

**Comment by midchildan** [comment]
Thanks for raising this issue, I've created a PR in #119454.

In case mikutter breaks again, I'd also like to add that building from AppImages should be considered a last resort. Aside from the usual arguments for building from source, AppImage binaries would only work on Linux which is problematic for Darwin support. The Darwin build for mikutter is currently broken at the moment due to ruby-gnome packages, but building from source would make it easier to fix.

**Comment by omasanori** [comment]
Thank you for working on this, @midchildan! Sure, AppImages is not necessary as long as we can make a working build from the source.
