### ISSUE TITLE
julia fails to build on macos

### ISSUE THREAD

**Issue by idontgetoutmuch** [NixOS/nixpkgs#114766]
**Describe the bug**

`nix-build '<nixpkgs>' -A julia`

produces

```
ld: library not found for -lgfortblas
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Notify maintainers**

@garrison 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/6z3a76k322cwr63ndr6cni2csai5rcf6-DarwinTools-1
  /nix/store/wyjlk6rwj2krarb1i3yrn59h11k1vmmb-nix-info
copying path '/nix/store/6z3a76k322cwr63ndr6cni2csai5rcf6-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/wyjlk6rwj2krarb1i3yrn59h11k1vmmb-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.1.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(dom): `"nixpkgs-21.05pre272788.870dbb751f4"`
 - nixpkgs: `/Users/dom/.nix-defexpr/channels/nixpkgs`
```

**Comment by thequicksort** [comment]
Just an extra data point: I just tried this on my MacOS Catalina machine (v10.15.6), and was able to install Julia okay. Through some digging, I found this issue with Julia failing to build due to GCC [1], so wonder if it's related to libtool (a dependency of GCC) not accounting for a Darwin major version change [2]? From what I understand, this would affect GCC on Big Sur . The good news is, I think they found the root cause and released a patch commit of GCC [3], the bad news is I don't think it's been incorporated into an official release patch branch.

[1] - https://github.com/JuliaLang/julia/issues/19588#issuecomment-266986703 
[2] - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97865
[3] - https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=1352bc88a0525743c952197fb2db6e4f8c091cde
<img width="767" alt="image" src="https://user-images.githubusercontent.com/14322653/109593607-1e931100-7ac6-11eb-9ce3-32874ae1cbe9.png">

**Comment by idontgetoutmuch** [comment]
That's very useful - thanks for investigating - but I tried this on a catalina machine I had and it failed :( I think you must be using nixos-20.03 or earlier.

```
dom@MacBook-Pro depot % $(nix-build '<nixpkgs>' -A julia)/bin/julia
$(nix-build '<nixpkgs>' -A julia)/bin/julia
error: Package ‘julia-1.0.4’ in /nix/store/4gi6vkv28h2c68jaw90dyqnfnypxwx65-nixpkgs-20.09.3341.df8e3bd1109/nixpkgs/pkgs/development/compilers/julia/shared.nix:204 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

and

```
dom@MacBook-Pro depot % nix-channel --list
nix-channel --list
nixpkgs https://nixos.org/channels/nixos-20.03
dom@MacBook-Pro depot % $(nix-build '<nixpkgs>' -A julia)/bin/julia
$(nix-build '<nixpkgs>' -A julia)/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.4 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

┌ Warning: Terminal not fully functional
└ @ Base client.jl:346
julia> 
```

This is a really old version of julia - I guess we can look at the diff between 20.03 and 20.09 and unstable.

**Comment by idontgetoutmuch** [comment]
I tried against HEAD turning off the checks and setting

```
      "USE_SYSTEM_BLAS=0"
```

because I think the blas that comes with macos is probably the wrong thing to use - see this discussion: https://github.com/JuliaLang/julia/issues/27044

But this gives me a different build error

```
make: *** [Makefile:60: julia-deps] Error 2
builder for '/nix/store/6adcbvidll19h8i9zwgl8hjn5v8qg6bf-julia-1.5.3.drv' failed with exit code 2
error: build of '/nix/store/6adcbvidll19h8i9zwgl8hjn5v8qg6bf-julia-1.5.3.drv' failed
```

**Comment by idontgetoutmuch** [comment]
https://github.com/NixOS/nixpkgs/pull/114855 but obviously it needs work

**Comment by samuela** [comment]
See also https://github.com/NixOS/nixpkgs/issues/123394
