### ISSUE TITLE
I think fetchgit is broken

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11496]
Commit https://github.com/NixOS/nixpkgs/commit/2cf7069b7da368326b51520536ac0f1020157f7a seems to have broken my calls to `fetchgit`:

Bash complains that it cannot execute the binary file. I noticed this when building `gitAndTools.hub` against nixpkgs 84b3af19b826cbab1cff4b26c0c53ee1d6e83ea3. Removing @peti's change makes it work again.

**Comment by peti** [comment]
How do you call `fetchgit` and what error message do you get?

**Comment by peti** [comment]
`gitAndTools.hub` compiles fine for me in the current `unstable` channel at b1dca6ca881e3e5864c60a2ef206579ce4d718b1.

**Comment by hrdinka** [comment]
It is broken for me as well. I am building NixOS on top of the current master. For me it fails for gnulib with:
`/nix/store/33k6qnz10brkf66lr6yav6bcl4bhy5z0-bash-4.3-p42/bin/bash: /nix/store/33k6qnz10brkf66lr6yav6bcl4bhy5z0-bash-4.3-p42/bin/bash: cannot execute binary file`

I guess that it uses `/nix/*/bash /nix/*/bash` as shell for calling `nix-prefetch-git`. I think this happens because as soon as you make the value of `fetcher` a string it will be executed with bash. The command does call bash itself so bash tries to call bash.

**Comment by peti** [comment]
Please try version b89514eced6d32203982c54e0ad8c2f83dbca900 and let me know if that patch didn't do the trick.

**Comment by hrdinka** [comment]
:+1: thanks that fixed it.
