### ISSUE TITLE
Haskell aarch64 packages are now failing on unstable

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#115117]
Recently, aarch64 haskell packages have stopped working

https://hydra.nixos.org/eval/1652959
log: https://hydra.nixos.org/build/138158017/nixlog/1

cc @peti @roberth @cdepillabout

**Comment by roberth** [comment]
ghc8104 has [always](https://github.com/NixOS/nixpkgs/blame/2a1bda47f7a3365daa6c73dd86d1d28c02f526db/pkgs/development/compilers/ghc/8.10.4.nix#L256) had a 24 hour timeout.

This seems to be a hydra bug. Some ideas:
 - Maybe it's because hydra tried to build ghc from https://hydra.nixos.org/build/138142449, where it is not an attribute (with meta) but a mere dependency of a derivation (therefore without meta?)
 - It's in cross-trunk, which means it probably didn't encounter the meta.timeout attribute, as it's not directly in an attribute of the release file there.

I've restarted it from [here in trunk](https://hydra.nixos.org/build/138150118), hoping that it picks up the extended timeout that way.

**Comment by cdepillabout** [comment]
It looks like the above job that roberth restarted has succeeded: https://hydra.nixos.org/build/138150118

I'll go ahead and close this issue.
