### ISSUE TITLE
Packaging request: Jumpdrive

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#115254]
**Project description**
Scripts that compile a disk image which turns the PinePhone into a jumpdrive for flashing the eMMC.

**Metadata**
* homepage URL: https://github.com/dreemurrs-embedded/Jumpdrive
* license: gpl2
* platforms: linux

cc @NixOS/mobile-nixos

**Comment by samueldr** [comment]
It wouldn't exactly be possible to *package* it. Unless we just copy the prebuilt images. And then there's not much value. We might be able to re-do most of the packaging it does in Nix to make an equivalent build...

But Mobile NixOS has its own [target disk mode](https://github.com/NixOS/mobile-nixos/tree/master/examples/target-disk-mode) system, which for now does pretty much the same thing.

In the future it will have a bit more features. But really none that will be useful for the Pinephone. Still, one step further, the target disk mode features will eventually be rolled-back into the standard recovery.

With that said, I believe it does not work with the Pinephone *yet*. I need to pair with someone to investigate the issue as my Pinephone unit *does not have working USB at all*. (Note: I know about all the expected issues with the Pinephone... My unit has a real abnormal issue.)

Once we have verified working TDM images with Mobile NixOS, we could even get them prebuilt in the NixOS.org Hydra.

**Comment by samueldr** [comment]
Oh, and if we're talking Librem 5 or Pinetab...

Making it work for the Librem 5 should be trivial enough, once there is a Mobile NixOS port for the Librem 5. Which, I don't have it planned personally, I can help someone with the device to do it. Since it's a mainline-ish u-boot based target, it should be trivial to go about 90% of the way.

The Pinetab is basically a big Pinephone, so porting Mobile NixOS to the Pinetab should be trivial enough, and the required changes to make it work for the Pinetab would be the same for the Pinephone

If we're talking other targets, well, Jumpdrive does not support them! But Target Disk Mode already supports (as in verified to work well) RK3399 chromeos-based devices, the pinebook pro (out of tree), and could be made to work with Android devices with planned upcoming features (it's dangerous to use as-is on Android devices).

**Comment by samueldr** [comment]
*Closing*, as Mobile NixOS already provides a system with the same semantics that can be used by end-users.
