### ISSUE TITLE
[21.05] Python release Items

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#115272]
@fridh 

Should we bump the python package sets to python3.8 and 3.9?

Would you like to do another `python-unstable` round before ZHF?

Is there any additional work needed for the 21.05 release in regards to python?

**Comment by FRidh** [comment]
> Should we bump the python package sets to python3.8 and 3.9?

Yes, major updates are still needed. Its just a lot of work again. Core packages such as sphinx and security issue prone packages such as requests need to be updated.

> Is there any additional work needed for the 21.05 release in regards to python?

Then, in order of importance:

1. The default interpreter needs to be changed to 3.9. Now that astroid has been updated to 2.5.0 on staging, I think that will work out. 
2. Get rid of `python setup.py test` wherever that is used, because support for it was removed from `setuptools`.
3. Make `pyproject` the default `format`.

**Comment by SuperSandro2000** [comment]
> Make pyproject the default format.

Wouldn't that break most packages that did not convert yet?

**Comment by NomisIV** [comment]
Would it be a good idea to make sure the python packages are somewhat up to date? I came across flask-jwt-extended, which has gotten a new release, and I see it unlikely all other python packages are up to date. I'm quite new to NixOS, but this would be quite easy

**Comment by jonringer** [comment]
> Would it be a good idea to make sure the python packages are somewhat up to date?

`python-unstable` is a branch that we usually force update all python packages, and try to then stabilize.

**Comment by fabaff** [comment]
> I came across flask-jwt-extended, which has gotten a new release, and I see it unlikely all other python packages are up to date.

No, they aren't all up-to-date unfortunately.

**Comment by jonringer** [comment]
We did a `python-unstable` bump before ZHF.

The other items that @FRidh mentioned I have broken out into separate issues, so they can be tracked individually.

Going to close this, as it's still mentioned a release blocker, but not critical to the release.
