### ISSUE TITLE
Document OpenJDK bootstrapping process

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11545]
It looks like Darwin is currently special-cased and locked at OpenJDK 7 (with a binary package). There's a make-bootstrap.nix with no comments and the existing bootstrap.nix only supports Linux.

I'd like to get proper OpenJDK support for Darwin, but am not sure how to do it properly.

cc @shlevy and @wkennington who have dealt with it before.

**Comment by copumpkin** [comment]
It looks fairly easy to get a bootstrap for OpenJDK 7 given the existing prebuilt binary, but I'm not sure how to cross versions.

**Comment by shlevy** [comment]
The way I did it originally was start with the jdk6 binary we had in nixpkgs at the time, use it to build openjdk7, and then trim down the result of that as much as possible without removing the ability of that version to build itself. Can't the binary of openjdk7 build openjdk8?

**Comment by copumpkin** [comment]
I see; just saw that there appeared to be one bootstrap for 7 and another for 8 and thought there might be something special. I'll try getting it working, thanks!

**Comment by shlevy** [comment]
Not sure why there's a separate bootstrap for 8, we needed a bootstrap for 7 because 6 was unfree.

**Comment by Profpatsch** [comment]
(triage) The files look kind of suspicious. The last change was by @rbvermaa to add 8 in the same fashion as 7.

**Comment by Profpatsch** [comment]
(triage) any updates?

**Comment by Enteee** [comment]
This is a very old and stale Issue. The related files in nixpkgs have been modified and refactored a lot since this issue was created. I have had a quick look at the files in question ([bootstrap.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/openjdk/bootstrap.nix), [make-bootstrap.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/openjdk/make-bootstrap.nix)) and they look ok to me. Currently openjdk 7 is no longer available in unstable. Also I am unsure what kind of documentation @copumpkin is asking for here and what we are trying to fix with this issue.

So unless anybody objects I would vote to close this issue.

cc @Profpatsch , @shlevy
