### ISSUE TITLE
flashplayer is not using archives

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#11571]
`flashplayer` src is currently set to http://fpdownload.adobe.com/get/ that only seems to keep the latest version.
It means that if a user tries to build from source after upstream has pushed a new version, the build will fail due to the source file not found.

Adobe provides an [archive](https://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html) page that could be used to avoid this problem.

As `flashplugin` is not currently in the binary cache, doing a `nixos-rebuild switch` on current nixos-unstable triggers source building and fails with the following error:

```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download install_flash_player_11_linux.x86_64.tar.gz from any mirror
builder for ‘/nix/store/sfp13idhcd1r69gqf0x91pw1b0hgl8y1-install_flash_player_11_linux.x86_64.tar.gz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/alfp7k7qqhx3axviarfa6in5rwgfvrif-flashplayer-11.2.202.540.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/law42xkripv7cr7k52hvcqzrc66abz5d-firefox-with-plugins-42.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/c94g6crlgba972878g46716ls1zds6m5-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/00vkap9hkpg2qiwkd4y8nj1cpsmvl8cm-nixos-system-alpha-16.03pre73106.b1dca6c.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/00vkap9hkpg2qiwkd4y8nj1cpsmvl8cm-nixos-system-alpha-16.03pre73106.b1dca6c.drv’ failed
```
Using archives would prevent issues like #10571 to happen in the future.

cc flashplayer maintainer @enolan 

PS: I made an example of what could look like the derivation using the archives [here](http://nixpaste.lbr.uno/qQlkKzt0) (building, not tested).

**Comment by carldong** [comment]
I am pretty new to NixOS. How would I modify locally for a temporary fix?

**Comment by ericsagnes** [comment]
The workaround from #10571 should work:

```nix
  nixpkgs.config = {
    allowUnfree = true;
    firefox.enableAdobeFlash = true;
    packageOverrides = pkgs: rec {
       flashplayer = pkgs.stdenv.lib.overrideDerivation pkgs.flashplayer (oldAttrs: {
        name = "flashplayer-11.2.202.554";
        src = pkgs.fetchurl {
          url = "http://fpdownload.adobe.com/get/flashplayer/pdc/11.2.202.554/install_flash_player_11_linux.x86_64.tar.gz";
          sha256 = "15zziclffvsa0wpygkwzbh3v367n73pmzwsnkanhg75rv28dgl3x";
        };
      });
    };
  };
```

**Comment by vcunat** [comment]
I'm not certain the current status is necessarily bad, as flash is often vulnerable and this bugs people when installing an outdated version ;-)

**Comment by abbradar** [comment]
While the case of Flash Player is extreme one w.r.t its fame for vulnerabilities using changing source URL for a package seems is a very bad practice in my opinion. It doesn't reach a big part of the target audience with the message:

1. People who do the channel upgrade shortly after it's pushed (chance of hash changed is low at this point)
2. People who do updates rarely, preferring to stay on same `nixpkgs` for a long time.

It also is frustrating to get a hash mismatch during channel upgrade -- what is user expected to do at this point? I was forced to explain to a friend how to do `nixpkgs` checkout and cherry-pick a patch from `master` due to this bug recently -- I imagine other people would be much less patient, especially when no "so what do I do now" guide is available.

**Comment by abbradar** [comment]
I've made a PR addressing this at https://github.com/NixOS/nixpkgs/pull/11675

**Comment by vcunat** [comment]
Hmm, yes, there are better ways of watching for vulnerabilities.

**Comment by vcunat** [comment]
Merged now.
