### ISSUE TITLE
gitlab doesn't work on non-NixOS host systems

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#11592]
When trying to install gitlab using `nix-env -i gitlab` on openSUSE11, the installation process crashes with the error:

    ...
    2907 /tmp/nix-build-gitlab-7.4.2.drv-0/config/environment.rb

    * Process memory map:

    00400000-00401000 r-xp 00000000 00:1c 24189700                           ~/opt/nix-mnt/nix-1.10-x86_64-linux/store/i2sy75caqgk7x1yl33aaschykqqg87ax-ruby-2.1.3-p0/bin/ruby
    00600000-00601000 rwxp 00000000 00:1c 24189700                           ~/opt/nix-mnt/nix-1.10-x86_64-linux/store/i2sy75caqgk7x1yl33aaschykqqg87ax-ruby-2.1.3-p0/bin/ruby
    ...
    ...
    You may have encountered a bug in the Ruby interpreter or extension libraries.

How can I fix this problem?

[crash.log.txt](https://github.com/NixOS/nixpkgs/files/57752/crash.log.txt)

**Comment by domenkozar** [comment]
I'd recommend as first step to enable  `use-chroot` in  `/etc/nix.conf`. see `man nix.conf`

**Comment by knedlsepp** [comment]
Thanks for the quick answer! I will give this a try on a different machine, as I'm not root here and use nix via the proot installation method.

**Comment by fpletz** [comment]
Additionally, I wouldn't really advise to use the gitlab package on an distribution other than NixOS because there are some changes that require the code from the service module to work correctly. For instance, quite a few environment variables and additional config need to be provided which aren't really documented anywhere except in the code in the service module: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/gitlab.nix

This is because gitlab can't write to the nix store as it's mounted read-only. You can't modify the config/gitlab.yml and uploads to gitlab which are hardwired in gitlab to public/uploads won't work as a result.

That's why I think we can close this. If you still feel we should fix this at some point please feel free to reopen.

**Comment by knedlsepp** [comment]
@fpletz That's what I figured also in the meantime. But doing a `nix-env -qaP` gives you all those cool packages to try out and it's disappointing when they fail. Maybe something like `platforms = platforms.nixos`?

**Comment by fpletz** [comment]
@knedlsepp Duh! :wink: Now you discovered our secret plan to lure people into the full nixperience by switching from NixOS! :cake: 

But to get more serious businessy, such a meta attribute does indeed sound very useful yet IMHO not as a platform. I've open another ticket to look into adding this: #13402

**Comment by peti** [comment]
It sounds much better to me to *fix* the gitlab build expression so that its result works for people who aren't using NixOS.

**Comment by fpletz** [comment]
I don't think anyone has the time to fix Rails and Gitlab so that it works on every system with a non-writable Rails root directory. Either way some conventions would have to be defined and a lot of code from the NixOS module would somehow have to be converted to a package or environment - I don't think this is worth the hassle. Closing again.
