### ISSUE TITLE
Should ghcWithPackages withLLVM default to true on platforms where ghc requires llvm?

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#116235]
**Describe the bug**
On aarch64-linux, if you try to build a haskell project in a nix-shell with ghcWithPackages, it will often fail because ghcWithPackages' `withLLVM` parameter defaults to `false`, but GHC on aarch64 requires the llvm executables opt and llc to compile things. There is no documentation mentioning the `withLLVM` parameter, and it's not clear whether it is possible for the user to override it.

**To Reproduce**
1. Get the source code for a haskell project (As an example `git clone https://github.com/nick8325/quickcheck && cd quickcheck`)
2. Spawn a shell with the necessary dependencies and try to build the project:
```
nix-shell --pure -p cabal-install "haskellPackages.ghcWithPackages (pkgs: with pkgs; [ splitmix random ])" --run "cabal build"
```
It will fail with something like
```
<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM 9
ghc: could not execute: opt
```

If I change `withLLVM` to `true` in nixpkgs, it builds successfully.

**Expected behavior**
It should successfully build the project (or it should be documented / easy for the user to specify `withLLVM = true` themselves)

**Notify maintainers**
@maralorn @peti @Ericson2314 @abbradar @matthewbauer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.0-rc5, NixOS, 21.05.git.9e76aa2cca8M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.03.git.0c1c18c"`
 - nixpkgs: `/home/thrall/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    ghcWithPackages
# a list of nixos modules affected by the problem
module:
```

**Comment by cdepillabout** [comment]
@Thra11 This sounds reasonable to me, although I don't know anything about aarch64.

> GHC on aarch64 requires the llvm executables opt and llc to compile things

If this is for compiling _anything_, I'm quite surprised that `withLLVM` is not set to to true by default then, as you suggest.

It would be great to hear from other aarch64 users.  Maybe @domenkozar or @vcunat (they've participated in issues before for Haskell on aarch64)?

Someone else who would probably immediately know the answer to this is @bgamari or @angerman (since I'm pretty sure they are both intimately familiar with GHC on aarch64).

**Comment by angerman** [comment]
I must admit I haven't touched or used the stock ghc in nixpkgs for a long time, since we ship our own ones in haskell.nix to be independent of what ever nixpkgs does. For anything that's not x86, or explicitly set to not use LLVM we do enable `useLLVM`.  (https://github.com/input-output-hk/haskell.nix/blob/bab2eaea62be97649e0d38ef9e3bd313b92cf21d/compiler/ghc/default.nix#L22-L52)

In general GHC up to 9.2 has Native Code Gens for: PowerPC, SPARC, X86 only. From 9.2 this will also include AArch64, but no AArch32.

**Comment by Mathnerd314** [comment]
> There is no documentation mentioning the withLLVM parameter, and it's not clear whether it is possible for the user to override it.

For anyone searching, the magic expression is of the form
```Nix
(pkgs.haskellPackages.ghcWithPackages (ps: with ps; [persistent])).override { withLLVM = true; }
```

**Comment by sternenseemann** [comment]
If anybody wants to test this again, should be fixed on the `haskell-updates` branch.

**Comment by Mathnerd314** [comment]
I put the documentation in https://github.com/NixOS/cabal2nix/pull/491, so hopefully it will be more visible.
