### ISSUE TITLE
mullvad-vpn has a hardcoded path for the GUI autostart.

### ISSUE THREAD

**Issue by vahnrr** [NixOS/nixpkgs#116401]
**Describe the bug**
In [*mullvadvpn-app/gui/src/main/autostart.ts*](https://github.com/mullvad/mullvadvpn-app/blob/38fedbc486fff7c470278859e972bfbd3b085399/gui/src/main/autostart.ts#L35), the path */usr/share/applications* is hardcoded, the only way to change it would be to patch the `mullvad-vpn` package. However, from [*nixpkgs/pkgs/applications/networking/mullvad-vpn/default.nix*](https://github.com/NixOS/nixpkgs/blob/266dc8c3d052f549826ba246d06787a219533b8f/pkgs/applications/networking/mullvad-vpn/default.nix#L47) I see that the Debian package is used, so fixing this in the source code would require not to use a binary version (I guess).

**To Reproduce**
Steps to reproduce the behavior (tested with the package from the `nixos-20.09.3346.4d0ee90c6e2` channel):
1. Open the GUI client using the `mullvad-vpn` command
2. Enable `Settings > Preferences > Launch app on start-up`
3. Notice the following error be thrown in the console: `[<date> <time>][error] Failed to check autostart file: ENOENT: no such file or directory, access '/home/<username>/.config/autostart/mullvad-vpn.desktop'`

**Expected behavior**
The autostart file is properly symlinked to the `mullvad-vpn` nix store package.

**Additional context**
I found a dirty fix for this issue, enable the `auto-start` preference and run:
```sh
ln -sf "$(realpath /run/current-system/sw/share/applications/mullvad-vpn.desktop)" "$HOME/.config/autostart/mullvad-vpn.desktop"
```
However, note that disabling this preference will replace the symlink with the one throwing the error.

**Notify maintainers**
@Br1ght0ne @ymarkus

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.18-hardened1, NixOS, 20.09.3346.4d0ee90c6e2 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.3346.4d0ee90c6e2, nixos-unstable-21.05pre273435.0aeba64fb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute:
- mullvad-vpn
module:
- services.mullvad-vpn.enable
```

**Comment by ymarkus** [comment]
I always use sway and just started it that way on launch so I didn't notice. This will probably, as you said, need a change away from the pre-built package. Right now I'm quite busy, but I'll do it soon. Will tag you in the PR so you can test (as I can't...).

Did the `~/.config/autostart` dir exist before changing the setting?

**Comment by pinkisemils** [comment]
Hey, I'm working on the client daily, and I'm doing so on NixOS, so maybe I can help with this. Building the package might be a bit involved, since our [build script](https://github.com/mullvad/mullvadvpn-app/blob/master/build.sh) is a bit involved ,and it relies on a rust toolchain installed by `rustup`, although this could be worked around with some bash magic to just drop the `+stable` argument. I personally just have a somewhat involved `shell.nix` for building the daemon and then separate FSH environments for running electron builder, but that's because I'm also trying to build for Android and do weird debuggy stuff.

**Comment by vahnrr** [comment]
> Did the `~/.config/autostart` dir exist before changing the setting?

Yes it did since other packages created their own entries beforehand.

**Comment by ymarkus** [comment]
Thanks for the insight, @pinkisemils 
So, is this an issue that might make sense to fix in the mullvad-vpn project itself? If not, could you please send me your `shell.nix` so I have some guidance when building it?

**Comment by pinkisemils** [comment]
I must apologize for the hiatus, but life happened. I've been playing around with a somewhat cleaned up nix shell for building all the things for a proper nix package, but there's still some manual labor required.

The shell that I use is somewhat similar to [this](https://gist.github.com/pinkisemils/3ba7efe9cc5838a186f2e683aeabcce6), but mine has far more cruft to also do android stuff. And this one could very well be slimmed down further too. The FSH environment for node is a vain attempt at making `npm install` and `npm run $script` work better, but to make things work, there's still some manual labor involved. The weird wrapping of `cargo` is there because all the app's build scripts expect rust to be installed via rustup, whereas I use an overlay - so the nix script could be simplified. As long as the rust compiler is new enough, I think the app should build. 

To build the app, there are 6 parts that need to be built:
- `wireguard-go` for when the kernel module is not loaded, built via [a script](https://github.com/mullvad/mullvadvpn-app/blob/master/wireguard/build-wireguard-go.sh). Just executing that script on Linux should work just fine.
- the daemon, the CLI, problem report tool and OpenVPN plugin, should be buildable via `cargo build --release`, but the binaries end up being quite chonky, so they should all be stripped. 
- Shell completions, the following snippet is copied verbatim from  `build.sh` script. 
   ```bash
    mkdir -p "$SCRIPT_DIR/dist-assets/shell-completions"
    for sh in bash zsh fish; do
        echo "Generating shell completion script for $sh..."
        cargo +stable run --bin mullvad $CARGO_ARGS --release -- shell-completions "$sh" \
            "$SCRIPT_DIR/dist-assets/shell-completions/"
    done
   ```
- Download the relay list via `update-relays.sh`
- Download the API address list via `update-api-address.sh`
- the electron GUI, built with an gulp [script](https://github.com/mullvad/mullvadvpn-app/blob/master/gui/gulpfile.js) that eventually invokes [`electron-builder`](https://github.com/mullvad/mullvadvpn-app/blob/master/gui/tasks/distribution.js). The [extra resources](https://github.com/mullvad/mullvadvpn-app/blob/master/gui/tasks/distribution.js#L115-L123) listed is basically a list of things that you must build or adjust so that they work in NixOS. Ideally, one would be able to just invoke `npm install; npm run pack:linux`, but due to [`nseventmonitor`](https://github.com/mullvad/mullvadvpn-app/blob/master/gui/package.json#L35) not building on nixOS (fails due to a node-gyp builder failing to find python) and `pack:linux` producing an `rpm` and a `deb` package, some patching would be required. It'd be great if a nix-npm wizard would apply some arcane knowledge to make `nseventmonitor` build, otherwise it can just be removed from `packages.json`, as it's strictly a macOS dependency. Another change you'd probably want to make is to make `electron-builder` make an unpacked build rather than producing RPMs and DEBs. The electron binary that's downloaded via `npm install` will also not run. A dirty hack that I use to make it work is to just replace it with NixOS's one - `cp $electronPath/bin/electron node_modules/electron/dist`, but this is not what the app developers are testing against, so there most certainly will be dragons.

We build statically linked OpenVPN and Shadowsocks binaries, and those are found in [`dist-assets/binaries`](https://github.com/mullvad/mullvadvpn-app-binaries/tree/2063422c167c874eceab10692d4385a0c40b3f47/x86_64-unknown-linux-gnu) submodule. I assume these should be patchelf'ed so that they can be used on NixOS, but it seems like just using `patchelf --set-rpath ${openVpnLibPath} ./openvpn` is not good enough, but doing what the current derivation does will most likely do the trick. These binaries may be substituted with NixOS native counterparts, but they wouldn't necessarily be equivalent - Mullvad's OpenVPN binaries have some patches that upstream are not interested in and we also try to build the minimal amount of features along with a minimal build of OpenSSL supporting only the ciphersuites that Mullvad servers use. 

I don't believe we have published the keys we use for signing commits currently, I'll see if we can make that happen. Currently, all the release commits are always signed by the same person - but this may change arbitrarily. 

After having written all of the above, I'm not entirely sure if making a native package would be worth the effort, given that I can't guarantee that any of the above won't change often. Maybe the best bet would be to make a minimal patch to get electron builder so that `build.sh` can just run. It seems to me that it's only electron/node related scripts that fail on nixOS:
- the GRPC buildscript fails because it expects to be able to call a downloaded binary from `node_modules`
- building `nseventmonitor` fails when running `npm install`
- probably some other electron quirk
