### ISSUE TITLE
Laptop Reboots on high disk usage.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#116484]
I am largely tracking this for the help of anyone else who runs into this and a place to keep my debugging notes. This occured quite reliably while downloading Google Takeout archives at 50MiB/s. The chance of occurance could be increased by running baobab at the same time.

Eventually my GNOME 3 desktop would lock up, then the system would reboot a couple of minutes later. Looking at `journalctl -b -1` reveals nothing. It appears that the logs leading up to the reboot could not be flushed to disk. The shutdown appears to be unclean because ext4 has some cleanup to do on boot.

Current questions:

- [ ] What is triggering the reboot?
- [ ] Is there a way to ensure that logs are flushed to disk before the reboot?

**Comment by kevincox** [comment]
Tangentially related: Mutter/GNOME Shell seems to lock up when there is a lot of disk usage. I wouldn't expect that Mutter touched the disk at all but there is a very strong correlation, I need to report that upstream.

**Comment by kevincox** [comment]
I had it occur again. I was only downloading on archive in parallel so it was only running at about 30MiB/s. My screen froze at 19:18 and the system rebooted at 19:25.

**Comment by kevincox** [comment]
The last log message is from 19:18:34. So maybe the hardware is bugging out. Unless there was such a priority issue that nothing was being written for 7 minutes.

**Comment by Melkor333** [comment]
I would recommend you to make a backup to an external disk as soon as possible as I assume that you have a broken disk!

When a disk goes bad the system can start to act in very weird ways. And worst of all, the smart status can say everything's OK. We had such a bad disk on one of our development servers with proxmox installed and it took us quite some time to figure out that one disk went bad. What happened was that at random points our virtual machines started going very slow and after a moment everything locked up completely. The disk was only used for the vms but we weren't able to access the host system some times. We only figured out it was the disk because we found out that the so called "disk wait time" went up like crazy (instead of the absolute maximum of like 400ms it went to multiple seconds).

To answer your questions:
- We didn't get automatic reboots on our server but this is usually caused by some kind of BIOS Watchdog (which we deactivate on our servers for some reason). Automatic reboot is also a small indicator that the power supply could be the problem (more below)
- If my assumption is right and the disk is the problem then I guess there's no way to get the logs onto the disk. What could help is if you send the logs to another device by setting up logstash or something like that.

Another possibility is a bad Power Supply. Power Supply and Disk are typically the first things that break on a device and a bad power supply can cause extremely strange issues. But in my experiences a screen freeze seems not typical for a power supply problem.

**Comment by kevincox** [comment]
I have everything backed up and am waiting on a new computer to arrive so I'm not too worried about the disk going bad. It is definitely good to keep that as  the first response though.

I appear to have hardware watchdogs `/dev/watchdog` and `/dev/watchdog1` (not 100% about the name of the second one) but systemd isn't configured to use them so I wouldn't expect that they are causing the reboots.

In my case it seems like generally the disk does eventually accept the writes, so in this case I think it would be best if it didn't reboot. I'm pretty sure the screen lockups are just caused by GNOME Shell blocking on the disk for some reason. I've had cases where I was playing a video and the audio continued for a very significant length of time even though the display was frozen.

**Comment by kevincox** [comment]
I'm going to close this as unless I can get some later logs off I will have a hard time identifying what is killing the machine. I tried the "none" scheduler which seemed to keep it usable longer but it still got rebooted in the end.
