### ISSUE TITLE
Add Git 2.31.0 maintenance support

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#116512]
## Issue description

Git version `2.31.0` has a new feature called [maintenance](https://github.blog/2021-03-15-highlights-from-git-2-31/#introducing-git-maintenance). Add a Nix module that starts a systemd service that run `git maintenance ...` on configured repositories.

## Technical details
- [Git maintenance doc](https://git-scm.com/docs/git-maintenance)

**Comment by primeos** [comment]
I feel like I have to ask the obvious question: Do we really need a Nix module for that?

From the GitHub blog:
> …and, you’re stuck. Now you’ve got to wait for Git to finish running git gc --auto before you can get back to work.

I don't remember this being a problem on Linux because it runs on the background and `man git-gc` confirms this:
> gc.autoDetach
> Make git gc --auto return immediately and run in background if the system supports it. Default is true.

This is the behaviour that I'm used to.

git-maintenance can still be useful (e.g. pre-fetching) but I wonder how many users actually need or even want that.
IMO the main problem is that git-maintenance seems to rely on cron (s. https://git-scm.com/docs/git-maintenance#_background_maintenance_on_posix_systems) so it shouldn't work on NixOS as intended (unless there is a fallback for systemd user timers). So IMO we certainly shouldn't implement more than a systemd timer that uses `maintenance.repo` so that `git maintenance start`, etc. work as usual (and it seems even better to wait until upstream supports this). Just my opinion though.

**Comment by SuperSandro2000** [comment]
> I don't remember this being a problem on Linux

I often get problems with it because I open too fast lived shells in nixpkgs-review, the gc --auto stops and creates a log file which stops it forever.

**Comment by primeos** [comment]
@SuperSandro2000 that's a different issue though, that comment was regarding git-gc blocking the shell instead of forking to the background. I assume you're running into (something like) this:
```
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove $DIR/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: reflog of 'HEAD' references pruned commits
warning: There are too many unreachable loose objects; run 'git prune' to remove them.
```

Not sure if git-maintenance would solve that as well (it might/should avoid the too many loose objects problem, at least if it packs them more often than the `gc.auto` default, but the unreachable objects count still depend on settings like `gc.pruneExpire`, `gc.worktreePruneExpire`, and `gc.reflogExpireUnreachable`).

**Comment by rhoriguchi** [comment]
> git-maintenance can still be useful (e.g. pre-fetching) but I wonder how many users actually need or even want that.

It seems really convenient when you work a lot on public transportation or your internet is not that great and you have the latest change already fetched, which in theory should speed up `git pull` since no or very few objects need to be transferred.

**Comment by shanesveller** [comment]
There is upstream systemd support now, though I don't know when it was introduced:

https://git-scm.com/docs/git-maintenance#_background_maintenance_on_linux_systemd_systems

**Comment by SuperSandro2000** [comment]
I think that was there since the beginning or very early on.

**Comment by ck3d** [comment]
This issue can be closed. I tested successfully git maintenance on nixos-23.11 with git 2.42.0
