### ISSUE TITLE
long boot time on NixOS 15.09

### ISSUE THREAD

**Issue by sorokin** [NixOS/nixpkgs#11650]
I have updated to NixOS 15.09. My current revision is f7006cd23bdfafa89538032d27b959fbac256cb4, but I use kernel 3.14 because of #9133.

The first thing I noticed is a very long boot time. On my laptop it takes 13 seconds (measured with stopwatch) from selecting boot configuration to seeing the full screen of text where first line is a message "early console in decompress kernel". After that the loading is almost instantaneous.

Also the loading process is quite ugly: the font is changing in the middle of the boot process (bold letters become lighter), screen resolution is changing.

I thought that probably splash image is a problem and I disabled it "boot.loader.grub.splashImage = null;". It turned out this is not the case. Boot time is the same and now I see black screen for the same 13 seconds.

Can I speed up boot process somehow? What is happening before the message "early console in decompress kernel" appears?

Can I prevent it from changing a font in the middle of boot process?

**Comment by sorokin** [comment]
I tried selecting GRUB 1 as a boot loader. But nixos-rebuild reported a few SIGSEGVs. I haven't tried booting with GRUB 1 after that.

``
/nix/store/r8q3b5n574578sw6jbp2m85i9hjjallz-grub-0.97-patch-1.12/sbin/grub-install: line 337: 15936 Segmentation fault      $grub_shell --batch $no_floppy --device-map=$device_map  > $log_file <<EOF
quit
EOF

/nix/store/r8q3b5n574578sw6jbp2m85i9hjjallz-grub-0.97-patch-1.12/sbin/grub-install: line 411: 16006 Segmentation fault      $grub_shell --batch $no_floppy --device-map=$device_map  > $log_file <<EOF
dump ${root_drive}${tmp} ${img_file}
quit
EOF

cmp: /tmp/grub-install.img.15930: No such file or directory
/nix/store/r8q3b5n574578sw6jbp2m85i9hjjallz-grub-0.97-patch-1.12/sbin/grub-install: line 411: 16011 Segmentation fault      $grub_shell --batch $no_floppy --device-map=$device_map  > $log_file <<EOF
dump ${root_drive}${tmp} ${img_file}
quit
EOF

cmp: /tmp/grub-install.img.15930: No such file or directory
/nix/store/r8q3b5n574578sw6jbp2m85i9hjjallz-grub-0.97-patch-1.12/sbin/grub-install: line 411: 16016 Segmentation fault      $grub_shell --batch $no_floppy --device-map=$device_map  > $log_file <<EOF
dump ${root_drive}${tmp} ${img_file}
quit
EOF
``

**Comment by vcunat** [comment]
`boot.loader.grub.*` should only affect the phase around selection of the config, and after that it should be under control of others. grub-1 might be broken; even Hydra tests for that are failing consistently IIRC.

Startup-time splashing is typically handled by `plymouth` in distros, but we've never had support for that in NixOS, I believe. Console resolution typically changes due to kernel mode setting starting up, and you can select your preferred font in `configuration.nix`. 13 seconds seems fine to me, but it's personal and I rarely boot (I use suspend to RAM or HDD instead).

**Comment by dezgeg** [comment]
Do you happen to have `/boot` on an XFS filesystem by any chance? I have one machine which takes extremely long in GRUB and I've once seen it spam tons of XFS-related messages before the kernel. (The hardware is an old, crappy netbook though, so it could be a firmware/BIOS related things as well...)

**Comment by sorokin** [comment]
@dezgeg Yes. I have XFS as my / and /boot is on the same partition.

**Comment by dezgeg** [comment]
Ok, most likely it's a XFS-specific regression in GRUB then. It hasn't always been like this, although for quite a long time (even before 15.09 release IIRC).

**Comment by Profpatsch** [comment]
(triage) still a problem @sorokin?

**Comment by dezgeg** [comment]
I still issue the problem. Trying newest grub (#22923) didn't help. I will try to investigate more.

**Comment by dezgeg** [comment]
I had a "fun" evening playing around with `grub-fstest`.

It turns out that pathname lookups in GRUB are simply `O(n)` lookups in the directory, without any use of e.g. the B-trees in XFS or the hash trees in ext4. But what's worse, on XFS the abstracted "list directory" operation also unconditionally reads the inode referred by the directory entry from disk to determine whether it's a directory or a regular file. (Unlike ext4, where that info is additionally stored in the directory entry itself).

Doing that twice (loading both kernel & initrd) on a `/nix/store` with 170 000 files took 17 minutes on spinning rust.

After setting `boot.loader.grub.copyKernels = true;` the booting is instant.

/me weeps
