### ISSUE TITLE
The zip package is built without unicode support

### ISSUE THREAD

**Issue by glaebhoerl** [NixOS/nixpkgs#11704]
Paths with an 'ő' character in them are truncated, and if I run it with `--unicode UTF8`, it reports that this option is not available.

I would be happy to contribute a patch, if I can, but I would like someone to walk me through the process -- chiefly how to build the package, experiment, and test my changes. I tried following https://nixos.org/wiki/Create_and_debug_nix_packages, but after the point where I've opened a development shell for the `zip` package, when I tried running the various build phases as described, they didn't work as-is, rather I needed to manually `cd` into directories, `chmod +x configure`, and `checkPhase` didn't work any way I tried, which makes me suspect I must've been doing something wrong.

(cc @spacefrogg)

**Comment by spacefrogg** [comment]
The changes were rather intricate, which is why I made them myself, see PR https://github.com/NixOS/nixpkgs/pull/11736.

You could also read up on packaging in the [Nixpkgs Manual](https://nixos.org/nixpkgs/manual/). It is normal that you have to change to the build directory after the `unpackPhase`, maybe this should be expressed more clearly somewhere. The other phases did not properly work, because the `configurePhase` isn't used, and the `buildPhase` was broken, which I fixed now. The `installPhase` didn't behave as you expected, because the build environment calculates where to put the build in the `/nix/store`. You cannot normally write into it, only the build daemon can. Within your `nix-shell` do the following:
```
[nix-shell: ~/foo]$ export out=some/path/you/can/write/to
[nix-shell: ~/foo]$ export prefix=$out
```
This should redirect installing the built files for most of the cases. `typeset` in the nix-shell should tell you why my changes did the trick.

Other steps I did to fix the problem: I found out, by reading the configure script, that it should not be normally called by itself but from the Makefile. This is why the `configurePhase` isn't used, it's all done in the `buildPhase`. By fixing the `buildPhase` the zip package calls configure and finds out that it properly supports unicode and large files. N.B. I also read the gentoo ebuild of zip, as I knew it worked there, which gave me some other hints on how to build zip.

**Comment by vcunat** [comment]
The PR got merged, so this should be fixed now.

**Comment by glaebhoerl** [comment]
@spacefrogg Thanks! This might've been related to some of the anamolies I experienced as well, e.g. when running the configure script it reported that unicode is not supported, but when building its test file myself manually it worked fine...
