### ISSUE TITLE
Get @wkennington contributing to nixpkgs again

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11765]
Seems like losing @wkennington's contributions is a pretty big loss for the project and that we should brainstorm how we can align the community's goals with his again :smile: 

cc @edolstra and possibly others that I don't know yet

Feel free to close if this seems like the wrong place to address it, but I wanted to get this out there.

**Comment by vcunat** [comment]
:-D You seem to be caring for "PR".

I would certainly be interested in the reasons why he's "left", but perhaps it's just a temporary pause.

**Comment by jagajaga** [comment]
:+1:

**Comment by peti** [comment]
I totally sympathize with the intention behind this "issue". However, this ticket doesn't feel like something that's actionable for anyone (except, possibly, @wkennington). I have no idea why William stopped to contribute, therefore I don't see what I could possibly do to help remedy and close this ticket. My guess is that virtually everyone else will be in the same situation. Therefore, I'd very much prefer to frame this discussion in the context of a concrete patch, a concrete change request, etc. If there is any particular patch that @wkennington wants merged to Nixpkgs, then the proper way to approach that is to open a pull request and ask for feedback. Given a concrete request, I'm sure we can figure out ways to compromise and merge the patch so that everybody is kind-of happy.

I'd also be hugely in favor of having a conversation with William about his perception, i.e. it would be great if he could write a mailing list posting that says, basically: "I don't want to contribute any more for reasons X, Y, and Z." Then we would try to figure out what went wrong and channel those insights into other, actionable tickets.

This particular ticket, however, I'd rather see closed ... and I'll be pro-active about it. If anyone feels that this issue should be re-opened, please go ahead and re-open it -- I don't feel strongly about it.

**Comment by jagajaga** [comment]
:crying_cat_face:

**Comment by copumpkin** [comment]
My main goal with putting this here is that it's a high-traffic place to draw attention to an issue I consider deserving of attention. It's definitely not the best place, but I also don't see the mailing list as particularly good either. He said he might post something to the mailing list, but in the absence of that, I don't think the pushing remedy forward should fall on him by default.

Not really sure what to do, but I do understand that this isn't a traditional GitHub "issue" :smile:
