### ISSUE TITLE
haskellPackage.stack ghci linking fails with missing symbol _dl_fatal_printf

### ISSUE THREAD

**Issue by larsr** [NixOS/nixpkgs#118693]
**Describe the bug**

I create a minimal nix-shell with just haskellPackage.stack in it in a completely fresh ubuntu and try to run `stack ghci` (i.e. start a haskell repl) and it fails with 

```
GHCi, version 8.10.4: https://www.haskell.org/ghc/  :? for help
<command line>: /nix/store/0qrayfgw779phhbasnrynvyakpczwdkb-glibc-2.32-39/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```

**To Reproduce**

    nix-shell -p haskellPackages.stack --pure --command "stack ghci"`

outputs

```
Configuring GHCi with the following packages:
GHCi, version 8.10.4: https://www.haskell.org/ghc/  :? for help
<command line>: /nix/store/0qrayfgw779phhbasnrynvyakpczwdkb-glibc-2.32-39/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```

**Expected behavior**

I expect a prompt that says `Prelude>` but instead the command fails with the above error message.

**Additional context**

It worked when I cloned this repository and checked out the tag `20.09`.

I'm trying this out in a fresh Docker instance built with these commands

```
# docker run --rm --name ubuntu -ti ubuntu

apt update; apt install -y  curl xz-utils sudo
echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
adduser --gecos "" --disabled-password  --ingroup sudo user
su -l user

sh <(curl -L https://nixos.org/nix/install)
exec bash -l
# this fails
nix-shell -p haskellPackages.stack --pure --command "stack ghci"

sudo apt install -y git
git clone -b 20.09 --depth 1 https://github.com/NixOS/nixpkgs.git
echo > test.nix 'with (import ./nixpkgs {}).pkgs; stdenv.mkDerivation {name="env";buildInputs=[haskellPackages.stack];}'
# this works
nix-shell test.nix --pure --command "stack ghci"
```

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
user@2d25eec20f8d:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-53-generic, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(user): `"nixpkgs-21.05pre280420.bc0144e5c9b"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:  haskellPackages.stack
```

**Comment by larsr** [comment]
By searching through the .so files that `ldd` lists and using `nm` to list which symbols are referenced and defined in the .so files, I find that the missing symbol is referenced from

    /nix/store/1jn6apz0fa9h9x7rl3v6vwiymwnjznwv-glibc-2.32-40/lib/libc.so.6
                 U _dl_fatal_printf@@GLIBC_PRIVATE

A similar symbol, without @GLIBC_PRIVATE is defined in 

```
/nix/store/1jn6apz0fa9h9x7rl3v6vwiymwnjznwv-glibc-2.32-40/lib64/ld-linux-x86-64.so.2
0000000000010af0 T _dl_fatal_printf
```

**Comment by larsr** [comment]
@veprbl I'm not convinced this is a haskell bug.  It seems more related to how libc is built, don't you think? Can you help me add/find the right tag to add to alert the right people?  Thanks!

**Comment by veprbl** [comment]
cc @Ma27

**Comment by cdepillabout** [comment]
There are a couple things here:

- If you want to use `stack` from Nixpkgs, I'd generally suggest you use the `--nix` flag with `stack`.  The command `nix-shell -p haskellPackages.stack --pure --command "stack --nix ghci"` works for me in the docker setup as described above.
- `stack --nix` internally runs `nix-shell`.  You can confirm this by running `stack --nix --verbose ghci`.  In general, you don't want to run `stack` within `nix-shell`, but you let `stack` internally execute `nix-shell`.
- Because you don't explicitly call `stack` from within a `nix-shell`, you generally install `stack` globally.  In your example above, you could do something like `nix-env -iA nixpkgs.stack`.
- If you've installed stack globally from Nixpkgs (with `nix-env`?), then running `stack --nix ghci` should work.  In this scenario, `stack` will download `ghc` from Nixpkgs.  This is generally what you'd expect?  Without the `--nix` flag, `stack` _won't_ download GHC from Nixpkgs, but instead download a GHC binary that is compatible with Ubuntu.
- If you really _actually_ don't want to have stack pull GHC from Nixpkgs (which means that you shouldn't use the `--nix` flag), then I'd suggest not getting stack from Nixpkgs, but just downloading a binary of `stack` compatible with Ubuntu.

-------------------------------------------------

As for the actual problem you're seeing, here is what I think happened:

You ran `stack ghci` (note without `--nix`) from within a `nix-shell`.  This causes `stack` to download an Ubuntu-compatible GHC binary, and try to install it.  However, `nix-shell` sets various environment variables, causing this process to not work correctly.

Instead, if you were to install `stack` from Nixpkgs globally (with `nix-env`?), and run `stack ghci`, then `stack` would still download an Ubuntu-compatible GHC and try to install it.  You wouldn't be running in a `nix-shell` at this point, so Stack's GHC installation process would run correctly.  `stack ghci` would work fine.  (I actually tried this locally and it seemed to work.  Although be aware that you might have to blow away `~/.stack` if it gets in a weird state.)

**Comment by larsr** [comment]
Thanks for the detailed comment! 

So, since `stack` pulls down compiled binaries that don't play well with `nix`, one should run `stack` with the `--nix` flag.  Thx!
