### ISSUE TITLE
sway (1.6) / wlroots (0.13.0) broke screen sharing and gnome3 pinentry popups

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#119445]
**Describe the bug**
The recent update of sway and wlroots seems to have broken screen sharing as well as gnome3 pinentry popups.

**To Reproduce**

I've built a system on 311ceed827f531f88f46222920cd1ebb2c101f73 (current nixos-unstable, there neither of the mentioned things works).

But if I build a system on 04a2b269d8921505a2969fc9ec25c1f517f2b307 (previous unstable, there both of the mentioned things works.).

I've then checked out 04a2b269d8921505a2969fc9ec25c1f517f2b307 and copied the folders `pkgs/development/libraries/wlroots/` and `pkgs/applications/window-managers/sway/` from master into my checkout and built a system based on the old unstable but with only those two packages updated. Then it's still broken. So it's at least isolated to those two packages.

**Expected behavior**
I expect screen sharing to work.

I also expect to be able to unlock my security key from places where the ncurses interface doesn't work (like within Emacs).

**Additional context**
Here's my complete sway setup: https://github.com/etu/nixconfig/blob/main/modules/my-sway.nix#L465-L516

**Notify maintainers**
cc @primeos @Synthetica9 @Ma27 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.9, NixOS, 21.05.git.04a2b269d89M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nix/nixos-unstable`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sway wlroots
# a list of nixos modules affected by the problem
module:
```

**Comment by Ma27** [comment]
Related: #112914.

**Comment by primeos** [comment]
I can confirm the gnome3 pinentry (`gcr-prompter`) issue (wasn't aware of it but can reproduce it).

I'm not using screen sharing on Wayland (yet) so unfortunately I cannot have a look into that.
cc @minijackson (`xdg-desktop-portal-wlr`): FYI, in case you use Sway and can reproduce this.

**Comment by jakobrs** [comment]
`xdg-desktop-portal-wlr.service` fails to start for me on nixos-unstable; presumably this is why screen sharing doesn't work. This appears in `journalctl`:

```
Apr 14 20:02:20 girafarig systemd[1244]: Starting Portal service (wlroots implementation)...
Apr 14 20:02:20 girafarig xdg-desktop-portal-wlr[1363]: 2021/04/14 20:02:20 [ERROR] - wayland: failed to connect to display
Apr 14 20:02:20 girafarig systemd[1244]: xdg-desktop-portal-wlr.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 20:02:20 girafarig systemd[1244]: xdg-desktop-portal-wlr.service: Failed with result 'exit-code'.
Apr 14 20:02:20 girafarig systemd[1244]: Failed to start Portal service (wlroots implementation).
```

**Comment by etu** [comment]
@jakobrs I've have the same errors on latest unstable, may be related to `$WAYLAND_DISPLAY` as @primeos mentioned.

**Comment by etu** [comment]
I've just noticed that on sway 1.6 my firefox launches in XWayland and not in Wayland mode.

Something seems to be very fishy with how environment variables are handled here.

**Comment by primeos** [comment]
Ok, so I've had a closer look at this and all of my issues where surprisingly related to the `$WAYLAND_DISPLAY` change.

I've executed `dbus-update-activation-environment WAYLAND_DISPLAY` and now the Gnome3 Pinentry (`gcr-prompter`) works again. I guess that should fix the screen sharing issues too.

There are two things that surprised me:
1) I'd assume some of you did reboot and in my case `dbus-deamon` should've had the correct `WAYLAND_DISPLAY` due to our `dbus-run-session` (which should've caused my `dbus-daemon` to be "restarted" as well)
2) My systemd unit for swaylock uses neither D-Bus nor does it hard-code `WAYLAND_DISPLAY`

So I wondered where the `wayland-0` comes from so I had a quick look at the Wayland source-code and, indeed, it's the default if `$WAYLAND_DISPLAY` isn't set: https://gitlab.freedesktop.org/wayland/wayland/-/blob/1.19.0/src/wayland-client.c#L969

So it seems like Sway's `WAYLAND_DISPLAY` change is much more severe than I though and causes (all of) these regressions (but the change makes sense as this reveals that it was basically always "broken" as it worked with a default value instead of properly via `WAYLAND_DISPLAY`).

For a quick fix it should be enough to add `exec dbus-update-activation-environment WAYLAND_DISPLAY` to your `~/.config/sway/config` (I already had `exec systemctl --user import-environment WAYLAND_DISPLAY DISPLAY DBUS_SESSION_BUS_ADDRESS SWAYSOCK` in there, which is useful as well). However, to fix this properly we need to find a nice solution for Nixpkgs.
