### ISSUE TITLE
put the different ansible versions in the python-packages set.

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#119609]
**Describe the bug**
I was trying to create an ansible environment with ansible 2.10 and I was expecting the different versions to be in python-packages.nix while the ansible different versions are created somewhere else 
```
  inherit (callPackage ../tools/admin/ansible { })
    ansible
    ansible_2_8
    ansible_2_9
    ansible_2_10;
```
by overriding the default python3Packages.ansible

It makes the creation of python environment harder with a non-default ansible harder and doesn't seem to be a good practice.

**Comment by FRidh** [comment]
Yes and no. Applications are typically outside of the package set. One reason for this is because they should have the possibility to have different dependencies. With Python libraries that is not possible at all, or we would end up with an inconsistent set resulting in collisions.

Do you need to be able to import ansible modules?

**Comment by teto** [comment]
ansible may need some libraries to work at all (for instance in my case, the kubernetes module requires openshift which I packaged but haven't upstreamed yet).
