### ISSUE TITLE
Sometimes nix-env is slow and use a lot of memory ~500(RES).

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#12019]
Sometimes some operations in the nix-env command use a lot of memory and it's slow.
For example: nix-env -qa '.*keep.*' uses about 500M of RES memory.
If I run again then it's executed fast.   

I did't meet such problem In the other package managers: apt-get, yum, equo.

**Comment by vcunat** [comment]
That's because nix uses a different approach. Using nix-env without specifying attribute name (-A) requires it to evaluate all top-level packages and inspect whether they match or not. So far there's no cache or database for these in vanilla nixpkgs. IIRC [nox](https://github.com/madjar/nox) offers a cached variant.

BTW, this issue would belong to the nix repository, so I'm closing anyway.
