### ISSUE TITLE
Sublime Text tries to use /bin/bash when executing commands for build systems

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#12011]
See line 66 of `exec.py` in `/nix/store/*-sublimetext3-3083-bin/Packages/Default.sublime-package`

I assume this applies to any shell command, not just those for build systems, but building is where it's particularly noticeable.

`Default.sublime-package` is a zip file, so it will need to be unpacked, patched and repacked.

**Comment by neilmayhew** [comment]
The following changes work well for me when I use them in `~/.config/sublime-text-3/Packages/Default/exec.py`. Maybe this could be used as the patch file.

[exec.py.diff.txt](https://github.com/NixOS/nixpkgs/files/75043/exec.py.diff.txt)

**Comment by wmertens** [comment]
I agree, that patch looks good. Should be pretty easy to apply to the Sublime build. Any takers?


On phone, sorry for brevity…

**Comment by mogria** [comment]
I tried to fix this in on my repo with this commit https://github.com/mogria/nixpkgs/commit/8f6b30281569a411b40e30d00df33b17bc16d758
(branch https://github.com/mogria/nixpkgs/commits/sublime3-fix-hardcoded-bash)

The derivation builds successfully and replaces the instances of `/bin/bash with` `/usr/bin/env bash`. I opted to use substituteInPlace instead of a patch, because it didn't apply.

Now when I start a build with a simple Makefile like this:
```
all:
	touch made

clean:
	rm made
```

The following error appears in the Sublime-Text console:
```
/usr/bin/env: relocation error: /nix/store/68sa3m89shpfaqq1b9xp5p1360vqhwx6-glibc-2.25/lib/libdl.so.2: symbol _dl_catch_error, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

**Comment by yorickvP** [comment]
That sounds like it's trying to link to the wrong libc somehow.
I would suggest using a direct path to a bash from the nix store (${bash}/bin/bash I suppose) in case it tries to exec it directly. I'm not sure how to debug the new error, `strace` might sound like a good idea.

**Comment by calvertvl** [comment]
@Mic92, @globin: This change was cherry-picked to 17.03 but not 16.09; it looks to me like it would not have any conflicts.

As it is a bug, it should probably be cherry-picked to 16.09, followed by closing this issue.
