### ISSUE TITLE
Transparent VM-based cross-platform evaluation of nixpkgs

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12039]
This might be infeasible, but that's what the "feedback requested" field is for, right? :sweat_smile: 

Currently, all-packages.nix is a function accepting a `system` parameter. There's a whole system of `crossSystem` that I'm not touching right now, as I don't think this proposal affects any of it.

Basically, we have `libvirt` running on our two major platforms, Linux and Darwin. `qemu` doesn't work usefully on Darwin, which is why I'm trying to stay more generic, but we do have `xhyve` which works fine and should be pluggable into `libvirt`.

Could we just have a simple system that semi-transparently spins up a `libvirt` VM if you attempt to evaluate `nixpkgs` on a system other than your own? For example, we could have an attrset that provides VM images for a minimal NixOS distro, another one that can build a minimal Mac OS image (assuming you manually add the base image to the store, to avoid licensing issues, and run it on Mac hardware, which is legal and permitted). That way, I can ask my Mac-running-NixOS to build/test/run Darwin packages and ask my Mac-running-OSX to build Linux packages for me (for e.g., NixOps deployments). We could conceivably also use it to handle Windows builds, but I don't care about those as much right now. The builds would all end up in the host store and everything would otherwise be seamless. 

We'd basically be doing a deterministic Nix-flavored Vagrant and using it transparently. We could even expose that to the user!

It doesn't seem like we're that far off right now. `runInLinuxVM` is pretty close, but would just need to be generalized a bit, and plugged into the evaluation of `nixpkgs`.

Edit: TBC, if I were to make this into a concrete proposal, it would be:
- Generalize `runInLinuxVM` to use `libvirt` (or call it something else) and work on both Darwin and Linux. Would need to make sure it could share the host store.
- Keep a handful of minimal VM definitions around for it to run for different `system` values
- Add a shim to all-packages.nix that would call `runInLinuxVM`
- Make sure none of this produces different hashes than it would on the native platform

**Comment by copumpkin** [comment]
@shlevy says this is probably better suited to a build hook, which makes this all look a bit more like the idea I think @nbp mentioned to me back at NixCon. I'd support that, too, if it could lead to similar outcomes :grinning:

**Comment by nbp** [comment]
The build hook mechanism already exists and is made for distributing builds to computers which already have a nix-daemon running.

The question of cross-compilation is a bit harder, and would require a way to register in the `nix.conf` file, a reference to an emulation platform, whether this is `libvirt` or `qemu`.

Basically, the cross-compilation problem can be separated in 3 stages:

1. Cross-compile on the current environment.
2. Cross-compile on a managed environment.
3. Compile on a remote computer.

(1) is extremely hard, mostly because none of the packages get it right, or they never considered it.
(2) is difficult, as it requires to manage another build environment, and to bridge the operations necessary for building.
(3) is easy as it is already implemented under the form of a build hook.

Currently we have a few packages with (1), and are able to distribute builds (3).  Sadly, so far we have no good solution for cross compiling the nix daemon yet (not 1), and if the targeted environment is not a capable of compiling (not 3), then we are left with a gap for doing cross-compilation.

I definitely think that we can add a `chroot-hook` to the Nix daemon, which can be used to manage an environment which will allow us to cross-compile.

Note, `runInLinuxVM` is nice, but as opposed to (2) and (3), the result of your compilation will get a different hash as the hash that you would expect to have if your were to build natively.  Which I why I would recommend to have a `chroot-hook` for some systems in the nix.conf, as this will allow us to blend cross-compiled builds in managed environment, as-if they were compiled natively.

**Comment by kevincox** [comment]
It might be nicer (although more difficult) to cross compile for MacOS using a Linux built GCC. Similar to using MingGW to compile for windows. Although I don't know about the state of this support (since GCC supports darwin I don't think it will be a problem) and you run into the problem of having a different "host compiler" and "target compiler".

From my understanding NixOS has some cross compilation support but I don't know how well that works.

**Comment by vcunat** [comment]
Standard cross-compilation works, but many packages need tweaks for particular platform combinations. For a couple of months I worked on linux -> mingw cross for some packages, and I think I saw some changes for linux -> darwin as well, but it might've rotten a bit...

**Comment by kevincox** [comment]
It might be worth supporting anyways however testing is generally pretty difficult. It also seems a lot more elegant then having to do it on Apple hardware and in a VM.

**Comment by vcunat** [comment]
Cross-compiling is more difficult, but the core autotools-based packages tend to handle that relatively well.

**Comment by Profpatsch** [comment]
@copumpkin with the work of @Ericson2314 this can be considered implemented, right?

**Comment by Ericson2314** [comment]
Cross works, but VM builds have a meaningfully different outcome in that normal binary caches can be used. I would thus keep this open.

**Comment by dezgeg** [comment]
We do have an implementation nowadays: https://github.com/nix-community/linuxkit-builder
