### ISSUE TITLE
postfix relies on /bin/sh being a symlink to bash

### ISSUE THREAD

**Issue by phunehehe** [NixOS/nixpkgs#12046]
[`postfix-script`](https://github.com/vdukhovni/postfix/blob/bbe8bc4/postfix/conf/postfix-script#L232) calls `post-install` using `/bin/sh` (non-official repo, but I couldn't find anything better to link to). In nixpkgs, [`post-install`](https://github.com/nixos/nixpkgs/blob/929e734/pkgs/servers/mail/postfix/3.0.nix#L49-L50) is a wrapper that uses bash.

When the wrapper is called using `/bin/sh` that is a symlink to bash (like in nixos), it works fine. However if it's not bash the wrapper will fail with "Bad substitution". I have only tested with dash on ubuntu, but the same thing should happen to a more vanilla sh too, because the wrapper uses bash' array syntax.

I'll try to submit a patch against postfix upstream to remove the use of `SHELL` (which looks inconsistent and unneeded anyway), but before a new release lands, does it make sense to have a patch in nixpkgs too?

**Comment by phunehehe** [comment]
for prosperity, here's the post in postfix mailing list https://groups.google.com/forum/#!topic/list.postfix.users/oSUlroqdi8w

**Comment by peti** [comment]
IMHO, it's fine to have the patch in Nixpkgs since it fixes a real problem for people who use Nix on a system that doesn't have `bash` at `/bin/sh`. I merged it a moment ago. It would be nice to have this fixed upstream of course -- also see my comments at https://github.com/NixOS/nixpkgs/pull/12047#issuecomment-168181653.
