### ISSUE TITLE
Clevis needs options for initrd

### ISSUE THREAD

**Issue by cerulis64** [NixOS/nixpkgs#121636]
**Project description**
From README.md:
> Clevis is a pluggable framework for automated decryption. It can be used to provide automated decryption of data or even automated unlocking of LUKS volumes.

Although there is a `clevis` package, it would be preferable to have an option to add it to the initrd for automated decryption of LUKS volumes before mounting the root.

**Metadata**

* homepage URL: [https://github.com/latchset/clevis](https://github.com/latchset/clevis)
* source URL: [https://github.com/latchset/clevis](https://github.com/latchset/clevis)
* license: gpl3
* platforms: linux

**Comment by nothingmuch** [comment]
I tried copying clevis and some of its dependencies into the initrd using the undocumented `boot.initrd.extraUtilsCommands` option, which I was already using for `havegd`.

`copy_bin_and_libs` works as expected on `${pkgs.jose}/bin/jose`, `bash` and `curl`, but i'm not sure what to do about the bash scripts that clevis itself is composed of. If I use that function on the scripts, they are `/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bash-5.1-p16/bin/bash` as an interpreter. I looked around I don't think the nixos stage 1 stuff has anything in place to support copying scripts, but I hope I just missed something.

Since the initrd has `/bin/` populated with things including `/bin/bash`, using the initrd ssh to try to run clevis I tried just symlinking directories for clevis, cat and bash just based on the errors i got from trying to run it. e.g.:

```sh
ln -s / /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bash-5.1-p16
```

By doing that was able to execute `/bin/bash /bin/clevis luks unlock -d /dev/disk/by-uuid/... -n nixos-root`, which successfully ran `cryptsetup open` on a device bound to a tang server on the local network. I did not try the `sss` backend yet, and this machine does not have a tpm, so I can't test that out (maybe under qemu?)

Unforuntately I was not able to convince the boot process to proceed after unlocking the device. In order to boot I must first run `cryptsetup close` and then run `cryptsetup-askpass` as I would normally, because `cryptsetup open` at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/luksroot.nix#L189 fails with e.g. `Device nixos-root already exists.` and therefore never breaks out of the loop.

I suppose the next step would be to patch `do_open_passphrase` so that it can break out of the password loop if the device gets unlocked independently of itself? Perhaps the `wait_target` function could be used to check if `/dev/mapper/${dev.name}` already exists? I might have a go at doing that in the next few days when I find more time for this.

After that in order to find a cleaner way to get the programs executable on the initrd, taking a closer look at these seems like a good idea:

- https://github.com/latchset/clevis/blob/master/src/luks/systemd/dracut/clevis/module-setup.sh.in
- https://github.com/latchset/clevis/blob/master/src/initramfs-tools/hooks/clevis.in

I'm personally interested in tang & sss providers from clevis, for tpm2 unlocking I would speculate that systemd is the likely path forward based on some ongoing efforts https://github.com/NixOS/nixpkgs/issues/139433#issuecomment-986187161, #134577, https://github.com/NixOS/nixpkgs/projects/51

**Comment by nothingmuch** [comment]
more or less working config:

```nix
boot.initrd.extraUtilsCommands = ''
    # clevis dependencies
    copy_bin_and_libs ${pkgs.curl}/bin/curl
    copy_bin_and_libs ${pkgs.bash}/bin/bash
    copy_bin_and_libs ${pkgs.jose}/bin/jose

    # clevis scripts and binaries
    for i in ${pkgs.clevis}/bin/* ${pkgs.clevis}/bin/.clevis-wrapped; do
      copy_bin_and_libs "$i"
    done
'';
```

```nix
boot.initrd.luks.devices.nixos-root = {
  device = "/dev/disk/by-uuid/${uuid}";
  preOpenCommands = ''
    # what would be a sensible way of automating this? at the very least the versions should not be hard coded
    ln -s ../.. /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-bash-5.1-p16
    ln -s ../.. /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-clevis-18
    ln -s ../.. /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-coreutils-9.0

    # this runs in the background so that /crypt-ramfs/device gets set up, which implies crypt-askpass
    # is ready to receive an input which it will write to /crypt-ramfs/passphrase.
    # for some reason writing that file directly does not seem to work, which is why the pipe is used.
    # the clevis_luks_unlock_device function is equivalent to the clevis-luks-pass command but avoid
    # needing to pass the slot argument.
    # using clevis-luks-unlock directly can successfully open the luks device but requires the name
    # argument to be passed and will not be detected by the stage-1 luks root stuff.
    bash -e -c 'while [ ! -f /crypt-ramfs/device ]; do sleep 1; done; . /bin/clevis-luks-common-functions; clevis_luks_unlock_device "$(cat /crypt-ramfs/device)" | cryptsetup-askpass' &
  '';
};
```

I'm running tang on another computer like this for testing with the keys set up in `/var/db/tang`, set up manually but based on the provided systemd unit files:

```sh
socat TCP4-LISTEN:8081 SYSTEM:"/nix/store/p4rs5d2w6y5zp4ax4ib2w82xgif73dss-tang-7/libexec/tangd /var/cache/tang";
```

To bind a keyslot, run this while tang is running:

```sh
clevis luks bind -d $DEV tang '{"url":"http://10.0.0.1:8081"}'
```

**Comment by fegies** [comment]
Thank you for your investigation efforts :) 

Regarding automating the versions in your script, you can refer to the package name from the derivation:

```nix
boot.initrd.luks.devices.nixos-root = {
  device = "/dev/disk/by-uuid/${uuid}";
  preOpenCommands = with pkgs; ''
    # what would be a sensible way of automating this? at the very least the versions should not be hard coded
    ln -s ../.. /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-${bash.name}
    ln -s ../.. /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-${clevis.name}
    ln -s ../.. /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-${coreutils.name}

       ...

  '';
};
```

Since clevis binding to the disk did not work for me, I instead opted to just encrypt the keyfile with tang and put it on the boot partition.
I have a complete nixos module that anyone who is interested can take a look at here:
https://github.com/fegies/nix-config/blob/master/src/tang-unlock.nix

**Comment by balintmaci** [comment]
I tried this without binding with clevis to see if I could still recover with the passphrase if the TPM doesn't unlock. What seems to happen is that I get prompted to enter the password, afterwords the output shows "success", then the bash command runs in an infinite loop, stopping the boot process. There must be a better way. Any ideas? @nothingmuch

**Comment by nothingmuch** [comment]
> There must be a better way. Any ideas? @nothingmuch

Incidentally just yesterday I started working on this again, I think the right approach is to extend cryptsetup-askpass itself so that it is aware of clevis.

BTW, tang also changed and now listens on port 9090 by default, so that the socat stuff is no longer required for testing.

**Comment by sedlund** [comment]
Still new to this.  Trying to make clevis work for me.  Using this for testing.  Hope someone finds it useful.

```nix
  virtualisation.oci-containers.containers = {
    tang = {
      image = "padhihomelab/tang";
      volumes = ["tangdb:/db"];
      ports = ["9090:8080"]; # expose on 9090
    };
  };
```

**Comment by joconcepts** [comment]
Does anyone know how to auto unlock a luks device on a mdraid which is not nix-root using clevis?

**Comment by usmcamp0811** [comment]
Any movement on this? I tried the above clevis initrd config but get stuck in a loop during boot. I can't see the example using a tang encrypted keyfile because it seems the repo doesn't exist any more.

**Comment by sedlund** [comment]
That PR made its way into nixos-unstable-small 
- https://nixpk.gs/pr-tracker.html?pr=257525

**Comment by gernotfeichter** [comment]
I am successfully using that since recently. As mentioned, it is in nixos-unstable currently.

Since it is not trivial how to configure this to get it running, I just hint at this comment right now: https://github.com/NixOS/nixpkgs/pull/257525#issuecomment-1869119413

I suggest we leave this issue open till an entry in the nixos manual is created.

I might find motivation to do that but I can not guarantee it.
