### ISSUE TITLE
Termite is deprecated

### ISSUE THREAD

**Issue by equirosa** [NixOS/nixpkgs#122929]
## Issue description

As per [this issue comment](https://github.com/thestinger/termite/issues/760#issuecomment-834305851) Termite is no longer developed/maintained and forks are discouraged. Wanted to mostly raise awareness about the issue, inclined towards the idea that it should be removed from nixpkgs.

That said, some comments on that same issue do mention the value of VTE-based terminal emulators, and how Termite in particular excels, so perhaps further discussion is warranted(?)

**Comment by samuela** [comment]
Is there a deprecated flag in `meta` like there is for `meta.broken`?

**Comment by equirosa** [comment]
I don't think so :thinking:

**Comment by buckley310** [comment]
There's probably no need to quickly react to this news, after all, the latest release was over 2 years ago. Perhaps it would be best to wait a few months to see if any community-maintained forks gain traction, and then flip it to that before the 21.11 branch, or remove it at that point?

**Comment by equirosa** [comment]
That's a good point, should I close this issue or leave it open for further discussion in November?

**Comment by jtojnar** [comment]
The package has been dead for years now and no prominent fork emerged so far. And while it is possible that the announcement might trigger something, even against its recommendations, I do not consider anything but life support forks likely.

But we actually already have [one such fork](https://github.com/NixOS/nixpkgs/pull/103704) right in Nixpkgs. As long as @JJJollyjim or someone else wants to fix the occasional incompatibilities with newer versions of VTE and no security vulnerability is found, there is not much to do.

We could keep this open in case a new upstream appears but again, that is unlikely to happen so I would just close this and do nothing until the package stops building or otherwise breaks.

**Comment by equirosa** [comment]
Oh! I wasn't aware of that. Fair enough, closing now :smile: .
