### ISSUE TITLE
Some certificate servers in chromium became untrusted

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#12298]
After the last --upgrade, on some sites with HTTPS (including google, google mail, youtube and many others), chromium says

SSL connection error
ERR_SSL_PROTOCOL_ERROR
Hide details
Unable to make a secure connection to the server. This may be a problem with the server, or it may be requiring a client authentication certificate that you don't have.

As i can see in "HTTP/SSL Manage certificates" settings,
some "Authorities" became "Untrusted" and
_all_ the "Servers" became "Untrusted" too.

All is ok in firefox.
% nixos-version 
15.09.897.aa2d714 (Dingo)

**Comment by heydojo** [comment]
Just to help the maintainers : Could you confirm that the version of chromium which you are running is 45.0.2454.93 and could you list a few of the untrusted sites.
The current stable version in the NixOS unstable tree is 47.0.2526.106 so the package might just need a version bump.

**Comment by comonoid** [comment]
Oh, sorry!
Version 45.0.2454.93 (64-bit)

**Comment by heydojo** [comment]
Yeah I can confirm that I do not see that error using chromium 47.0.2526.106. I have been using it for over a week now and seems very stable.
I am unsure if a backport to stable is trivial because there has been a bit of work going on with chromium in unstable since the last release judging by the commits.
I guess you could test by downloading :
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium
and building it in your user environment. That is until the version is bumped.
Of course the bug could be originating from one of it's dependencies also.
You will be able to determine if the chromium package itself is causing the issue by testing the new version however.

**Comment by comonoid** [comment]
Just upgraded.
Watching the newest chromium version — chromium-dev-47.0.2508.0
Begining to disappoint in "stable" channels...
Just switched to "unstable". 47.0.2526.106 is stable here.
And all works fine (except a few falls while switching).
I thought 47.0.2526.106 can be at least 'marked' as -dev while not version-bumped, but...
Think we may close this ticket?

**Comment by joepie91** [comment]
Issue occurs for me in `-dev` (`47.0.2508.0 (64-bit)`) and `-beta` (`46.0.2490.33 (64-bit)`) as well, on `15.09.911.53286a8 (Dingo)`.

**Comment by comonoid** [comment]
There is 47.0.2526.106 in unstable and 15.09 too.
Works (at least) for me in 15.09 and unstable.

**Comment by vcunat** [comment]
Right, it should be OK now with recent channel updates. Reopen otherwise.

**Comment by jbaum98** [comment]
This occurs for me even with the default GNOME Web browser, only for Google sites.

**Comment by comonoid** [comment]
With version ≥ 47.0.2526.106?

**Comment by vcunat** [comment]
@jbaum98: epiphany seems to have a different issue. I opened #12518.

**Comment by 0x4A6F** [comment]
chromium (47.0.2526.106 32-bit) and chromiumDev (49.0.2593.0 32-bit) does work on 15.09.
