### ISSUE TITLE
stderred

### ISSUE THREAD

**Issue by Scoder12** [NixOS/nixpkgs#123057]
**Project description**
Makes stderr red through LD_PRELOAD.

**Metadata**

* homepage URL: https://github.com/sickill/stderred
* source URL: https://github.com/sickill/stderred
* license: MIT
* platforms: unix, linux, darwin

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/80973

**Comment by Scoder12** [comment]
keep open

**Comment by YarekTyshchenko** [comment]
Any tips on how to actually use this?

**Comment by jtojnar** [comment]
Just like specified in the [README](https://github.com/ku1ik/stderred) – set `LD_PRELOAD="/absolute/path/to/stderred/build/libstderred.so` environment variable. You can get the path by running `nix-build -A stderred` in Nixpkgs directory and then appending `/lib/stderred.so` to it.

Only I would recommend against setting the variable globally (e.g. in shell config) since the effects of `LD_PRELOAD` on random programs are hard to anticipate.

**Comment by YarekTyshchenko** [comment]
The path, and the way to trigger it is sort of what I was after. I'd be happy with an extra shell script that wraps the env var, but looking to set that up declaratively. I will post an example when I get a chance

**Comment by jtojnar** [comment]
You can create `shell.nix` like the following:

```nix
let
  pkgs = import <nixpkgs> { };
in
pkgs.mkShell {
  env = {
    LD_PRELOAD = "${pkgs.stderred}/lib/libstderred.so";
  };
}
```
