### ISSUE TITLE
Document what releases we still support

### ISSUE THREAD

**Issue by womfoo** [NixOS/nixpkgs#12322]
I could not find references online if we still support 14.12 and older.

http://howoldis.herokuapp.com/ shows that there is recent movement for 14.12 (small).

| Channel | Updated | Tests |
| --- | --- | --- |
| nixos-13.10 | 540 days ago | Hydra |
| nixos-14.04-small | 328 days ago | Hydra |
| nixos-14.04 | 319 days ago | Hydra |
| nixos-14.12-small | 21 days ago | Hydra |
| nixos-14.12 | 105 days ago | Hydra |
| nixos-15.09-small | 1 days ago | Hydra |
| nixos-15.09 | 1 days ago | Hydra |
| nixos-unstable-small | 32 days ago | Hydra |
| nixos-unstable | 31 days ago | Hydra |
| nixpkgs-unstable | 4 days ago | Hydra |

**Comment by vcunat** [comment]
I registered no larger incentive to support 14.12 since after 15.09 was released, so it is *de facto* unsupported (including all older ones). On the [download page](http://nixos.org/nixos/download.html) I only see 15.09 mentioned, so I'd think that implies there are no "guarantees" about the state of other branches.

It might be better to mention the state explicitly somewhere, perhaps on that page &ndash; but you see &ndash; anyone could step up and start supporting them. It just hasn't happened.

**Comment by jgillich** [comment]
We should also document how long releases will be supported, even if it's just "supported until next stable release".

**Comment by vcunat** [comment]
Well, of course the current release is always supported at least until another one is announced. IIRC there was typically some small overlap (several weeks?).

It feels natural to me to say in the announcement for a new release that the previous one has only this much time of support planned and people are free to step up to maintain it longer. If one restricted just to significant security fixes, it wouldn't need much work to support another release, IMHO.

**Comment by domenkozar** [comment]
@womfoo it's written at https://nixos.org/releases/nixos/14.12/nixos-14.12.231.139ead2/manual/sec-upgrading.html, where else would you like to see this?

**Comment by peti** [comment]
This may sound silly, but what exactly does it mean for a NixOS release to be "supported"?

I suppose that every branch with an active Hydra jobset and an up-to-date binary cache is "supported" to some degree, no? People can open a pull request that changes `release-14.12`, and after a little while every user of that release will get updates. That's pretty decent support.

On the other hand, `release-14.12` is clearly not as well supported as `release-15.09` simply because the number of active NixOS developers running the latter release is much higher than the number of those developers who are running the former. So arguably bugs in 15.09 are more likely to be fixed than those in 14.12. But even so, that's a rather fuzzy metric.

Personally, I wouldn't use a vague term like "supported" in the manual (or elsewhere), and I believe we wisely don't do that.

**Comment by vcunat** [comment]
By "supported" I understand, for example, that committers try to remember and port any security fixes to it (and try not to break it at the same time).

**Comment by jgillich** [comment]
I would call a release supported when there are people dedicated to fixing bugs and security issues, and not just scratching their own itch. Most security updates are only going into 15.09, and bug fixes are often not back-ported at all, so we obviously don't have the same level of support that, for example, Debian has.

**Comment by womfoo** [comment]
I guess we can now close this up as @domenkozar pointed out that its documented in the manual. 

I have several friends wanting to try NixOS and security updates are usually one of their main concerns.

It would be nice though if we could say how often we release like the [ubuntu download page](http://www.ubuntu.com/download/desktop).

**Comment by Profpatsch** [comment]
> By "supported" I understand, for example, that committers try to remember and port any security fixes to it (and try not to break it at the same time).

Does that really happen? Until there is a dedicated team backporting at least (!) security patches we should cleanse the manual of the word “supported” imo.

**Comment by vcunat** [comment]
I don't know, but in my experience the committer to master typically has the most of information needed to port it to stable. (S)he might not have enough motivation, though, or even know that/whether (s)he should do it.

**Comment by joepie91** [comment]
Is there any update on this? I agree that this should probably be mentioned on [the download page](https://github.com/NixOS/nixos-homepage/blob/master/nixos/download.tt), but I'm not sure how other people feel about this.

**Comment by vcunat** [comment]
Release notes of recent releases state the lifetime &ndash; the promised part, as some updates may happen even after that, especially for critical security fixes.
