### ISSUE TITLE
Emacs does not find my home directory

### ISSUE THREAD

**Issue by fowlay** [NixOS/nixpkgs#12335]
After installing 'emacs' and launching 'emacs' a "warnings" buffer is shown, saying

Error (initialization): User xyz has no home directory

I am using Nix packages as single-user with a writable /nix/store. My channel is nixos-15.09. The Emacs version is reported as "GNU Emacs 24.5.2 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.28) of 2016-01-07 on localhost" when I do 'Alt-X emacs-version'. My host OS is Xubuntu 14.04.3 LTS.

There is nothing special with my home directory, it is /home/xyz and HOME is set in the environment.

**Comment by oxij** [comment]
Please, supply the outputs of at least

  env | grep HOME
  stat $HOME
  cat /etc/passwd | grep xyz

**Comment by Zimmi48** [comment]
Hello,
I'm having the same problem.
I run Ubuntu 15.10, I installed Nix in the standard way. I installed Emacs 24.5 using `nix-env -i emacs`. The output of the required commands is:
```
$ env | grep HOME
HOME=/home/invites/theo
$ stat $HOME
  Fichier : «/home/invites/theo»
   Taille : 4096      	Blocs : 8          Blocs d'E/S : 4096   répertoire
Périphérique : 802h/2050d	Inœud : 18481354    Liens : 58
Accès : (0755/drwxr-xr-x)  UID : (11309/    theo)   GID : (11100/pps-invites)
Accès : 2016-04-18 10:24:32.236603574 +0200
Modif. : 2016-04-18 10:24:12.808545332 +0200
Changt : 2016-04-18 10:24:12.808545332 +0200
  Créé : -
$ cat /etc/passwd | grep xyz
$
```

(sorry for the French)

I don't know if this has anything to do with that error but I have created some custom development environments and when I load one with `load-env-myenv` I can read:
 `myenv:[Je n'ai pas de nom !@mymachine:~]$`
("Je n'ai pas de nom !" is French for "I don't have a name!").

Many thanks in advance,
Théo

**Comment by Zimmi48** [comment]
Hello,

I was having the same problem and, following the advice here http://comments.gmane.org/gmane.linux.distributions.nixos/17480, I solved it by installing nscd:
`sudo apt-get install nscd`
Of course I presume that it's bad to install a dependency with another package manager and that the emacs package should be fixed instead but I don't know how to do that.

Thanks,
Théo

**Comment by peti** [comment]
Without a lot more (detailed) information, we cannot debug this issue.

**Comment by svetlyak40wt** [comment]
I have the same issue.
Here are some details:
```
[+|art@yd-dev:~/]% env | grep HOME
HOME=/home/art
[+|art@yd-dev:~/]% stat $HOME
  File: ‘/home/art’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d    Inode: 131093      Links: 11
Access: (0755/drwxr-xr-x)  Uid: (20364/     art)   Gid: (61119/dpt_bus_dev)
Access: 2016-06-06 15:16:32.271243888 +0300
Modify: 2016-06-06 15:21:57.166440970 +0300
Change: 2016-06-06 15:21:57.166440970 +0300
 Birth: -
[+|art@yd-dev:~/]% cat /etc/passwd | grep art
[+|art@yd-dev:~/]% echo $USER
art
[+|art@yd-dev:~/]% echo $LOGNAME
art
```

I know, our admins use some centralized authentication solution, that is why there isn't my login in the /etc/passwd.

**Comment by svetlyak40wt** [comment]
Please, reopen the Issue.

**Comment by svetlyak40wt** [comment]
BTW, installation of nscd really fixes the problem, but this is annoying.

**Comment by tadfisher** [comment]
(triage)

Similar issue with Guix on a Fedora host: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19780#115

The culprit is likely that your Emacs is linked against Nix' glibc, but is loading a libnss_sss.so linked to the system's glibc. Running nscd on the system works around this problem, and I'm not seeing an obvious way to fix this in the Nix package without resorting to LD_PRELOAD hacks.

**Comment by ashgillman** [comment]
I am also getting this issue w/ Nix installed on Ubuntu 16.04. I also am not in /etc/passwd, I am not sure exactly what out company uses for centralized auth. I have tried installing `nscd` with `apt-get` and `libnscd` with Nix, but neither seem to fix the issue.

**Comment by ashgillman** [comment]
Actually I managed to fix this just by adding a fake entry into /etc/passwd. I am not sure if this is a bad idea or not, but it also fixes similar issues with openssh (and git by extension).

**Comment by zyxue** [comment]
@svetlyak40wt 

> I know, our admins use some centralized authentication solution, that is why there isn't my login in the /etc/passwd.

Is this what's causing the problem? I am in exactly the same situation, no record found in my `/etc/passwd`

**Comment by catern** [comment]
Recently this can happen even without sssd if your /etc/passwd uses "compat" rather than "files". Change that to "files" and it will work.

**Comment by wizmer** [comment]
This is obviously not a solution but launching emacs with `emacs --user ""` makes the error message disappear.

**Comment by seirios** [comment]
I had the same issue, with no entry in `/etc/passwd` due to the way credentials are managed. After reading [this](https://emacs.stackexchange.com/questions/34022/error-initialization-user-has-no-home-directory), it seems that doing `emacs --user ""` is effectively a solution. This sets `init-file-user` to an empty string, allowing emacs to expand the correct path, instead of `$HOME/~user` which is obviously wrong.

**Comment by codemac** [comment]
This is not stale and still occurs.

**Comment by catern** [comment]
This is difficult to solve in Nix or Nixpkgs. It's a fundamental flaw in how glibc NSS lookups work - by dynamically loading plugins. The best solution is for the administrator of the machine to run nscd, which will be autodetected by any glibc version (even from Nix) and used to do NSS lookups via RPC to nscd, instead of dynamically loading plugins.

NixOS uses nscd in this way. IMO, that should be the policy of Nixpkgs: If you're using a non-NixOS distro, install nscd to solve this sort of user lookup issue.

Since that is a known solution, and since there isn't really any acceptable alternative (you could maybe figure out a way to modify Nixpkgs to include the sssd plugin in the glibc package, but that would require recompiling everything), I think this issue can be closed with nscd as the solution.

**Comment by fredcy** [comment]
I'm running into the same error message with the latest nix (installed today) on RHEL 7.9.  In my case installing ncsd is not an option as we use sssd (for LDAP authentication).  Is there any other workaround?

**Comment by bjornfor** [comment]
> Is there any other workaround?

https://github.com/NixOS/nix/issues/3356#issuecomment-917416118

**Comment by fredcy** [comment]
> > Is there any other workaround?
> 
> [NixOS/nix#3356 (comment)](https://github.com/NixOS/nix/issues/3356#issuecomment-917416118)

Thanks. Based on that I was able to get around the problem by invoking emacs this way:

```
nix-shell -p emacs29-nox
LD_LIBRARY_PATH=/nix/store/b5rb6fjjx73n5yg0jin9kcr3hkg5599z-sssd-2.9.3/lib emacs
```

I'm new to nix and couldn't get nix-build to work for sssd (no default.nix), so I just ran `nix-shell -p sssd` to get it to build the package as side effect.  I did the same for nss_ldap, but it turned out to be unnecessary.

I am puzzed that, without LD_LIBRARY_PATH, lsof does not show the emacs process using any any sssd library. With it, I see it using /nix/store/b5rb6fjjx73n5yg0jin9kcr3hkg5599z-sssd-2.9.3/lib/libnss_sss.so.2

**Comment by fredcy** [comment]
My LD_LIBRARY_PATH hack just above has the bad side-effect of hosing up user id lookup in subshells run from emacs.

**Comment by kastl-ars** [comment]
This hit me today using the same emacs configuration via home-manager on two openSUSE laptops, where one has the user from LDAP via sssd. This is the one having issues, the other (with the local one) works fine.

I'll try the `--user ""` workaround.
