### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#12345]
NixOS should detect (if possible) a high-resolution "retina" displays and scale the output that it looks good and is readable.

Other Distros and Desktops are already working on it:

https://wiki.archlinux.org/index.php/HiDPI
https://blueprints.launchpad.net/elementaryos/+spec/hidpi-support
https://lwn.net/Articles/619784/
http://www.makeuseof.com/tag/linux-hidpi-support-for-gnome-kde-xfce-cinnamon-and-firefox/
https://bugzilla.mozilla.org/show_bug.cgi?id=975919

current state on a Macbook Pro late 2012 with 13" Retina Display:

![img_4106](https://cloud.githubusercontent.com/assets/91113/12280366/a37f70f2-b98d-11e5-96c7-6818c2807a8b.JPG)
![img_4112](https://cloud.githubusercontent.com/assets/91113/12280372/ab1acd8e-b98d-11e5-9ff4-48687dd7f034.JPG)

**Comment by vcunat** [comment]
I'd personally rather think this is mainly job of each desktop and framework (Qt, GTK+), or eventually each application. (Excuse me, but rendering at a lower resolution and scaling is as if you downgraded your display. Still, we could provide a nixos option for that.)

Using "KDE5" instead of KDE4 might also produce better results. Similarly, it might be difficult with GTK+2 stuff and other older toolkits.

**Comment by heydojo** [comment]
The boot up text you should be able to hide using plymouth (you should use journalctl to read system logs instead.)
kde 4 does not support high dots per inch displays and is abandoned software.
I think kde 5 has ongoing work in this area.
Firefox has support (I think I read about it last year,) as does chromium.

In the short term, you can increase font size in kde control center or install kde 5 and see how you get on with that.
In the long term - will kde 5 become the default to make this a none issue?
Not my decision. But, I will say that sddm (the recommended display manager for kde 5) is a very long way off being ready for prime time imo.
When sddm fails it just makes the screen go all black or all white and if you are lucky you get some messages of varying usefulness in your system log.
sddm does not make enough checks when it initialises in order find out if the resources it wants to use are supported by the hardware. For example sddm does not check what opengl versions are provided by the display driver, what the minimum opengl version the qt library supports and whether or not to error out properly if it cannot run due to the opengl version not being high enough in the driver. It just runs and crashes.
sddm does not check properly that it is running and has not crashed and if so return control of X back to the server and exit. It just sits there if it fails instead.

So imo we will just have to wait and see if the developers responsible for sddm build robustness into their display manager. I just hope they don't focus too much on new features and get their core fault tolerant in the up coming months. I'm sure they will the software is still quite new.

**Comment by vcunat** [comment]
> you can increase font size in kde control center

IIRC you can set DPI in there, which I find a better way. (But either will probably only help with fonts anyway.)

**Comment by davidak** [comment]
In the short term, there should be a way to make the current NixOS usable on such devices. I got this laptop at work and don't really care about the display. So just set a lower resolution would help me. That should get set automatically as early as possible. It would be helpful if the boot output is readable.

In long term, the effort of individual Desktops and programs should get integrated into NixOS to play nice together with programs that are not optimized. (On elementary OS all Gtk+ Programs looks good but Qt programs have tiny text and buttons what looks really ugly and is not usable)

**Comment by heydojo** [comment]
```
In the short term, there should be a way to make the current NixOS usable on such devices.
```
There is. We have already mentioned kde 5. I think gnome may also support.
```
It would be helpful if the boot output is readable.
```
Would you mind explaining to me how and why that would be helpful?

```
So just set a lower resolution would help me.
```
https://nixos.org/nixos/options.html
services.xserver.extraDisplaySettings
```
In long term, the effort of individual Desktops and programs should get integrated into NixOS to play nice together with programs that are not optimized.
```
As already mentioned. Nothing can be done about gtk2 and qt4 applications.
Those tool kits are not developed anymore and will likely never support high dots per inch displays.

**Comment by grahamc** [comment]
@davidak you can set the console font: 

```nix
{
  i18n = {
    consoleFont = "sun12x22";
  };
}
```

it will take effect fairly quickly after boot.

**Comment by Baughn** [comment]
> Would you mind explaining to me how and why that would be helpful?

Occasionally bootup fails. In those cases it'd be *very nice* if the text on the screen was readable.

**Comment by grahamc** [comment]
Looks like maybe this fixed it? https://github.com/NixOS/nixpkgs/pull/16801 Can this be closed?

**Comment by Baughn** [comment]
Not quite. The default needs to change based on the screen DPI, unless you want to close this as WONTFIX.

**Comment by abbradar** [comment]
An idea: compose a map "DPI -> preferred font". Take as a default console font value from this table when the key is nearest value to the current `fonts.fontconfig.dpi`.

**Comment by vcunat** [comment]
I suppose, if those users are fine with setting DPI explicitly in their config.

**Comment by abbradar** [comment]
I see no other way because those users (as I imagine) want those fonts as early as possible to see things properly on screen if errors occur. This means in initrd, and this means that we can't pull in all the available fonts. We can introduce some kind of auto-detection into `nixos-generate-config` though...

...but of course, it would be very nice to have another way to accomplish this! Still thinking...

**Comment by Baughn** [comment]
Isn't font scaling a possibility? Even if only by integer factors.

**Comment by abbradar** [comment]
Integer factors might be one way to at least improve this (console fonts are raster). That said, the quality might still suffer, and we might need custom tools to do this correctly and also fit into initrd. I haven't done any research into PSF (fonts' format) handling yet.

**Comment by Profpatsch** [comment]
(triage) is this still relevant?

**Comment by Baughn** [comment]
Well, boot-time / vty text is still unreadable on high-dpi displays.

**Comment by lheckemann** [comment]
For a prettier option on ttys (not just a naïvely n×-scaled font), you can use terminus:
```
{
  i18n.consoleFont = "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
```

I suspect that the `boot.earlyVconsoleSetup` would also help with getting the password prompts easier to read.

**Comment by matthewbauer** [comment]
Is there a way to make this automatic in KDE? I know you can do the force font dpi, but it would be really good if this was automatic for the end user.

**Comment by vcunat** [comment]
I would be surprised if today's KDE/Plasma5 didn't work well out of the box in this respect.  Text-mode console seems to have been the main stumbling block in this thread.  DPI detection has worked fine for me with X in the past several years (several GPUs from all three makers, a few displays).

- - -
I can't even really test high-DPI stuff &ndash; due to little personal motivation for such a display.  FullHD or WUXGA around 100 DPI feels OK for_ my _usage, with sub-pixel rendering for text.  Well, I can just check on a FullHD 15" notebook with NixOS + Plasma5, but I've heard no DPI problem about that one and it's still pretty low ~145 DPI.

**Comment by lheckemann** [comment]
I've created a PR (#56337) adding a rudimentary mechanism for detecting high-DPI framebuffers in nixos-generate-config and setting an appropriate font.

**Comment by lheckemann** [comment]
Reviews on said PR would be appreciated ;) I don't know perl.

**Comment by lheckemann** [comment]
Since what was AFAIU the last remaining pain point that can be fixed in nixpkgs/nixos (console fonts) is now addressed by my PR (`hardware-configuration.nix` needs to be regenerated however), which I've just merged, I'm closing this issue. If there's anything missing, I'd recommend opening a new, more specific issue and referencing this one.
