### ISSUE TITLE
phosh: Night Light feature doesn't work

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#123772]
Assuming gnome settings services are working, see https://github.com/NixOS/nixpkgs/issues/123735#issuecomment-844726397

Enabling the feature shows this error message in the log:

```
May 20 02:16:50 toddflanders .gsd-color-wrap[1897]: unable to get EDID for xrandr-DSI-1: unable to get EDID for output
```

I haven't taken the time to investigate further. It looks like that, at least as far as phosh is concerned, it's asking nicely for the night light to apply.

cc @zhaofengli @dotlambda @jtojnar

**Comment by jtojnar** [comment]
Warning trace:

https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/b23408d1cffd2ab07cb22fcf797137c41ef6f3af/plugins/color/gsd-color-state.c#L1060-1062
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/b23408d1cffd2ab07cb22fcf797137c41ef6f3af/plugins/color/gsd-color-state.c#L108-115
https://gitlab.gnome.org/GNOME/gnome-desktop/-/blob/106a729c3f98b8ee56823a0a49fa8504f78dd355/libgnome-desktop/gnome-rr.c#L1519

Looks like it just accesses a member of `GnomeRROutput` so we would probably need to look at where it is created.

Would be nice to get some more debug info but since it is not started as a systemd service, we cannot just use:

```nix
  systemd.user.services."org.gnome.SettingsDaemon.Color".serviceConfig.Environment = [
    "G_MESSAGES_DEBUG=all"
    # "G_DEBUG=fatal_warnings"
  ];
```

**Comment by davidak** [comment]
This issue seem to be fixed. Night light does apply (but flickers).

https://www.youtube.com/watch?v=Bf20SHc8iDU
