### ISSUE TITLE
Radeonsi card stuck at software rendering 

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#12380]
I think I misconfigured my system but can't find the cause.
My OpenGL is stuck at software
```
$glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD PITCAIRN (DRM 2.43.0, LLVM 3.6.2)
OpenGL version string: 2.1 Mesa 11.0.8
OpenGL shading language version string: 1.30
```
[X.log](https://gist.github.com/anonymous/1c26cfc9fff1416b7986)
[Full config](https://gogs.xndr.de/philipp/nixos-config)

Any help is appreciated.

**Comment by vcunat** [comment]
Why do you believe it does rendering in SW? The X.log seems to me like it uses the usual HW rendering.

**Comment by pstn** [comment]
The OpenGL version is just 2.1 it should be > 3 for radeonsi on mesa 11.0.8. Additionally I think that the vendor string is X.Org for SW rendering, isn't it?

**Comment by vcunat** [comment]
I believe it doesn't do SW rendering. After reading a [gentoo comment](https://forums.gentoo.org/viewtopic-t-1015000.html?sid=54b9db45ef48cc2eb46dd4f79c9c08e8), I think it shows a lower version because texture floats are disabled. That's so by default because of some patent issues.

You can override the settings by `packageOverrides`, e.g. as in https://github.com/ttuegel/nixos-config/blob/fc382dcd19e7f2ed2e34157de2c85671138b6665/overrides/mesa_drivers.nix but instead of `llvmPackages = ...` you put `enableTextureFloats = true;`.

**Comment by vcunat** [comment]
SW rendering looks more like this:
```
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 0x300)
OpenGL version string: 2.1 Mesa 8.0.1
OpenGL shading language version string: 1.20
```

**Comment by pstn** [comment]
Thanks. I was able to successfully build mesa with TextureFloats and have a more recent OpenGL version now.
