### ISSUE TITLE
webkitgtk fails to build on both hydra (out of disk) and locally (OOM)

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#123800]
**Describe the bug**
https://hydra.nixos.org/build/143392902#tabs-summary is the hydra failure. When building locally on a machine with 32G of memory, the build also fails, but this time with out of memory errors:

```
[1972/4925] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/TextSinkGStreamer.cpp.o^M[1973/4925] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/page/UserMessageHa>
FAILED: Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/unified-sources/UnifiedSource-3a52ce78-26.cpp.o 
/nix/store/jabh25wi8r7v2gpkfyhvm9jaxpzgw73x-gcc-wrapper-10.3.0/bin/g++ -DBUILDING_GTK__=1 -DBUILDING_WEBKIT -DBUILDING_WITH_CMAKE=1 -DBUILDING_WebCore -DBWRAP_EXECUTABLE=\"/nix/store/08cvvl4ga833svkhlmk83ywji9j8qj>
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[2288/4925] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/unified-sources/UnifiedSource-3a52ce78-96.cpp.o^M[2289/4925] Building CXX object Source/WebCore/CMakeFiles/WebCo>
ninja: build stopped: subcommand failed.
```

**To Reproduce**
1. Build webkitgtk at https://github.com/NixOS/nixpkgs/commit/62b840ba3fb462c159bc4226bec4288e1064a853

**Expected behavior**
Build succeeds on hydra and locally without extraorbitant resource requirements.

**Screenshots**
N/A

**Additional context**
N/A

**Notify maintainers**
@worldofpeace @hedning @jtojnar @dasj19

**Metadata**
Channel at https://github.com/NixOS/nixpkgs/commit/62b840ba3fb462c159bc4226bec4288e1064a853

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnome.webkitgtk
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
> When building locally on a machine with 32G of memory, the build also fails, but this time with out of memory errors.

You probably need to limit your `--cores`.  IIRC with 32G RAM, 32 cores is too much and I now use 16.  Similarly with firefox+thunderbird.  I don't know what else to do... the build systems (used by those projects) just aren't clever enough for this.

I restarted the Hydra build.

**Comment by vcunat** [comment]
I don't know, I can't see anything actionable here, really.

**Comment by aakropotkin** [comment]
Hey did you find a way to get your build to succeed? I haven't been able to rebuild my system in over a week because of ( what I believe is ) this same issue.

Basically whenever the rebuild hits `webkitgtk` the whole box gets thrashed. I've got a new Intel CPU and 32Gb of memory so unless `webkitgtk` devs are expecting folks to be building on a server farm I can't imagine that I have a real resource issue.

From what I can tell the build gets locked up, most of my logs look identical to yours. Usually I have to force the box to shutdown by killing the power/unplugging because `ninja` or whatever trendy bullshit build system they are using is hogging so badly that Linux can't even respond to a power off request...

Apologies for the frustration; but this has been making me nuts.
