### ISSUE TITLE
memoryAllocator: error while loading shared libraries: libstdc++.so.6

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#125415]
**Describe the bug**
Error running ping with enable memoryAllocator provider:
```
/run/wrappers/bin/ping: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**To Reproduce**
Add to configuration:
```
environment.memoryAllocator.provider = "jemalloc";
```
**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.22-hardened1, NixOS, 21.11.git.22bc080cadc (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05pre289039.d1601a40c48"`
 - channels(lf): `"nixpkgs-1903-19.03.173691.34c7eb7545d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Izorkin** [comment]
This commit breaks the ping utility - 05d334cfe265f021b16c41375e3e5a4c4a07fc74

cc @ju1m

**Comment by ju1m** [comment]
@Izorkin, this is likely due to `environment.memoryAllocator.provider` adding in `/etc/ld-nix.so.preload` the `jemalloc` library, itself depending on `libstdc++.so.6`, both being normally not need by ping (be it `inetutil`'s `ping` or `iputils`' `ping`) hence not allowed in the default relevant AppArmor profile: `bin.ping`.

Please note that this option has a warning that it "may result in instability, data loss and/or service failure" not only because of an experimental allocator but also because of its fundamental departure from what Nix tries to achieve: https://github.com/NixOS/nixpkgs/issues/100799#issuecomment-727896254

Now, if this problem is indeed due to a too restrictive AppArmor profile, you can add AppArmor rules to `security.apparmor.includes."local/bin.ping"` which creates the `/etc/apparmor.d/local/bin.ping` file, loaded by the `bin.ping` profile. See for instance this done [here](https://github.com/NixOS/nixpkgs/blob/163f88aff8911ee81f2038bc409c2e41d9e35823/nixos/modules/services/torrent/transmission.nix#L364) with `local/bin.transmission`.

Adding this config snippet may be enough (I've not tested it though):
```
security.apparmor.includes."local/bin.ping" = ''
  include "${pkgs.apparmorRulesFromClosure {} [pkgs.jemalloc]}"
'';
```
But you might have to use `journalctl -b --grep audit | aa-logprof -f /dev/stdin` to get any remaining missing rules.

**Comment by Izorkin** [comment]
Can all possible applications be allowed to use the jemalloc library?

**Comment by Izorkin** [comment]
And does not work with a hardened profile:
```
  imports = [
    <nixpkgs/nixos/modules/profiles/hardened.nix>
...
```
```
cat /etc/ld-nix.so.preload
/nix/store/afihhz6qs3c4d2sc6f4w0m6ygzllhj0n-malloc-provider-scudo/lib/libclang_rt.scudo-x86_64.so
```
```
ping ya.ru
/run/wrappers/bin/ping: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by Izorkin** [comment]
@ju1m found work variant:
```
  security.apparmor.includes."local/bin.ping" = ''
    include "${pkgs.apparmorRulesFromClosure {} [pkgs.stdenv.cc.cc.lib]}"
  '';
```
Needed add `include "${pkgs.apparmorRulesFromClosure {} [pkgs.stdenv.cc.cc.lib]}"` to `nixos/modules/security/apparmor/profiles.nix` ?

**Comment by ju1m** [comment]
> Can all possible applications be allowed to use the jemalloc library?

@Izorkin, AppArmor only blocks processes for which it has a profile loaded, which you can check with `aa-status`, so applications without a profile won't be denied access to `jemalloc` by AppArmor.
For the profiled programs, I've push a new PR to fix it: https://github.com/NixOS/nixpkgs/pull/125966
