### ISSUE TITLE
grub-install: locale directory doesn't exist

### ISSUE THREAD

**Issue by Munksgaard** [NixOS/nixpkgs#125491]
After upgrading to 21.05, when running `nixos-rebuild switch --upgrade`, I get the following warning:

```
/nix/store/475gqf8jmkgsnzqr3zspvwj20xdbl0xr-grub-2.06-rc1/sbin/grub-install: warning: cannot open directory `/nix/store/475gqf8jmkgsnzqr3zspvwj20xdbl0xr-grub-2.06-rc1/share/locale': No such file or directory.
```

Everything else seems to work fine, but it's unclear what has gone wrong here, or if I should be worried.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.78, NixOS, 21.05.650.eaba7870ffc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.650.eaba7870ffc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
discussed here a bit https://github.com/NixOS/nixpkgs/pull/115310
you can safely ignore it 

to hide it we could add
 `--disable-nls` to the `configureFlags`
or
`mkdir $out/share/locale` to `postInstall`

**Comment by golddranks** [comment]
Not sure if my case is related, but I had the same error after `sudo nixos-rebuild --upgrade boot`:
```
updating GRUB 2 menu...
installing the GRUB 2 boot loader on /dev/sda...
Installing for i386-pc platform.
/nix/store/18n04zvcv8zgysjbh2km6waxy77l2kx0-grub-2.06-rc1/sbin/grub-install: warning: cannot open directory `/nix/store/18n04zvcv8zgysjbh2km6waxy77l2kx0-grub-2.06-rc1/share/locale': No such file or directory.
Installation finished. No error reported.
```
The overall install didn't error. Attempting to reboot, it would be unable to boot:
`error: symbol grub_calloc not found. Entering resque mode...`

**Comment by golddranks** [comment]
My boot got fixed after converting my MBR to GPT and creating an ESP partition and setting it to use systemd-boot instead of GRUB. If GRUB continues to work with people that see this warning, it's unlikely that my boot problems are related. (But, still, a different bug; if MBR got deprecated, there should have been an announcement.)

**Comment by ppenguin** [comment]
> Not sure if my case is related, but I had the same error after `sudo nixos-rebuild --upgrade boot`:
> 
> ```
> updating GRUB 2 menu...
> installing the GRUB 2 boot loader on /dev/sda...
> Installing for i386-pc platform.
> /nix/store/18n04zvcv8zgysjbh2km6waxy77l2kx0-grub-2.06-rc1/sbin/grub-install: warning: cannot open directory `/nix/store/18n04zvcv8zgysjbh2km6waxy77l2kx0-grub-2.06-rc1/share/locale': No such file or directory.
> Installation finished. No error reported.
> ```
> 
> The overall install didn't error. Attempting to reboot, it would be unable to boot:
> `error: symbol grub_calloc not found. Entering resque mode...`

I was bitten by the same. I'm not sure the locale error is related to the second one? 
But the `grub_calloc` issue is quite severe (I just lost hours on it because it happened on a remote server which boots very slowly on a web-mounted rescue iso), and I could only get my system running again by reverting to `20.09`.
I'd propose to throw out the new `grub` version for now.

Same error referenced [here](https://askubuntu.com/questions/1263125/how-to-fix-a-grub-boot-error-symbol-grub-calloc-not-found), it appears to be an issue with the grub package itself.
