### ISSUE TITLE
`hyperlinkSource = false` doesn't seem to be working

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#12567]
See my commented out code at https://github.com/forked-upstream-packages-for-ghcjs/ghcjs/blob/nix/default.nix#L36-L39.

Moreover, wouldn't it be less rebuilding to always use `haskelPackages.hscolour` for this? Or are we worried it might be too old to support some new syntax in a bleeding-edge package set?

**Comment by peti** [comment]
I'm not sure what you're expecting, but `hyperlinkSource = false` does not mean "don't build hscolour". It means "don't *run* hscolour". If you want to avoid building that particular program, then you must replace the default version of mkDerivation with:

    mkDerivation.override { hscolour = null; }

About your second question: we cannot use the default version of hscolour in this context because that would create an inifinite recursion.

**Comment by Ericson2314** [comment]
But if hscolour isn't run, shouldn't it not need to be built either?

Heh, silly me forgetting that even if `haskellPackages.hscolour` didn't colorize itself, we'd still need to disable coloring in all packages used to boot `haskellPackages`. How about instead always using the booting package set's hscolour? You may be interested in this https://github.com/Ericson2314/nixpkgs/commit/93986e6b2198071c414e6c311b6ae22ab2887219 as a foundation to to do so without overriding hscolour in the current package set (as is sometimes done today).

**Comment by peti** [comment]
> But if hscolour isn't run, shouldn't it not need to be built either?

The generic builder does not reference `hscolour` if `hyperlinkSource` is `false`. If it gets built anyway, then probably some other build is still using it.

> How about instead always using the booting package set's hscolour?

I'd rather not make that change in Nixpkgs, because it feels wrong for the default builder to use a version of `hscolour` outside of the package set it's building. This behavior would certainly surprise me as a user. But in your particular setup you *can* pass any `hscolour` you'd like using the override I mentioned in my previous message.

**Comment by Ericson2314** [comment]
Oh wow, I was forgetting about transitive dependencies. Obviously I'd need to disable hyperlinking on those too. For now I'll just make hscolour come from the same pkg set as ghc.
-----
Well, to tie everything together, that commit comes from a branch for cross compiling, which I am testing by making ghcjs our first cross compiler, and using nix instead of ghcjs-boot to boot it. If such a thing were to land, then I think it is useful to distinguish between build tools vs other packages---hscolour in the package set would be cross-compiled, `bootPkgs.hascolour` wouldn't be. But yes, without the rest of the changes, just overriding hscolour in the current package set makes sense.
