### ISSUE TITLE
dotnetCorePackages.net_5_0 is out of date, and out of sync with sdk_5_0

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#125735]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
  - #112582 is also out of date

###### Project name
`nix search` name: (I'm not sure how to check this on a system with flakes)

current version: 5.0.0 / 5.0.3
desired version: 5.0.6

###### Additional note
I have a PR open for packaging netcoredbg (#103940). Building netcoredbg requires knowing the version of the runtime bundled with the SDK. Currently, the `net_5_0` package and `sdk_5_0` package are out of sync, making this difficult. The easiest solution would be to make sure to keep these in sync, but another option might be to add something like `passthrough.runtimeVersion`.

###### Notify maintainers

maintainers: @kuznero

###### Note for maintainers

Please tag this issue in your PR.

**Comment by avdv** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/138296

What's a bit confusing is that release 5.0.10 includes two SDKs (see https://dotnetcli.blob.core.windows.net/dotnet/checksums/5.0.10-sha.txt
):

- dotnet-sdk-5.0.207
- dotnet-sdk-5.0.401

I do not understand the difference nor why there are two inside the same release.

I have upgraded the dotnet 5 sdk to the latter in nixpkgs.
