### ISSUE TITLE
nodejs 5.x is broken on darwin

### ISSUE THREAD

**Issue by manveru** [NixOS/nixpkgs#12592]
All builds of http://hydra.nixos.org/search?query=nodejs-5_x.x86_64-darwin fail. When I try to build nixpkgs/master locally, I get the same failure as http://hydra.nixos.org/build/30868848/nixlog/1

Any ideas what might cause this?

**Comment by copumpkin** [comment]
I think the issue is that it's reaching out to the host Xcode and needs to be patched not to do that. I don't have time to look and although I know about darwin impurities a fair amount, know nothing about nodejs. Someone who actually uses it needs to step up and fix it properly. The fix will likely look like a patch that tells it not to reach out to Xcode and instead teaches it where to find the things it needs.

Also relevant is a project @pikajude is working on to present a fake Xcode to our `stdenv`, but I don't think that's ready yet.

**Comment by codedmart** [comment]
@manveru @copumpkin For what it is worth. I have Xcode installed and if I add this line back in it builds for me: https://github.com/NixOS/nixpkgs/commit/5cb1e43fd6eb7f87c9b17e9dc6d1a92ae7c360a4#diff-ca370b1235dc533ddf1c7effd45a0327L41

**Comment by copumpkin** [comment]
That's weird. I took it out because I couldn't even find that line in the source, but I might have missed it somehow. Feel free to push it back in!
