### ISSUE TITLE
auto-cpufreq: should start on boot if enabled

### ISSUE THREAD

**Issue by pnelson** [NixOS/nixpkgs#126320]
**Describe the bug**
I believe the auto-cpufreq daemon should start on boot if enabled.

**To Reproduce**
1. Enable auto-cpufreq daemon: `services.auto-cpufreq.enable = true;`.
2. Reboot the system.
3. Run `systemctl status auto-cpufreq`.
4. Observe auto-cpufreq as dead/inactive.

**Expected behavior**
auto-cpufreq service should be started on boot.

**Additional context**
I was using the unstable service in 20.09 and it worked as expected. In 21.05 stable, the service starts dead/inactive and my system is very slow. I manually start the service and I'm back to the NixOS I know and love.

I was able to fix this by adding the following to my configuration:
```
  systemd.services.auto-cpufreq.wantedBy = [ "default.target" ];
```

**Notify maintainers**
@Technical27 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.804.5de44c15758 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(pnelson): `""`
 - channels(root): `"nixos-21.05.804.5de44c15758, nixos-unstable-21.11pre294109.fbfb79400a0, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/81138

**Comment by Technical27** [comment]
Sorry for being late, #126897 should fix this.

**Comment by ASHGOLDOFFICIAL** [comment]
I have the exact same issue now, on 23.11.

**Comment by becknik** [comment]
Same here, also facing this problem on 23.11...

**Comment by becknik** [comment]
@nicoo

**Comment by stusmall** [comment]
For others who might still be hitting this, I thought I was too.  When checking the logs I saw that power-profiles-daemon was starting up, causing auto-cpufreq to shut down.  I fixed this by adding: `services.power-profiles-daemon.enable = false;`

From looking at this code, and be kind with me here since I'm a nix beginner, [while this is off by default ](https://github.com/NixOS/nixpkgs/blob/cd18e2ae9ab8e2a0a8d715b60c91b54c0ac35ff9/nixos/modules/services/hardware/power-profiles-daemon.nix#L17)[it is enabled when using gnome](https://github.com/NixOS/nixpkgs/blob/cd18e2ae9ab8e2a0a8d715b60c91b54c0ac35ff9/nixos/modules/services/x11/desktop-managers/gnome.nix#L264).
[
I think the best action would be to add an assertion to give users a prompt like with tlp](https://github.com/NixOS/nixpkgs/blob/cd18e2ae9ab8e2a0a8d715b60c91b54c0ac35ff9/nixos/modules/services/hardware/power-profiles-daemon.nix#L35).  If this looks correct I can open a PR for it
