### ISSUE TITLE
Systemd service execution environment lacks nix-shell

### ISSUE THREAD

**Issue by cyounkins** [NixOS/nixpkgs#126723]
**Describe the bug**
I'm unable to use nix-shell shebang environments for a script being invoked from a systemd unit.

**To Reproduce**

Part of `/etc/nixos/configuration.nix`:
```
  systemd.services.test = {
    enable = true;
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStart = "/test.sh";
    };
  };
```

`/test.sh`:

```
#! /usr/bin/env nix-shell
#! nix-shell --pure -i bash -p rsync

echo "OK!!"
rsync --version
```

Upon rebuild, the unit is started and fails:
```
test.sh[28909]: /usr/bin/env: ‘nix-shell’: No such file or directory
```

If I modify the configuration to add `path = [ pkgs.nix ];` to the service configuration, `nix-shell` is found but another issue is found:

```
test.sh[31435]: error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
```

**Expected behavior**
I expected the systemd execution environment to have and be able to use `nix-shell`

**Additional context**

I'm able and would like to contribute a patch, but need confirmation and direction from someone more familiar with this. I think `pkgs.nix` should be included in the default PATH, and `NIX_PATH` provided (but I don't know where to get it).

**Notify maintainers**

@kirelagin  @mdlayher @flokli ?? (I looked for recent editors)

**Metadata**

root@pluto ~# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.804.5de44c15758 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.804.5de44c15758"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information: (I'm uncertain about this)
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by kirelagin** [comment]
> I expected the systemd execution environment to have and be able to use `nix-shell`

Just as with everything else in the Nix world, you have to declare your dependencies explicitly. The easiest way in your case is probably to use the [`path` option](https://nixos.org/manual/nixos/stable/options.html#opt-systemd.services._name_.path) that is a list of packages that will be added to the `$PATH` variable of the unit (you’ll need to add `pkgs.nix`, since it is what provides `nix-shell`.

I am assuming that you actually need to use `nix-shell` for some reason, e.g. it is a script reused elsewhere. If that is not the case, then instead of using `nix-shell` you should just add the packages that your script needs to the `path` option and get do away with `nix-shell` altogether.

**Comment by kirelagin** [comment]
Just FTR, alternatively, if you were to inline your script, you could just use absolute paths rather than relying on the `$PATH` variable, so, e.g. in your script you would replace `rsync` with `${pkgs.rsync}/bin/rsync}`. I am only mentioning this for completeness, this is just another option, and using `path` is probably a cleaner solution in your case.

**Comment by cyounkins** [comment]
Thank you @kirelagin . It's hidden in the middle of the report but I did try the `path` solution:

If I modify the configuration to add `path = [ pkgs.nix ];` to the service configuration, `nix-shell` is found but another issue occurs:

```test.sh[31435]: error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13```

I now added `NIX_PATH` in `environment`:
```
    environment = {
      NIX_PATH = "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos";
    };
```

and it works. I assumed manually putting more things into the environment was going to be a rabbit hole of dependencies and the wrong way to do it, but it looks like `path` and `environment` are sufficient.

To any future readers - to get `nix-shell` to work in a systemd unit, add these to `systemd.services.<name>`:
```
    path = [ pkgs.nix ];
    environment = {
      NIX_PATH = "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos";
    };
```

Closing, thanks again @kirelagin.
