### ISSUE TITLE
Emacs overrides user-set colors

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#12704]
On startup, after setting a color theme in .emacs, the colors seem to subsequently be overridden—but only partially, giving a situation where the text is white-on-white if the theme has white text.

To replicate, include color-theme in the set of provided packages, then use this .emacs:

```
(color-theme-initialize)
(color-theme-subtle-hacker)
```

Manually setting the color theme after startup is finished, works. I'm not sure how exactly this can be breaking, but break it does.

**Comment by Baughn** [comment]
Here's one workaround:

```
(setq default-frame-alist nil)
```

I'm not sure why default-frame-alist would be set to problematic values, but it doesn't happen on the non-NixOS install at work, so I'll investigate a bit from there to see what's different. Meanwhile, if anyone else runs into this, just add that line to the end of your .emacs.

**Comment by Baughn** [comment]
One workaround:
```
;; For the end of .emacs
(setq default-frame-alist nil)
```
Investigation proceeding.

**Comment by jagajaga** [comment]
cc @oxij

**Comment by oxij** [comment]
I fail to see how this can be a nix/nixos issue. AFAICS, neither
`pkgs/build-support/emacs`, nor `pkgs/applications/editors/emacs-24`
mention color themes.

Applying different color themes in succession is Emacs does produce
strange results because theme settings are mutable variables and most
`color-theme-whatever` override only some of the variables. That's,
regretfully, just how it works in Emacs.

Also of note is the fact that most color themes in `color-theme` package
use outdated variable names (which, regretfully, very often are not
aliased to their new names) for those mutable settings, which means most
of them give results that are different from that their authors
originally intended. (My hypothesis, without looking at the definitions
you mention, is that this case is exactly what happens on your config.)

Some considerable time ago I too became perplexed with all this and I
simply copy-pasted the definitions of my couple favorite themes to my
`init.el` and fixed them to use the new variable names (with the help of
`describe-varible` and friends), also changing them somewhat to my
likening in the process.

**Comment by Baughn** [comment]
It looks like this is *probably* being caused by NixOS' version of Emacs being somewhat newer than the one I've got at work. Someone will need to fix it somewhere, but you're right, it's not Nix' fault.
