### ISSUE TITLE
ghc801:  ChasingBottoms needs upstream fix, due to upper bounds

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#12735]
```
Configuring ChasingBottoms-1.3.0.13...
Setup: At least the following dependencies are missing:
base >=4.0 && <4.9
builder for ‘/nix/store/7hm6dhxf5jhxfsq4day9b8rwrjrsfrx8-ChasingBottoms-1.3.0.13.drv’ failed with exit code 1
```
This raises a meta-question -- how does one efficiently contact DarcsDen people?

**Comment by deepfire** [comment]
Maintainer has uploaded `ChasingBottoms-1.3.0.14`.

**Comment by deepfire** [comment]
@peti, wouldn't a tag in the vein of `needs-hackage-import` help?

`tag:needs-hackage-import`

**Comment by peti** [comment]
Personally, I don't see much value in opening this kind of ticket in the Nixpkgs repository. This is an upstream issue that should be fixed upstream. Once it is, we'll import the new version from Hackage automatically the next time `hackage2nix` is run. There is no manual interaction involved on our side. So from my point of view, this ticket doesn't serve any purpose and should IMHO have been opened upstream rather than here. Just my 2 cents.

Anyway, https://github.com/peti/nixpkgs/commit/a68ace81ca007bb21e10f0e2521116cbb8af1571 add the new version in `haskell-updates`. I'll merge to `master` ASAP.
