### ISSUE TITLE
Basictex

### ISSUE THREAD

**Issue by shaunsingh** [NixOS/nixpkgs#127673]
**Project description**
BasicTeX is a much smaller alternate TeX Distribution for users who do not want to download the full TeX Live, or have unreliable internet connections. BasicTeX is a subset of TeX Live of size 110 megabytes instead of 2 gigabytes. BasicTeX does not overwrite the full distribution; it is installed in /usr/local/texlive/2021basic.

**Metadata**

* homepage URL: https://tug.org/mactex/morepackages.html
* source URL: https://github.com/TeX-Live/texlive-source (not sure)
* license: Mixed free licenses
* platforms: darwin

**Comment by AndersonTorres** [comment]
Being a subset of TexLive, maybe it was already covered by `scheme-small`.

**Comment by rnhmjoj** [comment]
Using `texlive.combine` you can choose one or more predefined subset of packages (`scheme-minimal`, `scheme-small`, `collection-math-science`, etc), but you can even pick the packages you strictly require manually.

For example, to make a beamer slideshow using xetex, unicode-math and pgf:
```
texlive.combine {
  inherit (texlive)
    texlive-scripts xetex unicode-math
    listings caption infwarerr kvoptions
    latex-tools-dev beamer;
}
```
which is around 270MB. So, if you're only concerned about the size, this problem is already solved.

There is also a tool that generates the exact texlive closure you need to build a given document: https://github.com/Mic92/tex2nix

**Comment by AndersonTorres** [comment]
Closing as "solved" (?).

**Comment by shaunsingh** [comment]
Yup, solved.
