### ISSUE TITLE
version in /etc/os-release is verbose

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#127654]
The NixOS version in `/etc/os-release` is way more verbose than [intended](https://www.freedesktop.org/software/systemd/man/os-release.html#Information%20about%20the%20version%20of%20the%20operating%20system) (and in other distros).  One likely consequence is #99677, but the issue is general (I encountered it elsewhere).

We have e.g.:
```ini
VERSION="21.05.git.ad4079ba81d (Okapi)"
VERSION_ID="21.05.git.ad4079ba81d"
```
Others have e.g.:
```ini
VERSION="18.04.5 LTS (Bionic Beaver)"
VERSION_ID="18.04"
```

From a quick glance at [the docs](https://www.freedesktop.org/software/systemd/man/os-release.html#Information%20about%20the%20version%20of%20the%20operating%20system), I'd suggest to move the commit hash to other fields, probably `BUILD_ID`.

_Source: `nixos/modules/misc/version.nix`_

**Comment by prusnak** [comment]
This is probably the fix:

``` patch
--- a/nixos/modules/misc/version.nix
+++ b/nixos/modules/misc/version.nix
@@ -103,9 +103,10 @@ in
       ''
         NAME=NixOS
         ID=nixos
-        VERSION="${cfg.version} (${cfg.codeName})"
+        VERSION="${cfg.release} (${cfg.codeName})"
         VERSION_CODENAME=${toLower cfg.codeName}
-        VERSION_ID="${cfg.version}"
+        VERSION_ID="${cfg.release}"
+        BUILD_ID="${cfg.version}"
         PRETTY_NAME="NixOS ${cfg.release} (${cfg.codeName})"
         LOGO="nix-snowflake"
         HOME_URL="https://nixos.org/"
```

**Comment by mohe2015** [comment]
Would make sense as e.g. archlinux seems to have:
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**Comment by 1000101** [comment]
@vcunat I'm a tad late to the party, but I somehow thought the functionality introduced in 20.05 was intentional and beneficial, too. I think this "bug" was really handy because it was easily distinguishable if a system is up to date by running a single command. I've realized it when I tried to update [this guide](https://dopp.sk/posts/NixOS_channels/).

```
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.49, NixOS, 20.03.2411.30fb4e1e206 (Markhor)`
 - ...
 - channels(root): `"nixos-20.03.2520.add5529b3ee"`
```

By looking at this output, you can tell that the system is lacking behind the channel.

I know I could use `nix-info` in conjunction with `nixos-version` but this simplified so many things (especially debugging) and was really handy that I consider this to be probably first living example of "it's not a bug, it's a feature" :).

Now, I understand there's possibly no way of going back, since this fixes some UX issues, but what about adding a new line to the `nix-info` output, called let's say `os version`, which would display the long name, i.e. output of `nixos-version`?

**Comment by vcunat** [comment]
This issue was about `/etc/os-release` which is standardized cross-distro.  Keeping the information in `nix-info` output seems perfectly fine.

**Comment by 1000101** [comment]
> This issue was about `/etc/os-release` which is standardized cross-distro. Keeping the information in `nix-info` output seems perfectly fine.

Thanks a million for the reply! Yes, I understand that, but since `nix-info` is using that underlying information too.

```
nix-info  -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.101, NixOS, 21.11 (Porcupine)`
 ...
```

And I'm not sure how to approach this. Propose a direct change to the `host os` behaviour (use `BUILD_ID` [instead of `VERSION`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/nix/info/info.sh#L87)), append the `BUILD_ID`, or introduce a new key?

Anyway, I'll open a PR and reference this issue, let's see how that goes :). Thanks.

**Comment by vcunat** [comment]
Yes, sounds like a good direction to me, at a quick glance.
