### ISSUE TITLE
swaylock pam authentication is broken on non-NixOS; pam.d file isn't respected

### ISSUE THREAD

**Issue by jkatzmewing** [NixOS/nixpkgs#128523]
**Describe the bug**
As per https://github.com/nix-community/home-manager/issues/1288, except with nixpkgs on non-NixOS distros, and putting the swaylock pam.d file in /etc/pam.d doesn't help. Even with that file in place, authentication fails with

```pam_authenticate failed: unknown error (6)```

and the screen cannot be unlocked except by killing swaylock.

**To Reproduce**
1. Use nix to install nixpkgs.sway and nixpkgs.swaylock on a non-NixOS distro
2. Make sure swaylock in your shell points to the nix version, and invoke it from a terminal.
3. Attempt to unlock the screen with the correct user password. This will always fail.
4. Switch to a virtual console, log in, and kill swaylock. Switch back. Observe the pam auth error.
5. Manually copy the pam.d file to /etc/pam.d. Verify that it contains the line ```auth include login``` Relogin, or reboot if you like.
6. Repeat steps 2-4. Unlocking the screen will still fail, with no changes from before installing the pam.d file. 

**Expected behavior**
If the requisite pam.d file for swaylock is in /etc/pam.d on a non-NixOS distro, pam should respect that file and allow swaylock to be unlocked.

**Additional context**
First discovered on Ubuntu Hirsute x86-64, on a Microsoft Surface Pro 3. The versions of sway and swaylock from the Ubuntu repos work fine - I wanted to switch to the nix versions to avoid a bug with sway and Firefox. 

**Notify maintainers**
@primeos 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-22-lowlatency, Ubuntu, 21.04 (Hirsute Hippo)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.13`
 - channels(melpomene): `"nixgl"`
 - channels(root): `"nixpkgs-21.11pre297902.e8597594274"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- nixpkgs.swaylock
# a list of nixos modules affected by the problem
module:
```

**Comment by primeos** [comment]
I cannot test/fix this on non-NixOS unfortunately. Does `/etc/pam.d/login` exist and has `/etc/pam.d/swaylock` the correct owner and permissions? It should probably have the same content as `/etc/pam.d/swaylock` from the Ubuntu package (I guess just `auth include login`). Another thing that I could think of is that the `swaylock` binary might need to be in `/usr/bin/` (no idea, I've never really looked into PAM but that would make sense to me).

**Comment by jkatzmewing** [comment]
Yup, ```/etc/pam.d/login``` exists on Ubuntu. There is no ```/etc/pam.d/swaylock``` for the Ubuntu package though. Which is weird, because it's not suid:

```
% ls -l /usr/bin/swaylock
.rwxr-xr-x 74k root 10 Feb  2020 /usr/bin/swaylock
```

TBH this isn't a big deal, because most major distros have working swaylock in their repos anyway.

**Comment by primeos** [comment]
> There is no /etc/pam.d/swaylock for the Ubuntu package though.

Strange, according to https://packages.ubuntu.com/focal/amd64/swaylock/filelist it should exist. Maybe it just isn't reinstalled or there's some other issue/bug (but I guess it doesn't matter anyway).

> TBH this isn't a big deal, because most major distros have working swaylock in their repos anyway.

Ok, in that case I'll close it as there likely isn't anything that we could do in Nixpkgs apart from documenting it (we cannot suid or install to `/etc`). Feel free to reply or reopen it if there's still something to do or discuss.

**Comment by fluffynukeit** [comment]
Hi, I'm having problems with pam on non-NixOs also.  I'm hoping someone can help because I am getting Error 6 Permission denied.  Basic pamtester works fine with the debian package, but in nix-shell it does not even prompt me for my password:
```

zei@mds:~$ pamtester -v auth daustin authenticate
pamtester: invoking pam_start(auth, daustin, ...)
pamtester: performing operation - authenticate
Password: 
pamtester: successfully authenticated
zei@mds:~$ nix-shell -p pamtester

[nix-shell:~]$ pamtester -v auth daustin authenticate
pamtester: invoking pam_start(auth, daustin, ...)
pamtester: performing operation - authenticate
pamtester: Permission denied

```

I am new to PAM so I am unsure what could be wrong.  My end goal is to use nix jupyterhub with the PAM Authenticator module.  This module uses pkgs.linux-pam behind the scenes as I am running Linux.  The PAM authenticator module always fails with Permission Denied, but the minimal example above demonstrates the issue without jupyter or python at all.

**Comment by fluffynukeit** [comment]
I have more information about this issue.  In my case, I was running on Ubuntu, and Ubuntu and other Debian variants maintain a version of PAM that supports the @include directive in /etc/pam.d configuration files.  The nixpkgs PAM version does not support this, so when nixpkgs pamtester tried to access the systems /etc/pam.d/other file, it could not read the file because it included @include lines.  

I tried temporarily changing the /etc/pam.d/other configuration file to not use @include and instead copied the content of the included files directly to the other file.  This got past the original problem, but then pam had problems finding multiple pam modules required by my system's setup.  I was unable to find whether these modules were in nixpkgs and what derivations I'd need to use them.  Instead, I gave up on using nix for my jupyterhub deployment and instead just installed from debian.  I still use nix for the single user services that jupyterhub launches after login is validated, though.

If you have a problem with PAM, you can check the systemd journal for previous PAM errors using `journalctl -r | grep PAM` or just using `journalctl -f` and looking manually for new errors as they show up.  I have found them to be quite informative in contrast to the command line Permission Denied error.

**Comment by primeos** [comment]
Just a quick FYI: This is a closed issue and about swaylock so it's unlikely that anyone will reply here / see your comment. It's likely better to ask via Matrix or Discord but this isn't really a NixOS issue or something we can fix with Nixpkgs changes. The PAM configuration isn't and cannot be managed by Nix (mainly for security reasons) so this entirely depends on the configuration of the Linux distribution. Anyway, good luck ;)

**Comment by fluffynukeit** [comment]
@primeos I posted my comments as additional information for people who might come across this issue through google, like I did.  I am not requesting or expecting help on my issue as I consider the matter resolved.  Thanks.
