### ISSUE TITLE
keycloak module cannot be built

### ISSUE THREAD

**Issue by hrdinka** [NixOS/nixpkgs#128757]
**Describe the bug**

While building the configuration for the keycloak NixOS module a server gets started which just runs forever instead of building the actual configuration. Seems like a WildFly server gets started within the build process of `keycloak-config`. The server is just listening so the whole build never finishes.

**To Reproduce**

Enable `services.keycloak` and build the configuration.

**Expected behavior**

The configuration gets built correctly.

**Screenshots**

![](https://user-images.githubusercontent.com/1436960/123935912-f4c6f980-d994-11eb-917f-12aac1e13140.png)

**Additional context**

**Notify maintainers**

@talyz

**Metadata**

Using latest nixpkgs from master.

**Comment by talyz** [comment]
I'm not able to reproduce this on master. Can you provide your configuration and the full build output? Also, please try running the keycloak tests (`nix-build '<nixpkgs>' -A keycloak.tests`).

**Comment by hrdinka** [comment]
The test does succeed. What is the builder for the config doing (I don’t know anything about jboss/WildFly)?

**Comment by talyz** [comment]
Hm, okay. Then there might be something strange going on in your keycloak config or you hit a temporary build failure for some reason. The builder starts a fresh keycloak instance and waits for it to boot fully, then runs a generated jboss script to apply the declared configuration.

**Comment by hrdinka** [comment]
What is that instance doing? I have seen a PostgreSQL connection string in there, does it try to connect to a database or access local files?

**Comment by talyz** [comment]
No, the instance is a minimal thing with no external dependencies. The jboss script puts the database config in place. If you were able to build the config for the tests, there shouldn't be any issues starting or running the instance on your machine, since that part of the process is identical. What probably differs is the generated jboss script. A copy of it, your config and the complete build output would be helpful here. Can you try to reproduce this in a way that doesn't reveal any sensitive details and submit it?

**Comment by talyz** [comment]
Closing this, since the reporter never got back and the module has since been rewritten for the quarkus version of Keycloak.
