### ISSUE TITLE
networking.firewall: We are not good ICMP citizens by default

### ISSUE THREAD

**Issue by MostAwesomeDude** [NixOS/nixpkgs#12927]
By default, ICMPv4 traffic is blackholed. This is disappointing, especially since the docs on ``networking.firewall.allowPing`` suggest that this is done for security reasons.

There should be a configuration option, perhaps called ``networking.firewall.allowICMPv4``, which should permit all ICMPv4 traffic. (We can put things like ICMPv4 redirects behind ``networking.firewall.allowUnsafeICMPv4Redirects`` or something.)

Additionally, I'd like to humbly suggest that maybe we not default these options to ``false``.

**Comment by jb55** [comment]
:+1: bit myself on one of my hosts the other day because of this

**Comment by fpletz** [comment]
:+1: on all your points and thanks for opening this issue. I have `networking.firewall.allowPing = true` on all of my NixOS machines. This is by no means a security but an obscurity measure.

I'm waiting for some more feedback from the @NixOS/nixpkgs-committers gang before implementing this in a few days.

**Comment by wmertens** [comment]
:+1:

On Fri, Feb 12, 2016, 8:53 AM Franz Pletz <notifications@github.com> wrote:

> [image: :+1:] on all your points and thanks for opening this issue. I
> have networking.firewall.allowPing = true on all of my NixOS machines.
> This is by no means a security but an obscurity measure.
>
> I'm waiting for some more feedback from the @NixOS/nixpkgs-committers
> <https://github.com/orgs/NixOS/teams/nixpkgs-committers> gang before
> implementing this in a few days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/12927#issuecomment-183220647>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by viric** [comment]
I use firewall.enable = false;  in all my machines. :) I definitely dislike the defaults (breaks upnp, ping, and any good p2p)

**Comment by jagajaga** [comment]
On my nonNixos machines I turn pinging off asap. So I respect current defaults..

**Comment by abbradar** [comment]
I agree with current "firewall enabled by default" setting (though I disable it on all "desktop" machines), but I don't like blocking ICMP as a security measure (it's "not nice" and obscurity != security), so I have it enabled everywhere.

**Comment by globin** [comment]
:+1: i turn in allowPing by default, too

**Comment by domenkozar** [comment]
:+1: IPv6 doesn't even work correctly without icmp.

**Comment by lethalman** [comment]
:+1: ping exists for debugging the network

If one wants to secure the icmp stuff, there are other actions to take, not disable pings.

**Comment by domenkozar** [comment]
Even original commit hints for "Maybe". 12161f3183ce0b4d538fbd80b6e05ee947e03e04

**Comment by copumpkin** [comment]
I'm fine with allowing ping by default, but please don't turn the firewall off by default.

**Comment by peti** [comment]
:+1: for allowing ping. Personally, I'd like to see some rate limit attached, i.e. `-m limit --limit 3/minute --limit-burst 5` or so, but I don't feel stronly about it. Ping should work by default, though.

**Comment by shlevy** [comment]
Please don't tag nixpkgs-committers unless you truly need to inform/feedback from everyone who commits to nixpkgs. If there is a potential security issue here, it should probably be discussed or at least announced on-list, as that is not a developer-specific concern.

**Comment by aszlig** [comment]
@copumpkin: Well, why should the netfilter be **on** by default, even for servers? It is introducing additional kernel modules (and thus additional complexity) and makes people even lazy to open ports carelessly when they're better off just **not** opening their ports in the first place. Especially if we enable ICMP and maybe also TCP RST for rejecting connections to "closed" ports it doesn't make sense, also adding rate limit using netfilter when there are sysctl options (http://man7.org/linux/man-pages/man7/icmp.7.html) to do it without *adding* new kernel modules to the attack vector.

I mean we have declarative configuration of services, so if we say "enable a webserver on port 80", we actually _want_ port 80 to be open, if said webserver is *not* enabled, we simply do not enable the module instead of aimlessly opening ports across the universe, hoping that some netfilter is going to save our asses. A port/service that doesn't exist in the first place cannot be attacked regardless of netfilter or not, so we should rather focus on modules to choose tho most secure listening policy. For example if you have a Hydra running on port 3000 and a Web server on port 80 proxying that Hydra backend, the backend should listen locally **only** either using the loopback interface or UNIX sockets (even better) and _not_ on `::`, hoping that some netfilter would block it. So we have port 80 open to the world and all the netfilter would do is purely redundancy.

Of course I'm not against netfilter in general, there are a lot of use cases where it *does* make sense, but I'm still against doing so by default.

Also I've made that point already [in the past](https://github.com/NixOS/nixos/issues/55#issuecomment-11260507) but I probably wasn't clear enough back then.

**Comment by copumpkin** [comment]
The thing is, I don't necessarily want things listening outwards. I could spin up a small mysql database for a local service. I want it enabled, but I don't want it accessible to the outside world. It doesn't seem silly to be more restrictive by default, in a world full of zero-days and services that may be unexpectedly listening  outwards.

**Comment by aszlig** [comment]
@copumpkin: So you just listen to the loopback interface and/or UNIX sockets and you're good to go. I mean instead of netfilter we could add a generic option which defines which ports you want to listen on that is implemented by modules *and* netfilter, also checking against something like `netstat -ntlpeu` during activation (after the services are being started) so we can deliberately break misbehaving modules so we can fix them. And even if you want to have netfilter enabled, you can still use that generic option for the "firewall" module instead of `networking.firewall.allowed*Ports`.

**Comment by ocharles** [comment]
@aszlig the problem with your approach is that you assume all software can be configured that way. Yes, MySQL and nginx can, but that is not an assumption that holds for everything.

**Comment by aszlig** [comment]
@ocharles: Sure, but we can still patch them to be able to configure them that way, at least with my deployments I haven't  yet found any service where I couldn't disable listening to the world and/or patch them to only listen on specific interfaces.

**Comment by aszlig** [comment]
Addendum: Most well-known services already have those options, so it's only a small set of services that will need patching.

**Comment by aszlig** [comment]
Also, I prefer [@shlevy' s idea](https://github.com/NixOS/nixos/issues/55#issuecomment-11298666) but the other way around: Putting `networking.firewall.enable = true;` into the default *template* config but leaving it **off** by default.

**Comment by aszlig** [comment]
As this got a bit off-topic here, I've opened #12957 to continue the discussion over there.

On-topic: :+1: I'm in favor of this, but as to @peti's comment, let's rate limit using `sysctl` instead of adding another netfilter module.

**Comment by edolstra** [comment]
I'm fine with allowing ping by default. I also have `rejectPackets = true` on my machines BTW.

**Comment by peti** [comment]
@aszlig, how is rate-limiting configure via `sysctl`?

**Comment by aszlig** [comment]
@peti: There is `/proc/sys/net/ipv4/icmp_ratelimit` and `/proc/sys/net/ipv6/icmp/ratelimit` and a lot of more options described in the kernel documentation, see: https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt
