### ISSUE TITLE
My NixOS system reports incorrect hashes

### ISSUE THREAD

**Issue by yurrriq** [NixOS/nixpkgs#129471]
**Describe the bug**
Example: https://github.com/NixOS/nixpkgs/pull/128801

**To Reproduce**
1. `nix-prefetch- ...*

**Expected behavior**
Correct hashes.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.44, NixOS, 21.05.20210620.e3c88e2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/store/d46sya9jav92y1frlx3m1wz3rxx39wi6-source`
```

This has happened to me a few times over the years. Any advice?

**Comment by jakobrs** [comment]
This is intentional behaviour (although I don't know where it's documented). Nix notices that your new `src` definition has the same hash as the old one, and since they have the same hash, they're assumed to be the same file. Therefore Nix skips "redownloading" the sources (since it thinks they're the same).

In practice, this just means that, to get a new hash, you have to change something about the hash to "invalidate" it. The easiest way to do this is to just change a random character in the hash to `1` (or some other valid character).

**Comment by roberth** [comment]
If you only updated `rev` or `version` but not the `sha256` hash, you ran into the known issue that @jakobrs described. A design discussion to attempt to address this happened in [RFC 84](https://github.com/NixOS/rfcs/pull/84), concluding for now that it is best solved by changes in Nix itself.

If you got the `sha256` from a nix-prefetch-* tool, you may have found a bug. An example of the invocation would be helpful in this case.
