### ISSUE TITLE
Spanish speaker wanted to help guide a new contributor

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#129919]
Looking for a spanish speaker willing to assist @heroku-miraheze / @joaquinito2051 with his contributions to nixos as he struggles with interpreting CoC (https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Aheroku-miraheze+is%3Aclosed) and needs guidance.

**Comment by Ma27** [comment]
Cross-linking the messages around https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$HgT68vrg3p5PCcjc6GUhMUhK9MmBnwn2tqzocu17TaQ?via=nixos.org&via=matrix.org&via=fairydust.space.

I gotta say given the past interactions with them I personally doubt that there's a good intention (and according to the messages I linked, I'm not alone).

I'm not going to close this (yet), though since I don't really want to decide something like this on my own.

**Comment by Kreyren** [comment]
FWIW from my interactions with him on matrix he seems to be in good faith

**Comment by mausch** [comment]
I'll send him an email in Spanish.

**Comment by mausch** [comment]
Three weeks later, still no response. :man_shrugging: 
Make of that what you will.

**Comment by Kreyren** [comment]
@mausch Are you sure that you sent it on a correct e-mail?

**Comment by mausch** [comment]
I sent it to his gmail account and it didn't bounce.

**Comment by siraben** [comment]
Note: persistent troll on Matrix and recently got banned again. I had a conversation with him on Matrix in spanish a few days ago and he is quite demanding "Vale. Agregalo ahora por favor." and doesn't seem to understand our package vetting process.

**Comment by siraben** [comment]
Closing because person in question has been banned multiple times on Matrix and GitHub.
