### ISSUE TITLE
Audacity 3.0.2 : can’t close after saving project on NixOS 21.05

### ISSUE THREAD

**Issue by jcagui** [NixOS/nixpkgs#130347]
**Describe the bug**

Since the last NixOS upgrade, from 20.09 to 21.05 version, I have this problem with audacity, the same as specified in this forum :

http://64.227.98.153/viewtopic.php?f=68&t=116712&sid=6be8c12ad6a39b289fb4d237fd9c0390

“Internal Error at DBConnection.cpp”

It occures after saving a project and quitting the audacity application.

and they say the solution migth be :
“SQLite must be compiled with SQLITE_ENABLE_DBPAGE_VTAB”

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

@lheckemann

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
copying path '/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1493.1f4e50f03c5 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1493.1f4e50f03c5"`
 - channels(jc): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jcagui** [comment]
Hello,
My problem have been resolved by msackman on Discourse, there : 
[https://discourse.nixos.org/t/audacity-3-0-2-cant-close-after-saving-project/14046/2](url)

I finally added/adapted his solution  in my `/etc/nixos/configuration.nix` : 

```
environment.systemPackages = with pkgs; [

     (
       let
          sqlite = pkgs.sqlite.overrideAttrs (oldAttrs: {
          NIX_CFLAGS_COMPILE = oldAttrs.NIX_CFLAGS_COMPILE + " -DSQLITE_ENABLE_DBPAGE_VTAB";
          });
       in
         pkgs.audacity.override { inherit sqlite; }
     )
];
```
and it works.

I hope it will help
thanks

**Comment by sbruder** [comment]
This still is a problem, overriding sqlite should not be necessary. I don’t know if adding the build flag to sqlite globally is a reasonable fix.

**Comment by jcagui** [comment]
OK, thank you for answering.
Do you mean it could cause a security issue ?
That would be a shame, because it works for me like that.
I'm not at home to try anything else on my computer, and anyway not very skillful.

**Comment by sbruder** [comment]
No, I meant that I don’t know if always building sqlite with the required option is acceptable, since it increases the closure size and could theoretically cause breakage in unrelated packages.
Adding the build flag to sqlite isn’t very complicated, I’ve already patched it locally in my nixpkgs clone. I’m just not sure if that is the preferred way of fixing this problem.

**Comment by lheckemann** [comment]
I don't think it's a security issue. Based on a cursory reading of [the docs](https://www.sqlite.org/dbpage.html) however, I do think we shouldn't enable it globally. I dug in a bit, and it seems that it's only used for some optional functionality (or at least optional enough that [tenacity checks for it at runtime](https://git.sr.ht/~tenacity/tenacity/tree/master/item/src/ProjectFileIO.cpp#L2392). Which also leads me to the conclusion that this wouldn't happen with tenacity. Would using tenacity instead of audacity be a workable solution for you?

**Comment by sbruder** [comment]
The requirement has also been removed by Audacity (https://github.com/audacity/audacity/pull/1802), which now uses a different method to estimate disk usage. Applying that patch could be an option, I’ll look into that later.

I tried tenacity, but it didn’t work as reliably as Audacity, so I personally will continue to use the overriden Audacity for now.

The reason why I reopened this issue is because I wanted to avoid frustration with people trying to run the audacity package and experiencing this problem. I think the package should be either functional out of the box without requiring to manually override sqlite or be marked as broken.

**Comment by jcagui** [comment]
Just a probably stupid question, but a wonder why not packaging the last audacity version ?

**Comment by sbruder** [comment]
Versions after 3.0.2 implement telemetry, which many people dislike for privacy reasons.
The decision to not update it until a solution is found was merged here: https://github.com/NixOS/nixpkgs/pull/129431
Some more discussion about it can be found in the NixOS discourse: https://discourse.nixos.org/t/should-we-support-free-audacity-forks/13960

**Comment by jcagui** [comment]
OK thank you !
