### ISSUE TITLE
GHCJS removed?

### ISSUE THREAD

**Issue by lierdakil** [NixOS/nixpkgs#130584]
GHCJS was removed in cb4346597f033750a432f0161eb5d2c426776960 along with GHC 8.6. If this is a conscious decision, I question why then `pkgs/development/compilers/ghcjs-ng` is still in the tree. Besides, the commit message says nothing of GHCJS. If this was an accident, probably a good idea to revert that. In any case, I'll be grateful for some explanation.

/cc @peti

Sorry I didn't follow the "proper" issue template, but there are no "question" templates and I don't know how to contact all concerned parties otherwise.

Cheers

**Comment by peti** [comment]
I removed `ghcjs` because it was broken and had been broken for several months at that point. Reverting that commit won't accomplish anything, I'm afraid. Making `ghcjs` work again is going to be a more complicated task than that.

**Comment by lierdakil** [comment]
I see. Thanks for the explanation.

**Comment by falsifian** [comment]
I'm interested in getting it working. Tracking it at https://github.com/NixOS/nixpkgs/issues/133271

**Comment by tysonzero** [comment]
@peti I don't suppose you know approximately what nixpkgs commits were the latest with a working ghcjs-8.6? Due to a TH bug and a huge performance regression we can't use ghcjs-8.10, and are currently on [this commit](https://github.com/NixOS/nixpkgs/tree/4dd5c93998da55002fdec1c715c680531420381c) from 3 years ago. Unfortunately that nixpkgs has some bugs to do with mistakenly thinking some SSL certificates are expired, so I was hoping to upgrade a little whilst still continuing to use ghcjs-8.6.
