### ISSUE TITLE
Firefox Branding

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#13075]
Debian is switching back to the official Firefox branding:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815006
* https://bugzilla.mozilla.org/show_bug.cgi?id=555935

> Mozilla recognizes that patches applied to Iceweasel/Firefox don't
> impact the quality of the product.
> Patches which should be reported upstream to improve the product always
> have been forward upstream by the Debian packagers. Mozilla agrees about
> specific patches to facilitate the support of Iceweasel on architecture
> supported by Debian or Debian-specific patches.
> ...
> In case of derivatives of Debian, Firefox branding can be used as long
> as the patches applied are in the same category as described above.
> ...
> The Firefox logo was released under a free copyright license which
matches the DFSG.

If Debian is able to distribute the branded version, maybe we can too?

**Comment by vcunat** [comment]
> If Debian is able to distribute the branded version, maybe we can too?

Doing so needs approval from Mozilla IIRC. @nbp is likely to know more.

**Comment by domenkozar** [comment]
@garbas also :)

**Comment by nbp** [comment]
This decision got made by the history of Debian maintainers, which are by the way Mozilla employee.

Knowing that some contributor attempted to replace the `-O3` by a `-O1` last year.  I do not think we fit in this category yet.

**Comment by garbas** [comment]
i would say lets close it for now and reopen the ticket after a year and then re-evaluate again if we fit into the category with debian maintainers. you can be sure i'll be pursuing this on a daily basis :)

**Comment by jgillich** [comment]
Are you implying they are able to use the branding because they have Mozilla employees as contributors? I don't think that is true, neither do I think it is appropriate to just close this issue with such a nasty comment.

**Comment by vcunat** [comment]
I believe the implication was that before being allowed to use branding, we would have to maintain the package with much more quality.

**Comment by vcunat** [comment]
BTW, I believe we have at least one Mozilla employee among active contributors.

**Comment by nbp** [comment]
> Are you implying they are able to use the branding because they have Mozilla employees as contributors? I don't think that is true, neither do I think it is appropriate to just close this issue with such a nasty comment.

No, they enabled the branding because the license of the logo is fine now, and because they do respect the quality requirement mentioned by Mozilla.  Then as a side note, the Firefox package is maintained by Mozilla employee, on their spare time.

This requirement used to claim that if you were compiling your-self or making a custom version of Firefox, then you are not not supposed to use the branding.

Knowing that we still have the following hack:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/default.nix#L76

I still do not think we respect the quality requirement imposed by Mozilla.
