### ISSUE TITLE
Chromium and qtwebengine based browsers have broken text rendering (invisible) 

### ISSUE THREAD

**Issue by MartinPotier** [NixOS/nixpkgs#131074]
**Describe the bug**

**To Reproduce**
1. Update to chromium 91.0.4472.164 (current on unstable channel)
2. Open chromium
3. Observe that some area where there should be text do not render, this also happens in the developer console or at chrome://gpu/ for example. 

**Expected behavior**
No error in font rendering

**Screenshots**
![image](https://user-images.githubusercontent.com/33028900/126639864-4940a5bd-e73b-413e-9a1f-c213b165b6be.png)

or

![image](https://user-images.githubusercontent.com/33028900/126639931-bb5cf20c-b488-4175-ae00-72480ff0b1be.png)

**Additional informations**
Works on some pages, like meet.google.com or teams, when directly accessing a meeting.

Same behavior observed by a colleague running qutebrowser:
![image](https://user-images.githubusercontent.com/33028900/126641363-890df02b-502b-4285-9ecc-c896758fee22.png)

(this is http://github.com/nixos/nixpkgs)

```
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.3.0
Git commit: 
Backend: QtWebEngine 5.15.3, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: no
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: 2.8.335 (/nix/store/z5n6n43w80lh2p2pfp694q38chlrmnl0-pdfjs-2.8.335/build/pdf.js)
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.1.5
Platform: Linux-5.10.48-x86_64-with-glibc2.33, 64bit
Linux distribution: NixOS 21.11 (Porcupine) (nixos)
Frozen: False
Imported from /nix/store/42sm4xmn4z74m19q7n70b7bgikd9qcy9-qutebrowser-2.3.0/lib/python3.9/site-packages/qutebrowser
Using Python from /nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/bin/python3.9
Qt library executable path: /nix/store/i1gvlgf0g8scyc9rqk9gcz0pvwnvy6sp-qtbase-5.15.2/libexec, data path: /nix/store/i1gvlgf0g8scyc9rqk9gcz0pvwnvy6sp-qtbase-5.15.2
```

**Notify maintainers**
@primeos @thefloweringash @bendlas

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.18, NixOS, 21.11pre303315.16105403bdd (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.14`
 - channels(e): `""`
 - channels(root): `"nixos-21.11pre303315.16105403bdd, doom-emacs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: chromium
# a list of nixos modules affected by the problem
module:
```

**Comment by MartinPotier** [comment]
Rolling back to chromium v91.0.4472.114 fixes the problem:

```
nix run -f https://github.com/NixOS/nixpkgs/archive/aaaa05c78e3ad679335acedafda0a10c62798183.tar.gz chromium -c chromium
```

**Comment by dschrempf** [comment]
I can confirm this issue. All browsers based on `qtwebengine` seem to be affected. Qutebrowser definitely is.

**Comment by primeos** [comment]
I can also confirm it (noticed it a few hours ago) but didn't have time to investigate so far. A good revision is b59c06dc92f8d03660eb4155754d93a6c34cda83 and a bad revision adbf99843c96a7d996e724edf73e59c1f9192ee0 so something between those two revisions must've caused this regression (it's unrelated to Chromium updates). I suspect either acdcb8566ae560752a8a1ce3aacc617a3da6cdd5 or maybe 824c83d7cee7afdc095ef01a5cc0fc447bb31506.

**Comment by lilyinstarlight** [comment]
I'm personally experiencing this in both qutebrowser and Chromium (but Chromium works with `--no-sandbox` on the command line). From what I can tell, this does seem to be caused by the glibc 2.33 update:
* Chromium bug tracker issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1164975
* QtWebEngine bug tracker issue - https://bugreports.qt.io/browse/QTBUG-92969
* Fix in Chromium - https://chromium.googlesource.com/chromium/src/+/60d5e803ef2a4874d29799b638754152285e0ed9 (seems to be in versions since 92)
* Fedora patch for issue on older versions of Chromium - https://src.fedoraproject.org/rpms/chromium/c/82ff440ce80f6a03b150f768a2cba9469a8ec4f4?branch=rawhide

**Comment by primeos** [comment]
@matthewbauer (qtwebengine maintainer): Could you look into the fix for QtWebEngine (see https://github.com/NixOS/nixpkgs/issues/131074#issuecomment-884952978)?
cc @jagajaga @rnhmjoj @ebzzry @dotlambda (qutebrowser maintainers)

Regarding Chromium: #131100 should hopefully fix this regression: https://nixpk.gs/pr-tracker.html?pr=131100
