### ISSUE TITLE
google-java-format

### ISSUE THREAD

**Issue by winston0410** [NixOS/nixpkgs#131220]
**Project description**
A formatter for java.

**Metadata**

* homepage URL: https://github.com/google/google-java-format
* source URL: https://github.com/google/google-java-format
* license: Apache-2.0 License
* platforms: unix, linux, darwin

**Comment by smancill** [comment]
It's trivial to add since Google provides the jar.

smancill/nixpkgs@7315efe3e4f4a2173aa7e12365cdc73f613839ea

But I won't create a PR because it would make me the maintainer of a package that I won't use.

Someone can just take my branch https://github.com/smancill/nixpkgs/tree/google-java-formatter, set the maintainers info and send a PR:

**Comment by asbachb** [comment]
@winston0410 Don't you think it's more convenient to add this tool as part of your build process?

**Comment by smancill** [comment]
Closed by #139964.
