### ISSUE TITLE
explicitly give runtime dependency because clang isn't coming up as dependency

### ISSUE THREAD

**Issue by fxfactorial** [NixOS/nixpkgs#13135]
I am almost done with a new package and I need clang. My current opening function looks like:

```nix 
{ stdenv, git, fetchFromGitHub, requireFile,
  openssl, xz, gnutar, automake, autoconf, libtool,
  clangStdenv, patchelf, which, clang_37 } :
```
and my builder gets clang and uses it with 

```nix
  buildInputs = 
  [ git xz gnutar openssl automake clang_37
    autoconf libtool ];
```

Unfortunately this isn't apparently enough to establish a dependency on clang, I think its because my program doesn't have an rpath of using clang, etc and so to actually use my code I need to also have clang installed with `nix-env -i clang`

I have thought of ways to use patchelf for this, 

like so:
```shell
local libs=$(patchelf --print-rpath $(readlink -f $(which clang)))
patchelf --set-rpath ....
```

But this doesn't work because clang is apparently some kind of wrapper to here for which I 'll just post this insane shell history, utterly insane.

```shell
(Fri Feb-2 12:49:01pm)-(CPU 11.7%:1:Net 222)-(gar:/nix/store/i47yln3r5a89wp0gza9nv7zla5xim714-clang-wrapper-3.7.1/bin)-(60K:9)
> ls
./  ../  as@  c++@  cc@  clang*  clang++*  cpp*  ld*  ld.bfd*  ld.gold*
(Fri Feb-2 12:49:01pm)-(CPU 11.7%:1:Net 222)-(gar:/nix/store/i47yln3r5a89wp0gza9nv7zla5xim714-clang-wrapper-3.7.1/bin)-(60K:9)
> ./clang
clang-3.7: error: no input files
(ERROR)-(Exit Code 1)-(General error)
(Fri Feb-2 12:49:02pm)-(CPU 11.7%:1:Net 222)-(gar:/nix/store/i47yln3r5a89wp0gza9nv7zla5xim714-clang-wrapper-3.7.1/bin)-(60K:9)
> patchelf --print-rpath ./clang
not an ELF executable
(ERROR)-(Exit Code 1)-(General error)
```

So clang is clearly a binary but patchelf says its not? what.

I then tried also clang unwrapped, but then that crapped out because it was trying to link against the C runtime and that was considered unpure and hence the build crapped out. 

So I am once again spending a lot of time to get nix to play nicely and getting super frustrated.

**Comment by avnik** [comment]
If your code itself use clang (execute binary or open .so) you need refer directly ${clang}/bin/clang in your code (via ./configure option, or patching source at build time)

Would be better if you give link to repo to your code which not workign

**Comment by fxfactorial** [comment]
@avnik Okay, so that sort of worked but now made a new problem by giving me an incorrect linker. Once again I have to change my business logic because of the limits of nix.

**Comment by layus** [comment]
Hi @fxfactorial,

Is you problem solved ? If not, are you willing to work with me to fix it ?

Nix adds will add a dependency on clang for your package if it *detects* that your package depends on clang. You cannot force it manually (well, you can... but you should not).

Now there are mostly two ways a package can use another. Either it has an executable linking agains clang libs, then you will get an automatic dependency against these libs and the clang-lib package, or it contains a (bash ?) script that call clang.
In the later case, you need to fixup the script to call `${clang}/bin/clang` instead of plain clang.

It would be damn more easy to help you if we had the code, like avnik said.
This looks like a very easy bug to fix, but we are completely blind here.

Finally, NixOS is a libre project, working thanks to an amazing community of volunteers. I understand that being blocked on packaging something is annoying, but you cannot reasonably expect enterprise-grade support here :-).

I can assure you that you will get answers from me in this thread.

-- Layus.

**Comment by fxfactorial** [comment]
@layus Truthfully I don't know and I've moved on from this issue and Nix itself.
