### ISSUE TITLE
wiki: How to install nix in home (on another distribution

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13185]
https://nixos.org/wiki/How_to_install_nix_in_home_

**Comment by jluttine** [comment]
I'd be interested in such instructions. I've tried the following:

1) The link in the OP doesn't exist anymore.

2) There are two suggestions here: https://nixos.wiki/wiki/Nix_Installation_Guide#PRoot
- chroot doesn't work for me because the test command doesn't work
- proot command is apparently incorrect and I have no idea what it should be: https://github.com/proot-me/PRoot/issues/133

3) Found this: https://gist.github.com/mbbx6spp/4f467adb4e0133063fd87e264c6b9f78#file-homedir_install-sh. Proot URL was incorrect, fixed that, then ran `homedir_install.sh`. That ran seemingly successfully but I still can't use it:
```
$ nixrun nix-env
proot error: 'nix-env' not found (root = /, cwd = /home/7/jluttine, $PATH=/home/users/jluttine/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games)
fatal error: see `proot --help`.
```

So, all these three instructions failed and none of them was official. Could official manual provide instructions on how to install nix in a system where I don't have root access? I don't mind building everything from source, so nix store can be located in home directory. But of course I don't mind using the binary cache either.

**Comment by jluttine** [comment]
Also, related to (3):
```
$ nixrun ls
proot info: pid 20622: terminated with signal 9
```
So I suppose it's not working properly?

**Comment by ignesco** [comment]
Looks like the -b option is needed:

mkdir -m 0755 ~/.nix
./proot_5.1.1_x86_64_rc2--no-seccomp -b ~/.nix:/nix

Now it should be possible to run the standard nix package manager install instructions

N.B. Be sure to fully logout after installing nix so that .nix-profile is loaded.
