### ISSUE TITLE
wiki: Emacs configuration

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13217]
https://nixos.org/wiki/Emacs_configuration

**Comment by rvl** [comment]
I'm writing some documentation (draft is 1ddf86d). Would anyone like to help?

/cc @ttuegel @DamienCassou @oxij @deepfire

**Comment by DamienCassou** [comment]
Thanks for your proposal. I thought we could structure it with more titles and subtitles. What do you think? Here is a proposal:

1. Installing Emacs
  1. Introduction
      - the different releases of Emacs
      - adding packages to Emacs
  2. Installing system-wide (on nixos only)
  3. Installing for a particular user
  4. Advanced configuration
     - mixing stable and unstable packages
     - playing around with the Emacs compilation flags
2. Running Emacs as a service (on nixos only)
  1. Enabling the service
  2. Starting the client
  3. Configuring the `EDITOR` variable
3. Configuring Emacs
  1. The `nix-mode`
  2. Accessing man pages

I would not talk about the old packaging system nor about installing packages system wide.

**Comment by rvl** [comment]
I think those are very good ideas. I shall make another draft on the weekend.

**Comment by rvl** [comment]
I have written a second draft f194ddc. This version validates, so it's possible to build and read it as HTML.

**Comment by DamienCassou** [comment]
@rvl I'm making some changes and will propose you a patch.

**Comment by DamienCassou** [comment]
@rvl I'm really not comfortable doing it in XML. Would you mind if I move it to a public wiki so we can both work on it and then I can convert if to XML when we are ready?

**Comment by deepfire** [comment]
@edolstra, yet another data point.

**Comment by rvl** [comment]
Thanks for offering to help @DamienCassou. I converted the document with pandoc and put it into a gist here: https://gist.github.com/rvl/adc65a89a91af2e27956fe6c6502b204 . You should be able to make revisions on that I think.

@deepfire woah there ... actually writing good docs seems to be harder than getting the xml to validate.

**Comment by deepfire** [comment]
@rvl, how is the comparison meaningful -- I mean, how does it justifies piling a burden upon another?

**Comment by rvl** [comment]
I don't want to get drawn in to the squabble...

But please do put it into a wiki/format of your choice while we draft it.

**Comment by DamienCassou** [comment]
@rvl how can I edit that? In case it doesn't work, I've activated wiki on my [nixpkgs repo](https://github.com/DamienCassou/nixpkgs) and added you to the collaborators.

**Comment by DamienCassou** [comment]
@rvl I finished my pass at https://github.com/DamienCassou/nixpkgs/wiki/Emacs-wiki

**Comment by DamienCassou** [comment]
@rvl what do you think?

**Comment by rvl** [comment]
Hi @DamienCassou, sorry for the delay :snail:.

I think it's very good, thanks!

One thing which is worrying me is the use of a separate `emacs.nix` file. I believe that a significant target audience of this chapter is existing Emacs users who are coming from Ubuntu (for example). For these users, creating and building `.nix` files, just to install emacs might be too much hassle. At least, this was my own experience -- making `.nix` files was a serious impediment for me (until I got organised, and became familiar with the syntax).

I think providing nix snippets suitable for copy&paste into `~/.nixpkgs/config.nix` or `/etc/nixos/configuration.nix` would be more palatable. What do you think?

**Comment by DamienCassou** [comment]
Separating the Emacs description from the nix configuration has a number of advantages:

- it is easier to describe in the documentation (if you don't do that, you have to explain 2 ways of creating the Emacs configuration, one for nixos and one for non-nixos). By separating in a dedicated file, the documentation can focus on the Emacs description

- it permits to move the Emacs description in a public place (e.g., a public git repository) even if configuration.nix is kept private (e.g., because it contains passwords). The Emacs description can even be moved in the `.emacs.d` git repository if the user has one, thus raising the Nix awareness across the world (this is [what I do](https://github.com/DamienCassou/emacs.d)). There are people looking at other's `.emacs.d` repositories to learn tricks and they may be tempted to install Nix on their non-NixOS distribution just as a way to get a fully ready Emacs (that's why there is a beginner-friendly tutorial at the beginning of the nix file I put in my repo)

- it keeps the nix/nixos configuration cleaner (if many Emacs packages are added to the configuration, the Emacs configuration becomes quite long: e.g., mine is a hundred lines long).

I agree there are disadvantages as well. Feel free to adapt my text if you think having everything in one nix file is more important than above advantages (don't worry, I'm ok with both solutions :-)).

**Comment by siddharthist** [comment]
@rvl @DamienCassou Where are you two getting `services.emacs` from? I'm running NixOS 16.03, but these instructions don't work for me: 
```
$ sudo nixos-rebuild switch
building Nix...
building the system configuration...
error: The option `services.emacs' defined in `/etc/nixos/configuration.nix' does not exist.
```

**Comment by DamienCassou** [comment]
@siddharthist `services.emacs` is not in the latest NixOS release, it is in `nixos-unstable`.

**Comment by siddharthist** [comment]
@DamienCassou Sorry to be a bother, but I'm still having trouble testing these docs. I get the same message as above, even after 
```
nix-channel --add  https://nixos.org/channels/nixos-unstable nixos
nixos-rebuild switch --upgrade
```
And with `/etc/nixos/configuration.nix`:
```nix
  services.emacs = {
    enable = true;
  };

  system = {
    stateVersion = "16.03";
    autoUpgrade = {
      enable = true;
      channel = "https://nixos.org/channels/nixos-unstable";
    };
  };
```

**Comment by DamienCassou** [comment]
@siddharthist sorry, I never understood how channels work. Maybe you should add the `nixos-unstable` channel to root (with `sudo`)

**Comment by rvl** [comment]
@siddharthist nixos-unstable channel is the latest version of nixpkgs master branch which builds and passes the NixOS release tests. I think this channel has been blocked for a couple weeks now. So the emacs service from #16356 is not yet in nixos-unstable. You could either wait, or put a git clone of nixpkgs master in your `NIX_PATH`.

@DamienCassou I made a small change to the wiki page, and also translated it back to `emacs.xml`. I think it could be more or less ready for inclusion.

**Comment by DamienCassou** [comment]
@rvl what is the status? Can I merge a PR?

**Comment by DamienCassou** [comment]
@rvl can you please tell us what we should do with your commit?

**Comment by rvl** [comment]
Sorry again for the :snail: I have just come back from holiday. Here is the pull request #17349.
