### ISSUE TITLE
wiki: Audio HOWTO

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13213]
https://nixos.org/wiki/Audio_HOWTO
PulseAudio -> https://nixos.org/wiki/PulseAudio

**Comment by erlandsona** [comment]
I'm going through some of this this weekend while I've got time to work on my nix configs for my new Acer Predator. I'm trying to setup an alternative Music Production Workstation to use based on Nix that I can use to replace my OSX Logic Pro X Setup... I'm super tired of Apple forcing pro-sumers to buy new hardware every few years just to get the latest software. Story of my life for the past ten years before I became a developer.

Could I help move this section of the Wiki into the Manual for helping new users setup sound in the future? The #nixos channel has been so helpful this past week, I'm just trying to give back since I'm still a newb.

**Comment by erlandsona** [comment]
@garbas maybe you can help? I've got a Realtek surround sound system in my Acer Predator that I'm trying to configure pulseaudio to recognize but in all the different configurations I've tried, (will list) none have lead to any result but either the sound plays stereo through the subwoofers... or no sound at all.

`aplay -L` http://nixpaste.lbr.uno/-bxhVAO4
`aplay -l` http://nixpaste.lbr.uno/S5dHiiyz
You can see my configuration.nix @ https://bitbucket.org/erlandsona/.dotfiles/src/99b13076084f8f8938c93c82d230bcdcf7469a23/Nix/configuration.nix?at=master&fileviewer=file-view-default#configuration.nix-21

`nixos-version` => 16.09.695.45b2a6d (Flounder)
`nix-env --version` => (Nix) 1.11.4

**Comment by Mic92** [comment]
does you additional devices show up in pavucontrol?

**Comment by erlandsona** [comment]
@Mic92 unfortunately nope... I was chatting with some friends on Slack and someone mentioned I should check my hda-intel pin configurations with the hdajackretask tool from Alsa-Utils or Alsa-Tools and when I try to run that package I get a DBUS segfault error.
