### ISSUE TITLE
wiki: Python discussion and Python and Plone development

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13244]
https://nixos.org/wiki/Python_discussion
https://nixos.org/wiki/Python
https://nixos.org/wiki/Plone_development

ping @domenkozar @datakurre @cillianderoiste could you check that all info from above wiki pages is in nixpkgs manual.

**Comment by FRidh** [comment]
I'm updating Python docs in #13320 

- https://nixos.org/wiki/Python_discussion contains nothing interesting. Maybe we should write something about recursive pth loader
- https://nixos.org/wiki/Python is trivial. I'm including http://python-on-nix.readthedocs.org/en/latest/ in the docs which covers this article.

**Comment by datakurre** [comment]
@FRidh Thanks. I was not aware of python-on-nix docs. Would've definitely helped earlier.

@garbas I'd just drop "Plone development" chapter for now, and replace it later with more generic "Buildout" development later.

@garbas, @cillianderoiste What should we do with various zc_buildout versions vs. zc_buildout_nix? Should zc_buildout_nix behavior be made the default? (And maybe an option to turn it off at will.) zc_buildout_nix is patched to always prefer packages from the current nix environment and made possible to e.g. properly build Plone in Nix until namespace packages broke with buildout due to wheels.

**Comment by datakurre** [comment]
@garbas Here's the buildout namespace issue, which I mentioned: https://github.com/NixOS/nixpkgs/issues/12141

**Comment by FRidh** [comment]
@Profpatsch if you close an issue, please motivate way.

**Comment by datakurre** [comment]
I wonder, how many there are using buildout-based development with nix? @cillianderoiste? I have a team using nix with buildout but the current version of `pythonPackages.zc_buildout_nix` should just work.

@cillianderoiste I do have one more patch locally for my team for `zc_buildout_nix`:

```
    postInstall = ''                                                            
      sed -i "s|import sys|import sys\nimport os\nsys.executable = os.path.join(sys.prefix, 'bin', os.path.basename(sys.executable))|" $out/bin/buildout
      cat $out/bin/buildout                                                     
    '';
```

It fixes zc.buildout-generated scripts to have python interpreter with zc.buildout available. Of course, it does not prevent garbage collection of those envs. Maybe I should propose that as a patch for `zc_buildout_nix`...

**Comment by FRidh** [comment]
Nothing actionable here I think, so closing.
