### ISSUE TITLE
package request: keyd - "A key remapping daemon for linux"

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#132474]
**Project description**

https://github.com/rvaiya/keyd

> A key remapping daemon for linux.

> Linux lacks a good key remapping solution. In order to achieve satisfactory results a medley of tools need to be employed (e.g xcape, xmodmap) with the end result often being tethered to a specified environment (X11). keyd attempts to solve this problem by providing a flexible system wide daemon which remaps keys using kernel level input primitives (evdev, uinput).

> Features
> keyd has several unique features many of which are traditionally only found in custom keyboard firmware like QMK. Some of the more interesting ones include:

>Layers.
>Key overloading (different behaviour on tap/hold).
Per keyboard configuration.
Instantaneous remapping (no flashing required).
A simple and intuitive config format.
Being display server agnostic (works on wayland and virtual console alike).

**Metadata**

* homepage URL: https://github.com/rvaiya/keyd
* source URL: https://github.com/rvaiya/keyd
* license: MIT
* platforms: linux

**Comment by dit7ya** [comment]
I am new to Nix and was thinking of contributing to it by submitting this package. I am curious, @foolnotion, what is wrong with letting the config directories etc. stay that the way they are? Of course I would want more control over the dotfiles but that is an upstream issue, right?

**Comment by foolnotion** [comment]
@dit7ya I am actually not sure about the proper "nix" way to package this, as nix does not strictly adhere to the FHS standard, but I thought it'd be nice to be able to configure the path. It seems more logical to me to keep the config files under `/home/$USER/.config/keyd` rather than system-wide in `/etc`. I had made an [issue](https://github.com/rvaiya/keyd/issues/18) upstream so the paths are configurable at build time but not at runtime.

**Comment by peterhoeg** [comment]
I've been carrying this locally for ages - apologies for not upstreaming it earlier.
