### ISSUE TITLE
wiki: I3 Window Manager

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13269]
https://nixos.org/wiki/I3_Window_Manager

**Comment by siddharthist** [comment]
I'm happy to migrate this (although much of the information should probably be cut out). Where would you like it?

**Comment by ericsagnes** [comment]
@siddharthist 

For the record, the information on this wiki page is pretty much outdated:
- there is no need to have `dmenu` and `i3status` in environment.systemPackages since  89fa4724f188d2950203446e91720b3880c5d9c3.
- I am pretty sure `i3status` will not show any error and just work out of the box.

The place of choice to document modules is the [`meta.doc`](http://hydra.nixos.org/job/nixos/trunk-combined/nixos.manual.x86_64-linux/latest/download/2/nixos/index.html#sec-meta-attributes) module attribute.

**Comment by garbas** [comment]
closing this one since wiki page is as @ericsagnes said really outdated
