### ISSUE TITLE
wiki: Bluetooth

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13289]
https://nixos.org/wiki/Bluetooth

**Comment by siddharthist** [comment]
Information on this wiki page is out of date, bluez 5 is the default (at least in nixos-unstable)

**Comment by garbas** [comment]
@siddhanathan +1 i think it would be useful to have a section how to setup bluetooth in the manual

**Comment by MasseGuillaume** [comment]
More detail for Bluetooth Headset:
https://gist.github.com/spaceCamel/f40d2d551b4a990f6464

**Comment by garbas** [comment]
@MasseGuillaume @jb55 

should we make (in current master) bluez5 a default bluez? 
also when you enable ``hardware.bluetooth`` maybe we should also do ``hardware.pulseaudio.package = pkgs.pulseaudioFull;``?

i can not test this myself, but will be able to soon ... i just ordered [something from kickstarted](https://www.kickstarter.com/projects/inspero/vinci-first-smart-3d-headphones-that-understand-yo)

**Comment by socksy** [comment]
Maybe this should be moved into another issue, but it seems most relevant here, given that the information in the wiki/internet seems to not be working enough to set things up right.

I have done all the steps in the wiki and @MasseGuillaume's gist, and it fails for me on the connecting part, with `Failed to connect: org.bluez.Error.Failed`. 
(Aside: I do not see the point in specifying bluez as pkgs.bluez5 now it appears to be the default in unstable, but nonetheless have it.)

I'm getting a lot of:
```log
bluetoothd[1876]: a2dp-sink profile connect failed for 00:E0:4C:A1:0D:94: Protocol not available
```
in the results of `systemctl status -l dbus-org.bluez`. Google would suggest that's because pulseaudio doesn't have bluetooth support, but I am using the pulseaudioFull package, and pactl list clearly shows the following modules:

- module-bluetooth-policy
- module-bluetooth-discover
- module-bluez5-discover
- module-bluez4-discover

Restarting pulseaudio also appears to have no effect.

The relevant parts of my configuration are:
  ```nix
hardware = {
    pulseaudio = {
      enable = true;
      systemWide = true;
      support32Bit = true;
      package = pkgs.pulseaudioFull;
    };
    bluetooth.enable = true;
  };
```
And in my custom packages:
```nix
  bluez = pkgs.bluez5;
```
I also put bluez in and out of the package list for no affect.

Anyway, thanks for reading. Thought it might be worth pointing out that the current docs are not enough to get BT audio working for me...

**Comment by qfjp** [comment]
@socksy I know it's been a year, but I think it can be fixed by adding this to `/etc/nixos/configuration.nix`:

    hardware.bluetooth.extraConfig = ''
      [general]
      Enable=Source,Sink,Media,Socket
    ''

**Comment by socksy** [comment]
Thanks for the suggestion, @qfjp, but this gives exactly the same errors as before (blueman-manager saying `Connection Failed: DBusFailedError: Protocol not available` and from the journalctl command I specified in my previous `a2dp-sink profile connect failed for [my bluetooth device address]: Protocol not available`). 

Perhaps I should file a bug report somewhere, but I've not looked up the process. Would be curious to know if anyone else with a Dell XPS 9360/9560 has a similar issue.

**Comment by gmarmstrong** [comment]
I was receiving that same `Connection Failed: DBusFailedError: Protocol not available` from `blueman-manager`, and I solved this by running `systemctl --user daemon-reload; systemctl --user restart pulseaudio` (which is noted in *Using Bluetooth headsets with PulseAudio*) before connecting. I imagine I'll need to do this every time I want to connect to my headset. :slightly_frowning_face:

**Comment by schmittlauch** [comment]
@gmarmstrong I also needed the pulseaudio restart you described, but afterwards the connection mode was, judged by the quality, definitely not A2DP but the old headset mode. Any ideas?
