### ISSUE TITLE
Package request: Ink/Stitch

### ISSUE THREAD

**Issue by dali99** [NixOS/nixpkgs#133180]
**Project description**
Ink/Stitch is an extension for inkscape to generate files for use in embroidery machines

This seems like a real challenge to package: https://inkstitch.org/developers/inkstitch/manual-setup/
needs python, node, and electron. Probably quite a bit over my head

**Metadata**

* homepage URL: https://inkstitch.org/
* source URL: https://github.com/inkstitch/inkstitch
* license: gpl3Only
* platforms: linux, windows, darwin (?)

**Comment by tropf** [comment]
I've hacked together a flake for that, but it's **really** hacky.
Electron has been a headache (+the usual JS problems), python dependencies seem to be deprecated etc., and I had to disable Color Palettes to get the GUI working.

Either way, better than nothing I guess: https://codeberg.org/tropf/nix-inkstitch
(I'm kinda against putting my version into the nixpkgs repo just because how wonky it is, and probably a nightmare to update to new releases.)

**Comment by luzpaz** [comment]
bump
