### ISSUE TITLE
Package Request: Powercord

### ISSUE THREAD

**Issue by huantianad** [NixOS/nixpkgs#133206]
**Project description**
Powercord is a lightweight client mod focused on simplicity and performance, similar to BetterDiscord.

**Metadata**

* homepage URL: https://powercord.dev/
* source URL: https://github.com/powercord-org/powercord
* license: Custom - [Porkord](https://powercord.dev/porkord-license)
* platforms: Linux, Darwin, Windows

**Comment by fufexan** [comment]
@huantianad there's a flake for Powercord already, https://github.com/LavaDesu/powercord-overlay. Even if you don't use flakes, you can still use that overlay.

Packaging something like Powercord isn't possible in Nixpkgs the way BetterDiscord is packaged, since it needs to modify the core components of Discord, which are in the store. In order to get it to install, we need to apply Powercord when building Discord itself, so they're coupled in the same store path.

**Comment by huantianad** [comment]
@fufexan That makes sense, I'll use the flake for now.

**Comment by huantianad** [comment]
Closing for now, as it probably won't be added to nixpkgs.
