### ISSUE TITLE
sway-borders

### ISSUE THREAD

**Issue by shaunsingh** [NixOS/nixpkgs#134334]
**Project description**
sway-borders is a fork of Sway, an i3-compatible Wayland compositor. It introduces some new features like more customizable borders, but is otherwise kept up to date with sway. It serves as a drop-in replacement to sway, since sway isn't looking to offer borers or rounded corners. 

**Metadata**

* homepage URL: https://github.com/fluix-dev/sway-borders
* source URL: https://github.com/fluix-dev/sway-borders
* license: mit 
* platforms: linux

**Comment by jmc-figueira** [comment]
The main issue I see with using `sway-borders` instead of the official sway package is that the [module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/sway.nix) for sway is hard-coded to use the default sway package; maybe the easiest way would be to add a `package` option, like the corresponding home-manager module does. You wouldn't even need a separate package, you could just override the `src` of the existing one, as the compilation process is the same for sway-borders (similar to how one uses the ibhagwan picom fork).

I'll try to do it ASAP and add a pull request here if successful.

**Comment by shaunsingh** [comment]
I ended up making an overlay to replace sway-unwrapped with sway-borders (from git) for now. It handles the meson dependency as well, you can take a look at my dotfiles repo (~/nixos/overlays/flake.nix) for the solution

**Comment by WillPower3309** [comment]
> The main issue I see with using sway-borders instead of the official sway package is that the [module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/sway.nix) for sway is hard-coded to use the default sway package; maybe the easiest way would be to add a `package` option, like the corresponding home-manager module does. You wouldn't even need a separate package, you could just override the `src` of the existing one, as the compilation process is the same for sway-borders (similar to how one uses the ibhagwan picom fork).
> 
> I'll try to do it ASAP and add a pull request here if successful.
> 
> EDIT: In the meantime, you may be able to make do with this strategy: #55366
> 
> EDIT 2: the method above fails with a Meson error: `meson.build:1:0: ERROR: Meson version is 0.57.1 but project requires >=0.58.1`

relies on #140545

**Comment by quantenzitrone** [comment]
If no one objects, I'd close this, as I think sway-borders is not relevant anymore. 
It has no stable release and hasn't seen development in the last 10 months.
For anyone wanting to use sway with eye-candy, there is swayfx. It also works with the sway module now.
