### ISSUE TITLE
callHackageDirect suggests wrong hash in case of multiple revisions

### ISSUE THREAD

**Issue by yaitskov** [NixOS/nixpkgs#134747]
Hi,

I didn't know that Hackage permits multiple versions under same number.
They are called revisions, nix function interface doesn't have any argument for revision.

```
 # callHackageDirect
    #   :: { pkg :: Text, ver :: Text, sha256 :: Text }
    #   -> AttrSet
    #   -> HaskellPackage
    callHackageDirect = {pkg, ver, sha256}:

```

I am updating packages, because of migration to GHC9 and I noticed a trend - several packages
instead of bumping version - reuse old version and revision to disambiguate.

The typical scenario - I set version (e.g. "1.0.0"), I need, and fake SHA to get the correct one on the first run, because it is convenient. nixpkgs gives me some SHA. It turns out that it picks SHA for oldest revision!
I think I am not the one who use the function such a way.

It would nice to check package version for multiple revisions and print hashes and dates for all of them!

Minimum is to extend callHackageDirect comments about Hackage revisions.

**Comment by sternenseemann** [comment]
Revision don't cause a new tarball to be uploaded, so the hash is indeed correct (and stays correct). Instead revisions need to be handled separately because the only thing exposed by hackage are the updated cabal files (so it is limited what you can change in a revision).

That there's no convenient interface in `callHackageDirect` for revisions is unfortunate indeed and we should consider adding this. In the meantime the following workaround should work:

```nix
overrideCabal (callHackageDirect { pkg = "mypkg"; version = "1.2.0"; sha256 = "…"; }) {
  revision = "1";
  editedCabalFile = sha256;
}
```
