### ISSUE TITLE
overridden haskellPackages.callPackage passes a haskellPackages that doesn't contain the added packages

### ISSUE THREAD

**Issue by samuelrivas** [NixOS/nixpkgs#135046]
### Describe the bug
If I override `haskellPackages` to add new packages, the resulting `haskellPackages.callPackage` function passes a `haskellPackages` argument that does not contain the packages I added.

### Steps To Reproduce

Create a file like this (`/tmp/test.nix` henceforth)

```nix
let
  pkgs = import <nixpkgs> { };
  myHaskellPackages = pkgs.haskellPackages.override {
    overrides = self: super: {
      myPackage = super.servant;
    };
  };
  fakePkgHp = pkgs.writeText "fake-derivation-hp"
    ''
    { haskellPackages } : haskellPackages.myPackage
    '';
  fakePkgDirect = pkgs.writeText "fake-derivation-direct"
    ''
    { myPackage } : myPackage
    '';
in
{
  fromHaskellPackages = myHaskellPackages.callPackage fakePkgHp {};
  direct = myHaskellPackages.callPackage fakePkgDirect {};
}
```

Open `nix repl` and load it
```
nix-repl> p = import /tmp/test.nix
```

Check that `direct` outputs a valid derivation (`servant` in this case)

```
nix-repl> p.direct                 
«derivation /nix/store/2dj9armlyad7w1y4iagqs2nqjaqznixm-servant-0.18.2.drv»
```

And that `fromHaskellPackages` fails to evaluate

```
nix-repl> p.fromHaskellPackages
error: attribute 'myPackage' missing, at /nix/store/5qc68x18dlargwdrwbm7vsgnmr8qb9vi-fake-derivation-hp:1:23
```
### Expected behavior

I would expect that, in the nix repl, `p.fromHaskellPackages` to be the same as `p.direct`.

Alternatively, that `haskellPackages` is not passed by `myHaskelllPackages.callPackage`.

What I find confusing is that `haskellPackages` is passed as argument by `myHaskellPackages.callPackage` but doesn't contain `myPackage`, whereas `myHaskellPackages.callPackage` does pass `myPackage` as argument (as expected).
 
### Notify maintainers

Notifying a bit randomly here, not sure who knows about this part of the codebase: @utdemir , @peti . Let me know if there is a better way to notify the relevant people, please.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-80-generic, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(samuel): `"nixpkgs-21.05.2329.348bc5de8bc, nixos-21.05-21.05.961.1f91fd10406"`
 - nixpkgs: `/home/samuel/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: haskellPackages
# a list of nixos modules affected by the problem
module:
```

**Comment by sternenseemann** [comment]
This happens because `pkgs.haskellPackage.callPackage` also inherits the upper scope from `pkgs`, so `haskellPackages` will return whatever `pkgs.haskellPackages` is. Thus using an overlay to do the override will make this behave like you expect:

```nix
let
  pkgs = import <nixpkgs> {
    overlays = [
      (self: super: {
        haskellPackages = super.haskellPackages.override {
          overrides = self: super: { myPackage = self.servant; };
        };
      })
    ];
  };
in pkgs.haskellPackages.callPackage ({ haskellPackages }: haskellPackages.myPackage) { }
```

Note that I would not recommend to use `callPackage` in this way: It is specifically designed to pass individual derivations which it uses to attach extra data to passed derivations (which for example means you get working cross compilation almost for free). This does not work if you are passing entire package sets, so I'd discourage it in normal cases.

Given `callPackage`s semantics this is a maybe surprising, but expected behavior. Because it only affects fringe (ab)use of `callPackage`, I'm personally hesitant to add extra special cased code to prevent users from shooting themselves in the foot in this way.

What are you using this for exactly? Possibly just adding an `haskellPackages = self;` attribute to `haskellPackages` could be an effictive workaround, but I'm not a 100% sold yet.

**Comment by samuelrivas** [comment]
> What are you using this for exactly? Possibly just adding an haskellPackages = self; attribute to haskellPackages could be an effictive workaround, but I'm not a 100% sold yet.

I have several functions and derivations that use `ghc` and a bunch of libraries. I can pass them individually, but since I need all of them to come from a single `haskellPackages`, or at least have been compiled with the same `ghc` version, I thought that passing `haskellPackages` instead of all the individual derivations would be more robust.

Using an overlay sounds like a better solution, I'll try it out and see how it works. I was following the advice given here: https://haskell4nix.readthedocs.io/nixpkgs-users-guide.html#how-to-build-projects-that-depend-on-each-other

> Note that I would not recommend to use callPackage in this way: It is specifically designed to pass individual derivations which it uses to attach extra data to passed derivations (which for example means you get working cross compilation almost for free). This does not work if you are passing entire package sets, so I'd discourage it in normal cases.

This is good to know, thanks. Is there any documentation I missed for this? Reading the document that I linked above didn't gave me the impression that `callPackage` was inheriting the scope from `pkgs`. Actually, I had a pending task to figure out where `haskellPackages` was coming from in the scope :)

**Comment by sternenseemann** [comment]
> I thought that passing haskellPackages instead of all the individual derivations would be more robust.

`callPackage` will enforce a consistent scope already. Also you don't need to explicitly add `ghc` if you use the `mkDerivation` provided by `haskellPackages`.

Another thing is that it's not wise to assume that your haskell package set is called `haskellPackages` since that is just the default set (granted the one you're most likely to be using). Therefore I think it is probably not a good idea to add a workaround for your issue: It would be quite weird if `haskell.packages.ghc901.callPackages ({ haskellPackages }: haskellPackages)` did return `haskell.packages.ghc901` itself, as it isn't called that.

> Is there any documentation I missed for this?

Not really, package set scoping is a bit underdocumented I'd say:

* Explains `callPackage` in general: <https://nixos.org/guides/nix-pills/callpackage-design-pattern.html>
* The basic idea is explained here: <https://github.com/NixOS/nixpkgs/blob/2250e82c70df0cdfaa2bf4fa56b90035c4a5a929/lib/customisation.nix#L199-L218>; However `haskellPackages` uses a [different implementation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/make-package-set.nix) from this.

**Comment by samuelrivas** [comment]
> callPackage will enforce a consistent scope already. Also you don't need to explicitly add ghc if you use the mkDerivation provided by haskellPackages.

Yeah, I think it will probably be better to rework my code to use `callPackage`. This code comes from a past where I was not aware of this function.

> Another thing is that it's not wise to assume that your haskell package set is called haskellPackages since that is just the default set (granted the one you're most likely to be using). Therefore I think it is probably not a good idea to add a workaround for your issue: It would be quite weird if `haskell.packages.ghc901.callPackages ({ haskellPackages }: haskellPackages)` did return `haskell.packages.ghc901` itself, as it isn't called that.

Hrm, maybe I am interpreting it wrong, but my understanding is rather that a function `{ haskellPackages } : ...` gets a set of haskell packages as input, all of them compatible with a given compiler version. Then `pkgs.haskellPackages`  is the default haskell package set, with the default compilation configuration, and `haskell.packages.ghc901` is another package set, containing the same packages, but compiled with another version of ghc.

In that sense the example you wrote does make sense to me. If you run `haskell.packages.ghc901.callPackages ({ haskellPackages })` I expect `haskellPackages` to bind to the `haskell.packages.ghc901` package set.

I understand that what I get in my example is really `pkgs.haskellPackages`, as I am inheriting from the top level `pkgs`, but I am also curious about where my interpretation breaks down. Just to get better understanding of the underlying design choices.

Thanks for the references and the explanations by the way, they have been very helpful.
