### ISSUE TITLE
s3cmd: module python-magic is not available

### ISSUE THREAD

**Issue by ip1981** [NixOS/nixpkgs#13612]
When uploading with s3cmd:

```
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
```

[s3cmd](https://github.com/NixOS/nixpkgs/blob/40ca841c5c0b264a0d1a1ffc2f912e17e30f9caa/pkgs/tools/networking/s3cmd/default.nix) has 

``` nix
{
propagatedBuildInputs = with pythonPackages; [ python_magic dateutil ];
}
```

But is seems pointless at all.

Should a wrapper be used?

``` nix
{
    buildInputs = with pythonPackages; [ python_magic dateutil wrapPython ];
    # ^^ is this enough?
    pythonPath = with pythonPackages; [ python_magic ];
}
```

**Comment by domenkozar** [comment]
There are two python-magic packages, try the other one :)

**Comment by FRidh** [comment]
@ip1981 is this issue solved?

**Comment by ip1981** [comment]
No :-)

**Comment by sleekweasel** [comment]
domenkozar wrote:
> There are two python-magic packages, try the other one :)

How would one go about doing that? pip install python-magic didn't resolve the issue.

**Comment by jdanbrown** [comment]
> There are two python-magic packages, try the other one :)

+1 That's not a helpful comment.

**Comment by jdanbrown** [comment]
Here's a solution that worked for me:
1. Observe in the code that `import magic` is what's triggering the "Module python-magic is not available" error msg:
  - https://github.com/s3tools/s3cmd/blob/b549182/S3/S3.py#L51
  - https://github.com/s3tools/s3cmd/blob/b549182/S3/S3.py#L95
2. Repro the failing import to get more information:

```sh
$ python -c 'import magic'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/danb/miniconda3/lib/python3.6/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```
3. Since I'm using conda, reinstall the `python-magic` package to get the native `libmagic` dependency. If you aren't using conda, then something like `brew install libmagic` (osx) or `apt-get install libmagic-dev` (ubuntu) might work.
```sh
$ conda install -y python-magic
...
The following NEW packages will be INSTALLED:

    libmagic:     5.32-0                                conda-forge
    libopenblas:  0.2.20-hdc02c5d_7
    numpy-base:   1.14.3-py36h7ef55bc_1
    python-magic: 0.4.15-py36_0                         conda-forge
...
```
4. Re-run the import to verify that it no longer fails:
```sh
$ python -c 'import magic'
$
```

**Comment by austinbutler** [comment]
Going to go ahead and close this since it seems to be working fine at this time, it was marked stale nearly a year ago with no comments since, and I see [there have been fixes to `python_magic` recently that reference `libmagic`](https://github.com/NixOS/nixpkgs/pull/115260).

```sh
s3cmd put test.sh s3://bucket-test/test.sh
upload: 'test.sh' -> 's3://bucket-test/test.sh'  [1 of 1]
 53 of 53   100% in    0s   190.01 B/s  done
```

If someone is still able to repro please show what command triggers it and what Nix channel you're on.

**Comment by tmm1** [comment]
Is it possible to silence this warning if I don't care about magic?
