### ISSUE TITLE
Github's response to the issues with the CocoaPods repository may be relevant to this repository

### ISSUE THREAD

**Issue by solenoids** [NixOS/nixpkgs#13774]
Recently, Github has rate-limited the [CocoaPods repository](https://github.com/CocoaPods/CocoaPods) because of the scalability issues with using Github as a CDN. [Github's response is here](https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935).

NixOS uses Github in a similar manner, so it seems to me that the way NixOS distributes package sources needs to change soon. I doubt it's a major issue right now, but if NixOS becomes more popular, this could pose an issue for Github and NixOS.

Thoughts?

**Comment by joachifm** [comment]
Quoting from GitHub's response, linked above:
```
there have been approximately 1.1 Million clones/fetches from CocoaPods/Specs in the past week.
```

For comparison, the nixpkgs repo has seen 2319 clones in the time period 02.25--03.09, peaking at 298 clones (according to https://github.com/NixOS/nixpkgs/graphs/traffic).

**Comment by vcunat** [comment]
I believe our typical workflows do *not* include very frequent clones/fetches. (I discount active contributors, but there will likely never be more than thousands of those.)

It seems to me personally that CocoaPod wasn't using git in a fitting/efficient way. In any case, I believe NixOS.org is rather far from having similar problems and it shouldn't be hard to cope with them in case they appear in (far) future.

**Comment by 7c6f434c** [comment]
>I believe our typical workflows do *not* include very frequent clones/fetches. (I discount active contributors, but there will likely never be more than thousands of those.)
>
>It seems to me personally that CocoaPod wasn't using git in a fitting/efficient way. In any case, I believe NixOS.org is rather far from having similar problems and it shouldn't be hard to cope with them in case they appear in (far) future.

As far as I understand, the things CocoaPods done wrong (according to 
GitHub) are:

1. Not having a way for the end users to use CocoaPods without checking
out from Git (Nix has channels)

2. Having thousands subdirectories as a flat structure inside one 
directory (we have our hierarchical classification, and if we abandon it
I hope we just switch to the `n/ng/nginx` approach)

3. Having periodic fetches into a shallow checkout. I think we never
encouraged this specific usage pattern and have not encoded it into any
scripts.

4. Using Git in an append-only way with adding new versions instead of 
ever updating any packages.

5. Not using a preview API to check whether there are any changes to
fetch before fetching. I am not sure if trying to update NixPkgs and not
getting any new commits because the checkout is already fresh enough is
widespread.

Given our much smaller userbase, I also think going through the
checklist should be enough…

I have no idea about the preview API and adding support for it, though.
