### ISSUE TITLE
python39Packages.sqlalchemy-continuum fails build/tests: = 1 failed, 9 passed, ...

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#138390]
`python39Packages.sqlalchemy-continuum` fails to build as: https://hydra.nixos.org/build/153101820

```
= 1 failed, 9 passed, 91 skipped, 3702 warnings, 651 errors in 145.33s (0:02:25) =
```

All sorts of attribute access errors.

### Notify maintainers

Looks like there is no maintainer.  `python39Packages.ihatemoney` seems to be the only user. Adding @symphorien 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python39Packages.sqlalchemy-continuum
```

**Comment by symphorien** [comment]
It seems that there is no good solution to this problem. sqlalchemy-continuum is incompatible with sqlalchemy 1.4 https://github.com/kvesteri/sqlalchemy-continuum/issues/255 but ihatemoney still depends on it (I contacted upstream about it). Since ihatemoney is a leaf package, it's possible to override it to use sqlalchemy 1.3. I'll try to make a PR in this direction soon.

**Comment by symphorien** [comment]
I am unable to make the latest release of ihatemoney work with the newer versions of its dependencies we have. However I have something that works with their current master. I'll ask upstream about whether they have plans for a release soon.

**Comment by trofi** [comment]
Closing in flavour of open pull request
