### ISSUE TITLE
`erlang` always wants to update to odbc version

### ISSUE THREAD

**Issue by sidkshatriya** [NixOS/nixpkgs#139473]
I have installed `erlang` via nix package manager on my Ubuntu 20.04 system (`nix (Nix) 2.4pre20210908_3c56f62`). The installation works fine.

Currently it is `erlang-24.0.6`

Today when I typed in `nix-env -u '*' --dry-run` I saw the following:
```
(dry run; not doing anything)
upgrading 'erlang-24.0.6' to 'erlang-24.0.6-odbc'
...
```

### Expected behavior
There is no reason why I should be updated to the odbc version if I have installed just `erlang`. This has happened before too. On an older version of `erlang`, the same problem happened -- nix wanted to upgrade me to erlang odbc version. 

(Also note that odbc is part of the version i.e. it is `erlang-24.0.6-odbc` and not something like `erlang_odbc-24.0.6` -- this may or may not be relevant)

cc: @ankhers @Br1ght0ne @DianaOlympos @gleber @happysalada @yurrriq

**Comment by happysalada** [comment]
[nix-env documentation](https://nixos.org/manual/nix/unstable/command-ref/nix-env.html#versions) says the following
```
The versions are compared by splitting them into contiguous components of numbers and letters. E.g., 3.3.1pre5 is split into [3, 3, 1, "pre", 5]. These lists are then compared lexicographically (from left to right). Corresponding components a and b are compared as follows. If they are both numbers, integer comparison is used. If a is an empty string and b is a number, a is considered less than b. The special string component pre (for pre-release) is considered to be less than other components. String components are considered less than number components. Otherwise, they are compared lexicographically (i.e., using case-sensitive string comparison).
```

it looks that erlang has the following code
```
  name = "${baseName}-${version}"
    + optionalString javacSupport "-javac"
    + optionalString odbcSupport "-odbc";
```

it seems to me that it's mistakingly understanding the suffix as part of the version.

the fix is probably
```
name = "${baseName}-${optionalString javacSupport "-javac"}-${optionalString odbcSupport "-odbc"}-${version}";
```
to have something more like `erlang-odbc-24.0.6`

I should have some time to have a look at this tomrrow (if no one else beats me to it :-).
If anybody thinks that this fix is wrong, feel free to comment on this issue.

**Comment by sidkshatriya** [comment]
Thanks for your quick response on this issue! Interestingly there are already pakages in nix that are called `erlang_odbc`, `erlang_odbc_javac` and `erlang_javac`. This is little confusing because `erlang_odbc` has version `24.0.6-odbc` -- here odbc is repeated in the version string.

When you make the fix we would need to ensure that somehow things don't get affected due to this confusing naming scheme in which the variant name is repeated in version string. Is it supposed to be like that?

---
@happysalada Thanks for your appreciative comments about my blog! I'm definitely aware of `helix` and have looked at its website in the past. I have not tried this editor out yet though -- do you like it? It does check lot of my preferences: it is influenced by kakoune, uses rust and the excellent ecosystem of libraries in cargo, has LSP built in and so forth. 

Sadly my editor "exploration budget" is current "spent". I was using vim & jetbrains clion for rust, then I switched to kakoune as my editor of choice for rust. Shifting to another editor at this stage will be too disruptive. I am reasonably productive in kakoune and do supplement with mainstream IDEs from time to time when needed. I plan to be with kakoune for some more time before I try out another terminal editor. Is helix worth the change from kakoune? Is it mature enough?

Thanks for the suggestion to add rd to nix and appreciate your offer for help. This might be an option in the future but I think I want to hold off for now about that and try to get rd to get more mature. Unfortunately I have not been able to spend much time on rd lately...

Have a nice day!  Please feel free to email me if you want to talk more about helix. Sounds like you really like it!

**Comment by happysalada** [comment]
Just made a PR for the fix. I don't think it will have too much impact, since this just changes the name of the package, not it's reference in nix code.

---

regarding helix, I like it because things are improving fast at the moment. Lots of clever people contributing to it. However it's not feature complete at all. global search in repo is only on master (no plugin system yet).
So it's exciting because I feel the future is being built, but you have to tolerate some roughness around the edges. Feel free to revisit this in a couple of years :-)

Regarding rd, I always feel it's by getting the word out that something gets mature. Nix user are usually people interested in the bleeding edge and happy to file an issue (you have to be otherwise you can't use nix in the first place). That said though, take all the time you need to feel comfortable about it, it's important.

**Comment by sidkshatriya** [comment]
@happysalada Thanks for addressing this issue in #139581 --  Sadly, the nix package manager 7 days later is still saying that it will upgrade me from 'erlang-24.0.6' to 'erlang-24.0.6-odbc' if I do `nix-env -u '*' --dry-run`. I'm on the https://nixos.org/channels/nixpkgs-unstable channel. I know there is a sort of time delay between a fix on the repo and when the unstable channel received it but I'm thinking this should be live by now...?

**Comment by sidkshatriya** [comment]
Hmm on further enquiry... it seems that commit 1cbb0feae596544af67bec58c8282de9e31d807b has still not reached the unstable channel.

**Comment by happysalada** [comment]
yes, there are lots of things in the queue at the moment and the unstable job doesn't get as much share as it should. `staging-next` which contains lots of major upgrades gets a higher share at the moment.
it might take 3-4 more days.
