### ISSUE TITLE
Chromium: Smooth scrolling enabled by default

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#13947]
A few days ago smooth scrolling was enabled by default in Chromium; I wonder if that was an upstream or a downstream decision.

On my T400 at least the “feature” causes heavy headache after a few hours and very hard eye-strain, since the text is blurred in a way my eyes can’t focus anymore (as compared to non-smooth mode, where the steps are so small my eyes keep focused).

For anyone wondering: You can disable it in `chrome://flags/`.

cc @chaoflow

**Comment by colemickens** [comment]
Can't find an official source, but it was an upstream change. I'm not sure why it's making the text blurry for you though.

I'm confused by your description of the "steps". Smooth scrolling should make it so that it scrolls in a continuous fashion rather than in jumps. For me, it's actually much easier to stay focused because it scrolls continuously at a very slow rate, if I desire, rather than every tiny scroll mapping to a 6 line jump, or whatever. I'd kinda be curious to see a screen capture if you're setup for it...

(Another way of describing, my scrolling in Chromium just started acting like I would expect it to with a touchpad. My GTK3 apps have smooth, continuous scroll, and now Chromium does too. Maybe it's different for non-touchpad users?)

**Comment by Profpatsch** [comment]
It is how it is I suppose.
