### ISSUE TITLE
direwolf does not build: libgps API version might be incompatible

### ISSUE THREAD

**Issue by anm** [NixOS/nixpkgs#140059]
### Describe the bug
direwolf does not build.

### Additional context

`/build/source/src/dwgpsd.c:64:2: error: #error libgps API version might be incompatible.`

This seems to have been noticed previously as mentioned in this comment on the upgrade of gpsd from 3.22 -> 3.23:
https://github.com/NixOS/nixpkgs/pull/133216#issuecomment-895943208

### Notify maintainers
@lasandell

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.3367.fd8a7fd07da (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(user): `"nixos-21.05pre283367.0a5f5bab0e0, nixpkgs-21.05pre283770.f73da2880a9"`
 - channels(root): `"nixos-21.05.3367.fd8a7fd07da, nixos-hardware, nixos-unstable-21.11pre303315.16105403bdd"`
 - nixpkgs: `/home/anon/.nix-defexpr/channels/nixpkgs`
```

**Comment by lasandell** [comment]
Thanks for the report. Someone else had pointed this out the other day and I had been looking into it. The current stable version of direwolf doesn't support the latest version of gpsd, but that may only be because of the version check that we could override with a patch until it is fixed upstream. Will try to open a PR when I get a chance, but need to test out my theory first.
