### ISSUE TITLE
Chromium is not built on unstable or master

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14034]
Chromium doesn't have successful builds since March 11 -- https://hydra.nixos.org/build/33283038 . The reason is "Output exceeded" (I haven't known that Hydra has output size limits, BTW). This includes latest unstable channel, so we don't have binary substitutions for Chromium on NixOS unstable.

**Comment by cpages** [comment]
This is not limited to unstable/master. 16.03 is also affected, but I just saw that @aszlig committed a bunch of changes related to https://github.com/NixOS/nixpkgs/issues/12794. Not sure if they fix this?

**Comment by aszlig** [comment]
Yes, this is because since NixOS/hydra@4151be7e69957d22af712dd5410b5ad8aa3a2289 the output size of build steps is configurable and before 4f981b4f84707a63904410bb3e2b88621db03e8e the source tree was split up into several derivations, which exceeded the maximum output size at the official Hydra.

So this should be fixed in [`release-15.09`](https://hydra.nixos.org/jobset/nixos/release-15.09/jobs-tab?filter=nixpkgs.chromium), [`release-16.03`](https://hydra.nixos.org/jobset/nixos/release-16.03/jobs-tab?filter=nixpkgs.chromium) and [`master`](https://hydra.nixos.org/jobset/nixos/trunk-combined/jobs-tab?filter=nixpkgs.chromium).
