### ISSUE TITLE
Allow configuring root as the owner of acme certificate files

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#140709]
## Issue description

Currently the acme service hard codes `acme` as the owner of the certificate files. This can cause problems for applications that require very restrict permission (either 600 or 640 with root as the owner) on the private key, such as PostgreSQL. It would be nice to allow configuring the owner of the certificate files, preferably on a per-domain basis.

cc @NixOS/acme

**Comment by pennae** [comment]
sounds like in those extremely restrictive cases it might be better(/necessary) to copy the certificate and use the copy in the service? :/

**Comment by m1cr0man** [comment]
Indeed it would! The solution is very new and with #123261 I just never got around to doing so.

**Comment by m1cr0man** [comment]
Ok, I think we can add a `useRoot` option which is explicit in intention and prevents users setting whoever they want. It's really important that the same user is used across all parts of the acme module... and this is still going to take some testing to validate. I can't create a solid argument against this other than that it is a lot of complexity to maintain.

**Comment by aanderse** [comment]
> I can't create a solid argument against this other than that it is a lot of complexity to maintain.

Sure... but that's a **really** solid argument 😕 The module is overly complicated enough to a point where if you get hit by a truck I'm pretty sure the next update after that happens is going to break something. At this point we should really focus on simplifying the module instead of adding complication. It's not hard for users to write their own `systemd` service to do what they need our module doesn't fit their needs.

I'm not saying we definitely shouldn't accommodate this request, but we should think carefully what we gain vs what we lose if we do.

**Comment by m1cr0man** [comment]
Yeah, the bus factor and the module complexity is a good way to put it. I'll take a look at the delta for this change tomorrow and then make a decision from that. My thought is that the group setting logic is robust enough to cover user too. Need to test it.

I'm preparing a bunch of updates this weekend and for once I did actually remove some complexity from the script which is nice.

**Comment by m1cr0man** [comment]
Adding a `useRoot` option wasn't too bad in the end. I added a test for it too, and I put a big warning against it on the option's description :) It really is better to use LoadCredential as described in https://github.com/NixOS/nixpkgs/issues/101389#issuecomment-841704851 and I have added such steps to the manual now.
