### ISSUE TITLE
gitFull has msmtp not wrapped successfully

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#14092]
## Basic info

To make sure that we are on the same page:

* Kernel: `Linux yuu 4.3.6 #1-NixOS SMP Fri Feb 19 22:35:24 UTC 2016 x86_64 GNU/Linux`
* System: `16.09pre78286.0bf8a1a (Emu)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09pre78286.0bf8a1a"`

## Describe your issue here

`gitFull` has `msmtp` not wrapped and looks for `/usr/bin/msmtp`.

### Steps to reproduce

Try to `git send-email` a patch generated with `git format-patch`

---

Maintainers of git: @peti , @the-kenny , @wmertens

**Comment by bjornfor** [comment]
Does it look for /usr/bin/msmtp by itself? I was under the impression that the user has to tell git where to look:

```
$ cat ~/.gitconfig
...
[sendemail]
	smtpserver = /run/current-system/sw/bin/msmtp
```

(That's how I've configured it.)

I've always thought that a good solution to this would be to let git look in $PATH for msmtp, so that the same .gitconfig file can work on NixOS and any other distro. I never found the energy to suggest that upstream though. :-)

**Comment by bjornfor** [comment]
I also thought that git didn't have anything in particular to do with "msmtp" (you seem to imply that). So from my point of view, wrapping msmtp up in gitFull is not something I've ever considered doing (because I think it's wrong).

**Comment by matthiasbeyer** [comment]
Damn, should have checked that first. Sorry for the noise!
