### ISSUE TITLE
Package requests: wingpanel indicator ayatana

### ISSUE THREAD

**Issue by axtloss** [NixOS/nixpkgs#144045]
**Project description**
This wingpanel plugin adds support for app tray icons back into pantheon, as it has been removed in Elementary OS 5. I think it'd be nice to have it packaged as many would like to completely quit steam or other applications that run in the background with a tray icon. 

**Metadata**

* homepage URL: https://github.com/lafydev/wingpanel-indicator-ayatana
* source URL: https://github.com/lafydev/wingpanel-indicator-ayatana
* license: LGPL-2.1
* platforms: same as pantheon

**Comment by davidak** [comment]
If it's not officially part of pantheon, it has to be optional. But otherwise, it seems useful.

**Comment by bobby285271** [comment]
I managed to build it and make it work (see below screenshot for fcitx5 indicator).

However I cannot maintain this because I don't use it daily and someone has to further improve my code and PR this and maintain this. According to previous practice from packaging pantheon-tweaks, it will be nice to avoid putting this under the pantheon namespace (maybe we need a folder for third party indicators and plugins, but the number is small so far so maybe not a big issue).

![2021-12-13 21-09-27 的屏幕截图](https://user-images.githubusercontent.com/20080233/145818508-fa944af7-d01a-4d54-9ddc-fed776ad1469.png)

```nix
{ lib
, stdenv
, fetchFromGitHub
, substituteAll
, meson
, ninja
, pkg-config
, vala
, gtk3
, libindicator-gtk3
, pantheon
, indicator-application-gtk3
}:

stdenv.mkDerivation rec {
  pname = "wingpanel-indicator-ayatana";
  version = "unstable-2021-12-01";

  src = fetchFromGitHub {
    owner = "Lafydev";
    repo = pname;
    rev = "53dc05919cdba772c787620a4bee5821e38c53cd";
    sha256 = "sha256-T0OHzqENyeAr0pvXUaRMwF1RpwKVyDAF5P5G9S28COU=";
  };

  patches = [
    ./fix-indicator-dir.patch # TODO: Upstream this
    (substituteAll {
      src = ./fix-libapplication-dir.patch;
      indicator_application = indicator-application-gtk3;
    })
  ];

  nativeBuildInputs = [
    meson
    ninja
    pkg-config
    vala
  ];

  buildInputs = [
    gtk3
    libindicator-gtk3
    pantheon.granite
    pantheon.wingpanel
  ];

  meta = with lib; {
    description = "Ayatana Compatibility Indicator for Wingpanel";
    homepage = "https://github.com/lafydev/wingpanel-indicator-ayatana";
    license = licenses.lgpl21Plus;
    platforms = platforms.linux;
    maintainers = with maintainers; [ /* TODO */ ];
  };
}
```

The `fix-indicator-dir.patch` is very similar with I have done to pantheon-tweaks (https://github.com/pantheon-tweaks/pantheon-tweaks/pull/104) and actually does the same thing. It will be nice if someone can upstream this.

```diff
diff --git a/meson.build b/meson.build
index 4aeab2b..a8133c8 100644
--- a/meson.build
+++ b/meson.build
@@ -26,7 +26,8 @@ dependencies = {
 }
 
 indicator_name = 'ayatana'
-indicator_dir  = dependencies['wingpanel'].get_pkgconfig_variable('indicatorsdir')
+libdir = join_paths(get_option('prefix'), get_option('libdir'))
+indicator_dir  = dependencies['wingpanel'].get_pkgconfig_variable('indicatorsdir', define_variable: ['libdir', libdir])
 
 # ----------------------------------------------------------------------------------------------------------------------
 # Bindings:
```

The `fix-libapplication-dir.patch` is used to tell the wingpanel indicator the path for `indicator-application-gtk3` otherwise it is of course impossible to find `libapplication.so` in `Constants.AYATANA_INDICATOR_DIR` and yeah the path looks wired, not sure if there is a better patch.

```diff
diff --git a/src/IndicatorFactory.vala b/src/IndicatorFactory.vala
index 9411de0..632d83b 100644
--- a/src/IndicatorFactory.vala
+++ b/src/IndicatorFactory.vala
@@ -24,7 +24,7 @@ public class AyatanaCompatibility.IndicatorFactory : Object, IndicatorLoader {
     public Gee.Collection<IndicatorIface> get_indicators () {
         if (indicators == null) {
             indicators = new Gee.LinkedList<IndicatorIface> ();
-            load_indicator (File.new_for_path (Constants.AYATANA_INDICATOR_DIR), "libapplication.so");
+            load_indicator (File.new_for_path ("@indicator_application@/lib/indicators3/7/"), "libapplication.so");
         }
 
         return indicators.read_only_view;
```

To add the indicator to wingpanel, you may want to check [the NixOS Manual](https://nixos.org/manual/nixos/unstable/index.html#sec-pantheon-wingpanel-switchboard), that is, add the package to [`services.xserver.desktopManager.pantheon.extraWingpanelIndicators`](https://nixos.org/manual/nixos/unstable/options.html#opt-services.xserver.desktopManager.pantheon.extraWingpanelIndicators).

Following https://github.com/lafydev/wingpanel-indicator-ayatana#easy-install-user-only you will need indicator-application-gtk3 autostart to actually make this work. I am too lazy to do more things, so I just add `indicator-application-gtk3` to `environment.systemPackages` then links `/libexec` from derivations to `/run/current-system/sw`:

```nix
environment.pathsToLink = [ "/libexec" ];
environment.systemPackages = with pkgs; [ indicator-application-gtk3 ];
```

Finally add `/run/current-system/sw/libexec/indicator-application/indicator-application-service` to startup and reboot, and things should work.

![](https://user-images.githubusercontent.com/20080233/145821274-938a50a8-268b-4353-bbe0-42eb023c9905.png)

Of course I guess systemd services can make things a lot easier. And if someone wishes, the whole procedure can be made into a NixOS module, well I am just too lazy to do this...
