### ISSUE TITLE
Instructions to install in home dir result in 404 Not Found

### ISSUE THREAD

**Issue by eterps** [NixOS/nixpkgs#14450]
## Issue description

https://nixos.org/wiki/How_to_install_nix_in_home_(on_another_distribution) doesn't work
### Steps to reproduce

```
wget http://hydra.nixos.org/build/25489771/download/1/nix-1.10-x86_64-linux.tar.bz2
--2016-04-04 20:36:13--  http://hydra.nixos.org/build/25489771/download/1/nix-1.10-x86_64-linux.tar.bz2
Resolving hydra.nixos.org (hydra.nixos.org)... 46.4.67.10
Connecting to hydra.nixos.org (hydra.nixos.org)|46.4.67.10|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-04 20:36:13 ERROR 404: Not Found.
```

Couldn't find a directory index with correct build pacakge links.

**Comment by joachifm** [comment]
See, this is why I think the wiki going down was a good thing. The instructions are a bit unclear, you're supposed to go to hydra and find the latest nix build,not enter the command verbatim.

The *sane* way to do this, however, is

```
$ curl https://nixos.org/nix/install | sh
```

Granted, it's not quite the same, because it installs into `/nix` and not the homedir, but it gives you a single-user nix experience with minimal input.

Given that the wiki is going away, I'm not sure it's even worth updating this page, but I suppose you can do so if you're motivated.

**Comment by matthewbauer** [comment]
Wiki is now deprecated.
