### ISSUE TITLE
Automate rustRegistry updates

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#14469]
Having to update rustRegistry manually is super annoying when you're developing in Rust.

I propose adding a script to nixpkgs that can generate the latest version, and then put a `.travis.yml` in a repo that calls the script and submits a PR, invoked daily by [Nightli.es](https://nightli.es/). Alternatively, it could be a cronjob running on nixos.org infrastructure. This would also be reusable for other packages.

cc @abbradar @trishume @jagajaga What do you think?

**Comment by abbradar** [comment]
Given that snapshot update can't break anything in theory (we require `Cargo.lock` files to ensure dependencies' determinism in our Rust packages, and upstream keeps all old package versions there) I'm all for automated updating. I don't think spamming nixpkgs with automated PRs is a good thing, however. Maybe, given that I can't think of a situation when a snapshot update is harmful, we want to just push updates directly to master. Before doing that, however, we must carefully ensure that upstream is committed to keep all old package versions there and doesn't have an npm-style "unpublish" procedure (i.e. what's got into repository stays there and can only be "hidden" from search maybe).

**Comment by jgillich** [comment]
Crates.io never had an unpublish feature, they only remove things for legal reasons: https://www.reddit.com/r/rust/comments/4bm3rk/how_would_cratesio_react_in_a_case_similar_to_the/d1bqxc0

You're right about directly pushing to master; after a while, nobody's going to check generated commits anyway and will just hit merge. In the unlikely case something breaks, we can always revert it.

**Comment by trishume** [comment]
This sounds good to me. 

I really like the way the rust infrastructure works in Nix relative to the other languages where you have to use Nix file generators, depsSha256 and then making Cargo deterministic is clever.

Specifically for how the script updates the crates index, perhaps this new Nix feature might be of some use: https://github.com/NixOS/nix/commit/06f29fa
I think that should let it prefetch directly based on the `fetchFromGitHub` call in `rust-packages.nix`.
But otherwise we can just figure out the correct URL and use nix-prefetch-url, then update the URL and SHA256 in `rust-packages.nix`

Here's some other things it could update (not necessarily in first implementation, but eventually):
- https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs-modes/melpa-generated.nix
- https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs-modes/elpa-generated.nix
- https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/node-packages-generated.nix
- https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/ghcjs/node-packages-generated.nix

**Comment by kevincox** [comment]
I think that this can be fixed with https://github.com/alexcrichton/cargo-local-registry

This would allow creating a local registry with only the package specified in a Cargo.toml file. This should be constant over time (and is verfiied by hashes) and would eliminate the need to have the registry package at all.

I might try to get it working but I'm not faimilar with the rust packaging and the tool itself has a number of dependencies which I would probably need to build manually to avoid a circular dependency.

**Comment by Artturin** [comment]
we don't have a rustRegistry anymore
