### ISSUE TITLE
error: build of ‘/nix/store/...-VirtualBox-GuestAdditions-5.0.12-4.5-rc5.drv’ failed

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#14562]
## Issue description

I had upgrated from 15.09 to 16.03 branch. After that system rebooted. To update all packages I ran `nix-env -u` and got error while VirtualBox-GuestAdditions-5.0.12-4.5-rc5 compilation.
Log: http://pastebin.com/NTL4QDec
- System: 16.03.526.567b65d (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.03.526.567b65d"

**Comment by dezgeg** [comment]
Sounds like a too new kernel for VirtualBox.

**Comment by danykey** [comment]
I did't install 4.5-rc5 kernel specially. It's runs automatically. Also I had see while `nixos-rebuild switch --upgrade` works - it's compiled 4.5 kernel.

**Comment by dezgeg** [comment]
Yes, `nix-env -u` does that.

**Comment by boobiesinc** [comment]
Getting this during `nixos-install`! Booted from the iso available from https://nixos.org/nixos/download.html which is `nixos-minimal-16.03.769.f98d57b-x86_64-linux.iso`

**Comment by domenkozar** [comment]
@boobiesinc can you post logs?

**Comment by boobiesinc** [comment]
@domenkozar 
The logs looked like the ones OP posted (see from line 585)

Then, I tried to make it use 5.0.20 by modifying [version](https://github.com/NixOS/nixpkgs/blob/50d6c3ba3874c5b79750868786ca0de9982390b4/pkgs/applications/virtualization/virtualbox/default.nix#L21) and [sha256](https://github.com/NixOS/nixpkgs/blob/50d6c3ba3874c5b79750868786ca0de9982390b4/pkgs/applications/virtualization/virtualbox/default.nix#L66) but I must've missed something since I was getting the name 5.0.20 but the same 5.0.12 sources, here's a pic:
![virtualbox_nixos2_16_05_2016_13_35_38](https://cloud.githubusercontent.com/assets/19384416/15294326/712371ee-1b94-11e6-8baf-a73d0a5e5ecb.png)
But note however that I was using a `reset --hard` version of the repo to `channels/16.03` that's why the version was `5.0.12` not 5.0.14(as I have linked)

I was using these lines in `configuration.nix` however:
`linuxPackages = pkgs.linuxPackages_4_5;` (this is likely why I was getting the issue, newer kernel with older vbox)
also
`virtualisation.virtalbox.guest.enable = true;`
and
```
virtualbox = linuxPackages.virtualbox.override {                              
    enableExtensionPack = false;
    pulseSupport = true;
  };
```
and
`services.xserver.videoDrivers = [ "virtualbox" ];`
and
`virtualisation.virtualbox.host.enable = false;`

---------------- 

I have just switched to booting `nixos-minimal-16.09pre83100.25e3c09-x86_64-linux.iso`
and using the latest master when doing the `nixos-install` like so:
`NIX_PATH="nixpkgs=/mnt/etc/nixos/nixpkgs" nixos-install`
I have kept the above lines in my `configuration.nix`, of course. 
Noting that I see some `linux-headers-4.4.10` during compilation of something(`glibc` 2.23).
Compiling...

**Comment by dezgeg** [comment]
Sounds like this has been fixed in the meantime.
