### ISSUE TITLE
sd-image-aarch64 should respect boot.loader.raspberrypi.* options

### ISSUE THREAD

**Issue by DWagenk** [NixOS/nixpkgs#146199]
### Describe the bug
Building an sd-image for the raspberrypi (3B in my case) by including the file `<nixpkgs/nixos/modules/installer/sd-card/sd-image-aarch64.nix>` in a configuration that also sets any of the `boot.loader.raspberrypi.*` has unexpected results.

### Steps To Reproduce
1. build with configuration
```nix
{ config, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/sd-card/sd-image-aarch64.nix>
  ];

  boot.loader.raspberryPi = {
      enable = true;
      uboot.enable = false;
      version = 3;
  };
  
}
```

### Expected behavior
The `FIRMWARE` partition of the generated image should contain a boot loader matching the configuration given above. In this case:
- u-boot is NOT installed
- `config.txt` contains `kernel=kernel.img`

### Additional context
I cross-compiled and pre-configured an image for the raspberrypi. It took quite some time until I figured out that the `boot.loader.raspberryPi.*` options were ignored. I think the sd-image should respect those settings.

I've started work on a patch. Since it wouldn't be completely backwards compatible (options that are currently being ignored would suddenly be respected) I wanted to start a discussion before finishing this up. Would a warning be a good way to deal with this? How is this generally handled?

 This would also need transformation of the enum `boot.loader.raspberryPi.version` into a list and corresponding adaptions in the builder. This brings up the question, whether the builder should prevent incompatible combinations (e.g. an image for both raspberrypi 2 and 4)

### Notify maintainers
@tkerber @bkchr @lopsided98

**Comment by samueldr** [comment]
Hi,

I understand where you're coming from with this issue, but this is a tough problem.

First, strictly technically speaking, the disk image is not "a NixOS configured system". This is why you're seeing this. Note that even the current `extlinux.conf` options are mostly ineffective without special casing:

 * https://github.com/NixOS/nixpkgs/blob/5201be2d3a10da36d7196c13464ee65d84e02582/nixos/modules/installer/sd-card/sd-image-aarch64.nix#L65

This could be *largely* fixed if there were better semantics for image building in NixOS, rather than a few ad-hoc scripts that do the minimum for a specific use case. The actual "bootloader install" mechanisms are not used at all any of the built images (AFAIK).

Second, and this is where it gets a bit harder for me to answer, is that this is not the direction NixOS is going into. The SD images are meant to produce only one *generic mainline Linux* image. The "FIRMWARE" partition is only an inconvenient truth forced on the image by the way the Raspberry Pi startup sequence works; if it was not extremely inconvenient *with the current design*, there would be no firmware partition at all, leaving it as "bring your own firmware". [I wrote recently about planning for a better NixOS on ARM](https://discourse.nixos.org/t/planning-for-a-better-nixos-on-arm/15346).

Adding device-specific management for *any kind of devices* is not desired. It is also planned to move away from the pre-built SD images as they are.

Finally, something I've been tempted to "just do" has been to remove those `boot.loader.raspberrypi.*` options. They are more trouble than they're worth, and break the generations lifecycle. To my knowledge nothing that can be done without U-Boot can't be done with U-Boot.

Maybe we can figure what it is that is lacking and you need, and work towards fixing that?

Side-note, at some point I want to "just" delete the `sd-image` derivations as they are, and provide *better* image building semantics. I think there is some values for pre-built images under some circumstances, and it would be better to provide the required tooling than to continuously hack on the barely adequate ones. These `sd-image` and similar ad-hoc image builders were not really meant to be external interfaces, and it shows.

* * *

See also:

 - https://github.com/NixOS/nixpkgs/pull/67902
 - https://github.com/NixOS/nixpkgs/pull/112677

**Comment by DWagenk** [comment]
Hello @samueldr,

In general I agree with the "FIRMWARE is external" approach, your reasoning - here and in the linked issues - seems absolutely valid.

I started working on some patches populating the FIRMWARE partition as configured through the `boot.loader.raspberrypi.*` options. Similar to what you noted for extlinux.conf. I will not pursue finishing them then.
 > To my knowledge nothing that can be done without U-Boot can't be done with U-Boot.
> Maybe we can figure what it is that is lacking and you need, and work towards fixing that?

I wanted to use the raspberry + raspberry kernel + raspberry prebuilt device-tree-overlays and focus on configuring the rootfs part of the system. Diving into that layer while still not really mastering nix seems a little to ambitious right now. The support and presumably easier getting started was also the reason to choose the raspberry and not one of the more exotic boards.

I guess this is mostly a problem of lacking documentation. Both
> remove those boot.loader.raspberrypi.* options.

> at some point I want to "just" delete the sd-image derivations

seem reasonable if the documentation and/or the tooling (maybe separate from nixpkgs, e.g. the nixos-hardware repo) for building complete system images improves.

**Comment by samueldr** [comment]
> I wanted to use the raspberry + raspberry kernel + raspberry prebuilt device-tree-overlays and focus on configuring the rootfs part of the system.

If you rebuild your system using `boot.linuxPackages = linux_rpi3;` (written from memory) that should get you ~98% of the way there. *As long as you don't need device tree overlays*.

If you have precise questions or issues, I'd be glad to look into them. In that case, open an issue, ping me. 

For device tree overlays, there is a solution, but nothing out of the box *at the current time*. But it can be made to work with not that much effort (all the hard work was already figured out earlier this year).

> seem reasonable if the documentation and/or the tooling (maybe separate from nixpkgs, e.g. the nixos-hardware repo) for building complete system images improves.

Yes. The intention will not be to leave the few user using it out of options.

**Comment by Asqiir** [comment]
For anybody finding this in the future: The option is (currently) called `boot.kernelPackages` and you can find available options at [the linux kernel wiki page of nixos](https://nixos.wiki/wiki/Linux_Kernel).
