### ISSUE TITLE
The commit for teleport 7.3.2 seems stuck

### ISSUE THREAD

**Issue by pecigonzalo** [NixOS/nixpkgs#146175]
This is not really a package bug, but rather to report that it seems like this build https://github.com/NixOS/nixpkgs/runs/4034687795 is stuck. 18d running.

**Comment by cole-h** [comment]
Prior to last Thursday / Friday, we only had 1 Darwin builder for ofborg. Once we added more builders, we moved all the previously-queued builds to a backup queue so that ofborg could work on new PRs instead of on the old, queued PRs (the queue was in the 3000s). Not an ideal situation, but IMHO newer PRs are much more useful to have built than old ones.

So, essentially, this is a "known issue", but nothing is planned to be done at the moment.
