### ISSUE TITLE
gnome.gedit: Error loading plugin 'externaltools'

### ISSUE THREAD

**Issue by psydvl** [NixOS/nixpkgs#146239]
### Describe the bug
`gedit`'s plugin "External tools" cannot be activated

### Steps To Reproduce
1. Open `gedit` preferences (☰ → Preferences)
2. On plugins tab, activate "External tools"

### Expected behavior
"External tools" plugin activated

### Screenshots
![image](https://user-images.githubusercontent.com/43755002/141985322-62145dd0-165b-439b-af81-4ac9f719a81e.png)

### Additional context
1. At least required `python38Packages.pygobject3` 

<details>
<summary>without `python38Packages.pygobject3`</summary>

```console
$ gedit

** (gedit:12595): WARNING **: 15:24:05.707: Error initializing Python Plugin Loader: PyGObject initialization failed
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

** (gedit:12595): WARNING **: 15:24:05.707: Please check the installation of all the Python related packages required by libpeas and try again

(gedit:12595): libpeas-WARNING **: 15:24:05.707: Loader 'python3' is not a valid PeasPluginLoader instance
```
</details>

<details>
<summary>with `python38Packages.pygobject3`</summary>

```console
$ nix-shell -p python38Packages.pygobject3 --run gedit

** (gedit:12567): WARNING **: 15:22:12.313: Failed to load shared library '/nix/store/msn3v1kmihvii0jfxcjzm6z5a1dgwn9s-gedit-40.1/lib/libgedit-40.0.so' referenced by the typelib: /nix/store/msn3v1kmihvii0jfxcjzm6z5a1dgwn9s-gedit-40.1/lib/libgedit-40.0.so: cannot open shared object file: No such file or directory

** (gedit:12567): WARNING **: 15:22:12.314: Error importing plugin 'externaltools':
Traceback (most recent call last):
  File "/nix/store/32q6ryrb860sksdi1al5djg3pgcpq92l-python3-3.8.11/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nix/store/msn3v1kmihvii0jfxcjzm6z5a1dgwn9s-gedit-40.1/lib/gedit/plugins/externaltools/__init__.py", line 23, in <module>
    from .appactivatable import AppActivatable
  File "/nix/store/msn3v1kmihvii0jfxcjzm6z5a1dgwn9s-gedit-40.1/lib/gedit/plugins/externaltools/appactivatable.py", line 78, in <module>
    class AppActivatable(GObject.Object, Gedit.AppActivatable):
  File "/nix/store/v8yqq0yc2prapdnn23cw4kzsxr1rfvn8-python3.8-pygobject-3.40.1/lib/python3.8/site-packages/gi/module.py", line 207, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/nix/store/v8yqq0yc2prapdnn23cw4kzsxr1rfvn8-python3.8-pygobject-3.40.1/lib/python3.8/site-packages/gi/types.py", line 247, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface

(gedit:12567): libpeas-WARNING **: 15:22:12.315: Error loading plugin 'externaltools'
```
</details>

2. Also, app seems trying to call `/nix/store/msn3v1kmihvii0jfxcjzm6z5a1dgwn9s-gedit-40.1/lib/libgedit-40.0.so` instead of `/nix/store/msn3v1kmihvii0jfxcjzm6z5a1dgwn9s-gedit-40.1/lib/gedit/libgedit-40.0.so` but I don't know how to fix it
> `lib/libgedit-40.0.so` instead of
> `lib/gedit/libgedit-40.0.so`

### Notify maintainers
@hedning @jtojnar @dasj19 @maxeaubrey

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13-zen1, NixOS, 21.05.4114.195d5816cdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.4114.195d5816cdd, nixos-unstable-21.11pre330462.2fa862644fc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnome.gedit
```

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/commit/1b2a061c87fd079f57a05c5390a42dcc777498f0 fixed the typelib path issue. The pygobject issue is more complicated. We either need to wrap gedit (easy but ugly). or patch the individual plug-ins with python path.

**Comment by Syndamia** [comment]
I think https://github.com/NixOS/nixpkgs/pull/273060 fixes this issue (alongside others like it), though why it still hasn't been merged is beyond me


<details>
<summary>As a temporary workaround, until this is resolved, you could add an overlay:</summary>

If you've never used overlays before, they allow you to override/modify the pkgs attrset.

### How to

Add the following to your `configuration.nix`:

```nix
nixpkgs.overlays = [ (final: prev: {
  gedit = prev.gedit.overrideAttrs (prevAttrs: {
    buildInputs = prevAttrs.buildInputs ++ (with final; [
      gobject-introspection
      python3.pkgs.pygobject3
    ]);

    preFixup = with final; ''
      gappsWrapperArgs+=(
        --prefix PYTHONPATH : "${python3.pkgs.pygobject3}/${python3.sitePackages}:$out/lib/libgedit/plugins/"
      )
    '';
  });
}) ];
```

### Rough explanation

The first error you get normally is:

> ** (gedit:3697734): WARNING **: 12:02:20.332: Error initializing Python Plugin Loader: PyGObject initialization failed
> ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

We'll need to add the gobject dependency to gedit, so we update `buildInputs`. However, gedit also needs to know the dependency's location, so we need to update `PYTHONPATH` too, which is done in the `preFixup` step.

Everything was taken from a similar Rhythmbox problem: issue https://github.com/NixOS/nixpkgs/issues/140078 and pr https://github.com/NixOS/nixpkgs/pull/162976

### Beyond gedit

This issue is not really unique to gedit, and this solution is applicable to other packages.

More notably, I first figured it out for xed, though there you need to also create a patch file, since the text editor has trouble finding a library it creates upon building (I think it's because [the `meson` builder is hard-coded to look for libraries under `lib`](https://github.com/NixOS/nixpkgs/blob/2fcb2da9e88f6b7bbee426a5753bd0fd3fda228d/pkgs/by-name/me/meson/setup-hook.sh#L14) but maybe can't handle subdirectories).

Solution for xed [here](https://gitlab.com/Syndamia/nix/-/tree/7391362d84121fc1f464fd36a56c45bac3d8eb98/overlays/xed-editor).

</details>

**Comment by bobby285271** [comment]
> https://github.com/NixOS/nixpkgs/issues/146239#issuecomment-1871035564

https://github.com/NixOS/nixpkgs/pull/280933
