### ISSUE TITLE
Use buildDotnetModule for .NET packages

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#146257]
Packages using `fetchNuGet` in `deps.nix` could benefit from using `buildDotnetModule`.

- [x] pkgs/applications/blockchains/btcpayserver - https://github.com/NixOS/nixpkgs/pull/142218
- [x] pkgs/applications/blockchains/nbxplorer - https://github.com/NixOS/nixpkgs/pull/142218
- [X] pkgs/applications/blockchains/wasabibackend - https://github.com/NixOS/nixpkgs/pull/152843
- [x] pkgs/applications/misc/ArchiSteamFarm - https://github.com/NixOS/nixpkgs/pull/145542
- [x] pkgs/development/compilers/roslyn - https://github.com/NixOS/nixpkgs/pull/202765
- [x] pkgs/development/dotnet-modules/python-language-server - https://github.com/NixOS/nixpkgs/pull/144165
- [ ] ~~pkgs/development/tools/build-managers/msbuild~~ 
- [x] pkgs/development/tools/continuous-integration/github-runner - https://github.com/NixOS/nixpkgs/pull/218455
- [x] pkgs/development/tools/misc/netcoredbg - https://github.com/NixOS/nixpkgs/pull/103940
- [x] pkgs/development/tools/omnisharp-roslyn - https://github.com/NixOS/nixpkgs/pull/178004
- [X] pkgs/games/osu-lazer - https://github.com/NixOS/nixpkgs/pull/152260
- [x] pkgs/misc/emulators/ryujinx - https://github.com/NixOS/nixpkgs/pull/139222
- [x] pkgs/servers/jellyfin - https://github.com/NixOS/nixpkgs/pull/144082
- [x] pkgs/servers/jackett - https://github.com/NixOS/nixpkgs/pull/144563
- [x] pkgs/servers/nosql/eventstore - https://github.com/NixOS/nixpkgs/pull/179187
- [x] pkgs/tools/X11/opentabletdriver - https://github.com/NixOS/nixpkgs/pull/146935
- [x] pkgs/tools/backup/discordchatexporter-cli - https://github.com/NixOS/nixpkgs/pull/139222
- [x] pkgs/tools/games/opentracker - https://github.com/NixOS/nixpkgs/pull/142919
- [x] pkgs/tools/misc/depotdownloader - https://github.com/NixOS/nixpkgs/pull/142909

**Comment by prusnak** [comment]
cc @IvarWithoutBones as he did almost all existing work, but anyone from the community is welcome to join the effort!

**Comment by IvarWithoutBones** [comment]
Thank you for creating this list! I have a few additions:

* `pkgs/development/tools/misc/netcoredbg` already uses `buildDotnetModule`: https://github.com/NixOS/nixpkgs/blob/354ff094e42e16055d4b2a3624c2928d7fc02bd4/pkgs/development/tools/misc/netcoredbg/default.nix#L52.
* `pkgs/servers/jackett` could be added to it as well, see https://github.com/NixOS/nixpkgs/pull/144563.
* `pkgs/development/dotnet-modules/python-language-server` has an open PR: https://github.com/NixOS/nixpkgs/pull/144165.

Also, I use she/her pronouns :)

**Comment by prusnak** [comment]
> I have a few additions:

Added to the list in the OP

> Also, I use she/her pronouns :)

Sorry, fixed that in my post.

**Comment by jojosch** [comment]
`jellyfin` will also be using `buildDotnetModule`: https://github.com/NixOS/nixpkgs/pull/144082

**Comment by mdarocha** [comment]
I started work on porting `omnisharp-roslyn` - https://github.com/NixOS/nixpkgs/pull/178004

**Comment by mdarocha** [comment]
Started porting `eventstore` - https://github.com/NixOS/nixpkgs/pull/179187

**Comment by IvarWithoutBones** [comment]
Switched over `github-runner` in #191541.

**Comment by mdarocha** [comment]
`msbuild` should probably be removed from this list. From what I tried to refactor it, there's not much point, since it doesn't use .NET Core at any point for building, only for some small dependencies.

We can't really use the `nuget-to-nix` script in there without big changes to the script, and every build step would need overriding anyways.

**Comment by mdarocha** [comment]
I migrated `roslyn` in https://github.com/NixOS/nixpkgs/pull/202765

**Comment by JamieMagee** [comment]
I think `pkgs/development/tools/azure-functions-core-tools` is also a candidate if we start building it from source.

**Comment by mdarocha** [comment]
`github-runner` was migrated here: https://github.com/NixOS/nixpkgs/pull/218455

**Comment by prusnak** [comment]
Removing msbuild from the list as per the [comment above](https://github.com/NixOS/nixpkgs/issues/146257#issuecomment-1326900026). 

Closing the issue as all other packages have been addressed! 🎉

**Comment by mdarocha** [comment]
Sorry fo the reopen, hope this applies to this issue.

I found several packages that still use `buildDotnetPackage`:

- `./pkgs/shells/pash` - the project is archived, and the whole package seems superseeded by the official PowerShell Core. Probably should be removed from nixpkgs?

- `./pkgs/applications/misc/keepass` - this is the Keepass 2.x version, which is still built using Mono. Migrating it to `buildDotnetModule` will be probably difficult, similar to `msbuild`. Maybe we can consider either dropping the package (in favour of KeepassX) or migrating to a standard `stdenv.makeDerivation`, in order to lessen the dependency on`buildDotnetPackage` (which we should work on removing)?

**Comment by mdarocha** [comment]
Ok, closing and moving the rest of the issues to https://github.com/NixOS/nixpkgs/issues/234775
