### ISSUE TITLE
Elasticsearch lack environment variables

### ISSUE THREAD

**Issue by yogsototh** [NixOS/nixpkgs#14667]
## Issue description

The elasticsearch returns: "You must set the ES_HOME var"

### Steps to reproduce

~~~
> nix-shell -p elasticsearch
[nix-shell:~] elasticsearch
You must set the ES_HOME
~~~

or

~~~
> nix-env -i elasticsearch-1.7.2
> elasticsearch
You must set the ES_HOME
~~~

## Technical details

* System: Mac OS X El Capitan 10.11.4 (Darwin Kernel Version 15.4.0)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre80183.551296a

**Comment by grahamc** [comment]
I'm not sure how to fix this, because it is a problem of just installing the Elasticsearch executables but not setting up the Elasticsearch service. ES_HOME needs to point to a data directory. Since Nix only manages /nix/store and the module system used on NixOS is what configures the services and /var directories, I'm not sure how to resolve your problem.

I believe the responsibility sits in your default.nix or shell.nix or whatever to set `ES_HOME` to where you want it.

Does that make sense? Am I wrong about the Nix / NixOS split?

**Comment by yogsototh** [comment]
I believe you are completely right. Sorry I'm just a complete n00b and I was just thinking about using `nix` as a cooler `brew` for Mac. I managed to make `elasticsearch` work correctly using the right `default.nix`.

Thanks, and sorry for the lost time.

**Comment by grahamc** [comment]
No worries! I think this is a common source of confusion, but I'm not particularly sure how to fix it.

**Comment by willian** [comment]
> I believe you are completely right. Sorry I'm just a complete n00b and I was just thinking about using `nix` as a cooler `brew` for Mac. I managed to make `elasticsearch` work correctly using the right `default.nix`.
> 
> Thanks, and sorry for the lost time.

Can you share how you make that work? I am trying to install elasticsearch v6.x on my mac with nix but it does not work. This is the problem I am having: https://github.com/NixOS/nixpkgs/issues/56536
