### ISSUE TITLE
Qt 5's new build hook breaks popular qmake pattern

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14670]
## Issue description

With new Qt 5 hook user must run `preConfigure` to ensure that specially-crafted `qmake` gets in path or use `$QMAKE` -- otherwise it won't work. This breaks a rather popular pattern of doing `configurePhase = "qmake PREFIX=$out";`. I think this is a good use case and we shouldn't break it.

From what I see in the hook it sets several things in `envHook` and then adds `qmake` to `PATH` only in `preConfigureHook`. Why can't we add it earlier? Maybe do it in some other hook? I would have proposed a patch myself but I can't understand at which point `envHooks` are called -- there is no mention of them in `setup.sh`.

cc @ttuegel

**Comment by ttuegel** [comment]
> This breaks a rather popular pattern of doing configurePhase = "qmake PREFIX=$out";. I think this is a good use case and we shouldn't break it.

This pattern should be discouraged; it makes it impossible to take advantage of the new multiple-outputs features. More generally, we should discourage overriding individual phases rather than writing a custom builder. Each phase does much more than call one command and overriding individual phases is likely to break things.

We should export a `qmakeConfigurePhase` from `qtbase` that calls all the pre- and post-hooks and encourage maintainers to do `configurePhase = qmakeConfigurePhase` instead.

> Why can't we add it earlier?

It has to be prefixed to `PATH` after everything else so that the local `qmake` binary is found before any others.

> I would have proposed a patch myself but I can't understand at which point envHooks are called -- there is no mention of them in setup.sh.

I don't remember where this is documented, but each of the `envHooks` is called once for every (transitive) dependency.

**Comment by abbradar** [comment]
Sounds good to me. I can mass-replace those today. Why won't we also run `qmake` by default, like `cmake` does?

**Comment by vcunat** [comment]
It's a question whether most Qt users also use `qmake`... but we might add `qt.qmake` attribute for that purpose (including mainly a hook to override `configurePhase`).

**Comment by vcunat** [comment]
... so like you just do `buildInputs = [ cmake ];`, you could do the same with `qmake`.

**Comment by abbradar** [comment]
Indeed, I've not thought of this. I like adding `qmakeHook` (analogous to `autoreconfHook`) derivation more than `qmakeConfigurePhase` string attribute -- what do you think?

**Comment by vcunat** [comment]
The main advantage I see is that build-input hooks are very flexible &ndash; if there is a need, they can change any phase, any variables, etc... and you don't need to touch any of the "call sites".

**Comment by abbradar** [comment]
Alright, I'll go on and try to implement this.

**Comment by ttuegel** [comment]
> so like you just do buildInputs = [ cmake ];, you could do the same with qmake.

Oh, I like this idea even better. Also, this way we can offload all that awful symlink-farm business from the `qtbase` setup hook into the `qmake` setup hook.
