### ISSUE TITLE
Channels advancing ahead of cache availability

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#147320]
### Describe the bug
I don't know if "channel update" and "git tag pushed" are separate events, but I have ANOTHER CI job from today where I updated to latest `nixos-unstable` and then had to wait an hour while the world built.

A job that ran a bit later ran in 10 minutes and then failed to push the ref because the older, longer job finished.

see also: https://github.com/NixOS/nixpkgs/issues/146719

First things first:
* is the "channel update" done synchronously with the git tag push?

**Comment by lukegb** [comment]
Are the packages in question part of the `tested` job?

If not, then they are not required for the channel to advance, and may not be built (even if they *are buildable*) when the channel tag is advanced - this usually only happens when builds are cancelled or if a prerequisite build ends up scheduled on a bad machine that errors out during the build somehow.

(This probably does mean that more things that we consider essential should be part of this jobset, though...)

But otherwise: no, the cache should be populated as soon as things are built, independently of the tag being advanced. Even builds which never make it into a version of nixpkgs pushed to one of the "tag branches" make it into the cache, I believe.

**Comment by colemickens** [comment]
My pretty big apologies here, re-examining the log, I have to be suspicious of something else. It seems like maybe there's just the gap around jobs being canceled and the job being treated as success.

I'm going to close this and not re-open it without more conclusive logs. I shouldn't have been doing so many things at once.

**Comment by vcunat** [comment]
This time we had no significant cancellations or failures, though.

**Comment by colemickens** [comment]
To re-iterate, this was just a mistake on my part. I saw a few CI jobs taking a long time right around channel advancement.

It turns out, there were just packages to build for `nixpkgs-wayland`, and I suspect my runners got scheduled on slow hosts.

Just poor form on my part, if I'd posted logs to go with this issue in the first place I'd have noticed that it wasn't the same issue.
