### ISSUE TITLE
abricotine

### ISSUE THREAD

**Issue by schlichtanders** [NixOS/nixpkgs#148152]
**Project description**
Abricotine is an open-source markdown editor built for desktop.

Desktop markdown editor with inline preview

**Metadata**

* homepage URL: http://abricotine.brrd.fr/
* source URL: https://github.com/brrd/abricotine/tree/master
* license: gpl3
* platforms: unix, linux, darwin, windows, ...

**Comment by WolfangAukang** [comment]
There is a set of issues with this application, unfortunately:

- Uses a very old Electron version (6). Currently we are on 16. That's not a major issue though.
- Now, it does not create the .config directory with the correct permissions, so I get a bunch of permission errors:

```
[
  [Error: EACCES: permission denied, mkdir '/home/bjorn/.config/Abricotine/app/dict/da_DK'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'mkdir',
    path: '/home/bjorn/.config/Abricotine/app/dict/da_DK'
  },
  [Error: EACCES: permission denied, mkdir '/home/bjorn/.config/Abricotine/app/dict/de_DE'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'mkdir',
    path: '/home/bjorn/.config/Abricotine/app/dict/de_DE'
  },
  [Error: EACCES: permission denied, mkdir '/home/bjorn/.config/Abricotine/app/dict/en_US'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'mkdir',
    path: '/home/bjorn/.config/Abricotine/app/dict/en_US'
  },
  [Error: EACCES: permission denied, mkdir '/home/bjorn/.config/Abricotine/app/dict/es'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'mkdir',
    path: '/home/bjorn/.config/Abricotine/app/dict/es'
  },
```

And with that, you get the error
```
·> ./result/bin/abricotine
Error while loading localization data: Error: ENOENT: no such file or directory, open '/home/bjorn/.config/Abricotine/app/lang/en.json'
```

I can try to replicate the directories at the beginning, but who knows if that would work, plus it would make the process more cumbersome.

**Comment by WolfangAukang** [comment]
Regarding the permission issue, here are:
- [Line in charge of indicating where to retrieve the config files](https://github.com/brrd/abricotine/blob/d65bf8211540c26f7549fec9d4877e3b482a7007/app/constants.js#L24)
- [Line in charge of the action of copying the config files](https://github.com/brrd/abricotine/blob/d65bf8211540c26f7549fec9d4877e3b482a7007/app/creator.js#L17)

Let me explain what happens:

- As we need to pack it from the asar (as it is an Electron application), it will try to pick the files from `$out/opt/abricotine/resources/app.asar.unpacked/default` and put it at `~/.config/Abricotine`.
- The problem is, when you package something on Nix, you won't be able to write on these files after built neither set them as writable (as it would defeat its purpose), and the code is just copying the content of that directory without verifying if the target is writable in the end. Hence, packaging this on NixOS without a hacky workaround is impossible.

**Comment by schlichtanders** [comment]
Hi @WolfangAukang 
thank you very much for explaining the difficulty of the situation.
Very impressive how a package can be setup such that it is impossible for it to be build on NixOS.

What would be the hacky workaround to at least try it out on NixOS (within an overlay or nix-shell or whatever)?

**Comment by WolfangAukang** [comment]
Ready, I was able to package it. Let's see how it goes.

**Comment by schlichtanders** [comment]
Very impressive. Thank you so much @WolfangAukang 

I looked over the code and am able to understand what is going on :). Still quite some steps away from my personal skills - I would wish to be able to package this myself at some time - the config script with `set -euo pipefail` is new to me (really good to know), the `copyDesktopItems` (nice one!), the electron runner, and some parts here and there. Looks very concise altogether. 

Thank you. Looking forward to try abricotine and also I learned a lot.

**Comment by WolfangAukang** [comment]
@schlichtanders Unfortunately, Nixpkgs dropped support to Electron 6. As the application hasn't brought up newer versions, the only option would be asking the dev for newer versions and see if they can upgrade the support to a newer Electron version.

**Comment by WolfangAukang** [comment]
[The developer decided to not continue with the project](https://github.com/brrd/abricotine/issues/310#issuecomment-974038822). I will close the PR as porting this wouldn't be accepted by the commiters, but in case someone decides to fork it and improve the Electron support, I can definitely port it.
