### ISSUE TITLE
package-request: deep-translator

### ISSUE THREAD

**Issue by juligreen** [NixOS/nixpkgs#148572]
**Project description**
Python package and command line tool to translate between different languages in a simple way using multiple translators.

**Metadata**

* homepage URL: https://deep-translator.readthedocs.io/en/latest/
* source URL: https://github.com/nidhaloff/deep-translator
* license: mit
* platforms: unix, linux, darwin, etc (python package)

**Comment by WolfangAukang** [comment]
The main issue packaging this library is regarding tests and verification. When I try to package it, I need to disable both `doCheck` and `pythonImportsCheck`, because the initialization of a `deep_translator` instance requires contacting an API and fails with a "Name or service not known" (which I believe it is intended as the build environment is isolated):
```
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffff5d735b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

If I build it with no imports or test checks, I can use the binary successfully:
```
·> ./result/bin/deep-translator translate -src "en" -tgt "de" -txt "keep it up, you are awesome"
 | Translation from en to de |
Translated text:
 mach weiter so du bist toll
```

**Comment by WolfangAukang** [comment]
Merged
