### ISSUE TITLE
curl unable to establish ssl connections since update to 21.11

### ISSUE THREAD

**Issue by liketechnik** [NixOS/nixpkgs#148686]
### Describe the bug
curl is unable to establish SSL connections and exits with `curl: (60) SSL certificate problem: unable to get local issuer certificate`, though that can be circumvented (see reproduction).

### Steps To Reproduce
1. Try to connect to an https url with curl:

```sh
$ curl https://curl.se/download/curl-7.80.0.tar.gz
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

2. The error can be circumvented using nix's `SSL_CERT_FILE` env variable and curl's ability to read the env variable `CURL_CA_BUNDLE` (cf. https://curl.se/docs/sslcerts.html):

```sh
$ CURL_CA_BUNDLE=$SSL_CERT_FILE curl https://curl.se/download/curl-7.80.0.tar.gz --output /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4069k  100 4069k    0     0   959k      0  0:00:04  0:00:04 --:--:--  959k
```

### Expected behavior
curl successfully establishes ssl connection without having to specify any variables or options.

### Additional context
Looking at the git history of curl, 4e1b102af618fc3e8da11da8a0cea28e5c104f3a might be relevant, though I don't have any idea if it really is (e. g. I don't know anything about building/packaging curl and/or ssl stuff on nix).

Not sure if relevant, but my system is using nix flakes.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/p5lnl4zr45n7mf9kz9w8yz3rqh001b5c-bash-interactive-4.4-p23-dev
copying path '/nix/store/p5lnl4zr45n7mf9kz9w8yz3rqh001b5c-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.2-xanmod1-tt, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ckiee** [comment]
I can reproduce this with `curl https://www.webtoons.com/en`, `https://curl.se` returns a certificate that doesn't explode.

**Comment by cyounkins** [comment]
I think this is #3382 ?

**Comment by cyounkins** [comment]
I'm having some SSL cert issues too, not sure if they are related. I'm on freshly updated 21.05.

```
$ curl -v 'https://diagnostic.opendns.com'
*   Trying 34.117.80.25:443...
* Connected to diagnostic.opendns.com (34.117.80.25) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
....

$ curl -v 'https://www.webtoons.com'
*   Trying 203.104.164.11:443...
* Connected to www.webtoons.com (203.104.164.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
...

$ sha256sum /etc/ssl/certs/*
80721e0ae70f70606885864a1bca218110476bca60e1a34862ce139561d1203e  /etc/ssl/certs/ca-bundle.crt
80721e0ae70f70606885864a1bca218110476bca60e1a34862ce139561d1203e  /etc/ssl/certs/ca-certificates.crt
$ echo $SSL_CERT_FILE

$
```

`curl.se` works for me. The above `unable to get local issuer certificate` is reproducible in the latest Ubuntu docker image, which makes me think the issue lies somewhere upstream.

At this time, both domains above have incomplete chains: [OpenDNS](https://www.ssllabs.com/ssltest/analyze.html?d=diagnostic.opendns.com) [Webtoons](https://www.ssllabs.com/ssltest/analyze.html?d=www.webtoons.com) but the intermediate certs are described as "DigiCert TLS RSA SHA256 2020 CA1" and "GeoTrust RSA CA 2018" so they don't seem new.

If you are able to reproduce with `curl.se`, post full output with `-v` so we can validate the IP.

**Comment by cyounkins** [comment]
I looked at this a little more, and I believe in my case the reason for curl reporting "unable to get local issuer certificate" is due to the incomplete certificate chain presented by the remote server. Browsers and OS-level cert management tools may cache or are able to look up intermediate certs, but not with curl. It is best practice for the servers to provide the full chain, so it may be worth contacting OpenDNS and Webtoons to correct the issue.

`curl.se` should be configured correctly. If you experience an issue with that domain, you should verify that your DNS is not hijacked and that curl can find the certificate bundle. On NixOS, verify `/etc/ssl/certs/ca-bundle.crt` exists and try `CURL_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt curl -v 'curl https://curl.se'`. If that path does not exist, try adding `cacert` to `systemPackages`.

**Comment by ckiee** [comment]
> so it may be worth contacting OpenDNS and Webtoons to correct the issue.

Recently my bot started delivering comic updates for the ones hosted on Webtoons again so it seems they noticed the problem and fixed it (:

p.s. that `/etc/ssl/...` path is fine

**Comment by pmarreck** [comment]
Just mentioning that I saw this issue with curl as well, and the fix was @liketechnik 's solution, which I materialized declaratively with this config in configuration.nix:
```
  environment.variables = {
    # ...
    # fix for this curl issue with https requests: https://github.com/NixOS/nixpkgs/issues/148686
    CURL_CA_BUNDLE = "/etc/pki/tls/certs/ca-bundle.crt"; # this is the value of $SSL_CERT_FILE ; may be brittle
  };
```
I will next try to add `cacert` to my `systemPackages` and remove this extra env config to see if that fixes it without the brittleness

**Comment by ckiee** [comment]
It hasn't been happening here either.
