### ISSUE TITLE
git-annex broken in master

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#148780]
According to https://hydra.nixos.org/job/nixpkgs/trunk/git-annex.x86_64-linux, the build was broken 2 days ago when the test suite started failing. git-annex itself doesn't appear to have changed, so it's probably a side-effect of some other update.

**Comment by Retrodynen** [comment]
[https://git-annex.branchable.com/bugs/git_2.34__58___some_conflict_resolution_unit_tests_fail/](https://git-annex.branchable.com/bugs/git_2.34__58___some_conflict_resolution_unit_tests_fail/)

Appears fixed in [https://git-annex.branchable.com/news/version_8.20211123/](https://git-annex.branchable.com/news/version_8.20211123/)

I'm new to NixOS so not sure the best procedure in updating the version used in the hackage part of nixpkgs but hopefully the above helps somewhat.

**Comment by sternenseemann** [comment]
Indeed, this regression was introduced via `staging-next` where the `git-annex` failure wasn't caught. Fixed on master as of 34bc3e2ae898f6f6eff2747b2e604500bfad0f5b.
