### ISSUE TITLE
android-studio can't work with read-only sdk from nixstore

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#14903]
So the name tells it all. Using the latest android-studio from master I can't create a new project because of that error.
[Imgur](http://i.imgur.com/DQrlEkI.png)

**Comment by jagajaga** [comment]
cc @the-kenny

**Comment by jagajaga** [comment]
The solution I've found is to use this [nix-shell](http://p.tarn-vedra.de/nixos-android.nix.html) configuration. Download both android-studio and android-sdk from google and run it. Also I've told android-studio that my android-sdk is located in a folder of extracted android-sdk I've downloaded frim google.

**Comment by the-kenny** [comment]
Good to hear you got it working! I wonder why android-studio even needs writable paths. Things like react-native work just fine. Did you try if the fhsUserEnv allows you to install other sdk packages via the `android` tool?

**Comment by Mathnerd314** [comment]
This seems similar to https://github.com/NixOS/nixpkgs/issues/8650.

**Comment by bobvanderlinden** [comment]
@jagajaga That seems to me like the way to go for Android development. Is there some way to get that into nixpkgs in a clean manner? At the moment Android Studio seems useless on NixOS without such FHS additions. The package for Steam seems to do something similar.

**Comment by Sicaine** [comment]
Is it possible to fix this through the package itself or is the nix-shell the only solution?

**Comment by phunehehe** [comment]
@jagajaga I wonder how do you deal with missing development headers as described in http://stackoverflow.com/q/29241640/168034?

**Comment by jagajaga** [comment]
@phunehehe somehow :)

**Comment by phunehehe** [comment]
@jagajaga I hoped that somehow doesn't involve invoking `apt-get` :)

**Comment by bjornfor** [comment]
Isn't there something that can be done here? I mean, we got steam packaged...!

**Comment by bobvanderlinden** [comment]
See https://github.com/NixOS/nixpkgs/issues/8650#issuecomment-205060988. Basically use `buildFHSChrootEnv` to create a chroot environment that looks like Debian and run Android Studio and `android` inside it. It is possible to do this as a package in nixpkgs, but I haven't found how yet. Steam seems to use a similar scheme, so that would be a first step.

The chroot will allow the use of binaries like `mksdcard` without patching. When that works, it should be possible to use `android` for package management. I'd set `ANDROID_HOME` to your home directory (probably `~/.android`) or some other user-writable directory and let `android` figure out its dependencies on its own.

This is far from ideal what you want on NixOS, but I don't see a practical alternative. Handling dependencies of Android in NixOS (like how it is packaged right now) seems like maintenance hell, since a lot needs to be patched to get the IDE working (Android Studio, `android` and any binaries that are downloaded through `android`).

**Comment by phunehehe** [comment]
@bobvanderlinden thanks! I just discovered that in parallel too, by looking for `lib32`, seeing `build-fhs-chrootenv` among the results and "oh wait this looks familiar to that shell.nix thing" :)

**Comment by Profpatsch** [comment]
Thank you very much, @phunehehe.
