### ISSUE TITLE
Packing Request: grcov

### ISSUE THREAD

**Issue by d-johnston-fugro** [NixOS/nixpkgs#149209]
**Project description**
grcov collects and aggregates code coverage information for multiple source files. grcov processes .profraw and .gcda files which can be generated from llvm/clang or gcc. grcov also processes lcov files (for JS coverage) and JaCoCo files (for Java coverage). Linux, macOS and Windows are supported.

This is a project initiated by Mozilla to gather code coverage results on Firefox.

**Metadata**

* homepage URL: https://github.com/mozilla/grcov
* source URL: https://github.com/mozilla/grcov
* license: MPL2
* platforms: unix, linux, darwin,

**Comment by d-johnston-fugro** [comment]
I've got it building with 

```nix
# flake.nix
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-21.11";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, flake-utils, nixpkgs }: flake-utils.lib.eachDefaultSystem (system:
    let pkgs = nixpkgs.legacyPackages.${system}; in
    {
      defaultPackage = pkgs.callPackage ./package.nix { };
    });
}
```
```nix
# package.nix
{ lib, fetchFromGitHub, rustPlatform }: rustPlatform.buildRustPackage rec {
  pname = "grcov";
  version = "v0.8.2";

  src = fetchFromGitHub {
    owner = "mozilla";
    repo = pname;
    rev = version;
    sha256 = "t1Gj5u4MmXPbQ5jmO9Sstn7aXJ6Ge+AnsmmG2GiAGKE=";
  };

  cargoSha256 = "DRAUeDzNUMg0AGrqU1TdrqBZJw4A2o3YJB0MdwwzefQ=";

  meta = with lib; {
    description = "grcov collects and aggregates code coverage information for multiple source files.";
    homepage = "https://github.com/mozilla/grcov";
    license = licenses.mpl20;
  };
}
```

**Comment by DieracDelta** [comment]
@AndersonTorres thoughts on merging this into nixpkgs? I did a version bump, and things *seem* to work apart from a few failing tests. Two of the integration ones are weird linking errors (these seem like edge cases for a very specific test case), and the rest is just being unable to find the `grcov` executable since it's not in the expected location of `./target/(release|debug)/grcov`. I don't think these are show-stoppers. It would be helpful (for me at least) to merge this into nixpkgs instead of copying this overlay around, since this mostly seems to work in my limited testing. As for skipping failing tests we can do something akin to the blightmud derivation and have 

```nix
  checkFlags = let
    skipList = [ "some" "failing" "test" "names" ];
    skipFlag = test: "--skip " + test;
  in builtins.concatStringsSep " " (builtins.map skipFlag skipList);
```

If you don't have the time, I'd be happy to edit the expression to explicitly skip the failing tests and bump input version, then open a PR.

**Comment by AndersonTorres** [comment]
@DieracDelta good, please do it. I can review and merge if you like.

**Comment by DieracDelta** [comment]
This has been mergeed into nixpkgs
