### ISSUE TITLE
Two slashes in URL which should be one slash

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#14948]
Notice the two slashes:

```
 nix-channel --update
downloading Nix expressions from ‘https://nixos.org/releases/nixos/16.03/nixos-16.03.616.4ac4b35//nixexprs.tar.xz’...
```
 while I have

```
nix-channel --list
nixos https://nixos.org/channels/nixos-16.03
```

It might "work", but it is -- again -- sloppy.

**Comment by joachifm** [comment]
What is the problem, exactly? Doing `head + '/' + tail` is a simple method of ensuring that the result is usable, checking whether `head` contains a trailing slash seems like a waste of time to me.

Anyway, this is a Nix issue, not a nixpkgs issue.

**Comment by 0xABAB** [comment]
@joachifm The problem is that there is end-user visible URLs which look wrong; no human would ever enter that. If I have to explain this further, I think you just lack the engineering quality of "taste". 

In case you are wondering why double slashes might be wrong, see my recent "NixOS doesn't boot" issue.

It is ridiculous to phrase this as an optimization. 

Programming wise doing `head + '/' + tail` is also amateur programming (I didn't check whether this is really being done, but I really hope not). It would *never* enter any of the codebases I am responsible for. 

I actually find it surprising (and highly annoying) that anyone can disagree on this. Let's hope you don't have too much influence in this project.

**Comment by joachifm** [comment]
On Sun, Apr 24, 2016, at 05:17 PM, 0xABAB wrote:
> @joachifm The problem is that there is end-user visible URLs which look
> wrong; no human would ever enter that. If I have to explain this further,
> I think you just lack the engineering quality of "taste". 
> 
> In case you are wondering why double slashes might be wrong, see my
> recent "NixOS doesn't boot" issue.
> 
> It is ridiculous to phrase this as an optimization. 
> 
> Programming wise doing `head + '/' + tail` is also amateur programming (I
> didn't check whether this is really being done, but I really hope not).
> It would *never* enter any of the codebases I am responsible for. 
> 
> I actually find it surprising (and highly annoying) that anyone can
> disagree on this. Let's hope you don't have too much influence in this
> project. 

Relevant code is here:
https://github.com/NixOS/nix/blob/master/scripts/nix-channel.in#L134

You might have had a point if the URLs where generated for any other
reason than to be fed directly into curl. This isn't about optimization,
it's about what to spend programmer time on.

All you ever do is complain, in the rudest manner possible. If you
expect others to do the work for you, at least provide a compelling
value proposition. At the very least, use your godlike genius to pick
the right issue tracker to complain on.

As for the rest of your rant ... all I can say is, why don't you
contribute instead of playing tough guy on the issue tracker?

**Comment by grahamc** [comment]
@0xABAB Could you submit a PR to fix https://github.com/NixOS/nix/blob/master/scripts/nix-channel.in#L134 in the double-slash case?

**Comment by 0xABAB** [comment]
@joachifm There *is* another point, which is that the user *sees* the curl command. That means it becomes part of the UI and the UI is screaming that the programmer likely made a mistake. The mere coincidence that this is not the case is not relevant to the argument.

**Comment by globin** [comment]
As this is in nix I'm closing this.
