### ISSUE TITLE
Mounting /nix/store and updating grub results into unbootable system

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#14999]
According to https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/grub/install-grub.pl#L117 if `/nix/store` is mounted as not `ro`, then it's accounted for as mount on a different drive.

This renders into unmountable boot as grub config is corrputed for linux kernel:

```
linux ($drive2)//y2jbh18qavl269dmij1frgczxg4lfw4g-linux-4.4.6/bzImage systemConfig=/nix/store/c8djqbq1a0f76zjigpkaq5hzijwbybmp-nixos-system-lugano-2-16.03.616.4ac4b35 init=/nix/store/c8djqbq1a0f76zjigpkaq5hzijwbybmp-nixos-system-lugano-2-16.03.616.4ac4b35/init intel_iommu=off hugepages=4096 panic=60
```

While we don't support setting `/nix/store` as rw, I think this should be fixed regardless as it holds on assumption that might not be true on other cases.

**Comment by dezgeg** [comment]
We do have the `nix.readOnlyStore` option.

**Comment by domenkozar** [comment]
We could add a check to the grub install if kernel path really exists (and similarlly for others).

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by wkennington** [comment]
The problem is that the grub path is relative to the mount point it exists
on. Not root.

**Comment by wkennington** [comment]
Note, this shouldn't affect users of the read-only store option as this
doesn't cause the nix store to be directly mounted rw. This really only
happens for cases where you have a ro store and remount it rw.

**Comment by 0xABAB** [comment]
@domenkozar Nice detective work.

**Comment by domenkozar** [comment]
@wkennington you're the author of https://github.com/NixOS/nixpkgs/commit/f73f7ccc6e0b17d08d2ef689b76755769d3663b4, could you explain what's going on here? It's quite some edge cases and no comments why they could happen.

Could we just check for `/nix/store` and skip the ro check?

**Comment by bjornfor** [comment]
Hit this again today. (Long story, not bothering you with the details. Luckily it's fixable: insert missing "/nix/store" strings in /boot/grub/grub.cfg.)

**Comment by 0xABAB** [comment]
I am running 14.12; can I upgrade to the latest stable version without breaking already if I do that with /nix mounted ro (ZFS)? I only care about it booting and having SSH up.

**Comment by domenkozar** [comment]
I've hit another instance of this, but I'm sure it wasn't due to `rw` flag. I would really like to catch these errors since it's really annoying to get unbootable server.

**Comment by domenkozar** [comment]
Opened https://github.com/NixOS/nixpkgs/issues/17531 to address this.

**Comment by therealpxc** [comment]
On my system the kernel images were actually missing (the symlinks under /nix/store/<path-to-nixos-system>/kernel were broken links). Inserting /nix/store/<whatever> likely would not fix things then, right?

There's a chance that was caused by the same issue, I don't recall if I looked at their full paths. But when I tried to do tab completion from my recovery media (based on the hashes in my /boot/grub/grub.cfg file) it didn't spell out the kernel images. I'm not sure if my system was really screwed up or I just didn't type enough characters for the completion. :-\

**Comment by symphorien** [comment]
This has happened to me dozens of times because I was launching `nixos-rebuild` from a (root) nix-shell : see #27362 
Besides, I acknowledge that remounting the store read write (even willingly) is a bad pratice, but it should not result in an unbootable system.

**Comment by butterflya** [comment]
```
# Figure out what filesystem is used for the directory with init/initrd/kernel files
```
Can anyone please rewrite the purpose of that function in a way that is unambiguous? 

I am fairly sure I could replace some 70 lines of code with 5 or so that would be more robust, if that's done.

**Comment by symphorien** [comment]
It takes a path to a file in argument, and returns a struct (pardon my lack of  knowledge in proper perl vocabulary) containing information on the filesystem of the disk where this file lives : 
* `type` is the filesystem type (ext4, btrfs)
* `device` is the device file from where this filesystem can be mounted, for example `/dev/disk/by-uuid/f2eb657e-4c6c-4a53-b3db-67d1c4f7812d`
* `mount` is the mountpoint of the top of the filesystem of that device, excluding bind mounts because that early in the boot process, grub can't see those bind mounts

Hope it's clear and correct

**Comment by butterflya** [comment]
@symphorien Just calling `df` also does that. See: https://askubuntu.com/questions/23710/find-out-what-filesystem-a-file-or-directory-is-part-of

**Comment by symphorien** [comment]
yes but it doesn't seem to have an option to ignore bind mounts

**Comment by butterflya** [comment]
@symphorien  https://unix.stackexchange.com/questions/18048/list-only-bind-mounts lists various mechanisms that depend on the specific OS. NixOS could be modified to support one of these methods if it doesn't already.

**Comment by fpletz** [comment]
See https://github.com/NixOS/nix/issues/1336 for the read-writable nix store in root nix-shells.
