### ISSUE TITLE
KDE 5 does not find shared_mime_info installed as user

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#15006]
KDE 5 needs shared_mime_info to be installed system-wide. I do not understand why, yet; it may need to be patched.

**Comment by vandenoever** [comment]
I think this is regression from NixOS 15.09.

The problem is not just with KDE. It's with fundamental tools like `xdg-mime`.
An easy way to test is with `xdg-mime`. It should work like this:
```bash
$ xdg-mime query filetype .
inode/directory
```
From using `strace` on `xdg-mime` i learned a few things.
XDG_DATA_DIRS is used to find mime information under `$dir/share/mime`. If `$dir/share/mime/mime.cache` is found that is used. Otherwise `$dir/share/mime/types` is read.
When shared_mime_info is installed system-wide, a basic set of mime information is available under `/run/current-system/sw/share/mime/`.

**Comment by vandenoever** [comment]
Is this closed because shared_mime_info does not need to be system-wide anymore or because it is installed system-wide now?

**Comment by ttuegel** [comment]
It should be installed system wide now, but it was evidently not KDE's problem in any case.
