### ISSUE TITLE
vimPlugins.vim-colorschemes have hash mismatch

### ISSUE THREAD

**Issue by KAction** [NixOS/nixpkgs#151350]
### Steps To Reproduce

```
:; nix-build -A vimPlugins.vim-colorschemes
these 2 derivations will be built:
  /nix/store/03k8iyms9hadvk2a8csalqhnlr3s7nb3-source.drv
  /nix/store/8ifriy2q0mymvs2iip7pwmziqqd3iqyg-vimplugin-vim-colorschemes-2020-05
-15.drv
building '/nix/store/03k8iyms9hadvk2a8csalqhnlr3s7nb3-source.drv'...


trying https://github.com/flazz/vim-colorschemes/archive/fd8f122cef604330c96a6a6
e434682dbdfb878c9.tar.gz
trying https://github.com/flazz/vim-colorschemes/archive/fd8f122cef604330c96a6a6
e434682dbdfb878c9.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
                                 Dload  Upload   Total   Spent    Left  Speed
100   164  100   164    0     0   1197      0 --:--:-- --:--:-- --:--:--  1205
100   164  100   164    0     0   1197      0 --:--:-- --:--:-- --:--:--  1205
100 1216k    0 1216k    0     0  1547k      0 --:--:-- --:--:-- --:--:-- 2826k
100 1216k    0 1216k    0     0  1547k      0 --:--:-- --:--:-- --:--:-- 2826k
unpacking source archive /build/fd8f122cef604330c96a6a6e434682dbdfb878c9.tar.gz
unpacking source archive /build/fd8f122cef604330c96a6a6e434682dbdfb878c9.tar.gz
hash mismatch in fixed-output derivation '/nix/store/2r0hrjgnhb8nyf5zh0gn8xwyqxa
zrg9f-source':
  wanted: sha256:0kpsf6j20fgblc8vhqn7ymr52v2d1h52vc7rbxmxfwdm80nvv3g5
  got:    sha256:1cg8q7w0vgl73aw1b9zz0zh5vw5d2pm8pm54fhfzva4azg56f416
cannot build derivation '/nix/store/8ifriy2q0mymvs2iip7pwmziqqd3iqyg-vimplugin-v
im-colorschemes-2020-05-15.drv': 1 dependencies couldn't be built
error: build of '/nix/store/8ifriy2q0mymvs2iip7pwmziqqd3iqyg-vimplugin-vim-color
schemes-2020-05-15.drv' failed
```

**Comment by hqurve** [comment]
This problem seems to no longer exist on master however it is interesting that the hash (and only the hash) has been oscillating between 0kpsf6j20fgblc8vhqn7ymr52v2d1h52vc7rbxmxfwdm80nvv3g5 and 1cg8q7w0vgl73aw1b9zz0zh5vw5d2pm8pm54fhfzva4azg56f416.

Result from `git log -L7328,7338:generated.nix` on master(`f403d1f7913da888ace330636315a766cf6ac5dc`)

- 2021-05-28: (`9afcc52f0d2c29a01060050399384c7b23118c30`) the plugin was updated to 2020-05-15 and its has was 1cg8....
- 2021-05-27: (`d4de973c917d4bdc74dd2eff3ac027c03a3b3b72`) it was changed to 0kps...
- 2021-06-03: (`e317f994d2ffbeaca1bd7b1d6decf942b9c19880`) it was changed to 1cg8...
- 2021-11-12: (`af115051b8cb3fed175bdfefca0e95efe76966d2`) it was changed to 0kps...
- 2021-11-16: (`2284d771dba1b1ca96059ae9d28effe2da5a13c3`) it was changed to 1cg8...
- 2021-12-15: (`2edd8e6c73e79844714915798772c6f4b7b4a9e4`) it was changed to 0kps...
- 2021-12-18: (`5dd8c8cb1c1867a8a79bf602c978ba3ec8a4f8fc`) it was changed to 1cg8...

(this is concerning)

**Comment by teto** [comment]
closing in favour of the linked issue that has more information.
