### ISSUE TITLE
nix search disable auto update

### ISSUE THREAD

**Issue by s9gf4ult** [NixOS/nixpkgs#151533]
### Describe the bug

There is no flag disabling auto updating the packages database. Every time I enter `nix search` it downloads about 26 megs of data. It is not acceptable behavior on a flaky mobile network and/or when internet is not available at all. 

### Steps To Reproduce
1. `nix search nixpkgs firefox`

### Expected behavior

Do not download files from then Internet, just use existing database. Or have special flag to force using existing database (with warning or something).

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by veprbl** [comment]
Please file this to https://github.com/NixOS/nix/issues

**Comment by L-as** [comment]
This is really an issue with documentation for flakes.
In the default global registry, `nixpkgs` is an alias for `github:NixOS/nixpkgs`. This means that when you access the flake, it gets the latest commit. This is obviously a problem as you can tell.
You can do something like the following if you're using flakes for your NixOS configuration:
```nix
{ config, lib, pkgs, inputs, ...}:

{
  nix.registry.nixpkgs.flake = inputs.nixpkgs;
  nixPath = [ "nixpkgs=${inputs.nixpkgs}" ];
}
```
`inputs` isn't there by default. To get it you must do something like the following:
```nix
    nixosConfigurations.example = inputs.nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [ mymodule ];
      specialArgs = { inherit inputs; };
    };
```
The result of evaluating the flake should be cached too, since the commit doesn't change every time.
