### ISSUE TITLE
buildPythonPackage does not seem to be verifying the sha256 checksum

### ISSUE THREAD

**Issue by vrthra** [NixOS/nixpkgs#15311]
## Issue description
I was trying to add `python-datetime_2_2` package to `pkgs/top-level/python-packages.nix`. To do that, I copied `python-datetime_2_1` declaration, and changed the version in the name. I discovered that even if I did not correct the sha256 key, the package gets installed. For some reason, I can only use the keys from previous `python-datetime_x_y` packages -- see commented out shas.

### Steps to reproduce
Apply the below patch, and run `nix-env -f $MYPKGS -i python2.7-dateutil-2.2` this should install the correct version of datetime util. Now comment out the current sha, and uncomment one of the commented sha. If you try to unistall and install again, with the changed sha, it will allow it.

```
diff --git a/pkgs/top-level/python-packages.nix b/pkgs/top-level/python-packages.nix
index 297dfae..07052a0 100644
--- a/pkgs/top-level/python-packages.nix
+++ b/pkgs/top-level/python-packages.nix
@@ -4750,6 +4750,29 @@ in modules // {
     };
   });
 
+  # csvkit 0.9.1 needs dateutil==2.2
+  dateutil_2_2 = buildPythonPackage (rec {
+    name = "dateutil-2.2";
+
+    propagatedBuildInputs = with self; [ self.six ];
+
+    buildInputs = [ pkgs.glibcLocales ];
+
+    src = pkgs.fetchurl {
+      url = "mirror://pypi/p/python-dateutil/python-${name}.tar.gz";
+      #sha256 = "02dhw57jf5kjcp7ng1if7vdrbnlpb9yjmz7wygwwvf3gni4766bg";
+      #sha256 = "1vlx0lpsxjxz64pz87csx800cwfqznjyr2y7nk3vhmzhkwzyqi2c";
+      sha256 = "0s74ad6r789810s10dxgvaf48ni6adac2icrdad34zxygqq6bj7f";
+  
+    };
+
+    meta = {
+      description = "Powerful extensions to the standard datetime module";
+      homepage = http://pypi.python.org/pypi/python-dateutil;
+      license = "BSD-style";
+    };
+  });
+
   # Buildbot 0.8.7p1 needs dateutil==1.5
   dateutil_1_5 = buildPythonPackage (rec {
     name = "dateutil-1.5";

```

## Technical details

* System: `16.03.714.69420c5 (Emu)`

* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03.657.0c12bab"

**Comment by copumpkin** [comment]
This is standard (if unintuitive) nix behavior, if I'm understanding you correctly. `fetchurl` is a fixed-output derivation and really only cares about the output hash. It doesn't care where you got the content, as long as you have the correct hash (which makes intuitive sense, in a world with mirrors and spotty connectivity). When you copied the hash from another package, it looked to see if it already had that hash and just used it. For all it knows, you changing the URL was because that particular mirror was down.

One approach I've seen `fetchFromGitHub` take is to make the `basename` of the URL play a part in the final output hash, which makes confusing things like this go away, but costs us some flexibility.

Anyway, when copying around fixed-output derivation hashes, corrupt them a little (flip a non-zero digit to zero) before running a build.

**Comment by vrthra** [comment]
I worked around in the manner you described, by corrupting the hash a little. I see what you mean. The hash is just used in a lookup, and fetched only if it is not already present.

Since this still seems a faulty behavior, I am wondering if one could check if there are multiple rules for fetching the same hash in the same config, and trigger an error if there is.

**Comment by FRidh** [comment]
While I understand the issue (I've been bitten by it myself as well...) this isn't an issue of `buildPythonPackage` but, as @copumpkin wrote, Nix behavior. Therefore I am closing this issue.
If you want to discuss this further I suggest opening an issue on the Nix tracker.
