### ISSUE TITLE
Should I PR 100 typo fixes?

### ISSUE THREAD

**Issue by fetsorn** [NixOS/nixpkgs#154300]
I went through nixpkgs/master with ripgrep and found a hundred typos in about 50 packages.
Most are in the comments - some in nix files, some in patch files and other package files. Some are in package descriptions. And a couple are in top-level plain text files and docs.
I don't want to trouble the maintainers unnecessarily, so asking here beforehand.
Would a PR with fixes be likely to be accepted? Would one be useful? If so, is it better to submit one or separate PRs? e.g by package or by descriptions/comments/files/docs?

**Comment by fabaff** [comment]
From my point of view could typos in `description` be fixed in one PR. Often multiple PRs are made for such changes to keep the commits grouped and made it possible to do the reviewing in smaller portions.

Fixing typos in patch files is a different case. Patches are often downloaded from the upstream project or other distributions. If possible, should issues fixed upstream that all consumers can profit.
