### ISSUE TITLE
Have MySQL and Postgress ensureDatabases include an schema file, just like initialDatabases

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#154873]
**Project description**

Being able to initialize a database directly from the Nix configuration is very useful. I used this successfully when deploying systems where there client would offer a snapshot of the data-base or initial SQL schema to load. However, when adding new data-bases to the system, which can be done by updating `ensureDatabases`, this can not be done. However, it would make sense for it to accept schemas just like `initalDatabases` does!

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by aanderse** [comment]
You should create a `systemd` service instead to achieve this. What you're asking for is "bad" (according to nix philosophy). Consider you provide schema A and then activate the configuration. Now change your configuration to scheme B. What happens when you activate your configuration? Nothing good. You end up with a `configuration.nix` which doesn't resemble reality at all and if run again on another machine could result in a *very* different system.

You're asking for something practical. I understand that. But the "cost" of adding such a feature isn't great in my opinion.

**Comment by arximboldi** [comment]
Hi @aanderse! Thanks for the reply. I saw that you have some PR attempts to clean up this kind of state management. However I do not fully understand how such a `systemd` service would work. Would you mind elaborating a little bit?

**Comment by aanderse** [comment]
@arximboldi sure no problem.

https://github.com/NixOS/nixpkgs/blob/386234e2a61e1e8acf94dfa3a3d3ca19a6776efb/nixos/modules/services/misc/gitlab.nix#L985-L1022

Let me know if this example doesn't fill in enough blanks for you and I can lend a hand.

**Comment by arximboldi** [comment]
This is great. Thank you so much! <3
