### ISSUE TITLE
keepass: no way to install plugins

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#15514]
## Issue description

I'm trying to install a plugin to keepass. [The keepass plugin-documentation](http://keepass.info/help/v2/plugins.html) says to place it in a folder named _plugins_ next to the executable, which is in the nix store and therefore not writable.
## Technical details
- System: 6.09pre83100.25e3c09 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09pre83100.25e3c09

**Comment by Shados** [comment]
Keepass, at least in [master](https://github.com/NixOS/nixpkgs/blob/7475728593a49f09c4b7b959b15513aee38ab4b4/pkgs/applications/misc/keepass/default.nix), already has support for plugins. You'll just need to package them in Nix ([keefox](https://github.com/NixOS/nixpkgs/blob/7475728593a49f09c4b7b959b15513aee38ab4b4/pkgs/applications/misc/keepass-plugins/keefox/default.nix) already has been, as an example) and pass them to the keepass derivation's `plugins` argument.

**Comment by steveeJ** [comment]
@Shados thanks for the information. I've installed keepass and keepass-keefox from the unstable channel, but keepass doesn't detect the plugin.

**Comment by mirrexagon** [comment]
You have to tell KeePass to use the plugin by overriding the `plugins` list that gets passed to the derivation. I have something like this:

```nix
# ~/.nixpkgs/config.nix

{
  packageOverrides = pkgs: {
    keepass = pkgs.keepass.override {
      plugins = [ pkgs.keepass-keefox ];
    };
  };
}
```

**Comment by steveeJ** [comment]
@mirrexagon I've been trying to get keefox to work but I can't figure out how to. Which locations exactly are expected by keefox for it to work? The RPC plugin definitely gets loaded.

**Comment by mirrexagon** [comment]
@steveeJ I was having problems with Keefox myself (addon conflicts, and the setup message always popping up, which might've been related to the paths to KeePass and stuff), so I'm not actually using it anymore.

So yeah, sorry, I can't really help. :/

**Comment by mikael-andersson** [comment]
@steveeJ Is it still not working for you? I can try to help but I do not remember all steps to get it to work. I think I installed it from here: https://addons.mozilla.org/en-US/firefox/addon/keefox/

As for Keepass, I think I installed it by unpacking the portable version in a folder rather than installing it from the NixOS repo. The reason was because I did not really know how to install the Keepass plugins with NixOS.

**Comment by mjanczyk** [comment]
@steveeJ @mirrexagon The Keepass RPC plugin and the Firefox add-on seemingly must match version, otherwise the setup message shows up and they cannot communicate. The add-on is obviously not managed via nixpkgs, so it gets broken without a warning after add-on channel gets upgraded. E.g. I just created a PR for 1.6.4, as it stopped working for me.

It'd be great if there was a way of either documenting this, bringing that to users' attention, or automatizing version upgrades.

**Comment by steveeJ** [comment]
I'm closing this issue because it is actually possible to install plugins. @mjanczyk please open a separate issue for synchronizing plugin and addon versions, or at least the documentation thereof.
