### ISSUE TITLE
borgbackup broken under python35

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#15576]
## Issue description

295bcdfb5e6791c67dc824206f04cc037f0057cb causes this package to become unbuildable.

### Steps to reproduce

Well you an see *some* of the issue by looking at [the latest hydra build log](http://hydra.nixos.org/build/35972278/nixlog/1/raw), where `detox` fails to build.

Unfortunately, that doesn't tell the whole story---if you upgrade the `eventlet` package, you then end up with a different failure to test for `detox` that seems to be a `tox` issue---but there's no upgrade available there.  It *might* handled by PR the author hasn't yet integrated and released (https://bitbucket.org/hpk42/detox/pull-requests/4/better-python-3-support/diff).

Anyway, if you just turn off testing for `detox`, you will finally get to where `borgbackup` will fail all on its own

```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/nix/store/9rw1p5waza2ca071g2w2cqn58zpvljri-python3-3.5.1/include/python3.5m -c borg/platform_linux.c -o build/temp.linux-x86_64-3.5/borg/platform_linux.o
gcc -pthread -shared -L/nix/store/ks485pqry62dwddlqlbafhvjzpwzv1gv-zlib-1.2.8/lib -L/nix/store/granx4nac2287m1bwdlhvvg0aac5p66x-bzip2-1.0.6.0.1/lib -L/nix/store/spjxmrzga516x6qa9jygrpryvx4yqla6-xz-5.2.2/lib -L/nix/store/jh53hcmz7d294f356wzfqza5ldxsrc3m-gdbm-1.11/lib -L/nix/store/l86xg1n8kf9xk4hy6xp5k2fch2dij5vm-sqlite-3.12.2/lib -L/nix/store/fjkn41v5dpd40grzfi7b9c170rqfacw4-db-5.3.28/lib -L/nix/store/kahqk17fwx100bc7lxz1jn0zafd4g2xk-readline-6.3p08/lib -L/nix/store/ac92ylnnqs4f8kqyd86783mnn4k97sj2-ncurses-5.9/lib -L/nix/store/6ghnf08dzamqx9iwn29g3i7gdnq722di-openssl-1.0.2h/lib -L/nix/store/305s42cpxvl4wy5i81nncgvx6fqgql0s-tcl-8.6.4/lib -L/nix/store/amdac7441fig5l2y8003p12hg8yxnfs7-tk-8.6.4/lib -L/nix/store/m4l9lhv48csxw9wl72brbna93ghpxy6i-libX11-1.6.3/lib -L/nix/store/67m59xzhm677wqhnmjwbnnvryw9x0kj8-xproto-7.0.28/lib build/temp.linux-x86_64-3.5/borg/platform_linux.o -L/nix/store/9rw1p5waza2ca071g2w2cqn58zpvljri-python3-3.5.1/lib -lacl -lpython3.5m -o /tmp/nix-build-borgbackup-1.0.2.drv-0/borgbackup-1.0.2/borg/platform_linux.cpython-35m-x86_64-linux-gnu.so
usage: nix_run_setup.py [-h] [-V] <command> ...
nix_run_setup.py: error: argument <command>: invalid choice: 'test' (choose from 'serve', 'init', 'check', 'change-passphrase', 'migrate-to-repokey', 'create', 'extract', 'rename', 'delete', 'list', 'mount', 'info', 'break-lock', 'prune', 'upgrade', 'help', 'debug-dump-archive-items', 'debug-get-obj', 'debug-put-obj', 'debug-delete-obj')
builder for ‘/nix/store/3y8wf8zazj8xv8xqp1zk0h6p0w9dphr8-borgbackup-1.0.2.drv’ failed with exit code 2
```
Backing out the change to python35 fixes it all.

## Technical details

Nixos against a lightly tweaked version of the master branch.

**Comment by mdorman** [comment]
@FRidh you made the version change, maybe you have some insight?

**Comment by FRidh** [comment]
@mdorman, just to be clear, packages in `python-packages.nix` are not affected by this change, only applications that depend on `python3Packages` since that now means `python35Packages` instead of `python34Packages`. 

> if you upgrade the eventlet package, you then end up with a different failure to test for detox that seems to be a tox issue

Please open a PR with the updated `eventlet` package.

> nix_run_setup.py: error: argument <command>: invalid choice: 'test' (choose from 'serve', 'init', 'check', ...)

Clearly it cannot run tests, which `buildPythonPackage` does by default.
In `setup.py` they give as argument to `setup` `cmd_class`, but they do not include `test`.

Since a certain `setuptools` update (I think it was 19.4) they changed test behaviour, but this behaviour doesn't seem to be exactly the same for the different Python versions. Anyway, checking older build logs where `borgbackup` still built, you can see that no tests were actually run.

So, you have two options:
- explicitly disable testing for borgbackup
- set the checkPhase to something like `${python.interpreter} -m unittest discover`

cc maintainer @nckx

**Comment by bjornfor** [comment]
I pushed 06fc3790bcbe462d4ef2c555cd67d65e18c7a562 for attic and b12c9b83b560c52930e1fc01772d5b55ea18e99a for borgbackup, fixing the build by using with python 3.4 instead of 3.5.
