### ISSUE TITLE
Rebuilding NixOS on Raspberry Pi 4 fails after commit 4014fb6

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#155925]
Rebuilding NixOS on Raspberry Pi 4 fails after commit: https://github.com/NixOS/nixpkgs/commit/4014fb6a64bc5f68326fc08cbaa83475db1fae8e (PR #151082)

Errors as:
```
/nix/store/l3lj95gg3fx9amqcywv0qfsabs2nw4nj-raspberrypi-builder.sh: illegal option -- g
usage: /nix/store/l3lj95gg3fx9amqcywv0qfsabs2nw4nj-raspberrypi-builder.sh -c <path-to-default-configuration> [-d <boot-dir>]
warning: error(s) occurred while switching to the new configuration
```

My configuration.nix has:
```
boot.loader.raspberryPi = {
  enable = true;
  version = 4;
  firmwareConfig = ''
    dtparam=sd_poll_once=on
    dtoverlay=vc4_fkms_v3d,cma-256
  '';
};

boot.loader.generic-extlinux-compatible.enable = true;

system.stateVersion = "21.11";
```

Question:
1) Does it affect other Raspberry Pi 4 users (when upgrading past PR #151082)?

@roberth @ncfavier @samueldr

**Comment by rhoriguchi** [comment]
Might be able to help: @samueldr @tkerber

**Comment by ncfavier** [comment]
I think the problem is that the new type causes multiple definitions to be merged (concatenated as strings), and since you're probably generating an SD image your config has `boot.loader.generic-extlinux-compatible.enable = true` which results in two definitions for `system.build.installBootLoader`, one from [`raspberrypi.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/raspberrypi/raspberrypi.nix) and one from [`generic-extlinux-compatible`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/generic-extlinux-compatible/default.nix), so the resulting builder is nonsense.

Now I wonder why this succeeded before this commit.

**Comment by superherointj** [comment]
> I think the problem is that the new type causes multiple definitions to be merged (concatenated as strings), and since you're probably generating an SD image your config has `boot.loader.generic-extlinux-compatible.enable = true` which results in two definitions for `system.build.installBootLoader`, one from [`raspberrypi.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/raspberrypi/raspberrypi.nix) and one from [`generic-extlinux-compatible`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/generic-extlinux-compatible/default.nix) (notice the `-g` there in `builderArgs`), so the resulting builder is nonsense.
> 
> Now I wonder why this succeeded before this commit.

Correct, my configuration.nix has:
`boot.loader.generic-extlinux-compatible.enable = true`

**Comment by superherointj** [comment]
As @ncfavier correctly pointed out. The configs were clashing and that was causing the issue. After fixing the configuration.nix (by removing the raspberryPi specific config) I'm now able to upgrade to past that commit to unstable. So I'm closing the issue.

Thanks @samueldr @ncfavier for the support in solving this issue.
