### ISSUE TITLE
qutebrowser does not play videos anymore (without additonal packages)

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#15597]
## Issue description
Since issue #15419 is fixed, qutebrowser does not playback videos anymore. Only after qt55.qtmultimedia is installed, it plays videos, but stutters on high quality/in fullscreen. I have not experienced this issue before.

### Steps to reproduce
* install qutebrowser
* try to playback videos in qutebrowser, for example on youtube

* install qt55.qtmultimedia
* restart qutebrowser
* try to playback videos on youtube
* switch to fullscreen

## Technical details

* System: 16.09pre83796.d541e0d
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre83796.d541e0d

**Comment by gebner** [comment]
This bug was introduced with the multiple outputs change.  In the qutebrowser wrapper, we added the path to the development output of qtmultimedia, and not the standard output, where the plugin lives.

Now we use the standard makeQtWrapper wrapper to add the path to the Qt plugins.  In other news, qutebrowser now has 3 wrappers...
