### ISSUE TITLE
Cannot see iptables masquerade rule set by systemd since 21.11

### ISSUE THREAD

**Issue by datafoo** [NixOS/nixpkgs#156041]
### Describe the bug

On NixOS 21.05, when setting [`IPMasquerade = "yes";`](https://www.freedesktop.org/software/systemd/man/systemd.network.html#IPMasquerade=) on my WireGuard interface via option [`systemd.network.networks.<name>.networkConfig`](https://nixos.org/manual/nixos/stable/options.html#opt-systemd.network.networks._name_.networkConfig), I could see the result of this settings by running:

```sh
# iptables -t nat -L -v
Chain PREROUTING (policy ACCEPT 1 packets, 60 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 1 packets, 60 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 17 packets, 1504 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 17 packets, 1504 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  any    any     10.201.0.0/24        anywhere
```

Since NixOS 21.11 however, altought the masquerade works, I cannot see anything with iptables commands:

```sh
# iptables -t nat -L -v
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

# iptables-legacy -t nat -L -v
Chain PREROUTING (policy ACCEPT 3 packets, 296 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 1 packets, 176 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 2 packets, 120 bytes)
 pkts bytes target     prot opt in     out     source               destination
```

As discussed on the Discourse topic [Cannot see iptables masquerade rule since 21.11](https://discourse.nixos.org/t/cannot-see-iptables-masquerade-rule-since-21-11/17228), I suspect this is linked to the following change in NixOS 21.11 (PR https://github.com/NixOS/nixpkgs/pull/81172):

> iptables now uses nf_tables backend.

### Steps To Reproduce
1. Configure an interface with `systemd.network.networks.<name>.networkConfig.IPMasquerade = "yes";` on a system running NixOS 21.11
2. Run `iptables -t nat -L -v`
3. Notice the lack of information about the IP masquerade
```sh
# iptables -t nat -L -v
[…]
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination        
```

### Expected behavior
The IP masquerade should be visible like in NixOS 21.05:

```sh
# iptables -t nat -L -v
[…]
Chain POSTROUTING (policy ACCEPT 17 packets, 1504 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  any    any     10.201.0.0/24        anywhere
```
### Notify maintainers
@fpletz @misuzu 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.91, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fpletz** [comment]
Actually, this is due to systemd since v248 preferring to use nftables if available, see https://github.com/systemd/systemd/blob/5efbd0bf897a990ebe43d7dc69141d87c404ac9a/src/shared/firewall-util.c#L29-L36. Systemd does not use the iptables binaries and but a separate library that creates iptables rules directly without translation to nft by iptables-nft.

So even without #81172 using the legacy iptables tools, these rules in nftables by networkd would not be visible. Other services that need to add firewall rules like libvirtd, docker or podman are likely getting proper nftables support soon and users still using iptables will run into the same issues.

Since we are not the only distribution dealing with this, this should either be solved in systemd (can rules be generated that are compatible to and can be parsed by iptables-nft?) or in iptables-nft by displaying a warning that other nftables rules are active.

The only related problem remaining in NixOS is that since our `networking.firewall` module is heavily based around iptables, our users assume NixOS is using iptables when in fact it is using nftables with iptables compatibility.

cc @flokli @Mic92 @misuzu

**Comment by b3vis** [comment]
This particular issue is also giving me issues running docker on NixOS 21.11 in WSL2 on Windows 10. It requires iptables and the docker service fails to start due to docker trying to issue iptables a command and the nftables reply throws docker as an error. Same configuration using systemd v247 via 21.05 works fine

**Comment by fpletz** [comment]
@b3vis What you're seeing is directly caused by #81172 and has nothing to with this issue since the problem described here is that not all active rules are visible. Are we even supporting WSL officially? You might want to open a separate issue for this if you're interested in seeing support or getting this fixed. We would need to detect if nftables support is available and use the correct iptables package everywhere. Not sure if it's worth it, though.

**Comment by flokli** [comment]
@fpletz this seems to also cause problems when upgrading systems from before the nftables bump.

In my case, these were fixed after a reboot, but it's still a pretty annoying thing, for which we probably should at least make sure there's a release note entry. cc @misuzu

**Comment by flokli** [comment]
Hmmh, I'm also a bit baffled about how to interpret `networking.nftables.enable` defaulting to false.

**Comment by flokli** [comment]
@datafoo, you should see `table {ip,ip6} io.systemd.nat` nftable tables when invoking `nft list tables`, which is where systemd keeps its nft rules.

iptables rules configured with the `iptables` command are in `table {ip,ip6} {filter,nat,mangle}`.

I think this is mostly a matter of updating the release notes, and raising awareness, that nftables is used, the `iptables` command is only managing some tables in the nft system, and that there's more rules than what you can see with `iptables`. I'll try to come up with a PR updating the release notes in that regard.

It might not be possible to translate some nftable rules to a iptables syntax - I'm not sure if logging a warning breaks backwards compat with some tools relying on iptables output…

**Comment by flokli** [comment]
I improved the docs in https://github.com/NixOS/nixpkgs/pull/161426, PTAL.

Fixing the nftables module, and using less iptables in the firewall module should probably be left to another PR.

**Comment by flokli** [comment]
I opened https://github.com/NixOS/nixpkgs/issues/161428 to track the nftables NixOS module improvements.
