### ISSUE TITLE
With nix options changes, first substituter is always cache.nixos.org

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nixpkgs#158356]
### Describe the bug

It seems with the move from `nix.binaryCaches` to `nix.settings.substituters`, the first substitutes server is always `https://cache.nixos.org` which defeats the use of a local caching server. 

`/etc/nix/nix.conf` with `nix.settings.substituters = [ "http://10.42.42.150/" "https://cache.nixos.org" ];`
```
substituters = https://cache.nixos.org/ http://10.42.42.150/ https://cache.nixos.org
```

If I use mkForce to force a value with `nix.settings.substituters = pkgs.lib.mkForce [ "http://10.42.42.150/" "https://cache.nixos.org" ];` I get the following `/etc/nix/nix.conf`
```
substituters = http://10.42.42.150/ https://cache.nixos.org
```

### Steps To Reproduce

Define a custom substituter `nix.settings.substituters = [ "http://10.42.42.150/" ];` , check `grep ^substituters /etc/nix/nix.conf`, you will have `https://cache.nixos.org` first in the list.

### Expected behavior

It seems `https://cache.nixos.org` is always merged first in the list, it should be merged after the user defined value.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.12-xanmod1-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by roberth** [comment]
The order of cache queries is actually determined by a metadata file served by the caches.
That's what the priority number is for.

```
$ curl https://cache.nixos.org/nix-cache-info
StoreDir: /nix/store
WantMassQuery: 1
Priority: 40
```

I suppose this will only affect you if the caches have an equal priority number.

> It seems https://cache.nixos.org is always merged first in the list, it should be merged after the user defined value.

This can be achieved by putting a `lib.mkOrder` on the `cache.nixos.org` definition, or `mkBefore` on your own definitions.
Or use the priority number.

cc @domenkozar fyi

**Comment by rapenne-s** [comment]
After a git bisect, I found that the behavior changed with commit 4a9d9928dc01421b878cfe4a16961c1e4862d846

Prior to this and the renaming, `nix.binaryCaches = [ "http://10.42.42.150/" ];` used to work as expected but after, it adds `https://cache.nixos.org/` first in the list.

**Comment by roberth** [comment]
cc @polykernel

**Comment by polykernel** [comment]
This seems to be caused by the nondeterminism in the evaluation order. In the `nix.settings` submodule, the relative order of the `substituters` definitions are merged is reversed compared to before the PR(I don't know if this is specific to submodules).

I also noticed that `mkRenamedOption` does not preserve order priority, which means it can not fully map legacy options to the structural settings. I think the easiest solution for now is to just make the default option definition have lower order priority, as it doesn't require substantial changes to the module system.

**Comment by rapenne-s** [comment]
I confirm this has been fixed since I made the issue.

**Comment by stuser81** [comment]
Everyone, if you have time please see #8101 if you have the time. I quote "It seems people want this automatic appending [of "cache.nixos.org"], which feels strange to me. What about people who also want to offload the cache downloading [and not just building] to the build machine?"

**Comment by huandzh** [comment]
In my particular situation, the default cache "https://cache.nixos.org/" was completely unreachable, yet it continued to be appended to the substituters, causing the nix-* commands to attempt to download and check its priority in vain.

The issue was resolved by using `mkForce` to prevent automatic appending.

```nix
# configuration.nix
{ config, pkgs, lib, ... }:
{
 # ...
 nix.settings.substituters = lib.mkForce [ "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store" ];
 # ...
}
```

I hope the code above can be helpful for someone who has encountered the same problem and reached here through searching.
