### ISSUE TITLE
Request to add SoundConverter package

### ISSUE THREAD

**Issue by NoraCodes** [NixOS/nixpkgs#159029]
**SoundConverter**
_A GNOME application which provides a graphical interface for converting many audio files between formats in parallel._

**Metadata**

* homepage URL: https://soundconverter.org/
* source URL: https://github.com/kassoulet/soundconverter (or https://launchpad.net/soundconverter/trunk )
* license: gpl3
* platforms: linux, gnome

**Comment by FaustXVI** [comment]
Hi @NoraCodes ,

It seems to me like it's available : https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=soundconverter

Am I missing something ?

**Comment by auroraanna** [comment]
> Am I missing something ?

No

**Comment by auroraanna** [comment]
The package was even added before this issue was created. I guess she just didn't check if it was already added or she or she used the stable channel and it wasn't in there yet.

**Comment by NoraCodes** [comment]
I'm not sure that's true; the package was made here (https://github.com/jakubgs/nixpkgs/tree/init/soundconverter) on March 7 and merged to nixpkgs 3 days later (https://github.com/NixOS/nixpkgs/commit/635b5afceb2bbf27f3746851a8c5a7d550b506e4), both *after* I created this issue on Feb 10th of the same year.

That said, I'm happy to see that it does exist now!

**Comment by auroraanna** [comment]
Oh, sorry, mixed up the date the commit was made with the date the PR was merged tho somehow GitHub shows 2 dates for when the commit was made: [One before this issue was created](https://github.com/NixOS/nixpkgs/blob/073e7d59f48f1bf24055afd92988fdd020ddc3df/pkgs/applications/audio/soundconverter/default.nix) and [one after](https://github.com/NixOS/nixpkgs/commit/073e7d59f48f1bf24055afd92988fdd020ddc3df). The [PR](https://github.com/NixOS/nixpkgs/pull/152733) however, was created before this issue

**Comment by NoraCodes** [comment]
Well, I apologize for not searching through PRs, but it's worth noting that the "make a packaging request" link on search.nixos.org leads directly to an issue template; if it's an issue for people to create packaging requests for packages that have in-flight PRs, it might be worth calling that out in the template.
