### ISSUE TITLE
ffmpeg has two different implementations

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#15930]
While patching some functionality into mpv I noticed that there are two completely separate ffmpeg derivations, which both do basically the same thing, but `ffmpeg-full` enables more options.

What’s the reasoning behind splitting them, instead of creating a generic derivation with all options turned of by default and `ffmpeg-full` calling it with most options set to `true`, as most other packages do it? @codyopel

**Comment by edolstra** [comment]
Strong :+1: on merging them. This is even a security issue: ffmpeg in 16.03 is at 2.8.6, but ffmpeg-full is at 2.8.5, lacking the fix for CVE-2016-2329.

**Comment by codyopel** [comment]
@Profpatsch 
It was when I was trying to simplify what should be enabled by default (e.g. non-full only enables the bare minimum for applications building against ffmpeg), there is no reason to keep them separate anymore.

I rewrote the build in Triton recently, there are a few things that still need to be cleaned up, but it should give you an idea.  Keep in mind we have dropped `0.x` & `1.x` completely so if those versions are still maintained in nixpkgs you would need to add the necessary changes if you want to maintain a generic build.
https://github.com/triton/triton/blob/master/pkgs/all-pkgs/ffmpeg/

Feel free to remove me from maintainers when you update the build.

**Comment by Profpatsch** [comment]
This is still the case I’m afraid.

**Comment by mweinelt** [comment]
Still somewhat relevant.

**Comment by AndersonTorres** [comment]
Related: 

https://github.com/NixOS/nixpkgs/issues/120705

**Comment by jonringer** [comment]
Hmm, there is a pretty significant closure size:
```
[22:55:55] jon@nixos ~/projects/nixpkgs (master)
$ nix path-info -Sh ./small-bin
/nix/store/2d7sllqxhqcvdkfrdsa6g2sqzq0x1m0d-ffmpeg-4.3.2-bin	 254.9M
[22:56:24] jon@nixos ~/projects/nixpkgs (master)
$ nix path-info -Sh ./full
/nix/store/6sp1l5dr21dxv4x9xybxa6bw10kazdj4-ffmpeg-full-4.3.2	 536.3M
```

**Comment by AndersonTorres** [comment]
But FFMPEG has many options and interacts with a plethora of formats of video, audio, images and even text (for subtitles at least). It is well inside expectations its closure size is big if we plug in everything we can.
OTOH bin is basically a precompiled version.

**Comment by oxalica** [comment]
I run into some issue when trying `srt://` protocol. Note that `mpv` and `obs-studio` depends on `ffmpeg` to handle protocols, but they use `ffmpeg`, which is the minimum build by default, instead of `ffmpeg-full`. If I need some extra features like `srt://` in `mpv` or `obs-studio`, I need to override their dependencies all to `ffmpeg-full`, which cause these downstream packages all need to be rebuilt.

> Hmm, there is a pretty significant closure size:

@jonringer The small closure size results in lack of features for all downstream packages when used as a library.
I don't think we should prefer a *minimal* `ffmpeg` for applications. Default `ffmpeg` should have default features enabled.

**Comment by tbenst** [comment]
Previously, I was able to use just a single `ffmpeg` on my system by using an overlay like 
```
ffmpeg-full = super.ffmpeg-full.override {
  ffmpeg = super.ffmpeg_4;
  nonfreeLicensing = true;
  nvenc = true; # nvidia support
};
ffmpeg = super.ffmpeg-full.override {
  ffmpeg = super.ffmpeg_4;
  nonfreeLicensing = true;
  nvenc = true; # nvidia support
};
```

As of 21.05, this now causes an infinite recursion. Is there a workaround?

**Comment by Atemu** [comment]
I'm surprised this was ever a thing but it still is. The derivations should definitely be merged.

**Comment by jonringer** [comment]
Well, I would suspect that for most user facing scenarios, they would want the full version. In which case any closure savings would get thrown out the window.

Maybe just provide `ffmpeg` and `ffmpegMinimal` (for cases in which minimal closure is may be desirable) instead of a `ffmpegFull`.

**Comment by Atemu** [comment]
How were the options enabled for our current `ffmpeg` determined?  

`ffmpeg-full` should obviously enable all free options. A `ffmpeg-full-unfree` could also be added for a ffmpeg with everything (including unfree) enabled.

We already provide a `ffmpeg-headless` for purposes that don't require things like SDL, pipewire, X etc. and for bootstrapping.

As for `ffmpeg-minimal`, I wonder what options that should have enabled because at some point, too minimal becomes useless.

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/204198 for WIP.

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/204198 is now at a state where I'd like some eyes on it.
