### ISSUE TITLE
Unable to install virtualenvwrapper for Python 3.5

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#15973]
## Issue description

Trying to install `python35Packages.virtualenvwrapper` gives the following build error:
```
error: sphinx-1.2.3 not supported for interpreter python3.5m
```
I don't understand why `virtualenvwrapper` is concerned about `sphinx` package??

### Steps to reproduce

Add the following to `environment.systemPackages = with pkgs;` list:
```
   python35Packages.virtualenvwrapper
 ```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
# nixos-version
16.03.898.3111985 (Emu)
```

* Nix version: (run `nix-env --version`)

```
# nix-env --version
nix-env (Nix) 1.11.2
```
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.03.898.3111985"
```

**Comment by FRidh** [comment]
> I don't understand why virtualenvwrapper is concerned about sphinx package??

Nix builds up a graph of dependencies. Sphinx 1.2.3 is somewhere an (indirect) dependency of `virtualenvwrapper`. Likely one or more packages need to be updated to get this working for you.

**Comment by jluttine** [comment]
Ok, thanks. Do you have any pointers what I could do about it? I just installed Nix(OS) so I'm new to this.

**Comment by FRidh** [comment]
Typically dependencies are added for a reason. It is a bit strange though, that we have things depending on specifically Sphinx 1.2.x, and not 1.3.x which is the default Sphinx. I suggest you have a look at `python-packages.nix`, and start updating packages, beginning with `virtualenvwrapper`, so that eventually you can get rid of Sphinx 1.2.x and use 1.3.x instead. 

At this point I do have to ask you. Why are you interested in `virtualenvwrapper`? Is it because you simply have to work with `virtualenv`? Since now you're on Nix you have a far more powerful tool for creating such environments: `nix-shell`

**Comment by groxxda** [comment]
[Pypi](https://pypi.python.org/pypi/virtualenvwrapper/) suggests virtualenvwrapper itself is not tested on python 3.5.
Maybe you can use `pythonPackages34.virtualenvwrapper`?

**Comment by jluttine** [comment]
Thanks for pointing out `nix-shell`. I read about it but I couldn't quite figure out how I can use it to replace `virtualenv`. For instance, is it possible to install packages via `pip` into that development environment without `virtualenv`.

I found this, but seems quite experimental and not very well working yet:
https://github.com/garbas/nix-virtualenv

Also, I found these interesting posts:
http://datakurre.pandala.org/2015/10/nix-for-python-developers.html
http://datakurre.pandala.org/2014/09/nix-expressions-as-executable-commands.html

So, perhaps I'll study a bit and see what would be a good approach. Anyway, I like the `virtualenv` integrations, for instance, in Emacs (e.g., possibility to activate different virtualenvs within Emacs and run unit tests etc) and `workon myproject` in `virtualenvwrapper`

Thanks!

**Comment by FRidh** [comment]
@jluttine with Nix we don't have a global/user site-packages. Therefore, if you use `nix-shell`, and try a `pip install` a package it will complain because it cannot install anything in the store. Of course, you could install those packages elsewhere.

Now, you can create a virtualenv, and then use pip. However, packages that were included in your `nix-shell` will leak into your virtualenv. This can be considered both a bug and a feature :)
Some more details about this can be found in the https://github.com/NixOS/nixpkgs/issues/15224

Anyway, I will close this issue because it is simply not possible at this point to install virtualenvwrapper on Python 3.5 because of the currently defined dependencies. And as  @groxxda pointed out, 'officially' it is not supported either.
