### ISSUE TITLE
khal does no longer build

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#15981]
## Issue description

`khal` does not build, neither the old version (0.7.0) nor the newer version in nixpkgs (0.8.2).

### Steps to reproduce

`nix-build -A nixpkgs.khal` on latest or one of the older unstable channels.

## Technical details

* System: 16.09pre84107.be5b596 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre84674.fbde3a7"

**Comment by gebner** [comment]
For the record, the problem was that the `test_set_focus_date_weekstart_6` test was failing.  For testing, khal overrides the current date using the freezegun package.  This takes effect after the call to freeze_time; however python evaluates default arguments only once--in this case before the call to freeze_time.  The culprit is the following code in calendarwidget.py:
```python
    def _construct_month(self,
                         year=date.today().year,
                         month=date.today().month,
                         clean_first_row=False,
                         clean_last_row=False):
```
Here, year and date default to the current date (2016-06-18), however the rest of the code expects the overriden date (2016-04-10).

This is fixed in master, probably in [this commit](https://github.com/pimutils/khal/commit/6bfe237a83d653a360d5a6e373dd78ccbb10b3e5).  I didn't want to backport the fix, as there seemed to be several commits related to this issue and it's unclear what dependencies they have.

We might also need to upgrade khal to the git version soon, as khal 0.8.2 no longer works with the current version of icalendar (3.10), this is fixed in master as well.
