### ISSUE TITLE
buildEnv.pl problems

### ISSUE THREAD

**Issue by dredozubov** [NixOS/nixpkgs#16048]
## Issue description

When i try to install binutils, this happens:

```
% nix-env -f "<nixpkgs>" -iA binutils --show-trace
installing ‘cctools-binutils-darwin’
building path(s) ‘/nix/store/r6dq1hy9a9kzmrz36cscyjy05frm36nw-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 87.
error creating link ‘/nix/store/r6dq1hy9a9kzmrz36cscyjy05frm36nw-user-environment/share’: File exists at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 87.
builder for ‘/nix/store/hbwm86gy1911viszpab0d03n6zdpsy2m-user-environment.drv’ failed with exit code 17
error: build of ‘/nix/store/hbwm86gy1911viszpab0d03n6zdpsy2m-user-environment.drv’ failed
```
### Steps to reproduce

`nix-env -f "<nixpkgs>" -iA binutils`
## Technical details
- System: OS X 10.10.5
- Nix version: 1.11.2
- Nixpkgs version: 16.09pre83147.df89584

**Comment by vcunat** [comment]
The error is *not* during building binutils. It's during `buildEnv`: probably some bug in it triggered by the combination you've installed by `nix-env`. The bug is probably "portable". IIRC there were problems if there's a symlink-directory collision. Note that `buildEnv` is about to [get rewritten](https://github.com/NixOS/nix/issues/341) soonish and you're affected by the copy living in a different repository.

**Comment by rasendubi** [comment]
Could you retest this now? https://github.com/NixOS/nixpkgs/pull/16828 was merged and might have solved the issue

**Comment by dredozubov** [comment]
I get the same result with nixpkgs-unstable channel.

**Comment by rasendubi** [comment]
@dredozubov could you please post the output of `nix-env -q` here (as @vcunat noted, the issue is most probably caused by your particular combination of installed packages).

**Comment by matthewbauer** [comment]
Closing. This has been fixed for a while. Feel free to reopen it if it's still an issue. Thanks!
