### ISSUE TITLE
nixos.sd_image_new_kernel.aarch64-linux is not building on Hydra

### ISSUE THREAD

**Issue by alex-robbins** [NixOS/nixpkgs#161296]
It [looks like] nixos.sd_image_new_kernel.aarch64-linux was being built daily by Hydra, but it stopped on January 10. 

As a result, the new-kernel SD image is stuck with kernel 5.15.13. I think there might be an upstream kernel bug in subsequent releases, and it would be nice to have a Hydra-built SD image to test with.

[looks like]: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.sd_image_new_kernel.aarch64-linux

### Notify maintainers

@samueldr since it looks like he added the new-kernel image originally

**Comment by samueldr** [comment]
Yeah, it happens every release of Linux because of the hard dependency on ZFS.

The job page has this banner:

![image](https://user-images.githubusercontent.com/132835/155058931-608af662-5b82-467f-8862-ce5f28ce5bd2.png)

When this happens, for any build, copy the job name part after the colon (`nixos.sd_image_new_kernel.aarch64-linux`). Go to the [jobset page](https://hydra.nixos.org/jobset/nixos/trunk-combined), then to the [Evaluation Errors tab](https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors), and search for the job name.

Current issue is, as expected:

```
in job ‘nixos.sd_image_new_kernel.aarch64-linux’:
error: Package ‘zfs-kernel-2.1.2-5.16.10’ in /nix/store/d9wpzgyjlpw1424kw2lyilah6690fnk3-source/pkgs/os-specific/linux/zfs/default.nix:195 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
```

See also: #59863.

**Comment by samueldr** [comment]
I'm closing assuming this was answered correctly. This is a known defect, and there's not much actionable specifically here, other than waiting for ZFS package updates. Sadly.

**Comment by alex-robbins** [comment]
Thanks for the tip on navigating Hydra; that's helpful. Agree on closing. 

Too bad about the ZFS thing, but if you couldn't get a solution accepted then I'm sure there's nothing I can do about it either. (It definitely makes sense to me that people who want ZFS should expect to have to downgrade their kernel if ZFS does not yet support the current one.)
