### ISSUE TITLE
emacs-webkit

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#16199]
Package request.
Would be fine to have [emacs-webkit](https://www.emacswiki.org/emacs/WebKit) packet an a NixOS derivation because of python/qt dependencies.

@bendlas @ttuegel

**Comment by bendlas** [comment]
From glancing at the package, it looks like it comes with its own python script, that just imports its dependecies from `PYTHONPATH`.
It could live in `pkgs/applications/editors/emacs/emacs-modes/webkit/default.nix` and be defined by [buildPythonPackage](https://nixos.org/nixpkgs/manual/#ssec-build-python-package), right?

**Comment by Pitometsu** [comment]
well, probably there should be two packages: python part and elisp part.
python part may be included into derivation of elisp part, it's good because of encapsulation.
But on other hand elisp better to install locally (to `~/.emacs.d/...`). So if user use e.g. `el-get` to manage elisp packages, it wold better to avoid duplication, and install just python part system-wide, and elisp locally.

**Comment by bendlas** [comment]
No, the `.el` should live together with its `.py` file in a package. The `.el` finds its `.py` relative to itself, so the source should just be copied verbatim into `$out/share/emacs/`. 

In addition we need emacs to set environment variables, before it activates that mode. That is a `PYTHON` variable, which should point to a python to a python binary, as well as its `PYTHONPATH` extended with `pyqt` et al
The logic to assemble `PYTHONPATH` is usually accessed via `buildPythonPackage`. Maybe @ttuegel can comment on how this is expected to work within `emacsWithPackages`.

For testing locally, you can `nix-env -iA` the appropriate dependencies, then loading the mode into emacs should just work.

**Comment by jgeerds** [comment]
I think this is also the reason why `anaconda-mode` doesn't work for me:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named pkg_resources
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named pip
```

I tried to add those packages (e.g. `pythonPackages.pip` and `pythonPackages.setuptools`) to my system profile and/or the emacsWithPackages derivation but it still doesn't work for me.

**Comment by bendlas** [comment]
Correction to my previous statement: Installing python packages to your profile will _not_ set `PYTHONPATH`. Instead you should define your dev-environment as a derivation and `nix-shell` into it.

We might consider having `emacsWithPackages` pick up shell hooks in a generic way, since emacs is, in fact, a shell. For python this would facilitate a complete reuse of https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/generic/wrap.sh, which would put us in a good place compatibility-wise and possibly solve the same problem for other language environments, but it might lead to a lot of complexity and unforseeable bugs.

An alternative would be to have `emacsWithPackages` add `(setenv "PYTHONPATH" ..)` and similar clauses to `site-start.el`, on a per-package basis, which would have only a local impact and facilitate custom fixes, but create more maintenance burden and lead to duplicate logic, that could get out of sync.

**Comment by FRidh** [comment]
I suggest you use `python.withPackages` that creates a Python environment with the packages that you need (like `pyqt5`) through `python.buildEnv`, and then add this derivation to the `propagatedBuildInputs` of your package. If you then patch the shebangs, the shebangs of the [Python scripts](https://github.com/linuxdeepin/deepin-emacs/tree/master/site-lisp/extensions/webkit) will point to the interpreter that is in the environment.

**Comment by jgeerds** [comment]
@FRidh You mean putting a custom python version to the `propagatedBuildInputs` of the emacs derivation? But wouldn't that mean you have to build Emacs on your own? (no binary cache)

**Comment by FRidh** [comment]
@jgeerds I mean `python.withPackages(ps: with ps; [ python dependencies of emacs-webkit ])` where `ps` is the Python package set.

Before, people would use `PYTHONPATH` to make Python libraries available but this is a better method.

**Comment by olejorgenb** [comment]
Off topic: @jgeerds: the easiest way to get anaconda up and running (at least these days) is to run emacs from a nix-shell exposing the required dependencies. This works for me `nix-shell -p python2 python2Packages.setuptools --command emacs`. Seems like anaconda mode uses setuptools not only to install the server, but also to check if it is installed (this has changed over time) so you have to start emacs this way every time.
