### ISSUE TITLE
scilab is outdated and fails to build

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#16209]
## Issue description

The scilab package in nixpkgs is outdated (4.1.2 instead of 5.5.2). The old package fails to build. I have tried to update the package, but java seems to now be a required dependency. In particular, scilab now needs jogl, which I have been unable to create a derivation for.

**Comment by vrthra** [comment]
For the old package,   using USE_INTERP_RESULT and USE_INTERP_ERRORLINE in CFLAGS for make would get rid of the TCL/TK errors. However, there seems to be a compilation issue with `routines/system` folder possibly due to a `gfortran` [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41154). It seems a gfortran bug, because the code in question looks legal.

**Comment by volth** [comment]
An example of jogl derivation in ```Processing 3```: https://github.com/NixOS/nixpkgs/pull/36851/files

**Comment by volth** [comment]
```jogl``` is included in ```nixpkgs``` (under ```javaPackages.```) and used by ```gephi``` and ```processing3```

**Comment by tomberek** [comment]
(triage) we are on 6.0.2 now. close as outdated.
