### ISSUE TITLE
hplip fails to build on `aarch64-linux` for multiple reasons

### ISSUE THREAD

**Issue by vikanezrimaya** [NixOS/nixpkgs#162141]
### Describe the bug
The recent fixes to disable `imageProcessor` in hplip didn't seem to properly work on `aarch64-linux`, making the whole package fail with a cryptic error. Additionally, due to a **dependency failure in PyQt5**, the package further refuses to build unless it's disabled.

### Steps To Reproduce
1. be an aarch64-linux user
2. `nix build nixpkgs#hplip`
3. watch it fail due to PyQt5 failure
4. Realize that PyQt5 support can be disabled
5. `nix build --impure --expr '(builtins.getFlake "nixpkgs").legacyPackages.aarch64-linux.hplip.override { withQt5 = false; }'`
6. Watch it fail again with `-lImageProcessor`-related errors

### Expected behavior
hplip works

### Screenshots
n/a

### Additional context
Current unstable as of writing this is `github:nixos/nixpkgs/7f9b6e2babf232412682c09e57ed666d8f84ac2d`.

### Notify maintainers

cc @ttuegel as maintainer

**Comment by kisik21** [comment]
cc @svanderburg as PyQt5 maintainer due to dependency failure - should a separate issue be filed for this?

**Comment by ckiee** [comment]
Can reproduce. I ended up moving the print server to a x86-64 machine which was conveniently only a ~meter away from the RPi.

**Comment by simplejack-src** [comment]
Also got bit by this on a RaspberryPi 4 server upgrade to 22.05.

Did a bit of investigation, and came up with an overlay workaround (and hplip upgrade to 3.22.4) using a patch by the Debian crew:
```
   config = {
      nixpkgs.overlays = [ (self: super: {               
         hplip = super.hplip.overrideAttrs (old: {
            name = "hplip-3.22.4-patched";
            src = builtins.fetchurl "https://sourceforge.net/projects/hplip/files/hplip/3.22.4/hplip-3.22.4.tar.gz";
            patches = old.patches ++ [ 
               (builtins.fetchurl "https://sources.debian.org/data/main/h/hplip/3.22.4%2Bdfsg0-1/debian/patches/0028-Remove-ImageProcessor-binary-installs.patch")
            ];                                                                        
            nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.autoreconfHook ];
            postPatch = old.postPatch + ''
               echo 'AUTOMAKE_OPTIONS = foreign' >> Makefile.am
            '';
         });                                                                         
      })];
};
```

The meat of the issue comes down to the HP folks feeling the need to include their non-free x86/-64 'ImageProcessor' in the default build (even when the applicable ```./configure``` flag is specified). So the community consensus is hoping that HP will fix/revert this, but until then everyone's just patching it out.


@ttuegel Could this patch be added to the patch list (and likely update hplip to 3.22.4) ?

[Debian patch](https://sources.debian.org/patches/hplip/3.22.4+dfsg0-1/0028-Remove-ImageProcessor-binary-installs.patch/)
[Good overview of the issue](https://bugs.launchpad.net/hplip/+bug/1785230)
