### ISSUE TITLE
Raspberry Pi 3B+ does not boot with latest kernel from 21.11

### ISSUE THREAD

**Issue by terinjokes** [NixOS/nixpkgs#162435]
### Describe the bug

This is a 21.11 follow up of #142848. I was running 21.11, and upgraded today (to 5.10.102) and now my boot fails with:

```
Moving image from 0x80000 to 0x200000, end=3140000
ERROR: RD image overlaps OS image (OS=0x200000..0x3140000)
[...]
SCRIPT FAILED: continuing...
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
```

Per `/etc/extlinux/extlinux.conf`, I had upgraded to `2022-03-02 00:25 - 21.11.336182.a25df4c2b79`.

## Expected behavior

Successfully boot from the SD card.

**Comment by terinjokes** [comment]
Following the recommendations from https://github.com/NixOS/nixpkgs/issues/142848#issuecomment-1033465663, I downloaded a new u-boot build from https://hydra.nixos.org/build/166809101 and that successfully brought my system back up.

Would be great if there's a reminder to sync u-boot (or automatically update it).

**Comment by DavidEGrayson** [comment]
I ran into this issue too.  I successfully fixed it by replacing my old firmware with the files from nixos-sd-image-23.05.2300.f3fbbc36b4e-aarch64-linux.img.zst, which comes from [https://hydra.nixos.org/build/229325903 hydra build 229325903].

Does anyone know what Nix expression I could use to build those same firmware files myself?  Or if you could just say what Nix expression is used to build the SD image I downloaded from Hydra, that would be helpful, because I can probably find the firmware in there.

**Comment by crazyminecuber** [comment]
I got the same issue on a pi 4 when upgrading to 24.05. Mine however still tried to boot 23.11. So it was even trickier for me to diagnose.

It would be really good to have this automated if possible, otherwise clearly documented and give some kind of notification to the end user somehow.

I wonder if it possible to get around this issue by flashing a uefi firmware instead of using uboot directly 🤔 [https://github.com/pftf/RPi4](https://github.com/pftf/RPi4)

**Comment by VTimofeenko** [comment]
[Link to the latest hydra sd image](https://hydra.nixos.org/build/263360563). Worked for Rpi4 and cm4.

**Comment by udf** [comment]
I've automated this in my setup by making a derivation that runs the commands to populate the firmware from the sdcard's module:

`sd-image-firmware.nix`:
```nix
{ pkgs, callPackage, stdenv }:

let
  sdImageDrv = (callPackage "${pkgs.path}/nixos/modules/installer/sd-card/sd-image-aarch64.nix" { });
in
stdenv.mkDerivation {
  name = "sd-image-firmware";
  buildCommand = ''
    mkdir firmware
    ${sdImageDrv.sdImage.populateFirmwareCommands}
    mkdir -p $out
    mv firmware $out/firmware
  '';
}
```

And then I have the firmware be updated (if it's changed) on every configuration rebuild via an activation script (also remember to mount the firmware partition):

`configuration.nix`:
```nix
{ pkgs, lib, ... }:
let
  sdImageFirmware = (pkgs.callPackage ./packages/sd-image-firmware.nix {});
in
{
...
  # Assuming this is installed on top of the disk image.
  fileSystems = {
    "/boot/firmware" = {
      device = "/dev/disk/by-label/FIRMWARE";
      fsType = "vfat";
    };
    ...
  };

  system.activationScripts = {
    updateFirmware = ''
      if [ "$(cat /boot/firmware/src.path 2>/dev/null || true)" != "${sdImageFirmware}" ]; then
        echo Updating firmware from ${sdImageFirmware}
        ${pkgs.rsync}/bin/rsync -rv "${sdImageFirmware}/firmware/" /boot/firmware/ && \
        echo -n "${sdImageFirmware}" > /boot/firmware/src.path
      fi
    '';
  };
...
}
```

-----

Directly calling `sd-image-aarch64.nix` is maybe not the right way to do it, but I didn't find an easy way to access it in the nixpkgs set. Additionally, having it run on each rebuild is a bit excessive, though I do write the source path to `/boot/firmware/src.path` to prevent running rsync every time.

**Comment by flokli** [comment]
I ran into this today too, on a CM4 - manually building `pkgs.pkgsCross.aarch64-multiplatform.ubootRaspberryPi4_64bit`, and then copying the `u-boot.bin` from there to `u-boot-rpi4.bin` on the FAT partition did the trick for me.

I don't think there's much we can do to fix old versions of sdcards. technically that "firmware" partition is not touched by NixOS, and only created when creating a new image.
