### ISSUE TITLE
Document wrapGAppsHook

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#16285]
I just found out about wrapGAppsHook by examining a gnome package, but there really should be documentation about this in the Nixpkgs User Guide (a section about Gnome would be nice, which would show the right way to package GTK3 / GTK2 glib based apps).

Also, perhaps there are other things I missed that one should know when packaging Gnome Applications or GTK3/2 apps? 

/cc @lethalman @jgeerds @DamienCassou Gnome maintainers

**Comment by CMCDragonkai** [comment]
I'd like to know as well. Currently receiving this error:

```
(gpredict:7844): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```

On one of the packages I'm trying to put into nixpkgs.

**Comment by jtojnar** [comment]
The error occurs when you do not have any directory containing `glib-2.0/schemas/gschemas.compiled` in `XDG_DATA_DIRS` variable. One of the things `wrapGAppsHook` does is [adding `share/gsettings-schemas/$name`](https://github.com/NixOS/nixpkgs/blob/d8bc997dbe102fba9be39c7bc67e9e364859c961/pkgs/build-support/setup-hooks/wrap-gapps-hook.sh#L26) (which usually contains the aforementioned file) of dependencies to `XDG_DATA_DIRS`. (Actually this happens in cooperation with [glib setup hook](https://github.com/NixOS/nixpkgs/blob/d8bc997dbe102fba9be39c7bc67e9e364859c961/pkgs/development/libraries/glib/setup-hook.sh#L5) via `$GSETTINGS_SCHEMAS_PATH` variable.)

Icon themes work in the same vein, only [`XDG_ICON_DIRS` variable](https://github.com/NixOS/nixpkgs/blob/d8bc997dbe102fba9be39c7bc67e9e364859c961/pkgs/build-support/setup-hooks/wrap-gapps-hook.sh#L22) is used and it is populated by [`hicolor-icon-theme`’s setup hook](https://github.com/NixOS/nixpkgs/blob/d8bc997dbe102fba9be39c7bc67e9e364859c961/pkgs/data/icons/hicolor-icon-theme/setup-hook.sh#L6) which is propagated to `gnome3.defaultIconTheme` ([`adwaita-icon-theme`](https://github.com/NixOS/nixpkgs/blob/d8bc997dbe102fba9be39c7bc67e9e364859c961/pkgs/desktops/gnome-3/core/adwaita-icon-theme/default.nix#L18)).

`hicolor-icon-theme` (XDG fallback theme) should be probably added to any GTK application that uses icons (I think that is every GTK applicaton nowadays due to CSD) but some applications require Adwaita because they use icons not in hicolor. Not sure if this functions correctly though, at least it should not according to my mental model of how icon theme selection works; I will need to read the relevant XDG spec before I can finish the documentation.

**Comment by tbenst** [comment]
Just thought I'd leave this comment here for future reference: if you get an error like `ValueError: Namespace Gtk not available` for python gtk applications, try adding `wrapGAppsHook` to propogatedBuildInputs!

**Comment by jtojnar** [comment]
@tbenst It should go to `nativeBuildInputs`, though. But be wary of https://github.com/NixOS/nixpkgs/issues/56943
