### ISSUE TITLE
Can't install python27Packages.virtualenv

### ISSUE THREAD

**Issue by erahhal** [NixOS/nixpkgs#162957]
### Describe the bug
Can't install `python27Packages.virtualenv`.  Error is:

`error: pytest-asyncio-0.17.2 not supported for interpreter python2.7`

### Steps To Reproduce
1. Use unstable or trunk channel
2. add `python27` and `python27Packages.virtualenv` to your configuration 
3. run `nixos-rebuild switch`
4. note failure

### Expected behavior
Should install without failure
### Metadata
```console
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/xsgq8c5pg6lpjils5qvg67crrv6sy247-bash-interactive-5.1-p12-dev
copying path '/nix/store/xsgq8c5pg6lpjils5qvg67crrv6sy247-bash-interactive-5.1-p12-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.24, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - nixpkgs: `/nix/store/d9wpzgyjlpw1424kw2lyilah6690fnk3-source`
```

**Comment by Artturin** [comment]
rolling back 10 000 commits 
then the error we get is
```
nix build ".#python27Packages.virtualenv"
error: platformdirs-2.4.0 not supported for interpreter python2.7
```

which is because of d9674e2c038b3cef594f5fdef917870d4ca08fc5
so we need to do `git checkout d9674e2c038b3cef594f5fdef917870d4ca08fc5~1` to rollback to the commit before that
then when we need to compile some packages so rollback to about `d9674e2c038b3cef594f5fdef917870d4ca08fc5~300` to utilize the binary cache to not have to compile anything  

so please rollback to 778525fd49bc8a68d9b5b88314b5af1786736c3b if you need to use python27Packages.virtualenv as we're currently trying to remove python2 https://github.com/NixOS/nixpkgs/projects/27

**Comment by Artturin** [comment]
```nix
let
  pkgs = import (builtins.fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/778525fd49bc8a68d9b5b88314b5af1786736c3b.tar.gz";
    sha256 = "0ch84fjna9ybdw47w1c4hgn9fvc3d1f88qdngc66fn0h33rjcwiw";
  }) { };

  python-with-packages = pkgs.python2.withPackages (p: with p; [
    virtualenv
  ]);
in
pkgs.mkShell {
  buildInputs = with pkgs; [
    python-with-packages
  ];
}
```
put this in a `shell.nix` and then run `nix-shell`

**Comment by erahhal** [comment]
Thanks.
