### ISSUE TITLE
ms liveshare macOS

### ISSUE THREAD

**Issue by djgoku** [NixOS/nixpkgs#163202]
**Support macOS/M1**
Currently live share is linux only. How would I start the process to add liveshare extension to support macOS and M1.

**Metadata**

The below does not work currently:
```
  vscodeExtensions = (with pkgs.vscode-extensions; [

  ]) ++ pkgs.vscode-utils.extensionsFromVscodeMarketplace [
    {
      name = "vsliveshare";
      publisher = "ms-vsliveshare";
      version = "1.0.5418";
      sha256 = "11pnfvssn2vv975liwx5g7qm0l3l6q0lcl91hxgd0bwpkdzmnr1h";
    }
```

* homepage URL:
* source URL: https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/applications/editors/vscode/extensions/ms-vsliveshare-vsliveshare/default.nix
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, m1

**Comment by mdarocha** [comment]
The extension is defined here: https://github.com/NixOS/nixpkgs/blob/8b8a64d737ebd31924b4e86f3c46afccff7141b3/pkgs/applications/editors/vscode/extensions/ms-vsliveshare.vsliveshare/default.nix#L2

You can start with trying to remove the `platforms` attribute (see https://github.com/NixOS/nixpkgs/blob/8b8a64d737ebd31924b4e86f3c46afccff7141b3/pkgs/applications/editors/vscode/extensions/ms-vsliveshare.vsliveshare/default.nix#L52), and testing if it works. Since the newer extension versions are pure js, it should work without futher changes.
