### ISSUE TITLE
pandoc-crossref fails because of missing dependency: template-haskell >=2.4 && <2.11

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#16393]
## Issue description

On lastest unstable channel, pandoc-crossref fails because of missing dependency: template-haskell >=2.4 && <2.11

### Steps to reproduce

nix-shell -p haskellPackages.pandoc-crossref

## Technical details

* System: 16.09pre85639.453086a (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre85639.453086a"

**Comment by matthiasbeyer** [comment]
Pinging some haskellers now... @peti @kosmikus @ocharles @shlevy @jagajaga

**Comment by peti** [comment]
Apparently, `pandoc-crossref` does not support GHC version 8.0.x. You should report that issue upstream and lobby them to release an update to fix that issue. Meanwhile, you can use the binary from the `haskell.packages.lts` package set, which shouldn't have that problem since those packages are still compiled with GHC 7.10.x.
