### ISSUE TITLE
Override doesn't compose

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#16394]
## Issue description

Calling `override` on an already overriden value seems to override the base value, instead of the result of the first override.

### Steps to reproduce

Run `nix-instantiatiate --eval` on this file:

```nix
let
  pkgs = import <nixpkgs> {};

  hp = pkgs.haskell.packages.ghc7103;

  o1 = hp.override {
    overrides = self: super: {
      a = "hello";
    };
  };

  o2 = o1.override {
    overrides = self: super: {
      b = super.a;
    };
  };

in

  o2.b
```

### Expected result

`"hello"`

### Actual result

`error: attribute ‘a’ missing, at /path/to/override.nix:14:11
(use ‘--show-trace’ to show detailed location information)`

## Technical details

* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre83147.df89584

**Comment by cleverca22** [comment]
i think the issue is a conflict between how .override normally works, and how the haskel packages are using it

normally, you have different arguments going to override, and want to keep the latest value of each, but haskel is putting everything into a single overrides argument

**Comment by expipiplus1** [comment]
I couldn't find the place in nixpkgs where `.override` is being defined for haskell packages. Is this a simple fix, or something deeper?

@peti, it would be great to get your input on this too.

**Comment by peti** [comment]
It is true that overrides don't compose in the way you'd expect them to work in your example code. To make that happen, override would have to re-define itself on the overriden package set to take history into account, i.e. `super` would have to turn into a stack of values, possibly with some kind of `super` member so that `super.super` would allow you to move up the stack. I guess it's doable ... but I'm not sure whether it's worth the effort and added code complexity. Personally, I've never actually needed nested overrides, so I've never bothered to implement anything like this. If you have a compelling use-case, then I'd certainly be interested to know.

Anyway, if you'd like to see the `override` implementation, a good place to start is the `makeOverridable` function in `lib/customisation.nix`.

I hope this helps.

**Comment by expipiplus1** [comment]
My use case for this is maintaining a custom set of Haskell packages on top of the set provided by nixpkgs. At the moment the package set contains `mypkgs.haskellPackages` which is generated by overriding `nixpkgs.haskellPackages`. It's sometime necessary to temporarily override other packages where this package set is being used. This issue makes `mypkgs.haskellPackages` behave very differently to `nixpkgs.haskellPackages`, i.e. it can't be a drop in replacement for any code which requires overriding `haskellPackages`.

Given the confusing nature of `haskellPackages.override` currently it might be a good idea to remove it from an already overriden package set. 

The workaround I'm using at the moment is to pass in an `extraHaskellOverrides` attribute to `mypkgs` when it's created, which is merged into `overrides` when `nixpkgs.haskellPackages` is overriden.

I'm sure I've seen this workaround being used elsewhere when I was investigating this. But I can't seem to find it at the moment.

**Comment by peti** [comment]
> My use case for this is maintaining a custom set of Haskell packages on top of the set provided by nixpkgs.

Well, can you be a little more specific than this? What exactly are you doing that would be easy with stacked overrides but that is hard now without them?

**Comment by expipiplus1** [comment]
The overrides to create this custom set are changing the version of a few packages compared to what's in nixos-16.03 and adding several packages which are not in hackage. I also do builds with `mkDerivation` overriden to help generate a local hoogle server.

Any of the use cases for `.override` such as changing the source for a package, or compiling things with profiling enabled are harder because the package set we're compiling against has already been overriden. 

Using the `extraHaskellOverrides` workaround is not difficult to use, but it's a shame to lose the consistency which would be afforded by being able to stack overrides.

**Comment by peti** [comment]
I am sorry, but these abstract descriptions are really hard for me to follow.  I do all the things you describe there, too, and I have no trouble with the absence of a composable  override as you seem to have. Would you mind sharing a specific piece of source code that illustrates the problem you're having?

**Comment by expipiplus1** [comment]
sure thing. I'll try and post something this weekend.

**Comment by siddharthist** [comment]
@peti I'm also attempting to compose multiple overrides, is there a solution for this these days? My situation is like the following:
```nix
{ pkgs_old ? import ./pinned-pkgs.nix { }
, compiler ? "ghc843"
}:

let
  overrides1 = new: old: {
    my_new_pkg1 = ...;
    my_new_pkg2 = ...;
  };

  myHaskellPackages = pkgs_old.haskell.packages."${compiler}".override {
    overrides = overrides1;
  };

  brokenHaskellPackages = myHaskellPackages.override {
    overrides = new: old: {
      my_new_pkg2 = pkgs_old.haskell.lib.markBroken old.my_new_pkg1
    };
  };

  config = {
    packageOverrides = pkgs: rec {
      haskellPackages = brokenHaskellPackages;
    };
  };

  nixpkgs = builtins.fromJSON (builtins.readFile ./nixpkgs.json);

in import (pkgs_old.fetchFromGitHub {
  owner = "NixOS";
  repo  = "nixpkgs";
  inherit (nixpkgs) rev sha256;
}) { inherit config; }
```
I can attempt to build `my_new_pkg2`, after which I receive the expected error, but I can't build `my_new_pkg1` (it's missing from the selection path).

The use case is that I'm incrementally developing a large custom Haskell package set. I don't want to have to remove `my_new_pkg2` completely, just quickly and temporarily mark it as broken.

**Comment by stepcut** [comment]
I am also attempting to stack multiple overlays/overrides. Here is my user story:

I work on a development team and we want an overlay for our project and its dependencies. This works fine using overlays + override. Let's call that overlay `development.nix`.

But when developers have a package checked out locally, they'd like to be able to override some of those packages a second time so that the local version is built instead. So let's call that `local.nix`. 

If I attempt to use both overlays, one completely overrides the other.

I can work around this by having `development.nix` explicitly import `local.nix`. 

But it is still a bit disappointing that I need to create an adhoc solution to this problem and that the 'obvious' thing of just importing additional overlays does not work.
