### ISSUE TITLE
Docker service is absent from nixpkgs?

### ISSUE THREAD

**Issue by bbarker** [NixOS/nixpkgs#16427]
## Issue description
There doesn't appear to be a docker unit (.service file) installed in NixOS.

### Steps to reproduce

```
 sudo systemctl list-units
```

Observer the lack of 'docker'

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

    16.03.948.a96c308 (Emu)

* Nix version: (run `nix-env --version`)

    nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

    "16.03.948.a96c308"

**Comment by joachifm** [comment]
Did you enable the docker service module?

**Comment by bbarker** [comment]
Err. No , will check soon if that helps. But if so, how can one search for
available but unenabled services?
On Jun 22, 2016 12:55 PM, "Joachim Fasting" <notifications@github.com>
wrote:

Did you enable the docker service module?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/nixpkgs/issues/16427#issuecomment-227807235>, or mute
the thread
<https://github.com/notifications/unsubscribe/AA37jh7rBx7Pbya71qpkRUPkCOEi0mdxks5qOWjugaJpZM4I7-2M>
.

**Comment by joachifm** [comment]
If you didn't enable docker, the service file won't be installed; only certain upstream systemd units are installed unconditionally. Generally, you'll need to look for a module that provides the service you want and enable that. You can usually find the relevant module by searching for the service/daemon by name at https://nixos.org/nixos/options.html. In the case of docker, it is somewhat unfortunate that the result you want is on the second page of search results, but I believe the lookup result is simply alphabetized, so that's as good as it gets.

**Comment by joachifm** [comment]
For completeness, the option you want is `virtualisation.docker.enable`.

**Comment by bbarker** [comment]
@joachifm I see - thanks! That registry is very helpful to know about.
