### ISSUE TITLE
nix profile install .#libzip  fails because there is no folder matching the "dev" output

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#164610]
### Describe the bug

on nixpkgs b10adca6c87b78f2c6b2324474259087c3361cc1 with nix 2.7.0
```
nix profile install .#libzip    
error: opening directory '/nix/store/3cxqmjp211rj1qyr7ys87cyli9fx21n6-libzip-1.8.0-dev': No such file or directory
```
because pkgs/development/libraries/libzip/default.nix contains ` outputs = [ "out" "dev" "man" ];` and the dev folder doesn't exist.

If I remove the "dev" output then it works again. I can send a PR for that but I wonder if we shouldn't add some systematic check or workaround to avoid having the warning/

**Comment by dtzWill** [comment]
I started seeing these with my upgrade to nix 2.7.0 as well, lots of "error: opening directory" for outputs similar to but not part of my profile (`-debug`, `-man`, `-dev`) and as workaround just did `nix-store -r $PATH` for each :/.

I'm not sure of the cause, I was guessing something now expects these outputs as part of my profile.  Haven't confirmed happened with 2.7.0 vs not, if you're still experiencing this that might be good to check.

My guess/hunch was maybe it was packages I installed before adding `keep-outputs` to my `nix.conf`, which are now causing problems?
Anyway I'd guess it's a `nix` bug, but we'll see.

I wouldn't think changing `outputs` will help here, I'm not sure how it helped you.  As I remember it, the paths missing were outputs for paths already in my profile (not replacements/additions).  And that path above (the `libzip` one) didn't exist when you were doing your `nix profile install`, but it sure does in general for builders of `libzip`--it's available via binary cache with `nix-store -r /nix/store/3cxqmjp211rj1qyr7ys87cyli9fx21n6-libzip-1.8.0-dev` (and is non-empty).  So if the path exists, what is expecting it to exist (nix, presumably) and is that correct, and if it should exist then why doesn't it exist (failed to be realized?),

Sorry for some lack of clarity in the reporting above, I was trying _not_ to debug this immediately :grin:.  But since you're encountering something similar, want to at least get a +1 to see if others are too.

**Comment by FedX-sudo** [comment]
I do think this is a bug in Nix itself, specifically related to how flakes are parsing the `output` parameter. I ran `nix profile install` on several packages with the outputs defined and got the same error, but don't get the error on any other packages.

**Comment by teto** [comment]
should be closed by https://github.com/NixOS/nix/pull/6328 IIUC
