### ISSUE TITLE
Packaging request: Authelia

### ISSUE THREAD

**Issue by ettom** [NixOS/nixpkgs#165345]
**Project description**
Authelia is an open-source authentication and authorization server providing two-factor authentication and single sign-on (SSO) for web applications.

**Metadata**

* homepage URL: https://www.authelia.com/
* source URL: https://github.com/authelia/authelia
* license: Apache License 2.0
* platforms: linux

**Comment by 06kellyjac** [comment]
I'm working on this here and there

**Comment by LongerHV** [comment]
I have just packaged a binary release of Authelia and opened a [PR](https://github.com/NixOS/nixpkgs/pull/180381)

**Comment by dit7ya** [comment]
I had missed this issue and the linked PRs - and started working on https://github.com/NixOS/nixpkgs/pull/207931. Since authelia uses `pnpm` as the frontend package manager it has a generated package-lock.json which we may or may not want to check into source control. Feel free to close that one if someone has a better solution.

**Comment by 06kellyjac** [comment]
@dit7ya, sorry I've been dragging my feet a bit on this PR.

Building the front end from source is very nice. My PR just grabs the frontend from GH releases, this started pre `buildNpmPackage` being merged.

We might be able to add pnpm lockfile support to [fetch-npm-deps](https://github.com/NixOS/nixpkgs/tree/nixos-22.11/pkgs/build-support/node/fetch-npm-deps) at some point :shrug: 

How did you generate the lockfile? The commonly accepted method looks like `pnpm install` then `npm install --only-lock-file` but I think that still leads to differences

https://github.com/pnpm/pnpm/discussions/3367#discussioncomment-2919171

Since the package.json is actually very strict and not using any semver symbols like `^` it might actually remain accurate so we might not have that issue

**Comment by natsukium** [comment]
closed by #180469
