### ISSUE TITLE
21.11: git crashes on commits with SSH signatures

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#165958]
### Describe the bug
git pre-2.34 crashes when asked to show the signature of a commit signed with an ssh key:

```console
$ git show --show-signature 6d6dfc8fdf04b7b187128cea480aa467c80a2a08
BUG: gpg-interface.c:284: bad signature '-----BEGIN SSH SIGNATURE-----
U1NIU0lHAAAAAQAAAGgAAAATZWNkc2Etc2hhMi1uaXN0cDI1NgAAAAhuaXN0cDI1NgAAAE
EEJjeiqwgYxvFNPcSGHiJXIhuubNfMpqxpSstx+FwHCEJqBDYzrKRb0U7orqAw//nFhkwL
QvD/JyM3R95+EZRo0AAAAANnaXQAAAAAAAAABnNoYTUxMgAAAGQAAAATZWNkc2Etc2hhMi
1uaXN0cDI1NgAAAEkAAAAhAMXlaJQLAlRENc62oGdJbSjPkTkRJ3qdo1X98xbf6oWyAAAA
IH61bgYRswjrGJLzx/sJt9NcOONzQyr974E4hULdMUyK
-----END SSH SIGNATURE-----
'
fish: Job 1, 'git show --show-signature 6d6df…' terminated by signal SIGABRT (Abort)
```

This also happens if you e.g. have `%G?` in a `--pretty=format:` string to `git log`.

### Steps To Reproduce
1. have git 2.33.1 installed
2. in nixpkgs, `git show --show-signature 6d6dfc8fdf04b7b187128cea480aa467c80a2a08`
3. ...

### Expected behavior
it would be nice if it were possible to browse nixpkgs with the current stable version of nixos :)

### Additional context
I guess it's a little late to do much about this at this point; there are already ssh-signed commits merged into nixpkgs. Updating 21.11 to git 2.34.1 would probably fix it, though that introduces a backwards-incompatible change ('The "--preserve-merges" option of "git rebase" has been removed.') and has the potential to introduce more bugs...

(given 22.05 will release in at most two months, I am not particularly expecting this to get fixed, I just wanted to open an issue in the hope that anyone else running into this would be able to find some reference to it on google)

### Notify maintainers
@primeos @wmertens @globin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.29, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(ash): `"home-manager-21.11, nixos-unstable-22.05pre360796.73ad5f9e147"`
 - channels(root): `"nixos-21.11.336589.2c66a7a6e03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment]
https://github.com/NixOS/nixpkgs/commit/6d6dfc8fdf04b7b187128cea480aa467c80a2a08 seems like even GitHub cannot verify SSh signatures yet:

![image](https://user-images.githubusercontent.com/7537109/160295021-01363d36-f6dc-450d-8141-e0337463baff.png)

https://github.com/github/feedback/discussions/7744

I guess that makes it pretty useless at the moment (there's https://github.com/<username>.keys but still...). However, Git crashing is obviously not ideal, especially for your described `git-log` use case.
But I also think that fixing this in 21.11 is probably not worth it (Git remains very backward compatible so it should be acceptable but it should affect only very few people wit special Git configurations so that probably isn't reason enough).
Anyway, good to know that this is an issue :)

**Comment by sersorrel** [comment]
21.11 is long-obsolete now, closing.
