### ISSUE TITLE
overriding haskellPackages.cairo in overlay can lead to infinite loops

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#166004]
### Describe the bug
I've been trying to override haskellPackages.cairo with an overlay (for ghc9.2 support)
```
          hfinal: hprev: 
          let 
            gk2hs-src = pkgs.fetchzip {
               url = "https://github.com/teto/gtk2hs/archive/298e46920d850b450d10ceddd432fdcc106a7df4.tar.gz";
               sha256 = "sha256-bWnP7MpV10N/TqQVvS3cfRr7RG7pAR0FqPgerpwfzX4=";
           };
           in {
          gtk2hs-buildtools = hnew.callCabal2nix "gtk2hs-buildtools" "${gtk2hs-src}/tools" {};
           cairo = hnew.callCabal2nix "cairo" "${gtk2hs-src}/cairo"  {};
}
```
and then enter my `nix develop` but this triggered an infinite loop. After investigating a bit , turned out that haskellPackages.cairo depends from cairo (pkgs/development/libraries/cairo/default.nix), my  now overriden haskell cairo was passed as a buildInput instead ofthe C library hence the infinite loop.

What I did instead was copy/paste the nixpkgs definition for gtk2hs-buildtools and make sure I was passing the correct cairo at each step. Solved it.

### Expected behavior
Not sure. I wanted to at least log it.

### Metadata

(unstable):
```
+  ❯ nix flake metadata nixpkgs
Resolved URL:  github:NixOS/nixpkgs/nixpkgs-unstable
Locked URL:    github:NixOS/nixpkgs/30d3d79b7d3607d56546dd2a6b49e156ba0ec634
```

**Comment by sternenseemann** [comment]
This happens because `haskellPackages`, like all sub package sets in nixpkgs, uses a scoped `callPackage` where the attribute from the inner scope (`haskellPackages`) will take precedence over the attribute from the outer scope (`pkgs`).

In cases where the inner scope would take precedence, but something from the outer scope is needed, it needs to be specified manually by passing explicit `args` to `callPackage` (in the case of `hackage-packages.nix` these can be generated).

Your example would need to be adjusted like this:

```nix
          hfinal: hprev: 
          let 
            gk2hs-src = pkgs.fetchzip {
               url = "https://github.com/teto/gtk2hs/archive/298e46920d850b450d10ceddd432fdcc106a7df4.tar.gz";
               sha256 = "sha256-bWnP7MpV10N/TqQVvS3cfRr7RG7pAR0FqPgerpwfzX4=";
           };
           in {
          gtk2hs-buildtools = hfinal.callCabal2nix "gtk2hs-buildtools" "${gtk2hs-src}/tools" { inherit (pkgs) cairo; };
           cairo = hfinal.callCabal2nix "cairo" "${gtk2hs-src}/cairo"  {};
```

I don't think this is an issue / bug per se, as it is just a necessary problem with the way nixpkgs' scopes are designed. “Fixing” this would mean introducing an interface alien to nixpkgs which I'd like to avoid – `haskellPackages` has enough specific quirks as it is already.

**Comment by teto** [comment]
I understand there is no good solution in the short term so I'll close it but it's annoying. If we could only warn the user that the derivation may be in another set that would be already better.
