### ISSUE TITLE
waypipe package doesn't seem to import enough drivers

### ISSUE THREAD

**Issue by spiralw** [NixOS/nixpkgs#166177]
### Describe the bug
trying to run the `waypipe` example from upstream repo in nix-shell throws errors related to not being able to find drivers.

### Steps To Reproduce
```console
spiral@xps:~$ nix-shell -p waypipe

[nix-shell:~]$ waypipe ssh root@192.168.0.240 weston-terminal
```

### Expected behavior
`weston-terminal` app opens GUI on my local machine while running on remote server.

### Screenshots
```console
MESA-LOADER: failed to open iris: /run/opengl-driver/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast: /run/opengl-driver/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix _dri)
failed to load swrast driver
C375575:  1.260203 [src/dmabuf.c:177] Failed to create gbm device from drm_fd
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
S1063:  1.278067 [src/mainloop.c:875] application has closed
```

### Notify maintainers
@primeos

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
spiral@xps:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-46-generic, KDE neon, 5.23, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - channels(spiral): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

**Comment by colemickens** [comment]
That looks like you don't have opengl configured correctly in nixos.

**Comment by primeos** [comment]
Yes, in this case because it isn't NixOS (`KDE neon`). Unfortunately such OpenGL apps don't work out-of-the box on non-NixOS systems due to those hard-coded paths (`/run/opengl-driver`). It should be possible to override the path via `$LIBGL_DRIVERS_PATH` (https://docs.mesa3d.org/envvars.html) or `$LD_LIBRARY_PATH`. See https://github.com/NixOS/nixpkgs/issues/62169 and https://github.com/NixOS/nixpkgs/issues/9415 for more information (not sure if there's a guide in the wiki or blog posts). I'll go ahead and close this issue in favor of those issues then if you don't mind. Hopefully we'll have a better solution for this in the future.
