### ISSUE TITLE
fetchgit: doesn't update when modifying rev

### ISSUE THREAD

**Issue by YPares** [NixOS/nixpkgs#16645]
## Issue description

I have a nix file containing this configuration

```
  version = "2_7_0";
  src = fetchgit {
    url = "git://git.hpdd.intel.com/fs/lustre-release.git";
    rev = "refs/tags/v${version}";
    sha256 = "1gsb6j5ak25y0hxrigg8pqgayyxidnfhjfg238b0m0jhg9drmihx";
  };
```

After nix-building it, then modifying version to "2_8_0", nothing is updated and it doesn't complain about sha256 not being right.
## Technical details
- System: Ubuntu
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09pre83147.df89584

**Comment by edolstra** [comment]
This is because `fetchgit` returns a "fixed-output derivation", meaning its store path is determined only by the expected hash and the `name` attribute. When `rev` is `refs/tags/*`, `rev` is not included in `name` (see `urlToName` in `pkgs/build-support/fetchgit/default.nix`), so you don't get a rebuild.

**Comment by copumpkin** [comment]
To put it differently, this is expected behavior and is what allows us to swap out fixed-output derivations produced in one manner with ones produced differently. At the same time it isn't very user-friendly but I'm not sure there's a good universal answer for it. `fetchFromGitHub` just incorporates some of the source data into the name to make things rebuild as needed, but that isn't always feasible.

**Comment by YPares** [comment]
Ok thanks!
User-friendliness isn't really the problem, but it's definitely error-prone, because updating the `rev` doesn't cause nix to re-checkout the repository.
