### ISSUE TITLE
davinci-resolve: package studio version

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#166902]
Create package "davinci-resolve-studio".

Might need some changes to support license: https://github.com/NixOS/nixpkgs/pull/152113#issuecomment-1075642604

Check out other derivations like [nvidia](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/os-specific/linux/nvidia-x11/default.nix) to prevent duplication of code. Have one file for general package build and another one for specific versions. (not sure what the best practices are now)

You can add the beta versions too.

Follow up to https://github.com/NixOS/nixpkgs/pull/152113.

@jshcmpbll

**Comment by lukego** [comment]
I have an extra Resolve Studio license and I would be happy to make that available to a maintainer if that is helpful.

I have corresponded with support about the license mechanism. Each license can be used to activate two installations of Studio at one time. It is important to de-activate an installation before deleting it so that the license server knows how many installations are active and can continue to activate new ones. Support can reset a license if the activated copies were lost somehow but they are cautious about this due to past abuse.

I have found that license activation needs to write files into the resolve installation directory. This will require support in the Nix package (as discussed on the comment referenced above.) Support told me that other operations will also require writing to the resolve directory e.g. installation of new LUTs.

They are not interested in making changes to Resolve to accommodate non-CentOS users at this time. In the future they are considering a more distro-agnostic strategy but not for today.

**Comment by PAI5REECHO** [comment]
> You can add the beta versions too.

This would be very nice

**Comment by jshcmpbll** [comment]
@lukego Appreciate the offer but I have a studio license already 😄 Thanks for the insight/background information too! Just getting started on this

@PAI5REECHO I'm afraid I am unfamiliar with the beta releases for resolve.. Is there a page you can point me to or are we just referring to version `17.4.6` as opposed to `17.4.3`?

**Comment by davidak** [comment]
17.4.6 is the latest stable. i have seen that a beta version is in AUR, but it is for 17, so outdated. a beta for 18 will probably be released in the future...

https://repology.org/projects/?search=davinci-resolve&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

you could add a 17.0b10 beta now to have the package or later when a new beta version is released

**Comment by valwithoutfriends** [comment]
> 17.4.6 is the latest stable. i have seen that a beta version is in AUR, but it is for 17, so outdated. a beta for 18 will probably be released in the future...
> 
> https://repology.org/projects/?search=davinci-resolve&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=
> 
> you could add a 17.0b10 beta now to have the package or later when a new beta version is released

Resolve 18 beta is out now
