### ISSUE TITLE
Package request for dxhd (sxhkd but Golang)

### ISSUE THREAD

**Issue by rakinishraq** [NixOS/nixpkgs#167470]
**Project description**
Dxhkd (daky's X11 Hotkey Daemon) is a Go version of sxhkd with an elegant config syntax.

**Metadata**

* source URL: https://github.com/dakyskye/dxhd/tree/master
* license: mit
* platforms: linux, not sure about others...

**Comment by 06kellyjac** [comment]
Hi @rakinishraq thanks for showing interest

This package isn't packaged for any other normal [repos](https://repology.org/project/dxhd/versions) and it hasn't been updated for a couple of months, and the last tag being "18 Jun 2021" and the last GH release being "05 Apr 2021"

I'd say this is one more suited to a personal [NUR](https://github.com/nix-community/nur) as it seems very nichec 
But if you were going to maintain it I guess you could add it to the main nixpkgs

Another option is grabbing the release off GH since it is static it'd probably work on NixOS
Or use go to install it via `go get`/`go install`

---

```nix
{ lib, buildGoModule, fetchFromGitHub }:

buildGoModule rec {
  pname = "dxhd";
  version = "unstable-2021-11-11";

  src = fetchFromGitHub {
    owner = "dakyskye";
    repo = pname;
    rev = "e47570232b2d2a5bd90e7fdeab104443f3fd4048";
    sha256 = "sha256-k0yybeAKKy2670iq4nFl1QJCYnXmyFQGcSCx3AlZniM=";
  };
  vendorSha256 = "sha256-yL18s5n5PMo/oqjJ8jT6k/dm3AB9kIGX8Oa+TU06cI0=";

  ldflags = [ "-s" "-w" ];

  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    $out/bin/dxhd --help
    runHook postInstallCheck
  '';

  meta = with lib; {
    homepage = "https://github.com/dakyskye/dxhd/tree/master";
    description = "daky's X11 Hotkey Daemon";
    license = licenses.mit;
    platforms = platforms.linux;
    # maintainers = with maintainers; [ ];
  };
}
```

**Comment by rakinishraq** [comment]
Got it. I haven't heard of the NUR until now. Thanks for your time.
