### ISSUE TITLE
qtbase no longer builds on x86_64-darwin with zlib 1.2.12

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#167708]
### Describe the bug

After the `zlib` update, [qtbase fails to build](https://hydra.nixos.org/build/172211145) with an seemingly related build error on `x86_64-darwin`. This blocks the `nixpkgs-unstable` channel at the moment.

```
ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.
```

Possibly related: #166933.

### Steps To Reproduce

`nix-build -A qt5.qtbase`

### Notify maintainers

cc @ttuegel @qknight @periklis @bkchr @NixOS/darwin-maintainers

**Comment by vcunat** [comment]
Note: this affects both unstable and 21.11.

**Comment by leiserfg** [comment]
Is there any plan to make `nixpkgs-darwin` a different branch? unstable has been blocked for every platform for half a month because of darwin issues (after just a few days of being working after another more than a week block also because of darwin).

**Comment by willcohen** [comment]
From the perspective of a dual darwin/linux user, the issue seems to be that insufficiently tested PRs keep getting merged to master, which repeatedly regress behavior on darwin and break unstable. I'm not sure how downgrading darwin to not even deserve a place on unstable will do anything to alleviate the deeper issue that the PRs aren't being tested enough in the first place.

**Comment by vcunat** [comment]
If you use a Linux, why don't you use NixOS channels instead?  Even if you don't use a NixOS, the packages get extra testing through the NixOS tests.

**Comment by vcunat** [comment]
From the perspective of a person without any Apple devices, testing darwin stuff is quite hard, even though @OfBorg builds work nowadays, at least for small rebuilds.  Some people get even annoyed by having to deal with darwin-specific issues, and I have sympathy for that.

The zlib update in particular fixes quite a severe security problem.  I certainly would not want to delay that on Linux (or even on Darwins) because of the qtbase regression.

**Comment by willcohen** [comment]
That’s fair of course - the status quo has lots of underlying factors! I know it’s outside the scope of this issue, but should we all think about how to use some of the recently added Mac build machines to, say, be able to trigger something like a more full nixpkgs-review on packages that could cascade a bunch of failures like this? Barring that, I know that the Darwin maintainers group has grown a lot. If we could find a way to get looped in on some of these changes before merge, that might help avoid the breakage churn. There’s gotta be a way to help Linux-only maintainers and committers prevent regressions more proactively, rather than frantically fixing things after the fact. Sorry I don’t have an obvious solution!

**Comment by vcunat** [comment]
Well, it depends.  This regression in particular was known and reported (to a thread with quite many participants) before merging to master.

**Comment by leiserfg** [comment]
> If you use a Linux, why don't you use NixOS channels instead? Even if you don't use a NixOS, the packages get extra testing through the NixOS tests.

Is it possible to use nixos-unstable with home-manager in a non nixOS distro? If it is, I had no idea.

**Comment by vcunat** [comment]
I don't think there can be anything preventing it.  Though I don't really know home-manager in particular.

**Comment by reckenrode** [comment]
> Is it possible to use nixos-unstable with home-manager in a non nixOS distro? If it is, I had no idea.

I use `nixos-unstable` (along with `nixos-21.11`) on macOS, so presumably yes. The branch isn’t NixOS-specific. It’s just what criteria are used to advance the branch (so sometimes things are broken on Darwin IME).

**Comment by vcunat** [comment]
Non-NixOS Linuxes use the same binaries as NixOS (contrary to darwin).  And you always have the whole binary cache available, not just what's associated with the particular channel.

**Comment by leiserfg** [comment]
Thanks a lot, I'm changing to that branch right now, you made my day.

**Comment by toonn** [comment]
Fwiw, for Darwin in particular, nixpkgs-unstable does run some tests that nixos-unstable doesn't.

**Comment by vcunat** [comment]
Yes, NixOS channels have no dependency on darwin at all.

**Comment by leiserfg** [comment]
@vcunat  I did the change and it's working nice, but some packages are not getting downloaded from the cache (till now zathura and llpp) and painfully they also fail while compiling locally no idea why, any pointer to what can I check??. I know this is not the place to ask this kind of questions but I don't know which is the correct one either.

**Comment by sternenseemann** [comment]
> @vcunat I did the change and it's working nice, but some packages are not getting downloaded from the cache (till now zathura and llpp) and painfully they also fail while compiling locally no idea why, any pointer to what can I check??. I know this is not the place to ask this kind of questions but I don't know which is the correct one either.

There's no guarantee that everything in nixpkgs is working all the time, for zathura see [#https://github.com/NixOS/nixpkgs/issues/167700](https://github.com/NixOS/nixpkgs/issues/167700).
