### ISSUE TITLE
Hashlink - virtual machine for Haxe development

### ISSUE THREAD

**Issue by Ashe** [NixOS/nixpkgs#168248]
**Project description**
Hashlink is a virtual machine used in Haxe/Heaps game projects. This is the same stack that shiro games and motion twin uses to make things like Dead Cells and Northgard. The full steps for installing heaps (which goes through dependencies) can be found [here](https://heaps.io/documentation/installation.html), and one of the steps is to download hashlink and put it on the path.

**Metadata**

* homepage URL: https://hashlink.haxe.org/
* source URL: https://github.com/HaxeFoundation/hashlink/releases
* license: mit 
* platforms: linux, mac, windows

**Comment by iblech** [comment]
I am on it, will try to compose a first draft. :-)

**Comment by Ashe** [comment]
> I am on it, will try to compose a first draft. :-)

That was fast! I really appreciate it! I put in a few haxe-related package requests today, I'm so surprised no one else has requested them before! But once they're in we'll be happy! Not really looking to nix-ify my haxe projects yet since I imagine it'll be involved, but getting hashlink on the path in a package is a step in the right direction right? :) 

Really appreciate this, thank you!

**Comment by iblech** [comment]
I'm not really familiar with the Haxe ecosystem, but the Arch build for Hashlink suggested that this packaging task seemed simple enough (no complex build system, just a Makefile, no dependencies on other parts of the Haxe ecosystem) so that I could do it. Glad that I could be of help.

While the pull request is not yet merged, you can use hashlink as follows:

> nix-shell -I nixpkgs=https://github.com/iblech/nixpkgs/archive/patch-hashlink.tar.gz -p hashlink

(Be wary that commands like this can cause the execution of arbitrary code, so in principle one should use these only with trusted repositories.)

**Comment by Ashe** [comment]
Thanks for your hard work!

**Comment by Ashe** [comment]
@iblech how are things going with the PR? I think someone has asked a question on it, I don't know if that means that it's stalled from going in? 

Thanks again!

**Comment by Ashe** [comment]
There are in fact issues with hashlink on NixOS I think - I think there's some libraries that are build with hashlink that are unhandled - there's an issue for this already as hinted in your PR: https://github.com/HeapsIO/heaps/issues/939
