### ISSUE TITLE
Some Octave packages fail to build ever since 7.1.0

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#168943]
For example:

```
$ nix build -Lf. octave.pkgs.io
octave> Sourcing write-required-octave-packages-hook.sh
octave> Using writeRequiredOctavePackagesPhase
octave> unpacking sources
octave> unpacking source archive /nix/store/zh1w2v3fh79hrkx0cx37a1a48hvwhjiy-io-2.6.3.tar.gz
octave> source root is io-2.6.3
octave> setting SOURCE_DATE_EPOCH to timestamp 1604255252 of file io-2.6.3/src/octave_4_2_co
octave> patching sources
octave> building
octave> error: unlink: operation failed: No such file or directory
octave> error: called from
octave>     build at line 80 column 7
octave>     pkg at line 720 column 7
```

`octave.pkgs.signal` fails similarly. The line that causes the failure according to my testing is:

https://github.com/NixOS/nixpkgs/blob/7392416a539344c3b3d19c7e6cb7f4e6f49f72aa/pkgs/development/interpreters/octave/build-octave-package.nix#L115

A list of some packages that didn't break:

1. `octave.pkgs.netcdf`
2. `octave.pkgs.symbolic`
3. `octave.pkgs.control`

Could be this is an upstream issue.

**Comment by KarlJoad** [comment]
So digging into it, this is an issue raised by Octave's package management system itself. Namely, this `if`-statement from `octave-7.1.0/scripts/pkg/private/build.m`
```octave
## If there is no configure or Makefile within src/, there is nothing
## to do to prepare a "binary" package.  We only repackage to add more
## info to the tarball filename (version and arch).
if (! exist (fullfile (build_root, "src", "configure"), "file")
    && ! exist (fullfile (build_root, "src", "Makefile"), "file"))
  arch_abi = "any-none";
else
  arch_abi = getarch ();
  configure_make (desc, build_root, verbose);
  unlink (fullfile (build_root, "src", "configure"));
  unlink (fullfile (build_root, "src", "Makefile"));
endif
```
Line 80 in that file is the `unlink (fullfile (build_root, "src", "configure"));` statement. It expects to remove a `$build_root/src/configure` file, which is not existing. 

> A list of some packages that didn't break:
>
>    `octave.pkgs.netcdf`
>    `octave.pkgs.symbolic`
>    `octave.pkgs.control`
>
>Could be this is an upstream issue.

The reason the other packages did _not_ break was because they either do not have a `src` directory (`symbolic`) or they actually _do_ have a generated `configure` file (netcdf & control).

You can technically solve this by adding an empty `configure` script to the `src` directory. I manually did this, and the `io` package built correctly again.
As for _why_ this change happened, I cannot tell. The particular `if` statement shown did not change between 6.4.0 and 7.1.0 in the `build.m` file.

**Comment by abathur** [comment]
Looks like https://savannah.gnu.org/bugs/?func=detailitem&item_id=62436

**Comment by doronbehar** [comment]
> That's the exact issue. Seems like we will need to wait for upstream to fix it. How does this usually get handled @doronbehar?

Seems like we should apply to `octave` the patch:

https://savannah.gnu.org/support/download.php?file_id=53190

**Comment by KarlJoad** [comment]
There are still 5 packages failing to build, but that is a lot fewer than before.
