### ISSUE TITLE
RFP: filestash - web-based file manager

### ISSUE THREAD

**Issue by phaer** [NixOS/nixpkgs#169231]
**Project description**
Dropbox-like file manager that let you manage your data anywhere it is located:
[FTP](https://www.filestash.app/ftp-client.html) • FTPS • [SFTP](https://www.filestash.app/ssh-file-transfer.html) • [WebDAV](https://www.filestash.app/webdav-client.html) • Git • [S3](https://www.filestash.app/s3-browser.html) • [LDAP](https://www.filestash.app/ldap-browser.html) • Mysql
CardDAV • CalDAV • Backblaze B2 • [Minio](https://www.filestash.app/s3-browser.html)
Dropbox • Google Drive

Technically it's a go-app with an nodejs/webpack/react-based frontend and quite a few external dependencies. See dockerfile at https://github.com/mickael-kerjean/filestash/blob/master/docker/Dockerfile

**Metadata**

* homepage URL: https://www.filestash.app/
* source URL: https://github.com/mickael-kerjean/filestash
* license: AGPLv3
* platforms: unix, linux, darwin,

**Comment by mfrischknecht** [comment]
Just as an offer: I have tried to start a Nix expression for Filestash, mainly to learn more about Nix derivations myself. So far, I _think_ I succeeded in getting the Go part to build properly (not so simple considering it pulls in various Xorg libs via cgo), but: I am _absolutely_ stumped when it comes to the Node part.

I tried converting the npm lockfile to Nix with multiple conversion tools and had little luck so far. In fact, I am not even able to restore the npm packages by hand using npm. I'm always getting resolution errors, even with `--force` and `--legacy-peer-deps`.

Is there maybe someone here who has ideas on how I might fix that? Otherwise, I'll likely drop the project…

**Comment by phaer** [comment]
It's not in nixpkgs (yet), but @MatthewCroughan packaged it in a nix flake, thank! :tada:

https://github.com/MatthewCroughan/filestash-nix

**Comment by MatthewCroughan** [comment]
In my view, putting this into Nixpkgs is too much of a chore to keep up with maintenance. My flake automatically updates Filestash and performs a VM test, and blocks the channel so to speak if the upstream Filestash is broken, so the `master` of filestash-nix is always working. The VM Test is very basic and could do with some work though.

It would be really nice if this was merged so you could find this flake via search.nixos.org https://github.com/NixOS/nixos-search/pull/547

**Comment by phaer** [comment]
I agree, especially as we couldn't depend on dream2nix in nixpkgs yet afaik. And there's really no need to keep it in nixpkgs as long as its discoverable through search.

**Comment by edrex** [comment]
Update automation is currently broken https://github.com/MatthewCroughan/filestash-nix/actions

**Comment by Aixple** [comment]
any updates on this?
