### ISSUE TITLE
PHP composer question

### ISSUE THREAD

**Issue by mykiwi** [NixOS/nixpkgs#169363]
Hi,

I'm opening this issue because I'm wondering why `composer.phar` is not directly accessible in the `PATH`?
Sorry if this is a dumb question, I'm starting with Nix.

```
$ whereis composer
composer: /nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6/bin/composer

$ tree /nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6/
/nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6
├── bin
│   └── composer
└── libexec
    └── composer
        └── composer.phar
```

Relevant links:
- symfony-cli/symfony-cli#132

CC:
- PHP maintainers: @aanderse @drupol @etu @globin @ma27 @talyz

**Comment by etu** [comment]
This is because we expose three variations of composer,
- `php74.packages.composer`
- `php80.packages.composer` (aliased as `php.packages.composer`)
- `php81.packages.composer`

So if you install one of these you'd get a composer using that version of composer. If we "just" provided `composer.phar` in the path it wouldn't be reproducible since it would rely on the user also having PHP installed to a path, but not just that, it would also rely on the user having `unzip` installed to a path (which is also wrapped into the same wrapper).

**Comment by mykiwi** [comment]
Thank you for the explanation
