### ISSUE TITLE
[Haskell] Handle custom setup dependencies

### ISSUE THREAD

**Issue by k0ral** [NixOS/nixpkgs#16998]
Disclaimer: my understanding of the issue might be wrong, in which case sorry for the noise.

## Issue description
Haskell packages which rely on a custom `Setup.hs` to build (`build-type: Custom` in cabal file) may depend on non-haskell libraries. It seems that current haskell derivations cannot specify such dependencies: though there is the `libraryPkgconfigDepends` attribute, it isn't taken into account when executing `Setup.hs`. As far as I checked, there is no such thing as a `setupPkgconfigDepends` attribute.

### Steps to reproduce
`gi-cairo` is a good example:

```bash
> cabal unpack gi-cairo-1.0.3
```

Then setup a local nix derivation using cabal2nix [as explained in the manual][1] (I've observed the issue with both GHC 7.10.3 and 8.0.1). Due to https://github.com/NixOS/cabal2nix/issues/235, you might need to fix the derivation so that in the end it looks like this:

```nix
{ mkDerivation, base, bytestring, cairo, containers
, gobjectIntrospection, haskell-gi, haskell-gi-base, stdenv, text
, transformers
}:
mkDerivation {
  pname = "gi-cairo";
  version = "1.0.3";
  src = ./.;
  libraryHaskellDepends = [
    base bytestring containers haskell-gi haskell-gi-base text
    transformers
  ];
  libraryPkgconfigDepends = [ cairo gobjectIntrospection ];
  preConfigure = "export HASKELL_GI_GIR_SEARCH_PATH=${gobjectIntrospection.dev}/share/gir-1.0";
  homepage = "https://github.com/haskell-gi/haskell-gi";
  description = "Cairo bindings";
  license = stdenv.lib.licenses.lgpl21;
}
```

Then try and build it with `nix-build`, it should fail with the following error:

```
** (process:32612): WARNING **: Failed to load shared library 'libcairo-gobject.so.2' referenced by the typelib: libcairo-gobject.so.2: cannot open shared object file: No such file or directory
Could not resolve symbol "cairo_gobject_context_get_type" in namespace "cairo"
CallStack (from HasCallStack):
error, called at lib/Data/GI/CodeGen/LibGIRepository.hs:136:8 in
haskell-gi-0.18-8aZS3litRp8ES1uGR3vsBU:Data.GI.CodeGen.LibGIRepository
builder for ‘/nix/store/793gqnz12k94wxsqjvywn7xjalahvgp7-gi-cairo-1.0.3.drv’ failed with exit code 1
```

## Technical details

* System: NixOS 16.09.git.af25e01 (Flounder)
* Nix version: 1.11.2

[1]: https://nixos.org/nixpkgs/manual/#how-to-build-a-stand-alone-project

**Comment by peti** [comment]
Our Haskell builder does not support non-Haskell setup dependencies simply because Cabal does not: the [`PackageDescription`](http://hackage.haskell.org/package/Cabal-1.24.0.0/docs/Distribution-PackageDescription.html#t:PackageDescription) type uses `BuildInfo` to specify dependencies for libraries, executables, tests, and benchmarks, but the setup script gets to use the restricted `SetupBuildInfo` type, which lacks entries for anything other than Haskell dependencies. So arguably setup scripts that have system dependencies other than  those imported implicitly through other Haskell libraries are unsupported by the Haskell ecosystem. I'm not sure what exactly `gi-cairo` is doing here, but it looks a little like they shouldn't be doing it.

Anyway, you can work around this issue temporarily by adding the following override to `configuration-common.nix` 

~~~~
  gi-cairo = overrideCabal super.gi-cairo (drv: {
    preCompileBuildDriver = ''
      PKG_CONFIG_PATH+=":${pkgs.cairo}/lib/pkgconfig"
      setupCompileFlags+=" $(pkg-config --libs cairo-gobject)"
      '';
  });
~~~~~

or by adding those attributes directly into your local build expression.

**Comment by k0ral** [comment]
Understood, thank you.
In this case, the custom setup script generates haskell bindings from cairo-gobject library, therefore the "external" dependency at setup time looks legitimate to me. I'll check with `gi-cairo` maintainers.

**Comment by peti** [comment]
It may be "legitimate", but Cabal cannot express it.

**Comment by k0ral** [comment]
Since Cabal only makes it possible to express a non-Haskell dependency at library level, we could assume `compileBuildDriverPhase` always has the same pkgconfig dependencies as the library... or we can sparingly add exception rules as you just did for `gi-cairo`.
