### ISSUE TITLE
many python builds failing due to DeprecationWarning

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#170080]
https://gist.github.com/samuela/f4dad8455762fe70ef44044140081814

Why is deprecation warning an error instead of an warning?

**Comment by samuela** [comment]
This recently broke flax (https://github.com/NixOS/nixpkgs/issues/169504). What changed caused this?

**Comment by Artturin** [comment]
something in the staging merge https://github.com/nixos/nixpkgs/commit/95af2245a32f8e1310ad4e3bf50b76d86ddbbc0a
caused new `DeprecationWarning`s

**Comment by samuela** [comment]
Yet another case of staging causing mass breakages...

**Comment by SuperSandro2000** [comment]
> [gist.github.com/samuela/f4dad8455762fe70ef44044140081814](https://gist.github.com/samuela/f4dad8455762fe70ef44044140081814)_ (too large to embed)_

Those logs are incomplete and not very helpful. If we have the full logs most of the time it is very easy to pin down the failure.

> Why is deprecation warning an error instead of an warning?

Because people set ***** options like https://docs.pytest.org/en/6.2.x/warnings.html https://github.com/jupyterlab/jupyterlab_server/blob/main/pyproject.toml#L34-L38

> What changed caused this?

> caused new DeprecationWarnings

Updating pytest which always causes problems.

> Yet another case of staging causing mass breakages...

Yeah, this is deemed to happen. We cannot possible test everything and things just happen to break from time to time. 

But it didn't take me longer than a few minutes to pin point this down to pytest and figuring out the problematic setting.

**Comment by SuperSandro2000** [comment]
Turns out jupyerlab-server failed because of something else and the error just didn't bubble up. Fixed in #170154.

**Comment by SuperSandro2000** [comment]
Also fixes in #170154, #170155, #170156, #170158, #170159, #170160
