### ISSUE TITLE
Inochi2D: do not publish in-repo with branding

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [NixOS/nixpkgs#170315]
## Issue description
As per the response from the team in https://github.com/NixOS/nixpkgs/pull/170283, I would again formally request that Inochi2D does **NOT** get packaged in to the nixpkgs repository or the NUR. Or at the very least that if you package Inochi Creator and Inochi Session that you remove all branding (logo & mascot) from the user interface via external patches.

The Inochi2D project does not allow our branding assets to be used in projects that may tarnish our image; as a part of our target userbase is marginalized people I find the response in the above PR to warrant us not wanting to associate with NixOS.

Additionally, it does not make sense to package the Inochi2D package as a dynamic library, as that would lead to multiple D runtimes being loaded at once and cause 2 garbage collectors to conflict, which could cause crashes. The main Inochi2D project is *only* officially available on the dub D package database.

## Technical details
Files to omit:
 - res/ada-tex.png
 - res/logo.png

Files with code referencing assets which needs to be patched:
- source/creator/windows/about.d
- source/creator/windows/notice.d
- source/creator/widgets/titlebar.d
- source/creator/widgets/mainmenu.d
- source/creator/core/package.d

**Comment by grahamc** [comment]
Thanks for filing this request @LunaTheFoxgirl. I think it should be very easy to comply with your request to not be packaged, and it is very generous of you to include specifics of how an interested user could follow your wishes. I appreciate that.

**Comment by MagicRB** [comment]
If you wish your software be packaged without branding, change your license, simple. Add a clause such as:
```
I reserve the right to demand removal from any package repositories I personally do not like.
```
But then please also add a big fat warning that your project is proprietary and stop using all opensource/free software. We just had this discussion, you literally now judge a whole Linux distribution, by the fact that we refused to remove a package because the author happens to be a bigot and an asshole.

**Comment by adisbladis** [comment]
> Thanks for filing this request @LunaTheFoxgirl. I think it should be very easy to comply with your request to not be packaged

This software is _already_ not packaged, and like what @MagicRB says, unless there is a license issue involved with the assets I don't see why it wouldn't be up to the packager to comply with the request or not.

In any case as this is not packaged I'm considering this whole thing entirely a non-issue.

**Comment by alyssais** [comment]
Licenses are not the only intellectual property we have to consider in Nixpkgs.  Permission to use the logo and branding is also a trademark issue.  There's a pretty well established [precedent](https://en.wikipedia.org/wiki/Mozilla_software_rebranded_by_Debian) of free software that has to have the official branding stripped to be distributed in package repositories, and we've done it in Nixpkgs before.  It does not make the software non-free — it's even explicitly allowed by e.g. the GPL (§7e).

I don't think there's more action required to be taken here, since the software is indeed not currently packaged, but it's important to understand that it's more complicated than it simply being up to the packager whether they comply with the request or not.

**Comment by MagicRB** [comment]
Thats news to me. But doesn't a trademark have to be registered? Afaik theyre not automatic unlike copyright.

**Comment by LunaTheFoxgirl** [comment]
In my country of juristiction (Denmark) you automatically have copyright and trademark to the creations you make and name -- as long as the trademark is not already taken by an other thing in the similar domain.

**Comment by MagicRB** [comment]
Well you came to our issue tracker, after lunarequest opened an issue with a personal request. We at first declined, respectfully, then recommended to "gain thicker skin" which tbh is necessary. Then you came running, not having any previous affiliation with NixOS, demanded the exclusion of your project into the future, because we refused to remove a package based on personal issues. And no, the D runtime thing isn't your main motivator here, no point in pretending. And then on top of all that, you branded the whole NixOS community as cis white linux something on Twitter, tbh i dont remember. And no, just because person X may be transphobic, homophobic or any other phobic, isnt grounds for the removal of their package. It will never be. 

In fact, i do agree that the phrase "separate the artist from their art" is bullshit. But, i do believe that separating code, which carries no personal marks and creative forms of the author, from the author is the right thing to do. Yes if you happened to used the aforementioned nuclues thing and then ran into issues, then went to contact the author, you would told to fuck off. I have two responses to that hypothetical:
1. If you know people who will hate you just because you're trans exist, why not before joining a new community, do some anonymous surveying? You can have your cake and eat it too. Im not saying ro be ashamed of your identity, but for effectiveness and youe benefit, doing some research would be wise.
2. If you do happen to show up in a transphobic chat, just ignore them. Block them. Whatever, is it really worth your time to deal with their bullshit? Is it worth your to cry about said package on the NixOS bug tracker?

That's that. And before this devolved into an argument, just know that I was brutally honest above, because i value every person on earth and want to have a civil discussion with you. If i said something you disagree with, point it out. If you want to block me, go ahead. Let's talk. This whole thing escalated and while i stand behind "you two initiated it" ill admit some people, me included, could have reacted better.

**Comment by grahamc** [comment]
@LunaTheFoxgirl Like I said earlier, thanks for making it so easy to comply with your wishes. I believe it is well within the licensing of your software. I've also talked with a colleague who is an expert in software licensing who agrees.

@MagicRB, your comments here are inappropriate and unwanted. As I said in the other thread, it is up to us to create a community which supports trans people and makes trans people feel welcome. We have lots of trans contributors, and they're highly valued members of our community. Please do not tell anyone (especially marginalized people!) that they need to grow a thicker skin, or that they need to look for people who hate them first. Stop.

**Comment by MagicRB** [comment]
@grahamc i get what you mean, but you misunderstood me. What i meant was that we have no control over that place, that person who is transphobic. If he showed up here and started being tramsphobic on our channels you can bet id do something about it. But unfortunately the world is what it is and even though we here are nice and welcoming, some people aren't. Thats what i meant.

**Comment by MagicRB** [comment]
We really have no other recourse than to either remove the package, which we denied or do nothing like we decided to do. My suggestion and associated question was well meaning. @LunaTheFoxgirl can we discuss this privately? I do honestly want to settle this. It bothers me that it has ended up like it has, in another reality we could be friends. So please, from the bottom of my heart, can we talk about it DMs? Discord perhaps.

**Comment by grahamc** [comment]
@MagicRB I have asked you to stop, and your approach has been inappropriate in this thread. I'm instituting a 3 day ban from the GitHub repository.

**Comment by grahamc** [comment]
I've been in conversation with someone who has discussed this ticket with LunaTheFoxgirl, and is looking to package Inochi2D minus branding while complying with the author's wishes. LunaTheFoxgirl, if that isn't true let me know. Unless that happens, it looks like we may be receiving a PR to package it.

**Comment by LunaTheFoxgirl** [comment]
Yup, I've talked to the person in question and let them know the procedure to make an unofficial unsupported build which will let the end user know that it's not officially supported. As long as that procedure is followed then I have no issue it being on nixpkgs.

**Comment by orowith2os** [comment]
@luxus no, I looked into it but decided against it, as building offline (reproducibly) is *very* hard and I want to prioritize the flatpak package, as that can have the same end result but with better security (sandboxing), and more people use Flatpak than Nix.
