### ISSUE TITLE
Remove openjdk 12, 13, 14, 15, 16

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#170825]
All of these are EOL and releases >=15 haven't received fixes for psychic signatures vulnerability.

https://endoflife.date/java

@edwtjo @asbachb

**Comment by dasJ** [comment]
Is this still a release blocker? The versions have already been marked as insecure

**Comment by mweinelt** [comment]
Not a blocker anymore, but still should be removed.

**Comment by asbachb** [comment]
I guess for now we cannot remove them easily as they're needed to build the next jdks.

e.g. for 17 you need 16 to compile. So 16 is the so called bootstrap jdk.

I had a look at the current implementation. Currently for non x86 jdk builds NixOS is using adoptopenjdk binary builds and for x86 NixOS is using previous nixos packaged variant.

Basically the problem is that nor OpenJDK nor Adoptium is currently providing x86 builds for linux which we could use as binary bootstrap jdk.
