### ISSUE TITLE
noto-fonts-cjk: does not display correctly since #166600

### ISSUE THREAD

**Issue by ckiee** [NixOS/nixpkgs#171976]
### Describe the bug
Since #166600 `noto-fonts-cjk` no longer displays CJK text in Discord (old electron) and sometimes Element (happened, can't reproduce anymore, probably some cache)

### Steps To Reproduce
1. Use a recent `nixos-unstable` with #166600 in it.
2. `nix-shell -p discord --run discord`
3. Sign in
4. Send some CJK characters like `饼干是书呆子，但很棒` (friend sent that, not my words)

### Expected behavior
I expected the text to render. It displayed as missing character boxes.

###### Discord (electron)
![A screenshot of a discord message with broken text rendering and other details censored out](https://user-images.githubusercontent.com/25263210/167264791-fb7db9af-7030-4bf7-829e-03510fb14ca2.png)
###### Dunst (not)
![A screenshot of a dunst notification with the correct rendering, also some stuff censored out](https://user-images.githubusercontent.com/25263210/167264792-6299df68-e91d-45e3-bd69-d37c66b1d5d2.png)

### Additional context
Reverting #166600 fixes this so I've done that although I recognize that's probably not great to have in master.

I have a bunch of GNOME commits reverted in my tree so I hope it isn't that. It shouldn't be since electron doesn't touch GNOME I think..? Maybe GTK? I guess we'll see if anyone can reproduce.

### Notify maintainers
@Mathnerd314 @midchildan @emilazy

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
ckie@cookiemonster ~/git/nixpkgs -> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.36, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220428_4bb111c`
 - nixpkgs: `/run/current-system/sw/nixpkgs`
```

**Comment by Mathnerd314** [comment]
Well, my initial attempt failed, because I have a lot of fonts installed and it just picked another CJK font. Now I'm working on a VM test...

**Comment by Mathnerd314** [comment]
Alright, confirmed with a [hacky script](https://gist.github.com/Mathnerd314/39e5cac86adfdb7b1c244b3049409256)
![image](https://user-images.githubusercontent.com/322214/167267681-d8a881cc-df6a-4830-9932-7ba3527ffe8e.png)
It seems like discord is using the system harfbuzz, so that isn't the issue. Not sure if there is an easy fix.

**Comment by midchildan** [comment]
I'd hazard a guess that Discord isn't actually using the system harfbuzz. Browsers seem to bundle their own copy in their source trees:

https://chromium.googlesource.com/chromium/src/third_party/+/refs/heads/main/harfbuzz-ng/README.chromium

**Comment by Mathnerd314** [comment]
Ah, true. The browser string in the Discord binary is Chrome/91.0.4472.164 Electron/13.6.6. Looking at the log, the magic commit https://github.com/harfbuzz/harfbuzz/commit/da7dba0002616eab73b7dd1621274992ce6eb2aa only rolled around [Jan 12 2022](https://chromium.googlesource.com/chromium/src/third_party/+/3c97613d1cf831daba0340599dada7c4bd1d7426%5E%21/), which judging from the [version history](https://en.wikipedia.org/wiki/Google_Chrome_version_history) would correspond to Chrome 97 or 98. The latest versions of Electron are 100+, which probably is sufficient, so the issue is as [ckiee](https://github.com/ckiee) says, that Discord hasn't updated to the latest Electron. Incidentally there is also a security bug fixed in electron 13.6.8: [link](https://support.discord.com/hc/en-us/community/posts/5220185294615-Which-electron-version-is-discord-currently-using-), and an [open Electron bug](https://github.com/electron/electron/issues/31129) about backporting Harfbuzz 3.0

Well, as far as fixes, it suffices to recommend installing another CJK font that isn't variable. We could also package the non-variable Noto CJK font for some amount of time so people can easily install it if they run into problems. Or maybe there is some patchelf magic that would let us replace the harfbuzz in the discord binary?

**Comment by Mathnerd314** [comment]
Arch has some patches which allow using a system Electron 16 with Discord: https://aur.archlinux.org/packages/discord_arch_electron. But I think the font issue needs at least Electron 17, which according to a comment doesn't work for this patched Discord due to some JS issue.

**Comment by Mathnerd314** [comment]
Well, I guess fixing the problem right now does not seem to be an option. So, the viable options in more detail:
1. Recommend installing another CJK font that isn't variable for these old applications, e.g. Source Han that still uses the TTC
2. Revert Noto CJK to the TTC version, wait until Discord updates their version of Electron (could take months). Optionally package the variable font as a separate version `noto-fonts-cjk-vf`
3. Package the TTC version of Noto CJK as a separate version `noto-fonts-cjk-ttc`

Votes?

**Comment by ckiee** [comment]
Very nice investigation :D
> 
>1. Recommend installing another CJK font that isn't variable for these old applications, e.g. Source Han that still uses the TTC

Not feasible long term assuming you're planning to migrate all of them. Also, discord does not seem to be planning to upgrade their electron. (check the submitted date on the [AUR package](https://aur.archlinux.org/packages/discord_arch_electron))
> 
>2. Revert Noto CJK to the TTC version, wait until Discord updates their version of Electron (could take months). Optionally package the variable font as a separate version `noto-fonts-cjk-vf`
> 

This breaks less things for downstream users but will need an alias later on. (downvote)
> 
>3. Package the TTC version of Noto CJK as a separate version `noto-fonts-cjk-ttc`
> 

I think this is my favorite since it kind of hints "this is legacy" but we can keep it around for a while.

**Comment by midchildan** [comment]
My preference would be 2 or 3. Maybe revert #166600 and re-apply the changes a year later.

**Comment by Mathnerd314** [comment]
> discord does not seem to be planning to upgrade their electron. (check the submitted date on the [AUR package](https://aur.archlinux.org/packages/discord_arch_electron))

Discord 0.0.10 used Electron 7.1.11 while the current uses Electron 13, so Discord does update their version of Electron periodically. They just don't follow the Electron support guidelines to update in a timely fashion, which is why I said it could take months.

I guess there is a fourth option, add format annotations for all package names. Then we have packages `noto-fonts-cjk-sans-vf`, `noto-fonts-cjk-sans-ttc`, `noto-fonts-cjk-serif-vf`, `noto-fonts-cjk-serif-ttc`. This neatly solves the defaulting problem because now there is no default. ☺️ There is kind of a default in that `noto-fonts-cjk` aliases to something, but I think it is clear that it should alias to `noto-fonts-cjk-sans-vf`, because that is what we want people to install.

**Comment by midchildan** [comment]
Upon further thought, I think a temporary revert would be the safest option. Fonts not rendering is a pretty critical bug, especially for a font like Noto which is a popular choice for a system default. It would be best for users if they can just search for Noto CJK on https://search.nixos.org and get a single result that works. This way, when the time comes, we can just switch back to variable fonts transparently without having to deprecate packages or require changes in user configuration. It would be a different matter if Discord is the only affected application, but that's probably not the case since there are multiple other non-free Electron packages in Nixpkgs.

**Comment by Mathnerd314** [comment]
Discord 0.0.18 is out, but it still uses Electron 13.6.6. So no change.

**Comment by InternetUnexplorer** [comment]
Discord Canary 0.0.141 finally uses a newer version of Electron (17.4.9), hopefully this change will make its way to stable soon!

**Comment by Mathnerd314** [comment]
I checked and Discord PTB/Beta 0.0.38 uses Electron 17 now. But the stable build 0.0.21 is still at 13. It would be nice if someone could test the variable fonts and see if they work with the newer Discord builds.

**Comment by lilyinstarlight** [comment]
> I checked and Discord PTB/Beta 0.0.38 uses Electron 17 now. But the stable build 0.0.21 is still at 13. It would be nice if someone could test the variable fonts and see if they work with the newer Discord builds.

It looks like they do work with Discord PTB now! (Also native Wayland)

I've been using my web browser for Discord because of this, but I guess I can switch to the PTB client now :)

**Comment by ckiee** [comment]
I can (vaguely) reproduce @lilyinstarlight's comment:

In the Chromium Devtools console with "Electron Isolated Context" selected, for `process.versions.electron` I see "13.6.6" on stable and "22.2.0" on canary.

![CJK text not rendering in Discord message on stable](https://user-images.githubusercontent.com/25263210/230104432-79c243ee-8ad6-4d98-8c0a-4b365bae4d51.png)
![CJK text rendering in Discord message on canary](https://user-images.githubusercontent.com/25263210/230104598-a856e588-4031-41fe-91ee-d1d7c9ffc559.png)

```
ckie@cookiemonster ~ -> cat ~/.config/discord/settings.json | rg DEV
  "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true,
```


I suppose we continue to wait. They changed their built-in font stack so that seems to be why the missing glyph glyph changed.

**Comment by nevivurn** [comment]
I was running discord-ptb because I ran into this issue, but it seems to have been fixed in discord now. Can this issue be closed now?

**Comment by orowith2os** [comment]
Discord stable now uses modern electron, and it sounds like the issue is fixed there? Would like to close this if it's confirmed to be fixed on your end @ckiee

**Comment by ckiee** [comment]
I'm getting `process.versions.electron == '22.3.2'` now, and it does also seem to render fine here.

@midchildan, @Mathnerd314 - would one of you like to unrevert the workaround? I'm not very familiar with the font stack.
