### ISSUE TITLE
/run/opengl-driver is sometimes missing

### ISSUE THREAD

**Issue by danth** [NixOS/nixpkgs#172579]
### Describe the bug
Sometimes, `/run/opengl-driver` does not exist after boot. It is created after re-running the system activation script.

When the file is missing, it causes my Wayland compositor to fail to start as it cannot load the drivers. This has affected both Sway and Wayfire.

### Steps To Reproduce
I'm not sure how to reproduce this issue because it doesn't occur every time the machine is booted.

### Expected behavior
`/run/opengl-driver` should always exist, or be created.

### Additional context
This has happened with both Nvidia and Intel graphics, on different machines.

OpenGL is enabled using `hardware.opengl.enable = true`.

### Notify maintainers
Pinging some people who have edited the OpenGL module in the last few years.
@ambrop72 @jameysharp @joachifm @abbradar @delroth @jonringer

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.20220505.c777cdf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

**Comment by jameysharp** [comment]
This sounds to me like a missing dependency between systemd units.

`/run/opengl-driver` should be created by `systemd-tmpfiles-setup.service`. I get confused by systemd's dependency mechanisms pretty often, but I think `systemctl list-dependencies --before systemd-tmpfiles-setup.service` is the right one to look at. I believe your compositors need to show up in that list.

Since `sysinit.target` is ordered after tmpfiles, my current guess is that your compositors have `DefaultDependencies=no` in their systemd units, or are being started by a display manager with that setting. But that would be surprising, since there aren't any NixOS modules with that setting aside from basic things like filesystems or networking.

**Comment by danth** [comment]
> This sounds to me like a missing dependency between systemd units.

Turns out that I had a network mount unit which was incorrectly treated as a local filesystem. This created a dependency cycle, which Systemd resolved by skipping the tmpfiles service.

Thanks for pointing me in the right direction!

**Comment by jameysharp** [comment]
Wow, that's subtle. Nice work figuring it out!
