### ISSUE TITLE
official zeronet is abandoned, please patch or replace with active forks

### ISSUE THREAD

**Issue by caryoscelus** [NixOS/nixpkgs#173276]
even though Nix contains the latest official release of ZeroNet , official version is no longer updated and is becoming harder and harder to use (the most important thing – tor onion-v3 compatibility – can be solved with a patch) . however , we have a couple of more or less active forks (i'm the lead developer/maintainer of https://github.com/zeronet-conservancy/zeronet-conservancy) . i'm not sure what is the process of deprecating and replacing packages with forks , but since none of the forks can be considered official i feel like the best option is to make a package under new name and mark zeronet package as deprecated (suggesting updating to alternative)

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: zeronet
current version: 0.7.1
desired version: zeronet-conservancy and/or zeronetx

###### Notify maintainers

maintainers: @fgaz 

###### Note for maintainers

Please tag this issue in your PR.

PS: i'm not yet Nix user (even though very excited by the distro and planning to switch on my next machine ^_^) , which is why i'm only submitting an issue rather than a PR myself

**Comment by fgaz** [comment]
We should definitely mark zeronet as deprecated sooner or later... a project like that _needs_ security updates.

I see a couple of [other](https://github.com/ZeroNetX/ZeroNet) [forks](https://github.com/zeronet-enhanced/ZeroNet) (and even [a rust reimplementation](https://github.com/canewsin/zeronet-rs)!) but yours does look like the most active. One of the fork is even named like one of your suggestions, zeronetx, and it'd be best to avoid confusion. Maybe you could collaborate with @canewsin and/or @geekless so that there's more consensus on a successor?

cc @Madouura, what do you think?

**Comment by Madouura** [comment]
I'm not entirely sure, but I'm leaning towards keeping the zeronet package as-is, but throwing a warning somewhere and a suggestion to use something like zeronet-conservancy.
How does marking as deprecated work in nixpkgs?

**Comment by vcunat** [comment]
If it has security issues, I'd suggest `meta.knownVulnerabilities = [ "some explanation" ];`

**Comment by fgaz** [comment]
The zeronet package is indeed vulnerable. I did some research about the fork and I'm in favor of pushing users towards it.

I opened #173900 to address this.
