### ISSUE TITLE
timesyncd doesn't seem to sync if the clock is too far off (DNSSEC?) - thus breaking all DNS

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#174173]
### Describe the bug

I'm bringing up new RPis and their clocks are often wrong.

Even though upstream systemd has given `timesyncd` exceptions to be able to skip dnssec check for ntp sync, it doesn't... appear to be working.

If I set the date manually, often by time I check timesyncd will have already taken care of kicking in and it reports that it's synced.

### Steps To Reproduce
1. Skew the clock badly.
2. Enable `timesyncd`.
3. Reboot and see if your DNS works

**Comment by vcunat** [comment]
If I read it right, [their workaround](https://github.com/systemd/systemd/commit/abf4e5c1d3ad767bc0ed67883e8e4d916af095ec) only works for systemd-resolved.  A general workaround is to use hard-coded IP addresses for NTP (our routers actually do that IIRC).

**Comment by colemickens** [comment]
That commit seems to indicate that it should bypass DNSSEC for timesyncd. This would get my clock back in sync, thus resolving DNSSEC errors for the rest of the system. But timesyncd isn't doing its job. I assume that's because: date wrong -> dnssec failure. But maybe `timesyncd` also fails if the clock is just too askew?

I'll try to look more later, maybe I have to opt-in large corrections? Seems a bit weird to me. Or do we maybe use timesyncd in a non-standard way?

**Comment by Eisfunke** [comment]
I ran into this on a Raspberry Pi 3B. I'm using systemd-networkd including systemd-resolved. At some point DNS started failing, and I noticed the system clock was out of sync by about 4 hours and not synchronizing anymore. The log of systemd-resolved was full of DNSSEC `signature-expired`s:

```
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question pool.ntp.org IN SOA: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question NIXos.pool.ntp.org IN DS: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question NIXos.pool.ntp.org IN SOA: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question pool.ntp.org IN SOA: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question NIXos.pool.ntp.org IN DS: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question NIXos.pool.ntp.org IN SOA: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question 1.NIXos.pool.ntp.org IN DS: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question 1.NIXos.pool.ntp.org IN SOA: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question 1.nixos.pool.ntp.org IN AAAA: signature-expired
Jun 01 16:31:10 obsidian systemd-resolved[655]: [🡕] DNSSEC validation failed for question 1.nixos.pool.ntp.org IN A: signature-expired
```

I'm not sure what changed, because I was able to install NixOS just fine. It also was offline before for some time without this problem happening (as far as I noticed at least), and it started happening after it was online for some time without break.

Also, the systemd-native workaround should be working on NixOS as well, I can't find anything that indicates a non-standard setup that might overwrite tha workaround.
Checking `systemctl cat systemd-timesyncd` is the standard original systemd unit file that includes the relevant `Environment=` line and as far as I can see it isn't overridden. I also checked `/proc/[PID of the systemd-timesyncd process]/environ` and it includes `SYSTEMD_NSS_RESOLVE_VALIDATE=0`.

For now, I worked around the issue by specifying my NTP servers by IP (I used the ones by the [German PTB](https://www.ptb.de/cms/ptb/fachabteilungen/abtq/gruppe-q4/ref-q42/zeitsynchronisation-von-rechnern-mit-hilfe-des-network-time-protocol-ntp.html)).
