### ISSUE TITLE
Run nixpkgs-lint in travis

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#17458]
Seems like it would be helpful to run it on the diff to give people early feedback about common issues.

**Comment by matthewbauer** [comment]
There's a lot of warning on in master, so we may need to fix those first.

**Comment by copumpkin** [comment]
The ideal would be for the linter to only warn about lines you've touched, but that seems tricky.

Then we can whittle down the overall number of lint errors and also make it hard to add new ones.

**Comment by cmfwyp** [comment]
A simple solution is to check only the files modified. The list of files modified can be found with `git diff --numstat HEAD~1`. This means [nixpkgs-lint](https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/nixpkgs-lint.pl) needs to accept an argument for a file to only check that file instead of checking all of Nixpkgs.

Also, this might be a duplicate of #11265.

**Comment by copumpkin** [comment]
Oh, it is a dupe, sorry. I'll close!
