### ISSUE TITLE
argocd-autopilot: FATAL failed to build bootstrap manifests: failed running kustomization

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#174782]
### Steps To Reproduce
1. run `argocd-autopilot repo bootstrap`

```
FATAL failed to build bootstrap manifests: failed running kustomization: accumulating resources: accumulation err='accumulating resources from 'manifests/base': evalsymlink failure on '/home/bbigras/auto-pilot2292030908/manifests/base' : lstat /home/bbigras/auto-pilot2292030908/manifests: no such file or directory': evalsymlink failure on '/home/bbigras/auto-pilot2292030908/manifests/base' : lstat /home/bbigras/auto-pilot2292030908/manifests: no such file or directory
```

### Notify maintainers

@sagikazarmark @bryanasdev000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.39, NixOS, 22.05 (Quokka), 22.05.20220516.1d7db1b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-21.11pre299825.d8079260a30"`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by bryanasdev000** [comment]
Related to https://github.com/argoproj-labs/argocd-autopilot/issues/203

I think that is related to app URL, since I generally enforce it with `--app` flag I did not spot this bug until now.

Example:

```
argocd-autopilot repo bootstrap --repo https://github.com/user/repo --log-level debug --app "github.com/argoproj-labs/argocd-autopilot/manifests?ref=v0.2.5"
```

@bbigras could you please test with the command above? (NOTE: It will pull an old version to test, 0.2.5, just to make sure that it works).

Also, please make sure you are exporting GIT_TOKEN.

I will double-check if there is anything different between our expression and argocd-autopilot build scripts to make sure we are not breaking something.

**Comment by bryanasdev000** [comment]
Found a small typo, will test it.

```
@@ -24,7 +24,7 @@ buildGoModule rec {
       "-X ${package_url}.version=${src.rev}"
       "-X ${package_url}.buildDate=unknown"
       "-X ${package_url}.gitCommit=${src.rev}"
-      "-X ${package_url}.installationManifestURL=github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=${src.rev}"
+      "-X ${package_url}.installationManifestsURL=github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=${src.rev}"
       "-X ${package_url}.installationManifestsNamespacedURL=github.com/argoproj-labs/argocd-autopilot/manifests/insecure?ref=${src.rev}"
     ];
```

**Comment by bryanasdev000** [comment]
Yeap, fully working now, PR for it https://github.com/NixOS/nixpkgs/pull/175221
