### ISSUE TITLE
Syncthing updates to release-16.03

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#17509]
@pshendry @jokogr @peterhoeg 

Would it be possible to have the Syncthing updates merged to the release-16.03 branch as well? Without the updates, Syncthing simply doesn't work on this branch since the protocol isn't compatible with other Syncthing devices running up-to-date versions.

**Comment by jokogr** [comment]
This is also an issue for me, since my server is also on nixos-stable and I have to override the syncthing packages there, so that other clients (Android ones, ones from nixos-unstable) communicate properly with the nixos-stable server.

I have to emphasize that the package on nixos-stable does not require a bugfix, nor a security update; its developers have just broken backwards compatibility twice since 16.03 was released. However, as @a1russell pointed out, this compatibility refers to client communication. I think that system configuration won't break if version 0.12 is upgraded to 0.14.x

Having said that, I do not have sufficient permissions to push the upgrades to the stable channel, yet I endorse it :+1:

**Comment by joachifm** [comment]
One way to help move this along would be to open a PR against the release branch.

**Comment by rycee** [comment]
Closable?

**Comment by a1russell** [comment]
Yep!
