### ISSUE TITLE
makeBinaryWrapper produces binaries for build instead of host

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#175045]
making a pr fixing cross compilation for some things and found this
```
$ file .xdt-csource-wrapped
.xdt-csource-wrapped: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /nix/store/5gg0aph41cj424z5glbibq5381943his-glibc-aarch64-unknown-linux-gnu-2.34-210/lib/ld-linux-aarch64.so.1, for GNU/Linux 2.6.32, not stripped
$ file xdt-csource
xdt-csource: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, with debug_info, not stripped
```

```
nix-repl> pkgsCross.aarch64-multiplatform.stdenv.cc
«derivation /nix/store/hdsxwz94k248f1wmc2npfz8s2qq6c65p-aarch64-unknown-linux-gnu-stage-final-gcc-debug-wrapper-9.3.0.drv»

nix-repl> stdenv.cc
«derivation /nix/store/bl5y9zix1vsdiq6q0lxypggsahb65np5-gcc-wrapper-11.3.0.drv»
```

https://github.com/NixOS/nixpkgs/blob/dbd004ea9bee830402aa410c6b8a0a493efa454b/pkgs/build-support/setup-hooks/make-binary-wrapper/default.nix#L17

@ncfavier @bergkvist @milahu

**Comment by milahu** [comment]
... and `cc` defaults to `stdenv.cc` which is `buildPackages.cc` per https://github.com/NixOS/nixpkgs/issues/35543#issuecomment-368565351

missing compiler arguments? (target)

https://github.com/NixOS/nixpkgs/blob/dbd004ea9bee830402aa410c6b8a0a493efa454b/pkgs/build-support/setup-hooks/make-binary-wrapper/make-binary-wrapper.sh#L46-L52

maybe use cmake?

**Comment by ncfavier** [comment]
Something that seems to fix the problem, weirdly, is to add `makeBinaryWrapper` to `buildInputs` instead of `nativeBuildInputs`, and use `${cc}/bin/${cc.targetPrefix}cc` in https://github.com/NixOS/nixpkgs/blob/dbd004ea9bee830402aa410c6b8a0a493efa454b/pkgs/build-support/setup-hooks/make-binary-wrapper/default.nix#L17

I have no idea what's going on, need a cross-compilation guru (@sternenseemann ?).

**Comment by sternenseemann** [comment]
`stdenv` is special: All packages in a package set are build→host (e.g. the normal `gcc` attribute), `stdenv` however is derived from `buildPackages` and re-exposed as the thing that builds *this* package set. This gives rise to the inconsistency that `stdenv.cc` is one of the few attributes in the package set that's build→host.

Putting it into `nativeBuildInputs` (where it conceptually belongs) will of course pick `buildPackages.stdenv`. 

To pick the default compiler we should use to build here, it should take `targetPackages.stdenv.cc` by default where `targetPackages` would then be the package set *produced by* `buildPackages` which is the actual cross compiled set: `pkgsCross.aarch64-multiplatform.buildPackages.targetPackages.stdenv == pkgsCross.aarch64-multiplatform.stdenv`.

We need to jump through these hoops because, unfortunately the default compiler / libc etc. picking logic is only done as part of picking the `stdenv`'s from the *previous* package set.

**Comment by ncfavier** [comment]
> All packages in a package set are build→host

Do you mean host→target here?

**Comment by sternenseemann** [comment]
> Do you mean host→target here?

Yes, fixed.

**Comment by ncfavier** [comment]
Attempting a fix in https://github.com/NixOS/nixpkgs/pull/175317

**Comment by Mindavi** [comment]
Thanks for reporting this Artturin! Verified the PR that was made and merged :)
