### ISSUE TITLE
Declarative management of user environments and config files

### ISSUE THREAD

**Issue by jameshfisher** [NixOS/nixpkgs#1750]
I have a user called `james` declared in my `configuration.nix`. What's not clear to me is how I customize those users' environments and config files. For example, can I declare that `james` should have
- some extra package, e.g. `pkgs.git`, installed and available just to him.
- a file `.gitconfig` in his home directory with such-and-such contents in it. (Or, more generally, an arbitrary set of files to be put in the home directory.)

On the second point, I suppose ideally this kind of config should be done by Nix expressions in the same way as global config files are. But there are always going to be custom things that are not covered by the options in `configuration.nix`, so I would expect there to be a lower-level way to declaratively manage those things. Is it currently possible?

**Comment by domenkozar** [comment]
Prototype implementation: https://github.com/NixOS/nixpkgs/pull/9250

**Comment by zimbatm** [comment]
This would be huge.

Right now most nixos users are also root on their machines and thus tend to encode everything on a system level. As a non-root user it's hard to port all of my config to another machine. It would great if instead I could port a set of nix expressions and have everything installed with a single command.

**Comment by kamilchm** [comment]
Declarative user enviroment was the biggest benefit of using NixOS that I thought I would get after moving to NixOS.
Because of that this was my first target as NixOS user.
I found __package collections__ on https://nixos.org/wiki/Howto_keep_multiple_packages_up_to_date_at_once and started to do it that way, ended with https://github.com/kamilchm/.nixpkgs where I declare all packages and configs I need.
So if I'll need to move to different machine everything I need is just ``git clone ...`` and ``nix-env -i all``.

Maybe I don't understand this PR correctly, but I can _port all of my config to another machine_ now without this PR.
But it would be great if we get standard solution with separate command design exactly for this :+1:

**Comment by zimbatm** [comment]
That's really cool. Thanks a lot for the example !

**Comment by anderspapitto** [comment]
@kamilchm I don't quite follow how your setup works for dotfiles. For example, does your .bashrc file end up in your home directory? It seems to be installed in `$out/userHome`, which presumably is a path in `/nix/store` - so how does bash know to look there for its config file?

**Comment by kamilchm** [comment]
Yoou're right, it's not complete,
I've done one thing after `nix-env -i all`:
```
find .nix-profile/userHome/ | sed "s/.nix-profile\/userHome\///g" | grep -v "^$" | xargs -I {} echo "ln -s ~/nix.profile/userHome/{} ~/{}"
```

**Comment by domenkozar** [comment]
See http://nix-cookbook.readthedocs.io/en/latest/faq.html#how-can-i-manage-dotfiles-in-home-with-nix

**Comment by asymmetric** [comment]
An alternative to [sheenobu/nix-home](https://github.com/sheenobu/nix-home) (mentioned in the [nix-cookbook FAQ](http://nix-cookbook.readthedocs.io/en/latest/faq.html#how-can-i-manage-dotfiles-in-home-with-nix)) is [rycee/home-manager](https://github.com/rycee/home-manager).
