### ISSUE TITLE
terminal-server looks interesting

### ISSUE THREAD

**Issue by rvl** [NixOS/nixpkgs#17602]
## Issue description

The module `<nixpkgs/nixos/modules/services/x11/terminal-server.nix>` looks highly interesting but I'm unable to get it to work.
### Steps to reproduce

Follow this guide: http://nixer.ghost.io/nixos-in-the-cloud/
### Unexpected results
1. Need to rename `pkgs.xorgserver.out` to `pkgs.xorg.xorgserver.out`.
2. `x11vnc` can't access su. The `sed` script on `x11vnc/ssltools.h` needs updating but I couldn't get it right. Workaround was to `source ${config.system.build.setEnvironment}` in the `ExecStart` script
3. The display manager which is started looks extremely basic, doesn't seem to be kdm.
4. The setting of `services.xserver.displayManager.kdm.enable` should use `mkDefault` I think.
5. I wasn't able to get x11vnc to actually start XFCE, but I could run `DISPLAY=:20 xterm` from ssh and then launch `xfce-session`.
6. After some sleep interval, the service would report "XDM: too many retransmissions", and exit.
7. If connecting to x11vnc over a websocket using noVNC, a browser-accepted ssl cert needs to be used. I wasn't sure how to specify it, but it should be an option for the service.
## Technical details
- System: NixOS: 16.09.git.20f009d (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09.git.20f009dM"

**Comment by danbst** [comment]
It looks like terminal-server is abandoned and has no tests for it.
I'm too interested in it working out of box (and shipped with up-to-date documentation).

**Comment by timsears** [comment]
I just tried a version of this on a recent version of the unstable channel. I copied the service directly into my configuration.niz so I could use lightdm instead of the default. Terminal Server starts and can initially connect. Appears to time out after 10 seconds. 

**service definition from configuration.nix**
 systemd.sockets.terminal-server = {
    description = "Terminal Server Socket";
    wantedBy = [ "sockets.target" ];
    before = [ "multi-user.target" ];
    socketConfig.Accept = true;
     socketConfig.ListenStream = 5900;
  };

  systemd.services."terminal-server@" = {
    description = "Terminal Server";
       pkgs.xorg.xorgserver.out pkgs.gawk pkgs.which pkgs.openssl pkgs.xorg.xauth
       pkgs.nettools pkgs.shadow pkgs.procps pkgs.utillinux pkgs.bash
     ];

     environment.FD_GEOM = "1024x786x24";
     environment.FD_XDMCP_IF = "127.0.0.1";
     #environment.FIND_DISPLAY_OUTPUT = "/tmp/foo"; # to debug the "find display" script

     serviceConfig = {
       StandardInput = "socket";
       StandardOutput = "socket";
       StandardError = "journal";
       ExecStart = "@${pkgs.x11vnc}/bin/x11vnc x11vnc -inetd -display WAIT:1024x786:cmd=FINDCREATEDISPLAY-Xvfb.xdmcp -unixpw -ssl SAVE";
       # Don't kill the X server when the user quits the VNC
       # connection.  FIXME: the X server should run in a
       # separate systemd session.
       KillMode = "process";
     };
 };

**journalctl log...**

Apr 08 09:34:28 nassella systemd[1]: Started Terminal Server (10.0.0.14:55433).
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 10167
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 wait_for_client: WAIT:1024x786:cmd=FINDCREATEDISPLAY-Xvfb.xdmcp
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 wait_for_client set: w=1024 h=786
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/4096
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 Initializing SSL (server connect mode).
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 RAND_file_name:
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 initialized PRNG with 64 random bytes.
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 created  512 bit temporary RSA key: 0.006s
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 created 1024 bit temporary RSA key: 0.046s
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 Using SSL Certificate:
Apr 08 09:34:28 nassella x11vnc[10167]: -----BEGIN CERTIFICATE-----
Apr 08 09:34:28 nassella x11vnc[10167]: MIID3DCCAsSgAwIBAgIJAJ7mjQficn3mMA0GCSqGSIb3DQEBCwUAMIGhMQswCQYD
Apr 08 09:34:28 nassella x11vnc[10167]: VQQGEwJBVTEOMAwGA1UEBwwFTGludXgxIzAhBgNVBAsMGm5hc3NlbGxhLTE0OTA5
Apr 08 09:34:28 nassella x11vnc[10167]: MTg4NzMuMDU3MjQ1MQ8wDQYDVQQKDAZ4MTF2bmMxJjAkBgNVBAMMHXgxMXZuYy1T
Apr 08 09:34:28 nassella x11vnc[10167]: RUxGLVNJR05FRC1DRVJULTIyMTE5MSQwIgYJKoZIhvcNAQkBFhV4MTF2bmNAc2Vy
Apr 08 09:34:28 nassella x11vnc[10167]: dmVyLm5vd2hlcmUwHhcNMTcwMzMxMDAwNzUzWhcNMTgwMzMxMDAwNzUzWjCBoTEL
Apr 08 09:34:28 nassella x11vnc[10167]: MAkGA1UEBhMCQVUxDjAMBgNVBAcMBUxpbnV4MSMwIQYDVQQLDBpuYXNzZWxsYS0x
Apr 08 09:34:28 nassella x11vnc[10167]: NDkwOTE4ODczLjA1NzI0NTEPMA0GA1UECgwGeDExdm5jMSYwJAYDVQQDDB14MTF2
Apr 08 09:34:28 nassella x11vnc[10167]: bmMtU0VMRi1TSUdORUQtQ0VSVC0yMjExOTEkMCIGCSqGSIb3DQEJARYVeDExdm5j
Apr 08 09:34:28 nassella x11vnc[10167]: QHNlcnZlci5ub3doZXJlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
Apr 08 09:34:28 nassella x11vnc[10167]: 3kgiYOHceHfJOvq16MJXTnWnkPHfBodxfgbCxk56NFxf5u0YRMgBz8nmhFiLbTYd
Apr 08 09:34:28 nassella x11vnc[10167]: U+A9BKJrXltJXQPvKgImDxR7Z7oEyRNNF7GhJ2qyjbhoJhLAfkbHErQesCj7iiBJ
Apr 08 09:34:28 nassella x11vnc[10167]: o6Hrlnitya5EEKZRM7rIRBAn0eJ5vQPthYzwpkGR7ETfcg5O4C43KcTgUlVwQOtf
Apr 08 09:34:28 nassella x11vnc[10167]: xh9oMsSQYL1KR81Xa2gJqpXgQadO6ebtmBvEETvRz0Ikr4nkvwGmNz2KLhfZ6weh
Apr 08 09:34:28 nassella x11vnc[10167]: t//NDbjtGahTrCNdKxKkL0SzJ1caVqDWcgI0UoBvrKdGpIhPFWPJUV1WG438zRxz
Apr 08 09:34:28 nassella x11vnc[10167]: UKIyHidYm0SQphwIpF5cAQIDAQABoxUwEzARBglghkgBhvhCAQEEBAMCBkAwDQYJ
Apr 08 09:34:28 nassella x11vnc[10167]: KoZIhvcNAQELBQADggEBACOdb9zNYjJSNZqArQJtpdMVhuEZeZGaow3pligPDegc
Apr 08 09:34:28 nassella x11vnc[10167]: Uzw4zPCpOdREfgZQ0xlseAkzJ47GX133QWzV8GlQKZRsvM2g1s9NrhEZxLqkpoSV
Apr 08 09:34:28 nassella x11vnc[10167]: 9m9iVZ4jOURAAweFNjAR76iiADT4C762YQnQQAMs8cfdGUtllcehy1Sk3o4peCEW
Apr 08 09:34:28 nassella x11vnc[10167]: gKD62cHXkfFjx30kQ7g4teqDRw0Rjmg0f16/KTHNK/nkP36pYlS+uISC2WrQZHed
Apr 08 09:34:28 nassella x11vnc[10167]: eab6ksc9FzvNviKrzDfh8YeI8PN1efiDELhlI5rWN2MNEysCCnncQKGMVGYxK7iQ
Apr 08 09:34:28 nassella x11vnc[10167]: egzNJZ3rJ7MpqFS3i53unqYZNPevOLRsC2nt/T0mp94=
Apr 08 09:34:28 nassella x11vnc[10167]: -----END CERTIFICATE-----
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 using PEM /root/.vnc/certs/server.pem  0.000s
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 accept_openssl: using socketpair: 3 4
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 SSL: (inetd) spawning helper process to handle: 0.0.0.0:55433
Apr 08 09:34:28 nassella x11vnc[10167]: 08/04/2017 09:34:28 SSL: helper for peerport 55433 is pid 10168:
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 check_vnc_tls_mode: waited: 1.412815 / 1.40 input: (future) RFB Handshake
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 check_vnc_tls_mode: version: 3.8
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 check_vnc_tls_mode: reply: 18 (ANONTLS)
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 Using Anonymous Diffie-Hellman mode.
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 WARNING: Anonymous Diffie-Hellman uses encryption but is
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 WARNING: susceptible to a Man-In-The-Middle attack.
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 loaded Diffie Hellman 1024 bits, 0.000s
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 SSL: ssl_init[10168]: 0/1 initialization timeout: 20 secs.
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 SSL: ssl_helper[10168]: SSL_accept() succeeded for: 0.0.0.0:55433
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 SSL: ssl_helper[10168]: Cipher: TLSv1/SSLv3 ADH-AES256-GCM-SHA384 Proto: unknown
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 SSL: ssl_helper[10168]: accepted client 0.0.0.0 x509 peer cert is null
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 SSL: ANONTLS mode=1 accepted. helper[10168]
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 SSL: handshake with helper process[10168] succeeded.
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30   other clients:
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 incr accepted_client=1 for UNNAMED_AF_UNIX:0  sock=3
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 rfbUnregisterTightVNCFileTransferExtension: 1
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 new client: UNNAMED_AF_UNIX in non-unixpw_in_rfbPE.
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 accept_openssl: renaming client 'UNNAMED_AF_UNIX' -> '0.0.0.0'
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 client progressed=1 in 0/0 0.000000 s
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 wait_for_client: got client
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 taking unixpw_client off hold.
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 rfbProcessClientSecurityType: executing handler for type 1
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 Enabling LastRect protocol extension for client 0.0.0.0
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 Enabling full-color cursor updates for client 0.0.0.0
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 Enabling NewFBSize protocol extension for client 0.0.0.0
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 Using image quality level 9 for client 0.0.0.0
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 Using tight encoding for client 0.0.0.0
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30 Pixel format for client 0.0.0.0:
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30   16 bpp, depth 16, little endian
Apr 08 09:34:30 nassella x11vnc[10167]: 08/04/2017 09:34:30   true colour: max r 31 g 63 b 31, shift r 11 g 5 b 0
Apr 08 09:34:40 nassella x11vnc[10167]: 08/04/2017 09:34:40 SSL: ssl_xfer[10168]: closing sockets 4, 0, 1
Apr 08 09:34:40 nassella x11vnc[10167]: 08/04/2017 09:34:40 SSL: ssl_helper[10168]: exit case 7 (ssl_xfer done)
Apr 08 09:34:40 nassella x11vnc[10167]: 08/04/2017 09:34:40 client_count: 0
Apr 08 09:34:40 nassella x11vnc[10167]: 08/04/2017 09:34:40 sending SIGTERM to ssl_helper_pid: 10168
Apr 08 09:34:40 nassella x11vnc[10167]: 08/04/2017 09:34:40 inetd viewer exited.

**Comment by rvl** [comment]
Will close this for the time being because I have no imminent plans to fix the module.
