### ISSUE TITLE
Hamsket 

### ISSUE THREAD

**Issue by alemswaj** [NixOS/nixpkgs#176526]
Free and Open Source messaging and emailing app that combines common web applications into one. 
It is fork/successor to Rambox community edition. Since Rambox went closed source this could be useful.

**Metadata**

* homepage URL: https://github.com/TheGoddessInari/hamsket
* source URL: https://github.com/TheGoddessInari/hamsket/releases
* license: gpl3+
* platforms: linux

**Comment by raspher** [comment]
- https://github.com/ramboxapp/community-edition is no longer maintained and was archived on Apr 22, 2022
- https://github.com/TheGoddessInari/hamsket was archived on Oct 13, 2023 without notice. 

Because of the above, i'm closing this issue. If you feel it's still a need to package this, feel free to reopen 🙂

**Comment by eclairevoyant** [comment]
it's er... [already in nixpkgs](https://github.com/NixOS/nixpkgs/commit/304ccf2486da4113c02002aa5bac6187f43c8d80).
