### ISSUE TITLE
clang 3.8 retains runtime reference on the python that built it

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#17789]
@andrewrk @vcunat I noticed that clang 3.8 now retains the python that built it, seemingly because you added python to the `buildInputs` and `patchShebangs` now notices it and kills it from python scripts that have been around for a while.

These are the references, all in python shebangs:
- bin/git-clang-format
- bin/scan-view
- bin/set-xcode-analyzer
- share/clang/clang-format-diff.py
- share/clang/clang-tidy-diff.py
- share/clang/run-clang-tidy.py

At least one of those scripts (`git-clang-format`) was in 3.7.1 too, but its shebang was left as `/usr/bin/env python`.

This causes me some pain since it messes quite deeply with the bootstrap sequence in the darwin stdenv. It also feels a little icky that those tiny tools would be retaining a 54M closure for Python.

Not sure what to do to fix it: I could not patch those shebangs, or I could remove those scripts, or I could move them to a separate output. Lastly, I could reshuffle the entire darwin bootstrap to account for those tiny scripts, but I'll let you guess which option I want to do the least 😄 

Any thoughts?

**Comment by copumpkin** [comment]
It also looks like it's retaining an unnecessary reference to libxml2 (80MB) via `bin/c-index-test`, which appears to be a testing tool that probably doesn't need to be distributed.

**Comment by vcunat** [comment]
Are any of those even useful at all? They could go into a separate output, or they could be purged depending on an option set during bootstrapping...

**Comment by vcunat** [comment]
There's also 3.8.1, but I don't expect that bump to change anything related to this issue.

**Comment by dtzWill** [comment]
Yeah, they still exist in trunk too (4.0.0).  IMO they're definitely useful, I like the idea of making their inclusion optional.  I'd imagine there are other things you'd want to do for a bootstrap build ( so maybe they can be grouped under this flag?

Other things that I can think of are mostly LLVM-related:

* "-DLLVM_TARGETS_TO_BUILD=host"
* "-DCOMPILER_RT_BUILD_SANITIZERS=OFF"
* "-DCOMPILER_RT_BUILD_XRAY=OFF"
* "-DLLVM_ENABLE_BACKTRACES=OFF"
* "-DLLVM_ENABLE_TERMINFO=OFF"
* "-DLLVM_ENABLE_THREADS=OFF"

(etc.)

These are all useful things but since the first thing you do with a bootstrap set of tools is build a new compiler, there's no reason to include things like support for sanitizers :).

(I don't have a darwin machine but I'm interesting in an llvm-only bootstrap so this is related to my interests/work :grin:)

**Comment by dtzWill** [comment]
Regarding `c-index-test`, looks like LLVM_INSTALL_TOOLCHAIN_ONLY might be the way to go (and if naming is any guide, relevant to bootstrap purposes too).

Maybe that'll remove a number of these references?

**Comment by copumpkin** [comment]
Does the separate output appeal to you? They'd end up in a separate `bin` folder, but wouldn't add to the runtime closure of the stuff I need in the bootstrap, and would generally save most people from having to care about having them around unless they want them.

**Comment by dtzWill** [comment]
Putting them in a separate output sounds good to me!  I mostly don't want to have to rebuild clang or something just to get a tiny python script for my development use hehe.  Separate output works nicely :+1:

**Comment by Profpatsch** [comment]
(triage) has this been fixed?

**Comment by dtzWill** [comment]
I believe so! I just built clang_38 (source of this issue) and clang_6 and don't see python in the closure of the default output of either.  And I recall we have 'python' outputs ---err I just double-checked and yep `clang_38.cc.python` is a thing, for example.

Thanks for asking, closing since this seems resolved for the above reasons.

**Comment by olejorgenb** [comment]
In case anyone else is looking for the python tools: They're under "share/clang" in the `clang.cc.python` package
