### ISSUE TITLE
awscli2: cryptography package version mismatch

### ISSUE THREAD

**Issue by michielboekhoff** [NixOS/nixpkgs#178344]
### Steps To Reproduce
1. build `awscli2` on the `master` branch
2. see error

### Build log
https://gist.github.com/michielboekhoff/9ff1208201775ee8efb4e751c5af2c55

### Additional context
This seems to have been introduced via a combination of commit 5377b75a52156cf3cc94cb0fa3e8237ef76a0856 & a bump of the version of the cryptography package in 4561bf0464c55d4871ca7d32042bf8f2ec81cad4. I've confirmed that reverting 5377b75a52156cf3cc94cb0fa3e8237ef76a0856 & correcting the version fixes the problem, and it might make sense to keep this in because of [this comment](https://github.com/aws/aws-cli/issues/5943#issuecomment-780078645).

My (confirmed) diff:
```
diff --git a/pkgs/tools/admin/awscli2/default.nix b/pkgs/tools/admin/awscli2/default.nix
index 305a1e719f5..8ba850b6ead 100644
--- a/pkgs/tools/admin/awscli2/default.nix
+++ b/pkgs/tools/admin/awscli2/default.nix
@@ -70,7 +70,8 @@ with py.pkgs; buildPythonApplication rec {
       --replace "docutils>=0.10,<0.16" "docutils" \
       --replace "ruamel.yaml>=0.15.0,<0.16.0" "ruamel.yaml" \
       --replace "wcwidth<0.2.0" "wcwidth" \
-      --replace "distro>=1.5.0,<1.6.0" "distro"
+      --replace "distro>=1.5.0,<1.6.0" "distro" \
+      --replace "cryptography>=3.3.2,<37.0.0" "cryptography"
   '';
 
   checkPhase = ''
```

### Notify maintainers
@bhipple @davegallant @bryanasdev000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.36, NixOS, 22.05 (Quokka), 22.05.20220502.fb679d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - nixpkgs: `/nix/store/yw1synf6pp4hvc8zjlmr25ay7k8ikhf3-source`
```

**Comment by bryanasdev000** [comment]
Thanks for reporting!

Closed by https://github.com/NixOS/nixpkgs/pull/178313.

**Comment by michielboekhoff** [comment]
Brilliant, thanks @bryanasdev000!

**Comment by chasecaleb** [comment]
Looks like this same breakage is happening again, except this time due to some combination of:
- awscli2 version update from 2.10.0 -> 2.10.1: https://github.com/NixOS/nixpkgs/commit/a0e76d80c628d634e7bf346ef7fa778c2899d54e
- cryptography version update: https://github.com/NixOS/nixpkgs/commit/8e69a97f5101c64286ba23d4ce830a66ef4883ad

1. This specific build failure should be fixed
2. Bigger picture: Shouldn't an issue like this be caught _before_ getting merged into master or promoted to nixos-unstable branch? I'm confused and surprised that this keeps happening.
