### ISSUE TITLE
Should be able to use libinput as alternative to evdev

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#17841]
## Issue description

Currently libinput is only used for touchpads, but it's capable of handling all input devices.

**Comment by unlmtd** [comment]
I need this. Has anyone found a way to hack around the issue?
This isnt my field but it's high on my list; my thinkpad is a pain to use without middle-button scroll...
As it is, enabling libinput doesnt really enable it!

**Comment by unlmtd** [comment]
Looking at #19022 I found a fix for my problem from @DamienCassou 
``` nix
{
  services.xserver = {
    libinput.enable = true;
    synaptics.enable = false;

    config = ''
      Section "InputClass"
        Identifier     "Enable libinput for TrackPoint"
        MatchIsPointer "on"
        Driver         "libinput"
      EndSection
    '';
  };
}
```

I took out
```nix
        Option         "ScrollMethod" "button"
        Option         "ScrollButton" "8"
```
Because libinput takes care of that by itself very well.

**Comment by unode** [comment]
I've just hit this myself while trying to make use of the "Disable While Typing" functionality that disables the touchpad for 1 second upon key-press.

At the moment I have:
```
    xserver = {
      enable = true;
      ...
      libinput = {
          enable = true;
          clickMethod = "clickfinger";
          scrollMethod = "twofinger";
          tapping = true;
          disableWhileTyping = true;
      };
    };
```
And I can confirm that his option is enabled on the touchpad:

```
$ xinput list-props 12
Device 'ETPS/2 Elantech Touchpad':
	Device Enabled (142):	1
        ...
	libinput Disable While Typing Enabled (297):	1
        ...
```

But pressing the keyboard does not disable the touchpad.
This happens because only the touchpad is handled by **libinput**. The keyboard is handled by **evdev**.

If I run:
```
rm /etc/X11/xorg.conf.d/10-evdev.conf
ln -s /nix/store/...-xf86-input-libinput-0.25.1/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/
```
and restart X I get the expected behaviour.
However, in this case the keyboard doesn't seem to recognise all keys, likely due to interference of some other setting in `/etc/X11/xorg.conf`.

Looking at the code, *evdev* is hardcoded at https://github.com/NixOS/nixpkgs/blob/07bc859e9acec3cc6f7a8129e4b05a7584fef209/nixos/modules/services/x11/xserver.nix#L567 
There doesn't seem to be an easy way to override this.

Does anyone have any workarounds?

**Comment by jtojnar** [comment]
@unode Try https://github.com/NixOS/nixpkgs/pull/31995, the `base` XkbLayout was causing problems for me.

**Comment by BadDecisionsAlex** [comment]
Hey I have been struggling with this same issue for the last couple of days. I wanted to leave some breadcrumbs for people who might run into this down the line.

I have been trying to enable my touchpad on a dell laptop. I tried the usual options with no luck. (enabling libinput or synaptics in my config). Neither of these seemed to work. But I just made kind of breakthrough that might be helpful to people later.
The short rundown is:
With "libinput" enabled (services.xserver.libinput.enable = true;) rebuilding would create the expected "/etc/X11/40-libinput.conf"
For these changes to take effect I needed to restart X. This can be accomplished by rebooting or forcing it to restart with "systemctl restart display-manager". I had repeatedly been trying to just let it reboot, which was not working.
I discovered that when I would restart X without a reboot cycle, the trackpad would work!
The reason : after a reboot cycle "/etc/X11/40-libinput.conf" is MISSING unless I rebuild the system after booting. Following a rebuild I need to restart X with systemctl.

It seems that during the creation of the /etc directory that occurs during boot, libinput is not built (I have not yet discovered why). I am going to look into why.

In any case I hope this breadcrumb is helpful to someone down the line!
