### ISSUE TITLE
dotnet package fetching experience

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#179136]
Hey @IvarWithoutBones  , thanks for working on the dotnet stuff, this is about my first experience trying to use it.
I'm not familiar with the C# ecosystem in general so this is my first real experience with it.

This is too complicated just to get a fetch-deps script the first time you're trying to package a dotnet package:
```
(buildDotnetModule { pname = "as"; version = "0"; src = ./.; projectFile = "Mono.Cecil.csproj"; nugetDeps = builtins.toFile "test" "{...}: []";  }).passthru.fetch-deps
```
At least setting nugetDeps to empty is mentioned by the documentation but needing to use toFile is unintuitive. 
The documentation says to "set it to the empty string" (which errors, so it's "wrong"). 

It would be much friendlier if there was a more direct way to get something.
Also, I found nuget-to-nix way before I found fetch-deps, which is suboptimal.

fetch-deps should be easier to find than nuget-to-nix!
Does fetch-deps even need to be defined in passthru? The only thing it seems to use as a parameter is the package name.

Some things I tried:
```
nix-repl> (buildDotnetModule { pname = "as"; version = "0"; src = ./.; projectFile = "Mono.Cecil.csproj"; nugetDeps = null;  })              
error: Defining the `nugetDeps` attribute is required, as to lock the NuGet dependencies. This file can be generated by running the `passthru.fetch-deps` script.
```

```
nix-repl> (buildDotnetModule { pname = "as"; version = "0"; src = ./.; projectFile = "Mono.Cecil.csproj"; nugetDeps = "";  })                                                                                                                 
error: string '' doesn't represent an absolute path
```

**Comment by aopom** [comment]
Up, I can't figure out how to get this `fetchDeps` script… @deliciouslytyped, did you manage to use the script?

**Comment by aopom** [comment]
Is this the shortest way to get this script? I'd like to add this explicit step in nixpkgs' manual

**Comment by mdarocha** [comment]
Yeah, thats the shortest way to get the fetch-deps script, if the package isn't part of nixpkgs.

If you have any ideas how to update the manual to make it more clear, go for it. The dotnet related stuff is in https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/dotnet.section.md

**Comment by YoshiRulz** [comment]
How about extracting the shell script to somewhere else, maybe `nuget-to-nix.passthru`, and having `fetch-deps` just call that with the source dir as a shell argument? That way the script could be used as the first step of packaging, before even making an expression file.

---

Unrelated, running the shell script currently causes 800 MiB (half the closure!) of packages to be downloaded from NuGet, most of which seem to be native variants for every TFM.
https://github.com/NixOS/nixpkgs/blob/cd71c603a1d7a9624a83d31d7c06a76d9010da8e/pkgs/build-support/dotnet/build-dotnet-module/default.nix#L291
https://github.com/NixOS/nixpkgs/blob/cd71c603a1d7a9624a83d31d7c06a76d9010da8e/pkgs/build-support/dotnet/build-dotnet-module/default.nix#L129-L132
If this is just a blocklist for what ends up in `deps.nix` (the codegen output), can it strip the context i.e. `excluded_sources="${builtins.unsafeDiscardStringContext (lib.concatStringsSep " " sdkDeps)}"`? The same `dotnet-sdk` is already in the shell script's closure.

**Comment by eclairevoyant** [comment]
> ```shell
> $ nix-repl '<nixpkgs>'
> > :b (callPackage ./default.nix {}).passthru.fetch-deps
> ```

This doesn't work, because `nix-repl` is not a command that exists, only `nix repl` does. Beyond this, even if I correct the command:

```bash
$ nix repl
> nix-repl> :l <nixpkgs>
> nix-repl> :b (callPackage ./default.nix {}).passthru.fetch-deps
```

This still has the same issue where `nugetDeps` needs to be defined .... to generate the file to put into `nugetDeps` :facepalm:

(And no, not even the `nugetDeps = builtins.toFile "test" "{...}: []";` hack mentioned above works.)

**Comment by ppom0** [comment]
@eclairevoyant Indeed, I don't remember what did I put as a placeholder for `nugetDeps` attribute

**Comment by mdarocha** [comment]
I've made #258184, which fixes the problems you encountered with `fetch-deps` - you should be able to run `fetch-deps` when `nugetDeps` is set to `null`. I've also updated docs to hopefully make it more clear on how to generate the `deps.nix` file.

**Comment by lostmsu** [comment]
I went ahead and updated DotNET wiki with some of my findings from this and other threads.

**Comment by lostmsu** [comment]
Since I am also quite a noob with Nix derivations and system in general, I also ended up resorting with directly calling `nuget-to-nix` as @YoshiRulz suggested above. It is much more straightforward. Thanks, @YoshiRulz !

**Comment by YoshiRulz** [comment]
I've partially reverted your edits to [the wiki](https://wiki.nixos.org/wiki/DotNET) so it reflects the intended `fetch-deps` method. As noted above, it must be `nugetDeps = "";` to init, not `nugetDeps = null;`. I'll submit a PR for the manual if it hasn't been fixed already.

If you push your code somewhere I could review it for you. `buildDotnetModule` is now in a good state, comparable to Python, Rust, etc., and hacks are only needed for unorthodox setups.

**Comment by lostmsu** [comment]
@YoshiRulz this is probably not the best place to discuss it.

You probably have not noticed it, but I completely removed `fetch-deps` method from the wiki, because in comparison to `nuget-to-nix` it wasted me over 1h trying to get it working and eventually I gave up alltogether while `nuget-to-nix` worked the first time without any shenanigans with nix build system. Unless there is some clear advantage to `fetch-deps` I think it should be completely retired.

Consequentially, I think wiki should say to put `nugetDeps = ./nuget-dep.nix` and tell the reader to use `nuget-to-nix` and never even mention `nugetDeps = null` or `nugetDeps = ""` in the first place.

**Comment by YoshiRulz** [comment]
What are you talking about? It does work for expressions outside of Nixpkgs; I wrote one in order to verify how it worked before editing the article. Obviously it involved an `import` to get things like `buildDotnetModule`. The way you run the script is the same, it's just whatever attribute path you'd normally use + `.fetch-deps`, since it's in `passthru`. If your expression isn't nested then it's just `-A fetch-deps`.

The advantage is that it's all automated, even identifying and overwriting the file passed for `nugetDeps`.

You're asserting that your experience matches everyone else's and that the documentation is therefore incorrect, but no-one else has spoken up about it.

**Comment by lostmsu** [comment]
> You're asserting that your experience matches everyone else's and that the documentation is therefore incorrect, but no-one else has spoken up about it.

Look, I know you are a volunteer, and I am guessing you put work in the `fetch-deps`, but I am not claiming documentation is incorrect. I am claiming `nuget-to-nix` tool is far more superior to `fetch-deps` in practical use, and therefore the `fetch-deps` should be removed from documentation because unlike `nuget-to-nix` it is very confusing thing to use, and why would you want to send people do a confusing thing vs a straightforward thing?

> The advantage is that it's all automated, even identifying and overwriting the file passed for nugetDeps.

I am not quite sure what is more automated vs running `nuget-to-nix`. The latter only needs a temporary directory and creating and removing it is right there in the suggestion.

> but no-one else has spoken up about it.

Half of this thread is about this. See:

> Up, I can't figure out how to get this fetchDeps script…

> Yeah, thats the shortest way to get the fetch-deps script, **if the package isn't part of nixpkgs.**

> This still has the same issue where nugetDeps needs to be defined .... to generate the file to put into nugetDeps 🤦

There's even a facepalm from another frustrated user.

> From what I can tell, just building passthru.fetch-deps doesn't actually generate the file. You must run the script output by that build. Unfortunately, when using this with a flake you can't just run ...
> I only tried nuget-to-nix because the passthru wasn’t working and the script was mentioned in the manual

This is another history of struggle. It even tells that they had the struggle because they tried to use `fetch-deps` because it was what "the manual" (which probably is either the docs thingie or the wiki) told them to do. Same in my case.

On the contrary since you added `nuget-to-nix` comment nobody complained about it. In fact it worked for me with no setup or any prior knowledge of any kind, and seemed to have worked for adamcstephens too.

**Comment by YoshiRulz** [comment]
> ```
> $ nix-build -A fetch-deps
> error: getting status of '/home/lost/Queen.NixOS/cloud/default.nix': No such file or directory
> ```
> 
> Well guess what? Nowhere do wiki or docs say you have to put your `buildDotnetModule` in a `default.nix`. Guess what number 2? In `nixpkgs` repository majority of the primary package files are instead called `package.nix`. So if you are following their convention (which I did), the current suggestion in the wiki is basically broken.

The .NET section of the manual makes the (IMO fair) assumption that you're familiar with these more fundamental concepts: Nixpkgs' by-name is its own convention which doesn't affect development outside of Nixpkgs. If you wanted to keep the filename then you'd need to pass `-f package.nix`.

Perhaps the docs for packaging .NET apps could be made clearer for those not already well-versed in Nix, but I don't think going back to manual `nuget-to-nix` invocation would be an improvement on the whole.

**Comment by eclairevoyant** [comment]
> The point is that you don't need to _carefully_ set up `nuget-to-nix`. It works well straight away.

In any case my frustration at the time was due to the mismatch between documentation and code behaviour, _not_ the fact that you have to be careful in the steps. (Pretty much everything in nixpkgs requires careful attention to the steps :upside_down_face:) . I tried `nuget-to-nix` at the time (with my best effort, having zero knowledge) and ended up with the same error; though obviously it was user error, it's certainly not a foolproof script that "just works".

Also, I should note, `fetch-deps` uses `dotnet restore` + `nuget-to-nix` anyway:
https://github.com/NixOS/nixpkgs/blob/b5447275d2d3314e85880357f9ea4828c7070610/pkgs/build-support/dotnet/build-dotnet-module/default.nix#L303-L326

So as was said, `fetch-deps` is a more automated way to achieve the same end result.

**Comment by lostmsu** [comment]
> Perhaps the docs for packaging .NET apps could be made clearer for those not already well-versed in Nix, but I don't think going back to manual nuget-to-nix invocation would be an improvement on the whole.

I keep hearing that, but you are not really giving any arguments. In fact in your own comment you provide an argument in favor of `nuget-to-nix`: ".NET section of the manual makes the (IMO fair) assumption that you're familiar with these more fundamental concepts". This dependency is completely unnecessary.

**Comment by eclairevoyant** [comment]
We need to know nix to work with it effectively; the nixpkgs manual will not provide a primer on how to use the basics of nix. And the docs issue is being looked at in #322184. So let's take a breather instead of arguing which method you prefer, both methods are doing the same thing.

**Comment by lostmsu** [comment]
Here's an argument by analogy if a straight up simplification argument does not convince you.

Prior to .NET Core the .csproj files looked like this: https://gist.github.com/lostmsu/e0375a3bc9a6ff70bfc4269c254b7b65 (I'm not even gonna paste it here, cause it is so obnoxious).

Now it looks like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

</Project>
```

The crucial difference between the two is that most people developing C# code do not and should not care about intricacies of MSBuild unless they really need it. Simple projects should be straightforward.

> We need to know nix to work with it effectively

I was writing above before I saw your comment, and it still stands. No. You don't need to know nix. Like you might not know ARM64 assembly to write Swift for iOS. There are abstraction layers and build tooling for .NET projects on Nix is one of them.

**Comment by lostmsu** [comment]
> So let's take a breather instead of arguing which method you prefer

Hey, I am arguing for the sake of future of NixOS here. The more people will feel comfortable using it, the better tools it will get. It is a perpetual loop. If you want that, you should help new people onboard, and based on my experience as a .NET dev and as a human, not everyone new to NixOS would sit for 2h+ trying to figure out how to build a trivial .NET package. Many would just turn away after a few tries.

**Comment by lostmsu** [comment]
@YoshiRulz I think the change to `use e.g. nix-prefetch-git` is also bad, because it introduces yet another dependency, and does not link an instruction to get it. What was wrong with trying to build and getting the hash from the log?

**Comment by YoshiRulz** [comment]
> I think the change to `use e.g. nix-prefetch-git` is also bad, because it introduces yet another dependency, and does not link an instruction to get it. What was wrong with trying to build and getting the hash from the log?

The Nixpkgs manual has a brief section explaining that you're slightly more susceptible to MITM attacks if you fetch twice, and until recently it recommended using a prefetch tool, but in [the current version](https://nixos.org/manual/nixpkgs/stable/#chap-pkgs-fetchers-caveats) it looks like passing `""` is now the recommended method. Which is probably what most people were already doing.

---

re: improving the experience for new Nix users, I like the direction https://github.com/nix-community/nix-init and https://github.com/nix-community/dream2nix are going in.

**Comment by lostmsu** [comment]
I am all for simplifying (im)porting things. But we should not let perfect be the enemy of better.

BTW, I figured out running ASP.NET project as systemd service and updated wiki.
