### ISSUE TITLE
glibc can't be built on darwin

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#18048]
## Issue description

The package `glibc` don't builds on darwin.

(I want to use `iconv` in nix-shell.)
### Steps to reproduce

```
nix-shell -p glibc --show-trace -f ~/code/nixpkgs/
error: syntax error, unexpected ')', at (string):1:102
nix-env -iA glibc -f ~/code/nixpkgs/
error: assertion failed at /Users/davidak/code/nixpkgs/pkgs/development/libraries/glibc/default.nix:8:1
```
## Technical details
- System: OS X 10.10.5
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: git master

**Comment by vcunat** [comment]
That's `assert stdenv.cc.isGNU;`. Why do you think `glibc` should work on Darwin?

**Comment by vcunat** [comment]
@davidak: you should use `-A libiconv`. That one is redirected to glibc on GNU platforms and e.g. to `darwin.libiconv` in your case.

**Comment by davidak** [comment]
@vcunat thanks, that work!

I used `command-not-found` to find the package that has the `iconv` binary:

```
command-not-found iconv
The program ‘iconv’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.glibc
  nix-env -iA nixos.glibc_multi
```

**Comment by vcunat** [comment]
The database for it is generated on Linux...

**Comment by Ericson2314** [comment]
I'm going to steal this issue. Cross compiling `glibc` on Darwin is one of the few remaining hurdles for linux->darwin cross compilation. @periklis.

**Comment by Ericson2314** [comment]
1. I found a bug where `AR=`$CC -print-program-name=ar` doesn't work correctly as `*-ar` isn't in a `-B` directory or forced at compile-time with `--with-ar`. The latter doesn't exist, and the former isn't expected, so I'd say this is glibc's fault, though GCC could certainly do better too. This normally isn't an issue because the wrong `ar` on Linux is good enough.

2. I think I am running into issues due to case-insensative file systems. They use both `oS` and `os` object prefixes. Lovely.

**Comment by veprbl** [comment]
Native compilation of glibc is not supported:
```
configure: error: 
*** The GNU C library is currently unavailable for this platform.
*** If you are interested in seeing glibc on this platform visit
*** the "How to submit a new port" in the wiki:
***   https://sourceware.org/glibc/wiki/#Development
*** and join the community!
```
