### ISSUE TITLE
Plasma: Wayland applications don't follow GTK theme

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#180720]
### Describe the bug
KDE Plasma allows setting GTK themes in System Settings > Application Style > Configure GNOME/GTK Application Style.
While the configuration works on X11/XWayland, on pure Wayland the GTK applications won't be themed at all (at most they'll only follow the dark theme). Even the window decoration will only be the close button (without having the maximize and minimize buttons like you'd expect).

### Steps To Reproduce
1. `services.xserver.desktopManager.plasma5.enable = true;`;
2. Start Plasma Wayland (on TTY it can be done with `dbus-run-session startplasma-wayland`);
3. Make sure to set the GTK theme in the settings;
4. Open a GTK app that runs on pure Wayland (you can check with `xeyes`: the eyes won't follow the cursor if a Wayland app is focused);
5. The app won't be themed.

### Expected behavior
The app should be themed.

### Screenshots
The app on the left is clearly not themed.
![image](https://user-images.githubusercontent.com/40663462/178008862-0eea9ade-dd8b-4030-85af-e87ef24911fd.png)

### Additional context
Can reproduce with a basic `configuration.nix` and a new user. 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.9-zen1, NixOS, 22.11 (Raccoon), 22.11pre390234.2770cc0b1e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eddyb** [comment]
I'm not even sure where to post this anymore, found too many separate bug reports while trying to fix this for myself, but roughly this was the chain of events:
* was only happening on Wayland for me
* `GTK_THEME=Breeze` (or `Breeze-Dark`) seems to work to fix it on every app I tried
* [a comment on a different-but-related issue](https://github.com/NixOS/nixpkgs/issues/155291#issuecomment-1014772774) made me look at `dconf-editor /org/gnome/desktop/interface`, and shockingly, *only some of the `~/gtk-{3,4}/settings.ini` entries* (that Systems Settings set) were there - notably absent: `gtk-theme`
* going into Systems Settings -> Appearance -> Application Style -> GNOME/GTK, then selecting *the same entry* from the dropdown, and clicking Apply (which I didn't expect to become available, since I didn't change entries), fixed it *instantly*

My best guess so far is that something deleted some of the entries (or migrated the `.ini`s but only partially?), but I have no idea what or when. I suppose I could check another machine that shares a common history with this one, and try to dig into the exact `dconf` state there, it could be years-old at this point.

Now I doubt this applies to this particular report, at least using a new user for this, but if you don't have `programs.dconf.enable = true;` in your `configuration.nix` can you try adding it, then re-setting Breeze for GTK in System Settings? If *that* works, maybe `plasma5` needs to require `dconf` by default?

**Comment by SuperSamus** [comment]
Enabling dconf and setting the Apllication Style in System Settings worked!
(Didn't need to use the terminal command.)

**Comment by eddyb** [comment]
In that case, someone should make an issue regarding Plasma and `dconf`, maybe it has to be default-enabled? - however, I'm worried I'm missing a lot of context here, e.g. I don't really understand this other issue:
* #11239

**Comment by rokejulianlockhart** [comment]
> Enabling dconf and setting the Apllication Style in System Settings worked! (Didn't need to use the terminal command.)

@SuperSamus, how did you enable it? (I'm experiencing this problem via the Fedora KDE Spin.)

**Comment by SuperSamus** [comment]
```nix
programs.dconf.enable = true;
```

in `configuration.nix`, but this only applies to NixOS (and not Fedora).

**Comment by SuperSamus** [comment]
Should be fixed in Plasma 5.27.4.

**Comment by rokejulianlockhart** [comment]
@SuperSamus, is there a relevant bugs.kde.org issue or invent.kde.org pull request? I'd just like to know where ya got that from.

**Comment by SuperSamus** [comment]
Ask @K900, I got it from this.
https://github.com/NixOS/nixpkgs/pull/196017#issuecomment-1498469779
