### ISSUE TITLE
NixOS 22.05 (rev 71d7a4c037) VirtualBox 6.1.34 fails to bulid

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixpkgs#180877]
### Steps To Reproduce

Rebuild NixOS 22.05 (71d7a4c037) with the below configuration:

`nixpkgs` flake lock

``` json
    "nixpkgs": {
      "locked": {
        "lastModified": 1657296039,
        "narHash": "sha256-Ghh39+aS+pw5sTP/ZO8VIKE6sBhMadDaQZtf+3yu4Vc=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "71d7a4c037dc4f3e98d5c4a81b941933cf5bf675",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-22.05",
        "repo": "nixpkgs",
        "type": "github"
      }

```

relevant NixOS configuration

``` nix
{ ... } : 
{  
    boot.kernelPackages = pkgs.linuxPackages_hardened; # currently 5.15.47
    virtualisation.virtualbox.host.enable = true;
}
```

### Build log

https://gist.github.com/stefano-m/353ab3e930673492221952c37a94153c

The relevant bit is

```
The failing command:
$(QUIET)$(REDIRECT) -wo $@ -- $(SED) -f $< $(filter %.h,$^)
kmk: *** Deleting file '/build/VirtualBox-6.1.34/out/linux.amd64/release/obj/Runtime/errmsgdata.h'
kBuild: Generating /build/VirtualBox-6.1.34/out/linux.amd64/release/obj/Runtime/errmsgdata.h
kmk: *** [/build/VirtualBox-6.1.34/src/VBox/Runtime/Makefile.kmk:3685: /build/VirtualBox-6.1.34/out/linux.amd64/release/obj/Runtime/errmsgdata.h] Segmentation fault

```

### Additional context
N/A

### Notify maintainers

@svanderburg 
@Yarny0 (re #177413 and related)

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47-hardened1, NixOS, 22.05 (Quokka), 22.05.20220617.d17a56d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/store/4syzn98z4wb6mmvvfz6281s6z9p1nr3c-source`

**Comment by Yarny0** [comment]
Some observations:

* The VirtualBox derivation builds fine on my machines (which is using a not-hardened kernel), also on hydra:

  https://hydra.nixos.org/build/183239913#tabs-summary

* The build fails if running the hardened kernel while building; tested by me with `5.15.51-hardened1`.

  If this kernel is running, the older VirtualBox 6.1.30 fails to build as well.

  Actually, the problem also occurs if older versions of the hardened kernel and of the VirtualBox sources are used: I booted the hardened kernel (`5.15.41-hardened1`) of the only beta release of NixOS 22.05

  https://releases.nixos.org/nixos/22.05/nixos-22.05beta67.6efc186e607

  and tried to build VirtualBox (6.1.30, also from that beta release) locally: It failed with the same error.

  So it looks like the recent updates of VirtualBox (https://github.com/NixOS/nixpkgs/pull/177413 , https://github.com/NixOS/nixpkgs/pull/180564) are not related to the issue reported here.

* The segmentation fault seen in the log file happens while calling

  `$(QUIET)$(REDIRECT) -wo $@ -- $(SED) -f $< $(filter %.h,$^)`

  which translates to

  `kmk_builtin_redirect -wo /build/VirtualBox-6.1.34/out/linux.amd64/release/obj/Runtime/errmsgdata.h -- /build/VirtualBox-6.1.34/kBuild/bin/linux.amd64/kmk_sed -f /build/VirtualBox-6.1.34/src/VBox/Runtime/common/err/errmsg.sed /build/VirtualBox-6.1.34/include/iprt/err.h /build/VirtualBox-6.1.34/include/VBox/err.h` .

  Apparently, something in VirtualBox'es build system doesn't play well with the hardened kernel.

* Modifying the `buildPhase` so that it invokes the offending `kmk_sed` command

  `/build/VirtualBox-6.1.34/kBuild/bin/linux.amd64/kmk_sed -f /build/VirtualBox-6.1.34/src/VBox/Runtime/common/err/errmsg.sed /build/VirtualBox-6.1.34/include/iprt/err.h /build/VirtualBox-6.1.34/include/VBox/err.h`

  directly (without `kmk` and `kmk_builtin_redirect` around it) does not trigger the segmentation fault.

  So the cause of the issue might be a combination of the hardened kernel and of `kmk_builtins_redirect` and `kmk_sed` from VirtualBox'es build system.

@stefano-m , did compiling virtualbox with a hardened kernel ever work in NixOS 22.05?  I failed to accomplish this even with the very first release.

Since compiling works fine with the "normal" (not hardened) kernel, I guess the problem is caused by one of the modifications that set the hardened kernel apart from the "normal" kernels.  To find the exact cause, one would probably have to disable these modifications one by one and see which one makes the problem go away.

**Comment by stefano-m** [comment]
@Yarny0 thank you very much for your analysis and quick reply.

Until the last flake update, I could use VirtualBox with a hardened kernel without any problems. I can't remember whether VirtualBox was compiled on my machine of came already build form the NixOS cache though.

Before this update I was using NixOS on d17a56d90ecbd1b8fc908d49598fb854ef188461 that had:

- VirtualBox 6.1.30
- Hardened Kernel 5.16.47

Now, I have tried again to install VirtualBox, and apparently hydra has built the package and I can download it from the cache.

Apparently I can *run* VirtualBox on my hardened kernel but I *cannot* build it.

Not sure whether it's possible to add a warning/failure when someone tries to *build* the derivation on a hardened kernel, but just be silent if a substitution from the cache is found?

Anyway, I think we can close this issue.
