### ISSUE TITLE
Update bottles to 2022.7.14-brescia-1

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#181501]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: bottles

current version: 2022.5.28-trento-3
desired version: 2022.7.14-brescia-1

###### Notify maintainers

maintainers: @psydvl @SCOTT-HAMILTON 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by psydvl** [comment]
While automatic update using `passthru.UpdateScript` was removed by @SuperSandro2000 in https://github.com/NixOS/nixpkgs/pull/169136 you need to wait while we will "get auto updates from r-rynatm"

**Comment by SuperSandro2000** [comment]
> While automatic update using `passthru.UpdateScript` was removed

That not true. I removed the over complicated updater in https://github.com/NixOS/nixpkgs/commit/d002c9f58f2e63cb2548ee6649d9deb310788818 which wasn't necessary at all. Since r-ryantm also uses nix-update there was also no need to replace it.

> you need to wait while we will "get auto updates from r-rynatm"

That's wrong. You can always create an update PR yourself by running ``nix-update bottles`` or by manually update the package and create a PR with that.

r-ryantm goes through all packages so it can sometimes take a few days until the update PR is created. 

Also nix-update is very lightweight with minimal dependencies, so there is not really a reason to not use it. It also does not require any kind of token or authentication.

**Comment by QuantMint** [comment]
> > While automatic update using `passthru.UpdateScript` was removed
> 
> That not true. I removed the over complicated updater in [d002c9f](https://github.com/NixOS/nixpkgs/commit/d002c9f58f2e63cb2548ee6649d9deb310788818) which wasn't necessary at all. Since r-ryantm also uses nix-update there was also no need to replace it.
> 
> > you need to wait while we will "get auto updates from r-rynatm"
> 
> That's wrong. You can always create an update PR yourself by running `nix-update bottles` or by manually update the package and create a PR with that.
> 
> r-ryantm goes through all packages so it can sometimes take a few days until the update PR is created.
> 
> Also nix-update is very lightweight with minimal dependencies, so there is not really a reason to not use it. It also does not require any kind of token or authentication.

Bottles [2022.6.14-brescia](https://github.com/bottlesdevs/Bottles/releases/tag/2022.6.14-brescia) the version released after the one currently present in nixpkgs, was released on June 13. Over one month has passed, so something about the auto-updater isn't working.

**Comment by SuperSandro2000** [comment]
The latest r-ryantm log is here https://r.ryantm.com/log/bottles/2022-07-07.log . Not sure why that is not working like it should.

**Comment by bobby285271** [comment]
I guess a update script is needed for this case :disappointed: 

##### For [r.ryantm.com/log/bottles/2022-07-05.log](https://r.ryantm.com/log/bottles/2022-07-05.log) and [r.ryantm.com/log/github/bottles/2022-07-11.log](https://r.ryantm.com/log/github/bottles/2022-07-11.log)

Since the package is using `buildPythonApplication`, it has a fallback update script [`update-python-libraries`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/update-python-libraries/update-python-libraries.py), so nixpkgs-update is no longer trying to figure out the latest version itself but just run the script.

However seems like [packaging](https://github.com/pypa/packaging) cannot handle the version `2022.5.28-trento-3`, so it will fail at

https://github.com/NixOS/nixpkgs/blob/8d78af079998a0dcb47b277da307ec963636cf26/pkgs/development/interpreters/python/update-python-libraries/update-python-libraries.py#L137

You may just try

```py
#!/usr/bin/env nix-shell
#!nix-shell -i python3 -p python3Packages.packaging
from packaging.version import Version
version = Version("2022.5.28-trento-3")
```

##### For [r.ryantm.com/log/bottles/2022-07-07.log](https://r.ryantm.com/log/bottles/2022-07-07.log)

```
2022-07-07T08:51:48 bottles 2022.5.28-trento-3 -> 2022.6.14 https://repology.org/metapackage/bottles/versions
```

Repology gets software latest version from various Linux distributions that ships this app, so since AUR and OpenMandriva have 2022.6.14 (no suffix) the latest version is 2022.6.14. So I guess since you cannot get the suffix from Repology nixpkgs-update fails to bump it.

Looks like there is also an related report in https://repology.org/project/bottles/report.
