### ISSUE TITLE
abseil-cpp LTS is out of date

### ISSUE THREAD

**Issue by smancill** [NixOS/nixpkgs#181672]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: abseil-cpp

current version: 20210324.2, 20211102.0
desired version: [20220623.0](https://github.com/abseil/abseil-cpp/releases/tag/20220623.0)

I was going to create a PR to update Abseil, but then I found that there are two versions of the package, so I don't know what I am supposed to do.

The version 20211102.0 was added by @jonringer in a0da54e4d11c289b0c8b5fae54bd77be0cb5af10.

Also, it looks that an update to abseil-cpp needs to target staging?

###### Notify maintainers

maintainers:

@andersk 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by andersk** [comment]
Abseil’s “live at HEAD” approach has meant that Abseil upgrades have generally broken many builds in the past, which is why there are multiple versions. You’re welcome to add a third version (this itself shouldn’t need to target `staging`), and to move packages over to using it *if* you verify that they still build (this may or may not need to target `staging` depending on the blast radius).

**Comment by pbsds** [comment]
Closing this, since the desired version is packaged

![image](https://github.com/NixOS/nixpkgs/assets/140964/c8135f0e-b276-4ef3-9961-45f88860897a)
