### ISSUE TITLE
Migrate to Python 3 as default install

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#18185]
- [x] [Remove bloated Python modules such as tcl/tk (see Python 2 how it's done)](https://github.com/NixOS/nixpkgs/pull/19309)
- [ ] identify python2 dependencies in common environments (server,kde,gnome,e17)
- [x] [Migrate `nixos/modules/system/boot/loader/systemd-boot` (or alternatively, seems simple enough to rewrite in some other language)](https://github.com/NixOS/nixpkgs/issues/19102)

**Comment by abbradar** [comment]
I wanted to create this issue long ago and help with what I can, but hasn't found time ~_^

**Comment by FRidh** [comment]
We should have for each interpreter version a
- `python` which is the *full* version
- `python-stripped` which is commonly used in other packages
and package sets for each.

**Comment by aneeshusa** [comment]
I have used my nixpkgs config to set Python 3 as the default, and have only encountered a few packages requiring Python 2 so far. I can help put in PRs to make sure they use `python2` (or `python2.tiny` / `python2.small` / `python2-stripped` ) instead of `python3`.

Maybe the python infra should automatically use the smaller version when `python`/`python2` is a build input?

**Comment by edolstra** [comment]
Regarding `systemd-boot`, I started rewriting it in Perl a while back, but it's not entirely finished yet. I can pick that up.

Other than that, what exactly does it mean to have Python 3 as the "default install" given that NixOS doesn't install Python by default (AFAIK)?

**Comment by FRidh** [comment]
`pkgs.python = pkgs.python3` instead of `pkgs.python = pkgs.python2`, and likely `pkgs.python3 = pkgs.python35` although we could try 3.6 as well; there aren't going to be many changes. This change will impact a lot of packages/services.

**Comment by domenkozar** [comment]
@edolstra it means that for graphical stacks we have only python3 in the closure. So Python 3 should be the default interpreter used in applications.

**Comment by domenkozar** [comment]
`nixos/modules/system/boot/loader/systemd-boot` can be easily ported to python3, unless you want to maintain it in perl @edolstra

**Comment by FRidh** [comment]
is there a test for systemd-boot?

**Comment by vcunat** [comment]
Many packages use python in their build system. I don't know how well `python3` is supported for that, generally.

**Comment by dezgeg** [comment]
> is there a test for systemd-boot?

There is `tests.boot.simpleUefiGummiboot`. It's not a release blocker currently though.

**Comment by FRidh** [comment]
`patchShebangs` doesn't patch a `#!/usr/bin/python` to a Python 3.x path. We could add a symbolic link from `python` to `python3` in the Python 3.x derivations. Any idea what other distributions do?

**Comment by aneeshusa** [comment]
I think it would be best to leave patchShebangs as is, and add a symlink for `python` in the `python3` derivation (and remove it from the `python2` derivation to allow simultaneous installations). This adds less complexity, matches how most distributions handle `/usr/bin/python`, and is something I've been using for a few months without any issues.

**Comment by Mic92** [comment]
see @domenkozar #19102 regarding systemd-boot

**Comment by domenkozar** [comment]
Thanks! So to identify leftover todos we have to take following closures and check what depends on Python2 and upgrade libs to Python3 (or identify them if they don't):

http://hydra.nixos.org/eval/1297209?filter=closure&compare=1297083&full=

**Comment by domenkozar** [comment]
For example in ec2:

```
nix-store -r /nix/store/sl9g3vbahp48wi1d85gb4dkchykg5m6w-nixos-system-unnamed-17.03pre93673.09e4b78

$ nix-store -q --graph /nix/store/sl9g3vbahp48wi1d85gb4dkchykg5m6w-nixos-system-unnamed-17.03pre93673.09e4b78|grep python
```

So EC2 closure doesn't use Python.

**Comment by domenkozar** [comment]
@FRidh could we change `python = python3;` and same for `pythonPackages` and push that to `python-wip` branch to see the result? Do you think something else is missing before we try that?

**Comment by FRidh** [comment]
We could create a `python3` branch where we set `python = `python3` and fix whatever we need to fix. 

One possible issue I could see is that, because `${python3/bin/python}` does not exist, there will be a lot of shebangs that will not be patched. As @aneeshusa and I wrote we could create the symlink in the Python 3 expressions. Even so, I think it would be a good idea to let patchShebangs raise an exception when it is not able to patch a shebang.

**Comment by FRidh** [comment]
@domenkozar we will have to add the `x11Support` flag to the other interpreters as well because Python tkinter indirectly depends on Python.

**Comment by FRidh** [comment]
Considering I doubt agreement will be found in time on how to do the migration I've shifted this to 18.09.

**Comment by rnhmjoj** [comment]
I'm moving here my comment
> If I understand correctly people are against it because PEP 394 recommends to symlink python to python2 with the rationale being to preserve compatibility with existing python2 script.
But don't we patch shebang to point to a very specific python interpreter already? Also this document is from 2011: python2 EOL now is only 1.5 years away. What do people expect it will happen after this date?

**Comment by FRidh** [comment]
> If I understand correctly people are against it because PEP 394 recommends to symlink python to python2 with the rationale being to preserve compatibility with existing python2 script.
But don't we patch shebang to point to a very specific python interpreter already? Also this document is from 2011: python2 EOL now is only 1.5 years away. What do people expect it will happen after this date?

PEP 394 says that *for the time being* the `python` executable should point to the `python2` executable. However, because on Arch `python` points to `python3`, it is also advised that scripts that use `python` in their shebang are made Python 2 *and* 3 compatible.

In the case of Nix we're not so much talking about the executables (the `python` executable in Nixpkgs points to both `python2` and `python3`, with `python2` taking precedence), but more about the *attribute* `python`, and having that point to the `python3` attribute instead of the current `python2` attribute.

I would argue we should do the same as with the shebang but with out attributes: use the `python` attribute for packages that are both 2 and 3 compatible. Then it becomes easy to change at some point. Many did not like this, because it could break their expressions *outside* of Nixpkgs. Fair point.

Last month there was again a discussion on `python-dev` about PEP 394 and whether `python` should always point to `python2`, leading to revision of PEP 394 (https://github.com/python/peps/pull/630). Judging from the discussion I think it is clear now that `python` should *not* and *will* not point to `python3`. 

Based on that, and the earlier resistance, I am fine with not pointing the `python` attribute to `python3`, but instead update *all* occurrences where `python3` can be used. But good luck finding volunteers for doing that.

**Comment by dotlambda** [comment]
Besides using `python3` where possible, do we also want to explicitly use `python2` instead of `python` as I did in #44400?

**Comment by dotlambda** [comment]
I think that, in the long run, we might wantto remove the `python` and `pythonPackages` attributes from `all-packages.nix`.

**Comment by grahamc** [comment]
https://www.python.org/dev/peps/pep-0394/

> for the time being, all distributions should ensure that python, if installed, refers to the same target as python2, unless the user deliberately overrides this or a virtual environment is active.

**Comment by ryneeverett** [comment]
pep394 [has been changed](https://github.com/python/peps/pull/989) since this discussion dropped off. I'm surprised this isn't a 20.03 milestone.

**Comment by FRidh** [comment]
That PEP is about the executable and it has been like this for years in Nixpkgs (Python refers to 2 and 3 but if both present 3 takes precedence). It's also a relatively unimportant issue for us.

Anyway, there are not many Python 2 applications left and we as a project do not have project milestones, but our members may have.

**Comment by doronbehar** [comment]
That's still important.

**Comment by FRidh** [comment]
Default image uses Python 3 as does nearly every application. There are a couple build-time dependencies for the default image that use Python 2, that are a bit harder to get around. Aside from that there's nothing to be done, so I am closing this.

**Comment by doronbehar** [comment]
@FRidh what about renaming the attributes? Making `python = python3`?

**Comment by rnhmjoj** [comment]
I thinkg it would be a good idea to write down all remaining python2 packages. For instance, I would start removing old `2.x.nix` expressions for packages that have python3 support.
