### ISSUE TITLE
k3s: support HA cluster

### ISSUE THREAD

**Issue by yajo** [NixOS/nixpkgs#182085]
### Describe the bug
While trying to set up a NixOS HA k3s cluster, I found this: https://github.com/NixOS/nixpkgs/blob/c8585bf4a88d6ec2b659cf5fd02a10cac2d31c82/nixos/modules/services/cluster/k3s/default.nix#L34-L55

Notice how it says that those options only make sense for an agent? [It's not true](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/). Otherwise, how are we supposed to build a HA cluster? (With 3 or more servers)

### Expected behavior
There should be a documented path towards building an HA cluster.

### Additional context
Embedded etcd is these days the default storage endpoint for k3s. This means that HA clusters are supported out of the box.

For NixOS, all I had to do is deploy this module on all servers:

```nix
firstServer: firstServerEndpoint: host: {
  services.k3s.enable = true;
  environment.systemPackages = [pkgs.k3s];
  services.k3s.extraFlags = "--secrets-encryption ${
    if host == firstServer
    then "--cluster-init"
    else ""
  }";
  networking.firewall.allowedTCPPorts = [6443];

  # These work fine for servers, no matter what option docs say
  services.k3s.token = "mySecretToken";
  services.k3s.serverAddr =
    if host == firstServer
    then ""
    else firstServerEndpoint;

  # This is important for server nodes to reach each other
  networking.firewall.allowedTCPPortRanges = [
    {
      from = 2379;
      to = 2380;
    }
  ];
}
```

Another key point is [the etcd port range that has to be open for multiple servers to join together](https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/#networking). [The wiki](https://nixos.wiki/wiki/K3s) doesn't mention that.

Finally, if you're deploying in parallel (NixOps or similar), not-first nodes (agents or servers) can have a race condition waiting for the 1st server to be available. It'd be nice to be able to configure those services to wait automatically for some kind of socket availability (maybe defined as a systemd unit?).

### Notify maintainers

@euank @mic92 @superherointj

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.54, NixOS, 22.05 (Quokka), 22.05.20220710.cf034a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

@moduon MT-904

**Comment by superherointj** [comment]
> how are we supposed to build a HA cluster? (With 3 or more servers)

I (and likely others) haven't tested HA with K3s. (Mostly because I don't need the feature myself.) As you just pointed out, a solution seem straight forward, feel free to propose a PR fixing the shortcomings you found. Also make sure to add a test to validate the HA feature. Or we might not notice when it breaks (as we aren't using it).

**Comment by yajo** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/185231

**Comment by euank** [comment]
Confusingly enough, there's two ways to build HA clusters with k3s.

There's the method this issue talks about, where you launch one server with `--cluster-init`, and then a second one is joined, and then there's the more "normal" k8s way of having two servers share the datastore and leader elect that way.

The k3s docs call this out as [HA with embedded DB](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/), and [HA with external DB](https://rancher.com/docs/k3s/latest/en/installation/ha/).

I've used the HA with external DB method to rotate masters on my cluster, and that's worked fine, but that's just because I'm using an existing etcd not managed by k3s... so I think that bit works without us having to do anything.

Streamlining the embedded HA setup sounds great, thanks a ton for filing this issue and making a PR!

**Comment by yajo** [comment]
Yes, also the external DB can be etcd (like normal k8s) or postgresql/mariadb (which is kinda exclusive to k3s).

But I think at least with https://github.com/NixOS/nixpkgs/pull/185231 we can make it easier to use the builtin k3s methods. Other more advanced setups can always be achieved with custom flags.
