### ISSUE TITLE
Finding JetBrains IntelliJ IDEA easier

### ISSUE THREAD

**Issue by WilliButz** [NixOS/nixpkgs#18241]
## Issue description

@edwtjo 
The JetBrains IntelliJ IDEA  can't be found using the search string "IntelliJ" on the main website. It would be nice for other users, who might just know it under this name, to find it easier.

kind regards
Willi
### Suggestion

Maybe adding a small piece of additional information to the short description would help:
current: "Integrated Development Environment (IDE) by Jetbrains, community edition"
-> "Integrated Development Environment (IDE) by Jetbrains, IntelliJ IDEA community edition"
- System: NixOS version 16.09
- Nix version: 1.11.3
- Nixpkgs version: 16.09
- Kernel version: 4.6.7

**Comment by edwtjo** [comment]
*IntelliJ is to IDEA what Chromium is to Chrome.* I've previously made an attempt to package intellij, see #8130, but finally dropped it since was to much effort with too little value added. The motivation is:

  1. Then there wasn't any real changes between the final built intellij dist and IDEA from Jetbrains.
  2. Dependencies of java programs usually rely on third party repos and pre compiled jars anyway, some are missing signatures.
  3. There are circular dependencies in intellij which are messy.

That being said I would still like to do this since I think it is still preferable to have stuff reproducible from source. In such case then yes there would be an intellij attribute in nixpkgs. I think it is preferable with a separation of the two, even if it is a little frustrating at first and that the name should be avoided/reserved in the eventuality that we do see a native from source build of intellij.

But I'm open to change if people think I'm wrong. Please downvote this comment if you think we should add "Intellij" to the description field. This issue should then be easy to resolve by then end of Sept.
