### ISSUE TITLE
wget and curl do not have letsencrypt ca accessible.

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#18411]
## Issue description
wget, curl, and possibly other commands don't have cert setup correctly.  i can navigate to my site home.rldn.net without problem in firefox and in chromium.

### Steps to reproduce
$ wget home.rldn.net
--2016-09-07 18:35:21--  http://home.rldn.net/
Resolving home.rldn.net (home.rldn.net)... 192.168.1.128
Connecting to home.rldn.net (home.rldn.net)|192.168.1.128|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://home.rldn.net/ [following]
--2016-09-07 18:35:21--  https://home.rldn.net/
Connecting to home.rldn.net (home.rldn.net)|192.168.1.128|:443... connected.
ERROR: cannot verify home.rldn.net's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to home.rldn.net insecurely, use `--no-check-certificate'.

## Technical details
16.09beta133.ebe7f35 (Flounder)
nix-env (Nix) 1.11.4
"16.09beta133.ebe7f35"
Linux toadman 4.7.2 #1-NixOS SMP Sat Aug 20 16:11:18 UTC 2016 x86_64 GNU/Linux

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by vcunat** [comment]
The default nixos certificates, located on `/etc/ssl/certs/ca-certificates.crt`, are extracted from the default `nss`. I thought that's the same list that Mozilla upstream uses by default, but apparently not.

**Comment by vcunat** [comment]
Actually, there's something stranger going on. The file does seem to include the correct root certificate.

**Comment by vcunat** [comment]
It seems to me some clients (firefox) are more thorough when searching for a validable certificate chain.

**Comment by fpletz** [comment]
The "Let's Encrypt Authority X3" is actually not in Mozilla's trust store (yet?) but the "ISRG Root X1" is. This is the parent organization running Let's Encrypt (Internet Security Research Group). That's why you have to provide the full chain to the ISRG root. Before that, Let's Encrypt was cross-signed by the "DST Root CA X3" (IdenTrust) which is an established Root CA.

I'm not sure, though, why this works in browsers. I can access the example site without problems in Chromium even though I don't have "Let's Encrypt Authority X3" in my trust store.

However, the behaviour of wget and curl (and openssl s_client for that matter) is the expected one and doesn't work on other distributions (Debian stretch/sid tested) either.

You have to provide an intermediate certificate, either for the DST or the ISRG root, see https://letsencrypt.org/certificates/:

> When configuring a web server, the server operator configures not only the end-entity certificate, but also a list of intermediates to help browsers verify that the end-entity certificate has a trust chain leading to a trusted root certificate. Almost all server operators will choose to serve a chain including the intermediate certificate with Subject “Let’s Encrypt Authority X3” and Issuer “DST Root CA X3.” The official Let’s Encrypt software will make this configuration seamlessly.

That's why I'm closing this issue. Feel free to reopen if you don't agree and have anything to add. Thanks.

**Comment by vcunat** [comment]
Yes, I also ended up with the quote you made. I suppose Firefox does some magic to find the intermediate certificates, as the required roots *are* in our trust store.
