### ISSUE TITLE
keyfinder has no binaries

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#18475]
## Issue description

There’s no KeyFinder executable in path, after installing keyfinder — https://github.com/NixOS/nixpkgs/blob/e9379f7416d04b6b7ff475816b0aa395c1e3f7f9/pkgs/applications/audio/keyfinder/default.nix
### Steps to reproduce

```
% nix-shell -p keyfinder
% cd /nix/store ; find $(ls | grep keyfinder) -type f -executable
8bhrl2wyb6s8wpsyag4zycipzwhkn9vj-libkeyfinder-2.1/lib/libkeyfinder.so.2.1.0
%
```
## Technical details
- System: 16.09.git.8a8c1a9 (Flounder)
- Nix version: nix-env (Nix) 1.11.3
- Nixpkgs version: "16.09pre90254.6b20d5b"

**Comment by copumpkin** [comment]
cc @nckx

**Comment by michalrus** [comment]
I don’t know

**Comment by Profpatsch** [comment]
@michalrus can you check?

**Comment by michalrus** [comment]
Sorry, I meant that I don’t know yet, but it’ll be hard to find some time to check (where did all my time go to ;( ;( ;( ), but I’ll try to soon

**Comment by tomberek** [comment]
(triage) close?

**Comment by lasers** [comment]
Please revisit this. The binary is only thing installed from this package.
```
~ ❯ nix-shell -p keyfinder

[nix-shell:~]$ readlink -f $(which KeyFinder)
/nix/store/mdr1hj388zfxl3mqm84fmq8190mk024b-keyfinder-2.2/bin/KeyFinder

[nix-shell:~]$ tree -a /nix/store/mdr1hj388zfxl3mqm84fmq8190mk024b-keyfinder-2.2/
/nix/store/mdr1hj388zfxl3mqm84fmq8190mk024b-keyfinder-2.2/
└── bin
    └── KeyFinder

1 directory, 1 file
```
`KeyFinder` gave me a GUI with a dialog saying "A new version, 2.4, is available on...".

**Comment by dotlambda** [comment]
@lasers Version 2.4 contains exactly *zero* functional changes compared to 2.2: https://github.com/ibsh/is_KeyFinder/compare/2.2...master
Does the binary work for you? If it does I will update the version in nixpkgs.

**Comment by twhitehead** [comment]
The KeyFinder derivation should also import `mkDerivation` and use that instead of `stdenv.mkDerivation` in order for the binaries to get properly wrapped to find their QT libraries (see [point 2](https://nixos.org/manual/nixpkgs/stable/#qt-default-nix-co-2) in the nixpkgs manual QT section).

That said, KeyFinder is [apparently unmaintained upstream](https://github.com/ibsh/is_KeyFinder/issues/110), and won't compile against `ffmpeg` instead of `libav`. This is an issue as the former is also unmaintained and has accumulated over 30 known CVEs listings against it (common vulnerabilities and exposures).

In the above bug report about this, you will see their was a recommendation to switch to Mixxx or keyfinder-cli (both of which are part of nixpkgs).

**Comment by lasers** [comment]
`KeyFinder` binary gave me that screenshot. I don't use it myself. This issue is about missing binary. Looking through stale issues.

**Comment by twhitehead** [comment]
Right. Thanks for doing that. I would think this could be closed as it sounds like the issue is the original submitter looked for `keyfinder` and not `KeyFinder`.
