### ISSUE TITLE
darwin: problem with chmod from coreutils-8.25

### ISSUE THREAD

**Issue by squiddle** [NixOS/nixpkgs#18471]
## Issue description
i try to install a modified package for boot (pkgs/development/tools/build-managers/boot).
I want it to use JDK 8 instead of 7.

But when it comes to building boot it fails with the following error:

```
installing ‘boot-2.5.2’
these derivations will be built:
  /nix/store/jalm2jiygcgb1qxdmvvrab20gxmwfn7c-boot-2.5.2.drv
building path(s) ‘/nix/store/34a74ckhbba5k97wsbyn7phs6ficj9j4-boot-2.5.2’
mkdir: created directory '/nix/store/34a74ckhbba5k97wsbyn7phs6ficj9j4-boot-2.5.2'
mkdir: created directory '/nix/store/34a74ckhbba5k97wsbyn7phs6ficj9j4-boot-2.5.2/bin'
'/nix/store/0592q8kpdgg2wygmmv4qbgxxkmqcaq20-boot.sh' -> '/nix/store/34a74ckhbba5k97wsbyn7phs6ficj9j4-boot-2.5.2/bin/boot'
dyld: lazy symbol binding failed: Symbol not found: _fchmodat
  Referenced from: /nix/store/mhygbibbr31b6dqwxy1iqaj7g4lz03zj-coreutils-8.25/bin/chmod
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fchmodat
  Referenced from: /nix/store/mhygbibbr31b6dqwxy1iqaj7g4lz03zj-coreutils-8.25/bin/chmod
  Expected in: /usr/lib/libSystem.B.dylib

/nix/store/s18jyv965qzrvvl6wjs73642pbfr59fg-builder.sh: line 7: 26002 Trace/BPT trap: 5       chmod -v 755 $boot_bin
builder for ‘/nix/store/jalm2jiygcgb1qxdmvvrab20gxmwfn7c-boot-2.5.2.drv’ failed with exit code 133
error: build of ‘/nix/store/jalm2jiygcgb1qxdmvvrab20gxmwfn7c-boot-2.5.2.drv’ failed
```

### Steps to reproduce

I add this to my `~/.nixpkgs/config.nix`

```
{
  packageOverrides = pkgs: rec {
    boot = pkgs.boot.override {
      jdk = pkgs.openjdk8;
    };
  };
}
```
and run `nix-env --install boot`

when i use `otool -L` to see the linking information of the named chmod cmd i get the following output:

```
$ otool -L /nix/store/mhygbibbr31b6dqwxy1iqaj7g4lz03zj-coreutils-8.25/bin/chmod
/nix/store/mhygbibbr31b6dqwxy1iqaj7g4lz03zj-coreutils-8.25/bin/chmod:
        /nix/store/n9pqsflc5k0fj518k1gxkj3g2dyxvbcg-gmp-6.1.1/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

## Technical details

* System: OSX 10.9.5
* Nix version: nix-env (Nix) 1.11.3
* Nixpkgs version: "16.09pre90369.202d9e2"

**Comment by copumpkin** [comment]
Yeah, I just recently killed the compatibility with 10.9 because it was a pain to maintain and Mac users are infamous for keeping their machines constantly up to date. See https://github.com/NixOS/nixpkgs/commit/948b7f23bbc42a87e66a473c5c4543cfa5a03da7 for the offending commit and part of the motivation. Might be worth creating a ticket saying "Nix on Darwin no longer supports 10.9" or posting to the mailing list. Basically, as long as I'm the only one maintaining the stdenv on Darwin, with limited time I can't really invest in keeping compatibility with old versions of OSX. If someone wants to pick that up, or present evidence that I'm cutting out a ton of users by doing this, then that'd be helpful.

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/issues/18472

**Comment by vcunat** [comment]
Let's keep just the other issue, right?

**Comment by copumpkin** [comment]
Yeah, I think that's right. This is (to some extent) expected behavior, for better or for worse.

**Comment by vcunat** [comment]
Well, it depends on someone stepping up in that issue.
