### ISSUE TITLE
ipfshttpclient is broken on master

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#185294]
### Steps To Reproduce
1. build `ipfshttpclient`

### Build log
Interesting chunks:
```
FAILED test/functional/test_block.py::test_put - AssertionError: assert 'bafk...
FAILED test/functional/test_repo.py::test_gc - AssertionError: assert 'QmNXW2...
FAILED test/functional/test_unstable.py::test_log_tail - ipfshttpclient.excep...
FAILED test/functional/test_unstable.py::test_refs_local_1 - AssertionError: ...
FAILED test/functional/test_unstable.py::test_refs_local_2 - AssertionError: ...
```

Full log: https://clbin.com/S7Rbk

### Additional context
I do not know if those are new tests which should be handled, etc.

### Notify maintainers

@mguentner @Luflosi 

### Metadata
This was run against ff4f69a15872c3bf03dec13f6f1403ee3eaa9374 of this repository.

FWIW, `nix-info -m` :
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon), 22.11pre389925.a5c867d9fe9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"home-manager, nixos, sops-nix"`
 - channels(raito): `"home-manager, nixgl, nixpkgs-21.11pre319254.b5182c214fa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Luflosi** [comment]
Yes, this is because `ipfshttpclient` hasn't seen any development in over a year and the latest officially supported IPFS version as stated by the [README](https://github.com/ipfs-shipyard/py-ipfs-http-client) is go-ipfs v0.8.0. As IPFS received more and more updates, more and more stuff in `ipfshttpclient` broke. At first I worked around these issues by skipping some tests (see https://github.com/NixOS/nixpkgs/pull/150072) but now I am not even sure if the basic functionality still works with the latest version of go-ipfs (now officially named kubo but not yet in Nixpkgs).
The best course of action would probably be to just mark this package as broken and hope for some future upstream fixes.

**Comment by RaitoBezarius** [comment]
@Luflosi I see, thank you for the insights ; I was packaging `web3.py` which seems to rely on it (https://github.com/ethereum/web3.py/blob/master/setup.py#L85), do you know if they actually do not use it at all?

**Comment by Luflosi** [comment]
[Searching the repo](https://github.com/ethereum/web3.py/search?q=ipfshttpclient) yields a couple actual uses of ipfshttpclient in the code itself, so it seems that they actually use it. You can try adding `doCheck = false;` to `pkgs/development/python-modules/ipfshttpclient/default.nix`. If you can make web3.py work fine with that workaround then I'll see if I can disable the failing ipfshttpclient tests so it builds again.

**Comment by RaitoBezarius** [comment]
@Luflosi I opened a draft PR linked here, if you want to take a look. :)

**Comment by Luflosi** [comment]
Yeah, let's just disable the tests entirely. As time goes on, it will only get worse. As long as the packages that depend on this package seem to still work fine...
