### ISSUE TITLE
zenbones.nvim

### ISSUE THREAD

**Issue by cigrainger** [NixOS/nixpkgs#185380]
**Project description**
A collection of Vim/Neovim colorschemes designed to highlight code using contrasts and font variations. Colors are tasked only for other roles such as diagnostics, diffs, search matches.

**Metadata**

* homepage URL: https://github.com/mcchrish/zenbones.nvim
* source URL: https://github.com/mcchrish/zenbones.nvim
* license: mit
* platforms: unix, linux, darwin

**Comment by cigrainger** [comment]
I had a go with the following:

```nix
  zenbones = pkgs.vimUtils.buildVimPlugin {
    name = "zenbones";
    src = pkgs.fetchFromGitHub {
      owner = "mcchrish";
      repo = "zenbones.nvim";
      rev = "e2ac0557a3df217e5d82b7e580af75c244602a33";
      sha256 = "sha256-63JrB2mklWxZyniMsRMiEn1H00HoV4gmXhoB/BAw2kQ=";
    };
  };
```

but got the following error:

```sh
error: builder for '/nix/store/hf822qynkpgcq00w0qxfv2wxaww570kn-vimplugin-zenbones.drv' failed with exit code 2;
       last 10 log lines:
       > configuring
       > no configure script, doing nothing
       > building
       > build flags: SHELL=/nix/store/kdakh3hx6mxh45jqpcynz1lp2y3f82yp-bash-5.1-p16/bin/bash
       > nvim --headless -u NORC \
       >         --cmd 'set rtp+=.' \
       >   --cmd 'lua require("zenbones.shipwright").run()' \
       >     --cmd 'q'
       > /nix/store/kdakh3hx6mxh45jqpcynz1lp2y3f82yp-bash-5.1-p16/bin/bash: line 1: nvim: command not found
       > make: *** [makefile:2: make] Error 127
       For full logs, run 'nix log /nix/store/hf822qynkpgcq00w0qxfv2wxaww570kn-vimplugin-zenbones.drv'.
```

**Comment by cigrainger** [comment]
Okay appears I just needed to add `buildInputs = [ pkgs.neovim ];`. 🤦  I'll open a PR.

**Comment by ilkecan** [comment]
> I had a go with the following:
> 
> ```nix
>   zenbones = pkgs.vimUtils.buildVimPlugin {
>     name = "zenbones";
>     src = pkgs.fetchFromGitHub {
>       owner = "mcchrish";
>       repo = "zenbones.nvim";
>       rev = "e2ac0557a3df217e5d82b7e580af75c244602a33";
>       sha256 = "sha256-63JrB2mklWxZyniMsRMiEn1H00HoV4gmXhoB/BAw2kQ=";
>     };
>   };
> ```

@cigrainger This is normally enough for most vim plugins. What is problem in this case is that the root directory of "zenbones.nvim" repository contains a `makefile`. `stdenv.mkDerivation`, which is used under the hood by `vimUtils.buildVimPlugin`, has the default behaviour of calling `make` during `buildPhase` if there is a Makefile. The `makefile` contains:
``` make

make:
	nvim --headless -u NORC \
		--cmd 'set rtp+=.' \
		--cmd 'lua require("zenbones.shipwright").run()' \
		--cmd 'q'
```
So it tries to run `nvim` which is not available inside the build environment as you noticed. But I don't think this Makefile is for end users, so rather than adding `neovim` to the build environment you can also skip calling `make`:

``` nix
zenbones = pkgs.vimUtils.buildVimPlugin {
  name = "zenbones";
  src = pkgs.fetchFromGitHub {
    owner = "mcchrish";
    repo = "zenbones.nvim";
    rev = "e2ac0557a3df217e5d82b7e580af75c244602a33";
    sha256 = "sha256-63JrB2mklWxZyniMsRMiEn1H00HoV4gmXhoB/BAw2kQ=";
  };
  dontBuild = true;
}
```

I tested the derivation above and it seems to be working as expected after:
``` vim
let g:zenbones_compat = 1
colorscheme zenbones
```
