### ISSUE TITLE
VS Code: Retry as Sudo doesn't work since 1.70

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#185662]
### Describe the bug
It seems that since VS Code 1.70, #49643 and #76526 are back.
This time, the error message when clicking "Retry as Sudo..." is 
```
Failed to save 'filename': User did not grant permission.
```

### Steps To Reproduce
1. Open VS Code;
2. Try to save a root-owned file;
3. Click "Retry as Sudo...";
4. See error.

### Expected behavior
A prompt appears to ask your password.

### Notify maintainers
@eadwu @Synthetica9 @maxeaubrey @bobby285271

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.16-zen1, NixOS, 22.11 (Raccoon), 22.11.20220807.4bdf416`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by orbistertius** [comment]
@SuperSamus I'm not able to reproduce the error message: are you running a polkit authentication agent?

With VS Code version 1.69.2, without polkit authentication agent installed, I had a different error message: 

![Selection_001](https://user-images.githubusercontent.com/1592773/183733134-7b2c2129-e82a-4831-b79d-d483cf18952d.png)

To fix this, I installed packages polkit and polkit_gnome.
Since I use i3, I also needed to run the polkit authentication agent , for example running the desktop file /run/current-system/sw/etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop with dex (Gnome runs it automatically but i3 does not).

With polkit authentication agent running, after "Retry with Sudo..." you will have a dialog asking the password for sudo.

With this setup working, I then updated VS Code to the unstable channel, v. 1.70.0, and it's working, no error messages.

```
[emiliano@galactica:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.05 (Quokka), 22.05.2322.92fe622fdfe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by SuperSamus** [comment]
Trying again, even I can't reproduce it anymore.
Must have been a fluke or something... Sorry for the noise.
Closing. (Using Plasma, by the way)

**Comment by orbistertius** [comment]
Searching for "User did not grant permission" brings this: microsoft/vscode#80516.
So I was able to reproduce the error message  entering, three times, a wrong password in the polkit authentication dialog, then in VS Code I got the "user did not grant permission" message:

![Selection_005](https://user-images.githubusercontent.com/1592773/183761862-1d792a28-2ccb-452d-9b55-917285faf43e.png)

**Comment by m911t** [comment]
Retry as sudo doesn't work for me on vscode, using nixos-unstable as system channel
