### ISSUE TITLE
no validation on systemd timer during build time

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#18594]
## Issue description

There is no build time validation for systemd timers and probably could be a systemd check to make sure that OnCalendar field is correct.
### Steps to reproduce
1. Create systemd timer like:

```
systemd.services.my-cron = {                 
    preStart = ''                                                             
       # just check if the command is for sure installed                       
       exec command --help
    '';                                                                       
     script = ''exec command import'';
     startAt = "* *-*-* 06:00:00";                                             
     restartIfChanged = false;                                                 
     stopIfChanged = false;                                                    
};  
```
1. nixos-rebuild build
2. Configuration is build but the timer specification is incorrect. This configuration throws no error on build time (ticket ticket) and on activation time (#18593).
## Technical details
- System: (NixOS: 16.09pre-git)
- Nix version: (run nix-env (Nix) 1.11.2)
- Nixpkgs version: (run 15.09.1134.19a3dd8)

**Comment by spinus** [comment]
OK, I did some more testing here. Looks like there is no validation for any systemd files. I'll try to make some work here and add validation.

**Comment by vcunat** [comment]
I think most nixos config doesn't get much validation.

**Comment by Profpatsch** [comment]
There is, unfortunately, no possibility to check a systemd unit file without a running systemd daemon, which expects to be process 1. It is simply not a use-case intended by the systemd devs (see `systemd-analyze verify --help`).

What that tells us about systemd/systemd devs should be decided is up to each person’s interpretation.

I’ll close because we have to wait for upstream to make that possible.
