### ISSUE TITLE
Gitkraken no shared packages

### ISSUE THREAD

**Issue by janat08** [NixOS/nixpkgs#186250]
### Steps To Reproduce
1. : nix-shell -p gitkraken
2. gitkraken

### Build log
```
/usr/share/gitkraken/gitkraken: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
```

### Additional context
wsl 2 debian

### Notify maintainers
@xnwdd @evanjs @arkivm 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
jk@jk:~/community-app$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/l1993ah8cpzz300p2dmpk7j5nmp4ahq3-nix-info
copying path '/nix/store/l1993ah8cpzz300p2dmpk7j5nmp4ahq3-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.16.3-microsoft-standard-WSL2, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
  - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(jk): `"nixpkgs"`
 - nixpkgs: `/home/jk/.nix-defexpr/channels/nixpkgs`

```

**Comment by abathur** [comment]
Do you still see this? 

gitkraken has been updated several times since you opened this report, though the `/usr/share/gitkraken/gitkraken` makes me think this might not have been running nix's gitkraken in the first place (I'd expect something like `/nix/store/*-gitkraken-<version>/share/gitkraken/gitkraken` if the error is using an absolute path).

**Comment by abathur** [comment]
Taking this as a "no" but happy to reopen if anyone objects.
