### ISSUE TITLE
sbt pkg does not use prescribed JDK instance

### ISSUE THREAD

**Issue by davesmith00000** [NixOS/nixpkgs#186913]
### Describe the bug
If you create a simple nix shell description that include `pkgs.sbt` and `pkgs.jdk11` where the host system has `jdk17` installed, `jdk17` is used by sbt instead of `jdk11`.

The issue is described [here](https://github.com/leigh-perry/nix-setup/issues/5) by someone else I believe who knows more about nix than I do!

### Steps To Reproduce
1. On a machine with JDK 17 installed.
2. Create a nix-shell file
3. Add the sbt and jdk11 pkgs
4. Launch the nix-shell

### Expected behavior
Once inside the shell, checking JAVA_HOME will correctly point to JDK11 in the nix-store. Entering `sbt` on the command line will fire up the sbt console, and one of the first lines will read:

`[info] welcome to sbt 1.6.1 (Azul Systems, Inc. Java 17.0.3)`

Where it should say:

`[info] welcome to sbt 1.6.1 (Azul Systems, Inc. Java 11.0.11)`

### Screenshots
N/A

### Additional context
I am not good at Nix yet 😄, but I've managed to bodge a local fix for my nix-shell by doing the following:

```
  buildInputs =
    let
      sbtWithJRE = pkgs.sbt.overrideAttrs (finalAttrs: previousAttrs: {
        postPatch = '''';
      });
    in
      [
        pkgs.jdk11
        sbtWithJRE
      ];
```

Essentially (I think) removing this line from the pkg:
https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/tools/build-managers/sbt/default.nix#L18

### Notify maintainers
@nequissimus

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.14 MiB unpacked):
  /nix/store/d1nci0syj7sn38bz157z49z5p34yl1gz-nix-info
  /nix/store/dqwlzb1jb51padp3f09nj470kfy96yha-DarwinTools-1
copying path '/nix/store/dqwlzb1jb51padp3f09nj470kfy96yha-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/d1nci0syj7sn38bz157z49z5p34yl1gz-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(dave): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by davesmith00000** [comment]
(Paging scala Nix guru @gvolpe, who might be interested and/or have a better idea of how the fix should have been done than me. 😄)

**Comment by gvolpe** [comment]
Hey @davesmith00000 👋🏽 

I think this is one of the quirks that's classified as "it's a feature, not a bug" :)  Every Nix package is required to declared all its dependencies. In the case of `sbt`, it [needs to declare](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/sbt/default.nix#L19) the `jre / jdk` in order to make a derivation, it doesn't care about global packages or global environment variables.

This can be easily overridden, though. Just need to override a `pkgs.jre = yourJdk`, and `sbt` will pick it up.

For instance, in `tyrian`, I think it will suffice to add a `jre` overlay to point to the desired JDK package, right [here](https://github.com/PurpleKingdomGames/tyrian/blob/main/flake.nix#L21).

```nix
{
overlays = [
  (f: p: { jre = p.jdk17_headless; } ) 
  (f: p: { mill = p.mill.override { jre = p.jdk17_headless; }; })
 ];
}
```

Happy to help with any specific shell :)

**Comment by tpwrules** [comment]
Yes, this is in fact how Nix is supposed to work. The overlay solution is somewhat of a large hammer, as that will configure every package which uses `jre` to use that particular one.

Another solution is to say `sbtWithJRE = pkgs.sbt.override { jre = pkgs.jre11 };` to set that input for just that sbt.

**Comment by davesmith00000** [comment]
Great! Thank you both for the explanations. :+1:
