### ISSUE TITLE
cryptsetup 2.4.3 -> 2.5.0 update breaks builds of fido2luks

### ISSUE THREAD

**Issue by ehllie** [NixOS/nixpkgs#188524]
### Steps To Reproduce
1. Build fido2luks using a version of nixpkgs with commit ad0cd6e56a9a469edfbc77242b0bac8783e8e9b4 merged.

### Build log
https://gist.github.com/ehllie/027f0280eec139172ce1f6d7fe579105

### Notify maintainers
@prusnak
@mmahut  
@danc86

### Metadata
```console
~/Code/nixpkgs on  ad0cd6e56a9 [?] took 2s 
[I] ➜ nix-shell -p nix-info --run "nix-info -m"                 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.11 (Raccoon), 22.11.20220816.762b003`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by danc86** [comment]
If I understand it rightly, some changes in cryptsetup headers in 2.5 resulted in API changes in the bindgen-generated bindings in libcryptsetup-rs-sys (these constants disappeared).

Seems there is a corresponding "fix" / workaround in libcryptsetup-rs-sys here: https://github.com/stratis-storage/libcryptsetup-rs/pull/224

fido2luks builds successfully against libcryptsetup-rs 0.5.1 (which pulls in that workaround). It fails to build against 0.6.0 because of some other API changes (perhaps also unintentional).
