### ISSUE TITLE
grsecurity vanilla doesn't support virtualbox guestadditions but nixos tries to install them anyway

### ISSUE THREAD

**Issue by matomer** [NixOS/nixpkgs#18892]
## Issue description
When grsec is enabled and the machine is a virtualbox VM, nixos tries to build the guestadditions against a grsec kernel that isn't compiled with virtualization. This results in strange build failures for GuestAdditions.

The issue is a bit more complicated because the virtualisation is enabled in the hardware-config file and then grsec is enabled in the regular config file, which cause nixos-rebuild to succeed to build the grsec kernel but to fail to build the virtualbox guest additions.

### Steps to reproduce

1. Setup virtualbox VM (optional, this would probably work on any host)
2. Set 'virtualisation.virtualbox.guest.enable = true;'
3. Set 'security.grsecurity.enable = true;'
4. Rebuild (nixos-rebuild switch)

## Technical details

* System: NixOS: 16.09beta335.7617e7e
* Nix version: 1.11.4
* Nixpkgs version: 16.09beta335.7617e7e

**Comment by joachifm** [comment]
Virtualbox is unsupported on the stock grsec kernel.

The reason why the nixos grsec module doesn't assert non-virtualbox support is that it's designed to be somewhat kernel agnostic (i.e., to accommodate a custom kernel that might be configured to support virtualbox).

I'll look into adding checks on the kernel config so that you'll get a warning or build failure when combining virtualbox with a non-virtualbox capable grsec kernel.

**Comment by joachifm** [comment]
The guest additions can be compiled on master now, whether it actually works is another matter, but I think there's nothing more to do here.
