### ISSUE TITLE
Packaging request: yadm

### ISSUE THREAD

**Issue by Samisafool** [NixOS/nixpkgs#190800]
**Project description**
Yet Another Dotfiles Manager
yadm is a tool for managing dotfiles.

**Metadata**

* homepage URL: https://yadm.io/
* source URL: https://github.com/TheLocehiliosan/yadm
* license: GPL3.0
* platforms: Unix

**Comment by IvarWithoutBones** [comment]
Looks like that's already packaged: https://github.com/NixOS/nixpkgs/blob/368346c5a13a5c5c6f6dfbe5e7719c3065ce3429/pkgs/applications/version-management/yadm/default.nix

**Comment by Samisafool** [comment]
The sources button led to https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/misc/resholve/resholve-utils.nix#L181 on nixpkgs search, so I got confused

(Btw it's outdated too, even on unstable. The latest version is 3.2.1 whereas on nixpkgs it's 3.1.1)

**Comment by abathur** [comment]
@Samisafool If the YADM bump isn't urgent for you, I'm going to see if I can fix the underlying issue in resholve's Nix API, get that updated, and then wait a few days before bumping YADM. 

(I hadn't noticed the bump because I was expecting the package-bumping bot to ping me if there was one--but the same problem in resholve's API also seems to break the bumping bot. Since I know we have a valid test case, I'm hoping to use it to confirm the change.)

**Comment by Samisafool** [comment]
Alright then, it's cool

**Comment by abathur** [comment]
@Samisafool yadm update in #191872 has been merged. Should be available in unstable in the next day or so.
