### ISSUE TITLE
lapce segfaults when opening a file or folder

### ISSUE THREAD

**Issue by MonAaraj** [NixOS/nixpkgs#191563]
### Describe the bug
Lapce launches *fine* on NixOS after `nix shell nixpkgs#lapce`. But if I attempt to use the "Open file" or "Open folder" commands in any way, it errors then segfaults with
```
(lapce:464846): GLib-GIO-ERROR **: 00:31:47.576: No GSettings schemas are installed on the system
zsh: trace trap (core dumped)  lapce
```

### Steps To Reproduce
1. `nix shell nixpkgs#lapce`
2. `lapce`
3. click anywhere on any "Open folder" or "Open file" command.

### Expected behavior
It would've probably opened a file picker for me to choose a folder or file from.

### Notify maintainers
@Eliot00 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[mon@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.11 (Raccoon), 22.11.20220901.2da64a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `""`
 - channels(mon): `""`
 - nixpkgs: `/etc/nix/flake-channels/nixpkgs`

```

**Comment by MonAaraj** [comment]
If you see this issue, then I believe the Lapce package also needs a version bump, though that's off-topic for now.

**Comment by tengkuizdihar** [comment]
There's a package called `gsettings-desktop-schemas`, maybe we need to add it to buildInputs to make this works?

**Comment by MonAaraj** [comment]
```console
~/gi/ghc:mon% nix shell nixpkgs#gsettings-desktop-schemas
~/gi/ghc:mon% nix shell nixpkgs#lapce
~/gi/ghc:mon% lapce

(lapce:28031): GLib-GIO-ERROR **: 01:31:28.564: No GSettings schemas are installed on the system
zsh: trace trap (core dumped)  lapce
```

**Comment by tengkuizdihar** [comment]
Right now I'm building it against the latest version `0.2.0`, so I hope it would fix the problem.

**Comment by tengkuizdihar** [comment]
@Eliot00 hello sorry for disturbing you, have you ever countered this error message before? It seems one of the dependencies is throwing an error because it wants to read an unexisting file?

This is the log btw https://gist.github.com/tengkuizdihar/b63833597d922d17ceb2325f14a07ae6

**Comment by 0x715C** [comment]
@tengkuizdihar Try this
```
treesitterpatch = pkgs.fetchurl {
	url = https://github.com/lapce/lapce/compare/v0.2.0...MinusGix:36c0eb5.diff;
	sha256 = "sha256-mvTrRzh/Pnys26Qj5BPglFX4A3HOy/CqhwpxVt7PyhA=";
};
cargoPatches = [ treesitterpatch ];
cargoHash = "sha256-4njr6W42DnBItmz6Yrmu5pCR13/Bfv10BxqgoP4JKS0=";
```

**Comment by tengkuizdihar** [comment]
I'll try it @0x715C

**Comment by tengkuizdihar** [comment]
0.2.0 is successfully built but the GSettings error persists. Right now I'm compiling with `wrapGAppsHook` added to `nativeBuildInputs` and see what happens.

Can you explain the magic for that patch? @0x715C

**Comment by tengkuizdihar** [comment]
Right now I'm stumped because even with wrapGAppsHook, gsettings-desktop-schemas added to the inputs, it still not able to open it the "choose folder" prompt with the same `No GSettings schemas are installed on the system` error.

**Comment by MonAaraj** [comment]
0.2.0 has this ticket: #189571. it turns out a plausible solution would be https://github.com/NixOS/nixpkgs/issues/189571#issuecomment-1252609999 @tengkuizdihar

**Comment by 0x715C** [comment]
> Can you explain the magic for that patch? @0x715C

I figured out the github link from reading [this](https://stackoverflow.com/questions/6188591/download-github-pull-request-as-unified-diff) and [this](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits). I don't think the .diff bit is documented on github.
 I don't recommend pushing expressions with these links in them to nixpkgs, but it's fine to quickly check if something will work.
MinusGix has a [merged pull](https://github.com/lapce/lapce/pull/957) to lapce/master, that's where I found the commit sha 36c0eb5.
Could use `https://github.com/lapce/lapce/pull/957.diff` as the url instead, but if the feature branch is force pushed it could invalidate the cargoHash and the fetchurl sha will not match.

I tried https://github.com/NixOS/nixpkgs/issues/189571#issuecomment-1252609999, it fixes the crash but it's missing gnome icons. Maybe this can be fixed with `--prefix XDG_DATA_DIRS : "${prev.hicolor-icon-theme}/share"`, from reading [manual](https://nixos.org/manual/nixpkgs/unstable/#ssec-gnome-hooks).

**Comment by 0x715C** [comment]
This is what I have now as a [flake](https://gist.github.com/0x715C/64f2ab39a56172d34541caa01db022b4).
Not sure if these are all needed, but I just figured I'd throw a kitchen at it.
I added gsettings-desktop-schemas, gdk-pixbuf, librsvg, gobject-introspection, hicolor-icon-theme and wrapGAppsHook to nativeBuildInputs.

**Comment by 0x715C** [comment]
https://github.com/NixOS/nixpkgs/pull/192163#issuecomment-1253163196

**Comment by tengkuizdihar** [comment]
this is solved on master btw, at last.

**Comment by MonAaraj** [comment]
@tengkuizdihar Thank you for reminding me, I'll be closing this issue. Though it's off-topic, could you tell me more about the `nix-env-selector` part? Specficially, what is it (project link?), and I didn't know VSCode had such a feature.
