### ISSUE TITLE
pysam supported platforms excludes macOS

### ISSUE THREAD

**Issue by Aehmlo** [NixOS/nixpkgs#191512]
(Apologies if this is the wrong place/format for this issue; I'm a Nix newcomer.)

I'm trying to use the Python package [`pysam`](https://pysam.readthedocs.io/) on macOS. The package itself lists macOS as a supported platform, and the package seems to work just fine for me on macOS (using `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-shell --impure -p python39Packages.pysam`), but the `pkgs.python39Packages.pysam` derivation [lists only Linux](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/python-modules/pysam/default.nix#L112) as supported. I'd be happy to contribute a patch to change this if someone could help me figure out what needs to happen.

**Comment by tjni** [comment]
That sounds reasonable to me. The list of supported platforms came from https://github.com/NixOS/nixpkgs/pull/34532, which doesn't mention MacOS, only that the package failed to build on aarch64-linux. I was locally able to build it on aarch64-darwin, so the restriction doesn't seem to be needed for MacOS.

You can open a PR that adds `platforms.darwin` (which is a list) to the platforms list (in Nix, `++` is the list concatenation operator), following the [contributing guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

**Comment by arkivm** [comment]
per https://github.com/NixOS/nixpkgs/pull/34532#issuecomment-363357113, `aarch64-linux` failed due to lack of `bcftools` on aarch64. But nothing is marked as broken in [bcftools](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/applications/science/biology/bcftools/default.nix#L38).
FWIW, I successfully built both `bcftools` and `pysam` on `aarch64-darwin`.
Any volunteers to test it on `aarch64-linux`?
