### ISSUE TITLE
esqueleto does not compile

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#19247]
## Issue description

Installing haskellPackages.esqueleto from NixOS 16.09 gives a compile error.

### Steps to reproduce

```bash
$ nix-env -iA haskellPackages.esqueleto
...
src/Database/Esqueleto.hs:437:13: error:
    • Couldn't match type ‘BaseBackend (PersistEntityBackend val)’
                     with ‘PersistEntityBackend val’
        arising from a use of ‘Database.Persist.delete’
    • In the expression: Database.Persist.delete
      In an equation for ‘deleteKey’: deleteKey = Database.Persist.delete
    • Relevant bindings include
        deleteKey :: Key val -> ReaderT (PersistEntityBackend val) m ()
          (bound at src/Database/Esqueleto.hs:437:1)
builder for ‘/nix/store/56wp6f0ami15p60mr2hrgzy3jj50chcs-esqueleto-2.4.3.drv’ failed with exit code 1
error: build of ‘/nix/store/56wp6f0ami15p60mr2hrgzy3jj50chcs-esqueleto-2.4.3.drv’ failed
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nixos-version
16.09.677.0dc31e8 (Flounder)
$ lsb_release -a
LSB Version:    n/a
Distributor ID: n/a
Description:    (none)
Release:        n/a
Codename:       n/a
$ nix-env --version
nix-env (Nix) 1.11.4
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion"16.09.677.0dc31e8"
```

**Comment by vandenoever** [comment]
@peti hope this is not too hard to fix, might be related to https://github.com/prowdsponsor/esqueleto/issues/137

**Comment by peti** [comment]
This a known problem that's not related to Nix. `esqueleto` is broken upstream -- has been for months, really --, and the package is clearly unmaintained. This library needs a new maintainer.

**Comment by vandenoever** [comment]
Nix ships a package that does not compile. That's a bug in Nix. This issue is not invalid. The solution is to remove the package, downgrade the package to a working version or patch the package.

**Comment by Mic92** [comment]
@vandenoever can you provide a patch to fix this?

**Comment by vandenoever** [comment]
prowdsponsor/esqueleto#137 links to two PRs: https://github.com/prowdsponsor/esqueleto/issues/149 and https://github.com/prowdsponsor/esqueleto/issues/150 which might fix the issue. @meteficha is maintainer and would ideally look at the PRs. Barring that, I'm not sure what the nixy solution is here. The packaging of Haskell has changed in 16.09. For my project odftestserver, which uses esqueleto, I'm sticking to using the 16.03 of nixpkgs branch for now.

**Comment by Mic92** [comment]
in `pkgs/development/haskell-modules/configuration-common.nix`  in nixpkgs there is a place to put patches. You can obtain a patch like this https://github.com/prowdsponsor/esqueleto/compare/2.4.2...enolan:stackage-nightly-updates.patch (first pull request).

if the patch is bigger it is advisable to use `fetchpatch` instead of putting it into `pkgs/development/haskell-modules/patches`.

**Comment by peti** [comment]
> Nix ships a package that does not compile. That's a bug in Nix.

The situation is more complicated that you seem to realize. First of all, Nixpkgs ship the entire Hackage database, i.e. ~72,000 Haskell at the time of this writing. The vast majority of them do not compile, simply because the respective package authors released broken code or didn't update their packages to cope with modern compilers, etc. These broken builds are not "a bug in Nix". These are bugs in the packages we offer. Now, one could argue that we shouldn't distribute broken builds. I happen to totally agree, but the unfortunate truth is that we don't even know which builds work and which ones don't.

Case in point, `esqueletto` compiles just fine when you build it with older versions of the `persistent` library, like we do [when compiling git-annex](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix#L52-L54). So arguably this build is very useful for us and should not be removed! You, on the other hand, try to compile `esqueletto` in the context of LTS Haskell 7.x, which mandates `persistent` 2.6 or later, and in that environment the build is broken, indeed.

Generally speaking, you can *not* assume that arbitrary Haskell packages compile in Nixpkgs. As I said, the situation is complicated, because Haskell library ecosystem is complicated. Nixpkgs gives you an accurate representation of that reality; it does not attempt to make things "just work". In case of `esqueletto` the responsibility for improving the situation rests firmly on the upstream package author, who has clearly abandoned this library. So now we need someone else to step up and take over maintenance. The Nix maintainers are not going to do that, but you, @vandenoever, just might?
