### ISSUE TITLE
Electron fails to build on OSX because assertion fails in libcap/default.nix

### ISSUE THREAD

**Issue by TikhonJelvis** [NixOS/nixpkgs#19308]
## Issue description

The `electron-1.2.2` package fails to build on OS X because an assertion fails:

```
installing ‘electron-1.2.2’
error: assertion failed at /nix/store/2k70j2jyvj7z27l4gwf5mx1l8n8zg3ai-nixpkgs-17.03pre93030.548bcd0/nixpkgs/pkgs/os-specific/linux/libcap/default.nix:2:1
```

Since `libcap` is in `os-specific/linux`, I'm guessing the `electron` package should check whether it's on Linux before requiring it as a dependency. 

The failed assertion:

```
{ stdenv, fetchurl, attr, perl, pam ? null }:
assert pam != null -> stdenv.isLinux;
```
### Steps to reproduce

On OS X:

```
nix-env -i electron
```
## Technical details
- System: OS X 10.11.6
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 17.03pre93030.548bcd0

**Comment by copumpkin** [comment]
If I look at the electron expression today, it looks like it has a few things that assume Linux, presumably because it uses a precompiled binary rather than a source release. It might need some work before it works on OSX. The current expression seems to be using `patchelf`, `libXscreensaver`, and the url mentions linux. Might be worth coordinating with @travisbhartwell to figure out how to make it more friendly to other platforms?

**Comment by TikhonJelvis** [comment]
I've been trying to write a version for OS X myself.

There's already a couple of issues (https://github.com/NixOS/nixpkgs/issues/17073 and https://github.com/NixOS/nixpkgs/issues/6689) for building Electron from source, but apparently it's quite difficult—certainly beyond my Nix knowledge to fix.

Would it be possible to install Electron on OS X using a binary provided by Electron? I can fetch the Darwin binary as easily as the Linux one, but there are a few things I don't know:

  * what do I need to do with the `Electron.app` file after I downloaded and extracted it?
  * do I need some equivalent of `patchelf` to make external binaries work on OS X with Nix?
  * what does `makeWrapper` do and would I need it for OS X as well?

I don't know if installing binaries like this is really practical on OS X or not, but if it is I could definitely work on updating the Electron derivation.

**Comment by matthewbauer** [comment]
I think we'd all prefer to have everything be source based. That said, pull requests are usually accepted with binary blobs.

The main thing you're going to need to do is download the file, extract the .dmg, then copy it to $out/Applications/. You probably won't need to use something like patchelf because the binaries are probably not dynamically compiled. This means that the closure going to be bigger than it would be if we used Nix-pure stuff.

Anyway, is there a reason you want to use Electron on Nix Mac? I usually just use homebrew for Application level stuff on my Mac computers.

https://github.com/NixOS/nixpkgs/issues/16455#issuecomment-228061221

**Comment by TikhonJelvis** [comment]
> Anyway, is there a reason you want to use Electron on Nix Mac?

Philosophically, I want to manage everything with Nix: I don't even have homebrew installed. (It's a work computer, so I haven't needed anything Nix couldn't handle.)

More practically, I want to create a friendly Nix wrapper around a Haskell project that uses Electron to make it easy to install on both OS X and Linux. People on my team at work all have Nix and use OS X, so this can save them a lot of time over manually fiddling with Electron.

**Comment by TikhonJelvis** [comment]
@matthewbauer The binary distribution of Electron comes as a .app bundle. I put together a .nix expression that downloads and unpacks Electron.app from the .zip file and puts it in `$out/Applications`—but I'm not sure it does what I want. At the very least, it doesn't seem to put `electron` into my path. How should I install a .app file?

Thanks for the help!

**Comment by matthewbauer** [comment]
Can we close this?
