### ISSUE TITLE
timedatectl status always reports UTC timezone

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#19339]
## Issue description

`timedatectl status` is meant to show the current timezone. It doesn't.

(I have some reason to believe that this is connected to Steam game failures, but still working on that. In any case...)

### Steps to reproduce

Set time.timeZone to anything other than UTC. Rebuild your system. Run `timedatectl status`

The output will be in UTC, with no timezone shown:
```
$  timedatectl status
  Local time: Fri 2016-10-07 20:42:31 UTC
  Universal time: Fri 2016-10-07 20:42:31 UTC
  RTC time: Fri 2016-10-07 20:42:31
  Time zone: n/a (UTC, +0000)
  Network time on: n/a
  NTP synchronized: yes
  RTC in local TZ: no

$ date
Fri Oct  7 21:46:16 IST 2016

$ grep timeZone /etc/nixos/configuration.nix
  time.timeZone = "Europe/Dublin";
```

`timedatectl list-timezones` lists only UTC.

## Technical details

* System: 17.03pre92039.adfcc2d (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre92039.adfcc2d

**Comment by abbradar** [comment]
I think this is because of this line: https://github.com/systemd/systemd/blob/master/src/basic/time-util.c#L1290

We can patch this to not check prefix, but `timezones` stil wouldn't work. For discoverability of timezones we can add `tzdata` to `system.environmentPackages` and look for them in `/run/current-system/sw/share/zoneinfo` but I'm not sure this is a good idea.

**Comment by abbradar** [comment]
See #19449, https://github.com/NixOS/systemd/pull/7.
