### ISSUE TITLE
ghcjs broken since 09-26

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#19417]
ghcjs is broken, because of problems with version pinning: https://hydra.nixos.org/build/41499439/nixlog/56
I assume it has something to do with how `stage2` pins the versions of some of the packages, but I’m not sure.

cc @cstrahan @jwiegley

**Comment by guaraqe** [comment]
I happened to try to use ghcjs right now, and while it builds here with `master`, I noted that:

- It currently is built with ghc 7.10.3 (maybe on purpose)
- As soon as ghcjs-dom is added, everything breaks since the package suffered lots of changes, which as a consequence, breaks reflex-dom.
- By removing the right non-ghcjs dependencies from ghcjs-dom, the problem moves to ghcjs-prim, which seems to be deprecated and included with ghcjs itself.

Maybe the configuration used in [try-reflex](https://github.com/reflex-frp/reflex-platform) could help? They currently have it built with ghc 8.0.1 and reflex-dom works, which implies that ghcjs-dom works.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/commit/8c95f0ffafbde396d607d0ca5d4925f8bc37588b
