### ISSUE TITLE
Barrier is unmaintained - alternative is available

### ISSUE THREAD

**Issue by Qwerty-Space** [NixOS/nixpkgs#194432]
**Project description**
Barrier is an Open-source KVM software forked from synergy, however Barrier has been unmaintained for a while.
Please see this issue:  https://github.com/input-leap/input-leap/issues/1414

**Comment by shymega** [comment]
One of the maintainers of Input Leap here. I've switched over to NixOS for an easier developer workflow, and because I like immutability, but I've pushed a commit to a branch on my `nixpkgs` fork. It's not ready yet, because I need to discuss a few things with the other maintainers, and the `.desktop` files need changing. We're heavily in the process of renaming, but both of us are busy with RL, and it's a bit full-on.

I'm working on adding the new org name to the copyright headers, Flatpak, Snap, and NixOS. It's just going to take a while.

Of course, I will not be making a PR until it builds locally. So far it's not.

The branch is [here][]

[here]: https://github.com/shymega/nixpkgs/tree/add/input-leap

**Comment by KoviRobi** [comment]
So I've debugged `barrier` to see why it wasn't writing the certificate, only to find someone had got there first https://github.com/input-leap/input-leap/commit/4874f4553025a3b9242e2bfb00f527079c023840, but it seems like I can maybe still be of use? I've made a PR against your branch, it compiles and works for me :)

https://github.com/shymega/nixpkgs/pull/1#pullrequestreview-1316744491

**Comment by shymega** [comment]
Thanks, I'll merge it soon. I actually moved back to Fedora to be honest, because my ESP32 toolchain (`espup` for Rust, and `esp-idf`) was a bit of a pain with NixOS, and I didn't understand Flakes, wanted to use it for my system configuration... but I didn't 'get' it.

I'm not sure if I'll be carrying on with my port, but I can install Nix on Fedora and test there.

**Comment by KoviRobi** [comment]
Fair of course, I think nix as a package manager, plus maybe home-manager are easier to get into than NixOS as a whole, because you can do a more gradual thing, instead of being overwhelmed having to configure everything at the start :) I'm using input-leap daily so I can be a maintainer for it on NixOS :)

**Comment by shymega** [comment]
Yeah, I need to install Nix here soon. I was going to make an Ansible playbook and Kickstart config for replicating my Fedora setup.

I don't actually like.. use Input Leap full-time. I use a proper KVM switch, and started work on a hybrid one, but hit issues. I just handle PRs, basic troubleshooting, support, and CI. If you want to take over the package, you're welcome to it :)

**Comment by KoviRobi** [comment]
To be clear, I was proposing being one of the package maintainers for it in nixpkgs -- not sure I can commit to maintaining the input-leap/input-leap if that's what you mean.

But I do use it pretty much daily, I do actually have a physical KVM too, but to me they serve slightly different purpose, one of them is using my laptop as an extra monitor. Granted it doesn't integrate into i3's stacking fully, but it's still useful especially as my laptop has Windows & WSL on it so this way I can use that for the Windows software I sometimes need to

**Comment by shymega** [comment]
No no, the package maintainer in Nixpkgs. Our policy is generally for distros to do the packaging, and we provide the scaffolding for the base of it. But we do intend to support Flatpak, Scoop, Chocolately, Snap, and Homebrew offically.

**Comment by devurandom** [comment]
input-leap is available in NixOS 24.05: https://search.nixos.org/packages?channel=24.05&show=input-leap&from=0&size=50&sort=relevance&type=packages&query=input-leap
Should this issue be closed?

**Comment by AkechiShiro** [comment]
I agree with you if should be closes @devurandom

**Comment by shymega** [comment]
Input Leap on NixOS is not functioning correctly. This issue is not yet complete.

The issue is that `libportal` doesn't have the correct D-Bus interface, whereas other distros like the Fedora COPR do. Input Leap has not yet had a stable release. I do not feel comfortable releasing Git builds on NixOS 24.05, as it leads to more issues being opened erroneously.

A release of Input Leap will not be made until we, the maintainers, are happy with the state of things.

**Comment by AkechiShiro** [comment]
@shymega this issue isn't about `libportal` or `input leap` not working functionally, there should be a new issue, IMO.

**Comment by shymega** [comment]
Yes, I understand that, but the main issue is that Input Leap hasn't had a stable release yet - I would've rather that the derivation was kept in the unstable channel, and out of the main release channels for now.

Building from Git certainly isn't recommended at this stage.

**Comment by pluiedev** [comment]
> Yes, I understand that, but the main issue is that Input Leap hasn't had a stable release yet - I would've rather that the derivation was kept in the unstable channel, and out of the main release channels for now.
> 
> Building from Git certainly isn't recommended at this stage.

It would stay in the unstable channel unless someone makes a backport PR. Also, building stuff from source is no strange matter in Nixpkgs — it's actually the preferred way, if possible.
