### ISSUE TITLE
qutebrowser-qt6: :help doesn't load

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#195626]
### Describe the bug
This error occurs when trying to open the help page.
```
23:13:04 ERROR: SchemeOSError while handling qute://* URL: [Errno 2] No such file or directory: '/nix/store/l8n17zmc8nxbxkgnhvdgk2qjm9vf6zx2-qutebrowser-unstable-2022-09-16/lib/python3.10/site-packages/qutebrowser/html/doc/index.html'
```

!["qute" links are blocked error screenshot](https://user-images.githubusercontent.com/782440/195264469-5aa0466b-5f98-4e8d-b227-7dff1eaba6be.png)

### Steps To Reproduce
Launch qutebrowser-qt6
Run :help

### Expected behavior
Loads help page

### Notify maintainers
@nrdxp (since added qt6 build, although not a maintainer)
@jagajaga @rnhmjoj @ebzzry @dotlambda

Note this doesn't happen for the qt5 build.

**Comment by nrdxp** [comment]
I probably should have added myself as a maintainer. Right now I am still using the one in my flake, i.e. `github:nrdxp/nrdos/locked#qutebrowser` since it hasn't made it to nixos unstable yet.

I'll build the one in master and see if I can reproduce, but in this build it works fine which comes directly from my PR branch: #194833
