### ISSUE TITLE
Ambiguous choice of setup hooks document location

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#195759]
## Problem

After #168932, there are two places to document the setup hooks:
1.  [6.7. Package setup hooks (ssec-setup-hooks)](https://nixos.org/manual/nixpkgs/unstable/#ssec-setup-hooks)
2.  [Chapter 16. Hooks reference (chap-hooks)](https://nixos.org/manual/nixpkgs/unstable/#chap-hooks)

How should contributors choose between them?

## Checklist

- [X] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [X] checked [open documentation issues] for possible duplicates
- [X] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Proposal

1.  Document the roles of each part of hook documentation.
2.  Merge one of them into another, so that there's only one place to document setup hooks.

## Maintainers

@edolstra (01da550)
@Ericson2314 (#26805)
@roberth (#168932)

**Comment by roberth** [comment]
Looks like I bodged it in #168932. How did I not find "Package setup hooks"...

**Comment by roberth** [comment]
> How did I not find "Package setup hooks"...

Non-stdenv hooks shouldn't be documented in the stdenv chapter. I should stop making excuses for myself ;), but this seems like a very reasonable rule.

I think we could either move the hooks that aren't built into stdenv into the new hooks chapter, or we could consider segmenting the documentation by functional subdivisions first and technical subdivisions second. In this case there would be no hooks chapter, but hooks sections in each of the functional units that come with hooks. For example, the Haskell chapter would have a section about the `ghc` hook, we'd have a PostgreSQL chapter that documents the `postgresqlTestHook` (among other things, although not sure which ), etc. Instead of hooks chapters, we could have a hooks index.

@fricklerhandwerk what do you think?

**Comment by fricklerhandwerk** [comment]
@roberth Sounds good as a longer-term goal. Present in context, collect in an index.

As a first step let's merge the Postgres hook section with the others under an appropriate section. Then once someone gets around to it, build the machinery to do the more sophisticated thing.

**Comment by roberth** [comment]
> How should contributors choose between them?

> 1. [6.7. Package setup hooks (ssec-setup-hooks)](https://nixos.org/manual/nixpkgs/unstable/#ssec-setup-hooks)

`stdenv` built-in hooks

> 2. [Chapter 16. Hooks reference (chap-hooks)](https://nixos.org/manual/nixpkgs/unstable/#chap-hooks)

Hooks you can add yourself.

**Comment by ShamrockLee** [comment]
Solved in #195796 :tada:
