### ISSUE TITLE
h-raylib: Raylib bindings for Haskell

### ISSUE THREAD

**Issue by Ashe** [NixOS/nixpkgs#197407]
**Project description**
This library includes Haskell bindings to the Raylib library. It supports Windows, Mac, Linux, and BSD.

**Metadata**

* homepage URL: https://hackage.haskell.org/package/h-raylib
* source URL: https://github.com/Anut-py/h-raylib
* license: Apache-2.0
* platforms: Windows, Mac, Linux, and BSD

**Comment by sternenseemann** [comment]
A package description for this package was automatically generated a few days ago and is present in `master` as `haskellPackages.h-raylib`. However it is marked as broken, since the build [actually failed](https://hydra.nixos.org/build/196687260/nixlog/2) and I lacked the time debugging the problem at the time.

The generated package definition looks like this:

```nix
  "h-raylib" = callPackage
    ({ mkDerivation, base, c, libGL, libX11 }:
     mkDerivation {
       pname = "h-raylib";
       version = "4.5.0.1";
       sha256 = "1bb0g8gn08pp2s763d0ic7hj46whpb6xdq0hvpar26srxlkxnzjl";
       libraryHaskellDepends = [ base ]; 
       librarySystemDepends = [ c libGL libX11 ];
       description = "Raylib bindings for Haskell";
       license = lib.licenses.asl20;
       hydraPlatforms = lib.platforms.none;
       broken = true;
     }) {c = null; inherit (pkgs) libGL; inherit (pkgs.xorg) libX11;};
```

Looking at the build log and the package description, it seems to me that the upstream cabal file neglected to declare a dependency on `libXcursor` which is missing as a result.

I think the best way to resolve this issue would be to propose a change upstream adding `Xcursor` in `extra-libraries` and asking them to release a new version to Hackage. As soon as that propagates to our package set, we can simply drop the broken flag.
Maybe you could try getting that change upstreamed? You can always test what package expression would be generated by running `cabal2nix path/to/h-raylib-source`. Also happy to answer any questions you may have.

(Currently, there is a way to get it to work by using a expression like `with haskell.lib.compose; addBuildDepend xorg.libXcursor (markUnbroken haskellPackages.h-raylib)`. I'd prefer not to maintain such an override if we can fix the metadata upstream.)

**Comment by Ashe** [comment]
Just an update to say I'm doing my best to try and test things out as per @sternenseemann 's comment, however with me still being a beginner I have to start from scratch knowledge wise. If someone wants to beat me to it then I'd be grateful, but if not I'm going to (slowly) work towards becoming comfortable with diving into this.

**Comment by Ashe** [comment]
@sternenseemann sorry for the double-ping, but the cabal file has been changed upstream in 4.5.0.2. Is there any way to retrigger a build?

Thank you for your help earlier I'm still going to use this as an opportunity to try and learn a little more so I can be more independent.

**Comment by cdepillabout** [comment]
@Ashe The easiest thing would be to wait for the `haskell-updates` branch to re-generate all the Haskell packages from the latest hackage versions, then `h-raylib` will likely be bumped to 4.5.0.2.

That will generally happen once every week or two weeks or so.

**Comment by sternenseemann** [comment]
Indeed, you can check for [PRs from the haskell-updates branch](https://github.com/nixos/nixpkgs/pulls?q=is%3Apr+is%3Aopen+head%3Ahaskell-updates). Currently there is no PR since we are taking a bit of a break until the openssl security update is done, since CI build time will be required for more important tasks during this time.

You can use `cabal2nix` to generate a nix expression for the version:

```console
> cabal2nix cabal://h-raylib-4.5.0.2
{ mkDerivation, base, c, lib, libGL, libX11, libXcursor, libXi
, libXinerama, libXrandr
}:
mkDerivation {
  pname = "h-raylib";
  version = "4.5.0.2";
  sha256 = "112dbb53ff8433ead7559d52d3ed8fcb9610c0e7c33fa423ac423a11bcc8b27b";
  libraryHaskellDepends = [ base ];
  librarySystemDepends = [
    c libGL libX11 libXcursor libXi libXinerama libXrandr
  ];
  description = "Raylib bindings for Haskell";
  license = lib.licenses.asl20;
}
```

Contrary to `hackage2nix` which generates the package set in nixpkgs it can't resolve the (system) libraries outside of `haskellPackages` (since they need to be passed at the outer, calling level), but the names that are generated seem to check out.

**Comment by sternenseemann** [comment]
From my testing this seems to work fine after applying #199423. However there are some warnings left:

```
[5 of 5] Compiling Raylib           ( src/Raylib.hs, dist/build/Raylib.p_o )

In file included from raylib/src/rglfw.c:87:0: error: 
raylib/src/external/glfw/src/posix_poll.c: In function ‘_glfwPollPOSIX’:

raylib/src/external/glfw/src/posix_poll.c:49:32: error:
     warning: implicit declaration of function ‘ppoll’; did you mean ‘poll’? [-Wimplicit-function-declaration]
       49 |             const int result = ppoll(fds, count, &ts, NULL);
          |                                ^~~~~
          |                                poll
   |
49 |             const int result = ppoll(fds, count, &ts, NULL);
   |                                ^

In file included from raylib/src/rglfw.c:87:0: error: 
raylib/src/external/glfw/src/posix_poll.c: In function ‘_glfwPollPOSIX’:

raylib/src/external/glfw/src/posix_poll.c:49:32: error:
     warning: implicit declaration of function ‘ppoll’; did you mean ‘poll’? [-Wimplicit-function-declaration]
       49 |             const int result = ppoll(fds, count, &ts, NULL);
          |                                ^~~~~
          |                                poll
   |
49 |             const int result = ppoll(fds, count, &ts, NULL);
   |                                ^

In file included from raylib/src/rglfw.c:87:0: error: 
raylib/src/external/glfw/src/posix_poll.c: In function ‘_glfwPollPOSIX’:

raylib/src/external/glfw/src/posix_poll.c:49:32: error:
     warning: implicit declaration of function ‘ppoll’; did you mean ‘poll’? [-Wimplicit-function-declaration]
       49 |             const int result = ppoll(fds, count, &ts, NULL);
          |                                ^~~~~
          |                                poll
   |
49 |             const int result = ppoll(fds, count, &ts, NULL);
   |                                ^
```

**Comment by Anut-py** [comment]
`Xext` was just added to `extra-libraries` in `h-raylib` version 4.5.0.3

**Comment by sternenseemann** [comment]
Hm, that would also work, but I don't think it is the correct fix. You don't depend on `Xext` directly, do you, @Anut-py? It seems to me that it is only pulled in via the `XInput2.h` header.

The warnings seem to be fixable (with glibc at least) by passing `-D_GNU_SOURCE` to the C compiler.

**Comment by Anut-py** [comment]
`Xext` was required as an extra library due to an unrelated issue. I thought it might be relevant here.

**Comment by sternenseemann** [comment]
I assume you are referring to [this](https://github.com/Anut-py/h-raylib/pull/2#discussion_r1014185385)? This header is only included via the xinput2 header and not directly from what I could tell, hence my comment.

**Comment by Anut-py** [comment]
Ah, I see. #199423 has been merged, does that mean it is ok to remove `Xext` from the cabal `extra-libraries`?

**Comment by sternenseemann** [comment]
It's going to take a bit of time before this change is propagated to downstream users, see the [PR tracker](https://nixpk.gs/pr-tracker.html?pr=199423). You can safely drop it when this issue is closed, probably, I'll let you know.

**Comment by sternenseemann** [comment]
Should work in #200740.

**Comment by sternenseemann** [comment]
It is definitely correctly propagated in nixpkgs (and `h-raylib` is working correctly), so I would assume it is an `haskell.nix` issue. Maybe it is ignoring the specified nixpkgs revision or preventing propagation somehow?
