### ISSUE TITLE
kdeDerivation / kdeApp should be documented in the manual

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#19793]
It seems the correct way to create a package for an application using kde5 is through kdeCallpackage and kdeDerivation, while kdeApp should be used for "official" kde applications. Is that so? If so, it should be documented in the nixpkgs manual.

**Comment by wmertens** [comment]
[triage] @ttuegel, is this documented now? Is the question correct? Would this be hard to document?

**Comment by abathur** [comment]
Closing since looks like the identifiers `kdeDerivation` and `kdeApp` were separately removed from nixpkgs and replaced with `mkDerivation`:

- `kdeDerivation` was removed and replaced with `mkDerivation` in 7b6f8dc77f7ba2cc28bdff390f5922befefa8b48. 
- `kdeApp` was replaced with `mkDerivation` in 6beea32ab104af7aad43383513682198d2f01430

I'm a little less sure given the ubiquity of the name `mkDerivation` whether this ever got sufficiently documented, but the renames probably merit taking it up in a fresh issue?
