### ISSUE TITLE
Gthumb is missing icons

### ISSUE THREAD

**Issue by exi** [NixOS/nixpkgs#19790]
## Issue description
When installing and starting gThumb, most icons are missing and replace with the standard "icon missing" icon. This leads to an unusable user experience.
I guess this is missing some implicit dependency for the icons to be present.

## Technical details

* System: NixOS 17.03pre92039.adfcc2d

@mimadrid

**Comment by mimadrid** [comment]
Could You attach a picture?
I don't have this problem, perhaps something missing in your configuration.nix?
Regards

**Comment by exi** [comment]
For me it looks like this
![gthumb](https://cloud.githubusercontent.com/assets/449463/19625706/5e08be2a-9920-11e6-9254-ea409d96ce0b.png)

What configs should i add that i might be missing?

**Comment by mimadrid** [comment]
I'm not a gtk expert and in my opinion my configuration.nix is not a good example but here it is. 
[https://gist.github.com/mimadrid/92ef860f90f7fad8a1b163c96e61dd8a](https://gist.github.com/mimadrid/92ef860f90f7fad8a1b163c96e61dd8a) (I will remove the gist as soon as the bug is resolved)
I'm using pkg.theme-vertex with pkg.paper-icon-theme.
See and copy all you could need of my environment.{pathsToLink,systemPackages,variables}
Don't hesitate to continue asking
![captura de pantalla de 2016-10-23 13-11-43](https://cloud.githubusercontent.com/assets/3269878/19625846/1921ceec-9924-11e6-8bc8-7dc1cb1810ea.png)

**Comment by exi** [comment]
Ah, installing gnome3.defaultIconTheme solved it. thank you.
Should we add this to the dependencies?

**Comment by mimadrid** [comment]
I think so, could You do a pull request? it would be great.

**Comment by Mic92** [comment]
pull request was merged
