### ISSUE TITLE
sourcehut.buildsrht fails to build

### ISSUE THREAD

**Issue by selkie-diligent** [NixOS/nixpkgs#198478]
### Steps To Reproduce
1. build *nix build github:NixOS/nixpkgs/nixos-unstable#sourcehut.buildsrht*

### Build log
```
error: builder for '/nix/store/3ls5r4wnz7fcq7jxhndd425jw8w7s8r7-python3.10-buildsrht-0.82.8.drv' failed with exit code 1;
       last 10 log lines:
       > Installing collected packages: buildsrht
       > Successfully installed buildsrht-0.82.8
       > /build/source
       > Finished executing pipInstallPhase
       > pythonOutputDistPhase
       > Executing pythonOutputDistPhase
       > Finished executing pythonOutputDistPhase
       > pythonOutputDistPhase
       > Executing pythonOutputDistPhase
       > mv: cannot stat 'dist': No such file or directory
```

### Additional context
Other sourcehut python pkgs fail in a similar manner

### Notify maintainers
@eadwu @tjni 

### Metadata
`nix flake metadata github:NixOS/nixpkgs/nixos-unstable`

```
Resolved URL:  github:NixOS/nixpkgs/nixos-unstable
Locked URL:    github:NixOS/nixpkgs/448a599c49978c2794401bfc3a2e1fba1a8663be
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/hlqsxiwbmbgsp66xdlf5adlzz2y3xmh6-source
Revision:      448a599c49978c2794401bfc3a2e1fba1a8663be
Last modified: 2022-10-28 14:21:31
```

**Comment by tjni** [comment]
Bisected this to https://github.com/NixOS/nixpkgs/pull/190487.

I don't know a lot about Python packaging. @FRidh would you have an idea? This project uses `distutils`, and I suspect that's why I get a different error when I try changing `format` to `other`, but I don't know why nothing ends up in `dist`.

For reference:

- Link to `setup.py`: https://git.sr.ht/~sircmpwn/builds.sr.ht/tree/master/item/setup.py
- Successful build output from before the change: https://pastebin.com/1T6Ne2Ci

**Comment by winterqt** [comment]
Funny, I was in the process of fixing this when you posted this comment 😄

**Comment by tjni** [comment]
Thank you!
