### ISSUE TITLE
Adding a new package to nodePackages takes hours (node2nix is slow)

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#198651]
### Describe the bug
A few hours ago I followed the documentation to add a new Javascript package to nixpkgs's nodePackages. Running `pkgs/development/node-packages/update.sh` to regenerate the `node-packages.nix` is currently still running after 2h30, slowly downloading things from the NPM registry.

### Steps To Reproduce
1. (possibly optional) Add a new Javascript package to `pkgs/development/node-packages`
2. Run `pkgs/development/node-packages/update.sh` as instructed

### Expected behavior
Adding a new package does not require several hours of waiting time. This is not good maintainer experience.

### Screenshots
n/a

### Additional context

I don't particularly have a solution here, but I have ideas:
1. Can we have something like update.sh that performs incremental only changes when adding a new package?
2. node2nix seems to issue only a single HTTP request at a time, synchronously. Parallelizing this seems like an easy win but might require talking to NPM folks to figure out quotas / rate limiting.
3. Does NPM maybe have some kind of batch API we could be using in node2nix?
4. Is there perhaps redundant work being done that could be internally cached? The node2nix usage in nixpkgs is maybe unusual in that it's looking at a forest of dependency trees, not a single one.

### Notify maintainers
cc @svanderburg who's the main node2nix author and might have other ideas

### Metadata
(irrelevant, `update.sh` runs node2nix from HEAD)

**Comment by Smona** [comment]
I've been using `--max-jobs 100` when running any nix commands that fetch node modules. It's very effective at speeding up npm dependency builds, but it's definitely not ideal, since it's not suitable for a system-wide default, and you probably want it set for any use of node2nix/yarn2nix.

I would love to see a better solution. Perhaps a `fetchNodePackages` helper which takes a list of package entries and generates an intermediate derivation by bulk-downloading them? I could see this being very inefficient though unless it can also check which packages are already cached and symlink those in directly. Otherwise adding a single dependency to a large project would cause a re-download of all dependencies, blowing out network bandwidth & nix store size.

**Comment by SuperSandro2000** [comment]
This ia known issue and was one of the reasons why we are moving to buildNpmPackage.
