### ISSUE TITLE
Support for reloadable services

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#1988]
Some services (e.g. `ngircd`) have support for reloading configuration files without stopping the service, which `systemd` supports with `ExecReload`. Unfortunately, as far as I can tell there's no good way to express something like "if, during activation, `/etc/ngircd.conf` changes but `/etc/systemd/system/ngircd.service` stays the same, do a `systemctl reload ngircd`" in the `NixOS`.

**Comment by Profpatsch** [comment]
(triage) I think this has been working for a rather long time now, right @domenkozar?

**Comment by domenkozar** [comment]
We don't have a proper solution for this (but I don't see how we could have it). Maybe @shlevy has a better vision here :)

**Comment by bobvanderlinden** [comment]
Just ran into this 'problem' as well with nginx. A wrong nginx configuration will result in the server stopping.

The current nginx service uses a direct path to the configuration file (which resides in `/nix/store`). Reloading in this case wouldn't do much good as the file will never change.

However, if we were to symlink `/etc/nginx/nginx.conf` to the right configuration file we could check in the `activationScript` if the symlink itself has changed. A bit of a dirty way to do this would be to have the `activationScript` look for `/etc/nginx/nginx.conf` and `/etc/nginx/nginx.previous.conf`. If they are both the same, do nothing. If they are different, reload and update `/etc/nginx/nginx.previous.conf`. There are probably cleaner ways to do this, but I can't think of any at the moment.

Socket activation is another alternative, but it seems like a workaround for what we really want (reloading instead of connection-forwarding).

**Comment by spinus** [comment]
I usually do it that way:
- systemd service which runs binary (restarted when binary chances)
- systemd service which keeps configuration (restarted when configuration changes, also triggers binary service to reload)

**Comment by danbst** [comment]
@spinus could you be kind enough to provide a gist, for example, how to do this for nixpkgs nginx without losing functionality? Or do you do this trick only for own services?

**Comment by spinus** [comment]
@danbst I don't have it in beautiful form which I could just paste, but I can put more details into it. I'm not sure about nginx, but haproxy for example gives you live reload.

so you create a service haproxy like that:
https://github.com/horms/haproxy/blob/master/contrib/systemd/haproxy.service.in
which depends on (but not fails when it fails) a configuration file /var/lib/haproxy.cfg

configuration.service which keeps your nix config, and during the start it links your "current" configuration to /var/lib/haproxy.cfg and does "systemctl reload haproxy" (and you can handle rollback here as well)

**Comment by spinus** [comment]
I suggest few things:

1. As outcome from this ticket, maybe it could be good to add documentation paragraph about how to implement that solution using example that @danbst implemented and describe the pattern?
2. Close the ticket - as "reloadable" configuration is very service specific I don't think we can provide anything much better than dependant services as described above (and confirmed that pattern is working).
