### ISSUE TITLE
X Server no longer starts up

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#19930]
## Issue description
I just rebuilt my full system from the `master` branch.
Upon reboot, X will not start anymore, it reports the following:

```
Oct 27 13:02:29 nixus systemd[1]: Starting X11 Server...
Oct 27 13:02:29 nixus systemd[1]: Started X11 Server.
Oct 27 13:02:29 nixus display-manager[918]: /nix/store/xvfm331xijr6xd1il3l48rz0qi9bfm72-xsession 'xterm + i3' - xterm + i3
Oct 27 13:02:29 nixus display-manager[918]: /nix/store/xvfm331xijr6xd1il3l48rz0qi9bfm72-xsession 'xterm' - xterm
Oct 27 13:02:29 nixus display-manager[918]: /nix/store/xvfm331xijr6xd1il3l48rz0qi9bfm72-xsession 'none + i3' - none + i3
Oct 27 13:02:29 nixus display-manager[918]: /nix/store/xvfm331xijr6xd1il3l48rz0qi9bfm72-xsession 'xterm + i3' - xterm + i3
Oct 27 13:02:29 nixus display-manager[918]: /nix/store/xvfm331xijr6xd1il3l48rz0qi9bfm72-xsession 'xterm' - xterm
Oct 27 13:02:29 nixus display-manager[918]: /nix/store/xvfm331xijr6xd1il3l48rz0qi9bfm72-xsession 'none + i3' - none + i3
Oct 27 13:02:29 nixus display-manager[918]: /nix/store/2wb8fqwpm2yw1ah1r0m9lxzyfnrv7sny-xauth-1.0.9/bin/xauth:  file /var/run/slim.auth does not exist
Oct 27 13:02:29 nixus display-manager[918]: (EE)
Oct 27 13:02:29 nixus display-manager[918]: Fatal server error:
Oct 27 13:02:29 nixus display-manager[918]: (EE) Cannot open log file "/nix/store/3am4s2bcm1h44cf30ysqq3jniryy4rxl-xorg-server-1.18.4/var/log/Xorg.0.log"
Oct 27 13:02:29 nixus display-manager[918]: (EE)
Oct 27 13:02:29 nixus display-manager[918]: (EE)
Oct 27 13:02:29 nixus display-manager[918]: Please consult the The X.Org Foundation support
Oct 27 13:02:29 nixus display-manager[918]:          at http://wiki.x.org
Oct 27 13:02:29 nixus display-manager[918]:  for help.
Oct 27 13:02:29 nixus display-manager[918]: (EE)
```

### Steps to reproduce
- `nixos-rebuild boot -I nixpkgs=/home/nequi/dev/nixpkgs`

## Technical details

* System:17.03pre94330.d333ec5 (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre94330.d333ec5"

**Comment by NeQuissimus** [comment]
So, I did some digging.
I set `xserver.displayManager.xserverArgs = [ "-logfile" "/var/log/X.log" ];`

The log prints this:
```
[    16.040] (II) GLX: Initialized DRI2 GL provider for screen 0
[    16.043] (II) intel(0): switch to mode 1920x1080@60.0 on eDP1 using pipe 0, position (0, 0), rotation normal, reflection none
[    16.052] (II) intel(0): Setting screen physical size to 508 x 285
[    16.076] (EE) XKB: Couldn't open rules file /nix/store/3am4s2bcm1h44cf30ysqq3jniryy4rxl-xorg-server-1.18.4/share/X11/xkb/rules/evdev
[    16.076] (EE) XKB: Failed to load keymap. Loading default keymap instead.
[    16.076] (EE) XKB: Couldn't open rules file /nix/store/3am4s2bcm1h44cf30ysqq3jniryy4rxl-xorg-server-1.18.4/share/X11/xkb/rules/evdev
[    16.076] XKB: Failed to compile keymap
[    16.076] Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
[    16.076] (EE) 
Fatal server error:
[    16.076] (EE) Failed to activate core devices.(EE) 
[    16.076] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[    16.076] (EE) Please also check the log file at "/var/log/X.log" for additional information.
[    16.076] (EE) 
[    16.076] (II) AIGLX: Suspending AIGLX clients for VT switch
[    16.156] (EE) Server terminated with error (1). Closing log file.
```

**Comment by vcunat** [comment]
It seems likely to be caused by c2922a915. On my machine X logs correctly, probably because `lightdm` also solves it in some way. Apparently `slim` doesn't, judging from your report.

**Comment by NeQuissimus** [comment]
I have the same behvaiour with all of `slim`, `gdm` and `lightdm`

**Comment by vcunat** [comment]
@NeQuissimus: perhaps try with that particular commit reverted.

**Comment by joachifm** [comment]
Note also that lots of vm tests that rely on X are currently failing

**Comment by NeQuissimus** [comment]
@vcunat @groxxda If I revert the commit c2922a9 on top of current `HEAD` of the master branch everything works again.

**Comment by joachifm** [comment]
@NeQuissimus +1 for reverting that for now, seems kind of heavy handed to me. cc @groxxda

**Comment by groxxda** [comment]
Reverting will break gdm 3.22.
`xkbdir` is needed for all display managers that start x. Things like `loglevel` and `termiate` are dm-specific, so they should be moved to the dm's that need them.

I also vote for removing the `vt` option. Only in single user environments where the login screen is replaced by the user session after logging in, it will do what you expect. In other configurations it seems unwanted to me:
- Display managers that run on x will be started on the configured vt. If the dm starts a second X for the user session, it will fail because the vt is already in use.
- Display managers that run on wayland will run on the first available vt. If they start a separate X session for the user, that one will be started on the configured vt. This fails when more than one user logs in. It also fails if you configure vt = 1.

Setting `vt = 7` is probably there because "x has been there for decades" and we don't want to surprise users. But as described above, this legacy behavior only works for legacy dms with x.

**Comment by joachifm** [comment]
Breaking gdm is preferable to breaking everything else, though. If gdm can't be made to work without breaking everything else, that's a gdm problem and ought to be treated as such. Some of us don't use or care about gdm, gnome, wayland, or what have you.

**Comment by groxxda** [comment]
I agree that if it's either gdm or everything else, break gdm.
I just wanted to outline that some of the options are broken (mainly `display` and `tty` because it restricts the module to environments where only one instance of X is started, maybe also `verbose` and `logfile` at least on `lightdm`).

Right now the breakage won't affect channel users since the channels are blocked. I'm not sure if reverting will allow the channels to update and give channel users a broken gdm.
That said, feel free to revert the commit and I'll see if I can come up with a solution for gdm.

**Comment by joachifm** [comment]
I'm sure a solution can be found that satisfies all of us, though I have no suggestion right now, apart from reverting ofc :) Btw., the vm tests suggest that gdm & gnome is broken on master anyway. If those are real errors, a revert might not make a difference.

**Comment by NeQuissimus** [comment]
I can confirm my system built off master works again.
So technically, my issue is solved. @groxxda Do you want to make a new issue for the now (I guess?) broken GDM?

**Comment by groxxda** [comment]
#19896

**Comment by vcunat** [comment]
The tests do succeed now, including the gnome one. http://hydra.nixos.org/build/42883335 I hope gdm isn't truly broken, as the channel is likely to be bumped very soon.

**Comment by joachifm** [comment]
We even almost had a channel update :)

**Comment by vcunat** [comment]
All conditions I know were (and are) fulfilled; I've got no idea why there's no channel update (yet)...

**Comment by joachifm** [comment]
Lag perhaps? No matter, seems like all is well now :)

**Comment by vcunat** [comment]
Yeah, I don't really know what's the trigger mechanism in there; maybe a few hours of latency is normal.
