### ISSUE TITLE
Libreoffice fails to build on nixos-unstable

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#199314]
https://hydra.nixos.org/eval/1784611?filter=libreoffice&compare=1784592&full=
### Build log
https://hydra.nixos.org/build/197381087
### Notify maintainers
 @7c6f434c

**Comment by ncfavier** [comment]
As a temporary workaround, you can use `libreoffice-fresh` which builds fine.

The problem seems to come from the recent update to poppler 22.09.0 in https://github.com/NixOS/nixpkgs/commit/ca9eb8eee37736e4ae2d493136597e1edb3f813d, which contains [this commit](https://github.com/freedesktop/poppler/commit/c9c5eb782a8820f328dc32bcaf74d7f0b2cb6d7a) which changes the API for `GfxState::getLineDash`.

**Comment by ncfavier** [comment]
I will note that poppler [explicitly](https://github.com/freedesktop/poppler#stable-and-unstable-apis) makes no promises about the stability of that function:

> **UNSTABLE, INTERNAL C++ API** to operate directly on Poppler's internal representation of PDF files. *If you use this API, you are on your own.* This API may change at any time, even among minor versions of Poppler!

So if LibreOffice relies on this internal API that's something to look out for.
