### ISSUE TITLE
Xorg fails to run by default when run under KVM

### ISSUE THREAD

**Issue by VShell** [NixOS/nixpkgs#1994]
KVM emulates a cirrus video card by default (on my Debian Wheezy host system), which NixOS's kernel picks up as belonging to the cirrus kernel module. Xorg then fails when loading, as its cirrus driver assumes that the cirrus kernel module is not loaded. Blacklisting the cirrus kernel module allows Xorg to load.

@vcunat added in a package for the modesetting driver, which works with the cirrus kernel module, except that both the KDE taskbar and Konsole have severe rendering issues.

I've checked Debian under KVM, and it does not ship with the cirrus kernel module, with its Xorg successfully using the cirrus driver. I've also checked NixOS 13.10, which works and matches Debian's behaviour (no cirrus kernel module, Xorg using cirrus driver).

To match old behaviour, disable CONFIG_DRM_CIRRUS_QEMU in the kernel config.

**Comment by vcunat** [comment]
@VShell: have we resolved this? I would think so, but I don't remember anymore.

**Comment by wizeman** [comment]
@vcunat It appears that @shlevy's patch hasn't been applied to master yet.

There is no `CONFIG_DRM_CIRRUS_QEMU` option defined in our kernel config, which means that we'll just pick-up whatever the kernel selects as default.

Also, if we apply @shlevy's patch, perhaps we should also revert @vcunat's change to use the `modesetting` driver, since the `cirrus` driver appears to be more robust, according to the @VShell's comment?

**Comment by vcunat** [comment]
I just added the driver package 4f50a0917. Others should know better than me why it gets used: 938f92e8, 784503864b. (Note: I do not use any VM.)

**Comment by Profpatsch** [comment]
(triage) can be close, right @vc
