### ISSUE TITLE
Collision of dotnet-sdk and dotnet-runtime

### ISSUE THREAD

**Issue by AlexD97** [NixOS/nixpkgs#199413]
### Describe the bug
When I want to install dotnet-sdk and dotnet-runtime I get 
```
error: collision between `/nix/store/jx0yf1lmwy7inmxh5nncz40bpfl2shda-dotnet-runtime-6.0.10/shared/Microsoft.NETCore.App/6.0.10/libmscordbi.so' and `/nix/store/xzcrqns22fn9sb92dmnqyl1rjg5qgf9d-dotnet-sdk-6.0.402/shared/Microsoft.NETCore.App/6.0.10/libmscordbi.so'
```

### Steps To Reproduce
1. Install dotnet-sdk and dotnet-runtime

### Notify maintainers
@kuznero @mdarocha 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.5, NixOS, 22.11 (Raccoon), 22.11.20221031.d40fea9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mdarocha** [comment]
That is because you should install more than one dotnet package using the normal means.

In your case, you should just install dotnet-sdk, since it already includes dotnet-runtime (which you can see by running dotnet --info).

If you want to install more than one dotnet version, you can use the dotnetCorePackages.combinePackages function, which will generate a combined package avoiding collisions.

**Comment by madorian** [comment]
If I install unstable.dotnet-sdk, it only installs dotnet-runtime-6.0.5

, but if I install dotnet-runtime, it installs dotnet-runtime-6.0.10

I have a collision if I install both: 

ref: https://discourse.nixos.org/t/omnisharp-from-unstable-net-6-0-10-was-not-found/23034
