### ISSUE TITLE
nvidia X11 drivers: long and short lived branch

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#19955]
## Issue description

We currently have several official nvidia drivers: `nvidia`, `nvidiaBeta`, and a bunch of `nvidiaLegacyXXX`. 
The default driver (`nvidia`) corresponds to the long-lived branch. Should this one always correspond to the long-lived branch, or can it be the short-lived one as well?

The reason I am asking is that I'm currently using the short-lived branch because it solves a bunch of artifacts.

cc @vcunat 

Overview of drivers http://www.nvidia.com/object/unix.html
Beta drivers: http://www.nvidia.com/Download/Find.aspx?lang=en-us

**Comment by NeQuissimus** [comment]
Maybe create `nvidiaShortLived` and `nvidiaLongLived` and turn `nvidia` into an alias towards the long lived version? It would be easy enough to pick which one you like then.
Also, do we really need all the legacy versions? Is there benefit to keeping them around?

**Comment by vcunat** [comment]
- Legacy versions are there because some major bumps drop support for some sets of older cards; so some people can't use any newer branches.
- Switching to short-lived is fine on unstable/master and it's not really worth it maintaining both branches in there. Still, it's probably better to keep the long-lived one on the stable branch.

**Comment by FRidh** [comment]
Thanks @NeQuissimus and @vcunat . That answers my question.
