### ISSUE TITLE
Remove Linux 4.9

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#199933]
The Linux 4.9 LTS release will be EOL after 2023/01 and I hope we can remove it before the 22.11 release, so we don't carry it around until then.

via https://endoflife.date/linux

cc kernel maintainer team

@TredwellGit @Ma27 @NeQuissimus @alyssais

**Comment by Ma27** [comment]
Thanks for the heads-up. I'd be fine with doing the removal right now (considering that it's LTS and having that one removed on stable may be an unpleasant surprise), but FWIW: we usually drop kernel releases when they get EOLed (also from stable branches), otherwise we wouldn't be able to provide non-LTS kernels on any stable branch anyways.
