### ISSUE TITLE
freetype: include/freetype2 symlink

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#20035]
## Issue description
The `freetype2` include directory is a symbolic link to itself.

```
$ ls -ld $(nix-build --no-out-link '<nixpkgs>' -A freetype.dev)/include/freetype2
lrwxr-xr-x  1 acowley  wheel  1 Dec 31  1969 /nix/store/h2rsdjnskxvn1yljpmlgzab10vlkgp85-freetype-2.6.5-dev/include/freetype2 -> .
```

A program I am using ([rospack](http://wiki.ros.org/rospack)) tries to crawl the directory, and ends up emitting warnings including the message, `boost::filesystem::status: Too many levels of symbolic links`. 

The program works properly, but I am not sure if this is the intended arrangement of the `freetype2` directory.

* System: darwin
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre-git"

**Comment by vcunat** [comment]
Yes, it was intended. There's a function for that `glib.flattenInclude`. It was just a hack to easily support packages that get the include levels incorrectly; there used to be several, I don't know why. Maybe there aren't any anymore...

**Comment by acowley** [comment]
`flattenInclude` is only used in `freetype`, `pixman`, and `cairo`, but I don't think I understand what the thinking is behind it as it seems really extreme to me. I'm wary of changing `include` paths, though, as just building those three packages probably isn't enough to gauge the impact on user code, and I don't want to break everyone's stuff.

**Comment by vcunat** [comment]
It adds another possible include path-set, and the original one remains intact (only goes through one symlink). It was done to fix builds of other packages; I don't remember any breakage because of it.

It helped in packages that don't add `-I` paths correctly (e.g. as given by `pkg-config` invocation) and still include without the `<freetype2/...>` prefix. Our hooks only add `-I${package}/include` and not one level lower... Some our expressions just solve it by directly extending the CFLAGS explicitly, but that can be tedious.

Maybe it isn't much useful anyway, which would be seen by starting a Hydra jobset without `flattenInclude` to see how many builds break. (But currently my personal motivation to explore that isn't very high, given lack of knowledge of any real problem caused by it.)

**Comment by acowley** [comment]
Well, you now have one example of a problem caused by it 😜

I don't have the build capacity to see if downstream things break with the removal, so there's not much that can be done. Thanks for taking a look!

**Comment by vcunat** [comment]
I could setup a Hydra jobset for you, if you're interested in looking into the failures etc. (with low priority so it shouldn't be a problem for others).
