### ISSUE TITLE
Mistake in cinnamon.nix

### ISSUE THREAD

**Issue by lorenzomormina** [NixOS/nixpkgs#201078]
### Describe the bug
The file cinnamon.nix
https://github.com/NixOS/nixpkgs/blob/nixos-22.05/nixos/modules/services/x11/desktop-managers/cinnamon.nix

has a mistake at line 208 (xed). It should be xed-editor because xed is "Intel X86 Encoder Decoder (Intel XED)"

### Notify maintainers
@mkg20001 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.78, NixOS, 22.05 (Quokka), 22.05.4093.cb8d3fe07d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
This is fixed in NixOS Unstable in https://github.com/NixOS/nixpkgs/commit/1abe15cfa5a8f720b7cc4e44d470e57023e13eb1, and should be part of NixOS 22.11 (which will be released in this month), it is unclear to me whether changing a default set up is okay on stable branch so I didn't do a backport. But I guess you can just add `xed-editor` in your `environment.systemPackages`.

**Comment by lorenzomormina** [comment]
Indeed I can add the correct package in `environment.systemPackages` and remove xed with `environment.cinnamon.excludePackages`

**Comment by bobby285271** [comment]
Yeah that will be the suggested way if you are still using 22.05. Closing this since this is not actionable right now :bow:
