### ISSUE TITLE
Packaging Request: Sapling

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#201473]
**Project description**
Sapling is a replacement for Git from Meta/Facebook, used internally. It's compatible with existing git repos as well as their (not yet released but planned) backend. It appears to have some notable improvements over the standard git tooling for new users. 

https://engineering.fb.com/2022/11/15/open-source/sapling-source-control-scalable/

**Metadata**

* homepage URL: https://github.com/facebook/sapling/
* source URL: https://github.com/facebook/sapling/
* license: GPLv2
* platforms: Linux, Darwin, NT

**Comment by thoughtpolice** [comment]
Nix flakes won't work out of the box with Sapling I think; we'll need to modify `libfetchers` to add a new sapling codepath so that e.g. detect when a flake is managed by sapling, detect changes, as well as some support for `fetchSapling` to fetch repositories. The git backend is totally an implementation detail and I doubt they'll ever expose `.git` directly, which would be neccessary to make the existing code work (some wrapper like `sl git` might be possible...)

But the first thing to do is package it so users can just run `sl`, of course.

That said, I've been testing it, and Sapling indeed is quite wonderful. It solves many of the issues I've had with Nixpkgs-scale (and smaller!) repositories when using git, and I've been testing it quite a lot for the past day, including by porting several of my branches to it. I'm not signing up to package it just yet (it doesn't look especially fun to tackle...) but it will almost certainly happen soon, I hope.

**Comment by pbar1** [comment]
Here's a draft PR - rough work in progress: https://github.com/NixOS/nixpkgs/pull/201798

It uses autoPatchelfHook to get the Ubuntu 22.04 deb working on NixOS. Ideally, `exec/hgmain` would be built via Cargo. I tried a frankenbuild of that, building `hgmain` and then copying the `site-packages` from the deb into a directory and setting `PYTHONPATH` to said dir, which worked. There's a shared object in the site packages that I don't know how is built yet.

**Comment by thoughtpolice** [comment]
Done, as of 47dfc53feab971ef125444fd9981c6340c1a8f0b, which is now a source-based build thanks to @pbar1's work.

macOS support is MIA. I think it's worth closing this bug and making a new one, honestly, but I'll leave it for a little while now since I'm short on time.
