### ISSUE TITLE
Please update to systemd-232!

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20156]
[Changelog](https://lists.freedesktop.org/archives/systemd-devel/2016-November/037698.html)

Systemd-232 brings a whole heap of features which can fix many security-related issues, such as #14645 #11908

**Comment by Mic92** [comment]
`DynamicUser` option is interesting. That way do not have to allocate users for services without persistent data.

**Comment by spacekitteh** [comment]
@grahamc security, update, possibly mass-rebuild

**Comment by Mic92** [comment]
@spacekitteh is there a security issue the update does address beside hardening?

**Comment by spacekitteh** [comment]
@Mic92 [CVE-2016-7795](https://www.cvedetails.com/cve/CVE-2016-7795/)

**Comment by vcunat** [comment]
I updated nixos patches to v232, built it, and running some tests locally now.

**Comment by spacekitteh** [comment]
Sweet. I'll create a ticket to take advantage of the new features.

**Comment by vcunat** [comment]
The simple nixpkgs part of the WIP: 0d3981941e6b8. I don't think I can really finish it anytime soon.

Many tests are failing with systemd-journald complaining `Failed to create notify socket: Protocol not supported`, maybe due to https://github.com/systemd/systemd/issues/4575. It's well possible some other problems are there as well, but some tests did succeed for me.

For now it might be best to find and apply security-only patches &ndash; we probably don't want systemd-232 in 16.09 anyway.

**Comment by vcunat** [comment]
From 64-bit ones, `tests.simple` times out, for example, repeatedly spitting
```
node2# Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
```

**Comment by spacekitteh** [comment]
It looks like a seccomp problem: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1576066

**Comment by Mic92** [comment]
@vcunat work-around seccomp bug for the moment: https://github.com/fbuihuu/systemd-opensuse-next/commit/e798dcbc24681f9516be4e18dfbe916cf9fa44bf

**Comment by globin** [comment]
This is pushed to staging btw. (a38f1911d34f2a72e15d5e98d76bece6cb8042a8)
