### ISSUE TITLE
xwayland: symlink causes nixos-rebuild to fail

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#20235]
## Issue description

A [symlink to /var/tmp](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/servers/x11/xorg/xwayland.nix#L28) in the xwayland package output causes nixos-rebuild to fail due to permission issues, since /var/tmp contains private directories (mode 700)

```
# ls -l /nix/store/ispxspmf82g4wydmpsx3s8v6x106j5v4-xwayland-1.18.3/share/X11/xkb
total 4,0K
lrwxrwxrwx 1 root root 8 Jan  1  1970 compiled -> /var/tmp
```

### Steps to reproduce

```
# nixos-rebuild switch
building Nix...
building the system configuration...
these derivations will be built:
...
building path(s) ‘/nix/store/zp8ckfixvmyzy9nb5s03il74psgynfqd-system-path’
...
cannot open `/nix/store/ispxspmf82g4wydmpsx3s8v6x106j5v4-xwayland-1.18.3/share/X11/xkb/compiled/systemd-private-66f44e4416bd44f2973a22015a841675-tor.service-7WtqoN': Permission denied at /nix/store/9g4wc31j7a2xp22xpgwr0qssfxahx
dzl-builder.pl line 58.

```

## Technical details

* System: NixOS 16.09
* Nix version: 1.11.4
* Nixpkgs version: 16.09.901.9902430

**Comment by dezgeg** [comment]
Essentially the same problem as in vanilla X server: #19673

**Comment by cleverca22** [comment]
found some more info on the problem

the issue, is that both wayland and xorg have the same "fix" for packages wanting to write to the store, at the same place

/nix/store/dd65ni8yzibvq2aj5jdylnv557i3hcd1-xwayland-1.18.4/share/X11/xkb/compiled and /nix/store/v82zrx8dnm5j8lq4a2fc5g0rcx2jx04k-xorg-server-1.18.4/share/X11/xkb/compiled are "conflicting"

so buildEnv tries to cd into both, find every file within, and then create a compiled directory with symlinks to merge the 2
except, both versions of compiled are symlinks to /var/tmp


in this case, there is no need to merge the contents of "compiled" since its 2 identical symlinks that are conflicting, so id say buildEnv should be patched

and i have a simple testcase: https://gist.github.com/cleverca22/29297ea8706f9346ef2c46178814eb80

**Comment by peterhoeg** [comment]
I'm guessing that this works OK when built in a sandbox?

**Comment by peterhoeg** [comment]
As both the referenced packages build now, I guess it's safe to close this.
