### ISSUE TITLE
Patroni NixOS tests time out

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#202459]
### Describe the bug
The NixOS test for patroni time out on hydra, unnecessarily delaying the channel by about 9 hours.

### Steps To Reproduce
e.g.
https://hydra.nixos.org/build/199759381
https://hydra.nixos.org/build/199760600

### Expected behavior
Tests should finish promptly or fail, not stall the channel.

### Notify maintainers
@phfroidmont 

### Metadata
Happens on both nixos-22.11 and nixos-unstable.

**Comment by phfroidmont** [comment]
I will take a look today

**Comment by phfroidmont** [comment]
I can't reproduce the problem locally, even using the exact commit from one of your examples works:
```
nix build github:nixos/nixpkgs/c9538a9b7074925ac117835c775fb81d0e7f98fa#nixosTests.patroni
```

Now by looking at hydra logs, my understanding is that the test waits for the patroni service to be started to consider the VM booted.
To address the timeout issue, I think configuring the patroni service to fail after x attempts should do the trick.
I would like to be sure and also fix the actual root cause but I don't know how without being able to reproduce.

Any idea on how I can investigate this further?

**Comment by phfroidmont** [comment]
#202567 should fix the issue
