### ISSUE TITLE
Folder in /etc: permissions

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#20258]
I am using `environment.etc."xmonad/xmonad.hs".text = ''...'';` to place my xmonad config into `/etc`.
Now, I would like to use `/etc/xmonad` as my target for this configuration (I have a patch for XMonad that will trigger it to load from there).
The issue is that `/etc/xmonad` will be created with the permissions 755.
However, XMonad requires write access to function properly (it will place other files into the folder).
I can `sudo chmod 755 /etc/xmonad` by hand, but I want to do this declaratively.
Is there any way? I looked through `env.nix` and it allows me to `chmod` the file you create but not the intermediary folders.

In case this was confusing:
- `environment.etc."xmonad/xmonad.hs".text = ''...'';` creates `/etc/xmonad/xmonad.hs`
- `/etc/xmonad` is chmod 755, needs to be 777
- `environment.etc.*` only allow chmod on the file, not the folders
- (Currently) no way to do this? What am I missing?

Thank you :D

**Comment by danbst** [comment]
Guys (don't remember who) say all the mutable stuff should be in `/var`
So patch your XMonad to do file creation in `/var/xmonad/etc`.

this should be in window manager's preStart service script. You can do chmod and chown there.

There is also a way to set ownership with `tmpfiles`, but it does work only after reboot (don't know if this is intentional) and don't know if it works with `/etc`
