### ISSUE TITLE
Allow GRUB password protection

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20272]
From the [Ubuntu GRUB page](https://help.ubuntu.com/community/Grub2/Passwords):

>GRUB 2 offers basic password protection for its menu and terminal. The user can set up passwords to protect the entire menu or specific menuentries. Passwords can be required for all users or only for selected users. The passwords can be stored in encrypted or unencrypted format.

This is a crucial, basic step for protecting a system.

**Comment by buckley310** [comment]
I took a crack at this #65231
This patch allows you to specify GRUB2 user accounts from a Nix config. Currently it just sets all user accounts as superusers, which I suspect is the most common use case. It should be straightforward to add more fine-grained permissions later if someone has the desire to do so.
This patch also only applies to GRUB2, since GRUB1 has an entirely different password system.

**Comment by rnhmjoj** [comment]
Thanks to @buclkey310 there are now options for password protection.
