### ISSUE TITLE
future dxvk `setup_dxvk.sh` script removal

### ISSUE THREAD

**Issue by Blisto91** [NixOS/nixpkgs#202865]
## Issue description
In future releases of dxvk the setup script won't be included anymore so this issue is just to notify so something can be figured out for how the nix package should handle it beforehand. (Hope such an issue is okay)

See https://github.com/doitsujin/dxvk/pull/3097

**Comment by Blisto91** [comment]
CC @reckenrode

**Comment by reckenrode** [comment]
Thanks for the heads up. The DLLs are already available via a `bin` output, but this will break anyone’s set up that relies on `setup_dxvk.sh`. A short term solution would be to vendor the script. Longer term, it would be ideal if there were a way to declaratively create and manage a Wine prefix.

**Comment by Blisto91** [comment]
2.1 has been released with the script removed 🙂

**Comment by reckenrode** [comment]
I saw that. It can also build natively on Linux, which is interesting. I need to think about how I want to do things and maybe see what other distributions that package it are doing.

**Comment by Blisto91** [comment]
God speed 🙏

**Comment by kurnevsky** [comment]
There is a nix-gaming repository that contains such derivation: https://github.com/fufexan/nix-gaming/blob/master/pkgs/wineprefix-preparer/default.nix
It also handles vkd3d-proton: https://github.com/fufexan/nix-gaming/blob/master/pkgs/vkd3d-proton/default.nix

**Comment by reckenrode** [comment]
One approach I’m considering is splitting dxvk into dxvk_1_10 (for Darwin and hardware no longer supported by 2.0) and dxvk_2_x (or just dxvk_2, not sure). The plain DXVK derivation could continue to provide the script (most likely copied from before upstream removed it) while the versioned ones would be built for the native platform only (Linux and Windows).

Well, I guess if it builds on Darwin, I can set the platform to `unix` then mark it broken on Darwin. I doubt DXVK 2.0 will work on Darwin any time soon. There are a number of extensions DXVK needs that aren’t implemented yet in MoltenVK, and since DXVK is always adding and using new ones, it’s a moving target.

**Comment by reckenrode** [comment]
I created #213026 to add the script and bump DXVK. It also exposes native builds on Linux.
