### ISSUE TITLE
oracle-instantclient does not export required env variables

### ISSUE THREAD

**Issue by dereke** [NixOS/nixpkgs#20354]
## Issue description
[oracle-instantclient](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/oracle-instantclient/default.nix) is unusable because it does not setup required env variables to point to where it is installed (OCI_LIB_DIR & ORACLE_HOME)

### Steps to reproduce
install oracle-instantclient
try and install node-oracledb using npm (you will need the node package) `npm i oracledb`

Error:
```
npm i oracledb

> oracledb@1.11.0 install /home/projecs/node_modules/oracledb
> node-gyp rebuild

node-oracledb ERR! Error: Cannot find Oracle library libclntsh.so
node-oracledb ERR! Error: See https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

gyp: Call to 'INSTURL="https://github.com/oracle/node-oracledb/blob/master/INSTALL.md"; ERR="node-oracledb ERR! Error:"; if [ -z $OCI_LIB_DIR ]; then OCI_LIB_DIR=`ls -d /usr/lib/oracle/*/client*/lib/libclntsh.* 2> /dev/null | tail -1 | sed -e 's#/libclntsh[^/]*##'`; if [ -z $OCI_LIB_DIR ]; then if [ -z "$ORACLE_HOME" ]; then if [ -f /opt/oracle/instantclient/libclntsh.so ]; then echo "/opt/oracle/instantclient/"; else echo "$ERR Cannot find Oracle library libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; else if [ -f "$ORACLE_HOME/lib/libclntsh.so" ]; then echo $ORACLE_HOME/lib; else echo "$ERR Cannot find \$ORACLE_HOME/lib/libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi; else if [ -f "$OCI_LIB_DIR/libclntsh.so" ]; then echo $OCI_LIB_DIR; else echo "$ERR Cannot find \$OCI_LIB_DIR/libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi; else if [ -f "$OCI_LIB_DIR/libclntsh.so" ]; then echo $OCI_LIB_DIR; else echo "$ERR Cannot find \$OCI_LIB_DIR/libclntsh.so" >&2; echo "$ERR See $INSTURL" >&2; echo "" >&2; fi; fi;' returned exit status 0 while in binding.gyp. while trying to load binding.gy
```

## Technical details

* System: nixos-16.09
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1017.030ffa9

**Comment by tohl** [comment]
path to libclntsh.so needs to be in environment variable LD_LIBRARY_PATH on linux and PATH on windows

**Comment by flokli** [comment]
The problem here is that the `odpi` library that takes care of loading `libclntsh.so` needs to know where to load it from.
As there's no build-time discovery and dynamic linking of this library, but `dlopen()` is being used, you need to set `${LD_LIBRARY_PATH}` or `${ORACLE_HOME}/lib` at runtime.

In the `oracle-instantclient` expression, [we patch `odpi` to load libclntsh from the correct path](https://github.com/NixOS/nixpkgs/pull/40695/commits/311c44c03b78e9e126c957d56a7db14894f78a72).

The nodejs package installed by `npm` builds its own `odpi`, so it doesn't profit from this patch. I don't know how you could patch this while building through plain npm. Building all node packages through nix and patching while doing so might work too, although node packages are somewhat WIP. 

So for now on I'd suggest to set one of the environment variables, there's not much that can be done…

**Comment by flokli** [comment]
As written in 2018, this is a nodejs issue, and could probably be fixed by passing in the right `odpi` library to the nodejs build process. As you're not using any nixpkgs packages here, closing.
