### ISSUE TITLE
zeal does not work

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#20368]
## Issue description

The `zeal` application does not start due to some icon issues.
It endless prints `QSystemTrayIcon::setVisible: No Icon set` again and again.

### Steps to reproduce

Use `awesome`, `konsole` and just run `zeal`.

## Technical details

* System: NixOS `17.03pre95306.a24728f (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `17.03pre95306.a24728f`
* Zeal: `0.3.1`
* awesome: `v3.5.9 (Mighty Ravendark)`
* konsole: `16.08.2`

**Comment by jokogr** [comment]
@flosse it seems to be working just fine here, maybe there is an issue with your Qt settings.

Before checking them, could you temporarily move your configuration, e.g. `mv ~/.config/Zeal{,.old}` and check if it works?

**Comment by flosse** [comment]
> maybe there is an issue with your Qt settings.

how & where can i change them?

>  could you temporarily move your configuration

unfortunately the error is still there :(

**Comment by jokogr** [comment]
It's ok. Install qt5ct (`nix-env -iA nixos.qt5ct`), run it to configure the theme you are using and then `export QT_QPA_PLATFORMTHEME=qt5ct` just before running zeal from your terminal.

**Comment by flosse** [comment]
cool, that works!
How can I reflect this in my `configuration.nix`?

**Comment by olejorgenb** [comment]
@flosse https://github.com/NixOS/nixpkgs/blob/eedc0f0a78f807f9dafadf14b5ed944e0239bca2/nixos/modules/programs/qt5ct.nix#L27 indicates that simply setting `config.programs.qt5ct.enable` to true should work.

You can also set `environment.variables.QT_QPA_PLATFORMTHEME="qt5ct";` directly in configuration.nix.

**Comment by Mic92** [comment]
Is there a way to make this work by default?

**Comment by olejorgenb** [comment]
Yeah, it's really not ideal that one need to know about these things to use kde programs outside kde. Same problem for okular for instance (startup time is doubled+ also in that case in addition to lack of icons).

Seems like alot of kde programs is wrapped so one way would be to add a default value to QT_QPA_PLATFORMTHEME in those wrappers? I guess which value to use depends on what themes is available though so that might be a problem.

Unfortunately these kinds of problems seems to come up alot in nixos, at least for programs used outside their "native" desktop environment. Thunar outside xfce also lack alot of icons for instance.

**Comment by flosse** [comment]
@olejorgenb Thanks for your tips :) I just did both setting `qt5ct.enable = true;` and the environment variable `QT_QPA_PLATFORMTHEME="qt5ct";` and it works :)

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by teto** [comment]
even though zeal doesn't build on current unstable (or maybe it's just my fork), it worked fine on the previous iteration thus closing
