### ISSUE TITLE
python37Packages.poetry fails with `error: pandas-1.4.4 not supported for interpreter python3.7`

### ISSUE THREAD

**Issue by pheki** [NixOS/nixpkgs#204533]
### Steps To Reproduce
1. build `python37Packages.poetry`

### Build log
```shell
$ nix-shell -p python37Packages.poetry
error: pandas-1.4.4 not supported for interpreter python3.7
(use '--show-trace' to show detailed location information)
```

### Additional context
`poetry` still supports python 3.7, but the latest `pandas` requires python 3.8.

### Notify maintainers
@jbaum98 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.78-1-lts, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(myusername): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/myusername/channels/nixpkgs`
```

**Comment by tjni** [comment]
I don't have a solution for you but can share some of the considerations you might have to keep in mind to solve this.

- nixpkgs maintainers concentrate most of their efforts on the 2 latest versions of python
- nixpkgs only (in general) maintains the most recent version of a python package

This means that, unless the fix is simple, you'll either need to do some work yourself or find someone who also cares about the issue; in this case, that's building this package on Python 3.7. If your solution(s) make the ecosystem as a whole better (e.g. simpler, more maintainable), they'll be more likely to be accepted. Keeping that in mind, here are my findings:

- one source of the pandas error is through deepdiff -> clevercsv -> ...

But this should be unnecessary, because clevercsv is only used by deepdiff's tests. I believe this is running into https://github.com/NixOS/nixpkgs/issues/118452. Solving it would take some work, but it would solve a big portion of these issues.

- some chain of dependencies leads to backports-cached-property, which is disabled for python 3.7

This is weird, because backports-cached-property is only _needed_ on python 3.6 and python 3.7. I believe that it's disabled because it runs into a known issue by which it depends (maybe transitively) on both setuptools-scm and importlib-metadata, but those depend on each other in python 3.7, so the build fails. You'd need to find an acceptable way to resolve this that doesn't introduce extra complexity; or you might be able to find a way to solve this through your own overlay.

**Comment by pheki** [comment]
I ended up using python 3.8 and also overlay / pinned old nixpkgs for what I needed... Thanks for your help!
