### ISSUE TITLE
bazel is not supported on darwin

### ISSUE THREAD

**Issue by jyp** [NixOS/nixpkgs#20579]
## Issue description

Bazel is marked "broken" for darwin. Forcing it yields a failed assertion:

```
nix-env -i bazel --show-trace
installing ‘bazel-0.3.2’
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘bazel-0.3.2’ at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/development/tools/build-managers/bazel/default.nix:25:5:
while evaluating the attribute ‘buildCommand’ of the derivation ‘bazel-bootstrap-env’ at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute ‘text’ of the derivation ‘bazel-bootstrap-env-init’ at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute ‘buildCommand’ of the derivation ‘bazel-bootstrap-env-fhs’ at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/build-support/build-fhs-userenv/env.nix:183:3:
while evaluating the attribute ‘pkgs’ of the derivation ‘bazel-bootstrap-env-usr-target’ at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating ‘callPackageWith’ at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/lib/customisation.nix:95:35, called from /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/top-level/all-packages.nix:7100:11:
while evaluating ‘makeOverridable’ at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/lib/customisation.nix:54:24, called from /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/lib/customisation.nix:99:8:
while evaluating anonymous function at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/development/libraries/glibc/default.nix:1:1, called from /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/lib/customisation.nix:56:12:
assertion failed at /nix/store/wi4y04kphl122mdq8zp76c1bw5azr7h2-nixpkgs-17.03pre95946.1fec301/nixpkgs/pkgs/development/libraries/glibc/default.nix:8:1
```

### Steps to reproduce

```
nix-env -i bazel
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

OSX Sierra

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

17.03pre95946.1fec301

**Comment by jyp** [comment]
Note:

bazel depends on `getconf`, which is apparently provided only by `buildFHSUserEnv`; which in turns is not available on darwin.

**Comment by copumpkin** [comment]
That's not very friendly to depend on `buildFHSUserEnv` ☹️  I'm guessing someone will need to think through how to make that work without it, probably with some judicious use of `patchelf` (on Linux) and `install_name_tool` (on Darwin) to rewrite the bootstrap binaries to point to sensible places in the store.

**Comment by Mic92** [comment]
This is the pull request, which introduced bazel: 
https://github.com/NixOS/nixpkgs/pull/19380

**Comment by IreneKnapp** [comment]
Yeah, I wrote this implementation. I tried a number of other strategies in addition to buildFHSUserEnv, which really isn't meant to be used at build-time like this, but it's very finicky. The build process for this package results in the various compiler binaries having hardcoded paths that are used, not for themselves, but for programs they build. So the dependencies in that category need to be in the same locations at build-time and run-time.

I don't have access to a Darwin machine right now, but would be happy to advise.

**Comment by teh** [comment]
I spent almost a day on trying to get bazel to work in a more standard way without success. I think working with upstream to make it less "weird" would be the most productive long term plan. There's also a newer version so maybe it's worth trying an update & testing.

**Comment by philandstuff** [comment]
today the build changed from "dependency failed" to "failed".  It seems there hasn't been a successful hydra build of bazel (x86_64-linux) since september: https://hydra.nixos.org/build/45076997

I'm listed as maintainer but I don't really understand the current implementation.

**Comment by IreneKnapp** [comment]
I think it's useful to look into the possible getconf dependency, because that definitely isn't declared explicitly. The log on that hydra link says "file not found" but doesn't say what file, so it's almost certainly something like that.

When I get a chance in the next few days, I'll see whether I can reproduce this locally - I admit I'm not actually sure how to make my local test build use a container.

@philandstuff, I don't really have the bandwidth to be the maintainer for this package, so what I'd like to do is share enough knowledge that you're able to continue being the maintainer? Or somebody else, I'm not picky.

**Comment by Mic92** [comment]
looking at the error it looks like user-chroot fails to mount one of the following directories:

```
mounts = { '/' => 'host',                                                                                                                                                    
           '/proc' => nil,                                                                                                                                                   
           '/sys' => nil,                                                                                                                                                    
           '/nix' => nil,                                                                                                                                                    
           '/tmp' => nil,                                                                                                                                                    
           '/var' => nil,                                                                                                                                                    
           '/run' => nil,                                                                                                                                                    
           '/dev' => nil,                                                                                                                                                    
           '/home' => nil,                                                                                                                                                   
         }                                                                                                                                                                  
```

**Comment by IreneKnapp** [comment]
Okay, on further investigation, it is specifically trying to do a recursive bind-mount of /sys into the chroot directory, and that is failing. The reason that it fails with /sys but succeeds with / and /proc is that it is already running in some sort of chroot, and that environment doesn't have all the top-level directories that the outer one does. If it got that far, it would also need /var, /run, and /home.

I don't think Bazel actually needs those directories, and I'm currently experimenting with a modified copy of user-chroot.rb which doesn't try to mount them. So far, the bazel executable produced this way can produce working Java programs, but fails to find the "as" command when asked to compile C++. I'm reasonably sure this is an unrelated problem, but it highlights the need for more automated tests...

The main users of buildFHSUserEnv are things like Steam, which definitely need those mounts set up, so I don't think changing the behavior is a good idea. Perhaps the best fix is to fork it, and create buildFHSBuildEnv, which for now would only differ in the set of mounts it creates? That seems like a lot of work...

**Comment by Mic92** [comment]
I currently do not see any user of the `extraBindMounts` arguments. That's why I would suggest the following change:
the nix function `buildFHSEnv` could take an argument called `bindMounts`. The default value of this list would be same as the current hard coded list in chroot-user.rb. Inside the ruby script ``CHROOTENV_BINDS=` would then get the complete list of mounts instead of the current ``CHROOTENV_EXTRA_BINDS=``.

**Comment by copumpkin** [comment]
Does Hydra even allow the creation of namespaces of this sort from inside a build? With `build-use-sandbox = true`, it seems unlikely that we'd be able to use them.

**Comment by Mic92** [comment]
@copumpkin it should be possible without privileges to create nested username spaces. LXC does this.

**Comment by stepcut** [comment]
I know very little about `bazel`, but I think the `chroot` approach is not the right approach.

It seems that `bazel` *does* have support for specifying where to look for the compiler and other tools. This can normally be configured by adding an appropriate entry in CROSSTOOL. Here is some information on using your own custom toolchain:

https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain

So, I am thinking that instead of trying to make darwn/nix look like FHS we instead want to tell bazel what our custom toolchain looks like.

Now, the bazel bootstrapping process does not use the [CROSSTOOL](https://github.com/stepcut/bazel-0.4.3/blob/master/tools/cpp/CROSSTOOL) that you can find in the source. Instead it uses the one created on the fly in `cc_configure.bzl`:

https://github.com/stepcut/bazel-0.4.3/blob/master/tools/cpp/cc_configure.bzl#L192

As an experiment, I hacked my local copy of `bazel-0.4.3-dist` and added in the local paths that are currently correct for my system:

https://github.com/stepcut/bazel-0.4.3/commit/50b06fb44bbb7f2468f9da5b77ced280b82fb897

And it built! Though when I try to run I get an error. Here is the full set of steps. 

First I downloaded and unpacked [bazel-0.4.3-dist.zip](https://github.com/bazelbuild/bazel/releases/download/0.4.3/bazel-0.4.3-dist.zip).

Then I entered a `nix-shell`:
```
 $ nix-shell -p clang openjdk8 darwin.apple_sdk.frameworks.CoreServices
```

Then I ran `env | grep NIX_` to get a list of the extra compiler/linker flags I might need. The values for `NIX_CFLAGS_COMPILE`, `NIX_CXXSTDLIB_COMPILE`, `NIX_LDFLAGS`, etc.

Then I hacked up `cc_configure.bzl` so that the builds using those extra flags.

Then I just run `./compile.sh` and it produces an executable! 

Unfortunately, when I run the executable I get the following error:

```
$ ./output/bazel 
dyld: Symbol not found: _kCFURLIsExcludedFromBackupKey
  Referenced from: /Users/stepcut/projects/bazel-0.4.3/./output/bazel
  Expected in: flat namespace
 in /Users/stepcut/projects/bazel-0.4.3/./output/bazel
Trace/BPT trap: 5
```

I assume this is due to some bit of arcane OS X linking that I don't understand. But is hopefully easy to fix.

There are at least two remaining challenges.

 1. how to I fix that runtime dynamic linking error

 2. how do we patch `cc_configure.bzl` at build time to add the extra flags. That is trickier than just adding a static patch in the `.nix` file since the paths have nix hashes in them.

Another challenge is that you can't just plop the `NIX_CFLAGS_COMPILE` value directly into the `cc_configure.bzl` file. You need to actually break all the separate arguments up into separate arguments.

Thoughts? All I really want is to be able to install `tensorflow` on darwin (and linux-armv7).

**Comment by IreneKnapp** [comment]
That's definitely a possible approach. I did try it for most of a day before settling on the chroot strategy, and wasn't able to make it work.

After the dynamic linker is fixed, you'll discover that there are other things it hardcodes, many of them not in ways that patchelf can find. To catch them all you need to use it to compile and run libraries and executables in C++ and Java. Before I did my rewrite of the package, it was successfully building a bazel which could not be used to build anything else.

The general thing to keep in mind is that any time you point Bazel or its bootstrap process to something, make sure it's in the location that it will be forever, even later on at runtime. So, don't put things at temporary locations just to get Bazel built.

I'm afraid I don't have a Nix-Darwin install, so I can't help with that error specifically.

**Comment by jyp** [comment]
Bazel build changed completely; the current relevent issue is #32080
