### ISSUE TITLE
brscan4 fails to configure scanner

### ISSUE THREAD

**Issue by yochai** [NixOS/nixpkgs#20632]
## Issue description
Listing brscan4 as an extra back end for sane is not working.
As far as I can tell brscan4 depends on 'nixos/modules/services/hardware/sane_extra_backends/brscan4.nix' being listed in the modules list.
Currently it's not listed there.

### Steps to reproduce
1. Add brscan4 as an extra back end without configuring the module brscan4.
2. Try to configure the scanner, will not work.
3. Try to scan anyway, just in case something did step 2 for you, will not work.

## Technical details
NixOS: 17.03.git.5711082

## Possible fix
Add the module into the modules list, tried it locally and I can scan.
But the author might have intended it to be used differently ?

**Comment by yochai** [comment]
@jraygauthier what do you think ?

**Comment by jraygauthier** [comment]
Hi, sorry for the delay. Here's how it was originally intended to be used, in this instance with a networked device:

~~~
{ config, pkgs, ... }:
{
  imports =
    [
      <nixpkgs/nixos/modules/services/hardware/sane_extra_backends/brscan4.nix>
    ];
  hardware.sane = {
    enable = true;

    brscan4.enable = true;

    brscan4.netDevices = {
      livingRoom = { model = "MFC-7860DW"; nodename = "BRW0080927AFBCE"; };
    };
  };
}
~~~

If usb plugged, you would no longer need the `.netDevices` directive.

The reason why it fails without the module is because the driver and companion utilities were shipped only as compiled binaries which depends on a bunch of `/etc` configuration files (as installed by `nixos/modules/services/hardware/sane_extra_backends/brscan4_etc_files.nix:` under the nix store and then by the `nixos/modules/services/hardware/sane_extra_backends/brscan4.nix` service directly under `/etc` were they are expected by the driver).

The `*.exe` binaries (e.g.: brsaneconfig4) are patched using `pkgs/applications/graphics/sane/backends/brscan4/preload.c`, however, the driver itself being a `*.so` (not a final executable), it is not possible to patch it in this way (it would requires all the `*.exe` which links to the driver to be patched as well, which is a pretty impossible task). Hence the need for a service to perform this setup.

You could however if you wanted perform the same mutations as performed by `nixos/modules/services/hardware/sane_extra_backends/brscan4_etc_files.nix` to get all the required file at their expected places under `/etc` and everything would work as expected. However, you would no longer have a declarative OS.

Arguing for the module to be added to the default module list was not attempted as I wasn't sure if
it was to be used at large. If you can bring it in, I'm 100% for it. Any argument against this move anyone?

**Comment by joncfoo** [comment]
Another vote for adding the module to the default set.  I scoured the repo for "brscan" and came across this issue and finally got my scanner to work over the network.

Please add :)

**Comment by jraygauthier** [comment]
I also do agree that it would be nice were it added to the default set. Not sure who's deciding however. @jagajaga Any idea?

**Comment by Mic92** [comment]
this is now reachable without weird imports.
