### ISSUE TITLE
Unable to get latest grsecurity kernel on nixos-stable

### ISSUE THREAD

**Issue by pingberlin** [NixOS/nixpkgs#20640]
## Issue description

It doesn't seem to be possible to get the latest grsecurity kernel on the nixos-stable channel.
For running NixOS on servers, having the latest still maintained kernel with grsecurity-patches enabled is necessary. 
(On desktops as well in my opinion.)
(By latest I mean the last mainline or last longterm kernel.)

I even tried configs from https://nixos.org/wiki/How_to_tweak_Linux_kernel_config_options
but did not find any working configuration to achieve this.

Is there any easy way to get the latest maintained kernel with grsecurity-patches on nixos-stable or is using a package override the most user friendly thing to do here?

---

With the following
```
security.grsecurity.enable = true;
```
I get this kernel:
```
Linux nixos 4.7.10-grsec #1-NixOS SMP Sat Oct 22 10:07:05 UTC 2016 x86_64 GNU/Linux
```

As far as I see this kernel is EOL.

---

With the following config:
```
boot.kernelPackages = pkgs.linuxPackages_latest;
security.grsecurity.enable = true; 
```

I get the following kernel without grsec:
<code>
Linux nixos 4.8.7 #1-NixOS SMP Thu Nov 10 15:39:23 UTC 2016 x86_64 GNU/Linux
</code>

### Steps to reproduce

set the following in *configuration.nix*:
```
boot.kernelPackages = pkgs.linuxPackages_latest;
security.grsecurity.enable = true; 
```

## Technical details

* System: (NixOS: `16.09.1032.6270733 (Flounder)`)
* Nix version: (nix-env (Nix) 1.11.4)
* Nixpkgs version: ("16.09.1032.6270733")

**Comment by joachifm** [comment]
The grsec kernel on 16.09 is based on 4.8. What you're seeing is a result of the channel lagging for a bit.

Please do not set `boot.kernelPackages`, unless you're specifying a custom grsec enabled kernel package set. In your config snippet, you've effectively overriden grsec entirely.

Also, note that I don't always push updates immediately to stable because it sometimes breaks boot (happened twice with 4.8, which delayed the update more than usual). All in all, maintaining an unstable patchset on a stable branch is awkward ...

**Comment by joachifm** [comment]
To elaborate on setting `boot.kernelPackages`. The module was originally designed on the assumption that nixos could enforce that a kernel had certain configuration options enabled. That would allow a user to specify a custom grsec kernel so long as it satisfied certain configuration constraints. Turns out this feature is entirely advisory. Consequently, the grsec module on nixos-stable is broken in the sense that it accepts non-grsecurity kernel packages.

**Comment by pingberlin** [comment]
Thanks for the heads up. I should "nix-channel --update" more often... my fault.

1. So there should be another ticket about the grsec-module accepting non-grsecurity kernel packages? And this one should get closed?

2. Is there a current best practice snippet floating around on overriding the kernel to a newer version with grsecurity-patches and my own kernel config file? Or is this the wrong place to ask and I should rather dig through the Nix internals and update the wiki myself?

**Comment by joachifm** [comment]
1) The language that suggests that it's possible to use a custom kernel with the module has been removed from the manual. I'm still undecided on how to deal with the issue more comprehensively. The problem is basically how to support some amount of customization while ruling out invalid configurations.

2) If you really want this, I recommend working from the definition of linux_grsec_nixos in `top-level/all-packages.nix`. You can copy-paste and tweak as necessary.
I don't recommend doing this, because you risk having to deal with boot failures &c that would otherwise be caught by our automated testing. I recommend instead waiting for the channel. If it ends up lagging, like it does from time to time, you can always cherry-pick version bumps from master.

**Comment by joachifm** [comment]
I'll close this for now. Please let me know if you encounter any other problems using grsec on stable.
