### ISSUE TITLE
mkDerivation.installPhase fails without a Makefile

### ISSUE THREAD

**Issue by LoveIsGrief** [NixOS/nixpkgs#208625]
### Describe the bug

Without a `Makefile` the installPhase of `pkgs.stdenv.mkDerivation` simply fails. For projects that don't use `make`, they consistently have use `dontInstall = true;`

### Steps To Reproduce

```sh
rm -rf /tmp/my-derivation
mkdir -p /tmp/my-derivation/bin
cd /tmp/my-derivation
echo '
{ pkgs ?  (import <nixpkgs> {}), ...}:
pkgs.stdenv.mkDerivation {
  name = "my-derivation";
  src = ./.;
}
' > default.nix
echo '#!/usr/bin/env bash
echo Hello there' > bin/hello.sh
chmod +x bin/hello.sh
nix-build
```

**output**
```
this derivation will be built:
  /nix/store/mr57j1cg42sh0gbmzzbphm5bjbca42cc-my-derivation.drv
building '/nix/store/mr57j1cg42sh0gbmzzbphm5bjbca42cc-my-derivation.drv'...
unpacking sources
unpacking source archive /nix/store/yd34hij6qplaqn61ayx247754p32dnlk-my-derivation
source root is my-derivation
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
install flags: SHELL=/nix/store/dsd5gz46hdbdk2rfdimqddhq6m8m8fqs-bash-5.1-p16/bin/bash install
make: *** No rule to make target 'install'.  Stop.
error: builder for '/nix/store/mr57j1cg42sh0gbmzzbphm5bjbca42cc-my-derivation.drv' failed with exit code 2;
       last 10 log lines:
       > unpacking source archive /nix/store/yd34hij6qplaqn61ayx247754p32dnlk-my-derivation
       > source root is my-derivation
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > no Makefile, doing nothing
       > installing
       > install flags: SHELL=/nix/store/dsd5gz46hdbdk2rfdimqddhq6m8m8fqs-bash-5.1-p16/bin/bash install
       > make: *** No rule to make target 'install'.  Stop.
       For full logs, run 'nix log /nix/store/mr57j1cg42sh0gbmzzbphm5bjbca42cc-my-derivation.drv'.
```

### Additional context

Other phases like [the build phase don't fail](https://github.com/NixOS/nixpkgs/blob/5a9a3353342fc2a964c58f91ef8cbb19585c3af8/pkgs/stdenv/generic/setup.sh#L1095) without a Makefile however this phase always does. It would be great if it worked out of the box by e.g copying the sources to `$out`, which I would consider a sane default. That's because using `dontInstall = true;` in the sample code above just fails at the next phase because `$out` is simply empty:
```
this derivation will be built:
  /nix/store/mjiy6zkl2ikag2wkyyhniblamhfz3slw-my-derivation.drv
building '/nix/store/mjiy6zkl2ikag2wkyyhniblamhfz3slw-my-derivation.drv'...
unpacking sources
unpacking source archive /nix/store/9xd9a51d97pb8ya80gmyfzisysxli473-my-derivation
source root is my-derivation
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
post-installation fixup
find: '/nix/store/j45k0r86kjb48ydgy5s12r4j0zyscwqg-my-derivation': No such file or directory
strip is /nix/store/dq0xwmsk1g0i2ayg6pb7y87na2knzylh-gcc-wrapper-11.3.0/bin/strip
error: builder for '/nix/store/mjiy6zkl2ikag2wkyyhniblamhfz3slw-my-derivation.drv' failed to produce output path for output 'out' at '/nix/store/mjiy6zkl2ikag2wkyyhniblamhfz3slw-my-derivation.drv.chroot/nix/store/j45k0r86kjb48ydgy5s12r4j0zyscwqg-my-derivation'
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.11 (Raccoon), 22.11.1137.dac57a4eccf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FRidh** [comment]
An output is needed and the primary phase that is supposed to be used for that is the `installPhase`. Hence, it should fail without an `installPhase`. I agree the communication is not very good here.

`Make` as default is how its always been around. Quite likely if there ever would be a change (and that is not going to happen lightly) then I imagine that `Make` support would be implemented as a setup took.

I want to close this as a `won't fix` but we can give it some time to let others see it.

**Comment by tpwrules** [comment]
I agree with FRidh. At some point a null derivation should fail, and failing to install is natural. I don't agree with having the default to be to copy the input directly to the output as in most scenarios that would be the result of an error in the derivation.

There are other builders which have simpler behavior. For the specific case you illustrate, have you looked at the [trivial builders](https://nixos.org/manual/nixpkgs/stable/#chap-trivial-builders), in particular `writeShellScriptBin`?

Build systems other than `make` do have hooks to customize the `installPhase` so that `dontInstall = true` is actually very rare in nixpkgs. For example, `buildPythonPackage` will (more or less) run `python setup.py install` instead of `make install`. A quick grep shows it's in 0.2% of files in nixpkgs, mostly in test-specfic derivations and the build system definitions themselves.

**Comment by LoveIsGrief** [comment]
Why not consistently fail the build, check, install, and installCheck phases if there's no `Makefile` and they haven't been overridden or skipped by the derivation author? The install phase is the only one of those phases that fails while:

 - build [checks for a `Makefile`](https://github.com/NixOS/nixpkgs/blob/5a9a3353342fc2a964c58f91ef8cbb19585c3af8/pkgs/stdenv/generic/setup.sh#L1095) and [sets `foundMakefile`](https://github.com/NixOS/nixpkgs/blob/5a9a3353342fc2a964c58f91ef8cbb19585c3af8/pkgs/stdenv/generic/setup.sh#L1098)
 - build does nothing when a `Makefile` isn't found
 - check and installCheck use `foundMakefile` to fallback to doing nothing if it's not set

IMO this is inconsistent, surprising and undocumented behavior.

@tpwrules, I'm not sure what a null derivation to you is, but if it's a `mkDerivation {}` then even with a default `cp -r $src $out` in the install, it would still fail at the `unpack` phase because there's nothing to copy.

> `Make` as default is how its always been around. Quite likely if there ever would be a change (and that is not going to happen lightly) then I imagine that `Make` support would be implemented as a setup took.

@FRidh  I'm not suggesting to replace `make`. All I'm suggesting is a default fallback just like in the other phases that provide fallbacks. If the consensus is to keep the failing behavior, then I suggest that it should at least be documented that the install phase is mandatory and should either be:

 - overriden with `installPhase = '' yada yada yada'';`
 - skipped with `dontInstall = true;`

**Comment by tpwrules** [comment]
By a null derivation, I mean one that doesn't do anything. If it just has a source input and name and no phases run, then it can pretty much just be replaced by the source input and there's no point involving `mkDerivation` at all (modulo `unpackPhase`).

The job of the `installPhase` is to create the final output, so having it be the one to die noisily instead of an earlier phase makes the most sense. Having a fallback which just copies the input to the output would mean that this case succeeds but nothing useful happens. In the case of a derivation with e.g. a broken `make install`, the output would be filled up with build junk which is bad too.

The error message is indeed unhelpful. But the behavior and philosophy of the standard build environment is pretty explicitly documented in the [relevant chapter](https://nixos.org/manual/nixpkgs/stable/#chap-stdenv) of the Nixpkgs manual.

**Comment by LoveIsGrief** [comment]
> By a null derivation, I mean one that doesn't do anything.

As in no `build` phase? Or would you consider a bunch of bash, python, and perl scripts with dependencies (`buildInputs`) that have to be copied into `$out/bin/` also "not doing anything"?

> If it just has a source input and name and no phases run, then it can pretty much just be replaced by the source input and there's no point involving `mkDerivation` at all (modulo `unpackPhase`).

How would that work? I'm new to `nix` and still learning. `derivation` still needs to put something into `$out` in order to work

> The job of the installPhase is to create the final output, so having it be the one to die noisily instead of an earlier phase makes the most sense. **Having a fallback which just copies the input to the output would mean that this case succeeds but nothing useful happens.**

I disagree here, because copying is useful (it's the entire goal of the step). `make install`'s goal is to copy the compiled binaries and relevant assets to a configured prefix. In this case the prefix is often `$out`. In the simplest case, it's just a single `cp`. 
Additionally, there are other phases that occur after e.g the [fixup phase](https://nixos.org/manual/nixpkgs/stable/#ssec-fixup-phase) which includes `patchShebang`, `patchelf`, and others, so it is indeed not the final output.

> But the behavior and philosophy of the standard build environment is pretty explicitly documented in the [relevant chapter](https://nixos.org/manual/nixpkgs/stable/#chap-stdenv) of the Nixpkgs manual.

I really do not find that helpful documentation. It's a huge chapter that starts with 

>> The standard build environment in the Nix Packages collection provides an environment for building Unix packages that does a lot of common build tasks automatically. In fact, for Unix packages that use the standard `./configure; make; make install` build interface, you don’t need to write a build script at all; the standard environment does everything automatically.

For the first two, common tasks that may deviate from the "standard" `./configure; make; make install` fallbacks are provided, but for the last, common, and simplest step (copying build output to the destination), there's no fallback nor is it explicitly documented that there is no fallback.

**Comment by tpwrules** [comment]
> How would that work? I'm new to nix and still learning. derivation still needs to put something into $out in order to work

Yes, but a derivation which does `cp $src $out` is, except for the unpack and fixup phases, the same as just replacing the `pkgs.stdenv.mkDerivation {}` with `./.`, as `./.` expands to a store path with the contents of that path copied into it.

> As in no build phase? Or would you consider a bunch of bash, python, and perl scripts with dependencies (buildInputs) that have to be copied into $out/bin/ also "not doing anything"?

Then you would have to specify a custom `installPhase` to copy the scripts to `$out/bin/`. Your previous suggested default of `cp $src $out` isn't correct here.

Which underscores the problem, that there's no general way to know what the "build output" actually is. And given that it's the purpose of a derivation, it's better to fail if the convenience here doesn't work so the user can do it properly instead of just copying some arbitrary files. In your example derivation, for instance, you'd end up with a spurious `default.nix` in the output if it worked how you wanted.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/209255

**Comment by LoveIsGrief** [comment]
I think we're on opposing ends here @tpwrules on whether the default action should be a `cp` or not. IMO the middle ground is either @Artturin's PR to make it consistent with the other phases and print a message saying it'll do nothing, or to add documentation and very clear error message stating a `Makefile` is missing and the `installPhase` attribute has not been override.

Either way, it's my staunch opinion that the current situation should not persist at it does right now:

 - A somewhat cryptic error message
 - Missing documentation
 - no suggestion on how to remedy the situation
