### ISSUE TITLE
GNOME should probably add gtk to systemPackages, or else hicolor icons are missing

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#20874]
## Issue description

In [system-path.nix](https://github.com/NixOS/nixpkgs/blob/1ac5869907a9bbe9bb361e9d1a248bbb848c8544/nixos/modules/config/system-path.nix#L137), we're running `$out/bin/gtk-update-icon-cache`. But when `gtk` is not in `PATH`, this executable does not exists. In effect, icon cache for `hicolor/` icons is not updated and the icons are not visible in GNOME applications view.

### Steps to reproduce

Turn on just GNOME with GDM, with no `gtk` or `gtk2` in `environment.systemPackages`. Log in. Press `<Super>`. More/less half of the icons are missing (the `share/icons/hicolor/…` ones).

## Technical details

* System: 16.09.1135.b833b10 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1135.b833b10"

**Comment by e-user** [comment]
I can confirm the behavior and the workaround.

**Comment by bjornfor** [comment]
CC @lethalman

**Comment by globin** [comment]
Should more likely be an explicit `${gtk}/bin/gtk-update-icon-cache` or similar.

**Comment by bjornfor** [comment]
Actually, no. The problem is a regression due to multiple-output.

```gtk-update-icon-cache``` used to be in the ```gtk3``` package, but is now in ```gtk3.dev```. (The GNOME desktop module ensures that "gtk3" goes into ```environment.systemPackages```, so we just have to fix that multiple-outputs thing. AFAIK, binaries shouldn't be in .dev.)

cc @vcunat

**Comment by vcunat** [comment]
Well, for binaries that are exclusively useful during development (building etc.), I was putting such commonly into `.dev`.  In this case it wasn't a good choice due to this consequence; it has been reverted long ago but only for `gtk2` and not `gtk3`.

It would be best to have it refer to the binary explicitly, but you don't know *when* the cache would be needed &ndash; so it's generated whenever that binary can be found.  (People using pure KDE+Qt probably wouldn't like that rebuilding their system requires GTK and generates GTK-specific cache.)

**Comment by vcunat** [comment]
I staged a commit that should fix this with gtk3/gnome as well.

**Comment by bjornfor** [comment]
Thanks!

**Comment by bjornfor** [comment]
Cherry-picked to release-16.09: 326e156567f87da63c0ff70c3031c9b0460aeb28.
