### ISSUE TITLE
Boot freezes at Starting WPA supplicant

### ISSUE THREAD

**Issue by AnzenKodo** [NixOS/nixpkgs#208881]
**Describe the bug**

When booting my laptop, which is running NisOS 23.05pre437883 on kernal 6.1.1, it freezes when it gets to WPA supplicant saying:

```
[ OK ] Started WPA supplicant
```

I have to use older generation NixOS 23.05pre434398 on kernel 6.0.12 for it to work.

**Expected behavior**

Continue to booting after `[OK] Starting WPA Supplicant`

**Additional context**

Stoped Working after: NixOS 23.05pre435935 kernel 6.1.0

**Comment by foo-dogsquared** [comment]
This recently happened to me at NixOS 23.05.20230306.a028e28, 6.1.15 kernel. I will document what I've done and the workaround for this. Maybe someone with more familiarity with Linux networking setup and/or hardware can infer. Unfortunately, I was not able to pinpoint the problem but I'll try to once I have some time.

I initially thought the problem would be related to the kernel and it just happened to affect my hardware so I updated the configuration to use Linux kernel version to 6.2. Boot still freezes.

I booted to the last good generation with Linux kernel 5.15.94 and tried to compare it with the failed boot but all of the logs from the failed boot are not flushed after a certain point so I cannot get a good look what is really happening. I tested this multiple times and all of the failed boots only have the logs up to a certain point consistently.

The next thing I tried is disabling some of the services and I thought the problem is on wpa_supplicant since it always freezes at that point. I just looked at the logs from the successful boot (which is in the good generation) and try to disable the services without disrupting the system entirely. Still the same.

At this point, I gave up and just switched to iwd which NetworkManager also supports as a backend. System successfully boots. It's using Linux kernel 6.2 and everything (and also the disabled services from before has been re-enabled).

**Comment by rnhmjoj** [comment]
> The next thing I tried is disabling some of the services and I thought the problem is on wpa_supplicant since it always freezes at that point. 

I really doubt that: it's just that wpa_supplicant happens to start right before the kernel does modesetting, so it's the last thing you see on the console if something goes wrong during.

**Comment by hostops** [comment]
Yeah, I'm having the same issue with my Lenovo Yoga 9000s. It keeps freezing up and showing different "Starting <service>" messages in the last log whenever I try different configurations. Unfortunately, I can't seem to find anything helpful in the logs. It happened to me earlier today when I was just rebuilding my configuration, and I didn't even change anything significant. My configuration from yesterday was working just fine, so it's probably due to some updated packages. Right now, I'm on the 22.11 branch with the same version for home-manager.

**Comment by hostops** [comment]
In latest version of the same branch, it seems to work now.
