### ISSUE TITLE
Krita doesn't build.

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#209000]
### Steps To Reproduce
1. Add `krita` to `environment.systemPackages`
2. Try to nixos-rebuild

### Build log
https://gist.githubusercontent.com/surfaceflinger/ba2447d65de78286c7fae0a7ea36c50e/raw/baf122b542c33e83a6705241d7fb35fe0bd4da14/krita.log

### Additional context
Log shows `fatal error: cannot write PCH file: No space left on device` but I don't think that's the case, because I have almost 300GB left. Looks like it doesn't build on Hydra either, because it's been trying to build locally for me for few days and flake updates now.

### Notify maintainers
@abbradar @sifmelcara @nek0

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.15, NixOS, 23.05 (Stoat), 23.05.20221231.8ba56d7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lilyinstarlight** [comment]
It actually does build, but the most recent build failed on Hydra due to a transient error (builder disk space) and was never restarted: https://hydra.nixos.org/build/203494336

I've built it locally and pushed the storepath `/nix/store/vwp5549a039dsv0ii869284cb3hl40ci-krita-5.1.3` to https://foosteros.cachix.org/ to show that it does in fact build (and also to unblock my own config)

Maybe @vcunat could restart the Hydra job? (or we could get #207330 merged, which would cause a rebuild anyway)

**Comment by vcunat** [comment]
Maybe you're using tmpfs and that's where it doesn't fit?

Anyway, it succeeded after restarting, so I'd close this.  The build is probably expensive and that can cause issues unfortunately, but I think it will be hard for us to improve.

**Comment by surfaceflinger** [comment]
oh, for some reason I've thought builds are happening in /nix too:)
