### ISSUE TITLE
okular: Can't find PDF files in "Open"

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#209706]
### Describe the bug
In Okular, when opening a file in the "Open" menu, PDF files are not shown in the file picker, even if you filter specifically for them. They only show with the filter "All Files", or on "Open Recent".
There is no problem actually opening a PDF file.

### Steps To Reproduce
1. Open Okular
2. "Open..."
3. Navigate to where there should be a PDF file
4. There is no PDF file listed

### Expected behavior
PDF files are listed.

### Additional context
I tried deleting the configurations files from `.config` and `.local/share`, but no dice.
Other programs (like LibreOffice) have no problem listing PDF files.

### Notify maintainers
@ttuegel @turion 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.2-zen1, NixOS, 23.05 (Stoat), 23.05.20230103.298add3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by OPNA2608** [comment]
When you say PDF files, are their extensions upper-case `.PDF` by chance (or just not exactly all lower-case `.pdf` in general)? Could you test some other Qt applications that use Qt's file dialogue functions (`qcomicbook` seems to exhibit the same problem)? What DE are you on, is it GTK-based?

This smells to me like a bug we noticed in a downstream Qt application, where some Qt-GTK interplay in the file dialogues makes capitalisation of file extensions hard to deal with: https://github.com/BambooTracker/BambooTracker/issues/338

I can confirm this on my end with the same workaround we noticed downstream: Forcing Qt to use its own file dialogue instead of the native one fixes it:

`QT_QPA_PLATFORMTHEME= XDG_SESSION_DESKTOP= DESKTOP_SESSION= LD_PRELOAD= XDG_CURRENT_DESKTOP= okular`

![image](https://user-images.githubusercontent.com/23431373/211209501-c0cd9cb4-128b-45f1-99cd-c520813946de.png)

**Comment by SuperSamus** [comment]
`.PDF` or `.pdf` doesn't matter.
I'm on KDE Plasma 5.26.4 (Wayland).
`qcomicbook` doesn't exhibit the problem.
`XDG_CURRENT_DESKTOP= okular` does solve the problem.

**Comment by turion** [comment]
I cannot reproduce. Maybe it's Wayland-specific?

**Comment by turion** [comment]
What does `echo $XDG_CURRENT_DESKTOP` return for you? For me it's `KDE`.

**Comment by SuperSamus** [comment]
I reproduce on both X11 and Wayland.
```console
$ echo $XDG_CURRENT_DESKTOP
KDE
```

**Comment by peterhoeg** [comment]
I'm also unable to reproduce this on latest unstable in a KDE wayland session.
```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.7, NixOS, 23.05 (Stoat), 23.05.20230127.782af6c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/etc/nixPath`
 ```

**Comment by turion** [comment]
@SuperSamus can you create a new user on your system and check whether you can recreate? If yes, can you share your config?

**Comment by SuperSamus** [comment]
I created a new user, and it *doesn't* have the issue.
However, the old user still has the problem, even though I deleted the files with `okular` in the name in `.config` and `.local/share`.

**Comment by turion** [comment]
Then this must be an okular bug where it messed up some other file in your home folder. Sorry! Seems we can rule out a nixos issue at least, even though it remains mysterious.

**Comment by SuperSamus** [comment]
I found the cause: Wine's file associations were somehow interfering (according to logs, Okular was seeing `x-wine-extension-pdf` instead of `application/pdf`). I solved it by following https://appuals.com/unregister-wine-file-associations-linux/.
Should I report this to bugs.kde.org, or somewhere else? (Or is it already reported?)
