### ISSUE TITLE
SHENZHEN I/O on Steam

### ISSUE THREAD

**Issue by puffnfresh** [NixOS/nixpkgs#21109]
The SHENZHEN I/O game on Steam launches after overriding `LD_LIBRARY_PATH`. Sadly this means it can't then load libGL on NixOS. I had to modify the launcher script under `~/.steam/steam/steamapps/common/SHENZHEN IO/Shenzhen` so that it would prepend, instead of override:

```bash
export LD_LIBRARY_PATH=$STEAM_LD_LIBRARY_PATH${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH
```

I emailed this to the creator of the game but they indicated that NixOS is not supported and so may not be able to do any work for it.

Do we have any mechanism for patching a Steam game ourselves?

**Comment by abbradar** [comment]
I recently thought about using `ld.so.cache` instead of `LD_LIBRARY_PATH`. It solves those problems and also speeds things up, but there is one thing which breaks the idea: we can't do nested `ld.so.cache`. That is, Steam FHS would have its own `ld.so.cache`, and host NixOS would have its own (with `/run/opengl-driver/lib`), and we can't simply combine them somehow -- the only way from what I see is to run `ldconfig` at _every_ start of FHS env (which seems hacky and slow to me).

Also I've thought of adding support for `NIX_LD_LIBRARY_PATH` to Glibc. Unfortunately, the code is... not so easy I hoped it to be. I took a look long ago so the details are hazy but we can't just add `add_library_path("NIX_LD_LIBRARY_PATH")` somewhere and be done.

**Comment by abbradar** [comment]
And to answer your question -- no, we don't have any automated way to patch games ATM, and it would be difficult to do (we need to somehow track your game installations and run hooks for new ones). Also, Steam will replace this patch on the game update, and some games might check their files too, so some other solution must be found.

**Comment by tomberek** [comment]
close as resolved or old?

**Comment by puffnfresh** [comment]
Yeah just old

**Comment by nyanloutre** [comment]
Still happening, the export in the launch script did the trick
