### ISSUE TITLE
win-virtio erased

### ISSUE THREAD

**Issue by pzant** [NixOS/nixpkgs#211106]
### Describe the bug
nix-collect-garbage erase win-virtio from /nix/store

### Steps To Reproduce
1. environment.systemPackages = [ pkgs.virt-manager ];
2. nix-collect-garbage -d

### Expected behavior
Should keep directory

### Notify maintainers
@ajs124 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10-zen2, NixOS, 22.11 (Raccoon), 22.11.1629.2f9fd351ec3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ajs124** [comment]
I'm neither the maintainer of virt-manager nor win-virtio

**Comment by Atemu** [comment]
What was the path and how did you set it?

Only things that are (transitively) depended on by a path with a gc-root on it (such as things in your system closure) will be preserved by garbage collecion.

**Comment by pzant** [comment]
> What was the path and how did you set it?
/nix/store/_hash_-win-virtio-0.1.196-1
> Only things that are (transitively) depended on by a path with a gc-root on it (such as things in your system closure) will be preserved by garbage collecion.
The packages is in the systemPackages of config file, is this not enough?
If install the package with nix-env -iA by user then the package is not erased.

**Comment by Atemu** [comment]
> The packages is in the systemPackages of config file, is this not enough?

That would be enough.

However, if you reference an output path directly via its Nix store path, you still run the risk of it disappearing on you because of updates.

Say you reference win-virtio in your system closure and it evals to `/nix/store/aaa-win-virtio-0.1.196-1`. That path will only stay alive as long as your system closure is alive. If you decide to update a month down the line, the win-virtio derivation will likely have an entirely different hash because at least one of its (transitive) dependencies changed. `/nix/store/bbb-win-virtio-0.1.196-1` for example.  
If the old generation referencing `aaa` was cleaned up using i.e. `--delete-older-than`, there is no longer a root protecting it from being GC'd. `bbb` will still be alive because it's part of your current closure but it too will be freed if you update at some later point.

Output paths are not guaranteed to be stable. Quite the opposite is the case!

The reason it might not be removed in `nix-env` is that you're either not updating it or not removing old generations; thus keeping a GC root on it alive.

You should instead reference a path like `/run/current-system/sw/share/whereveritis/whateveryouwant` instead.

**Comment by pzant** [comment]
@Atemu win-virtio has no link in /run/current-system/sw/ and collect-garbage -d remove uncompressed dir within on version of the package.
The problem is not solved.

**Comment by Atemu** [comment]
I'll gladly help you with your problem but there isn't anything for Nixpkgs to do here because the "issue" is on your end. This is a question, not an issue. That's why I closed this. 

The discourse would be the more appropriate place to discuss this.

You need to explicitly reference win-virtio in your system closure somewhere so that you have a stable path to it rather than a store path.  

Which derivation is the file you need to reference in? What's the concrete content of said derivation?

**Comment by pzant** [comment]
I just want to have the up-to-dated drivers and see when they are updated. Further install if necessary.

**Comment by Atemu** [comment]
I'm afraid you'll have to be more specific than that. I'm not familiar with the package or how it's used.
