### ISSUE TITLE
chromium with enablePepperFlash=true: Flash version bump required

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21169]
## Issue description

https://fpdownload.adobe.com/pub/flashplayer/pdc/23.0.0.207/flash_player_ppapi_linux.x86_64.tar.gz is not available for download, the server returns 404; Current version is 24.0.0.186

### Steps to reproduce

echo "{ chromium = { enablePepperFlash = true; }; }" > ~/.nixpkgs/config
nix-env -i chromium

## Technical details

nixos 16.09.1229.f52eaf4 (Flounder)

**Comment by joachifm** [comment]
See also https://github.com/NixOS/nixpkgs/issues/21119

**Comment by calvertvl** [comment]
Of interest to me is how we can override the plugin derivation, as that is a good way to test that only a version bump is required (and nothing else has changed).

If the usual lib.overrideDerivation works, what name should be used? Nix can't find 'flashplayer-ppapi' which is the name in the file; it seems to me like I'm missing a scope definition.

Further, I expect that because the browser is wrapped (and thus dependent on the derivation), we would have to use the substitution mechanism to override the package (nixos.config.packageOverrides). Once the above question about naming/scope is answered, this probably becomes obvious.

**Comment by joachifm** [comment]
Picked to release at commit decc84b22167391afabac27deecd9dfa6471b595
