### ISSUE TITLE
add init.lua support to neovim 

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#211998]
## Issue description

Neovim now supports both init.lua and init.vim. I would like nixpkgs neovim wrapper pkgs/applications/editors/neovim/wrapper.nix to default to init.lua as the support for lua is now quite good and covers most of vimscript commands. 
What it means in practice:
Next to extraConfig (we want to maintain vimscript support), accept "extraLuaConfig" 
in neovim.passthrough.initRc, use lua instead of vimscript 

I am unlikely to implement this anytime soon so anyone interested feel free to pick it up.

**Comment by emptyflask** [comment]
Home-manager has some lua support -- have a look at https://github.com/nix-community/home-manager/blob/master/modules/programs/neovim.nix

**Comment by lucc** [comment]
@teto I would like to implement this, because I want to use it myself but I am a bit at loss how it all comes together in the neovim derivation and related code.

1. You mention `pkgs/applications/editors/neovim/wrapper.nix`. That file defines a wrapper function for neovim. This wrapper function has an argument `neovimRcContent` that should be a string of vimL which is written to the `init.vim` file that is used to the wrapper.
  Do you want to add an extra argument `neovimLuaRcContent` or do you want to change the semantics of the existing argument from vimL to lua?
2. You mention `extraConfig`. Under `pkgs/applications/editors` there is only one occurrence of this string, in  `pkgs/applications/editors/neovim/build-neovim-plugin.nix` where it is used as in a function argument to override a luarocks derivation. So I assume you meant something else. But what? Maybe `neovimRcContent` from point 1?
3.  I assume that `pkgs.neovim.passthrough.initRc` is set by the wrapper function in  `pkgs/applications/editors/neovim/wrapper.nix`, so changing that to lua should be easy once I know which arguments we want to have where.

Can you shed some light for me here?
