### ISSUE TITLE
oh-my-fish: omf-install fails

### ISSUE THREAD

**Issue by kephas** [NixOS/nixpkgs#212158]
### Describe the bug
omf-install fails because it copies read-only files and directories from the Nix store (and the resulting installation cannot work without modifying the permissions)

### Steps To Reproduce
1. omf-install

### Expected behavior
The installation should suceed.

### Screenshots
```
pierre@force ~> omf-install
Checking for a sane environment...
Installing Oh My Fish to /home/pierre/.local/share/omf...
Writing bootstrap to /home/pierre/.config/fish/conf.d/omf.fish...
Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package default
fatal: could not create work tree dir '/home/pierre/.local/share/omf/pkg/default': Permission denied
Could not install default.
Install aborted: Error installing plugins

Oh My Fish installation failed
```

### Additional context
 ~/.local/share/omf/ files are all without write permission

### Notify maintainers
@AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.153-20432-gaa06ea936644, Debian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.1`
 - channels(pierre): `"nixpkgs"`
 - nixpkgs: `/home/pierre/.nix-defexpr/channels/nixpkgs`
```

**Comment by rengare** [comment]
indeed, adding a `chmod +w -R ~/.local/share/omf`
fixes that

**Comment by kephas** [comment]
What would be the best way to have `omf-install` work out of the box?

**Comment by AndersonTorres** [comment]
Not sure. Maybe patching the original source to deal with the read-only bits.

**Comment by gbirke** [comment]
I looked through the Oh-my-Fish installer code and found the issue: The installer does not set permissions for the user directory after copying the files. I suggested a change to the project, but since this is an edge case that's very Nix specific, changing the package to patch the original source before running the installer might be the better option. 

I don't have the skill set yet to create such a patch for the package, but here are some pointers:

1. Patch the file `$out/share/${finalAttrs.pname}/bin/install` before running it
2. Look for the following lines:
```fish
  # Copy the source into the install location.
  command cp -r "$OFFLINE_PATH" "$OMF_PATH"
    or abort "Failed to copy source!"
```
3. Add the following line(s) after that:
```fish
chmod -R u+w "OMF_PATH"
```

**Comment by AndersonTorres** [comment]
> this is an edge case that's very Nix specific,

I do not believe so. This is just one line.
