### ISSUE TITLE
Acme dependency is not maintained.

### ISSUE THREAD

**Issue by ibrahimsag** [NixOS/nixpkgs#21300]
## Issue description
I've encountered the following error on acme daemons. seems like simp_le is not maintained anymore, and it starting getting this error after a let's encrypt api update.
https://github.com/kuba/simp_le/issues/118 

What would be the path forward? does anyone have any better client alternatives?

**Comment by ibrahimsag** [comment]
@domenkozar @ericsagnes @groxxda @abbradar @fpletz 
apologies, can you help discuss this?

**Comment by abbradar** [comment]
See [this mailing list message](http://lists.science.uu.nl/pipermail/nix-dev/2016-December/022348.html). tl;dr: it is fixed in master but we can't update channels now due to new way Hydra builds packages. You can cherry-pick commit https://github.com/NixOS/nixpkgs/pull/21102/commits/c8c6ff4a96f1216fdb9c1fae6002b12d1b8deacf from [the PR](https://github.com/NixOS/nixpkgs/pull/21102) to get it faster.

**Comment by ibrahimsag** [comment]
Thank you!
