### ISSUE TITLE
rPackages.Rserve does not install library Rserve and cli tools does not start

### ISSUE THREAD

**Issue by behrica** [NixOS/nixpkgs#213007]
### Describe the bug
rPackages.Rserve does not install library Rserve and cli tools does not start

### Steps To Reproduce
1.  nix-shell -p rPackages.Rserve
2. Run "R" in shell
3.  library(Rserve); run.Rserve() fails with  there is no package called ‘Rserve’

The `RServe` command line tolls gets installed by teh packge,
but starting it via `Rserve` fails with
Fatal error: R home directory is not defined

**Comment by TomaSajt** [comment]
You'd also need to also add `R` to the used packages, because `R` contains the setup-hook, which discovers R packages
command: `nix-shell -p R rPackages.Rserve`

This is not specific to `Rserve`

Instead of using `nix-shell -p`, I'd recommend using an environment with `mkShell` (or alternatives), and using either `nix-shell` or `nix develop`
