### ISSUE TITLE
Package request: quiet

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#213678]
**Project description**
A private, p2p and decentralized alternative to Slack & Discord, built on Tor & IPFS.

**Metadata**

* homepage URL: https://tryquiet.org
* source URL: https://github.com/TryQuiet/quiet
* license: gpl3
* platforms: unix, linux, darwin, android, windows

**Comment by AndersonTorres** [comment]
Why are you spamming?

**Comment by sogreatandpowerfull** [comment]
I am looking for some packages but can't seem to find them. Not necessarily spamming; I have already opened a few request issues for these packages.

**Comment by sogreatandpowerfull** [comment]
Though not a good time to package this app right now, since it's in beta/alpha quality.

**Comment by AndersonTorres** [comment]
Given that you have a big list, what about opening one PR and include all your wishes there? I believe it will be easier to track down.

**Comment by Lord-Valen** [comment]
> Given that you have a big list, what about opening one PR and include all your wishes there? I believe it will be easier to track down.

Single issues are bite-sized and more discoverable; hence, the title scheme. From the title we can easily identify the type of issue and (for package requests) the subject package. This makes it very easy to prevent and identify duplicates and for contributors to link PRs. There have already been duplicate requests made because of this decision. Using a list creates an unnecessary burden on the issue author to keep track of which items have been met and which have not in order to mitigate the increased tracking burden on contributors. With a list, contributors are forced to iterate over the list asking the questions: 1. Is this already packaged? 2. Is there a duplicate issue? 3. Is there an open but unlinked pull request? Request lists are plainly more difficult to reason about. I dread to imagine a nixpkgs where everyone submits package request lists which may or may not overlap to an unknown degree. Considering that, I'd rather we reopen this (since quiet now has stable releases) and split https://github.com/NixOS/nixpkgs/issues/61371 into separate issues.

**Comment by AndersonTorres** [comment]
given that the OP ghosted, I believe the listing approach was a better idea instead of the huge spam it generated.
