### ISSUE TITLE
Changing Manual text is awkward

### ISSUE THREAD

**Issue by timfenney** [NixOS/nixpkgs#214989]
## Issue description
The Manual text is present in 2 places. This presents friction:

- a dev must update the text in 2 places, perhaps by a build step
- if a code reviewer suggests text changes, they must be suggested in 2 places, and accepted in 2 places (my last code review had suggestions in 1 place, for which I made corresponding changes in the 2nd)

## Technical details

For example, the Manual sources can be edited in a file such as: `nixos/doc/manual/configuration/config-file.section.md`.
For CI to succeed, corresponding updates must be performed in: `nixos/doc/manual/from_md/configuration/config-file.section.xml`.

## Proposal
CI already builds the xml to sanity check the xml checked in by developers. I propose the CI builds the relevant xml, instead of the developers. The file path to the built xml files can be added to a `.gitignore` so they are not checked in.

**Comment by timfenney** [comment]
@fricklerhandwerk

**Comment by laalsaas** [comment]
the docs are currently in a migration process (xml -> md). That's why you currently have to run `md-to-db.sh`, everytime you update the docs. this won't be necessary soon(tm) when migration is complete (someone told me it's planned before 23.05), and for this time period it's an acceptable workaround.

**Comment by timfenney** [comment]
It seems like there are plans underway to fix this situation. Just a paper cut 🫠
