### ISSUE TITLE
LuaTeX only finds fonts in the last directory of OSFONTDIR

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#215857]
### Describe the bug
I'm trying to build documents with LuaLaTeX in mkDerivation, and setting `OSFONTDIR` so LuaLaTeX can find system fonts. This works if `OSFONTDIR` is set to a single directory, but if multiple directories are set (separated by `:` or `;`) only fonts in the last listed directory are found. 

### Steps To Reproduce
1. Clone my MWE flake [here](https://gist.github.com/lunik1/7a771166e4e22d0de114bf485a3532db)
2. Building as-is means Fira Sans is not found
3. Swapping the order of Libertinus and Fira Sans in `OSFONTDIR` means Libertinus Serif is not found
4. Removing `\setsansfont{Fira Sans}` from `two_system_fonts.tex` and listing Libertinus first in OSFONTDIR still causes Libertinus to not be found
5. ...but listing Libertinus last means the document compiles.

### Expected behavior
LuaLaTeX should find all fonts in every directory listed on the `OSFONTDIR` search path.

...or at least setting it to multiple files should cause no fonts to be found. The fact that the last directory works implies that there is some sort of support for multiple directories. Maybe this is an upstream bug?

### Additional context
I know that in the example above both fonts are distributed by texlive so installing them as a system font is not necessary, I just picked them for demonstrational purposes.

An alternative would be to use fontspec, but I didn't have any luck getting LuaLaTeX to respect `FONTCONFIG_FILE`.

### Notify maintainers
@veprbl 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10-zen2, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos-21.11.337899.3aad50c30c8"`
 - channels(corin): `"nixos-22.11pre387075.e1e08fe28bf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ehwat** [comment]
kpathsea only decends into subdirectories¹ when recursion is requested by suffixing the path with `//`.  It happens to recurse into the last directory in `$OSFONTDIR` because it acually searches in the  paths specified via the `OPENTYPEFONTS` option, which defaults to 
`$TEXMFDOTDIR;$TEXMF/fonts/{opentype,truetype}//;$OSFONTDIR//`.

Using `builtins.concatStringsSep "://"` should work.

[1] As a sidenote, kpathsea has the amazing feature to only recurse into symlinked directories when they also have "real" sibling directories. The rationale was that in the 80s this could measurably improve performance since checking for real subdirectories is cheaper (one checks whether `st_nlink` in `stat(2)` is larger than 2.). Surely this does not cause any problems in nixpkgs, right?

**Comment by lunik1** [comment]
Yes, using `"//:"` works. Thanks, was pulling my hair out over this one!

**Comment by lunik1** [comment]
> [1] As a sidenote, kpathsea has the amazing feature to only recurse into symlinked directories when they also have "real" sibling directories. The rationale was that in the 80s this could measurably improve performance since checking for real subdirectories is cheaper (one checks whether `st_nlink` in `stat(2)` is larger than 2.). Surely this does not cause any problems in nixpkgs, right?

Huh, I think this might be behind another issue I was having where font families installed via texlive weren't working. Fortunately the paths were the (o|t)tf files are located is pretty predictable, so you can add them to `OSFONTDIR` and not have to rely on recursive search.
