### ISSUE TITLE
Caddy: Caddyfile input is not formatted

### ISSUE THREAD

**Issue by M-arcus** [NixOS/nixpkgs#216149]
### Describe the bug
Caddy fails building & starting, citing: 
`> Error: /nix/store/h97ybha4a6yryrpa1pcb9lgxyv6bad6w-Caddyfile:1: Caddyfile input is not formatted`

### Steps To Reproduce
1. Build and start caddy 

### Expected behavior
Build & Startup doesn't fail

### Screenshots
![image](https://user-images.githubusercontent.com/25648755/218440794-24095150-fe88-42e6-bb1a-a52d893748fe.png)

Content of the file 
![image](https://user-images.githubusercontent.com/25648755/218440918-fb6a2299-99b0-4046-a0fd-a32637155099.png)

### Additional context
Reverting to an older version works:
![image](https://user-images.githubusercontent.com/25648755/218441051-9b83c9c7-7147-49b2-814b-a3d7db1eee5a.png)

### Metadata
```
$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):
  /nix/store/1dqwviwjk1ncjrqgnfk1gx67i6fg9xz2-DarwinTools-1
  /nix/store/cdg9xx3p8s2bl3gsfg0yycq6d5r6b0gb-nix-info
copying path '/nix/store/1dqwviwjk1ncjrqgnfk1gx67i6fg9xz2-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/cdg9xx3p8s2bl3gsfg0yycq6d5r6b0gb-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

**Comment by domenkozar** [comment]
Likely fixed by https://github.com/NixOS/nixpkgs/pull/215369

**Comment by M-arcus** [comment]
Error does not appear anymore, after updating to newest versions

**Comment by IndeedNotJames** [comment]
Being the author of #215369, could I have done something differently, so this wouldn't have happened?

That error was would I would describe as pretty self-contained.
It was introduced in that PR and fixed in another commit in the very same PR. (the final commit dates were just 5 minutes apart (due to a lot of rebasing)).

**Comment by IndeedNotJames** [comment]
@halictuz that is a different issue.
Similar, yes, but the context differs.
OP ran into an error of the nixos module (which is used by the package tests).

You on the other hand, are encountering a runtime warning, not an error.
Please refer to the official cli documentation at https://caddyserver.com/docs/command-line#caddy-fmt

You want to use `caddy fmt --overwrite`

Your issue is not specific to v2.6.3
