### ISSUE TITLE
Use different license in documentation/manual

### ISSUE THREAD

**Issue by efferifick** [NixOS/nixpkgs#21623]
Hello,

I am trying to print this document https://nixos.org/releases/nix/nix-1.11.5/manual.pdf . Because it is copyrighted, my local printer correctly refuses to print it. Could it be possible to change the license of the manual to allow people to print a personal copy to read offline?

Thanks

**Comment by vyp** [comment]
What do you mean your printer refuses to print it?? I thought Nix along with the manuals are released under the LGPL so you are allowed to make copies.

**Comment by Mic92** [comment]
the printer probably does not understand LGPL, but found a copyright tag.

**Comment by vyp** [comment]
Even if it has a copyright tag, that doesn't necessarily mean all rights were reserved. Or even if they were, you could have specifically got permission to make a copy... I think it's pretty stupid for a printer to refuse to print because of something like a copyright tag... what if ***you're** the copyright holder??? What printer is it?

Anyway, look into using using pdftk or qpdf or something to slice out pages from a pdf.

**Comment by efferifick** [comment]
@Mic92 I meant the printer station at the university. It is managed by people and the people are the ones refusing, not the hardware printer.

@vyp Yes, they did mention that they would print it if I got permission to make a copy. I think because the license is not stated on the pdf, the people refused to print it. I guess I can print it myself but I just wanted to point out that explicitly mentioning the license in the manual could be a good idea. 

I'll close the ticket now.

**Comment by vyp** [comment]
Ahhh understood!

But still, educate them! On page 4 it says that it's released under the LGPL. And remember the source for the manuals are in the source repositories so COPYING files of the repositories apply (unless stated otherwise). Don't give in to printing yourself, insist on it. If they refuse to print for another reason, okay, but don't take copyright as a reason.

Don't be sorry!

**Comment by vcunat** [comment]
Well, all software licenses are done via a copyright.  On the contrary, specifying no license means that people basically have no right to do anything with it...
