### ISSUE TITLE
Blockers for dropping the unsupported LibreSSL 3.4

### ISSUE THREAD

**Issue by ruuda** [NixOS/nixpkgs#216207]
### Describe the bug

LibreSSL 3.4 is no longer supported upstream. It became unsupported on October 14th 2022, one year after [the corresponding OpenBSD release](https://www.openbsd.org/70.html). At the time of writing, 3.5 and 3.6 are both supported. [Both branches recently had a security update](https://github.com/NixOS/nixpkgs/pull/216202) that fixes a serious vulnerability:

> A malicious certificate revocation list or timestamp response token would allow an attacker to read arbitrary memory.

I suspect (but haven’t verified) that this vulnerability is present in LibreSSL 3.4. It is time to remove it from Nixpkgs. However, there are some packages that still depend on it.

### FoundationDB

`foundationdb{52,52,60,61}` all depend on `libressl_3_4`. I tried building `foundationdb61` against `libressl_3_5` and `libressl_3_6`, but both fail. I don’t see any packages that depend on `foundationdb`, so I think we could remove the older versions, if we can first update FoundationDB to a version that is compatible with a more recent LibreSSL release. Maybe #215336 will be sufficient for this.

Alternatively, we might patch FoundationDB. The compilation errors are about an incomplete type for which only a forward declaration is known. I haven’t looked into it deeply but it may be easy to fix.

@thoughtpolice, @lostnet, as the maintainers of `foundationdb`, what are your thoughts on this?

### <del>ovftool</del>

This has been addressed by #214663.

<details>
<summary>Original comment</summary>

The other package that explicitly depends on LibreSSL 3.4 is `ovftool`. This is a proprietary package so I couldn’t test if it is compatible with a more recent LibreSSL release, it might actually be.

@numinit, @WolfangAukang, as the maintainers of `ovftool`, could you try and see if it is compatible with a newer LibreSSL release?

</details>

**Comment by botovq** [comment]
The x.400 issue that was patched recently is present in LibreSSL 3.4. The fix is very small and applies to all older versions that have it, so it might be an option [patch it][1] while you sort out the other issues.

If you could share build logs for the foundationdb I could take a look if you want.

[1]: https://github.com/openbsd/src/commit/dbc8ff32ddf2c685f4e9a42b3f890b85c5992d68

**Comment by numinit** [comment]
You can drop this. #214663 uses their bundled OpenSSL and drops the dependency. It's about to merge.

**Comment by happysalada** [comment]
all of darwin depends on 3_4 at the moment.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/network_cmds/default.nix

@ajs124 You've pinned to 3.4, do you know if by any chance we can upgrade to 3.5 ?
maybe @matthewbauer ?

**Comment by ajs124** [comment]
I'm quite sure we can't. My history with that package is 49c51cdd516d51e3ebbb7930e5edb4174c25a0fa and f76d71f98f8b070f638a9ce8df3ec923deb7fd28. f76d71f98f8b070f638a9ce8df3ec923deb7fd28 happened, because someone did 36b5da498ce5634390eae97f43b09d942f6cb285.

iirc 36b5da498ce5634390eae97f43b09d942f6cb285 happened, because this package depends on ancient long unsupported openssl APIs that weren't part of `openssl_1_1` anymore.

**Comment by happysalada** [comment]
Small rectification, after a bit more testing, it doesn't appear to be all of darwin that is impacted by that change.
So perhaps we don't need to put too much effort into this.
I'm still trying to figure out the impact.

**Comment by reckenrode** [comment]
I’m working on a fix for #223977, which drops the dependency on `libressl_3_4` from `darwin.network_cmds` by unconditionally dropping Unbound from the build (instead of only on aarch64-darwin). Apple doesn’t even include Unbound in macOS anymore, and it’s not present in newer source releases. That should remove `darwin.network_cmds` as a blocker for dropping LibreSSL 3.4.
