### ISSUE TITLE
Vaultwarden admin panel can't read server version

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#216409]
### Describe the bug
Vaultwarden is able to retrieve the latest version of the software but unable to determine its own version.
This does however work for the web vault.

### Steps To Reproduce
Go to https://your-vaultwarden-instance/admin/diagnostics.

### Screenshots
![screenshot](https://user-images.githubusercontent.com/6806011/218897973-9843440d-742c-4247-81d4-862b76e2c8ab.png)

### Notify maintainers
@msteen @ivan

**Comment by RRvW** [comment]
This is due to vaultwarden getting it's version information from the  `VW_VERSION` env variable during build, which is somehow unset on Nixpkgs. It also causes the mobile clients to crash, as they depend on that information for feature detection, see https://github.com/dani-garcia/vaultwarden/discussions/3996
Should be fixed in next vaultwarden release, but as a workaround you can use overrideAttrs to inject the variable: 
```
vaultwarden.overrideAttrs (final: prev: {VW_VERSION = "prev.version";  } )
```

**Comment by dotlambda** [comment]
Do you want to submit that workaround as a PR? I guess it won't be needed anymore to make mobile clients work but it would still fix the admin panel I assume?

**Comment by Sohalt** [comment]
>Should be fixed in next vaultwarden release, but as a workaround you can use overrideAttrs to inject the variable:

I still needed the workaround in nixos 23.11 with vaultwarden 1.30.1.
