### ISSUE TITLE
vscode: eamodio.gitlens can't load icons

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#218031]
### Describe the bug
In VSCode (and Codium), the extension `eamodio.gitlens` is unable to load icons, and uses generic rectangles instead.
Opening VSCode/Codium with `--verbose` shows:
```
vscode-file: Refused to load resource /nix/store/wls3y80nfld9hln166zw0b1rhssj5wyk-vscode-extension-eamodio-gitlens-2022.12.604/share/vscode/extensions/eamodio.gitlens/dist/glicons.woff2 from vscode-file: protocol (original URL: vscode-file://vscode-app/nix/store/wls3y80nfld9hln166zw0b1rhssj5wyk-vscode-extension-eamodio-gitlens-2022.12.604/share/vscode/extensions/eamodio.gitlens/dist/glicons.woff2)
```

### Steps To Reproduce
1. `nix-shell -p "vscode-with-extensions.override {vscodeExtensions = [vscode-extensions.eamodio.gitlens];}"`
2. Open `code`.
3. You can see that what are supposed to be GitLens icons are rectangles instead.

### Expected behavior
GitLens should load the icons correctly.

### Screenshots
EDIT: Instead of rectangles, the icons are invisible now.

![image](https://user-images.githubusercontent.com/40663462/221197829-4b01fbdb-a208-49f1-b9ca-2908f32ea2c3.png)
![image](https://user-images.githubusercontent.com/40663462/221198068-8e847aef-c77f-4918-8544-056fe9d5c504.png)

### Additional context
Bug also happens with the extension fetched from https://github.com/nix-community/nix-vscode-extensions (both from vscode-marketplace and open-vsx).

The bug doesn't reproduce with `vscode-fhs`.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12-zen1, NixOS, 23.05 (Stoat), 23.05.20230223.03fb722`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by CedricFinance** [comment]
VScode only allows files to be loaded from certain root folders ([source](https://github.com/microsoft/vscode/blob/main/src/vs/platform/protocol/electron-main/protocolMainService.ts#L36)).

```
// Define an initial set of roots we allow loading from
// - appRoot	: all files installed as part of the app
// - extensions : all files shipped from extensions
// - storage    : all files in global and workspace storage (https://github.com/microsoft/vscode/issues/116735)
```

On NixOS, the extensionsDir is in the Nix store with links to the different extensions (also in the Nix store).

This issue is that the extensions tries to load the file from the extension's folder directly (`/nix/store/wls3y80nfld9hln166zw0b1rhssj5wyk-vscode-extension-eamodio-gitlens-2022.12.604`) and not from the extensions folder (something like `/nix/store/xxxxx-vscode-extensions`).

If the path of the font is `/nix/store/xxxxx-vscode-extensions/share/vscode/extensions/eamodio.gitlens/dist/glicons.woff2`, it should work (`/nix/store/xxxxx-vscode-extensions` must be in the authorised folders whereas `/nix/store/wls3y80nfld9hln166zw0b1rhssj5wyk-vscode-extension-eamodio-gitlens-2022.12.604` isn't).

**Comment by ranuwp** [comment]
Facing this until today. Anyone has workaround for this issue?

**Comment by katexochen** [comment]
@CedricFinance thanks for the research! Do you think this is something we can patch in our packaging? Or does it require an upstream fix?

**Comment by Quoteme** [comment]
I researched into this as well. I am not really sure how @CedricFinance came to his conclusion, that the problem stems from vscode/vscodium not having permissions to load icons from specific places, if I understood him correctly. Neither do I know how we could test this hypothesis.

What I noticed, however, is that the `github.copilot` extension has the same problem:

| Figure 1 |
|---|
| ![image](https://github.com/NixOS/nixpkgs/assets/6796009/84d409ef-1b69-4f30-a572-13053d93a3fa) |
| Missing GitHub-Copilot Icon|

Furthermore, if I go into my `/nix/store/XXXXX-vscode-extensions/share/vscode/extensions/` folder and issues the command `rg "\"icons\": \{" --max-columns=100 --max-columns-preview=10 ./*`, I get the following output:

```
./vscjava.vscode-spring-boot-dashboard/package.json
30:    "icons": {

./github.copilot/package.json
304:		"icons": {

./eamodio.gitlens/package.json
7665:		"icons": {
```

Not sure about the spring-boot-dashboard extension, but it seems like extensions which define this attribute in their `package.json` cannot load their icons.
