### ISSUE TITLE
Package request: Maintain poetry2nix within nixpkgs

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#219087]
It would be good if this were part of nixpkgs itself, rather than [maintained separately](https://github.com/NixOS/nixpkgs/blob/10e51cdc0456f1d5c8a00f026c384f0e81126538/pkgs/development/tools/poetry2nix/poetry2nix/README.md), to make sure it keeps working with newer Python packages and doesn't require a separate release process. More people would also be able to contribute directly.

**Project description**

From the [web site](https://github.com/nix-community/poetry2nix/): poetry2nix turns [Poetry](https://python-poetry.org/) projects into Nix derivations without the need to actually write Nix expressions. It does so by parsing pyproject.toml and poetry.lock and converting them to Nix derivations on the fly.

**Metadata**

* homepage URL: https://github.com/nix-community/poetry2nix/
* source URL: https://github.com/nix-community/poetry2nix/
* license: MIT
* platforms: Any

**Comment by Shawn8901** [comment]
isnt this what you are requesting? https://github.com/NixOS/nixpkgs/tree/10e51cdc0456f1d5c8a00f026c384f0e81126538/pkgs/development/tools/poetry2nix/poetry2nix

**Comment by l0b0** [comment]
@Shawn8901 No, I've clarified the initial comment.

**Comment by SuperSandro2000** [comment]
We shouldn't do that because:
- the code contains parts of (semi-)auto generated code and meta information about old releases and python versions. In nixpkgs we only support the two latest python versions and definitely not old package releases where it makes no sense (my favorite example cryptography)
- the project encourages vendoring through lock files which is the opposite of what a distro tries to achieve and promotes outdated and insecure dependency versions (eg cryptography)
- potential use of IFD which is banned in nixpkgs
- disagreements between the developer and the python maintainers
- disinterest and discouragement by the python maintainers to co-maintain it and use it within nixpkgs 

I am against moving the development.

**Comment by adisbladis** [comment]
> the project encourages vendoring through lock files which is the opposite of what a distro tries to achieve and promotes outdated and insecure dependency versions (eg cryptography)

Citation needed. There are plenty of people in the community who would prefer that packages lock their own Python dependencies.
The current crop of Python maintainers in nixpkgs has completely steamrolled anyone who opposes them so this set of people mostly keep quiet.

> potential use of IFD which is banned in nixpkgs

This is patently untrue FUD. Poetry2nix does not use IFD.

> My wish would be to remove that vendored directory. In their own repo the developers can do whatever them pleases but encouraging such a vendoring style in nixpkgs is unproductive and shouldn't get popular

This needs way more elaboration. If we're talking about unproductive approaches look no further than python-packages.nix and it's manual maintenance.

---

I'm also against moving development, but I would still like to see _more_ use of poetry2nix and similar solutions in nixpkgs, but instead we massively waste peoples time manually hacking up expressions and maintaining a set which will never be 100% mutually compatible instead of using tools that eliminate boilerplate and repetition.

Nixpkgs just isn't suited for developing these things because of workflow issues (good luck running the poetry2nix CI as a part of nixpkgs).

**Comment by SuperSandro2000** [comment]
> Citation needed.

The last 3 discussions we had in the python nixos matrix chat about that.

> There are plenty of people in the community who would prefer that packages lock their own Python dependencies.

This would create the same problem Golang and rust and potentially others ecosystems have: for a distro unfixable security issues. See #141368 for an example which is only a problem because of vendoring and realistically cannot be fixed unless we vendoring is broken.

From my experience Python developers do not create high quality lock files and update them in a timely manner, often lacking multiple months if not a year behind. Also for biennial issues, often caused by tests which assert literal string outputs, dependencies get pinned to old versions not temporarily, but for a long time and that is somehow an accepted fix. Also some pinning is a none issue for nixpkgs like that cryptography requires rust to build since a good amount of time and some people still pin it to before that.

> This needs way more elaboration.

For every change in poetry2nix we need to take a d-tour over upstream and then update vendoring. This is not ideal for projects that live so close together.
