### ISSUE TITLE
nixos-unstable: console.font reset to default font at end of boot

### ISSUE THREAD

**Issue by kindrowboat** [NixOS/nixpkgs#219239]
### Describe the bug
My laptop has an HDPI monitor, so I set a larger font to help with eye-strain.
```
  console = {
    earlySetup = true;
    font = "${pkgs.terminus_font}/share/consolefonts/ter-132n.psf.gz";
    packages = with pkgs; [ terminus_font ];
    keyMap = "us";
  };
```

This has worked in the past, but after a recent upgrade, I see the font get set for a brief second, but then it gets set back to the default smaller font. If I run `sudo systemctl restart systemd-vconsole-setup.service` after start-up, the font does get set properly, so I think something else must be running afterwards to reset it.

### Steps To Reproduce
1. Add to nix configuration:
  ```
   console = {
    earlySetup = true;
    font = "${pkgs.terminus_font}/share/consolefonts/ter-132n.psf.gz";
    packages = with pkgs; [ terminus_font ];
    keyMap = "us";
  };
  ```
2. Run `sudo nixos-rebuild switch`
3. Restart computer
4. Notice font start small, get large, and then get small again

### Expected behavior
Font starts small during boot, changes to the larger set font, and stays that size.

### Screenshots
![output1_6](https://user-images.githubusercontent.com/777773/222568656-6edbd52e-56ee-485b-bb9e-82554bf0a643.gif)

![output2](https://user-images.githubusercontent.com/777773/222568763-32c4f0e2-f8b5-47cb-b6e8-833a1eb0ae71.gif)

### Additional context
This was working as expected before an upgrade.

### Notify maintainers
@lilyinstarlight

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
kindrobot@framework2 ~/w/nix-config (main)> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.1, NixOS, 23.05 (Stoat), 23.05.20230228.68196a6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lilyinstarlight** [comment]
What video driver do you use, if it i915 (intel iGPU)?

Also are you using default stage-1 or experimental systemd-stage-1?

**Comment by lilyinstarlight** [comment]
Oh I see you have videos now. Yeah I think you don't have i915 in the initrd and vconsole setting from udev can race driver load (since driver load resets the fbcon without rerunning the udev rule)

Are you using the https://github.com/NixOS/nixos-hardware module for your framework laptop?

**Comment by kindrowboat** [comment]
> What video driver do you use

I'm setting `"i915.enable_psr=0"`. I'm not sure which driver that ends up loading.

> Also are you using default stage-1 or experimental systemd-stage-1?

I _think_ I'm using the default stage-1. I haven't enabled the experimental systemd-stage-1.

> Are you using the https://github.com/NixOS/nixos-hardware module for your framework laptop?

I'm not but, I am borrowing inspiration from it. My config can be seen here: https://git.kindrobot.ca/kindrobot/nix-config/src/commit/cc3dfadcfc9ead39e81def71e9efbdda5f0254c1/box/framework2.nix

> Yeah I think you don't have i915 in the initrd

Ah, OK. I'll try switching `"i915.enable_psr=0"` to `"i915.enable_psr=1"` and see if that makes a difference.

**Comment by lilyinstarlight** [comment]
That kernel param shouldn't change anything wrt initrd, but it looks like you missed `boot.initrd.kernelModules = [ "i915" ]` when copying from nixos-hardware (see [`common/gpu/intel/default.nix`](https://github.com/NixOS/nixos-hardware/blob/77de4cd09db4dbee9551ed2853cfcf113d7dc5ce/common/gpu/intel/default.nix) which gets (indirectly) imported by the framework module)

Does adding that help?

**Comment by kindrowboat** [comment]
Ah yes! Well, I just bit the bullet and switched over to nixos-hardware, and it's working. Thank you for your help!

**Comment by cx405** [comment]
@kindrowboat You need to request your videocard driver to be force-loaded, just like @lilyinstarlight  mentioned. 
If driver is packed into initramfs ("m") during kernel build, it stays domant, until something requests it. 
If its built in kernel, it usually automatically loads - but there is still no warrantly  (initcall_blacklist=acpi_cpufreq_init blacklisting, because acpi_cpufreq being preferred over amd_pstate, for example). 

Either way, when Xorg/Wayland start, - if they detect the "better" driver, that causes its activation in kernel, that clears the videoram, which contains font changes.

To solve this problem you need at least first line to activate the driver during early kernel start:
```
boot.initrd.kernelModules=["i915"]
services.xserver.videoDrivers=["intel"]
```
Thus when Xorg/Wayland start, there will be no need to reload the video driver and font change stays.

Xorg can sometimes have [more than one driver for same card ](https://wiki.archlinux.org/title/xorg)(AMD{amdgpu,ati}, Nvidia {nv, nouveau}), but for intel there is only one - so in your case second line (xserver.videoDrivers) is not really needed.

I realise that you have marked this case as completed, but perhaps, this could be useful for somebody in the future.

**Comment by lilyinstarlight** [comment]
> I realise that you have marked this case as completed, but perhaps, this could be useful for somebody in the future.

Just to add more info to this thread so that it exists somewhere, I actually had to also add `  boot.kernelParams = [ "i915.fastboot=1" ];` to my config to consistently avoid it, because my computer was still too fast and sometimes the vconsole-setup udev hook beat i915 in the init race and left me with a broken font until initrd pivoted to system root and the hook ran again

**Comment by AkechiShiro** [comment]
I'm hitting the same issue but inside a QEMU VM, is there any way to fix it ? Since using drivers for the GPU, I'm not sure what kind of drivers I should add ? i915 ?

**Comment by fadenb** [comment]
For reference, I experienced the same issue on a Thinkpad T14s using the `amdgpu` driver.
Adding `boot.initrd.kernelModules = [ "amdgpu" ];` to my config fixed the issue for me.
