### ISSUE TITLE
haskell: separate "essential" overrides from version overrides

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#22052]
### Problem

When defining your own package sets as an alternative to `hackage-packages.nix`, it would be nice to re-use `configuration-common.nix` for this package set. However, this is currently difficult due to `configuration-common.nix` also containing overrides of versions of specific packages or changing build flags and so on.

### Solution

I would like to propose that `configuration-common.nix` should only contain overrides of one of the follow kinds:

* Nix-specific configure flags that are needed to find native library dependencies in the nix store
* Disabling test suites that rely on functionality not available in the nix sandbox (network, ...)
* Something else that is essential for *every* package set that I forgot here?

I suggest to move the remaining overrides to `configuration-hackage.nix`. What do you think?

/cc @peti

**Comment by peti** [comment]
I think that's a good idea in principle. I'm not fond of the name `configuration-hackage.nix` because it offers no clue as for what the difference is between it and `configuration-common.nix`. This distinction will work in practice only if contributors "get it", so IMHO it's import to have clear documentation, guidelines, and names.

**Comment by bennofs** [comment]
This is fixed on master with the configuration-nix/common split.
