### ISSUE TITLE
No in-build execution for CMake managed builds

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#22060]
## Issue description
I try to migrate a library written in C++ build via CMake to Nix. The test executables also written in C++ are part of this project. CMake allows in-build execution (and therefor in-build testing), because it sets the RPATH for the build executable.

Nixpkgs skips adding this RPATH by setting [CMAKE_SKIP_BUILD_RPATH`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/cmake/setup-hook.sh#L52). This behavior breaks the possibility to test the library or call built executables during build.

### Workarounds
* Expand LD_LIBRARY_PATH; Following command gives an overview how many derivations tackle this issue.
`.../nixpkgs $ git grep -E "LD_LIBRARY_PATH.*pwd"`
* Install before checking/install project before checking/testing

## Proposal
The canonical behavior of CMake should be preserved and CMAKE_SKIP_BUILD_RPATH should not be set.

What do you think about this issue?

**Comment by cpages** [comment]
That behavior is a bit annoying, but there is a reason CMAKE_SKIP_BUILD_RPATH is set, as is explained on the comment above the line you referred. Specifically, cmake clears the rpath after the build if the SKIP option is not set, breaking all the dependencies that are set by nix.

So it's not as easy as just not setting that flag. Did you have a specific solution in mind?

**Comment by ck3d** [comment]
Only if CMake would use RPATH for local and RUNPATH for global dependencies. But CMake uses put all the dependencies into RUNPATH.

No I have no solution.
I think we should document the limitation.

**Comment by globin** [comment]
cc @viric

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by bjornfor** [comment]
I dug in the nixpkgs tree and found that some packages actually set -DCMAKE_SKIP_BUILD_RPATH=OFF, to reverse the effect of the setup hook and be able to run binaries from the build tree.

Digging a bit more I found that -DCMAKE_SKIP_BUILD_RPATH=ON was added in 2009. Commit f3c23487a2c8a09b7f77bf32e2c1ef7a7276414b added it to the cmake setup hook after it having been manually set in a few packages earlier that year.

In 2016 an attempt was made to change from -DCMAKE_SKIP_BUILD_RPATH=ON to -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE, but it was reverted due to a blocking darwin issue: d5d4606190fc951b421e2bbd47585b99c46bf6bf. I'm not sure that commit would have fixed _this_ issue, but the discussion that lead up the the revert is worth a read:https://github.com/nixos/nixpkgs/issues/15881.

After that revert, -DCMAKE_SKIP_BUILD_RPATH=OFF popped up in various package to workaround this issue.

I wonder if we could try removing it again, possibly only for Linux?

**Comment by knedlsepp** [comment]
> I dug in the nixpkgs tree and found that some packages actually set -DCMAKE_SKIP_BUILD_RPATH=OFF, to reverse the effect of the setup hook and be able to run binaries from the build tree.
> 
> Digging a bit more I found that -DCMAKE_SKIP_BUILD_RPATH=ON was added in 2009. Commit [f3c2348](https://github.com/NixOS/nixpkgs/commit/f3c23487a2c8a09b7f77bf32e2c1ef7a7276414b) added it to the cmake setup hook after it having been manually set in a few packages earlier that year.
> 
> In 2016 an attempt was made to change from -DCMAKE_SKIP_BUILD_RPATH=ON to -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE, but it was reverted due to a blocking darwin issue: [d5d4606](https://github.com/NixOS/nixpkgs/commit/d5d4606190fc951b421e2bbd47585b99c46bf6bf). I'm not sure that commit would have fixed _this_ issue, but the discussion that lead up the the revert is worth a read:#15881.
> 
> After that revert, -DCMAKE_SKIP_BUILD_RPATH=OFF popped up in various package to workaround this issue.
> 
> I wonder if we could try removing it again, possibly only for Linux?

I'd highly appreciate that. I've had the same issue too. 😀

**Comment by knedlsepp** [comment]
Still important to me.

**Comment by knedlsepp** [comment]
@LnL7 As this bit me again today while developing on a project, I'm wondering if you could help with fixing this issue. The previous attempt to fix this failed because of some issues [on darwin](https://github.com/NixOS/nixpkgs/commit/d5d4606190fc951b421e2bbd47585b99c46bf6bf), so you seem like the perfect person to fix this (being both maintainer of `cmake` and a top darwin contributor)

**Comment by Artturin** [comment]
pr merged

**Comment by Artturin** [comment]
can someone add a section to @jtojnar's  https://github.com/jtojnar/cmake-snips on how to fix this without 
`"-DCMAKE_SKIP_BUILD_RPATH=ON"` workaround

https://github.com/NixOS/nixpkgs/pull/181243
https://github.com/NixOS/nixpkgs/pull/181540

example of a error

https://hydra.nixos.org/build/183517097/log
https://github.com/SIPp/sipp/blob/f44d0cf5dec0013eff8fd7b4da885d455aa82e0e/CMakeLists.txt#L125

```
Install the project...
-- Install configuration: "Release"
-- Installing: /nix/store/wm6dndxvsnsxfv95dm3vgg7jm6b1vkzi-sipp-3.6.1/bin/sipp
CMake Error at cmake_install.cmake:55 (file):
  file RPATH_CHANGE could not write new RPATH:

    

  to the file:

    /nix/store/wm6dndxvsnsxfv95dm3vgg7jm6b1vkzi-sipp-3.6.1/bin/sipp

  The current RUNPATH is:

    /nix/store/wm6dndxvsnsxfv95dm3vgg7jm6b1vkzi-sipp-3.6.1/lib64:/nix/store/wm6dndxvsnsxfv95dm3vgg7jm6b1vkzi-sipp-3.6.1/lib:/nix/store/pkv4ngqc7arfqpr1bsn1bappvms9xbfg-ncurses-6.3-p20220507/lib:/nix/store/ff98lqrrlndgcai7hjrw50pjgdfmnixr-libpcap-1.10.1/lib:/nix/store/c8fc7saagp0vm5ll5mccpfnhg957pfya-openssl-1.1.1q/lib:/nix/store/x4h0a3mv3mw2sv3j2ysrl4wsacfrg7kq-lksctp-tools-1.0.17/lib:/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib:/nix/store/xjmm9xg5sq47q63cbf447qalz9fmwp0v-gcc-11.3.0-lib/lib

  which does not contain:

    /var/empty/local/lib:

  as was expected.


make: *** [Makefile:100: install] Error 1

```

**Comment by lopsided98** [comment]
What actually is the root cause of the `# RPATH of binary ... contains a forbidden reference to /build/` error? I can't seem to find any examples where that has been without setting `-DCMAKE_SKIP_BUILD_RPATH=ON`.

**Comment by bjornfor** [comment]
> What actually is the root cause of the `# RPATH of binary ... contains a forbidden reference to /build/` error? I can't seem to find any examples where that has been fixed without setting `-DCMAKE_SKIP_BUILD_RPATH=ON`.

AFAIK, it's due to bad cmake code in upstream projects. If the cmake code installs binaries with `install(FILES ...)` or `install(DIRECTORY ...)`, instead of the proper `install(TARGETS ...)`, then cmake will not fixup the rpath in the binaries inside the install tree. The nixpkgs setup-hook [audit-tmpdir.sh](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/audit-tmpdir.sh) then detects the bad rpath reference and emits `RPATH of binary $i contains a forbidden reference to $TMPDIR/"`.
