### ISSUE TITLE
Package request: slskd

### ISSUE THREAD

**Issue by 6e6f61** [NixOS/nixpkgs#220774]
**Project description**

**slskd** is a [SoulSeek](https://www.slsknet.org) daemon and web ui.

**Metadata**

* homepage URL: https://github.com/slskd/slskd
* source URL: https://github.com/slskd/slskd
* license: AGPL-3.0
* platforms: linux, darwin

**Comment by turlando** [comment]
I started to package slskd. It's far from done, and it would be my first contribution to nixpkgs, so it's taking more than it should.

[This is what I've done so far](https://gist.github.com/turlando/9604cb242cc49161143e39f2f7a893e8). This is coming from my local nix host configuration. I don't think I have more time for today. I will try to integrate that into nixpkgs and write a nixos module as well in the future.

Right now I'm stuck at building the frontend. Running `% nix-build -E "with import <nixpkgs> {}; callPackage ./web.nix {}"` I get

```
npm WARN ERESOLVE overriding peer dependency                       
npm WARN While resolving: craco-less@2.0.0
npm WARN Found: @craco/craco@7.0.0                                                                                                                                           
npm WARN node_modules/@craco/craco                                                    
npm WARN   dev @craco/craco@"^7.0.0" from the root project
npm WARN   1 more (@semantic-ui-react/craco-less)                                                                                                                            
npm WARN                                                                                                                                                                     
npm WARN Could not resolve dependency:                                                                                                                                       
npm WARN peer @craco/craco@"^7.0.0" from @semantic-ui-react/craco-less@3.0.0                                                                                                 
npm WARN node_modules/@semantic-ui-react/craco-less
npm WARN   dev @semantic-ui-react/craco-less@"^3.0.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: craco-less@2.0.0
npm WARN Found: peer @craco/craco@"^6.0.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @craco/craco@"^6.0.0" from the root project
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/@craco%2fcraco failed: cache mode is 'only-if-cached' but no cached response is available.
```

I think it's due to #223964, but I don't have more time now to dig further. Any help would be appreciated.

**Comment by aopom** [comment]
I got a working package [here](https://framagit.org/ppom/nixos/-/tree/main/pkgs/slskd), and I'm working on the module as well. I'll try to propose a PR in a few days!

**Comment by aopom** [comment]
I got a working module [here](https://framagit.org/ppom/nixos/-/tree/master/modules/common/slskd.nix), I'll open a PR in the following days.

**Comment by Atemu** [comment]
I presume this can be closed due to https://github.com/NixOS/nixpkgs/pull/227059?

**Comment by 6e6f61** [comment]
lgtm :) thanks
