### ISSUE TITLE
nixos/restic: rcloneConfig not applied if there is no rcloneConfigFile

### ISSUE THREAD

**Issue by jboynyc** [NixOS/nixpkgs#220869]
### Describe the bug

When using rclone with the restic service and providing the rclone configuration via `rcloneConfig`, it is not applied. See this [forum post](https://discourse.nixos.org/t/trying-to-get-backups-working-with-a-webdav-remote-using-restic-rclone/26246) providing an example of the issue.

### Steps To Reproduce

1. enable the restic service, set an rclone repository, and configure rclone via `rcloneConfig`
2. enable the configuration
3. try to run the restic backup

### Expected behavior

The backup should run, using the rclone repository.

Instead, the backup fails after the service emits this message:

`NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
`
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.99, NixOS, 22.11 (Raccoon), 22.11.3042.5eb98948b66`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11-small"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by IndeedNotJames** [comment]
`services.restic.backups.<name>.rcloneConfig` uses environment variables, not `.config/rclone/rclone.conf`.
So that notice (not error) you shared shouldn't matter -- like at all.

You can either read the implementation or look at `systemctl cat restic-backups-varlib.service` (assuming your backup is called `varlib`, just like you posted in your forum post) to see those environment vars.

If I had to guess, I would say you didn't [`rclone obscure`](https://rclone.org/commands/rclone_obscure/)-ed your password before.
`rclone` then de-`obscure`-ed your password wrong, which lead to http/401.

You also probably don't want to set your secrets in `rcloneConfig` anyway, because those end up world-readable in `/nix/store/`.

Excerpt from the `rcloneConfig` option description:
> [...] Warning: Secrets set in here will be world-readable in the Nix store! Consider using the `rcloneConfigFile` option instead to specify secret values separately. Note that options set here will override those set in the config file.

**Comment by jboynyc** [comment]
Thanks, very helpful! I guess there's no bug then, so I'll close this issue.

I saw the warning about secrets in the store, but since this is a server that only I use, I wasn't concerned. Config file outside the store makes sense though.
