### ISSUE TITLE
Build failure: nvidia drivers with linuxPackages_latest

### ISSUE THREAD

**Issue by nklsfrt** [NixOS/nixpkgs#221035]
### Steps To Reproduce

- `services.xserver.videoDrivers = ["nvidia"];`
- `boot.kernelPackages = pkgs.linuxPackages_latest;`
- rebuild the system

### Build log

```
error: builder for '/nix/store/l7ivlpnjrn0rwancq8ax9nsdyyqys5j2-nvidia-x11-520.56.06-6.2.3.drv' failed with exit code 2;
       last 10 log lines:
       >       |                                ^~~~~~~~~~~~~~~~~~
       > /build/NVIDIA-Linux-x86_64-520.56.06/kernel/nvidia-drm/nvidia-drm-crtc.c: In function 'nv_drm_enumerate_crtcs_and_planes':
       > /build/NVIDIA-Linux-x86_64-520.56.06/kernel/nvidia-drm/nvidia-drm-crtc.c:1148:13: warning: ISO C90 forbids mixed declarations and code [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeclaration-after-statement-Wdeclaration-after-statement8;;]
       >  1148 |             struct drm_plane *overlay_plane =
       >       |             ^~~~~~
       > make[2]: *** [/nix/store/5h14y0aza51bpdgd1nffy4xhzcgaa3vx-linux-6.2.3-dev/lib/modules/6.2.3/source/Makefile:2021: /build/NVIDIA-Linux-x86_64-520.56.06/kernel] Error 2
       > make[2]: Leaving directory '/nix/store/5h14y0aza51bpdgd1nffy4xhzcgaa3vx-linux-6.2.3-dev/lib/modules/6.2.3/build'
       > make[1]: *** [Makefile:242: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/5h14y0aza51bpdgd1nffy4xhzcgaa3vx-linux-6.2.3-dev/lib/modules/6.2.3/source'
       > make: *** [Makefile:82: modules] Error 2
       For full logs, run 'nix log /nix/store/l7ivlpnjrn0rwancq8ax9nsdyyqys5j2-nvidia-x11-520.56.06-6.2.3.drv'.
```
[Full log here.](https://gist.github.com/nklsfrt/c1cfbe428472234e39ab62343b68a8f2)

### Additional context

It built fine when `linuxPackages_latest` pointed to `6.1.13`.
There seems to be a regression somewhere between that and `6.2.3`.
I tried the stable and beta nvidia packages, both fail to build.
It does build with `boot.kernelPackages = pkgs.linuxPackages;`

This is with a flake configuration locked to:
`nixpkgs: github:NixOS/nixpkgs/5eb98948b66de29f899c7fe27ae112a47964baf8`

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.13, NixOS, 22.11 (Raccoon), 22.11.20230311.5eb9894`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by romatthe** [comment]
I've been having various issues with building the nvidia drivers for a few days now. I thought the issue was on my side at first, but there's something else going on I think.

Pulling in the latest commits on the `nixos-22.11` branch, `nix-build -A linuxPackages_6_2.nvidia_x11` simply fails to build for me:

```
/build/NVIDIA-Linux-x86_64-520.56.06/kernel/nvidia-drm/nvidia-drm-connector.c:101:18: error: 'struct drm_connector' has no member named 'override_edid'
  101 |     if (connector->override_edid) {
      |                  ^~
make[3]: *** [/nix/store/2ldb15rc4vf2v05ca5vv7ik6l1gcz7p4-linux-6.2.5-dev/lib/modules/6.2.5/source/scripts/Makefile.build:252: /build/NVIDIA-Linux-x86_64-520.56.06/kernel/nvidia-drm/nvidia-drm-connector.o] Error 1
```
Followed by a gargantuan list of `objtool` errors that, to be very honest, I don't understand. Building `linuxPackages_latest.nvidia_x11` instead does not give me the `objtool` errors, but still fails because of the `override_edid` member.

My first thought was that this has something to do with the `ibt=off` kernel paramater which was being set to `on` by default starting with kernal 6.2.0. However, a fix for that has already been backported to stable.

The build failure has been happening for me on kernel 6.2.0 and 6.2.3.

**Comment by romatthe** [comment]
@Kiskae Apologies for the ping, I saw you recently submitted patches for the `ibt` issue with kernel 6.2 and a patch for the legacy 470 driver, so I wondered if you had any idea what could be causing our issue here.

For the record, it looks like I can't build any of the drivers on stable atm. I tried `525`, `520`, `515` and `470`. All failed to build on my machines on the latest commit on the stable `nixos-22.11` branch. I *was* able to build `nvidia_x11_legacy470` by applying the patch you recently submitted, but that's it.

One thing that I found curious is that my build failures on the `520` driver are because of a non-existing `override_edid` member, and the patch for `470` specifically puts access of the `override_edid` member behind a `#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 2, 0)`. But on the other hand, the patch clearly mentions being for the `470` driver series.

Sorry if what I'm trying to say is confusing.

(I'm assuming the `objtool` errors is not something we can do anything about right now in nixpkgs.)

**Comment by Kiskae** [comment]
You should be able to apply the `legacy470` patches to the other versions as well, if that version of the driver does not include a fix from nvidia's side then the patch should apply cleanly regardless of version. The reason it explicitly mentions `470xx` is because that is an actively supported branch that hasn't been patched by nvidia already.

Regarding the `objtool` errors there is no way to get rid of them, they get triggered by the precompiled binaries provided by nvidia and if `X86_KERNEL_IBT` is enabled the kernel build always runs the check.

**Comment by romatthe** [comment]
Thanks for the feedback. I haven't had the time to try applying the patches, I'll do so as soon as I can.

Am I correct in understanding that never versions of the Nvidia drivers have already fixed this issue?

**Comment by Kiskae** [comment]
Yes, generally nvidia makes sure the linux drivers are compatible by the time a new kernel release is published which then gets pushed to `nixos-unstable`.

Ideally the nvidia driver would be backported just like the latest kernels are, but that is very likely to cause incompatibilities between the kernel and the `/run/opengl-driver` binaries that stable users wouldn't expect.

**Comment by afrepues** [comment]
> Ideally the nvidia driver would be backported just like the latest kernels are

What about backporting the patch instead?

**Comment by icodeforyou-dot-net** [comment]
I appear to be facing a similar issue, this time when building modules for kernel 6.2.11.

The error message is however not the same.

```bash
error: builder for '/nix/store/j7w46d05lnn01dizcrafrrkjkq4d955f-nvidia-x11-520.56.06-6.2.11.drv' failed with exit code 2;
       last 10 log lines:
       >    97 |     bool primary_event = false;
       >       |          ^~~~~~~~~~~~~
       > /build/NVIDIA-Linux-x86_64-520.56.06/kernel/nvidia-drm/nvidia-drm-modeset.c:96:23: warning: unused variable 'primary_plane' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-variable-Wunused-variable8;;]
       >    96 |     struct drm_plane *primary_plane = crtc->primary;
       >       |                       ^~~~~~~~~~~~~
       > make[2]: *** [/nix/store/vzcadfyrbcd24pwp29qn3ry5czsh00r4-linux-6.2.11-dev/lib/modules/6.2.11/source/Makefile:2021: /build/NVIDIA-Linux-x86_64-520.56.06/kernel] Error 2
       > make[2]: Leaving directory '/nix/store/vzcadfyrbcd24pwp29qn3ry5czsh00r4-linux-6.2.11-dev/lib/modules/6.2.11/build'
       > make[1]: *** [Makefile:242: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/vzcadfyrbcd24pwp29qn3ry5czsh00r4-linux-6.2.11-dev/lib/modules/6.2.11/source'
       > make: *** [Makefile:82: modules] Error 2
       For full logs, run 'nix log /nix/store/j7w46d05lnn01dizcrafrrkjkq4d955f-nvidia-x11-520.56.06-6.2.11.drv'.
```

**Comment by Kiskae** [comment]
The actual error is here:

```console
nvidia-x11> /build/NVIDIA-Linux-x86_64-520.56.06/kernel/nvidia-drm/nvidia-drm-connector.c: In function '__nv_drm_detect_encoder':
nvidia-x11> /build/NVIDIA-Linux-x86_64-520.56.06/kernel/nvidia-drm/nvidia-drm-connector.c:101:18: error: 'struct drm_connector' has no member named 'override_edid'
nvidia-x11>   101 |     if (connector->override_edid) {
nvidia-x11>       |                  ^
```

You should be able to fix this by applying the `nvidia-470xx-fix-linux-6.2.patch` from the `legacy470` package. There aren't any offical updates from nvidia since they've moved on to the `530` release branch.

**Comment by icodeforyou-dot-net** [comment]
Did anyone make any progress on this? I have been trying to apply the patch `nvidia-470xx-fix-linux-6.2.patch`, but failed to do so. If anyone has a simple solution to this issue, I would appreciate it.

**Comment by Dessix** [comment]
I've had success with:
```nix
let
  unstable = import <nixos-unstable> {
    config = {
      allowUnfree = true;
      allowUnfreePredicate = (pkg: true);
    };
  };
in
{
  # ...
  boot.kernelPackages = unstable.linuxPackages_latest;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.latest;
  # ...
}
```
But that relies on jumping to the unstable kernel, which may not be something you want to deal with.

**Comment by icodeforyou-dot-net** [comment]
Yeah, in the meantime I decided to do this: `boot.kernelPackages = pkgs.linuxPackages_6_1;` which does get rid of the problem. I don't need kernel 6.2 for now, so that will do.

**Comment by ovitente** [comment]
I have lenovo legion 7 pro with intel and nvidia rtx4080.
And before i found and read this issue - i was not able to make any graphic system work on this kernel and latest nvidia drivers.

I was desperate, but this `boot.kernelPackages = pkgs.linuxPackages_6_1;` worked for me, and now i see lightdm. Thank you!

**Comment by Kiskae** [comment]
@nklsfrt Your issue was probably covered by some of the solutions mentioned, are there still other open issues or can this be closed?

**Comment by romatthe** [comment]
With the release of NixOS 23.05 earlier today, the Nvidia drivers should now rebuild again on stable for everyone. I think this issue can be closed, as there should no longer be any need for workarounds. Personally, I'm now successfully running again on kernel 6.3.5 and Nvidia driver 530.41.03.
