### ISSUE TITLE
boot.binfmt.emulatedSystems requires compiling QEMU

### ISSUE THREAD

**Issue by Luflosi** [NixOS/nixpkgs#221056]
### Describe the bug
Adding a system to `boot.binfmt.emulatedSystems` requires building QEMU from source.

### Steps To Reproduce
1. Have a NixOS system with `boot.binfmt.emulatedSystems` not set
2. Set `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` in your `configuration.nix`
3. Rebuild the system
4. QEMU will be recompiled from source

### Expected behavior
I would expect the relevant versions of QEMU to be cached.

### Additional context
This happens because the QEMU derivation is being modified with `.override`:
https://github.com/NixOS/nixpkgs/blob/adb03acc9b902e833473efba5ad77dc95039f500/lib/systems/default.nix#L177-L189
Hydra obviously can't find these modified QEMU derivations.

I don't know what the best way to fix this would be. Perhaps we could add all the different architecture specific QEMU versions to `pkgs/top-level/all-packages.nix`? Is there a better solution?

### Notify maintainers
Cc @matthewbauer because you created 9c8fd412248ad907eee7547b19bf3f7583d2c411 many years ago.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.14, NixOS, 22.11 (Raccoon), 22.11.20230302.96e1871`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/mh2gsjjpvckd42b205h9g2fjypximf9d-source`
```

**Comment by Bvngee** [comment]
Am I correct that this is fixed by #314998?  qemu-user as shown above was abstracted out as an argument to qemu called `userOnly`, and `qemu-user = qemu.override { userOnly=true; }` was added to `all-packages.nix`. `boot.binfmt.emulatedSystems` now refers to it directly.

Interestingly, even using `pkgsStatic.qemu-user` didn't seem to require a recompile for me; is pkgsStatic partially covered by Hydra now? Or maybe I just looked away for too long and didn't notice it compiling lol. I would've expected `pkgs.qemu-user` to be cached but not `pkgsStatic.qemu-user`.

**Comment by Luflosi** [comment]
Yes, I believe that was indeed fixed with #314998 laying the groundwork and 4658a06076ea881730dbb7acee879e90dcc435f5 in #334859 actually fixing it.

There is however a downside to the new approach: the closure size is bigger, since the package now contains 34 emulators instead of just one. To measure this, I added `qemu-user-orig-aarch64 = qemu.override { smartcardSupport = false; spiceSupport = false; openGLSupport = false; virglSupport = false; vncSupport = false; gtkSupport = false; sdlSupport = false; pulseSupport = false; smbdSupport = false; seccompSupport = false; hostCpuTargets = [ "aarch64-linux-user" ]; };` and `qemu-user-aarch64 = qemu-user.override { hostCpuTargets = [ "aarch64-linux-user" ]; };` to `pkgs/top-level/all-packages.nix`, built the two new packages and `qemu-user` and looked at the result with `nix-tree ./result`. The original `qemu-user` that was used before 4658a06076ea881730dbb7acee879e90dcc435f5 (built with a current Nixpkgs version) has a NAR size of 48.55 MiB and a total closure size of 135.71 MiB, while `qemu-user` has a NAR size of 112.63 MiB and a total closure size of 163.54 MiB. The size increase was less than I expected. But if we take `qemu-user` and let it build only for one architecture, we can make it much smaller than even the original `qemu-user` version, coming in with a NAR size of only 6.51 MiB and a total closure size of 57.42 MiB.

**Comment by jcaesar** [comment]
@Luflosi I [considered this](https://github.com/NixOS/nixpkgs/pull/314998#discussion_r1702775896) but ultimately decided that doing something about the size is not worth it. Emulating foreign CPU architectures is a heavy thing to do anyway.

* As you noted, you can override `qemu-user` with `hostCpuTargets` with a single entry. You can do this in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/fe21dd5ab593b2cd974161e462b2e2b0c8e24bae/lib/systems/default.nix#L290) or in your config by setting `boot.binfmt.registrations.<name>.interpreter`. But this would need some solution for making sure that each architecture is being cached, and it also causes a lot of duplicated complication for the parts of qemu that aren't architecture-specific. That'll be especially annoying if you override or the caching somehow breaks because `pkgsStatic` wasn't properly considered or something.
* You can [override locally](https://github.com/jcaesar/sysflake/blob/182ca2c66ff0d1bcd4ba5f3032cca97bbb32da59/mod/binfmt.nix#L6-L11) to build one qemu-user with just the architecture you need. But that only makes sense in `--build-host`/`--target-host` situations or if you're running your own cache.
* You could make qemu a multi-output derivation, with one output for each architecture binary (and symlinks in `$out` to not break stuff). That'll fix the "compile common parts many times"-problem and caching will be easily achievable, but it'll also increase the complexity of the qemu derivation even more (and you'll need a list of all architectures in the qemu derivation, which so far was avoidable).
* You could make `boot.binfmt.preferStaticEmulators` the default, and make sure that `boot.binfmt.registrations.${system}.interpreter` ends up being set to `runCommand "qemu-${pkgs.qemu-user.version}-user-${system}" "cp ${pkgs.pkgsStatic.qemu-user}/bin/qemu-${(lib.systems.elaborate { inherit system; }).qemuArch} $out"; }`. You'd still have to worry about getting this `runCommand` cached for every architecture, but that failing would be a small problem, only forcing to download the bigger `pkgsStatic.qemu-user`.

**Comment by Luflosi** [comment]
Thanks for the detailed explanation of the trade-offs. I agree, we should leave it like this for now.
