### ISSUE TITLE
Haskell: fix amazonka package suite dependencies

### ISSUE THREAD

**Issue by k0001** [NixOS/nixpkgs#22143]
## Issue description

The many `amazonka*_1_4_5` packages depend on `amazonka*` 1.4.3 packages, but they should be depending on other `amazonka*_1_4_5` packages instead. The "amazonka package suite", if you will, is versioned as a whole, and it's expected that versions `1.4.5.*` of the `amazonka-*` packages are used everywhere when using the "amazonka package suite 1.4.5".

We currently have this in `hackage-packages.nix`, for example:

```nix
  "amazonka-autoscaling_1_4_5" = callPackage
    ({ amazonka-core, amazonka-test, ...  # some other unrelated dependencies
     }:
     mkDerivation { ...
```

Yet, the `amazonka-core` and `amazonka-test` in in that very same package set refer to version `1.4.3` of these packages, not `1.4.5` as expected. So, cabal dependency resolution fails. Ideally, we should have this instead:

```nix
  "amazonka-autoscaling_1_4_5" = callPackage
    ({ amazonka-core_1_4_5, amazonka-test_1_4_5, ...  # some other unrelated dependencies
     }:
     mkDerivation { ...
```

My question is: Where and how to fix this so that the fix is preserved across future automatically generated `hackage-package.nix`?

**Comment by teh** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-hackage2nix.yaml maybe?

**Comment by k0001** [comment]
That doesn't seem to be from where the `_1_4_5` versions are coming from. 

@peti do you know how the `amazonka*_1_4_5` entries are ending up in `hackage-packages.nix`, and where I should make the relevant changes so as to solve the issue in question?

**Comment by peti** [comment]
The "amazonka*_1_4_5" entries exist because the package set contains (a) all packages mandated in the latest version of LTS-7.x plus without a version suffix (b) the latest version of every package on Hackage *with* a version suffix (unless (a) and (b) happen to be identical).

There is no easy solution for your problem, I'm afraid. You could write explicit overrides for all packages involved into `configuration-common.nix`, but doing this (and keeping it up-to-date) is obviously going to be a crazy effort.

My recommendation would be to use the amazonka version that's in LTS 7.x.
