### ISSUE TITLE
gimpPlugins.resynthesizer: requires python2

### ISSUE THREAD

**Issue by bryango** [NixOS/nixpkgs#221599]
### Describe the bug

`gimpPlugins.resynthesizer` requires python2, which is not pulled in automatically. This is mentioned in https://github.com/NixOS/nixpkgs/issues/205742.

### Steps To Reproduce

- I install `gimpPlugins.resynthesizer` with `nix-env -iA nixpkgs.gimp-with-plugins`, but it doesn't work out of the box. GIMP's python2 bindings are missing.
- I can include python2 manually, with `packageOverrides`:

```nix
# cat ~/.config/nixpkgs/config.nix 
{
  packageOverrides = pkgs: with pkgs; {
    gimp = gimp.override {
      withPython = true;
    };
  };
}
```
... as mentioned in https://github.com/NixOS/nixpkgs/issues/205742. However, IMHO this should be automatic.

### Expected behavior

`gimp.override { withPython = true; }` should be part of `resynthesizer`.

### There is an attempt

I am not at all familiar with nix, though I did try to do this with `resynthesizer.overrideAttrs` and failed:
```nix
# cat ~/.config/nixpkgs/config.nix 
{
  packageOverrides = pkgs: with pkgs; {
    gimpPlugins.resynthesizer = with gimpPlugins; resynthesizer.overrideAttrs (
      outAttr: inAttr: {
        gimp = gimp.override {
          withPython = true;
        };
      }
    );  ## this does NOT work
  };
}
```
I am not sure if it's okay to naively add `gimp.override` to `resynthesizer` with `resynthesizer.overrideAttrs`. This also causes `gimpPlugins` to skip all other plugins which I don't understand why:
```
nix-repl> (import <nixpkgs> {}).gimpPlugins
{ resynthesizer = «derivation /nix/store/cnw590qf5394h3si209g73znzdmdsm54-gimp-plugin-resynthesizer-2.0.3.drv»; }

### ^ somehow all other plugins are gone once I used `resynthesizer.overrideAttrs`
### ... consequently, `gimp-with-plugins` fails:

nix-repl> (import <nixpkgs> {}).gimp-with-plugins
error: attribute 'gimp' missing

       at /nix/store/hdcd9p53x22cbpcgqas3p1lh6sgrqsyd-nixpkgs/nixpkgs/pkgs/applications/graphics/gimp/wrapper.nix:5:43:

            4| allPlugins = lib.filter (pkg: lib.isDerivation pkg && !pkg.meta.broken or false) (lib.attrValues gimpPlugins);
            5| selectedPlugins = lib.filter (pkg: pkg != gimpPlugins.gimp) (if plugins == null then allPlugins else plugins);
             |                                           ^
            6| extraArgs = map (x: x.wrapArgs or "") selectedPlugins;
```

### Notify maintainers

@jtojnar 

This is a non-essential bug; it's more like a feature request... Sorry for the noise.

### Metadata

```console
[$USER@$HOST:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.94-1-MANJARO, Manjaro Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels($USER): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/$USER/channels/nixpkgs`
```

**Comment by jtojnar** [comment]
`resynthesizer` is created using `pluginDerivation`:

https://github.com/NixOS/nixpkgs/blob/1d07677d2a3f61ca85ae4524732af5f7636e8dff/pkgs/applications/graphics/gimp/plugins/default.nix#L190

If you do

```nix
gimpPlugins.resynthesizer.overrideAttrs (
  oldAttrs: {
    gimp = ...;
  };
}
```

you will just add a new `gimp` attribute to the attribute set passed to `stdenv.mkDerivation` by `mkDerivation`. But that will not be used by anything since nothing expects that attribute.

Moreover, overlay like

```nix
packageOverrides = pkgs: with pkgs; {
    gimpPlugins.resynthesizer = ...;
};
```

is identical to

```nix
packageOverrides = pkgs: with pkgs; {
  gimpPlugins = {
    resynthesizer = ...;
  };
};
```

And since overlays do not perform recursive merge, there is no `gimpPlugins.gimp` attribute and the GIMP wrapper expression crashes.

`gimpPlugins` is actually a scope

https://github.com/NixOS/nixpkgs/blob/1d07677d2a3f61ca85ae4524732af5f7636e8dff/pkgs/applications/graphics/gimp/plugins/default.nix#L11

so the proper way to override `gimp` used by `gimpPlugins` through `gimpPlugins.overrideScope'`:

```nix
pkgs:
{
  gimpPlugins = pkgs.gimpPlugins.overrideScope' (gimpPluginsFinal: gimpPluginsPrev: {
    gimp = gimpPluginsPrev.gimp.override {
      withPython = true;
    };
  });
}
```

But you will still need to override the top-level GIMP, since that is what will actually use control interpreters, so I would just go with the first package set override you came up with

```nix
pkgs:
{
  gimp = pkgs.gimp.override {
    withPython = true;
  };
}
```

There are ways we could make the wrapper automatically enable Python 2 when a plug-in depending on it is selected but IMO the additional complexity is not worth it. Especially, when we would need to disable Python 2 specific plug-ins.

https://github.com/NixOS/nixpkgs/blob/1d07677d2a3f61ca85ae4524732af5f7636e8dff/pkgs/applications/graphics/gimp/wrapper.nix

**Comment by jtojnar** [comment]
I have opened https://github.com/NixOS/nixpkgs/pull/221660 that will at least make it fail loudly when resynthesizer is used with incompatible GIMP.
