### ISSUE TITLE
`mozc_tool` installed with `fcitx5-mozc` immediately closes with return code `255`

### ISSUE THREAD

**Issue by toyboot4e** [NixOS/nixpkgs#221958]
### Steps To Reproduce
1. Enable `fcitx5-mozc` in `configuration.nix` and run `sudo nixos-rebuild switch`:
```nix
  i18n.inputMethod = {
    enabled = "fcitx5";
    fcitx5.addons = with pkgs; [ fcitx5-mozc fcitx5-gtk ];
  };
```
2. Run `/run/current-system/sw/lib/mozc/mozc_tool --mode=config_dialog`
3. `mozc_tool` immediately closes with return code `255`.

### Expected behavior
`mozc_tool` window shows.

### Additional context
Same issue in `fcitx-mozc` (#72896) was fixed with `wrapQtApp`.

### Notify maintainers

@gebner who fixed #72896 (thanks!).

### Metadata

 - host os: `Linux 6.1.15, NixOS, 23.05 (Stoat), 23.05pre461735.1e2590679d0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos, stable-22.11, unstable"`
 - channels(tbm): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by natsukium** [comment]
I tried `strace ${fcitx5-mozc}/lib/mozc/mozc_tool` and found that `mozc_tool` is not wrapped with wrapQtApp.
Next, I tried the following patch.
```diff
installPhase = ''
    export PREFIX=$out
    export _bldtype=Release
    ../scripts/install_server
    install -d $out/share/licenses/fcitx5-mozc
    head -n 29 server/mozc_server.cc > $out/share/licenses/fcitx5-mozc/LICENSE
    install -m644 data/installer/*.html $out/share/licenses/fcitx5-mozc/
    install -d $out/share/fcitx5/addon
    install -d $out/share/fcitx5/inputmethod
    install -d $out/lib/fcitx5
+   wrapQtApp $out/lib/mozc/mozc_tool
    ../scripts/install_fcitx5
  '';
```
https://github.com/NixOS/nixpkgs/blob/4d2b37a84fad1091b9de401eb450aae66f1a741e/pkgs/tools/inputmethods/fcitx5/fcitx5-mozc.nix#L93-L104

This derivation failed with `Builder called die`.
(`Builder called die: Cannot wrap '/nix/store/91ya0habnqqf2rdqkfdnciavzpvhlp9l-fcitx5-mozc-2.26.4220.102/lib/mozc/mocz_tool' because it is not an executable file`)

In the [nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#qt-runtime-dependencies), you need to manually wrap an application that is non-ELF executable (but `mozc_tool` seems to be ELF).
> wrapQtAppsHook ignores files that are non-ELF executables. This means that scripts won’t be automatically wrapped so you’ll need to manually wrap them as previously mentioned. An example of when you’d always need to do this is with Python applications that use PyQt.

So I added a preFixup phase like this. https://github.com/natsukium/nixpkgs/commit/e2e0a48ada75b052722fa1233f876f6a543f3e7b
I have confirmed that `mozc_tool` runs without errors and shows a window, but I have not checked whether it can be set up correctly yet.

**Comment by toyboot4e** [comment]
Awesome! I tried https://github.com/natsukium/nixpkgs/commit/e2e0a48ada75b052722fa1233f876f6a543f3e7b and I confirm it worked like a charm. Great job!
