### ISSUE TITLE
Build failure: findimagedupes

### ISSUE THREAD

**Issue by olebedev** [NixOS/nixpkgs#222284]
### Steps To Reproduce

1. install `findimagedupes`:
    ```
    $ nix profile install nixpkgs#findimagedupes
    ```
2. run  it with help option:
    ```
    $ findimagedupes --help
    [...]
    ```
    For some reasons it tries build some stuff after the main package has been built and installed into the profile, I don't understand this behaviour. 

### Build log

https://gist.github.com/olebedev/bed511344d2fa8b0d1f2f8b0677aaf2e

### Notify maintainers

@Stunkymonkey 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Stunkymonkey** [comment]
maybe we should switch to https://gitlab.com/opennota/findimagedupes
Not sure about migration for a package.

**Comment by Stunkymonkey** [comment]
i tried fixing it. But the perl binding are out of date. Therefore I removed it.

I will migrate to https://github.com/NixOS/nixpkgs/pull/242522

**Comment by amalgame21** [comment]
@Stunkymonkey I found a workaround (I don't know if it is appropriate).

1. Change
https://github.com/NixOS/nixpkgs/blob/9ef5b7d793a0ac1f1742696b5ec668169ff9c80d/pkgs/tools/graphics/findimagedupes/default.nix#L1
to
```nix
{ lib, stdenv, fetchurl, makeWrapper, perl, perlPackages, installShellFiles, libxcrypt }:
```
2. Change
https://github.com/NixOS/nixpkgs/blob/9ef5b7d793a0ac1f1742696b5ec668169ff9c80d/pkgs/tools/graphics/findimagedupes/default.nix#L33
to
```nix
      --replace "DIRECTORY => '/usr/local/lib/findimagedupes';" "DIRECTORY => '/tmp'; use Inline C => config => ccflagsex => \"-I${libxcrypt}/include\";" \

```

Reference: https://metacpan.org/dist/Inline-C/view/lib/Inline/C.pod#C-CONFIGURATION-OPTIONS

findimagedupes is still better for my use case because it is a command line utility but the python variant is not.

**Comment by Stunkymonkey** [comment]
@amalgame21 `findimagedupes` is already removed in #242697. If you want it to add it again. Please go ahead an submit an PR.
