### ISSUE TITLE
Package dmenu-rs fails to build on NixOS 23.05

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#222351]
### Steps To Reproduce

1. build *dmenu-rs*

### Build log

```
this derivation will be built:
  /nix/store/ay386p1ma1ivq54l9zck4fbfijf1frvi-dmenu-rs-5.5.1.drv
building '/nix/store/ay386p1ma1ivq54l9zck4fbfijf1frvi-dmenu-rs-5.5.1.drv'...
unpacking sources
unpacking source archive /nix/store/cfff3dy90qc00b47sxi7m4rmvhf7m4k1-source
source root is source
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
patching sources
unlink: cannot unlink '/build/cargo-vendor-dir/xcb-0.8.2': Is a directory
/nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux/setup: line 136: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/ay386p1ma1ivq54l9zck4fbfijf1frvi-dmenu-rs-5.5.1.drv' failed with exit code 1;
       last 8 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/cfff3dy90qc00b47sxi7m4rmvhf7m4k1-source
       > source root is source
       > Executing cargoSetupPostUnpackHook
       > Finished cargoSetupPostUnpackHook
       > patching sources
       > unlink: cannot unlink '/build/cargo-vendor-dir/xcb-0.8.2': Is a directory
       > /nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux/setup: line 136: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/ay386p1ma1ivq54l9zck4fbfijf1frvi-dmenu-rs-5.5.1.drv'.
```

### Notify maintainers
@benjaminedwardwebb

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[sogreatandpowerful@ProbabilityWaveFunction:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.3-xanmod1, NixOS, 23.05 (Stoat), 23.05pre465704.1603d11595a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(sogreatandpowerful): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by benjaminedwardwebb** [comment]
Hi @sogreatandpowerfull. Thanks for filing this issue.

I haven't had time to look into this yet, but `dmenu-rs` builds successfully on my personal host, which uses NixOS 22.11.

```bash
sudo nix-channel --list
```
```
home-manager https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz
nixos https://nixos.org/channels/nixos-22.11
```

Perhaps dropping down to NixOS 22.11 will work for you, so I wanted to at least mention it as a potential option.

However, I expect there's a reason you're using 23.05.

Given the `unlink` error, my first thought is that the cargo vendoring functions in nixpkgs have changed between 22.11 and 23.05 such that vendored dependencies are no longer symlinked into the `/build/cargo-vendor-dir` directory but are instead copied or otherwise placed there as actual directories. See https://github.com/NixOS/nixpkgs/pull/200977/files#diff-ef477e2f90602bd0aab4d651c310dd6ff8066ae659c2e46ff711f8583d62b112R66 for the line that appears to be causing the issue. A potential fix might be to update this line to instead remove the directory with `rmdir` or some other unix command that will work in both the symlink and directory case. There may also be better fixes that involve working with the [upstream project][1] directly to remove the problematic XCB dependency directly, but this would be more involved.

But this is just a theory I haven't looked into yet.

Here are some additional details about my system, where the `dmenu-rs` build works, so that you can compare them with yours if you'd like to look into the issue yourself.

```bash
uname -a
```
```
Linux berrio 5.15.81 #1-NixOS SMP Fri Dec 2 16:41:12 UTC 2022 x86_64 GNU/Linux
```

Otherwise, I'll probably have some time over the next week to look into it.

[1]: https://github.com/Shizcow/dmenu-rs

**Comment by sogreatandpowerfull** [comment]
Oh, I've also been able to build it successfully on version 22.11, however, it encounters errors and fails to build on version 23.05.

**Comment by benjaminedwardwebb** [comment]
> Oh, I've also been able to build it successfully on version 22.11, however, it encounters errors and fails to build on version 23.05.

OK. I figured that was likely the case, but wanted to mention it in case downgrading was an acceptable option for you.

**Comment by sogreatandpowerfull** [comment]
Out of the numerous packages that I have installed, this particular package is the only one that couldn't be built on 23.05. Therefore, it is not practical for me to downgrade the entire system just for one package. As an alternative, I will have to resort to using dmenu. 
Thank you very much for your help.

**Comment by benjaminedwardwebb** [comment]
> Out of the numerous packages that I have installed, this particular package is the only one that couldn't be built on 23.05.

Ouch. I won't lie, that particular phrasing stung my pride a bit.

But I am also not surprised this is the case --  `dmenu-rs` is the first and only package I've added to `nixpkgs`, and the particular XCB dependency related to the build issue in 23.05 required some hacking to get it working initially for 22.11.

You're welcome to keep the issue open and check back some time in the next week. I'll plan to address the issue and will probably post here when it's fixed either way, since I will eventually be using 23.05 as well.

Of course, there really are only very trivial differences between `dmenu-rs` and `dmenu`, so it may not end up mattering to you at the end of the day.

**Comment by benjaminedwardwebb** [comment]
@sogreatandpowerfull I have a fix in PR [here][1].

More details are in the PR and commit, but as I mentioned up thread it did seem to be related to [changes in nixpkgs functions that broke the brittle call to `unlink` in the `dmenu-rs` derivation][2].

Thankfully, due to those same changes, I was able to dramatically simplify the derivation so it should be less brittle going forward (thanks to @figsoda both for those changes and for help debugging the build).

[2]: https://github.com/NixOS/nixpkgs/pull/218472
[1]: https://github.com/NixOS/nixpkgs/pull/223667

**Comment by benjaminedwardwebb** [comment]
@sogreatandpowerfull were you able to install dmenu-rs on 23.05 on your machine (if you cared to)?

Should I close this issue?

**Comment by sogreatandpowerfull** [comment]
Yup!
