### ISSUE TITLE
(Optionally) Disable PaX SOFTMODE and PT_PAX

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#22253]
## Issue description
In our grsecurity configuration, we currently enable `SOFTMODE` for PaX, which according to [the Gentoo Hardened wiki](https://wiki.gentoo.org/wiki/Hardened/PaX_Quickstart), means that "PaX protection will not be enforced by default for those features which can be turned on or off at runtime". Is there a good reason for this to be enabled? Should we at least allow users to disable it via a `config.grsecurity.softmode` flag or something similar?

More generally, perhaps we could allow users to specifically override individual options?

Relevant code is [here](https://github.com/NixOS/nixpkgs/blob/d918c80e133d00693973fb15ae12b6fd0b2d7a5c/pkgs/os-specific/linux/kernel/grsecurity-nixos-config.nix#L20).

**Comment by siddharthist** [comment]
Also, it seems like it's not recommended to set both `PT_PAX` and `XATTR_PAX`:
> One final caveat about the two supported methods of doing PaX markings: the PaX kernel allows both PT_PAX and XATTR_PAX to be enabled, however if both features have been enabled PaX will not impose the markings unless the same flags are found in both locations. For this reason, the Hardened Project not recommend enabling both features at the same time, even for migration which is described below.

**Comment by joachifm** [comment]
Our needs are different than gentoo's. We *need* ELF markings for stuff in the store, but taking away the ability to set flags via xattrs is too severe, as it's a good feature for people who need it for out-of-store stuff, where modifying binaries might not be feasible or desirable (e.g., for games). It's pretty clear that per-executable PaX flags set by `paxmark` are respected even if xattrs remain unset; as far as I can tell, the problem is setting conflicting flags for the same executable. Conflicts are unlikely to occur for in-store stuff (impossible on a properly configured system); for out-of-store stuff I expect xattrs will be used exclusively, so no conflicts should occur there either.

Regarding PaX softmode, it's a good feature to have, IMO, and it is disabled by default and requires super user rights. I consider it a convenience for just getting stuff to work in a hurry. If the adversary is able to toggle arbitrary sysctls, you've already lost (in any case, `mprotect()` hardening on `ls` is likely not what's going to stop the adversary at that point). Note also that per-executable PaX hardening typically gets disabled for stuff that could benefit the most from it, anyway, like firefox, so it's not like you're that much worse off even with softmode enabled.

Please be mindful that the NixOS module is unsuitable for high security deployments, as explained in the manual, which also explains how to use custom configs.

**Comment by siddharthist** [comment]
@joachifm Thanks for taking the time to explain this to me.

**Comment by joachifm** [comment]
Once we have a better RBAC story, I'd like to deal with this more at that level, at least for NixOS, I find that potentially much neater than both markings and xattrs (though `paxmark` would still be needed for non-NixOS hosts).
