### ISSUE TITLE
Unable to use breeze-plymouth

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#22292]
## Issue description

Trying to use ```breeze-plymouth``` makes ```nixos-rebuild``` fail:

```sh
  output ‘/nix/store/l3xipkcs93ddcd9lsfjrknymn1z538k6-extra-utils’ is not allowed to refer to path ‘/nix/store/7mni656sr2prhx5qj1cwpgk7hkdf68lz-plymouth-0.9.2’
```

Cc: @ttuegel

### Steps to reproduce

```nix 
boot.plymouth.themePackages = with pkgs; [ kde5.breeze-plymouth];
```

Then we get the error above.

## Technical details

* NixOS: 17.03.git.0353b9662aM (Gorilla)
* Nix: nix-env (Nix) 1.11.6
* nixpkgs: 17.03.git.2f06667cdaM

**Comment by ttuegel** [comment]
I'm aware of this issue. Unfortunately, I've never been able to get even plain plymouth working on my development machine; something about graphics drivers. The proximate cause is some reference not being removed as necessary. It's rather hard to debug as-is because there isn't a single package one can build to test this issue. So, a good first step might be factoring out the appropriate stage (I think it's stage-2) into a standalone package.

**Comment by peterhoeg** [comment]
@ttuegel, plymouth works fine on 2 different machines here. I'll take a look at it during Feb - I was just hoping there was a quick solution...

**Comment by therealpxc** [comment]
I'm still getting this bug on May 14. Did you end up figuring out anything about what's going on here, @peterhoeg ?

**Comment by peterhoeg** [comment]
No, I haven't looked at it at all and I simply disabled plymouth instead.

**Comment by therealpxc** [comment]
Yeah, I'm in the same boat. Just wanted to make sure I hadn't missed out on something you forgot to post. Thanks for the update. :-)

**Comment by michaelpj** [comment]
I fixed this a few months ago, so this issue can be closed.

**Comment by peterhoeg** [comment]
Indeed, plymouth works now with the breeze theme. Nice, thanks @michaelpj !
