### ISSUE TITLE
DBus and Xfce

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#22302]
## Issue description

DBus currently seems broken on Xfce -- for example, `services.gnome-keyring` doesn't work for me. Reverting 29667f639c8f88b736e8607f36eb713f8b26b6e9. fixes it; that suggests problem is that `dbus-daemon` is started not by systemd but by Xfce itself, so it misses arguments and expects its configuration in `/etc/dbus-1`. `systemctl --user status dbus` shows that the service is not started on Xfce, which confirms this theory.

EDIT: Additionally, `services.dbus.socketActivated` fixes SSH agent but then Chromium and some other applications begin to take forever to start up; `strace` shows that they get a DBus-related error from some fd.

### Steps to reproduce

1. Start Xfce;
2. Attempt to use GNOME keyring (e.g. SSH agent).

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) f66d7823ece6fa4bf99e56fa4b4cb0ab16522839

**Comment by cstrahan** [comment]
For the sake of linking the two issues/PRs: https://github.com/NixOS/nixpkgs/pull/20871

**Comment by layus** [comment]
Hi @abbradar,
Could you find what command is used by xfce to start the session dbus instance ? How was it able to pick /etc/dbus-1 when it should look for /usr/share/dbus-1 ?

**Comment by abbradar** [comment]
A grep in `xfce.xfce4session` shows that it uses `dbus-launch`, without any parameters.

**Comment by abbradar** [comment]
After some more digging it seems that when configuration is stored in `/etc/dbus-1` dbus needs just `--system` or `--session` argument to work. See https://github.com/abbradar/nixpkgs/commit/687579757d163eed098853e1b20f2663d6e65491 -- with this my desktop runs correctly.

**Comment by layus** [comment]
:-) Or, you could just drop the ExecStart part, because --system and --session are what dbus does by default.

**Comment by layus** [comment]
See `systemctl cat dbus` and `systemctl --user cat dbus`

**Comment by abbradar** [comment]
Yep, it works! See #22343; it'd be nice if you could review.

**Comment by layus** [comment]
My feeling in this issue is that while putting files in /etc might seemingly solve the issue, the files in /etc may not be read at all. See https://github.com/NixOS/nixpkgs/blob/29667f639c8f88b736e8607f36eb713f8b26b6e9/nixos/modules/services/system/dbus.nix#L147 and https://github.com/NixOS/nixpkgs/blob/ea42d6fe62e5e21c4d191505019931d02182ea25/pkgs/development/libraries/dbus/default.nix#L53.
To me, this hints that it may work for some reason we do not understand. An not do what we think it does.
For example, the services uses both https://github.com/NixOS/nixpkgs/blob/29667f639c8f88b736e8607f36eb713f8b26b6e9/nixos/modules/services/system/dbus.nix#L147 and https://github.com/NixOS/nixpkgs/blob/29667f639c8f88b736e8607f36eb713f8b26b6e9/nixos/modules/services/system/dbus.nix#L67-L80
Why use both ? and how do they interact ?

**Comment by layus** [comment]
@abbradar For example, if you `strace -ff -e trace=file dbus-launch`, you will see that dbus does not look at /etc. Do you also observe that behavior ?

**Comment by abbradar** [comment]
I can't reproduce this, for me `strace` shows:

```
[pid 12068] open("/run/current-system/sw/share/dbus-1/session.conf", O_RDONLY) = 4
[pid 12068] open("/etc/dbus-1/session.conf", O_RDONLY) = 4
```

**Comment by abbradar** [comment]
Oh, I found it:
```
  <!-- Include legacy configuration location -->
  <include ignore_missing="yes">/etc/dbus-1/session.conf</include>
```
in `${dbus}/share/dbus-1/session.conf`.

**Comment by layus** [comment]
Ok, so you see that dbus loads `/run/current-system/sw/share/dbus-1/session.conf`. That file comes from upstream and is only kept to allow the dbus module to modify it (see https://github.com/NixOS/nixpkgs/blob/f66d7823ece6fa4bf99e56fa4b4cb0ab16522839/nixos/modules/services/system/dbus.nix#L25-L45). Loading that files means that something is wrong. The file we setup for dbus to load is located in "/nix/store/...-dbus-conf/system.conf".
This needs to be addressed before making yet another change to dbus.

**Comment by abbradar** [comment]
I looked through it and it seems to me that we don't actually need to modify it -- we can just use the upstream version. The only modification is used to force D-Bus to use `${configDir}` instead of `/etc/dbus-1`, but we link `configDir` exactly there so this is a non-issue. See https://github.com/NixOS/nixpkgs/pull/22343/commits/72b37462668e3a7568d94632994a9df5d7fd37eb

**Comment by abbradar** [comment]
BTW I think this file is used because of [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/dbus/default.nix#L53).

**Comment by layus** [comment]
The current behavior is due to a commit (https://github.com/NixOS/nixpkgs/commit/783c40eb68bbbcb9cf6918255157ecab55eedb6e) from @vcunat that set the datadir of dbus to "/run/current-system/sw/share". (https://github.com/NixOS/nixpkgs/blob/f66d7823ece6fa4bf99e56fa4b4cb0ab16522839/pkgs/development/libraries/dbus/default.nix#L53)

I wonder why such a NixOS specific path was used in the configuration of the package. I guess this is because there are not many users of our dbus package outside of NixOS. Such a setup makes dbus very special compared to other services.

**Comment by abbradar** [comment]
@vcunat Maybe we can remove this option? Then dbus will use its configuration from `$out/share/dbus-1` and correctly include our `-local` files from `/etc/dbus-1`. Perhaps not a high priority -- as @layus mentioned there are probably no/very few people who run D-Bus daemon from nixpkgs on non-NixOS, but this also feels cleaner to me.

**Comment by vcunat** [comment]
:-) certainly don't feel bounded by that commit of mine.  I don't remember it, but I'm fairly certain my understanding of dbus was minimal at that time (and it hasn't improved much since).
