### ISSUE TITLE
Keybase file system (KBFS) not working?

### ISSUE THREAD

**Issue by OJFord** [NixOS/nixpkgs#22375]
## Issue description
I can install Keybase package fine; at time of writing it's at the latest release 1.0.18.

However, after it's started and logged in etc. there's no file system available at `/keybase` as expected. Does this go somewhere else under NixOS, or is it just not working currently?

## Technical details

* System: (NixOS: `17.03pre99759.f66d782 (Gorilla)`)
* Nix version: `1.11.6`
* Nixpkgs version: `17.03pre99759.f66d782`

**Comment by yorickvP** [comment]
kbfs is in the package 'kbfs' (it could probably use an update, though)

**Comment by copumpkin** [comment]
In general, installing a package has no effect on "global" things like filesystems showing up. If your user "installs" a package, that doesn't do anything to other users, for example. An installation is a symlink into your profile.

To make something like keybase filesystem work in NixOS, I'd expect there to be a NixOS module for it. I don't know if there is one.

**Comment by OJFord** [comment]
@copumpkin I see, thank you. I'm just running on a personal machine as the sole user (well, sole non-root and with login) so that doesn't affect me, but it makes sense.

There is [a kbfs package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/kbfs/default.nix) as yorickvP mentioned, but when run it complains about not being able to talk to the Keybase server - possibly because it's out of date as suggested, I didn't dig deeper.

Ought that to work, if up to date? I'm afraid I'm not aware of the module v package distinction - is the former such that it would be `filesystems.kbfs.enable = true;` for example, rather than adding to a list of packages?

I don't think it matters that it's at a global location in a multi-user system, since Keybase will require that the user's logged in for access to `/keybase/private/username` and any `/keybase/private/username,sharedwith1,...` directories.

**Comment by yorickvP** [comment]
I've used it in the past (there's a command line argument to specify alternate mount directories). That would suggest it's just outdated. It's not currently a module, someone would have to write one (like https://github.com/NixOS/nixpkgs/tree/master/nixos/modules/services/network-filesystems)

**Comment by SuprDewd** [comment]
It seems to work just fine for me. Specifically, after already having installed `keybase`, this is what I did:
~~~bash
$ nix-env -f '<nixpkgs>' -iA kbfs
$ sudo mkdir /keybase
$ sudo chown $USER /keybase
$ KEYBASE_RUN_MODE=prod kbfsfuse /keybase
$ cat /keybase/public/suprdewd/hello.txt
~~~

Note that I do get a warning every second, though:
~~~
▶ WARNING Background keep alive hit an error: method 'sessionPing' not found in protocol 'keybase.1.session'
~~~
But apparently it doesn't seem to matter.

The latest version of `keybase`, which is the one that we have packaged, is from [Oct 26, 2016](https://github.com/keybase/client/releases/tag/v1.0.18). The packaged version of `kbfs` is slightly newer, or from [Nov 18, 2016](https://github.com/keybase/kbfs/commit/aac615d7c50e7512a51a133c14cb699d9941ba8c). I don't know why this version of `kbfs` was used (@aristidb?), but it's probably just because it was the latest version when it was packaged (the same day).

But I tried building a version of `kbfs` that was closer to the version we have of `keybase`, [8cd5e0bb07](https://github.com/keybase/kbfs/commit/8cd5e0bb07e731a649afe1c9c712cf0bb93211bb) to be precise. That version seemed to work just as well, but without the annoying warnings.

Not suggesting anything, but just an FYI.

**Comment by OJFord** [comment]
Thanks for the reply @SuprDewd, I'll have another look at it and perhaps try matching revisions more closely as you ~~suggest~~ allude to (:wink:) if I still can't get it functional.

I'll close this, as it's obviously not a problem with the package.
