### ISSUE TITLE
ocamlPackages.camomile: 1.0.2 → 2.0.0

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#224318]
- Package name: ocamlPackages.camomile
- Latest released version: 2.0.0

- Current version on the unstable channel: 1.0.2
- Current version on the stable/release channel: 1.0.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@vbgl

-----

Note for maintainers:

I was looking to do the 4.5.0 Soupault upgrade, but I ran into Camomile 2.x dependency issue. 

It looks like Camomile switched maintainers: https://github.com/savonet/Camomile
And the upgrade had some notable breaking changes: https://discuss.ocaml.org/t/ann-camomile-2-0-0-is-out/11751/

My experience in this ecosystem is too low to know what needs to be done. Does it need a `2_0_0.nix` file while the dust settles on other project upgrading? Are the `configurePhase` and `postInstall` hooks still relevant? Is `cppo` needed? Does it get moved to a more modern (e.g. 5.x) version of the packages?

Please feel free to tag me to review and test build it if @vbgl could use the extra eyes and/or testing.

**Comment by Alizter** [comment]
So I attempted this last week and the issue is that Camomile 2.0 is quite different from previous versions. The only reason therefore we would add camomile 2 is if anybody is actually using it. I am not currently aware of any packages that require it.

The discussions do also mention that other users have been frustrated by this. Therefore I think it is best if we think of Camomile 2 as a new library, therefore we currently have no reason to add it.

What we really need are compatability patches for Camomile 1.0 so that we can use it with OCaml 5.
