### ISSUE TITLE
Update request: Tenacity

### ISSUE THREAD

**Issue by n0toose** [NixOS/nixpkgs#225176]
- Package name: Tenacity
- Latest released version: [Tenacity 1.3 Beta 2](https://codeberg.org/tenacityteam/tenacity/releases/tag/v1.3-beta2)

- Current version on the unstable channel: 2022-06-30
- Current version on the stable/release channel: 2022-06-30

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@IreneKnapp
@lheckemann

-----

Note for maintainers:
- Please tag this issue in your PR.
- I am an old maintainer, but the entire project is under new management. I can direct you to the right channels for any questions, but my ability to collaborate with you on this is very limited.
- The project is highly friendly towards maintainers of ports that want to upstream code so as to minimize the effort required to maintain up-to-date packages on the side of the maintainers. The project has accepted patches for [Haiku](https://haiku-os.org), which also doesn't store binaries under `/usr/bin`, etc.
- The project has been moved to [**Codeberg**](https://codeberg.org/tenacityteam/tenacity) and a whole new tree (with the previous work rebased) has been created. GitHub is used as a mirror for legacy purposes, but I highly recommend using Codeberg instead.
- Expect some build system-related changes.

**Comment by generic-pers0n** [comment]
Hello! I'm the new maintainer of Tenacity now, and I'm willing to help you guys in packaging Tenacity for NixOS. I'd like to mention a couple of changes in dependencies that Tenacity 1.3 beta 2 has compared to the current version packaged:

1. **Tenacity now builds against wxWidgets >= 3.1.6, including the latest version**. Therefore, the current patches used to get Tenacity to build against newer versions of wxWidgets can be dropped from this package.
2. **Tenacity supports FFmpeg 5.x**. Although I don't know how relevant this is since FFmpeg is optional, I'm listing this here anyway to assure anyone that we support modern versions of FFmpeg. Also, as of the latest git version of Tenacity 1.3, we cherry-picked upstream commits to add support for FFmpeg 6.0, so we should support that by our latest stable version as well.

Finally, if there is any issue with building the latest version of Tenacity, feel free to let us know over at https://codeberg.org/tenacityteam/tenacity/issues. We will be glad to assist you guys in figuring out what's going on and fix these issues before 1.3 stable is out. Additionally, if there need to be any additional patches, we will gladly accept those upstream in order to minimize the effort of maintaining Tenacity packages and to keep Tenacity consistent across multiple OSes and platforms. Just be sure to open a pull request at https://codeberg.org/tenacityteam/tenacity/pulls :D

**Comment by IreneKnapp** [comment]
oh excellent, thanks! great to have your direct input @generic-pers0n. I'm really excited to see Tenacity having proper releases and energy around it, it will be my pleasure to update the package.
