### ISSUE TITLE
There's two "sad" packages, with one being not used at-all + unused nix files + perhaps even more

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#225489]
### Describe the bug
There's two "sad" packages, with one being not used at-all

### Steps To Reproduce
1. Open top-level/all-packages.nix in a text-editor (as of writing https://github.com/NixOS/nixpkgs/blob/48b2f723f5/pkgs/top-level/all-packages.nix but beware this will lag, so open it locally)
2. Look at this comment:

```
  /*  This package references ghc844, which we no longer have. Unfortunately, I
      have been unable to mark it as "broken" in a way that the ofBorg bot
      recognizes. Since I don't want to merge code into master that generates
      evaluation errors, I have no other idea but to comment it out entirely.

  sad = callPackage ../applications/science/logic/sad { };
  */
```

3. Look at this

```
  sad = callPackage ../tools/text/sad { };
```

4. Wonder what happened

### Expected behavior
Should be just one

### Additional context
We should just drop the old pkg's nix files after notifying the maintainer of the old package, but I'm opening this issue for discussion, because there might be more left to cleanup.

_Perhaps we should check if we have files in-tree that are no longer being referenced and do a prune of those files (and maybe check it in ci afterwards, or at least occasionally during hydra builds)._

### Notify maintainers

@fkz

**Comment by fkz** [comment]
The `sad` package of which I'm the maintainer has nothing to do with the other `sad` package, these are completely different packages. I am not using this application anymore, it is commented (and probably broken) since at least c8c80478e145 and b4dd96b2062aedf16d738b7e39c453ce9cf35574, which were committed in July 2020. This is nearly 3 years ago. I'm not maintaining it anymore.

So yes, let's remove it. I think deleting the folder `applications/science/logic/sad` and the commented reference in all-packages.nix should remove all references to it.
