### ISSUE TITLE
nix-shell sets $PYTHONPATH, normal environment does not

### ISSUE THREAD

**Issue by samvher** [NixOS/nixpkgs#22548]
## Issue description
I'm trying to install python with some packages, for use by a vim plugin (CoVim). This means I want that setup to be available in my regular shell. However, even though I can properly import all the packages in a python prompt, vim cannot access them because the `$PYTHONPATH` is not set. When I make the same packages available with nix-shell, it sets the `$PYTHONPATH` and everything works fine.

Is there some way I can generate the `PYTHONPATH` in my regular environment?

### Steps to reproduce
I put this in python.nix:
```
with import <nixpkgs> {};
pkgs.python27.withPackages (ps: with ps; [ twisted argparse service-identity ])
```
and activated with `nix-env -if python.nix`. Running `import twisted` in python works fine, but loading CoVim gives an error. `echo $PYTHONPATH` shows the variable is empty.

If I run `nix-shell -p pythonPackages.twisted` and then `echo $PYTHONPATH` everything I need is there.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
NixOS version 16.09.1650.d2cd8a0 (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
16.09.1650.d2cd8a0

**Comment by FRidh** [comment]
> I'm trying to install python with some packages, for use by a vim plugin (CoVim). This means I want that setup to be available in my regular shell. However, even though I can properly import all the packages in a python prompt, vim cannot access them because the $PYTHONPATH is not set. 

Other programs should not rely on a global `$PYTHONPATH`. Instead, they should make sure they point to the Python environment that should be used.

> When I make the same packages available with nix-shell, it sets the $PYTHONPATH and everything works fine.

`nix-shell` is a shell for development of packages/expressions. A setup-hook builds up `$PYTHONPATH`. This shouldn't be relied on outside of `nix-shell`.

> and activated with nix-env -if python.nix. Running import twisted in python works fine, but loading CoVim gives an error. echo $PYTHONPATH shows the variable is empty.

That's because `CoVim` is not aware of this Python environment.

Do we have `CoVim` in Nixpkgs? I cannot find it. In any case, this should be fixed in the expression of `CoVim`.

**Comment by samvher** [comment]
Actually I installed `CoVim` with Vundle - so I should use nix to install vim plugins?

When I look at the `CoVim` source code I don't actually see any reliance on `$PYTHONPATH` though, it simply calls `python` in a `vim` file. Also when I run `!which python` inside `vim` it gives me the same path that I get when running it `which python` in my regular shell, that makes it surprising to me that the environment is different.

**Comment by FRidh** [comment]
Whenever a program needs another program during runtime, we wrap the first with a wrapper that adds the second program to `PATH`. With Nix you can have multiple Python environments simultaneously, much like `virtualenv`. Now, I don't know how you use `CoVim` and what Python environment you expect it to use.

If the vim file has calls `python`, and you have the Python environment installed in your profile, as you described, then vim should be able to find it and everything should work. `PYTHONPATH` is indeed still empty, because we don't use it at all.

Anyway, I'm not really familiar with vim or Vundle so I can't help you much there. I am closing this issue because its not a Nixpkgs issue, but if you have more questions, feel free to write them here. For a question like this you might also want to write to the nix-dev list.

**Comment by samvher** [comment]
In my NixOS environment I'm not really using python so I intended to just have a single, global one. I expected that `vim_configurable` would in fact make sure that python is available, because it has python support. But maybe something goes wrong there - perhaps `vim_configurable` requires only python and does not call its packages, somehow.

Your second paragraph seems counter to my experiences :) It's what I expected as well though, that's why I put the issue here.

I guess if I will want to use `CoVim` (I actually never tried it before) I will just have to package it. I haven't done that before, but I will try to make some time for that.
