### ISSUE TITLE
Build failure: diffoscope

### ISSUE THREAD

**Issue by NotAShelf** [NixOS/nixpkgs#226357]
### Steps To Reproduce

1. Try to rebuild with [my system configuration](https://github.com/notashelf/Nyx)
2. observe logs

### Build Logs
https://p.frzn.dev/1f2

### Additional context

According to nix-tree, the offending package is build-tools that is added by `diffoscope`. Building diffoscope, however, seems to be fine.

`libgcc_s.so.1 -> not found!`

### Notify maintainers

@hadilq seems to be the last person to touch it

### Metadata

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.2.10, NixOS, 23.05 (Stoat), 23.05.20230411.3fb8eed`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/store/9lkm36ac7hfl7f9h2z9dj00mdh30mjhi-source`
```

**Comment by hadilq** [comment]
Thank you for reporting. I'll take a look.

**Comment by hadilq** [comment]
I can reproduce this one, but I cannot find any changes in the androidenv directory related to this new problem. It certainly occurred because of changes in the dependency packages. As your log also shows

```
auto-patchelf: 2 dependencies could not be satisfied
error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by emulator
error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by emulator-check
```

`emulator` and `emulator-check` need `libgcc_s.so`, which apparently it doesn't exist anymore! Interesting thing is that locally I completely ignored the `patchInstructions` phase in `build-tools.nix` and `emulator.nix`, which supposed to be responsible to call `auto-patchelf`, but it still occur, so currently I don't understand in which line in the androidenv directory this happens! I'll report more if I found anything new.

**Comment by hadilq** [comment]
found the issue. It's in the `tools.nix`. I just needed to add the `stdenv.cc.cc` dependency. I'll create the PR soon :)
