### ISSUE TITLE
Build failure: mysql80

### ISSUE THREAD

**Issue by jnvrs** [NixOS/nixpkgs#226673]
### Steps To Reproduce
Just add mysql80 to your System

### Build log

```
467a468
> #include_next <stdint.h>
CMake Error at /build/mysql-8.0.32/cmake/do_abi_check.cmake:121 (MESSAGE):
  ABI check found difference between
  /build/mysql-8.0.32/include/mysql/services.h.pp and
  /build/mysql-8.0.32/build/abi_check.out


make[2]: *** [CMakeFiles/abi_check.dir/build.make:70: CMakeFiles/abi_check] Error 1
make[1]: *** [CMakeFiles/Makefile2:2990: CMakeFiles/abi_check.dir/all] Error 2
```

### Additional context
The build also failed in Hydra
https://hydra.nixos.org/build/215738828

### Notify maintainers
@orivej

**Comment by orivej** [comment]
I've briefly looked into this and it seems that mysql configure does something strange, it preprocesses its headers that include standard C headers with `gcc -nostdinc` (to do an ABI check). (Another strange thing is that some of the included headers are C++ only since they do `#include <cstdint>`, but the compiler used is `gcc`, not `g++`, and it fails to process these headers if I remove `-nostdinc` from the call.)

I am not sure that I will resolve this in a timely manner, but probably this can be worked around with gcc10StdenvCompat.

**Comment by orivej** [comment]
> probably this can be worked around with gcc10StdenvCompat

Some dependencies of mysql80, protobuf and icu, use symbols of libstdc++ from gcc 12; mysql80 fails to build with gcc10StdenvCompat or gcc11Stdenv (unless the dependencies are also built with older gcc).

**Comment by jerith666** [comment]
My bisect hasn't quite completed yet, but it's looking like #209870 is the culprit here.

**Comment by jerith666** [comment]
Yep, fdd49f1bcd8 from that PR is the last good commit, then there's a series of commits that fail with undefined variables, then 5f57c2e0f97 is where the build gets far enough to encounter this error.

I guess I'll add this to the project they created for follow-ups to that PR.

I'm pretty out of my depth here in terms of ideas for a fix.  I found https://bugs.mysql.com/bug.php?id=61297 which mentions running `make abi_update` to fix a similar issue a couple years back, but I'm not sure if that makes sense in nixpkgs or not.

**Comment by wegank** [comment]
This should have been resolved in `staging-next`, see https://hydra.nixos.org/job/nixpkgs/staging-next/mysql80.x86_64-linux.

**Comment by amjoseph-nixpkgs** [comment]
> This should have been resolved in `staging-next`, see https://hydra.nixos.org/job/nixpkgs/staging-next/mysql80.x86_64-linux.

If it isn't, please ping me and I will investigate this.
