### ISSUE TITLE
16.09 channel is not updating

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#22699]
Failures because of 8dc4af61dd6b569f5b582074ad422cb8637db096 and/or fd7e5cbae5faf95b2e812b5a97d1745060e83ce6.

cc @dtzWill @vcunat

**Comment by vcunat** [comment]
It's the glibc update.  I was just about to file an issue.  There are two security fixes in the bump, which is why I backported it, but there are also many other changes, so it's not very clear whether to do this potentially disruptive update on 16.09 or not.

**Security**: the first issue only affects ARM 32-bit EABI, so I suppose we can ignore it; [the other issue](https://sourceware.org/bugzilla/show_bug.cgi?id=18784) has been known since 2015 summer, so it's probably no big deal either.

**Comment by vcunat** [comment]
So far I have patches for `host` and `fontconfig` to fix them; I don't know what other failures might be lurking.

**Comment by FRidh** [comment]
@vcunat unrelated, but could you cancel http://hydra.nixos.org/eval/1331547  I think I accidentally pushed a mass-rebuild to master (the argparse change).

**Comment by vcunat** [comment]
I just now independently located the commit causing it :-) Done.

**Comment by vcunat** [comment]
I reverted the glibc bump on 16.09, at least for now.

**Comment by grahamc** [comment]
That seems fine, @vcunat. Thank you :)

**Comment by grahamc** [comment]
16.09 has updated to 019dcc3
