### ISSUE TITLE
update-luarocks-packages script broken

### ISSUE THREAD

**Issue by de11n** [NixOS/nixpkgs#227475]
I am trying to use `maintainers/scripts/update-luarocks-packages` but I cannot get it to run on either Linux or macOS. How are Lua packages getting updated without a working update script? I'd like to add a few packages and this script seems to be *the* way to do it.

**Comment by teto** [comment]
hard to help without some basic information including:
-  what version did you run
- what arguments
- what errors did you see

**Comment by de11n** [comment]
I'm not sure if I'm running it properly. If you can point me to good docs for this process then that might help.

When I check out the latest `master` it fails with something silly:

```
$ git rev-parse HEAD
8c6d3cbdc0dab17d4affb8fa75bfd216cacdd33a
$ maintainers/scripts/update-luarocks-packages
  File "/local/apps/camerone/nixpkgs-public-contrib/maintainers/scripts/update-luarocks-packages", line 206
    editor.run()
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by de11n** [comment]
If I fix that error it just gives me a different one:

```bash
$ maintainers/scripts/update-luarocks-packages
the update member function should be overriden in subclasses
```

(Technically it's not an error but it probably should have been.)

**Comment by teto** [comment]
indeed, I  introduced the bug recently. Here is a fix https://github.com/NixOS/nixpkgs/pull/227513 . The script still fails because lua-iconv fails (a known issue I am looking forward to see solved).
The updater runs https://github.com/nix-community/luarocks-nix on the packages listed in the csv file.
`luarocks nix lua-iconv --verbose` shows that the rockspec mentions a bad url https://luarocks.org/modules/luarocks/lua-iconv/7-3 . 
You can work around it by commenting the lua-iconv line in the maintainers/scripts/luarocks-packages.csv , maybe downgrade lua-iconv or propose a fix for it upstream.

Out of curiosity what lua packages are you interested in adding to nixpkgs ?
