### ISSUE TITLE
Darcs broken in master

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#22765]
## Issue description

I cannot find a version of Haskell packages that would allow me to build Darcs.

### Steps to reproduce

`nix-build '<nixpkgs>' -a darcs`

## Technical details

NixPkgs cda4a4dcfce277b93b87be49945ed44f61483ee1 (~2017-02-13 22:30 UTC)
x86_64, sandboxed builds

**Comment by 7c6f434c** [comment]
a4ec1841da14fc98c5c35cc72242c23bb698d4ac works

8821b3899ec2d1dc89d3a8347c5af8173ab90c81 and 5d3bb96f622e62062945aa8e70a827449c21f686 and 6a472cf4c1b78580de79c79ca7d7b714f4d8d36e fail
with `fgl-5.5.3.0` complaining about `hspec >=2.1 && <2.3` not being available.

@peti ?

**Comment by 7c6f434c** [comment]
Just checked: `hspec` is passed to `fgl`, but it is `hspec` 2.4

**Comment by peti** [comment]
Many package are broken because we've switched to LTS 8.x. I've posted an announcement to the nix-dev mailing list a few days ago. PRs to fix these issues are welcome.

**Comment by 7c6f434c** [comment]
What your announcement lacks is the preferred order of approaches to fixes. For complicated partially auto-generated expression sets that sounds like a good thing to specify explicitly.

Is the expected order of approaches «jailbreak, if that fails add a previous version of a dependency»? Is the stuff supposed to go into `configuration-common.nix`? If I know for sure that I am changing a package that just did not load at all, is it OK to just commit the change that makes it work somehow or is it still better to do a PR?

**Comment by peti** [comment]
Personally, I prefer issues like that one to be resolved by, first of all, reporting it upstream. Once that's done, local actions inside of Nixpkgs in order of preference are:

 1. `doJailbreak` the build,
 2. `dontCheck` the build,
 3. add old package versions to Nixpkgs and override the build inputs.

Now, in case of `darcs` (1) is almost certainly not going to work and (2) is what we do anyway because the tests did not succeed on Nixpkgs for older versions of `darcs` either. So (3) is probably the only realistic option. You *might* get away with manually jailbreak the `darcs.cabal` file `sed` or by adding appropriate patches, because jailbreaking actually might help, it's just that `jailbreak-cabal` can't do it properly on its own.

**Comment by 7c6f434c** [comment]
Well, as I have mentioned the build fails at `fgl` (Darcs has its own workarounds in the top-level `darcs` expression). Jailbreaking the `hspec` requirement does seem to be enough.

**Comment by 7c6f434c** [comment]
Fixed in 3508b4832fbed06db1d0dd6bbf6ca9c1c3c3ed8e

**Comment by 7c6f434c** [comment]
Thanks, `doJailbreak` being preferable to `dontCheck` is a useful reminder.

**Comment by peti** [comment]
Thank you for your help!
