### ISSUE TITLE
QuickCheck unable to build due to missing semigroups dependency

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#22802]
Hi @peti, after updating `nixpkgs` yesterday (now at 3a0efcc4ca59cc3ebb3676e47b05f05dfbc6c9d2), I have many Haskell packages that are no longer building. The strangest problem is that `QuickCheck` will not build due to a missing dependency:

```
Configuring QuickCheck-2.9.2...
Setup: At least the following dependencies are missing:
semigroups >=0.9
builder for ‘/nix/store/i46kwj03kkla7c59327sh9vh88djci41-QuickCheck-2.9.2.drv’ failed with exit code 1
```

Two things that are odd about this:

1. `semigroups` in `hackage-packages.nix` is set to 0.18, which should satisfy the dependency.

2. Setting `QuickCheck = doJailbreak super.QuickCheck;` as an override in my `config.nix` has no effect on the problem, although it does work for other packages.

This just starting happening within the last day.

**Comment by Dridus** [comment]
@jwiegley the jailbreak won't work because QuickCheck's nix expression doesn't depend on semigroups at all, so jailbreaking the version bounds won't help.

looking into QuickCheck's cabal it seems this is a proper behavior as it should only depend on semigroups for GHC < 8.0:

https://github.com/nick8325/quickcheck/blob/master/QuickCheck.cabal#L137

but nixpkgs overall now depends on ghc 8.0.2. Are you overriding your GHC version perhaps? If so you might need to explicitly override QuickCheck.

**Comment by peti** [comment]
@jwiegley, you seem to be using the `ghc7103` package set, which is kind-of unsupported I'm afraid.

**Comment by jwiegley** [comment]
I even forgot that I was also building ghc7103, in addition to ghc801.  Thanks for catching that, I'll just abandon the older version then.
