### ISSUE TITLE
snakemake should be moved to python-modules and built with buildPythonPackage

### ISSUE THREAD

**Issue by bcdarwin** [NixOS/nixpkgs#228356]
(because it has a Python API)

**Comment by renatoGarcia** [comment]
When first adding Snakemake to nixpkgs, we had a discussion like this. The understanding at the time was that Snakemake, same as [deluge](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/applications/networking/p2p/deluge/default.nix) for example, is more an application incidentally written in Python than a Python library.

Because that, we have decided put it not as a Python module. The Snakemake [last version](https://snakemake.readthedocs.io/en/stable/snakefiles/utils.html) not even has the Python API on his documentation.

About the `buildPythonPackage`, would exist any advantage of using it over `buildPythonApplication`?
Maybe are you having the same bug as me? As reported on #230376?
