### ISSUE TITLE
http-only, and https-enabled mirror list for tarballs.nixos.org

### ISSUE THREAD

**Issue by alexanderkjeldaas** [NixOS/nixpkgs#2289]
The tarballs.nixos.org domain is a single point of failure for NixOS, and it should be converted into a mirror://... scheme.

For a subset of these tarballs, namely the tarballs required during the stdenv bootstrapping process, http-only access is a requirement.  The bootstrap process uses a curl that does not support SSL.  For the others, https is also reasonable.  A majority of distribution systems such as github, gdrive and others are now SSL-only so this distinction is important.

I suggest that tarballs.nixos.org is split into two namespaces,
mirror://nixos-http/...  and mirror://nixos/...

**Comment by grahamc** [comment]
Since tarballs.nixos.org is on CloudFront, the only real realm of possible failure is if the domain expires or DNS gets mucked up. That seems within the realm of acceptable risk. Secondly, tarballs.nixos.org already seems to support http and https, so I'm not sure what the enhancement is to be made here.

**Comment by vcunat** [comment]
I also don't see what's the problem with this.
