### ISSUE TITLE
emacsWithPackages ignores Applications dir on darwin

### ISSUE THREAD

**Issue by sellout** [NixOS/nixpkgs#22893]
## Issue description

emacsWithPackages creates wrappers for everything in `$emacs/bin/`, but on darwin (or whenever `$emacs/Applications/` exists), it should do the same for `$emacs/Applications/Emacs.app/Contents/MacOS/`.

## Technical details

* System: Mac OS X Sierra
* Nix version: 1.11.6
* Nixpkgs version: 17.03pre100898.e63d15f

**Comment by jwiegley** [comment]
@matthewbauer The solution you've given for this issue prevents me from being able to wrap Emacs using a different executable name -- essential if I'm to effectively run two copies of Emacs on my machine, one for ERC (for example) and one for editing.

All I need is an ability to specify the name of the app, rather than assuming it is "Emacs". I'll create a PR and link to this issue.
