### ISSUE TITLE
Package request: update of Krita to version 5.1.5 (current is 5.1.3)

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#229374]
**Update krita package from 5.1.3 to 5.1.5**

* homepage URL: https://krita.org/en/download/krita-desktop/
* source URL: https://krita.org/en/download/krita-desktop/
* platforms: linux

![Screenshot from 2023-05-02 00-08-48](https://user-images.githubusercontent.com/23100970/235540192-0a81a641-f114-4aa9-95c8-a45936df95b9.png)

![Screenshot from 2023-05-02 00-09-49](https://user-images.githubusercontent.com/23100970/235540262-2e444d51-33d8-40a9-9f75-4447ecfa960b.png)

**Comment by pinn3** [comment]
It's up to date, check the unstable channel

**Comment by KCynk** [comment]
@pinn3 but this version should be in stable not in unstable

**Comment by pinn3** [comment]
@KCynk Why should it be? It was updated to 5.1.4 in December and 5.1.5 in February, both outside of the stable release schedule. It will very likely be included in 23.05, but you could ask the maintainers to backport it

**Comment by KCynk** [comment]
> @KCynk Why should it be? It was updated to 5.1.4 in December and 5.1.5 in February, both outside of the stable release schedule. It will very likely be included in 23.05, but you could ask the maintainers to backport it if you need it in an older release

In my opinion, if the software is released by the vendor it means that the package is stable and can be added to the stable branch.

In 'unstable' in my opinion should be the latest stable and 'nightly builds'

But as I said this is my understanding of 'stable' and 'unstable'

**Comment by pinn3** [comment]
Good points! I mostly agree with you. The one thing I disagree with is the software stable state should equal the package state.

This is because Nix packages are built from source, sometimes with various patches to make them work with the Nix ecosystem.

Setting that aside, I do think it's perfectly valid to ask for having it be backported to an earlier release, since it's just a patch version (so it should only contain backwards compatible fixes and such).

Ping @abbradar @sifmelcara @nek0

**Comment by sifmelcara** [comment]
> In my opinion, if the software is released by the vendor it means that the package is stable and can be added to the stable branch.

The difference between stable channel and unstable channel in NixOS has very little to do with package being stable or not. The `nixos-22.11` stable channel is basically a snapshot of nixpkgs at Nov. 2022 + bug fixes and security fixes. That's why stable channels are stable (the package versions are stable).

> In 'unstable' in my opinion should be the latest stable and 'nightly builds'

People generally don't check-in nightly builds and unstable software into nixpkgs. Packages in nixos-unstable branch are expected to be stable upstream releases

Feel free to install krita from unstable channel as a workaround, or wait until nixos-23.05 release
