### ISSUE TITLE
purescript-0.10.7 fix dependences

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#23036]
Trying to install purescript, it says:
<pre>Configuring purescript-0.10.7...
Setup: Encountered missing dependencies:
aeson >=0.8 && <1.0,
http-client >=0.4.30 && <0.5,
pipes >=4.0.0 && <4.3.0,
websockets ==0.9.*</pre>
but there are only
aeson-0.7.0.6, aeson-1.0.2.1, aeson-1.1.0.0,
http-client-0.5.5, http-client-0.5.6
pipes-4.3.2
websockets-0.10.0.0
<pre># nixos-version                                                          
17.03pre101636.183eeb3 (Gorilla)
# nix-env --version                                                         
nix-env (Nix) 1.11.6
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion               
"17.03pre101636.183eeb3"</pre>

**Comment by domenkozar** [comment]
@peti how do we deal with these?

**Comment by peti** [comment]
My favorite solution is to lobby upstream to support recent versions of their dependencies!

We can provide those old versions in Nixpkgs, too, of course, but usually these packages subsequently require a whole zoo of other old versions, too, and then things get messy and inconvenient.

**Comment by domenkozar** [comment]
Let's do both. Can you teach me how to do the latter?

**Comment by themoritz** [comment]
Seems the bounds were already loosened: https://github.com/purescript/purescript/commit/e336bbae159d556d2ee9148e3a1a9a2dca47adcf

So we just need a purescript release?

**Comment by peti** [comment]
Fixing the current build of purescript in Nixpks works as follows:

1. Create an `overrideScope` for `purescript` in `configuration-common.nix` and pass the appropriate versions of the required libraries. Since those versions don't exist in Nixpkgs yet, it's easiest to conjure them up as `aeson = callHackage "aeson" "0.11.3.0" {}`, etc.

2. Test the build. If other version conflicts surface, them the override has to be extended.

3. Once the build works, add all new library versions to the `extra-packages` section in `configuration-hackage2nix.yaml` (and make sure to add a comment saying that you're adding them because of purescript version x.y.z).

4. Run `hackage2nix` to re-generate the package set. The script update-nixpkgs.sh can be used as an example of how that tool is run and what inputs it needs. If you don't want to bother, just push the changes in `configuration-hackage2nix.yaml` to `master` or to `haskell-updates` in my Nixpkgs fork and wait for the automatic process to re-generate the package set for you.

5. Edit the `overrideScope` to refer to packages by their proper attribute names rather then using `callHackage` and push the change.

**Comment by domenkozar** [comment]
Thanks @peti - this is now fixed.
