### ISSUE TITLE
It's not clear to me how to update go packages made with go2nix

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#23416]
I decided to try to update `etcd` to 3.1.2 this evening. I clone the `etcd` repo, follow the instructions in the `go2nix` readme. I get no errors during the process, but then when I transport the `deps.nix` it generated to nixpkgs, the `etcd` build fails. It's clear that there was some successful `go2nix` process that generated the current `etcd` expression, because the current version works fine, but there's no indication of what that process is, and I don't know how to derive it automatically.

I'm using the example of `etcd` but it's obviously broader than that, since I've encountered other go projects in the past that needed to be massaged a bit before `go2nix` would give me a proper dependency set.

cc @offlinehacker @kamilchm who are closest to the specific examples at hand

**Comment by kamilchm** [comment]
There're something in etcd tools that go2nix can't handle properly now.
I'll take a deeper look at it and try to make better/easier go2nix or Nix documentation with cases from `etcd` as examples.

**Comment by copumpkin** [comment]
@kamilchm thanks! but the current expression looks like it was generated by `go2nix` (except for the `fetchFromGitHub`) so I'm a bit confused how that one came into existence

**Comment by kamilchm** [comment]
I looked better on ectd structure. Etcd moved from Godep to glide in 3.1.0 https://github.com/coreos/etcd/commit/d5900e8b63904daaf63d315d4c43fdcaaf023720#diff-dfff0a7fa1a55c8c1a4966c19f6da452 and this can cause different dependency resolving by go2nix.

But I did different experiment. Etcd commands vendor dir seems to have all commands dependencies included https://github.com/coreos/etcd/tree/v3.1.3/cmd
So instead of building all packages found in etcd repo, I explicitly set only etcd commands to build, which can be built without any external dependencies -> https://github.com/kamilchm/nixpkgs/commit/6a7fdfd6169f422ca4132fa363ac2df49a3bc85c

What stopped me from submiting it, is the `nixos/tests/etcd-cluster.nix` which reports one error. But I'm not an etcd user and don't know if it's not something that changed and can/should be configured after 3.0 -> 3.1 move. @offlinehacker could you look at it?

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by kamilchm** [comment]
Recent version of etcd is [using go modules](https://github.com/etcd-io/etcd/commit/527ff8216d0ab5e0a8e9604d0d9f6b226af3d510#diff-37aff102a57d3d7b797f152915a6dc16).
You can try to use [buildGoModule](https://nixos.org/nixpkgs/manual/#ssec-go-modules) or alternatively fallback to https://github.com/adisbladis/vgo2nix

**Comment by adisbladis** [comment]
Privately I've been packaging non go-modules applications by running something `go mod && vgo2nix`.

**Comment by offlinehacker** [comment]
I'm closing this as etcd is updated and it should be clear how to do an update and most of the packages migrate to go modules.
