### ISSUE TITLE
nixos.python35Packages.jupyter collides with itself (or its dependencies)

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#23466]
## Issue description

Trying to set up a single Python environment with [Jupyter](https://jupyter.org/) through `~/.nixpkgs/config.nix` fails unless `ignoreCollisions = true;` is added because `nixos.python35Packages.jupyter` collides with itself.

### Steps to reproduce

`~/.nixpkgs/config.nix`:
```nix
{
  packageOverrides = pkgs: with pkgs; {
    myPythonEnv = python35.buildEnv.override {
      extraLibs = with python35Packages; [jupyter];
    };
  };
}
```
Try to install `myPythonEnv`:
```
sh-4.3$ nix-env -iA nixos.myPythonEnv
installing ‘python3-3.5.2-env’
these derivations will be built:
  /nix/store/anwfhwmgniv4wafvjxn7frv16p4n3ppq-python3-3.5.2-env.drv
building path(s) ‘/nix/store/fzkn2zb1fr6bihzd4aw8sl1p88d4kpfr-python3-3.5.2-env’
collision between `/nix/store/4xdbh4cbwmyfdlrby01vpnzgssjmib7m-python3.5-jupyter-1.0.0/lib/python3.5/site-packages/jupyter.py' and `/nix/store/lxipvgq8p9kk99jzd95iijs2q2vrqsf4-python3.5-jupyter_core-4.1.1/lib/python3.5/site-packages/jupyter.py'
builder for ‘/nix/store/anwfhwmgniv4wafvjxn7frv16p4n3ppq-python3-3.5.2-env.drv’ failed with exit code 25
error: build of ‘/nix/store/anwfhwmgniv4wafvjxn7frv16p4n3ppq-python3-3.5.2-env.drv’ failed
```

Tested with a fresh user account, confirmed on a second machine.

Adding `ignoreCollisions = true;` allows installation to succeed.

## Technical details

* NixOS: `16.09.1803.40de598 (Flounder)`
* Nix version: `1.11.6`
* Nixpkgs version: `16.09.1803.40de598`

**Comment by FRidh** [comment]
Thanks for reporting.

`jupyter` is a metapackage depending on several packages. It doesn't do anything really. When you import from `jupyter` it forwards the call to `jupyter_core`.

I've added a priority so that it now uses the file from `jupyter_core` by default. The fix is in master, release-16.09 and release-17.03 so you should have it in your channel shortly.

**Comment by alexeymuranov** [comment]
Thanks!

**Comment by alexeymuranov** [comment]
@FRidh, by the way, in my opinion this mode of setting up Python user environment should be made more prominent in the [documentation](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.md), something like Quick Start for a Tranditional User (non-developer).  Currently it is somewhere in the FAQ, but it takes time to figure out that this is exactly the method that just works.

I am not sure if documentation in this format needs a FAQ section (full text search will allow to find information without reading through FAQ).  If this method is kept in FAQ, maybe at least it can be made more prominent in FAQ.

If it is ok, i may try to edit this documentation, but i am not sure if i am qualified enough yet.

**Comment by FRidh** [comment]
What method of setting up an environment do you mean? `buildEnv`, or `withPackages`? The latter is used throughout the section. The former was originally used, but, because `withPackages` covers most use cases it was replaced with that in the docs.

You can always open a PR with documentation changes. Improvements are very much appreciated!

**Comment by alexeymuranov** [comment]
I meant `packageOverrides` in `~/.nixpkgs/config.nix` in general.  For a newcomer this is not obvious, i was reaching for the `pip`.  I will think about a PR.
