### ISSUE TITLE
okular: missing gschemas

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#23474]
## Issue description

Opening a file dialog leads to a crash with:
```
GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```

## Technical details

* System: 17.03 25c590f9 (probably the same on master)

**Comment by vcunat** [comment]
This is surprising to me.  Apparently qtbase can decide to use `lib/qt5/plugins/platformthemes/libqgtk3.so` and thus show gtk3 file dialogs.  Those lead to a crash unless the executable can find the schemas; we typically solve this by a wrapper that extends `$XDG_DATA_DIRS` by `${gtk3.out}/share/gsettings-schemas`. (IIRC `wrapGAppsHook` does this automatically, maybe conditioned on having `gtk3` in build inputs.)

I suspect all Qt apps may suffer from this problem. /cc @ttuegel.

**Comment by ttuegel** [comment]
Yes, all Qt applications will have this problem. Qt 5 already depends on GTK 3, so I think it would be fine to extend `makeQtWrapper` to depend on it also.

Related: we really *really* need an extensible interface for `wrapProgram` in Nixpkgs. To implement this, I will have to copy `wrapGAppsHook` into `makeQtWrapper`. We can't have both run because that will just stack wrappers on top of wrappers...

**Comment by vcunat** [comment]
IIRC `wrapGAppsHook` is extensible.  Packages can define setup hooks that extend `gappsWrapperArgs`.  Maybe it doesn't cover all use cases or something...

**Comment by ttuegel** [comment]
1. It has built-in functionality: just because I want an extensible wrapper doesn't mean I want all of the presets that come with `wrapGAppsHook`.
2. It wraps everything it can get its hands on, which is not correct.

**Comment by abbradar** [comment]
Adding this to the milestone -- seems pretty serious (all Qt applications terminate for me now when I try to open a file).

**Comment by ttuegel** [comment]
I can't do anything about this on the Qt end except to disable all GTK support. Qt 5 detects GTK 3 at runtime for desktop integration; there is no build dependency. I can't add GTK as a dependency to every Qt program, so I can't set this in wrappers. Either I completely disable GTK integration in Qt, or you patch GTK to find its own dependencies. (Fair is fair: I've patched Qt several times for the same reason.)

**Comment by abbradar** [comment]
I wanted to propose this very idea -- since GTK applications don't work without `gsettings_desktop_schemas` to this extent it would be easier to just patch it into GTK.

**Comment by abbradar** [comment]
I'm working on that now; this will require patches to both GTK and Glib (I also want to patch dconf into GTK so settings for file choosers and other components would work as expected). On the good side this will actually allow us to reduce closure of many applications: most of non-GNOME ones don't actually require `gsettings_desktop_schemas`, just the schemas from GTK 3 itself.

@ttuegel I'm interested, how does Qt find GTK if it's not a build dependency?

**Comment by abbradar** [comment]
After a little more investigation:

1. Instead of (very hacky) patches we should just require everyone to properly use `wrapGAppsHook` instead of custom wrappers; it should also add `dconf` by default to ensure GTK can save its settings.
2. Qt 5 does actually have a dependency on GTK3 now (in `nix-store -qR`) so what about adding needed additional wrapping to `wrapQtProgram`? One needs to add paths to GTK3 gsettings schemas and GIO paths to dconf; I'll try to do it later if @ttuegel agrees with the general direction.

**Comment by ttuegel** [comment]
> Qt 5 does actually have a dependency on GTK3 now (in nix-store -qR) so what about adding needed additional wrapping to wrapQtProgram?

I thought it was supposed to `dlopen(libgtk)` at runtime to avoid retaining a dependency. Either that is broken or I misunderstood how it works.

> One needs to add paths to GTK3 gsettings schemas and GIO paths to dconf; I'll try to do it later if @ttuegel agrees with the general direction.

That would be fine with me. You will need to fork `make-qt-wrapper.sh` because Qt < 5.7 do not have GTK support, but Qt >= 5.7 do have it. There is also a separate setup hook `make-qt-wrapper-darwin.sh` for Darwin. I'm not sure if `qgtk` is disabled on Darwin, but it it probably should be. (Ostensibly, the point of `qgtk` is for Qt apps to integrate into GTK-based desktop environments, but there aren't such on Darwin!)

**Comment by abbradar** [comment]
@ttuegel Quick question: why do you use `import` for calling Qt instead of `callPackage`? I ask because I need to add several arguments and wonder if I can just use `callPackage` instead.

**Comment by ttuegel** [comment]
Two reasons: First, I have been reprimanded in the past for using `callPackage` on a thing that is not a package. More importantly, `callPackage` uses `makeOverrideable`, which will break the call to `makeScope` in the Qt 5 package set.

By the way, I'm putting together something to supplant `makeQtWrapper` and maybe `wrapGAppsHook` which would probably fix this by coincidence:
https://github.com/ttuegel/nixpkgs/tree/wrapProgramsHook
It may or may not be of interest.

**Comment by abbradar** [comment]
I wanted to do just that too, thanks for linking otherwise we would duplicate the work ^_^

But I'm not sure if we would be able to get this into release so I wanted to make something minimal meanwhile. Is that a good idea or maybe we should just pursue more fundamental solution?

**Comment by ttuegel** [comment]
> But I'm not sure if we would be able to get this into release so I wanted to make something minimal meanwhile. Is that a good idea or maybe we should just pursue more fundamental solution?

No, you're absolutely right, a minimal solution is what we want for the release.
