### ISSUE TITLE
texlive-bin regression update

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#235872]
```
-------------------------------------------------------------------------
Debian LTS Advisory DLA-3427-2                [debian-lts@lists.debian.org](mailto:debian-lts@lists.debian.org)
https://www.debian.org/lts/security/                      Markus Koschany
May 31, 2023                                  https://wiki.debian.org/LTS
-------------------------------------------------------------------------

Package        : texlive-bin
Version        : 2018.20181218.49446-1+deb10u2
CVE ID         : CVE-2019-18604
Debian Bug     : 1036891

It was discovered that the patch to fix CVE-2023-32700 in texlive-bin, released
as DLA-3427-1, was incomplete and caused an error when running the lualatex
command. 

The following security vulnerability has been addressed as well.    

CVE-2019-18604

     A flaw was found in axohelp in axodraw2. The sprintf function is
     mishandled which may cause a stack overflow error.

For Debian 10 buster, this problem has been fixed in version
2018.20181218.49446-1+deb10u2.

We recommend that you upgrade your texlive-bin packages.

For the detailed security status of texlive-bin please refer to
its security tracker page at:
https://security-tracker.debian.org/tracker/texlive-bin

Further information about Debian LTS security advisories, how to apply
these updates to your system and frequently asked questions can be
found at: https://wiki.debian.org/LTS
```
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036891

cc @apfelkuchen6 @xworld21

**Comment by gucci-on-fleek** [comment]
I don't think that either of these affect you.

CVE-2019-18604 was [patched upstream in October 2019](https://github.com/TeX-Live/texlive-source/commit/9216833a3888a4105a18e8c349f65b045ddb1079#diff-987e40c0e27ee43f6a2414ada73a191a), so it's automatically fixed in TL2020 and later. You appear to be using TL2023, so you should be fine.

For CVE-2023-32700, Debian only cherry-picked 1 of the 2 necessary commits to fix the vulnerability. You [appear to be using my patch](https://github.com/NixOS/nixpkgs/blob/7285c1973d91dc4764efc2dfea077d8df0943475/pkgs/tools/typesetting/tex/texlive/bin.nix#L207-L208) which doesn't have this issue.

**Comment by veprbl** [comment]
@gucci-on-fleek Thank you for checking this! We are currently shipping TL2022:
https://github.com/NixOS/nixpkgs/blob/3f697e808b31a955462bc0b20b229d4072c99aa7/pkgs/tools/typesetting/tex/texlive/default.nix#L122
