### ISSUE TITLE
Steam fails to launch on unstable/master. CA cert error

### ISSUE THREAD

**Issue by syboxez** [NixOS/nixpkgs#236561]
### Describe the bug
Steam fails to launch with the error message: `error: Peer certificate cannot be authenticated with given CA certificates`

### Steps To Reproduce
1. Launch Steam

Also tested moving ~/.local/share/Steam and launching fresh, and I get the same error logged to my terminal, but with a blank logon screen instead of crashing outright.

### Expected behavior
I expect Steam to launch normally.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/12841859/4b1250c6-d534-487d-b5dd-dbb8950cab4c)

### Additional context
Not sure if relevant, but also repeatedly get ```dirname: /home/syboxez/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libattr.so.1: version `ATTR_1.3' not found (required by dirname)```

### Notify maintainers
@jagajaga  @jonringer  

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5-xanmod1, NixOS, 23.11 (Tapir), 23.11pre492103.4729ffac6fd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by devusb** [comment]
Same after `nix flake update` today -- my metadata:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.11 (Tapir), 23.11.20230606.4729ffa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.0`
 - nixpkgs: `/nix/store/ain1lgmwvhc90yhw1rki6c7xhb0jp2hj-source`
 ```
Anecdotally I get `error: Peer certificate cannot be authenticated with given CA certificates` on my previous generation where Steam works and current where it doesn't work, but `dirname: /home/username/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libattr.so.1: version `ATTR_1.3' not found (required by dirname)` is only present on a generation that does not work.

**Comment by lugeha** [comment]
Here's a workaround

 programs.steam = {
    enable = true;
    package = with pkgs; steam.override { extraPkgs = pkgs: [ attr ]; };
  };

**Comment by samueldr** [comment]
The certificate error is likely from `breakpad` trying to upload the "minidump" for Valve to know about problems. You would have to find the error which will be just before `Installing breakpad exception handler for appid(steam)`. If you can, report back with that problem *and* the line, since the line contains the version number (among multiple locations).

I can't guarantee you're hitting the same issue, but there seems to have been some breakage in the latest version of Steam that affects us. On my end, version `1686092969`.

Cross-referencing:

 - https://github.com/ValveSoftware/steam-for-linux/issues/9321#issuecomment-1581566134
 - https://github.com/Jovian-Experiments/Jovian-NixOS/issues/94

**Comment by K900** [comment]
I'm pretty sure the real issue is earlier:

```
dirname: /home/k900/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libattr.so.1: version `ATTR_1.3' not found (required by dirname)
```

**Comment by syboxez** [comment]
@K900 fixed the issue. Thanks!

**Comment by Root-Time** [comment]
i still get the issue if i try to open r2modman
