### ISSUE TITLE
libuv tests seem to fail randomly on Darwin

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#23651]
@vcunat has been heroically disabling them but they keep failing in new ways (see [here](http://hydra.nixos.org/build/49867226/nixlog/1) for latest) and there has to be some sort of underlying cause

cc @cstrahan

**Comment by copumpkin** [comment]
Also, a lot of things depend transitively on libuv, so it failing randomly means we get no darwin binary cache for lots of useful things.

**Comment by vcunat** [comment]
(I'm trying to avoid Darwin.)  Most of the dependencies are relatively new, due to cmake using it.  IIRC that dependency is still optional, so one way to mitigate the impact would be to avoid building cmake with libuv on Darwin.

It's a bit strange, because all the libuv tests we run on Linux used to work on Darwin a few months ago, I think.

**Comment by LnL7** [comment]
The darwin stdenv depends on cmake, not sure if that would help.

**Comment by copumpkin** [comment]
The infamous "(temporarily)" strikes again: https://github.com/NixOS/nixpkgs/commit/15a1743d87edf9f2c85ded977ced7dba52ad6beb

**Comment by copumpkin** [comment]
Anyway, I don't know what the right thing to do is here (I might poke at it if I'm feeling ambitious but no guarantees), but I also don't want a cached random failure breaking the binary cache for an indefinite period here, so I turned off the tests.

**Comment by matthewbauer** [comment]
Not the case anymore: https://hydra.nixos.org/job/nixpkgs/trunk/libuv.x86_64-darwin/all
