### ISSUE TITLE
error: could not dynamically open plugin file … libnix_doc_plugin.so

### ISSUE THREAD

**Issue by tdillenburg** [NixOS/nixpkgs#237637]
When trying to switch to a new generation, `nixos-rebuild switch --flake '.#'` throws this error: 

```
error: could not dynamically open plugin file '/nix/store/458wmvsdw95kd96j88gnhjc6a38hq8aw-nix-doc-0.5.8/lib/libnix_doc_plugin.so': /nix/store/458wmvsdw95kd96j88gnhjc6a38hq8aw-nix-doc-0.5.8/lib/libnix_doc_plugin.so: undefined symbol: _ZN3nix9EvalState14throwEvalErrorENS_6PosIdxEPKc
Traceback (most recent call last):
  File "/nix/store/8c27ljrks2590wmdr1pcg3a7l3j4nhxm-systemd-boot", line 341, in <module>
    main()
  File "/nix/store/8c27ljrks2590wmdr1pcg3a7l3j4nhxm-systemd-boot", line 292, in main
    gens = get_generations()
  File "/nix/store/8c27ljrks2590wmdr1pcg3a7l3j4nhxm-systemd-boot", line 160, in get_generations
    gen_list = subprocess.check_output([
  File "/nix/store/6qk2ybm2yx2dxmx9h4dikr1shjhhbpfr-python3-3.10.11/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/6qk2ybm2yx2dxmx9h4dikr1shjhhbpfr-python3-3.10.11/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/k6ciawnknm1yxxiwm4pih008rijyn9wh-nix-2.15.1/bin/nix-env', '--list-generations', '-p', '/nix/var/nix/profiles/system', '--option', 'build-users-group', '']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
```

Apparently it's an issue with nix-doc. In [nix-doc issue 20](https://github.com/lf-/nix-doc/issues/20), the author suggests overriding nix but it didn't work. It seams like nix got corrupted.

This is pointed as a risk at [nix documentation](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-plugin-files):  

> Warning! These APIs are inherently unstable and may change from release to release.
> Since these files are loaded into the same address space as Nix itself, they must be DSOs compatible with the instance of Nix running at the time (i.e. compiled against the same headers, not linked to any incompatible libraries). They should not be linked to any Nix libs directly, as those will be available already at load time.

I've tryed removing `nix-doc` and `nix.extraOptions = "plugin-files = ${pkgs.nix-doc}/lib/libnix_doc_plugin.so";` but the error perssists and nixos can't switch to the new generations.

I can't edit `/etc/nix/nix.conf` as it's linked so I can't manually remove the line:
plugin-files = /nix/store/458wmvsdw95kd96j88gnhjc6a38hq8aw-nix-doc-0.5.8/lib/libnix_doc_plugin.so

### Steps To Reproduce
1. add environment.systemPackages = pkgs.nix-doc; and nix.extraOptions = "$plugin-files = ${pkgs.nix-doc}/lib/libnix_doc_plugin.so"; to configuration.nix
2. `nixos-rebuild switch` or `nixos-rebuild boot`
3. nixos-rebuild is not longer working

### Expected behavior
There should be a way to unlink dynamic libraries linked to nix cli during build time.

### Notify maintainers
@lf- 

### Metadata
I can't run `nix-shell -p nix-info --run "nix-info -m"`.

nixos-version: `23.11.20230606.4729ffa (Tapir)`
`nix --version` was 2.13.1, but it throws error now

**Comment by kirillrdy** [comment]
greetings @tdillenburg 

Is my understanding correct 

- you had previously `nix.extraOptions = "plugin-files = ${pkgs.nix-doc}/lib/libnix_doc_plugin.so";` in your nixos configuration ?
- after recent upgrade nix commands eg `nix-env` dont work  because of ABI incompatibility when it tries to load nix-doc?

if that's the case, and we are confident that removing `plugin-files = ${pkgs.nix-doc}/lib/libnix_doc_plugin.so` from nix.conf will solve the issue, then you can just copy the nix.conf over that symlink and edit it manually.


```
cd /etc/nix
sudo rm nix.conf 
sudo cp /etc/static/nix/nix.conf .
ls
sudo nvim nix.conf   # or editor of your choice, the file is read only so you will need to use `:w!` for neovim
```

If that fixes nix, the after next nixos-rebuild /etc/nix/nix.conf will be restored to correct symlink

Hopefully this helps

**Comment by lf-** [comment]
I have a hunch as to why this is happening: most likely you're using a newer version of Nix to build your configuration (the default behaviour of nixos-rebuild is to reexec Nix of the version from the config) and so that newer version of Nix is being used with the old nix.conf to build the new NixOS config. 

It's plausible that you can avoid this by either using --fast with nixos-rebuild to disable such reexec or pass `--plugin-files ""` to Nix to fix it temporarily (although you would have to read the nixos-rebuild sources to figure out how). 

I believe that this problem is sadly unavoidable without somehow detecting linker errors and bailing on the dynamic library loading, which, maybe that's possible but I doubt it.

**Comment by tdillenburg** [comment]
Thank you @kirillrdy. It worked perfectly. I didn't know nix kept a static version of files and that I could simply replace it. Without the plugin-files line nixos-rebuild worked. 

@lf-, it's weird because I had nix-doc for a long time in my config but it just "broke" now. Well, I'm not sure why it broke, but the workarround worked. Thanks!
