### ISSUE TITLE
Gogs configuration parameters invalid

### ISSUE THREAD

**Issue by gianmarcogg03** [NixOS/nixpkgs#237951]
### Describe the bug
Gogs fails to start saying that it can't connect to the database. I'm assuming the problem is related to some changes in the config file syntax seen in https://github.com/gogs/gogs/releases where it says "Removed" on the latest release (0.13.0). These parameters are still in use in this nixpkg.

### Steps To Reproduce
1. Start Gogs

### Expected behavior
The config file should have the correct parameters.

### Screenshots
Output of `sudo journalctl -xeu gogs`.
![immagine](https://github.com/NixOS/nixpkgs/assets/28053717/f8bb5f45-c457-4c29-af47-999596dce44b)

### Notify maintainers

@schneefux 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[gianmarco@nixdiance:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.5, NixOS, 23.05 (Stoat), 23.05.997.ddf4688dc7a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - channels(gianmarco): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by gianmarcogg03** [comment]
@schneefux can you take a look, please?

**Comment by ammesonb** [comment]
I am experiencing the same error, and I believe in my case it is due to the `DB_TYPE` configuration being set in `app.ini` on [this line](https://github.com/NixOS/nixpkgs/blob/23.05/nixos/modules/services/misc/gogs.nix#L14) which has been renamed to `TYPE` (documented in the [v13 release changes](https://github.com/gogs/gogs/releases/tag/v0.13.0), see `Removed` section, 3 lines from the bottom)

It appears the master branch has this change already implemented ([PR #245233](https://github.com/NixOS/nixpkgs/commit/b34a51f5a7ec2b7f57ed291fee7852f03634a409)), but it does not seem to have been backported to the 23.05 channel.

**Comment by ammesonb** [comment]
I was able to work around this by providing the `extraConfig` with the proper parameters for v13. It appears the removed settings are simply ignored, including the unnecessary host/port that was causing my connection failure

**Comment by gianmarcogg03** [comment]
That seemed to do the trick, we just have to wait for that PR of mine to go down from master, probably in the next version of the stable channel(s).
