### ISSUE TITLE
nextcloudPackages.apps don't expose licensing information

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#238402]
The nextcloud package set offers apps, that have licensing information attached, but not exposed as part of their meta attribute.

Also, there are some apps, like news, where the licensing information says `null`, which requires clarification.

This needs to be fixed. @onny

**Comment by onny** [comment]
Thank you @RaitoBezarius for opening the draft PR in order to fix my mistakes and broken packages. I'm sorry for the bad communication and the inability to resolve this serious issue.

Fixing this for Wordpress packages and themes (wp4nix) and Nextcloud apps (nc4nix) in a foreseeable time exceeds my skills and competence. Therefore I would like to offer to add a `broken` flag to these package sets and remove them for the next release 23.11 if it's not resolved by then.
