### ISSUE TITLE
xmonad recompile fails

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#23849]
## Issue description

Trying to set up dzen on xmonad, `xmonad --recompile` fails.

### Steps to reproduce

I have an `xmonad.hs` like

```
import XMonad
import XMonad.Hooks.DynamicLog

main = xmonad =<< dzen defaultConfig
              { modMask = mod4Mask  -- super instead of alt (usually Windows key)
              , terminal = "urxvt"
              }
```

(I think this is right? It's basically verbatim from http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-DynamicLog.html)

When I `xmonad --recompile`, though, I get an xmessage with 
```
xmonad.hs:2:1: error:
    Failed to load interface for âXMonad.Hooks.DynamicLogâ
    Use -v to see a list of the files searched for.
```

I'm a novice with xmonad, but searches for the errors give suggests like "you're missing certain Haskell packages", which makes me wonder if the xmonad-with-packages doesn't include the DynamicLog stuff?

## Technical details
* System: 16.09.1803.40de598 (Flounder) 
* Nix version: nix-env (Nix) 1.11.6 
* Nixpkgs version: "16.09.1803.40de598"

**Comment by joachifm** [comment]
@NeQuissimus uses xmonad, they might know

**Comment by HappyEnte** [comment]
xmonad-with-packages is only a wrapper which you pass packages to that you want included with your ghc environment xmonad is running in (see the xmonad [module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/window-managers/xmonad.nix)) for how it should be used). If you are on nixos you should install xmonad with the module:
``services.xserver.windowManager.xmonad.enable
services.xserver.windowManager.xmonad.enableContribAndExtras``
Otherwise just override the xmonad-with-packages just as in the nixos module.

**Comment by NeQuissimus** [comment]
You may just need contrib and extras. Try adding the following:

```
      windowManager.xmonad = {
        enable = true;
        enableContribAndExtras = true;
      };
```

**Comment by nyarly** [comment]
That was exactly what I needed. Thanks!
