### ISSUE TITLE
sway test flaky, blocks channel updates

### ISSUE THREAD

**Issue by pennae** [NixOS/nixpkgs#238642]
### Describe the bug

the sway test is flaky, both because ocr itself seems to flaky *and* because ocr seems to be very slow.

### Steps To Reproduce
1. build `nixosTests.sway` a couple times, we haven't gotten it to work even once

### Additional context

this seems to be blocking nixos-unstable channel updates. there are a number of timeouts in the hydra build logs that we can very clearly attribute to either ocr not working, or ocr timing out because it gets only one shot at finding the gpg prompt (and if that fails, loops forever on the empty desktop).

### Notify maintainers

@primeos @Synthetica9

**Comment by vcunat** [comment]
I found it failing quite reliably, exactly since merging the [last staging-next](https://github.com/NixOS/nixpkgs/pull/237233#issuecomment-1596003123).

**Comment by primeos** [comment]
> scrolling throug hydra logs it's been flaky before too though

Where do you see this? Looking through https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.sway.x86_64-linux/all I only see successful builds (apart from the cancelled builds and dependency failures). I also don't remember it ever failing when working on it. So this definitely seems to be a regression from staging-next (either it just causes issues with (some of) the OCR tests or it can even affect users - in which case it would be very good that the test is failing). Unfortunately I don't really have time to look into it right now (maybe Thursday or Saturday). It could be due to a font rendering regression.

> ocr timing out because it gets only one shot at finding the gpg prompt (and if that fails, loops forever on the empty desktop)

Hm, that's strange - the GnuPG pinentry-gnome3 passphrase prompt shouldn't disappear automatically / after a short timeout (if that's the case than we definitely need to change that part).

**Comment by primeos** [comment]
Both https://hydra.nixos.org/build/224824334/log/tail and https://hydra.nixos.org/build/224439713/log/tail failed consistently at this point:
```
machine: sending key 'alt-ret'
(finished: sending key 'alt-ret', in 0.01 seconds)
machine: waiting for alice@machine to appear on screen
```

So it looks like either `alacritty` doesn't start when using the Wayland backend or the font rendering is broken then (with the X11 backend (XWayland) the test succeeds).

**Comment by primeos** [comment]
> Some of the “cancelled” builds are cancelled due to it timing-out, e.g. https://hydra.nixos.org/build/218931684 and https://hydra.nixos.org/build/219234504;

Ah, right, thanks for the examples :)

> the reason there may be unrelated, though

Indeed, that seems to be to the gnome3-pinentry timeout that I wasn't aware of (so that part would be fixable).

> run locally here the things the tests wants to happen did always happen, but OCR was incredibly flaky and either did not detect them at the first try, or not at all

Weird, that shouldn't happen. OCR is slow but should be reliable. Not sure if this could be setup dependant. On Hydra it doesn't seem to be an issue.

> this is especially bad for pinentry because it closes after 10 seconds for reasons we have not dug into

That is indeed bad. Luckily @Synthetica9 already found a solution for the timeout in #238997.

> and the way it's used here does seem at least somewhat suspect, maybe using other tooling to list windows would be more appropriate?

I intentionally chose OCR to ensure that the (font) rendering works but it isn't required for ensuring that the windows are there.
The slowness of OCR is certainly a drawback though.
