### ISSUE TITLE
dockerTools always copies closure content to root of image

### ISSUE THREAD

**Issue by scealiontach** [NixOS/nixpkgs#23966]
Currently, dockerTools ends up copying the contents of the derivations to the root of the docker container.  While broadly I agree this is a good thing, it isn't always appropriate.  For example using the wordpress package.  You end up with a pile of php and other stuff in the root of the container. That might lead one to think the next thing to do would be to point the document root of some server to the root of the container - which would be a bad thing, since you have, proc, dev, sys etc from there down.  Seems to me that we should be able to at minimum specify derivations which we do not want copied to the root, leaving just the closure under /nix/store.  Even better might be to be able to specify destination to copy derivation to other than root for some subset of derivations.

**Comment by FRidh** [comment]
>  For example using the wordpress package.

Actually, then that expression is incorrect. We should aim at roughly following FHS inside store paths.

**Comment by puffnfresh** [comment]
Yeah, I agree with that, if you `nix-env -i wordpress` it shouldn't pollute your `~/.nix-profile`.

**Comment by nlewo** [comment]
Not all closure files are copied to the root of the container, but only the paths specified in the `contents` atttribute, ie. the dependencies of these paths are not copied to `/`.

So, if you need to create your own root layout, you can create a derivation that symlinks some paths to your custom destinations and only put this derivation into the `contents` list.

I close this issue since I think we can address this need by creating a custom derivation. Moreover, the issue title is actually wrong ;)
But feel free to reopen it if you disagree!

**Comment by scealiontach** [comment]
I do disagree actually. There is a break in expectation here. I would expect the paths in the contents attribute to show up in the image similar to the way they would show up in a normal nixos installation, if not necessarily FHS, and then any customization would start from there.  While not the same obviously, this is roughly the same thing you would expect from installation of a package into a Ubuntu or other Linux.  And again, installating what amounts to a docroot into the root direct of a docker image is a mess.
