### ISSUE TITLE
nixos-rebuild switch --rollback scrambled ownership of home directories

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#24010]
## Issue description

I did all of this on a production server in frantic recovery so I didn't spend time messing around with the cause.

I ran `nixos-rebuild switch` on a NixOps-managed server and learned that is a horrible idea. I use `users.mutableUsers = false` and apparently the switch decided to shut everything down and remove all my users. I quickly ran `nixos-rebuild switch --rollback` which thankfully (!) put everything back. However it appears that it put something back incorrectly: permissions on the users' `/home` directory. Here's basically what happened. I had 4 users, let's just call them A, B, C, and D. Each user had a home directory named after his name: `/home/A`, `/home/B`, `/home/C`, `/home/D`. Naturally each home directory should be *owned* by the respective user. However, after the rollback, I found that the ownership of each home folder belonged to a *different* user! For example, `/home/A` was owned by user C, `/home/B` was owned by user A, etc. It seemed random but I don't know if it actually is (it could be some off-by-one error somehow).

The same thing happened to the folders in `/nix/var/nix/profiles/per-user` and `/nix/var/nix/gcroots/per-user`.

In every case, users like `root` and `nginx` were not affected, only the users I had added in `users.users` in my deployment.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

Using: https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-17.03pre101896.4a524cf/nixexprs.tar.xz

**Comment by globin** [comment]
cc @rickynils and @edolstra from looking at the git history.

**Comment by cleverca22** [comment]
this sounds like just a design flaw within mutableUsers

the initial switch deleted all users, because the original pre-nixops configuration.nix said they didnt belong

and because no uid has been specified, the rollback re-made them, and assigned the uid's on a first come, first serve basis (and not the same as before)

i have had similar problems when i force one user to uid 1000, then dont set a uid on the next, which allocates itself to 1000, and now they collide

my own solution has been to just always specify a uid on every user, so nixos cant collide or change its mind, and i dont have to deal with uid mapping at the nfs level either

**Comment by 3noch** [comment]
@cleverca22 If that's the best solution then we need to make uid required for all users.

**Comment by 3noch** [comment]
Still, that implies there is a "mutation leak" in user permissions. Files created for some user will always be mishandled across rebuilds if users are added/removed or uid changes.

**Comment by 3noch** [comment]
@edolstra Fantastic!
