### ISSUE TITLE
sddm has cmake in its runtime closure

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#24126]
## Issue description

On NixOS 17.03, the `sddm` in the system configuration with Plasma 5 enabled, has `cmake` and `extra-cmake-modules` in its runtime closure, which causes unnecessary bloat. This is because `nixos/modules/services/x11/desktop-managers/plasma5.nix` has:
```
      services.xserver.displayManager.sddm = {
        theme = "breeze";
        themes = [
          pkgs.extra-cmake-modules # for the setup-hook          
```

`makeQtWrapper` then causes the `share` directories of `cmake` and `extra-cmake-modules` to be added to the `sddm` wrapper script. (Automatically adding everything with a `share` directory to the wrapper seems pretty drastic BTW.)

@ttuegel 

## Technical details

* System: NixOS 17.03.git.5ea3986
* Nix version: 1.12pre5073_1cf4801

**Comment by ttuegel** [comment]
> Automatically adding everything with a share directory to the wrapper seems pretty drastic BTW.

KDE upstream is slightly careless about implicit runtime dependencies. I spent hours trying to figure out which runtime dependencies needed to be in `XDG_DATA_DIRS`. By the way, you have to guess at this because SDDM doesn't log error messages. 🙄 

Could we drop `extra-cmake-modules`? Probably. Can I answer that question for any of the other dependencies? Not a chance. So I nuked it from orbit. Guessing the correct `XDG_DATA_DIRS` setting would be a good project for a first-time contributor with a lot of free time.

At the moment, I'm trying to get rid of `makeQtWrapper` entirely. This problem may go away as a happy accident, but that won't help this release. I'm open to other suggestions.
