### ISSUE TITLE
fetchFromGitHub lacks leaveDotGit feature of fetchgit

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#24169]
## Issue description

```fetchFromGitHub``` lacks ```leaveDotGit``` feature.
```fetchgit``` has it.

Sometimes it is useful https://github.com/NixOS/nixpkgs/pull/24151#pullrequestreview-28112520

**Comment by copumpkin** [comment]
`leaveDotGit` is a time bomb, and is a false friend that almost always breaks fixed-output derivation hashes every time we upgrade git. In almost all cases, build tools use it to figure out their own version (or more rarely, which files are checked into the current tree), and we don't need the complexity of 99% of the rest of the .git directory.

I'd actively oppose adding it to `fetchFromGitHub` unless it could be done in a way that doesn't suffer from those issues. But in general, I think just amending builds not to rely on .git is the better direction.

**Comment by copumpkin** [comment]
One possible dummy implementation of .git (that if we adopt we should use in `fetchgit` too) would be something like:

1. Initialize an empty repository
2. Craft a commit from the complete current source tree, with either a dummy commit message (and deterministic times, etc.) or the correct commit message from upstream (which would require teaching `fetchFromGitHub` about the GitHub API and all that awkwardness, instead of just being a `fetchzip` wrapper.
3. _Lie_ about the hash in the git storage: the commit in the previous step will have the wrong hash, so we rename the backing file and repoint the ref to the new hash. If anyone runs `git fsck`, they'll be sad. I think most git commands won't check the hash though.
4. Create a tag ref for the current `fetchFromGitHub` `rev` attribute, if it was symbolic. Point it to the fake commit hash we crafted above.

But all of that seems like far more work than just making builds behave properly.
