### ISSUE TITLE
plasma tests are broken

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#24240]
- Last success on March 11, but we have about a week without evaluation after that http://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.plasma5.x86_64-linux (i686 looks the same)
- Example log: http://hydra.nixos.org/build/50047287/nixlog/20/raw (newer ones look the same locally but Hydra doesn't show logs anymore for some reason)
- Note that latest nixos-unstable is ~17 days old ATM.  All other tests seem fine now (or were during the last 24h).

/cc @ttuegel, just in case.

**Comment by ttuegel** [comment]
The problem seems to be
```
machine# [   40.519201] systemd[896]: user@1000.service: Failed at step EXEC spawning /nix/store/c5j270pibypikcrsbp3f3mn700plwh1r-systemd-232/lib/systemd/systemd: Permission denied
```
I don't know what that means, but that's when everything starts crashing.

I cannot reproduce locally because some change in master since the last channel update broke QEMU. Evidently QEMU is only broken on my machines. I'm also running Plasma 5, so the problem map not exist outside the VM. I'm running something branched off of master, so I can't say with certainty.

Since I can't fix the Plasma tests, you can disable them to get a channel update.

**Comment by vcunat** [comment]
Right, that doesn't appear in [the last succeeding log](http://hydra.nixos.org/build/50002754/log/raw).  

OK, disabled temporarily, as it's tested by human(s); I had been thinking about that.

**Comment by vcunat** [comment]
The channel has updated!
