### ISSUE TITLE
Pass username and password to nix-prefetch-git

### ISSUE THREAD

**Issue by linquize** [NixOS/nixpkgs#2427]
Without embedding username and password in URL, e.g. (http://username:password@xxx.com),
how to pass username and password to `nix-prefetch-git`?
It is a private repository with password protected.
I use http basic auth.
I cannot use `.netrc` because it has no `$HOME`.

**Comment by pSub** [comment]
@linquize does fetchgitPrivate suits your needs?

**Comment by linquize** [comment]
let me see

**Comment by domenkozar** [comment]
status?

**Comment by cleverca22** [comment]
the ssh-agent stuff in fetchgitPrivate is currently non-functional (was meaning to open a ticket)

the simplest way to use it right now is the following
```
src = fetchgitPrivate {
url = "ssh://user@host/path/to/repo.git/";
sha256 = "...";
rev = "...";
}
```
and then set this before nix-build or nixos/rebuild
```
export NIX_PATH="ssh-config-file=/root/config:$NIX_PATH"
```
with these contents
```
IdentityFile /root/.ssh/id_rsa
StrictHostKeyChecking no
```
the nixbld group will need read permissions on the file, and execute on any dir above it

**Comment by fxfactorial** [comment]
@domenkozar @cleverca22 is this still the best way to do this ?

**Comment by mboes** [comment]
> the ssh-agent stuff in fetchgitPrivate is currently non-functional (was meaning to open a ticket)

@cleverca22 is there a ticket for this now?

**Comment by cleverca22** [comment]
never got around to opening a ticket about the agent, the root problem is that the ssh agent checks to see which user is contacting it for security, and rejects any abnormal users, so nixbld1 can never use the agent

**Comment by mboes** [comment]
OK. Sounds insoluble?

Come to think of it I have yet to see a good use case for `fetchgitPrivate`. Handing over one's SSH private keys to a "foreign" build user sounds like a risky proposition. Even just copying it anywhere else than the canonical location means there's now two locations to remember to keep secure, rather than one. The alternative is to ask the user to checkout the Git repo manually, then point to it via a local path. This should work for most use cases and doesn't pose any particular security risk.

@fxfactorial @linquize so I would recommend the following: if your nix expression is stored in a git repo, add the remote private repo that you want to check out as a submodule, checked out in a known location of the parent repo. Then, you can have your nix expression point to the location of the checkout.

That said, while `fetchgitPrivate` sounds to me like the wrong approach, having the ability to use `nix-prefetch-git` + `fetchgit` instead of a submodule sounds like a reasonable feature request. The difference is, conceivable `nix-prefetch-git` could be made to perform the checkout part under the identity of the local user, not one of Nix's build users.

**Comment by layus** [comment]
@mboes Your idea may not be feasible when building trough the nix daemon. In that setup the environment of the user asking for the build is not known to the daemon.

Seems to me that the Nix way is to add support for a `-A` option in nix-prefetch-git.
This way, you could write `nix-prefetch-git -A mypackage.src` and have the source automatically downloaded with the current user setup.

**Comment by cleverca22** [comment]
misread your comment and wound up with another idea, an argument similar to ssh -A, so nix-build will proxy the ssh-agent stuff from the build user to the user running nix-build, that would solve the current ssh-agent issues

**Comment by cleverca22** [comment]
i recently found another solution, that works fully with ssh agents

https://gist.github.com/cleverca22/ef075e5dfe092fa6b08cec0ae1dfde66

**Comment by expipiplus1** [comment]
^ this should go into the `nix-` tools, along with destroying the socket once finished with it and all that.

Perhaps after the C++ rewrite.

**Comment by cleverca22** [comment]
another way of doing it, this one generates the ssh_config from within nix and injects it into the nixPath

https://gist.github.com/cleverca22/8b1b21a25a1d18fbcf558d23c36767cc

**Comment by gilligan** [comment]
Seems to me like there are a couple of solutions for this - can this issue be closed?
