### ISSUE TITLE
Google Compute Engine image fails to fetch SSH keys

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#24273]
Now that I've successfully built and booted the NixOS image for Google
Compute Engine, its systemd service `fetch-ssh-keys.service`, which is
part of the boot process, fails to fetch the SSH keys provided by the
Google Compute Engine environment, preventing me from accessing the
virtual machine via SSH.

The service's error messages are to be found at the end of this boot
log: <https://gist.github.com/8573/78c3c1916049dc89402c79e6f110b756>.

**Comment by 8573** [comment]
It appears that the URLs whence the `fetch-ssh-keys` systemd service
attempts to fetch SSH keys [(1)] are obsolete [(2)].

[(1)]: <https://github.com/NixOS/nixpkgs/blob/a4ac5506f57f767fd53aebd0eeea8db4c911f83f/nixos/modules/virtualisation/google-compute-image.nix#L132-L196>
[(2)]: <https://cloud.google.com/compute/docs/instances/ssh-keys#metadatavalues>

**Comment by 8573** [comment]
Oh, and if it does fetch keys, it sets them as the `authorized_keys`
for the superuser `root`, when Google Compute Engine wants no-one to
log in as `root` [(1)], instead seeming to want new user accounts
created for each Google user account given access to the Google Cloud
Platform project.

[(1)]: <https://cloud.google.com/compute/docs/instances/ssh-keys#root>

**Comment by 8573** [comment]
Saving this link here in case I end up having time to look into it
more:
<https://cloud.google.com/compute/docs/images/configuring-imported-images>

**Comment by ilya-kolpakov** [comment]
Same here. Google provides the [account daemon](https://github.com/GoogleCloudPlatform/compute-image-packages#accounts) in its [compute-image-packages](https://github.com/GoogleCloudPlatform/compute-image-packages) and it would be great to get it working under NixOS.

**Comment by 4e6** [comment]
I also had troubles trying to boot the google-cloud-image using NixOps.
For now, this is the [minimal working configuration](https://github.com/4e6/nixops-minimal/blob/19bccd819781613a3091a9ac894b0e99f1630a52/gce-minimal.nix) and its [journalctl boot log](https://gist.github.com/4e6/9016b5243062bac803cc5ddaf9166c89).

```
$ nixops --version
NixOps 1.5.2                   
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixos-17.09
```

## fetch-ssh-keys.service

After a thorough investigation, I found that `fetch-ssh-keys.service` duplicates the `fetch-ssh-keys-start.service` and can be [disabled](https://github.com/4e6/nixops-minimal/blob/19bccd819781613a3091a9ac894b0e99f1630a52/gce-minimal.nix#L25-L31).

@8573 looking at your boot log, you are having issues with the `fetch-ssh-keys-start.service` and not the `fetch-ssh-keys.service`. The names are very confusing. For me `fetch-ssh-keys-start.service` works well and is able to fetch the keys from instance's metadata correctly.

## google_instance_setup.service

First, `fetch-ssh-keys-start.service` downloads `/etc/ssh/ssh_host_ed25519_key`, host key of the instance.

```
Dec 29 18:12:07 localhost fetch-ssh-keys-start[891]: Downloaded /etc/ssh/ssh_host_ed25519_key
Dec 29 18:12:07 localhost systemd[1]: Starting SSH Daemon...
Dec 29 18:12:09 localhost sshd-pre-start[914]: Generating public/private rsa key pair.
Dec 29 18:12:09 localhost sshd-pre-start[914]: Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Dec 29 18:12:09 localhost sshd-pre-start[914]: Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
```

Next, `google_instance_setup.service` overwrites it by generating a new host key.

```
Dec 29 18:14:41 machine google_instance_setup[3333]: instance-setup: INFO Generating SSH key /etc/ssh/ssh_host_ed25519_key.
Dec 29 18:14:41 machine instance-setup[3333]: INFO Generating SSH key /etc/ssh/ssh_host_ed25519_key.
```

This result in an error when trying to ssh to the host:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:mpfuuc1GASOCQaUO9XLmqrDzZjwFAq8aT4U++Hoe3I8.
Please contact your system administrator.
Add correct host key in /home/dbushev/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /home/dbushev/.ssh/known_hosts:8
ED25519 host key for 35.225.30.45 has changed and you have requested strict checking.
Host key verification failed.
```

I thought `google-instance-setup` generates new key because is not able to fetch the metadata:

```
Dec 29 18:14:36 machine google_instance_setup[3333]: instance-setup: ERROR GET request error retrieving metadata. <urlopen error [Errno 101] Network is unreachable>.
Dec 29 18:14:36 machine instance-setup[3333]: ERROR GET request error retrieving metadata. <urlopen error [Errno 101] Network is unreachable>.
```

But even sequencing it after the `dhcpcd.service`, the error is gone, but it still overwrites the keys.

I was able to [fix it](https://github.com/4e6/nixops-minimal/blob/19bccd819781613a3091a9ac894b0e99f1630a52/gce-minimal.nix#L35-L61) only by backing up the keys and restoring after the `google-instance-setup` is done.

## Summary

I'll update https://github.com/NixOS/nixpkgs/pull/33004 and remove the part that closes this issue. I also understand that these problems go beyond the scope of this issue. I'll see what's there in the issue tracker, and maybe create a separate one for the `google-instance-setup`

**Comment by 8573** [comment]
> After a thorough investigation, […]

@4e6: Thanks for the thorough investigation!

**Comment by yegortimoshenko** [comment]
I am definitely experiencing the same problem.

**Comment by flokli** [comment]
Work to fix this is going on in https://github.com/NixOS/nixpkgs/pull/51566, which uses libnss, pam and metadata.google.internal to configure accounts and ssh keys via oslogin.

**Comment by flokli** [comment]
I think this can be closed. I use oslogin quite extensively, and it's enabled by default in `google-compute-config.nix`.
