### ISSUE TITLE
Package request: goxlr-utility

### ISSUE THREAD

**Issue by Sporesirius** [NixOS/nixpkgs#243701]
**Project description**

An unofficial GoXLR App replacement for Linux, Windows and MacOS.

**Metadata**

* homepage URL: https://github.com/GoXLR-on-Linux/goxlr-utility
* source URL: https://github.com/GoXLR-on-Linux/goxlr-utility
* license: MIT
* platforms: linux

**Comment by errnoh** [comment]
Moving conversation back here to avoid spamming goxlr-utility maintainers :sweat_smile: 

@Sporesirius I made a draft commit that you can find from https://github.com/NixOS/nixpkgs/pull/249860

It's closer to what the official .deb and .rpm packaging is doing, i.e. including some of the relevant resources, shell completion etc. I wouldn't mind adding you as a maintainer but to do that it probably requires adding you to the maintainer list as well. Should be easy to fix if you want to add PR to the branch.

**Comment by Sporesirius** [comment]
Hey @errnoh, wow you are fast :D 
Yes, you can add me as a maintainer for this package. But as I understand it, I need to add me to the maintainer list first, right?

**Comment by errnoh** [comment]
Hah, had some free time during the night and since I wanted to get my GoXLR setup working anyways thought I might as well sort this out. 

For the question: Yup, the `maintainers = [ xxxx ];` requires `xxxx` to be on `maintainers/maintainer-list.nix`. The file itself lists the mandatory/optional fields in the metadata, but basically "a name and at least one contact/identity information" (e.g. a github id). Oh, and the list needs to stay in alphabetical order ^^

Feel free to make PR against this branch, I'll merge it as soon as I notice the PR :)

**Comment by errnoh** [comment]
Managed to get the PR reviewed and should now be code-wise idiomatic enough to pass. I think based on https://discourse.nixos.org/t/prs-in-distress/3604/67 the main thing remaining is getting thumbs up functionality-wise so that's it's not only "works on my machine" :sweat_smile:

**Comment by Sporesirius** [comment]
I saw your PR and tried using nixpkgs-review to download it to my local machine and try to run it. I used these steps: https://github.com/Mic92/nixpkgs-review
Do you know if my approach is wrong? This is the first time I've tried a Nix PR. Unfortunately, I haven't found much information about it.

**Comment by errnoh** [comment]
Glad to hear you got it working! :) The nixpkgs-review tool seems nice, hadn't used it myself but for building the PR it seems to do exactly what one would expect. I guess in this case there's a limit what it can do though as the udev rules are being added on the module side and it probably doesn't handle that so some manual work is required :shrug: 

But again, all is good since you did manage to test the build!
