### ISSUE TITLE
Package request: atlauncher

### ISSUE THREAD

**Issue by LuciusofLegend** [NixOS/nixpkgs#243836]
**Project description**

ATLauncher is a custom Minecraft launcher that allows players to create and install various modpacks.  It's an essential tool for anyone who wants to modify Minecraft.  ATLauncher offers packages for other Linux distributions, so hopefully it's not too big a hassle.

**Metadata**

* homepage URL: https://atlauncher.com/
* source URL: https://github.com/ATLauncher/ATLauncher
* license: GPL-3.0
* platforms: Windows, MacOSX, Linux

**Comment by max-amb** [comment]
It is currently in the `unstable` channel under name [atlauncher](https://search.nixos.org/packages?channel=unstable&show=atlauncher&from=0&size=50&sort=relevance&type=packages&query=atlauncher) so to obtain it you could either:
- switch channel to `unstable` detailed [here](https://nixos.wiki/wiki/Nix_channels) and more if you just want to copy-paste [here](https://stackoverflow.com/questions/41230430/how-do-i-upgrade-my-system-to-nixos-unstable)
- switch to `unstable` for specifically `atlauncher`, details on how to do this [here](https://discourse.nixos.org/t/installing-multiple-packages-from-unstable-channel-in-configuration-nix/19271/2), but be aware this option is risky and the package may not work due to graphics drivers and such

Let me know if you have any questions, otherwise I will close this issue.
