### ISSUE TITLE
buildNpmPackage fails to build pdfkit

### ISSUE THREAD

**Issue by ners** [NixOS/nixpkgs#244285]
### Describe the bug

I'm trying to package https://github.com/LibreScore/dl-librescore which directly depends on https://github.com/foliojs/pdfkit.

I get the following error:
```
Error: Git dependency node_modules/pdfkit contains install scripts, but has no lockfile, which is something that will probably break. Open an issue if you can't feasibly patch this dependency out, and we'll come up with a workaround.
If you'd like to attempt to try to use this dependency anyways, set `forceGitDeps = true`.
```

If I set `forceGitDeps = true`, then I get the following error from npm:
```
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:100 "/nix/store/qxdmy3k4s2ysgdkahi3497jab735jxz1-dl-librescore-0.34.46-npm-deps"
```

The error messages are good enough at explaining why it's a problem, but I don't know how to fix it. I'd appreciate some help!

I cannot feasibly remove the pdfkit dependency because generating PDFs is essential functionality of this package.

### Steps To Reproduce
1. try to build the package `dl-librescore` from https://github.com/ners/nixpkgs/tree/dl-librescore, e.g. by issuing:
  ```console
  nix build github:ners/nixpkgs/dl-librescore#dl-librescore
  ```

### Expected behavior
The package builds.

cc @lilyinstarlight

**Comment by lilyinstarlight** [comment]
> If I set forceGitDeps = true, then I get the following error from npm:

Setting `makeCacheWritable = true` should fix that problem specifically but there are more issues which the git deps error is warning will probably be the case

> The error messages are good enough at explaining why it's a problem, but I don't know how to fix it. I'd appreciate some help!

So the problem specifically is:
* dl-librescore depends on pdfkit as a git dep rather than registry dep
* pdfkit doesn't have a npm lockfile (only a `yarn.lock`)
* npm requires dev dependencies for git deps that have install scripts (which pdfkit has)
* npm does not lock dev dependencies at all, so without an upstream npm lockfile then there just is no (npm) lock information for these required dev dependencies

There's only so much we can do downstream about this, but we have had some ideas for how to deal with mixed lockfiles (like having a yarn.lock in a git dev dep with install scripts), but it'll be a good while before we get around to implementing such a thing (since it's more in the "nice to have" rather than "required for many packages" sort of thing)

As for what you can do about it now, here are some options:

1. Patch `dl-librescore` to depend on `pdfkit` only as a registry dep rather than git dep
2. Patch out install scripts from `pdfkit`
3. If `dl-librescore` really needs an unreleased version, pester `pdfkit` to make a new release and then have `dl-librescore` depend on `pdfkit` as a registry dep similar to option 1

I wish I had better news for you, but npm is kinda hell in regards to git deps :(
