### ISSUE TITLE
gcc6.2 has -Wunused-result  by default. Is this really a must?

### ISSUE THREAD

**Issue by bugereport** [NixOS/nixpkgs#24469]
## Issue description
Compiling anything causes lots of warnings i have to turn of flag. Not a huge problem but caused little chaos. in the end you guys will decide should it stay or not. is there way to turn it out by your self (without  giving each time gcc -Wno-unused-result.

### Steps to reproduce

gcc this.c -o this. Silly warning pops out.

int main( void )  {
  int i = 0;  
  scanf( "%i", &i );
  return 0;
}

## Technical details
Linux huenix 4.4.56 #1-NixOS SMP Wed Mar 22 11:17:51 UTC 2017 x86_64 GNU/Linux

* System: 16.09.1904.4da11d7 (Flounder)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "16.09.1904.4da11d7"

gcc -v
Using built-in specs.
COLLECT_GCC=/nix/store/8f4rnl7x43vnxgj1ik76i1nazfigdzha-gcc-6.2.0/bin/gcc
COLLECT_LTO_WRAPPER=/nix/store/8f4rnl7x43vnxgj1ik76i1nazfigdzha-gcc-6.2.0/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: 
Thread model: posix
gcc version 6.2.0 (GCC) 

thx for answers.

**Comment by globin** [comment]
I don't think this is a silly warning, as this should be fixed in upstream projects and we normally never change defaults that upstream GCC or other compilers provide.

Warnings should also never be turned off in package builds in nixpkgs except for not making them errors to still allow building projects (`-Wno-error=whatever`)
