### ISSUE TITLE
Best practice: nix derivation in nixpkgs or $project/default.nix?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#24468]
Question: Is there a strong "best practices" for whether to put a nix derivation definition in the`nixpkgs` repo or whether to put it into the sources of the project being built as `default.nix` file that can be referenced from nixpkgs?

I know that for most packages the nix code lives in `nixpkgs` but I am not sure if this is the preferred approach or simply the pragmatic reality because most upstream projects do not have a nix expression that could be referenced.

Advice would be welcome. If it does make sense to put the expressions inside the projects being packaged then it would be great to see some examples of how to do that well too.

**Comment by Mic92** [comment]
We do not import nix expressions from external sources in nixpkgs. If you want get a package into nixos/nixpkgs, it should added directly to this repo. However a default.nix still makes sense in an upstream project, because it helps contributors/developers to get all build dependencies to get started with the project: 

The package manager nix itself is managed this way: https://github.com/NixOS/nix has a default.nix,
while a separate expression is in https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/nix/default.nix

**Comment by lukego** [comment]
Thank you very much for explaining this.

**Comment by nuxeh** [comment]
It seems `nix` no longer has a `default.nix` ;)
