### ISSUE TITLE
cargo-unused-features is installed as "unused-features"

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#244815]
https://github.com/NixOS/nixpkgs/blob/0a2745684e8e97340d947d56b0ba778056c10395/pkgs/development/tools/rust/cargo-unused-features/default.nix#L12

The `cargo-unused-features` package installs a binary called `unused-features` rather than `cargo-unused-features`.

Pinging maintainer here: @figsoda

**Comment by figsoda** [comment]
This seems to be an intentional decision by upstream

https://github.com/TimonPost/cargo-unused-features/commit/472ecca1708f7a7e764d1251fb847d65b12fd4db#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R30

The binary is named `unused-features`, but the repository (and the package) is named `cargo-unused-features`

**Comment by matthiasbeyer** [comment]
I filed a PR at upstream to solve this, I will close this issue therefore.
