### ISSUE TITLE
How to debug "waiting for device to appear".

### ISSUE THREAD

**Issue by liamwigney** [NixOS/nixpkgs#24584]
## Issue description
Just finished installing NixOS and when rebooting "waiting for device to appear" appears on the screen with the uuid of the disk. I thought that it might be due to it not existing but when I boot into the live cd the uuid is there. I've tried several times regenerating the config but it keeps happening.

Weirdly I saw in another issue that the hardwareconfig.nix is supposed to list the disk in the way you mount it but I used the method in the manual ( by-label/nixos) and it still writes it as uuid.

I'm trying to install on a Kaby Lake XPS 13 if that has an impact. I did have to change a setting from RAID to APCI or something to get the disk's visible in Linux.

### Steps to reproduce

Install NixOS and try to boot on late 2016 XPS 13.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
NixOS
* Nix version: (run `nix-env --version`)
Latest I assume
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
Whatever is on the latest

**Comment by liamwigney** [comment]
Issue was to do with raid mode.

**Comment by jdbosser** [comment]
liamwigney: how can you fail us/me like this?? Can you elaborate? 
![image](https://github.com/NixOS/nixpkgs/assets/3251406/fbd4e3b3-9437-4fad-8170-03b3fbc84ce3)

**Comment by ShadowCreator** [comment]
@jdbosser sorry haha, my eldest was a month old when I closed the issue so in my lack of sleep zombie state I didn't elaborate (I don't have access to the liamwigney account anymore but this was my alt).

My issue was really simple, after install I was changing from APCI back to RAID in the BIOS. But I needed to just leave the disk setting as APCI to book NixOS. 

The problem was that I was dual booting and windows was installed with RAID enabled so I had to manually swap between settings in the BIOS depending on which OS I was trying to use.

So the issue was literally RAID mode didn't/doesn't work like my admittedly short comment says. These days I only run NixOS so I just keep it in APCI mode! 

Hopefully this helps if you've got the same issue

**Comment by jdbosser** [comment]
I failed myself and the community. I think I managed to solve my issue, but I no longer remember how I solved it. Maybe, I managed to do something with APCI. I should have posted it here.

 I am impressed that you remember so many details, given that it was 7 years ago you found your fix. 
 
Thank you so much for taking the time to get back to this issue and update it.

**Comment by hiibolt** [comment]
> @jdbosser sorry haha, my eldest was a month old when I closed the issue so in my lack of sleep zombie state I didn't elaborate (I don't have access to the liamwigney account anymore but this was my alt).
> 
> My issue was really simple, after install I was changing from APCI back to RAID in the BIOS. But I needed to just leave the disk setting as APCI to book NixOS.
> 
> The problem was that I was dual booting and windows was installed with RAID enabled so I had to manually swap between settings in the BIOS depending on which OS I was trying to use.
> 
> So the issue was literally RAID mode didn't/doesn't work like my admittedly short comment says. These days I only run NixOS so I just keep it in APCI mode!
> 
> Hopefully this helps if you've got the same issue

I’d like to give my utmost thanks for coming back to share your solution, you saved me and likely others a ton of time!
