### ISSUE TITLE
pacman miss dependencies fakeroot

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#245839]
### Describe the bug

```
$ nix-shell -p pacman
$ makepkg
==> ERROR: Cannot find the fakeroot binary.
```

`fakeroot` doesn't come from <https://archlinux.org/packages/core/x86_64/pacman/>, it comes from <https://archlinux.org/packages/core/any/base-devel/>.

### Notify maintainers

@SamLukeYes

**Comment by Freed-Wu** [comment]
Seems to miss more dependencies:

```
$ nix-shell -p pacman fakeroot
==> ERROR: The download program curl is not installed.
```

**Comment by SamLukeYes** [comment]
If you're using an Arch-like distro, you can simply install `base-devel` on your system. If not, then building an Arch package directly on your host system through `makepkg` is not supported, since it requires Arch packages to be installed on your system. BTW, it's always recommended to [build in a clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot). I've packaged devtools in [Archix](https://github.com/SamLukeYes/archix/).
