### ISSUE TITLE
is it OK to run "nixos-rebuild switch" during a dd disk dump?

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#24603]
I have a disk dump running and curious if I should wait for it to complete before running nixos-rebuild switch or if it will remain unaffected and is OK to do so.  The dd is from one drive to another, neither is mounted or being used by nixos.

**Comment by teozkr** [comment]
A Nix rebuild shouldn't affect anything currently running, since the only stateful thing it does is flip around a few symlinks. That said, to stay on the safe side, you could run `nixos-rebuild boot` while it's building to download and build everything, and then run `nixos-rebuild switch` later to actually apply the changes.

**Comment by ob7** [comment]
Awesome, thank you for letting me know!  My dd is on a terabyte drive so I decided not to wait, and everything worked out.
