### ISSUE TITLE
Update request: woodpecker 0.15.11 → 1.0.0

### ISSUE THREAD

**Issue by Smaug123** [NixOS/nixpkgs#246104]
- Package name: `woodpecker-*`
- Latest released version: 0.15.8

- Current version on the unstable channel: 0.15.8
- Current version on the stable/release channel: 0.15.8
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ambroisie @techknowlogick

# Details

v1.0.0 [was released today](https://github.com/woodpecker-ci/woodpecker/releases/tag/v1.0.0), after a recent release candidate. There are a number of breaking changes, listed in the linked release notes. In particular, [the YAML config files have changed schema](https://github.com/woodpecker-ci/woodpecker/pull/1833) in a backward-incompatible way. However, this release does bring a number of welcome changes, e.g. [`when` evaluation filter expressions](https://github.com/woodpecker-ci/woodpecker/pull/1213), as well as a laundry list of bugfixes.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by ambroisie** [comment]
Nice to finally have a v1! 

A few notes:

* the move to `pnpm` is a small problem for packaging the front-end (see #231513)
* I have an old-ish `woodpecker-next` packaged on the NUR, from before they moved to `pnpm`, if you're in a rush to update.

I don't think we'll get the `pnpm` tooling moving soon, however we probably can package `woodpecker` either though:

* using the fork of `pnpm-lock-export` with v6 support.
* use a `package-lock.json` created by hand.

I am partial to the first option, as it keeps the set of packages similar to the one used by upstream rather than a potential different distribution in the lock file.

Finally, as mentioned in the issue, this release includes a bunch of breaking changes. This means updating the package must come with a note in the manual documenting them (simply pointing to up stream's should be fine).

**Comment by Smaug123** [comment]
I'm in no particular rush, thanks - this is all for a side project of mine anyway, and I have many things I should be doing rather than the side project!
