### ISSUE TITLE
Pharo VM is old

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#24616]
## Issue description

(This issue is intended to be self-assigned i.e. something that I will do when unblocked by dependencies.)

The stable Pharo VM in NixOS is an old version that is not compatible with the latest Pharo release (5.0). We should upgrade to a newer VM. The problem is that no newer official release is available yet: the Pharo community all seem to be running unofficial releases directly from CI.

One potential workaround would be to build a more recent version directly from Git but this is complicated. The version available in Git requires more bootstrapping than the official releases. In particular it requires you to already have another version of Pharo available for bootstrapping (and, circularly, the Pharo community usually use the latest version from CI for the build.) To reproduce this bootstrapping step in Nix seems both complex and also error prone if we would use an older Pharo to bootstrap from.

The best solution seems to be for upstream to make a new stable release. I am hoping that this will happen soon and when it does I will update nixpkgs. See [mailing list thread](http://lists.pharo.org/pipermail/pharo-users_lists.pharo.org/2017-April/031361.html) for status.

**Comment by lukego** [comment]
Slow progress.

Pharo upstream are telling me that they don't have the time to make a new source release of the VM. I suspect that everybody else is running binaries produced by their Jenkins CI (probably on Ubuntu.) I also don't know which commit from their master branch would be appropriate to build a NixOS package from because there are no tags and none of the individual commits look like obvious candidates to me.

Have to think about a new approach, possibly to replicate whatever their Jenkins CI is doing both in terms of build steps and also deciding which commits from their master branch are shippable.

Have to also think about whether that is an adequate solution. The reason I want to use Pharo via NixOS in the first place is that I have had a lot of problems with using the binaries provided by upstream. I want the nixpkgs version to be stable and dependable and this may require taking a different approach to upstream if they are just shipping their nightly builds all the time.

**Comment by 7c6f434c** [comment]
>Have to think about a new approach, possibly to replicate whatever their Jenkins CI is doing both in terms of build steps and also deciding which commits from their master branch are shippable.

Maybe just implement our own nightly-beta-stable loop on top of their 
nightly picks, with promotion being based of complaints not being 
applicable to the good candidate?

**Comment by lukego** [comment]
I nagged a little bit more (sigh, I don't like being that guy) and it sounds like they are going to make a new VM release but don't have the time at the moment due to an upcoming image release and conference ([mailing list post](http://lists.pharo.org/pipermail/pharo-users_lists.pharo.org/2017-April/031429.html)).

I am tempted to wait for a while and see what happens upstream. Browsing the [archive](http://files.pharo.org/vm/src/vm-unix-sources/blessed/) it looks like they usually make a VM release every few months and it's an exceptional situation now.

In the background I need to do a little more digging to understand the VM development work that is ongoing, specifically the status of transitioning to the new [Cog](http://www.mirandabanda.org/cogblog/about-cog/) VM and from 32-bit to 64-bit mode. I have the impression there is a lot going on in that space at the moment. It would be nice to shield nixpkgs users from having to worry about this if possible.

**Comment by das-g** [comment]
It looks like Pharo has replaced the pharo VM (or at least the GitHub repo?) with <https://github.com/opensmalltalk/opensmalltalk-vm>.

According to its [README.md](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/README.md) of the latter, the `opensmalltalk/opensmalltalk-vm` repo has C exports of the VMs' source code (which are being developed within such VMs in SmallTalk), so that the VMs can be built without needing the VMs first. (Thus solving the bootstrap problem you mentioned, I hope?)

Strangely, there seem to be **two** tags for the Pharo 7.0 VM:
* [`pharo7.0.0`](https://github.com/OpenSmalltalk/opensmalltalk-vm/tree/pharo7.0.0) (currently pointing to OpenSmalltalk/opensmalltalk-vm@5a38b3483dc5c82c7ecc85a590fdf1b095377a1f)
* [`Pharo7.0.0`](https://github.com/OpenSmalltalk/opensmalltalk-vm/tree/Pharo7.0.0) (currently pointing to OpenSmalltalk/opensmalltalk-vm@234f27281b46dbddd03a70e70901c910a4754385)

Maybe you can find out which one of these (if any) is the "official" one and/or corresponds to the "PharoVM 7.0 for Linux" binary download available on <https://pharo.org/download>?

**Comment by iNode** [comment]
Thanks for working on this. Are there any further news?

**Comment by ehmry** [comment]
Squeak is also using an old VM and should be updated to use OpenSmalltalk.
