### ISSUE TITLE
Missing man pages for packages with multiple outputs

### ISSUE THREAD

**Issue by nixy** [NixOS/nixpkgs#24717]
## Issue description

For packages with multiple outputs the default meta.outputsToInstall is `[ "out" ]` which won't install any documents/man pages required by this. On NixOS this is resolved using the man module as shown in the link below:

  https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/man.nix#L27

On other platforms such as Linux or Darwin, this NixOS option doesn't trigger and the meta.outputsToInstall defaults to `["out"]` which means missing man pages for any package that uses multiple outputs to separate its man pages.

This can be fixed by modifying the meta.outputsToInstall attribute for the specific package, but I feel like this behavior isn't intended and is more of a bug. Patching each package where including manuals makes sense seems like a pain.

### Steps to reproduce

On Darwin/Linux:

    nix-env -i nix
    nix-env --help || man nix-env || echo "Nobody here but us chickens"

## Technical details

* System: darwin x86_64
* Nix version: 1.11.8
* Nixpkgs version: 17.09pre105100.78adf1832f

**Comment by vcunat** [comment]
It's intentional, as it's a little difficult to guess what parts a user wants.  Configurability for `nix-env` is missing ATM, though it wouldn't be difficult to add an option to `~/.nixpkgs/config.nix`.

You can `nix-env -iA nixpkgs.nix.man`, but that's not much convenient.

**Comment by nixy** [comment]
I get that it can be hard to guess what parts a user wants and that there should be a flag in config.nix to set the default outputsToInstall, but at the same time these don't really seem like sane defaults right now. I think this is pretty bad for user experience on non NixOS platforms as a user who downloads Nix on Darwin right now can't even read the man pages to get started.

Also I should have been a little clearer about what I had tried in debugging this. I tried running `nix-env -iA nixpkgs.nix.man`, but that didn't install the man pages. It gave the following output and resulted in no perceivable difference in my ~/.nix-profile:

    +$ nix-env -iA nixpkgs.nix.man
    replacing old ‘nix-1.11.8’
    installing ‘nix-1.11.8’

So I think some flags should be added to ~/.nixpkgs/config.nix to allow users to specify a default outputsToInstall, but up till now the default was to install all ouputs. I think we should go back to installing all outputs by default for the sake of maintaining existing behavior and having a better user experience.

**Comment by vcunat** [comment]
I'll look into this.  It's all rather old work, so I've forgotten much.  The change to respect `meta.outputsToInstall` only now got into release 1.11.8 (instead of always installing everything).

The nixpkgs change should be easy enough, but I suspect there's something wrong in nix (1.11.8) itself about this.

**Comment by cyraxjoe** [comment]
Indeed, I noticed the problem when 17.03 was released, currently I worked around the issue by adding an overlay to include the man pages.
`.config/nixpkgs/default.nix`:
```
self: super:                                                                                                                                                                    
{                                                                                                                                                                               
  # add man to the outputs to install for nix                                                                                                                                   
  nix = super.nix.overrideAttrs (oldAttrs: {                                                                                                                                    
     meta = oldAttrs.meta // {                                                                                                                                                  
       outputsToInstall = [ "out" "man" ];                                                                                                                                      
     };                                                                                                                                                                         
  });                                                                                                                                                                           
}  
```

**Comment by vcunat** [comment]
It's not as easy as I imagined.  I somehow didn't implement the explicit choice of outputs into `nix-env` (e.g. `nix-env -iA nixpkgs.nix.man`);  I don't remember why.  Still, I don't think that part is important and there seem to be enough tools in Nix to handle this purely from nixpkgs, though it's all complicated by our various ways of using `buildEnv` &ndash; we probably don't want this choice in nixpkgs config to affect all `buildEnv` occurrences in nixpkgs...

**Comment by asppsa** [comment]
I'm a bit confused.  `man nix-env` says: "By default all outputs are installed for each derivation. That can be reduced by setting meta.outputsToInstall."  However, this issue states that only "out" will be installed by default, and it sounds like `meta.outputsToInstall` is rather used to grow the ouputs, instead of reducing them.

Is the manpage for nix-env out of date, perhaps?

**Comment by vcunat** [comment]
No, I think that's correct, as it's basically always set.  For details see: https://github.com/NixOS/nixpkgs/blob/release-17.03/pkgs/stdenv/generic/default.nix#L303

Documenting stuff can get confusing when you have "internal APIs" that most people don't (need to) use.

**Comment by matthewbauer** [comment]
This can be set up using "buildEnv": see #25955.

**Comment by kirelagin** [comment]
I’d say that this is even worse for `nix-shell` .

**Comment by twhitehead** [comment]
I have nix installed on my debian systems (use it for a variety of packages) and find it really inconvenient to not have the man pages installed for the nix commands by default.

Is the overlay hack the accepted way we are suppose to get around this?

**Comment by vcunat** [comment]
It certainly is **a** way.  A more comfortable one would be to install with `nix-env -iA channelName.withMan.packageName`, allowing you to choose per-package.  That's doable by one common definition in `packageOverrides`.

**Comment by twhitehead** [comment]
@vcunat thanks.  I just gave it a try on my machine and it doesn't seem to work though.

```bash
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
$ nix-channel --update
...
$ nix-env -iA nixpkgs.withMan.nix
error: attribute ‘withMan’ in selection path ‘nixpkgs.withMan.nix’ not found
```

I'm guessing you maybe mean to add an appropriate `withMan` definition via `packageOverrides`?

I was also digging through things a bit to try and figure out why installing the `packageName.doc` didn't give me anything different than `packageName`.

If I'm understanding correctly it is because `nix-env` bases it off the `meta.outputsToInstall` attribute (presumably it just pulls those top-level attributes from the derivation) and the [`derivation`](https://github.com/NixOS/nix/blob/1dd29d7aebae706f3e90a18bbfae727f2ed03c70/corepkgs/derivation.nix) function doesn't override the `meta.outputsToInstall` attributes for each of the output specific derivation attributes it adds (i.e., the added `doc` attribute is identical to the `out` attribute except the `outputName` is different).

Perhaps the nixpkgs [mkDerivaiton](https://github.com/NixOS/nixpkgs/blob/8efe90a3f45d0b3be2fa266c51875c1fd1dc0998/pkgs/stdenv/generic/make-derivation.nix) function could fix this up after the fact?  Something like this maybe

```nix
outputsOld = ...;   # The current derivation
outputNames = ...;  # A list of the outputs

let
  outputsNew = listToAttrs outputsList;

  outputsList = map (name: {
      name = name;
      value = getAttr name outputsOld // outputsNew;
      all = map (x: x.value) outputsList;
      meta.outputsToInstall = [ name ];
    }) outputNames

  in
    getAttr outputsOld.name outputsNew // {
      meta.outputsToInstall = outputsOld.meta.outputsToInstall;
    }
```

(a bit ugly as we have to retie `derivation`'s recursive knot -- but not too horrible).

**Comment by vcunat** [comment]
Right, that was just a suggestion.  One would have to add `withMan` definition, e.g. to `packageOverrides` :-)

**Comment by kballard** [comment]
As someone who doesn't know very much about Nix, and who just hit this issue with `tmux` missing a manpage (#35242), is there a simple instruction I can follow to get the tmux manpage right now?

**Comment by dtzWill** [comment]
> is there a simple instruction I can follow to get the tmux manpage right now?

This is very ad-hoc, but should do the trick:

```console
$ man $(nix-store -r /nix/store/iw9s784ydbgvr3rfhr6zhmvjkj062h70-tmux-2.6-man)/share/man/man1/tmux.1.gz
```

**Comment by kballard** [comment]
What I actually meant was some way to get nix to install the symlink.

**Comment by matthewbauer** [comment]
> What I actually meant was some way to get nix to install the symlink

This will work for installing tmux (you can set p to anything):

```
nix-env -i $(nix-instantiate --no-gc-warning -E 'with import <nixpkgs> {}; let p = tmux; in buildEnv { inherit (p) name; paths = [ tmux ]; extraOutputsToInstall = [ "man" ];}')
```

But, we definitely need a real solution to this.

**Comment by kballard** [comment]
Why does `nix-env -iA nixpkgs.tmux.man` not work? If I run that, it just installs tmux-2.6, and I still don't have manpages. (the `buildEnv` expression works, but a) it's awkward to replicate for other packages, and b) it's unclear to me if nix will tell me about any available updates to `tmux`, since it doesn't list the original `tmux` package as installed).

**Comment by vcunat** [comment]
It's a bug, as stated.  I don't think it really help searching for "why".

**Comment by twhitehead** [comment]
@kballard I believe I answered your question about why this happens in my earlier comment [above](#issuecomment-336509696).  That is, it doesn't make a difference because the `deviation` function gives `nixpkgs.tmux.man` the same `meta.outputsToInstall` value as `nixpkgs.tmux`, and this is what `nix-env` uses to determine what components it installs.

**Comment by Ericson2314** [comment]
We just landed something that should help with this, maybe even completely fix it.

**Comment by dtzWill** [comment]
So can we modify mkDerivation to add "man" to outputsToInstall by default/if it exists? Maybe keyed off a nixpkgs config setting?

This is a bit embarrassing, and hits users who haven't "bought" into Nix the hardest, since they don't use NixOS.

And it gets worse with every helpful commit diligently separating man pages by using multiple outputs.... :)

Are there any proposed fixes around in a branch? Let's fix this! :D

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/35071

**Comment by twhitehead** [comment]
Might be nice to fix the actually `derivation` function in nix itself too (or patch it up in `mkDerivation` as I suggested earleir) so that the individual output attributes have `meta.outputsToInstall` set to themselves so you can install them with `nix-env`.

For example, using `nix-repl`

```
$ nix-repl
Welcome to Nix version 1.11.13. Type :? for help.
nix-repl> :a import <nixpkgs> { }
Added 8292 variables.
nix-repl> tmux.outputs
[ "out" "man" ]
nix-repl> tmux.meta.outputsToInstall
[ "out" ]
nix-repl> tmux.man.meta.outputsToInstall
[ "out" ]
```

`tmux.man.meta.outputsToInstall` really should be `[ "man" ]` (or maybe even `[ "out" "man" ]`).

**Comment by dtzWill** [comment]
My hero.

```console
$ nix-env -f . -iA tmux
replacing old 'tmux-2.6-allexe'
installing 'tmux-2.6'
these paths will be fetched (0.03 MiB download, 0.03 MiB unpacked):
  /nix/store/wg7vqkbjmq1ivsxisc339dpjr848zn85-tmux-2.6-man
copying path '/nix/store/wg7vqkbjmq1ivsxisc339dpjr848zn85-tmux-2.6-man' from 'https://cache.nixos.org'...
building '/nix/store/5vil3pancacr9hp7g8302dchgihy62d0-user-environment.drv'...
created 3667 symlinks in user environment
```

Unfortunately it never makes it into my profile?
The high-level result is that `man tmux` doesn't work, but `ls ~/.nix-profile/share/man/man1` doesn't contain `tmux` either.   Is this expected? (sorry I haven't looked deeply at the PR or the underlying implementation details yet)

**Comment by dtzWill** [comment]
AFAICT the PR is intended to fix man pages for cc-wrapper, bintools-wrapper, and bash--but not "in general".  Is that correct?

**Comment by Ericson2314** [comment]
Yes. it sets up all the man outputs correctly, so that the general solution will actually work for those.

**Comment by oxij** [comment]
Related #38114.

**Comment by oxij** [comment]
Also related #11501.

**Comment by oxij** [comment]
Just wondering, though. I don't use `nix-env` much, so I didn't look at the related code very carefully. But from the top of my head, why can't `nix-env` and etc just use `pkgs.buildEnv` to build user environments (I mean, always, by default)? It would then be easy to have the effect of #35884 without any side-effects by just configuring that call to `pkgs.buildEnv`. No?

**Comment by matthewbauer** [comment]
> why can't nix-env and etc just use pkgs.buildEnv

Something like this is probably coming in the future. Note that "buildEnv" calls a perl script and we have been trying to get rid of the perl dependency in Nix. But a 'builtin' buildEnv written in C or Bash would definitely be useful.

**Comment by oxij** [comment]
Well, I don't like the idea of pushing more stuff into nix builtins, since `nix`, in practice, is the slowest thing to update on many systems and I'd like to be able to patch `buildEnv` at will (e.g. I have a pending feature branch that adds some awesome stuff there and I would like too keep that freedom to patch it without waiting two years for `nix` to update). But `buildEnv` in bash/C would be nice, yes.

**Comment by matthewbauer** [comment]
Actually correction on that- there is already a builtin buildenv. But it is much simpler than buildenv.pl:

https://github.com/NixOS/nix/blob/03d8136b02e8c5929dfc9db91214e34bdc8089be/corepkgs/buildenv.nix

**Comment by Ericson2314** [comment]
`nix-env` could simply be `nixpkgs-env`, part of Nixpkgs rather than Nix. That is an easy way to fix the layer violation while keeping nix simple.

**Comment by oxij** [comment]
> `nix-env` could simply be `nixpkgs-env`, part of Nixpkgs rather than Nix. That is an easy way to fix the layer violation while keeping nix simple.

:+1: That would be awesome. `nix-env` could then just manage the manifest and call configured hook (`nixpkgs-env` or whatever else) to do the actual environment building work.
