### ISSUE TITLE
fish shell installed with nix error at startup: "Runtime path not available."

### ISSUE THREAD

**Issue by puhsu** [NixOS/nixpkgs#247228]
### Describe the bug
Fish errors at startup, when installed on ubuntu via nix. With the following errors:
```sh
error: Runtime path not available.
error: Try deleting the directory /tmp/fish. and restarting fish.
```
After that it works fine.

### Steps To Reproduce
1. install nix on ubuntu (nix version 2.15.0) (18/22 reproduces on either one for me)
2. run `nix-env -iA nixpkgs.fish`
3. try starting fish with `fish`

### Expected behavior
fish startsup without error

### Additional context
This does not replicate on macos for me, fish runs and installs fine there.

### Notify maintainers

@cole-h 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-150-generic, Ubuntu, 18.04.6 LTS (Bionic Beaver), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - nixpkgs: `/nix/store/w7k58nkr2n6r00hgx6a3rf6zhidlwmd2-source`
```

**Comment by cole-h** [comment]
Did you try removing `/tmp/fish.`?

Is `XDG_RUNTIME_DIR` set in your environment? If so, to what?

Can you try running `XDG_RUNTIME_DIR=$(mktemp -d) fish`?

Looks like this error happens when it 1) can't get your user's login name from the information returned by `getpwuid(geteuid())`; or 2) it can't `mkdir` the tempdir, `lstat` the tempdir, the tempdir is not a directory, the tempdir is not owned by the user, or the permissions are not what it expects (I'm no C(++) expert, but it looks like they want the directory to not be RWX by group or others).

**Comment by puhsu** [comment]
There is no `/tmp/fish`, and the `XDG_RUNTIME_DIR` is not set. 

Running the `XDG_RUNTIME_DIR=$(mktemp -d) fish` runs fine, no error (thanks for the ok fix!). And the `/tmp`on my machine indeed has rwx on both group and others. 

Why the env var fixes this though?

**Comment by cole-h** [comment]
FYI, I was asking about `/tmp/fish.`, including the period, not `/tmp/fish`, excluding the period.

I don't know why it fixes it, but if you grep their codebase for one of those error messages, you'll find the function in question. Maybe Ubuntu doesn't enable XDG base dir stuff by default? I dunno, I don't use it.

**Comment by puhsu** [comment]
No `/tmp/fish.` either. Thanks for the fix anyway!
