### ISSUE TITLE
Package request: modrinth-app

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#247468]
**Project description**

A game launcher which can be used as a CLI, GUI, and a library for creating and playing modrinth projects

**Metadata**

* homepage URL: https://modrinth.com
* source URL: https://github.com/modrinth/theseus
* license: gpl3only
* platforms: linux, darwin

**Comment by pinkcreeper100** [comment]
oh I should probably ping @getchoo as they have a working package

**Comment by pinkcreeper100** [comment]
also tagging this issue on the theseus repo
https://github.com/modrinth/theseus/issues/497

**Comment by getchoo** [comment]
i would be alright maintaining this; the current working derivation is [here](https://github.com/getchoo/nix-exprs/blob/main/pkgs/theseus.nix). i'm merging support for darwin now, so the only real issues i can see are with proper desktop integration (may be sorted by upstream soon) and possibly splitting the package into an unwrapped and wrapped version similar to `prismlauncher`.

i think we should wait for a final stable release though, since as it stands there are some pretty annoying bugs such as the onboarding being a bit broken on both linux and darwin

**Comment by triphora** [comment]
It should be referred to as "modrinth-app", not "theseus" — theseus is not meant to be a public-facing name

**Comment by getchoo** [comment]
i've renamed it [here](https://github.com/getchoo/nix-exprs/pull/15) (along with some other fun things :p)
