### ISSUE TITLE
Improve error handling for nixos-rebuild

### ISSUE THREAD

**Issue by gepbird** [NixOS/nixpkgs#248572]
### Describe the bug
In the command `nixos-rebuild switch -I key=value`, invalid keys don't throw an error and get ignored.

### Steps To Reproduce
1. Run `nixos-rebuild switch -I NonExistentKey=something`
2. Watch it output the same text as the output of `nixos-rebuild switch` instead of giving an error.

### Expected behavior
It should give the user an error instead of ignoring it.

### Additional context
I've ran the command `sudo nixos-rebuild switch -I config=/path/to/my/configuration.nix` and it ran successfully, I even checked the exit code which is 0 but it generated a configuration I had weeks ago in /etc/nixos (initially I used that config but I soon copied my config to a folder in home). Took me a while to figure out that it should be **nixos-config** and not **config**. I assumed this command did what I intended it to do, since I've got no errors and it was building the configuration.

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/94x80fp2gyj14l6w4b8yn7kkgshifh2a-nix-info
copying path '/nix/store/94x80fp2gyj14l6w4b8yn7kkgshifh2a-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.11 (Tapir), 23.11pre505080.6cee3b58930`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixos"`
 - channels(gep): `"nixpkgs"`
 - nixpkgs: `/home/gep/.nix-defexpr/channels/nixpkgs`
```

**Comment by samueldr** [comment]
Hi, I'm triaging issues, and noticed this one. Sorry it took a while until someone answered.

This is a fundamental issue from how `NIX_PATH` is handled within Nix, and can't be "fixed" here, especially since the issue is not part of `nixos-rebuild`.

`-I` is basically a shortcut to appending to `$NIX_PATH` in-situ. `nixos-rebuild` directly passes the values down to `nix-build`.

NOTE: *Now, I'll continue with `nix repl`, but you should know that it acts exactly like `nix-build` would here.*

The values in `NIX_PATH` are not "arguments" provided to the evaluation, as in they are not passed as a function input.

```
 $ nix repl -I some=bogus -I other=wrong
Welcome to Nix 2.18.2. Type :? for help.

nix-repl>  
```

At this point, no expression has been evaluated yet. Those values though are "ambiantly" available in an impure Nix evaluation.

```
nix-repl> :p builtins.nixPath
[ { path = "bogus"; prefix = "some"; } { path = "wrong"; prefix = "other"; } { path = "/etc/system-channels"; prefix = ""; } { path = "/etc/nixos/configuration.nix"; prefix = "nixos-config"; } ]
```

Though they are normally assumed to be used with the angled-brackets syntax:

```
nix-repl> <nixos-config>      
/etc/nixos/configuration.nix

nix-repl> builtins.typeOf <nixos-config>
"path"
```

Here's what happens though if a bogus entry is requested:

```
nix-repl> <some>
warning: Nix search path entry 'bogus' does not exist, ignoring
error:
       … while calling the 'findFile' builtin

         at «string»:1:1:

            1| <some>
             | ^

       error: file 'some' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
```

So, for any error to be thrown, with the environment-variable-like design here, it all values would need to be attempted to be accessed. This would take a long time. Especially since entries unused shouldn't affect the evaluation.

Hopefully this properly explains why this can't be resolved as such.

* * *

With that said, IMO, though, this shows that the use of `NIX_PATH` to provide a location to a configuration file is the wrong way to handle this. It may be wise to add a `--file` (or similar) flag that handles that, abstracting away the `NIX_PATH` pains  when building an arbitrary configuration. Though I'm unsure if this can be done with the current design.
