### ISSUE TITLE
Using vim.ftNix = false in ~/.nixpkgs/config.nix makes vim inaccessible.

### ISSUE THREAD

**Issue by nixy** [NixOS/nixpkgs#24852]
## Issue description
The `vim.ftNix` option in config.nix is used to modify the behavior of vim_configurable, but it makes the `vim` package stop being evaluated. This is the same as if you set `vim.breakMe = false` seemingly setting nonexistant properties as false will break this.

### Steps to reproduce

Add `vim.ftNix = false` to ~/.nixpkgs/config.nix

Try `nix-env -iA nixpkgs.vim` and `nix-env -qa vim`

## Technical details

* System: darwin
* Nix version: 1.11.8
* Nixpkgs version: 17.09pre105126.efe12d6658

**Comment by edanaher** [comment]
If I'm understanding this correctly, vim.ftNix should be a top-level config option in your config.nix, which, AFAICT, doesn't break anything.  (It only appears to modify the build of qvim, which I'm not using, so I'm not sure it works.)

If you set vim.ftNix = false in packageOverrides in config.nix, then it would break, since you're now overriding the "vim" package, which is supposed to be a derivation, with the nearly empty set { ftNix = false}; nix-env will then correctly ignore this non-package.

To be a bit more clear:
```nix
{
  vim.ftNix = true; # Should enable the flag in qvim
  packageOverrides = pkgs: rec {
    # vim.ftNix = true; # Would hide the actual vim package if enabled
    # vim = { ftNix = true } # Equivalent to the line above
    vim = pkgs.vim.overridePackage {
      # The usual way to override packages, since this will start with the base vim package and apply your changes
    };
  };
}
```

I know I've been confused about what goes where in config.vim, so I'm guessing this is your issue.  If it isn't, it might be good if you could provide more detail (e.g., a full config.nix that reproduces the problem).

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by edanaher** [comment]
I'm not sure what "news" you're looking for; as my comment above indicates, my best guess is that this is user error.  If you have a config.nix that reproduces this issue, I'll happily take a look, but as it stands, I think this issue should have been closed.
