### ISSUE TITLE
Tmodloader on steam does not start

### ISSUE THREAD

**Issue by Dekomoro** [NixOS/nixpkgs#248854]
### Describe the bug
Tmodloader for Terraria on steam does not start

### Steps To Reproduce
1. Make sure both Terraria and Tmodloader are installed
2. Run Tmodloader

### Expected behavior
Tmodloader would have ran

### Additional context
Tmodloader needs to run a steam installed copy of Terraria in order to run itself. It fails to run Terraria only on Nixos

### Notify maintainers
@jonringer

**Comment by Yeshey** [comment]
This might be related with this issue: https://github.com/tModLoader/tModLoader/issues/2140

I was able to fix it in my case in by going in tModLoader:
> under the Compatibility section, checking the box that says "Force the use of a specific Steam Play compatibility tool" and choosing "Steam Linux Runtime" under the dropdown of options.
As suggested by https://github.com/tModLoader/tModLoader/issues/2140#issuecomment-1116687890.

That issue seems to have been fixed but I don't know if it has landed on nixOS yet, we'd have to check if the problem persists in that fixed version to see if this is a nixOS issue
