### ISSUE TITLE
many `xorg.*` tools are missing `mainProgram`

### ISSUE THREAD

**Issue by arcnmx** [NixOS/nixpkgs#249169]
Many command-line tools under the [`pkgs.xorg` attr](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/default.nix) are single-purpose tools that certainly want `meta.mainProgram` set, but will now complain if used with `lib.getExe`. For example, tools such as `setxkbmap` or `xinput`.

Since these derivations are [generated by a perl script](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/generate-expr-from-tarballs.pl), fixing this doesn't seem as trivial as it would be for most packages.

**Comment by jordilin** [comment]
Also seeing this related warning when running `nixos-rebuild` - xrandr

```
trace: warning: getExe: Package "xrandr-1.5.2" does not have the meta.mainProgram attribute. We'll assume that the main program has the same name for now, but this behavior is deprecated, because it leads to surprising errors when the assumption does not hold. If the package has a main program, please set `meta.mainProgram` in its definition to make this warning go away. Otherwise, if the package does not have a main program, or if you don't control its definition, use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
```

**Comment by Fryuni** [comment]
I sent this on the wrong issue (different tab while researching about this). This warning was caused by this PR:
- https://github.com/NixOS/nixpkgs/pull/246386

Overlay to remove the warning while the generating script is not changed:

```nix
_: pkgs:
{
  xorg = pkgs.xorg // {
    xrandr = pkgs.xorg.xrandr.overrideAttrs (_: prev: {
      meta = prev.meta // {
        mainProgram = "xrandr";
      };
    });
  };
}
```

[Artturi](https://github.com/Artturin) mentioned that there is a file to override attributes for the generated `xrandr` derivation, so I opened a PR for that. You can use the overlay above locally to remove the warning even without that PR.
