### ISSUE TITLE
NixOS hangs after shutdown/restart

### ISSUE THREAD

**Issue by marvin-bitterlich** [NixOS/nixpkgs#249388]
### Describe the bug
When I restart or shutdown my computer, it doesn't actually shut down and hangs at the end till I forcefully kill power. 

### Steps To Reproduce
1. Install nixos plasma edition
2. Press shutdown/reboot
3. 50% chance to hit this 

### Expected behavior
The computer should cut power itself. 

### Screenshots
![20230815_214443](https://github.com/NixOS/nixpkgs/assets/644950/1224af43-3028-45f4-a93d-808ebc1b9c90)

### Additional context
I have an intel system with an nvidea gpu, nothing fancy going on (I think) config all auto generated, newest stable, allowed unfree with nvideoa driver

### Metadata

```console
[marvin@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.45, NixOS, 23.05 (Stoat), 23.05.2775.720e61ed8de1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(marvin): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

If theres anything else I can provide I'll do so once I'm at my pc again :)

**Comment by Majiir** [comment]
Huh. I also have this issue. I had assumed it was my power supply going bad or something, but maybe not. My setup:

- Intel i7-8700K
- Nvidia GTX 1080 Ti
- Using the proprietary Nvidia driver
- NixOS 23.05

**Comment by michaelshmitty** [comment]
Same problem here, on an Intel NUC 7 running NixOS unstable. It's at the office and down now because of an attempted reboot after autoupgrade at around 4am this morning. I'll probably put a sonoff switch between it so I can hard reboot it from a distance.
Anyway... I feel like this _could_ be an issue with the Linux kernel integrating with the hardware or some buggy UEFI bios, acpi stuff.
What I would really like to know is where to start to debug this. It doesn't happen all the time, I can't reliably reproduce it.
This may not even be a NixOS specific issue. For reference I found this 10-year old (!) stack overflow post: https://unix.stackexchange.com/questions/80687/rebooting-fails-randomly

One answer there talks about getting into kernel debugging. I don't mind getting into that if that's the way to really get to the bottom of this. The journal log doesn't seem to indicate any problem. Must be after it's all shut down, some interrupt that fails or something.

There's also **a ton** of options in my UEFI bios on that NUC related to power, could be an issue with any one of those. I kinda miss the days when a BIOS was dead simple and not its own OS! :p

**Comment by buckley310** [comment]
The last line from the screenshot there appears to be the actual kernel message saying that the kernel is telling the hardware to reset. There's not a lot of room for the distro to get in the way of that :thinking:

Have you tried upgrading to kernel 6.4 and/or trying to recreate this issue on another distro that uses kernel 6.1?

Are you enabling `hardware.cpu.intel.updateMicrocode` and `hardware.enableRedistributableFirmware` ?

**Comment by Majiir** [comment]
I have `hardware.cpu.intel.updateMicrocode` and `hardware.enableRedistributableFirmware` enabled. I should also mention that I run ZFS on root, which is why the kernel version is held back to `6.1.44`. @marvin-bitterlich Are you also running ZFS by chance?

**Comment by marvin-bitterlich** [comment]
![20230828_173703](https://github.com/NixOS/nixpkgs/assets/644950/bb60b2d6-0f4d-488d-9f54-5c3f17392071)
Update: restarted just now and it hang again.

With two people who have the same combination of both CPU and GPU, it seems to suggest something related to that?

**Comment by marvin-bitterlich** [comment]
@buckley310 
> Have you tried upgrading to kernel 6.4 and/or trying to recreate this issue on another distro that uses kernel 6.1?

Its my main OS so I don't have the luxury to try out a different distro with it. But I can update Kernel versions as a test, would just have to figure out how to :)

**Comment by n8henrie** [comment]
Having the same / similar issue on an RPi4 on 23.05, using the rpi4 kernel, on a ZFS root. Spent several hours trying to debug over the last couple of days.

Setting the watchdog reboot timer to 15s successfully forces a reboot (there an error about the 10m default), but clearly isn't the *right* way to go about it.

**Comment by Majiir** [comment]
@marvin-bitterlich Can you confirm whether you are using ZFS on root? That could also be the common factor if so.

**Comment by marvin-bitterlich** [comment]
> @marvin-bitterlich Can you confirm whether you are using ZFS? That could also be the common factor if so.

I mentioned above, but again no, I am using ext4 and swap, nothing else.

**Comment by marvin-bitterlich** [comment]
I am going to try the acpi one for a bit to see if that helps. Just a note though that it also happens on shutdowns, not just reboots

**Comment by n8henrie** [comment]
On my Pi4:

I had no luck with `reboot=efi`, `reboot=bios`, `reboot=acpi`, or `reboot=pci`.

To try to help debug, based on https://www.freedesktop.org/software/systemd/man/systemd-poweroff.service.html, I added:

```nix
boot.kernelParams = [
      "systemd.log_level=debug"
      "systemd.log_target=kmsg"
      "log_buf_len=1M"
      "enforcing=0"
    ];
 systemd.shutdown."debug.sh" = pkgs.writeScript "debug.sh" ''
      #!/bin/sh
      mount -o remount,rw /
      dmesg > /shutdown-log.txt
      mount -o remount,ro /
      reboot
    '';
```

I don't see anything super interesting in the resulting `shutdown-log.txt`, the last few lines are below.

<details>
<summary>shutdown-log.txt</summary>

```
[  134.797395] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  134.811511] systemd-journald[1002]: Received SIGTERM from PID 1 (systemd-shutdow).
[  134.811555] systemd-journald[1002]: Exit event sources are now pending.
[  134.811636] (udev-worker)[3471]: Unload kernel module index.
[  134.811643] (udev-worker)[3474]: Unload kernel module index.
[  134.811649] (udev-worker)[3585]: Unload kernel module index.
[  134.811862] (udev-worker)[3471]: Unloaded link configuration context.
[  134.811903] (udev-worker)[3474]: Unloaded link configuration context.
[  134.811925] (udev-worker)[3585]: Unloaded link configuration context.
[  134.812608] systemd-journald[1002]: systemd-journald stopped as PID 1002 for the system.
[  134.826442] systemd-udevd[1022]: Worker [3474] exited.
[  134.826571] systemd-udevd[1022]: Worker [3585] exited.
[  134.826652] systemd-udevd[1022]: Worker [3471] exited.
[  134.827909] systemd-udevd[1022]: Unload kernel module index.
[  134.828112] systemd-udevd[1022]: Unloaded link configuration context.
[  134.830508] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  134.844160] systemd-shutdown[1]: Unmounting file systems.
[  134.845241] systemd-shutdown[1]: Successfully forked off '(sd-remount)' as PID 3589.
[  134.845880] (sd-remount)[3589]: Remounting '/nix/store' read-only with options 'xattr,posixacl'.
[  134.858666] systemd-shutdown[1]: Successfully forked off '(sd-remount)' as PID 3590.
[  134.859273] (sd-remount)[3590]: Remounting '/nix' read-only with options 'xattr,posixacl'.
[  134.861580] systemd-shutdown[1]: Successfully forked off '(sd-remount)' as PID 3591.
[  134.862179] (sd-remount)[3591]: Remounting '/' read-only with options 'xattr,posixacl'.
[  134.864932] systemd-shutdown[1]: All filesystems unmounted.
[  134.864948] systemd-shutdown[1]: Deactivating swaps.
[  134.865060] systemd-shutdown[1]: All swaps deactivated.
[  134.865070] systemd-shutdown[1]: Detaching loop devices.
[  134.867315] systemd-shutdown[1]: All loop devices detached.
[  134.867328] systemd-shutdown[1]: Stopping MD devices.
[  134.867548] systemd-shutdown[1]: All MD devices stopped.
[  134.867558] systemd-shutdown[1]: Detaching DM devices.
[  134.867758] systemd-shutdown[1]: All DM devices detached.
[  134.867769] systemd-shutdown[1]: All filesystems, swaps, loop devices, MD devices and DM devices detached.
[  134.868302] systemd-shutdown[1]: Successfully forked off '(sd-executor)' as PID 3592.
[  134.876841] (sd-executor)[3592]: Successfully forked off '(direxec)' as PID 3593.
[  134.877526] (sd-executor)[3592]: Successfully forked off '(direxec)' as PID 3594.
[  134.894544] (sd-executor)[3592]: /nix/store/2159n1jib47g4g310jmi2dn0kc7yab60-system-shutdown/mdadm.shutdown succeeded.
```
</details>

**Comment by n8henrie** [comment]
Partly for my own documentation...

After reading a few threads, with a little more tinkering on my UEFI Pi4, I found:

- I **cannot** reboot with the RPi kernel, even with docker and/or [bluetooth disabled](https://forum.manjaro.org/t/new-raspberry-pi-kernels-related-packages/4721/970?page=49)
- I **can** reboot with the stock kernel (latest ZFS compatible)
- Setting `8250.nr_uarts=1` ([source](https://github.com/pftf/RPi4/issues/182)) allows a reboot even with the RPi kernel and with bluetooth enabled; I still have a docker container that is hanging, but that's a separate issue. As long as I disable that container, `8250.nr_uarts=1` allows me to reboot successfully.

**Comment by Majiir** [comment]
> - Intel i7-8700K 
> - Nvidia GTX 1080 Ti
> - Using the proprietary Nvidia driver
> - NixOS 23.05

Data point: With this hardware, `reboot=acpi` fixed the issue for me.

**Comment by chiefnoah** [comment]
I'm encountering a very similar problem that is almost certain caused by a recent update to NixOS 23.11's channel, possibly in AMD microcode, but we'll see if anyone has other ideas.

Hardware info: GEEKOM A7 (AMD Ryzen 9 7940HS w/ Radeon 780M)

Relevant configuration:

```nix
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "amdgpu"];
  boot.extraModulePackages = [ ];

  hardware.enableRedistributableFirmware = true;

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelParams = ["apm=power_off" "acpi=force" "reboot=acpi"];

}
```

It just started happening within the last week. I also tried using a bootable flashdrive that I created a few months ago from an earlier generation of my nix config and the issue was not there, so it's almost certainly a package/software problem.

**Comment by lucaato** [comment]
> I'm encountering a very similar problem that is almost certainly caused by a recent update to NixOS 23.11's channel, possibly in AMD microcode, but we'll see if anyone has other ideas.

Hi @chiefnoah, I had the same problem after my last update of the flake inputs on nixpkgs unstable. 
I solved it by downgrading the kernel. Could you try doing the same ? After the update I was on kernel version `6.6.31`, i downgraded to `6.6.28` and now i can correctly shutdown the system.
If it works for you too we can stop necropostings :smiley: and open a proper issue.
I do not have any more info about the issue because it hangs after stopping the journal so i can't read any logs there.

**Comment by chiefnoah** [comment]
If I blacklist the `amdgpu` kernel module at boot and do nothing else the problem goes away, suggesting that this is a bug in the `amdgpu` driver in the kernel. I'm on a mostly stable Nixos 23.11 system with the latest stable kernel for that channel:

```shell
$ uname -a
Linux odin 6.1.91 #1-NixOS SMP PREEMPT_DYNAMIC Fri May 17 09:56:25 UTC 2024 x86_64 GNU/Linux
```

I'll attempt downgrading to the last point release (`6.1.90`) and report back. It looks like [the latest 6.1 kernel has a couple of patches to the amdgpu driver](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/?id=v6.1.92&id2=v6.1.91&dt=2) that might be relevant.

**Comment by chiefnoah** [comment]
I switched to the "zen" kernel instead (it seemed easier than trying to pin an older point release) and issue is gone, so most definitely a kernel issue. I'll wait for the latest 6.1 point release to become available and see if that resolves it before I submit a bug report to the LKML

**Comment by RafTeog** [comment]
> I'm encountering a very similar problem that is almost certainly caused by a recent update to NixOS 23.11's channel, possibly in AMD microcode, but we'll see if anyone has other ideas.
> 
> Hardware info: GEEKOM A7 (AMD Ryzen 9 7940HS w/ Radeon 780M)
> 
> Relevant configuration:
> 
> ```nix
> { config, lib, modulesPath, ... }:
> 
> {
>   imports =
>     [ (modulesPath + "/installer/scan/not-detected.nix")
>     ];
> 
>   boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
>   boot.initrd.kernelModules = [ ];
>   boot.kernelModules = [ "kvm-amd" "amdgpu"];
>   boot.extraModulePackages = [ ];
> 
>   hardware.enableRedistributableFirmware = true;
> 
>   networking.useDHCP = lib.mkDefault true;
> 
>   nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
>   hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
> 
>   # Use the systemd-boot EFI boot loader.
>   boot.loader.systemd-boot.enable = true;
>   boot.loader.efi.canTouchEfiVariables = true;
>   boot.kernelParams = ["apm=power_off" "acpi=force" "reboot=acpi"];
> 
> }
> ```
> 
> It just started happening within the last week. I also tried using a bootable flashdrive that I created a few months ago from an earlier generation of my nix config and the issue was not there, so it's almost certainly a package/software problem.

I have exactly the same problem, at exactly the time frame mentioned. Running all amd hardware here. This was the config that was working <https://github.com/RafTeog/nixos-sway-basic>. The last commit was on the day that the problem started happening. And only sway stuff was changed, nothing on config or hard-config. I will try the solution kindly mentioned by @chiefnoah. 

Thank you!

**Comment by TerminalTilt** [comment]
I fixed this on my system (MSI Z690-A WIFI DDR4, i7-12700KF, RX 5700 XT, kernel 7.1.3) by enabling `CONFIG_POWER_RESET` via `boot.kernelPatches`:

```nix
boot.kernelPatches = [{
  name = "enable-power-reset";
  patch = null;
  structuredExtraConfig = with pkgs.lib.kernel; {
    POWER_RESET = yes;
  };
}];
```

Also added:

```nix
systemd.settings.Manager.DefaultTimeoutStopSec = "5s";
```

Root cause: NixOS's default kernel config ships without CONFIG_POWER_RESET=y. Other distros (Arch, CachyOS) enable it by default. Without it, the kernel can't properly trigger the final ACPI reset on some motherboards.

Same hardware ran Arch without issue, same kernel version, different kernel config. This is NixOS-specific.

Things I tried that did NOT work:

- reboot=acpi
- reboot=t (triple fault)
- reboot=pci
- reboot=efi
- reboot=bios
- nowatchdog
- amdgpu.dc=0
- amdgpu.gpu_recovery=1
- Zen kernel

None fixed it. The issue was never the GPU or kernel version, it was a missing kernel config option specific to NixOS's kernel build.

My journal log from before the fix showed systemd reaching "System Shutdown" then the watchdog message before hanging:

```
systemd[1]: Reached target System Shutdown.
systemd[1]: Finished System Reboot.
systemd[1]: Reached target System Reboot.
systemd[1]: Shutting down.
kernel: watchdog: watchdog0: watchdog did not stop!
```

After applying the POWER_RESET fix, reboot completes cleanly with no hang.

Hardware comparison if useful:

- Motherboard: MSI PRO Z690-A WIFI DDR4 (MS-7D25)
- BIOS: 7D25v1N (April 2026) - latest available
- GPU: Sapphire Radeon RX 5700 XT (Navi 10)
- Kernel: 7.1.3 (linuxPackages_latest)
- Distro: NixOS unstable
