### ISSUE TITLE
pulseaudio: mismatched nixpkgs.config.pulseaudio and hardware.pulseaudio.enable

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#25030]
## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by joachifm** [comment]
I suppose the reason is that Nixpkgs is more general purpose than just serving the needs of NixOS.  Pulseaudio's merits aside, it probably makes sense to enable it for a general-purpose package set. If packages were not built with pulseaudio support, toggling the NixOS option would incur a huge rebuild whereas now you just get some annoying warnings, much less painful and easier to rectify :)

**Comment by gnidorah** [comment]
@joachifm Thank you for the answer! I'm more just about setting `hardware.pulseaudio.enable` to true by default. This should give better out-of-box experience on NixOS, and shouldn't break nixpkgs usage on other platforms (as option is NixOS only). Anything against this?

**Comment by FRidh** [comment]
@gnidorah you wouldn't want to enable pulseaudio on your server. I think it makes more sense to just have the option presented in the default `configuration.nix`.

**Comment by gnidorah** [comment]
@FRidh Ah, indeed. Thank you! I've created #25077 PR for this.

**Comment by gnidorah** [comment]
Continuing in PR
