### ISSUE TITLE
override ghc containers version?

### ISSUE THREAD

**Issue by kwquick** [NixOS/nixpkgs#25045]
## Issue description

Working with a haskell package that requires containers >= 0.5.8, but ghc802 seems to have containers 0.5.7.1 as a builtin.  Wondering if/how it is possible to override this setting.

### Steps to reproduce

I tried the override instructions at https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/haskell.md#how-to-override-package-versions-in-a-compiler-specific-package-set but `containers = self.callPackage ./containers-0.5.8.2` results in nix-env failing with an infinite recursion error.  It seems that containers is special (nixpkgs/pkgs/development/haskell-modules/configuration-ghc-8.0.x.nix sets it to null, which apparently means it comes from the ghc build itself, as confirmed by: 

```$ nix-shell -p ghc
[nix-shell:~]$ ghc-pkg describe containers
...
library-dirs: /nix/store/hg0ppf88q1.../ghc-8.0.2/containers-0.5.7.1
...
[nix-shell:~]$ which ghc
/nix/store/hg0ppf88q1.../ghc-8.0.2/bin/ghc
```

I can successfully override the containers passed to my specific library, but since containers is used by almost everything (10949 references in hackage-packages.nix), all the other packages that nix-env brings into scope are built with the ghc-provided version, and `cabal configure` reports conflicts and fails.

I would like to know if there is an easy way to override the containers version.  I realize that will probably result in a local rebuild of ghc itself, along with *all* of the hackage packages, but that's a one-time cost I'm OK with.  I can presumably do it by cloning nixpkgs and creating a new haskell.packages.ghc802local version and tweaking  things all over the place, but I'm wondering if there is a simpler, more elegant way to approach something like this.

I'd be happy to contribute back to the doc referenced above with the results if someone was able to provide some guidance.

## Technical details

* System: NixOS: 17.03.917.12a39478fd (Gorilla)`
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.03.917.12a39478fd

**Comment by ljli** [comment]
You shouldn't have to rebuild GHC. The [boot packages](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory) always end up in the pkg-db that GHC sees during compilation, but when multiple packages are included newer packages take precedence. As long as all dependencies of your package can be build with the newer `containers`, all is good. I would either use `extend` on a pkg set or `overrideScope` on an individual package, the result should be the same. This "deep" overrides the dependency for all packages that rely on it. They have to be rebuilt then. Assuming `my-pkg` is already part of the package set otherwise you would have to `callPackage` it, too.
Example:
```
# my-pkg.nix
let pkgs = import <nixpkgs> {};
    my-haskell-pkgs = pkgs.haskell.packages.ghc802.extend (self: super: {
      containers = super.callPackage ./containers-0.5.8.2 {};
    });
in my-haskell-pkgs.my-pkg
```
With overrideScope:
```
...
pkgs.haskell.packages.ghc802.my-pkg.overrideScope (self: super: {
  containers = super.callPackage ./containers-0.5.8.2 {};
})
```

**Comment by peti** [comment]
You cannot override `containers` in any meaningful (other than patching a newer version into the source code of `ghc` itself). It's a core package that's part of the compiler, and using any other version than that one is not possible, in general.
