### ISSUE TITLE
Package request: Hyprshot

### ISSUE THREAD

**Issue by sanjayjaras** [NixOS/nixpkgs#250853]
**Project description**
Hyprshot is an utility to easily take screenshot in Hyprland using your mouse.

It allows taking screenshots of windows, regions and monitors which are saved to a folder of your choosing and copied to your clipboard.

**Metadata**

* homepage URL:https://github.com/Gustash/Hyprshot
* source URL:https://github.com/Gustash/Hyprshot
* license: [GPL-3.0 
* platforms: unix, linux, darwin, ...

**Comment by AndersonTorres** [comment]
It reminds me of learn [resholve](https://github.com/abathur/resholve)!

**Comment by SrEstegosaurio** [comment]
I'm pretty close to getting the derivation finished.

Although this would be my very first time contributing to `nixpkgs` and writing a derivation for a shellscript so I cannot guarantee the quality my first iteration. 😅

I'll be more than happy to improve and fix ti in order to fit the required standards.

**Comment by AndersonTorres** [comment]
Are you using resholve?

**Comment by SrEstegosaurio** [comment]
I wasn't aware of that project until now. It seams great to be able to deal with dependencies in a nix-y way.
Now I want to look into it and explore it. A lot of projects could benefit from it.

I was approaching the problem using [this post](https://discourse.nixos.org/t/packaging-a-bash-script-issues/20224/3?u=11453ab5) as a reference. Hope is not much of crime....

I've kinda finished writing my derivation _(I only need to check if it works and properly fill all metadata if possible)_.

I'm a bit stuck since following the nixpkgs manual on packaging I cannot get my derivation to build. Nothing happens if I try `nix-build -A hyprshot`. What could be causing this?

**Comment by Cryolitia** [comment]
Hello, I have create a PR, hope it helps ^_^

https://github.com/NixOS/nixpkgs/pull/268237

**Comment by Cryolitia** [comment]
close by #268237
