### ISSUE TITLE
OBS is missing virtual camera functionality

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#251655]
### Describe the bug
On other distros OBS has a "Start Virtual Camera" button below the "Start Recording" button, but on NixOS it is missing. AFAIK this is based on v4l2loopback.

### Notify maintainers

@jb55  @MP2E 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.4.11, NixOS, 23.11 (Tapir), 23.11.git.91a22f76cd17M`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wentasah** [comment]
I have the button in OBS with the following in `/etc/nixos/configuration.nix`:
```nix
boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
boot.kernelModules = [
  "v4l2loopback"
];
```

**Comment by jansol** [comment]
That does indeed fix it. And I see it's mentioned [on the wiki](https://nixos.wiki/wiki/OBS_Studio) too.

**Comment by srghma** [comment]
followed https://nixos.wiki/wiki/OBS_Studio

but it asked my sudo password

added 

```
  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.policykit.exec" &&
            action.lookup("program") == "/run/current-system/sw/bin/modprobe" &&
            subject.isInGroup("users")) {
            return polkit.Result.YES;
        }
    });
  '';
```

and it worked


full config

```
{ config, lib, pkgs, modulesPath, inputs, settings, localpkgs, ... }:

let
  mypkgs = pkgs.nixpkgsMaster.pkgs;

  obs = mypkgs.wrapOBS {
    plugins = with mypkgs.obs-studio-plugins; [
      advanced-scene-switcher
      # obs-pipewire-audio-capture
      droidcam-obs
      # obs-shaderfilter
      # input-overlay
      # obs-source-clone
      # looking-glass-obs
      obs-source-record
      # obs-3d-effect
      # obs-teleport
      obs-backgroundremoval
      # obs-vaapi
      # obs-command-source
      # obs-vintage-filter
      # obs-gstreamer
      # obs-vkcapture
      # obs-hyperion
      # obs-websocket
      # obs-livesplit-one
      # obs-move-transition
      # obs-multi-rtmp
      # obs-ndi
      # wlrobs
      # obs-nvfbc
    ];
  };
in
{
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
  ];
  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=1 card_label="My OBS Virt Cam" exclusive_caps=1
  '';
  security.polkit.enable = true;

  # subject.isInGroup("users")
  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.policykit.exec" &&
            action.lookup("program") == "/run/current-system/sw/bin/modprobe" &&
            subject.isInGroup("users")) {
            return polkit.Result.YES;
        }
    });
  '';

  # boot.extraModulePackages = [
  #   config.boot.kernelPackages.v4l2loopback # Webcam loopback
  # ];

  # boot.kernelModules = [
  #   "v4l2loopback" # Webcam loopback
  #   # "snd-aloop"
  # ];
  # services.usbmuxd.enable = true; # Webcam loopback

  environment.systemPackages = [
    obs

    # Webcam packages
    # mypkgs.v4l-utils
    # mypkgs.android-tools
    # mypkgs.adb-sync
    # mypkgs.usbmuxd
  ];
}
```

**Comment by wentasah** [comment]
> followed https://nixos.wiki/wiki/OBS_Studio

Please use the official wiki: https://wiki.nixos.org/wiki/OBS_Studio.
 
> but it asked my sudo password
> 
> added
> 
> ```nix
>   security.polkit.extraConfig = ''
>     polkit.addRule(function(action, subject) {
>         if (action.id == "org.freedesktop.policykit.exec" &&
>             action.lookup("program") == "/run/current-system/sw/bin/modprobe" &&
>             subject.isInGroup("users")) {
>             return polkit.Result.YES;
>         }
>     });
>   '';
> ```

This doesn't look very secure. If I understand it correctly, this allows every user of the system to load arbitrary kernel modules.

**Comment by srghma** [comment]
> Please use the official wiki: https://wiki.nixos.org/wiki/OBS_Studio.

it didnt work for me

1. I open obs in terminal
1. I click button "start virtual camera"
1. I see in terminal logs it asks my user password to escalate to sudo
1. I enter password
1. doesnt work, "Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date." error in gui


log

```
...

==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/run/current-system/sw/bin/modprobe v4 ... _caps=1 card_label=OBS Virtual Camera' as the super user
Authenticating as: Serhii Khoma (srghma)
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
info: Starting Virtual Camera output to Scene : My Scene

```


> This doesn't look very secure

can fix to 

subject.user == "srghma"

```
  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.policykit.exec" &&
            action.lookup("program") == "/run/current-system/sw/bin/modprobe" &&
            subject.user == "srghma") {
            return polkit.Result.YES;
        }
    });
  '';
```


<details>
  <summary>Can be improved using wrapper script solution from ChatGPT</summary>
  
To allow only the loading of a specific kernel module, such as a camera module, you can modify the Polkit rule to include a condition that checks the specific module being loaded. However, `modprobe` doesn't provide a straightforward way to enforce this directly via Polkit since it doesn't expose the module name in a way that Polkit rules can inspect.

One way to achieve this is by creating a wrapper script around `modprobe` that enforces the loading of only specific modules and then configuring Polkit to allow the execution of this script.

### Steps to Implement

1. **Create a Wrapper Script for Modprobe:**
   Create a script, for example, `/usr/local/bin/modprobe-camera`, that only allows loading the specific camera module (replace `camera_module_name` with the actual module name).

   ```bash
   #!/bin/bash

   if [ "$1" == "camera_module_name" ]; then
     /run/current-system/sw/bin/modprobe "$@"
   else
     echo "Error: Only the camera module can be loaded via this script."
     exit 1
   fi
   ```

   Make sure to make the script executable:
   ```bash
   sudo chmod +x /usr/local/bin/modprobe-camera
   ```

3. **Modify the Polkit Rule to Allow Execution of the Wrapper Script:**
   Update your NixOS configuration to allow the user `srghma` to execute the wrapper script with elevated permissions.

   ```nix
   security.polkit.extraConfig = ''
     polkit.addRule(function(action, subject) {
         if (action.id == "org.freedesktop.policykit.exec" &&
             action.lookup("program") == "/usr/local/bin/modprobe-camera" &&
             subject.user == "srghma") {
             return polkit.Result.YES;
         }
     });
   '';
   ```

4. **Rebuild Your NixOS Configuration:**
   Apply the changes by rebuilding your NixOS configuration.

   ```bash
   sudo nixos-rebuild switch
   ```

5. **Test the Wrapper Script:**
   As the user `srghma`, try loading the camera module using the wrapper script.

   ```bash
   modprobe-camera camera_module_name
   ```

   It should load the module if it is the camera module and deny loading any other modules.

### Explanation:
- **Wrapper Script**: The script ensures that only the specified camera module can be loaded. It checks the first argument (`$1`) to see if it matches `camera_module_name` and only then calls the actual `modprobe` command.
- **Polkit Rule**: The Polkit rule grants the user `srghma` permission to execute the wrapper script with elevated permissions, ensuring that the security is enforced while allowing the required functionality.

By following these steps, you limit the user's ability to load kernel modules to only the specified camera module, enhancing the security of your system.
  
</details>

**Comment by jansol** [comment]
> can fix to
>
> subject.user == "srghma"

Orrr you could add "video" to that user's "extraGroups", which gives you access to camera devices including the v4l2loopback module which the virtual camera relies on. Then you don't need any of this polkit hackery.

**Comment by srghma** [comment]
@jansol

I already have had

```
 ~  groups
users wheel disk audio video dialout networkmanager libvirtd docker adbusers
 ~  nix-info                                                                                          
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.18.2, channels(root): "nixos-24.05, nixpkgs, nixpkgs-master, nixpkgs-unstable", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```
