### ISSUE TITLE
ACME cert renewal overwrites ownership for other certs, breaking services

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixpkgs#25182]
## Issue description
If you have multiple acme certs with different user/group ownership, whenever the renew timer for one fires (even if the cert doesn't need to be renewed), it will overwrite the ownership for all the other certs.

The root cause is [this line](https://github.com/nh2/nixpkgs/blob/ee0f3e7ad9aa61f02283eb1c18f670703eea20ca/nixos/modules/security/acme.nix#L181), introduced in #24532; it resets the ownership for *everything* under `cfg.directory` -- /var/lib/acme by default -- including other certs that have other ownership configured.

This is at best an outage (your mail certs get reset to `nginx:nginx` and now your mail server can't read them and rejects all incoming connections because it can't SSL) and at worst a security risk (your webserver cert gets reset to `nginx:something` and is now visible to a bunch of things that aren't the webserver).

### Steps to reproduce
```
  security.acme.certs."mail.example.ca" = {
    email = "postmaster@example.ca";
    group = "mail";
    allowKeysForGroup = true;
  };

  services.nginx = {
    enable = true;
    virtualHosts = {
      "mail.example.ca" = {
        forceSSL = true;
        enableACME = true;
      };
      "kittens.example.ca" = {
        forceSSL = true;
        enableACME = true;
        locations."/".root = "/srv/kittens";
      };
    };
  };

```

Note that the `acme-mail.example.com.service` PreStart opens with `chown -R 'nginx:mail' '/var/lib/acme'`, while the `acme-kittens.example.com.service` PreStart has `chown -R 'nginx:nginx' '/var/lib/acme'`; whichever one runs last will "win", overwriting the permissions for all the other certs.

## Technical details

* System: 17.09pre105553.da20d0e488 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: 17.09pre105622.f0fac3b578

**Comment by domenkozar** [comment]
Cc @nh2

**Comment by nh2** [comment]
> whichever one runs last will "win", overwriting the permissions for all the other certs

> introduced in #24532

```diff
-                    chown '${data.user}:${data.group}' '${cfg.directory}'
+                    chown -R '${data.user}:${data.group}' '${cfg.directory}'
```

To my defense and that of #24532, the "owner toggling" was already there before it (just that it happened at the directory level and the `-R` made it more visible), so it didn't occur to me that this dir was intended for more than 1 user. I fell bad about it still for breaking your setup by making this problem more apparent - very sorry.

---

@ToxicFrog You are totally right, this toggling behaviour is wrong.

It seems to me that the right solution would be to remove the `chown ${data.user}` (`cfg.directory`) from there altogether, and have it `drwxr-xr-x root root`, and only the `cpath = "${cfg.directory}/${cert}";` use `chown -R`.
Same thing for the directory hierarchy `/var/lib/acme/acme-challenge/.well-known/acme-challenge/`

@domenkozar @ToxicFrog Do you agree?

What might not be so obvious is what to do with `security.acme.certs.<name>.webroot`, when the same value is shared across multiple certs; for example, `services.nginx.virtualHosts.<name>.acmeRoot` defaults this to `"/var/lib/acme/acme-challenge"`, which does not sound at all like an nginx-specific directory, even though here it is.
It seems that because it _is_ an nginx specific dir (though I guess it should be renamed for clarity), it would be correct to `chown -R nginx` that one. But we should add at least a comment that you can't share `webroot` across users and must thus also not use nginx's `acmeRoot`; better yet, we would add an assertion that prevents that.

**Comment by edanaher** [comment]
FYI, @fpletz brought up redoing the ACME setup in #24731; my impression is that the current setup has kind of evolved in a couple different directions without anyone fully understanding how it's used in real life.  (Maybe that's unfair, but I know that describes my contribution ; ).

I'm working on some other projects now, but in the near future I may be interested in leading that.

**Comment by fpletz** [comment]
@nh2 Regarding your comment on nginx, this is actually a problem because the same acme-challanges directory is used for all vhosts. This creates a race condition when multiple acme service instances are running. This happens for instance on activating new configurations with more than one new vhost.

**Comment by edanaher** [comment]
@fpletz I don't understand how that's a race condition; my (possibly incorrect) understanding is that the acme-challenges directory is indeed used for all vhosts, but unless the challenges issued for multiple hosts happen to collide, they will happily write alongside each other (permissions allowing, but that's not racy, AFAICT).

Incidentally, it looks like we could theoretically resolve that whole issue by using the [try_files](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files) directive in nginx.conf to tell nginx to check multiple directories for challenges, and just add on a new one for each service.  I haven't tested this in any way, but it would make it possible to, say, have each challenge directory writable only by the service that needs it, and readable by nginx.  (I suppose that still allows for a theoretical DoS since the first directory in the list can block later reads if it knows what file to write, but it's certainly better than a shared-writable directory.)

**Comment by fpletz** [comment]
The root problem of the race condition I mentioned is that the acme-challenge directory could be owned by another user/group if these are changed in `security.acme.certs.*.user` while another simp_le instance wants to write a file into it. We're using this to make the certs and keys available for other TLS-enabled services and use the nginx vhost mechanism only to provide the verification for Let's Encrypt.

**Comment by edanaher** [comment]
Ah, I see.  The race condition is added in the PR when the directory is chown'd to the appropriate group.  So it sounds like my try_files fix to give each certificate its own challenge directory would actually fix this.

**Comment by fpletz** [comment]
Yup, that would fix it. But I'm wondering if it would be cleaner to just add a `/.well-known/acme-challenge` location to each http server block (port 80) with it's own root/webroot. There is only one service (a http server) needed to help simp_le fulfill the http-01 challenge. Thus IMHO unix permissions should be enough to model the permissions for the directory. It's basically just using or creating a group. In our case we would use the nginx group and set the directory mode to 710. We would need a new option to set the group for the challenges directory or maybe just use the already provided group if we assume that the http server user would also be in that group (i.e. because it also serves a https vhost).

Sidenote: Now I remember why we implemented it this way. We wrote the nginx acme integration before we had the automatic selfsigned cert creation, so we had to get the certs before restarting nginx. That's why we used the same acme-challenge directory and a default vhost so that challenge requests to new vhosts would hit it.
