### ISSUE TITLE
Nextcloud service: erroneous extraOptions parsing/conversion

### ISSUE THREAD

**Issue by borg1622** [NixOS/nixpkgs#252445]
### Describe the bug
The Nexcloud module allows to configure `services.nextcloud.extraOptions` which will be appended to Nextclouds `config.php`.
The conversion from `extraOptions` to `config.php` items is faulty in two cases:

1. Parameter name contains a dot `.`, 
for example `filelocking.enabled = true;`
this is converted to `'filelocking' => array ( 'enabled' => true, ),` 
2. Parameter value contains a list of strings. And these strings containing backslashes `\`. 
For example `"OC\Preview\MP3"` is converted to  `"OCPreviewMP3"`
Whereas for example `"OC\\Preview\\MP3"` is converted to  `"OC\\Preview\\MP3"`

The first issue can be circumvented by an unintuitive rewrite to `"filelocking.enabled" = true;`
The second issue cannot be circumvented. It results in stripped backslashes or erroneous escaped backslashes. 
Thus in both cases the parameter values cannot be applied to Nextcloud.

### Steps To Reproduce
NixOS configuration snippets (input)
```
services.nextcloud.extraOptions = {
      filelocking.enabled = true;
      enabledPreviewProviders = [
        "OC\Preview\MP3"
        "OC\Preview\TXT"
        "OC\Preview\Imaginary"
      ];
    };
```
then `nixos-rebuild switch` succeded but generates the following faulty `config.php`.
checked by `vi <path-to-nextcloud-base-dir>/config/config.php` OR by `nextcloud-occ config:list`
```
'filelocking' =>                                                                                   
   array (                                                                                            
     'enabled' => true,                                                                               
  ),
'enabledPreviewProviders' =>                                                                       
   array (                                                                                            
    0 => 'OCPreviewMP3',                                                                         
    1 => 'OCPreviewTXT',                                                                                                                                           
    2 => 'OCPreviewImaginary',                                                                   
  ),  
```

**Note 1:** If you try to escape `"OC\Preview\MP3"` by adding slashes `"OC\\Preview\\MP3"` it will end up with double slashes `"OC\\Preview\\MP3"` in the `config.php`
**Note 2:** If you try to use two single quotes `''` as string delimitier and keep the single slahes `\` in NixOS like `''OC\Preview\MP3''` it will end up with double slashes `"OC\\Preview\\MP3"` in the `config.php`, too.

### Expected behavior
The `config.php` should look like this according to the Nextcloud official documentation 
for the [paramter list (enabledPreviewProviders)](https://docs.nextcloud.com/server/27/admin_manual/installation/server_tuning.html#previews) and the [dotted parameter (filelocking)](https://docs.nextcloud.com/server/27/admin_manual/configuration_files/files_locking_transactional.html?highlight=filelocking#):
```
'filelocking.enabled' = true,
'enabledPreviewProviders' => [
    'OC\Preview\MP3',
    'OC\Preview\TXT',
    'OC\Preview\Imaginary',
],
```

### Additional context

- I guess the root cause for both issues are the JSON conversion of `extraOptions` in the [NixOS Nextcloud module](https://github.com/NixOS/nixpkgs/blob/2ab91c8d65c00fd22a441c69bbf1bc9b420d5ea1/nixos/modules/services/web-apps/nextcloud.nix#L893C1-L896C16)
But because I'm not fluent in `nix` I don't understand at which place the error is realized or how to solve the issue.
```
$CONFIG = array_replace_recursive($CONFIG, nix_decode_json_file(
              "${jsonFormat.generate "nextcloud-extraOptions.json" cfg.extraOptions}",
              "impossible: this should never happen (decoding generated extraOptions file %s failed)"
            ));
 ```
- the strings added to Nextclouds `config.php` are delimited by single quotes `'`. Since [PHP does not evaluate](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.single) special chars within  single quoted strings, the double backslashes `\\` are treated literally. 
- I've documented little more details on Discourse:
https://discourse.nixos.org/t/nextcloud-extraoptions-conversion-issues/32389
- Another user ran into the same issues a few months ago - still unresolved:
https://discourse.nixos.org/t/nextlcoud-with-redis-distributed-cashing-and-file-locking/25321/2

### Notify maintainers
@stuebinm you've introduced this config. Maybe you have a better idea what is wrong here :smile: 
@Ma27 @pennae @aanderse @DavHau any suggestions/ideas ? 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"aarch64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05.3056.ea5234e7073d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ma27** [comment]
> For example "OC\Preview\MP3" is converted to "OCPreviewMP3"

This is how Nix works:

```
nix-repl> "OC\App\FooBar"
"OCAppFooBar"
```

You'd have to patch the evaluator itself to change that.

> Whereas for example "OC\\Preview\\MP3" is converted to "OC\\Preview\\MP3"

Is this an actual problem? AFAICS it's working fine.

> The first issue can be circumvented by an unintuitive rewrite to "filelocking.enabled" = true;

First of all again, this is how Nix works. When writing nginx config you also specify `locations."/"` rather than `locations./` because `/` is the attribute name, but not a valid identifier. Same here.

In fact, converting `memcache.local` to `"memcache.local"` is something I'd consider a very bad idea and I'm opposed to it:

* it's IMHO pretty counter-intuitive to write an attribute-set when the keys get stringified when you're familiar with how the Nix syntax works and why it's not the same as in Nextcloud.
* There are two cases, e.g.
  ```nix
  {
    redis = {
      host = "foo"; port = 2342;
    };
  }
  ```

  which must be transformed to
  ```php
  [ 'redis' => ['host' => 'foo', 'port' => 2342]]
  ```

  whereas

  ```nix
  memcache = {
    local = "...";
  }
  ```
  which must be transformed to
  ```php
  ['memcache.local' => '...']
  ```

An implementation of that will have to decide on a case-by-case base when to rewrite nested attribute-sets into key-value associations with dotted keys and when it shouldn't.

This is not only error-prone and will increase the complexity of `services.nextcloud` even more, it'll also significantly slow down each Nextcloud update because you'll have to check for changes in config-options not only in Nextcloud itself, but also in each app, at least in the ones we've packaged here (if we don't it'll be horribly inconsistent).

**Comment by itc-ger** [comment]
I think we are talking past each other. :see_no_evil: 

The problem is that the resulting `config.php` expects PHP syntax and not Nix syntax.
But `extraConfig` treats the input as Nix syntax which leads to not intended PHP syntax. Thus Nextcloud cannot handle it.

> >   Whereas for example "OC\Preview\MP3" is converted to "OC\Preview\MP3"

> Is this an actual problem? AFAICS it's working fine.

No, it isn't. 
Regardless what you define in `services.nextcloud.extraConfig`, you won't get `OC\Preview\MP3` with single `\` in the Nextclouds `config.php`. Again, you will get either double `\\` or no backslashes at all.
`OC\Preview\MP3` is converted to `OCPreviewMP3`
and `OC\\Preview\\MP3` is converted to `OC\\Preview\\MP3`


>> The first issue can be circumvented by an unintuitive rewrite to "filelocking.enabled" = true;

> First of all again, this is how Nix works. When writing nginx config you also specify locations."/" rather than locations./ because / is the attribute name, but not a valid identifier. Same here.
> In fact, converting memcache.local to "memcache.local" is something I'd consider a very bad idea

We're talking about Nextclouds `config.php` interpreted by PHP. 
In this config file there are dotted object attribute names like `'memcache.local'` or `'filelocking.enabled'`. 
- **First:** Whereas Nix access attributes by `.`-syntax. PHP access object attributes by `->`-syntax. 
- **Second:** PHP treats all strings in single quotes `'string'` literally. That means dots inside the string are not evaluated. 

It try to clarify this example
| Nix extraOption expression | resulting `config.php` | accessed in PHP by |
|-|-|-|
| `'filelocking.enabled' = true;` | `'filelocking.enabled' => true, ` |  `$object->{'filelocking.enabled'} = true` |
| `filelocking.enabled = true;` | `'filelocking' => array (  'enabled' => true,  ),` |  `$object.filelocking['enabled'] = true` |

You see in PHP arrays and object attributes are not the same and **cannot** be used interchangeable.
PHP does **not** interpret it as nested objects like `$object->filelocking->enabled = true`. 

**Possible solution approach**
I think `services.nextcloud.extraConfig` should not be parsed as JSON, instead it could be treated (by the Nextcloud module) as `attribute set of string` like in `services.nextcloud.phpOptions`.

But again, I'm not fluent in Nix. 
At present I can only point out issue. Because by abilities to solve this issues are limited.

**Comment by itc-ger** [comment]
> An implementation of that will have to decide on a case-by-case base when to rewrite nested attribute-sets into key-value associations with dotted keys and when it shouldn't.

@Ma27 I got that. I think the dot paramter issue is only a minor one, not worth of big discussions.
Let's have a focus on the backslash issue which really hurts.

**Comment by kirelagin** [comment]
1. As you have already discovered, when specifying the extra config in Nix, you have to quote the entire key if it includes a dot:

    ```nix
    extraOptions = {
      "filelocking.enabled" = true;
    }
    ```

    This is not particularly obvious, but this is absolutely the intended behaviour. Maybe there is some room for documentation.

2. The NixOS module generates the JSON correctly and then the conversion from JSON to PHP is done using PHP built-in functions, so if there were any bugs, they would be in the PHP standard library and not here. There are no bugs though: the backslash in single-quoted string literals [_can_ and should be escaped](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.single), since it _does_ have a special meaning there.
