### ISSUE TITLE
Support for building sd-image with a FS other than Ext4

### ISSUE THREAD

**Issue by pyrotelekinetic** [NixOS/nixpkgs#252868]
### Describe the bug
This isn't really a bug, but I'm not sure what other label or template to use.

A bootable sd-image can be built using `nixpkgs/nixos/modules/installer/sd-card/sd-image-*.nix`. This builds an image using the Ext4 filesystem, a very sensible default.

I would like to build an image using the f2fs filesystem. I think wanting to use a different fs is probably a decently common usecase.

### Additional context
`sd-image.nix` calls `make-ext4-fs.nix`. Perhaps I could add a similar function for f2fs? Or even better, a generalized function to create a given fs.

### Notify maintainers

@mschwaig
@wucke13
@samueldr

### Metadata
`$ nix-info -m`:
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.49, NixOS, 23.11 (Tapir), 23.11.20230828.3efb0f6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
 
 *PS: this is my first issue, so please let me know if I should do anything differently in the future!

**Comment by samueldr** [comment]
Hi, and welcome! :wave: 

So first of all, your issue...

... well done! Everything explained as needed, understandable, no problem here.

By the way, in my opinion filing a new issue in case of doubt that any other definitely apply is not a problem. You're making it easier to close any other issue if it ends-up not being exactly the same.

* * *

Now, about the image building. This is a long-standing issue, which has had some discussions happen around it in different avenues, and the general consensus at this point in time is that adding any more is a bad idea due to how they create *de facto* public APIs that people rely on, even if they never were intended to be.

Now, don't let yourself be discouraged *for your own usage*. **You can** edit the repo, make yourself an f2fs image, and it should work even when it references an upstream Nixpkgs commit without your generator ***because the generation derivation is not used by the final system***. So here, thankfully, you can eat your cake and have it too. Add an f2fs builder in your fork, generate your image, and as long as it works, no one is the wiser about whether or not it was generated or hand-crafted.

See also #23052 for the earliest (that I  know of) overall issue about that.

See also #42242 for another discussion especially about f2fs, and a previous PR in #106031.

**Comment by pyrotelekinetic** [comment]
Thanks for your response. For now I've settled using ext4, but I still think locking the generator to ext4 isn't ideal.

I understand what you're saying about creating APIs that aren't meant to be trusted, however. Maybe filesystem part of the build could accept a different derivation to use? That would make it easier to generate an image with a different fs, while not making it feel like a "supported" feature.

**Comment by mschwaig** [comment]
In my opinion users of such functionality should be able to expect that nixpkgs does not break their stuff all the time just because someone is making a change in the same area of the code without considering their usage, no matter if they access the provided functionality by setting an attribute or by passing a derivation to a function.

I think it would be easier to work in something like this in a fork or in an independent project. It can still be used by the community that way.

For something like this to land in nixpkgs I guess it would probably not only need to add one specific feature but improve the quality of the code so that the result is easier to maintain then what we have now.

**Comment by pyrotelekinetic** [comment]
That seems reasonable. I'll close this issue then.

If I find a suitable project, or publish my own, I'll link it here.
