### ISSUE TITLE
Package request: mealie

### ISSUE THREAD

**Issue by anoadragon453** [NixOS/nixpkgs#254260]
**Project description**

Mealie is an open source, self-hostable recipe management app. It offers features such as meal planning, shared shopping lists, recipe storage and scraping from third-party websites, and more. 

**Metadata**

* homepage URL: https://nightly.mealie.io/
* source URL: https://github.com/mealie-recipes/mealie
* license: AGPLv3
* platforms: unix, linux, darwin

The installation instructions attempt to point you to using docker-compose. But they also publish a single Docker image with both the front end and backend, which may be easier to work from: https://nightly.mealie.io/documentation/getting-started/installation/single-container/

**Comment by mweinelt** [comment]
We tried packaging up mealie at some point, see https://github.com/fleaz/nixpkgs/commits/mealie. I think @fleaz is still using mealie, not sure if that setup lives on nixos though.

If you're not set on mealie, we do have https://github.com/TandoorRecipes/recipes in nixpkgs already.

**Comment by fleaz** [comment]
Yeah, current Mealie user here. But still just using the Docker container on my last non-Nixos server. 

They started a complete rewrite for v1.0 which is going on for a really long time now and the last releasae they made was nearly a year ago (Oct. '22). Also the old codebase was really "Docker focused" and was a pain in the butt to get running without docker due to e.g. hardcoded paths in the code. Not sure if they will do such shenanigans again for the rewrite but tbh I lost interest in the project due to their development practices and currently switching to Tandoor, which even has an importer for your Mealie backup so the migration if you are already a Mealie user, is literally one mouse click to upload a zip file.

**Comment by anoadragon453** [comment]
Thanks for the context!

**Comment by anoadragon453** [comment]
I ended up trying tandoor for a while, but was not satisfied with its UX. Mealie development on the other hand appears to not be dead, and is currently in the process of releasing a v1.0.0!

I managed to get their RC2 docker container running on my NixOS VPS without too much trouble. See my config here if you want to replicate it: https://github.com/anoadragon453/dotfiles/commit/3bf4f6f0cd2c14b26a9dc1a9420ce2102a6e6036#diff-e3ae1acc3c94ad463336aada02b70015c228252eb6edbde48872483e8efc1ac9. The most annoying bit was getting it to connect to my system's PostgreSQL instance, though mealie does support SQLite.

Note that there were a few bugs in mealie and nixpkgs 23.11 that needed to be worked around here. Each are commented in the linked file.

**Comment by litchipi** [comment]
I managed to get mealie working: https://github.com/litchipi/nixos-service-builder/tree/mealie

I never contributed to nixpkgs yet, so it may take a while before I can open a PR here (the frontend build feels like a dirty hack), but it works ! 
If anyone reading this knows how it could be improved and made mergeable, I'd really like to get some help on this !

**Comment by ambroisie** [comment]
@litchipi I can review the PR when you open it.

**Comment by litchipi** [comment]
PR got merged, mealie is now available at version 1.2.0 ! :smile:
