### ISSUE TITLE
Unable to insert kernel parameters with spaces in them

### ISSUE THREAD

**Issue by obj-obj** [NixOS/nixpkgs#254331]
There are a couple legitimate use-cases for this, one of which is the kernel parameter `acpi_osi="!Windows 2020"` to fix some issues with s2idle on the Framework laptop

Currently, if I try to add this kernel parameter, nix just gets angry at me:
![image](https://github.com/NixOS/nixpkgs/assets/57120300/eca872ce-d496-4f38-a36a-b500cfba4132)

**Comment by pwaller** [comment]
You didn't provide a configuration fragment so we can see what you tried, so I can only guess that you wrote:

```
boot.kernelParams = ["foo=foo bar"];
```

Instead of:

```
boot.kernelParams = ["foo=\"foo bar\""];
```

There is a hint of this in the error message, my read of it is "you quotes inside the string", and that's not what is shown where it says `in /etc/nixos/configuration.nix: "acpi_osi=!Windows 2020"`.

Please can I request a paste of the terminal output rather than a screenshot. A screenshot means it won't be searchable, and it's more awkward for someone wanting to copy-paste fragments of text from it.

**Comment by obj-obj** [comment]
Strange, I tried escaping the quotes before I posted this issue but it works now for some reason? I must have done something wrong the first time I tried
