### ISSUE TITLE
Missing compiler paths

### ISSUE THREAD

**Issue by traustitj** [NixOS/nixpkgs#25637]
## Issue description
When installing python modules inside a virtualenv, building fails

### Steps to reproduce
nix-env -i libffi (requirement)
virtualenv env
source env/bin/activate
pip install bcrypt

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
(unfortunately I am not near the box in question, I installed Nixos a week ago with the latest image). I can supply this information later if absolutely needed.

**Comment by lheckemann** [comment]
Libraries aren't discovered from the user profile. You should use nix-shell instead — in the ideal case, you won't need to use virtualenv or pip at all. You can get a shell with python and the bcrypt library using `nix-shell -p 'python[3].withPackages (ps: [ps.bcrypt])'`. Because this is such a common question, I'm writing an entry for it (a bit more detailed than this) [over here](https://github.com/nixos-users/wiki/wiki/FAQ), should be done soon!

**Comment by FRidh** [comment]
@traustitj while there's ways you can use virtualenv with nix, it is quite brittle. I advise you to avoid using virtualenv when you can and use `nix-shell` for it instead.

**Comment by lheckemann** [comment]
Can we close this? It seems to be a misunderstanding, which is covered by https://nixos.wiki/wiki/FAQ/Libraries

**Comment by peterhoeg** [comment]
libffi was additionally missing from bcrypt buildInputs as well - fixed by #63326.

**Comment by peterhoeg** [comment]
I think we can close this.
