### ISSUE TITLE
No icons in KDE applications running outside Plasma

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#25762]
## Description

KDE applications do not have any icons when running outside the Plasma 5 desktop environment. Qt applications in general do not appear with the correct theme.

## Technical details

* Nixpkgs version: e8880627e8

**Comment by ttuegel** [comment]
This is not a bug; this is how Qt 5 is supposed to work.

Outside of Plasma, one must manually set the environment variable `QT_QPA_PLATFORMTHEME` environment variable to select a platform theme. Setting `kde` will mimic the Plasma theme. Setting `qt5ct` will allow using the `qt5ct` package to configure the theme.

**Comment by olejorgenb** [comment]
Would be nice if that variable somehow got a sane default though. Okular for instance works ok without it (lots of icons missing, but not that big a deal actually). BUT - startup time is affected due to how icon lookup works: Without `QT_QPA_PLATFORMTHEME` set okular makes 400k+ stat calls looking for icons. With the variable set this is reduced to 9k and startup time is at least cut in half...

**Comment by qknight** [comment]
@ttuegel i've tried to set it with `qt5ct` but i see this error message:

```
nix-shell -p qt5ct
```

inside this shell:
```
qt5ct 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted
```

```
nixos-version 
18.03pre124015.f59a0f7f1a6 (Impala)
```
