### ISSUE TITLE
Update request: kapacitor 1.5.7 → 1.7.0

### ISSUE THREAD

**Issue by aaronjheng** [NixOS/nixpkgs#258037]
- Package name: kapacitor
- Latest released version: 1.7.0

- Current version on the unstable channel: 1.5.7
- Current version on the stable/release channel: 1.5.7

- [ ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@offline

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by MikaelFangel** [comment]
When you request for the update to 1.7.0 to you by any chance mean [1.7.0-rc2](https://github.com/influxdata/kapacitor/releases/tag/v1.7.0-rc2)? Because the lastest non-prerelease I see is [1.6.6](https://github.com/influxdata/kapacitor/releases/tag/v1.6.6) and I can also see that the package haven't been updated in three years so I think it is time (;

Notify maintainers: 
@offlinehacker

**Comment by MikaelFangel** [comment]
@totoroot when looking in the  maintainer list it shows that "offline" actually uses "offlinehacker" as their handle. 

I'm on my phone but here a screenshot showing it:
![image](https://github.com/NixOS/nixpkgs/assets/34864484/221aa665-a63c-4775-8717-cfcf8d76d71c)

**Comment by totoroot** [comment]
Done in #259152
