### ISSUE TITLE
How to run an XFCE desktop in vncserver on NixOS?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#25824]
I would like to run an xfce desktop on a NixOS machine for remote access via VNC. Is there a recommended way to do this?

So far I have installed tigervnc+xfdesktop+xfwm4 and written a `~/.vnc/xstartup` script that runs `xfdesktop &`. This does work but is very minimal: I have few desktop menu items, not all of them work, I have no panels, and I can't do things like recover windows that have been minimized.

I have tried installing more packages with `nix-env -iA nixos.xfce` but this is failing for me, on both stable and unstable channels, with confusing conflicts like https://gist.github.com/lukego/5bcea80e4ba371114f8510782bd4f659.

So I would like to at least extend my current setup with a more complete xfce environment. Better yet would be to have a nix expression to describe the whole environment instead of manually installing packages with `nix-env` and writing `~/.vnc/xstartup` by hand.

Any hot tips? :-)

**Comment by lheckemann** [comment]
You probably want to use `startxfce4` or `xfce4-session` instead of `xfdesktop`, not sure about this one though.

For installing the rest of the software, you may want to take inspiration from [the list of software installed by the xfce module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/xfce.nix#L83-L121).

**Comment by mmahut** [comment]
Are there any updates on this issue, please
