### ISSUE TITLE
unable to run Sway: "failed to load driver"

### ISSUE THREAD

**Issue by timjrd** [NixOS/nixpkgs#25871]
## Issue description

Hi :) I don't know if I'm doing something wrong or if it's a bug but I can't run the Sway wayland compositor from my tty. I'm on a fresh nixos install, without X. Here is the output of `$ sway --debug`:

```
05/17/17 23:12:03 - [main.c:46] [wlc] logind: session control granted
05/17/17 23:12:03 - [main.c:46] [wlc] Running on vt 1 (fd 0)
05/17/17 23:12:03 - [main.c:44] [wlc] Failed to open X11 display
gbm: failed to open any driver (search paths /run/opengl-driver/lib/dri)
gbm: Last dlopen error: /run/opengl-driver/lib/dri/i965_dri.so: cannot open shared object file: No such file or directory
failed to load driver: i965
gbm: failed to open any driver (search paths /run/opengl-driver/lib/dri)
gbm: Last dlopen error: /run/opengl-driver/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory
failed to load driver: kms_swrast
gbm: failed to open any driver (search paths /run/opengl-driver/lib/dri)
gbm: Last dlopen error: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory
failed to load swrast driver
05/17/17 23:12:03 - [main.c:44] [wlc] gbm_create_device failed
05/17/17 23:12:03 - [main.c:46] [wlc] Closed drm
05/17/17 23:12:03 - [main.c:44] [wlc] Could not initialize any backend
05/17/17 23:12:03 - [main.c:42] [wlc] Failed to init compositor
05/17/17 23:12:03 - [main.c:46] [wlc] Parent exit (1945)
05/17/17 23:12:03 - [main.c:46] [wlc] Restoring vt 1 (0x4) (fd 0)
```

### Steps to reproduce

```
$ nix-env -i sway
```
reboot, login in a tty, then:
```
$ sway --debug
```

## Technical details

* System: 17.03.1152.22da5d0246 (Gorilla)
* Nix version: nix-env (Nix) 1.11.8
* Nixpkgs version: "17.03.1152.22da5d0246"
* Sandboxing enabled: build-use-sandbox = false

**Comment by lheckemann** [comment]
I can't reproduce this one. Does /run/opengl-driver exist at all on your system? Do you have the X server module enabled? If not, I suspect that the DRI drivers won't be installed because `hardware.opengl.enable` isn't set to true by the xserver module — try setting `hardware.opengl.enable = true;` in your config, rebuilding the system, and then running sway again. Potentially this option should not be internal, or there should be a separate option for enabling wayland support without X. In any case, I think NixOS's wayland support isn't very fleshed out yet so you're probably in uncharted territory here.

**Comment by timjrd** [comment]
Thank you :) setting `hardware.opengl.enable = true;` did the trick.
(internal means it doesn't appear here: http://nixos.org/nixos/options.html ?)

**Comment by lheckemann** [comment]
Yes, it isn't exposed in the user documentation as a result of being marked as internal. I'm not sure if that has any other consequences.
