### ISSUE TITLE
Update request: furnace 0.6pre18 → 0.6

### ISSUE THREAD

**Issue by FavoritoHJS** [NixOS/nixpkgs#259093]
- Package name: furnace
- Latest released version: 0.6

- Current version on the unstable channel: 0.6pre18
- Current version on the stable/release channel: 0.6pre7

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

For some reason this update did not add an automatic pull request...

Now that the update spam is over, I wonder if it might be time to update the release channel as well.

**Notify maintainers**

@OPNA2608 

PS: I am once again asking y'all to prepare an escape plan from github - what with repeated false bans, including _some of our members_, that are so strong they are more-or-less **removed from history**, and unnerving serves of direction form host to social to ai... can't trust this site.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by cafkafk** [comment]
> what with repeated false bans, including _some of our members_, that are so strong they are more-or-less **removed from history**

Sounds interesting, link?

**Comment by OPNA2608** [comment]
On-topic stuff:

> For some reason this update did not add an automatic pull request...

r-ryantm update PRs don't happen instantly, I'm not sure if the exact timing is documented anywhere.

> Now that the update spam is over, I wonder if it might be time to update the release channel as well.

Still disagree with the idea. Our 23.11 release is [starting to be planned](https://github.com/NixOS/nixpkgs/issues/258640), so that one will likely end up with a proper 0.6 release. If upstream doesn't do the same year-long, feature-packed pre-release hell again then I'd be fine with backporting patch releases with fixes onto 23.11.

---

Off-topic stuff:

> PS: I am once again asking y'all to prepare an escape plan from github [...]

Read https://github.com/NixOS/nixpkgs/issues/41448 for past stances & discussions about this, and where future discussions about this are supposed to be done.

> > what with repeated false bans, including _some of our members_, that are so strong they are more-or-less **removed from history**
>
> Sounds interesting, link?

Only similar situation I can think of volth, I'm not sure that can be considered a false ban though. Unfortunate nonetheless though.

**Comment by FavoritoHJS** [comment]
> > what with repeated false bans, including _some of our members_, that are so strong they are more-or-less **removed from history**
> 
> Sounds interesting, link?

@cafkafk iirc joepie91 got this sledgehammer treatment. Here's a link to someone else who got dragged through hell: https://nrk.neocities.org/articles/miserable-state-of-github-moderation

<hr/>

> [...] If upstream doesn't do the same year-long, feature-packed pre-release hell again then I'd be fine with backporting patch releases with fixes onto 23.11.

@OPNA2608 don't worry, from what i hear 0.7 is going to be mostly minor patches and work for hardware export, so i doubt tildearrow will machine-gun prereleases in a while.
