### ISSUE TITLE
Override package version help

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#25912]
I'm using the standard nixos channel, but sometimes the packages within there are outdated.
I'm trying to install bitcoin 0.14.1, the version currently in stable is 0.12.0.
So I am trying to override the version like so:
```
(bitcoin.overrideDerivation (oldAttrs: {
      name = "bitcoin-0.14.1";
      core_version = "0.14.1";
      version = "0.14.1";
    }))
```
I'm using the same variable names that is within the bitcoin.nix file located at [pkgs/applications/altcoins/bitcoin.nix](https://github.com/NixOS/nixpkgs/blob/release-16.09/pkgs/applications/altcoins/bitcoin.nix)

But it appears to make no difference ( other than it doing a bare build of bitcoin which takes a while ).... but the version it installs is still 0.12.0.

What am I doing wrong here?

**Comment by FRidh** [comment]
@ob7 use `overrideAttrs` instead of `overrideDerivation`. The latter overrides the call to `derivation` whereas the former overrides the call to `stdenv.mkDerivation`. Even so, when you override the call you also have to pass in a `src` again or it will still use the old `src` argument.

**Comment by ob7** [comment]
I figured I wouldn't need to pass the src in again since it uses the core_version variable to determine the source...
`
src = fetchurl {
    urls = [ "https://bitcoin.org/bin/bitcoin-core-${core_version}/bitcoin-${version}.tar.gz"
             "mirror://sourceforge/bitcoin/Bitcoin/bitcoin-${core_version}/bitcoin-${version}.tar.gz"
];
`

**Comment by lheckemann** [comment]
Because the version number is only used to determine where to obtain the files, but not the actual contents of the files. Given that the expected hash is still the one given in the fetchurl call in bitcoin.nix, it finds that the expected files have already been downloaded and will not download them again. If you garbage-collect and then try to build this overridden version it will likely fail, because the downloaded files will not match the hash given in the derivation. So you'll still want to override src.
