### ISSUE TITLE
Python says it cannot find SetupTools

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#25984]
I've installed Python3, python 3 setuptools, and pip.

Whenever I run a pip install or python ./setup I get a complaint that it cannot find module setuptools.

When I pip install setuptools it says its already installed and points to the nix path ( which is probably created by installing setuptools via python35Packages.setuptools.

But my error remains.  What is wrong with the default python setup to where it cannot find the modules to import that are being installed by the nix expression?

When I check for 'echo $PYTHONPATH' nothing is returned.

**Comment by FRidh** [comment]
> I've installed Python3, python 3 setuptools, and pip.

How did you install these? Which version of Nixpkgs?

**Comment by ob7** [comment]
Within configuration.nix

environment.systemPackages = with pkgs; [
  python3Full
  python35Packages.pip
  python35Packages.setuptools
]

nixos-rebuild switch

Stable branch 17.03

Then I try to install this package:  https://github.com/flyingrub/scdl
via the command line per github instructions.  Running pip install or python3 ./setup both through same error message:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

Doesn't matter if I'm sudo or not error is the same.

**Comment by FRidh** [comment]
Please check the manual on how to use Python on Nix.
https://nixos.org/nixpkgs/manual/#using-python

**Comment by bjornfor** [comment]
@FRidh: Do you think it would be worth a try to have Python pick up libraries from $NIX_PROFILES? I think the current Python behaviour is highly un-intuitive. When something _is_ installable, either with systemPackages or nix-env, it's weird that it doesn't work. It trips people up.

I think the only people this could possible hurt is advanced users who mix wildly different python modules in their profiles _and_ forget to set/unset $NIX_PROFILES or create a special wrapper that purges impure environment variables for these special development environments. For ordinary use this should be fine. But we will never know unless we try.

**Comment by FRidh** [comment]
@bjornfor I'm up for ideas and proposals on how to make it better usable, like perhaps using $NIX_PROFILES. I don't know how that should be done though, and I am not really that interested in it either because in my opinion `python.withPackages` works fine.

**Comment by bjornfor** [comment]
@FRidh: In technical terms, I was thinking just iterating over $NIX_PROFILES in sitecustomize.py and appending $profile/lib/python2.7/site-packages to sys.path (as appropriate for each interpreter).

**Comment by FRidh** [comment]
I really think that's asking for trouble. If you have one version of the interpreter along with packages installed in systemPackages, and then another, ABI-incompatible one, installed with nix-env, then you're going to get some funny errors. This is quite a realistic scenario since what you install with nix-env doesn't have to be of the same channel/version as what you install globally.

**Comment by bjornfor** [comment]
You only get funny errors iff the abi compatible version loads the other version's modules. And that only happens for plugins, not for hardcoded dependencies. (Paths from $NIX_PROFILES must be appended, not prefixed, to python search path.) So for normal apps you can have as different abi as you like, AFAICS.

I'm not arguing that there won't ever be cases where you get a crash, but I think the convenience of loading modules from $NIX_PROFILES may outweigh the occasional problems.

Anyway, a simple compromise is to make this opt-in. I.e. reading $NIX_PROFILES only happens if $NIX_PYTHON_USE_PROFILES is set, or something like that. Then people like me can set that one flag and have working impure envs.
