### ISSUE TITLE
haskell: tls package override is broken on aarch64

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#260013]
The `tls` package currently has this override in `pkgs/development/haskell-modules/configuration-ghc-9.6.x.nix`

```
  tls = appendConfigureFlags
    (lib.optionals pkgs.stdenv.hostPlatform.isAarch64 [ "--ghc-option=-fllvm" ])
    super.tls;
```

However this doesn't work because `ghc` is not wrapped with a suitable llvm installation so when you attempt to build the package you get errors along the lines of:

```
Building library for tls-1.6.0..

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)
```

cc @sternenseemann

**Comment by sternenseemann** [comment]
Yeah, this known by me and I have drafted a clean fix that I’ll have to push in the next days. (I was a bit lazy about this, since it was broken already, sorry.)On 9. Oct 2023, at 18:02, Matthew Pickering ***@***.***> wrote:﻿
The tls package currently has this override in pkgs/development/haskell-modules/configuration-ghc-9.6.x.nix
  tls = appendConfigureFlags
    (lib.optionals pkgs.stdenv.hostPlatform.isAarch64 [ "--ghc-option=-fllvm" ])
    super.tls;

However this doesn't work because ghc is not wrapped with a suitable llvm installation so when you attempt to build the package you get errors along the lines of:
Building library for tls-1.6.0..

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [11 and 16)

cc @sternenseemann

**Comment by sternenseemann** [comment]
#260079
