### ISSUE TITLE
Documentation: information missing on setting up NixOS behind a proxy server

### ISSUE THREAD

**Issue by oz42** [NixOS/nixpkgs#26051]
## Issue description
I have searched the manual for information about using a proxy server. I googled around and found the option networking.proxy.default but it has no effect.

Please add a description in the manual how to configure NixOS proxy setting.

## Technical details

* System: 17.03.1198
* Nix version: 1.11.8

**Comment by regnat** [comment]
There was some information on the defunct wiki. You can find it [here](http://web.archive.org/web/20160829175539/https://nixos.org/wiki/Proxies).

Maybe I'm wrong, but your problem is probably that you need to rebuild your system from behind the proxy, which you can't because it would require setting the proxy, which is impossible because the `networking.proxy.default` only has effect after the system is rebuilt.
If this is the case, a workaround is available on the page I linked − but moving it into the manual or at any other place would be much welcome as the wiki is now down.

**Comment by mmahut** [comment]
Are there any updates on this issue, please
