### ISSUE TITLE
Build failure: haskellPackages.sdl2-gfx

### ISSUE THREAD

**Issue by locallycompact** [NixOS/nixpkgs#260863]
Hi. I'm not sure when this began failing to build. This was working at some point.

https://hydra.nixos.org/log/mzkflkxx1ps6nimbwd483k52b87lqch3-sdl2-gfx-0.3.0.0.drv

**Comment by locallycompact** [comment]
Bisecting yields this commit a83158c7b9c248032de5be0e69a38c5c44f00801

**Comment by sternenseemann** [comment]
Using

```
nix-build -E 'with import ./. {}; with haskell.lib.compose; overrideCabal { __propagatePkgConfigDepends = true; configureFlags = [ "-v3" ]; } haskellPackages.sdl2-gfx'
```

the issue reveals itself: Cabal attempts a linker test using the found libraries via `pkg-config` which includes an `-lSDL2` directive (thus the uppercase SDL2 in the error message). Due to propagation, the argument list is too long and execve will fail somewhere. Consequently, we'll have to employ similar workarounds as for the `gi` packages as shown in #265678.
