### ISSUE TITLE
`hostname --fqdn` broken with nsncd

### ISSUE THREAD

**Issue by Majiir** [NixOS/nixpkgs#261269]
### Describe the bug

`hostname --fqdn` only returns the hostname, even when both `networking.hostName` and `networking.domain` are set.

### Steps To Reproduce
1. Configure `networking.hostName` and `networking.domain`.
2. Run `hostname --fqdn`.

### Expected behavior

`hostname --fqdn` should return the FQDN defined by `networking.hostName` and `networking.domain`.

### Additional context

The breakage happens when `nsncd` is used, which is now the default in NixOS after https://github.com/NixOS/nixpkgs/pull/214153. Stopping `nsncd.service` causes `hostname --fqdn` to return the correct value.

`nixosTests.hostname.explicitDomain` reproduces the issue. It broke at fbfe2907af640ba3fb3528ab5e75d9dcd150a0e0, which is when `nsncd` became enabled by default. It's still broken on `master` which is b137e2f8301a29e6fe4369c5b713ec6112e394a9 at time of writing.

Possibly related issues:

- https://github.com/NixOS/nixpkgs/issues/218813
- https://github.com/NixOS/nixpkgs/issues/196934
- https://github.com/NixOS/nixpkgs/issues/132646

### Notify maintainers

@flokli @lukegb @NickCao @rnhmjoj @NinjaTrappeur @mweinelt 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.56, NixOS, 23.05 (Stoat), 23.05.20231011.bd1cde4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `""`
 - channels(majiir): `""`
 - nixpkgs: `/nix/store/mbz4hixfgxq5b6vc0k3pp2iglcd4c353-source`
```

**Comment by lukegb** [comment]
This seems to happen because the resolution flow (when nscd is running) looks like:

1. `hostname` calls `gethostname`, which uses the nodename (`uname -n`), which is the short hostname
1. `hostname` then calls `gethostbyname`, which invokes the nss machinery
2. `nscd` gets the request and processes the request according to the NSS rules; on my NixOS system this is `mymachines resolve files myhostname dns`
3. mymachines (from systemd) doesn't match
4. resolve (from systemd) does match, and returns a synthesized record; systemd internally determines the hostname for this using _only_ the nodename, so unless the nodename is already the FQDN then we fail here, and it does this before checking /etc/hosts.

I wonder if we can fix this by patching out the support in systemd-resolved for looking up the nodename, which will make it fall back to the result from /etc/hosts instead; on NixOS we can (probably) always assume that /etc/hosts will actually have the correct system hostname in it.

**Comment by flokli** [comment]
No, this is most likely https://github.com/nix-community/nsncd/pull/9.

We wanted to polish that PR in the next days, and once merged, bump our nixpkgs pin (and resurrect the upstreaming attempts).

If you want, can you check if using nsncd from this PR fixes the problem for you?

**Comment by lukegb** [comment]
Ah, actually, I think I'm just talking out of my ass. systemd-resolved seems to be able to cope with this properly when I query it over DNS, so it probably isn't to blame.

**Comment by Majiir** [comment]
> No, this is most likely [nix-community/nsncd#9](https://github.com/nix-community/nsncd/pull/9).
> If you want, can you check if using nsncd from this PR fixes the problem for you?

`nsncd` tests fail at that PR. Setting `doCheck = false` gets a successful build, which then passes the `hostname --fqdn` test in `nixosTests.hostname.explicitDomain`, but it fails on the `dnsdomainname` test.
