### ISSUE TITLE
Switching to nixpkgs-unstable breaks keyboard special function shortcut for rfkill

### ISSUE THREAD

**Issue by NovaViper** [NixOS/nixpkgs#261880]
### Describe the bug
Hey I noticed when I switch from NixOS 23.05 to the latest unstable nixpkgs version (currently ca012a0), the special function shortcut for rfkill (The XF86RFKill keycode, which is F8 on my Lenovo Yoga 7i 16IRL8) is no longer functions. It functions when I'm on the stable NixOS version 23.05 it works fine, but switching over to the unstable version is what breaks it.

### Steps To Reproduce
1. Install NixOS 23.05 with KDE Plasma
2. Switch the channels from `nixos-23.05` to `nixos-unstable` and update the system to use the packages from the unstable channels
4. Press the key that sends the XF86RFKill keycode (in my case, it's F8)
5. The bug occurs

### Expected behavior
Pressing the key that sends the XF86RFKill keycode should make rfkill run and toggle the wifi and bluetooth card.

### Screenshots
N/A

### Additional context
My system is running KDE Plasma 5.27.8, but this could also be present on other desktop environments

### Notify maintainers
KDE Plasma: @ttuegel @nyanloutre
util-linux: ?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[novaviper@yoganova:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.5.7, NixOS, 23.11 (Tapir), 23.11.20231016.ca012a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.0`
 - nixpkgs: `/nix/store/4smdp3v5a9bcg1hpdhl2hs70rq385ykq-source`
```

**Comment by acid-bong** [comment]
Same behaviour: Asus X541UAK, dwm desktop, NixOS 23.11 stable

**Comment by ibbem** [comment]
I experienced the same issue after upgrading from NixOS 23.05 1216a5ba22a93a4a3a3bfdb4bff0f4727c576fcc to NixOS 23.11 d02ffbbe834b5599fc5f134e644e49397eb07188 (although I use Xmonad instead of KDE) and I was able to find the root cause of this issue:

The [rfkill driver of the Linux kernel](https://www.kernel.org/doc/html/latest/driver-api/rfkill.html) provides the rfkill-input module which handles the `XF86XK_RFKill` key. However, the Kconfig option `RFKILL_INPUT` can be used to disable the rfkill-input module and the default value of this option depends on the Kconfig option `EXPERT` which was changed in 3b07356d2d55c5eacc7a11eb08c3a8de97884b2f. Hence, `RFKILL_INPUT` is currently disabled and this issue surfaces when using a desktop environment which does not handle the `XF86XK_RFKill` key.

@RaitoBezarius This change seems unintentional. As this is a regression, `RFKILL_INPUT` should probably be set to `yes` again, right?

@NovaViper It could also be the case that the keyboard layout misinterprets this key. Did you verify (e.g., using `xev`) that the key code `XF86XK_RFKill` is actually sent? If yes, then it's probably a good idea to report this problem to the KDE developers because the kernel documentation states that the rfkill-input module is deprecated.

**Comment by NovaViper** [comment]
> I experienced the same issue after upgrading from NixOS 23.05 [1216a5b](https://github.com/NixOS/nixpkgs/commit/1216a5ba22a93a4a3a3bfdb4bff0f4727c576fcc) to NixOS 23.11 [d02ffbb](https://github.com/NixOS/nixpkgs/commit/d02ffbbe834b5599fc5f134e644e49397eb07188) (although I use Xmonad instead of KDE) and I was able to find the root cause of this issue:
> 
> The [rfkill driver of the Linux kernel](https://www.kernel.org/doc/html/latest/driver-api/rfkill.html) provides the rfkill-input module which handles the `XF86XK_RFKill` key. However, the Kconfig option `RFKILL_INPUT` can be used to disable the rfkill-input module and the default value of this option depends on the Kconfig option `EXPERT` which was changed in [3b07356](https://github.com/NixOS/nixpkgs/commit/3b07356d2d55c5eacc7a11eb08c3a8de97884b2f). Hence, `RFKILL_INPUT` is currently disabled and this issue surfaces when using a desktop environment which does not handle the `XF86XK_RFKill` key.
> 
> @RaitoBezarius This change seems unintentional. As this is a regression, `RFKILL_INPUT` should probably be set to `yes` again, right?
> 
> @NovaViper It could also be the case that the keyboard layout misinterprets this key. Did you verify (e.g., using `xev`) that the key code `XF86XK_RFKill` is actually sent? If yes, then it's probably a good idea to report this problem to the KDE developers because the kernel documentation states that the rfkill-input module is deprecated.

Hey @ibbem, the wi-fi toggle button on my laptop  is sending the following key codes, as shown below from `xev`
```
KeyPress event, serial 39, synthetic NO, window 0x2e00001,
    root 0x4a1, subw 0x0, time 66653062, (151,0), root:(1021,498),
    state 0x10, keycode 255 (keysym 0x1008ffb5, XF86RFKill), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 39, synthetic NO, window 0x2e00001,
    root 0x4a1, subw 0x0, time 66653062, (151,0), root:(1021,498),
    state 0x10, keycode 255 (keysym 0x1008ffb5, XF86RFKill), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by RaitoBezarius** [comment]
@ibbem Yes, LGTM, please send such a PR if it makes sense.

**Comment by ibbem** [comment]
Should #279368 be backported to nixos-23.11?
Otherwise this issue can be closed because it's resolved on `master`.
