### ISSUE TITLE
`ino` can't find boards.txt

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixpkgs#26274]
## Issue description
`ino` (the command line arduino build tool) needs (among other things, like avr-gcc) a boards.txt file telling it what parameters to use for each model of arduino. That file is present in arduino-core, but in the wrong place.

### Steps to reproduce
Install `ino` (which automatically installs `arduino-core` as well), then try to use it:
```
$ nix-shell -p ino
$ ino list-models                                                                                       
Searching for Board description file (boards.txt) ... FAILED
Board description file (boards.txt) not found. Searched in following places: 
  - /nix/store/8w6nhga46z9b23f5k90blmjzcj7hv3dv-arduino-core-1.6.12/share/arduino/hardware/arduino
  - /usr/share/arduino/hardware/arduino
```

It looks like boards.txt is actually in `/nix/store/8w6nhga46z9b23f5k90blmjzcj7hv3dv-arduino-core-1.6.12/share/arduino/hardware/arduino/avr/`.

## Technical details

* System: (NixOS: 17.09pre107928.65477dcd34 (Hummingbird))
* Nix version: (nix-env (Nix) 1.11.9)
* Nixpkgs version: ("17.09pre108200.13f2f8673b")
* Sandboxing enabled: (build-use-sandbox = true)

**Comment by gazally** [comment]
Arduino 1.8 is in master as of yesterday, see [#26294](https://github.com/NixOS/nixpkgs/pull/26294). I followed the [link](https://github.com/amperka/ino) to the `ino` sources and there haven't been any updates there for three years, which is why it doesn't work with recent versions of Arduino. `ino` should probably be removed from Nixpkgs. If you're wanting to build for your Arduino from the command line, try this instead: [There is no "Arduino" language](http://hackaday.com/2015/07/28/embed-with-elliot-there-is-no-arduino-language/).

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by haslersn** [comment]
This issue ist still present.

**Comment by haslersn** [comment]
I didn't hear anything about this being fixed, so the issue is probably still present.

**Comment by emilytrau** [comment]
```
error: ino has been removed from nixpkgs, the project is stuck on python2 and upstream has archived the project
```
