### ISSUE TITLE
Package request: niri

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#262804]
**Project description**

 A scrollable-tiling Wayland compositor. 

**Metadata**

* homepage URL: https://github.com/YaLTeR/niri
* source URL: https://github.com/YaLTeR/niri
* license: GPL-3.0
* platforms: linux, ?

**Comment by billksun** [comment]
I just found out about Niri today, and this looks like just what I am looking for!

**Comment by dywedir** [comment]
Added in #288861

**Comment by IogaMaster** [comment]
I will look at creating a module for the package as well. I've never made one before, so let's see how it goes :p

**Comment by KiaraGrouwstra** [comment]
@IogaMaster you might wanna check out the `niri-flake` repo linked above for some inspiration on doing a niri module.
(@sodiboo: looks like you hadn't specified a license there yet. :see_no_evil:)

**Comment by sodiboo** [comment]
> @IogaMaster you might wanna check out the `niri-flake` repo linked above for some inspiration on doing a niri module. (@sodiboo: looks like you hadn't specified a license there yet. 🙈)

in the works. (i've asked in matrix channel, just to be sure i don't break niri's GPL when picking one)

i'll add that some inspiration for my own module comes from the Hyprland modules (nixos and home-manager alike), and those (as well as other established compositors) might be more relevant to nixpkgs rules? dunno really. my module is also missing some things, that i haven't fixed yet:

- vscode keyring? is this part of the compositor module even? currently, i just use the "weaker encryption" option because i didn't wanna deal with it anymore
- polkit? what do
- [unidentified issues]
