### ISSUE TITLE
Reorganizing Wayland specific NixOS modules

### ISSUE THREAD

**Issue by elijahimmer** [NixOS/nixpkgs#267134]
The NixOS Modules for Wayland are very unorganized, and have no clear structure for where to place them.

Currently, the `nixos/modules/services/X11` folder has taken more of the place for all desktop environments, such as this PR for cosmic (#267099 ) which has no X11 support.

I can think of two main ways of organizing this. Either creating a separate folder in services for all desktops (like `nixos/modules/services/graphical`, or to separate technologies better move all Wayland desktops to a `nixos/modules/services/Wayland/desktops` or similar folder.

I personally think we should go for the second option, and keep the `nixos/modules/services/X11` for X11 specific tools, window managers, desktops, etc. and create another folder `nixos/modules/services/Wayland` for Wayland specific things. This should again be followed when eventually some technology will come and replace Wayland.

If we go the second route, more discussion needs to take place on where to place desktops with X11 and Wayland support.

With the Linux desktop world moving to Wayland, it will be important to show where these modules should be placed and just be able to clean up the Wayland specific services, as they have been placed fairly loosely.

(I saw no guidelines on where to propose something like this, so I hope that this is where it should be, if not please tell me and I can do whatever is needed to this idea looked it)

**Comment by FliegendeWurst** [comment]
> I personally think we should go for the second option, and keep the nixos/modules/services/X11 for X11 specific tools, window managers, desktops, etc. and create another folder nixos/modules/services/Wayland for Wayland specific things. This should again be followed when eventually some technology will come and replace Wayland.

I also like this idea. Whilst we're at it I would also appreciate a "6.topic: wayland" issue label for Wayland-specific problems.

> (I saw no guidelines on where to propose something like this, so I hope that this is where it should be, if not please tell me and I can do whatever is needed to this idea looked it)

I think the Discourse might be better: https://discourse.nixos.org/

Btw, the topic has also been previously discussed in: #139984, #102542, #94799, #53394

**Comment by elijahimmer** [comment]
Yea, I didn't see those other issues, I think I am just going to learn more and just implement my second idea (or something like that) and move stuff some stuff over, from there maybe this issue will get somewhere, as it is starting to get really important and nobody (as far as I can tell) is working on it.

**Comment by Nyabinary** [comment]
In general, a restructure of the modules seems in order for housekeeping at least, for example, the `by-name` structure done for Nix packages was great, could there be something done similar for modules?

**Comment by michaelBelsanti** [comment]
It would be great to have this merged before the Cosmic module, so we can avoid having to move that in the future

**Comment by RuRo** [comment]
This issue is marked with "9.needs: community feedback", but it's not really clear, what to discuss here. It's pretty clear that a major refactor for configuration of graphical environments in NixOS is long overdue, and I think that everyone is on board, that **something** has to be done.

So this means, that what we should be discussing next is all the nitty-gritty details of how exactly do we want to do this refactor. Separate `services.xserver` and `services.wayland`? A common `services.graphical`? How to handle graphical environments that support both `xserver` and `wayland`? Should we keep the `desktopManager` vs `windowManager` separation? We should also probably get input from codeowners/maintainers of each affected subsystem and graphical environment.

I think that it's practically impossible to discuss the specifics in individual issues in nixpkgs. Also, there is a lot of noise in nixpkgs, so discussions here have much lower exposure to members of the community. Maybe, this issue warrants an [RFC](https://github.com/NixOS/rfcs)?

**Comment by elijahimmer** [comment]
I was originally looking for ideas on how to refactor, I do think it should be a RFC with how large it would be, but I just haven't had the time to do that. I was actually going to work on it next week once I finish finals and I'll probably make a RFC because it would be a major change to the module structure internally, and it's API, so it would likely be best to do that. I'll look at RFCs a little more to make sure it fits the criteria and all that, and how I would do that.

I will close this once I, or someone else, starts a RFC or something else like that, unless someone says to close it sooner than that.

**Comment by michaelBelsanti** [comment]
#292141 was merged and plasma 6 options are now located at `services.desktopManager.plasma6` on unstable. Other desktops should be able to follow
