### ISSUE TITLE
Package request: 'When'

### ISSUE THREAD

**Issue by Vonixxx** [NixOS/nixpkgs#267474]
**Project description**

When is an extremely simple personal calendar program, aimed at the Unix geek who wants something minimalistic. It can keep track of things you need to do on particular dates. There are a lot of calendar and "personal information manager" programs out there, so what reasons are there to use When?

- It's a very short and simple program, so you can easily tinker with it yourself.
- It doesn't depend on any libraries, so it's easy to install. You should be able to install it on any system where Perl is available, even if you don't have privileges for installing libraries.
- Its file format is a simple text file, which you can edit in your favorite editor.

**Metadata**

* homepage URL: https://www.lightandmatter.com/when/when.html
* source URL: https://bitbucket.org/ben-crowell/when/src/master/
* license: GPL
* platforms: Linux

I have already made a .nix file in order to build this package on NixOS, however I am posting it here to make sure there are no issues with it since it is my first time writing a .nix file for this purpose.

```
{ lib ? pkgs.lib, pkgs ? import <nixpkgs> {} }:

with pkgs; stdenv.mkDerivation rec {
 pname   = "when";
 version = "1.1.46";

 src = pkgs.fetchgit {
   rev    = "a57ccbd"; 
   url    = "https://bitbucket.org/ben-crowell/when.git";
   sha256 = "uNIU4tsoJBBPj+2rYVvXl+D5f/GB80ox6s2MgxjuJa4=";
 };

 buildInputs = [ pkgs.perl ];
 makeFlags   = [ "PREFIX=$(out)" ];
 installPhase = "
   mkdir -p $out/bin
   mkdir -p $out/share/man/man1
   install -m 755 when $out/bin/
   pod2man $out/bin/when $out/share/man/man1/when.1
 ";

 meta = with lib; {
   license     = licenses.gpl3;
   platforms   = platforms.linux;
   maintainers = with maintainers; [ Benjamin Crowell ];
   homepage    = "https://www.lightandmatter.com/when/when.html";
   description = "When is an extremely simple personal calendar program";
 };
}
```

**Comment by TomaSajt** [comment]
Hey, I reviewed your derivation, and made some changes:

```nix
{ lib
, stdenv
, perl
, fetchFromBitbucket
}:

stdenv.mkDerivation {
  pname = "when";
  version = "1.1.46";

  src = fetchFromBitbucket {
    owner = "ben-crowell";
    repo = "when";
    rev = "a57ccbd";
    hash = "sha256-uNIU4tsoJBBPj+2rYVvXl+D5f/GB80ox6s2MgxjuJa4=";
  };

  buildInputs = [ perl ];

  makeFlags = [ "PREFIX=$(out)" ];

  installPhase = ''
    mkdir -p $out/bin $out/share/man/man1
    install -m 755 when $out/bin/
    pod2man $out/bin/when $out/share/man/man1/when.1
  '';

  meta = with lib; {
    description = "An extremely simple personal calendar program";
    homepage = "https://www.lightandmatter.com/when/when.html";
    license = licenses.gpl2Only;
    maintainers = with maintainers; [ yourname ];
    platforms = platforms.all;
  };
}
```

The way you were importing `<nixpkgs>` is not allowed inside Nixpkgs itself. A derivation is usually internally called with `pkgs.callPackage`, which will pass in the required things from `pkgs`.

I changed `fetchgit` to `fetchFromBitbucket`, but it's basically the same.

Instead of `sha256` it is recommended to use `hash` most of the time.

In the maintainer list, you should put the identifier of the person, who's going to mainting the derivation inside this repo. If you're not yet in the `maintainers` list you can add yourself in a separate commit into [`maintainer-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix)

According to the repo, this program should run on anything supporting perl (`platforms.all`)

Also, according to `LINCENSE` in the repo, this should be under the `gpl2` license or whatever license `perl` uses (`artistic1`)

**Comment by TomaSajt** [comment]
If you wanted to use the `Makefile` from the repo, you can chose not to override the default `installPhase`

```nix
{ lib
, stdenv
, perl
, which
, fetchFromBitbucket
}:

stdenv.mkDerivation {
  pname = "when";
  version = "1.1.46";

  src = fetchFromBitbucket {
    owner = "ben-crowell";
    repo = "when";
    rev = "a57ccbd";
    hash = "sha256-uNIU4tsoJBBPj+2rYVvXl+D5f/GB80ox6s2MgxjuJa4=";
  };

  nativeBuildInputs = [ which ];

  buildInputs = [ perl ];

  makeFlags = [ "prefix=$(out)" ];

  meta = with lib; {
    description = "An extremely simple personal calendar program";
    homepage = "https://www.lightandmatter.com/when/when.html";
    license = licenses.gpl3;
    maintainers = with maintainers; [ ];
    platforms = platforms.linux;
  };
}
```
(`which` is only used inside the `Makefile`, that's why it's in `nativeBuildInputs`)

**Comment by h7x4** [comment]
@Vonixxx Would you mind opening a PR?
