### ISSUE TITLE
pipewiredoes not correctly include dev output, thus rendering it unusable

### ISSUE THREAD

**Issue by johnworchester** [NixOS/nixpkgs#268100]
### Describe the bug
when including pipewire in buildInputs (I need its API), it provides the headers in <pipewire-0.3/pipewire/pipewire.h> instead of <pipewire/pipewire.h>

### Steps To Reproduce
1. install pipewire package
2. try to embed it in a C++ application like this --> header not found
`
#include <pipewire/pipewire.h>
`

### Expected behavior
pipewire headers should be accessible using <pipewire/pipewire.h> instead of the versioned import <pipewire-0.3/pipewire/pipewire.h>.

Temporary measures taken:
correct using CPATH in a shellHook
`export CPATH=${pipewire.dev}/include/pipewire-0.3/:${pipewire.dev}/include/spa-0.2/`

### Notify maintainers
@Kranzes

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.133.1-microsoft-standard-WSL2, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by OPNA2608** [comment]
We have the same behaviour here as [Debian](https://packages.debian.org/bookworm/amd64/libpipewire-0.3-dev/filelist) & [Fedora](https://packages.fedoraproject.org/pkgs/pipewire/pipewire-devel/fedora-rawhide.html#files), the versioning is intentional by upstream. Does any other distro mess with the header locations which causes you to expect something else?
 
 > 2. try to embed it in a C++ application like this --> header not found
>     #include <pipewire/pipewire.h>

> Temporary measures taken:
> correct using CPATH in a shellHook

In general, consider using `pkg-config` to get cflags & ldflags for dependencies instead of relying on everything to be, i.e. `pkg-config --cflags libpipewire-0.3`. I would expect the same to be necessary on other distros, and pipewire's own wireplumber subproject [uses this pkg-config to find & use libpipewire](https://gitlab.freedesktop.org/pipewire/wireplumber/-/blob/74d3b550d3e7e4899ec2a8d32081c53de30f72d7/meson.build#L52).
