### ISSUE TITLE
Why isn't Intellij community edition build from source?

### ISSUE THREAD

**Issue by liamwigney** [NixOS/nixpkgs#26866]

**Comment by Mic92** [comment]
Probably because nobody made the effort to build it from source. Archlinux seems to have taken the same route: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/intellij-idea-community-edition

**Comment by copumpkin** [comment]
Might be nice to make a Project (that tab next to Pull Requests) for "big gnarly binary packages that we'd like to build from source" so we can track things like this, Electron, bazel, openjdk for mac, and a few others. Then motivated folks could go browse them and figure out how to turn them into source builds.

I wouldn't say that bootstraps are fundamentally bad but they do make builds more annoying. The OpenJDK build for Linux currently has a bootstrap expression for building a bootstrap compiler that then gets fetched to build the one we actually use. It's a fairly common pattern and not an awful one (unless you want source builds because you're afraid of Ken Thompson attacking you; then you're probably out of luck)

**Comment by copumpkin** [comment]
Okay, did the project thing. Feel free to add stuff.

**Comment by vcunat** [comment]
AFAIK Java stuff in nixpkgs is often handled this way, as there are yet few nixpkgs contributors that work on Java packages.

**Comment by copumpkin** [comment]
Yeah, and also bootstrapping the java package world from scratch is genuinely terrifying.

**Comment by vcunat** [comment]
The advantage is that you can "update" arbitrary packages independently, AFAIK, so it wouldn't seem too terrifying to me to start with the most interesting stuff for the interested (potential) contributors.

**Comment by copumpkin** [comment]
Yeah, just saying that building all the really low-level maven stuff that everyone else uses is going to be a big PITA.

**Comment by glglwty** [comment]
IMO there should be a meta field to protect people who don't want blobs from accidentally installing those packages. Licence doesn't express that.

**Comment by vcunat** [comment]
See [another thread](https://discourse.nixos.org/t/meta-attribute-for-binary-packages/657) for that.

**Comment by kurnevsky** [comment]
Arch builds it from source now: https://github.com/archlinux/svntogit-community/blob/packages/intellij-idea-community-edition/trunk/PKGBUILD

**Comment by GenericNerdyUsername** [comment]
Is the goal for this to compile just the ide from source, or the ide+dependencies? Former seems somewhat redundant, latter is probably a pretty big task

**Comment by GenericNerdyUsername** [comment]
Also, theres mention of a docker build method in [the readme](https://github.com/JetBrains/intellij-community/blob/master/README.md), which might be worth a shot

**Comment by GenericNerdyUsername** [comment]
ive looked into this some more, turns out they have their own build system (JPS), but also use others in various places (ant, gradle, maven). As far as I can tell, JPS is exclusive to jetbrains and has no documentation, or at least none that I can find. They do include a bootstrap utility, but it downloads classes via maven that are part of the source tree, which means we have three options: using the downloaded classes (kinda defeats the point of building from source), making a JPS builder that doesn't have this problem (a lot of effort) or using past versions to build our way up to the current one (hacky, also a lot of work)

**Comment by GenericNerdyUsername** [comment]
Theres also a `libdbm.so` binary there, which I can't find the source of, unless its an [old database thing from oracle](https://docs.oracle.com/cd/E19455-01/806-0632/6j9vm89ha/index.html) or [this random project with 5 stars](https://github.com/libdbm/libdbm)

**Comment by GenericNerdyUsername** [comment]
Im not very well versed in java build systems, so theres a good chance I've missed something, but the way the docker container does it seems like a no-go

**Comment by YoshiRulz** [comment]
> Theres also a `libdbm.so` binary there, which I can't find the source of, unless its an [old database thing from oracle](https://docs.oracle.com/cd/E19455-01/806-0632/6j9vm89ha/index.html) or [this random project with 5 stars](https://github.com/libdbm/libdbm)

From commit history, looks to be "**DB**us **m**enu wrapper" https://github.com/JetBrains/intellij-community/tree/master/native/LinuxGlobalMenu

**Comment by GenericNerdyUsername** [comment]
pull #259373 isn't done, but might be of interest

**Comment by MattSturgeon** [comment]
This can be closed as completed

**Comment by samueldr** [comment]
Closing, assumed this is right.
