### ISSUE TITLE
Build failure: nvidia-x11 with linuxPackages_latest

### ISSUE THREAD

**Issue by drakon64** [NixOS/nixpkgs#269037]
### Steps To Reproduce

1. build nvidia-x11 with the `linuxPackages_latest` kernel

### Build log
https://gist.github.com/drakon64/1aa3dce8e014438b83a11694b3a3be72

### Additional context

- Occurs with both the proprietary module and the open module (log is for the open module)
- Cannot reproduce with the default Linux kernel
- Build command: `nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=live.nix`
- Configuration file: https://github.com/drakon64/nixos-config/blob/82488a6ea7acb27b3ca93eeb2ae0051cb8444950/live.nix

### Notify maintainers

@jonringer @Kiskae 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
adamc@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.05 (Stoat), 23.05.4873.8e5e424b1c05`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.6`
 - channels(adamc): `""`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Kiskae** [comment]
The issue is that nvidia driver updates don't get backported while linux kernel updates do. And it looks like the `nvidiaPackages.latest` release shipped with `nixos-23.05` is not compatible with linux 6.6.

You can probably use `linuxPackages_6_5` until nixos `23.11` releases, which includes the latest nvidia driver and works with all new kernels.

**Comment by Atemu** [comment]
Why is the nvidia driver assumed to be generally compatible with any future kernel version when it is clearly not?

The nvidia-x11 packages should mark themselves broken when newer than the last known good kernel version. The last known good kernel version should then manually be bumped when verified to be working.

**Comment by Kiskae** [comment]
Mostly because the nvidia drivers are in an awkward spot:
- Individual driver versions tend to only be supported until a superceding version is released, leading to issues between older driver versions and newer kernels.
- The nvidia userspace libraries are hardcoded to their respective kernel module version, so backporting would result in breaking running systems when their versions become mismatched during an update. #255070
- I generally keep an eye on the unstable branch and whether the current drivers compile, but nobody really checks the stable channels until a report comes in.

Explicitly marking a supported latest version like zfs is possible, but someone will need to take responsibility for maintaining this on the stable branch since we can't synchronize it with the unstable branch without updating the driver version.

**Comment by Atemu** [comment]
> Individual driver versions tend to only be supported until a superceding version is released, leading to issues between older driver versions and newer kernels.

Well, the incompatibility was always there.

That's why the driver should mark itself as broken as soon as it encounters a kernel ABI newer than the last known good ABI.

> * The nvidia userspace libraries are hardcoded to their respective kernel module version, so backporting would result in breaking running systems when their versions become mismatched during an update.

This issue will always exist; in any distro.

We have the luxury of potentially working around the issue using hack (as described in #255070) but I don't think we should pay much attention to that issue. It's up to Nvidia to get their shit together and provide stable kernel APIs like everyone else does.

> I generally keep an eye on the unstable branch and whether the current drivers compile, but nobody really checks the stable channels until a report comes in.

Marking the drivers as broken on "unknown" kernel versions will systemise this process and also speed it up because the time until "a report comes in" will be instantly after the kernel ABI changes as your system would simply not even eval.

> someone will need to take responsibility for maintaining this on the stable branch since we can't synchronize it with the unstable branch without updating the driver version.

This systemisation will lead to easier backports. Ideally, all it should take to backport is just attaching a backport label to every PR which bumps version compats.

You should be backporting all version bumps anyways (security bugs say hello). The only difference between unstable and stable should be that `nvidia_stable = nvidia_xyz;` rather than `nvidia_latest` perhaps and that shouldn't interfere with the compatibility declarations.

**Comment by drakon64** [comment]
23.05 is EOL and this does not occur on 23.11 with the 6.7 kernel
