### ISSUE TITLE
when starting minecraft through prismlauncher screen flickers after loading screen

### ISSUE THREAD

**Issue by TheBunnyMan123** [NixOS/nixpkgs#269017]
### Describe the bug
Minecraft flickers red or black when starting through prismlauncher

### Steps To Reproduce
1. Install latest prismlauncher
2. Run Minecraft
3. Wait for loading to finish

### Screenshots
Video because screenshot wont work
[out.webm](https://github.com/NixOS/nixpkgs/assets/69465699/e2e49054-65c0-4471-9849-1ec5edab75bd)

### Additional context
When starting older versions, it complains about no glibc

### Metadata 
(I use flakes)
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11.20231119.e4ad989`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
@TheBunnyMan123

I had glibc issues too that was caused by java being set to a nix store path, for example `/nix/store/q6g0d4ay38ydn99z2n5249fma8267ym3-openjdk-19.0.2+7/lib/openjdk/bin/java` which I assume causes issues after a system update.
To fix this, make sure your java (Prism Launcher -> Settings -> Java -> java path OR instance -> Edit -> Settings -> Java installation) is set to `java`  and you have the correct version of java installed.
For running old and new minecraft versions, I make symlinks to java 8 and 21 using Nix, and just put `java-8` or `java-21` to the java field for each instance:
```nix
environment.sessionVariables.PATH = [
  "$HOME/.local/bin"
];

home-manager.users.<user> = {
  home.file = with lib; with pkgs; {
    ".local/bin/java-8".source = getExe' jdk8 "java";
    ".local/bin/java-21".source = getExe' jdk21 "java";
  };
}
```


The flickering black screen is most likely a graphics driver issue, have you installed them correctly? [Nvidia](https://nixos.wiki/wiki/Nvidia) needs some extra tweeking.

**Comment by gepbird** [comment]
This issue should be resolved. Feel free to reopen, if not.
