### ISSUE TITLE
global: GTAGSCONF path

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#26971]
## Discovery
`helm-gtags-update-tags` in emacs was failing for me. I dug into it and found that it runs the `global` program.

## Issue description
When I run `global`, I get an error like this,

```
$ global --single-update /Users/acowley/Documents/Projects/Foo/src/main.cpp
gtags: config file '/nix/store/w7jasgcw1vpdf2baqbz82dpr2mcswhkk-global-6.5.7/share/gtags/gtags.conf:/nix/store/w7jasgcw1vpdf2baqbz82dpr2mcswhkk-global-6.5.7/share/gtags/gtags.conf' not found.
```

However, the `gtags` executable works fine.

## Suggested Fix

If I remove the `GTAGSCONF` environment variable update [in the `global` wrapper script](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/global/default.nix#L40), the problem goes away.

I did not change the `gtags` wrapper, so the issue reported in the [PR that added this setting](https://github.com/NixOS/nixpkgs/pull/24057) is still fixed as that issue only mentions the `gtags` executable.

All that said, I am not a very deep user of `global`, so I may be inadvertently breaking something. If other people think my suggested change (removing the `GTAGSCONF` setting from the `global` wrapper) is fine, I can open a PR.

**Comment by 0xABAB** [comment]
@acowley The PR was complete garbage and `GTAGSCONF` should never have been set and certainly not via `--prefix`. `--set` would have been an option, but would be equally stupid based on the documentation https://www.gsp.com/cgi-bin/man.cgi?section=5&topic=gtags.conf#4, because presumably a user would want to override `GTAGSCONF` by pointing to a location in their home dir, for example.

The author had an immediate problem and fixed it for his use case, but didn't care about the general case. So, what should have happened was an injection of the location of the default location of the configuration file into probably the source code and `GTAGSCONF` should be left alone, such that users can override it on a by need basis. 

With this analysis, this is now ready for implementation.

**Comment by vmandela** [comment]
@0xABAB

I am facing the same issue as well and have reverted https://github.com/NixOS/nixpkgs/pull/24057 to fix the issue. I believe the issue in the original PR can be fixed by copying gtags.conf from the installation directory in to the users home folder as ~/.globalrc. Is that an acceptable solution? If yes, can we revert https://github.com/NixOS/nixpkgs/commit/5f488bfc342371d632fe95a3d1c11cc91f03c442

CC: @lpenz @acowley

**Comment by acowley** [comment]
I liked the suggestion by @0xABAB to inject the default location into the source when building, but haven't had a chance to try implementing it.

**Comment by lpenz** [comment]
We while we don't have that, the PR above reverts the previous one.

Sorry for the trouble.
