### ISSUE TITLE
virtualenvwrapper hurts the $PATH

### ISSUE THREAD

**Issue by mickk-on-cpp** [NixOS/nixpkgs#26982]
## Issue description

A typical workflow when using virtualenvwrapper begins with something similar to the following:

```bash
source virtualenvwrapper.sh
```

Unfortunately when using e.g. `python3Packages.virtualenvwrapper` this can be troublesome. Consider the following, starting from a system with `gcc7` installed:

```bash
mickk@behemoth-nixos:~$ echo "$PATH"
/home/mickk/bin:/run/wrappers/bin:/etc/per-user-pkgs/mickk/bin:/home/mickk/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
mickk@behemoth-nixos:~$ gcc --version
gcc (GCC) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mickk@behemoth-nixos:~$ nix-shell --command bash --pure -p bashInteractive gcc7 python3Packages.virtualenvwrapper
mickk@behemoth-nixos:~$ gcc --version
gcc (GCC) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mickk@behemoth-nixos:~$ source virtualenvwrapper.sh
mickk@behemoth-nixos:~$ gcc --version
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

This is particularly annoying for a user that follows this advice from [the documentation](https://virtualenvwrapper.readthedocs.io/en/latest/):

> You will want to add the command to `source /usr/local/bin/virtualenvwrapper.sh` to your shell startup file […]

(For my part `virtualenvwrapper.sh` was being sourced at every zsh session by the Oh-My-Zsh [virtualenvwrapper plugin](https://github.com/robbyrussell/oh-my-zsh/blob/d848c94804918138375041a9f800f401bec12068/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh#L22) that I enabled in my configuration.)

### Possible cause

As I understand it this is caused by the following, excerpted from the `python3Packages.virtualenvwrapper` derivation call in `pkgs/top-level/python-packages.nix`:

```nix
    postInstall = ''
      # This might look like a dirty hack but we can't use the makeWrapper function because
      # the wrapped file were then called via "exec". The virtualenvwrapper shell scripts
      # aren't normal executables. Instead, the user has to evaluate them.

      for file in "virtualenvwrapper.sh" "virtualenvwrapper_lazy.sh"; do
        local wrapper="$out/bin/$file"
        local wrapped="$out/bin/.$file-wrapped"
        mv "$wrapper" "$wrapped"

        # WARNING: Don't indent the lines below because that would break EOF
        cat > "$wrapper" << EOF
export PATH="$PATH:\$PATH"
export VIRTUALENVWRAPPER_PYTHONPATH="$PYTHONPATH:$(toPythonPath $out)"
source "$wrapped"
EOF

        chmod -x "$wrapped"
        chmod +x "$wrapper"
      done
    '';
```

Namely the `export PATH="$PATH:\$PATH"` line which clobbers `PATH` when the virtualenvwrapper.sh wrapper is sourced. I'm not sure what the correct remedy should be.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

  Nixos 17.09pre109180.0d4431cfe9 (Hummingbird)

* Nix version: (run `nix-env --version`)

  nix-env (Nix) 1.11.10

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

  "17.09pre109180.0d4431cfe9"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

  No.

**Comment by FRidh** [comment]
I think @cillianderoiste used or wrote this.

**Comment by 0xABAB** [comment]
@mickk-on-cpp The semantics you want cannot work in general, which is why it's not done like that. Consider that the python you are running did something at run-time to inspect the PATH to find gcc and crash if it was different from the build time version of gcc (which is possible in general).

As such, what you want to do requires knowledge about the specific operating conditions and environment, which presumably you have in this particular case. To fix this, one could introduce a script to selectively override certain entries on the PATH. Such a feature would be useful to have, but I wouldn't mind if such a feature didn't exist in nixpkgs.

I think the best way forward is for @mickk-on-cpp to implement whatever he wants privately and then reports back in a year or so to share what is working great for him and then open a PR with the changes. 

So, my recommendation would be to close this ticket as WONTFIX, because it's questionable whether it's in scope of the nixpkgs project and it's not actionable.

**Comment by mickk-on-cpp** [comment]
To clarify I am not the upstream author of virtualenvwrapper. I am not the author of the OMZ plugin either. The decisions that virtualenvwrapper must work by sourcing a script, and that OMZ integration automatically takes care of that sourcing are not mine to make.

> The semantics you want […]

> I think the best way forward is for @mickk-on-cpp to implement whatever he wants privately […]

I hope you don’t mind my saying but those are weird things to say. What are all these things I want? I was not kept informed of them.

**Comment by 0xABAB** [comment]
@mickk-on-cpp  You want it to work such that some plugin works, right? That means you want certain semantics. In particular semantics you have failed to articulate for the general case. I know what you want to happen in case of `gcc` and it would be easy to fix that in some script that's sourced after ` virtualenvwrapper.sh`.

However, there might be another user who wants to have the semantics as they are today. Both are valid semantics and there is no reason why your example should fall within the default semantics. 

So, while there are ad hoc changes to fix this; it's not obvious that such changes would not result in someone else complaining about the new behaviour, which is why any such fix should be based on the documentation of the semantics of the projects involved. 

No such case has been made in my opinion and as such there is no point in discussing this further. 

Please, do not be alarmed, since I am just another user, and you can hope that people with commit access have another opinion.

**Comment by FRidh** [comment]
```
export PATH="$PATH:\$PATH"
````
`$PATH` is taken from the derivation and that includes all build-dependencies. This is a bug. All it needs is `/nix/store/....-python.../bin`.

**Comment by FRidh** [comment]
Proposed fix at https://github.com/NixOS/nixpkgs/pull/27079

**Comment by FRidh** [comment]
@mickk-on-cpp did you try the PR?

**Comment by mickk-on-cpp** [comment]
Sorry for my late response, I was not available the past couple of weeks.

I tried the fix and that does look like a happier `$PATH` on my end, that’s great! As a nitpick (and keeping in mind that ultimately I don’t know what the wrapper should be doing), this bit is unconditionally setting the path:

```bash
export PATH="${python}/bin:\$PATH"
```

That means if I re-enable my OMZ plugin, subshells typically will get duplicate path entries (including those started by a `nix-shell` without the `--pure` argument). Fortunately that's relatively harmless, but I’d rather mention it in this discussion in case someone stumble their way here via a web search.

(There are ways to conditionally set the path, but those I know rely on double bracket syntax e.g.:

```bash
if [[ \$PATH: == "${python}"/bin:* ]]; then
```

I don’t think it’s appropriate considering `virtualenvwrapper.sh` is meant to be [cross-shell compatible](http://virtualenvwrapper.readthedocs.io/en/latest/install.html#supported-shells). As a point of reference, it does not use that syntax itself.)
