### ISSUE TITLE
Update request: gradience 0.4.1 → 0.8.0-beta1

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#270074]
- Package name: gradience
- Latest released version: 0.8.0-beta1

- Current version on the unstable channel: 0.4.1
- Current version on the stable/release channel: 0.4.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@foo-dogsquared 

-----

Note for maintainers: Please tag this issue in your PR.

**Priorities**

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by surfaceflinger** [comment]
Hi, for now I have it available here if u need it: `nix run github:surfaceflinger/flake#gradience`

I had to patch out shell theme switching related to shell theming because it didn't work with my GNOME. `gsettings list-schemas` for some reason doesn't list schemas related to my extensions - idk why. "Patch" is here: https://github.com/GradienceTeam/Gradience/blob/main/gradience/backend/theming/shell.py
I also made [the package](https://github.com/surfaceflinger/flake/blob/master/packages/gradience/default.nix) a bit simpler in comparison to [what's in nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/gradience/default.nix#L78)

Also, as of today, current main branch of Gradience still doesn't theme latest GTK4/Libadwaita/adw-gtk3 properly. So if you just want to change Adwaita accent color, put eg. this into ur `.config/gtk-{3.0,4.0}/gtk.css`

```
@define-color accent_color #e8cbe0;
@define-color accent_bg_color #a86487;
```

**Comment by Ashvith10** [comment]
@surfaceflinger thank you for taking your time to create a convenient flake. Since I'm on the early version of 23.11-beta/24.05-pre, I think I'll wait for the official release of 23.11, after which I'll experiment with your repo.
