### ISSUE TITLE
Package request: libadwaita-without-adwaita

### ISSUE THREAD

**Issue by RoccoRakete** [NixOS/nixpkgs#270458]
**This enables adwaita applications to use GTK3 theming.**

**Metadata**

* homepage URL: https://gnome.pages.gitlab.gnome.org/libadwaita/
* source URL: https://aur.archlinux.org/packages/libadwaita-without-adwaita-git
* license: LGPL 
* platforms: linux

**Comment by alex-fu27** [comment]
Hmm, this is a patch for the original libadwaita.
The thing is that in Nix, if you apply a patch to a library, all applications depending on that library need to be rebuilt. So I do not want to try this out myself, but to apply this patch to your system, try adding an [Overlay](https://nixos.wiki/wiki/Overlays) to your NixOS configuration like this:
```nix
nixpkgs.overlays = let
      aurRepo = pkgs.fetchgit {
            url = "https://aur.archlinux.org/libadwaita-without-adwaita-git.git";
            rev = "f3fd1a3412eed5c901145932f7d8d37ad8f8ca36";
            hash = ""; # fix later
      };
      themingPatch = aurRepo + "/theming_patch.diff";
in [
    (final: prev: {
	libadwaita = prev.libadwaita.overrideAttrs (old: {
            patches = (old.patches or []) ++ [
                themingPatch
            ];
	});
    })];
```

Now I dont know if it is desirable to have this in nixpkgs. I am also "new" to the Nix ecosystem, so I dont know whom to ask. If you want, find the maintainers of the `libadwaita` package in nixpkgs and ask them to add an override switch for the `libadwaita` package to enable the patch.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/NixOS/nixpkgs/issues/270458#issuecomment-2622069296

@SuperSandro2000, applying DE-wide colour themes to GTK4 CSS. Despite GTK4 supporting it just like GTK3 does, Libadwaita usually prevents this, but the patch should re-enable it.

**Comment by SuperSandro2000** [comment]
That's something custom for your personal config and not for nixpkgs.

**Comment by 1emank** [comment]
@SuperSandro2000 I'd say it's something in the general interest of anyone who doesn't use Gnome but may use some libadwaita apps, like gnome-boxes or flatseal (to the point it should be a default).

If it's against some crucial philosophy of nixpkgs, maybe instead of a package it could be a configuration option. Maybe something under `programs.libadwaita`? It could be this, or [libadapta](https://github.com/xapp-project/libadapta), which from what I understand (although I'm not an expert), it's less of a hack and more like a proper library to substitute libadwaita.

**Comment by amarshall** [comment]
The issue with having this as “personal config” is that it requires a code change to libadwaita and thus a mass-rebuild or resorting to `replaceDependencies`. The patch could be adopted to make it opt-in at runtime, but IMO it would be a benefit to customizability (without mass rebuild) to have this as part of libadwaita. I’m willing to do the work, but I’m not sure if it would be accepted.

libadapta is likely not viable (at least as a default) since it is a fork that is now far behind.

**Comment by SuperSandro2000** [comment]
Please talk to the gnome people if adding this patch per default is acceptable.
