### ISSUE TITLE
Mosquitto service default config is insecure

### ISSUE THREAD

**Issue by richardlarocque** [NixOS/nixpkgs#27130]
## Issue description
The out-of-the-box configuration of Mosquitto will accept *any* password.  The `service.mosquitto.users.foo.password` setting is irrelevant.

### Steps to reproduce
I don't think these details make much difference, but I'll document them here just the same.

1. Set up Mosquitto with TLS.
2. Set up a user with some ACLs and a password.
3. Use `mosquitto_sub` to connect as this user.  Note that the password argument is irrelevant.

```
mosquitto_sub -h localhost -p 8883 -t 'foo/#' -d -u richard -P blargh --cafile /etc/ssl/certs/ca-bundle.crt
mosquitto_sub -h localhost -p 8883 -t 'foo/#' -d -u richard -P otherPW --cafile /etc/ssl/certs/ca-bundle.crt
```

## Technical details
The problem seems to be that the `password_file` option is not specified.  An effective work-around is:
```
services.mosquitto.extraConf = "password_file /var/lib/mosquitto/passwd";
```

It seems this is expected behavior.  See this matrix at: http://www.steves-internet-guide.com/mqtt-username-password-example/

* System: NixOS 17.03 (deployed with NixOps)

**Comment by 0xABAB** [comment]
I don't think this fix is within the spirit of the Mosquitto project. The Mosquitto project makes it easy to get started with the service, but you are now throwing that away too. 

The way I would like to see it work is to have a boolean option "insecure" where true means the behavior as it was before the PR. 

Additionally, when the password file is not set, a helpful hint is given pointing at the insecure option with a big warning about the security implications as well as the option for setting the password file to a real secure configuration.

**Comment by richardlarocque** [comment]
Sorry, I don't often get time to work on this.  I'll try to leave enough information here that you can make decisions and push forward without much more iterations.

I wrote some tests:
```ruby
#!/usr/bin/env ruby

[
  ["No auth",                        "mosquitto_pub -t 'test' -m 'Foo'"],
  ["Unregisterd user, no password",  "mosquitto_pub -u guest -t 'test' -m 'Foo'"],
  ["Registered user, no password",   "mosquitto_pub -u john -t 'test' -m 'Foo'"],
  ["Registered user, bad password",  "mosquitto_pub -u john -P 'badpass' -t 'test' -m 'Foo'"],
  ["Registered user, good password", "mosquitto_pub -u john -P '12345' -t 'test' -m 'Foo'"]
].each do |name, cmd|
	result = system(cmd + " 2>/dev/null") ? 'PASS' : 'FAIL'
	puts "#{name}: #{result}"
end
```

And here's a default-ish NixOS config for mosquitto:
```
{
  services.mosquitto.enable = true;
  #servies.mosuitto.allowAnonymous = true;
  services.mosquitto.checkPasswords = true;
  services.mosquitto.users = {
    john = {
      acl = [ "topic readwrite john/#" ];
      password = "12345";
    };
  };
}
```

And here's the result:

Invocation  | without allowAnonymous | with allowAnonymous
---|-----------------------------------|------------------------------
No auth | FAIL | PASS
Unregistered user | PASS | PASS
Registered user, no password | PASS | PASS
Registered user, bad password | PASS | PASS
Registered user, good password | PASS | PASS

This is so far from my expectations that I'm inclined to treat it as a bug.  Why should the NixOS configs allow the user to specify the contents of the password file when those contents will be completely ignored?

Here's what it looks like when we modify the config so that the password file is actually used:

Invocation  | without allowAnonymous | with allowAnonymous
---|-----------------------------------|------------------------------
No auth | FAIL | PASS
Unregistered user | FAIL | FAIL
Registered user, no password | FAIL | FAIL
Registered user, bad password | FAIL | FAIL
Registered user, good password | PASS | PASS

This is more like what I would have expected.

I believe this is not *too* much of an extra burden on setup.  If ease of use is your primary concern, you can either turn on `allowAnonymous` and have your client not specify a username and password, or just hard-code every password to `123`.

----

I understand opinions may differ, and my arguments could prove unconvincing in the end.  @Mic92 pointed out this is a breaking change, which is a very good argument against it.

So here's my plan.  I'll update the PR to include a new `checkPasswords` option and leave it off by default.  If the value is false, you get the classic behavior as seen in the first table above.  If the value is true, you get the behavior from the second table.

I'd hope that one day `checkPasswords` could default to true, but just having it in the first place seems like an improvement.

**Comment by makefu** [comment]
just fyi, as of right now the default config is `super` secure as no client is allowed to write or read any topic.
This is due to a change in mosquitto server where an empty ACL file means no access for anyone. I stumbled over this issue after my upgrade to 19.03.

For future generations, this is a setup for a `completely insecure` server:

```nix
{
  services.mosquitto = {
    enable = true;
    host = "0.0.0.0";
    users = {};
    # TODO: secure that shit
    aclExtraConf = ''
      pattern readwrite /#
    '';
    allowAnonymous = true;
  };
}
```

**Comment by hypersw** [comment]
Ouch this last comment really saved my day -- and saved a deep dive into more detailed logs.
What I like most about Nixos is how its configs are short, to the point, and sane/secure by default making a working setup. I think we should update the service definition just a bit to make it workable by default. I just can't think up the best way here -- so that it worked for new configs and didn't make any unsafe surprises for the existing old configs.

**Comment by wagdav** [comment]
@richardlarocque given the comment of @makefu  do you think this issue can be closed?

**Comment by johannesloetzsch** [comment]
@richardlarocque Thanks for fixing this bug :)

In my opinion the the description of the checkPasswords option is misleading. It should better be something like „Allow user authentication“. When it is not set to true, even clients using the correct password are refused (assuming the default allowAnonymous=false).

I would plead for setting the default of checkPasswords to true, since this is what a new user would expect.
If we don't want this to be a breaking change, it could wait till the next nixos release.

A compromise would be to set checkPasswords=true whenever allowAnonymous==false. I see no usecase for both being false, it just yields an unusable setup.

**Comment by makefu** [comment]
For anyone interested, this is how a `completely unsecure` configuration for Mosquitto looks like on 21.11 with the rewritten mosquitto module:

```
{
  networking.firewall.allowedTCPPorts = [ 1883 ];
  services.mosquitto = {
    enable = true;
    persistence = false;
    settings.max_keepalive = 60;
    listeners = [
      {
        port = 1883;
        omitPasswordAuth = true;
        users = {};
        settings = {
          allow_anonymous = true;
        };
        acl = [ "topic readwrite #" "pattern readwrite #" ];
      }
    ];
  };
}
```

thanks to @schuelermine on https://matrix.to/#/#nix:nixos.org
