### ISSUE TITLE
ZFS dataset with specified non-legacy mount point does not automount

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#27183]
## Issue description

I expected to see all the mount points associated with all ZFS datasets to be mounted at boot. In this case that means that doing `ls /a` where zpool/a is non-empty would return files.

```
systemctl list-unit-files | grep zfs
zfs-mount.service                      enabled  
zfs-share.service                      enabled  
zfs-sync-zpool.service                 enabled  
zfs-zed.service                        enabled  
zfs-import.target                      linked   
zfs.target                             enabled  
```

```zfs list| grep zpool/a
zpool/a          1G  1T  1G  /a
```

`zfs-import.target` status according to systemd tools was `dead` and that's not supposed to happen.

This code is rather suspicious:
```
# Remove provided services as they are buggy
        rm $out/etc/systemd/system/zfs-import-*.service
``` 
@ https://github.com/NixOS/nixpkgs/blob/0518ec00b542c49a9bdb67eaee995d108cbe5846/pkgs/os-specific/linux/zfs/default.nix#L88

The zfs-import service is the service which seems to be related in all the reports surrounding this issue and seems a critical component, which cannot just be deleted. 

```
17.03.git.81fceb2 (Gorilla)
```

@Mic92 (since it appears you worked most recently on the code)

**Comment by Mic92** [comment]
We do not support `non-legacy` mounts at the moment as they rely on the assumption that hardware is immediately available instead of using event-based mechanism provided by udev like all other filesystems on linux. This might be fixed by https://github.com/zfsonlinux/zfs/pull/4943
Since zfs mountpoints are not included in fstab, it also breaks horrible if non-zfs mounts are on top of a zfs dataset, since `mount` or the systemd's mount generator cannot inter proper hierarchical dependencies.
That being said there is a generator required before we can turn this on, because this can result in unbootable systems due race conditions between zfs and the rest. If you really insist on using this feature please implement it yourself, we cannot guarantee stability for the general case.

**Comment by CMCDragonkai** [comment]
Being able to use non-legacy mountpoints would definitely make ZFS alot easier to use on NixOS especially when creating ephemeral datasets and subdatasets for various version controlled workspaces.

**Comment by Mic92** [comment]
zfsonlinux has implemented a systemd generator now in zfs master: https://github.com/zfsonlinux/zfs/pull/7329
 It is not yet integrated into nixos.

**Comment by Thunderbottom** [comment]
any updates on having the zol systemd generator integrated into NixOS?

**Comment by waphire** [comment]
So, one possible workaround for using zfs native mounts is adding only the root filesystem mountpoint to /etc/nixos/hardware-configuration.nix (just so it doesn't throw an error) and rebuilding your system with zfs datasets (including the root dataset) set to native mounts.

**Comment by Mic92** [comment]
I opened a new more actionable issue: https://github.com/NixOS/nixpkgs/issues/89396 which solves the problem.
