### ISSUE TITLE
autofs documentation incorrect

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#27202]
## Issue description
https://github.com/NixOS/nixos/blob/master/modules/services/misc/autofs.nix#L61 claims it writes to a file, while in fact it writes to systemd's journal.

Version: master 

@abbradar

**Comment by Mic92** [comment]
It properly miss stderr: https://github.com/NixOS/nixos/blob/master/modules/services/misc/autofs.nix#L113

**Comment by 0xABAB** [comment]
@Mic92 I see the input redirection, but I am not sure what you mean.

**Comment by Mic92** [comment]
```
 ${if cfg.debug then "exec 2>&1 &> /var/log/autofs" else ""}
```

**Comment by edolstra** [comment]
The autofs module looks pretty unmaintained - it hasn't seen a commit since 2012. We should probably just remove it, unless there is some compelling use case that systemd's automount units don't provide.

**Comment by Mic92** [comment]
agreed. unless their is new maintainer, we should remove it.

**Comment by 0xABAB** [comment]
@edolstra It is working fine, other than this minor issue I reported. If you have another mechanism I can use to mount NFS on demand, that might change things.

**Comment by 0xABAB** [comment]
@Mic92 Yes, I have seen that line and I still don't understand what you try to communicate.

`It properly miss stderr` is not correct English, so you can't blame me for 100% for that.

**Comment by Mic92** [comment]
The following change might help:

```diff
- ${if cfg.debug then "exec &> /var/log/autofs" else ""}
+ ${if cfg.debug then "exec 2>&1 &> /var/log/autofs" else ""}
```

**Comment by 0xABAB** [comment]
@Mic92 Right, that would help.

**Comment by abbradar** [comment]
Quick heads-up -- I won't be able to work on NixOS (and generally be available online) for two more weeks.

**Comment by larkery** [comment]
@edolstra @Mic92: I would prefer if autofs were not removed. I use it to do things which systemd's automount units alone cannot do, specifically:

1. Mounting network shares based on the path name (automount units have to refer to a path known up-front, autofs can mount e.g. `/net/$my-server-name/$my-share-name` in an intelligent way).
2. Getting credentials out of my password database; my autofs script can run some commands to ask for this, systemd automount units cannot, so I would need to have unencrypted credentials lying around.

I think I could get around this by writing out a big list of automount units for every share I ever use, and then converting my password database access scripts into some combination of units that trigger before and after the mount to store and erase the credentials, but I'd prefer not to have to do this since I have about 8 lines of autofs config currently doing the job perfectly.

If I put it under the glorious control of systemd I will also have to rebuild my system configuration / edit my fstab / reload systemd / go back to manual mount commands whenever I am plugged into a new network or need to use a new network disk.

I do recognise the maintenance burden of keeping it, and I could stick it into a module if it really is a big headache for you guys.

**Comment by Mic92** [comment]
it is only the module not the package itself, which looks a little bit scary:

```
https://github.com/NixOS/nixos/blob/master/modules/services/misc/autofs.nix#L98
```

**Comment by abbradar** [comment]
I used autofs without any problems for a long time (I've switched to systemd automounts recently but only because I've accidentially lost my autofs configuration). It doesn't seem to have a big maintenance burden so I'd vote for leaving it be for now.

@Mic92, @edolstra you seem to look in the old (unmaintained) repository. See https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/autofs.nix
