### ISSUE TITLE
Thanos query.replica-label should be type string

### ISSUE THREAD

**Issue by jpds** [NixOS/nixpkgs#273432]
### Describe the bug

`services.thanos.query.query.replica-labels` should be of type: list of strings. I typically just set this to `replica` on my deployments:

- https://thanos.io/tip/components/query.md/#deduplication

But I don't understand how I'm suppose to do that with `attribute set of string`.

### Steps To Reproduce

```
  services.thanos.query = {
    enable = true;
    http-address = "0.0.0.0:9090";
    endpoints = [
      "store-api-ip:9090"
    ];
    query.replica-labels = { thing = "replica"; };
  };
```

...which then launches the query component with `--query.replica-label=thing="replica"`.

### Expected behavior

Something more like:

```
  services.thanos.query = {
    enable = true;
    http-address = "0.0.0.0:9090";
    endpoints = [
      "store-api-ip:9090"
    ];
    #query.replica-labels = ["replica"];
    query.replica-labels = ["replica", "rack"];
  };
```

...and then launching with `--query.replica-label="replica" --query.replica-label="rack"`. ?

### Notify maintainers

@anthonyroussel
@basvandijk

**Comment by anthonyroussel** [comment]
@jpds Hello, thanks for reporting this issue!

Indeed, it looks like I made a mistake when I updated the Thanos nixos module last time: https://github.com/NixOS/nixpkgs/pull/260089 (commit https://github.com/NixOS/nixpkgs/commit/9abb2a211672132f9f8f591f9f44cab81998a88c)

There have been a lot of deprecations in the Thanos cli since the last module update, and I was wrong about the `query.replica-label` argument. It shouldn't have been changed.

Sorry about that, I'll fix it as soon as I can!
