### ISSUE TITLE
nixos-install --max-jobs 16 --cores 16 downloads sequentially

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#27400]
## Issue description

I’m rebuilding my zpool, so have to reinstall the OS. My configuration has a large number of small derivation dependencies (namely texlive).

The nixos-install is taking disproportionally large amount of time by downloading each package one-by-one rather than in parallel, how it would usually do with the nixos-rebuild.

### Steps to reproduce

* Build the iso image from todays nixpkgs (commit 7383d69514f2ec11f8fab4d7bf04c142a5ab57fd);
* Drop in your configuration.nix/hardware-configuration.nix/etc from a already working system (those were previously generated by the generate-config);
* do nixos-install --max-jobs 16 --cores 16;
* Observe it fetching the packages sequentially.

## Technical details

* System: 17.09.git.7383d69 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.12
* Nixpkgs version: 17.09.git.7383d69
* Sandboxing enabled: no, installer

**Comment by emmanuelrosa** [comment]
`nixos-install` delegates to `nix-build` and is supposed to pass along the `--max-jobs` and `--cores` options, among others. When you run `nixos-install --max-jobs 16 --cores 16`, does it pass along the aforementioned options? You can check by getting `nix-build`'s process ID and then checking `/proc/[PID]/cmdline`

**Comment by vcunat** [comment]
Note that if one output path references another, they won't be downloaded in parallel, but otherwise you should be getting `--max-jobs` downloads at once.

**Comment by nagisa** [comment]
I hope I got the right cmdline, this is with nixos-install invoked from a live system. Of course this invocation wasn’t downloading anything and simply copied the texlive from my system nix store.

```
/nix/store/wb34dgkpmnssjkq7yj4qbjqxpnapq0lw-bash-4.4-p12/bin/bash/nix/store/s6nv2hi8301p40i65k7xx39kwr2abxy1-nixos-prepare-root/bin/nixos-prepare-root/tmp/foo//nix/store/mpv4wfg0801mak69b403qjdyd65g2qyw-nixos-17.09pre110213.01c3847b9c/nix/store/vga9jp51v1qzddxdny4f2wl3kpbpvj5v-nixos-system-nixos-17.09pre110213.01c3847b9c/nix/store/2nyxh4xrqkf9mwfx18yv3igfcy991sv2-closure/nix/store/naq205cmmknmny1nfqamv22lrcgfvclp-closure/tmp/tmp.0TCYv7xtMj/channel.closure
```

**Comment by emmanuelrosa** [comment]
@nagisa, no that's the cmdline for `bash` calling `nixos-prepare-root`

What you can try from the live CD is installing `tmux` or `screen` (whichever you're comfortable with) and `psmisc` using `nix-env`. Then, kick off the installer in one *screen* and run `pstree -p` in the other. Then hopefully you'll catch the PID for `nix-build`.

You can also use `top` (which I believe is already on the live CD) or `htop` instead of `pstree`.

**Comment by bendlas** [comment]
I'm running with
```
nix.extraOptions = ''
  binary-caches-parallel-connections = 24
'';
```
Don't know if that applies to your issue.

**Comment by CMCDragonkai** [comment]
What are the `--max-jobs` and `--cores` by default? And on nixos-install shouldn't auto set to the number of cores available on the computer?

**Comment by cyounkins** [comment]
I have confirmed on 18.09 that `--max-jobs` and `--cores` are passed from `nixos-install` to `nix build`. Note that on the livecd many objects are being copied from the disk instead of being downloaded. It's hard to verify that the HTTP requests are concurrent, but I believe they are. Can we close this or is there more work to be done?

**Comment by bendlas** [comment]
@nagisa if your issue persists, please reopen.
