### ISSUE TITLE
ipfs: "fusermount": executable file not found in $PATH

### ISSUE THREAD

**Issue by apeyroux** [NixOS/nixpkgs#27414]
## Issue description

When i run `ipfs mount`, I have this message : 

> ipfs: "fusermount": executable file not found in $PATH

### Steps to reproduce

`ipfs mount`

## Technical details

* System: 17.03.1506.b6f05ca54d (Gorilla)
* Nix version: nix-env (Nix) 1.11.11
* Nixpkgs version: 17.03.1506.b6f05ca54d
* Sandboxing enabled: false

**Comment by elitak** [comment]
In your patch, I don't think `buildDepends` does anything outside of haskell packages. There's no strong typing in derivations, yet ;) AFAICT, adding `fuse` there only worked because some part of the build was smart enough to pick it up out of the path somehow. I think this fix is more correct:
https://github.com/elitak/nixpkgs/commit/5d9e9f5414d5b14af93250047c0a505eadc1c675
(If more appropriate, the PATH could be set in the system-wide wrapper constructed at ./nixos/modules/services/network-filesystems/ipfs.nix exclusively, but I think having fuse in both is better)

... but the problem is that it still will not mount because of some exit code returned by fusermount. I spent some time debugging and found that it's just a permissions problem with fuse. if you set `services.ipfs.user = "root";`, the mounting works fine. I don't know how best to address this in the nixos module, since I see no way to grant user ipfs permission to add this fuse mount. I'll have to dig into exactly how the permissions are mediated between processes. If I figure it out, I'll include it in a PR i'm prepping for the ipfs nixos module.

**Comment by Ekleog** [comment]
(triage) Is this still an issue? I'd guess with PRs like https://github.com/NixOS/nixpkgs/pull/29133 this can now be closed, but not being familiar with IPFS I'm not sure.
