### ISSUE TITLE
FLATHUB/FLATPAK ISSUE: Chrome & Chromium unable to install APPS

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#274331]
I am using Gnome 45.2 on NixOS 23.11.

When installing Chrome & Chromium from **flathub**, I am unable to install websites as apps and getting them to integrate into the users menu. I get the following error:

![Bildschirmfoto vom 2023-12-15 01-14-57](https://github.com/NixOS/nixpkgs/assets/4227548/75feb5b2-0d0e-43c8-afb2-950e50fd8737)

However, **Microsoft Egde** (which is Chrome based) is able to install apps and integrate them to in the menu without any problems!

**Comment by arthsmn** [comment]
This is probably due to these apps not having permission to access/write in the directory. Not a NixOS issue though. You can [use this guide](https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory) to add permissions to ~/.local/share/applications and ~/.local/share/icons directories.
