### ISSUE TITLE
gnomeExtensions are built questionably

### ISSUE THREAD

**Issue by cmm** [NixOS/nixpkgs#274579]
https://github.com/NixOS/nixpkgs/blob/0f10e1681d87c273a5c4a6d1b51d0b419c363793/pkgs/desktops/gnome/extensions/default.nix#L69-L92

Recently I've had to set up my nice home environment atop a Ubuntu 22.04 LTS system, and the code above got me wondering:

- Why lump extensions over several shell versions into the one attset?  Let's say the latest Nixpkgs shell version is 45; let's also say that a user is stuck running 44 or 43; let's further say that they use an extension the latest version of which does not support anything older than 45 any more.  Could be a problem, or am I missing something?
- Why the choice of 3 versions there?  If the idea is to support people who are stuck running Gnome shells that are older then the Nixpkgs Gnome shell, then it stands to reason that what many, if not most, of those people are running is an LTS release of Ubuntu (I mean they could easily be running Centos 7 or whatever, I'm limiting my imagination to actually supportable cases here).  Ubuntu LTS releases come out every 2 years, so 4 shell versions would make more sense given Gnome's half-year release cadence.  Or 5, for good measure.
- What the code above actually does is mostly two things: rearranging the extension set to key on names instead of UUIDs, and applying the needed patches/overrides so that the extensions therein actually, like, work.  I.e. the raw version-specific attsets (`gnome43Extensions`, etc.) contain many extensions that don't, in fact, actually work.  Why are those raw attrsets exposed at all?  I guess unexposing them would be a breaking change now, so how about refactoring the transformation into a function and exposing that in addition, so a person stuck with shell 42 (Ubuntu 22.04, latest LTS, is what it is) can take `gnome42Extensions` and transform it into something usable?  Or, per shell version, exposing both raw and transformed extension sets?

@piegamesde @jtojnar, would love your opinion on this.

**Comment by piegamesde** [comment]
> Why lump extensions over several shell versions into the one attset?

Because most of the time, there is a short lag between the gnome update and the extension update. If we only kept compatible extensions, this would mean to break evaluation for users for a couple of weeks. Another reason for this is that some extensions tend to work on newer Gnome versions without modifications, so they can be used even if they don't explicitly state so.

> Could be a problem, or am I missing something?

This specific scenario you describe might indeed fail, however it is not supported in the first place. `gnomeExtensions` is about the Gnome extensions for the currently packaged Gnome version in Nixpkgs. Older Gnome versions are not supported, this is what we have the `gnomeXYExtensions` attributes for as fallback.

> Why the choice of 3 versions there? If the idea is to support people who are stuck running Gnome shells that are older then the Nixpkgs Gnome shell

No, that is not the intent. The choice of three versions here is a compromise to not break evaluation too much but also not clutter the package set too much. The heuristics behind that number are:

- If an extension has not seen an update for over two Gnome releases (more than a year), then it is reasonable to assume that it won't get any updates anymore and can be dropped.
- Each Gnome update introduces API breakage, sometimes more sometimes less. Some extensions are more affected than others. It is quite common for especially smaller extensions supporting a newer Gnome version without modifications. But with each version bump behind the probability of that gets smaller, and extensions that are three Gnome updates behind are extremely unlikely to still work.

> I.e. the raw version-specific attsets (gnome43Extensions, etc.) contain many extensions that don't, in fact, actually work.

Many extensions in `gnomeExtensions` don't work either.

> Why are those raw attrsets exposed at all?

Many do work though. They are a reasonable escape hatch when things go wrong (for example some very old extensions which miraculously still keep working), but they are also a good starting point for applying patches. The extensions packaged there already have 95% of the work done, and fixing them if necessary is quite easy in a lot of times. Yes this is a sub-optimal user experience, but also not having them would probably be worse.

Unfortunately we cannot patch the old extensions, because the maintenance burden would be too high for that. It is preferable to focus our limited development resources towards fixing more extensions to run on current Gnome. Keep in mind, that Gnome 42 is oldoldoldstable and end of life since March, so expect to having to use the fallbacks and escape hatches.

**Comment by cmm** [comment]
Appreciate you taking the time, very informative!

> This specific scenario you describe might indeed fail, however it is not supported in the first place. `gnomeExtensions` is about the Gnome extensions for the currently packaged Gnome version in Nixpkgs. Older Gnome versions are not supported, this is what we have the `gnomeXYExtensions` attributes for as fallback.

This makes perfect sense, and perhaps should be stated explicitly somewhere.

> > I.e. the raw version-specific attsets (gnome43Extensions, etc.) contain many extensions that don't, in fact, actually work.
> 
> Many extensions in `gnomeExtensions` don't work either.

:smile: 

> > Why are those raw attrsets exposed at all?
> 
> Many do work though. They are a reasonable escape hatch when things go wrong (for example some very old extensions which miraculously still keep working), but they are also a good starting point for applying patches. The extensions packaged there already have 95% of the work done, and fixing them if necessary is quite easy in a lot of times. Yes this is a sub-optimal user experience, but also not having them would probably be worse.
> 
> Unfortunately we cannot patch the old extensions, because the maintenance burden would be too high for that. It is preferable to focus our limited development resources towards fixing more extensions to run on current Gnome. Keep in mind, that Gnome 42 is oldoldoldstable and end of life since March, so expect to having to use the fallbacks and escape hatches.

This also makes total sense when explained.  I guess what would help me (as in, save me from having to carry another private change in my private Nixpkgs fork) is if the process used to obtain `gnomeExtensions` from the raw set were refactored out as a function and exposed also, so I'd be able to apply it to any of the older raw extension sets.  Still something to be done at one's own risk, obviously, but at least without having to patch Nixpkgs first.

**Comment by piegamesde** [comment]
Okay, I see your issue. See also #271800 for documentation improvements.

The issue with providing your function is that it requires information about how to "resolve" naming conflicts in the case that two different extensions have the same short name. I would have to double-check that this information is still valid for older extensions in all cases. Apart from that, this might be feasible.

**Comment by cmm** [comment]
> Okay, I see your issue. See also #271800 for documentation improvements.
> 
> The issue with providing your function is that it requires information about how to "resolve" naming conflicts in the case that two different extensions have the same short name. I would have to double-check that this information is still valid for older extensions in all cases. Apart from that, this might be feasible.

Yeah, the rekeying part is optional, it's the patching part that is important here.

**Comment by piegamesde** [comment]
I'm unsure which exact information you need exposed then.

The patches themselves are mostly not compatible, and the process of patching is as straightforward as calling `overrideAttrs` on the extension. (We only have a bit of fluff around it to reduce boilerplate at scale, but you don't really need that for two or three extensions.)
