### ISSUE TITLE
Missing AWS AMIs for nixos 23.11

### ISSUE THREAD

**Issue by dnaq** [NixOS/nixpkgs#275574]
### Describe the bug

There are no AWS AMIs for nixos 23.11.
Given that nixos 23.04 is deprecated, the only ways to deploy a nixos 23.11 machine in AWS now is to either create your own AMI, or to deploy a nixos 23.04 AMI and to upgrade it, incurring both high CPU usage and large amounts of network traffic from the machine.

### Expected behavior

That AMIs exist, as alluded to in the documentation (and the official download site). 

### Notify maintainers
@RaitoBezarius @AmineChikhaoui @arianvp

**Comment by stepbrobd** [comment]
related: https://discourse.nixos.org/t/ami-for-nixos-23-11/36860

**Comment by endgame** [comment]
Dupe of: #285881
Fixed by: https://github.com/NixOS/nixpkgs/pull/292886 , which is a stop-gap to add the images to `amazon-ec2-amis.nix`. But in [this comment](https://github.com/NixOS/nixpkgs/issues/285881#issuecomment-1987311730) @arianvp points people to https://nixos.github.io/amis/ , which _does_ have 23.11 AMIs.
We can probably close this issue.

**Comment by garbas** [comment]
This was now fixed by @arianvp
