### ISSUE TITLE
Caddy nixos-rebuild switch fails when "admin off" is set

### ISSUE THREAD

**Issue by merspieler** [NixOS/nixpkgs#275516]
### Describe the bug
When you've got an existing caddy config and change minor things such some paths in the virtualHosts extraConfig, the system tries to reload the new config via the admin interface. For security reasons I've disabled it which makes the reload fail and only successfully applies the changed with a manual restart of the caddy service

### Steps To Reproduce
1. setup some caddy config, setting `services.caddy.globalConfig = ''admin off'';`
2. change some stuff in a virtualHost config and do a nixos-rebuild switch
3. The switch says it had issues reloading the caddy config.
Caddy journal shows the following error:
```
Dec 19 19:28:36 kara caddy[2190151]: {"level":"info","ts":1703010516.8052123,"msg":"using provided configuration","config_file":"/etc/caddy/caddy_config","config_adapter":"caddyfile"}                                                                                           Dec 19 19:28:36 kara caddy[2190151]: Error: sending configuration to instance: performing request: Post "http://localhost:2019/load": dial tcp [::1]:2019: connect: connection refused
Dec 19 19:28:36 kara systemd[1]: caddy.service: Control process exited, code=exited, status=1/FAILURE
```

### Expected behavior
Caddy gets its new config reloaded no matter if `admin off` is set or not

### Notify maintainers

@Br1ght0ne @emilylange @techknowlogick

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.64, NixOS, 23.11 (Tapir), 23.11.1115.5de0b32be6e8`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by emilylange** [comment]
This is expected behavior.

Excerpt from the documentation/description of [`services.caddy.enableReload`](https://search.nixos.org/options?channel=23.11&show=services.caddy.enableReload):

> [...] Note that enabling this option requires the [admin API](https://caddyserver.com/docs/caddyfile/options#admin) to not be turned off. [...]

I get that you might not want to have an admin API listening on `127.0.0.1:2019`.
But please note that you should also be able to use a unix socket (with proper permissions) for the admin API instead :)

So your options are (in no particular order):
- Set `services.caddy.enableReload = false;` and thus lose hot reload
- Configure Caddy to use a unix sockets for the admin API instead of TCPIP.
- Re-enable the admin API with TCPIP (probably not what you want).
