### ISSUE TITLE
Build failure: aiogram

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#277097]
### Steps To Reproduce

1. `nix shell 'self#python3Packages.aiogram'`

### Build log

```
unpacking sources
unpacking source archive /nix/store/l82q5lfx9sf0cjd6cyd5a8077vx091kw-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tests/test_webhook/test_security.py
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
substitute(): ERROR: file 'setup.py' does not exist
/nix/store/wr08yanv2bjrphhi5aai12hf2qz5kvic-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
```

### Notify maintainers

@sikmir

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.4, NixOS, 24.05 (Uakari), 24.05.20231204.2c7f3c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - channels(root): `"nixos"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ghpzin** [comment]
Doesn't seem like it was ever built successfully after `2.25.1 -> 3.0.0` update:
https://github.com/NixOS/nixpkgs/commit/2586fb4407a05cf4b8ef51977c29fbbd6cbaf530
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python310Packages.aiogram.x86_64-linux
Because there is just no `setup.py` in that version any more:
https://github.com/aiogram/aiogram/blob/v2.25.1/setup.py
https://github.com/aiogram/aiogram/blob/v3.0.0/setup.py
https://github.com/aiogram/aiogram/commit/bdae5fb026ab3b6a0f97e4d6aed3b9b7ebd85e06

**Comment by fabaff** [comment]
The last couple of update of `aiogram` were done during mass update runs.  3.2.0 was introduced with #271586 and 3.0.0 was done with #251878. The latest release should be available in `staging-next`, I guess, which is also broken.
