### ISSUE TITLE
Default port value in Nebula service causes issues on local networks / lighthouse inside same NAT

### ISSUE THREAD

**Issue by magneticflux-** [NixOS/nixpkgs#277066]
### Describe the bug
When a "lighthouse" and a regular "roaming" node are on the same network and the default value for `listen.port` (`4242`) is used, nodes occasionally enter a consistent failure state while trying to connect. I suspect this occurs when Nebula tries to NAT-punch with the local router and always tries to connect to the lighthouse instead of the roaming node.

### Steps To Reproduce
1. Set up a lighthouse node and roaming node
2. Port-forward port 4242 for the lighthouse node
3. Forget to set a value for `port` in the Nebula config
4. Observe intermittent failures

### Expected behavior
The value of `port` should be required, with a link to Nebula docs: https://nebula.defined.net/docs/config/listen/#listenport

### Additional context
I'm not entirely sure, but logs from the issue indicate the lighthouse-node handshakes are both sending packets to "192.168.1.1:4242", which is port-forwarded to the lighthouse (I'm in a dual-NAT setup unfortunately; this is the IP of the outer NAT). Explicitly setting the port to `0` (to automatically select an ephemeral port) on the roaming nodes immediately fixes the issue.

### Notify maintainers
@Jaculabilis (wrote the initial module with the port default)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Jaculabilis** [comment]
> The value of `port` should be required, with a link to Nebula docs: https://nebula.defined.net/docs/config/listen/#listenport

Based on those docs, I think we can solve this without requiring the user to specify the port.

> `port` is the UDP port nebula should use on a host. For a lighthouse node, the port should be defined, conventionally to `4242`, however using port 0 or leaving `port` unset will dynamically assign a port and is recommended for roaming nodes. Using 0 on lighthouses and relay hosts will likely lead to connectivity issues.

Since we know whether a node is a lighthouse via `services.nebula.networks.<name>.isLighthouse`, we could implement a behavior where `port` defaults to `4242` for lighthouses and `0` for non-lighthouses:

```
listen.port = mkOption {
  type = types.port;
  default = if cfg.services.nebula.networks.<name>.isLighthouse then 4242 else 0;
  description = lib.mdDoc "Port number to listen on.";
};
```

I'm not sure how to get the `<name>` for this, though. Maybe if the options were `rec`, then we could just refer to `isLighthouse`? We'd probably also want to include `isRelay`.

@numinit Thoughts?

**Comment by numinit** [comment]
My thought is that a change should meet the following requirements:

- Per https://nixos.org/manual/nixos/stable/#sec-option-declarations set `default = 0` and `defaultText` to something like:

```
lib.literalExpression ''
if (config.services.nebula.networks.''${name}.isLighthouse
  || config.services.nebula.networks.''${name}.isRelay) then
4242
else
  0;
```

- Set the actual _value_ appropriately in the module with an expression like the above if the input is less than 1.
- If (isLighthouse or isRelay) and the final port evaluates to 0, we should warn, since this config will probably result in connectivity issues.

**Comment by numinit** [comment]
Also, @magneticflux-: good job diagnosing this. I think I've run into this before but didn't know what was causing it.

**Comment by numinit** [comment]
Per https://github.com/slackhq/nebula/blob/v1.8.2/CHANGELOG.md (captured in #279826 + https://github.com/slackhq/nebula/pull/1057)

> Fix multiple routines when listen.port is zero. This was a regression introduced in v1.6.0. (#1057)

Given this, it is probably a good idea to both fix and backport this.
