### ISSUE TITLE
hplip is missing photosmart printers

### ISSUE THREAD

**Issue by code-ape** [NixOS/nixpkgs#27740]
Note that the brackets with numbers throughout this issue description refer to the footnotes by number, example: [1]

## Issue description and steps

I have an HP Photosmart 7510 series printer, which has been supported by hplip as of 3.11.10[1] but it isn't part of the installation for Nixos 17.03 (hplip version 3.16.5)[2].

### Add hplip, printing, and avahi to configuration.nix
Install hplip with following lines in `configuration.nix`. 

```nix
{ config, pkgs, ... }:

{
 # ...
  environment.systemPackages = with pkgs; [
    # ...
    # HPLIP
    hplip
  ];

  # Enable the printing
  services.printing.enable = true;
  services.avahi.enable = true;

}
```

### Attempt to run from GUI icon
I'm running the Plasma5 desktop and attempting to run HP Device Manager (which can be launched from a terminal with `hp-toolbox`) crashes with the system tray stuck hanging and eating CPU (you can kill the process to solve this).

### Attempt to run setup wizard by launching from CLI
However I can run `hp-setup` which will launch without crashing, though it fails to run the avahi discovery option for the network printer and you must open therefore open up UDP ports 5353 (mDNS / Bonjour) and 427 (SLP) in your `configuration.nix`. Even with the ports open you must run `hp-setup` as root for it to work. To isolate the problem and remove the network aspect I simply plugged the printer up via its USB connection, though I still had to run `hp-setup` as root for it to find the printer.

### hp-setup, run under root, finds printer but installation is missing drivers for it

Upon running this it identified the printer but couldn't find the appropriate ppd file for it. I verified that there is no ppd file in the package installation for a photosmart 7510 series however the source code for this version of hplip[3] does include it (path `hplip-3.16.5/ppd/hpcups/hp-photosmart_7510_series.ppd.gz`). Thus it appears that somehow this is failing to be installed.

## Closing notes

I am happy to help contribute to fixing this! Though I would appreciate some minor guidance from those who have worked on hplip as I've worked on many things in my career but never with printer drivers.

Thanks,
Ferris

## Reference notes:

1. [http://hplipopensource.com/hplip-web/models/photosmart/photosmart_7510_series.html](http://hplipopensource.com/hplip-web/models/photosmart/photosmart_7510_series.html))
2. [https://github.com/NixOS/nixpkgs/blob/17.03/pkgs/misc/drivers/hplip/default.nix#L13](https://github.com/NixOS/nixpkgs/blob/17.03/pkgs/misc/drivers/hplip/default.nix#L13)
3. [https://sourceforge.net/projects/hplip/files/hplip/3.16.5/](https://sourceforge.net/projects/hplip/files/hplip/3.16.5/)

**Comment by emmanuelrosa** [comment]
Have you tried adding the hplip package to `services.printing.drivers` instead of `environment.systemPackages`? Here's an example:

```
# Enable CUPS to print documents.
  services.printing.enable = true;
  services.printing.drivers = [ pkgs.hplip ];
```

**Comment by code-ape** [comment]
@emmanuelrosa That did the trick! Thank you so much :) as a final question, is this documented somewhere that I totally missed? I did read through the Nix guide and the package before posting this.

**Comment by emmanuelrosa** [comment]
Well... sort of. There's documentation for NixOS configuration options: https://nixos.org/nixos/options.html#printing

If it were documented outright it would be in the [NixOS](https://nixos.org/nixos/manual/) manual since CUPS is a service, so it's at the OS level.

Roughly speaking, the Nix manual covers the Nix language and the tooling, such as `nix-build`. The Nixpkgs manual covers the packages, including abstractions reused by throughout the packages, such as functions for fetching sources from Github, and tools like `cabal2nix`. The NixOS manual covers installation, configuration, and maintenance of the OS, so things like the kernel and services. It takes a little while to figure out what is what :)

**Comment by olejorgenb** [comment]
Would've been helpful if print drivers was collected in attribute set like eg. `dictdDBs`. Then the `printing.drivers` documentation could refer to that set.

@code-ape btw: I think you need  `services.avahi.publish.userServices = true` also to get auto discovery to work (When I did that firefox crashed on opening the print dialog though. Could've been something else ofc.)

Close this issue if things worked out?

Can this

**Comment by emmanuelrosa** [comment]
I like that idea @olejorgenb . The print drivers can then be set with something like...

`services.printing.drivers = with pkgs.printingDrivers; [ hplip splix ];`

If I'm understanding this correctly, since the set --say it's called `printingDrivers`-- would contain package references, the `services.printing.drivers` option can remain unchanged, and therefore backwards compatible. So this improvement would involve:

1. Identifying the existing printing driver packages.
2. Creating a top-level set with references to these drivers.
3. Updating the  `services.printing.drivers` option documentation.

If there's a Nix function to map over the attribute names in a set, then it would be great to either list the available drivers in the NixOS documentation, or document a Nix expression that when executed would produce such a list. Since I don't think there's a way to do that right now other than searching through all the packages for just the right keywords.

**Comment by olejorgenb** [comment]
@code-ape close this?

**Comment by code-ape** [comment]
Yeah, I've got things working and it seems like some productive conversation came out of this. If a future issue opens up to implement the discussed changes I'm happy to contribute! Thanks everyone for the time and help :)
