### ISSUE TITLE
`julia.withPackages` fails to build environment

### ISSUE THREAD

**Issue by fedeinthemix** [NixOS/nixpkgs#277410]
### Describe the bug
I'm trying out the new Julia framework, but the following command fails

```julia
$ nix shell --impure --expr 'with builtins.getFlake "nixpkgs"; with legacyPackages.x86_64-linux; julia.withPackages [ "Plots" "DifferentialEquations" ]'
error: builder for '/nix/store/y5y63m7whs5pxzqcigm6nj0iz9lx0akp-applegpu.drv' failed with exit code 1;
       last 3 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/cp5zsbi316a2229cwkj3cdz7hs1ra1fb-0e3a4a2d471b489026684f506c83386581ddb112
       > do not know how to unpack source archive /nix/store/cp5zsbi316a2229cwkj3cdz7hs1ra1fb-0e3a4a2d471b489026684f506c83386581ddb112
       For full logs, run 'nix log /nix/store/y5y63m7whs5pxzqcigm6nj0iz9lx0akp-applegpu.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-FFMPEG.drv-0/lib': Directory not empty
error: 1 dependencies of derivation '/nix/store/bhfviyc86iwp18cdg98503dzk1j6y1b4-Overrides.json.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4nl70bzn0a4jn2jifpr27m2sjk6bbs05-julia-1.9.4-env.drv' failed to build
```
Am I doing it wrong?

If I only ask for the "Plots" package it works.

### Notify maintainers

@thomasjm @NickCao 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.2217.d02d818f22c7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(beffa): `""`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arthsmn** [comment]
Are you doing any overrides?

**Comment by thomasjm** [comment]
Hmm, this is arising from a Julia artifact in `Metal.jl` here:

https://github.com/JuliaGPU/Metal.jl/blob/73be9703eb52cf8c663cb5a62c59412cbb1f88ca/Artifacts.toml#L6

The artifact URL is given as

```
https://github.com/dougallj/applegpu/tarball/0e3a4a2d471b489026684f506c83386581ddb112
```

The Nix code we generate as part of the Julia machinery looks like this:

```nix
stdenv.mkDerivation { 
  src = fetchurl {                                                                                                                                                                      
    url = "https://github.com/dougallj/applegpu/tarball/0e3a4a2d471b489026684f506c83386581ddb112";                                                                                      
    sha256 = "473fa9146380574a781ba8a40138e3354d397364ccce5a8ec01ea31773c85595";                                                                                                        
  };
  ...
}                                                                                                                                                                                    
```

The URL seems to be valid. The problem seems to be that it doesn't end in `tar.gz`. So the Nix derivation downloads it, but doesn't unzip or untar it, which is why we run into a problem in the `unpackPhase`.

I'm thinking we need to stick a `name` into the `fetchurl` call. I'll try this in a bit.

**Comment by thomasjm** [comment]
> I'm thinking we need to stick a `name` into the `fetchurl` call.

This works for this example if I add a name ending with `.tar.gz`. The problem, of course, is that Julia artifacts are not necessarily tarballs, but can be arbitrary files.

I think what we need to do is parse the artifact URL and determine if it's an archive that the default `unpackPhase` knows how to handle. If so, we keep using the current derivation, and otherwise replace it with a plain `fetchurl` call. Per the [Nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#ssec-unpack-phase), the supported archive extensions are:

* `.tar.gz`
* `.tgz`
* `.tar.Z`
* `.tar.bz2`
* `.tbz2`
* `.tbz`
* `.tar.xz`
* `.tar.lzma`
* `.txz`
* `.zip` ?

The manual may not perfectly match the actual code; the relevant part of the default `unpackPhase` is [here](https://github.com/NixOS/nixpkgs/blob/59fa082abdbf462515facc8800d517f5728c909d/pkgs/stdenv/generic/setup.sh#L1044).

**Comment by fedeinthemix** [comment]
> Are you doing any overrides?

No

**Comment by fedeinthemix** [comment]
Unfortunately I've found another failing case, unrelated to the previous (it fails with PR #277618)
```julia
nix run --impure --expr 'with import ./. {}; (julia_19.withPackages [ "ImageView" "Images" "TestImages" ])'
error: builder for '/nix/store/vwpfy2kwyyf6nk2bifvpc06yb55khzwq-julia-depot.drv' failed with exit code 1;
       last 10 log lines:
       >  [3] precompile(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
       >    @ Pkg.API /nix/store/948q7s8iyrdccpqvi6z785njabcjd204-julia-1.9.4/share/julia/stdlib/v1.9/Pkg/src/API.jl:156
       >  [4] precompile(pkgs::Vector{Pkg.Types.PackageSpec})
       >    @ Pkg.API /nix/store/948q7s8iyrdccpqvi6z785njabcjd204-julia-1.9.4/share/julia/stdlib/v1.9/Pkg/src/API.jl:145
       >  [5] precompile(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
       >    @ Pkg.API /nix/store/948q7s8iyrdccpqvi6z785njabcjd204-julia-1.9.4/share/julia/stdlib/v1.9/Pkg/src/API.jl:171
       >  [6] precompile()
       >    @ Pkg.API /nix/store/948q7s8iyrdccpqvi6z785njabcjd204-julia-1.9.4/share/julia/stdlib/v1.9/Pkg/src/API.jl:162
       >  [7] top-level scope
       >    @ none:21
       For full logs, run 'nix log /nix/store/vwpfy2kwyyf6nk2bifvpc06yb55khzwq-julia-depot.drv'.
error: 1 dependencies of derivation '/nix/store/071dfr0s9x559m88xy0yglra24w4ps80-julia-1.9.4-env.drv' failed to build
```
It fails to build `ImageView`, likely for the reason I reported in PR #225513

**Comment by fedeinthemix** [comment]
Hi @NickCao, should I open another issue for `ImageView`?

**Comment by NickCao** [comment]
Or just reopen this one and use it as a tracker for future issues?

**Comment by fedeinthemix** [comment]
Let's reopen this one for the known issues.

**Comment by thomasjm** [comment]
This `ImageView` problem is due to the upstream `Gtk.jl` issue where it can't precompile in a headless environment, as discussed originally in #225513. It's also mentioned in the [docs](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/julia.section.md#arguments-julia-withpackage-arguments). The workaround is to use `precompile = false`.

Maybe we could open a Nixpkgs issue to track the upstream issue, but I view this primarily as an upstream problem.

**Comment by fedeinthemix** [comment]
You are right, I forgot about the workaround. Disabling pre-compilation works indeed.
