### ISSUE TITLE
Get rid of grub timeout

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#2776]
_Just collecting opinions for now._

This is based on a recent thread about `GRUB_HIDDEN_TIMEOUT`. So, basically, grub can do two kinds of timeout: menu timeout, and “hidden” one. This “hidden” timeout thing is just `sleep --interruptible` before displaying the menu (this will show a black screen letting you hit any key to get to the menu).

Currently NixOS grub module implements only ordinary timeout. I'd like to suggest to do what I have in all my grub configs (except for the box running NixOS) instead. Get rid of timeouts at all and put this instead:

    if keystatus --shift ; then
        set timeout=-1
    else
        set timeout=0
    fi

That is, if you are holding shift during boot, show menu right away (and do not choose any entry automatically). If you are not holding shift, just boot the default entry.

To be extra safe (according to grub manual, not all devices support key status detection, for some reason):

    if keystatus ; then
        if keystatus --shift ; then
            set timeout=-1
        else
            set timeout=0
        fi
    else  # key status detection is not possible
        set timeout=5  # fallback default, might be adjustable
    fi

So, what do you guys think?

**Comment by garbas** [comment]
I'm :-1: for this but let me explain it why:

 - biggest impact on the product's UX have the defaults, and we need to be very careful what we choose to select. while we should follow the rule of ``implicit is better then explicit`` we also need to account that too much of implicitness (if that is even a word) makes things harder to change, thus makes them harder to use in products like NixOS where want others to change/configure things.

 - expecting users to read the documentation is a very good sign that your UX sucks. eg. would you read the guide how to use bus/metro system in Berlin or would you like to be guided and explore how to use as you're using it?

 - please please please open a PR with making grub configurable in the way you describe while still preserving current default. you can mention me in the PR and i would love to merge that.

i'm closing this issue since it is quite some time since it has been open and i just suggested a way forward. thank you all.

**Comment by fricklerhandwerk** [comment]
@kirelagin "Some reason" is that UEFI does not report modifier key state. See [this bug ticket](https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/425979) and [a recent comment](https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/425979/comments/37).

A patch should therefore try to take into account if the system boots with UEFI.

**Comment by mightyiam** [comment]
[This](https://github.com/mightyiam/infra/commit/8473a1a9d1528759ce10c7377df0949b316debfd) is pretty much all it takes, but note that this does not cause GRUB to never show its ugly face during boot. I don't think that's supported by current options. At least not when EFI support is enabled (didn't try otherwise).

**Comment by mightyiam** [comment]
Also, I noticed that on one PC I had to disable fast boot in the firmware settings for the Shift to be detected on time. And on a different PC I couldn't get the Shift to be detected.
