### ISSUE TITLE
snapper: DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#27787]
## Issue description

I tried to use snapper but get an error.

### Steps to reproduce

```
nix-env -iA nixos.snapper

[root@nixos:~]# btrfs subvolume list /data
ID 258 gen 11 top level 5 path media
ID 259 gen 11 top level 5 path archiv
ID 260 gen 11 top level 5 path backup
ID 261 gen 12 top level 5 path upload

[root@nixos:~]# ll /data/
total 0
drwxr-xr-x 1 root root    0 Jul 31 04:44 archiv
drwxr-xr-x 1 root root    0 Jul 31 04:44 backup
drwxr-xr-x 1 root root    0 Jul 31 04:44 media
drwxr-xr-x 1 root root 1384 Jul 31 04:59 upload

[root@nixos:~]# snapper -c archiv create-config /data/archiv/
Failure (org.freedesktop.DBus.Error.ServiceUnknown).
```

Do i have to wait until https://github.com/NixOS/nixpkgs/pull/27154 lands in stable?

/cc @nckx @ck3d 

## Technical details

* System: NixOS 17.03.1621.0590ecbe9e (Gorilla)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: "17.03.1621.0590ecbe9e"
* Sandboxing enabled: build-use-sandbox = false

**Comment by ck3d** [comment]
You need the NixOS integration, otherwise snapper service is not started.
If you want to try snapper in NixOS, import the _nixos/.../snapper.nix_ from master and configure it as described in that module. 
Keep in mind, every subvolume needs an additional subvolume called _.snapshots_ and the builtin configuration modifications command like create-config are not needed nor possible (immutable configs).

**Comment by davidak** [comment]
@ck3d Thank you!
