### ISSUE TITLE
Ruby 3.1.2 broken when using ca-derivations

### ISSUE THREAD

**Issue by j-baker** [NixOS/nixpkgs#278334]
### Describe the bug

I'm aware that ca-derivations is experimental. I'm finding that on 23.11, Ruby does not compile with ca-derivations enabled.

### Steps To Reproduce

Steps to reproduce the behavior: Build ruby with `nixpkgs.config.contentAddressedByDefault = true`. Get 

```
error: build of '/nix/store/dpbvdh8pflzhkwkmjq92zmy85awq4jaw-ruby-3.1.4.drv' on 'ssh-ng://helcache@i-01bfd4ac504a8b1f0.eu-west-1.compute.internal' failed: derivation contains an illegal reference specifier '/0i99q8f7j8dv45qvbx1issri3v1w08z2mkhn5pv23i626zy2r029'
```

in return.

### Expected behavior

Either Ruby has CAD disabled or passes.

### Notify maintainers

@vrthra @manveru @marsam

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by marsam** [comment]
Would you mind testing whether https://github.com/NixOS/nixpkgs/pull/258705 fixes the Ruby ca-derivation?

**Comment by pillowtrucker** [comment]
jfc is it totally deranged how this is meant to be tested
https://github.com/pillowtrucker/computer-nixos/commit/4afe14d1aa039470cbed45b37f6128f4ace72650 I /think/ I figured out how to overlay this, because naturally the normal ruby = coolpackages.ruby didn't work. It's building now and I'll let you know in the morning if it worked, because it is the last 500+ packages that I have to rebuild to enable contentAddressedByDefault, but probably yes, since it didn't immediately implode.

**Comment by pillowtrucker** [comment]
works for me
