### ISSUE TITLE
Instructions for generating hashed passwords for mosquitto are incorrect

### ISSUE THREAD

**Issue by richardlarocque** [NixOS/nixpkgs#27996]
## Issue description

The documentation for `services.mosquitto.users.<user>.hashedPassword` states:
> To generate hashed password install mkpasswd package and run mkpasswd -m sha-512.

I believe this is incorrect.  The output of this hash function appears to be different than what is generated by `mosquitto_passwd` and incompatible with the mosquitto daemon.  At least, the mosquitto daemon seems to not accept any passwords that were configured this way.

However, passwords generated with `mosquitto_passwd` seem to work just fine.

Note that this issue becomes apparent only when a separate issue, https://github.com/NixOS/nixpkgs/issues/27130, is fixed.  Without that fix, the server performs no password validation, so passwords generated with `mkpasswd` (or even `/dev/random`) would appear to work just fine.

### Steps to reproduce

- Apply a fix for https://github.com/NixOS/nixpkgs/issues/27130.  The easiest to apply at the time of this writing is to add
```
services.mosquitto.extraConf = "password_file /var/lib/mosquitto/passwd";
```
- Use `mkpasswd` as directed to generate a hashed password and put it in your NixOS configs.  Rebuild.
- Verify that `mosquitto_pub -u youruser -p yourpassword -t 'foo' -m 'bar'` fails for authentication reasons.

Then try again using `mosquitto_passwd` to generate your password and notice the `mosquitto_pub` starts to work.

## Technical details

* System: NixOS 17.03
* Nix version: 1.11.8

**Comment by cprussin** [comment]
:wave: @Mic92 @richardlarocque not sure if this is important to ya'll but I recently butted up against this, because `mosquitto_passwd` is pretty awful to use when generating the hashed password problematically from some cli password manager (as it doesn't take stdin orstdout and so you have to deal with writing a temp file and cleaning it up & securing it & parsing it & etc).

I figured there had to be a better way, and it turns out that `mkpasswd -m sha-512` works just fine, you just have to suffix the output with `==`.  i.e.:

```sh
echo mypasswd | mkpasswd -m sha-512 -s | sed 's/$/==/'
```

Let me know if ya'll think a note about this is appropriate in nixpkgs and I'll be happy to open a PR to add it.

**Comment by Mic92** [comment]
How about this?

```
$ echo test | mosquitto_passwd -c -b passwd test /dev/stdin
```

**Comment by cprussin** [comment]
@Mic92 

```
$ echo test | mosquitto_passwd -c -b /dev/stdin passwd test
Error: -c argument given but password file or username missing.

$ echo test | mosquitto_passwd -b -c /dev/stdin passwd test
Error: -b argument given but password file, username or password missing.
```

I don't see any indication that there's any way to use `mosqitto_passwd` on stdin/stdout correctly.
