### ISSUE TITLE
[RFC] Idea: separate directory for each node package instead of  using single `node-packages.nix`

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#28009]
A single package add to `pkgs/development/node-packages/node-packages-v6.json` (and/or `node-packages-v4.json`) produce large diff of following files

    pkgs/development/node-packages/node-packages-v4.nix
    pkgs/development/node-packages/node-packages-v6.nix

for some example, see #23771 #25770 #26018

I have this idea while try to install `jsonlint` (#27952)

* create a new directory
* create `default.nix` using `node2nix`

    $ echo '["jsonlint"]' > in.json && node2nix -i in.json
    info attempt registry request try #1 at 6:14:48 PM
    http request GET http://registry.npmjs.org/jsonlint
    http 200 http://registry.npmjs.org/jsonlint
    --truncated--

* build `default.nix`

    $ nix-build -A jsonlint
    /nix/store/6rcbjvrqrq0ybqdjyrhzp68wdxyp3xiv-node-jsonlint-1.6.2

    $ ./result/bin/jsonlint --version
    1.6.2

---

I think this work flow might be able to adapt but I don't really sure if it is possible.

Instead of using `pkgs/development/node-packages/generate.sh` to generate all node packages to single nix file; the output of process would be like this for `jsonlint`

    /nix/nixpkgs/pkgs/development/node-packages/jsonlint/default.nix

with `jsonlint = callPackage ...` declared in central `node-packages.nix`

---

Any idea?

**Comment by FRidh** [comment]
If I look at the diffs of the PR's you refer to I see more than just adding a single package. Many packages are updated as well and that makes sense: generated package sets should be regenerated regularly to gain the maintenance updates.

**Comment by therealpxc** [comment]
@FRidh I don't think that for most of those PRs, updating so many packages was intended or desired. With our Node packages, at least, the _only way_ to add a new package (the one described in the [README](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/README.md)) involves updating *all* of the packages in nodePackages. Sure, we want to update our generated packages regularly in order to get maintenance updates, but don't we want more control than that?

Another problem is that when a simple update (adding a package, even if it has no dependencies), generates a ton of other package changes, Nixpkgs project members sometimes get nervous about merging those commits. And for contributors, that amount of update churn on adding new packages means that every time one Node package is updated, all the other outstanding PRs adding or updating Node packages have to be rebased/regenerated and pushed again.

@svanderburg Node 8 is entering LTS in a few weeks and I think I saw that you're already working on some packaging infrastructure for it (updating `node2nix`, among other things). Do you know yet whether we'll get a nodePackages_8_x that works the same way as the others, or is this the time to shift away from having a single, giant, unified package set for Node?

(Sorry if this feels like piling on when you've already got that other work in front of you.)

**Comment by FRidh** [comment]
>  but don't we want more control than that?

Absolutely. Is it technically possible? I know in the case of Python (`pypi2nix`), it isn't, because PyPI and `pip` don't offer any means. How is that for Node?

**Comment by therealpxc** [comment]
Well, the thing I had in mind is something along [these lines](https://github.com/NixOS/nixpkgs/issues/13103#issuecomment-186148878) (as cited [here](https://github.com/NixOS/nixpkgs/issues/14532)), where we lose the global nodePackages for libraries, encourage users with their own projects to use`node2nix` or a similar tool to generate their own nodePackages sets. Then end-user Node applications (mostly command-line utilities), I guess, could live in Nixpkgs top-level.

But you'd be right to note that going that route also means giving some things up.

**Comment by matthewbauer** [comment]
So I think the root problem is that we are just not very good at keeping these things up to date. Adding more files like this will not improve that very much.

I think our best solution is automating the update scripts & having it run on something like Travis daily. See ryantm/nixpkgs-update#12 for discussion on this.

**Comment by wizzup** [comment]
Close reason: outdated
