### ISSUE TITLE
where to put a disk image registry?

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#28030]
This is a discussion, to determine where to maintain a registry of all the disk images nixpkgs can build. For example, we just added #28008 but it's just a file somewhere in the tree.

Would an attribute like `nixpkgs.diskImages` be sufficient?

/cc @copumpkin @alexandergall

**Comment by copumpkin** [comment]
I'm thinking we should have some sort of `lib` sub-hierarchy for various sorts of image-building functions, and then an `images` section of nixpkgs. I'd refrain from calling them "disk" images specifically due to Docker and certain other systems having a slightly more nebulous definition of what an image really is.

It might be slightly controversial to have a part of nixpkgs that depends on the NixOS hierarchy though? The point is that non-NixOS systems should be able to (and can; I do it all the time) build NixOS images. I'd also like us to stick our other images into that namespace, for what it's worth. Things like our Ubuntu and CentOS test images.

**Comment by wmertens** [comment]
That sounds good to me… maybe you can prototype it in a PR?

**Comment by wmertens** [comment]
The years have shown that this is not an important issue.
