### ISSUE TITLE
Package request: waveterm

### ISSUE THREAD

**Issue by yelircaasi** [NixOS/nixpkgs#280566]
waveterm

Modern open-source terminal emulator supporting inline rendering.

* homepage URL: https://www.waveterm.dev/
* source URL: https://github.com/wavetermdev/waveterm
* license: Apache-2.0
* platforms: linux, darwin

**Comment by raspher** [comment]
I've tried, got stuck at packaging waveterm with scripthaus. However i have packaged scripthaus which is required here.

Maybe someone with better understanding of nodejs will make it.

**Comment by ErnWong** [comment]
Here's my attempt at cobbling something together for linux, which seems to be working locally for me (well, it's "working" in the sense that it builds, the GUI shows up and the basic shell features seem to be working): https://github.com/ErnWong/dotfiles/blob/689d0fe8932a188f524c20bd8121fc3bfc8ce6ed/pkgs/waveterm/default.nix

```
nix shell github:ErnWong/dotfiles#waveterm --command waveterm   
```

I wasn't able to get it building using the provided scripthaus scripts yet, but I'm also quite inexperienced in this area so that could be why. I'm currently using `buildGoModule` and `mkYarnPackage` instead, basing it off from a bunch of other electron and go packages on nixpkgs. I haven't carried across all the build flags from waveterm's provided scripthaus scripts though, and you might also see some vestigial code that I copied from other packages that don't apply for waveterm which I haven't cleaned up yet. If I have time I might give the scripthaus scripts another try.

Some other remaining todos that I'm aware of include the desktop icon, getting it working on darwin, checking the AI features, checking that the package includes all the dependencies it needs at runtime, and fixing a failing test regarding command completions.

Please feel free to continue working off from what I have if it helps, especially if I don't get back to this soon.

**Comment by Marin-Kitagawa** [comment]
Waveterm offers a `.deb` packages. I was installing `Vivaldi` and noticed that it fetched a `.deb` package and installed it. Is it not possible to do the same? I also saw in this [Reddit post](https://www.reddit.com/r/NixOS/comments/bs4q2p/installing_deb_packages_in_nixos/) that `.deb` packages are pulled for Opera and Skype as well. So, is it possible to do the same for Waveterm as well?

**Comment by ElrohirGT** [comment]
Forced M1 user here, tried packaging wave but didn't manage to make the scripthaus scripts run without fails, mainly because both go and scripthaus try to create cache directories and I didn't manage to disable this behaviour.

I also tried to use @ErnWong package but due to it requiring electron and it not being available for the M1 architecture I couldn't compile the application from source, so I think packaging for the M1 will have to be done through the .dmg that they have on the realeases page. I'll try packaging the application when I have time this weekend.

**Comment by ElrohirGT** [comment]
In the end I couldn't resist and worked something out for M1 in my free time, this works and creates a ./result directory with an application I can open, so I think it's pretty much done. The only thing missing is integrating with @ErnWong solution... I'll try doing it this weekend.

```nix
# package.nix
{
  lib,
  fetchurl,
  stdenvNoCC,
}: let
  pname = "waveterm";
  info = lib.importJSON ./info.json;
  meta = tag-version: {
    changelog = "https://github.com/wavetermdev/waveterm/releases/tag/v${tag-version}";
    description = "An Open-Source, AI-Native, Terminal Built for Seamless Workflows";
    homepage = "https://github.com/wavetermdev/wavetermn";
    license = lib.licenses.asl20;
    mainProgram = pname;
    platforms = lib.platforms.unix;
  };

  darwin = let
    version = info.darwin.version;
  in
    stdenvNoCC.mkDerivation (
      finalAttrs: {
        inherit pname version;
        meta = meta version;

        src = fetchurl {
          inherit (info.darwin) hash;
          url = "https://dl.waveterm.dev/releases/Wave-darwin-universal-${version}.dmg";
        };

        sourceRoot = ".";

        unpackPhase = ''
          runHook preUnpack

          # Since the .dmg is using APFS we can't use undmg.
          # I also tried to use _7zz but it corrupts the .app.
          /usr/bin/hdiutil attach $src
          cp -r "/Volumes/Wave ${version}-universal/Wave.app" .
          /usr/bin/hdiutil detach "/Volumes/Wave ${version}-universal"

          runHook postUnpack
        '';

        installPhase = ''
          runHook preInstall

          mkdir -p $out/Applications
          cp -r *.app $out/Applications
          chmod +x $out/Applications/*.app

          runHook postInstall
        '';
      }
    );
in
  darwin
```

info.json
```json
{
  "linux": {
    "hash": "",
    "version": "0.7.6"
  },
  "darwin": {
    "hash": "sha256-b75eQnUteQ767+crVe+gWfBf7PrrEjoNFVTx8s/jTXM=",
    "version": "0.7.6"
  }
}
```

**Comment by eclairevoyant** [comment]
> due to it requiring electron and it not being available for the M1 architecture I couldn't compile the application from source

where did you get that info from?

**Comment by ElrohirGT** [comment]
When I searched for electron on Nix packages it never appeared a platform for darwin... I know it should be possible to have electron in M1 but at least on Nix it isn't packaged for it already.
<img width="313" alt="image" src="https://github.com/user-attachments/assets/b71b5acc-1006-4153-a72a-9d5da9a1eab4">

**Comment by eclairevoyant** [comment]
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=electron-bin

**Comment by ElrohirGT** [comment]
Oh, nice! I thought the panel with platforms displayed all of them, clearly it doesn't. I'll first merge the linux build mentioned previously and then I'll try using that electron to build the app from scratch. Thank you!
