### ISSUE TITLE
Use of `throw` in all-packages.nix breaks nix-build with almost no information given

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#28076]
In commit 25a3563102e2beeae64257671581c93a2ef6e4b0, the `activator` attribute was changed to:

```
  activator = throw ''
    Typesafe Activator was removed in 2017-05-08 as the actual package reaches end of life.

    See https://github.com/NixOS/nixpkgs/pull/25616
    and http://www.lightbend.com/community/core-tools/activator-and-sbt
    for more information.
  '';
```

This appears to completely break `nix-build`, as I get this exception no matter what I try to build, even though I'm not using the activator attribute anywhere. Further, when `throw` aborts `nix-build`, adding `--show-trace` gives no additional information about why I'm getting this error.

If I delete the `activator` attribute entirely, it fixes the problem, proving that I wasn't doing anything that actually needed the attribute value.  So, it seems that when `nix-build` goes to evaluate `all-packages.nix`, it encounters this throw and executes it, even though it's not a path that needs to be taken.

I see two aspects to this issue:

  - Using `throw` should not break `nix-build` on expressions that shouldn't be evaluating the throw.

  - If `throw` does occur, `--show-trace` should work, in order to find out why the throw is happening.

**Comment by copumpkin** [comment]
The only case in which I could see this happening is if your `nix-build` invocation is trying to build an attrset that includes all of our packages. Are you not passing `-A` into it, or is an attrset somehow sneaking into the thing it sees? If `nix-build` encounters an attrset it'll try to build derivations as keys, so if you're re-exporting nixpkgs somehow, you'll see the behavior.

As an example, I've been using `nix-build -A foo` against nixpkgs (it's my primary way of testing things I contribute) for ages since that `throw` appeared and it's never caused me issues.

**Comment by jwiegley** [comment]
I was using `nix-build "<nixpkgs>" gnustep-make` rather than `nix-build "<nixpkgs>" -A pkgs.gnustep-make`.  The latter works, the former gives that strange error.  Is the `-A` flag required for `nix-build` to work?

**Comment by jwiegley** [comment]
Before the `throw` change, it appears I would get:

```
error: assertion failed at /Users/johnw/.nix-defexpr/nixpkgs-next/pkgs/games/adom/default.nix:4:1
```

So I guess `nix-build` never worked without `-A`.
