### ISSUE TITLE
The default java version in nixpkgs is EOL and insecure.

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#280901]
### Describe the bug
The default version of jdk and jre [in nixpkgs](https://github.com/NixOS/nixpkgs/blob/46cf5e9bf1465b7c0b8bc63e0bc23aa8a47ecc7c/pkgs/top-level/all-packages.nix#L16455-L16458) is currently jdk19, but jdk19 is [EOL and deprecated](https://jdk.java.net/19/), the [github repository](https://github.com/openjdk/jdk19u) hasn't been updated in a year and is archived.
This also applies to jdk20, adoptopenjdk15, adoptopenjdk16, temurin-bin-16, temurin-bin-18, temurin-bin-19 and temurin-bin-20.

### Notify maintainers

 @edwtjo @taku0 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Tungsten842** [comment]
@mweinelt  @lheckemann @risicle @LeSuisse

**Comment by mweinelt** [comment]
Looping in people who did work on Java, because none of us have.

@thiagokokada @wegank @asbachb @whentze @Infinidoge

**Comment by Infinidoge** [comment]
Java seems to lack an active maintainer in Nixpkgs, which is a bit concerning. If someone doesn't beat me to it, I can make a PR to bump the default version.

**Comment by wegank** [comment]
> Java seems to lack an active maintainer in Nixpkgs, which is a bit concerning. If someone doesn't beat me to it, I can make a PR to bump the default version.

#273811 was already there and has probably been posted multiple times on https://matrix.to/#/#review-requests:nixos.org, I guess no one is confident enough to merge the PR...

**Comment by Infinidoge** [comment]
I really should join that Matrix channel. Will review when I get back to my computer.

**Comment by thiagokokada** [comment]
There is also JavaFX that is even more out of date and probably insecure. I made it optional so it is not used by default, but some derivations override it and they're also insecure because of this fact.

> Java seems to lack an active maintainer in Nixpkgs, which is a bit concerning. If someone doesn't beat me to it, I can make a PR to bump the default version.

Yes, bumping Java versions is really annoying nowadays and there is no active maintainer. There are many versions to keep track: all LTS versions (8, 11, 17 and 21), whatever versions that are not LTS but still have updates, and also mark as EOL deprecated versions.

I think creating an update script and having OfBorg update it could result in faster updates, but ideally we still need a proper maintainer for the times when updating the version needs more attention.

The issue of creating an update script though is that I never found a good way to get the GA versions, so I rely by manually going to AdoptiumJDK website and trying to match whatever version they have as release as the newest.

**Comment by thiagokokada** [comment]
> #273811 was already there and has probably been posted multiple times on https://matrix.to/#/#review-requests:nixos.org, I guess no one is confident enough to merge the PR...

This probably doesn't solve the issue because I am almost sure that our JDK21 derivation is also out of date.

OpenJDK project publishes a new fix release AFAIK every 3 months for all supported JDK versions, that generally includes bug fixes (and especially concerning, security fixes), so if JDK21 was not updated in the last 3 months it is still probably insecure.

**Comment by thiagokokada** [comment]
> There are many versions to keep track: all LTS versions (8, 11, 17 and 21), whatever versions that are not LTS but still have updates, and also mark as EOL deprecated versions.

Since we are already having this talk, I think considering the current situation maybe we should just mark all non-latest LTS versions as insecure. Something like `meta.knownVulnerabilities = [ "nixpkgs has no active maintainer for Java so only the latest LTS version is supported" ];`.

This way, at least every user will be aware they're using packages that are not up to date, and should someone interested in improving the situation come we can remove this warning.

**Comment by Infinidoge** [comment]
I'm going ahead and bumping all of the JDK versions right now. This might be how I become the OpenJDK maintainer in Nixpkgs lol

The older versions have their uses, so I'd rather put in the effort to update them every so often than mark them as insecure.

**Comment by thiagokokada** [comment]
Thanks @Infinidoge for your work in #286267.

This still leaves the question about what to do with JavaFX/OpenJFX that are also (probably) out of date. 

Considering they're much less used, would it make sense to mark them as insecure/unsupported for now, at least until someone with interest enough in them decides to adopt those packages?

**Comment by Infinidoge** [comment]
From the look of it, the JFX versions don't actually seem that out of date. I'll go ahead and bump all of their versions too, though, since it's easy to loop in with the JDK.

**Comment by Infinidoge** [comment]
Bumped the JFX versions in said PR. The versions for out of date JDK versions already fail to evaluate because those JDK versions are marked with known vulnerabilities.

**Comment by Tungsten842** [comment]
I'm closing this in favor of https://github.com/NixOS/nixpkgs/issues/313216
