### ISSUE TITLE
Package request: dnss

### ISSUE THREAD

**Issue by devvythelopper** [NixOS/nixpkgs#281194]
**Project description**

forwards dns over https queries to normal dns servers and vice versa.

**Metadata**

* homepage URL: https://blitiri.com.ar/git/r/dnss/b/master/t/f=README.md.html
* source URL: https://github.com/albertito/dnss
* license: apache 2.0
* platforms: unix, linux, darwin, ...
* ubuntu package url: https://packages.ubuntu.com/jammy/dnssu

**Comment by raspher** [comment]
@devvythelopper Upstream has system services, but no release or tag has been published yet. Is there a need to include these modules (services) within this package? I would prefer not to include them if there is no need, because `ddns` is not actively developed and has not released a single stable version yet.

**Comment by devvythelopper** [comment]
I personally don't need them, because I prefer creating systemd services via nix configuration anyways.
