### ISSUE TITLE
gnome.anjuta redirects to a gambling site

### ISSUE THREAD

**Issue by AbrA-K** [NixOS/nixpkgs#281336]
If my sources are correct, the Project was archived in 2022 and the link for the Hompage now redirects to an indonesian gambling site.
Linking to the [GitHub repo](https://github.com/weynhamz/GNOME-anjuta) could be better, but the Homepage link (on mentioned repo) also links to the gambling site.

**Comment by ncfavier** [comment]
@NixOS/gnome

**Comment by jtojnar** [comment]
The github repo does not look official. That would be https://gitlab.gnome.org/Archive/anjuta/.

**Comment by amaxine** [comment]
Considering the archived repo also links to the lapsed domain that now redirects to a gambling site, I'd be in favour of removal. However, that will also necessitate the removal of `gtkpod`, which hasn't seen any updates since 2015. Neither has any maintainers, so I don't think the removal is likely to be objected to.
