### ISSUE TITLE
pkgs.gradle cannot be used as Gradle distribution in IntelliJ IDEs

### ISSUE THREAD

**Issue by msfjarvis** [NixOS/nixpkgs#281637]
### Describe the bug

The IntelliJ family of IDEs allows to specify a local installation of Gradle as the source of the build tool for the IDE in place of the usual `gradlew` wrapper script (screenshot is with a patched Gradle):

<details>
<summary>Screenshot</summary>

![image](https://github.com/NixOS/nixpkgs/assets/13348378/ccdf079c-3ae7-41a9-b6fc-424ef8fe1222)

</details>

This option rejects the store path of the Gradle package from NixOS but works correctly with an extracted copy of the upstream Gradle distribution.

### Steps To Reproduce

1. Install `androidStudioPackages.stable` and `gradle_8`
2. Open any Android project in Android Studio
3. Press Ctrl + Shift + A, search for "Change Gradle JDK location"
4. Change Gradle distribution to local, paste in the store path for `pkgs.gradle_8` and observe the error.

### Expected behavior

The IDE should be able to use Nix' packaged Gradle.

### Additional context

To validate the distribution path, IntelliJ invokes [this method](https://github.com/JetBrains/intellij-community/blob/de73f4976750b11c3dcd8cc81d9a45afac3f401d/plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/LocalGradleExecutionAware.kt#L73) and ultimately the part that fails is [this method](https://github.com/JetBrains/intellij-community/blob/de73f4976750b11c3dcd8cc81d9a45afac3f401d/plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/LocalGradleExecutionAware.kt#L199), which tries to locate [`lib/gradle-core-x.y.jar`](https://github.com/JetBrains/intellij-community/blob/de73f4976750b11c3dcd8cc81d9a45afac3f401d/plugins/gradle/src/org/jetbrains/plugins/gradle/service/GradleInstallationManager.java#L79) and bails if it does not.

The decision to hoist Gradle's dependencies in a separate `gradle` directory seems to have been made [here](https://github.com/NixOS/nixpkgs/commit/4dde32b4f240cb68ba7455bcf98c25749fd0235e) but I don't know if it holds true today. I [fixed the paths](https://github.com/msfjarvis/nixpkgs/commit/50362d42a196c096b7ec211fafaae0eff2e925ea) in my nixpkgs fork and the resultant Gradle derivation works fine.

### Notify maintainers

@lorenzleutgeb @liff

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.0, NixOS, 24.05 (Uakari), 24.05.20240117.50362d4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.2`
 - nixpkgs: `/nix/store/n0zy8vpmyvkjl1bn32inx8l1xif2yqb8-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by liff** [comment]
I think the reason for placing the JARs in `lib/gradle` is that, when you add Gradle to your `environment.systemPackages`, the contents of its `lib` directory are linked to the global `lib` of the current system. Specifically, you’d find symlink `slf4j-api-1.7.30.jar` (among others) directly in `/run/current-system/sw/lib`. That might be mostly fine if there are no conflicts, but it’s kind of like installing the Gradle’s libraries directly to `/usr/lib` in a more traditional FHS-based distro.

Instead of using the store path directly, you could tell the IDE to use:
 - `/run/current-system/sw/lib/gradle/lib` if installed via `environment.systemPackages`,
 - `/etc/profiles/<your-username>/lib/gradle/lib` if installed via `users.users.<your-username>.packages` or
 - `~/.nix-profile/lib/gradle/lib` or `~/.local/state/nix/profile/lib/gradle/lib` if installed via `nix-env` or `nix profile`
as path to Gradle.

Using one of those also means that you won’t need to update the installation location if the hash changes and you run a garbage collection.

**Comment by msfjarvis** [comment]
`/etc/profiles/per-user/$USER/lib/gradle` seems to do the trick, thanks for the tip.
