### ISSUE TITLE
glibc is not visible

### ISSUE THREAD

**Issue by david-varela** [NixOS/nixpkgs#28234]
## Issue description
Installing glibc has no effect no the ~/.nix-profile directory. I'm new to Nix, so I apologize in advance if I am misunderstanding the expected behavior: I would expect ~/.nix-profile/inlcude and ~/.nix-profile/lib to be updated with the proper files, but they don't appear to change at all. (As context, I am trying to get clang and lld to compile a c program using only packages on nixpkgs)

### Steps to reproduce
I ran `nix-env -i glibc` to install the package. It seems to have installed glibc version 2.25 from the nixpkgs repo.

## Technical details
I'm running Nix version 1.11.13 on a fresh install of debian stretch.

**Comment by vcunat** [comment]
That's intentional.  If you want a developing environment, you probably want `nix-shell -p dep1 dep2`, possibly also with `--pure` (depending on your taste).

These questions are probably not suitable as github issues.  I'd recommend our IRC for more interactive help; otherwise perhaps stackoverflow and the mailing list ([links](https://nixos.org/nixos/community.html)).  You can certainly find lots of howto/tutorial-like text by simple searching...

**Comment by david-varela** [comment]
Ok, that makes sense. Thanks for the advice! I'll keep it in mind in the future.
