### ISSUE TITLE
rmg: License Violation

### ISSUE THREAD

**Issue by orbea** [NixOS/nixpkgs#282736]
### Describe the bug
There is a license violation in the [rmg](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name/rm/rmg) package.

### Additional context
The package contains the code for [mupen64plus-video-angrylion-plus](https://github.com/Rosalie241/RMG/blob/master/Source/3rdParty/mupen64plus-video-angrylion-plus/MAME%20License.txt) under the old MAME license which is non-commercial and incompatible with the GPL code in the rest of the program.

I tried to notify upstream, but that didn't seem to go well...

https://github.com/Rosalie241/RMG/issues/215

### Notify maintainers

@slam-bert

**Comment by slam-bert** [comment]
Hello! It seems that upstream actually added an option to disable `angrylion-plus` in `>=0.5.6` version of `rmg`.

`rmg-0.5.6`, from my testing, gives me an error when I try to run it. You can find more info in this [pull request](https://github.com/NixOS/nixpkgs/pull/284124). So, i think merging the pull request linked to this issue is the best option right now.
