### ISSUE TITLE
Ruby gems pull in gcc as runtime dependency

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#28283]
## Issue description

Some ruby gems have a compiled component which requires gcc and libffi, but they will retain a *runtime* dependency on gcc as well.

I am not sure if this is a nixpkgs or bundix issue.

Cc: @manveru @cstrahan

### Steps to reproduce

1. Deploy ```sensu-client```  with nixops to any host
2. Notice the presence of gcc

## Technical details

* NixOS: 17.09.git.d7adff9938M (Hummingbird)
* Nix: nix-env (Nix) 1.11.13
* nixpkgs: 17.09.git.ffc06685a4M
* Sandboxing enabled:  true

**Comment by manveru** [comment]
Well, you can still use the `gem` command in ruby, which is also used by `bundle`, and that needs access to a compiler to build gems. Right now there's no real distinction between a "production" and "development" ruby, but might be worth providing an option for it, since we already have quite a few options to make the closure smaller.
I'll look into this, since it would be really neat for smaller docker images.

**Comment by manveru** [comment]
OK, after trying a few things, it seems like the root issue is that compiled extensions aren't being stripped. Additionally if you depend on `nokogiri` for example, it pulls in python by default, which also depends on `gcc`.
In your case you can try adding the line `dontStrip = false;` to your `gemset.nix` for the gems that have extensions.
For the time being I think there needs to be a flag in bundix that adds those lines to all gems, but I need to make sure that doesn't have negative consequences.

Ideally it'd be a flag in `bundlerEnv` instead, so it's more DRY and easier to use the same `gemset.nix` for production and development.

For an easy test case of building a docker image with nokogiri/libxslt without python and stripped binaries, i got an image size of 28M instead of 105M (compressed). The uncompresed nix directory went from 296M to 102M. So I definitely think this is worth some effort.

@zimbatm any thoughts?

**Comment by peterhoeg** [comment]
Still an issue.
