### ISSUE TITLE
Haskell: Nonsensical paths are generated into setup-config

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#28301]
## Issue description

I just had a look at a `dist/setup-config` file generated by `cabal configure` or equivalent `Setup.hs` call, and it contains things like this:

`^@^@^@^@^@^@^@;/nix/store/66znhpqvqyvhgw4wxpl1f2rlfpqrbcsd-lz4-131/bin/tar^@^@^@^@^@^@^@A/nix/store/vmisgqfbqywgsw9php70bbx90czr398i-openssh-7.4p1/bin/tar^@^@^@^@^@^@^@?/nix/store/cjpyvkqqd55s8jgj7c2qv9wwmisw5ayg-rsync-3.1.2/bin/tar^@^@^@^@^@^@^@=/nix/store/2m6v6lnmnf9521ixd5v0x4qrmjkn30ws-gcc-5.4.0/bin/tar`

The same thing happens for `tar`, `alex`, `happy` etc, so I suspect that this is about build-tools called during haskell builds.

The N*M combination of executables and paths they are in isn't anything new when it comes to `stat()`ing or `execve()`ing binaries, but it seems totally nonsensical to me that such paths would be written to a file (this also seems to blow up the file size of `setup-config` quite a bit, e.g. mine is 1.6 MB large).

Not sure if this is a nixpkgs or a cabal bug (I suspect the latter but I haven't found out what happens in detail yet).

@peti

**Comment by mdorman** [comment]
So that file is generated by the cabal library.  Given that fact---as well as looking at a freshly generated one, which seems to have plenty of redundancy that has nothing at all to do with paths!---I'm uncertain how this is a nixpkgs bug?

**Comment by nh2** [comment]
@mdorman The generic Haskell builder passes all kinds of flags to Cabal. It is not clear to me whether it passes some wrong/unnecessary flags in this case, or if it passes the right ones but Cabal does the wrong thing with them.

**Comment by peti** [comment]
The generic builder doesn't pass any flags to Cabal that aren't required to make the build succeed. Generally speaking, I don't see any indication that this issue is caused by Nix or the way it builds Haskell packages. I certainly don't see any reason why Cabal would need to record every $PATH entry for ever possible tool it tries to find in $PATH, which is what seems to be happening. IMHO, the proper way to get to the bottom of this is to read the Cabal source and to find out why it's recording those paths, and that seems to be outside of the scope of this issue tracker.

**Comment by nh2** [comment]
OK. I had hoped that some Nix+Cabal user here might know what's going on. But I've now filed the upstream cabal bug: https://github.com/haskell/cabal/issues/4726
