### ISSUE TITLE
QtPass not prompting for gpg password

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#28335]
## Issue description

Update Nixos Unstable yesterday and since then QtPass isn't working properly anymore. It will display all stored sites/entries just fine, but when selecting one, the GPG password entry won't appear - hence nothing being displayed.

pass on the cli still works fine.

### Steps to reproduce

Switch to Nixos-Unstable channel
Install QtPass
Add a few sites (through the cli)
Try to see them in QtPass

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.09pre112899.129f8d7e99 (Hummingbird)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.13

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.09pre112899.129f8d7e99"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

build-use-sandbox = false

**Comment by rasendubi** [comment]
@sjau would you like to git-bisect to find the first err commit?

**Comment by sjau** [comment]
No idea how to do that.

**Comment by rasendubi** [comment]
Here is an example of how to use git bisect: http://webchick.net/node/99

Basically, you can checkout nixpkgs. Your current nixpkgs revision is `bad`, while your previous one (before you have updated the channel) is `good`. Then you can do a binary search to find the first commit that introduced the break (git bisect will guide you through the process).

On every bisect stop, you should check whether qtpass works or not and mark it with either `git bisect good` or `git bisect bad`.

You can verify the package in a next way: execute `nix-build -A qtpass` to build the qtpass, then run `./results/bin/qtpass` and check if the bug is present.

**Comment by bjornfor** [comment]
FYI, recently Qt apps on nixpkgs master started looking for some dependencies in $PATH. So running directly from the store (./result/bin/qt-application) may not work properly. Rather, the application must be _installed_ with nix-env to work.

**Comment by sjau** [comment]
Still not working in current unstable.

**Comment by sjau** [comment]
Working again in current unstable small.

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

`18.03pre118082.00e56fbbee (Impala)`

* Nix version: (run `nix-env --version`)

`nix-env (Nix) 1.11.15`

* Nixpkgs version: (run `nix-instantiate --eval "<nixpkgs>" -A lib.nixpkgsVersion`)

`"18.03pre118082.00e56fbbee"`

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

`build-use-sandbox = false`
