### ISSUE TITLE
Update request: criterion 2.4.1 → 2.4.2

### ISSUE THREAD

**Issue by simonhollingshead** [NixOS/nixpkgs#283639]
- Package name: criterion
- Latest released version: 2.4.2

- Current version on the unstable channel: 2.4.1
- Current version on the stable/release channel: 2.4.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Thesola10 @Yumasi 

r-ryantm is failing to update the package because it now also depends on something called 'debugbreak'.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinpox** [comment]
The missing `debugbreak` is here: https://github.com/scottt/debugbreak (linked in the README.md of criterion)

**Comment by Sigmanificient** [comment]
I try to update it, but i wasn't successful.
Here is more information for anyone willing to give it a shot:

- criterion 2.4.2 hash: `sha256-5GH7AYjrnBnqiSmp28BoaM1Xmy8sPs1atfqJkGy3Yf0=`

- fetching `debugbreak` and `klib`
```nix
debugbreak = fetchFromGitHub {
  owner = "scottt";
  repo = "debugbreak";
  rev = "v1.0";
  sha256 = "sha256-lFMBSbA4mwAgW/+T+G1pfrwYjcZFuoKr6t8JYMB65Yw=";
  name = "debugbreak";
};
```

```nix
klib = fetchFromGitHub {
  owner = "attractivechaos";
  repo = "klib";
  rev = "2895a16cb55ee86152e5a4ee1403265342e40caf";
  sha256 = "sha256-AfeDouazTfh6ilf3miQeihqqm1SYHJks7fjgpyYJszE=";
  name = "klib";
};
```

Both do not have associated `pc` files, and since they do not build into shared object:

- setting `PKG_CONFIG_PATH` will not work for them
- setting `LIBRARY_PATH` wont help to solve dependencies either
- setting `--libdir` in `mesonFlags` is also not a solution
- there is *likely* not need to make a derivation for them
