### ISSUE TITLE
tailscale: Fails to detect nftables firewall mode

### ISSUE THREAD

**Issue by stackcoder** [NixOS/nixpkgs#285676]
### Describe the bug

Tailscale fails to detect firewall backend using default [heuristic mode](https://tailscale.com/kb/1294/firewall-mode#firewall-mode-heuristic). The NixOS Wiki also describes [switching to nftables](http://web.archive.org/web/20240202001755/https://nixos.wiki/wiki/Tailscale#Known_issues) to fix IPv6 issues.

### Steps To Reproduce
1. Set `networking.nftables.enable = true;` in NixOS configuration
2. Reboot to really get rid of iptables
3. Connect to tailnet
4. Check IPv6 connectivity using `tailscale netcheck` and `journalctl -u tailscaled.service | grep 'router:'`

### Expected behavior
Tailscale uses nftables instead of iptables.

### Additional context
~~Maybe we're just missing nftables binary dependency in [tailscale/default.nix](https://github.com/NixOS/nixpkgs/blob/53fbe41cf76b6a685004194e38e889bc8857e8c2/pkgs/servers/tailscale/default.nix#L45) or enforcing nftables by setting `TS_DEBUG_FIREWALL_MODE=nftables`?~~

Tailscale's [detectFirewallMode](https://github.com/tailscale/tailscale/blob/84f8311bcdb2404f0afbcf33905c95e23530a553/util/linuxfw/detector.go#L15), using [google/nftables](https://pkg.go.dev/github.com/google/nftables) <- [mdlayher/netlink](github.com/mdlayher/netlink) package, so no cli invocation

```console
[user@system:~]$ journalctl -u tailscaled.service | grep 'router:'
tailscaled[3205]: router: using firewall mode pref
tailscaled[3205]: router: default choosing iptables
tailscaled[3205]: router: v6nat = true
```

### Notify maintainers

@danderson @mbaillie @twitchyliquid64 @mfrw

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.11 (Tapir), 23.11.3684.f4a8d6d5324c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by danderson** [comment]
We should not set TS_DEBUG envvars in normal configuration, like they name suggests they are debug settings whose meaning can change (or break) at any time.

From the source code of the logic that picked the behavior, tailscale's nftables mode is currently experimental and not enabled by default except one corner case. I don't think we should enable experimental code by default for nixos users.

The names "iptables mode" and "nftables mode" may also be misleading from the outside: it doesn't mean that it uses the iptables kernel facility, just that it shells out to the `iptables` binary. If you enable nftables, the `iptables` binary _should_ be switching to the iptables-nft implementation, which translates the iptables invocations into nftables rules on the backend. So, the fact that the logs say "choosing iptables" doesn't mean nftables is not being used, just that tailscale is configuring nftables by shelling out to a binary, instead of using a netlink socket.

If the nixos module isn't giving tailscaled access to the appropriate iptables derivation when networking.nftables is enabled, that's definitely a bug we should fix. Aside from the misleading log statement, are you seeing any issues with how things run? If so, what?

**Comment by stackcoder** [comment]
I totally agree with not enabling experimental code by default! I have understood it like just use nftabels when available. However the used package description "This package is in very early stages(...)" does not does not assure much security.

I'm aware of these iptables to nftables fallback and can confirm the provided iptables derivation is working properly. On my system I've got these rule sets:

```console
[user@system:~]$ nft list tables 
table inet nixos-fw
table ip filter
table ip nat
table ip6 filter
table ip6 nat
```

So the obvious difference might be just insignificant chain names. Beside broken IPv6 exit node support. Maybe this is more an issue within Tailscale itself than setup or configuration.

**Comment by danderson** [comment]
For now, I think we want to keep using the iptables fallback, until upstream decides that the new netlink mode is ready for prime time. Hopefully soon!

It is normal that when you use iptables-nft, you end up with rulesets named similar to the legacy iptables rulesets. It should be harmless though, although I agree it will be nice when we can get rid of the legacy things :)

For your ipv6 issues, if you need help the best bet is to email support@tailscale.com and see if it's a known issue or if they recognize what you're seeing.
