### ISSUE TITLE
remove /nix/store prefix from backblaze-b2 --help ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#288102]
## Issue description

similar to what I had reported in https://github.com/NixOS/nixpkgs/issues/278098

would it be possible to change the output (I am using  `(backblaze-b2.override({ execName = "b2";}))` ):
```
$ b2 --help
  /nix/store/ifkw8cxs2xygypgsb3ax87jd5zjadla7-backblaze-b2-3.15.0/bin/b2 authorize-account [-h]  [applicationKeyId] [applicationKey]
  /nix/store/ifkw8cxs2xygypgsb3ax87jd5zjadla7-backblaze-b2-3.15.0/bin/b2 cancel-all-unfinished-large-files [-h] bucketName
  /nix/store/ifkw8cxs2xygypgsb3ax87jd5zjadla7-backblaze-b2-3.15.0/bin/b2 cancel-large-file [-h] fileId
```
to
```
usages:
b2 authorize-account   [-h] [applicationKeyId] [applicationKey]
b2 cancel-all-unfinished-large-files  [-h] bucketName
```

I didn't see anything in the nix code so maybe it's an upstream issue or a bad interaction between upstream and nix.

  

cc maintainers:

@hrdinka @kevincox @tomhoule

## Technical details
nixos-unstable

**Comment by samueldr** [comment]
(Triaging)

`backblaze-b2` currently doesn't build.

Though from:

  - https://github.com/NixOS/nixpkgs/pull/288256#issuecomment-2007687387
  - https://github.com/Backblaze/B2_Command_Line_Tool/commit/2f571b790ca04748b6090d3c183a45b91c3db4f5

I'll assume this is closed by the next update, since it's been in two tagged versions already.

If this is not the case, feel free to re-open and add necessary details.
