### ISSUE TITLE
Package request: Kanboard

### ISSUE THREAD

**Issue by schlichtanders** [NixOS/nixpkgs#288788]
**Project description**

kanban is a bit like trello, but open source and with support for multiple different database connections.
By github stars it is the most widespread kanban viewer for databases.

**Metadata**

* homepage URL: https://kanboard.org/
* source URL: https://github.com/kanboard/kanboard
* license: mit
* platforms: linux, freebsd, windows (see https://docs.kanboard.org/v1/admin/requirements/)
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bbenno** [comment]
Just a little sidenote (which I just noticed):
The Kanboard package was [removed last year due to its lack of utility](https://github.com/NixOS/nixpkgs/pull/214791)

For those interested in downloading the packages, akin to the now-removed package, the following suffices:
```
pkgs.fetchFromGitHub {
  owner = "kanboard";
  repo = "kanboard";
  rev = "v1.2.35";
  hash = "sha256-pWtI2Uuf/KbNNFP2To3HuGyGMe/4DERXmnnYuTFfVCY=";
};
```

As far as I can tell, for practical applications, a NixOS options similar to that for WordPress [^1] are necessary.

[^1]: https://github.com/NixOS/nixpkgs/blob/5350f74b81e49a9b0ac379db16a13de48a3da425/nixos/modules/services/web-apps/wordpress.nix
