### ISSUE TITLE
Package request: `playwright-driver`: package Firefox and Webkit

### ISSUE THREAD

**Issue by WesleyAC** [NixOS/nixpkgs#288826]
**Project description**

[`playwright-browser`](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/web/playwright/driver.nix) currently only packages Chromium. It would be good to also package the versions of Firefox and Webkit that are supported upstream.

cc @phaer @fabaff @pietdevries94 @kalekseev @teto

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
chromium is patchless while firefox had to carry some patch, + additional builds probably so that's a whole other level of commitment. Might be best to just patch with nix-ld (if that's possible) the proposed firefox (or run it in docker ?). Else feel free to takeover https://github.com/NixOS/nixpkgs/pull/197899

**Comment by WesleyAC** [comment]
Ah, that makes sense. I recall using https://github.com/ludiosarchive/nixos-playwright in the past, so that approach may be applicable.

Do you know if Webkit also requires patches?

**Comment by phaer** [comment]
I gave this a try in https://github.com/NixOS/nixpkgs/pull/298944

**Comment by teto** [comment]
merged the mnentioned PR
