### ISSUE TITLE
[Tracking issue] Silent retirement of maintainers

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#290642]
There are many maintainers that didn't touch Nixpkgs in a long span of time.
They should be listed, formally retired and their packages put to adoption.

Edit: here are some I have found while reading the PR list:

https://github.com/NixOS/nixpkgs/issues/290642#issuecomment-2147303665

**Comment by emilylange** [comment]
We have [RFC 55](https://github.com/NixOS/rfcs/blob/e4c27fdaba705f8b63caf1ace171b503ffe0b5ff/rfcs/0055-retired-committers.md) (and it's amendment [RFC 71](https://github.com/NixOS/rfcs/blob/e4c27fdaba705f8b63caf1ace171b503ffe0b5ff/rfcs/0071-retired-committers-amendment.md)) for committers already.

It's current tracking issue is #88867 and has been so since 2020.

Is this what you mean or are you specifically trying to target contributors which are not committers?

**Comment by AndersonTorres** [comment]
Yes, independent of commit bit.

**Comment by Sigmanificient** [comment]
Having a dedicated tag for package adoption would be very nice:
- https://github.com/NixOS/nixpkgs/issues/310364

**Comment by AndersonTorres** [comment]
I am cogitating another idea: mark them as inactive at maintainer-list.

**Comment by AndersonTorres** [comment]
Here is a more up-top-date list:

| GitHub user           | Fork                                        | Estimated most recent update                                                                              | Estimated most recent contribution (git log) |
|-----------------------|---------------------------------------------|-----------------------------------------------------------------------------------------------------------|---------------------------------------|
| yanateras             | inexistent                                  | inexistent                                                                                                |                                       |
| lovek323 | https://github.com/lovek323/nixpkgs | |
| max-niederman | https://github.com/max-niederman/nixpkgs | |
| cko     | https://github.com/cko/nixpkgs | |
| meisternu | https://github.com/meisternu/nixpkgs | |
| abbradar | https://github.com/abbradar/nixpkgs | |
| rardiol               | https://github.com/rardiol/nixpkgs          |                                                                                                           |                                       |
| vyp | https://github.com/vyp/nixpkgs ||
| gebner                | https://github.com/gebner/nixpkgs           |                                                                                                           |                                       |
| jhillyerd             | https://github.com/jhillyerd/nixpkgs        | [2021-10-04](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Ajhillyerd+sort%3Acreated-desc)     |                                       |
| sheenobu              | https://github.com/sheenobu/nixpkgs         | [2021-07-05](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Asheenobu+sort%3Acreated-desc)      |                                       |
| IvarWithoutBones      | https://github.com/IvarWithoutBones/nixpkgs | [2023-01-03](https://github.com/NixOS/nixpkgs/pulls?q=author%3AIvarWithoutBones+sort%3Acreated-desc)      |                                       |
| nielsegberts          | https://github.com/nielsegberts/nixpkgs     | [2023-06-05](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Anielsegberts+sort%3Acreated-desc)  |                                       |
| qknight               | https://github.com/qknight/nixpkgs          | [2020-02-09](https://github.com/NixOS/nixpkgs/pulls?q=author%3Aqknight+sort%3Acreated-desc)               |                                       |
| cpages                | https://github.com/cpages/nixpkgs           | [2020-11-27](https://github.com/NixOS/nixpkgs/pulls?q=author%3Acpages+sort%3Acreated-desc)                |                                       |
| sheenobu              | https://github.com/sheenobu/nixpkgs         | [2021-07-05](https://github.com/NixOS/nixpkgs/pulls?q=author%3Asheenobu+sort%3Acreated-desc)              |                                       |
| rmcgibbo              | https://github.com/rmcgibbo/nixpkgs         | [2022-04-26](https://github.com/NixOS/nixpkgs/pulls?q=author%3Armcgibbo+sort%3Acreated-desc)              |                                       |
| matthuszagh           | https://github.com/matthuszagh/nixpkgs      | [2022-11-04](https://github.com/NixOS/nixpkgs/pulls?q=author%3Amatthuszagh+sort%3Acreated-desc)           |                                       |
| andsild               | https://github.com/andsild/nixpkgs          | [2018-02-27](https://github.com/NixOS/nixpkgs/pulls?q=author%3Aandsild+sort%3Acreated-desc)               |                                       |
| yboettcher            | https://github.com/yboettcher/nixpkgs       | [2023-06-06](https://github.com/NixOS/nixpkgs/pulls?q=author%3Ayboettcher+sort%3Acreated-desc)            |                                       |
| urandom2              | https://github.com/urandom2/nixpkgs         | [2023-07-03](https://github.com/NixOS/nixpkgs/pulls?q=author%3Aurandom2+sort%3Acreated-desc)              |                                       |
| yureien               | https://github.com/yureien/nixpkgs          | [2022-08-23](https://github.com/NixOS/nixpkgs/pulls?q=author%3Ayureien+sort%3Acreated-desc)               |                                       |
| maurer                | https://github.com/maurer/nixpkgs           | [2020-08-14](https://github.com/NixOS/nixpkgs/pulls?q=author%3Amaurer+sort%3Acreated-desc)                |                                       |
| dtzWill               | https://github.com/dtzWill/nixpkgs          | [2022-08-12](https://github.com/NixOS/nixpkgs/pulls?q=author%3AdtzWill+sort%3Acreated-desc)               |                                       |
| vrthra                | https://github.com/vrthra-forks/nixpkgs     | [2017-05-05](https://github.com/NixOS/nixpkgs/pulls?q=author%3Avrthra+sort%3Acreated-desc)                |                                       |
| expipiplus1           | https://github.com/expipiplus1/nixpkgs      | [2023-12-04](https://github.com/NixOS/nixpkgs/pulls?q=author%3Aexpipiplus1+sort%3Acreated-desc)           |                                       |
| chkno                 | https://github.com/chkno/nixpkgs            | [2024-01-29](https://github.com/NixOS/nixpkgs/pulls?q=author%3Achkno+sort%3Acreated-desc)                 |                                       |
|terin | https://github.com/terinjokes/nixpkgs ||
| ~guyonvarch~ (active) | ~inexistent~                                | ~[2023-01-27](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Aguyonvarch+sort%3Acreated-desc+)~ |                                       |
| ~MP2E~  (retired)     | ~https://github.com/MP2E/nixpkgs~           | ~[2019-02-21](https://github.com/NixOS/nixpkgs/pulls?q=author%3AMP2E+sort%3Acreated-desc)~                |                                       |

**Comment by AndersonTorres** [comment]
Closing because of events in https://github.com/NixOS/nixpkgs/pull/337478

**Comment by SigmaSquadron** [comment]
I feel like while this issue should be closed, another should be opened for community consultation on inactive maintainers. Something like #331085, where the arguments for and against are organised.

**Comment by Mic92** [comment]
I am still interested in an RFC that also removes inactive maintainers. It helps to decided what packages are unmaintained and which can ultimately removed from nixpkgs.
Of course the person that is inactive should be informed with a reasonable time to respond.
The reason is that more package means more work for others i.e. when doing refactoring or bumping dependencies.
In nixpkgs we make it easy to add packages, therefore it shouldn't be harder to remove packages. Nixpkgs should not just be a dumping ground, if people don't have time to maintain their stuff, we rather not should have these packages.
When it comes to pinging former maintainers, there is also a "blame" and "log" view for every package that can be used even if no current maintainer is assigned. Github often suggest candidates to ping or review when making a pull request.

**Comment by bendlas** [comment]
> I am still interested in an RFC that also removes inactive maintainers

Why not just give them an `active = false;` flag? Or better yet a `lastActive = "2020-02-02";`? This would help with the same goal of deciding maintenance status, while retaining multiple advantages over outright deleting them:

- It doesn't look like we're erasing their contribution mark, while keeping the fruits of their labor
- It gives them a carrot (do this to get your active status back) instead of a stick (you're gone now)
- They might still be responding to specific questions, but not really doing code reviews or giving tutorials

Also: as part of any follow-up initiative, I'd like to see a very clear definition of what constitutes "activity", as well as the time frame that we're expecting people to engage within, in order to retain their active status.

**Comment by AndersonTorres** [comment]
Here is the issue about marking long term inactivity:

https://github.com/NixOS/nixpkgs/pull/310759

Feel free to rehash the issues already discussed and found wanting.
