### ISSUE TITLE
Megasync and megacmd refuse to build, because package ‘freeimage-unstable-2021-11-01’  is marked as insecure

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#290949]
### Describe the bug
Megasync and megacmd won't build, because one of the packages they depend on, ‘freeimage-unstable-2021-11-01’  is marked as insecure. The error reads: 

error: Package ‘freeimage-unstable-2021-11-01’ in /nix/store/gzf4zwcakda1nykn6h0avh45xhjhvsz4-source/pkgs/development/libraries/freeimage/default.nix:72 is marked as insecure, refusing to evaluate.

### Steps To Reproduce
1. Try building a system which includes the packages `megasync` or `megacmd`
2. Notice that you get an error `error: Package ‘freeimage-unstable-2021-11-01’ in /nix/store/gzf4zwcakda1nykn6h0avh45xhjhvsz4-source/pkgs/development/libraries/freeimage/default.nix:72 is marked as insecure, refusing to evaluate.`

### Expected behavior
I expect to be able to build my system which contains `megasync` and `megacmd`

### Notify maintainers

@michojel 
@alkeryn 
@Synthetica9 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.5, NixOS, 24.05 (Uakari), 24.05.20240218.b98a4e1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(jon): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by alkeryn** [comment]
hmm, i'm a little busy right now but it seems like it could be fixed by updating the freeimage derivation and unmarking it as unsafe.

I'd say that's probably my biggest gripe with nixos, not being able to update my whole system because megasync (or one of a few packages) broke again, having a temporary / hotfix --ignore feature woul be practical.
i'll see if i can find some time for it next week, otherwise it shouldn't be too much effort if someone wants to do it before i do.

**Comment by dotlambda** [comment]
https://nixos.org/manual/nixpkgs/unstable/#sec-allow-insecure and on NixOS:

```nix
nixpkgs.config.permittedInsecurePackages = [
  "freeimage-unstable-2021-11-01"
];
```

**Comment by alkeryn** [comment]
@dotlambda that is a hotfix, ideally we'd make it secure.
but i was talking about more generally being able to ignore a derivation when upgrading without having to edit the configuration.nix

something like nixos-rebuild --upgrade --ignore {derivations here}.

**Comment by dotlambda** [comment]
I don't understand what you mean but https://nixos.org/manual/nixpkgs/unstable/#sec-allow-insecure provides many ways of ignoring insecure packages even if their version changes.

**Comment by alkeryn** [comment]
@dotlambda it was more about ignoring a broken derivation when attempting to update.
right now if a single derivation is broken you cannot update the whole system.

it would be nice to be able to tell it "update everything but that derivation" with just a command line argument.

**Comment by SrTobi** [comment]
I don't think we can fix this. I looked up the vulnerabilities and for examples
CVE-2021-40262
-> https://security-tracker.debian.org/tracker/CVE-2021-40262
-> https://sourceforge.net/p/freeimage/bugs/338/

is still open and the whole freeimage library seems half abandoned (?)

**Comment by lunik1** [comment]
It looks like the [mega sdk](https://github.com/meganz/sdk) can be compiled without freeimage, although I do not know what features this would disable.

**Comment by lolbinarycat** [comment]
closing this for now, it looks like it's been fixed.

**Comment by gvolpe** [comment]
I submitted an issue regarding MEGAsync: https://github.com/meganz/MEGAsync/issues/910

**Comment by lunik1** [comment]
This should be reopened, only MEGAcmd is fixed.

**Comment by alkeryn** [comment]
I'll close it again once the gui is fixed by someone.

**Comment by SuperSandro2000** [comment]
> @dotlambda it was more about ignoring a broken derivation when attempting to update. right now if a single derivation is broken you cannot update the whole system.

That is the whole point of NixOS and a desired feature. If the defined config cannot be built, the built should fail.

> it would be nice to be able to tell it "update everything but that derivation" with just a command line argument.

You can impurely ignore that a package is marked broken but if it can't be built, then you must change your config and since there is no true one was to fix this, it cannot be easily done in a simple step.

**Comment by alkeryn** [comment]
@SuperSandro2000 yes but i'm talking about comand line flags for single time thing just for practical purpose, because not being able to update your whole system because a single package fail can get annoying, it'd be nice to have an easy option to tell "update everything but this package exceptionally".

my point exactly, in other distros if a single package is broken you can generally update the rest of the system and sometime that's something you actually wanna do for work or other productivity purposes.

**Comment by lunik1** [comment]
Why not remove that package from your declarative config and install it imperatively using `nix-env` or `nix profile` with an older nixpkgs pin?

Anyway this is starting to get off-topic. Can you discuss this more in a new issue or the discourse?

**Comment by MissLavender-LQ** [comment]
> I don't think we can fix this. I looked up the vulnerabilities and for examples [CVE-2021-40262](https://github.com/advisories/GHSA-ffv6-g99g-rj96) -> https://security-tracker.debian.org/tracker/CVE-2021-40262 -> https://sourceforge.net/p/freeimage/bugs/338/
> 
> is still open and the whole freeimage library seems half abandoned (?)

darn also causes issues for 
`trenchbroom`
and 
`slade`
