### ISSUE TITLE
pam_u2f: also require first factor?

### ISSUE THREAD

**Issue by shosti** [NixOS/nixpkgs#29172]
pam_u2f is currently always configured as being "sufficient", so no password is necessary if U2F authentication succeeds. It would be nice if it were optionally "requisite" instead (similarly to https://github.com/NixOS/nixpkgs/pull/22724 for OATH), since U2F is designed for second-factor auth after all.

**Comment by vlaci** [comment]
I've written a module to override the default behavior:
https://gist.github.com/vlaci/80bebce47a8ac6770035d362b3d004e0

I've used to hardcode pam configuration to overcome this limitation but it was really brittle because everytime the list of installed services changed I had to remember to look into the generated service file and copy-paste the modified version back to `configuration.nix`.

**Comment by benley** [comment]
It looks like this is configurable now, with:

```nix
{
  security.pam.u2f.control = "required";
}
```
