### ISSUE TITLE
`haskellPackages.time` is null? 

### ISSUE THREAD

**Issue by MangoIV** [NixOS/nixpkgs#292416]
### Describe the bug

for some reason the `time` haskell package is null

### Steps To Reproduce
`nix build github:nixos/nixpkgs/master#haskellPackages.time` 

### Expected behavior

time should be something. not null 

### Screenshots

![image](https://github.com/NixOS/nixpkgs/assets/40720523/e93c8621-1280-4c35-9877-6cbff2ddeb35)

### Additional context

n/a

### Notify maintainers

@maralorn perhaps? 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.17, NixOS, 24.05 (Uakari), 24.05.20240221.0e74ca9`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.20.0pre20231207_661b025`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by maralorn** [comment]
This is on purpose.

As you can see here https://github.com/NixOS/nixpkgs/blob/5250ee5c0b7086edd435843ae6c3ce537ba44fde/pkgs/development/haskell-modules/configuration-ghc-9.4.x.nix#L51

We override all packages bundled with ghc as null. The reason is that those packages are needed to build ghc and are therefore already part of the ghc derivation. They are always available to build with. Thus the nix representation of a haskellPackage does not need them as explicit inputs. The configure step of the build process will automatically discover them.

**Comment by MangoIV** [comment]
I mean you don’t trace it every time but only if some body wants build it.

**Comment by maralorn** [comment]
Huh, yeah, would be cool. I just don’t know how we’d do that.
