### ISSUE TITLE
services/loki: Configuration verification

### ISSUE THREAD

**Issue by jpds** [NixOS/nixpkgs#293088]
### Describe the bug

loki's configuration should be verified by the derivation before deploying with the `-verify-config -config.file` parameters.

### Notify maintainers

@WilliButz @globin @mmahut @emilylange @ajs124 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by drupol** [comment]
@jpds Do you think you could have a look at this?

**Comment by emilylange** [comment]
@martijnboers thanks for sharing your config in that gist. That's incredibly helpful for reproducing and understanding your issue.

I don't see how those validation errors are false positives though.

All those keys/fields/values that throw errors are have been deprecated and removed from loki `v3.0.0`.
See https://github.com/NixOS/nixpkgs/pull/304060 or [NixOS 24.05's release notes](https://nixos.org/manual/nixos/stable/release-notes#sec-release-24.05-incompatibilities).

What makes me believe that this isn't a false positive is, that even if you skip the validation, `loki.service` will not be able to start due to the same error:

```
loki[647]: failed parsing config: /nix/store/nzb5rshhyy2bcw7hm1ag9arh19ai9pbc-loki-config.json: yaml: unmarshal errors:
loki[647]:   line 4: field max_look_back_period not found in type config.ChunkStoreConfig
loki[647]:   line 12: field shared_store not found in type compactor.Config
loki[647]:   line 29: field max_transfer_retries not found in type ingester.Config
loki[647]:   line 57: field shared_store not found in type boltdb.IndexCfg. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
systemd[1]: loki.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: loki.service: Failed with result 'exit-code'.
```

and your workaround setting `services.loki.extraFlags = ["-v"];` does not work either, because `-v` isn't a valid flag:

```
loki[646]: flag provided but not defined: -v
loki[646]: Run with -help to get list of available parameters
systemd[1]: loki.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: loki.service: Failed with result 'exit-code'.
```

See

```
❯ loki -v
flag provided but not defined: -v
Run with -help to get list of available parameters
```

**Comment by martijnboers** [comment]
I've not looked into Loki logs to see if there are errors mentioned but my dashboards all still worked and I took that as an indicator that everything was still OK. Thank you for linking to the breaking changes documentation, this is also helpful for other broken programs I have at the moment.

**Comment by martijnboers** [comment]
Updated my configuration and you comment was spot on, indeed it was not working with that setup and the `-v` trick didn't work as I thought, I just was not informed enough on this loki/promtail service :sweat_smile:
