### ISSUE TITLE
Rendering crashing in kdenlive 

### ISSUE THREAD

**Issue by robert-elles** [NixOS/nixpkgs#293315]
### Describe the bug
Rendering a project in Kdenlive with default rendering settings leads to the following error:

[libprotobuf ERROR /build/source/src/google/protobuf/descriptor_database.cc:642] File already exists in database: opencv-caffe.proto [libprotobuf FATAL /build/source/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
what(): CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):

**Comment by praduca** [comment]
i'm having the same issue

**Comment by gbytedev** [comment]
This just bit me as well on unstable. If you found a workaround, please share.

**Comment by librephoenix** [comment]
This broke for me on unstable as well.  Don't know if this will be helpful to anyone trying to figure this out, but I've been testing random nixpkgs commits from nixos-unstable and pinning kdenlive to those commits, to try to pin down a time frame for what commit(s) broke it.  Based on my quick tests, this is what I've found:

1698ab22202db0b9432e829a551ea678cf76057b - Feb 22nd, 11:41pm CST - All good!
7d10a86bebda2dd005354b65c1a13a4d152d8a3d - Feb 24th, 11:56pm CST - All good!
c8cddb44f5a7d248c3b18f4f6511a1a646ed4cbe - Feb 25th, 11:59pm CST - Rendering error..
19df862e28db39f6dfebc3a7cbbd232d6fa6bb37 - Feb 26th, 2:06pm CST - Rendering error..
2213bf64c63e91aac8a4d271f0cd1d03ebc56465 - Feb 26th, 6:56pm CST - Rendering error..
62b6a40c3051e98b022cbace5e511681c47141e4 - Feb 26th, 8:15pm CST - Rendering error..
cfec6d9203a461d9d698d8a60ef003cac6d0da94 - Feb 26th, 11:49pm CST - All good!
c6472d9bf8c9422f94f18ccb13ee375a49531277 - Feb 27th, 11:48pm CST - Rendering error..
18b6efcdce77b13e59934c1bee407503e6378712 - Feb 28th, 11:58pm CST - Rendering error..
09c1497ce5d4ed4a0edfdd44450d3048074cb300 - Feb 29th, 11:31pm CST - Rendering error..

It looks like it broke at least twice.

So, it's probably one of [(any of) these commits on Feb 25th](https://github.com/NixOS/nixpkgs/commits/master?since=2024-02-25&until=2024-02-25) that broke it initially, then something on the 26th ([maybe something directly on this page?](https://github.com/NixOS/nixpkgs/commits/master?since=2024-02-26&until=2024-02-26&before=9a233d95a78fbd10bd46f637c87f088806b28ef2+35)) fixed it, before it got broken again [sometime on the 27th](https://github.com/NixOS/nixpkgs/commits/master?since=2024-02-27&until=2024-02-27).

In any case, I've pinned kdenlive to nixpkgs cfec6d92.. and I'm probably gonna leave it like that for a while.

The way I've pinned it in my config isn't very elegant, but here's my [flake.nix](https://github.com/librephoenix/nixos-config/blob/main/flake.nix) and [home.nix](https://github.com/librephoenix/nixos-config/blob/main/profiles/work/home.nix) in case it helps anyone..

**Comment by robert-elles** [comment]
Installing kdenlive  24.02.0 via pkgs.kdePackages.kdenlive (and switching to plasma 6) solved the issue for me. My project is rendering without issues in kdenlive.

**Comment by gbytedev** [comment]
Seems to be working after the last update + rebuild (libsForQt5.kdenlive unstable).

**Comment by RemcoSchrijver** [comment]
Works again on nixpkgs: https://github.com/NixOS/nixpkgs/commit/3b9f00d7a7bf68acd4c4abb9d43695afb04e03a5
