### ISSUE TITLE
boot.initrd.systemd.enable breaks the boot.initrd.network.ssh.authorizedKeys

### ISSUE THREAD

**Issue by farcaller** [NixOS/nixpkgs#294032]
### Describe the bug

If `boot.initrd.systemd.enable=true` and `boot.initrd.systemd.users.root.shell` is used instead of `boot.initrd.network.ssh.shell`, authorizedKeys aren't propagated properly.

### Steps To Reproduce
1. Have ssh enabled and functional in initrd.
2. Enable `boot.initrd.systemd.enable`.
3. Observe the warning "trace: warning: Please set 'boot.initrd.systemd.users.root.shell' instead of 'boot.initrd.network.ssh.shell'"
4. Do as it says.
5. Fail to log into initrd due to public key no longer being accepted.

### Expected behavior
Initrd is still accessible over ssh.

### Additional context
This is nixpkgs-unstable at 1536926ef5621b09bba54035ae2bb6d806d72ac8.

### Notify maintainers

@maralorn @ElvishJerricco @nikstur

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/root/.config/nix/inputs/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by maralorn** [comment]
I don’t feel related to this topic at all, sorry. :laughing:

**Comment by farcaller** [comment]
Sorry, I just grabbed the top 3 people from the history of the initrd module!

**Comment by stevenewey** [comment]
I ran into this too, and after investigating a bit, I don't think the problem is with the keys. If you don't set the shell, you can SSH in.

`cryptsetup-askpass` (defined [here](https://github.com/NixOS/nixpkgs/blob/04dbb29bbc3a9b795fd05ec748dbde2ef376687a/nixos/modules/system/boot/luksroot.nix#L494)) doesn't seem to be created, and also I suspect would be rejected even if it did as an invalid shell, unless added to `/etc/shells`.

A look at the running processes shows how the TTY unlock is being handled in a systemd unit, in my case...
```
systemd-cryptsetup attach nix-disk /dev/disk/by-uuid/478c282a-8823-4049-9c1c-29beda7cfaa2 - discard,no-read-workqueue,no-write-workqueue
```

Running that same command in the SSH session prompts for the passphrase and normal boot resumes. So it looks like there's some work to be done here to add something nicer and/or fix the docs/module when `boot.initrd.systemd.enable` is set.

There also seems to be an issue where if you don't enter the passphrase soon enough on the TTY, systemd goes to emergency mode, and when you do unlock the disk from this point, the system is not able to boot correctly.

**Comment by ElvishJerricco** [comment]
@stevenewey The `systemd-cryptsetup` unit that starts when the system boots uses the `systemd-ask-password` protocol. You can just use `systemd-tty-ask-password-agent` or `systemctl default` (which is my preference) to respond to the password prompt. In the end, the prompt on the console is actually just a `systemd-ask-password` response.

The wiki is broken. `boot.initrd.systemd.users.root.shell = "/bin/cryptsetup-askpass";` is an oxymoron. The `boot.initrd.systemd.users.root.shell` option only exists with systemd stage 1 but systemd stage 1 has never had `cryptsetup-askpass` because the *correct* thing to use is something that responds to the `systemd-ask-password` protocol.

As for the emergency mode thing, I explained this here: https://github.com/NixOS/nixpkgs/issues/250003#issuecomment-1724708072

Finally, the OP claims that `boot.initrd.systemd.users.root.shell` has different behavior from `boot.initrd.network.ssh.shell`, but the two are [literally equivalent](https://github.com/NixOS/nixpkgs/blob/b31b5db8b451752f61d117fdd6e1b7b477a79a20/nixos/modules/system/boot/initrd-ssh.nix#L255), so it's not possible for them to behave differently.

**Comment by stevenewey** [comment]
@ElvishJerricco that's much simpler, thanks for the explanation!

**Comment by erykwieliczko** [comment]
SSH rejects connection without any meaningful error if a shell doesn't exist.
`/bin/cryptsetup-askpass` exists in an initrd without systemd, but disappears when systemd is enabled.
If you set `boot.initrd.systemd.users.root.shell = "/bin/sh"` the SSH will work fine. Or don't define it at all.

I think that the issue doesn't exist and can be closed.

**Comment by garret** [comment]
I was planning today to follow the [wiki](https://nixos.wiki/wiki/Remote_disk_unlocking) to remote unlock my nixos server (with encrypted luks2 btrfs root partition) for the first time. However, I found this github issue where it seems it is claimed that the wiki is wrong. May I ask what should be the correct way? I am sorry but I am still quite a newbie with nixos/initrd/encryption.

**Comment by farcaller** [comment]
@garret it seems that you either do it the wiki way, or, if you have to turn `boot.initrd.systemd.enable` on for whatever reasons, you then unlock with `systemctl default`.

**Comment by erykwieliczko** [comment]
@garret Farcaller is right. If you want to unlock the encryption in initrd:
Not using systemd? `/bin/cryptsetup-askpass`. Using systemd? `systemctl default`.

I ultimately opted for non-systemd setup because `systemd+openvpn` wasn't working in initrd.

**Comment by erykwieliczko** [comment]
@garret I just ssh to shell and execute `/bin/cryptsetup-askpass` manually. No need to spend more time than required on a temporary solution.

**Comment by garret** [comment]
@erykwieliczko for me it will not be a temporary solution so I was looking for something where I have to spend less time as possible :)

**Comment by ElvishJerricco** [comment]
@erykwieliczko

> I ultimately opted for non-systemd setup because systemd+openvpn wasn't working in initrd.

Please open an issue, [openvpn is supposed to be working](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.systemd-initrd-networkd-openvpn.x86_64-linux).

Anyway, as for the original issue, I think it would make sense to have an alias command at `/bin/cryptsetup-askpass` that just runs `systemctl default` or `systemd-tty-ask-password-agent` simply for compatibility's sake, as we want to eventually make systemd initrd the default.
