### ISSUE TITLE
colemak keymap not found

### ISSUE THREAD

**Issue by maxigit** [NixOS/nixpkgs#29413]
## Issue description
when installing nixos `loadkeys colemak` doesn't find the colemak file. 

### Steps to reproduce
Launch the installer with the nixos-minimal or nixos-graphical iso. try `loadkeys colemak`.  I think the problem is the same once Nixos is installed.
However, the file is present. Doing `find /nix/store -name colemak` find some files. Loading the keymap with the full path then work.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

nixos-graphical-17.0.3.1769
nixos-minimal-17.0.3.1769

* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by ZzAntares** [comment]
Hi I just wanted to try nixos today (in a vm), and indeed I have this issue, but even if I provide the full path to the file it say's it can't load the file. Did someone manage to solve this? Is there any other way I could force `colemak` to be used?

Thanks in advance.

**Comment by ZzAntares** [comment]
Yes I was referring about the installer, but now I see it works fine, I just didn't know the correct name for the colemak layout (`loadkeys colemak/en-latin9`). I was expecting `loadkeys colemak` to just work (as it does with dvorak), thanks for pointing that out!

**Comment by MetaDark** [comment]
[Arch Linux appears to rename the keymaps files](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/kbd#n29) which is why `loadkeys colemak` works on Arch Linux. This patch was added almost 10 years ago so it seems unlikely that this will be fixed upstream in kbd any time soon. 

Maybe this should be implemented in [kbd.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/kbd.nix), possibly with symlinks instead of renames to ensure backwards compatibility.

**Comment by MetaDark** [comment]
@maxigit This can be closed now. It looks like it was fixed in commit f1987fb58f5.
