### ISSUE TITLE
Update request: go 1.21.8 → 1.22.1

### ISSUE THREAD

**Issue by bluefoxy009** [NixOS/nixpkgs#295511]
- Package name: go
- Latest released version: 1.22.1

- Current version on the unstable channel: 1.21.7
- Current version on the stable/release channel: 1.21.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@zowoq @kalbasit @Mic92 @qbit @mfrw 

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kirillrdy** [comment]
go 1_22 is availble on unstable channel

```
nix run nixpkgs#go_1_22 -- version
go version go1.22.1 linux/amd64
```

**Comment by kirillrdy** [comment]
default go 1_22 has been also been merged https://github.com/NixOS/nixpkgs/pull/290212

it just going to take a while before it lands unto unstable, since it requires to ensure that all go packages in nixpkgs build with go_1_22

you can read more about staging workflow

https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging
