### ISSUE TITLE
github results arrive before the actual manual in Google results 

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#29553]
## Issue description

As I switched fulltime to nixos, I've been doing a fair bit of googling on nixos related topics and an annoying thing I noticed is that the nix(os) manual rarely (never?) comes up in the results. What I usually see is the documentation xml files from the github. I wonder if any step can be done to improve the ranking of the manual as it's (I can read the XML but there is no navigation/anchor) ? or if it's because the manual url changed recently ?

### Steps to reproduce
google "nixos <whatever>"

As google does give different results depending on the account, it might not be the case for everyone ? maybe it's because I check the tracker regularly. I've tried searching "nixos overlay" in firefox private mode but even so "nixpkgs/overlays.xml at master · NixOS/nixpkgs · GitHub" comes up while the manual doesn't (I checked the 4 first pages of results)

**Comment by vyp** [comment]
When I google "nixos manual" I get all 3 manuals (nixos, nixpkgs, nix) as top 3 google search results (in incognito and private browsing modes). If I google "nixos overlays", the nixpkgs manual is the second search result so in my opinion that seems okay, and it may hopefully become better with time since I think this overlays section in the manual is a bit new. I not sure if this was exactly what you're concerned about though.

**Comment by teto** [comment]
if you add the "manual" keyword it does help bring it up (as first result) but without "manual", manual pages don't come up for me in incognito mode.
I guess I can just add "manual" for my research but ideally it shouldn't be the case. Even if it doesn't come up first, it should eventually appear.

**Comment by vyp** [comment]
Yeah I understand that but I guess people who google "nixos" probably want information about it, and what it is, rather than bring up the manual straight away.

But maybe you're right, maybe there's some seo stuff one can do to improve the manual's rankings, so I'm not necessarily disagreeing with you.

**Comment by teto** [comment]
well there are not so many resource about nixos and while you can't decide
the order of google results, not having the manual appear at all is kinda
awkward as it's supposed to be among the best source available. Sadly I
can't give any advice on SEO :(

2017-09-19 11:52 GMT+09:00 vyp <notifications@github.com>:

**Comment by joachifm** [comment]
Perhaps something could be done over at https://github.com/NixOS/nixos-homepage

**Comment by globin** [comment]
Yes we cannot do anything here, I don't see this as actionable in the nixpkgs repo, therefore closing, feel free to open an issue/PR in nixos-homepage.
