### ISSUE TITLE
CLion uses wrong JDK

### ISSUE THREAD

**Issue by matklad** [NixOS/nixpkgs#29645]
## Issue description

Wrapper scripts for JetBrains projects setup a special environmental variable to select JDK used by the product. Unfortunately, the variable used for CLion (`CLION_JDK`) is wrong, it should be `CL_JDK`.

`CL_JDK` is "documented" here https://blog.jetbrains.com/clion/2015/03/clion-eap-news-cmake-features-and-bug-fixes/ and I can confirm that for 2017.2 nothing has changed.

The line in nixpgks where the env var is set is this: https://github.com/NixOS/nixpkgs/blob/5f328b33abefca6bedd8b204a752c27318af4348/pkgs/applications/editors/jetbrains/common.nix#L71, and `hiName` is determined here: https://github.com/NixOS/nixpkgs/blob/5f328b33abefca6bedd8b204a752c27318af4348/pkgs/applications/editors/jetbrains/common.nix#L9

**Comment by matklad** [comment]
cc @edwtjo, my nix-fu is not refined enough to understand how to fix this special case without disturbing other products :)

**Comment by edwtjo** [comment]
The quick fix here is to use `wrapProgram` inside the already added `postFixup` for CLion. You need to know that `wrapProgram` can wrap any executable and set environment vars for it. Since env vars are passed downward it is ok to wrap a wrapper but the inner most env is the one that will be eventually used. This isn't a problem here since `CL_JDK` hasn't been defined yet. This is done in 4e12dbb09247e9e547a7a62649071bae43ad74ee
