### ISSUE TITLE
collision between texlive and asymptote

### ISSUE THREAD

**Issue by thblt** [NixOS/nixpkgs#29671]
## Issue description

Having both              `asymptote` and       `texlive.combined.scheme-full` in my `nixpkgs/config.nix` triggers the following error on `nix-env -i all`:

```
collision between `/nix/store/jl8fkpzhf1p21mi8yhj08d01d8jf5yz5-texlive-combined-full-2016/share/texmf/tex/latex/asymptote/asymptote.sty' and `/nix/store/1dqwslmjb75n2x3niqs0ajim09ydzwkz-asymptote-2.39/share/texmf/tex/latex/asymptote/asymptote.sty'
```

TeXLive itself doesn't provide asymptote: there's no `asy` binary in path.

### Steps to reproduce

Try to install `asymptote` and       `texlive.combined.scheme-full` together.  

This seems to also be the case with the `medium` texlive scheme. I haven't tried with others.

## Technical details

* System: NixOS 17.03.1825.df7e518568 (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1825.df7e518568"
* Sandboxing enabled: no

Thanks!

**Comment by rycee** [comment]
I'm imagining that the asymptote package should either avoid installing the LaTeX module or to install at a lower priority. Personally I would prefer the former, seems to me sufficient to have the one from texlive.

Maintainer CC: @7c6f434c @peti

**Comment by 7c6f434c** [comment]
Hm, never tried using the built-in asymptote code LaTeX package. I am 
not confident enough about the current TeXLive state: does it have 
a chance to find the asymptote package installed separately from its
combination machinery? If no, I guess removing the dot-sty in the 
asymptote installer is the only reasonable path.

**Comment by rycee** [comment]
@7c6f434c I'm not sure. Maybe @vcunat knows?

**Comment by FRidh** [comment]
> If no, I guess removing the dot-sty in the
asymptote installer is the only reasonable path.

Or "hiding" the texmf folder? We could create a wrapper derivation for asymptote with symlinks. Or maybe multiple outputs?

**Comment by 7c6f434c** [comment]
What you list are feasible options. I just don't think they provide any
benefit.

When I look at the TeX code provided by `texlive.asymptote`, I think
it will be a lot of «fun» if a fresh release of asymptote binary gets 
incompatible with any of that. Because that would break all the 
standalone handwritten asymptote code, too.

Anyway, I ran the diff on the file in question, and the difference is
restricted to copyright years and package versioning information.

Just for fun, CTAN seems to contain a version of asymptote package that
actually carries Windows 32-bit binaries.

(I am currently trying to actually test the fix — the most expensive
part is upgrading my mid-sized TeXLive installation to `scheme-full`)

**Comment by 7c6f434c** [comment]
Cherry-picked to release branches, too
