### ISSUE TITLE
nushell: NIX_LD and NIX_LD_LIBRARY_PATH not accessible by default

### ISSUE THREAD

**Issue by pacjo** [NixOS/nixpkgs#297449]
### Describe the bug

With [nix-ld](https://github.com/Mic92/nix-ld/) configured and working in bash, it's broken in nushell. Developer mentioned [a solution](https://github.com/Mic92/nix-ld/issues/59), but it doesn't work out of the box. Can fix be added to the nushell package?

### Steps To Reproduce
1. configure [nix-ld](https://github.com/Mic92/nix-ld/)
2. run any binary from nushell
3. see error

### Expected behavior

Binary would execute just fine.

### Additional context

Fix: https://github.com/Mic92/nix-ld/issues/59

### Notify maintainers

@Br1ght0ne @JohnTitor @marsam @JoaquinTrinanes 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.82, NixOS, 23.11 (Tapir), 23.11.5408.8ac30a39abc5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JoaquinTrinanes** [comment]
[You probably don't want nushell as a login shell](https://www.nushell.sh/book/default_shell.html#setting-nu-as-login-shell-linux-bsd-macos), precisely because of issues like this. You're probably missing some relevant env vars like `NIX_PATH`, or even some elements of `PATH` itself.

While we could hardcode or manually handle _some_ of them it's not maintainable in the ~long~ short run and not really a nushell issue, as it happens with any non-POSIX shells ([like fish](https://fishshell.com/docs/current/index.html#default-shell)).

My recommended approach (and the one I use) is starting `nu` from `bash`, after sourcing the relevant files). Adding the following to your `.bashrc` (for example, via `programs.bash.initExtra` in home-manager) will do the trick:

```bash
    if [[ ! $(ps T --no-header --format=comm | grep "^nu$") && -z $BASH_EXECUTION_STRING ]]; then
        shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION='''
        exec "${lib.getExe config.programs.nushell.package}" "$LOGIN_OPTION"
    fi
```

Replace `"${lib.getExe config.programs.nushell.package}"` with the correct path if needed.

**Comment by JoaquinTrinanes** [comment]
> Also shouldn't LOGIN_OPTION=''' be just LOGIN_OPTION=''? I've spent way too much time debugging this, but now it works.

The snippet I pasted came straight for nix, the first quote is there to escape the second one (inside a `''`-delimited string)

> So if it's not nushell's fault, closing?

Indeed 😁

**Comment by AThilenius** [comment]
@JoaquinTrinanes Just want to say thank you, I've been chasing a solution to this problem for a while. Although it does appear `LOGIN_OPTION='''` is invalid syntax. No idea what any of it does, bash is right up there with [brainf***](https://en.wikipedia.org/wiki/Brainfuck) in terms of readability.

**Comment by AThilenius** [comment]
> The third quote is needed for escaping if the code is written in a `nix` file.

Ahhh, got ya. That makes sense. I haven't started down the Home Manager route just yet, still getting my feet under me with Nix, and build-your-own Linux distros in general so I just pasted it into my normy `.bashrc` like a pleb.

**Comment by clementpoiret** [comment]
(I'm not sure if it's a good practice to do so) For the sake of reference, I simply added the following lines to my `env.nu` to load `/etc/set-environment`:

```nu
# Source /etc/set-environment
bash -c $"source /etc/set-environment && env"
    | lines
    | parse "{n}={v}"
    | filter { |x| ($x.n not-in $env) or $x.v != ($env | get $x.n) }
    | where n not-in ["_", "LAST_EXIT_CODE", "DIRS_POSITION"]
    | transpose --header-row
    | into record
    | load-env
```
