### ISSUE TITLE
build during evaluation

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#29774]
I was recently wondering why each Hydra eval of full nixpkgs now takes rougly one hour, and now I see there are apparently builds done during it.  See https://hydra.nixos.org/jobset/nixos/gcc-7#tabs-errors  (the branch only has a couple lines of changes when compared to master)

- [ ]  find the culprit

**Comment by edolstra** [comment]
Oh, that's very bad...

**Comment by dezgeg** [comment]
At least one instance fixed in c88075682389b7c16a519503cb8ca1f16fb31757. Maybe Hydra could be fixed to not allow that.

**Comment by vcunat** [comment]
Not fixed.  For the gcc-7 jobset I now worked around it by starting with `release-small` which doesn't seem to have this problem.  Also,in the nixpkgs staging job doesn't happen, so it must be something specific for `release-combined`.  I see things like
> defaultConfig = builtins.fromJSON (readFile "${pkgs.mattermost}/config/config.json")

**Comment by dezgeg** [comment]
`staging` doesn't show these because most of them are coming from NixOS modules and/or tests, e.g.:  https://github.com/NixOS/nixpkgs/commit/dc5cd7800a004b9c58d0cdd5482d6980e3e47205 and https://github.com/NixOS/nixpkgs/commit/cb008da16755d1de08e930461eb8be742a3daabf.

Those ones showed up while trying to evaluate `trunk-combined` on aarch64, which fails because apparently the Hydra evaluator can't connect to the aarch64 build slave, only the Hydra queue runner can.

**Comment by dezgeg** [comment]
`nix-instantiate nixos/tests/kubernetes/default.nix -A rbac` does it as well. The expression that imports it to the release jobset is not evaluating, though, so the kubernetes tests aren't getting run by Hydra either.

**Comment by vcunat** [comment]
Let's close this particular case.
