### ISSUE TITLE
Reinstate GHC v8.0.1

### ISSUE THREAD

**Issue by mboes** [NixOS/nixpkgs#29791]
## Issue description

GHC 8.0.1 was part of Nixpkgs, but now it's gone, breaking all LTS-7 builds and likely some other LTS series as well. This version was removed in 398b36431d6f08b4b9902a8e2d2d4eb0bd34e435 by @peti 

I submit that GHC 8.0.1 should stay for eternity, so that we can continue to build old LTS releases. Furthermore, GHC 8.0.2 has introduced unfortunate regressions. In particular, 8.0.2 does not support creating PIE executables at all. See https://ghc.haskell.org/trac/ghc/ticket/12759. Lack of PIE means that sparkle is unusable in such a release.

### Steps to reproduce

```
$ nix-shell -p haskell.compiler.ghc801
error: attribute ‘ghc801’ missing, at (string):1:66
```

**Comment by peti** [comment]
I don't want to maintain outdated compiler versions any longer than absolutely necessary and certainly not for eternity. Users who need older versions because of special interests can easily add it to their system by means of `override`.

**Comment by mboes** [comment]
I don't understand what makes 8.0.1 any different from 6.10.4. Why keep the latter (which is 8 years old) but not the former (just a year old, and something a lot of projects are stuck on if we're to go by the Haskell projects I see at Tweag I/O)? Because 8.0.2 is the latest in the series? But the fact of matter is even minor version bumps introduce incompatibilities, which is why LTS series pin to a specific compiler version.

Was there anything wrong with 8.0.1 support in nixpkgs meanwhile? If it wasn't broken and not causing problems, why not just keep it? It can take hours to build a new GHC. Do we really need to hoist no longer having the benefit of the binary cache onto users at this point? When the GHC devs cleanup their story around PIE (next release), dropping 8.0.1 will be much less problematic.

**Comment by gebner** [comment]
Note that this commit breaks `stack build`:
```
[gebner:~/tip-tools] master ± stack build                                                                              
Downloaded lts-7.7 build plan.    
error: attribute ‘ghc801’ missing, at (string):1:60
(use ‘--show-trace’ to show detailed location information)
```

**Comment by peti** [comment]
> I don't understand what makes 8.0.1 any different from 6.10.4.

The latter is different because it is the latest version of the 6.10.x branch, but the former is not the latest version of the 8.0.x branch.

Anyhow, support for GHC 6.10.x is completely broken in Nixpkgs and it's only a matter of time before someone removes that old compiler, too.

> Was there anything wrong with 8.0.1 support in nixpkgs meanwhile?

It was generating maintenance costs that I was unwilling to take on. If you still need the old compiler, then feel free to (a) use an older version of Nixpkgs, such as the 17.09 release branch, or (b) add it to your current package set by means of a local override and perform the necessary maintenance yourself. Please don't expect me to do that for you.

**Comment by mboes** [comment]
If _you_ don't use these compiler versions, that's fine. But don't assume that's the same for others. I'm perfectly happy to maintain GHC 8.0.1 at least until the next GHC release, *in Nixpkgs*. I see value in retaining support for building LTS-7 or indeed all recent LTS releases. Nixpkgs still supports building LTS-6 and prior versions.

**Comment by chris-martin** [comment]
@peti I'm confused.

> Users who need older versions because of special interests can easily add it to their system by means of `override`.

> It was generating maintenance costs that I was unwilling to take on.

Is it easy, or isn't it?

**Comment by peti** [comment]
@chris-martin, adding any other, currently unsupported version of `ghc` into Nixpkgs by way of a local override is easy. Making sure that it builds successfully in the face of frequent updates to `gcc`, `coreutils`, `binutils`, etc. is not quite as easy, but it's doable. Making sure that the old compiler builds a non-trivial Haskell package set is hard.

If you constrain yourself to release branches, then you should be fine (since major changes typically don't make it into those branches, so you have a stable environment). If you want to do this kind of thing on the current `master` branch of Nixpkgs, then it's going to be a bit of an effort.
