### ISSUE TITLE
Selecting python interpreter in PyCharm is slow

### ISSUE THREAD

**Issue by mkocha2** [NixOS/nixpkgs#29803]
## Issue description
The dialog box in PyCharm to select a python interpreter is a DoS attack on my computer. Presumably because it tries to display a very large Nix store.

I had to wait around 20 minutes for the listing to complete using a HDD.

This problem doesn't exist on e.g. Debian/Ubuntu.

### Steps to reproduce
Open a new Python project and try to select an interpreter.

## Technical details

* System: 17.03.1858.3d04a557b7 (Gorilla)
* Nixpkgs version: 8a1fb4b504d644e8a97394be74a3d3a6298fcbe7

**Comment by FRidh** [comment]
Let's see whether I understand what your issue is.

When you create a project with PyCharm and you want to select an interpreter, you browse to one, e.g. through the Nix store for which loading all entries may take a long time. Is this the issue you're facing? If so, how is that a Nixpkgs issue? You may consider creating an `out-link` to your Python environment, e.g. `nix-build -A python -o ~/myEnvs/mypython`. I suggest doing that in any case.

**Comment by mkocha2** [comment]
I ran `which python` and copy pasted the result in the file selection widget in PyCharm while using KDE5. This action took around 20 minutes.

**Comment by mkocha2** [comment]
Regarding whether or not this is a NixOS issue or not, fact is that NixOS uses the filesystem in a way that not many applications can cope with. 

As another example: `dolphin /nix/store` doesn't display a single file within 30 seconds. 

One could say that HDDs are not supported on NixOS. I.e., you are required to buy a high IOPS device in order to use NixOS, but otherwise this is undesirable.

**Comment by FRidh** [comment]
So, if `which python` refers to a store path (e.g. because you're in a Nix shell with Python), then yes, it takes very long. This is, however, a PyCharm issue. In any case, don't refer to store paths directly. Instead, create an `out-link` like I wrote in my previous post. That link you can put anywhere you want on your filesystem, and it won't be garbage-collected.

**Comment by mkocha2** [comment]
@FRidh I am using `nix-shell` (and don't use nix-build at all), which doesn't have a `-o` option. What should I do in that case?

**Comment by FRidh** [comment]
Use `nix-build` to build whatever expression you use to create an environment. E.g., if you have a `env.nix` with 
```
with import <nixpkgs> {};

python3.withPackages(ps: with ps; [
  numpy
  notebook
])
```
then you could run `nix-build env.nix -o myenv` and then it will create a link at `myenv`. This link you can then use in PyCharm.
