### ISSUE TITLE
Arrow keys don't work in konsole, yakuake

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#29951]
## Issue description
The arrow keys, and also Home, End etc. don't work in konsole or yakuake.

Pressing them does nothing - in particular it does *not* print an escape code, which makes me think that this isn't a `TERMINFO` problem.

I *am* using these from XFCE, rather than KDE, but I would hope that that would be supported.

### Steps to reproduce

Install konsole. Try to use the arrow keys.

## Technical details

* System: 18.03pre116572.9824ca6975 (Impala)
* Nix version: 1.11.15
* Nixpkgs version: 18.03pre116572.9824ca6975
* Sandboxing enabled: yes

**Comment by FRidh** [comment]
I think it was @edolstra that mentioned this on the mailing list as well. Did you find a solution?

**Comment by edolstra** [comment]
I didn't, I switched to Plasma.

**Comment by michaelpj** [comment]
Possibly relevant: running `showkey` I get output for arrow keys, but nothing when running `showkey -a`.

**Comment by qknight** [comment]
i switched to xfce4-terminal but we need to fix this, konsole is rather important for us.

**Comment by michaelpj** [comment]
I also switched to Plasma, where it works.

One thing I think I discovered when trying to debug this is that it is *not* a `TERM` issue, or anything relating to interpretation of escape sequences. Rather than getting uninterpreted escape sequences, it appears that konsole just doesn't get sent the sequences at all.

**Comment by qknight** [comment]
@michaelpj xev started from konsole can still get cursor keys, konsole still can't receive them.

**Comment by mbertolutti** [comment]
The navigation keys are not working because konsole can't find the data file for the [default keyboard translator](https://github.com/KDE/konsole/blob/d507d3381e52b16507a81e679119429f92a95a12/src/KeyboardTranslatorManager.cpp#L200).

As a temporary workaround, I manually placed [default.keytab](https://github.com/KDE/konsole/blob/master/data/keyboard-layouts/default.keytab) in my home directory's `.kde/share/apps/konsole/`.

For a real fix, konsole would need to look at the correct path in the nix store. Right now it relies on `QStandardPaths::GenericDataLocation`. Maybe this should include `/nix/store/<application>/share`?

**Comment by qknight** [comment]
@mbertolutti this solution is awesome, can you also fix the problem in nixpkgs? afterwards contact me to get a reward!
