### ISSUE TITLE
Package request: gg

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#299856]
**Project description**

`gg` is a GUI for jj users. It is a Tauri app.

I believe that @Khionu is working on some stuff to assist packaging Tauri apps in nixpkgs. I wanted to open a 'tracking' issue, maybe to coordinate efforts and keep an eye on things, rather than constantly bugging them in the JJ Discord.

(jj is awesome, if you're reading this, you might find it neat to checkout!)

**Metadata**

* homepage URL: https://github.com/gulbanana/gg
* source URL: https://github.com/gulbanana/gg
* license: apl2
* platforms: unix, linux, darwin, ... ??

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by chewblacka** [comment]
New version [0.16.0](https://github.com/gulbanana/gg/releases/tag/v0.16.0) has just come out. But my build still fails with:

```
error: failed to run custom build command for `jj-cli v0.16.0`

Caused by:
  process didn't exit successfully: `/build/source/src-tauri/target/release/build/jj-cli-28b6a5107c2375a4/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /build/cargo-vendor-dir/jj-cli-0.16.0/build.rs:30:10:
  called `Result::unwrap()` on an `Err` value: CargoMetadata { stderr: "error: failed to get `chrono` as a dependency of package `jj-cli v0.16.0 (/build/cargo-vendor-dir/jj-cli-0.16.0)`\n\nCaused by:\n  failed to load source for dependency `chrono`\n\nCaused by:\n  Unable to update registry `crates-io`\n\nCaused by:\n  failed to update replaced source registry `crates-io`\n\nCaused by:\n  failed to read root of directory source: /build/cargo-vendor-dir/cargo-vendor-dir\n\nCaused by:\n  No such file or directory (os error 2)\n" }
```

Anyone got any ideas?

**Comment by scoiatael** [comment]
I ran into similar problem when trying to add build `gg` using [buildRustPackage](https://github.com/scoiatael/dotfiles/blob/master/packages/gg/default.nix).

FWIW I believe problem is in the duplicate `cargo-vendor-dir` (i.e. `/build/cargo-vendor-dir/` is a valid directory, `/build/cargo-vendor-dir/cargo-vendor-dir` is not).

This is caused by paths in cargo config being relative to config itself (https://doc.rust-lang.org/cargo/reference/config.html#config-relative-paths).

Temporary fix is to patch `directory` in `.cargo/config` with an absolute path, but a long-term solution would be to fix https://github.com/NixOS/nixpkgs/blob/7f13fd4e7960fe2cefaba1048ea1885014311635/pkgs/build-support/rust/import-cargo-lock.nix#L234 

---

(Incomplete) solution can be found at https://github.com/scoiatael/dotfiles/blob/master/packages/gg/default.nix - I'm right now stuck at building frontend part, due to problems with rollup missing its native dependencies:

```
Executing npmBuildHook

> gg@0.15.3 build
> vite build

/private/tmp/nix-build-gg-ui-unstable-0.15.3.drv-22/source/node_modules/rollup/dist/native.js:87
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```
which I believe is tracked [here](https://github.com/NixOS/nixpkgs/issues/294183).

**Comment by jcollie** [comment]
@scoiatael any chance for an update to 0.20.0?

**Comment by scoiatael** [comment]
@jcollie done: https://github.com/scoiatael/dotfiles/blob/0963b3428506092ad9a6c1725eb87d136f0fca98/packages/gg/default.nix

notes:
- custom npm package-lock is no longer needed (upstream works fine), so the build should now work even on linux / x64 darwin,
- there is still an issue with upstream Cargo.{toml,lock} - for some reason cargo tries to download new deps during build process. I suspect this is caused by tauri enabling certain features, which add extra dependencies during build and/or `jj` using custom [build](https://github.com/martinvonz/jj/blob/v0.21.0/cli/build.rs). But I don't know Rust build process enough to suggest a solution other than declaring these extra dependencies outright in Cargo.toml and regenerating lockfile to reflect that.
- I'm no longer using `jj` daily so not a good fit for maintaining that ;)

**Comment by pluiedev** [comment]
Lemme take another shot at this as it was just updated to use Tauri v2
