### ISSUE TITLE
nixos-container should use systemd-run -M <machine>

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#30019]
## Issue description

Currently nixos-container.pl uses `nsenter` to attach to containers.
However this methods miss out some container context and does not create a pseudo tty.
`systemd-run -M <container> --pty` is the offical method recommended by upstream: https://github.com/systemd/systemd/issues/4215
Previous there was an attempt to use `machinectl shell`, which does not return the exit code.

cc @wlhlm

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

**Comment by danbst** [comment]
Previous opinion on this: https://github.com/NixOS/nixpkgs/pull/18825#issuecomment-288128971

**Comment by Mic92** [comment]
Can be fixed by adding `--pty`.

**Comment by wlhlm** [comment]
`nsenter` and `su` don't give the complete container environment, so I'd consider `nixos-container run` and `nixos-container shell` broken as of now.

I agree with using `systemd-run` for `nixos-container run` and `machinectl shell` for `nixos-container root-login`, which is also what systemd themselves recommend. From the [`machinectl(1)` manpage](https://www.freedesktop.org/software/systemd/man/machinectl.html):

> Note that systemd-run(1) with its --machine= switch may be used in place of the machinectl shell command, and allows non-interactive operation, more detailed and low-level configuration of the invoked unit, as well as access to runtime and exit code/status information of the invoked shell process. In particular, use systemd-run's --wait switch to propagate exit status information of the invoked process. Use systemd-run's --pty switch for acquiring an interactive shell, similar to machinectl shell. In general, systemd-run is preferable for scripting purposes. However, note that systemd-run might require higher privileges than machinectl shell.

There is still a problem with `--pty` merging `stdin`/`stdout` as @edolstra [pointed out](https://github.com/NixOS/nixpkgs/pull/18825#issuecomment-333580999), but I don't think that it's currently resolvable, since other container tools also just use a pty.

**Comment by Mic92** [comment]
It is possible with the latest systemd release: https://github.com/systemd/systemd/blob/master/NEWS#L102
However I still don't think exposing raw stdin/stdout by default is a good idea for the reason I have given here: https://github.com/NixOS/nixpkgs/pull/18825#issuecomment-333611986

**Comment by Mic92** [comment]
**UPDATE** I just read it possible to use `--pipe` and `--pty` in conjunction and `systemd-run` uses the more appropriate depending on the context.
