### ISSUE TITLE
Package request: coppwr

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#300268]
**Project description**

Low level control GUI for the PipeWire multimedia server.

**Metadata**

* homepage URL: https://github.com/dimtpap/coppwr
* source URL: https://github.com/dimtpap/coppwr
* license: gpl3
* platforms: linux

**Comment by imadnyc** [comment]
https://github.com/dimtpap/coppwr/issues/9#issuecomment-2008647534 Turns out someone already packaged this. @Ravenz46, do you mind making the PR? I don't want to take credit for your work. The only thing I could think to change is for flags for the cargo buildfeatures.

**Comment by imadnyc** [comment]
I could submit the PR on your behalf, but you wouldn't be able to be a maintainer unless you add yourself to the list. See https://github.com/NixOS/nixpkgs/tree/e047f577a9cadf8cea4b53c62f56c41ca91303c4/maintainers. 

If you want git to be easy, I recommend [lazygit](https://github.com/jesseduffield/lazygit). I use this even though I can use the commands because it makes it easier to understand.

**Comment by RAVENz46** [comment]
@imadnyc 
Okay, I will try to create PR.

**Comment by RAVENz46** [comment]
Done.
Wait until it merge to nixos-unstable.
https://nixpk.gs/pr-tracker.html?pr=300649

**Comment by TanvirOnGH** [comment]
Awesome. Thank you so much for your effort. @RAVENz46
