### ISSUE TITLE
Build failure: rocblas times out on hydra

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#301937]
### Build log

https://hydra.nixos.org/build/254878615

### Notify maintainers

 @NixOS/rocm-maintainers  @mschwaig 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mschwaig** [comment]
The build is quite flaky recently, yes. Sometimes it fails, sometimes it succeeds:
https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.rocmPackages.rocblas.x86_64-linux/all
When I looked last week I think I saw more timeouts than now.

My guess is that it times out because `composable_kernel` is not cached, and that this issue will go away once https://github.com/NixOS/nixpkgs/pull/299589 is merged.

**Comment by Tungsten842** [comment]
> The build is quite flaky recently, yes. Sometimes it fails, sometimes it succeeds: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.rocmPackages.rocblas.x86_64-linux/all When I looked last week I think I saw more timeouts than now.
> 
> My guess is that it times out because `composable_kernel` is not cached, and that this issue will go away once #299589 is merged.

Are you sure that that is actually the cause? It looks like that sometimes hydra is a little slower at building the package, and it exceeds the two hours timeout. Raising the hydra timeout should be enough to always fix these kind of build failures.
