### ISSUE TITLE
KDE5 file transfer notifications dissapeared

### ISSUE THREAD

**Issue by frigatefreedom** [NixOS/nixpkgs#30281]
## Issue description
Some time ago I've noticed, that when I move/paste/remove files and folders there are no any notifications about progress anywhere. 

I've tried to use new empty user to log in KDE5, but there were still no any progress notifications.

### Steps to reproduce

1. Copy file/folder
2. Paste it anywhere

## Technical details

* System: NixOS 17.09.1535.1fdca25ee8 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.1535.1fdca25ee8"
* Sandboxing enabled: build-use-sandbox = false
* KDE Plasma version 5.10.5

**Comment by joepie91** [comment]
Same here, also on NixOS 17.09. I'm unsure when it broke for me.

**Comment by dufresnep** [comment]
Will try to summarize info I found, even if it did not helped me yet.

It does not seems that the transfer info come from Dolphin, but rather somehow by Plasma itself.

"But the KDE devs are planning to extend the functionality to many of the applications included in the KDE Applications software suite, such as Dolphin, which will display the file transfer progress in the Task Manager.", Jan 2016, from:
http://news.softpedia.com/news/kde-plasma-5-6-to-feature-unity-launcher-support-media-controls-in-task-manager-498766.shtml

The problem seems to exist for a long time and be relatively complex:
https://marc.info/?l=kfm-devel&m=146559488013309&w=2

The preceding thread goes to suggest a specific commit might have caused the problem:
http://commits.kde.org/plasma-desktop/e284e9dc17051f22d05985e218fa44ddaba78de5
Taken from:
https://marc.info/?l=kfm-devel&m=146547703910982&w=2

"Both the System Tray track and the Task manager progress need to be disabled before the window for the file transfer progress is available - earlier KDE"
https://forum.kde.org/viewtopic.php?f=224&t=135264#p361971

**Comment by aanderse** [comment]
@frigatefreedom this appears to be fixed for me on 18.09. Can you please confirm and close?
