### ISSUE TITLE
NixOS question: How is NIXOS_EXTRA_MODULE_PATH meant to work?

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#30376]
`nixos/lib/eval-config.nix` references `NIXOS_EXTRA_MODULE_PATH`, and sticks the import of the specified file into a list. https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/eval-config.nix#L31

This means you can only have one extra module inside of `extraModules`. Is this intentional? The name of `extraModules` makes me think it just got messed up at some point.

I was expecting to need to supply a path to a file like `nixos/modules/module-list.nix` with a list of modules. This would work if the import wasn't being wrapped in a list, like it originally was:

https://github.com/NixOS/nixpkgs/commit/b609ff4fcf48b2124d94bf1052c303a36c8cabf1

**Comment by nbp** [comment]
with a `default.nix` being:
```nix
{ imports = import ./module-list.nix; }
```

**Comment by corngood** [comment]
@nbp Are you saying that should work?  I'm also unable to do more than import a single module, but maybe I'm missing something.

**Comment by nbp** [comment]
I just look at the code, and the earliest version using the environment variable probably never worked because this would imply getting a list out of an environment variable, which returns a string.

The example I gave was just a way to show that if you have a the ability to load a single module, then you can load any number of modules that you want.

**Comment by corngood** [comment]
Ah, I misunderstood how `imports` works.  Thanks!
