### ISSUE TITLE
freshrss: it returns `Error during context user init!`

### ISSUE THREAD

**Issue by honnip** [NixOS/nixpkgs#303965]
### Describe the bug
Unable to use freshrss. It returns the error `Error during context user init!`.

### Steps To Reproduce

```nix
{
  services.freshrss = {
    enable = true;
    baseUrl = "http://localhost";
    authType = "none";
  };
}
```
Try http://localhost, be redirected to http://localhost/i/?rid=abcd1234, see the error

### Expected behavior
It should run without errors.

### Notify maintainers
@etu  @stunkymonkey @mattchrist, thank you all for maintaining this module

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.2-zen2, NixOS, 24.05 (Uakari), 24.05.20240410.1042fd8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/r1g09wfd968168f6drdl7agfaf3msik4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mattchrist** [comment]
@honnip I think this issue is happening because the default user isn't being created by the 'freshrss-config' service when authType none is specified.

I'll work on a PR to fix this shortly.

In the meanwhile, I think a workaround would be to start freshrss with authType form configured once, to initialize the default user, then switching to authType none afterwards.
