### ISSUE TITLE
ollama fails to run: read only file system

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#304531]
### Describe the bug

```
апр 16 14:42:44 nixos systemd[1]: Started Server for local large language models.
апр 16 14:42:44 nixos ollama[19468]: Error: rename /mnt/nvme/ollama/models/blobs/sha256:04c54021011e980006d7b8cd0d441d53256f7b1cd5ea49271b134e0adbeb1008 /mnt/nvme/ollama/models/blobs/sha256-04c54021011e980006d7b8cd0d441d53256f7b1cd5ea49271b134e0adbeb1008: read-only file system
апр 16 14:42:44 nixos systemd[1]: ollama.service: Main process exited, code=exited, status=1/FAILURE
апр 16 14:42:44 nixos systemd[1]: ollama.service: Failed with result 'exit-code'.
```

### Steps To Reproduce
1. Enable ollama service
2. Set the model dir

### Expected behavior

Ollama should work, files and directories have rw permissions for anyone and the file system is not read-only.

It used to work before an update.

### Notify maintainers

@abysssol @onny

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5, NixOS, 24.05 (Uakari), 24.05.20240410.1042fd8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.21.2`
 - channels(root): `"nixos"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/store/r1g09wfd968168f6drdl7agfaf3msik4-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abysssol** [comment]
Could you try manually renaming the file to see if you get the same error? If you still get the error, the problem is probably with your system config. If you don't get the error, the problem could be with the ollama binary, or with the service config.
``` sh
mv /mnt/nvme/ollama/models/blobs/sha256:04c54021011e980006d7b8cd0d441d53256f7b1cd5ea49271b134e0adbeb1008 /mnt/nvme/ollama/models/blobs/sha256-04c54021011e980006d7b8cd0d441d53256f7b1cd5ea49271b134e0adbeb1008
```

By the way, the reason it's trying to rename the files is due to a change in [release 0.1.30](https://github.com/ollama/ollama/releases/tag/v0.1.30).

> #### Important change
>
> For filesystem compatibility, Ollama has changed model data filenames to use `-` instead of `:`. This change will be applied automatically. If downgrading to 0.1.29 or lower from 0.1.30 (on Linux or macOS only) run:
>
> ``` sh
> find ~/.ollama/models/blobs -type f -exec bash -c 'mv "$0" "${0//-/:}"' {} \;
> ```

**Comment by suhr** [comment]
Renaming files solves the problem of starting ollama, but does not solve the overall problem. I can't install a new model, for example.

**Comment by abysssol** [comment]
I found what the problem is. The ollama service has `DynamicUser = true;` set, which creates a new user for the service and enables some sandboxing that includes making most of the filesystem read-only.

I'm not sure at the moment the best way to fix this without compromising on security, so I'll do some more research on how systemd works, and any relevant options. At worst, I should be able to create an option that disables this sandboxing entirely. If you have any suggestions, I'd be happy to hear them.

**Comment by abysssol** [comment]
In the meantime, a temporary workaround that I think should work is this nixos config:
``` nix
systemd.services.ollama.serviceConfig.DynamicUser = lib.mkForce false;
```
