### ISSUE TITLE
Jetbrains Pycharm Community version mismatch

### ISSUE THREAD

**Issue by pedohorse** [NixOS/nixpkgs#304755]
### Describe the bug
Package `jetbrains.pycharm-community` claims to be version 2024.1, but actually is 2023.3 in branches master and nixos-unstable (other branches not checked)

### Steps To Reproduce
1.  just run the package's binary, for example with 
    - `nix run nixpkgs/nixos-unstable#jetbrains.pycharm-community`
    - `nix run nixpkgs/master#jetbrains.pycharm-community`

### Expected behavior
expecting 2024.1 version of pycharm community to run, but actually 2023.3 version starts

### Notify maintainers

@GenericNerdyUsername 
@tymscar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.84, NixOS, 23.11 (Tapir), 23.11.20240405.72da83d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/8mk40j3mfrvndrnh89azngcgdgr1fidi-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GenericNerdyUsername** [comment]
are you looking for `jetbrains.pycharm-community-bin`?

**Comment by pedohorse** [comment]
In nixos stable branches there used to be only `jetbrains.pycharm-community`,  
`jetbrains.pycharm-community-bin` is something new for me.

I see that now first one now claims to be built from source, second one claims to be patched binaries.

So then `jetbrains.pycharm-community-bin` is usable for me, yes,

But it doesn't change the fact that `jetbrains.pycharm-community` (and `jetbrains.pycharm-community-src`) package claims to be 2024.1, but actually is 2023.3.2

**Comment by jacekszymanski** [comment]
The same issue with `idea-community`, `-bin` package is also OK.

**Comment by dshatz** [comment]
It seems I am also affected. 

symlink of idea-community points to a directory named with the latest version from nixos-unstable.
But what actually launches is the version from nixos-stable.

**Comment by opl-** [comment]
After looking into this... no surprise the wrong version starts. The `idea-community-src` package is built from [source/default.nix](https://github.com/NixOS/nixpkgs/blob/0abc80da7fccfe6104ec9657c343ac4229ace612/pkgs/applications/editors/jetbrains/source/default.nix), which hasn't been updated in 6 months! The `pycharm-community-src` (with an `pycharm-community` alias on Linux) package has the same problem.

The reason it's tagged with the wrong version is because the version is taken from `versions.json`, with no checks or guarantees that the version in sources matches.

(I think this is related to symptoms from #281648. While the entry point is different (nix-shell/nix-env), the times at which people mention the symptoms changing or working workarounds kinda lines up with [when](https://github.com/NixOS/nixpkgs/commits/master/pkgs/applications/editors/jetbrains/source) the sources file was updated, lol.)

**Comment by GenericNerdyUsername** [comment]
Sorry, I've had some life stuff going on and haven't been/won't be able to contribute for a while. I will continue at some point, but not in the near future

**Comment by MattSturgeon** [comment]
I think one of the core issues here is that [`mkJetBrainsProduct`](https://github.com/NixOS/nixpkgs/blob/a73246e2eef4c6ed172979932bc80e1404ba2d56/pkgs/applications/editors/jetbrains/default.nix#L57-L78) blindly inherits the `version` from `bin/versions.json`.

This means we don't notice when the src-package is out of date; it _claims_ to be the same version as the bin-package.

`source/build.nix` does actually set `version = buildVer` (which may not be perfect, since that looks like `243.22562.145` instead of `2024.3.1`), but this is then overridden by `mkJetBrainsProduct`.

If no one beats me to it, I'll try and come up with a PR to fix this.
