### ISSUE TITLE
pcmanfm-qt: no icons shown

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#306741]
### Describe the bug
Since #305107 `pcmanfm-qt` doesn't show icons anymore. It worked before the update and i didn't change anything related to icons/themes (i have them set by `home-manager`).

Thumbnails of pictures are still shown.

### Steps To Reproduce
1. just launch `pcmanfm-qt`

### Expected behavior
`pcmanfm-qt` showing icons for directories, file types etc.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/64630479/836d832c-833d-4b21-bb38-d461f1076598)

### Notify maintainers
@romildo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7, NixOS, 24.05 (Uakari), 24.05pre615930.572af610f615`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eljamm** [comment]
It should also be noted that the program runs slow because it keeps trying (and failing) to load the icons. This can be seen by running `strace pcmanfm-qt` as it shows a lot of `access("...", F_OK) = -1 ENOENT (No such file or directory)` messages.

However, when I launch pcmanfm-qt from my app launcher (albert) the icons show up normally and everything works fine.
To be more precise I'm using an older version of albert (0.22.17) as it's currently broken from a recent update ([more details here](https://github.com/NixOS/nixpkgs/issues/305081)).
