### ISSUE TITLE
mopidy: pipewire connection fails

### ISSUE THREAD

**Issue by codebam** [NixOS/nixpkgs#307061]
### Describe the bug

```
Apr 26 16:39:27 nixos mopidy[405711]: [ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
Apr 26 16:39:27 nixos mopidy[405711]: WARNING  2024-04-26 16:39:27,945 [405711:MainThread] mopidy.audio.gst
Apr 26 16:39:27 nixos mopidy[405711]:   GStreamer warning: Failed to connect: Connection refused
```

### Steps To Reproduce
1. enable mopidy with `services.mopidy.enable = true;`
2. try to play any song in ncmpcpp
3. doesn't play

### Expected behavior

mopidy would be able to connect to pipewire

### Notify maintainers

@fpletz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.6-zen1, NixOS, 24.05 (Uakari), 24.05.20240424.8a30b52`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/s6dwp581gngnw81h5qn52h2nqb70cvz9-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by GangolfOvaert** [comment]
Note sure if its an NixOS issue here, because i have the same behavior on Arch aswell.

`Mai 05 18:07:36 laptop mopidy[4373]: [ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
Mai 05 18:07:36 laptop mopidy[4373]: WARNING  2024-05-05 18:07:36,974 [4373:MainThread] mopidy.audio.gst
Mai 05 18:07:36 laptop mopidy[4373]:   GStreamer warning: Failed to connect: Connection refused
Mai 05 18:07:37 laptop mopidy[4373]: ERROR    2024-05-05 18:07:37,678 [4373:MainThread] mopidy.audio.gst
Mai 05 18:07:37 laptop mopidy[4373]:   GStreamer error: Could not get/set settings from/on resource.`

**Comment by reinux** [comment]
Thought it was just me. Have you been able to run it in HM? I thought it might be because of user permissions, though I added `mopidy` to `audio` and that didn't seem to do it.
The service doesn't even seem to start when running in HM.

**Comment by fpletz** [comment]
Mopidy is run as a system service as its own user `mopidy` and thus has no access to the pipewire service which is by default started as a user service. You either need to run pipewire as a system service with `services.pipewire.systemWide` and add the `mopidy` user to the `pipewire` group or run mopidy via home-manager as a user service instead. It depends on your use case: Choose the system service on a server (and maybe even use alsa directly) or the user service via home-manager on a workstation.
