### ISSUE TITLE
k3s: update script is failing

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#308061]
### Describe the bug

k3s: update script is failing for 1.29.4+k3s1

> No auto update branch exists
> Old version 1.29.3+k3s1" not present in master derivation file with contents: [...]

### Steps To Reproduce

Logs:
* https://r.ryantm.com/log/k3s/2024-04-30.log
* https://r.ryantm.com/log/k3s_1_28/2024-04-27.log
* https://r.ryantm.com/log/k3s_1_27/2024-04-26.log

### Expected behavior
Bot should open a PR updating to 1.29.4+k3s1 successfully.

## Additional context
Works locally.

### Notify maintainers

@euank @yajo @Mic92

# When to close this PR

This PR should be closed once ryantm bot successfully suggest upgrade to K3s.

**Comment by euank** [comment]
Thanks for noticing and reporting it!

I looked into this a little, but I didn't figure out why it broke, here's my notes.

The error we see in the logs is from here:

https://github.com/nix-community/nixpkgs-update/blob/e2050fb126d1353d6c33b626a8aaf2067b7abe4c/src/Nix.hs#L227-L234

That's looking for the version in the attrPath, which it gets from here:

https://github.com/nix-community/nixpkgs-update/blob/e2050fb126d1353d6c33b626a8aaf2067b7abe4c/src/Nix.hs#L138

Which is:

```
$ EDITOR=echo nix edit k3s_1_28 -f
<nixpkgs>/pkgs/applications/networking/cluster/k3s/builder.nix
```

It's that value because nixpkgs pulls that value from `meta.position`, which is from `meta.description`:

https://github.com/NixOS/nixpkgs/blob/3fb8aadfd03c5fd44ca84a38a41def7c4631dfb3/pkgs/stdenv/generic/make-derivation.nix#L519-L520

https://github.com/NixOS/nixpkgs/blob/9a1693d3dd2bfc5cd150d41669059aa2a8a15455/pkgs/applications/networking/cluster/k3s/builder.nix#L83

So all k3s derivations have a meta.position of `builder.nix`, which doesn't have the version.

I'm able to reproduce this error myself, both with old nixpkgs-update versions and the current one, so I don't think a nixpkgs-update change broke this.

I guess next up is to git bisect nixpkgs itself, and see if that leads to enlightenment as to when this broke :smile: 

Alternatively, we could work around this by inverting it so the k3s derivations are the "root" (`k3s/1_28/default.nix` has `meta` set for `position`, and also contains the `versions.nix` stuff, and imports `builder`), instead of having `default.nix` import `versions.nix` + `builder.nix` and combine them.

I kinda like the idea of refactoring them to that structure anyway since it makes `nix edit` work correctly, and feels more "normal"

**Comment by superherointj** [comment]
The go compiler patch no longer cleanly merges. (Needs adaptation.)
And go compiler check only happens at runtime. Meaning, builds won't fail, but tests will fail.
Maybe that could influence the update script.

**Comment by endocrimes** [comment]
@superherointj https://github.com/NixOS/nixpkgs/pull/309110

**Comment by endocrimes** [comment]
FYI to folks running it manually: cd'ing into the k3s dir and running the update script by hand does work.
