### ISSUE TITLE
Graphite-related packages should move out of pythonPackages 

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixpkgs#30891]
## Issue description
I'm cleaning up `pythonPackages` and noticed that some dependencies of some `graphite` dependencies (`txamqp`) are several years out of date.

Since graphite is not a library it should move out of `pythonPackages` into it's own package. 

cc @rickynils @FRidh

**Comment by dotlambda** [comment]
I was just writing an issue about exactly this topic until I discovered there is already one, so I'm just copy-pasting my draft here.

---
In `python-packages.nix`, there are multiple packages related to Graphite, e.g. `graphite_web` and `whisper`. The current way of packaging them has some problems:

- The expressions are directly in `python-packages.nix` instead of in a subdir of `development/python-modules`.
- They use `name = graphiteVersion;`. This is possible but it would probably be better to just specify it for one package and refer to that from the other packages. Alternatively, we could have the version specified in every package and add an equality assertion somewhere.
- It should be checked which ones are really Python libraries and which ones are applications.
- They should generally brought up to date: `fetchPypi`, `pname`, ...

`pythonPackages.graphite_api` is also related to Graphite but does not use `graphiteVersion`. Why?
Anyway, the package should also be moved out of `python-packages.nix` and it would be nice to apply https://github.com/brutasse/graphite-api/pull/239/commits/842e93fc7d9736a3afa4cfbdeab39678ecf2c832 as a patch so it builds again and so we can get rid of `pythonPackages.flask_cache. See https://github.com/brutasse/graphite-api/pull/239.

cc maintainers @rickynils @offlinehacker

**Comment by dotlambda** [comment]
Btw, I vote to remove the remaining packages as there seems to be nobody having an interest in keeping them up-to-date and conformant with Nixpkgs conventions.

**Comment by adisbladis** [comment]
Yay! Great work @basvandijk!
