### ISSUE TITLE
mangohud: Failed to initialize PMU! (Permission denied)

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#309034]
### Describe the bug

For Intel dGPUs, `mangohud` requires `CAP_PERFMON` in order to access GPU utilization.

### Steps To Reproduce

1. Install an Intel dGPU, such as the Arc ~~largest civilian airliner~~ A380
2. Install `mangohud` and `vkcube`
3. Run `mangohud vkcube`
4. See the following relevant logs:

```
Selected GPU 0: Intel(R) Arc(tm) A380 Graphics (DG2), type: DiscreteGpu
Failed to initialize PMU! (Permission denied)

When running as a normal user CAP_PERFMON is required to access performance
monitoring. See "man 7 capabilities", "man 8 setcap", or contact your
distribution vendor for assistance.

More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
```

### Expected behavior

This error should not happen, and `mangohud` should be able to read GPU utilization.

### Screenshots

![Screenshot from 2024-05-04 07-46-43](https://github.com/NixOS/nixpkgs/assets/45835846/6dadcb45-3664-4f35-adaf-82f3d08fe84a)

As you can see, GPU utilization information is not being displayed.

### Additional context

*N.A.*

### Notify maintainers

CC @kira-bruneau @zeratax

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[gavin@gavin-gaming-desktop:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.30, NixOS, 24.05 (Uakari), 24.05.20240503.e96601e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3gcgx970vsz0h89kjm3nwixb74b03g7r-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kira-bruneau** [comment]
Hi @Pandapip1! It looks like there's an upstream issue tracking this: https://github.com/flightlessmango/MangoHud/issues/1082. 

I'll look into this more to see how we can get this working, but I don't think this is something we can solve directly in the mangohud package. We'll need to use a separate NixOS module for `intel_gpu_top` since it'll require a security wrapper to enable `CAP_PERFMON`.

After creating a intel-gpu-tools module that sets the capabilities, I'm pretty sure we'll be able to get it working through something like this:
```nix
programs.intel-gpu-tools.enable = true;
```

but this would need to be used in addition to installing mangohud, and wouldn't just work automatically if you installed mangohud by itself.

**Comment by kira-bruneau** [comment]
Was able to get this working 😊:

```nix
{
  security.wrappers.intel_gpu_top = {
    source = "${pkgs.intel-gpu-tools}/bin/intel_gpu_top";
    capabilities = "cap_perfmon+ep";
    owner = "root";
    group = "root";
  };
}
```

Now just need to add this to a new module.
