### ISSUE TITLE
Derivation platform checking compares against wrong machine

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#30902]
## Issue description

The logic in `pkgs/stdenv/generic/check-meta.nix` for checking the `meta.platforms` attribute currently compares `meta.platforms` against the `stdenv.system` attribute. In my cross-compilation environment `stdenv.system` is the double of my build platform, `x86_64-linux`.

It seems to me like this should rather be compared against `stdenv.hostPlatform.system`. Unfortunately, this attribute has slightly different semantics than `stdenv.system`. For instance, in the case of `armv7l-hf-multiplatform` it is `arm-linux` whereas the value expected by `uboot` is something like `armv7l-linux`. 

How much detail should `meta.system` capture?

Pinging @Ericson2314.

**Comment by Ericson2314** [comment]
1. It's a Nix rule that the `system` field of each derivation is the build platform, as a Nix-style 2-component string. No changing that just yet.

2. `stdenv.system` can't go away so long is `stdenv` is a derivation, but I'd like `stdenv` to be a plain attribute set. [See https://github.com/NixOS/nixpkgs/pull/30549#issuecomment-342247583 for other reasons why.]

3. https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/make-derivation.nix#L171-L173 we can at least make it a bit saner on cross my doing `inherit (stdenv.hostPlatform) system;` there instead. This will break some cross packages, so I'd like to do after we merge your https://github.com/NixOS/nixpkgs/pull/30882 and all the cross tests are fixed (if you fixed cross-built gcc then they will be, yay!).

4. `arm-linux` vs `rmv7l-linux` has to do with me changing everything https://github.com/nixos/nixpkgs/tree/master/lib/systems/ code. `armv7l-linux` is nicer than `arm-linux`, but if Nix expects that latter for all 32-bit arm linux native builds (Nix itself won't care for cross), we have a problem and that cross build will have to be adjusted accordingly.

5. I don't like how `meta.platforms` works by exhaustive enumeration, when platforms can be tweaked in such fine-grained ways. I suppose the huge space of cross platforms quotiented to just the `system` field isn't so big, but I still rather do arbitrary predicates or something, as if the space of platforms really was infinite so that was the only way.
