### ISSUE TITLE
Using ACME certificates in Nginx: "At the moment you still have to restart Nginx after the ACME certs arrive."

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#30945]
This is a quote from [the manual](https://nixos.org/nixos/manual/index.html#idm140737316179840):

> At the moment you still have to restart Nginx after the ACME certs arrive.

This looks like a todo item, but I couldn't find an issue for it, so I'm creating that issue here.

I also have a question: Does this mean you have to restart Nginx the *first* time to ACME certs arrive, or *every* time they renew? And do I understand correctly that this recurring manual task kind of defeats the purpose of using ACME while this issue is still open? (Should we update the manual in the meantime to clarify that the ACME feature isn't really usable yet?)

**Comment by globin** [comment]
As far as I'm aware and this includes me using ACME a lot, this no longer is necessary, can you open a PR removing that line?

**Comment by chris-martin** [comment]
Sure thing

**Comment by disassembler** [comment]
Thanks for the doc fixes!

**Comment by fadenb** [comment]
@globin: I just had had a case where the LE certificate was renewed but the change was not picked up by nginx (until I manually restarted nginx) (few weeks old 17.09). Seems like this is still necessary.

**Comment by chris-martin** [comment]
@fadenb Just to be sure, are you letting Nix generate the relevant nginx config (via setting the `enableACME` option)? I ask because I had that problem for a while because I didn't know you had to do that, and enabling this seems to be what's supposed to cause nginx to reload when certs arrive https://github.com/NixOS/nixpkgs/blob/41371512e2da3cf8d98d79fcca4649a976e9f52b/nixos/modules/services/web-servers/nginx/default.nix#L589

**Comment by fadenb** [comment]
@chris-martin: Yup, nginx config is generated with services.nginx.virtualHosts... and enableAcme is true for all 3 vhosts. All the acme stuff seems to be working fine and according to the logs nginx was reloaded:
```
Subject: Unit nginx.service has begun reloading its configuration
Defined-By: systemd
Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Unit nginx.service has begun reloading its configuration
---
Subject: Unit nginx.service has finished reloading its configuration
Defined-By: systemd
Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Unit nginx.service has finished reloading its configuration

The result is done.
---
Subject: Unit acme-graylog.logsrv.xyz.service has finished start-up
Defined-By: systemd
Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Unit acme-graylog.<removed>.xyz.service has finished starting up.

The start-up result is done.
```
(please ignore the unusual formatting as this is extracted from Graylog as the original journal entry was no longer available due to log rotation)


I can see no error/warning of any kind. Just a moment after nginx reload is completed the acme unit startup is completed so it looks ok but nginx was still using the old certificates. 
According to some quick research it should be sufficient to send SIGHUP to nginx which is exactly what is done at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/nginx/default.nix#L572 so I have no idea why it is not working.

This is the 2nd time this has happened to me. I dismissed the first one as I was unsure of the circumstances. It is quite hard to debug as one usually only notices the issue days(weeks) later when the certificate is expired.
