### ISSUE TITLE
Package request: picom-pijulius

### ISSUE THREAD

**Issue by ishaanpathak** [NixOS/nixpkgs#309522]
**Project Description**

An actively maintained picom fork that adds extended animation support.

**Metadata**

* homepage URL: https://github.com/pijulius/picom
* source URL: https://github.com/pijulius/picom
* license: mit, mpl-2.0
* platforms: linux

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by YvesStraten** [comment]
@ishaanpathak has been done, please check the pr I made

**Comment by YvesStraten** [comment]
One minute, I need to push the right branch

**Comment by YvesStraten** [comment]
@ishaanpathak has been done, please react onto the pr so that it is marked as being more important. Have a very nice day

**Comment by ishaanpathak** [comment]
Thanks a lot! Added the reaction to the PR too.

**Comment by andreaugustoaragao** [comment]
Is this working? I have changed my picom configuration to use this package but none of the new options work.

**Comment by YvesStraten** [comment]
It should be working, at least it does in my configuration, which includes the package before I ported it to nixpkgs. If you could state what problem you are having, that would be nice. Unfortunately I won't have much of a way to help you because the IC of my Linux laptop is fried, meaning that currently I have no way of being on Linux right now to test anything
