### ISSUE TITLE
cannot change UI language in firefox and thunderbird

### ISSUE THREAD

**Issue by castilma** [NixOS/nixpkgs#30962]
## Issue description
I can't add UI languages or new dictionaries to thunderbird.

### Steps to reproduce
Firefox: don't know how it is supposed to be changed.
Thunderbird:
1. Edit-> preferencs-> composition-> spelling-> Download More Dictionaries
2. On the opened site, search for your language (I tried german)  and try to install a dictionary or ui lang.
3. A: language pack: there is a note with a red, crossed through circle saying 'Works with Thunderbird 52.0 - 52.*' (I have earlybird 52.2.1). click on download. tab title changes to 'Loading ...' and a download dialog opens. i tried both: open with thunderbird and saving to disk. no matter what I do, the ui language stays the same.
3. B: dictionary: proceed like in 3A. still no way to change the dictionary language. (only english is offered)

## Technical details

* System: 17.03.1931.8b8977f9ff (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1931.8b8977f9ff"
* Sandboxing enabled: build-use-sandbox = false

**Comment by falsifian** [comment]
Not a complete answer, but a couple of notes about Firefox:

* I think you need to install the language pack and dictionary from [this page](https://addons.mozilla.org/en-US/firefox/language-tools/). In my case Canadian English wasn't listed, so I searched for and found [this unofficial one](https://addons.mozilla.org/en-US/firefox/addon/canadian-english-dictionary/?src=api).

* Once you have it installed, you may need to select it. For spelling, I right-clicked a text field, made sure "check spelling" was checked, and under "Languages" found that "English (Canada)" was already selected. For the UI language, there's some discussion [here](https://nixos.org/nix-dev/2013-January/010348.html) but I haven't tried it because I couldn't find a Canadian English UI pack.

**Comment by oyren** [comment]
Hey I also had the problem, here is my solution.
1. Download and Install the Language Pack and Dictionary.
2. Go to Edit>Preferences>Advanced> Config Editor
3. Search for general.useragent.locale and change it for example de-DE in favor german
4. Too change the default Spell checking language, go to Edit>Preferences>Composition>Spelling choose your language

**Comment by tohl** [comment]
https://github.com/NixOS/nixpkgs/pull/58197
allows specifying locale via override:
firefox-bin-unwrapped = super.firefox-bin-unwrapped.override {systemLocale = "ja";};

in the future, this could be extended to respect supportedLocales,
e.g. by installing firefox for each supportedLocale and then
wrapping the binary in shell script and dispatching
on LANG env var

not as nice as just putting the gettext translations in the right place,
but probably the easiest sollution for now

**Comment by cx405** [comment]
This line is the problem in [default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox-bin/default.nix):  
```
systemLocale = config.i18n.defaultLocale or "en-US";
...
source = stdenv.lib.findFirst (sourceMatches systemLocale) defaultSource sources;

```
while [beta_sources.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox-bin/beta_sources.nix) lists:
`locale = "ru";` and systemLocale is never "ru" in this example, but "ru_RU.UTF-8". So it always fallbacks to en_US.

This is not only "firefox-bin", but also "firefox-wrapper" / "firefox-esr".

**Comment by alanpearce** [comment]
Also happens with devedition. And, to make things worse, firefox locales use hyphens, whilst locale settings use underscores. `en-GB` vs `en_US`.

**Comment by FliegendeWurst** [comment]
Works for me on NixOS 21.11
