### ISSUE TITLE
Vesktop settings missing in vesktop menu

### ISSUE THREAD

**Issue by sylvi-3** [NixOS/nixpkgs#310227]
### Describe the bug
When using Vesktop, installed as a nix package, (`pkgs.vesktop`) there seems to be no evidence of vencord being installed at all. Running the `vesktop` command will, indeed, start up the app, including the custom vencord startup animation, but there are no settings for custom CSS, plugins, or vencord-specific options.

### Steps To Reproduce
1. Use the unstable branch of nixpkgs to install `pkgs.vesktop`
2. Run the `vesktop` command to start up the application
3. Attempt to edit the vencord settings in-app

### Expected behavior
There is supposed to be a section in the discord settings menu with the title "Vencord", where plugin settings, custom CSS, and other new options are available.

### Screenshots
As you can see, the Vencord settings in the nixpkgs version of Vesktop are missing:
![20240508-1921-screenie](https://github.com/NixOS/nixpkgs/assets/167730518/8380c1b5-3d92-4263-8131-faedd7db8246)

However, the Flatpak of Vesktop works properly, which I think is evidence that this is a nixpkgs issue.
![20240508-1922-screenie](https://github.com/NixOS/nixpkgs/assets/167730518/251a8e7c-a31a-4517-976b-119adef9308a)

### Additional context
I am installing `pkgs.vesktop` using `home.packages`, although I don't think this makes any significant difference.

### Notify maintainers
@getchoo 
@Scrumplex 
@vgskye 
@pluiedev 

### Metadata
The results of `nix-shell -p nix-info --run "nix-info -m"`:
```
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.27, NixOS, 24.05 (Uakari), 24.05.20240416.5672bc9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3kwj19dbdfxnjbcns4hw307ylhz3wgrm-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
Could you provied the startup log when running vesktop from a terminal

**Comment by sylvi-3** [comment]
@Scrumplex 
> Could you provide the startup log when running vesktop from a terminal

This is what it looks like when I run the `vesktop` command:
```
❯ vesktop

(electron:20410): Gtk-WARNING **: 13:16:08.048: Theme parsing error: gtk.css:7763:16: 'border-spacing' is not a valid property name
[20410:0509/131608.094073:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[20410:0509/131608.094087:ERROR:select_file_dialog_linux_portal.cc(286)] Failed to read portal version property
Error occurred in handler for 'VencordGetUpdates': Error: No handler registered for 'VencordGetUpdates'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78494)
    at WebContents.emit (node:events:514:28)
```
I'm on Hyprland, if that helps.

**Comment by Scrumplex** [comment]
I sadly can't reproduce this. Can one of you check the JavaScript console by pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>

**Comment by sylvi-3** [comment]
@Scrumplex 
> I sadly can't reproduce this. Can one of you check the JavaScript console by pressing Ctrl + Shift + I

What specifically do you want to see from this console?

**Comment by Scrumplex** [comment]
> @Scrumplex
> 
> > I sadly can't reproduce this. Can one of you check the JavaScript console by pressing Ctrl + Shift + I
> 
> What specifically do you want to see from this console?

There should be several log lines from Vencord. Perhaps there is some kind of error from Vencord too? I don't really know what to look for, as I don't know what's printed in there. I know that Discord already generates some errors by itself

**Comment by Ruediga** [comment]
This same problem is occuring to me on the newest release for the AUR, but not on NixOS, so this points towards it being a vesktop bug...

**Comment by getchoo** [comment]
yeah this seems to be a case of https://github.com/Vencord/Vesktop/issues/516. could those affected try disabling the system version of vencord by overriding the package? this can be done with `vesktop.override { withSystemVencord = false; }`

**Comment by Joshument** [comment]
> I sadly can't reproduce this. Can one of you check the JavaScript console by pressing Ctrl + Shift + I

There's a lot of errors in the log (mostly about stack size and reflection stuff) from Vencord, but I do specifically notice this:
`Patch by Settings had no effect (Module id is 202022): /\{section:([A-Za-z_$][\w$]*\.[A-Za-z_$][\w$]*)\.HEADER,\s*label:([A-Za-z_$][\w$]*)\.[A-Za-z_$][\w$]*\.Messages\.ACTIVITY_SETTINGS\}/
`

**Comment by Joshument** [comment]
> yeah this seems to be a case of [Vencord/Vesktop#516](https://github.com/Vencord/Vesktop/issues/516). could those affected try disabling the system version of vencord by overriding the package? this can be done with `vesktop.override { withSystemVencord = false; }`

I'm trying my best, but I can't seem to figure out how to override a package :/ maybe I'm dumb but I just cannot figure out how to do it in my configuration.nix, sorry

**Comment by pluiedev** [comment]
> > yeah this seems to be a case of [Vencord/Vesktop#516](https://github.com/Vencord/Vesktop/issues/516). could those affected try disabling the system version of vencord by overriding the package? this can be done with `vesktop.override { withSystemVencord = false; }`
> 
> 
> 
> I'm trying my best, but I can't seem to figure out how to override a package :/ maybe I'm dumb but I just cannot figure out how to do it in my configuration.nix, sorry

So in your `environment.systemPackages` or `users.users.<your name>.packages`, replace `vesktop` with `(vesktop.override { withSystemVencord = false; })`. The parens are necessary since otherwise Nix would parse that as two separate list items, `vesktop.override` and `{ withSystemVencord = false; }`, neither of which are valid packages.

**Comment by sylvi-3** [comment]
> (vesktop.override { withSystemVencord = false; })
I did this and it seems to have fixed the issue, the Vencord header in the settings is there now. I haven't tried out the plugins yet, but I didn't even notice when this issue originally developed, because there was no change in my plugin functions. Thank you so much !!

**Comment by getchoo** [comment]
this is definitely an issue with the nixpkgs ("system") version of vencord being outdated then

maybe we should set `withSystemVencord` to `false` by default? it would technically add some wasted space for users that have both discord installed with the vencord override *and* vesktop, but it can avoid issues like this

**Comment by pluiedev** [comment]
> this is definitely an issue with the nixpkgs ("system") version of vencord being outdated then
> 
> maybe we should set `withSystemVencord` to `false` by default? it would technically add some wasted space for users that have both discord installed with the vencord override _and_ vesktop, but it can avoid issues like this

I would argue that'd be better. The system Vencord is only updated whenever Ven feels like making an update (which is fairly arbitrary), and with how often Discord makes breaking changes (that can sometimes crash clients, see the whole RoleColorsEverywhere debacle), I personally feel like Nixpkgs is just going to be a bit too slow to catch up. 

Plus, the builtin updater works on a per-commit basis which would make catching up to upstream much easier, at the cost of not having a reproducible pinned version and of course, wasting space if you have both vanilla Discord + Vencord and Vesktop installed, but IMO it's not big enough to cause issues

**Comment by getchoo** [comment]
i've opened the above PR for this :)

**Comment by Vendicated** [comment]
> whenever Vee feels like bumping the version number (which is fairly arbitrary)

just to provide a little more insight... that's because as you have stated, our updater works on a per commit basis.

we use git commit hashes as version instead of a normal version number. 
we only use versions/tags to push a new update to the chrome web store, because it requires such versions. that's usually either immediately, whenever there's a bad breakage, or once a good amount of changes has accumulated. making more frequent tags isn't viable because google usually takes a day or two to approve updates, and while an update is pending you can't open a second one. the version numbers have 0 significance for anything but the chrome extension

proper versioning makes little sense in something like vencord because there are essentially just two versions at any time: up to date and outdated. using anything but latest version is not supported, because as soon as discord pushes an update to something that breaks some feature, we need to push a new update to fix it, and users optimally need this update immediately

vesktop itself is more stable because it is mostly self contained, so it uses proper versioning and using older versions is usually not a big deal

as for the file size... vencord's files total only a few megabytes, so it shouldn't be a big deal to have two copies on your system

personally i am not familiar with how nix handles things, but letting vesktop manage vencord itself would lead to a better user experience, exactly to prevent cases like this. it will never update without the user's consent (e.g. force an update). however, auto update is enabled by default (because most of our users are not that tech savvy so this is the best option for the majority of users as otherwise they don't update and then wonder why things are broken), so you might want to patch that to be disabled by default, it's just this one boolean https://github.com/Vendicated/Vencord/blob/main/src/api/Settings.ts#L80

if you have any questions or need help with something, you can always reach out to me, either here on github or (preferred) by just pinging me on discord. i appreciate that you guys are making vencord & vesktop available on nix, it's pretty cool!

**Comment by getchoo** [comment]
> personally i am not familiar with how nix handles things, but letting vesktop manage vencord itself would lead to a better user experience, exactly to prevent cases like this.

the PR above implements exactly this, so unless a user manually overrides the package this won't be an issue anymore

**Comment by getchoo** [comment]
closing as #310696 was merged
