### ISSUE TITLE
cabal.mkDerivation shouldn't copy over dist/

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#3112]
If we have `dist` in a Haskell project that nix copies over to the store, it won't properly re-build  and in the end the we end up with a `dist` directory that was there at copy time rather than the one created during package building.

This means that if you have `dist` and are depending on a project from source, you'll be in for a nasty surprise when the library stops to update even though it looks like the changes are being picked up by nix. See [this gmane thread](http://permalink.gmane.org/gmane.linux.distributions.nixos/13486) for some details and instruction to reproduce.

The best fix I can think of is to never copy or delete straight away the `dist` directory so that cabal can recreate it during build. Forcing recompilation or anything of the sort is sub-par as then we have space loss by copying over useless object files and whatnot.

**Comment by peti** [comment]
I'm closing this issue because it's been inactive for a couple of months. Please re-open if this is still a problem that needs to be addressed in Nixpkgs.

**Comment by Ericson2314** [comment]
Seems to me like the obvious thing to do is only `filterTree` with `.env`'s `src`. The default builder isn't cluttered for the pull-from-hackage default case, while anybody doing dev locally will be using nix-shell with `.env`. There's still room for error if you nix-shell, cabal-install and then nix-build, but that seems acceptable.

**Comment by Fuuzetsu** [comment]
Personally my own solution is to use `fetchgitLocal` which means dirty tree never causes spurious rebuilds of other projects and stuff like `dist` doesn't get copied. Of course there are cases where this doesn't do what you want but it works for me.

In general I agree with peti in that if someone really cares then they can just filter themselves when addressing the local dep.

**Comment by Ericson2314** [comment]
I take back "obvious". Even when developing a package, one might still want to use `nix-build` and `nix-shell` with a hackage package carries no risk, so just filtering with `.env`'s `src` doesn't cut it.

Perhaps cabal2nix could add the filter/`fetchgitlocal` when passed a local path? It is precisely when `src` is local the problems may arise (It's not nix's fault if you commit dist), and since the filter is the local shell.nix/default.nix and not hidden away in the Haskell infrastructure, the user can hardly miss it.

**Comment by peti** [comment]
See https://github.com/NixOS/cabal2nix/issues/112.
