### ISSUE TITLE
Color Palette Not Showing Colors

### ISSUE THREAD

**Issue by Mash-em** [NixOS/nixpkgs#311693]
### Describe the bug
Upon Changing theme to System Theme The Color Palette not showing colors clicking on individual color still changes the color.

### Steps To Reproduce
1. Change gtk4 theme to Dracula

### Expected behavior
Normal Color Palette with all colors.

### Screenshots
![swappy-20240514_215922](https://github.com/NixOS/nixpkgs/assets/169830207/efe187fb-f7ae-4f2a-b831-92637a664d9c)

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Mash-em** [comment]
wrong place my bad

**Comment by gepbird** [comment]
I was recently messing around with themes and encountered the exact same issue in rnote.
Using the adw-gtk3 package, gtk-4.0/gtk.css imports gtk-3.0/libadwaita.css which has a rule that makes buttons very transparent, most likely dracula-theme and other themes do it similarly:
```css
button {
  background-color: alpha(currentColor, 0.1);
}
```
My workaround was removing libadwaita.css, seeming this resulted in no visual change except the brush colors being visible instead of being very transparent.

But yes, this is not the best place to report it. Since it happens with multiple themes, probably an rnote issue.
