### ISSUE TITLE
phantomjs seems to be broken on macOS

### ISSUE THREAD

**Issue by szicari-farmobile** [NixOS/nixpkgs#31188]
## Issue description
phantomjs segfaults on macOS. This happens through `nix-shell` and `nix-env -i`.

### Steps to reproduce
1. Create a nix-shell with phantomjs:

    ```bash
    nix-shell -p phantomjs
    ```

1. Do anything with it:

    ```bash
    phantomjs --version
    phantomjs --help
    phantomjs
    ```

Segfaults.

## Technical details

* System: macOS Sierra 10.12.6 (16G29)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre119245.5cfd049a03"
* Sandboxing enabled: build-use-sandbox = false

**Comment by szicari-farmobile** [comment]
Closing as a duplicate of #12346.

**Comment by thefloweringash** [comment]
The phantomjs in nixpkgs refers to phantomjs-1.9.8, and is fetched as a binary from upstream. This binary is no longer compatible with current macOS, and there's an [upstream bug report][] indicating it broke in 10.12. Since 1.9.8 is no longer supported, this won't be fixed upstream.

[upstream bug report]: https://github.com/ariya/phantomjs/issues/14558
