### ISSUE TITLE
Path to icons (for dunst)?

### ISSUE THREAD

**Issue by BjornMelgaard** [NixOS/nixpkgs#31313]
## Issue description
What I have to paste in my dunstrc instead of this?

```
# Paths to default icons.
icon_folders = /usr/share/icons/gnome/16x16/status/:/usr/share/icons/gnome/16x16/devices/:/usr/share/icons/hicolor/16x16/apps/
```
Where icons are located?

## Technical details

* System:  (NixOS: `nixos-version`) 17.09.1880.ac2bb5684c (Hummingbird)
* Nix version:  (run `nix-env --version`) nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.09.1880.ac2bb5684c" 
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`) build-use-sandbox = false

**Comment by flokli** [comment]
You should use `icon_path` instead of `icon_folders`, the latter is deprecated ;-)

If not set explicitly, `dunst` uses the defaults specified here: https://github.com/dunst-project/dunst/blob/3691b7e47c3ff90abea9f95de3839587694df8ea/config.h#L63

It might make sense to add `gnome3.defaultIconTheme` as `buildInput`, and simply patch `config.h` to use paths from there as a default, so icons should work in general, without having to to specify the path explicitly. Could you file a PR for that?

**Comment by BjornMelgaard** [comment]
@flokli yes, it possible

By the way, this issue was recently addressed in [home-manager](https://github.com/rycee/home-manager/pull/120)

**Comment by flokli** [comment]
Having this done in home-manager is enough for me.

**Comment by BjornMelgaard** [comment]
Thanks for help then)
