### ISSUE TITLE
singularity: update to 2.4

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#31343]
## Issue description

I have a bit of a problem updating singularity to 2.4, as many of the helper scripts calls - e.g. to cat and egrep - need patching of the path. Did anyone try their hands on updating the package?

My current work can be found at https://github.com/Moredread/nixpkgs/tree/singularity-2.4 but I'm not sure whether substituting is the correct option. Is there a more automated way?

cc @jbedo

**Comment by jbedo** [comment]
Sorry for not being more on the ball with this, the current version is quite a bit behind. The shebangs can be patched with patchShebangs, and as for the remaining helper script I think the cleanest way is to wrap them to set $PATH such that they find the required utils. I updated your patch to do this, have a look at https://github.com/jbedo/nixpkgs/commit/7be6014d0bcae6a9a674e44104668d4a3fc75630. I haven't tested this heavily yet.

**Comment by Mic92** [comment]
something like `makeWrapper --prefix : ${coreutils}/bin` should do the job.

**Comment by Moredread** [comment]
Thanks, I'll have a look later.

**Comment by Moredread** [comment]
I've made progress on top of the work of @jbedo at https://github.com/Moredread/nixpkgs/commit/dd738990b10fd14a8f786f620d9cafbfb60ee568. I've identified a few more dependencies, and we need to patch even more scripts...

It seems though, that wrapping the scripts interferes with the way some of the cli scripts run 'libexec/singularity/cli/action_argpareser.sh'. E.g. running singularity build fails with

``` 
/nix/store/ik1dsl6a6116rb4g8myhyb4y2zlq3lc6-singularity-2.4/libexec/singularity/cli/.action_argparser.sh-wrapped: line 20: message: command not found
```

'message' is defined in 'libexec/singularity/functions', which is sourced by the *.exec scripts. When the 'action_argparser.sh' wrapper is sourced later in the script this isn't propagated though. I'm not sure what goes wrong there, but I guess 'sourcing' with '. $FOO' doesn't propagate stuff to scripts called by $FOO.

One option would be not to wrap 'action_argparser.sh' and patching stuff manually, but maybe you have a better idea.

**Comment by jbedo** [comment]
I've also done a bit more on this, take a look at my branch (https://github.com/jbedo/nixpkgs/tree/singularity-2.4). I have an extra patch now to remove some of the environment code, which is necessary when running singularity within a vm (e.g., like how I implemented singularity-tools). Building images with singularity-tools, which in tern uses "singularity image.create" and "singularity image.import" all work fine, as does "singularity shell" and "singularity run".

I hadn't tested "singularity build" in my branch, which is why I haven't discovered the extra dependencies you have. I don't wrap action_argparser.sh, it doesn't override PATH nor execute anything outside of singularity. I did have to explicitly patch a few hard coded paths, but not a whole lot yet.

As for suid binaries, I've been meaning to write a singularity option for configuration.nix that takes care of the appropriate suid permissions, that can wait until after we figure out this upgrade.

**Comment by Moredread** [comment]
Looks a lot better. :) I only had a quick look, but it seems that build still needs a few more dependencies. What I have identified so far are squashfsTools, gzip, gnused, curl. Also it needs mount, but I'm not sure where to get it from. What I have added is in https://github.com/Moredread/nixpkgs/tree/singularity-2.4-wip @ https://github.com/NixOS/nixpkgs/commit/edba8027a9b72bb45a60cd3b23a3d81b8c47c7e1 based on your latest commit. I guess we have to go through the scripts with a fine comb for additional deps.

The scripts in bootstrap-scripts need to be wrapped as well. I used https://github.com/GodloveD/busybox for my quick test. I cloned it and ran `sudo singularity build test.simg Singularity`  in that directory.

**Comment by jbedo** [comment]
Mount's in utillinux, the build example you gave seems to work with this added to buildInputs.

**Comment by Moredread** [comment]
Yup, that seems to work now :)

**Comment by aepsil0n** [comment]
Any progress on this?

**Comment by jbedo** [comment]
Sorry for delay.
