### ISSUE TITLE
django project error

### ISSUE THREAD

**Issue by tcpip4000** [NixOS/nixpkgs#3134]
Hi,

I installed python 2.7 and django 1.5 in my env and then enabled it; but when creating a django project with:
  > django-admin.py startproject myproj

And then using the manage.py script and error shows up:

django15:[ertech@sun:~/src/django15]$ python manage.py syncdb
  File "manage.py", line 2
    export PYTHONPATH=/nix/store/zifyk2dnph7a207dhmh4rdlw4x422alj-python2.7-Django-1.5.6/lib/python2.7/site-packages:/nix/store/bkvj4jmza28img8b688myq9b2la2q9ww-python-recursive-pth-loader-1.0/lib/python2.7/site-packages:/nix/store/ic4y16hjifcc7wdnd8hnpqbnwzy2vj9m-python2.7-setuptools-2.1/lib/python2.7/site-packages${PYTHONPATH:+:}$PYTHONPATH
                    ^
SyntaxError: invalid syntax

Looks like the python script have bash code.

**Comment by rzetterberg** [comment]
I just encountered this problem myself (The import error).

I couldn't find any information regarding this problem so I read the source to try to understand how python packages are produced on NixOS.

I have now a rudimentary understanding of how it works and how to fix it. So I thought I would document my findings in case someone else encounters the same problem.

Note that I am still new to NixOS, so this is just how I solved it. It seems to work fine, but I could be wrong in my conclusions.

## The fix

In case you just want to fix the problem and don't care why this happens:  

```
$ django-admin.py startproject myproject
$ cd myproject
$ mv .manage.py-wrapped manage.py
```

Then open manage.py in your texteditor and paste this in (note the project name I used with django-admin.py):

```
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

Then you can use manage.py like you normally would:

```
$ python manage.py runserver
Validating models...

0 errors found
March 06, 2015 - 16:26:30
Django version 1.6.6, using settings 'staircase.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

This way the `manage.py` is not specific to your install and you can commit it to your source tree.

## The reason behind it

After looking into how python packages are packaged I found out that most packages are packaged with [the generic packager.](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/python-modules/generic) 

The generic packager wraps all binaries as bash scripts that exports environment variables (such as PYTHONPATH and PATH). It does this to all files in the build dir that [has the +x flag set](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/generic/wrap.sh#L18).

When you run `django-admin.py startproject myproject` the `{{ project_name }}` on the line `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{{ project_name }}.settings")` is supposed to be replaced by the project name you supplied. 

However since `manage.py` has the `+x` flag set it gets wrapped by the generic packager. This makes `manage.py` become a bash script with environment exports that executes the original file that is now named `.manage.py-wrapped`. 

So when `django-admin.py` tries to replace `{{ project_name }}` it doesn't find it since it's now situated in another file.

It seems that `manage.py` doesn't need to be wrapped since using it like you normally would works.

**Comment by domenkozar** [comment]
Fixed, thanks for the report

**Comment by ericsagnes** [comment]
This problem seem to have reappeared, starter templates are wrapped again:

```
$ cat $(nix-build -A python3Packages.django)/lib/python3.5/site-packages/django/conf/project_template/manage.py-tpl
#! /nix/store/wsz11sx18n85if6gp50m870rypgavwpd-bash-4.4-p12/bin/bash -e
export PATH=/nix/store/ngfvnb22lh72z8prslmfdd2aiis5z08p-python3-3.5.3/bin:/nix/store/78p57dqgrlhhw66a7gxr1g353sy1r5ym-python3.5-Django-1.11.1/bin:/nix/store/lgp0b40bjmqwrndr6f6s2h8lr77w6y1d-python3.5-setuptools-30.2.0/bin${PATH:+:}$PATH
exec -a "$0" "/nix/store/78p57dqgrlhhw66a7gxr1g353sy1r5ym-python3.5-Django-1.11.1/lib/python3.5/site-packages/django/conf/project_template/.manage.py-tpl-wrapped"  "${extraFlagsArray[@]}" "$@"
```

**Comment by risicle** [comment]
Yes - I just noticed this too because I'm working on enabling the tests for the django packages and interestingly enough the tests catch this. Has the behaviour of `buildPythonPackage` changed recently? It appears to perform the wrapping before `postFixup` gets a chance to run at all (leaving `postFixup` to wrap the already-wrapped scripts again :))

```
...
wrapping `/nix/store/h3isn4my3kf9q4hxw5h93n4irl3z3qdc-python2.7-Django-1.11.1/lib/python2.7/site-packages/django/bin/django-admin.py'...
wrapping `/nix/store/h3isn4my3kf9q4hxw5h93n4irl3z3qdc-python2.7-Django-1.11.1/lib/python2.7/site-packages/django/conf/project_template/manage.py-tpl'...
wrapping `/nix/store/h3isn4my3kf9q4hxw5h93n4irl3z3qdc-python2.7-Django-1.11.1/bin/django-admin'...
wrapping `/nix/store/h3isn4my3kf9q4hxw5h93n4irl3z3qdc-python2.7-Django-1.11.1/bin/django-admin.py'...
!!! postFixup begins here !!!
wrapping `/nix/store/h3isn4my3kf9q4hxw5h93n4irl3z3qdc-python2.7-Django-1.11.1/bin/.django-admin-wrapped'...
wrapping `/nix/store/h3isn4my3kf9q4hxw5h93n4irl3z3qdc-python2.7-Django-1.11.1/bin/.django-admin.py-wrapped'...
!!! postFixup ends here !!!
```

Anyway, I'll investigate a bit and hopefully if I get the django tests going that should prevent this from regressing again.

**Comment by risicle** [comment]
I just did a `git bisect` and tracked down the bad commit as 85a87f5155f66dbdfcdb9869f4bd4f2a10fe8e2c.

Try doing _that_ with other distribution tools.
