### ISSUE TITLE
Why dependent packages doesn't recompiling?

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#31353]
## Issue description
https://gist.github.com/MrSorcus/a822a846e7c3916dcfeed80aff9dd5eb
Why kitty package doesn't recompile? How to rebuild all dependent packages?
I can't find any info about this.

### Steps to reproduce
Edit any dependency of any package, and run `nixos-rebuild switch`.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
Laptop: 18.03pre119245.5cfd049a03 (Impala)
* Nix version: (run `nix-env --version`)
Laptop: nix-env (Nix) 1.11.15
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
Laptop: 18.03pre119245.5cfd049a03
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
Laptop: build-use-sandbox = false

**Comment by srhb** [comment]
I'm assuming kitty depends on glfw and glew. The problem, in that case, is that you haven't actually redefined the packages that kitty depends on, but only installed a couple of entirely separate versions of them.

Please see [section 6.1.1 of the manual](https://nixos.org/nixos/manual/#sec-customising-packages) which explicitly addresses this; particularly the sentence beginning with: "The overrides shown above are not global. They do not affect the original package; other packages in Nixpkgs continue to depend on the original rather than the customised package."

**Comment by MrSorcus** [comment]
Ok, i understand now. Thank you.
