### ISSUE TITLE
linuxPackages.nvidia_x11.settings.libXNVCtrl: reconsider impure deployment

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#314289]
## Issue description

https://github.com/NixOS/nixpkgs/pull/312811#discussion_r1613495768

**Comment by aidalgol** [comment]
Going by [this upstream comment](https://github.com/NVIDIA/nvidia-settings/blob/b0807ed0b0280699f6fa1e5a1469fec1723f7b23/src/libXNVCtrl/nv_control.h#L24), I would not trust `libXNVCtrl` to work reliably with a different version of the Nvidia driver.  It may happen to work with some version combinations if the protocol happens to match, but could break at any time if an update makes the protocols not match.

**Comment by aidalgol** [comment]
I should have looked at the history before posting my previous comment.  The `NV-CONTROL Protocol Version History` comment has not changed since at least `340`, so it is quite stable.  The `NV-CONTROL Protocol` also appears to be between client and `libXNVCtrl`, rather than between the library and the driver.

**Comment by SomeoneSerge** [comment]
If we confirm this to work, I'd suggest we move `libXNVCtrl` into a separate package in `pkgs/by-name`, except that we write it in a generic manner so that each variant of `nvidia_x11` can override it with different sources

**Comment by Nosirus** [comment]
I don't have an Nvidia graphics card, I use Wayland and not x11 and I'm stuck during the rebuild with this error
