### ISSUE TITLE
Update request: prisma-engines 5.12.1 → 5.14.0

### ISSUE THREAD

**Issue by musjj** [NixOS/nixpkgs#314615]
- Package name: [prisma-engines](https://github.com/NixOS/nixpkgs/blob/8e4e789bb589dc3ca0b3389a14965d98ba885013/pkgs/development/tools/database/prisma-engines/default.nix)
- Latest released version: 5.14.0

- Current version on the unstable channel: 5.12.1
- Current version on the stable/release channel: 5.4.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@pimeys @tomhoule @ivan @aqrln 

There's a new `createManyAndReturn()` function that I really sorely need, would appreciate if it can be updated.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aqrln** [comment]
I can open a PR to update it but be aware that it will likely be rejected as it is or will take a while to merge. Updating the engines and Prisma CLI must happen in lockstep, and while the former is easy and uncontroversial, the latter is problematic and has been stalling the regular updates for quite some time already.

There's a consensus that `nodePackages` are being phased out and new and updated packages need to be moved out of there and be built with `buildNpmPackage`, which doesn't quite work for Prisma because of pnpm. I'm yet to try throwing out the pnpm lockfile and installing the dependencies with npm, as it was suggested the last time (and as other pnpm based projects are currently being built in nixpkgs), and I'm even not as opposed to this idea anymore as previously: the CLI actually has a pretty high chance of working with the wrong versions of dependencies (I wouldn't trust the client though). That said, I suspect further problems down the road given the complex build process of Prisma's TS codebase. Any help would be appreciated.

**Comment by musjj** [comment]
I see, thanks for the info.

For now I'm using this awesome flake: https://github.com/VanCoding/nix-prisma-utils, it's a real life-saver. It fetches the pre-built binaries from upstream that matches with your `package-lock.json` and patches them for Nix. The only downside is that you need to manually update the hashes.

**Comment by aqrln** [comment]
https://github.com/VanCoding/nix-prisma-utils is great, yes. In my opinion, this is actually a much better solution for typical development workflows involving Prisma than relying on prisma-engines from nixpkgs without any guarantees that it matches the version of Prisma you depend on in a specific project.

I also have a [work-in-progress proof of concept](https://github.com/prisma/prisma/pull/23672) of just supporting NixOS out of the box for local development in Prisma which would make using `prisma-engines` from nixpkgs only necessary if you were to package your own application with Nix.

**Comment by onny** [comment]
Prisma-engines is already at 5.16.X
