### ISSUE TITLE
intel-ocl is broken (hardware.opengl.extraOptions = [ intel-ocl ] )

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#31557]
## Issue description
The package intel-ocl is broken

`unpacking source archive /nix/store/8bq6xvbyhv829y7jzqj5iy9cdd8866w7-source
source root is .
error: source/intel-opencl-r5.0-63503.x86_64.rpm: signature region 62: tag number mismatch il 7 ril 5 dl 658 rdl 16

error reading header from package
/nix/store/nsgwmgp4lwy6hxi2bmn8chk3gsfdn4dz-cpio-2.12/bin/cpio: premature end of archive
builder for ‘/nix/store/f5ac6splmjm15cnxfw15shkkp19yyrj4-intel-ocl-5.0-63503.drv’ failed with exit code 2cannot build derivation ‘/nix/store/9bjnga5k06pji32
`

### Steps to reproduce

- add intel-ocl to hardware.opengl.extraPackages
- rebuild

## Technical details

* System: 18.03pre120031.7ebacd1a43 (Impala)
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "18.03pre120031.7ebacd1a43"
* Sandboxing enabled: build-use-sandbox = false

**Comment by kierdavis** [comment]
Thanks for the report. Apparently this problem is common among many Intel RPMs - see https://bugzilla.redhat.com/show_bug.cgi?id=1514190. It looks like most people solve it by adding `--nosignature` to the `rpm` command line, which doesn't sound ideal.

I'll look into it further, but since these are closed-source RPMs the above might be the only option here.

FYI if you mention the package maintainers' Github username(s) in the issue description or a comment, they'll get an email notification, which may prompt a faster response.

**Comment by kierdavis** [comment]
This regression was introduced by 9fa8f3ed0d3cb32c5fdf6fe8e4aff46ee2df842c.
