### ISSUE TITLE
NixOS: mysql ensureUsers should allow hostname

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nixpkgs#31592]
## Issue description

services.mysql.ensureUsers forces all users to "localhost", which is not particularly useful.  Adding an option to specify the hostname would be infinitely more useful.

**Comment by ilya-kolpakov** [comment]
Currently this option creates mysql accounts that are authenticated via the system user database. Hostname is irrelevant for this authentication scheme.

What kind of authentication would you like to see there? Do you intend to specify a password for each user account or?

**Comment by ledettwy** [comment]
Not sure what you mean, sorry if I wasn't clear before. The implementation of ensureUsers looks like this:
<pre>
${concatMapStrings (user:
  ''
    ( echo "CREATE USER IF NOT EXISTS '${user.name}'@'localhost' IDENTIFIED WITH ${if mysql == pkgs.mariadb then "unix_socket" else "auth_socket"};"
      ${concatStringsSep "\n" (mapAttrsToList (database: permission: ''
      echo "GRANT ${permission} ON ${database} TO '${user.name}'@'localhost';"
      '') user.ensurePermissions)}
    ) | ${mysql}/bin/mysql -u root -N
  '') cfg.ensureUsers}
</pre>

I'm suggesting that an ability to specify something other than "localhost" during the CREATE USER step would be useful, since frequently a database will need to be accessed from users outside the local system.

**Comment by ilya-kolpakov** [comment]
Please check the description of `ensureUsers` option. Assume there is a Unix user `tom` on the system. If one adds `tom` to `ensureUsers` he will be able to use MySQL without password. This works because MySQL can ask the system whether the user who presents himself as `tom` is actually logged in in the system as `tom`.

This scheme won’t work for users accessing MySQL via network from other computers. Anyone could connect claiming to be `jim@otherhost` and there is no easy way to verify it is actually so. So remote users typically authenticate using passwords, ssh keys and so on.

**Comment by aanderse** [comment]
@ledettwy any remaining questions on this topic or can the issue be closed?
