### ISSUE TITLE
buildLuarocksPackage: cannot build package that depends on luarocks

### ISSUE THREAD

**Issue by mrcjkb** [NixOS/nixpkgs#316009]
### Describe the bug

luarocks exists [as a luarocks package](https://luarocks.org/modules/hisham/luarocks) that other luarocks packages can depend on.
When trying to build a rockspec that depends on luarocks with `buildLuarocksPackage`, it fails.

```lua
-- rockspec dependencies
dependencies = {
  "lua >= 5.1",
  "luarocks",
}
```

```
       > Running phase: installPhase
       > Missing dependencies for testpackage scm-1:
       >    luarocks (not installed)
       >
       > testpackage scm-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
       > testpackage scm-1 depends on luarocks (not installed)
       > Warning: Failed searching manifest: Failed downloading https://luarocks.org/manifest-5.1 - no downloader tool available, 
please install wget or curl in your system
       >
       > Error: Could not satisfy dependency luarocks: No results matching query were found for Lua 5.1.
       For full logs, run 'nix log /nix/store/rnbmdmw05596619d3nsvzrwflqxh6gi6-lua5.1-testpackage-scm-1.drv'.
```

The `rocks_trees` entry in the generated luarocks config contains an entry for luarocks, but luarocks doesn't recognise it and tries to download the package instead.

### Steps To Reproduce

I have created a repository to reproduce it with: https://github.com/mrcjkb/nix-luarocks-repro

- Run `nix build .#testpackage`

A workaround is to use `luarocks-nix` to generate a `buildLuarocksPackage` expression for luarocks (`luarocks nix luarocks`),
and to add that package to the `testpackage`'s `propagatedBuildInputs` instead of the `luarocks` package from nixpkgs.

### Notify maintainers

@teto 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
thanks for creating the test repo, it's helpful. I've looked at the generated LUAROCKS_CONFIG and all looks good and I think luarocks just doesn't recognize the installed luarocks because of https://github.com/luarocks/luarocks/issues/1659

My first thought would have been to rename the current luarocks into a luarocks_bootstrap and add a generated `luarocks` derivation, for which we could run the tests without the cyclic dependency luarocks -> busted -> luarocks. 
While this might be the best outcome longterm, I am looking into the quickfix which would be to generate the manifest for the current luarocks
