### ISSUE TITLE
In a nix-shell, ghc should ignore user-installed packages that conflict with nix-installed packages

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#31674]
We've hit a case where a user with packages in their user package db (managed by brew-installed ghc) caused a "shadowed dependencies" error in the nix-shell, even with --pure. This went away when ~/.ghc was moved to ~/.ghc-backup.

cc @peti

**Comment by peti** [comment]
Personally, I frequently use user-installed Cabal libraries in my working environment, especially those installed by `new-build` and friends, so I'd be very upset if `ghc` would just stop supporting them. Generally speaking, it strikes me as a bad idea to modify the documented behavior of general-purpose tools like `ghc` in a substantial way, because this is going against people's expectations. I don't want a ghc installed by Nix to behave substantially different from one installed by Stack (or whatever). IMHO, the proper solution is to educate ghc users about their compilers'  package management. Nix can't help them if they don't understand what they are doing.

**Comment by shlevy** [comment]
@peti Specifically in a nix-shell though, the whole point is that the nix shell environment should Just Work for building what we want to build. At the very least `--pure` should not be broken by random stuff in the user package env!

**Comment by bjornfor** [comment]
Isn't that more of an issue with nix-shell --pure though, that it's not sandboxed?

**Comment by shlevy** [comment]
@peti What specific education would you give here, anyway? I have no idea how to solve this problem other than removing the user's ~/.ghc.

**Comment by peti** [comment]
> What specific education would you give here, anyway? 

Users must understand that library packages they install outside of a sandbox will be visible to all builds run with ghc.

**Comment by shlevy** [comment]
OK, and what do I do with that understanding? Why are they interfering with packages that are explicitly requested as part of a sandbox? This isn't a case of something *working* because something is in the user package db, it's a case of something *breaking*.

**Comment by peti** [comment]
> And what do I do with that understanding?

You don't install packages outside of a sandbox unless you need them for other builds. You are not surprised if globally installed packages show up in your package list. You don't call customer support and blame GHC or Nix if a globally installed package shows up in your package list and is chosen in a build context where you did not expect it. Generally speaking, people who understand what they are doing don't install Haskell libraries into their home directory but rather use sandboxing (or `cabal new-build`) precisely because this kind of problem will arise otherwise. Futhermore, people who know what they are doing don't expect a `nix-shell` build environment to be "pure" just because they pass a command line flag that says so. If you want pure builds, you must run them in a protected sandbox, like Nix actually does for you.

**Comment by shlevy** [comment]
OK then.
