### ISSUE TITLE
services.openssh.authorizedKeysInHomedir breaks gitea SSH authentication

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#316851]
When ``services.openssh.authorizedKeysInHomedir`` is set to ``false`` on a system that runs gitea, git-over-SSH (gitea@server:org/repos.git) does not work anymore due to failing authentications.

 @Ma27  @techknowlogick  @SuperSandro2000

**Comment by Ma27** [comment]
@sbourdeauducq gitea provides an authorizedKeys command.
Also, this isn't the even the default. Do you have a reason to disable this?

**Comment by SuperSandro2000** [comment]
My stance on this is, don't set the option then. We could probably convince gitea to write into /etc/ssh/authorized_keys.d but that is supposed to be declerative.

**Comment by Ma27** [comment]
Agreed.
The initial report doesn't say much which is why I decided to ask first about a little more details, but ultimately I think that this is the way to go (or - as mentioned - using AuthorizedKeysCommand).

**Comment by SuperSandro2000** [comment]
> AuthorizedKeysCommand

I think that's very brittle, as the command contains the key id in the database of gitea.

**Comment by Ma27** [comment]
I'd argue that your gitea is severely degraded if the DB is down already, but that's not the point. This is another alternative for the issue above I described.

**Comment by techknowlogick** [comment]
Not saying if it's a good/bad way to do things: but you can have the auth command be run when a specific user attempting to connect, rather than on all connections:
```
Match User specific_user
    AuthorizedKeysCommand /path/to/specific_user/command
    AuthorizedKeysCommandUser specific_user
```

**Comment by Ma27** [comment]
> AuthorizedKeysCommand makes things more fragile and can result in situations where you cannot fix certain gitea problems remotely because gitea broke SSH

It would be very bad if sshd would break down because a single authorizedkeyscommanduser command fails.
Just for completeness sake, I just tested it out by stopping the nspawn container with my git server and I could still open new SSH sessions on the host server.

> Right, in addition to the security problem

Are you actually using pam_ssh_agent_auth?

The default for it was fixed btw and it was not about the sshd default.

Anyways, I think the settings are fine and if you disagree, there were multiple alternatives described (another one is btw to use the internal ssh server of gitea) in this thread. It's up to you which to choose.

Closing.
