### ISSUE TITLE
Package request: codium

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#316833]
**Project description**

A compiler optimized fork of VSCodium

**Metadata**

* homepage URL: https://thorium.rocks/codium/
* source URL: https://github.com/Alex313031/codium.git
* license: mit
* platforms: linux, darwin

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
build instructions: https://github.com/Alex313031/codium/blob/master/docs/howto-build.md#dependencies-linux

**Comment by felbinger** [comment]
It looks like he just applied some patches to the [official vscodium that already exists in nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/editors/vscode/vscodium.nix). I think a good approach would be to add these patches as opt in to the existing codium package. I saw this ealier with `cudaSupport`, e.g. in [this pkg](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/python-modules/openai-triton/default.nix).

**Comment by Pandapip1** [comment]
I'd suggest that codium should be its own separate package, but should be an `overrideAttrs` of vscodium.

**Comment by emilylange** [comment]
Can those that are interested in Codium please comment why this should be added?

I went through the upstream patchset a while ago and again just now due to the ping and I really fail to see what Codium is supposed to add on top of VSCodium that would be of value in nixpkgs.

2 of the 3 things listed on the homepage are not applicable to nixpkgs, rendering this as a VSCodium fork that prefers and restores the VS Code logo for whatever reason and lacks behind upstream, just like the other projects of the author.

Projects of this author have some backstory in nixpkgs, so I lean towards closing this issue.
We really don't need more questionable one-man-army forks of software that lack behind upstream, fail to respond to security issues in a timely manner and add almost no value to their upstream variants.

So again, those that want Codium in nixpkgs, please shine some light on why.
I obviously have strong opinions on this, but open to leaving this package request open as-is if provided with some reasons why.

**Comment by Pandapip1** [comment]
Honestly, I have no strong feelings either way. If a PR was submitted that added the package, and there wasn't anything wrong with it, I'd probably approve it. The project has 138 stars; that suggests to me that there is adequate interest in the project in general. Also, the repository doesn't appear to be lagging behind vscodium upstream. My main concern is the naming: I think it could be misleading, as it might confuse people searching for vscodium; and I also agree that the fact that there's seemingly a single maintainer is concerning.

**Comment by ProxyVT** [comment]
I didn't expect this PR to spark such discussion. Honestly I wanted this app for standardization purpose since one of my computers was on Windows 7, which is supported by this fork. However, now I have switched to another program and I'm no longer using codium. Since you have expressed doubts about packaging this, I don't mind if codium will not land into nixpkgs.
