### ISSUE TITLE
Scrutiny tries to start before influxdb has started

### ISSUE THREAD

**Issue by devraza** [NixOS/nixpkgs#317017]
### Describe the bug
When installing scrutiny for the first time, and after rebuilding, scrutiny attempts to start before the database service has started, causing it to fail. This can be easily fixed by manually restarting the scrutiny service, however.

### Steps To Reproduce
1. Add `services.scrutiny.enable = true;` to configuration
2. Rebuild
3. Scrutiny fails to start

### Expected behavior
Scrutiny starts with no issues and without any manual intervention.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/47157273/09125321-6fb2-4e56-9d08-bad82e50b9ac)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.1-cachyos, NixOS, 24.11 (Vicuña), 24.11.20240527.9ca3f64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/b2xy0gk6sd3fc8zamarfzach5f3wpkvi-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Ideally scrutiny would be somewhat more robust to not have issues starting when the db isn't up yet. 

But there's also an issue with the influxdb service itself not properly notifying when its external endpoints are up - currently the service uses the `simple` type, which is clearly wrong. See https://github.com/influxdata/influxdb/pull/21850 for a related upstream fix in the past (though they've since removed the service file upstream). Of course I'm not suggesting we simply use that script directly, as it caused other issues - see https://github.com/influxdata/influxdb/issues/21967.

**Comment by eclairevoyant** [comment]
That's already present.

**Comment by bjornfor** [comment]
Here's a fix for this issue, waiting to be reviewed: https://github.com/NixOS/nixpkgs/pull/344246
