### ISSUE TITLE
pyLoad package dependencies are not 

### ISSUE THREAD

**Issue by TerkiKerel** [NixOS/nixpkgs#31751]
Hi,

I installed pyLoad(0.4.9). When it starts it check the system. I get below output. Can you please update the dependencies.

Note: To start "system check" you need to start pyLoadCode app.

Thank you

## System Check ##
Python Version: OK
pycurl: OK
sqlite3: OK

pycrypto: OK
py-OpenSSL: missing

py-imaging: missing
tesseract: missing

PyQt4: missing

Your installed jinja2 version 2.9.6 seems too old.

jinja2: missing
beaker: OK
JS engine: missing

**Comment by rnhmjoj** [comment]
ping @2chilled

**Comment by TerkiKerel** [comment]
@2chilled please help :(

**Comment by rnhmjoj** [comment]
I'm looking at the package right know. It looks those dependencies are optional: is the program not starting at all? There should at most some feature disabled.

**Comment by rnhmjoj** [comment]
I tried packaging the latest version only to realize the software i completely broken.
Too bad, the code is here https://github.com/rnhmjoj/nixpkgs/commits/pyload anyway.
Hopefully it will be userful in the future.

**Comment by austinbutler** [comment]
Seems `pyload` as packaged here is no longer maintained and is Python 2.x only. The developers have since published [`pyload-ng` ](https://pypi.org/project/pyload-ng/), which would likely be what to package if someone is interested in this functionality today. If so I'd recommend opening a new packaging request issue.
