### ISSUE TITLE
adguardhome: misleading assertion message

### ISSUE THREAD

**Issue by felbinger** [NixOS/nixpkgs#318460]
https://github.com/NixOS/nixpkgs/blob/9b5328b7f761a7bbdc0e332ac4cf076a3eedb89b/nixos/modules/services/networking/adguardhome.nix#L143

Should be `settings.bind_port` (copy paste error)

**Comment by parasew** [comment]
In the meanwhile this has changed again, and bind_host and bind_port are only valid up to v0.107.33. Since v0.107.36 the correct configuration is via settings.http.address (see the[ AdguardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) for more information)
