### ISSUE TITLE
Use systemd-sysusers

### ISSUE THREAD

**Issue by Mathnerd314** [NixOS/nixpkgs#3191]
Systemd 215 is released, and has a new way of configuring system user accounts which is much nicer than our current shell-script approach. Systemd should be updated to 215 and then the user/groups creation code changed to write to a systemd-sysusers configuration file.

**Comment by Profpatsch** [comment]
While using an “official” way to do declarative users would be nice, I believe our current scripts are quite mature by now.

Are there any good arguments for switching? My impressions are:
* It seems to be a quite small feature in systemd, how bug-free is it really?
* The manpage for `sysusers.d` doesn’t exist on my system
* Yet another thing that depends on systemd

@Mathnerd314, do you want to implement that? Otherwise it vote for close.

**Comment by joachifm** [comment]
I have used sysusers on non-NixOS setups, works as advertised in my experience. Whether it would bring anything to NixOS is unclear, apart from offloading some logic onto systemd (and thus also having to abide by their rules for how system users are to be handled).

**Comment by Mathnerd314** [comment]
The scripts are not what I would call "mature"; [they](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/update-users-groups.pl) are littered with "FIXME". That being said, systemd-sysusers cannot make ordinary users, so it seems preferable at the moment.

**Comment by Profpatsch** [comment]
Maybe @edolstra is in favor of a rewrite?

**Comment by bb010g** [comment]
Support for `systemd-sysusers` has been implemented in <https://github.com/NixOS/nixpkgs/pull/270727>.
