### ISSUE TITLE
`nvim-tree-sitter.withAllGrammars`: tree sitter grammars are missing

### ISSUE THREAD

**Issue by MangoIV** [NixOS/nixpkgs#319784]
### Describe the bug
When using `nvim-treesitter.withAllGrammars`, the koka treesitter grammar is missing

### Expected behavior
All grammars present in `tree-sitter-grammars` are present when choosing `withAllGrammars`

### Notify maintainers

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by teto** [comment]
you can run pkgs/applications/editors/vim/plugins/nvim-treesitter/update.py to sync the list with nvim-treesitter.

**Comment by MangoIV** [comment]
That script doesn’t seem to work :(

**Comment by MangoIV** [comment]
It says something about args not existing

**Comment by teto** [comment]
Related https://github.com/NixOS/nixpkgs/issues/300471. Will try to fix it in upcoming days

**Comment by MangoIV** [comment]
@GaetanLepage reguarly merges updates to the grammars - I wonder what they run - I also wonder why koka still isn't in there?

**Comment by teto** [comment]
the fix is really simple, I am pretty sure it's https://github.com/NixOS/nixpkgs/issues/300471#issuecomment-2036778807.

the vim plugins updater does a first pass to fetches the new plugins version, then it loads the lockfile.json from the new version of nvim-treesitter and updates the grammar based on this.

There is a flaw in the vim updater that makes it a lot slower than it should. I have identified it and wanted to fix both at the same time but didn't have time.

**Comment by MangoIV** [comment]
thank you. I will open a PR with the necessary change and documentation update.

**Comment by MangoIV** [comment]
the annoying things is that this still doesn't fix my issue - the update script just takes the jsons from the nvim-treesitter repo, but doesn't include the ones that are not mentioned there. :/

Is my only possibility of using that grammar to upstream it into nvim-treesitter or is there an easier way?

**Comment by MangoIV** [comment]
I
