### ISSUE TITLE
Kde Kwin runs on dgpu with nvidia prime offload enabled

### ISSUE THREAD

**Issue by kreutzi** [NixOS/nixpkgs#320238]
### Describe the bug
Previously on NixOS, NVIDIA Prime Offload successfully kept my dGPU inactive. However, after reinstalling NixOS, connecting a second monitor causes the window manager (KWin) to switch to the dGPU even though Prime Offload is still enabled.

### Steps To Reproduce
1.Install the latest KDE Plasma version.
2.Enable NVIDIA Prime Offload mode.

### Expected behavior
The dGPU should only be used when running nvidia-offload 

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/88722623/8b755bcf-8eb7-4881-b24d-72163f3c5301)

### Metadata

```console
 ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.4, NixOS, 24.11 (Vicuna), 24.11.20240613.e9ee548`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/qqwr649pc0qprc9lw2fmdsi1km6p7q2h-source`

```

---

**Comment by opl-** [comment]
I ran into the same problem and after some digging realized that it's likely due to the external screen being driven by the NVIDIA GPU, meaning it can't suspend to be able to talk to the screen. The dGPU properly suspends when I unplug/disable the external screen.

The dGPU draws 30W any time I do as little as moving the cursor on the external screen, which feels rather excessive for what I'd expect to be just a texture copy from the iGPU.

I also found out I can't change the power limit with `nvidia-smi --power-limit x`, which lead me to an issue that might have some useful information for mitigating this: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/483

Ultimately I have no idea if this is an issue with configuration, KWin's use of the dGPU, or the dGPU dynamic power management running it with far too much power to perform a simple task.

---

Here's how I obtained a bunch of information:

- The dGPU supports fine-grained dynamic power control and it is enabled: `cat /proc/driver/nvidia/gpus/0000\:01\:00.0/power` [^1]

- The dGPU doesn't suspend while the external display is connected (`cat /sys/devices/pci0000\:00/0000\:00\:01.0/power/runtime_status` is `active` and not `suspended`)[^2]. Doing as little as moving the cursor on the external screen causes its usage to spike up and draw silly amounts of power (`watch -n 0.5 nvidia-smi -q -d POWER`).

- The dGPU is not KWin's primary GPU. KWin gets available GPUs from udev, then sorts them to prefer non-USB GPUs and the one with the `boot_vga` attribute set to `1`.[^3]

    Running the following, the dGPU should indeed not be the primary GPU:
    ```sh
    udevadm info --export-db --subsystem-match drm --sysname-match card[0-9]
    sudo udevadm info /sys/devices/pci0000:00/0000:00:02.0/drm/card1 -a | grep boot_vga
    ```

- Setting `environment.sessionVariables = { QT_LOGGING_RULES = "kwin_wayland_drm=true"; };`, logging in again to restart KWin, and checking the logs with `sudo journalctl -t kwin_wayland | grep kwin_wayland_drm` shows clearly that the dGPU is driving the external display.

[^1]: <https://download.nvidia.com/XFree86/Linux-x86_64/555.58/README/dynamicpowermanagement.html#Procfs>
[^2]: <https://gitlab.com/asus-linux/supergfxctl/-/blob/7cba0d37bc6597b95e5d83d88076ad16aa76bab0/src/pci_device.rs#L422-431>
[^3]: <https://invent.kde.org/plasma/kwin/-/blob/fb2ca4f922a7276b7ca0e884c2510e63ab5ff168/src/utils/udev.cpp#L123-148>
