### ISSUE TITLE
ipfs: make swarmAddress configurable

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#32056]
`services.ipfs.swarmAddress`

default:
```
"/ip4/0.0.0.0/tcp/4001", "/ip6/::/tcp/4001"
```

cc @elitak

Until then, just edit `/var/lib/ipfs/config` manually.

**Comment by elitak** [comment]
Remember you can do this too:
     services.ipfs.extraConfig.Addresses.Swarm = [ "/ip4/0.0.0.0/tcp/4001" "/ip6/::/tcp/4001" ];

It seems reasonable to have this default, however, since the nixos module has no way of getting the daemon to reset options when the user removes an explicit option from configuration.nix. Incidentally, some config needs special handling, since it can't be set without re-initializing the leveldb, etc.

I don't like the idea of having to duplicate every default setting into a `mkOption`, but I guess there's no other way until the ipfs devs make the daemon's config less stateful. I would prefer they move this type of runtime config into command-line args whose absence indicates that defaults should be used. Perhaps we should file that upstream.
