### ISSUE TITLE
Please add: Tiling Shell (Gnome Extension)

### ISSUE THREAD

**Issue by boustanihani** [NixOS/nixpkgs#321036]
Please add: `Tiling Shell` (Gnome Extension)

https://extensions.gnome.org/extension/7065/tiling-shell/
https://github.com/domferr/tilingshell

**Comment by Neon-44** [comment]
1. I want the same thing, so I just asked on his Repo if we can get permission to package it. As soon as he gives us that Permission, we can begin.
2. Packaging for NixOS is actually very easy, I can show you how it's done if you want. Spread the knowledge so that in the future you can package it yourself :)

**Comment by Yash-Garg** [comment]
I've created a [package](https://github.com/Yash-Garg/dotfiles/blob/stable/packages/tiling-shell/default.nix) for my personal use.

**Comment by Neon-44** [comment]
He just answered. He said he doesn't want it to be packaged. So I'm afraid I can't help you, sorry :)

But I guess we could use the one from Yash-Garg? It probably should be okay since it's very clear that this package isn't official and noone will open issues at the original Repo :)
