### ISSUE TITLE
Keep Bitwig1 version as well

### ISSUE THREAD

**Issue by mrVanDalo** [NixOS/nixpkgs#32206]
## Issue description

There is Bitwig1 and Bitwig2. I for example have only a license for Bitwig1. And I will not pay frequently for features I don't use (because I'm not a professional musican).

Right now I use the overrideAttrs to install bitwig1, but it would be smarter to provide an older version as well (most likely there will be a bitwig3 someday).

I could create a pull-request, just wanted to open a quick discussion first, because I'm new to NixOs and maybe there is already a very smart thing that makes live much simpler, which I'm not aware.

**Comment by yegortimoshenko** [comment]
See 579219db498b9d3a01d7f62ccd1005ba96803e04. I think we shouldn't distribute paid updates for proprietary software under the same attribute without a way to opt out, this heavily breaks reverse compatibility.

I think that `bitwig-studio` should point to the latest version, with `bitwig-studio1` and `bitwig-studio2` pointing to specific major versions.

Derivation for 2.x branch may override 1.x, since it has same dependencies and layout, the only difference is additional dependency on `ffmpeg`:

```
{ stdenv, fetchurl, bitwig-studio1, ffmpeg }:

bitwig-studio1.overrideAttrs (super: rec {
  name = "bitwig-studio-${version}";
  version = "2.1.3";

  src = fetchurl {
    /* ... */
  };

  buildInputs = super.buildInputs ++ [ ffmpeg ];

  # I'm not entirely sure it can be overrided this way:
  binPath = stdenv.lib.makeBinPath [
    ffmpeg xdg_utils zenity
  ];
})
```

**Comment by mrVanDalo** [comment]
@yegortimoshenko  Is this more or less how you expect it to be ? 
* [Overlay File](https://github.com/mrVanDalo/nix-overlay/blob/feature/bitwig/mrVanDalo-overlay.nix)
* [Package Folders](https://github.com/mrVanDalo/nix-overlay/tree/feature/bitwig/pkgs/bitwig-studio)
