### ISSUE TITLE
Emacs 29.4 security fix release

### ISSUE THREAD

**Issue by mz-pdm** [NixOS/nixpkgs#323754]
### Describe the bug
Please note Emacs 29.4 security bug fix has been released more than a week ago (https://lists.gnu.org/archive/html/emacs-devel/2024-06/msg00695.html). As far as I can see that vulnerability hasn't been fixed in NixOS yet.

### Notify maintainers
AndersonTorres
adisbladis
jwiegley
lovek323
matthewbauer

**Comment by SuperSandro2000** [comment]
This was fixed with https://github.com/NixOS/nixpkgs/pull/321870 which is still propagating https://nixpk.gs/pr-tracker.html?pr=321870

**Comment by kini** [comment]
FWIW, the security patch was also backported to Emacs 28 and the ELPA version of org-mode in #321871, and that PR propagated much faster since it targeted the `master` branch instead of the `staging` branch. (I guess the 29.3 -> 29.4 PR targeted `staging` because bumping Emacs 29 triggers more rebuilds than patching Emacs 28 or ELPA org-mode does.)

**Comment by jian-lin** [comment]
FWIW, while the Emacs 29.4 [bump][1] takes quite a long time to reach users, if you install a secure org package, either from Nixpkgs (this security [patch][2] propagated much faster) or not, you are secure.

[1]: https://github.com/NixOS/nixpkgs/pull/321870
[2]: https://github.com/NixOS/nixpkgs/pull/321871
