### ISSUE TITLE
Update request: mealie 1.9.0 → 1.10.2

### ISSUE THREAD

**Issue by Jason-nz** [NixOS/nixpkgs#325120]
- Package name: mealie
- Latest released version: 1.10.2

- Current version on the unstable channel: 1.9.0
- Current version on the stable/release channel: 1.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@litchipi @anoadragon453

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ThoFrank** [comment]
Hi @litchipi & @anoadragon453,
mealie seems too have a lot of very specific dependencies. There was an issue when I tried to update it in nixpkgs. I was able to build it with poetry2nix: https://github.com/ThoFrank/mealie-nix
Do you think it is possible to keep mealie in nixpkgs up to date?

**Comment by litchipi** [comment]
Hello @ThoFrank, I tried to upgrade it, but it seams like the dependency `python-ldap` doesn't work with python `3.12`, and I got a build error on the `extruct` dependency for python `3.11`.

For now, I don't know if that's worth refactoring the package build to such a heavy process as your solution (though I am grateful you took the time to help us tackle this issue), but if it's really impossible to make it work otherwise, we may have to implement that.

**Comment by Jason-nz** [comment]
A PR for python-ldap 3.12 is already open

https://github.com/NixOS/nixpkgs/pull/326321

**Comment by litchipi** [comment]
Fixed the build for mealie `1.10.2` on python `3.11`, because of an out of date dependency (see PR https://github.com/NixOS/nixpkgs/pull/327291), should be able to get an updated mealie soon

**Comment by litchipi** [comment]
PR in process https://github.com/NixOS/nixpkgs/pull/331029
