### ISSUE TITLE
error: TeX Live package xdvi-22.87.03 is missing hash!

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#32661]
Nixpkgs at 8cdd9d56de158550ed6cc307c85df4d2462b5e01 cannot evaluate:

    texlive.combine {
      inherit (self.texlive) scheme-medium xdvi 
    };

Cc: @vcunat

**Comment by dtzWill** [comment]
While adding the missing hash is straightforward, the real problem is sorting out how this wasn't included in the fixedHashes.nix generated hashes.

Looks like the problem is due to this: https://github.com/NixOS/nixpkgs/blob/5b42c6f196d976d176fe73cdf8beb5420291c489/pkgs/tools/typesetting/tex/texlive/default.nix#L71

In which we remove xdvi from `collection-basic` and into `collection-genericextra`.  Except `collection-genericextra` no longer exists!

I'm not sure how this isn't an evaluation error, but regardless the question becomes what collection xdvi should belong to.

The closest replacement I see is `collection-plaingeneric`, but since that's included in even `scheme-minimal` it doesn't seem like we'd be accomplishing much.

Thoughts? Perhaps we just leave xdvi in `collection-basic`?

**Comment by veprbl** [comment]
By the way, here is a relevant snapshot of pkgs.nix with the original hashes:
https://gist.github.com/veprbl/3dc563802c97a95bcdc4eac6650ede7d

**Comment by veprbl** [comment]
I estimated some closure sizes of the ```scheme-basic``` (using ```du -sch $(nix-store -qR $(nix-build '<nixpkgs>' -A texlive.combined.scheme-basic))```).

With luatex, metafont and xdvi: 275M
With metafont and xdvi, but without luatex: 263M
Without luatex, metafont and xdvi: 187M
