### ISSUE TITLE
OBS-Studio + decklink + blackmagic-desktop-video does not display Intensity Pro 4k.

### ISSUE THREAD

**Issue by vertiKarl** [NixOS/nixpkgs#328925]
### Describe the bug
When trying to use OBS-Studio with my Intensity Pro 4k it does not recognize the decklink/blackmagic-desktop-video drivers.
So I can't use my capture card at all in OBS.

### Steps To Reproduce
1. Put the following inside configuration.nix:
```
hardware.decklink.enable = true;
services.udev.packages = with pkgs; [
	blackmagic-desktop-video
  ];
environment.systemPackages = {
    ...
    obs-studio
    blackmagic-desktop-video
    linuxKernel.packages.linux_zen.decklink # or switch with your preferred kernel
}
```
and add blackmagic as a kernel module inside hardware-configuration.nix.
2. rebuild
3. Start obs with `obs | grep decklink` and immediately see the missing libDeckLinkAPI.so

### Expected behavior
Obs just picks up the capture card.

### Screenshots
Just running obs
![Just running obs](https://i.imgur.com/PnOYChB.png)
Running obs with LD_LIBRARY_PATH set
![Running obs with LD_LIBRARY_PATH set](https://i.imgur.com/hfW8Ogb.png)

### Additional context
I tried:
- obs package alongside the blackmagic ones
- wrapOBS with other plugins
- Also when launching obs with LD_LIBRARY_PATH set to the blackmagic-desktop-video library, it finds the capture card but it doesn't display any input from it

I am still new to NixOS and am probably just missing a simple config somewhere, so any help would be appreciated!
I am btw not yet using flakes or home-manager, if that matters.

I recently switched from ArchLinux where it's basically just a pull from this [AUR package](https://aur.archlinux.org/packages/decklink) and enabling the systemd service
`# systemctl enable --now DesktopVideoHelper.service`

I hope this is the right place to ask/report. I also attached my configuration.nix and hardware-configuration file (though github wants them as .txt),
[configuration.txt](https://github.com/user-attachments/files/16324785/configuration.txt)
[hardware-configuration.txt](https://github.com/user-attachments/files/16324792/hardware-configuration.txt)
Also a log of obs without the LD_LIBRARY_PATH environment variable set:
[obs.log](https://github.com/user-attachments/files/16324812/obs.log)
and with it set:
[obs-with-ld-set.log](https://github.com/user-attachments/files/16324813/obs-with-ld-set.log)

If any crucial information is missing please let me know!

### Notify maintainers

@Naxdy 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8-zen1, NixOS, 24.11 (Vicuna), 24.11pre655136.1d9c2c9b3e71`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Naxdy** [comment]
Heya, so a couple things:

First off, `hardware.decklink.enable` already pulls in the kernel module for your currently configured kernel, the system package, and enables the systemd service (see the [source file](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/hardware/decklink.nix) for reference). So you don't need to pull in `blackmagic-desktop-video` or `linuxKernel.packages.linux_zen.decklink` manually (there's no harm in doing so, it's just unnecessary).

`blackmagic-desktop-video` also doesn't provide any udev rules (device access is handled via the `DesktopVideoHelper` service), so listing it in `services.udev.packages` doesn't do anything.

To get the plugin to show up in OBS, it needs to be made aware of it explicitly. As you've already discovered, you can do this by settings your `LD_LIBRARY_PATH` to include the plugin's path. My config looks like this:

```nix
hardware.decklink.enable = true;

environment.sessionVariables = {
  LD_LIBRARY_PATH = [
    "${pkgs.blackmagic-desktop-video}/lib"
  ];
};
```

This is the minimum config required to make my hardware work in NixOS.

Alternatively, instead of globally appending to `LD_LIBRARY_PATH`, you can also pull in OBS with the `decklinkSupport` argument set, like so:

```nix
environment.systemPackages = [
  (pkgs.obs-studio.override {
    decklinkSupport = true;
  })
];
```

Note however that this approach will require compiling OBS from source every time there's an update.

---

Finally, if you've managed to get to the point where OBS recognizes your device but doesn't display anything, I'd suggest changing the `Mode` to something else (I've personally found that `Auto` rarely works - if ever). You might also have to fiddle around with the `Pixel Format` values.

Hope this information is helpful to you, let me know how it goes for you!

**Comment by vertiKarl** [comment]
I knew it was something simple! Thank you so much for the in-depth and quick response on a Sunday!

I did just copy my obs settings from Arch on which the "auto-mode" worked and I now know why even with the library path it didn't work... the last time I unplugged my cables and plugged them back in, I accidentally plugged the HDMI into the output-port. 🤦‍♂️ (It doesn't help that Blackmagic didn't even label them on the hardware)

It now works even with auto mode! Feel free to close the issue.

Though I wish I could use this override with the wrapOBS function to also use other plugins like obs-vkcapture which I need. Is that possible without breaking it completely up into a seperate package? I don't really mind recompiling obs every update.

**Comment by Naxdy** [comment]
> the last time I unplugged my cables and plugged them back in, I accidentally plugged the HDMI into the output-port.

Hey, at least you remembered. I probably would've kept searching for a software fix for much longer 😅

I plan on adding the functionality to `wrapOBS` soon-ish (definitely in time for the 24.11 release), or modifying `blackmagic-desktop-video` so that the package can be included in the plugins list. I only recently assumed maintainership for these packages after the previous maintainer left the project, so right now I'm just focused on ensuring that everything works smoothly for everyone, but so far things look good.
