### ISSUE TITLE
Build failure: fuzzy-logic-toolkit

### ISSUE THREAD

**Issue by nyadiia** [NixOS/nixpkgs#330517]
### Steps To Reproduce

1. build using octaveFull.withPackages or octave.withPackages
```nix
pkgs.octaveFull.withPackages ( opkgs: [ opkgs.fuzzy-logic-toolkit ] )
pkgs.octave.withPackages ( opkgs: [ opkgs.fuzzy-logic-toolkit ] )
```

### Build log
```
error: parse error near line 49 of file /nix/store/pqjy1zv9f66a5rv4s2qlnlfllm04brzn-octave-9.2.0-env/share/octave/octave_packages/fuzzy-logic-toolkit-0.4.6/algebraic_sum.m

  syntax error

>>>     retval = x .+ y .- x .* y;
                    ^
error: called from
    doc_cache_create>create_cache at line 116 column 20
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 836 column 5
    install at line 241 column 7
    pkg at line 619 column 9
error: ignoring const execution_exception& while preparing to exit
```
Full log: https://gist.github.com/nyadiia/38929db3ce51076e7d8470933d8f9a08

### Additional context

This build failure only occurs when building using withPackages, building octavePackages.fuzzy-logic-toolkit works fine.

### Notify maintainers
@KarlJoad 
@afh 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.12, NixOS, 24.11 (Vicuna), 24.11.20240727.b73c222`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/qxf6anli54ij0q1sdlnlgx9hyl658a4v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by KarlJoad** [comment]
> This build failure only occurs when building using withPackages, building octavePackages.fuzzy-logic-toolkit works fine.

That is expected, because building `octavePackages.fuzzy-logic-toolkit` only compiles fuzzy-logic-toolkit (if it needs compilation) and places those files in the correct directories. However, `withPackages` is the part that actually finds and merges all `octavePackages` you specify, making them available to you.

I suspect that this is technically not `fuzzy-logic-toolkit` at all, but Octave itself.
```
>>>     retval = x .+ y .- x .* y;
                    ^
```
According to [Octave 9's changelog](https://octave.org/NEWS-9.html#deprecated-functions-properties-and-operators), the `.+` operator was completely removed.

fuzzy-logic-toolkit moved from SourceForge to GitHub, and released updated versions, fixing this problem in the process. Because I did not know about the move, the auto-updating script did not catch this update.

**Comment by KarlJoad** [comment]
@nyadiia Got the fix sitting in PR #330534. You should be good to go as soon as that gets merged! :smile:

**Comment by nyadiia** [comment]
Awesome, thank you!

**Comment by pbsds** [comment]
done in https://github.com/NixOS/nixpkgs/pull/330534
