### ISSUE TITLE
Build failure: viber

### ISSUE THREAD

**Issue by chr314** [NixOS/nixpkgs#330603]
### Steps To Reproduce

1. `sudo nixos-rebuild switch --upgrade-all`

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/vv7crjk78lmqcwlpmiddnjq5jyv1ybnk-viber.deb.drv':
         specified: sha256-RrObmN21QOm5nk0R2avgCH0ulrfiUIo2PnyYWvQaGVw=
            got:    sha256-9WHiI2WlsgEhCPkrQoAunmF6lSb2n5RgQJ2+sdnSShM=

```

### Additional context

the last commit removed the use of webarchive 

### Notify maintainers

@pyrox0

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.41, NixOS, 24.11 (Vicuna), 24.11pre655136.1d9c2c9b3e71`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pyrox0** [comment]
Hello, I'm not the maintainer. I think you meant to ping @jagajaga

**Comment by sinh-x** [comment]
I think there are multiple issues with latest viber update - https://github.com/NixOS/nixpkgs/pull/323215

it use url downloaded directly from viber instead of former practice using web.archive.org which lead to the hash mismatch issues.

I tried following overlay to fix them

```nix
    viber = final.pkgs.unstable.viber.overrideAttrs (oldAttrs: {
      src = final.fetchurl {
        url = "https://web.archive.org/web/20240114085219/https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb";
        sha256 = "sha256-RrObmN21QOm5nk0R2avgCH0ulrfiUIo2PnyYWvQaGVw"; # same hash as original commit in this PR https://github.com/NixOS/nixpkgs/pull/323215
      };
    });
```

The latest file from viber for linux with the hash `sha256-9WHiI2WlsgEhCPkrQoAunmF6lSb2n5RgQJ2+sdnSShM=` have some hard code that result failed to launch with message that `unable to make change to /opt/viber` on NixOS
