### ISSUE TITLE
BUG: Ananicy does not work anymore on nixos-unstable

### ISSUE THREAD

**Issue by Andy3153** [NixOS/nixpkgs#331320]
### Describe the bug
Neither the original `ananicy`, nor the `ananicy-cpp` programs support cgroupsv2 which only creates issues because systemd deprecated cgroupsv1. On boot, systemd itself throws the error `Refusing to run under cgroup v1, SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1 not specified on kernel command line at boot after update`, and if that cmdline parameter is added my system boots slower.

I think that these two programs and the subsequent module that enables them should be removed from nixpkgs at least until the programs migrate to cgroupsv2, or (bad idea) enable that kernel cmdline parameter if ananicy is enabled

### Steps To Reproduce
1. Run NixOS unstable
2. enable ananicy

### Expected behavior
Not applicable

### Screenshots
Not applicable

### Additional context
- Initially I made an issue on NixOS Discourse where I didn't initially know what was at fault: https://discourse.nixos.org/t/getting-refusing-to-run-under-cgroup-v1-at-boot-after-update/49924
- I created an issue on the Ananicy-Cpp GitLab repo regarding this issue: https://gitlab.com/ananicy-cpp/ananicy-cpp/-/issues/74
- Original Ananicy program is archived so there wasn't any point in creating an issue in there.
- I'll be happy to make a PR by myself for a solution to this, I just want some feedback and to say that this issue exists. 

### Notify maintainers
@Artturin
@JohnRTitor

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.1-zen1, NixOS, 24.11 (Vicuna), 24.11.20240728.52ec9ac`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ElvishJerricco** [comment]
https://github.com/NixOS/nixpkgs/pull/331248

**Comment by eclairevoyant** [comment]
upstream bug https://gitlab.com/ananicy-cpp/ananicy-cpp/-/issues/40

**Comment by ElvishJerricco** [comment]
@Andy3153 Let us know if https://github.com/NixOS/nixpkgs/pull/331248 has solved the issue.

**Comment by Andy3153** [comment]
> @Andy3153 Let us know if #331248 has solved the issue.

How can I test it on my system? Just use nixpkgs from master?

**Comment by ElvishJerricco** [comment]
That, or wait a couple of days for that PR to make it to nixos-unstable.

**Comment by Andy3153** [comment]
I'll let you know when it hits nixos-unstable then.

**Comment by volfyd** [comment]
(My observations are for nixos-24.05. I have not tried other versions).

The service for ananicy-cpp does not detect that the system has cgroupsv2 (even though it does). In order to determine if cgroups2 is active, ananicy-cpp reads /etc/mtab. This file is a symbolic link to /proc/mounts.

From the perspective of my terminal shell, /proc/mounts is a symbolic link to /proc/self/mounts.

From the perspective of the ananicy-cpp systemd service, /proc/mounts does not exist (but /proc/self/mounts does). When ananicy-cpp tries to open /etc/mtab, it fails. Thus it concludes, incorrectly, that cgroupv2 options will not work.

I was able to get ananicy-cpp to work this way:

```
    services.ananicy = {
      enable = true;
      package = pkgs.ananicy-cpp.overrideAttrs (_: _: {
        postPatch = ''
          substituteInPlace src/platform/linux/cgroups.cpp \
            --replace-fail "/etc/mtab" "/proc/self/mounts"
        '';
      });
```

I don't know if this is just something that is happening on my NixOS-24.05 config, or if it is something that happens to everyone. I don't know what controls whether /proc/mounts appears. I tried turing off  various "Protect" systemd options to see if that changed the behavior, but I was not able to find an option that caused the file to appear.

**Comment by Artturin** [comment]
@volfyd I created https://gitlab.com/ananicy-cpp/ananicy-cpp/-/merge_requests/27

**Comment by Artturin** [comment]
And https://github.com/NixOS/nixpkgs/pull/350109

**Comment by aviallon** [comment]
@Artturin don't hesitate to ping me for this kind of bugs!
