### ISSUE TITLE
Package request: Mailsy

### ISSUE THREAD

**Issue by mmj2023** [NixOS/nixpkgs#331854]
**Project description**

Quickly generates a disposable email via the `mail.tm` api
**Metadata**

* homepage URL: https://fig.io/manual/mailsy
* source URL: https://github.com/BalliAsghar/Mailsy
* license: mit
* platforms: unix, linux, darwin, windows.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 404Wolf** [comment]
@mmj2023 [I just packaged this](https://github.com/404Wolf/mailsy-nix), but this is my first contribution here, so I'll need to figure out the process to add it to the registry soon.

**Comment by mmj2023** [comment]
Thanks, appreciate it.

**Comment by 404Wolf** [comment]
Yeah, nix is great for a lot of reasons, consistency is definitely one of them. The issue here was that it wanted to access a file from the source's directory, which would be in the nix store (which is read only). Unfortunately to solve that I just had to patch it to change where it loads the `account.json` from.

**Comment by 404Wolf** [comment]
> Thanks, appreciate it. I was trying to figure out the process of packaging it myself , The package seemed useful but still wasn't available for some reason.I actually used homebrew or linuxbrew to get it but it's just better to be able to have one package manager do it for me and that is kinda the appeal for nix in my eyes.Thank you again for the support.

Yeah, nix is great for a lot of reasons, consistency is definitely one of them. The issue here was that it wanted to access a file from the source's directory, which would be in the nix store (which is read only). Unfortunately to solve that I just had to patch it to change where it loads the `account.json` from.

**Comment by 404Wolf** [comment]
I'll add that this was a somewhat arbitrary decision, it may be better to  allow the user to specify as a string the javascript that determines where account.json ends up, or just to put it in a tmp directory.

**Comment by mmj2023** [comment]
OK, great ! I will close the issue when the pull request gets accepted.

**Comment by mmj2023** [comment]
I looked into the issue and I am still reading docs so, I will try to help if I can.
