### ISSUE TITLE
Request for name change from: gnome.gnome-backgrounds to: gnome-backgrounds

### ISSUE THREAD

**Issue by KCynk** [NixOS/nixpkgs#332210]
Request for name change from: gnome.gnome-backgrounds to: gnome-backgrounds
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=gnome-background
@jtojnar

**Comment by jtojnar** [comment]
That’s the plan https://github.com/NixOS/nixpkgs/pull/319659#issuecomment-2209447523

**Comment by KCynk** [comment]
@jtojnar Ok, gnome.gnome-shell-extensions is also affected
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=gnome.gnome-shell-extensions

Thank you for your work!

**Comment by jtojnar** [comment]
If you have some spare time, feel free to help. It is pretty easy:

1. `nixfmt pkgs/desktops/gnome/misc/gnome-foo/default.nix` (format for [by-name](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#syntax))
2. `git commit -a -m 'gnome.gnome-foo: Format with nixfmt` (this needs to be a separate commit from moving the file so that git history tracking can match the move)
3. `git mv pkgs/desktops/gnome/misc/gnome-foo/{default,package}.nix`
4. `git mv pkgs/desktops/gnome/misc/gnome-foo pkgs/by-name/gn/`
5. Remove entry in `pkgs/desktops/gnome/default.nix` and add alias to the bottom.
6. Find any references in Nixpkgs (e.g. using `rg gnome-foo`) and replace them with top-level.
7. `git commit -a -m 'gnome-foo: Move from gnome scope to top-level`

**Comment by linsui** [comment]
This should have been closed by https://github.com/NixOS/nixpkgs/pull/333917 if the [correct syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) is used. :)
