### ISSUE TITLE
services.ollama.rocmOverrideGfx not working as expected

### ISSUE THREAD

**Issue by robertosw** [NixOS/nixpkgs#332446]
I've only tested this on the unstable channel, this might be different on stable.

## Describe the bug
The description of `services.ollama.rocmOverrideGfx` is:

> Override what rocm will detect your gpu model as. For example, make rocm treat your RX 5700 XT (or any other model) as an RX 6900 XT using a value of "10.3.0" (gfx 1030).
> 
> This sets the value of HSA_OVERRIDE_GFX_VERSION. See [ollama’s docs](https://github.com/ollama/ollama/blob/main/docs/gpu.md#amd-radeon) for details.

But this does not work as one might expect. I had to manually set `HSA_OVERRIDE_GFX_VERSION` before calling `ollama serve`, despite having defined `rocmOverrideGfx` in my configuration. This is because `HSA_OVERRIDE_GFX_VERSION` is set the same way as the environment variables defined in `services.ollama.environmentVariables`. However, these variables are not applied to the `ollama` command, as stated in its documentation:

> Set arbitrary environment variables for the ollama service.
> 
> Be aware that these are only seen by the ollama server (systemd service), not normal invocations like ollama run. Since ollama run is mostly a shell around the ollama server, this is usually sufficient.

I find this behavior useless because for the current version in the unstable channel, all environment variables have to be applied to the actual `ollama` command in order to be effective. 

## Expected behavior
Environment variables are applied to the `ollama` command, not to the systemd service.

## Additional context
This issue is only relevant for systems with AMD GPUs.

To get ollama working just by calling `ollama serve`, not `ENV1=x ENV2=y ollama serve`, this configuration can be used:
```nix
services.ollama = {
	enable = true;
	acceleration = "rocm";
	package = pkgs.ollama-rocm;
};

environment.variables = {
	HSA_OVERRIDE_GFX_VERSION = "10.3.0";
	HIP_VISIBLE_DEVICES = "0";
	OLLAMA_LLM_LIBRARY = "rocm";
};
```
This is not really an ideal solution because these environment variables are set for the entire system, not just the ollama command. I've not yet found how to set them for only the command.

## Notify maintainers
@abysssol
@onny

## Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.12, NixOS, 24.11 (Vicuna), 24.11pre661606.d04953086551`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by abysssol** [comment]
> I had to manually set `HSA_OVERRIDE_GFX_VERSION` before calling `ollama serve`

Why are you calling `ollama serve` when you're using the ollama service module? The service starts up an ollama server automatically.

You should be able to use this config:

``` nix
services.ollama = {
  enable = true;
  acceleration = "rocm";
  rocmOverrideGfx = "10.3.0";
};
```

Then just `ollama run` without having to run `ollama serve`, since systemd will start `ollama serve` for the service.

If you don't actually want to use this workflow and would rather run `ollama serve` yourself, then there is absolutely no need to use the ollama service module at all. If that is the case, you may be interested in me adding overrides to the ollama package to set environment variables in the wrapper script (which could also be utilized by the ollama module).

> I find this behavior useless because for the current version in the unstable channel, all environment variables have to be applied to the actual `ollama` command in order to be effective.

Are you sure? Could you point me to where the documentation states this?
Are you even connecting to the ollama service at all? It sounds to me from your previous comments that you are manually running `ollama serve` and connecting to that.

It is possible that I have misinterpreted you in some way. If that is the case, please do clarify.

**Comment by robertosw** [comment]
My bad, it never occured to me that ollama will be running in the background the entire time and one does not have to start it manually. In this case, everything works and the env vars are applied :D
