### ISSUE TITLE
PR #321550 causes bugs with nix and markdown grammars

### ISSUE THREAD

**Issue by humemm** [NixOS/nixpkgs#332580]
@MangoIV This pr causes a regression as mentioned in https://github.com/nvim-treesitter/nvim-treesitter/issues/6870. In addition to causing problems with the nix grammar it messes with markdown/inline_markdown. Prior to nvim 10.0 it just breaks the markdown in vim help. Because of this issue markdown is displayed as source/plain text. After nvim 10.1 it throws errors like nix and hits the is-not predicate mentioned in that issue.

_Originally posted by @humemm in https://github.com/NixOS/nixpkgs/issues/321550#issuecomment-2269967316_

**Comment by MangoIV** [comment]
Please excuse me @humemm I currently do not have time for this, even though I would like to help, afaiu this can be solved by preferring the queries from the nvim treasurer repo. 

If you or someone else could add the fix that would be nice, else I’ll open a PR for reverting #321550

**Comment by MangoIV** [comment]
Feel free to open a revert MR.

**Comment by teto** [comment]
I think the PR does the right thing (except for the nu grammar where files are put in the wrong folder as a report mentioend it), probably @humemm  is installing a wrong version of the grammar and/or mismatched with nvim-treesitter ?
We would need more details. 
Nix just puts files where neovim expects them, see `:h treesitter`.

**Comment by BirdeeHub** [comment]
Surprisingly, it still works in nixCats?

I talked with a guy who was having an issue with pkgs.wrapNeovim

I took a look and couldnt figure out, but decided to swap in his dependencies into a nixCats template

It worked flawlessly again.

We were confused for a while, but I think I figured out why treesitter grammars still work just fine in nixCats but not in pkgs.wrapNeovim, at least not when lazy loaded (and can still find their queries just fine, they dont seem to need this to be able to find them)

https://github.com/BirdeeHub/nixCats-nvim/blob/df8e6a6bee79e68feea4a873bc5b6247382cd157/nix/builder/vim-pack-dir.nix#L86

Here, in the process of consolidating the treesitter grammars to make it easier to add them to rtp when doing the lazy.nvim wrapper, I think I accidentally undid this exact change XD

**Comment by BirdeeHub** [comment]
so yeah, in conclusion, they could already find the damn things before this pr went through and now some things are having trouble finding them because of this change. I say revert it probably

**Comment by MangoIV** [comment]
> they could already find the queries before this pr went through and now some things are having trouble finding them because of this change.

What does this refer to? WithAllGrammars? Or? I’m 100% sure that it could not move queries for tree sitter grammars not coming from nvim-treesitter, that’s why I opened the PR. I do believe you that something goes wrong but I still don’t know what and nobody made it clear yet. 

As I said, I don’t know what is the problem so if you had something working before and now it doesn’t, feel free to revert but then all the other tree sitter grammars won’t be working, again.

**Comment by BirdeeHub** [comment]
> > they could already find the queries before this pr went through and now some things are having trouble finding them because of this change.
> 
> What does this refer to? WithAllGrammars? Or? I’m 100% sure that it could not move queries for tree sitter grammars not coming from nvim-treesitter, that’s why I opened the PR. I do believe you that something goes wrong but I still don’t know what and nobody made it clear yet.
> 
> As I said, I don’t know what is the problem so if you had something working before and now it doesn’t, feel free to revert but then all the other tree sitter grammars won’t be working, again.

I mean, before this change went through, the grammars seemed to work just fine is what im saying. you say "all the other grammars won't be working, again" but they seemed to work just fine?

 I think it is capable of following symlinks or something because it was definitely able to find the queries before despite them not being present directly

**Comment by teto** [comment]
what I meant by ` Nix just puts files where neovim expects them, see :h treesitter.` is that nix knowledge is not needed to diagnose the issue, just to fix the issue so dont let it stop you from investigating.  Once we know the issue, we can help with the nixpkgs part.

> Have you attempted to reproduce the bug?

I did not because I know from experience that neovim + treesitter issues are 90% misconfiguration. It's not robust at all, one little misconfiguration and it blows up, which is why it's still experimental (I dont blame users, it's the ecosystem that need to make it easier).
For instance your initial message mentions `with the nix grammar it messes with markdown/inline_markdown` but you dont need to install the `inline_markdown` grammar, it's builtins with neovim https://github.com/NixOS/nixpkgs/blob/2987ca5488c454724433d003f527680166373a41/pkgs/by-name/ne/neovim-unwrapped/package.nix#L92 ! 

So I think you override the builtins queries with more recent ones, the mismatch generates the error. Before https://github.com/NixOS/nixpkgs/pull/321550, one had mismatched libraries and queries but it was less likely to blow up (how neovim leverage queries change more frequently).
In the end I did try a short test but I could not break anything (I am on nightly neovim, which should be why). 
My guess is that you are using stable neovim (0.10) ? 
and the problem is that nixpkgs follows the development version of nvim-treesitter so it works only with neovim nightly.

It's a quick guess so I might be wrong (you could try nightly neovim see if it fixes your error https://github.com/nix-community/neovim-nightly-overlay).

 In case I guessed correclty, nixpkgs should package the last version of nvim-treesitter compatible with neovim 0.10 (and it's indeed a flaw in nixpkgs, but not the incriminated PR).

**Comment by BirdeeHub** [comment]
I have tried to reproduce and I can confirm that it does cause issues with the new copying. 

tried it on someones config, one outside of nixCats, one inside of nixCats. Same set of plugins(I copy pasted them into the default nixCats template), the other one using pkgs.wrapNeovim [which I mentioned here](https://github.com/NixOS/nixpkgs/issues/332580#issuecomment-2287745101)

The only difference in loading between the two methods that would have ANY effect is that nixCats posthumorously removes the queries directories (on accident, because when I wrote it, thats all there was, and it worked fine, and somehow also avoids this issue XD).

the one using nixCats works fine, the other one errored on every keypress on its flake.nix

I believe that if we need to copy them in, we also need to stop nvim-treesitter from vendoring them in for us. Or go back to not copying them in. Either way is fine with me, but the second one is easier and could be done as a temporary measure as well.

**Comment by teto** [comment]
@BirdeeHub can we avoid mentioning nixCats and focus on the problem here ? 

> I believe that if we need to copy them in, we also need to stop nvim-treesitter from vendoring them in for us. Or go back to not copying them in.

I dont think it's questionable here: if nvim-treesitter provides them so we must provide them, we are not half-installing software.
If the problem is actually the one I mentioned, our fault lies in mixing a dev version of nvim-treesitter with a stable version of neovim.

**Comment by BirdeeHub** [comment]
right, so, we need to stop nvim-treesitter from vendoring them in so that we can copy them without creating duplicates, so that we do it properly

**Comment by BirdeeHub** [comment]
Im all on board for that plan I just dont know how treesitter is doing it

**Comment by BirdeeHub** [comment]
and im not mentioning it just to mention it.

I was saying what I tried, because the result of its output is identical to how nixpkgs was before that patch, and that is how I found out.

I suppose I should have said, before the patch and after the patch, but thats not what I tested at first or how I found out.

Regardless, download that guys config I linked, lock his nixpkgs to before and after the patch and open his flake.nix and you will see the difference

**Comment by BirdeeHub** [comment]
Minimal reproduction.

nix run this file, use it to look at this file.

```nix
{
  inputs = {
    nixpkgs = {
      # commit from immediately before PR in question, if chosen instead, no bug
      # url = "github:nixos/nixpkgs/19581e2ce8bc43f898ef724f8072ebf62bebb325";
      url = "github:nixos/nixpkgs/nixpkgs-unstable";
    };
    neovim = {
      # It happens regardless of nightly, you can try too if you want.
      url = "github:nix-community/neovim-nightly-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = { nixpkgs, neovim, ...}: let
    forAllSys = nixpkgs.lib.genAttrs nixpkgs.lib.platforms.all;
    overlayMyNeovim = prev: final: {
      myNeovim = let
        customRClua = final.writeText "init.lua" /*lua*/''
          vim.schedule(function()
            vim.cmd("packadd nvim-treesitter");
            require("nvim-treesitter.configs").setup({
              auto_install = false,
              highlight = {
                enable = true
              },
            })
          end)
        '';
      in
      final.wrapNeovim final.neovim {
        configure = {
          customRC = ''lua dofile("${customRClua}")'';
          packages.all.start = with final.vimPlugins; [ 
          ];
          packages.all.opt = with final.vimPlugins; [
            nvim-treesitter.withAllGrammars
          ];
        };
        extraMakeWrapperArgs = ''--prefix PATH : "${final.lib.makeBinPath (with final; [ stdenv.cc.cc ])}"'';
      };
    };
  in 
  {
    packages = forAllSys (system: let
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ neovim.overlays.default overlayMyNeovim ];
      };
      in
      { default = pkgs.myNeovim; });
  };
}
```

**Comment by BirdeeHub** [comment]
Hopefully this helps clear up what is being discussed

**Comment by BirdeeHub** [comment]
Im happy to do it but idk where to look, anyone have any leads for me?

**Comment by BirdeeHub** [comment]
https://github.com/NixOS/nixpkgs/blob/5cbbd23d5de47e31a8db5351c89afb7e5197819c/pkgs/applications/editors/vim/plugins/nvim-treesitter/overrides.nix#L33-L55

Also, in withPlugins and withAllGrammars, it only links the parser anyway

**Comment by BirdeeHub** [comment]
So, I think the current set of queries that WAS being used are literally the queries in the nvim-treesitter repo itself?

They werent being included with the grammars and they were using the ones from nvim-treesitter likely to avoid such issues

I think unless we have a permenant way to deal with the collision issues from having both sets of queries this change should probably be reverted

**Comment by PerchunPak** [comment]
Using queries from grammars instead of treesitter repo doesn't work, though it is less annoying (I got the issue only after 10-30 seconds, instead of every keypress)

Here is the patch for fix I though about:
```patch
diff --git a/pkgs/applications/editors/vim/plugins/nvim-treesitter/overrides.nix b/pkgs/applications/editors/vim/plugins/nvim-treesitter/overrides.nix
index c7cd3266d9c7..ae0212ae44f4 100644
--- a/pkgs/applications/editors/vim/plugins/nvim-treesitter/overrides.nix
+++ b/pkgs/applications/editors/vim/plugins/nvim-treesitter/overrides.nix
@@ -1,4 +1,4 @@
-{ lib, callPackage, tree-sitter, neovim, neovimUtils, runCommand }:
+{ lib, callPackage, tree-sitter, neovim, neovimUtils, runCommand, symlinkJoin }:
 
 self: super:
 
@@ -40,17 +40,12 @@ let
         let
           grammars = map grammarToPlugin
             (f (tree-sitter.builtGrammars // builtGrammars));
-          copyGrammar = grammar:
-            let name = lib.last (lib.splitString "-" grammar.name); in
-            "ln -sf ${grammar}/parser/${name}.so $out/parser/${name}.so";
         in
         [
-          (runCommand "vimplugin-treesitter-grammars"
-            { meta.platforms = lib.platforms.all; }
-            ''
-              mkdir -p $out/parser
-              ${lib.concatMapStringsSep "\n" copyGrammar grammars}
-            '')
+          (symlinkJoin {
+            name = "vimplugin-treesitter-grammars";
+            paths = grammars;
+          })
         ];
     };
 
@@ -59,7 +54,7 @@ in
 
 {
   postPatch = ''
-    rm -r parser
+    rm -r parser queries
   '';
 
   passthru = (super.nvim-treesitter.passthru or { }) // {
```
See also https://ryantm.github.io/nixpkgs/builders/trivial-builders/#trivial-builder-symlinkJoin

BTW, #321550 was accidentally reverted by #319233

**Comment by BirdeeHub** [comment]
This looks like a good fix to me. Does it pass the minimal reproduction case above?

**Comment by BirdeeHub** [comment]
So, it actually does a much better job of including the queries and parsers correctly compared to what was being done before. This is a much more proper way of doing what the PR suggested.

However I pulled master, made these changes and tested it on the minimal reproduction case, and it still has the same issue, just as bad as before. On enter, and then on every edit to the file, it throws the same error.

So, people still cant lazy-load nvim-treesitter.

**Comment by BirdeeHub** [comment]
I dont know what is the issue though, because, this change deletes the queries directory from nvim-treesitter, correct? So what is even colliding in the first place?

**Comment by PerchunPak** [comment]
> it still has the same issue, just as bad as before

Yeah, I also tried the MRC you wrote above, and it didn't work. This is why I left this solution as a comment, and not as a PR. Though for me, it wasn't as bad as you describe, but it doesn't matter. No idea why the problem persists

> MUCH better than the sketchy bash script

Thanks to figsoda (I miss him). I found out about `linkFarm` in [some old thread](https://discourse.nixos.org/t/psa-if-you-are-on-unstable-try-out-nvim-treesitter-withallgrammars/23321/3) during debugging for #339076

---

P.S. I don't know how I spent so much time debugging treesitter grammars inside nix without ever reading `:help treesitter`...

> Parsers are searched for as `parser/{lang}.*` in any 'runtimepath' directory.
> If multiple parsers for the same language are found, the first one is used.
> (NOTE: This typically implies the priority "user config > plugins > bundled".)

**Comment by PerchunPak** [comment]
Yeah, reading `:help treesitter` answered a lot of my questions... I believe this is a bug in upstream, see https://github.com/nix-community/tree-sitter-nix/issues/84

**Comment by juanibiapina** [comment]
Also happens with ruby: https://github.com/tree-sitter/tree-sitter-ruby/blob/a66579f70d6f50ffd81a16fc3d3358e2ac173c88/queries/highlights.scm#L4

**Comment by PerchunPak** [comment]
> Also happens with ruby: https://github.com/tree-sitter/tree-sitter-ruby/blob/a66579f70d6f50ffd81a16fc3d3358e2ac173c88/queries/highlights.scm#L4

Looks like I found the issue

https://github.com/nvim-treesitter/nvim-treesitter/blob/929ca9c76ee20bb27cffbde4ee90583b6c54d616/queries/jsonnet/locals.scm#L27

Also, here is what `is-not` does: https://github.com/tree-sitter/tree-sitter/blob/4f0d463d49a3f1f2a6eaa75ecc284a5719aad94e/docs/section-4-syntax-highlighting.md?plain=1#L242

Solution for ruby would be to use grammars from `nvim-treesitter` org instead of `tree-sitter/tree-sitter-ruby`. Probably for Nix it would be the same.

Don't know how this could be done, and would love to hear what @figsoda has to say about this. Also, cannot work on a PR rn, so feel free to create one.

**Comment by juanibiapina** [comment]
The nvim-treesitter maintainer has confirmed that external grammars are incompatible with nvim-treesitter in this comment: https://github.com/nvim-treesitter/nvim-treesitter/issues/6870#issuecomment-2218056770

and also clarified that nvim-treesitter doesn't use locals for highlights: https://github.com/nvim-treesitter/nvim-treesitter/issues/6870#issuecomment-2363589200 which could explain why `is-not?` is not implemented there. It appears that `is-not?` only appears in highlights, even in the official documentation.

Does that mean `vimPlugins.nvim-treesitter.withAllGrammars` is working with an incorrect assumption?

**Comment by BirdeeHub** [comment]
https://github.com/NixOS/nixpkgs/pull/344849

This wonderful person once again is saving us with treesitter grammars
