### ISSUE TITLE
Build failure: castero

### ISSUE THREAD

**Issue by JeremiahSecrist** [NixOS/nixpkgs#333019]
### Steps To Reproduce

1. `nix build github:nixos/nixpkgs/master#casetro` **status:** `fail`
2. `nix build github:nixpkgs/nixos-unstable#casetro` **status:** `fail`
3. `nix build github:nixos/nixpkgs/nixos-24.05#castero` **status:** `success`
### Build log

[nix log](https://github.com/user-attachments/files/16531207/dump.txt)

### Additional context

This was discovered via pr #332628

### Notify maintainers
@TheRealKeto 

### Metadata

```console
❯  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.2-cachyos, NixOS, 24.11 (Vicuna), 24.11.20240703.9f4128e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.4`
 - nixpkgs: `/nix/store/dk2rpyb6ndvfbf19bkb2plcz5y3k8i5v-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by TheRealKeto** [comment]
It seems like some tests have began to fail.

When testing, the traceback shows the following tests fail because they don't initialize the `curses` module correctly (with [`curses.initscr()`](https://docs.python.org/3/howto/curses.html#starting-and-ending-a-curses-application)).

- `test_display_get_input_str`
- `test_display_y_n`

These tests don't undermine the functionality of `castero` when building from source, so I'm inclined to believe that the culprit is `pytest` itself.

Looking further, `pytest` throws various deprecation warnings when the tests run.  I fear that the more NixOS receives updates to `pytest`, the more the tests will become more deprecated. It's unclear how NixOS feels about packages and their tests (particularly whether it's necessary for a maintainer to maintain package tests), but the current workaround is to disable these tests.

Adding the tests to the `disabledTests` field produces the result package, and `castero` continues to work as normal. I'd like some input on how to approach as this does feel pretty hacky.

**Comment by JeremiahSecrist** [comment]
We could override pytest back to a previous working version. I looked to the upstream package and it hasn't been updated in a year, to which was just a readme update.

**Comment by TheRealKeto** [comment]
Wouldn't this affect newer packages (assuming they use `pytest` as a unit test framework) who utilize newer features of `pytest`? Though hacky, the solution I've suggested gets the job done. As mention previously, the failure of the tests don't influence `castero`'s functionality.

**Comment by JeremiahSecrist** [comment]
> Though hacky, the solution I've suggested gets the job done. As mention previously, the failure of the tests don't influence castero's functionality.

Disabling problematic tests is done a lot across nixpkgs. Since we know its still working when they are disabled it should be fine.
