### ISSUE TITLE
Package fac

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#33321]
## Issue description

Package [fac](https://github.com/mkchoi212/fac). This seems to be interesting, we should package it.

---

This issue is a friendly reminder for myself to package this some time. I do not feel offended if someone wants to do this, though!

**Comment by matthiasbeyer** [comment]
@dtzWill oh wow, thanks!

**Comment by dtzWill** [comment]
Oh! I thought @jtojnar was the one who filed this request haha, my mistake! That's why I included as maintainer originally....

I thought there was a sudden change of heart! :laughing: 

Anyway, no problem @matthiasbeyer GLHF.

(and it looks like 1.0.2 is out now, if there's a compelling reason to update LMK otherwise I was going to see if they stabilized a bit before updating)
