### ISSUE TITLE
crackmapexec: Fails to run with python 3.12 due to missing imp module

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#333529]
### Describe the bug
crackmapexec fails to run on the unstable branch.

Full backtrace :
```python
/nix/store/p599ivpsxjcg0rmipnf9xb8yx640vw18-crackmapexec-5.4.0/lib/python3.12/site-packages/cme/cli.py:35: SyntaxWarning: invalid escape sequence '\ '
  """,
Traceback (most recent call last):
  File "/nix/store/p599ivpsxjcg0rmipnf9xb8yx640vw18-crackmapexec-5.4.0/bin/.cme-wrapped", line 6, in <module>
    from cme.crackmapexec import main
  File "/nix/store/p599ivpsxjcg0rmipnf9xb8yx640vw18-crackmapexec-5.4.0/lib/python3.12/site-packages/cme/crackmapexec.py", line 10, in <module>
    from cme.cli import gen_cli_args
  File "/nix/store/p599ivpsxjcg0rmipnf9xb8yx640vw18-crackmapexec-5.4.0/lib/python3.12/site-packages/cme/cli.py", line 7, in <module>
    from cme.loaders.protocol_loader import protocol_loader
  File "/nix/store/p599ivpsxjcg0rmipnf9xb8yx640vw18-crackmapexec-5.4.0/lib/python3.12/site-packages/cme/loaders/protocol_loader.py", line 4, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

### Steps To Reproduce
1. run `cme`

### Expected behavior
Should be marked as broken for python 3.12 and above due to not being maintained anymore, it should be recommended to use the maintained fork `netexec`.

### Additional context
I may PR a proper fix later if I find time to do so

### Notify maintainers
@fabaff 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.11-amd64, Kali GNU/Linux, 2024.2, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.23.3`
 - channels(root): `"home-manager, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AkechiShiro** [comment]
I don't know if removal was the best choice for this tool but maybe `netexec` has all the features that `crackmapexec` had so it's alright. 

It's just that I'm not aware if there are any bugs that are not in `crackmapexec` that are in `netexec` but I understand why removal makes sense since later we'll move onto later version of Python such as 3.13 and further more

**Comment by fabaff** [comment]
> I don't know if removal was the best choice for this tool but maybe netexec has all the features that crackmapexec had so it's alright.

As `netexec` is a fork, I guess that the feature set is comparable or even bigger in the meantime. `crackmapexec` is still available for 24.05 and could still be used after 24.11 with some magic.

**Comment by AkechiShiro** [comment]
I ran into this issue where `cme` didn't have it, it is just a minor issue so it's alright on my side, but not sure if there will be any more issues I'll ran into later : 
https://github.com/Pennyw0rth/NetExec/issues/395

**Comment by jamesKhor** [comment]
i see similar errors too, not sure if this is due to python version?

`crackmapexec
/usr/lib/python3/dist-packages/cme/cli.py:35: SyntaxWarning: invalid escape sequence '\ '
  """,
/usr/lib/python3/dist-packages/cme/protocols/winrm.py:324: SyntaxWarning: invalid escape sequence '\S'
  self.conn.execute_cmd("reg save HKLM\SAM C:\\windows\\temp\\SAM && reg save HKLM\SYSTEM C:\\windows\\temp\\SYSTEM")
/usr/lib/python3/dist-packages/cme/protocols/winrm.py:338: SyntaxWarning: invalid escape sequence '\S'
  self.conn.execute_cmd("reg save HKLM\SECURITY C:\\windows\\temp\\SECURITY && reg save HKLM\SYSTEM C:\\windows\\temp\\SYSTEM")
/usr/lib/python3/dist-packages/cme/protocols/smb/smbexec.py:49: SyntaxWarning: invalid escape sequence '\p'
  stringbinding = 'ncacn_np:%s[\pipe\svcctl]' % self.__host
/usr/lib/python3/dist-packages/cme/protocols/smb/smbexec.py:93: SyntaxWarning: invalid escape sequence '\{'
  command = self.__shell + 'echo '+ data + ' ^> \\\\127.0.0.1\\{}\\{} 2^>^&1 > %TEMP%\{} & %COMSPEC% /Q /c %TEMP%\{} & %COMSPEC% /Q /c del %TEMP%\{}'.format(self.__share_name, self.__output, self.__batchFile, self.__batchFile, self.__batchFile)
usage: crackmapexec [-h] [-t THREADS] [--timeout TIMEOUT] [--jitter INTERVAL] [--darrell] [--verbose]
                    {rdp,mssql,ssh,winrm,ftp,ldap,smb} ...
`
