### ISSUE TITLE
`sudo nixos-rebuild list-generations` fails with exit code 141

### ISSUE THREAD

**Issue by RyanGibb** [NixOS/nixpkgs#333734]
### Describe the bug

`sudo nixos-rebuild list-generations` fails with exit code 141

### Notify maintainers

@miallo @Profpatsch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.05 (Uakari), 24.05.20240806.21cc704`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - channels(ryan): `""`
 - nixpkgs: `/etc/nix-path`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by eclairevoyant** [comment]
Can you provide logs? Config info? This doesn't tell us much of anything.

**Comment by eclairevoyant** [comment]
Can you try running it without `sudo`? That appears to work for me.

**Comment by RyanGibb** [comment]
Ah, that does it! Although this behavior is still a bit unexpected

**Comment by miallo** [comment]
Good find! I have to confess I usually only use it without sudo, but I am pretty sure that it worked before... 🤔 
Nevertheless - the issue is with https://github.com/NixOS/nixpkgs/blob/bef98989a27429e1cb9e3d9c25701ba2da742af2/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L733

Diving a bit deeper: $PAGER seems to be defined, but empty, and since I went with `${PAGER:cat}` which only sets cat as default if the variable is undefined (no matter the value) instead of `${PAGER:-cat}` (which also sets cat if the value of the variable is non empty), there is no command to pipe into.

The reason why I added the piping into the pager in the first place is that maybe people have many generations and if they are interested in the first one, it is annoying to scroll up...
Having said that: personally I do not really like it, since you either have everything on one screen anyways and you need to leave less after looking at the results or you can use the scroll back buffer.

So I would tend to vote to remove the line completely. Alternatively we could add the minus sign or try to figure out why the variable is set, but empty 🙃

**Comment by miallo** [comment]
To show that this is the issue, you can run `sudo PAGER=cat nixos-rebuild list-generations` which works as expected

**Comment by eclairevoyant** [comment]
welp 1 minute off, I also submitted a PR haha. Well my reasoning was that `${PAGER:cat}` is just invalid syntax, per https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html. `cat` would act as an offset here, which doesn't make sense.

**Comment by miallo** [comment]
Oh -.- that is indeed true! Thank you! I know why I hate shell syntax xD
Yeah - we should fix it in either way... Back when I implemented it, I thought it was a good idea if you have many generations to always be able to see the first line by piping it into the pager, but I personally am more annoyed by having to press `q` to quit it... I am fine with either solution though :)

**Comment by eclairevoyant** [comment]
Either is fine with me, some `nix` commands automatically page for example, but users can always use their own `PAGER` if they wish, so there's precedent for either solution.
I'll close mine to avoid split discussion.
