### ISSUE TITLE
Update Zanshin to 0.5.71

### ISSUE THREAD

**Issue by silverhook** [NixOS/nixpkgs#33448]
[Zanshin 0.5.0 is out](https://zanshin.kde.org/2018/01/03/zanshin-0.5.0-is-out-2018-will-be-organized/).

If no-one beats me to it, I will try to update the package myself as soon as I (re)learn how to :)

**Comment by JohnAZoidberg** [comment]
Zanshin is now at a commit of `2019-07-28`, which is after 0.5.0.
But since then 0.5.71 has been [released](https://github.com/KDE/zanshin/releases/tag/0.5.71), so it should be upgraded to that official version.
This should be easier, than the move to 0.5.0 because, I think, the dependencies and the build system stayed the same.
So please go ahead and try it :) Or @zraexy

**Comment by JohnAZoidberg** [comment]
Solved by ed68721cdea932ef74db95e1212ab10466991da2
