### ISSUE TITLE
Flip the default value of  `ignoreCompilationError` to `false` for Emacs package

### ISSUE THREAD

**Issue by jian-lin** [NixOS/nixpkgs#335442]
In https://github.com/NixOS/nixpkgs/pull/328573, `ignoreCompilationError` is added to elisp build helpers.  To keep the old behavior, its default value is `true`, which means `nix build` succeeds even if there are native compilation errors.

Flipping the default value of `ignoreCompilationError` to `false` means native compilation errors cause `nix build` to fail.  This is desirable  because native compilation errors usually mean packaging issues or issues in the package itself.

In my test, 12.7% of `emacsPackages` fail to build if `ignoreCompilationError` is set to `false`.  So to flip its default value, we need to fix native compilation for those packages first.

The first and easy part is done in https://github.com/NixOS/nixpkgs/pull/335440.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
I would like some data.
Supposing that our packaging job is working without bugs:

- What is the percentage of these machine-generated packages that will break if we force native compilation globally?
- How hard will be to fix them (whether by sending patches to their upstreams, crafting special options for them etc.)?
- What is expected to happen when we switch to a new version of Emacs?
  - I guess that newer versions of Emacs will become progressively stricter, therefore some packages will be in a state of "broken in the newer Emacs".

**Comment by jian-lin** [comment]
> if we force native compilation globally

To be clear, native compilation is enabled by default.  However, currently native compilation errors are ignored.  This issue wants to make `nix build` fail if there are native compilation errors.

> What is the percentage of these machine-generated packages that will break

There are about 6200 packages in `emacsPackages`.  I already said above that 12.7% of them will be broken by this.  So there are about 780 broken ones.

I find that if `org` is fixed (overriding its `ignoreCompilationError` to `true`), the number decreases to 558.  If `helm` is also fixed (overriding its ` ignoreCompilationError` to `true`), the number decreases to only **382**.  That's promising!

> How hard will be to fix them

I have not touched that too much so I am not sure.

My first [fix][1] is for `codesearch` errors about missing a dependency `dash`.  I sent a PR yesterday and it is merged today.  That is an easy fix and I guess there are many easy fixes like that.

For hard ones, we can restore to the current state, meaning overriding their `ignoreCompilationError` to `true`.

> What is expected to happen when we switch to a new version of Emacs?
> 
> I guess that newer versions of Emacs will become progressively stricter, therefore some packages will switch to a state of "broken in the newer Emacs".

IMHO, it is important to figure out whether there are false negatives, meaning the package can still be used properly even if there are native compilation errors.  Assuming there are no false negatives, then we, as package maintainers of Nixpkgs, should fix all of them.

[1]: https://github.com/abingham/emacs-codesearch/pull/14

**Comment by jian-lin** [comment]
@akirak You seem to do related things.  Would you like to help us on this?

**Comment by akirak** [comment]
@jian-lin I think you are right on your view here. Many packages fail to compile because of upstream issues. 

As a user of my own Nix-based build machinery for Emacs, I either avoid bad packages or work around issues locally. I have worked around only 10-20 packages I think. If you I wish, I can send PRs to those repositories.

While it's good to contribute to individual packages to fix those upstream issues (even without Nix), you should be aware that we will never cover 100% of the auto-generated packages. Packaging issues are constantly produced by authors, and not all maintainers merge PRs immediately. This also implies that some packages in nixpkgs can be insecure. This is why I am working on [my project](https://github.com/emacs-twist) to *not* auto-update all packages and let the user control individual package sources instead.

> I guess that newer versions of Emacs will become progressively stricter, therefore some packages will switch to a state of "broken in the newer Emacs".

In my experience, correct packages build successfully even with the latest byte compiler unless you set `byte-compile-error-on-warn` to t. Most failing packages either have insufficient dependencies or contain code errors. Note that some packages are actually broken, e.g. due to abusing internals of another package which has caused breakage later, and you can't work around such a case unless you fork the package. If the author/maintainer doesn't accept your PR, I think the package should be marked as broken.

Also note that some large packages may have an optional dependency, which causes a build failure but not required for using core features (like indium for lispy). In such a situation, I make a stripped version of the package by removing source files that depend on the problematic dependency. This will not work for nixpkgs. It's hard to properly handle optional dependencies in Emacs Lisp, so package split would be a better fit. However, the author may not agree with this decision. Much work that may not compensate.

**Comment by jian-lin** [comment]
Finally, I have gone through all affected packages.  There are several causes such as needing a writable HOME and errors in elisp code.

A large part of them is caused by dependencies of optional parts.  Even though MELPA suggests creating separated packages for optional parts which have their own dependencies, package authors may not want to do that due to maintenance burden or backward compatibility.

How should we deal with these optional dependencies in Nixpkgs?  I think it is a good idea to add missing optional dependencies because the increased closure size is very small.  Another option is to make those packages ignore compilation errors.  WDYH?

**Comment by AndersonTorres** [comment]
If "ignore compilation errors" option can be avoided with a reasonably small effort, then it should be avoided.
Further, adding the optional dependencies is not bad and ensures nothing goes wrong.

**Comment by jian-lin** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/343925
