### ISSUE TITLE
Update request: picom-pijulius 8.2-unstable-2024-07-01 → 8.2-unstable-2024-08-19

### ISSUE THREAD

**Issue by TanvirOnGH** [NixOS/nixpkgs#336787]
- Package name: picom-pijulius
- Latest released version: [8.2-unstable-2024-08-19](https://github.com/pijulius/picom/commit/acef3360caa6c6ed82eef208ff069eb6e3f55455)

- Current version on the unstable channel: 8.2-unstable-2024-07-01
- Current version on the stable/release channel: 8.2-unstable-2024-04-30

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@YvesStraten

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by YvesStraten** [comment]
Alrighty, will do. The automatic update script is in place but I have no clue when @r-ryantm runs

**Comment by YvesStraten** [comment]
Sorry if I haven't done it yet, I'm highly busy with university

**Comment by TanvirOnGH** [comment]
@YvesStraten ping

**Comment by YvesStraten** [comment]
Has been done, please check #338912. If you @TanvirOnGH or anyone  could build it, test it for me and leave a comment on the PR, that would be great. I do not posses a linux device anymore since the IC of my laptop has been fried, nor do I have a vm to test the pr rn. I am only on `aarch64-darwin`.

Thank you so much in advance, apologies if this too longer than expected.
