### ISSUE TITLE
Package request: legacy-launcher

### ISSUE THREAD

**Issue by Saiv46** [NixOS/nixpkgs#336763]
**Project description**

Legacy Launcher is stable, fast and simple Minecraft launcher. It includes historical and modified versions, alternative (open-source) authentication service @elyby and customizations to enhance Minecraft experience. Unfortunately direct download are unavailable, but Flathub version and source code are.

**Metadata**

* homepage URL: https://llaun.ch/en
* source URL: https://llaun.ch/source
* license: `Uhhh This is more of a "All rights reserved", than anything else.`
* platforms: Java

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by s0me1newithhand7s** [comment]
hm, i could try to package it

**Comment by s0me1newithhand7s** [comment]
> This launcher has been DCMA'd by Mojang, as per the website https://llaun.ch/en.
> 
> Think adding something like this can potentially cause legal troubles and should be avoided entirely.

i'll play devil's advocate here, but in nixpkgs already so much "questioning" packages, like vesktop, yet, nothing gone wrong with repo. as i remember from [my PR for pollymc](https://github.com/NixOS/nixpkgs/pull/325889) - we also have cracked and DMCA'd launcher here.

**Comment by Frontear** [comment]
Arguably Vesktop and the like is different since those exist as original sources still. If Discord performed a DMCA on them I'd suggest removing them from Nixpkgs too.

Anyways I wasn't aware of the existence of other packages like that. Personally I don't think they should exist either just purely off the problems they may bring, but thats a personal opinion. If we havent has trouble before I guess it wouldn't be a problem for another.

This package still needs a 3rd party source though, since the main site is down. Does the flathub have something?

**Comment by Nishimara** [comment]
Site is still there if you visit if from CIS country. Sadly, i don't think it'll help pushing legacy launcher to nixpkgs.
