### ISSUE TITLE
[Add] Haraka SMTP server

### ISSUE THREAD

**Issue by MrSorcus** [NixOS/nixpkgs#33692]
## Issue description
https://github.com/haraka/Haraka

**Comment by wamserma** [comment]
@MrSorcus Is this still relevant?

**Comment by MrSorcus** [comment]
> @MrSorcus Is this still relevant?

Hi. I don't know. I switched to Postfix.

**Comment by wamserma** [comment]
@MrSorcus Please close this PR.

**Comment by MrSorcus** [comment]
> @MrSorcus Please close this PR.

This an issue, not a PR. And what reason for closing?

**Comment by wamserma** [comment]
Yes, i meant to say issue. Are you still motivated to switch from Postfix to Haraka? If so, you can help by providing derivations for Haraka itself, its plugins, a NixOS module etc.
If you are not interested in Haraka anymore, the issue seems no longer relevant and in case someone else is seeking the inclusion in NixOS he/she may open a new issue.
