### ISSUE TITLE
taskwarrior shell tab complete doesnt work anymore

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#33704]
## Issue description

`task a<tab>` does not work as expected

### Steps to reproduce

Install taskwarrior from unstable channel and try to tab-complete:

```
nix-shell -p taskwarrior
task a<tab>
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.12, NixOS, 18.03pre124947.33a4de2941d (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre124947.33a4de2941d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by hedning** [comment]
The problem is the completion script being named `task.sh` and not eg. `task.bash`, which means that bash-completion lazy loading doesn't work (https://github.com/scop/bash-completion/blob/master/bash_completion#L2032). https://github.com/NixOS/nixpkgs/pull/32539 introduced proper lazy loading completion scripts, instead of loading it all on startup.

So a simple fix would be to rename the symlink to `task.bash` here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/taskwarrior/default.nix#L20

Somewhat off-topic, does auto-completion work for packages gotten through `nix-shell` (`XDG_DATA_DIRS` isn't changed when I'm doing it at least)?

**Comment by matthiasbeyer** [comment]
I have the package installed, but added the example with nix-shell without testing it, TBH. Sorry bout that.

The rest: I can fix this, I guess...

**Comment by hedning** [comment]
Looks like the completion script doesn't depend on bash-completion (which explains the `.sh` suffix), so probably expects to be put in `/etc/bash_completion.d/` or something similar. At the moment there's no real difference (aside from lazy loading) between `share/bash-completion/completions/` and `etc/bash_completion.d/` though.

**Comment by arianvp** [comment]
This is broken again in 19.09
