### ISSUE TITLE
browserpass does not taltk to firefox 57

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#33748]
## Issue description
With `firefox-57`, `browserpass` does not work properly. When clicking on the browserpass icon in firefox, browserpass states 'Error talking to browserpass'

### Steps to reproduce

+ Install browserpass via `programs.browserpass.enable = true`
+ Install firefox via `environment.systemPackages = with pkgs; [ firefox ]`
+ Install browserpass browserplugin via firefox marketplace
+ Click on browserpass icon in firefox

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.9, NixOS, 17.09.2498.a9ffb7b0b5a (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2498.a9ffb7b0b5a"`
 - channels(wucke13): `"nixpkgs-18.03pre121983.fd7953d95f4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by hedning** [comment]
Unfortunately I think this is unfixable at the moment. Firefox expects native messaging manifests to be found in `/usr/{lib,lib64}/mozilla/native-messaging-hosts/` (Chrome uses `/etc/`). This means there's no way to expose manifest files on NixOS on the system level. 

You can work around it by linking the firefox manifest from `browserpass` into `~/.mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json`. Something like this should do it:
```
mkdir -p ~/.mozilla/native-messaging-hosts/
ln -s $(nix-build '<nixpkgs>' -A browserpass)/lib/mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json ~/.mozilla/native-messaging-hosts/
```

Relevant Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1318461

**Comment by ttuegel** [comment]
This was fixed in #31743 by a Nixpkgs option. Maybe `programs.browserpass.enable` should set the correct Nixpkgs option by default{

**Comment by teto** [comment]
I never managed to make it work either so thanks @ttuegel for the pointer. I believe home-manager installs it in ~/.mozilla so that could work too.

**Comment by wucke13** [comment]
So this is fixable, the fix was not straightforward but it is going to be fixed in 18.03?

**Comment by hedning** [comment]
Yeah, disregard my comment above (nixpkgs patch around the firefox issue).

If I understand correctly you want to do something like this in `configuration.nix` to make browserpass work now:
```nix
 nixpkgs.config.firefox.enableBrowserPass = true;
```

**Comment by etu** [comment]
I'm experiencing this same issue with firefox 59.0.1.

I have tried both firefox-bin and firefox. I'm mostly using firefox-bin because I like the Mozilla branding, but it doesn't matter that much really.

I have added `programs.browserpass.enable = true;` in my configuration. I've used browserpass in firefox a long time ago (before 57 I believe) using home-manager and still have `programs.browserpass.enable = true;` set in home-manager which successfully creates the symlink in `.mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json`.

I've just started google-chrome up to test there and that seems to work. But that won't help me that much in firefox :smile:

**Comment by wucke13** [comment]
So this is still broken. Using browserpass-ce I get the suggestions but when clicking on them, it only displays "Error: An unexpected error occurred". Will this be fixed?

**Comment by ttuegel** [comment]
This works for me with `firefox` 59.0.1. IIUC, it won't work with `firefox-bin`.

**Comment by wucke13** [comment]
```
$ firefox -v        
Mozilla Firefox 59.0.2
```
Hmmh. Installed via `environment.systemPackages = with pkgs; [ firefox ];`. Using `programs.browserpass.enable = true;` for browserpass.

**Comment by etu** [comment]
@wucke13 Do you have gpg in your system-packages or not?

I'd say that it shouldn't be needed, but might be needed.

**Comment by etu** [comment]
If I look in the browserpass source, I found this function: https://github.com/dannyvankooten/browserpass/blob/4ca5c7c0d557f4aece063da54683eb04436d59be/browserpass.go#L135-L155

Which seems to be the one that failed. It's purpose seems to be to find a gpg binary. But it fails since it's not in your environment.

If I look in our package for browserpass https://github.com/NixOS/nixpkgs/blob/fbac1cbc06568380b538e81546e9d3b1715cab14/pkgs/tools/security/browserpass/default.nix -- I don't see that we patch the path to the gpg binary, which means that it must exist in the system environment for browserpass to find it.

A temporary fix for you would be to add it to your system packages, but in reality browserpass should be patched with our path to gpg.

**Comment by wucke13** [comment]
The temporary fix does work for me. Closing since you started a PR on this. Great thanks!
