### ISSUE TITLE
/etc/zshrc overrides environment variables like HISTFILE with "history defaults"

### ISSUE THREAD

**Issue by mekeor** [NixOS/nixpkgs#33797]
## Issue description

If you set `HISTFILE` variable in `~/.zprofile` it will be overriden by `/etc/zshrc`. You could instead use `~/.zshrc` to set the `HISTFILE` variable but I don't think that's where it belongs to.

I would suggest

1. either we remove [these](https://github.com/NixOS/nixpkgs/blob/release-17.09/nixos/modules/programs/zsh/zsh.nix#L152-L157) "history defaults" from `/etc/zshrc` because I don't see any reason why NixOS should not simply use the ZSH defaults of these variables.

2. Or we move those "history defaults" from `/etc/zshrc` to `/etc/zprofile`.

### Steps to reproduce

Set `HISTFILE` variable in `~/.zprofile` and watch it being overriden by `/etc/zshrc`.

**Comment by Infinisil** [comment]
`HISTFILE` is supposed to be set in `/etc/zshrc` and `~/.zshrc`, since these are the files being sourced for interactive shells, which is when you'll want to have history. Read the `STARTUP/SHUTDOWN FILES` section in `man 1 zsh`. Thanks to the folks in #zsh for answering my questions regarding this.

**Comment by mekeor** [comment]
Thank you, @Infinisil, very much for finding out. Forgive me this disruption.
