### ISSUE TITLE
Package request: Thunderbird Beta and Nightly

### ISSUE THREAD

**Issue by iamstonecutter** [NixOS/nixpkgs#338083]
**Project description**

Would like Thunderbird beta and nightly capabilities similar to how Firefox derivatives work with NixOS, using the commands below. If we can get the same implementation but for Thunderbird, that would be a great.

```
programs.firefox.enable = true;
programs.firefox.package = pkgs.latest.firefox-nightly-bin;
```

**Metadata**

* homepage URL: https://thunderbird.net
* source URL: https://github.com/thunderbird
* license: Mozilla Public License (MPL) 2.0.
* platforms: Linux

**Comment by SuperSandro2000** [comment]
nixpkgs tries to avoid packaging prerelease versions of software as much as possible as the maintenance burden on them is usually much higher because of early bugs and the higher release schedule. Since we already have mutliple variants of firefox there is no need to package beta/nightly.

This might be a good topic for an out of tree repo though.

Edit: eg https://github.com/nix-community/flake-firefox-nightly
