### ISSUE TITLE
Haddock API (as dep of GHCJS) fails to build on unstable channel

### ISSUE THREAD

**Issue by bradparker** [NixOS/nixpkgs#33815]
## Issue description

Haddock API, (as dep of GHCJS) fails to build on unstable channel with linker error. Can't find `tinfo`.

Succeeds on the `nixos-17.09` channel.

Relevant log lines:

```
Preprocessing test suite 'spec' for haddock-api-2.18.1..
Building test suite 'spec' for haddock-api-2.18.1..
Linking dist/build/spec/spec ...
/nix/store/wxn5gn8amxm1w0ikcx4gbs8a17wvss4j-binutils-2.28.1/bin/ld.gold: error: cannot find -ltinfo
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
builder for ‘/nix/store/ki40120vd11bxbz192ya5340yymiqff3-haddock-api-2.18.1.drv’ failed with exit code 1
```

### Steps to reproduce

```
$ nix-channel --add nixpkgs https://nixos.org/channels/nixos-unstable
$ nix-channel --update
$ nix-shell -p "haskell.packages.ghcjs.ghc"
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.0-1-amd64, PureOS GNU/Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
# This channel is the now working version, was "unstable" previously
 - channels(brad): `"nixpkgs-17.09.2683.360089b3521"`
 - nixpkgs: `/home/brad/.nix-defexpr/channels/nixpkgs`
```

**Comment by ElvishJerricco** [comment]
This is an issue with `ghc821`, which is a binary distribution of GHC meant for bootstrapping. Many packages fail to build with the same error message because this GHC fails to link with `ncurses` properly. `ghc822` does not have this problem.

As far as GHCJS goes, you can't even build it with `ghc822` or `ghc802` due to some odd requirements on cabal. It needs to be built with `Cabal-1.24.*` (and probably with `ghc-8.0.2`?), but it needs on the path a `cabal-install-2.0.*`.

**Comment by bradparker** [comment]
@ElvishJerricco thanks a bunch for helping me with this :D. #34037 means I can close this issue, eh?
