### ISSUE TITLE
fonts broken for some applications

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#338933]
### Describe the bug

root cause is #324516 removing the `<include />` directive from `fonts.conf`. #338326 (and #338815) attempted at fixing this, but they are incomplete. as they only hot patched the `fonts.conf` installed to `/etc`, but not the one in the output of `fontconfig`, which is used by some packages. 

for example:

https://github.com/NixOS/nixpkgs/blob/b79ce4c43f9117b2912e7dbc68ccae4539259dda/pkgs/applications/networking/browsers/vivaldi/default.nix#L114-L115

(just search for `FONTCONFIG_FILE`, there are many more.)

feels wrong to me to hardcode a fonconfig path for the application instead of using `/etc/fonts`.

related: #338908 

### Notify maintainers

@teto @K900 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by yshui** [comment]
a simple workaround for this is setting `FONTCONFIG_FILE` and `FONTCONFIG_PATH` in `system.sessionVariables`.

**Comment by yshui** [comment]
I reverted #324516 locally and now i have 700 derivations to build :(

**Comment by teto** [comment]
sorry about that. I usually run a nixpkgs-review on my PRs, especially of this magnitude but It's been some time so I dont remember the details.
I confess I missed that pkgs/development/libraries/fontconfig/default.nix was calling ./make-fonts-conf.xsl directly instead of `makeFontsConf`. If it stays like this, I fear a similar issue rises again.
Thanks for providing fixes to the issue.

**Comment by yshui** [comment]
don't worry about it, everyone makes mistakes/misses stuff from time to time, it's inevitable.

i am more disappointed by the fact nixpkgs doesn't have some process in place to catch mistakes like this. and mistakes like this isn't even that subtle. (well, maybe things like this is actually much harder to catch than it seems on the surface. i am not involved in nixpkgs development, so please correct me.)

personally, since i started using `nixos-unstable`, on average i have had easy-to-catch bugs like this around once per month. which feels way more frequent than it should be, and does erode my trust in nixpkgs.

**Comment by tukanoidd** [comment]
> i am more disappointed by the fact nixpkgs doesn't have some process in place to catch mistakes like this. and mistakes like this isn't even that subtle. (well, maybe things like this is actually much harder to catch than it seems on the surface. i am not involved in nixpkgs development, so please correct me.)
> 
> personally, since i started using `nixos-unstable`, on average i have had easy-to-catch bugs like this around once per month. which feels way more frequent than it should be, and does erode my trust in nixpkgs.

Not involved either, just pure speculation, but i think it's just not feasible to have some kind of automated testing for these things because there are more than 100k packages, 10k module options + home-manager, which also interacts with nixpkgs for some things. And they all can be mix-and-matched in variaety of different configurations, which nobody can predict. The language itself is lazy-evaluated and doesn't have any static type safety that you could encode your logic with (lib.types are runtime-based and dont enforce any compile-time guarantees either, just fancy test "identity" functions from what I can gather) and get errors as soon as the code is not used properly (LSPs try to provide as much static typing as possible based on pre-evaluated nixpkgs, but that usually is not enough). Basically, everything is mostly runtime and configuration (in terms of personal preferences) - dependant, hard/impossible to automate (unless you can think of something, then you're only welcome to contribute and make everyone's lives easier!)

**Comment by eclairevoyant** [comment]
Er no, we have package tests and NixOS tests, it's documented in the manual.
https://nixos.org/manual/nixpkgs/stable/#var-meta-tests-packages

**Comment by tukanoidd** [comment]
> Er no, we have package tests and NixOS tests, it's documented in the manual.
> https://nixos.org/manual/nixpkgs/stable/#var-meta-tests-packages
> 
> And half the time it's people not even checking if their PRs eval, so that's not even at the level of writing package tests. We just need more restraint and less self-merges and other rushed merges.

My bad, should've looked.

**Comment by luiswirth** [comment]
This just broke my system...
Is there a workaround?
I tried adding this to my `configuration.nix`:
```nix
  environment.sessionVariables = {
    FONTCONFIG_FILE = "${pkgs.fontconfig.out}/etc/fonts/fonts.conf";
    FONTCONFIG_PATH = "${pkgs.fontconfig.out}/etc/fonts";
  };
```
but it doesn't help :(

**Comment by K900** [comment]
The fix should be making its way to channels very soon.

**Comment by MrSom3body** [comment]
> This just broke my system... Is there a workaround? I tried adding this to my `configuration.nix`:
> 
> ```nix
>   environment.sessionVariables = {
>     FONTCONFIG_FILE = "${pkgs.fontconfig.out}/etc/fonts/fonts.conf";
>     FONTCONFIG_PATH = "${pkgs.fontconfig.out}/etc/fonts";
>   };
> ```
> 
> but it doesn't help :(

You need to remove the .out part so it looks like this:
```nix
environment.sessionVariables = {                               
  FONTCONFIG_PATH = "${pkgs.fontconfig}/etc/fonts";            
  FONTCONFIG_FILE = "${pkgs.fontconfig}/etc/fonts/fonts.conf"; 
};                                                             
```

**Comment by K900** [comment]
No, you don't, and it's not actually going to help.

**Comment by couchpotato007** [comment]
> This just broke my system... Is there a workaround? I tried adding this to my `configuration.nix`:
> 
> ```nix
>   environment.sessionVariables = {
>     FONTCONFIG_FILE = "${pkgs.fontconfig.out}/etc/fonts/fonts.conf";
>     FONTCONFIG_PATH = "${pkgs.fontconfig.out}/etc/fonts";
>   };
> ```
> 
> but it doesn't help :(

if you use flakes you can simply use an old flake.lock file until the fix comes. That works for me.

**Comment by nakoo** [comment]
> The fix should be making its way to channels very soon.

Is there a PR tracker related to this?

**Comment by eclairevoyant** [comment]
You'll have to wait for the next `staging-next` merge - #338840

**Comment by K900** [comment]
The fix for _most_ applications should be in nixos-unstable now.

**Comment by luiswirth** [comment]
This did fix many of my applications. But wezterm is for instance still broken... So this issue is not fully fixed.

**Comment by K900** [comment]
What is broken about wezterm?

**Comment by eclairevoyant** [comment]
@luiswirth unrelated issue - #336069

**Comment by acid-bong** [comment]
Is this issue the reason why `mono` font is (was?) no longer an alias for `monospace`? I just updated today (using nixos-unstable) and Rofi (which uses `mono` instead of `monospace`) now falls back to sans-serif
