### ISSUE TITLE
Can the commercial version of Qt be installed?

### ISSUE THREAD

**Issue by jor1196** [NixOS/nixpkgs#34183]
I have a doubt if I can install this with Nix?
I also have another
Can proprietary software be installed with Nix?

**Comment by FRidh** [comment]
Closed-source typically require patching or being build with the `buildFHSUserEnv` function. I don't know regarding the commercial Qt toolkit by itself. We do have some closed-source Qt applications packaged (e.g. `mendeley`).

**Comment by peterhoeg** [comment]
In principal *any* software (open and closed) can be used with nix - some with little to no effort and others with a huge amount of work.  The ML or IRC/Matrix is really the better places for this kind of Q&A.

**Comment by CMCDragonkai** [comment]
There's a bunch of proprietary software inside Nixpkgs. The only restriction is that to be in Nixpkgs, the software must be "downloadable" without prompting. (And this not even true with cuDNN which requires the user to download it manually into the `/nix/store` (even though I did find a unattended (undocumented yet official) download of cuDNN solution it has not been integrated into Nixpkgs)).

There's even software in nixpkgs that requires you to pass in a license to utilise. Such as the charles proxy and the sublime text editor. Both of these are in Nixpkgs, but they are not searchable on the https://nixos.org/nixos/packages.html due to political issues. These software often have some amount of utility even when the license is not used, so they represent "trialware" to some extent. The license mechanism is done through Nixpkgs. Instead you either apply the license after installing in some config location, or you use the Nix language to override the derivation and apply the license.

There's also no mechanism for payments because Nixpkgs is not an app-store. I've been pondering this problem of how to make opensource ecosystems like Linux be seamlessly merged with proprietary appstores that most of the world uses. This may result in political/philosophical differences though...
