### ISSUE TITLE
Restic service doesn’t use security wrapper binary

### ISSUE THREAD

**Issue by TheRedScreen64** [NixOS/nixpkgs#341999]
### Describe the bug
According to the [wiki](https://nixos.wiki/wiki/Restic) a security wrapper is used to create a binary that doesn’t run as root user but has full file access. But when creating a restic service through services.restic.backups it doesn’t use this wrapper. Instead it will run as root user unless a user is specified. It doesn’t seem like there is an option to make it run the wrapper binary.

### Steps To Reproduce
1. Create a security wrapper according to the wiki
2. Create a restic backup service

### Expected behavior
There should be an option, or even by default, to make the service run the wrapper binary with the wrapper user so that it has full file access without running as root.

### Additional context
I want to backup a dir that includes files owned by different users, some even by the root user. From my understanding the security wrapper should allow me to backup this dir without running the service as root.

### Notify maintainers
@kai-tub

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kai-tub** [comment]
Hey :wave: 
I am not the maintainer of the restic module but I can still try to answer your question. Looking at the code, you can see that you _can_ specify the user that is used by the service unit:

https://github.com/NixOS/nixpkgs/blob/8f7492cce28977fbf8bd12c72af08b1f6c7c3e49/nixos/modules/services/backup/restic.nix#L153-L160

I do not think the wiki is a good resource in this instance. If you are using the `restic` NixOS module, then there is no need to create a security wrapper, IMO.
For me, it also makes sense to run a backup service as `root` since it should be able to read _all_ files that are defined in the backup directory and not (potentially) silently skipping over files that were created by a different user. This is especially common when backing up directories from other users.

But nothing stops you from creating a `backup` user/group and using that in the service; so I do not really see anything that should be changed in NixOS module in that regard.

One thing that could be improved is that the service could _only_ see files that are defined in the module config but then we have the issue of handling the `exclude` options of restic correctly, i.e. it won't be a trivial implementation.

**Comment by TheRedScreen64** [comment]
Thanks for your response!
I really appreciate you taking the time, especially since you’re not the maintainer.
I see your point about running the service as root. However, my motivation for using a security wrapper was to avoid running the restic service as root while still maintaining full file access. I thought that this could reduce security risks. But it could well be that I’m overthinking this and the security risks are marginal. In that case, it's probably easier to just run it as root. 
In general, one would have to weigh whether it is more complicated to implement this than it is insecure to run as root.

**Comment by dotlambda** [comment]
> I thought that this could reduce security risks.

It wouldn't since the restic executable would still run as root.

**Comment by DerGuteMoritz** [comment]
> It wouldn't since the restic executable would still run as root.

AFAIUI the idea would be to run the security wrapper (which has only the necessary file capabilities) as an unprivileged user, no? Restic's documentation even has a [guide](https://restic.readthedocs.io/en/latest/080_examples.html#backing-up-your-system-without-running-restic-as-root) on how and why to do this, so unless I'm missing something, I'm voting to reopen the issue. I'd also be willing to try my hand at a patch then.

**Comment by DerGuteMoritz** [comment]
The following appears to do the trick:

```nix
users.groups.restic = {};
users.users.restic = {
  isSystemUser = true;
  group = "restic";
};
security.wrappers.restic = {
  source = "${pkgs.restic}/bin/restic";
  owner = "restic";
  group = "restic";
  permissions = "u=rwx,g=,o=";
  capabilities = "cap_dac_read_search=+ep";
};
services.restic.backups.foo = {
  # ...
  package = pkgs.writeShellScriptBin "restic" ''
    exec /run/wrappers/bin/restic "$@"
  '';    
};
```

But it would still be nice to support this as a first-class feature IMHO.
