### ISSUE TITLE
GHCJS versioning

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#34217]
GHCJS [has pushed a GHC 8.2 branch](https://github.com/ghcjs/ghcjs/tree/ghc-8.2). Given this, I'd be surprised if the 8.0 branch continues to get very much support, though it has been quite stable for a while now. So I'm proposing we follow suit with the package sets indexed by GHC version, and do the same with GHCJS. That is, move `haskell.packages.ghcjs` to `haskell.packages.ghcjs7103`, move the current `haskell.packages.ghcjsHEAD` to `haskell.packages.ghcjs80`, set `haskell.packages.ghcjs` to the `ghcjs80` set, and put the 8.2 branch on `haskell.packages.ghcjsHEAD` (and potentially `ghcjs82`, depending on how stable it is).

@peti what do you think of this? Having `ghcjs82` would probably make it easier to interact with the LTS-10 package set we're based on. Of course, this is predicated on having the GHCJS 8.2 branch building in Nix, which apparently has a bunch of changes in the build system. But I have a lousy prototype for that.

**Comment by peti** [comment]
My impression is that ghcjs is frequently broken in Nixpkgs and it often takes several weeks before someone notices and/or bothers to spend time fixing the issue. Therefore, I wonder whether supporting *multiple versions* is a good idea? Personally, I'd be perfectly happy to have *one* ghcjs package set and to base that one on the 8.2.x branch. I don't think we gain much by trying support multiple versions.

Cc: @basvandijk

**Comment by ElvishJerricco** [comment]
@peti Well we have two versions right now: 7.10 and 8.0. It's just that one of them goes by the name "HEAD" at the moment. I know that at least the `miso` community commonly uses the 7.10 version from `nixpkgs`, and the `reflex` community commonly uses the 8.0 version, so I do think there is value in maintaining other versions.

That said, it may not be valuable *enough* to warrant the ever-increasing maintenance costs. So I think we should maintain at least the ones that already work, plus 8.2. But in the future, we should *cease* to maintain any old version as soon as it becomes non-trivial to support that version.

**Comment by basvandijk** [comment]
@ElvishJerricco at LumiGuide we use `miso` with the `ghcjsHEAD` package set. So *we* wouldn't mind if the current `ghcjs` (7.10) package set is dropped to ease maintenance costs. 

@peti I would be very happy with a single well maintained `ghcjsHEAD` package set (targeting the 8.2 branch).

I think we should consider having multiple GHCJS package sets once GHCJS starts to have releases.

@ElvishJerricco let me know if you need help testing your prototype. I'm really looking forward to using GHCJS-8.2!

ping @FPtje @roelvandijk.

**Comment by ElvishJerricco** [comment]
For now, we have adopted the convention of keeping old GHCJSes and aliasing `ghcjs`.

**Comment by peti** [comment]
Just FYI: I intend to drop ghc 7.10.3 soon, and this implies that we'll drop the corresponding ghcjs too.

**Comment by ElvishJerricco** [comment]
@peti Fair enough. @dmjio you may want to start making arrangements...

**Comment by peti** [comment]
@dmjio, because ghc-7.10.x is old and I don't want to maintain it.

**Comment by dmjio** [comment]
@peti, understandable. Can you assign ownership of the derivation to me instead ? And I’ll perform the maintenance. I’d like to keep it around because GHCJS 7.10.3 is the only version that has a working GHCJSi.

**Comment by peti** [comment]
> Can you assign ownership of the derivation to me instead?

Such a thing as "assigning ownership" does not exist. Nixpkgs is a collaborative effort and people who make changes that affect other derivations, say, because they're changing stdenv for cross-compiling and whatnot, cannot just leave other packages in a broken state and say "someone else should fix that". If you're changing stdenv or updating binutils or updating gcc, then you have to fix the fallout from your change, too. This means that derivations we keep in Nixpkgs impose a cost on the team as a whole, especially if those are complex builds that are hard to understand, debug, and maintain. Keeping ghc-7.x around in Nixpkgs is too expensive from that PoV.

If you feel strongly about ghc 7.10.3, then I'd recommend that you maintain it in a separate repo and document how people who'd like to use it can register that repo as an overlay.

**Comment by dmjio** [comment]
I meant like put my name in the `maintainers` list in the derivation, but I guess it's already there:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/ghcjs/base.nix#L191

If you don't want to maintain it, I can't stop you. I'll handle things on my end accordingly. The real issue here is GHCJS itself.
