### ISSUE TITLE
Build failure: cdemu

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#342530]
### Steps To Reproduce

1. build cdemu/vhba on latest nixos-unstable

### Build log

```
vhba> /build/vhba-module-20240202/vhba.c:1087:15: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [-Werror=incompatible-pointer-types]
vhba>  1087 |     .remove = vhba_remove,
vhba>       |               ^~~~~~~~~~~
vhba> /build/vhba-module-20240202/vhba.c:1087:15: note: (near initialization for 'vhba_platform_driver.<anonymous>.remove')
kwin-better-blur> -- Found KF6Config: /nix/store/bkxfqm4zigarz5k4rc58mzmjx964nbbw-kconfig-6.6.0-dev/lib/cmake/KF6Config/KF6ConfigConfig.cmake (found version "6.6.0")
kwin-better-blur> -- Found KF6ConfigWidgets: /nix/store/yin77vn55ngw1dpprm56crzz3mjm6idh-kconfigwidgets-6.6.0-dev/lib/cmake/KF6ConfigWidgets/KF6ConfigWidgetsConfig.cmake (found version "6.6.0")
vhba> cc1: all warnings being treated as errors
kwin-better-blur> -- Found KF6CoreAddons: /nix/store/1kf9xmlm2bgy2jllbms9y3w8vr6b85la-kcoreaddons-6.6.0-dev/lib/cmake/KF6CoreAddons/KF6CoreAddonsConfig.cmake (found version "6.6.0")
vhba> make[3]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/scripts/Makefile.build:244: /build/vhba-module-20240202/vhba.o] Error 1
vhba> make[2]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:1926: /build/vhba-module-20240202] Error 2
vhba> make[1]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:224: __sub-make] Error 2
vhba> make[1]: Leaving directory '/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build'
vhba> make: *** [Makefile:14: modules] Error 2
error: builder for '/nix/store/9r6hwr3mkcs80hl8gx23d1xpj0y27z42-vhba-20240202.drv' failed with exit code 2;
       last 23 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/xrx8sw2fri58sw11pdqr7k260x77va7d-vhba-module-20240202.tar.xz
       > source root is vhba-module-20240202
       > setting SOURCE_DATE_EPOCH to timestamp 1706870626 of file vhba-module-20240202/vhba.c
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > build flags: SHELL=/nix/store/izpf49b74i15pcr9708s3xdwyqs4jxwl-bash-5.2p32/bin/bash O=\$\(buildRoot\) CC=/nix/store/zznja5f8v3jafffyah1rk46vpfcn38dv-gcc-wrapper-13.3.0/bin/cc HOSTCC=/nix/store/zznja5f8v3jafffyah1rk46vpfcn38dv-gcc-wrapper-13.3.0/bin/cc HOSTLD=/nix/store/b74nxf0yn2dzha02mgdxyklaqjaijzqp-binutils-wrapper-2.42/bin/ld ARCH=x86_64 KDIR=/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build INSTALL_MOD_PATH=\$\(out\)
       > make -C /nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build M=/build/vhba-module-20240202 modules
       > make[1]: Entering directory '/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build'
       >   CC [M]  /build/vhba-module-20240202/vhba.o
       > /build/vhba-module-20240202/vhba.c:1087:15: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [-Werror=incompatible-pointer-types]
       >  1087 |     .remove = vhba_remove,
       >       |               ^~~~~~~~~~~
       > /build/vhba-module-20240202/vhba.c:1087:15: note: (near initialization for 'vhba_platform_driver.<anonymous>.remove')
       > cc1: all warnings being treated as errors
       > make[3]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/scripts/Makefile.build:244: /build/vhba-module-20240202/vhba.o] Error 1
       > make[2]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:1926: /build/vhba-module-20240202] Error 2
       > make[1]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:224: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build'
       > make: *** [Makefile:14: modules] Error 2
       For full logs, run 'nix log /nix/store/9r6hwr3mkcs80hl8gx23d1xpj0y27z42-vhba-20240202.drv'.
error: 1 dependencies of derivation '/nix/store/5d881pnr6vrz5p14p2dhi7c1vjacyfi9-linux-6.11-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d4w29j0c23kbpkcl4z2ki0grq2idw6cl-nixos-system-nixos-desktop-24.11.20240916.99dc878.drv' failed to build
┏━ 1 Errors:
 ⋮
┃        > unpacking source archive /nix/store/xrx8sw2fri58sw11pdqr7k260x77va7d-vhba-module-20240202.tar.xz
┃        > source root is vhba-module-20240202
┃        > setting SOURCE_DATE_EPOCH to timestamp 1706870626 of file vhba-module-20240202/vhba.c
┃        > Running phase: patchPhase
┃        > Running phase: updateAutotoolsGnuConfigScriptsPhase
┃        > Running phase: configurePhase
┃        > no configure script, doing nothing
┃        > Running phase: buildPhase
┃        > build flags: SHELL=/nix/store/izpf49b74i15pcr9708s3xdwyqs4jxwl-bash-5.2p32/bin/bash O=\$\(buildRoot\) CC=/nix/store/zznja5f8v3jafffyah1rk46vpfcn38dv-gcc-wrapper-13.3.0/bin/cc HOSTCC=/nix/store/zznja5f8v3jafffyah1rk46vp…
┃        > make -C /nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build M=/build/vhba-module-20240202 modules
┃        > make[1]: Entering directory '/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build'
┃        >   CC [M]  /build/vhba-module-20240202/vhba.o
┃        > /build/vhba-module-20240202/vhba.c:1087:15: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [-Werror=incompatible-pointer-types]
┃        >  1087 |     .remove = vhba_remove,
┃        >       |               ^~~~~~~~~~~
┃        > /build/vhba-module-20240202/vhba.c:1087:15: note: (near initialization for 'vhba_platform_driver.<anonymous>.remove')
┃        > cc1: all warnings being treated as errors
┃        > make[3]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/scripts/Makefile.build:244: /build/vhba-module-20240202/vhba.o] Error 1
┃        > make[2]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:1926: /build/vhba-module-20240202] Error 2
┃        > make[1]: *** [/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/source/Makefile:224: __sub-make] Error 2
┃        > make[1]: Leaving directory '/nix/store/d4hzyrkkp1lqy8z30k10q6za7y4gxy5i-linux-6.11-dev/lib/modules/6.11.0/build'
┃        > make: *** [Makefile:14: modules] Error 2
┃        For full logs, run 'nix log /nix/store/9r6hwr3mkcs80hl8gx23d1xpj0y27z42-vhba-20240202.drv'.
```

### Additional context

Looks like there's a new vhba module version: https://sourceforge.net/projects/cdemu/files/vhba-module/

### Notify maintainers
@bendlas 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.10, NixOS, 24.11 (Vicuna), 24.11.20240913.345c263`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bendlas** [comment]
broken by https://github.com/NixOS/nixpkgs/pull/342703

**Comment by romatthe** [comment]
Apologies for bringing up a series of PRs that seemed to have been a little contentious, but from what I can tell, CDEmu and the VHBA kernel module are still broken (exact same issue) on stable (24.05) as of writing. I'm not 100% sure why the issue was closed.

**Comment by bendlas** [comment]
Well, fixing the build in previous stable is probably moot, now that 24.11 has been released.

I personally still am mystified why @NixOS/moderation has decided to issue a formal warning against me, but not against the person who decided to do a hot-headed revenge-revert; in a process that they called "mediation", where not a single perspective has been mediated between myself and opposing parties.

I don't know what I'm supposed to learn from being slammed for self-merging a trivial fix to a package where I've been creator and sole maintainer for years, in a PR that was **already approved by another member**, while the person who has called for my head most vocally seems to be able to [use](https://github.com/NixOS/nixpkgs/pull/370612) [`master`](https://github.com/NixOS/nixpkgs/pull/371281) [as](https://github.com/NixOS/nixpkgs/pull/371539) [their](https://github.com/NixOS/nixpkgs/pull/371545) [personal](https://github.com/NixOS/nixpkgs/pull/350292) [scratch](https://github.com/NixOS/nixpkgs/pull/368623) [pad](https://github.com/NixOS/nixpkgs/pull/348024) with impunity.

And most importantly: I don't know how I'm supposed to get out of a situation, where a **formal process that can end in my expulsion** has been started, but the party who owns the process (moderation) refuses to elaborate further. In fact, my attempts to gain clarity have been met with:

> [The mediation process] is private not to "public shame" and make it easy for people to change their behaviour without damage to their public image.

Which to me just sounds like "shame if somebody took your commit access away". Then also:

> I already spent 30 minutes out of my spare time trying to mediate this with you today. I won't spend any more time.

Which speaks for itself I think, but note that this has been on 18. September 2024, and any of my attempts to reconnect since have fallen on deaf ears.

Note that despite having permission by the relevant mod team member, I'm still protecting their identity, because to me, it's not about names and I'm speaking to the mod team as a community body, not to individual members personally. Though my patience is wearing thinner, every time this BS is taking my head for a spin. And just because I've not published all the private correspondence yet, doesn't mean I'm not refining the open letter, every time I need an outlet.

What I have been doing, is going on soft strike and refused to do significant work on NixOS, but that makes me uncomfortable and isn't good for the community. So I'm vowing to become gradually more vocal (and unfortunately necessary also annoying) this year, until this is either resolved, or until I'm being ejected from the community in an obvious display of injustice. What I'm refusing to do is go kamikaze or quiet-quit, as many members seem to have been doing since the infamous open letter.

If this attitude seems belligerent to anyone reading this, I assure you it's not. I do genuinely want to understand and improve my interactions, and continue to contribute productively. But as I said, I still don't know what I'm supposed to learn, because if that is "There is an in-crowd, you're not part of it, so better watch your mouth", I am refusing to learn that. Also, I don't want to give up my position just because someone is slighting me, because, I'm planning on staying and cleaning up your mess, long after you've burned out and moved on to greener pastures.

P.S.: I do think, moderation is necessary, and I still think that in a world of choosing between lesser evils, @NixOS/moderation is probably a net positive, even in its current operation. But ... oh boy ... the way, you're doing it is not the way to do it and I'm telling you that from almost two decades of experience, running (non-tech; IRL) communities. Please get back to me and I'll stop being publicly annoying, promise. Nobody made you take on the responsibility, but now that you have it, you need to own up! Or at least hand the matter off to the assembly, if you think it warrants that level of scrutiny.

**Comment by picnoir** [comment]
Hey bendlas,

I'm answering on behalf of the NixOS moderation team.

You were issued a formal warning about your adversarial communication style last September. As we pointed to you in private, the goal of such a warning was to nudge you to rethink the way you communicate with other contributors.

This warning was not triggered by a single particular occurence, but instead by a communication pattern you had. You decided to act adversarily against other contributors, alienating some of them. This builds up over several months before we decided to intervene.

In no particular order, these posts lead to this decision:

https://github.com/NixOS/nixpkgs/pull/342549#issuecomment-2358362434
https://discourse.nixos.org/t/can-we-please-stop-breaking-stuff-willy-nilly/48496
https://github.com/NixOS/nixpkgs/pull/337478#issuecomment-2310779183
https://github.com/NixOS/nixpkgs/pull/340663#issuecomment-2359497645
Reading "until this is either resolved or until I'm being ejected from the community in an obvious display of injustice", we're wondering what would you expect us to do to consider this matter as "resolved"?

After a formal warning, people usually understand what behavior was problematic and adjust it, which seems to have been your case so far since we did not see any new incidents. Or, sometimes, they decide to double down and eventually get banned.

It seems like you decided to strike and send us ultimatum letters asking us to retract the warning. To be fully honest, it's a bit of a surprising ask and we do not really know how to act on it.

On one hand, you're not exhibiting any problematic behavior anymore towards other contributors, which is great. On the other hand, you ask us either to retract the formal warning or ban you. We still think this warning is deserved, it won't be retracted. We're not really willing to escalate this further either.

So, now comes our question: what should we do next?

**Comment by bendlas** [comment]
> Hey bendlas,
> 
> I'm answering on behalf of the NixOS moderation team.

Hey picnoir and NixOS moderation team,

thanks for getting back immediately on this one.

OK, answers first:

> Reading "until this is either resolved or until I'm being ejected from the community in an obvious display of injustice", we're wondering what would you expect us to do to consider this matter as "resolved"?

Excellent question, thank you! For the purposes of this mine escalation, I'd be satisfied with clarity on the following point:

Is there any possible redemption arc for me at all? Or should I expect this blemish on my record to follow me around for the rest of my life with NixOS, i.e. could it forever after now be immediate "second warning" if and when somebody perceives a pattern of me crossing over from assertive to adversarial?

Or in other words: Imagine me being hard of learning for a second, and that the mod team's point of warning, last september, had already been after "last warning". And so imagine that I had actually gotten myself banned on that occasion. Now imagine I had come back now, and wanted to make credible that it was safe for you to probationally lift the ban. What steps would you have me do? What criteria would you communicate for me to observe?

Besides that clarity: It would be nice-to-have, if me and the NixOS moderation team could **agree to stay in touch**, until such time as - you are satisfied that you won't have to call out "adverserial behavior" on me - and I am satisfied that I won't have to call out "incompetent handling" on you or anyone in the community. I hope you recognize, that I've been trying hard to not filibuster your resources, so maybe you can grant me that level of trust?

> So, now comes our question: what should we do next?

Another excellent question! I do like the question game! Especially, when played cooperatively. Maybe we can keep playing that for a while?

I do have an idea for a choice of four possible next steps, but before I posit that, I'm afraid I'd like clarity on another slightly uncomfy question:

Will the NixOS moderation team allow for the record, that - formally - the previous message was the **first** instance of me being asked about or even presented with a cohesive set of examples for the alleged "pattern of adversarial behavior" **as part of the mediation process** or even **by a moderation team member** at all?

> ask us either to retract the formal warning or ban you

I feel that this framing grossly mischaracterizes my (publicly as well as privately) stated asks. Would you like me to quote from my (as yet unanswered) emails, sent to the NixOS moderation team appeals email address?

---

Thanks for bearing with me so far. Now, instead of waxing on about my defensibilia (got plenty. wanna read?), let me present the philosophical angle, that I'm trying to approach this from:

================================================================

There are plenty of people with even worse social skills than mine but better intentions yet, in the wider community. I'm making an example of myself, such that I might illuminate the new ways on all of our behalf.

I want to learn and document, whatever would have helped me avoid the trap of becoming adversarial, even while speaking on contentious topics.

Pedagocially speaking, being threatened with excommunication for transgression is not enough.

I also need an achievable goal of regaining lost communion. (see rehabilitation, prison reform movements)

I also need an achievable goal of dissenting while maintaining communion. (see freeze dem of peach)

**Comment by emilazy** [comment]
> I don't know what I'm supposed to learn from being slammed for self-merging a trivial fix to a package where I've been creator and sole maintainer for years, in a PR that was **already approved by another member**, while the person who has called for my head most vocally seems to be able to [use](https://github.com/NixOS/nixpkgs/pull/370612) [`master`](https://github.com/NixOS/nixpkgs/pull/371281) [as](https://github.com/NixOS/nixpkgs/pull/371539) [their](https://github.com/NixOS/nixpkgs/pull/371545) [personal](https://github.com/NixOS/nixpkgs/pull/350292) [scratch](https://github.com/NixOS/nixpkgs/pull/368623) [pad](https://github.com/NixOS/nixpkgs/pull/348024) with impunity.

Hi, since you’re continuing to attack me I thought I should address this:

* https://github.com/NixOS/nixpkgs/pull/370612 was reviewed by two people and approved by a committer. I also checked it with trofi before posting it.

* https://github.com/NixOS/nixpkgs/pull/371281 was merged to `staging`, not `master`, and was split out of https://github.com/NixOS/nixpkgs/pull/370995 where it had already been looked at by multiple people and the build verified as part of coordinated macOS < 11 clean‐up. Given how `staging` works, there was no risk of a regression hitting `master` without being built on `staging-next` first.

* https://github.com/NixOS/nixpkgs/pull/371539 and https://github.com/NixOS/nixpkgs/pull/371545 were merged into `staging-next`, not `master`. They fixed an urgent issue that prevented the Darwin `stdenv` being built at the start of the current `staging-next` cycle, as [reported by vcunat](https://github.com/NixOS/nixpkgs/pull/371501#issuecomment-2573780462). As with much activity in the `staging` cycle, the review and testing were coordinated [on Matrix](https://matrix.to/#/!UNVBThoJtlIiVwiDjU:nixos.org/$o8QMqMRawgmOyy0HxLzglPrWdjQjNisXnuLDGzEB97I?via=nixos.org&via=matrix.org&via=tchncs.de), not on GitHub.

* https://github.com/NixOS/nixpkgs/pull/350292 reverted a PR (by someone else) that I merged, to fix an eval issue. The problem and the revert were discussed on Matrix at the time. Taking responsibility for a PR you chose to merge and reverting immediately when it becomes clear it caused regressions is the responsible thing to do; to immediately revert a PR you merged does not require review since the state before the PR to be merged was already reviewed by definition, and it prevented CI from failing on unrelated PRs, a problem that delaying would have made worse. Yes, my original merge was premature given that regression, and I regret it and apologized at the time; nobody’s perfect, but I do try to learn from my mistakes. In my partial defence, this was back when ofborg eval was exceedingly slow to complete.

* https://github.com/NixOS/nixpkgs/pull/368623 was merged into `staging` as a revert of my ow nPR https://github.com/NixOS/nixpkgs/pull/368576, which was required to fix https://github.com/NixOS/nixpkgs/issues/368501 on `master`. The PR to `master` was reviewed and confirmed to fix the issue, and explicitly included a comment that it was a temporary fix to be reverted for the next `staging` cycle (as the proper fix for the LLVM 19 issue was already in `staging`), which I then did immediately so as to not forget it. This is standard procedure.

* https://github.com/NixOS/nixpkgs/pull/348024 was a follow‐up to https://github.com/NixOS/nixpkgs/pull/346043 to re‐enable a previously‐broken test that it fixed. I checked with mweinelt, the person who originally disabled it, on Matrix, and was told that a revert was fine if the test passes now, which it does. (Since it’s only a `passthru` test, it also caused no rebuilds and there is no way it could have broken the package – but I still checked before reverting.)

In summary, only two of the seven PRs you linked were merged into `master`, and not a single one of the non‐self‐reverts were merged without getting review. I appreciate that you may not understand the processes involved in the `staging` cycle – many don’t – but that’s no excuse for this attack. I would like you to retract your inaccurate claims and apologize for this and for when you responded to me with [“you know what I want to tell you to do with that statement, don't you?”](https://github.com/NixOS/nixpkgs/pull/342549#issuecomment-2359369663) right after being warned about your behaviour by the moderation team. (To be honest, I’m a little surprised that didn’t lead to any action from them at the time.)

I assume you have developed this fixation on me because I spoke out against your problematic behaviour on a couple of occasions. (I also spoke out at the same times about the problematic behaviour of other participants in those exchanges, like dotlambda and AndersonTorres.) But your focus on me is misplaced; I have heard from multiple others who have found your behaviour highly objectionable but didn’t feel like getting into a fight with you. I can’t really blame them given the ongoing reaction it has provoked. After your posts here and elsewhere I have to wonder what your intent in requesting my review on https://github.com/NixOS/nixpkgs/pull/367275 was.

Unfortunately I do not get the impression you are going to be able to participate in Nixpkgs without attacking people like this, so I feel my previous attempts at mediation have been somewhat of a waste and I won’t attempt to do so further. I do, however, think I am owed several apologies.

**Comment by bendlas** [comment]
> I appreciate that you may not understand ... I would like you to retract your inaccurate claims and apologize ... you have developed this fixation on me ... 

Gee whiz, hello as well, and thank you for talking **to** me, instead of **about** me, for once.

Unfortunately, it's too late for that. At this point in time, I'm not interested in (and honestly, afraid of) engaging with you directly.

I'll ask you to direct anything that you'd like to tell me or ask of me **about this matter** through mediation. And since we're at it, I'd appreciate if you could direct "multiple others" as well, to run their grievances through established, responsible structures, instead of you personally.

I trust that outside of this matter, we'll continue to be able to collaborate productively. Thanks!

**Comment by emilazy** [comment]
Okay, I’ll leave this for the moderation team to handle, then. Please stop requesting my review on PRs and posting unsubstantiated attacks about me.

**Comment by bendlas** [comment]
Hi Lassulus,

first, thanks for your answer! I feel you have gotten closest so far in dealing with my actual points of contention. However.

> The thing you’re asking for is impossible. We do not have a formal strike system, nor do we plan on implementing one.

With respect, that's not "impossible", that's either "we don't think it's a good idea" or "we don't want to do the work".

> We also can’t forget, or make other community members forget, your previous behavior, such that it doesn’t affect their interactions with you going forward.

That's not what I've been asking for, nor is it what I'm seeking. To the contrary: The risks I've been taking would have been pretty pointless if nobody remembered. And the reason I'm still harping on this, is exactly that I want us to remember and learn a thing or two.

> The way to move forward is not getting your warning formally expunged

See, I'm really trying to give the community a chance to strengthen the moderation team's agency here. And I'm telling you: If there is no possible recourse or even just revaluation at all - even in cases where the bag has been so grossly fumbled as here - then calling the warning **"formal"** is pretty well worthless.
 
> it’s rebuilding the trust we and other community members have in you, by listening to feedback and acting on it instead of trying to shift the blame to others. That’s something you’ll have to do yourself - we don’t have the ability to hold any individual person’s hand through any individual interaction even if we wanted to.

I'll not take offense to these statements, since they are based on many false premises of my intentions.

I **will point out** that abusing a community member (me) like this, and then asking them to just "learn from it" and "rebuild trust (a.k.a renew their investment)" is **parasitic** behavior and I will not stand for the community turning that way!

> We already gave you a list of things we see as overstepping the rules we have.

As of 2025-01-11, you have, yes. The list seems to have been carelessly copied from emilazy's attack post against me.

Are you saying that not bringing the list up during mediation was an oversight, but the formal warning would have still stood, even if I had had a chance to offer insight and ask forgiveness during mediation?

> Now it would be your responsibility to learn from those.

I hope that you're recognizing that I am in fact stepping up to that responsibility!

Is there any specific lesson that you would like me to direct my learning ability to?

Also recognize that I've been trying hard to not play the "show me the rules" or the "show me what I've done" or even the "but other people" game.  [1] [2]

> We hope that answers your question and what is the way forward.

Well, you did answer some questions. If I'm understanding your answers correctly though, then the implications for the way forward are unfortunate, though:

It is my belief that **any** reasonable system of guidance must either be precise or forgiving. Usually in the real world, it has to be both. The moderation team seems to want to execute its powers based on a system that is neither.

Two logical outcomes are that either 1) moderation enables many kinds of hidden methods of abuse or 2) moderation itself becomes a joke. Again, usually both, unfortunately.

I remain willing to talk, but until you open up for input (or at least revaluation and further mediation), my verdict stands.

Remember: I'm not arguing for my own sake (but for a just process for everybody). I'm not coming empty handed (offering improvement ideas and documentation work).

until then

---

P.S. OK, again, really trying hard to respect your reading time, but two slightly rantey footnotes taken out from above, because these two personal points will have to come out sooner or later, in order for everything to make sense.

[1] I will finally say to the point of my learning responsibility - even without being asked - that no: I'm not finding anything indefensible in anything I've posted. And for the one instance where I got too close for my comfort, I had already apologized to the people that I unilaterally (read, not emilazy wanting an apology from me about telling her to "reflect it" after calling me "unable or unwilling" [though you can offer her my apologies for that, by way of mediation]) directed my speech to, **long** before it got dug up and used as justification to call for my expulsion. Has the mod team been aware of that earlier apology? I can tell you that it wasn't brought up in mediation, since the corresponding point wasn't brought up during mediation at all!

[2] If what I'm supposed to learn is "don't be obnoxious", then has the moderation team even noticed so far, that in **every single** alleged point, I had been defending against severely obnoxious community standard transgressions? And each time successfully so, no less. Say what you will about my methods, but I haven't noticed a single careless or gratuitous module breakage in the 24.11 cycle, in stark contrast to the worsening tendency over the past couple years.
