### ISSUE TITLE
networking.interfaces.<name?>.virtualType: Documentation does not match implementation 

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#34258]
## Issue description

Documentation states that it accept null, but while it accepts null, it doesn't work. 
```
networking.interfaces.<name?>.virtualType
         The explicit type of interface to create. Accepts tun or
         tap strings. Also accepts null to implicitly detect the
         type of device.

         Type: null or one of "tun", "tap"

         Default: null
```
Output: 
```
myvirtual-netdev-start[1234]: You failed to specify a tunnel mode
```

### Steps to reproduce
Specify virtualType to be `null` in a virtual by not specifying it:

```
        networking.interfaces.myvirtual = {
         ip4 = [{address = "10.0.0.1"; prefixLength = 24;}];
         virtual = true;
         };
````

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by rnhmjoj** [comment]
I did a bit of research: the code (added in 59f512ef7d21) is as old as the module itself and seems to be broken since [2015](https://botbot.me/freenode/nixos/2015-11-09/?msg=53724066&page=1) at least. I think this never worked as the check is present since [2009](https://github.com/shemminger/iproute2/commit/580fbd88f75cc9eea0d28a48c025b090eb9419a7), but I may be wrong.

Anyway I don't know what should be picked as default and based on what. What do you expect it to do?
Otherwise I would just remove the `null` option and make it mandatory.

cc @wkennington @davidak @fpletz

**Comment by rnhmjoj** [comment]
Ok, in the networkd variant it's working, i will correct interfaces-scripted to do the same.

**Comment by rnhmjoj** [comment]
Close?

**Comment by coretemp** [comment]
I haven't tested it, but if you say it works, I will close it.

**Comment by rnhmjoj** [comment]
It does, but If you are on the stable channel you will have to wait for the 18.03 release or switch to unstable.
