### ISSUE TITLE
home-assistant: ModuleNotFoundError: No module named 'gtts'

### ISSUE THREAD

**Issue by luochen1990** [NixOS/nixpkgs#342698]
### Describe the bug

```
hass[1559]:   File "/nix/store/xhyzp75p6szxhqxscqbdjphlkwyv3biy-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/components/google_translate/tts.py", line 9,in <module>
hass[1559]:     from gtts import gTTS, gTTSError
hass[1559]: ModuleNotFoundError: No module named 'gtts'
```

### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Princemachiavelli** [comment]
While just adding the `gtts` python package is sufficient```nix
services.home-assistant = {
  extraPackages = python3Packages: with python3Packages; [ gtts ];
};
```
The hass module already maps the `google_translate` integration as requiring the `gtts` package, the issue is that the `google_translate` integration is not one of the default integration yet a fresh install of home-assistant has the `google_translate` present anway.

I guess we should either just add `google_translate` to the `defaultIntegrations` list or figure out why it's included in the base install and remove it (unless manually added).

**Comment by sweenu** [comment]
This was closed, but it seems like it was never actually fixed, right? I'm having the issue right now on a fresh home-assistant deployment.
