### ISSUE TITLE
Revert #16903 zfs: Force sync on shutdown

### ISSUE THREAD

**Issue by matdibu** [NixOS/nixpkgs#343014]
## Issue description

Half of my `zpool history` is the `zfs set nixos:shutdown-time=...` message set in #16903 by @Baughn 

And that PR explicitly modifies the behaviour of ZFS' `sync=disabled`; I don't think we should go against the users that decide to use that feature.

And for the large majority who left sync enabled, it's not doing much aside from setting a timestamp

Overall, I suggest removing this overriding behaviour.

### Steps to reproduce

1. use ZFS on NixOS
2. reboot
3. check the output of `zpool history`

**Comment by Baughn** [comment]
That would be a data-loss regression for anyone relying on the current behaviour, so I'm heavily against that. The idea is to allow performance improvements at the cost of time reversal if the system crashes; not to allow it at the cost of data loss on every single reboot.

I'm not sure if `zpool sync` will do the job, but that's testable. If it does not, how about making the forced sync only happen if sync happens to be disabled on some filesystem?

**Comment by matdibu** [comment]
I understand the risks, but so should anyone who goes out of their way to set `sync=disabled`, it's not a default setting and it comes with its own documented caveats.

**Comment by Peter-Flynn** [comment]
@matdibu You're misunderstanding the point of `sync = disabled`. It prevents explicit requests for synchronous transactions, and makes everything asynchronous. The average person disabling `sync` is absolutely not okay with avoidable data loss upon shutdown.

**Comment by matdibu** [comment]
@Peter-Flynn I realize now that I had originally misunderstood the effect of Baughn's change

I'll close this issue

But now I'm curious: how do other Linux or BSD distributions handle this?

**Comment by Baughn** [comment]
@matdibu  They don’t. Most distributions have data loss on shutdown in this configuration, but it’s less noticeable, since they reuse the same filename for system updates instead of getting a new hash. NixOS instead fails to boot.

**Comment by matdibu** [comment]
> @matdibu They don’t. Most distributions have data loss on shutdown in this configuration, but it’s less noticeable, since they reuse the same filename for system updates instead of getting a new hash. NixOS instead fails to boot.

haha, that's crazy

thank you for your fix, and apologies for misunderstanding things in the first place

**Comment by Petrusion** [comment]
@matdibu @Baughn I think this issue should be re-opened because https://github.com/NixOS/nixpkgs/pull/16903 is not needed anymore. Years after https://github.com/NixOS/nixpkgs/pull/16903, https://github.com/NixOS/nixpkgs/pull/170123 was merged which added `zpool sync` to the shutdown process.

Calling `zpool sync` during shutdown eliminates the need for https://github.com/NixOS/nixpkgs/pull/16903.

Here is how I tested that `zpool sync` works on datasets with `sync=disabled`:

1. Increased `zfs_txg_timeout` to `180` by setting `boot.extraModprobeConfig = "options zfs zfs_txg_timeout=180";` (so that a transaction group timeout wouldn't interfere with the test)
2. Created a dataset with `sync=disabled` on a USB hard drive (let's call it `usbhdd/test`)
3. Rebooted and made sure `cat /sys/module/zfs/parameters/zfs_txg_timeout` prints `180`
4. Mounted `usbhdd/test`
5. Copied some random file from my downloads folder, few kB in size, onto it
6. A few seconds after the copy was done, yanked the USB cable out of the computer
7. Rebooted, reconnected the USB drive, and mounted `usbhdd/test` again, the file was missing
8. Repeated step 5, called `zpool sync` (the hard drive started audibly working at this time)
9. As soon as `zpool sync` returned, yanked the USB cable out of the computer
10. Rebooted, reconnected the USB drive, and mounted `usbhdd/test` again, the file was there (with undamaged content)
