### ISSUE TITLE
Vim-plugins: vim-ensime python dependencies not available

### ISSUE THREAD

**Issue by dispanser** [NixOS/nixpkgs#34340]
## Issue description

Trying to customize vim using the following snippet in user config (minimal config):

```nix
{
  packageOverrides = pkgs_: with pkgs_;  {

    test-ensime = vim_configurable.customize {
		vimrcConfig.packages.myVimPackage = with pkgs.vimPlugins; {
			start = [ ensime-vim ];
		};
		name = "test-ensime";
	};
  };
}
```
when starting the editor (`vim-ensime`):

```
[ensime] A dependency is missing, please `pip2 install sexpdata websocket-client` and restart 
```

My local nixkgs checkout contains the following in `pkgs/misc/vim-plugins/default.nix`:
```
  ensime-vim = buildVimPluginFrom2Nix { # created by nix#NixDerivation
    name = "ensime-vim-2017-08-27";
    src = fetchgit {
      url = "https://github.com/ensime/ensime-vim";
      rev = "d992b971a84afdfb2d99896d8aed537030e09a80";
      sha256 = "1rhrq3zplvpyli1ymqjmhq91p61ixpjz1v5xf68nvq4ax50nl45z";
    };
    dependencies = ["vimproc" "vimshell" "self" "forms"];
    pythonDependencies = with pythonPackages; [ sexpdata websocket_client ];
  };
```
It seems the python dependencies are not picked up, or I've misunderstood the
configuration process (I've been following https://nixos.wiki/wiki/Vim_plugins)			   

### Steps to reproduce

install vim-ensime using the nix expression above.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.14, NixOS, 17.09.2853.b222a0713f4 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-17.09.2853.b222a0713f4"`
 - channels(pi): `"nixos-18.03pre125026.f607771d0f5"`

**Comment by timokau** [comment]
This is handled for [neovim](https://github.com/NixOS/nixpkgs/blob/42575040fc64c1f5560c1cd1d1fdf0fd5e5d4b49/pkgs/applications/editors/neovim/wrapper.nix#L43). In contrast vim [just uses a bare python without plugins](https://github.com/NixOS/nixpkgs/blob/42575040fc64c1f5560c1cd1d1fdf0fd5e5d4b49/pkgs/applications/editors/vim/configurable.nix#L155).

It should be relatively easy to port the code from neovim to vim. However I'm a bit confused why the vim derivation only has python2 *or* python3 support while neovim can support both. I'm not sure if there is some fundamental limitation or it was just done that way because it was easier at the time.

**Comment by teto** [comment]
python configuration s done at buildtime for vim and at runtime for neovim. Feel free to reopen if you have an issue but it looks out of date.
