### ISSUE TITLE
Gamemode scripts are not merged

### ISSUE THREAD

**Issue by MithicSpirit** [NixOS/nixpkgs#343575]
### Describe the bug
The custom start and end scripts for Gamemode are not merged.

### Steps To Reproduce
1. Set `programs.gamemode.settings.custom.start` (or `.end`) multiple times (in different files).

### Expected behavior
They should be merged with newlines.

### Notify maintainers
@kira-bruneau 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.10-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20240919.c04d565`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.6`
 - nixpkgs: `/nix/store/hiasfhl8f5yy88hcfbr3s8s4bm63wsjw-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Atemu** [comment]
Huh, this is an interesting case because the module uses an RFC42 `settings` option with `inherit (pkgs.formats.ini { }) type`.

It'd then be the responsibility of the format to specify how attributes should be merged but it doesn't which makes sense as there isn't a generic defined way to merge any conflicting string values in the INI format.

RFC42 doesn't cover this case AFAICT. Perhaps @infinisil could weigh in on this.

I guess the correct course of action would be to explicitly define options for these settings with types that do merging?  
Or perhaps you could do something with `listToValue` here; making it so that a list of lines would be concatenated into a script running each in order?  

@MithicSpirit how would upstream expect you to declare running multiple commands here?

**Comment by MithicSpirit** [comment]
> how would upstream expect you to declare running multiple commands in their INI file?

Gamemode uses [inih](https://github.com/benhoyt/inih) for parsing the config files, which supports multiline strings similarly to python's [configparser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure). Basically, lines after the first should be indented. I believe this could be done in Nix by using `concatStringsSep "\n  "`.

**Comment by Atemu** [comment]
> Maybe support for this could be added directly to `pkgs.formats.ini` (as an option)?

If this is indeed a custom format, this would seem like the right thing to do to me.

We already have an option to represent lists as duplicate keys, so an option like it could absolutely be a thing. Looking into the code, you'd have to touch a bunch of the core generator functions to do this but it should be doable.

**Comment by MithicSpirit** [comment]
Spelunking through more of the source code, it looks like gamemode just appends each script to a list ([here](https://github.com/FeralInteractive/gamemode/blob/c54d6d4243b0dd0afcb49f2c9836d432da171a2b/daemon/gamemode-config.c#L325)), so using `listsAsDuplicateKeys` works. Trying this on my local config seems to confirm that hypothesis, so I'll make a PR for this.
