### ISSUE TITLE
RFC: "Official" Compilers Team

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#344078]
Recently brought this up on the compilers team Matrix chat:

> Thoughts on having a GitHub team of code owners to own `pkgs/development/compilers`? It might be a good idea so that all of the compiler ecosystem in nixpkgs is kinda on the same page.

The idea is to have a team own the compilers side of Nixpkgs entirely. These individuals will have commit access and are familiar with how the compilers ecosystem is in Nixpkgs. Some of these compilers involved are: Flutter, Zig, LLVM, Go, & GCC.

CC (existing code owners for compilers): @Mic92 @zowoq @winterqt @figsoda @alyssais @raitobezarius @sternenseemann @maralorn @mattpolzin @kalbasit @katexochen @corngood

React with 👍 to agree or reply with a comment for any objections.

**Comment by mattpolzin** [comment]
The Idris2 compiler which I maintain may make me a weak applicant for the broader compiler ecosystem, but I don't object and I am sure I will learn a lot if I become more familiar with the other compilers in nixpkgs ❤️

**Comment by 7c6f434c** [comment]
1. Given that some of the things slowly move to `pkgs/by-name`, maybe defining in terms of `pkgs/development/compilers` will not stand the test of time.

2. Uniformising between any two of SBCL, Julia, FPC, OCaml, FASM, TypeScript (these are all currently in the compilers directory) with their very different considerations and contexts looks to me like way more trouble than it is worth.

**Comment by RossComputerGuy** [comment]
> 1. Given that some of the things slowly move to `pkgs/by-name`, maybe defining in terms of `pkgs/development/compilers` will not stand the test of time.

I doubt we'll move every compiler or package to `pkgs/by-name`. Is there plans to make that support multi-versioned multi-packaged packages? LLVM for one is packaged per version per subproject so a one size fits all solution doesn't inherently work. We package multiple versions of things like LLVM, GCC, Zig, Flutter, etc.

> 2\. Uniformising between any two of SBCL, Julia, FPC, OCaml, FASM, TypeScript (these are all currently in the compilers directory) with their very different considerations and contexts looks to me like way more trouble than it is worth.

I'm not sure what you mean with uniformising those compilers.

**Comment by 7c6f434c** [comment]
1. Not every compiler is multi-versioned, some are good enough at backward compatibility and have few enough fragile packages that we end up with a single versions.

2. What does it mean «on the same page»?

**Comment by RossComputerGuy** [comment]
> 1. Not every compiler is multi-versioned, some are good enough at backward compatibility and have few enough fragile packages that we end up with a single versions.

Yeah so it's expected we'd keep the multi versioned ones in place.

> 2\. What does it mean «on the same page»?

Like everyone is in touch.

**Comment by 7c6f434c** [comment]
«Everyone is in touch» for a large set of people doing quite different work is a lot of communication cost. Towards what end?

**Comment by Mic92** [comment]
I also think the scope of a compiler team is set a bit too broad. I would say an stdenv team is better (gcc, clang, binutils, cc-wrapper).

**Comment by corngood** [comment]
I'm in here because of `compilers/dotnet`.  Which is not really a compiler.  It's a runtime, an sdk (which includes a few compilers), and some build-support stuff that should arguably be somewhere else (`pkgs/build-support/dotnet`?).

The compilers themselves are pretty self contained, so I don't usually have to do any work on them.  Most of the work is in build-support stuff.  For that, I quite often find myself referring to stdenv, and build-support for other languages/runtimes.  I think that's where I see the biggest opportunity for collaboration.

Some specific examples of things I probably should discuss with build-support maintainers:

- In dotnet, we have this `fetch-deps` thing, which fetches dependency hashes in an online environment.  This is mostly automatic, but I packaged something recently that also had npm dependencies, and needed to also run `prefetch-npm-deps`.  I glued it all together in the updateScript, but it got me thinking of ways to better declare and compose these sort of dependencies.

- In dotnet we have `buildDotnetModule`, which is the high-level way of building a derviation for a dotnet sdk project.  It's a wrapper around `stdenvNoCC`.  I've been trying to break this down into more easily composed pieces (hooks, etc), so that it's more practical to build dotnet stuff in a `stdenv.mkDerivation`.  In nixpkgs there are a wide variety of approaches to this sort of thing.

I've never run either of these things by maintainers of build-support for other languages, but I probably would if knew of an appropriate forum.  Perhaps one already exists?

So I can't say there's no need for a compilers team.  I'm curious about what sort of things are discussed on the "compilers team Matrix chat", and how busy it is.  I would be interested in being more looped in on `stdenv` and `build-support` architecture, but maybe that's off-topic for this issue?

**Comment by RossComputerGuy** [comment]
> I would say an stdenv team is better (gcc, clang, binutils, cc-wrapper).

Hmm, makes sense.

> I'm curious about what sort of things are discussed on the "compilers team Matrix chat", and how busy it is. I would be interested in being more looped in on `stdenv` and `build-support` architecture, but maybe that's off-topic for this issue?

[Matrix invite](https://matrix.to/#/!kxOJEqURGkuOHTRRQB:matrix.org?via=matrix.org&via=tchncs.de&via=nixos.org), it's fairly active.

**Comment by corngood** [comment]
> [Matrix invite](https://matrix.to/#/!kxOJEqURGkuOHTRRQB:matrix.org?via=matrix.org&via=tchncs.de&via=nixos.org), it's fairly active.

Thanks!  At a glance that seems to be mostly discussion of llvm/gcc stuff?  I'm sure that's a subject that needs a forum, since nixpkgs abstracts the compiler in `stdenv`, and there are a lot of tricky details.

I think what @Mic92 suggested covers this pretty well:
> I also think the scope of a compiler team is set a bit too broad. I would say an stdenv team is better (gcc, clang, binutils, cc-wrapper).

So it would be specifically for stdenv+CC stuff. 

Maybe it would also be useful to have a forum/team for:

`stdenvNoCC` -> language-agnostic stdenv stuff, build-support, etc.

Assuming there isn't one already.

**Comment by Artturin** [comment]
@corngood There's a stdenv room too https://matrix.to/#/#stdenv:nixos.org

**Comment by sternenseemann** [comment]
I would also like to echo @7c6f434c's sentiment. The different language infrastructures (be it compiled or interpreted) each encode a lot of domain specific knowledge. So there is not really a shared mission or responsibility of all compiler maintainers in nixpkgs (just imagine if you got pinged via a theme on an issue regarding a compiler you are unfamiliar with). Any joint architectural changes can be deliberated via the RFC process. The disparity probably helps there so that an actual consensus needs to be established.

**Comment by RossComputerGuy** [comment]
So, we're in favor of closing this to open for core platforms/stdenv team(s) (eg. a stdenv team & a darwin core team)?
