### ISSUE TITLE
nixos/iso-image: can't nixos-rebuild switch. Failed to install bootloader

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#344535]
### Describe the bug

In the live CD environment, we include an `/etc/nixos/configuration.nix` file for convenience so you can edit it and `nixos-rebuild` to get some changes in the live environment (as long as they don't require a reboot). This works if you use `nixos-rebuild test`, but with `nixos-rebuild switch` you get `Failed to install bootloader` and the configuration doesn't take effect. This is a minor issue, because `nixos-rebuild test` does indeed still work. But `test` is knowledge that many brand new users won't have, so allowing `switch` to work (like I'm pretty sure it used to, though it's been years since I would have tested) would be very nice.

### Expected behavior
Edit `/etc/nixos/configuartion.nix` in the live CD environment, and `nixos-rebuild switch` should work.

**Comment by Atemu** [comment]
Perhaps `nixos-rebuild`'s the `boot` operation could be stubbed with a warning in ISO images and the like.

**Comment by kazikcz** [comment]
I've run into the same problem on Pinephone with nixos-mobile.

After digging a little bit it seems the new Rust version of switch-to-configuration (switch-to-configuration-ng, which replaced switch-to-configuration.pl in early September as far as I can tell from the git log) introduced some incompatibility.

What I found is the perl version used to system() the system.build.installBootLoader value. This value, by default, is a shell expression with echo + true. If I override the installBootLoader like so:
```
system.build.installBootLoader = "${pkgs.coreutils}/bin/true";
```
the problem ("Failed to install bootloader") goes away.

Looking at the rust implementation, it does _not_ do system(). Instead, it splits the installBootLoader into slices on whitespace, and exec() that (+ trailing "toplevel" argument). IOW it's not doing the same thing the perl script did.

I'm not sure if this was intentional and I don't fully get it why it would fail (tokenizing the default string as exec() manually works..), but it does seem it might've been a dead spot because documentation of installBootLoader (still) explicitly mentions  switch-to-configuration.pl.

The original switch-to-configuration.pl was supposedly passing an $out argument at the end of the shell expression, so "true" was supposed to (silently) be fed that argument.

It'd be best someone who's driving the rust implementation effort chimes in on this. @emilazy ?

**Comment by flacks** [comment]
@kazikcz's solution works for me on my pinephone as a short-term workaround, thank you!
