### ISSUE TITLE
Firefox doesn't see host pulseaudio, audio doesn't work

### ISSUE THREAD

**Issue by jad340** [NixOS/nixpkgs#34712]
## Issue description

When running Firefox 58.0.1 (`/nix/store/6sblfm52hkvzr2b4fp8y5bn8fvj2j6ag-firefox-58.0.1/bin/firefox`) on a non-nixos Linux system (Debian stretch in this case), audio doesn't work.  I can see the following messages on the console after running firefox and trying to play, for example, a youtube video:

```
[Child 14641, MediaPlayback #2] WARNING: 7fe5a381fd00 OpenCubeb() failed to init cubeb: file /build/firefox-58.0.1/dom/media/AudioStream.cpp, line 387
[Child 14641, MediaPlayback #2] WARNING: Decoder=7fe5aa798c00 [OnMediaSinkAudioError]: file /build/firefox-58.0.1/dom/media/MediaDecoderStateMachine.cpp, line 3642
```
Doing some searching, it appears that this error appears for people who aren't running pulseaudio, but I am running pulse via `start-pulseaudio-x11` in my `~/.xinitrc` (this is Debian's pulseaudio, version `10.0`).

### Steps to reproduce

1. Start non-nix-installed pulseaudio via `start-pulseaudio-x11`
2. Install firefox via `nix-env -i firefox` and run it
3. Try to play audio in firefox

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-5-amd64, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(jad): `"nixpkgs-18.03pre127228.91eb41b1383"`
 - nixpkgs: `/home/jad/.nix-defexpr/channels/nixpkgs`
```

**Comment by dtzWill** [comment]
Did this previously work for you?

I ask because some googling of my own turns up results like:
* https://www.reddit.com/r/archlinux/comments/7tdtis/firefox_flash_no_audio/
* https://bbs.archlinux.org/viewtopic.php?id=233904
and particularly:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1430274
which suggests this is a recent bug in that alsa no longer works.

(I know it's about pulseaudio but if the fallback stopped working perhaps that's related)
---------
Anyway looking at the store path you posted (YAY nix!), it looks like the LD_LIBRARY_PATH set there (it's a wrapper script) does not contain libpulseaudio, suggesting the wrapper wasn't generated with pulseaudio support.

(which apparently is controlled by `config.pulseaudio`:)
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/firefox/wrapper.nix#L74

So perhaps this problem can be reduced to "how do I set config options on non-NixOS?".
If so, the answer somewhat depends on how you're doing things but probably setting "pulseaudio = true;" in your `~/.config/nixpkgs/config.nix` would do the trick.  If you don't have this file already, try something like:

```
$ mkdir -p ~/.config/nixpkgs
$ echo "{ pulseaudio = true; }" > ~/.config/nixpkgs/config.nix
```

and see if that fixes things (after re-installing/updating firefox)?

**Comment by jad340** [comment]
Adding `{ pulseaudio = true; }` to `~/.config/nixpkgs/config.nix` worked!  Thank you!
