### ISSUE TITLE
Can't use Signal-Desktop because it's outdated. 

### ISSUE THREAD

**Issue by maikelthedev** [NixOS/nixpkgs#347465]
### Describe the bug
You guys are using 7.26 of Signal when the latest release is 7.27 because of this, you can't, as a user link your phone. It says you're not using the latest and only gives you the option to download signal or quit the app (on Nixos). 

### Steps To Reproduce
1. Open the app
2. Try to link phone. 
3. Get told you can't use it without updating. 

### Expected behavior
Be able to use the latest 7.27 Signal-Desktop so I can actually use it.  

### Screenshots

![image](https://github.com/user-attachments/assets/23f11f61-d27a-4737-b980-55590857da29)

**Comment by nobodyinperson** [comment]
https://github.com/NixOS/nixpkgs/pull/347058

**Comment by maikelthedev** [comment]
After doing a

```bash
  sudo nix-channel --update
  sudo nixos-rebuild switch --upgrade
```

I still don't seem to have the latest Signal. Has this been fixed at all? Am i missing something?

**Comment by maikelthedev** [comment]
I'm so confused

![image](https://github.com/user-attachments/assets/e0717a2c-9293-4614-9958-c325323b4f5e)

**Comment by maikelthedev** [comment]
Nevermind, I'm an idiot

![image](https://github.com/user-attachments/assets/81bf1706-5705-4b23-ba67-ab8e6c7a673b)

**Comment by nobodyinperson** [comment]
> Am i missing something?

Yes you are 🙂

This is the nixpkgs repository, the collection of packages for the nix package manager and NixOS. The way it works is that people make [PRs](https://github.com/NixOS/nixpkgs/pulls) to add updates to existing packages or add new packages.

People may open issues (like this one) to point out that certain things need to be done. In this case, [a PR to update Signal Desktop](https://github.com/NixOS/nixpkgs/pull/347467) is already opened **but still needs to be merged**. This issue is thus not needed, as the work to fix it has already been done. (As you can see there are thousands of issues and PRs open, and it is important to remove "noise" to keep an overview.)

**BUT**: Even if it gets merged, it'll be in nixpkgs **master** - so not even in the `unstable` branch, let alone one of the releases such as `24.05`. That'll take some time in addition.

I suggest you read about to apply `overrideAttrs` to manually update the Signal Desktop version in your `configuration.nix` or you learn how to import [that PR to update Signal Desktop](https://github.com/NixOS/nixpkgs/pull/347467) to use its Signal Desktop version.
