### ISSUE TITLE
Build failure: ida-free: https://web.archive.org/ is unreachable

### ISSUE THREAD

**Issue by BlaiZephyr** [NixOS/nixpkgs#347919]
### Steps To Reproduce
try installing ida-free  will fail because the source url is unreachable.

`nix-shell -p ida-free`

there will be a hash mismatch, fixing it will show that the site is unreachable, also doublechecked with ping:

```
❯ ping web.archive.org
PING web.archive.org (207.241.237.3) 56(84) Bytes an Daten.
^C
--- web.archive.org ping-Statistik ---
46 Pakete übertragen, 0 empfangen, 100% packet loss, time 46094ms
```

### Build log
```
trying https://web.archive.org/web/20240330140328/https://out7.hex-rays.com/files/idafree84_linux.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:13 --:--:--     0
curl: (28) Failed to connect to web.archive.org port 443 after 133979 ms: Could not connect to server
```

### Additional context
this would be easily fixable but i can't find any resource without registering myself on the website. so i hope msanft can figure this one out :)
### Notify maintainers
@msanft 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.54, NixOS, 24.11 (Vicuna), 24.11.20241009.5633bcf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by msanft** [comment]
See https://www.theverge.com/2024/10/9/24266419/internet-archive-ddos-attack-pop-up-message

I think this should be resolved soon without any changes. If you want to work around it now, just remove the archive mirror so that it's downloaded only from the Hex-Rays website. What other fix did you have in mind when you say "this would be easily fixable but i can't find any resource without registering myself on the website"?

**Comment by BlaiZephyr** [comment]
Ida-free beeing downloaded straight from their URL, not using web.archive for it, so basically what you mentioned by using hex-rays, website. But I didn't find a mention of ida-free, only their pro variant.

TiL they're experiencing these ddos attacks, sorry I missed that.

What was the reason to use the web archive as a mirror btw ?

**Comment by msanft** [comment]
> What was the reason to use the web archive as a mirror btw ?

It's a precautionary measure so that if Hex-Rays decides to remove the download, the package is still buildable.

You can download the file via `https://out7.hex-rays.com/files/idafree84_linux.run`. Just replace the URL in the `package.nix` with that and it should build again. But I don't think this is something we want upstreamed now, since the web archive should (hopefully) be back up soon.

**Comment by BlaiZephyr** [comment]
alright, thanks for your quick answer! i will close this with that information and reopen if needed!
