### ISSUE TITLE
Update request: osu-lazer/osu-lazer-bin 2024.906.2 → 2024.1009.1

### ISSUE THREAD

**Issue by suryavemuri30** [NixOS/nixpkgs#348037]
- Package name: osu-lazer/osu-lazer-bin
- Latest released version: 2024.1009.1

- Current version on the unstable channel: 2024.906.2
- Current version on the stable/release channel: 2024.521.2

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@gepbird 
@thiagokokada 

NOTE: This is the first time I am submitting an update request, I think I've checked everything properly, but my sincerest apologies if I do miss something.

![image](https://github.com/user-attachments/assets/2671dc26-40d5-4560-abcd-6e7d0675bfe3)
an image of the notification I get on opening osu-lazer-bin.

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by gepbird** [comment]
The update was done in https://github.com/NixOS/nixpkgs/pull/347450, but then they changed the AppImage files multiple times for the existing release (rather than making a new release), so we also need to wait for these PR: https://github.com/NixOS/nixpkgs/pull/347689, https://github.com/NixOS/nixpkgs/pull/347784.

The 2024.1009.1 update should land in unstable in about a week, until then you can launch it with `NIXPKGS_ALLOW_UNFREE=1 nix run github:gepbird/nixpkgs/osu-lazer-bin-fix-hash-again#osu-lazer-bin --impure`

**Comment by suryavemuri30** [comment]
This makes sense, thank you so much! I'll close this issue now then, thank you again for the quick reply.
