### ISSUE TITLE
Package request: python35Packages.i3ipc

### ISSUE THREAD

**Issue by Cypher1** [NixOS/nixpkgs#34828]
## Issue description

i3ipc python package exists in pypy but not in nixpackages.
It would be great if we could use it.

Link for reference: https://pypi.python.org/pypi/i3ipc

### Steps to reproduce
```
    nix-shell -p python35.i3ipc --run "python3 -c 'import i3ipc'"
```

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09.2955.76614894f34 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.16`
 - channels(cypher): `""`
 - channels(root): `"nixos-17.09.2955.76614894f34"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

Thanks.

I'm probably up for writing the nix package definition if someone can point me in the right direction,

**Comment by FRidh** [comment]
>   `nix-shell -p python35.i3ipc --run "python3 -c 'import i3ipc'"`

There are two mistakes in that line. But, your intention is clear ;)

**Comment by Cypher1** [comment]
@FRidh for future reference, what mistakes did I make? It's my first week of nix (and I'm loving it).

**Comment by FRidh** [comment]
> `nix-shell -p python35.i3ipc --run "python3 -c 'import i3ipc'"`

Python packages are part of the `pkgs` attribute of the interpreter, so `python35.pkgs.i3ipc` is the reference to the package. 

While it is now possible to use 
```
nix-shell -p python35.pkgs.i3ipc --run "python3 -c 'import i3ipc'"
```
the supported solution is
```
nix-shell -p 'python35.withPackages(ps: with ps; [ i3ipc ])' --run "python3 -c 'import i3ipc'"
```
The other one typically works, but not always because `python` is not always propagated and thus unavailable. Also, `withPackages` guarantees that you will have the Python that is "connected" to the package, and not accidentally the one that was in your `PATH`.

> It's my first week of nix (and I'm loving it).

Good to hear!

**Comment by Cypher1** [comment]
Thanks! Interesting to see the differences.

**Comment by Cypher1** [comment]
Just wanted to let you know that I finally got my i3 setup working near perfectly on nixos!

Loving it (Thank you all)
