### ISSUE TITLE
Build failure: gotosocial

### ISSUE THREAD

**Issue by surfaceflinger** [NixOS/nixpkgs#348366]
### Steps To Reproduce

1. build *gotosocial* with nixpkgs/master as of rn (https://github.com/NixOS/nixpkgs/commit/ae891b2c0934b8b0b75a31798b29001ad5af529d)

### Build log

```
gotosocial> Running phase: unpackPhase
gotosocial> unpacking source archive /nix/store/nz0h4xl085wjb0yb5ghc9bcx4j83h4dy-source
gotosocial> source root is source
gotosocial> Running phase: patchPhase
gotosocial> Running phase: updateAutotoolsGnuConfigScriptsPhase
gotosocial> Running phase: configurePhase
gotosocial> Running phase: buildPhase
gotosocial> Building subPackage ./cmd/gotosocial
gotosocial> # github.com/superseriousbusiness/gotosocial/cmd/gotosocial
gotosocial> link: codeberg.org/gruf/go-fastcopy: invalid reference to io.errInvalidWrite
```

### Notify maintainers

maintaner @blakesmith
recent changes by @asymmetric @jugendhacker

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2, NixOS, 24.11 (Vicuna), 24.11.20241009.65d98cb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.0
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux, x86_64-v4-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/nat/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/nat/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/nat/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/nat/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/cfl6rqw64ndbh2m0qapg410jf4xmycia-lix-2.91.0/share`
 - nixpkgs: `/nix/store/y4rmd9g036gmgz5xjiplw1zcbi16fqdr-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by blakesmith** [comment]
Thanks for the report @surfaceflinger. I'm able to reproduce. Hunting a little bit, I'm able to track down a related change in one of gotosocial's dependencies (go-fastcopy) to this commit: https://codeberg.org/gruf/go-fastcopy/commit/05491dc06f9527966e44eb2b9bb376031c4b24c9. The upstream dependency is referencing an `io` error value in the golang standard library here: https://github.com/golang/go/blob/b521ebb55a9b26c8824b219376c7f91f7cda6ec2/src/io/io.go#L32. 

Regardless, I am able to make the build work again by explicitly building `gotosocial` with golang 1.22. Will put up a PR here shortly. Perhaps some issue or bug was fixed in golang 1.23 that's affecting this dependency.

**Comment by asymmetric** [comment]
@blakesmith nice catch! [This change](https://go.dev/doc/go1.23#linker) in 1.23 is what's causing the build failure for that dependency.

**Comment by surfaceflinger** [comment]
I'll close this as the build failure is resolved now
