### ISSUE TITLE
ladybird: Browser doesn't work

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#350266]
### Describe the bug

When I try to load a webpage, it doesn't appear a webpage loading attempt is even made.

[ladybird.log](https://github.com/user-attachments/files/17463262/ladybird.log)

### Steps To Reproduce

1. `nix run nixpkgs#ladybird
2. Try to load any webpage (e.g. `https://example.com`)
3. It doesn't load

### Expected behavior

I expected to see https://example.com

### Screenshots

N.A.

### Additional context

N.A.

### Notify maintainers

@fgaz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ took 40s
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.3, NixOS, 24.11 (Vicuna), 24.11.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.8`
 - nixpkgs: `/nix/store/y5k9hx0ch578qsizi9p4d310f6b4vhfc-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fgaz** [comment]
Did you set [`programs.ladybird.enable`](https://search.nixos.org/options?show=programs.ladybird.enable&query=ladybird) to `true`?

**Comment by Pandapip1** [comment]
No. Is there a reason that ladybird needs a system configuration option? Couldn't the necessary fonts be included in the derivation?

**Comment by fgaz** [comment]
> No.

...can you try it? Does it fix the issue?

In general, if a package does not work on its own and there is an option with the same name, it's likely necessary and you should try enabling it.

> Is there a reason that ladybird needs a system configuration option?

Yes, it's because ladybird looks for fonts in standard locations under `$XDG_DATA_DIRS`, and by default NixOS does not put fonts under that location. `programs.ladybird.enable` is almost an alias for `fonts.fontDir.enable`:

https://github.com/NixOS/nixpkgs/blob/a9b86fc2290b69375c5542b622088eb6eca2a7c3/nixos/modules/programs/ladybird.nix#L12 

This will no longer be necessary if/when upstream switches to fontconfig (looks like they are [working on it](https://github.com/LadybirdBrowser/ladybird/pull/1736)).

> Couldn't the necessary fonts be included in the derivation?

No. The fonts you are going to install in your system are not known at package build time. However, we could include a fallback font. I'm reluctant to do that myself because ladybird is a fast-moving target and the package is already pretty complex, but I would probably accept a pr.

**Comment by Pandapip1** [comment]
I'm just going to assume that the option works. Any chance you can apply those patches before the next release?

**Comment by fgaz** [comment]
The upstream work on fontconfig is not complete yet. When/if they complete it I'll update the package, sure.
