### ISSUE TITLE
Stack on 17.09 #c882c4d fails on `stack new` complaining about AesonException

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#35260]
## Issue description

When using 17.09 https://github.com/NixOS/nixpkgs-channels/commit/c882c4dd55e36dda57532fb830fad0882c4d770b and running `stack new` inside a nix-shell, it reports:

```
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

When I made my nix-shell instead use the latest commit hash in nixpkgs-unstable https://github.com/NixOS/nixpkgs-channels/commit/8b1cf100cd8badad6e1b6d4650b904b88aa870db, it works without problems.

The main issue appears that `stack 1.5.1` simply has this error, and they recommend people to update their stack. Perhaps 17.09 should have its stack upgraded? https://github.com/fpco/stackage/issues/3132

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.11, Matrix Central, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(cmcdragonkai): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/nixpkgs`
```

**Comment by bjornfor** [comment]
(Funny, I hit this yesterday.) I worked around it by specifying --resolver=lts-9.14.

**Comment by rsoeldner** [comment]
@bjornfor this works for me.

Can we update stack for nixos - I'm a second day nixos user, if someone help me I try to do it :+1:

**Comment by bjornfor** [comment]
I think @peti is the right person to answer that.

**Comment by peti** [comment]
Updating `stack` is no trivial matter, unfortunately, because it has a rather large and complex dependency tree. There's a decent chance that we'd have to update other packages, too, to accommodate the new `stack` version. But then we run the risk of breaking other build that share the same dependencies but which cannot cope with the new versions. This gets messy quick.

I'll give it a shot and try whether an update is easy. If it's not, however, then I'd rather spend my time working on the `release-18.03` release which is going to come out in ~4 weeks anyway.

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/36204.
