### ISSUE TITLE
Build failure: jellyfin-ffmpeg

### ISSUE THREAD

**Issue by avanderbergh** [NixOS/nixpkgs#353600]
### Steps To Reproduce

1. build `jellyfin`

### Build log

```
error: builder for '/nix/store/n9vd6qaiyzkyc8jf09ikr07k3vm9wxs2-jellyfin-ffmpeg-7.0.2-5.drv' failed with exit code 2;
       last 25 log lines:
       > CC     libavcodec/libvpxenc.o
       > CC      libavcodec/libwebpenc.o
       > CC     libavcodec/libwebpenc_animencoder.o
       > CC libavcodec/libwebpenc_common.o
       > CC      libavcodec/libx264.o
       > CC        libavcodec/libx265.o
       > CC        libavcodec/libxavs.o
       > CC        libavcodec/libxevd.o
       > CC        libavcodec/libxeve.o
       > CC        libavcodec/libxvid.o
       > CC        libavcodec/libzvbi-teletextdec.o
       > CC    libavcodec/ljpegenc.o
       > CC       libavcodec/loco.o
       > CC   libavcodec/lossless_audiodsp.o
       > CC      libavcodec/lossless_videodsp.o
       > libavcodec/libxeve.c: In function 'get_conf':
       > libavcodec/libxeve.c:199:27: error: incompatible types when assigning to type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'} from type 'long int'
       >   199 |         cdsc->param.fps = lrintf(av_q2d(avctx->framerate));
       >       |                           ^~~~~~
       > libavcodec/libxeve.c: In function 'libxeve_encode':
       > libavcodec/libxeve.c:484:40: error: incompatible types when assigning to type 'int' from type 'XEVE_RATIONAL' {aka 'struct _XEVE_RATIONAL'}
       >   484 |                 avpkt->time_base.den = xectx->cdsc.param.fps;
       >       |                                        ^~~~~
       > make: *** [ffbuild/common.mak:82: libavcodec/libxeve.o] Error 1
       > make: *** Waiting for unfinished jobs....
       For full logs, run 'nix log /nix/store/n9vd6qaiyzkyc8jf09ikr07k3vm9wxs2-jellyfin-ffmpeg-7.0.2-5.drv'.
```

### Notify maintainers

@justinas 

### Metadata

- system: `"x86_64-linux"`
- host os: `Linux 6.6.58, NixOS, 24.11 (Vicuna), 24.11.20241025.18536bf`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.24.9`
- nixpkgs: `/nix/store/wb6agba4kfsxpbnb5hzlq58vkjzvbsk6-source`
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by justinas** [comment]
As others have commented on previous issues about this, this should have been solved by https://github.com/NixOS/nixpkgs/pull/353198 which just recently merged. The commit seems to have made it [to master, but not `nixos-unstable` yet](https://nixpk.gs/pr-tracker.html?pr=353198). Please be patient, once `nixos-unstable` (assuming you're on this channel) advances, you'll get the fix.

You have other options rather than waiting:
* Switch to an older revision of `nixos-unstable`
* Switch to `master` (you'll get this fix, but might need to rebuild other stuff, or something else might be broken)

`jellyfin-ffmpeg` is cached in Hydra for the current master (2bd5a51a151e0eac8244b38a394c10aeb5c6f75d ), so we do know that it has been fixed and builds successfully (x86_64-linux).

**Comment by JollyDevelopment** [comment]
As a note - this also happens when upgrading `immich` from unstable channel. Good to know that it's fixed, I will wait for the fix to hit `nixos-unstable` branch.

Just posting in case other `immich` users do the same search. :-)

**Comment by dotlambda** [comment]
duplicate
