### ISSUE TITLE
Update request: mullvad-vpn 2024.6 -> 2024.7

### ISSUE THREAD

**Issue by MisileLab** [NixOS/nixpkgs#353798]
- Package name: mullvad-vpn
- Latest released version: 2024.7

- Current version on the unstable channel: 2024.6
- Current version on the stable/release channel: 2024.3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

---

@Br1ght0ne @ymarkus @AtaraxiaSjel 

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by SigmaSquadron** [comment]
The `mullvad-vpn` package is Linux-only, and this changelog doesn't seem to include any changes for Linux. Is that right?

**Comment by MisileLab** [comment]
> The `mullvad-vpn` package is Linux-only, and this changelog doesn't seem to include any changes for Linux. Is that right?

honestly, I want to upgrade it because mullvad gui keeps saying "out of sync"

**Comment by ymarkus** [comment]
@cole-h @Br1ght0ne @AtaraxiaSjel We should maybe look into fixing the issue of having two different packages for the same software. It seems that like every few months, one of the two packages goes out of sync and breaks something. 
@MisileLab can you please send me the part of your config where you configure Mullvad? And any mentions of the package in your config. It is very weird to have it out of sync if you just configure it via module...
This issue was exactly the same, only that here `pkgs.mullvad` was not updated.: #321971

**Comment by MisileLab** [comment]
I looked at that issue, and I found a solution.
(I didn't `services.mullvad-vpn.package = pkgs.mullvad-vpn;`)
but I think it is a valid issue.
maybe can we make a new issue about this?

**Comment by MisileLab** [comment]
I'll close it for now, maybe we can open new issue
