### ISSUE TITLE
Package kanidm minor versions separately

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#353889]
### Describe the bug
Similar to PostgreSQL, Kanidm has a manual upgrade process to move between minor versions (e.g. 1.3 -> 1.4), and can only upgrade one minor version at a time. Hence, upgrading NixOS packages might invariably break Kanidm (especially on NixOS unstable). It would be great to be able to pin Kanidm to a minor version (i.e. services.kanidm.package = kanidm_1_4) to be able to avoid breakage.

### Steps To Reproduce
1. Update NixOS
2. Kanidm no longer starts because it was upgraded to a version that needs manual intervention

### Expected behavior
Like other databases, Kanidm should be explicitly pinned to a specific version to avoid this.

### Notify maintainers

@adamcstephens @Flakebi 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.59, NixOS, 24.11 (Vicuna), 24.11.20241103.b47af37`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by adamcstephens** [comment]
Upstream only provides one month of supported overlap, so this is a non-zero amount of extra effort for a limited period of time. I'm generally against this idea and if you want stability I think you should stay on the stable nixos release. 

Note that even on nixos stable we will need to upgrade between versions during its lifecycle in order to stay within the supported version windows. My current plan for this was to let the newer version bake for a bit and target the close to 30-day mark for updating nixos stable. For example, this means that 24.05 will be upgraded to 1.4.x at the end of November. 

While I understand the concerns about stability, this is a critical security component and it is imperative that we stay within what upstream supports.

https://kanidm.github.io/kanidm/stable/support.html

**Comment by adamcstephens** [comment]
I had a discussion with @mweinelt about this on Matrix, and have softened my stance somewhat. I'm currently short on spoons to implement something like this, but will hopefully do so soon in the near future.

**Comment by adamcstephens** [comment]
see #357734
