### ISSUE TITLE
Build failure: pyload-ng

### ISSUE THREAD

**Issue by PhilVoel** [NixOS/nixpkgs#354115]
### Steps To Reproduce

1. build `pyload-ng`

### Build log

Output of `nix log /nix/store/g8z4i906cpfm9slhibk16fw273m67zgz-pyload-ng-0.5.0b3.dev85.drv`: https://gist.github.com/PhilVoel/11dc82f73a2b171b49b5f0af2ad5bc22

### Additional context

I use it through `config.services.pyload` which does use the lastest version.
When i last updated my flake inputs (Oct 16) the build worked (`bs39xjl00q2ncxi3pzhk1jbak4phrr3n-pyload-ng-0.5.0b3.dev85` in the store). Now it still seems to build the package successfully but complains at the very end that the runtime dependency `js2py` is not installed.

### Notify maintainers

@ruby0b 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.56, NixOS, 24.05 (Uakari), 24.05.20241014.c0b1da3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.8`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/store/wdk3xa0vwx7swjdl1samf1bccvyyzfc1-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ruby0b** [comment]
js2py had a critical security vulnerability and was therefore removed (#349550) which is why pyload no longer builds with python3.11 (the version used by nixos-23.11).
You can use the nixos-unstable version of pyload-ng (set `services.pyload.package` accordingly) until nixos-24.11 releases.

(Ideally the error would mention this but I don't think that's worth working on at this point)
