### ISSUE TITLE
Add option in nix-ld module to load all libraries installed in the system

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#354513]
Right now, the [programs.nix-ld.libraries](https://search.nixos.org/options?channel=24.05&show=programs.nix-ld.libraries&from=0&size=50&sort=relevance&type=packages&query=nix-ld) option allows me to add packages to nix-ld… but this is really tedious to maintain this list. For instance, here is the list I currently maintain:
```
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      # List by default
      zlib
      zstd
      stdenv.cc.cc
      curl
      openssl
      attr
      libssh
      bzip2
      libxml2
      acl
      libsodium
      util-linux
      xz
      systemd

      # My own additions
	    xorg.libXcomposite
      xorg.libXtst
      xorg.libXrandr
      xorg.libXext
      xorg.libX11
      xorg.libXfixes
      libGL
      libva
      pipewire
      xorg.libxcb
      xorg.libXdamage
      xorg.libxshmfence
      xorg.libXxf86vm
      libelf
      
      # Required
      glib
      gtk2
      
      # Without these it silently fails
      xorg.libXinerama
      xorg.libXcursor
      xorg.libXrender
      xorg.libXScrnSaver
      xorg.libXi
      xorg.libSM
      xorg.libICE
      gnome2.GConf
      nspr
      nss
      cups
      libcap
      SDL2
      libusb1
      dbus-glib
      ffmpeg
      # Only libraries are needed from those two
      libudev0-shim

      # needed to run unity
      gtk3
      icu
      libnotify
      gsettings-desktop-schemas
      # https://github.com/NixOS/nixpkgs/issues/72282
      # https://github.com/NixOS/nixpkgs/blob/2e87260fafdd3d18aa1719246fd704b35e55b0f2/pkgs/applications/misc/joplin-desktop/default.nix#L16
      # log in /home/leo/.config/unity3d/Editor.log
      # it will segfault when opening files if you don’t do:
      # export XDG_DATA_DIRS=/nix/store/0nfsywbk0qml4faa7sk3sdfmbd85b7ra-gsettings-desktop-schemas-43.0/share/gsettings-schemas/gsettings-desktop-schemas-43.0:/nix/store/rkscn1raa3x850zq7jp9q3j5ghcf6zi2-gtk+3-3.24.35/share/gsettings-schemas/gtk+3-3.24.35/:$XDG_DATA_DIRS
      # other issue: (Unity:377230): GLib-GIO-CRITICAL **: 21:09:04.706: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
      
      # Verified games requirements
      xorg.libXt
      xorg.libXmu
      libogg
      libvorbis
      SDL
      SDL2_image
      glew110
      libidn
      tbb
      
      # Other things from runtime
      flac
      freeglut
      libjpeg
      libpng
      libpng12
      libsamplerate
      libmikmod
      libtheora
      libtiff
      pixman
      speex
      SDL_image
      SDL_ttf
      SDL_mixer
      SDL2_ttf
      SDL2_mixer
      libappindicator-gtk2
      libdbusmenu-gtk2
      libindicator-gtk2
      libcaca
      libcanberra
      libgcrypt
      libvpx
      librsvg
      xorg.libXft
      libvdpau
      # ...
      # Some more libraries that I needed to run programs
      gnome2.pango
      cairo
      atk
      gdk-pixbuf
      fontconfig
      freetype
      dbus
      alsaLib
      expat
      # Needed for electron
      libdrm
      mesa
      libxkbcommon
      # Needed to run, via virtualenv + pip, matplotlib & tikzplotlib
      stdenv.cc.cc.lib # to provide libstdc++.so.6
      pkgs.gcc-unwrapped.lib # maybe only the first one needed

      # needed to run appimages
      fuse # needed for musescore 4.2.1 appimage
      e2fsprogs # needed for musescore 4.2.1 appimage
      fribidi # needed for xournalpp (nightly 08/11/2024)
      librsvg # needed for xournalpp (nightly)
      ibus # needed for xournalpp (nightly)
    ];
};
```
and I need to add new entries everytime I try to run a new package (I'm fighting right now again to make xournalpp's nighly run locally…).

It would therefore be great to add an option that automatically adds all packages/libraries installed globally (or as a transitive dependency of an installed package), so that I don't need to worry too much about adding new entries here (or only really specific and rare ones). This option may accept a boolean like true to enable, or a function taking a list of all derivations that would be added, so that we can filter them if we want to add/remove some.

Pinging some people that modified this file in the past or are related to nix-ld:
- @SuperSandro2000 
- @Mic92 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
I'll be completely honest with you, this is a very bad decision. **nix-ld** was designed to help simplify the execution of apps that would require some form of wrapping/rebuilding to work in Nix/NixOS. It's a great tool to use when you want to avoid headaches, but you've genuinely used it too far. NixOS is _not_ intended to be used in this manner, because this is really only adding a headache for you, the user. At this point you would generally be better off using a standard FHS distro and avoiding NixOS/NixOS entirely.

I dont mean this in a disrespectful way at all, just want to point out that this is really making more work for you than its worth, and would cement a very bad practice for _NixOS_ users by encouraging this usage. You're practically ditching all the benefits of NixOS and Nix by proxy, to try and make FHS-compliant things work this way. It's really no different than just using any other distro with its package manager.

**Comment by SuperSandro2000** [comment]
it would also be easier to load incompatible libraries this way and produce very hard to debug errors.

**Comment by CHN-beta** [comment]
I use libraries from `steam-run`, which covers all my needs.

```
libraries = [(pkgs.runCommand "steamrun-lib" {}
  "mkdir $out; ln -s ${inputs.pkgs.steam-run.fhsenv}/usr/lib64 $out/lib")];
```

**Comment by Mic92** [comment]
@Frontear Can you please not tell people how they should or should not use NixOS? 
Not everyone has "Nix packaging" in it's pure form as a hobby and sometimes just need to get work done and get on with their live. I noticed the same line communication also in other places. nix-ld is an optional module and you don't have to use it if you don't like.

@tobiasBora I cannot think of an easy to way to inject all runtime libraries into your system closure. Nix only knows about system dependencies but runtime dependencies are figured out during the build. And as @SuperSandro2000 noted, we will likely have libraries in different versions in our NixOS closure that will be not compatible with each other. So an automatic approach that just pulls in all libraries will likely not work. i.e. if someone mixes nixpkgs unstable and stable they can end up will crash very likely. 

However there might be ways to analyze binaries with tools like `lddtree` and feed the input into `nix-index` to generate a better list. Since `nix-index` will likely report multiple hits for a package, I would use some sort of page rank algorithm to prefer packages that have more dependent packages. However this tool would be something that would generate the code rather to be imported in your NixOS configuration than a magic NixOS option, hence nixpkgs might be not the best place to start with it.

**Comment by Frontear** [comment]
> @Frontear Can you please not tell people how they should or should not use NixOS? 
> 
> Not everyone has "Nix packaging" in it's pure form as a hobby and sometimes just need to get work done and get on with their live.

I regret that this is how my comment came across, but I won't try to discredit how someone could have felt reading it. I apologize for how my comment came off, and I offer my apologies to the original poster and anyone else who felt upset or offended by what I had said. I most certainly did not intend to be rude, disparaging, and discouraging of other people's choices, despite that I acknowledge that my intent does not translate across the text, nor does it diminish the hostility and hurt someone could feel from it.

**Comment by drakon64** [comment]
> > @Frontear Can you please not tell people how they should or should not use NixOS?
> > Not everyone has "Nix packaging" in it's pure form as a hobby and sometimes just need to get work done and get on with their live.
> 
> I regret that this is how my comment came across, but I won't try to discredit how someone could have felt reading it. I apologize for how my comment came off, and I offer my apologies to the original poster and anyone else who felt upset or offended by what I had said. I most certainly did not intend to be rude, disparaging, and discouraging of other people's choices, despite that I acknowledge that my intent does not translate across the text, nor does it diminish the hostility and hurt someone could feel from it.

I don’t see the issue with anything you said, if anything the comment after was unnecessary 🤷‍♂️

**Comment by tobiasBora** [comment]
Thanks for your answers.

Regarding @Frontear's comment, I love NixOs, but there are many cases where the "nix way" is just not practical. E.g. just try to develop with npm/java/… or any other language that likes to download pre-built binaries. I could certainly try to find a way to package each dependency, but nix-ld is really practical to do a rapid prototyping before losing time on packaging. You can't imagine how much time I saved thanks to nix-ld, and in my opinion a good distribution must also be practical, not just beautiful theoretically. Similarly, testing a nightly-build package/a package not yet present in nixpkgs is impossible to do without nix-ld or losing 40mn (if not more) just to see how to package it properly. Finally there are some software maintainers that ask you to test their software with the binary they provide to be sure the bug is in their software and not in the way it was packaged… yet another use case for nix-ld. Yet, if you don't like nix-ld you can still disable it while understanding that some users may have a use-case for it.

@Mic92  thanks, collisions and incompatibilities are indeed interesting questions, that's also why I proposed to add a filter function to manually remove possibly conflicting libraries. Another solution could be, maybe, to take the newest version of each library by default, or something along this line… Or maybe to manually hardcode a large list of common libraries if it's too hard to do? Steam could indeed be a good starting point. (Or both approaches are maybe not incompatible)

**Comment by drakon64** [comment]
> Regarding @Frontear's comment, I love NixOs, but there are many cases where the "nix way" is just not practical.

The way I see it, a Linux distribution is a tool that is good for a job. Sometimes a tool just isn't suitable for a job, and that's okay.

To me `nix-ld` in its current state provides a reasonable compromise between following "the nix way" and still providing some utility where "the nix way" is more of a curse than a benefit. However the ideal solution would always be proper packaging of binaries.

> Or maybe to manually hardcode a large list of common libraries if it's too hard to do? Steam could indeed be a good starting point.

I feel like this could end up as a bikeshedding exercise where people argue over what the common libraries to be included are.

**Comment by Mic92** [comment]
@tobiasBora you can create a list of libraries one would get if installing one of the big desktop environments. One can assume that this wouldn't cause a lot of extra downloads because it's already in the runtime closure. Alternatively package manager such as flatpack also have a base set of libraries they provide, I believe.

**Comment by Jackaed** [comment]
> > [@Frontear](https://github.com/Frontear) Can you please not tell people how they should or should not use NixOS?
> > Not everyone has "Nix packaging" in it's pure form as a hobby and sometimes just need to get work done and get on with their live.
> 
> I regret that this is how my comment came across, but I won't try to discredit how someone could have felt reading it. I apologize for how my comment came off, and I offer my apologies to the original poster and anyone else who felt upset or offended by what I had said. I most certainly did not intend to be rude, disparaging, and discouraging of other people's choices, despite that I acknowledge that my intent does not translate across the text, nor does it diminish the hostility and hurt someone could feel from it.

I don't think you came off as particularly rude, but I also disagree with your original comment. Don't get me wrong, I understand where you're coming from - if you're going to use Nix, you should try and use Nix for as much as you can. But there are times it just isn't fesible or practical. For example, if you're a software engineer using a specific toolchain for some code, odds are you'd like to be on the same binary build of that toolchain as everyone on your team - rather than using the Nix version of that binary - since you don't want to introduce bugs and not spot them because they aren't issues with how nix built that particular binary.

The steam-run solution works well for this purpose.

**Comment by tobiasBora** [comment]
After a bit of investigation, I'd like to suggest to reopen this issue for a few reasons:

1. I agree that adding all libraries installed in the current system is hard to do to avoid conflicts etc… yet one solution is to simply hard-code a large list of good candidates.
2. steam-run was proposed, but it has a few issues: first it is not compatible with Arm, second, according to @ElvishJerricco [it does not add many libraries](https://github.com/NixOS/nixpkgs/blob/e3a39e5b47103de92d13b4f7809294ac730d5e1c/pkgs/by-name/st/steam/package.nix#L36-L852) because steam "uses its own runtime".

So it seems like the best solution would be to add one option in nix-ld to automatically pull a large list of dependencies. The list I gave above might be a good starting point, but we should probably add more.

**Comment by SuperSandro2000** [comment]
> 1. yet one solution is to simply hard-code a large list of good candidates.

You can already do that in your config and just add a hundred libraries into the option but from my experience with this, it would be a pretty bad default and can easily cause very strange errors that are not explainable.

> 2\. because steam "uses its own runtime".

Yep. Steam downloads it's own runtime which is guaranteed to be compatible and causes way less incompatibilities and reduces maintenance a lot. It had been abused since years as a grab bag for everything but it never was intended to be that.

> So it seems like the best solution would be to add one option in nix-ld to automatically pull a large list of dependencies. 

No, that would be a very bad solution. LD_LIBRARY_PATH is an env which can cause very strange and hard to debug errors and break things quite easily. It should be used careful and not in a shotgun approach where just everything is written into it.

> we should probably add more.

That won't scale well and just adding and adding to a list makes it unmaintainable. There is no target defined and no program for which it should work. A recent example I came across was libsoup 2 and 3 which cannot be loaded at the same time and a program that has that just crashes. Similar things will apply to other libraries and programs.

---

The solution to your problem is to either package the programs in nix, use targeted fhsenv's or expand your nix-ld config with everything you need.

**Comment by claymorwan** [comment]
> I use libraries from `steam-run`, which covers all my needs.
> 
> ```
> libraries = [(pkgs.runCommand "steamrun-lib" {}
>   "mkdir $out; ln -s ${inputs.pkgs.steam-run.fhsenv}/usr/lib64 $out/lib")];
> ```

ya happen to know if it's possible to make that work with games in lutris ? Launching the executable through the terminal works thanks to this but doesn't when using lutris

**Comment by CHN-beta** [comment]
> > I use libraries from `steam-run`, which covers all my needs.
> > ```
> > libraries = [(pkgs.runCommand "steamrun-lib" {}
> >   "mkdir $out; ln -s ${inputs.pkgs.steam-run.fhsenv}/usr/lib64 $out/lib")];
> > ```
> 
> ya happen to know if it's possible to make that work with games in lutris ? Launching the executable through the terminal works thanks to this but doesn't when using lutris

Sorry I do not use lutris. But I sometimes use binfmt to launch windows exe and it just works. I do not know if it is helpful for your games.
```
boot.binfmt.emulatedSystems = [ "x86_64-windows" ];
```

**Comment by tobiasBora** [comment]
Ok so in the meantime I maintain in the wiki a list of nix-ld dependencies that work well for my case https://wiki.nixos.org/w/index.php?title=Nix-ld&wvprov=sticky-header Feel free to modify it (but maybe add it at the end after a clearly visible line, since I may erase it by mistake as I often update it when i see a missing item).

> I repeat: this is NOT about some academic notion of "purity"; this is about the nix-ld module taking the problem that nix solved 20 years ago and bringing it back to NixOS and making the average beginner user even more confused.

Tired of repeating myself. If you think nix-ld is not useful, then how would you run, e.g. pdf4teachers in NixOs without nix-ld? (I tried to package it and failed due to weird java-related errors, so any answer here must involve a full derivation + the time you spent to write it) Or are you a programmer that needs to install thousands of java/javascript dependencies in some projects? Nix-ld allows sooo much flexibility (no need to lose X hours to package each dependency when starting a new project that is not yet worth packaging) that saying that it can solely be replaced with nix packaging is a lie.
