### ISSUE TITLE
tt-rss service broken with mysql

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#35469]
## Issue description

`services.tt-rss` fails with mysql (works with pgsql): Access denied.

### Steps to reproduce

I have the following service definition:
```
services.tt-rss = {
  enable = true;
  selfUrlPath = "http://localhost";
  database = {
    type = "mysql";
  };
};
```

However, `tt-rss` service fails with the following error:
```
tt-rss-pre-start[12363]: ERROR 1698 (28000): Access denied for user 'tt_rss'@'localhost'
```

I checked from the pre-start script that it's basically command similar to this that fails:

```
sudo -u tt_rss echo $(echo 'select count(*) > 0 from information_schema.tables where table_schema = schema()' | /nix/store/fw1zigv2wiai5yxhzlzsnjra11qfq15z-mariadb-10.2.12/bin/mysql -u tt_rss tt_rss)
```

I don't understand why it fails. This command works:

```
sudo -u tt_rss mysql tt_rss -u tt_rss
```

What could be wrong?

The user `tt_rss` is ensured: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix#L572

The database `tt_rss` is ensured: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix#L571

The permissions are ensured: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix#L575

Also, every user should have read access to `information_schema`.

What's wrong and how to fix?

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 18.03pre127302.e860b651d6e (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre127302.e860b651d6e"`
 - channels(jluttine): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by jluttine** [comment]
Works with pgsql.

**Comment by jtojnar** [comment]
>     sudo -u tt_rss echo $(echo 'select count(*) > 0 from information_schema.tables where table_schema = schema()' | /nix/store/fw1zigv2wiai5yxhzlzsnjra11qfq15z-mariadb-10.2.12/bin/mysql -u tt_rss tt_rss)

You are calling echo as root which is quite pointless – if you want to run the mariadb program as a different user, you need to move into the [command substitution](http://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html#sect_03_04_04). MySQL should not really need sudo, as it has its own user management.

The [`callSql`](https://github.com/NixOS/nixpkgs/blob/247a7504adb193c34fab2c3af8e25ed2b65e3763/nixos/modules/services/web-apps/tt-rss.nix#L507-L512) and the rest of the module looks fine to me, though.

**Comment by florianjacob** [comment]
I think I know hwat's going on here:

If no database password is specified (as you did when this is your full config), this tries to use Unix socket authentication, as `ensureUsers` sets that as authentication mechanism for the created users. The problem comes from the fact that `preStart` and therefore the `mysql` command is run as root, but then the root user tries to execute mysql commands using `mysql -u tt_rss`, which gets denied because the `root` user is not the `tt_rss` user. So it is the *authentication* that fails here, the root user would actually *have* the required permissions to execute the SQL statements if he tried to authenticate as the mysql `root` user, by *not* specifying `-u tt_rss`.

As the sql operations only require the privileges of the `tt_rss` user (or at least it seems for me that way from looking at the code, correct me if I'm wrong), the proper fix would actually be to run the mysql command as `tt_rss` user via sudo, essentially copying the sudo call from the pgsql branch for the `mysql` command.

So you were on the right track with `sudo`, and @jtojnar explained exactly why this still didn't work: sudo needs to be moved into the command substitution.

(author of the `services.mysql.ensure*` attributes here)

**Comment by jluttine** [comment]
Thanks for the comments. I may have mislead you by the example I gave, sorry.. It was just meant for reproducing the failing command at the command line, but the actual command in the service definition doesn't use `sudo`:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix#L545
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix#L508

There's no `sudo` in that service definition when using mysql, so if I understand correctly, the problem isn't related to `sudo`. So I don't understand why the authentication fails.

**Comment by jluttine** [comment]
The failing command is:

```
echo $(echo 'select count(*) > 0 from information_schema.tables where table_schema = schema()' | /nix/store/fw1zigv2wiai5yxhzlzsnjra11qfq15z-mariadb-10.2.12/bin/mysql -u tt_rss tt_rss)
```

And I think it's run as `tt_rss` user in pre-start phase.

**Comment by florianjacob** [comment]
No, what I tried to say is that the command fails *because* it has no sudo, but should have, like in the pgsql case at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix#L501.

Try this, this should work (if I got the bash syntax right):
```
echo $(echo 'select count(*) > 0 from information_schema.tables where table_schema = schema()' | sudo -u tt_rss /nix/store/fw1zigv2wiai5yxhzlzsnjra11qfq15z-mariadb-10.2.12/bin/mysql -u tt_rss tt_rss)
```

`preStart` isn't running as tt_rss because of `PermissionsStartOnly = true` at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix#L560 - probably some of the other setup commands like `mkdir -m 755 -p "${cfg.root}"` require root.

**Comment by yegortimoshenko** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/36367, no workarounds necessary.
