### ISSUE TITLE
Android Studio with nixpkgs-provided SDK does not work

### ISSUE THREAD

**Issue by musjj** [NixOS/nixpkgs#355045]
### Describe the bug

The `android-studio` package when provided with a custom SDK using `withSdk`, simply does not work because the filesystem is read-only.

### Steps To Reproduce

You can put this inside a dev shell:

```nix
with pkgs;
mkShell {
  buildInputs = [
    (android-studio.withSdk
      (androidenv.composeAndroidPackages {
        platformVersions = [ "34" ];
        includeEmulator = true;
        includeSystemImages = true;
        includeNDK = true;
      }).androidsdk
    )
  ];
};
```

### Expected behavior
Android Studio should function correctly with the custom SDK.

### Screenshots

![image](https://github.com/user-attachments/assets/8b745056-39e3-49ff-ae2b-dd9b0470a7f7)
![image](https://github.com/user-attachments/assets/bf43ed30-34ca-4d1e-b635-3c98df7d26b7)
![image](https://github.com/user-attachments/assets/523e58f6-397e-43e9-b76a-d105f112a4f3)

### Notify maintainers

@alapshin @johnrtitor @numinit @hadilq

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.59, NixOS, 24.11 (Vicuna), 24.11.20241105.4aa3656`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source`

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by musjj** [comment]
I tried to edit and reselect the path, but the error still persists. Here's a recording:

[Kooha-2024-11-11-02-37-30.webm](https://github.com/user-attachments/assets/8191e0c6-2adc-417f-8b2b-3401c362da7c)

**Comment by numinit** [comment]
I've figured out again what the exact silliness required to solve this is. You have to open a project first since, for some reason, it shows the SDK path but actually stores it in an individual project's local.properties.

https://github.com/user-attachments/assets/e0d63f45-e3a6-47f6-806c-cd32ba202914

**Comment by musjj** [comment]
Thank you so much for the help, the ritual worked for me!

I'm not working on an Android Studio project (I'm using Expo), so I downloaded a sample project from https://github.com/android/storage-samples/tree/main/ActionOpenDocument and opened it on Android Studio just like in your video. 

I clicked on `File` (top left hamburger icon) -> `Close Project` to go back to the main menu. Then, on the top right kebab menu I finally have access to the `Virtual Device Manager` and I can now set up a device for Expo to use!

**Comment by alapshin** [comment]
Yeah, combination of nixified Android SDK and Android Studio has some weird quirks because Android Studio tries to manage SDK by itself.

In ideal scenario Android Studio would just use ANDROID_SDK_ROOT but as far as I can tell it first writes it to `local.properties` and then use it from here. This means that value of `sdk.dir`  in `local.properties` has to be kept to date with current nix store path for Android SDK which can change after rebuilds.

**Comment by numinit** [comment]
I usually just obliterate that file and put the correct value there with a shell hook. Not ideal, but typically solves the issue.

**Comment by Philzen** [comment]
Trying this for days now in order to bootstrap a react-native/expo project and was trilled to read @numinit's and @musjj's replies above. Also tried creating that `local.properties` with an `sdk.dir` key manually. However, whatever i try – the entry in the main menu stays greyed out

<img width="392" height="174" alt="Image" src="https://github.com/user-attachments/assets/884f97a9-5969-4947-8eb4-be16327adc24" />

and when i open a project and then try to create a new virtual device from the device manager it always comes up with 

<img width="381" height="144" alt="Image" src="https://github.com/user-attachments/assets/568fb573-c567-4271-bd7d-e294f7e3e474" />

… following the "Configure SDK" path won't do anything as all the options are greyed out there as well. Contrary to this behavior the SDK path and the SDK components brought in via `shell.nix` all show up fine in the SDK manager reached via IDE settings, referring to the nix store path.

Notably, there is no Android SDK shown in the Project Structure… Dialogue – if i try to add it there, the browse dialogue will accept that nix store path, but on confirmation the SDK simply won't show up as being added.

I'm at the point of giving up here and only using nix to provide bun and node, while resorting to requiring the IDE and emulators as a "classical" user-space installation.
