### ISSUE TITLE
Cannot sign in to proton-pass application

### ISSUE THREAD

**Issue by LinuxMason** [NixOS/nixpkgs#355095]
### Describe the bug
On the date of this post, shortly after the system tray icon fix update made its way to the unstable repo, suddenly I cannot sign in to proton-pass application. It shows an error with the message “your session could not be resumed”.

I've signed out, and attempted to sign back in with no luck. It does accept my password and even my 2FA code, but once past that prompt, it fails to sign in and provides the error I mentioned above.

There was a new version update prompt earlier today in the app when I was able to sign in shortly after the system tray icon fix. This could potentially be the reason for the sign in error. Perhaps an upgrade to the new version is required?

### Steps To Reproduce
1. Sign in to proton-pass unstable nixpkg.
2. Observe the error.

### Expected behavior
It should sign in as usual.

### Screenshots
![image](https://github.com/user-attachments/assets/6ce9d8c3-22d7-4bc3-8987-3e34349182a9)

### Additional context
A new version is available.

### Notify maintainers
@luftmensch-luftmensch 
@massix 
@SebTM

**Comment by massix** [comment]
I think I know where the problem is, and I apologize for this. As a temporary workaround, you can start proton-pass using the environment variable `ELECTRON_FORCE_IS_PACKAGED` set to the value `1`, just be aware that the tray icon won't load. 

I forgot to embed the TLS certificates inside the ASAR archive (I must have tested using an asar version I built locally instead of the one from the `result` folder). Will fix it ASAP, I am truly sorry for this!

**Comment by massix** [comment]
> > Contributor
> 
> If this indeed is the root cause, why is the `overrideAttrs` of the latest version from Proton's website still resulting in the same issue?

Because it is not related to the version of Proton Pass.  The way Electron handles ASAR applications right now is kind of a mess and based on some heuristics which may or may not work on NixOS.  I kind of forced the things with the tray icons (putting there directly inside the ASAR), which worked well but broke the handling of SSL certificates.

The good news is that I managed to solve it, I'll open a PR first thing tomorrow morning, just need to clean a couple of things up.

Again, I am really sorry for the issue, I don't know why I thought it was working well for me before, might be that I wasn't testing the right version after all.

**Comment by massix** [comment]
If you want to test the fix you can `nix run github:massix/nixpkgs/fix/proton-pass-login#proton-pass`, you should have both the tray icon working *and* the ability to log in.

**Comment by massix** [comment]
Well, if you want to keep using my version, you have to launch Proton Pass using the `nix run` command above or add my repository as an input to your flakes and create an overlay.

**Comment by daniel-fahey** [comment]
`nix run github:massix/nixpkgs/fix/proton-pass-login#proton-pass` (without the package update) works for me, thanks @massix!

It's quite a nice program I can see why you use it over the browser extension.
