### ISSUE TITLE
nix.conf: create function for creating this file

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#35662]
## Issue description

The `nix-daemon` module creates a `nix.conf` file. The derivation creating this file is useful also for non-NixOS users and should therefore be factored out.

The main motivation is generating the paths for `"extra-sandbox-paths"`.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by 7c6f434c** [comment]
Should we factor out the generation of `nix.conf` or should we have official support for exporting `/etc/` entries from a NixOS system?

Currently I use 
```
  etcSelectPrefix = filenamePrefix: config:
    let
      nixosInstance = nixos {configuration = config;};
      selected = (pkgs.lib.filterAttrs
                           (k: v: pkgs.lib.hasPrefix filenamePrefix v.target)
                           nixosInstance.config.environment.etc);
    in (pkgs.lib.mapAttrs'
             (k: v: let source = v.source; in
                      { 
                        value = (if pkgs.lib.isString source then source else source.outPath);
                        name = v.target;
                      })
             selected);
```
and select the `nix/` prefix with a configuration containing _only_ `{ nix= {…}; }` part.

**Comment by FRidh** [comment]
> Should we factor out the generation of nix.conf or should we have official support for exporting /etc/ entries from a NixOS system?

It would need a different approach and is of a much larger scope, but why not. 

Does your `nixosInstance` need a kernel configuration? I suppose not, unless a module that you request needs it.

**Comment by 7c6f434c** [comment]
`nixos=import <nixpkgs/nixos>` is the typical context.

A typical invocation is `etcSelectPrefix "nix/" { nix = { useSandbox = true; }; }`

My current helper library is https://github.com/7c6f434c/lang-os/blob/master/use-from-nixos.nix and its use is https://github.com/7c6f434c/lang-os/blob/master/system-etc-pieces.nix and https://github.com/7c6f434c/lang-os/blob/master/local/test-system.nix (`etcSelect…` calls)

As of scope — I think the main question is «can we agree to keep `/etc`, and `/etc/nix/` there, for a longer time than a module system; and does Nixpkgs as a project commit not to do completely crazy scoping that makes the entries invisible from outside». Because if the answer is «Yes there is a commitment.», an implementation against the current NixOS code is small. And I need to maintain it for a comfortable environment anyway.

Of course, adding `makeNixConf` to Nixpkgs further normalizes splitting the implementation from coordination/configuration as implemented by NixOS module system which does sound nice…

**Comment by Infinisil** [comment]
See https://github.com/NixOS/nixpkgs/pull/44322#issuecomment-410203835

Feel free to close this issue if you feel like that's good enough

**Comment by FRidh** [comment]
I have no need for this any longer and the suggestion in https://github.com/NixOS/nixpkgs/pull/44322#issuecomment-410203835 seems adequate as well.
