### ISSUE TITLE
Renovate service restart loop

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#358028]
## Issue description

[The Renovate service is configured to restart on failure](https://github.com/NixOS/nixpkgs/blob/23e89b7da85c3640bbc2173fe04f4bd114342367/nixos/modules/services/misc/renovate.nix#L107). This is surprising, and could cause API throttling or infrastructure costs. This probably should be a one-shot service, especially when [`services.renovate.schedule`](https://search.nixos.org/options?channel=unstable&show=services.renovate.schedule&from=0&size=50&sort=relevance&type=packages&query=renovate) is set.

Ping @Scrumplex @NyCodeGHG 

### Steps to reproduce

Set `services.renovate.enable = true;` and start the service with world state such that it will fail to run every time.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.62, NixOS, 25.05 (Warbler), 25.05.20241118.5083ec8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"home-manager, nixos, nixos-hardware, nixos-stable-24.05"`
 - nixpkgs: `/nix/store/n1g84klfb0h3bpwyvc59lcy5ca58h36w-source`

**Comment by NyCodeGHG** [comment]
there has been a discussion in #334557 about `Type=oneshot`. It has been set to simple, because otherwise nixos-rebuild blocks if renovate is running at the same time. Adding an option to turn off restart would be an idea.
You can also add rate limits to renovate's systemd unit using [StartLimitIntervalSec and StartLimitBurst](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#StartLimitIntervalSec=interval)

**Comment by l0b0** [comment]
Thanks for the quick response! I've had a look through #334557, and considering all the arguments and counter-arguments I wonder whether making the type configurable might be a good compromise. I definitely do not ever want Renovate to run more than once a day, and I can absolutely live with `nixos-rebuild` taking a few minutes extra for the single relevant host.
