### ISSUE TITLE
Module request: factoriolab

### ISSUE THREAD

**Issue by Tanvir1337x** [NixOS/nixpkgs#362521]
## Description

A web server for hosting factoriolab, supporting both local and public deployments.

## Notify maintainers

@PatrickDaG

-----

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by PatrickDaG** [comment]
Not quite sure we really need a module for this. It's just a static website, which you can use any webserver to host. Since there is no configuration as far as I can see, a module would just be a very basic {nginx,caddy,traefik,...} configuration which I don't think would be to usefull since we'd have to make a lot of assumptions about systems.
