### ISSUE TITLE
GitHub actions may fail with refs/pull/<number>/merge not found when PR is merged immediately after changing title

### ISSUE THREAD

**Issue by FliegendeWurst** [NixOS/nixpkgs#365382]
## Describe the bug

See e.g.
- https://github.com/NixOS/nixpkgs/actions/runs/12339697729
- https://github.com/NixOS/nixpkgs/actions/runs/12339713317
- https://github.com/NixOS/nixpkgs/actions/runs/12339713307
- https://github.com/NixOS/nixpkgs/actions/runs/12339713316

## Steps To Reproduce

See issue title

## Expected behavior

GitHub action either uses the merged commit or skips execution.

## Notify maintainers

For Codeowners specifically: @infinisil 

It affects other checks too.

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by FliegendeWurst** [comment]
It is related - changing the title will re-trigger CI.

**Comment by infinisil** [comment]
Only the [first link](https://github.com/NixOS/nixpkgs/actions/runs/12339697729) is an instance of the problem with `refs/pull/<number>/merge`, and that is fixed on master with https://github.com/NixOS/nixpkgs/pull/364338! So that just needs a backport :)

The other three failed because they ran on an intermediate commit (https://github.com/NixOS/nixpkgs/commit/4f9ec4fb6d045cc2ed36d921f9fa8792b63c5e2a) that didn't have the `ffmpeg` argument which you [later force pushed](https://github.com/NixOS/nixpkgs/compare/4f9ec4fb6d045cc2ed36d921f9fa8792b63c5e2a..b42224fbbf424b50b61fbf09e7c0e3e5221852ce).

**Comment by infinisil** [comment]
https://github.com/NixOS/nixpkgs/pull/365673
