### ISSUE TITLE
proton-pass minimize and close argument no longer working

### ISSUE THREAD

**Issue by LinuxMason** [NixOS/nixpkgs#368026]
## Describe the bug

When using home-manager for xdg autostart to have proton-pass launch at startup, I had --minimize set as an argument previously, and it would start the application minimized on OS boot, which is ideal. In one of the recent updates, this no longer works. When proton-pass launches on startup, it launches in the foreground, and I can't find any other way to force it to minimize.

## Steps To Reproduce

1. Setup XDG autostart via home-manager for proton pass
2. Set the exec line with --minimize or even --close argument.
3. Reboot

## Expected behavior

I expect to be able to use an argument in the exec line for xdg autostart entry that can force the app to minimize on startup.

## Additional context

The argument used to work, but no longer works in recent updates.

## Notify maintainers

@luftmensch-luftmensch 
@massix 
@SebTM

**Comment by massix** [comment]
Hello,
could you please share a snippet of your home-manager configuration so that I can try to replicate it? I have never used such an option before.

Also, do you remember which version of proton-pass was working with the flags as you described?

Thanks!

**Comment by massix** [comment]
Hi again,
don't worry :)

Unluckily, implementing that kind of behavior means heavily modifying the source code, and I don't feel like doing it, since we only have a "transpiled" version of it in the Electron's ASAR. You can open a discussion on Proton's forums and ask for the feature to be implemented, though :)

Have a nice day.
