### ISSUE TITLE
couchdb: build fails with erlang issue

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#36823]
## Issue description

Build fails.  See [hydra output for full details](https://hydra.nixos.org/build/70844257/nixlog/1), but the short-and-sweet is:

```
checking Erlang version compatibility... detected Erlang version: 8.3.5...compatible
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
configure: error: Could not find the Erlang crypto library.

Has Erlang been compiled with OpenSSL support?
builder for '/nix/store/yad8msfx5fm4qclqp4sq5cp0al3kp109-couchdb-1.7.1.drv' failed with exit code 1
```

I did a bisect to address the culprit CL.  It identified eb0368554661385ae470e245e50bd0bc10693bf0, upgrading `gtk-doc`.  I was initially skeptical that that could be the issue---I mean, `gtk-doc`?---but if I revert that one change, and then rebuild 1) it does rebuild erlang, and 2) the couchdb build does, in fact, succeed.

So somehow that `gtk-doc` change seems to be provoking erlang to be rebuilt, but then it isn't rebuilding correctly.

**Comment by pbogdan** [comment]
While with a different package I encountered a related issue building an erlang package. However in my case reverting the commit you indicated was not sufficient and I had to revert b3d2a87b532 as well!

There appears to be at least one more instance where a seemingly unrelated package deep down erlang's dependency chain causes strange failures - https://github.com/NixOS/nixpkgs/commit/fced35fa44098be0296d8b42166583bd5e505141#commitcomment-27974860 /cc @the-kenny

**Comment by the-kenny** [comment]
I'll open a separate issue for this. I haven't had any luck solving this issue yet.

**Comment by pbogdan** [comment]
Further data point - on my machine (NixOS 17.09 with nixStable2, building from recent-ish master) the `gtk-doc` reverts only work if I let Nix use Erlang from the binary cache. If I however try to rebuild both Erlang and the affected package then Erlang build succeeds but the package itself fails. If I do the same with Nix 1.11.16 then both Erlang and the package build.

This looks to be related to what can be seen on Hydra here - https://hydra.nixos.org/build/70845721/log -> CTRL-F "cp: cannot stat". The error looks to be produced by the `Install` script which I believe is ran by `/bin/sh` and contains the following statement:

```
cp -p ../releases/19/start_*.boot .
```

(I believe this is the source of the script - https://github.com/mfoemmel/erlang-otp/blob/master/erts/etc/unix/Install.src#L148)

A quick experiment shows that the sandbox `/bin/sh` on 17.09 with nixStable2 somehow cannot deal with such globbing pattern which doesn't get expanded and so the argument is treated literally, and results in files missing in the Erlang package.

So it seems the issue here is that something in the dependency triggers an Erlang rebuild and I suspect the build may land on a Hydra builder with a feature-limited sandbox `/bin/sh` producing a non-working Erlang package. It's a guess but perhaps the results vary between both the different builders and locally depending on the Nix version and from which nixpkgs version it was obtained.

**Comment by xeji** [comment]
Yes, this could be another symptom of `/bin/sh` impurity, see also #36669

**Comment by xeji** [comment]
erlang source has a lot of  `#!/bin/sh` shebangs. `patchShebangs` in `preConfigure` might help.

**Comment by dtzWill** [comment]
Should be fixed by #36919.

**Comment by xeji** [comment]
This does not appear to be fixed yet: https://hydra.nixos.org/build/71407019 , same error as OP.

**Comment by the-kenny** [comment]
Note that there's some progress in #36853 - I'm just now evaluating if my fix there is the "correct" one (@xeji's comment looks relevant there)

**Comment by the-kenny** [comment]
I just pushed 3e61f3b911c to `master`, hopefully fixing (or at least work around) the issue. Please try & report :)

**Comment by xeji** [comment]
Hydra builds look fine now. @mdorman please close after confirming.
