### ISSUE TITLE
Build failure: openscad

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#368421]
## Steps To Reproduce

1. build *openscad* on unstable

## Build log

<details>

<summary>Build Log</summary>

```
src/FileModule.cc: In member function 'void FileModule::registerUse(std::string, const Location&)':
src/FileModule.cc:68:25: error: 'is_regular' is not a member of 'fs'; did you mean 'is_regular_file'?
   68 |                 if (fs::is_regular(path)) {
      |                         ^~~~~~~~~~
      |                         is_regular_file
````

</details>

## Metadata

commit: c8365111999b8e0f268de233ce0e967062d6128c

## Notify maintainers
@bjornfor @gebner 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by newAM** [comment]
This broke from updating `boost` to 1.85: <https://www.boost.org/users/history/version_1_85_0.html>

> Removed APIs that were previously declared deprecated. In particular, path and recursive_directory_iterator member functions, is_regular, copy_directory, symbolic_link_exists, complete, copy_option, symlink_option, as well as boost/filesystem/convenience.hpp and boost/filesystem/path_traits.hpp headers were removed. 

According to this SO answer <https://stackoverflow.com/a/37899472> `is_regular` and `is_regular_file` are the same.

This build failure can be fixed by pinning boost, or by patching the function call.

I opened a PR to patch the function since that seems like the lesser of two evils: #368477

**Comment by gshpychka** [comment]
Still fails on `aarch64-darwin` for me: https://github.com/NixOS/nixpkgs/pull/368477#issuecomment-2565372303
