### ISSUE TITLE
systemd is out of date.

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#36918]
## Issue description
Arch is already on [238](https://www.archlinux.org/packages/core/x86_64/systemd/).
[238](https://github.com/systemd/systemd/releases) fixes some PAM issues so having this up sooner than later would be very appreciated!

### Steps to reproduce
N/A

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.24, NixOS, 18.03pre130932.cc4677c36ee (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Chiiruno** [comment]
I'd open a pull request, but a big project like this I'm not too sure how to navigate the patches and other nuances something like systemd needs to have to work with nixos. If it's as simple as just changing the hash and download link and whatever else, then please say so.

**Comment by dtzWill** [comment]
I'm actually not sure why (what's different?) but NixOS uses a fork of systemd, perhaps a PR to that repo would be a starting point?

https://github.com/NixOS/systemd

**Comment by fpletz** [comment]
@Chiiruno Regarding the PAM fixes: I can't a mention in the NEWS file of systemd. Are they critical? Should we backport this to 18.03?

Otherwise the changelog looks fine to me, even for a 18.03 backport.

To update systemd a new branch has to be created on our systemd fork with all our patches rebased to the current tag. This is pretty easy and I can do it if required.

**Comment by 7c6f434c** [comment]
Just a recent change there: upstream systemd has long defaulted to breaking the very idea of screen, tmux and POSIX-required nohup by cleaning up user processes on logout regardless of the daemonised state. This is apparently because Gnome cannot keep track of its own daemons, and also cannot put them into a separate cgroup. When that version landed in Nixpkgs, NixOS default config for logind has been updated to switch this functionality off. Recently, config handling has changed, so just the default got patched.

Also, the log shows that special handling of / and /usr is extended to /nix and /nix/storem, that hardcoded /lib/modules check is removed etc.

**Comment by Chiiruno** [comment]
@fpletz No, it is not critical except for bcachefs and ecryptfs users. #32279 #30333
I'm a bit of a newbie, so I can't tell you whether or not this should be backported to 18.03, I can say I'd like it to be.

**Comment by fpletz** [comment]
Ah, those PAM issues. Awesome. Thanks! I'll look into it. cc @vcunat

**Comment by fpletz** [comment]
Fixed by #37647 for staging/master and https://github.com/NixOS/nixpkgs/compare/361bd591ea4a...2d2ab94cd2c7 for 18.03.

**Comment by Baughn** [comment]
Well, this is a problem -- see #37744.

I suspect any fix for the mouse problem won't make it into 18.03.

**Comment by vcunat** [comment]
Security and bug -fixes are the point of stable releases.
