### ISSUE TITLE
Restore ability to build Nix from a git checkout

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nixpkgs#37201]
nixUnstable used to build Nix from a git checkout, allowing overrideAttrs to be used on it to build Nix from custom git checkouts. Recently nixUnstable has been remapped to just "nixStable" though, which does not get the source from a git checkout. Attempting to use a git checkout on the current nixUnstable fails due to it not using the right builder.

Either nixUnstable should be restored to pulling from a git checkout, or the "common" function in nix/default.nix should be exposed in some way.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix/default.nix#L138

**Comment by matthewbauer** [comment]
You can still override source I believe:

```
nix-build -E 'with import <nixpkgs> {}; nixUnstable.overrideAttrs (o: {
  src = fetchFromGitHub {
    owner = "NixOS";
    repo = "nix";
    rev = "a6c0b773b72d4e30690e01f1f1dcffc28f2d9ea1";
    sha256 = "0i8wcblcjw3291ba6ki4llw3fgm8ylp9q52kajkyr58dih537346";
  };
  fromGit = true;
})'
```

**Comment by coreyoconnor** [comment]
That override should work but due to how the "common" attributes are constructed the "fromGit" change will have no effect. The result is the derivation missing hte "nativeBuildInputs" required.

There is still an override that works, requires adding those dependencies in manually:

~~~
nixUnstable = super.nixUnstable.overrideAttrs (oldAttrs: rec
  {
    rev = "48662d151bdf4a38670897beacea9d1bd750376a";

    src = self.fetchgit
    {
      rev = "48662d151bdf4a38670897beacea9d1bd750376a";
      url = "https://github.com/NixOS/nix.git";
      sha256 = "0avrdd5k138s2zlrwabxd60dz8jzhil0z29sdqs1g1cm5yxx83cp";
    };

    nativeBuildInputs = with self; [ autoreconfHook autoconf-archive bison flex libxml2 libxslt docbook5 docbook5_xsl pkgconfig boost ];
});
~~~

Still, the nix derivation should support overriding "fromGit" as expected.
