### ISSUE TITLE
lilypond: broken build

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#37548]
## Issue description

https://hydra.nixos.org/build/71492931

I attempted to bisect, but so many of the possible commits would have spent hours building that I wasn't able to narrow it down.

**Comment by pbogdan** [comment]
Reverting 76bc1d3fae46f28dd28cad8bc998dba74d03285e seems to fix the build here. I'm not sure which part of the commit is causing the issue in the first place, and since the commit is supposed to fix some issues a straight-up revert is likely a wrong solution. Perhaps @Ericson2314 will be able to help?

**Comment by pbogdan** [comment]
Seems like instead of reverting the commit adding `libtool` back to `propagatedBuildInputs` of guile fixes this build failure as well. If `guile-config` is any indication it does indeed seem to be required for linking to guile:

```shell
$ guile-config link
 -pthread -L/nix/store/05hmgk2niafrm93608l5rpc7xswv3cqi-guile-1.8.8/lib -lguile -lltdl -lgmp -lcrypt -lm -lltdl
```

(`ltdl` is part of libtool)

**Comment by Ericson2314** [comment]
Hmm ok I made it non-propagated to be consistent, because the newer ones just looked better packaged

**Comment by mdorman** [comment]
@Ericson2314 You mean the newer guile packages?  They all have `libtool` in their `propagatedBuildInputs`.

**Comment by Ericson2314** [comment]
Oh I see how I screwed this up. Changing the PR to make all the fixes happen in each.
