### ISSUE TITLE
Figure out why tests.gnome3-gdm are timing out

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#37642]
After [3.28 update](https://github.com/NixOS/nixpkgs/pull/36893) the test times out. It works just fine outside.

**Comment by hedning** [comment]
Seems like the test have been broken for a very long time: https://hydra.nixos.org/build/71887078

Could it be a problem with unepexpected DISPLAY. GDM hangs around on `:0` spawning gnome-shell on a new X server on `:1`. Might explain the `machine# xwininfo: error: unable to open display ":0.0"`?

**Comment by pbogdan** [comment]
IIRC the issue is with the Xauthority file not being where the test environment needs it, instead of being placed in the user's home folder it's under /run/user/$UID/gdm/Xauthority (exact path might be slightly different, can't remember exactly atm).

Because of that and the way gnome-terminal is being launched it fails to start, `xauth merge` fails as well causing those xwininfo errors.

I presume it doesn't affect normal user sessions as those would have XAUTHORITY environment variable set.

As an experiment I symlinked the file to /home/alice/.Xauthority as part of the test and that fixed it on my machine, but not sure what would be a proper fix for this.

**Comment by jtojnar** [comment]
It has been succeeding again for a while now:

https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.gnome3-gdm.x86_64-linux
