### ISSUE TITLE
nox-review broken with nix-shell --pure

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#37970]
## Issue description

Nox-review doesn't work if launched in nix-shell with `--pure`.

### Steps to reproduce

```
# nix-shell --pure -p nox

$ nox-review -h
Traceback (most recent call last):
  File "/nix/store/frhh9wads9vzbks8cv81a0h27hr6dr18-nox-0.0.6/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/s9x1fh363bp15f6f1mvaglbhwbb7h9pk-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/s9x1fh363bp15f6f1mvaglbhwbb7h9pk-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/nix/store/s9x1fh363bp15f6f1mvaglbhwbb7h9pk-python3.6-click-6.7/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

Additional information: on this system no suitable UTF-8
locales were discovered.  This most likely requires resolving
by reconfiguring the locale system.
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.20, NixOS, 18.03.git.831ef47 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by matthewbauer** [comment]
This is a pretty common issue. See discussion in madjar/nox#19. Most likely you will have to set LC_ALL in nix-shell:

```
export LC_ALL=en_us.UTF-8
```

Technically LC_ALL is an impurity that --pure will overwrite (run printenv inside nix-shell to see what is provided). It's not very easy to solve because we don't want things from your environment "leaking" into nix-shell for build purposes (although there are a few exceptions see https://github.com/NixOS/nix/blob/12913ccf454c1bc82a51c59872f8185b40c533c5/src/nix-build/nix-build.cc#L371). Maybe we should add LC_ALL as a keep var? Although for now I would suggest just leaving out '--pure'.

**Comment by jluttine** [comment]
Why does nox-review need `LC_ALL`? Maybe it shouldn't depend on that, or define some default value for it if it needs some value for it?

**Comment by matthewbauer** [comment]
It comes from Python's locale handling. I think it only happens on Python 3 though.

https://docs.python.org/3/library/locale.html

**Comment by jtojnar** [comment]
We now prefer nix-review.
