### ISSUE TITLE
Packaging request: beaker browser

### ISSUE THREAD

**Issue by patrl** [NixOS/nixpkgs#38037]
Peer-to-peer web browser based on Dat protocol: https://beakerbrowser.com/
Repository: https://github.com/beakerbrowser/beaker

I might come back and do this myself at some point, but I'm adding this here as a placeholder so that if anyone starts working on this, they can mention it here.

**Comment by kamilchm** [comment]
It would be probably better to build beaker with electron, but I use `appimageTools` to have beaker in nix:
```
{ stdenv, appimageTools, fetchurl }:
appimageTools.wrapType2 {
  name = "beakerbrowser";
  src = fetchurl {
    url = "https://github.com/beakerbrowser/beaker/releases/download/0.8.7/Beaker.Browser.0.8.7.AppImage";
    sha256 = "0x29ysnqjf7f0s6kgqkm5wmc4d3zp2gfbg0qh78qgl4phyhfzgfr";
  };
}

```

**Comment by bignaux** [comment]
I think we should be less regarding and accept packages that use appimageTools.wrapType2 (now you can use appimageTools.wrapAppImage , since this kind of application seems really annoying and discouraging to package, as show #66571 . You can be interesting on my work on #81833 , i now can provide a way to escape AppRun and let you run directly call ./beaker-browser .

**Comment by bbigras** [comment]
I still want that.

**Comment by milahu** [comment]
https://github.com/beakerbrowser/beaker is dead, last commit 2 years ago

see also https://github.com/beakerbrowser/beaker/issues/1959

**Comment by zimbatm** [comment]
RIP
