### ISSUE TITLE
Package request: Cockpit

### ISSUE THREAD

**Issue by Limero** [NixOS/nixpkgs#38161]
Cockpit is a server manager that makes it easy to administer your GNU/Linux servers via a web browser.

Website: http://cockpit-project.org/
Upstream: https://github.com/cockpit-project/cockpit/
License: LGPL2.1
Arch Linux package: https://aur.archlinux.org/packages/cockpit/

![image](http://cockpit-project.org/images/site/screenshot-docker.png)

**Comment by bachp** [comment]
Probably only a subset will work. But I think there is some stuff in cockpit that is helpful even on NixOS:

- View journald logs and systemd services
- Manage virtual machines via libvirt
- Get a shell terminal from the  Web UI
- Some general system information like disk usage etc.

It's mostly read only stuff but I'm not sure how easy it is to only use parts of cockpit that would work.

**Comment by dmjio** [comment]
+1 would love to have this

**Comment by thefenriswolf** [comment]
> 
> 
> Probably only a subset will work. But I think there is some stuff in cockpit that is helpful even on NixOS:
> 
>     * View journald logs and systemd services
> 
>     * Manage virtual machines via libvirt
> 
>     * Get a shell terminal from the  Web UI
> 
>     * Some general system information like disk usage etc.
> 
> 
> It's mostly read only stuff but I'm not sure how easy it is to only use parts of cockpit that would work.

Given that NixOS is pitched as a server os first, this would be very helpful. I already tried to package this myself but got stuck because it requires a few npm packages

**Comment by wmertens** [comment]
@thefenriswolf try with https://github.com/moretea/yarn2nix?

**Comment by bachp** [comment]
I still think it would be good to have this in NixOS.

**Comment by wmertens** [comment]
Well as @Mic92 pointed out, there will be quite a lot of patching up paths to do, as well as the NPM packages that need installing (try yarn2nix or npm2nix for that)

Seeing as it's non-trivial, it will have to be packaged by someone with real interest in getting it, and we can assist (make a draft PR and tag us on questions)

**Comment by thefenriswolf** [comment]
node is only required for the dev environment
I have made [some progress](https://gist.github.com/thefenriswolf/baaadf92a1b9511b49666ce83fabac8f) packaging cockpit, it still fails to compile tho
Any help would be greatly appreciated

**Comment by tomberek** [comment]
```
building
build flags: SHELL=/nix/store/5hplxs3kprdp6v62qk3di6a1m1s1paiq-bash-4.4-p23/bin/bash
  GEN      src/ws/mock-dbus-tests.h
Traceback (most recent call last):
  File "/nix/store/5zajbm8674d93nix4h8b0hxgglj2pbir-glib-2.64.3-dev/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/nix/store/5zajbm8674d93nix4h8b0hxgglj2pbir-glib-2.64.3-dev/share/glib-2.0/codegen/codegen_main.py", line 24, in <module>
    import argparse
  File "/nix/store/jli50q24fvik6pfsnjs1jd90g3dy4p6y-python3-3.8.3/lib/python3.8/argparse.py", line 88, in <module>
    import re as _re
  File "/nix/store/jli50q24fvik6pfsnjs1jd90g3dy4p6y-python3-3.8.3/lib/python3.8/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
make: *** [Makefile:10639: src/ws/mock-dbus-tests.h] Error 1
error: --- Error ------------------------------------------------------------------------------------------ nix-build
error: --- Error --- nix-daemon
builder for '/nix/store/mdiihwskfp862y17wp70skdy74kh33v5-cockpit-222.1.drv' failed with exit code 2; last 10 log lines:
    File "/nix/store/5zajbm8674d93nix4h8b0hxgglj2pbir-glib-2.64.3-dev/bin/gdbus-codegen", line 53, in <module>
      from codegen import codegen_main
    File "/nix/store/5zajbm8674d93nix4h8b0hxgglj2pbir-glib-2.64.3-dev/share/glib-2.0/codegen/codegen_main.py", line 24, in <module>
      import argparse
    File "/nix/store/jli50q24fvik6pfsnjs1jd90g3dy4p6y-python3-3.8.3/lib/python3.8/argparse.py", line 88, in <module>
      import re as _re
    File "/nix/store/jli50q24fvik6pfsnjs1jd90g3dy4p6y-python3-3.8.3/lib/python3.8/re.py", line 145, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  make: *** [Makefile:10639: src/ws/mock-dbus-tests.h] Error 1
```
Seems like an error in the package itself.

**Comment by catern** [comment]
The enum thing is due to a stray enum34 dependency in python38Packages.pyscss - enum34 is a backport of the enum module, and breaks things if it's installed on Python >= 3.4. You'll need to look at why pyscss is pulling in enum34 - it's not immediately obvious to me from pyscss's default.nix, it looks correct.

A pthread link error happens if that's fixed or if Python is removed from the deps entirely. That pthread link error is, I believe, a problem with the Cockpit makefiles; I made https://github.com/cockpit-project/cockpit/pull/14480 to fix it.

With that change applied, I get
```
  WEBPACK  apps
webpack-make: Cannot find module 'stdio'
Require stack:
- /home/sbaugh/.local/src/nixpkgs/cockpitsrc/tools/webpack-make
WARNING: './tools/webpack-make' is missing on your system.
```

I don't know anything about the Javascript packaging, so no idea how to progress from here. Good luck!

**Comment by thefenriswolf** [comment]
It compiles but gets stuck writing it's systemd.service files. I don't have much experience packaging applications which hook into systemd
https://gist.github.com/thefenriswolf/baaadf92a1b9511b49666ce83fabac8f

**Comment by michalrus** [comment]
How’s the effort? :crossed_fingers:  :crossed_fingers:  :crossed_fingers:

**Comment by baronleonardo** [comment]
If this gonna work I could start replacing my `Proxmox` with `NixOS`

**Comment by baronleonardo** [comment]
I have updated @thefenriswolf nix to solve the issue of `systemd` beside updating the version
https://gist.github.com/baronleonardo/a4e83df0a7e6c20fa3cd0c9317e10b80

**Comment by cyounkins** [comment]
I built the derivation posted by @baronleonardo by including `(import ./cockpit.nix)` in my `environment.systemPackages`. It built successfully, producing `/nix/store/dr8q3dwm7pz4p2nbn5v7xg08n5973ixz-cockpit-244.1`.

The output includes many things for `/etc` like systemd units that do not get installed on the system - I'm wondering if these should be symlinked in as-is, or do they need to be converted to Nix?

```
root@pluto /nix/store/dr8q3dwm7pz4p2nbn5v7xg08n5973ixz-cockpit-244.1/etc# find .
.
./motd.d
./motd.d/cockpit
./cockpit
./cockpit/machines.d
./cockpit/ws-certs.d
./issue.d
./issue.d/cockpit.issue
./systemd
./systemd/cockpit.socket
./systemd/cockpit-motd.service
./systemd/cockpit.service
./systemd/cockpit-wsinstance-https@.socket
./systemd/cockpit-wsinstance-https-factory.socket
./systemd/cockpit-wsinstance-http-redirect.service
./systemd/cockpit-wsinstance-http.service
./systemd/cockpit-wsinstance-https@.service
./systemd/cockpit-wsinstance-http-redirect.socket
./systemd/cockpit-wsinstance-https-factory@.service
./systemd/system-cockpithttps.slice
./systemd/cockpit-wsinstance-http.socket
```

Most systemd units look OK but `cockpit.socket` will need a fix to replace a reference to `/bin/ln`:
```
ExecStartPost=-/bin/ln -snf active.motd /run/cockpit/motd
ExecStopPost=-/bin/ln -snf inactive.motd /run/cockpit/motd
```

**Comment by cyounkins** [comment]
If `"--with-systemdunitdir=$(out)/etc/systemd"` is changed to `"--with-systemdunitdir=$(out)/etc/systemd/system"` (in patch below), and `systemd.packages = [ cockpit ];` is added to `configuration.nix`, the units get installed but are not enabled.

The package also has references to `/usr/bin/ssh-add` and `/usr/bin/ssh-agent`, please let me know if you know how best to patch these:
```
craig@pluto ~/c/cockpit-244.1> grep -ri 'usr/bin/ssh' *
configure:  test -z "$ac_cv_path_SSH_ADD" && ac_cv_path_SSH_ADD="/usr/bin/ssh-add"
configure:  test -z "$ac_cv_path_SSH_AGENT" && ac_cv_path_SSH_AGENT="/usr/bin/ssh-agent"
configure.ac:AC_PATH_PROG([SSH_ADD], [ssh-add], [/usr/bin/ssh-add], [$PATH:/usr/local/sbin:/usr/sbin:/sbin])
configure.ac:AC_PATH_PROG([SSH_AGENT], [ssh-agent], [/usr/bin/ssh-agent], [$PATH:/usr/local/bin:/usr/bin:/bin])

craig@pluto ~/c/cockpit-244.1> grep -r 'SSH_' Makefile.in
...
SSH_ADD = @SSH_ADD@
SSH_AGENT = @SSH_AGENT@
...
```

I patched the reference to `/bin/ln`, and replaced `stdenv.lib` with just `lib` due to build warning. Here's what I have, building entirely on what others have contributed to this thread: https://gist.github.com/cyounkins/2c3336b92cecb49f0699f860aee0a007

**Comment by cyounkins** [comment]
I considered running the docker container, but it requires [mounting the whole host filesystem](https://github.com/cockpit-project/cockpit-container/blob/21f395c81e12353e8bf5260b8f49ef21292cbee0/atomic-install#L17) and proceeds to modify the host's PAM config. Not something I personally like to see in a docker container...

Back to the Nixpkgs. I was able to use `wrapProgram` so that `cockpit-certificate-helper` has references to coreutils programs and patched the certificate paths to be `/var/lib/cockpit/ws-certs.d`. `autoreconfHook` was added because of patches to `Makefile-ws.am`.

Right now it fails running `ExecStartPre=/nix/store/kk1b9qnh8r5nx9clc4rwbcd9pqxgwi7f-cockpit-244.1/libexec/cockpit-certificate-ensure` with SIGSEGV. I thought it might be systemd's `ProtectSystem=strict` setting, but it does the same outside invocation by systemd.

```
$ strace /nix/store/kk1b9qnh8r5nx9clc4rwbcd9pqxgwi7f-cockpit-244.1/libexec/cockpit-certificate-ensure
...
stat("/etc/gnutls/config", 0x7ffe88a64760) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/var/lib/cockpit/ws-certs.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=2, ...}) = 0
mmap(NULL, 135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f854a12b000
getdents64(3, 0x7f854a12b040 /* 2 entries */, 131072) = 48
getdents64(3, 0x7f854a12b040 /* 0 entries */, 131072) = 0
munmap(0x7f854a12b000, 135168)          = 0
close(3)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
```

I tried building newer versions of cockpit, but I kept running into
```
Unknown subcommand make_package_lock_json
make[1]: *** [Makefile:9983: package-lock.json] Error 1
```

There are some notes [here](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#building) that might be helpful.

Here's the latest packaging attempt: https://gist.github.com/cyounkins/c0245db25a96f355f68bb212ecab33f8

Even though I've posted like 4 times in a row, I think I'm done trying to do this. I hope someone else can pick up the effort.

**Comment by jakobrs** [comment]
> I tried building newer versions of cockpit, but I kept running into
> 
> ```
> Unknown subcommand make_package_lock_json
> make[1]: *** [Makefile:9983: package-lock.json] Error 1
> ```

I was able to get past this by changing the interpreter in `build/node-modules` from `/bin/sh` to `${bash}/bin/bash`. Note that, for some reason, `/usr/bin/env bash` doesn't work. You also have to run `touch packages-lock.json`, because Nix resets its date and that breaks the "is packages-lock.json newer than packages.json" check.

I also had to replace `#!/usr/bin/env node` with `#!${node}/bin/node` in `tools/webpack-make`.

What's odd is that all of the scripts run correctly when run from `nix-shell ./cockpit.nix --pure`.

When this is done, `tools/webpack-make` will just error with "Cannot find module stdio".

**Comment by addreas** [comment]
Spent some time learning nix by giving this a shot and actually ended up getting things to start. A lot of things are not working, but some might be possible to fix.  For anyone  interested I have left things here: https://github.com/addreas/cockpit-nix

**Comment by dukzcry** [comment]
Another take on it
```nix
{ pkgs, config, lib, ... }:
let
  nur-no-pkgs = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {};
in {

  imports = [
    nur-no-pkgs.repos.dukzcry.modules.cockpit
  ];

  services.cockpit = {
    enable = true;
    port = 9090;
  };

}
```

`sudo systemctl start cockpit.socket`

Tested features:
- Logs
- Virtual Machines (cockpit-machines module)
- Services
- Terminal

Code:
https://github.com/repos-holder/nur-packages/blob/master/pkgs/cockpit/default.nix
https://github.com/repos-holder/nur-packages/blob/master/pkgs/cockpit/machines.nix
https://github.com/repos-holder/nur-packages/blob/master/pkgs/libvirt-dbus.nix
https://github.com/repos-holder/nur-packages/blob/master/modules/cockpit.nix

**Comment by 3Dcube** [comment]
> Another take on it
> 
> ```nix
> { pkgs, config, lib, ... }:
> let
>   nur-no-pkgs = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {};
> in {
> 
>   imports = [
>     nur-no-pkgs.repos.dukzcry.modules.cockpit
>   ];
> 
>   services.cockpit = {
>     enable = true;
>     port = 9090;
>   };
> 
> }
> ```
> 
> `sudo systemctl start cockpit.socket`
> 
> Tested features:
> 
> * Logs
> * Virtual Machines (cockpit-machines module)
> * Services
> * Terminal
> 
> Code: https://github.com/repos-holder/nur-packages/blob/master/pkgs/cockpit/default.nix https://github.com/repos-holder/nur-packages/blob/master/pkgs/cockpit/machines.nix https://github.com/repos-holder/nur-packages/blob/master/pkgs/libvirt-dbus.nix https://github.com/repos-holder/nur-packages/blob/master/modules/cockpit.nix

Tried to create a virtual machine, no luck, OS list is empty. Cannot create VM without choosing the operating system. I tried to fix it but I got the following error:
```
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/nix/store/x9646yl53vv1jwhjrlrjb4fv7fssgm3n-python3-3.9.6-env/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Libosinfo not available
```

![image](https://user-images.githubusercontent.com/17197542/163812315-e8e82a29-cf93-4e11-8985-6fd81f0abd82.png)

**Comment by montchr** [comment]
I came across this discussion in the upstream project and figured it might be helpful to cross-reference:

https://github.com/cockpit-project/cockpit/discussions/17558

**Comment by hurricanehrndz** [comment]
> > Another take on it
> > ```nix
> > { pkgs, config, lib, ... }:
> > let
> >   nur-no-pkgs = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {};
> > in {
> > 
> >   imports = [
> >     nur-no-pkgs.repos.dukzcry.modules.cockpit
> >   ];
> > 
> >   services.cockpit = {
> >     enable = true;
> >     port = 9090;
> >   };
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `sudo systemctl start cockpit.socket`
> > Tested features:
> > 
> > * Logs
> > * Virtual Machines (cockpit-machines module)
> > * Services
> > * Terminal
> > 
> > Code: https://github.com/repos-holder/nur-packages/blob/master/pkgs/cockpit/default.nix https://github.com/repos-holder/nur-packages/blob/master/pkgs/cockpit/machines.nix https://github.com/repos-holder/nur-packages/blob/master/pkgs/libvirt-dbus.nix https://github.com/repos-holder/nur-packages/blob/master/modules/cockpit.nix
> 
> Tried to create a virtual machine, no luck, OS list is empty. Cannot create VM without choosing the operating system. I tried to fix it but I got the following error:
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 7, in <module>
>   File "/nix/store/x9646yl53vv1jwhjrlrjb4fv7fssgm3n-python3-3.9.6-env/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Libosinfo not available
> ```
> 
> ![image](https://user-images.githubusercontent.com/17197542/163812470-159cb989-4eb0-4e81-b126-362458af1738.png)

You require libosinfo, and osinfo-db

**Comment by hurricanehrndz** [comment]
@3Dcube I would to keep working on this issue, any hints you got for me would be welcomed. I do see any errors in my log

**Comment by lucasew** [comment]
I am also working on this

Here is what I have so far: https://github.com/nixosbrasil/nixpkgs-brasil/tree/master/pacotes/wip/cockpit

It's building only. I was able to solve some documentation build bugs.

**Comment by lucasew** [comment]
:eyes: 

![Captura de tela_2023-01-05_13-19-21](https://user-images.githubusercontent.com/15693688/210828994-6d7b1f2c-c24c-413d-9d8a-5f0179e9d13a.png)

**Comment by dgiridharan** [comment]
Amazing! Thanks for providing the NixOS module for Cockpit!

I wanted to access Cockpit from another machine (and not just localhost) within the network. As such I've the following configuration:

```
services.cockpit = {
  enable = true;
  port = 9090;
  openFirewall = true;
  settings = {
    WebService = {
      AllowUnencrypted = true;
    };
  };
};
```

Everything works well. That said, when I try accessing Cockpit from my laptop on the same network, I can't enable admin controls. It throws the following error:

![image](https://github.com/user-attachments/assets/7f70d477-a921-40a0-891c-35e1538a548b)

I'm really new to Nix so sorry if this is a basic problem!

I suspect this might be due to different paths on NixOS. Does anyone know if it’s possible to use [nix-ld](https://github.com/nix-community/nix-ld) to resolve this issue?

Would love to hear if anyone has managed to fix this. Thanks in advance!

**Comment by lucasew** [comment]
I can reproduce the issue. I have no idea how to solve it now tho.

**Comment by dgiridharan** [comment]
@lucasew - It seems like a bug finding the `cockpit-askpass` path. Seems like this could be helpful (I cross posted there):
https://github.com/cockpit-project/cockpit/discussions/17558#discussioncomment-11677025

Any ideas?

**Comment by dgiridharan** [comment]
I created a new issue to keep track of this with some additional details. I hope that's ok!
