### ISSUE TITLE
nixos-container-compose: if nixos-container is docker, where docker-compose for nixos-containers?

### ISSUE THREAD

**Issue by srghma** [NixOS/nixpkgs#38299]
## Issue description
I want to be able run group of containers imperatively. 
Something like:
`nixos-container-compose -f containers.nix run backend rspec` where containers.nix 

```nix
{
  database = {
   ...
  };
  backend = {
    dependsOn = [ database ]
    ...  
  }
}
```

Expose ports, link containers and all other nifty things that docker-compose allows us, while keeping resulting configuration compatible with nixops. How can I do this?

**Comment by srghma** [comment]
Recently I wanted to test nixos module, very simple module with systemd job that starts `safeeyes`, and I didn't find any way to test it, except rebuild my whole configuration against local nixpkgs with this configuration using `nixos-rebuild -I nixpkgs=/path/to/nixpkgs test`

It would be cool if I could do something like this

```nix
# configuration-test.nix
{  pkgs }:
{
   systemd.user.services.test = ....
}
```
and run something like `nixos-rebuild test-additive ./configuration-test.nix` and it would spawn this one job, that wouldnt survive after restart or next `nixos-rebuild build`

Maybe this is related

**Comment by nixy** [comment]
I'm not sure about your second request (the additive tests), but if you're looking to imperatively manage groups of NixOS containers you'll probably want to look at the `containter` backend for [NixOps](https://github.com/nixos/nixops).

The container backend isn't very well documented, but it pretty much just spawns nixos-containers for the network you describe. Using NixOps like this you'd still end up describing your containers declaritively, but they would be separate from you system configuration so they wouldn't affect what happens when you do a `nixos-rebuild switch`.

I think that's the closest to what you're looking for with containers.

**Comment by Mic92** [comment]
Is this solved?

**Comment by srghma** [comment]
@Mic92 I think yes

**Comment by CMCDragonkai** [comment]
@srghma Nixos containers use systemd not docker?

**Comment by srghma** [comment]
@CMCDragonkai I know that nixos containers use systemd, and not docker. I wanted to find tool to manage multiple containers simultaneously (like docker-compose does), and it's nixops
