### ISSUE TITLE
Mopidy: Include pip modules with the installation of mopidy

### ISSUE THREAD

**Issue by thorerik** [NixOS/nixpkgs#38758]
## Issue description

It would be nice if like with `services.mopidy.extensionPackages`, one could specify pip modules like `mopidy-mpris`, to allow for including newer modules that don't yet have a native nix package.

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131792.becbe4dbe16 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03.131792.becbe4dbe16"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by dotlambda** [comment]
That will probably not happen, with the reasons being
- incompatibility with the Nix principle of reproducible builds (you don't know in advance which version is installed by `pip`)
- security (installing any software from PyPI is definitely a security risk)

That said, you have two options:
- package the python packages yourself and open PRs in this repo (better option because everyone can use the new packages)
- use https://github.com/garbas/pypi2nix or similar tools
