### ISSUE TITLE
qt510 binaries broken on 18.03 on non-NixOS

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#38832]
## Issue description
When trying to run qt510 binaries on 18.03, they fail with:
```
error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```
### Steps to reproduce
Use nixos-18.03 channel and run
```
nix-shell --pure -p qt510.qtbase --run 'uic --help'
nix-shell -p qt510.qtconnectivity --run 'sdpscanner --help'
nix-shell --pure -p owncloud-client --run 'owncloudcmd --help'
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 3.16.7-53-desktop, openSUSE, 13.2 (Harlequin)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(jkemet): `"nixos-17.03-17.03.1949.78e9665b48f, nixos-17.09-17.09.3238.e984f9e48e1, nixos-18.03-18.03.131950.1c52531bbe9, nixpkgs-18.03"`
 - nixpkgs: `/home/jkemet/.nix-defexpr/channels/nixpkgs`

**Comment by knedlsepp** [comment]
This seems to work for NixOS. I have also tried 5.9 on openSUSE and it worked too.

**Comment by knedlsepp** [comment]
I'm a little confused why this happens. Looking at the output of `readelf -d` for any of the programs doesn't yield anything suspicious. @ttuegel Do you have any suggestions?

**Comment by dtzWill** [comment]
I'm seeing what I believe is the same bug-- although in my case it happens:

* with sandbox enabled
* on CentOS 7

In particular I'm seeing behavior where the following works on NixOS (tested on local laptop and various servers running 18.03) but fails to find the libraries for `uic` on the CentOS box:

(sorry for the beast expression, it "grew" while investigating haha)
```
$ nix build '(let pkgs = import (fetchTarball https://github.com/NixOS/nixpkgs/archive/e0d6edddd7f3df2cecbe24c527f8dc5286564235.tar.gz) {}; in with pkgs; runCommand "sandbox-test" { buildInputs = [ qt5.qtbase ]; } "(echo \"find /:\"; find / || :; echo \"env:\"; env; echo \"LD_DEBUG=all uic --help\"; LD_DEBUG=all uic --help) >& $out")' --option builders ""
```

I've posted the outputs in this gist; https://gist.github.com/2623162b72cbe451dea7e9fa8844834c

The full logs are a bit hefty, the most immediately relevant bits are the `LD_DEBUG=all` portion, which I've split off for easier inspection on the web:

* non-NixOS, fails: https://gist.githubusercontent.com/dtzWill/2623162b72cbe451dea7e9fa8844834c/raw/7723b9547a2718f9ac3d8eeb081205ac3f836925/qtbase-uic-LD_DEBUG.log
* NixOS, succeeds: https://gist.githubusercontent.com/dtzWill/2623162b72cbe451dea7e9fa8844834c/raw/7723b9547a2718f9ac3d8eeb081205ac3f836925/qtbase-uic-local-LD_DEBUG.log (warning 5+MB, sorry :))

As these show, for **some** reason the loader skips the library when it finds it (in the failure case) while the same path is where the loader succeeds otherwise.

Not sure what might cause that, but hopefully this is helpful.  And the same issue as OP :).

**Comment by dtzWill** [comment]
Follow-up:

On my system as well, the problem appears specific to 5.10-- using 5.9 seems to work?

```
$ nix build '(let pkgs = import (fetchTarball https://github.com/NixOS/nixpkgs/archive/e0d6edddd7f3df2cecbe24c527f8dc5286564235.tar.gz) {}; in with pkgs; runCommand "sandbox-test" { buildInputs = [ qt510.qtbase ];  } "(LD_DEBUG=all uic --help || :;) |& tee $out")' -o qt510-ld_debug
$ nix build '(let pkgs = import (fetchTarball https://github.com/NixOS/nixpkgs/archive/e0d6edddd7f3df2cecbe24c527f8dc5286564235.tar.gz) {}; in with pkgs; runCommand "sandbox-test" { buildInputs = [ qt59.qtbase ];  } "(LD_DEBUG=all uic --help || :;) |& tee $out")' -o qt59-ld_debug
```

The former fails to find the qtcore library, the latter seems to work as expected.

I'm poking at strace/ltrace, nothing stands out just yet.  LMK if there's anything I can try to help sort this out!

**Comment by dtzWill** [comment]
According to [this post on the Arch Linux forum](https://bbs.archlinux.org/viewtopic.php?pid=1755257#p1755257) qt 5.10 requires kernel support for renameat2 or something?

If so, that could be the problem for me.  I'm not sure of the easiest way to determine if the kernel I'm running supports it, but seems like a reasonable explanation....

Does that explanation fit the problem you're seeing, @knedlsepp ?

**Comment by dtzWill** [comment]
It's pretty lame that no error or debug message is printed in this situation, though :(.  Or maybe it requires other debug options/approaches?

**Comment by dtzWill** [comment]
Specifically: https://github.com/qt/qtbase/blob/5.10/src/corelib/global/minimum-linux_p.h#L76

Hopefully we can disable these without much fuss.   I suppose there's the question of whether disabling their use is detrimental to users running kernels that support them... thoughts on this?

(cc @ttuegel as code owner of qt-5; sorry for the verbose path I took to get to this point :3)

**Comment by knedlsepp** [comment]
Thx for your analysis. I was really out of ideas on how to diagnose this. While I'm not able to try this out in the next few days, it looks like the attached PR would solve the problem. The "lessons learned" tag-scan is also a great idea.

**Comment by ttuegel** [comment]
It looks like this was addressed in a pull request, but please re-open if this issue persists in newer releases.
