### ISSUE TITLE
Mark INZIU as deprecated.

### ISSUE THREAD

**Issue by be5invis** [NixOS/nixpkgs#39551]
Hi @ChengCat 
Could you please note that Inziu is already deprecated and it is **replaced** by Sarasa Gothic/Sarasa Mono?
Yours Sincerely,
Belleve

**Comment by ChengCat** [comment]
This has been discussed here: https://github.com/NixOS/nixpkgs/pull/39477#discussion_r184034263. Due to stability reasons, I need Inziu Iosevka for myself at least for now, and it may also be helpful to others.

Just out of curiosity, why you want a font to be deprecated? I suppose different fonts have different styles, and could be useful in difference cases.

**Comment by be5invis** [comment]
Because I lost its building system (after an PC replace).
If you want to keep that please mirror its files to GitHub.

**Comment by ChengCat** [comment]
I am sorry to hear that. I'll do the mirroring work tomorrow.

**Comment by xeji** [comment]
closing after font was removed
