### ISSUE TITLE
EC2 instance root partition should fill all the available space

### ISSUE THREAD

**Issue by mightybyte** [NixOS/nixpkgs#39589]
## Issue description

When I create an EC2 instance with a large initial filesystem size, the actual partitions don't fill the space.  It's also pretty cumbersome to resize the partition, so this ends up being a pretty painful problem since `/nix` rapidly fills up.  This is similar to issue #22211, but I'm creating a separate issue because I think fixing it to work with whatever initial size you give it is a better overall fix.

### Steps to reproduce

Create an instance (I used m5.2xlarge) with the 17.09 AMI with a larger amount of initial storage (say, 10 gigs or more).

**Comment by jshcmpbll** [comment]
Cross posting from #22211

For my teams configuration we are seeing the boot disk size automatically grow from the snapshot size of 3gb to our configured EBS size of 40gb

Here are some dmesg logs:

```
[    0.534760] GPT:Alternate GPT header not at the end of the disk.
[    1.810611] stage-1-init: [Fri Apr 28 20:53:29 UTC 2023] checking /dev/disk/by-label/nixos...
[    1.813888] stage-1-init: [Fri Apr 28 20:53:29 UTC 2023] [fsck.ext4 (1) -- /mnt-root/] fsck.ext4 -a /dev/disk/by-label/nixos
[    2.149314] stage-1-init: [Fri Apr 28 20:53:30 UTC 2023] resizing /dev/disk/by-label/nixos...
[   31.169463] stage-1-init: [Fri Apr 28 20:53:59 UTC 2023] Resizing the filesystem on /dev/disk/by-label/nixos to 10423291 (4k) blocks.
[   31.170949] stage-1-init: [Fri Apr 28 20:53:59 UTC 2023] The filesystem on /dev/disk/by-label/nixos is now 10423291 (4k) blocks long.
[   31.171956] stage-1-init: [Fri Apr 28 20:53:59 UTC 2023] mounting /dev/disk/by-label/nixos on /...
```

Looks like `autoResize` is configured by default in the amazon image module and working as expected:
https://github.com/NixOS/nixpkgs/blob/358a179550508bf2dafdf1657a94b7f65d91c4bf/nixos/modules/virtualisation/amazon-image.nix#L35

I think this issue is good to be closed unless you're still having this issue

Thanks @sarcasticadmin for helping with this 🥳

**Comment by sarcasticadmin** [comment]
Going to close this, thanks @jshcmpbll !
