### ISSUE TITLE
fetchgit: support specifying location of public keys for ssh transport

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4004]
Follow up on #1923:

Currently using ssh urls for fetchgit results into:

```

Could not create directory '/var/empty/.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Could not create directory '/var/empty/.ssh'.
Host key verification failed.
```

Maybe fetchgit should grow an extra parameters?

**Comment by Profpatsch** [comment]
@domenkozar is this fixed?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.

**Comment by zimbatm** [comment]
@Profpatsch this is still an issue. You can repro by running nix-build against https://gist.github.com/anonymous/fb9353cabf8dd9fecd28

**Comment by Gabriel439** [comment]
I just ran into this issue.  For other people who have this same issue, you can work around it by using the alternative `HTTPS` url that Github provides for cloning (i.e. `https://github.com/your-name/your-project.git`).  If you are prompted to authenticate when cloning via the HTTPS url, follow these instructions, which include how to deal with two-factor authentication:

* [Cloning with HTTPS URLs ](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended)

**Comment by Gabriel439** [comment]
Okay, so I think this is basically solved by `fetchgitPrivate`, although I'm going to suggest two possible enhancements to the implementation of `fetchgitPrivate`.

First, using a variation on the gist that @zimbatm linked to, I can successfully build the repository by replacing `fetchgit` with `fetchgitPrivate` (and fixing the `sha256` field):

```nix
# default.nix

{ pkgs ? import <nixpkgs> {} }:

pkgs.buildRubyGem rec {
  src = pkgs.fetchgitPrivate {
    url = "git@github.com:flori/json.git";
    rev = "80e8213ce940005a1c7314793d39a0c4cc786821";
    sha256 = "0ki6a4vnccb86rmssbc5x3d067zvkhyi6y973068hz81q0rjqf8a";
  };
  gemName = "json";
  version = "1.8.3";
  sha256 = "1nsby6ry8l9xg3yw4adlhk2pnc7i0h0rznvcss4vk3v74qg0k8lc";
}
```

... and supplying the appropriate SSH config file and `SSH_AUTH_SOCK` on the command line (since that is how `fetchgitPrivate` is configured to work):

```haskell
nix-build default.nix -I ssh-config-file=/path/to/.ssh/config -I ssh-auth-sock=$SSH_AUTH_SOCK
```

So that alone is probably enough to mark this issue closed, but I'd like to also suggest two improvements to `fetchgitPrivate` to reduce the need to supply these parameters on the command line:

* Use `impureEnvVars` to automatically inherit the `SSH_AUTH_SOCK` from the user's environment
* Supply the configuration file directly as a `nix` argument

This would involve simplifying `pkgs/build-support/fetchgit/private.nix` to this:

```nix
{ fetchgit, writeScript, openssh, stdenv }:

sshConfigFile: fetchGitArgs:

derivation ((fetchgit fetchGitArgs).drvAttrs // {
  impureEnvVars = [ "SSH_AUTH_SOCK" ];

  GIT_SSH = writeScript "fetchgit-ssh" ''
    #! ${stdenv.shell}
    exec -a ssh ${openssh}/bin/ssh -F ${sshConfigFile} "$@"
  '';
})
```

... and then you'd just provide the `~/.ssh/config` file in `nix`:

```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.buildRubyGem rec {
  src = pkgs.fetchgitPrivate /path/to/.ssh/config {
    url = "git@github.com:flori/json.git";
    rev = "80e8213ce940005a1c7314793d39a0c4cc786821";
    sha256 = "0ki6a4vnccb86rmssbc5x3d067zvkhyi6y973068hz81q0rjqf8a";
  };
  gemName = "json";
  version = "1.8.3";
  sha256 = "1nsby6ry8l9xg3yw4adlhk2pnc7i0h0rznvcss4vk3v74qg0k8lc";
}
```

... and now you can run the build command without any command line arguments:

```bash
$ nix-build default.nix
```

Would people be okay with that proposed change?

**Comment by Profpatsch** [comment]
> src = pkgs.fetchgitPrivate /path/to/.ssh/config {

You mean it’s okay if that’s an argument, since `fetchgitPrivate` will only be used from private nix files?

**Comment by Gabriel439** [comment]
Yeah, the `.ssh/config` file can be made a private file if it contains any secrets, although it shouldn't need to.  The impure `SSH_AUTH_SOCK` environment variable forwarded from your environment actually does the authentication for you using your ambient `ssh` agent.  For example, in my case the `.ssh/config` file was just empty so I could pass `writeText "ssh-config" ""` if I wanted to.

**Comment by Gabriel439** [comment]
Actually, I've come to the conclusion that the current behavior of `fetchgitPrivate` is the ideal behavior and requires no modification

The thing that convinced me that the current behavior is the way to go was getting a package to work with `hydra`.  The only way to securely provision a secret to a `hydra` build is via the Nix search path.

Also, the `SSH_AUTH_SOCK` argument is not necessary (and won't even work in some cases like remote builds).  Another approach is to provide an `ssh-config-file` with an `IdentityFile` line, such as this:

```
StrictHostKeyChecking No
UserKnownHostsFile /dev/null
IdentityFile /path/to/.ssh/id_rsa
```

... and then supply the path to that on the Nix path like this:

```bash
$ nix-build example.nix -I ssh-config-file=path/to/above/config
```

So the conclusion I came to is that this issue is solved by `fetchgitPrivate` but could perhaps use better documentation on how to correctly use it in various circumstances (like local vs remote builds, `hydra`, `nixops`, etc.).

**Comment by zimbatm** [comment]
The only issue with `fetchgitPrivate` is that tools like nix-prefetch-git don't make a distinction between private and public repos and then the packaging tools like npm2nix, bundix, ... also don't make the distinction. Is there a heuristic that could be used to make that distinction possible?

**Comment by k0001** [comment]
Actually, there seems to be an issue with this. If `nix.useSandbox` (formerly known as `nix.useChroot`) is set, `ssh-config-file` won't be reachable from the build process, and building by will fail with something like `Can't open user config file /path/to/ssh-config-file: No such file or directory`. As soon as `nix.useSandbox` is disabled, everything work as @Gabriel439 described. 

To make this work, I think that `fetchgitPrivate` needs to take `ssh-config-file` and `ssh-auth-sock` as input parameters for overriding the current behavior. I'll try this now and submit a pull-request afterwards if it works.

**Comment by Gabriel439** [comment]
@k0001 There is one reason that you might want to still preserve the old ability to provide `ssh-config-file` via the `NIX_PATH` which is that it's the only way that seems to reliably work with Hydra (since Hydra seems to only let you configure the `NIX_PATH` when customizing an expression to build)

**Comment by k0001** [comment]
@Gabriel439 just so that we are on the same page: Are you using NixOps to deploy your Hydra instance? If so, how do you manage the deployment and permissions of the `ssh-config-file` file specified through Hydra, as well as the deployment and permissions of the associated `IdentityFile`?

**Comment by Gabriel439** [comment]
@k0001 I don't use `nixops` to deploy the Hydra instance.  I just use `nixos` directly

**Comment by matthewbauer** [comment]
I may open another issue for this- but I am having a similar problem with ```fetchcvs```. Basically, ssh refuses to authenticate anoncvs without ```/var/empty/.ssh/known_hosts```. I wonder if anyone has any work arounds for this? (Currently all of the CVS stuff is fetched through pserver but that can be hit or miss).

**Comment by yegortimoshenko** [comment]
This is resolved now (there is `builtins.fetchGit`, [`fetch-git`](https://github.com/target/nix-fetchers/tree/master/fetch-git), and `fetchgitPrivate` that all support this).

@matthewbauer: I've opened #41814.

**Comment by yegortimoshenko** [comment]
@jokogr You could pass it via NIX_PATH:

```
nix-build -I ssh-config-file=/path/to/ssh/config
```

**Comment by jokogr** [comment]
@yegortimoshenko: as @k0001 mentioned, `/path/to/ssh/config` is inaccessible in a sandbox, i.e. I get an error like "No such file". Are you using a special path to override this?

**Comment by yegortimoshenko** [comment]
You can specify additional paths available in sandbox via `extra-sandbox-paths` in `/etc/nix/nix.conf` or `nix.sandboxPaths` NixOS option.

**Comment by CMCDragonkai** [comment]
> This is resolved now (there is builtins.fetchGit, fetch-git, and fetchgitPrivate that all support this).

@yegortimoshenko Did you mean that `fetchGit` supports using the same `ssh-config-file` and `ssh-auth-sock` parameters on `NIX_PATH` that is supported by `fetchgitPrivate`? If so, what's the point of using `fetchgitPrivate` then?

**Comment by robinp** [comment]
For posterity, I had no luck trying to pass 'ssh-config-file' to the Hydra jobset. Instead I moved the config file itself to its standard location for Hydra (`/var/lib/hydra/.ssh/config`) and it got caught up fine.

Tip: you can more interactively test the evaluation by executing `hydra-eval-jobset proj jobsetname` as the `hydra` user. You can directly observe what happens over git/ssh then.

**Comment by Gabriella439** [comment]
Documenting for posterity that `fetchgitPrivate` was removed in favor of `builtins.fetchGit`.  See: https://github.com/NixOS/nixpkgs/commit/e578b8499f9e49441d9761875659381f95975fee

**Comment by shlok** [comment]
I can confirm that `fetchGit` currently (Nix 2.13.3) works fine for grabbing private repositories. Here is a working example:

```
builtins.fetchGit {
  url = "git@github.com:user/repo.git";
  rev = "your commit hash";
}
```
