### ISSUE TITLE
NULL devices?

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#40374]
## Issue description
```
[   21.729762] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
[   21.743078] (NULL device *): hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
```

Also, https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1666653. 

Yes, it's "just a warning", but I think we can all agree that we do not want to see such things.

### Steps to reproduce
Unknown

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.18, NixOS, 18.03.git.45cd609 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - channels(coretemp): `"nixos-18.03.132192.ce0d9d638de"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by xeji** [comment]
This is a warning generated by the kernel because a deprecated interface is still used - it is actually used in many places in the kernel: https://github.com/torvalds/linux/search?q=hwmon_device_register&unscoped_q=hwmon_device_register

It is apparently harmless, and nothing that we can (or want to) fix in nixpkgs. Please feel free to discuss this issue with the linux kernel project.

**Comment by coretemp** [comment]
Who is this "we" that you are talking about?
