### ISSUE TITLE
unibilium can't find ncurses terminfo dir

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#40404]
## Issue description
I am investigating terminfo related problems (my neovim leaks ANSI code everywhere even though terminfo is loaded and looks correct), The fault might lie in unibilium I am not sure (might not pick up TERMINFO_DIRS correctly at buildtime/runtime ?).

while doing so I wanted to run https://github.com/mauke/unibilium/blob/e3b16d6219ca1cb92d98b1d9cc416b49a3ac468e/Makefile#L36 but the program does 
ncursesw6-config --terminfo-dirs which returns the ncurses embedded terminfo instead of the system ones.

Ncurses has these flags:
```
  --with-terminfo-dirs=XXX specify list of terminfo directories (default: DATADIR/terminfo)
  --with-default-terminfo-dir=DIR default terminfo directory (default: DATADIR/terminfo)
```
I wonder if these should point to /etc/terminfo instead (my current $TERMINFO_DIRS is `/home/teto/.nix-profile/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo:/etc/profiles/per-user/teto/share/terminfo`)    ? or prepend it at least ? 
Right now programs rely on the environment variable TERMINFO_DIRS, such a modification could make terminfo discovery more reliable.

@wkennington

**Comment by teto** [comment]
No custom terminfo files.
You are right about the flag meaning it's used as a default when there is no runtime variable. I am thinking `nix-shell --pure`

To be more explicit: unibililium requests the terminfo_dirs from ncurses and if not available defaults to `"/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/usr/lib/terminfo:/usr/local/share/terminfo:/usr/local/lib/terminfo"` which has no intersection with the actual nixos values
`/home/teto/.nix-profile/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo:/etc/profiles/per-user/teto/share/terminfo` (in fact one: /etc/terminfo points to /run/current-system/sw/share/terminfo).

As $TERMINFO_DIRS is correctly set, in principle everything is ok but as nix tends to be explict about paths, I thought it would be good to be explicit here too and make programs more robust to the loss of the environment variable TERMINFO_DIRS.

**Comment by layus** [comment]
As a side note, this may be a good time to split the terminfo database in a separate ncurses output. A `terminfo` output would be consistent with urxvt. Now unibilium would only depend on the terminfo database at runtime, and not other ncurses files.

@teto I think the issue was that ncurses does not accept /etc/terminfo as --with-terminfo-dirs or --with-default-terminfo-dir because it tries to install its files there, or some other issue. You are much welcome to investigate this further, an I would gladly review your patches.

You need to be _very_ careful about hard-coded defaults, because you need to support various non-nixos platforms where they may not exist. 
In this case, it is safer to make ncurses depend on a known set of self-provided terminfo files than to take chances finding none in /etc/terminfo. Plus, there is nearly no terminfo files that are outside of the default terminfo database. The only know use-case for this is urxvt.
