### ISSUE TITLE
cmake is out of date

### ISSUE THREAD

**Issue by kballard** [NixOS/nixpkgs#40751]
cmake in nixpkgs is 3.10.2. This is over 2 months old. The current version is 3.11.2.

This is a problem for me as I'm trying to use cmake to build something that requires 3.11.0 or later.

/cc @ttuegel

**Comment by kballard** [comment]
#40800 was merged a day ago, but isn't showing up on nixpkgs-unstable yet. It looks like it was merged into staging rather than trunk. How long does it normally take for package updates like this to make it to trunk?

**Comment by ttuegel** [comment]
I merged it into `staging` rather than `master` because it causes ~1,000 rebuilds, so if it was merged into `master` it would block the unstable channel from updating. After `staging` rebuilds, I will merge it into `master` and then after a small rebuild, it will appear automatically in the unstable channel.

**Comment by kballard** [comment]
Thanks for the explanation!
