### ISSUE TITLE
pcsx2: GS plugin failed to open

### ISSUE THREAD

**Issue by va1entin** [NixOS/nixpkgs#40834]
## Issue description
pcsx2 does not boot images, because it fails with the error "GS plugin failed to open. Your computer may have insufficient resources or incompatible hardware/drivers."
Tried with both release-18.03 and master.
Also it logs errors, when started:
![image](https://user-images.githubusercontent.com/31535155/40283313-6fef2720-5c7c-11e8-83e6-0b74b97abe5f.png)

I made a screenshot because my Plasma regularly crashed when clicking anything in the log window. Had to reboot the system after, regular methods to restart Plasma didn't work.

My console output when starting PCSX2 looks as follows:
<pre>/nix/store/bqjqqq2fibhvfbz3gv3i6wbw0f9cv81d-bash-4.4-p19/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Interface is initializing.  Entering Pcsx2App::OnInit!
Applying operating system default language...
SetLanguage: 'English (U.S.)' [en_US] is not supported by the operating system
Command line parsing...
Command line parsed!
</pre>

@hrdinka 

### Steps to reproduce
Boot any image with PCSX2

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.03.132405.ee80654b526 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.1`
 - channels(root): `"nixos-18.03.132405.ee80654b526, nixos-unstable-18.09pre137305.d91caac6c3e, old-17.09"`
 - channels(val): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by hrdinka** [comment]
Hi @va1entin!

Thanks for your report. The log window seems to be bugged somehow. It looks like the whole UI does only refresh when the log window does. So it's best to just close it.

First make sure that PCSX2 found all of its plugins. The plugin selection screen should show valid entries for each plugin. If it can't find one it will set it to `null`.

Each game needs different plugin settings. You'll get that error message with some configurations/games (mostly when the software renderer would use up to many system resources). Open up the GS plugin settings page and make sure that the correct video card and depending on the game the software or hardware renderer is selected. There are many videos on youtube about this exact error. Here is one that shows it on Windows. It's not that different on NixOS—just play around with the settings. Some games will work with the software renderer, some with the hardware renderer and some on both or with artifacts on one or the other. Each game is different, performance and visual quality will differ depending on the game and your settings.

https://www.youtube.com/watch?v=Y8mPypEW9s8

The PCSX2 Wiki is a good entry point to find common problems and configurations/workarounds for nearly every PS2 game out there. Just don't give up to early, I got every game running with after some time of tweaking… With all of that set, you should be ready to play :)

**Comment by va1entin** [comment]
@hrdinka Sorry for not commenting the last few days, I've been too busy. Thanks for your comment, I'll certainly reply this weekend. :)

**Comment by va1entin** [comment]
Alright @hrdinka  here's what I'm observing now.

When I start PCSX2 the following windows opens
![screenshot_20180610_204410](https://user-images.githubusercontent.com/31535155/41205197-10900bae-6cef-11e8-81ae-610a92fc70f1.png)

The path `/nix/store/92...` does not exist.

Afterwards it tells me that it might not function properly due to plugins missing and offers me to open the plugin menu, which looks as follows:

![image](https://user-images.githubusercontent.com/31535155/41205205-37e7fcd4-6cef-11e8-8c2e-0691e8bac4a6.png)

i can open a dialog by clicking on "Configure" next to the GS plugin entry.

**Comment by hrdinka** [comment]
Hi @va1entin,

every time PCSX2 is updated its path will change (due how nix works). That is why it won't be able to find its libraries. It seems that it has corrected the error for you. The wrong path above is different from the one used below, that's why the path chosen below exists.

You can change the base path to something that won't change due updates. Depending on how you've installed the program you can locate it somewhere here:

- /home/USER/.nix-profile/lib/pcsx2
- /run/current-system/sw/lib/pcsx2

Besides that, does it finally work for you?

**Comment by va1entin** [comment]
The debug window, which automatically opens when I start PCSX2, still crashes it from time to time. The error message regarding missing plugins at `/nix/store/92...` above still opens on every start up and the folder it complains about doesn't change.

When I select an ISO and a BIOS with the correct version, it works though :+1: 
I still have some graphical issues, but I can play the game itself. So I guess PCSX2 just didn't fix the plugin path itself, when I submitted this issue :)

Do you want me to keep it open to track the error/debug message behaviour described above?

**Comment by va1entin** [comment]
The debug window, which automatically opens when I start PCSX2, still crashes it from time to time. The error message regarding missing plugins at `/nix/store/92...` above still opens on every start up and the folder it complains about doesn't change.

When I select an ISO and a BIOS with the correct version, it works though :+1: 
I still have some graphical issues (some eyes are just black spheres, some textures distorted), but I can play the game itself. So I guess PCSX2 just didn't fix the plugin path itself, when I submitted this issue :)

Do you want me to keep it open to track the error/debug message behaviour described above?

**Comment by va1entin** [comment]
Another thing I noticed is that I don't see most of the navigation elements such as checkboxes:
![image](https://user-images.githubusercontent.com/31535155/41308960-9acbee16-6e7d-11e8-83cf-cff848a0caa6.png)

**Comment by hrdinka** [comment]
@va1entin 

Have you changed the login path to a non changing path as I suggested above? This should make the debug window go away.

The UI problems as well as all log errors in you first post `…GDK_IS_PIXBUF…` are all non PCSX2/NixOS related. They occur because you have not setup your GTK2 theme & engines. I assume that you use KDE. It might have setup GTK3 themes for you, but not or only partially GTK2. There are many examples online how to do this. KDE might help with this too. Usually you have to install a GTK2 theming engine (through nix) and a GTK2 theme that makes use of the installed engine. Further make sure that hicolor_icon_theme is installed, this might explain the missing icons.

GTK2 is really dated now, it isn't that well supported by WMs any more and has many issues like being unable to work correctly with HIDPI screens. I always struggle with these applications as well…

**Comment by hrdinka** [comment]
Hi @kuamit5516!

This repo is about NixOS & nix a package manager, package repo and operating system. It looks like you're not a nix/NixOS user and have downloaded PCSX2 from their official website. We are not related to PCSX2 at all other than packaging their application for our OS. This is therefore the wrong place to ask for help.

The correct repo for PCSX2 is https://github.com/PCSX2/pcsx2

However I think it's best to try to solve this yourself before posting their or alternatively ask on their forums and not on github. It looks like the only problem you have is that you are missing needed libraries. PCSX2 is 32bit only, when your OS is a 64bit installation you need to install all of these libraries in their 32bit version.

The PCSX2 project explains how this is done in this document:
https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux#32-bit-libraries-on-x86_64

Since everyone who wants to use PCSX2 has to install these libraries you will find many examples and tutorials online on how to do this for your OS—in case the above link does not help.

**Comment by Ekleog** [comment]
(triage) All the problems in this issue appear solved (at least no one pointed since a few months ago that @hrdinka's answers didn't work, so…?). Maybe this can be closed? :)

**Comment by hrdinka** [comment]
@Ekleog Yep, you're right. I already forgot about this issue.

Closing this for now. Please reopen if any errors persist.

**Comment by rain-1** [comment]
I have this problem. GS plugin can't open. Do you know how to fix it?

**Comment by hrdinka** [comment]
@rain-1 Have you tried the steps above? If it's the same problem https://github.com/NixOS/nixpkgs/issues/40834#issuecomment-396078642 will fix it.

**Comment by rain-1** [comment]
@hrdinka Thank you for pointing me to that comment. I have tried it out now but it did not affect this problem, I got the same error.

I had a look in strace and I saw this (my username is nix)

```
[pid  3615] write(5, "\tBinding   GS: /home/nix/.nix-pr"..., 66 <unfinished ...>
[pid  3634] <... mprotect resumed> )    = 0
[pid  3615] <... write resumed> )       = 66
[pid  3615] stat64("/home/nix/.nix-profile/lib/pcsx2/libGSdx-1.0.0.so",  <unfinished ...>
[pid  3634] mprotect(0xf0d96000, 4096, PROT_READ|PROT_WRITE <unfinished ...>
[pid  3615] <... stat64 resumed> {st_mode=S_IFREG|0555, st_size=1375880, ...}) = 0
[pid  3634] <... mprotect resumed> )    = 0
[pid  3615] openat(AT_FDCWD, "/home/nix/.nix-profile/lib/pcsx2/libGSdx-1.0.0.so", O_RDONLY|O_CLOEXEC) = 11
[pid  3615] read(11, "\177ELF\1\1\1\3\0\0\0\0\0\0\0\0\3\0\3\0\1\0\0\0`\224\0\0004\0\0\0"..., 512) = 512
[pid  3615] fstat64(11, {st_mode=S_IFREG|0555, st_size=1375880, ...}) = 0
[pid  3634] mprotect(0xf0d97000, 4096, PROT_READ|PROT_WRITE <unfinished ...>
[pid  3615] mmap2(NULL, 7143048, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 11, 0 <unfinished ...>
```

but I am not sure how to interpret it.

**Comment by rain-1** [comment]
Yes that file exists, and I did provide a BIOS.

**Comment by seisdr** [comment]
Well can I use some opengl32
