### ISSUE TITLE
Failing nixos.tests.keymap.dvp test blocks channel update

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#41538]
According to https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.keymap.dvp.x86_64-linux, the test `nixos:trunk-combined:nixos.tests.keymap.dvp.x86_64-linux` has failed consistently for 2+ weeks and is blocking an update of the `nixos-unstable` channel. Could someone who knows what this code is doing please have a look?

@aszlig, maybe?

**Comment by aszlig** [comment]
Oh, I haven't been notified about the [changes](https://github.com/NixOS/nixpkgs/commit/84a6e18947fe961e97173f031318cd6111a43949) of the keymap tests :unamused:

So before the individual keys were pressed one after another, but now they're pressed in one go. If the machine is on high load and the key presses happen too quickly, not all of the key presses would be recognized. Note that the actual key presses are handled in HMP, so the guest could miss keyboard interrupts.

Cc: @xeji

**Comment by xeji** [comment]
@aszlig sorry I forgot to notify you.
The tests were changed because, at that time, the tests doing one keypress after another were frequently failing under high load so the channel was blocked - pretty much the same situation as it appears now. The move to doing all keypresses in one go seemed to improve the situation for about a month - there were still failures but less frequently than before.
Then things got worse again recently. Don't know why, could be all kinds of factors.

Anyway, I think going back to the previous strategy is unlikely to fix this, so we'll have to find another way. As a temporary fix I will make the keymap tests non-blocking until we have a reliable solution.

**Comment by abathur** [comment]
This test was renamed to `keymap.dvorak-programmer` in #119096. 

Closing since https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.keymap.dvorak-programmer.x86_64-linux/all suggests this has been running fairly clean recently (the last true failure I see is a little over 7 months ago).

Happy to reopen if I'm overreaching :)
