### ISSUE TITLE
Nautilus segfaults with deja-dup installed

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#42176]
When `deja-dup` is in `environment.systemPackages`, Nautilus does not start because of missing deja-dup GSettings schemas. One possible solution is hard-coding the schema path akin to the [GNOME extensions](https://github.com/NixOS/nixpkgs/pull/36410). Personally, I like this since it will allow us to get rid of the wrappers, but it makes the expressions less clean and maintainable.

The problem also occurs with other plug-ins and extensions or even other GTK applications so we should converge on a solution.

Eventually, we might want to lobby with GLib crowd for less global system state (or at least a single function so the patches could be simpler).

cc @hedning, @tiramiseb, @yegortimoshenko

**Comment by yegortimoshenko** [comment]
I probably misunderstand the issue, can't this be resolved similarly to `giDiscoverSelf`?

https://github.com/NixOS/nixpkgs/blob/804285f589ded484b530750dd1ec03b9052bcdac/pkgs/development/libraries/gobject-introspection/setup-hook.sh#L15-L19

**Comment by jtojnar** [comment]
@yegortimoshenko The issue is there is no wrapper (the extension is a `.so` file).

**Comment by hedning** [comment]
Hmm, so stepping back a bit and trying to understand the situation. What's the rationale for installing schemas in a non-standard location (which seems to be the underlying issue we keep bumping into)?

Wouldn't it be easier to install the `.xml` files to `share/glib-2.0/schemas/` and deal with `gschemas.compiled` the same way we deal with eg. `icons-theme.cache`?

I'm guessing the trouble is user installs, where https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/system-path.nix#L133 isn't run? Though the fix for that would seem to be to run those hooks when creating user profiles.

**Comment by jtojnar** [comment]
One thing to consider is running applications from `nix-shell`, they would still need compiled schemas. Maybe we could compile them in a `shellHook`.

For installed applications, your proposal makes sense.
