### ISSUE TITLE
Window manager 'gnome3' not found

### ISSUE THREAD

**Issue by glasserc** [NixOS/nixpkgs#42602]
## Issue description

Trying to start gnome3 from an SDDM display manager fails. The SDDM display never goes away and the display appears "locked up".

The following messages show up in `.xsession-errors`:

```
Failure: Module initialization failed
Warning: The unit file, source configuration file or drop-ins of graphical-session.target changed on disk. Run 'systemctl --user daemon-reload' to reload units.
/nix/store/9xvnmjyr0bkgd0p9w864gl4m53ya5h8q-xsession: Window manager 'gnome3' not found.
dbus-update-activation-environment: warning: error sending to systemd: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.systemd1 exited with status 1
```

I do not believe this is the same as #24298 because I do not see any error message about `gsd-datetime` segfaulting.

### Steps to reproduce

My [configuration.nix](https://github.com/NixOS/nixpkgs/files/2135381/configuration.nix.txt) with SDDM enabled.

## Technical details

nix-info:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.51, NixOS, 18.09pre143771.a8c71037e04 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(ethan): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
`Window manager 'gnome3' not found.` is expected. Since `sessionType=gnome3`, both `windowManager` and `desktopManager` will be set to `gnome3`:

https://github.com/NixOS/nixpkgs/blob/1b3111e4361fdc337390448b22b4271437e7efc6/nixos/modules/services/x11/display-managers/default.nix#L144-L147

When we cannot find `gnome3` WM, we will try the DE and succeed. This code is really terrible so we want to replace it: https://github.com/NixOS/nixpkgs/issues/39871

----

I do think this is the same bug as https://github.com/NixOS/nixpkgs/issues/24298, the error might just have changed slightly. For now, I recommend using a different DM (GDM, lightdm or SLiM).

**Comment by glasserc** [comment]
OK, I'll close this as a duplicate of #24298.
