### ISSUE TITLE
rename dino

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#42872]
## Issue description

I noticed dino is named "dino-im" in most repositorys.

https://repology.org/metapackage/dino-im/versions

There is a software named dino with the last release from 2011. It seams to be dead. I'm not sure if we would package it ever.

http://dino.nongnu.org/
https://repology.org/metapackage/dino/versions

What do you think?

cc @mic92

**Comment by Mic92** [comment]
We do not have the other dino thing packaged. dino-im seems to be only used by debian/ubuntu maintainers. The project calls itself dino: https://github.com/dino/dino/ 
I don't think debian always picks the name that makes the most sense. If you install docker on debian, you will get a strange window manager thing instead of container manager that is used by way more people. I do not have numbers, but dino the instance messenger has more users then this other applications no ones uses. So I would give it higher priority.

**Comment by davidak** [comment]
That's reasonable. Thanks for your opinion!
