### ISSUE TITLE
Discord autostart issue

### ISSUE THREAD

**Issue by SagnikSRHUSE** [NixOS/nixpkgs#43109]
There is an option within Discord:
![screenshot_20180706_150224](https://user-images.githubusercontent.com/16162562/42371623-9d35423e-812d-11e8-8c89-8660757ab92f.png)

It is unticked now, but when it's ticked, it created a discord-stable.desktop file in /home/user/.config/autostart/

```[Desktop Entry]
Type=Application
Exec=/nix/store/v3ikh3higgz5ynia5l3a7srx6g2zqr1y-discord-0.0.5/opt/discord/.Discord-wrapped
Hidden=false
NoDisplay=false
Name=.Discord-wrapped
Icon=/nix/store/v3ikh3higgz5ynia5l3a7srx6g2zqr1y-discord-0.0.5/opt/discord/discord.png
Comment=Text and voice chat for gamers.
X-GNOME-Autostart-enabled=true
```
However, this does NOT work as intended, i.e., to boot Discord on system boot. Also, you can't run Discord by clicking on the concerned .desktop file.

But the autostart option in KDE works perfectly with Discord, except that it displays an error as referenced in #43108

**Comment by dotlambda** [comment]
That's probably because it's trying to run `.Discord-wrapped` instead of `Discord`. There's nothing we can do about that; the wrapper is needed to setup the path correctly, see (https://github.com/NixOS/nixpkgs/blob/bab973a28b3d8e565300e798cc43e63fb2bf2a0c/pkgs/applications/networking/instant-messengers/discord/default.nix#L37).
You might want to ask upstream to fix this: https://support.discordapp.com/hc/en-us/articles/115000465492

**Comment by pSub** [comment]
Are we really waiting for upstream? In other words: Is there a bug report upstream? If so, please link it here.

**Comment by dotlambda** [comment]
@SagnikSRHUSE Did you report the bug upstream?

**Comment by dotlambda** [comment]
Closing because of missing reaction from OP.
