### ISSUE TITLE
makeDesktopItem: key "Encoding" in group "Desktop Entry" is deprecated

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#4319]
With a derivation containing:

```
desktopItem = makeDesktopItem {
  name = "Pharo";
  exec = "${executable-name}";
  icon = "pharo";
  comment = "Launcher for Pharo distributions";
  desktopName = "Pharo";
  genericName = "Pharo";
  categories = "Development;";
};
```

The desktop file validator shows a warning:

```bash
$ desktop-file-validate result/share/applications/Pharo.desktop 
result/share/applications/Pharo.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
```

**Comment by vcunat** [comment]
Is this fixed now?

**Comment by DamienCassou** [comment]
@vcunat I don't know, but this issue has been opened for 9 months and nobody cared to even answer. So I closed it. Please reopen if you think this should stay open (but the project already has 571 opened issues so I think closing some does not harm).

**Comment by lethalman** [comment]
@DamienCassou doesn't make sense what you are saying. That's a kiddish behavior, sorry to say. There are several reasons that an issue is not even answered:

1) Nobody cares
2) Most developers has overseen this (like myself)
3) Since it's low-prio, we probably expect a simple PR to fix this

All the above doesn't mean this is not an issue and should be closed. Also once you noted this bug you shouldn't not be in charge of closing it, because it's still an issue, regardless of whether you care about it or not anymore.

So unless you are sure this can be closed, keep it open, thanks.

**Comment by vcunat** [comment]
I have a fix, which I'll push soon.

**Comment by vcunat** [comment]
Yes, please, keep such issues open as long as they're reasonable. It isn't uncommon to have decade-old tickets in open-source, and just closing them unfixed seems to help nothing.

**Comment by DamienCassou** [comment]
Ok for me. Sorry for that. Just want to let you know that in some open-source communities, when nobody cares, the issue is manually (and sometimes automatically) closed.

**Comment by vcunat** [comment]
Really? I guess it depends on the meaning of "nobody cares".

**Comment by lethalman** [comment]
@DamienCassou this is a different community perhaps
