### ISSUE TITLE
fetchgit: add support for `keybase://` protocol

### ISSUE THREAD

**Issue by kalbasit** [NixOS/nixpkgs#43196]
## Issue description
I have a repo hosted with [keybase](https://keybase.io/blog/encrypted-git-for-everyone) that I'd like to install with Nix. I tried using `fetchgit` with the `keybase://` protocol and I got the error `fatal: Unable to find remote helper for 'keybase'`. I tried adding `keybase` to the `buildInputs` but that did not help.

There's also the question of how to pass the Keybase credentials?

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.4-1-zen, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(root): `"nixpkgs-18.09pre144572.9720833743f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by orivej** [comment]
`git-remote-keybase` is provided by `kbfs`, and it has to be a built input of `fetchgit` rather than a built input of your project. Try adding this to `all-packages.nix`:
```
  fetchkeybase = arg: (fetchgit arg).overrideAttrs (attrs: {
    nativeBuildInputs = attrs.nativeBuildInputs ++ [ kbfs ];
  });
```
Using `fetchkeybase` instead of `fetchgit` now fails with:
```
git-remote-keybase error: (1) stat /homeless-shelter/.local/share/keybase: no such file or directory
```
How would you like to provide your keybase key to `fetchkeybase`?

Alternatively you can manually clone your keybase repo without Nix, and use the local path as the `src` attribute.

**Comment by kalbasit** [comment]
I see. Perhaps it’s easier to clone myself like you suggested, and use fetchgit with `file://` to install it given a set revision. Thanks! I'll try this out.

**Comment by kalbasit** [comment]
fetching from local worked, for those trying the same, you need to make sure the `url` attribute of `fetchgit` must be a path (aka no quotes, no `file://`).
