### ISSUE TITLE
How do I configure Cassandra's data/log/etc directories?

### ISSUE THREAD

**Issue by dhruvio** [NixOS/nixpkgs#43296]
I am trying to run Cassandra on my NixOS computer after installing it with either `nix-env -i cassandra` or `nix-shell -p cassandra`. However, when I try to run `cassandra`, it states errors like the following:

```
ERROR 16:45:11 Has no permission to create directory /nix/store/jf03qrz58i7dmnkj0ajh1s1d86q61ws5-cassandra-3.0.9/bin/../data/data
```

This is happening because Cassandra's installation directory in `/nix/store` is immutable, and can not be written to. I receive a similar error message when Cassandra tries to write its logs. To configure Cassandra's storage and log directories to be located outside the Nix store, we need to modify configuration files inside the Nix store. However, these config files are also immutable given they have been installed to `/nix/store/{HASH}-cassandra-3.0.9/conf`.

Is it possible to use Cassandra after installing it with `nix-env` or `nix-shell`? Is there a way to configure it without requiring mutability in the Nix store? My hope is to be able to quickly start an ephemeral cassandra process in development so I can manually test things locally using `cqlsh` without much effort/headache.

Thanks

**Comment by danbst** [comment]
In short, no. Either you use cassandra NixOS module, or patch packages.

How would package patch look like? Essentially it should:
- provide cassandra wrapper, which selects some directory (home directory), probably in `~/.cassandra`. User may override this directory via env var
- links (or copies) cassandra "data" files there
- copies config file if it doesn't exist. Skips copy otherwise (to not overwrite user config)
- performs `cd ~/.cassandra`
- launches ./bin/cassandra

One more way is to do it yourself:
- `mkdir ~/.cassandra && cp -r $(nix-build '<nixpkgs>' -A cassandra) ~/.cassandra`
- `sudo chattr -i -R ~/.cassandra && sudo chown -R $USER ~/.cassandra && sudo chmod +w ~/.cassandra`

And one more way is to abuse `nix-shell`. Instead of running `nix-shell -p cassandra`, run 
```
$ mkdir /tmp/cassandra_build
$ cd /tmp/cassandra_build
$ rm -rf ~/.cassandra
$ nix-shell '<nixpkgs>' -A cassandra
nix-shell$ unpackPhase && cd apache-cassandra-*
nix-shell$ export out=~/.cassandra
nix-shell$ eval "$installPhase"
nix-shell$ exit
$ ~/.cassandra/bin/cassandra
```
This same should work with Tomcat, Grakn and other Java bundles.

**Comment by dhruvio** [comment]
Thank you.
