### ISSUE TITLE
Xfce with I3 doesn't display properly

### ISSUE THREAD

**Issue by mtetreault** [NixOS/nixpkgs#43714]
## Issue description
If I configure xfce with `noDesktop = false`. I have I3+xfce that display and I also have another xfce window on top of that.

However, if I set `noDesktop = true`. I only have I3 displayed.

To be quite honest, I have not clue on where to start to debug this.

### Steps to reproduce
```
  services.xserver = {
    enable = true;
    autorun = true;
 
    windowManager = {
      default = "i3";
      i3.enable = true;
    };

    desktopManager = {
      default = "xfce";
      xfce = {
        enable = true;
        enableXfwm = false;
        noDesktop = true;
      };
    };

    displayManager = {
      lightdm.enable = true;
      sessionCommands = ''
        ${pkgs.networkmanagerapplet}/bin/nm-applet &
        '';
    };
  };
```
## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.55, NixOS, 18.03.132865.411cc559c05 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Narice** [comment]
I know you probably moved on but here is how I did it, you can kill the desktop in the settings of xfce and tell xfce to never start or restart it.
Then you will only have the panel and i3

the noDesktop should only uninstall the desktop but currently it uninstalls also the panel which defeats the purpose in my opinion x)

**Comment by lobre** [comment]
It has been a long time since this issue was created but from what I understand, the `noDesktop` was implemented to have a different window manager on top of xfce. And in this case, the `xfce4-panel` is **not started**.

https://github.com/NixOS/nixpkgs/blob/91a22f76cd1716f9d0149e8a5c68424bb691de15/nixos/modules/services/x11/desktop-managers/xfce.nix#L130

Maybe starting the panel should have its own option so that people have the choice to **not start** the overall desktop but still start the panel. As of today, using xfce with i3 while using xfce panel is not a supported behaviour.

The only option is to use the i3 panel (or a custom one such as polybar). I am not sure that it defeats the purpose totally as you still benefit from the whole desktop environment such as sound, network applets, the launcher or the notification panel. Some people want this and still use i3status (and that's why it was implemented like this).

Also more information here in the section "Using as a desktop manager and not a window manager":

https://nixos.wiki/wiki/Xfce

**Comment by bobby285271** [comment]
The is an excludePackages option since https://github.com/NixOS/nixpkgs/commit/1c5e23c40559f0711b3a5b5ee94c230a5c852683
