### ISSUE TITLE
libdbus calls the wrong dbus-launch binary (was gnome-keyring-daemon[1898]: couldn't connect to dbus session bus)

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#4414]
``` journalctl
Oct 07 17:48:26 luz3 gnome-keyring-daemon[1898]: couldn't connect to dbus session bus: /nix/store/rz76dzpmrnh36dm1brdanfmyx6j02k1y-dbus-libs-1.8.6/bin/dbus-launch terminated abnormally without any error message
```

@lethalman is that something you've heard about?

**Comment by arno01** [comment]
I just woke up and got the same nightmare...
can't connect to wireless using standard means in gnome3 due to this error

**Comment by lethalman** [comment]
@arno01 seems random, I think if you reboot it works.

**Comment by arno01** [comment]
@lethalman doesn't look like... I've just tried a clean install in qemu and here what I've got again

```bash
[root@nixos-qemu:~]# journalctl -b |grep -i gnome-keyr
Feb 08 18:30:25 nixos-qemu gnome-keyring-daemon[1542]: GLib-GIO: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Feb 08 18:30:25 nixos-qemu gnome-keyring-daemon[1542]: couldn't connect to dbus session bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Feb 08 18:30:25 nixos-qemu gnome-keyring-daemon[1542]: couldn't connect to dbus session bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Feb 08 18:30:26 nixos-qemu gnome-keyring-daemon[1542]: The GPG agent was already initialized
Feb 08 18:30:26 nixos-qemu gnome-keyring-daemon[1542]: couldn't connect to dbus session bus: /nix/store/lnpz29inqp7fn4pra8r4d75xp9sllxax-dbus-libs-1.8.12/bin/dbus-launch terminated abnormally without any error message
Feb 08 18:30:26 nixos-qemu gnome-keyring-daemon[1542]: The SSH agent was already initialized
Feb 08 18:30:26 nixos-qemu gnome-keyring-daemon[1542]: The PKCS#11 component was already initialized

[root@nixos-qemu:~]# date
Sun Feb  8 18:31:10 CET 2015

[root@nixos-qemu:~]# nixos-version 
14.12.374.61adf9e (Caterpillar)
```


`/etc/nixos/configuration.nix`
```
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/sda";

  networking.hostName = "nixos-qemu";
  networking.hostId = "0b1bb429";

  services.openssh.enable = true;

  services.xserver.enable = true;
  services.xserver.layout = "us";

  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
}
```


### Checking the error message further
```bash
[root@nixos-qemu:~]# ls -la /nix/store/lnpz29inqp7fn4pra8r4d75xp9sllxax-dbus-libs-1.8.12/bin/dbus-launch
ls: cannot access /nix/store/lnpz29inqp7fn4pra8r4d75xp9sllxax-dbus-libs-1.8.12/bin/dbus-launch: No such file or directory

[root@nixos-qemu:~]# ls -la /nix/store/*/bin/dbus-launch
lrwxrwxrwx 1 root nixbld    77 Jan  1  1970 /nix/store/12bbnls9xci5bvhikp4dwcs8x89pd282-system-path/bin/dbus-launch -> /nix/store/qa5hh3mfca7cmqzwy9psg2k7pibkg5sx-dbus-tools-1.8.12/bin/dbus-launch
lrwxrwxrwx 1 root nixbld    77 Jan  1  1970 /nix/store/pfggm4anqpns2cd7qhy20awx1b0dz86h-system-path/bin/dbus-launch -> /nix/store/qa5hh3mfca7cmqzwy9psg2k7pibkg5sx-dbus-tools-1.8.12/bin/dbus-launch
-r-xr-xr-x 1 root root   30680 Jan  1  1970 /nix/store/qa5hh3mfca7cmqzwy9psg2k7pibkg5sx-dbus-tools-1.8.12/bin/dbus-launch
```

`gnome-keyring-daemon` is looking for the `dbus-launch` in the `dbus-libs` instead of `dbus-tools`.

either pkg-config argument has to be changed at some point of `gnome-keyring-daemon` build or maybe to play with `BuildInputs` to include `dbus.libs` there for the `nixpkgs/pkgs/desktops/gnome-3/3.12/core/gnome-keyring/default.nix`  (the same way as it is in `nixpkgs/pkgs/desktops/gnome-2/desktop/gnome-keyring/default.nix`)


Pitty it takes so much time to compile every dependency of `gnome-keyring-daemon`... is there a way to leverage ccache with nix ? ( I checked in IRC logs, seems jack_c managed to use it, see http://nixos.org/irc/logs/log.20121203 )

**Comment by lethalman** [comment]
The problem is in libdbus, cc @vcunat @edolstra :
```
$ strings /nix/store/p264m3p92v87d5rkdd3jf3s6kpwcnjmd-dbus-libs-1.8.12/lib/libdbus-1.so.3.8.9|grep dbus-launch
/nix/store/p264m3p92v87d5rkdd3jf3s6kpwcnjmd-dbus-libs-1.8.12/bin/dbus-launch
```

Problem: dbus-tools depends on dbus-libs, but then dbus-libs should depend on dbus-tools because it calls dbus-launch :S

**Comment by lethalman** [comment]
A possible solution is to include dbus-launch also in libs. And leave dbus-tools still with only binaries.

**Comment by vcunat** [comment]
It isn't much like that one, as dbus is a single package upstream artificially split by us. It used to be needed before systemd-212 ee9c068b, but I guess we should completely collapse it now. (Some splitting could be done afterwards with multiple outputs.)

The sizes are ~0.5MB for -libs and ~1MB for -tools (containing also the daemon), so that's not too bad. There are some extra build+runtime dependencies in -tools, which might have larger impact.

What do *you*/others think?

**Comment by lethalman** [comment]
Yes I think the main problem is for people not wanting X libs at all costs in their nix store. I wonder how can debian libdbus not depend on dbus-launch: https://packages.debian.org/sid/libdbus-1-3

**Comment by lethalman** [comment]
```
$ strings /lib/x86_64-linux-gnu/libdbus-1.so.3.7.6|grep dbus-launch
//bin/dbus-launch
```

Of course... if you install dbus tools then it works, otherwise it doesn't. Don't like this very much honestly.

**Comment by vcunat** [comment]
> I'm also thinking whether it's correct that libdbus is calling dbus-launch in this context.

Yes, that surprised me, as I thought dbus-launch is just some thin command-line wrapper around libdbus.

**Comment by vcunat** [comment]
The X11 dependency can be disabled - I see only dbus-launch refers to those, and I have no idea what

**Comment by lethalman** [comment]
X11 is used for autolaunch and it's used by dbus-launch. I wouldn't drop it :) Again, what about adding a new bundled package combining the two so that packages that require libdbus to call dbus-launch can use this package?

**Comment by vcunat** [comment]
I'm don't much like leaving the default libdbus referencing nonexistent dbus-launch.

Maybe it might at least try ``/run/current-system/sw/bin/dbus-launch`` (which exists by default on NixOS). I'm not even sure if for the semantics it's better to launch the system daemon or the version a a package was built against...

**Comment by lethalman** [comment]
You may end up calling a dbus-launch linked against another libdbus that way.

**Comment by vcunat** [comment]
Here I think that shouldn't matter, as dbus is specified even as a *protocol*, so e.g. other implementations than libdbus are used (gdbus etc.). But still, I don't see into (lib)dbus workings, so I'm not sure at all.

**Comment by lethalman** [comment]
Anyway with your suggestion you still need to install dbus tools manually, and if you don't it won't work. Especially for non-nixos.

It's all about those applications that use certain libdbus calls which will run dbus-launch or not. I understand you don't like the idea to keep libdbus broken, but since a long time this is the only issue I've seen.

**Comment by vcunat** [comment]
OK, so the patch above adds ``dbus.combined`` - a version with all within one output. Would you test using the problematic packages with it? (Leaving all else against the usual dbus, only overriding these with ``dbus = dbus.combined;``.)

**Comment by lethalman** [comment]
Ok, well the problematic one is glib :P so it will take some time.

**Comment by vcunat** [comment]
Oh, then I'm much less sure this is a good solution.

**Comment by lethalman** [comment]
Either x11 deps, or use PATH. I don't see many other solutions.

**Comment by DamienCassou** [comment]
What should we do about this issue?

**Comment by Profpatsch** [comment]
triage: what’s the status of this?
