### ISSUE TITLE
Can't pass extra arguments to cabal2nix

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#44377]
## Issue description

`haskell.lib` provides the convenience function `callCabal2nix`. `cabal2nix` has several command-line options and these are supported by `haskellSrc2nix` (used by `callCabal2nix`) via the `extraCabal2nixOptions` argument (see https://github.com/NixOS/nixpkgs/blob/464cf105c630109e19db8d183e229a749c0558db/pkgs/development/haskell-modules/make-package-set.nix#L122). However, there is no way to pass these to `haskellSrc2nix` via `callCabal2nix`.

**Comment by basvandijk** [comment]
Since `callCabal2nix` is defined as a function that takes its arguments individually instead of via an attribute set (i.e. `callCabal2nix = name: src: args: ...`) we can't add an `extraCabal2nixOptions` argument without breaking existing invocations. 

So if we want this we need to add a new function and define `callCabal2nix` in terms of it.

Do you know a good name for it?

**Comment by dhess** [comment]
`callCabal2nix'` ? `callCabal2nixWithOptions` ?

**Comment by basvandijk** [comment]
Thanks, I think `callCabal2nixWithOptions` works. Care to submit a PR?

**Comment by dhess** [comment]
Sure, I'll try to put this together this weekend.

**Comment by dhess** [comment]
Please see #44424
