### ISSUE TITLE
journalctl advertises options it doesn't implement

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#44595]
## Issue description
From `journalctl --help`:
```
Query the journal.

Options:
  -g --grep=PATTERN          Show entries with MESSSAGE matching PATTERN
     --case-sensitive[=BOOL] Force case sensitive or insenstive matching
```

### Steps to reproduce

```
journalctl --grep a -u sshd.service 
```
returns `Compiled without pattern matching support`

Expected response: 
Lines matching `a`.

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.55, NixOS, 18.03.git.d0c868e (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by jtojnar** [comment]
That  should be reported upstream:

The feature is wrapped in `#ifdef`:

https://github.com/systemd/systemd/blob/6f663594bc5ee087cb15175cb691eaebcc45a0a1/src/journal/journalctl.c#L798-L817

but not in the help section:

https://github.com/systemd/systemd/blob/6f663594bc5ee087cb15175cb691eaebcc45a0a1/src/journal/journalctl.c#L322

There are already some conditional options in help so that should not be a problem:

https://github.com/systemd/systemd/blob/6f663594bc5ee087cb15175cb691eaebcc45a0a1/src/journal/journalctl.c#L368-L370

**Comment by coretemp** [comment]
@jtojnar  Why don't we build it with this option enabled?

**Comment by jtojnar** [comment]
We do – at least it works on my NixOS system.

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/39698

**Comment by coretemp** [comment]
OK, so we didn't do it (18.03) and now we do. Good. Shall we just leave this open until upstream has fixed their stuff?

**Comment by jtojnar** [comment]
I would just close this. It is a minor thing that might even be intentional – having `--help` change across builds might be confusing.

**Comment by coretemp** [comment]
There are different use cases for different implementations of `--help`. My main concern is how it works by default on a released version of NixOS, which has been addressed here. 

I would probably have the --help display (this feature is not implemented on this version of the software use --<flag> to enable it when compiling, which in the case of NixOS would display a nix expression to enable it).

Conclusion, I am closing this.
