### ISSUE TITLE
Package request: scuttlebot

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#44647]
In a similar space as IPFS/Dat/BeakerBrowerser/etc: https://scuttlebot.io/

Looks like it's packaged via `npm`...

**Comment by xeji** [comment]
see #43661

**Comment by patrl** [comment]
It's pretty silly to leave both of these open. Can someone close one of them? The recommended process for adding node packages (detailed [here](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/node.section.md)) inevitably leads to a large merge conflict, since `node2nix` must be re-ran on the whole package set, which is presumably why my PR wasn't accepted. 

There's absolutely no reason why `scuttlebot` can't be packaged, so it would be nice to see some progress on this. It would also be nice to know how we're supposed to package node packages, since following the recommended procedure clearly leads to a rejected PR.

**Comment by patrl** [comment]
Anybody out there?

**Comment by xeji** [comment]
Unfortunately I cannot help with packaging node packages (don't know anything about it). But I'll close this issue as requested. @patrl let's leave your PR open, hopefully someone else will be able to help.
