### ISSUE TITLE
modprobe fails trying to access /lib/modules

### ISSUE THREAD

**Issue by pebbleKite** [NixOS/nixpkgs#44976]
## Issue description

I'm trying to get DisplayLink working on unstable NixOS and it fails when `modprobe` tries to access the non-existing `/lib/modules`. It was an previous issue, #5492 that was fixed in 2015, and the workaround of `sudo -E` doesn't help either. 

### Steps to reproduce

1. Add `services.xserver.videoDrivers = ["displayLink"];` to `configuration.nix`
2. `sudo -E nixos-rebuild switch`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.09pre147850.2428f5dda13 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(user): `"nixpkgs"`
 - channels(root): `"nixos-18.09pre140528.e96ec37c008"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

**Comment by dezgeg** [comment]
I think #5492 is a red herring here, because ever since 131fca0a85c6a2f7912061f8f3e57f582fb94f38 and 2abe917f18728d964a52b475edb44d053ab1b4a4 the `MODULE_DIR` mechanism has been removed and replaced with the much more elegant solution of patching kmod itself to search the correct directories (which include BOTH NixOS locations and non-NixOS locations).

**Comment by pebbleKite** [comment]
Indeed the modprobe is irrelevant here.
Thanks!
