### ISSUE TITLE
Visual Studio Code C# Extension cannot find Mono

### ISSUE THREAD

**Issue by billksun** [NixOS/nixpkgs#44999]
## Issue description
After installing the C# extension in Visual Studio Code and launching a C# project, the OmniSharp log will display the following message and error out after a timeout period:

`
/home/bill/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/bin/mono.linux-x86_64: No such file or directory
`

### Steps to reproduce

1. Install `vscode`
2. Install `dotnet-sdk`
3. Install the C# extension from the built-in extension manager
4. Start a C# project
5. Open a .cs file and observe the "No such file or directory" message in the "Output" pane, under  "OmniSharp Log"

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.17.11, NixOS, 18.09pre149044.6afd19e699c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.09pre149044.6afd19e699c"`
 - channels(bill): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by joepie91** [comment]
The error message is a bit misleading; that Mono binary is likely statically compiled against `/lib/ld-linux.so.2` or so, which does not exist on NixOS due to there not being a system-global `/lib`. The "No such file or directory" error you're seeing therefore refers to the *linker* not being found, rather than the binary itself.

Not sure how this would normally be solved in the context of VS Code, though. For stand-alone statically-compiled binaries, the answer is generally "`patchelf` it", but I don't know if that is practical here.

**Comment by Mic92** [comment]
It is possible to also package vscode extension for example: nixpkgs/pkgs/misc/vscode-extensions/cpptools

**Comment by sib-null** [comment]
How do I use `patchelf` to fix this?

**Comment by Mic92** [comment]
You can just add `autoPatchelfHook` in `nativeBuildInputs` and add missing libraries `buildInputs` as `autoPatchelfHook` reports them.

**Comment by Mic92** [comment]
Example: https://github.com/NixOS/nixpkgs/blob/dc02a284bc885a746a902764db243123a1de0bb6/pkgs/applications/audio/reaper/default.nix

**Comment by Mic92** [comment]
To clarify the problem is that it cannot execute the file `/home/bill/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/bin/mono.linux-x86_64` because it's link-loader points to`/lib/ld-linux.so.2`. Patchelf can replace this with the correct link loader instead. It does not mean, that it cannot find the file.

**Comment by billksun** [comment]
Resolved by #57205
