### ISSUE TITLE
networking.firewall.extraCommands is not of mergeable type

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#45024]
## Issue description
`networking.firewall.extraCommands` is of type string, so it cannot be merged. Is this intentional? 

Please consider the mergeable  type `type.lines`. Alternatively, introduce e.g. `networking.firewall.extraComposableCommands`.

### Steps to reproduce
Define networking.firewall.extraCommands in one module and also define it in a different module. 

## Technical details

`18.03`/`master`

**Comment by danbst** [comment]
It is of type `lines`
https://github.com/NixOS/nixpkgs/blob/release-18.03/nixos/modules/services/networking/firewall.nix#L463-L474

The problem you experience is that module system doesn't know in which order to merge your definitions. It won't merge them based on module order, because module order is irrelevant for module system.

What you want is to apply ordering - `mkAfter`, `mkBefore` and generic `mkOrder` to your definitions. Example:

https://github.com/NixOS/nixpkgs/blob/139924308181c0ad1b7b27d1e22e15e25b04f7ba/nixos/modules/services/networking/ssh/sshd.nix#L424

I agree that error description should be more descriptive on how to solve this issue. This issue is known, https://github.com/NixOS/nixpkgs/issues/15747, but nobody have volunteered yet to work on this.

**Comment by coretemp** [comment]
I agree that the file you referenced shows `lines` as the type. 

Why does `man configuration.nix` state it is of type string?

**Comment by dotlambda** [comment]
It states it is of type `strings concatenated with "\n"`. I guess the plural s is enough of an indication that the option can be specified multiple times.
