### ISSUE TITLE
Derivations with dead download links

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#45076]
## Issue description

The following derivations have dead download links in their `src` attribute.

- [x] altermime
- [x]  cowsay
- [x] xfig (src + links to the patches)
- [x] fsg CC @7c6f434c 
- [x] fusesmb
- [x] gen-gs
- [x] fbterm

**Comment by 7c6f434c** [comment]
Marked `fusesmb` as broken — maybe it should be dropped (Samba 3 is also bad)

**Comment by 7c6f434c** [comment]
I cannot find `gengs` in in Nixpkgs. `grep` doesn't help

**Comment by markuskowa** [comment]
Sorry, typo: should read `gens-gs`

**Comment by 7c6f434c** [comment]
Ah, OK

**Comment by 7c6f434c** [comment]
I guess this can be closed now?

**Comment by markuskowa** [comment]
Thanks for the cleanup! It can be closed for now. I reopen it, when needed.

**Comment by 7c6f434c** [comment]
Of course, GitHub notifies about the reopening, but not about the description change, so it looks like a mistake. Writing a reopen-message with the package names could be nice…

**Comment by markuskowa** [comment]
Sorry, for the confusion. I thought the list was obvious. Thanks for fixing!

**Comment by 7c6f434c** [comment]
Well, the problem is about GitHub UI: email update is useless, if I click on notification I first see the bottom of the page with «reopened», because obviously this is the latest update and description change doesn't count… If it behaved like actual issue tracking systems, of course the would be a notification with the new list and everything would be convenient.
