### ISSUE TITLE
Use nix 2.0 commands in nixos-rebuild

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nixpkgs#45595]
## Issue description
It would be great to replace the massive wall of output with the Nix 2.0 progress indicator.

It *looks* relatively straightforward, but does require https://github.com/NixOS/nixpkgs/pull/37693.

**Comment by michaelpj** [comment]
Ugh, and probably https://github.com/NixOS/nix/issues/1930, since most of the uses of `nix-build` rely on the path going to stdout.

**Comment by xeji** [comment]
Won't this make it harder to debug errors during rebuild?

**Comment by bhipple** [comment]
I find the nix 2.0 build almost unusable if you're actually developing (as opposed to just installing packages from Hydra).    While it's true that you can run `nix log` to get the failed output after-the-fact, if you're in an interactive edit-compile-test cycle it's much more natural to get your compiler/test output interactively as it proceeds instead of waiting for it to fail and then having to run a second command once it does.

**Comment by spinus** [comment]
> Won't this make it harder to debug errors during rebuild?

I guess implementing `--verbose` could do the job.

**Comment by samueldr** [comment]
What could happen is build a command for `nix` using the plugin system introduced in nix 2.0, which can have deeper integration within nix, thus hoist up important information as necessary when/if the build fails (hopefully). Instead of having `nixos-rebuild` be a wrapper around the nix ecosystem, the new tooling could integrate more deeply *without being part of `nix` itself*.

Caveat: I do not have any special knowledge, only superficial knowledge about the plugin system, about [as much as described in the manual](https://nixos.org/nix/manual/)

> Nix can now be extended with plugins. See the documentation of the plugin-files option for more details.

> `plugin-files`  
> A list of plugin files to be loaded by Nix. Each of these files will be dlopened by Nix, allowing them to affect execution through static initialization. In particular, these plugins may construct static instances of RegisterPrimOp to add new primops or constants to the expression language, RegisterStoreImplementation to add new store implementations, **RegisterCommand to add new subcommands to the nix command**, and RegisterSetting to add new nix config settings. See the constructors for those types for more details.
> 
> Since these files are loaded into the same address space as Nix itself, they must be DSOs compatible with the instance of Nix running at the time (i.e. compiled against the same headers, not linked to any incompatible libraries). They should not be linked to any Nix libs directly, as those will be available already at load time.
> 
> If an entry in the list is a directory, all files in the directory are loaded as plugins (non-recursively).

**Comment by glittershark** [comment]
this is still important to me

**Comment by Camsbury** [comment]
Seconded!

**Comment by plabadens** [comment]
Still matters to me.

**Comment by solson** [comment]
Still relevant.

**Comment by mohe2015** [comment]
https://asciinema.org/a/sbsZMR0H6s9phBKff8m43a6dh isn't this what this issue means?

**Comment by glittershark** [comment]
> https://asciinema.org/a/sbsZMR0H6s9phBKff8m43a6dh isn't this what this issue means?

definitely is - what's doing that? is that a newer version? (I no longer use nixos-rebuild so I wouldn't know, I switched to a script I wrote myself in part to address this issue)

**Comment by mdevlamynck** [comment]
Using when flakes `nixos-rebuild` uses the new ui. I think this issue is / should be limited to `nixos-rebuild` when not using flakes.

**Comment by lf-** [comment]
Hey, we could fix this today without actually relying on `nix-command`: set `--log-format bar-with-logs` on the existing nix commands. We would want to verify we are of a version that supports that, but that's not a big barrier to be honest.

**Comment by michaelpj** [comment]
As far as I'm concerned, the fact that using it with flakes gets the new UI is good enough for me. I'm going to close this unless someone else cares.
