### ISSUE TITLE
BCC Python 3 Support

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#45619]
## Issue description

Currently bcc appears to only support Python 2 in Nixpkgs, but the docs of bcc seems to support Python 3 as well. Is there a way to make bcc work in python 2 and 3?

**Comment by teto** [comment]
you should move bcc to python-packages.nix so that one can call it with python3Packages.bcc (and keep an alias in all-packages.nix so that it doesn't break user config)

**Comment by dotlambda** [comment]
Yes, it seems like this should be moved to `python-packages.nix` because it is also used as `import bcc`.
You can move the expression to `pkgs/development/python-modules/bcc`, modify it appropriately and call it from `python-packages.nix`.
Then, you should be able to add it to `linuxPackages` like so:
```
bcc = with python3.pkgs; toPythonApplication (bcc.override {
  inherit kernel;
});
```
However, in order to use `pythonPackages.bcc` you'd then probably have to override the kernel to the correct version as well because `pythonPackages` does obviously not differentiate between kernel versions.

**Comment by teto** [comment]
Btw on nixos-unstable at least bcc is configured with python3 :+1: 
```
    bcc = callPackage ../os-specific/linux/bcc {
      python = python3;
    };
```

**Comment by CMCDragonkai** [comment]
@teto That should mean an easy way to do this is to just override it right now to python3. I'm not on unstable, but 18.03.

**Comment by CMCDragonkai** [comment]
I think this is done now on 19.03.

**Comment by tfc** [comment]
I just stumbled upon this. Found the package `pkgs.bcc` but couldn't make it work in a shell with python.

What does work is adding `python3.withPackages (ps: [ (ps.toPythonModule pkgs.bcc) ])` to the shell.

I wonder if adding this call to `pkgs.python3Packages` would be the right thing?

**Comment by CMCDragonkai** [comment]
@tfc no idea right now, I haven't used it since 2019. You might want to figure it out and submit a PR.
