### ISSUE TITLE
ghc-mod shouldn't pull in emacs by default

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#4561]
ghc-mod can happily be used as a library only or with other text editors: pulling in emacs by default seems excessive and I believe it is only to bytecompile the ghc-mod mode, which is again useless if we don't plan to use it with emacs

I wonder if making emacs non-default or splitting ghc-mod into two (with and without emacs) expression would not be a better choice.

cc maintainers: @ocharles @bluescreen303 @kosmikus

**Comment by peti** [comment]
I'm closing this issue because it's been inactive for a couple of months.

The Haskell NG packages set allows for creating a derived version of the normal `ghc-mod` expression`, say `ghc-mod-vim`, that doesn't have `emacs` in its `buildTools` attribute. If anyone is up to the task, please submit a PR with a patch (or re-open this issue, if you care deeply enough).

**Comment by Fuuzetsu** [comment]
I shall re-open because I care; I will try to find time for this, I suspect we can split out the emacs bit into separate package all together.

**Comment by bluescreen303** [comment]
Please just use the multiple-outputs feature instead of creating a separate package.
Or use some `postInstall` trick to remove the emacs reference in the output.

**Comment by Fuuzetsu** [comment]
>Please just use the multiple-outputs feature instead of creating a separate package.

You're most welcome to fix this issue yourself if you have a prefered way of doing it ;)

>Or use some postInstall trick to remove the emacs reference in the output.

This defeats the point of ‘don't pull emacs in at all’ part.

**Comment by bluescreen303** [comment]
I don't find the current behaviour an issue :)

And no it does not defeat the point. It will only be a build-time dependency, so installing `ghc-mod` will no longer pull in emacs

**Comment by peti** [comment]
@bluescreen303, treating build-time dependencies as almost irrelevant doesn't feel quite right. Not everyone can get binaries from Hydra -- so build-time dependencies matter to them. Even those that *can* get binaries from Hydra frequently have to wait for cache to catch up with `master` which can take several days depending on the load, I agree that run-time dependencies matter more in the grand scheme of things, but build-time dependencies matter, too, because people frequently do have to build packages to get them installed on their machine.

**Comment by Fuuzetsu** [comment]
@cocreature

>If the elisp files are preserved anyway, don't you think they should be put in $out/share/emacs/site-lisp so that it can be easily loaded instead of having them in some weird place where you need to search for?

Yes, that's fine with me. 

@bluescreen303 Peter is correct in that build dependencies matter: if I update, say, `Agda` against master, why should I have to rebuild emacs at the same time: in the future I hope to use `Agda` outside of emacs (unthinkable, I know) so I shouldn't have to pull it in. Same with `ghc-mod`: people already use `ghc-mod` with vim so they shouldn't be forced to get fresh emacs too.

**Comment by cocreature** [comment]
So then we need special cases for every package that contains elisp to move it to the right place?

**Comment by Fuuzetsu** [comment]
Special case for every package where the ELisp is not the main bit. Honestly, there aren't that many packages which also ship ELisp so it should be easy to do by hand.

**Comment by gridaphobe** [comment]
@Fuuzetsu we have a pattern in the new `emacsPackagesNg` where we pull the ELisp directly from the base package, e.g. https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/emacs-packages.nix#L453-L459.

So all that needs to be done is to tell the main `ghc-mod` builder (and others) to skip the ELisp.

**Comment by Profpatsch** [comment]
(triage) what’s the status?
