### ISSUE TITLE
Enable iwd support in networkmanager build

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#45762]
## Issue description

Networkmanager has support for iwd (the iNet wireless daemon).
I suggest passing --with-iwd to the configure script, to enable support for it.

The next step might be to make a convenient option to use iwd with networkmanager, which inserts
 ''
[device]
wifi.backend=iwd
''
into the config. I would consider that an optional goody however.

**Comment by Mic92** [comment]
I would say for most wifi networks `iwd` should be faster then wpa_supplicant. I have not tested it in combination with network-manager. There might be a few enterprise wifis (WPA-EAP) that might not work yet, because it is not possible to match subdomains when verifying the radius server (domain-suffix-match) - This was the case for my university (eduroam).
Nevertheless iwd would be an optional feature.

**Comment by jtojnar** [comment]
I thought about this when working on the NM expressions but decided against it for now, since the iwd support is still marked as experimental.

Another thing to consider would be closure size – most people would probably still only use `wpa_supplicant`, do we want to add another dependency that does the same thing (not even completely) and will not ever be used?

**Comment by Mic92** [comment]
Fair concern.

**Comment by Mic92** [comment]
Would enabling the `iwd` backend mean that iwd becomes a runtime dependency or is it a library that is added?

**Comment by xaverdh** [comment]
Ok I compiled with iwd, an it indeed increases the closure size by ~60MB. I guess its an issue.

By the way, for some reason I also had to manually set
`systemd.services.iwd.wantedBy = [ "multi-user.target" ]`
in my config. Otherwise the iwd service would not start on boot.
I don't quite understand why that is necessary, since the iwd.service file
does specify multi-user.target. Still somehow it was not linked in multi-user.target.wants until I added that to my config...

**Comment by xaverdh** [comment]
Edit: I take back the closure size part, I digged a bit deeper and for some reason the version I compiled with iwd support pulls in a newer version of polkit (which depends on a vastly newer and larger spidermonkey). This is responsible for the increase in closure size and probably unrelated.

**Comment by xaverdh** [comment]
@Mic92 As I understand it, --with-iwd turns iwd into an (optional) runtime dependency. You can switch the backends at runtime.

**Comment by colemickens** [comment]
Would it be agreeable if it were an option to the nix package as well? So that you could avoid even compiling it in unless the user opts in? I'd like to give `iwd` and `NetworkManager` a whirl to help provide feedback.

**Comment by jtojnar** [comment]
Sure, that would be fine.

**Comment by xaverdh** [comment]
Fixed on master with b0537770d9564cc7337d1ef4c976c54e1679028e
