### ISSUE TITLE
Vivaldi browser (chromium) unable to use pepperFlash and widevine plugins

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#45947]
Hey there!

## Issue description
See title: I am unable to watch anything on twitch.tv (flash) or netflix/amazon (widevine) on the chromium-based vivaldi browser.

### Steps to reproduce
- Install vivaldi package
- add
```
  programs.chromium.enable = true;
  nixpkgs.config = {
    allowUnfree = true;
    chromium = {
      enablePepperFlash = true;
      enablePepperPDF = true;
      enableWideVine = true;
    };
  };
```
to /etc/nixos/configuration.nix.
- try to watch anything on twitch.tv or netflix/amazon.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.133185.a960b87ac21 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Cheers!

**Comment by pinage404** [comment]
There is a package called `vivaldi-ffmpeg-codecs` but i don't know how to run it

**Comment by betaboon** [comment]
i have it packaged and working locally, just have to find the time to clean it up and put it into a PR

**Comment by emilylange** [comment]
I don't think there is anything actionable left.

Both `vivaldi` and `chromium` had major DRM package refactors/improvements since this issue has been opened in 2018.

Additionally, `pepperFlash` and `enablePepperPDF` have long been removed from nixpkgs.

And I am genuinely confused why this issue talks about `vivaldi` but then continues on to use `programs.chromium` and `chromium` options in `nixpkgs.config` (?).

Closing.
