### ISSUE TITLE
package update required: Datadog version 6 

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#46142]
## Issue description
@rvl  Version 6.3 (or even newer) is available.

**Comment by domenkozar** [comment]
I'm working on this.

**Comment by domenkozar** [comment]
@rvl do you know how to package live process collection? I opened https://github.com/DataDog/datadog-process-agent/issues/182

**Comment by rvl** [comment]
Hi! I didn't even know that feature existed.

I can't really work it out.

I think the process collection is meant to be built into `cmd/agent` rather than be a separate program.
There is a doc which alludes to enabling certain features in the agent: [docs/dev/agent_build.md](https://github.com/DataDog/datadog-agent/blob/master/docs/dev/agent_build.md).

It could maybe be a missing dependency because I ended up having to set up `deps.nix` manually.

**Comment by coretemp** [comment]
The following looks like a packaging error:

`/nix/store/n9mmkgs929wz5gb45czz541k9h3mg9qy-datadog-agent-6.1.4-bin/bin/agent status` returns:

```
    process
    -------
      Core Check Loader:
        Check process not found in Catalog
        
      Python Check Loader:
        No module named process
```
