### ISSUE TITLE
Provide builder or tool for Electron

### ISSUE THREAD

**Issue by boomshroom** [NixOS/nixpkgs#46382]
With the popularity of Electron growing, there should be a standard tool for building Electron projects. There is the `node2nix` project which helps with building the applications, but it doesn't know about Electron and Electron can't find the packages that `node2nix` installs.

From what I can tell, the only Electron apps available in nixpkgs are Atom and `nyalas-mail-bin`, and both have very long custom build commands.

Let's work to get Electron apps on NixOS! This includes VSCode, Discord, and many others!

**Comment by matthewbauer** [comment]
Related to: https://github.com/NixOS/nixpkgs/issues/17073

**Comment by abathur** [comment]
Slight aside to the main concern of electron's own challenges. This may be misguided as I only stumbled on this while looking into packaging an Electron app for use on both NixOS/macOS and lack much sense of the pressures shaping the expressions in existing packages.

I see some repetitious work in packages already producing desktop apps for both platforms, which makes me think there may be one or a few missing abstractions/patterns between mkDerivation and something I can imagine the Electron-app-builder sitting atop neatly. An Electron builder might be an ideal time to iron out those patterns/abstractions (before the current patterns spread further...), especially since I imagine Electron apps are a large share of the in-demand cross-platform GUI apps.

**Comment by CMCDragonkai** [comment]
@justinwoo Why is it called `atomEnv`? Shouldn't this be `electronEnv`?

**Comment by disassembler** [comment]
Given I don't think any work has been done on in this yet, I think it's too later for this to be part of 19.09. Bumping to 20.03.

**Comment by trusktr** [comment]
I have a similar problem, but for me it is about development of electron apps. I normally run

```
$ npm install
...
$ npm run build
...
$ ./node_modules/.bin/electron ./dist/main.js
```

in my projects, but this results in the `ENOENT` error as described in my [forum post](https://discourse.nixos.org/t/running-node-electron-app-gives-enoent-error-in-nixos/5590).

I wonder how to work on electron projects locally, where each one may have a different version of `electron` normally installed with `npm install` at the root of the project.

**Comment by wmertens** [comment]
the problem is that the npm module pulls in a binary during installation, and force-building it would take a very long time.

Electron is far from the only npm module with this problem. I wonder if we can create a wrapper that detects updated node modules at startup, and scans them for binaries that aren't using the Nix ELF loader, and patches them to use the correct loader and libraries.

For binary packages in nixpkgs there's an automatic patchelf script that does this, but no idea how to call it from outside a builder.

As for detecting updated modules, how about touching each module directory to be 1970 and then doing a quick scan on node startup for changed directories? That should catch freshly installed modules.

**Comment by ericdallo** [comment]
I would like to add a new [YoutubeMusicDesktop](https://github.com/ytmdesktop/ytmdesktop) for nixpkgs using `node2nix` but I receive the error when installing `electron`  where it needs to use the internet on the build :/

**Comment by jraygauthier** [comment]
#86169 might be of interest. It packages a non trivial application from sources:  using node2nix + some discussions about what can eventually be done using `electron-builder` with regards to properly support both linux and darwin.

**Comment by Sohalt** [comment]
Still relevant

**Comment by CMCDragonkai** [comment]
The discussion about electron-forge here is relevant for any electron ecosystem for Nix: https://github.com/NixOS/nixpkgs/pull/115230

**Comment by CMCDragonkai** [comment]
We built a template repository for building electron apps with Nix here: https://github.com/MatrixAI/TypeScript-Demo-Electron

**Comment by dustinlacewell** [comment]
Not stale... It's 4 years later, but still badly needed.

**Comment by fetsorn** [comment]
Yet another electron nix template here: https://github.com/fetsorn/electron-react-esm-nix

**Comment by YarekTyshchenko** [comment]
Ouch, atom got deprecated and removed

**Comment by SuperSandro2000** [comment]
The situation described in the original issue is no longer the case and this issue doesn't apply anymore.

**Comment by doronbehar** [comment]
@SuperSandro2000 just for the record, `buildNpmPackage` is the solution?

**Comment by YarekTyshchenko** [comment]
Its still showing up in search. It would be good to just plop a link to whatever replaced atomEnv, so people aren't stranded here

**Comment by FliegendeWurst** [comment]
> Its still showing up in search. It would be good to just plop a link to whatever replaced atomEnv, so people aren't stranded here

atomEnv usages were replaced in this PR: https://github.com/NixOS/nixpkgs/pull/258440

**Comment by SuperSandro2000** [comment]
You shouldn't be using atomEnv or any replacement at all but the compiled/bin electron from nixpkgs. The only exception I know to this is vscode which uses a fork.

> @SuperSandro2000 just for the record, `buildNpmPackage` is the solution?

or mkYarnPackage or anything similar.

> From what I can tell, the only Electron apps available in nixpkgs are Atom and nyalas-mail-bin, and both have very long custom build commands.

This no longer helds true. Almost all electron apps we have have pretty short and standard phases.
