### ISSUE TITLE
Test all nix expressions where applicable

### ISSUE THREAD

**Issue by Chiiruno** [NixOS/nixpkgs#46632]
## Issue description
While the system we have right now is good for contributing, I think each new nix expression should have a test in `nixos/tests` written along with it in each new PR.
We should do this retroactively where possible for all currently existing packages too.
This way, we can ensure everything works with hydra, and be alerted quickly for broken, but successfully built expressions that may not be actively maintained and (user) tested anymore.

Would it be possible to change the policy in [Contributing](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) to do this?
The flow I see is this:
1. Make new expression for program X
2. Test locally to ensure it works
3. Make test in nixos/tests for it so hydra can do this automatically
4. Submit PR after everything fits [Contributing](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Is this a good idea, something we should implement? I see more benefits that drawbacks.

**Comment by Chiiruno** [comment]
This will also be really great for stable releases, since if implemented in full, we can ensure all packages are at least minimally tested.

**Comment by jtojnar** [comment]
Some packages offer installed tests https://github.com/NixOS/nixpkgs/issues/34987

**Comment by 7c6f434c** [comment]
>While the system we have right now is good for contributing, I think each new nix expression should have a test in `nixos/tests` written along with it in each new PR.

NixOS tests for simple things are currently very frustrating to debug, because the overhead of an empty NixOS test is larger than the runtime of a non-NixOS-test LibreOffice functional test.

And naive approaches to non-NixOS-based tests got rejected because launching DBus and X requires a minor duplication of functionality (and so it was rejected).

Installed tests shipped with packages come pre-debugged (hopefully), so it should be less of a problem there. Of course, some might depend on network access, but that should be easy to detect and block the coresponding tests.

So if you want to see more NixOS tests, your best bet probably includes something about a NixOS profile with minimal boot time. Maybe even with some code to boot it in a Nix build sandbox (used as a container).
