### ISSUE TITLE
NixOS Jellyfish artwork

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#46915]
## Issue description

A friend of mine created some sketches for ongoing NixOS Jellyfish release
If you like the idea, it can be elaborated for desktop backgrounds, boot time logo, t-shirt, etc

----

![jf](https://user-images.githubusercontent.com/508305/45781395-5cca4c00-bc4f-11e8-8c68-20b938c40b87.png)

**Comment by vcunat** [comment]
I do like the picture aesthetically, but I can see only very loose connection to NixOS (its logo), even the lambdas are oriented the other way than on the logo...

Also /cc @mogorman (author of past release artwork).

**Comment by mogorman** [comment]
I will upload the work I did for this release by friday and update the store. i did it a while back but never cleaned it up, but clearly its time.

**Comment by coretemp** [comment]
I have never understood why people want to have art for an operating system personally. I mean, I am not going to stop you (nor can I), but you are essentially creating more work for me, because all it does it take up space for our purposes. 

I am aware of such things as "But distrowatch.com needs a logo and new screenshots". It's just that I do not believe that our target market cares about such things.

**Comment by mogorman** [comment]
![image](https://user-images.githubusercontent.com/64710/45883713-db260b80-bd7f-11e8-96ab-a1bdcbb4ffa9.png)
https://www.redbubble.com/people/mogorman/works/34062374-nixos-18-09-jellyfish

**Comment by mogorman** [comment]
@coretemp it isn't a big deal and i don't see how it takes up much time. it also has raised hundreds of dollars for the foundation at this point and will continue to do so.

**Comment by vcunat** [comment]
This one reminds me of USS Enterprise, though it's a bit far-fetched :-)
