### ISSUE TITLE
containers-restart_networking test fails

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#47210]
## Issue description
Reported in #47183 -- couldn't find another relevant issue.
The test stopped working after https://github.com/NixOS/nixpkgs/pull/30994 07e0c0e0a2f237639600f2a0d62f6eac748b1e6e

First failing run:
https://hydra.nixos.org/build/63112069

It appears that the veth is no longer properly associated with the bridge after reconfiguration.

### Steps to reproduce
```
nix-build '<nixpkgs/nixos/tests/containers-restart_networking.nix>'
```

**Comment by xeji** [comment]
During reconfiguration the `br0` bridge interface is destroyed and then recreated with the same name but a new interface id (while the container network namespace is unchanged):

Initial:
```
client# 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
client#     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
client# 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
client#     link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
client# 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
client#     link/ether 52:54:00:12:01:01 brd ff:ff:ff:ff:ff:ff
client# 4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
client#     link/ether b6:40:cc:8b:3b:25 brd ff:ff:ff:ff:ff:ff
client# 5: vb-webserver@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP mode DEFAULT group default qlen 1000
client#     link/ether b6:40:cc:8b:3b:25 brd ff:ff:ff:ff:ff:ff link-netnsid 0

```

After switching config:

```

client# 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
client#     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
client# 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
client#     link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
client# 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UP mode DEFAULT group default
qlen 1000
client#     link/ether 52:54:00:12:01:01 brd ff:ff:ff:ff:ff:ff
client# 5: vb-webserver@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
client#     link/ether b6:40:cc:8b:3b:25 brd ff:ff:ff:ff:ff:ff link-netnsid 0
client# 6: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
client#     link/ether 52:54:00:12:01:01 brd ff:ff:ff:ff:ff:ff

```

**Comment by xeji** [comment]
I wonder if we should just let `systemd-networkd` manage container networking. It is supposed to work pretty much out of the box with `systemd-nspawn` containers.

**Comment by xeji** [comment]
Here's what happens in terms of systemd units:

1. `switch-to-configuration` restarts `network-addresses-br0.service` (makes sense)
2. stop `network-addresses-br0.service` -> stop `network-setup.service` due to the `partOf` relationship introduced in 07e0c0e0a2f237639600f2a0d62f6eac748b1e6e.
3. stop `network-setup.service` -> stop `br0-netdev.service` due to a (correct) dependency.
4. stopping `br0-netdev.service` removes the `br0` interface despite the container veth is still associated with it.

**Comment by xeji** [comment]
I don't understand step 2. Why restart the entire networking setup because one address has changed? But we can't just revert 07e0c0e0a2f237639600f2a0d62f6eac748b1e6e because that it fixed a nixops bug https://github.com/NixOS/nixops/issues/640 unrelated to bridge interfaces.

As a hack, we could skip deleting the bridge if a container veth is still associated with it.
