### ISSUE TITLE
Wireshark is broken on 18.03

### ISSUE THREAD

**Issue by arianvp** [NixOS/nixpkgs#47404]
### Steps to reproduce

```

[arian@t430s:~]$ nix run nixpkgs.wireshark
[arian@t430s:~]$ wireshark 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted


```

## Technical details

```

[arian@t430s:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.133188.8b92a4e6004 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133188.8b92a4e6004"`
 - channels(arian): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

**Comment by xeji** [comment]
Does it work when installed via `nix-env` or in the system-wide `configuration.nix` ? 

It's a well known limitation of Qt applications in NixOS that they often don't work in nix-shell or  nix run, because Qt apps load plugins and search the environment at runtime. It's a bit contrary to nix philosophy but at the moment there doesn't seem to be a better solution.

**Comment by xeji** [comment]
Reference: https://nixos.org/nixpkgs/manual/#sec-language-qt

**Comment by arianvp** [comment]
It works with `nix-env`

**Comment by xeji** [comment]
This can be annoying, I've run into it many times. Unfortunately it's a limitation we'll have to accept for now, sorry about that. I'll close this issue.
