### ISSUE TITLE
emacs: evil-collection not working

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#47993]
## Issue description

So, a bit of background: evil-collection wants a variable `evil-wants-integration` set to nil before evil (not evil-collection!) is loaded via `(require 'evil)`. However, even if my emacs init file is empty except:

```
(setq evil-wants-integration nil)
(require 'evil)
(require 'evil-collection)
```

still, a message pops up warning me that `evil-wants-integration` was set to nil, but not before initializing evil. Is this an artifact of the way emacs is packaged in nixpkgs? I'm using `(emacsPackagesNgGen emacs).emacsWithPackages (epkgs: [ ...]))` to construct my emacs.

**Comment by matthewbauer** [comment]
It looks like the var is ```evil-want-integration``` not ```evil-wants-integration```. Does that help at all?

https://github.com/emacs-evil/evil-collection/blob/abc9dd60f71ccc1f24803a12d853f84b4a8b258c/evil-collection.el#L40

**Comment by Ekleog** [comment]
(triage) @pmiddend Did what @matthewbauer suggested help? If not, could you provide a complete `.nix` with the proper `emacsWithPackages` call (as well as the version of nixpkgs you are using, potentially [pinning it](https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs)) so that we could try to reproduce without having to investigate ourselves how to setup evil-collection?

**Comment by pmiddend** [comment]
I can tell you it didn't help at the time. However, I've now switched away from evil and to emacs standard bindings, so I'll close this issue. Sorry for keeping it open for so long.

**Comment by Ekleog** [comment]
No problem, and thank you for your quick answer!
