### ISSUE TITLE
autoPatchelfHook skips position-independent executables

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#48330]
## Issue description

`autoPatchelfHook` determines which executables it should patch via:

```sh
isExecutable() {
    readelf -h "$1" 2> /dev/null | grep -q '^ *Type: *EXEC\>'
}
```

However, PIEs have a type of `DYN`, as in:

```
$ readelf -h result/build-tools/28.0.3/zipalign
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x5350
  Start of program headers:          241664 (bytes into file)
  Start of section headers:          198080 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         32
  Section header string table index: 27
```

Questions:

- Should `autoPatchelfHook` also patch PIEs? An alternative is to just call `autoPatchelfFile` manually, but I'm having trouble finding out how to run it in the correct phase.
- Is there even a reliable way to distinguish between shared libraries and PIEs? I know _in general_, shared libs don't have an `.interp` section, but is this a reliable enough assumption?

cc @aszlig

**Comment by aszlig** [comment]
@tadfisher: Actually, executables can *also* be shared libraries at the same time (eg. `libc.so.6` and I'm doing exactly that in my [recent project](https://github.com/nixcloud/ip2unix) as well), so the only thing that distinguishes them is an `.interp` section (except if statically linked of course). So I guess it's a better idea to just look for `.interp` in `isExecutable` instead of what we currently do. At least if I don't miss something, this should be the most reliable way, after all what we want to do with executables is to patch the `.interp` section.

If nobody else sends a PR in the meantime, I'm going to fix this next week.

As for `autoPatchelfFile` it's a bit more difficult, because it needs to be run after the normal `patchelf` hook, so it might be necessary to add `postPhases`.
