### ISSUE TITLE
Document NixOS configuration profiles

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#48563]
Add a chapter or section in the manual covering configuration profiles.

See discussion at https://github.com/NixOS/nixpkgs/pull/48207 regarding the hardened profile, for example. Discoverability is poor and usage implications unclear, at least in the case of the hardened profile.

A minor annoyance is that I can't just add `meta.doc` to the profile right now, so maybe that could be made to work for profiles.

**Comment by DIzFer** [comment]
Ok, so I've been exercising my docbook and I've now written (copied the profiles, mostly) drafts for almost every module, at the [profiles-documentation branch of my nixpkgs](https://github.com/dizfer/nixpkgs/tree/profiles-documentation). "Almost", because clone-config is a placeholder and qemu-guest isn't even there. But I figured it was as good time as any to ask for input and review before formally submitting it to Nixpkgs.

The Profiles chapter edit slipped into the All Hardware commit. And while I'm at it, I'm not sure I shoved this chapter into the most appropiate part (is "part" the right term for this?).

@joachifm You mentioned having a draft for the hardened section, we may proceed as you wish with that. I tried to be concise, but maybe in excess, so I'd like more eyes on this to confirm it's fine, and I am obviously open to replacing basically all of it with better and more in-depth explanations. This is but a draft, after all.

**Comment by joachifm** [comment]
Cool, thank you for working on this. I'll take a closer look later.

I don't think its necessary to have fully fleshed out docs for all the profiles right away.  To me, the general section you added on profiles would be a good addition in its own right.

Even if it's not ready for integration just yet, opening a PR is probably a good way to attract more feedback/contributions.

**Comment by DIzFer** [comment]
Will do once I fill up those two remaining sections.

**Comment by globin** [comment]
Implemented in #49821
