### ISSUE TITLE
numpy-mkl: undefined symbol: omp_get_num_procs

### ISSUE THREAD

**Issue by costrouc** [NixOS/nixpkgs#48876]
## Issue description

@bhipple @FRidh regarding the latest numpy mkl addition. The `numpy-mkl` in (currently in `staging`) fails when running "python: symbol lookup error: /nix/store/5in4rmhq0829zr675k203zqli8dvn77n-mkl-2019.0.117/lib/libmkl_intel_thread.so: undefined symbol: omp_get_num_procs"

### Steps to reproduce

default.nix
```
{ pkgs ? import <nixpkgs> { config = { allowUnfree = true; }; } }:

let numpy-mkl = pkgs.python3Packages.numpy.override {
      blas = pkgs.mkl;
    };
in
pkgs.mkShell {
  buildInputs = [ numpy-mkl ];

}
```

```
nix-shell --run "python -c 'import numpy as np; a = np.random.random((100, 100)); a.dot(a)'"
```

```
python: symbol lookup error: /nix/store/5in4rmhq0829zr675k203zqli8dvn77n-mkl-2019.0.117/lib/libmkl_intel_thread.so: undefined symbol: omp_get_num_procs
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.70, NixOS, 19.03pre-git (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - nixpkgs: `/nix/store/jaa863bvx6cjdvgbmyzjl3792d1ynpcn-source`
```

**Comment by FRidh** [comment]
Interesting. I did see this with sklearn. It seems we need to improve it in numpy then. If I recall correctly we should add openmp.

**Comment by bhipple** [comment]
Is that not solved by setting openmp in LD_LIBRARY_PATH?  I had considered doing that in `mkl` directly, but ditched that approach in order to make the fixed-output derivation simpler.  There's a comment about it:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/science/math/mkl/default.nix#L3-L13

I could move the binaries themselves to a private derivation in a `let` binding, and then make the actual `mkl` package itself depend on `openmp` with this setupHook if you guys think it'd be preferable.  Doing so would make all of `mkl`'s dependencies "just work", without each package having to futz about with `LD_LIBRARY_PATH`.

**Comment by costrouc** [comment]
I will try setting openmp in the path and see if this fixed it. If anything I wanted to raise this issue because I am sure that future people using numpy, scipy, or scikit-learn mkl will run into this problem. Should we automatically add openmp to the `LD_LIBRARY_PATH` for numpy if mkl is used?

**Comment by bhipple** [comment]
The linked PR fixes your issue, and it gets us very close to passing all of the test cases in `numpy` as well.

**Comment by costrouc** [comment]
@bhipple thanks for your work on this. I am not nearly knowledgeable on this but I appreciate your work. This will be helpful in allowing mkl to be added to many other packages. Which I think could be a big selling point of nix to people.

**Comment by AliRashidnejad** [comment]
I experienced the same issue via dlib installed from conda, in my case re-installing dlib via pip solved the issue
