### ISSUE TITLE
Update R packages

### ISSUE THREAD

**Issue by jabranham** [NixOS/nixpkgs#49105]
It looks like the R packages in https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/r-modules haven't been updated in ~4 months. There have been some large releases since then. Can someone please update them?

Apologies if I misunderstood something. I'm just getting started with nix.

**Comment by pstn** [comment]
Can you give me a list of the most important upgrades and how to test them?

**Comment by jabranham** [comment]
There's something like 13,000 packages on CRAN so providing a full list of "important" upgrades is hard. Nix says that it provides all CRAN packages so I assumed there was a script somewhere ([here?](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/r-modules/generate-r-packages.R)) to update them. 

You can test all R packages by doing:

```
R CMD check <package-name>.tar.gz
```

**Comment by costrouc** [comment]
It looks like @peti is the one that is responsible to updating the snapshot of R package see commit https://github.com/NixOS/nixpkgs/commit/49c649d57358acba87b851a763fdd4e1dc093112 . He has  been doing this for about 2 years. I am sure that he can speak more about the R community within nixpkgs. I mainly focus on `python` development but I would love to see a strong R packaging ecosystem because of how important both languages are for data science.

**Comment by pstn** [comment]
There is [documentation](
https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/r.section.md) on how to upgrade the R packages, but following that results in a
```
[nix-shell:~/repositories/nixpkgs/pkgs/development/r-modules]$ Rscript generate-r-packages.R > cran-packages.nix.new
Error: mirrorType %in% names(mirrorUrls) is not TRUE
Execution halted
```

for me so I guess the reason that the packages are not updates is that the script broken and @peti didn't get around to fix it.

**Comment by pstn** [comment]
There is a nice documentation on how to do the upgrades. I'm currently running it and will do a PR as soon as it's finished.

**Comment by peti** [comment]
We have the latest versions in `master` now.
