### ISSUE TITLE
cross compilation of clang (or llvmPackages*.tools) fails to evaluate

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#49475]
## Issue description

Evaluation complains that `llvmPackages` attribute doesn't exist in `targetPackages`.

Indeed, investigating with `nix repl` suggests `targetPackages` only contains `stdenv`.

### Steps to reproduce

* `$ nix build -f channel:nixos-unstable pkgsCross.musl64.clang`

OR

`$ nix build -f channel:nixos-unstable pkgsCross.aarch64-multiplatform.clang`

and so on.

FWIW occurs when directly setting `crossSystem` instead of using convenience `pkgsCross`.

**Comment by dtzWill** [comment]
This somehow made it to 18.09 as well? :(

To see it non-broken, you'll have to use 18.03 which is before the nice pkgsCross bits, so something like:

```
$ nix build -f channel:nixos-18.03 --arg crossSystem '{config="x86_64-unknown-linux-musl";}' clang
```

**Comment by dtzWill** [comment]
Not sure what caused it, but I bet @Ericson2314 knows how to fix it :innocent:

**Comment by dtzWill** [comment]
* Goes back before 18.09 branch
* `clangStdenv` and `llvm` work -- as does `llvmPackages{,_N}.{llvm,stdenv,libcxx}`
* `llvmPackages*.tools` does not

Hmm this may be known and possibly mentioned but I forgot...?  If nothing else it'd be good to improve this error so it's clearer to new folk or those who forget things ;).

--------

git bisect says 6e7e22da70850e18d7949b95b215c011b9afda70 is "first bad commit", FWIW.

**Comment by Ericson2314** [comment]
This is because `targetPackages.targetPackages` = `targetPackages` in cross builds. This because at then end of `/pkgs/stdenv/booter.nix` it makes a fake stadenv so things like `targetPackages.stdenv.cc` go to a good choice of C compiler to use at run time (a choice that would technically be made by the next change).

In this case, well, there is no next stage so hard to tell what runtime libraries to use! It's unfortunate. Not sure what the best fix is.
```
nix build -f channel:nixos-unstable pkgsCross.musl64.llvmPackages.clang-unwrapped
```
builds fine since it has no runtime libs.

**Comment by Ericson2314** [comment]
So yes, the real solution is https://github.com/NixOS/nixpkgs/issues/49481 haha

**Comment by Ericson2314** [comment]
@dtzWill Yeah maybe we should change it so `targetPackages = pkgs // { stdenv = fake };` in `pkgs/stdenv/booter.nix` instead.

**Comment by matthewbauer** [comment]
This looks to be fixed?
