### ISSUE TITLE
Stage 1 boot script does not recognize existing init

### ISSUE THREAD

**Issue by michas2** [NixOS/nixpkgs#49519]
## Issue description

The [stage 1 boot script](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-1-init.sh#L557) contains the following line: 

```
if ! test -e "$targetRoot/$stage2Init" -o ! -L "$targetRoot/$stage2Init"; then
    echo "stage 2 init script ($targetRoot/$stage2Init) not found"
    fail
fi
```

According to that everything is fine if the file exists or is *NOT* a symlink.
However in stage 1 the regular root file system is mounted under `/mnt-root/` and therefore absolute symlinks in `/mnt-root/nix/store` will not resolve. Therefore having an init living in that store will never work.

If I understand the semantic correctly the exclamation mark in the middle needs to be removed.

This kind of problem arises for example when trying to lustrate from ubuntu to nixos. In this case `switch-to-configuration` points to an init in the store which is (by the above logic) not found and the boot process comes to a sudden stop.

### Steps to reproduce

(See also #49520.)

**Comment by lheckemann** [comment]
>According to that everything is fine if the file exists or is NOT a symlink.

Not quite, since the whole test command is negated… Let me dig out my rudimentary knowledge of boolean logic:
`! test -e "$targetRoot/$stage2Init" -o ! -L "$targetRoot/$stage2Init"`
=> fail if not (it exists or not (it's a link))
=> fail if (it doesn't exist) and (it's not not a link) (De Morgan)
=> **fail if (it doesn't exist) and (it's a link)**
=> succeed if not ((it doesn't exist) and (it's a link))
=> succeed if (not it doesn't exist) or (it's not a link)
=> **succeed if (it exists) or (it's not a link)**

This means it will fail if it's an absolute symlink that doesn't resolve to an existing path in the initramfs root, since (it doesn't exist) and (it's a link) both apply — although such a link may very well resolve correctly in the system root.

It will also incorrectly perform the chroot if there is no filesystem entry at all ("it's not a link" is satisfied), resulting in a kernel panic rather than a debug shell.

This should be, as far as I understand it, "fail if it doesn't exist and it's not a link", or in other words "succeed if it exists or it's a link". I'll open a PR to fix it.

**Comment by michas2** [comment]
Well, the negation is kind of negated, so no need for De Morgan. ;)
We get an error if the test fails, so everything is fine if the test succeeds.

The test succeeds if either `-e "$targetRoot/$stage2Init"` is true or `! -L "$targetRoot/$stage2Init"` is true, i.e. if init "exists" or it is *not* a symlink.
A "broken" link (absolutely pointing to `/nix`) counts as "not existing".

Therefore the first test fails and the second fails, too, because it is a symlink, i.e. not not a symlink. ;) 

It's probably good to avoid such confusing code.

> This should be, as far as I understand it, "fail if it doesn't exist and it's not a link", or in
> other words "succeed if it exists or it's a link".

Exactly. So removing the exclamation mark in the middle should make it do the right thing.

(Interestingly a "normal" installation creates a cmdline pointing to the actual init, while `switch-to-configuration` points to a symlink pointing to init.)

**Comment by lheckemann** [comment]
>Well, the negation is kind of negated, so no need for De Morgan. ;)

I wanted to make both the "fail-if" and "succeed-if" conditions clear ;)
