### ISSUE TITLE
envoy is out of date

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixpkgs#49574]
## Issue description

`envoy` is out of date and doesn't build due to a broken dependency.

### Steps to reproduce

`nix-build -E "(import <nixpkgs> {}).envoy"`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(vaibhavsagar): `"nixpkgs-18.03.131807.489a14add9a"`
 - channels(root): `"nixos-18.09.932.09195057114"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by flokli** [comment]
Envoy being out of date also seems to be the only reason we're still shipping a `bazel_0_4`. However, `bazel_0_4` is marked as broken, so it doesn't seem to be possible to build `envoy` either.

It might be the best to just remove that package instead of keeping broken stuff.

@cstrahan, do you have another more recent version (upstream is at 1.11.2 nowadays) packaged somewhere?

**Comment by flokli** [comment]
Removal PR: https://github.com/NixOS/nixpkgs/pull/71131
