### ISSUE TITLE
Make section names linkable in documentation

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#4965]
Sections are links only in TOC, but not inside the documentation itself.

**Comment by thatdocslady** [comment]
Ok folks, my 2 cents - the problem that @iElectric is describing is that the manual is published as a multi-page HTML book, where the TOC and each chapter/section are all displayed in separate pages. Opposed to that, the contributors guide is displayed as HTML-single, where all chapters/sections are on the same page.

Therefore, when you jump to a section/chapter in the contributors guide, you don't actually load a new page so you can scroll up/down, and since the source XML file has its own ID, you can also send a permalink to that chapter/section. In the manual, you are forced to navigate up/down/next/previous through the parts, but if you want to send a permalink to a chapter/section then all you need to do is copy the URL from the address line.

This is not a problem per-say, because each book behaves correctly according to the chunking settings set in the publication tool. So for example, if the contributors guide was chunked in the same way as the manual, the permalink would need to be taken from the address bar. Or alternatively, if the manual was re-chunked as HTML-single, the permalinks would have the hash # in them.

The question is more functional - which way do we prefer to present the content to our readers? When we sprinted in Ljubljana, we changed the behavior of the manual from HTML-single to multi-page HTML, but theoretically we could give readers both options depending on what they need. For F5-induced searching, HTML-single is good. For I'm-not-sure-what-I-need browsing, multi-page is the way to go.

</2_cents>

**Comment by spwhitt** [comment]
I strongly prefer the single page HTML, because the multi-page is not
searchable. I've opened a Ctrl-F find window in the NixOS manual many
times, only to disappointedly realize I'd have to manually click through
the sections or work out some google-fu.

**Comment by wmertens** [comment]
Single page please, with rollover '#' things to click on to change the URL
to the permalink of that section, as is usual for these things...

**Comment by chaoflow** [comment]
I wholeheartedly agree with @spwhitt and @wmertens.

**Comment by pSub** [comment]
Closing. Both, the nixos and nixpkgs manual, are now single page manuals and each section has a permalink if you hover over it.
