### ISSUE TITLE
Gnome tweak tool doesn't allow for installing shell extensions

### ISSUE THREAD

**Issue by CryCic4da** [NixOS/nixpkgs#49759]
Is this expected behaviour or am I missing something? I have my configuration.nix configured with gnome3 and gdm. Was support for the ability to install extensions removed? I am new to NixOS and I hope I am not cluttering your issue board.

**Comment by jtojnar** [comment]
Was there ever a support for installing extensions? I do not recall it.

**Comment by coreyoconnor** [comment]
I don't recall seeing within gnome tweak tool the ability to install extensions... Only configure already installed. I only know of installing via https://extensions.gnome.org/ . Perhaps it was removed from gnome tweak in favor of the web one?

There is a bug related to https://extensions.gnome.org/ : The gnome native messaging app is not working. There is a workaround for that issue. Which, once applied, enables extensions to be installed. 

See

* https://unix.stackexchange.com/questions/437248/how-can-i-install-gnome-shell-extensions-from-extensions-gnome-org-through-firef

The workaround for that is specifically:

1. determine the location of the the manifest `org.gnome.chrome_gnome_shell.json` 
2. place under `~/.mozilla/native-messaging-hosts/`

See also #26981 which added support. This support did originally work. Something changed with how the messaging app is referenced by firefox since then.

**Comment by jtojnar** [comment]
You can also install extensions in GNOME Software or though Nix.

**Comment by hedning** [comment]
Yeah, upstream removed support for this in 3.26, due to gnome-software now doing the the job: https://gitlab.gnome.org/GNOME/gnome-tweaks/blob/9e4143d786c29c88d289b3d5755b51a47bdb650f/NEWS#L290

**Comment by coreyoconnor** [comment]
To be clear Gnome Software only supports installing and removing *not* updating:

* https://gitlab.gnome.org/GNOME/gnome-software/issues/380

Tweak only supports enable/disable. Not updating as well.

Looks like the only mechanism to update is via the chrome gnome shell.
