### ISSUE TITLE
mutableUsers break if you have password file on a non-root partition

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#4990]
They've worked previously, I suppose something had changed between recent channel releases. It wasn't working earlier really, too -- it reported "cannot open file" on each boot. We might need to mount everything before regenerating passwd/shadow, but this might break nice boot speed improvements systemd gives us because of mounts starting in parallel with services.

Maybe things just need to stay that way.

**Comment by Profpatsch** [comment]
@wmertens can that be done by checking if the option is set to true for the file system with the longest substring of the password file? Or are there other things to consider? Probably have to normalize the file paths first.

**Comment by gleber** [comment]
I've tried to implement tests for `users.mutableUsers` where one test would verify that `nixos-rebuild switch` removes undeclared users from `/etc/passwd`. Unfortunately the only test which currently supports `nixos-rebuild` is `installer.nix` test, which takes a lot of time (even individual partition-setup-specific test inside). Reusing parts of the installer test would be easiest, but the test would take a lot of time.

I've tried taking a standard test and making `nixos-rebuild switch` work there, but:
* `configuration.nix` is not present and I had to improvise one (not sure if it was correct or not)
* I couldn't figure out how to set up channels (e.g. I tried using the minimal installer channel) so that `nixos-rebuild` can build necessary packages

Any pointers on the best way to proceed? Which approach is best? If it is the extended standard test, what would be the setup you suggest?

Thanks

**Comment by globin** [comment]
```
$ rg switch-to nixos/tests 
nixos/tests/nat.nix
104:        $router->succeed("${routerDummyNoNatClosure}/bin/switch-to-configuration test 2>&1");
109:        $router->succeed("${routerClosure}/bin/switch-to-configuration test 2>&1");

nixos/tests/taskserver.nix
105:    switchToNewServer = "${newServerSystem}/bin/switch-to-configuration test";

nixos/tests/nginx.nix
60:    $webserver->succeed("${webserver_new}/bin/switch-to-configuration test");
66:    $webserver->fail("${webserver_invalid}/bin/switch-to-configuration test");

nixos/tests/radicale.nix
65:      in "${newSystem}/bin/switch-to-configuration test";

nixos/tests/containers-restart_networking.nix
81:      $client->succeed("${eth1_bridged}/bin/switch-to-configuration test >&2");
92:    #  $client->succeed("${eth1_rstp}/bin/switch-to-configuration test >&2");
104:      $client->succeed("${originalSystem}/bin/switch-to-configuration test >&2");

nixos/tests/containers-reloadable.nix
56:    $client->succeed("${c1System}/bin/switch-to-configuration test >&2");
60:    $client->succeed("${c2System}/bin/switch-to-configuration test >&2");

nixos/tests/firewall.nix
62:    $walled->succeed("${newSystem}/bin/switch-to-configuration test 2>&1" .
```

**Comment by gleber** [comment]
Ah! Somehow I haven't stumbled upon this call. Thanks!

**Comment by gleber** [comment]
Taking a shot at this. First step: #31569

**Comment by gleber** [comment]
It turned out @grahamc took a stab at the issue of asserting that nixos user configuration is sane at #31034. So far the PRs do not overlap.

**Comment by Ekleog** [comment]
(triage) Is someone still working on this?
