### ISSUE TITLE
Package request: AutoSpotting

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#50304]
## Issue description
This would allow massive cost savings in AWS: https://github.com/AutoSpotting/AutoSpotting.

**Comment by costrouc** [comment]
I have created the package but I would appreciate if you checked that it worked properly since I do not have much experience with AWS tooling. Also does the package require any propagated build inputs ?

Also if interested here are the steps that I did.

git checkout rep. nix-shell -p dep2nix. `dep2nix` will create a `deps.nix` file that you can use for all the dependencies. Then copying one of the `buildGoPackage` files and changing all the fields. I am sure there is a more automated way.
