### ISSUE TITLE
Request to package localstack

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#50445]
https://github.com/localstack/localstack is a fully functional local AWS cloud stack. It allows you to mock AWS services and develop tests for applications that rely on AWS.

If nobody gets around to this, I may work on this later.

**Comment by mogorman** [comment]
i started a pr for this will try to get more to it so it can be merged

**Comment by risicle** [comment]
Removing stale label as I've been looking into this more.

A few tricky things about `localstack` that I've discovered in researching this:

1. "localstack"'s code seems quite interwoven with the code for "localstack pro". For instance the main package `localstack` depends on `localstack_ext`, a package that exists on pypi but for which the source is not publicly hosted. You can of course download the tarball from pypi and _read_ the source, though much of it seems to have been minified, but the largest chunk of that package seems to consist of `.py.enc` files - encrypted python files. I guess these get "unlocked" when you pay for "localstack pro". I think it's a bit creepy to have all this mystery code floating about and I'd be hard pressed to call this an "open source" dependency. Maybe we'd be able to just do a `find . -name '*.enc' -delete` in a `postFixup` to avoid installing this on people's machines and this would be fine, I don't know.
2. It appears to depend on a forked `moto`, which they host at https://github.com/whummer/moto and publish as the pypi package `moto-ext` https://pypi.org/project/moto-ext. The problem is that this package still retains the toplevel import name `moto`, and so we wouldn't be able to include this package in `pythonPackages` due to policy (it would potentially collide with the vanilla moto in generated environments). It would would still be possible to keep `localstack` as a regular application, not exposing its internal `moto-ext` outside the derivation.

**Comment by CMCDragonkai** [comment]
Is it possible to bring in a python dep without propagating it?

**Comment by jonringer** [comment]
might be 40 months late, but I took a stab at this.
