### ISSUE TITLE
question: Declarative grafana configuration

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixpkgs#50514]
## Issue description
I would be interested in seeing declarative configuration of graphs in grafana, but it seems no such thing is currently supported. 

What's the expected usage of Grafana if one wants to use e.g. the same Grafana configuration across multiple machines on different networks? 

If that's not supported, what *is* the current expected usage of grafana? 

## Technical details

Any version of nixpkgs.

**Comment by atopuzov** [comment]
@coretemp you can try using https://github.com/NixOS/nixpkgs/pull/53874 and just commit your dashboard JSON files to your config repository.

I suggest instead of modeling dashboards in nix using either grafana jsonet [1] or grafanalib [2] to create JSONs. 

[1] https://github.com/grafana/jsonnet-libs
[2] https://github.com/weaveworks/grafanalib

**Comment by dotlambda** [comment]
@coretemp Do the features implemented https://github.com/NixOS/nixpkgs/pull/53874 suffice for you?

**Comment by Ma27** [comment]
Closing, this is sufficiently implemented IMHO (theoretically you can deploy alerting/dashboards/datasources with the module in here).

For examples see e.g. nixos/tests/grafana.
