### ISSUE TITLE
sway-beta module: prevents cli args from getting to sway

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#51303]
## Issue description

The wrapper around `sway` in the `sway-beta` module prevents the usage of cli args with sway, particularly flags for debugging, help, etc.

### Steps to reproduce

```
# activate the sway-beta module
sway --help
```

Notice that it just starts instead of displaying the help...

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by colemickens** [comment]
cc: @gnidorah @primeos Is there a reason that `pkgs.writeShellScriptBin` is used instead of something like `makeWrapper` ?

**Comment by gnidorah** [comment]
No special thinking, I just don't know how to write it using `makeWrapper`. How to write `ifs` with it?
@bbigras change is wrong, because we don't need to run it via `dbus-launch` each time, only on the start, in the same manner there is no need to set environment every time. The proper way should be:
```nix
  swayWrapped = pkgs.writeShellScriptBin "sway" ''
    if [[ "$#" -ge 1 ]]; then
      exec sway"$@"
    else
      ${cfg.extraSessionCommands}
      exec ${pkgs.dbus.dbus-launch} --exit-with-session sway
    fi
  '';
```
