### ISSUE TITLE
netdata: Access to file is not permitted

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#51309]
## Issue description

After upgrade to 18.09 (from 18.03), netdata shows only this error in the browser:

>Access to file is not permitted: /nix/store/lj1ifxwl3cw8xg9l9a3cgmxip59im26a-netdata-1.11.0/share/netdata/web//index.html

The strange thing is that i can access it without problems on console:

```
[root@nas:~]# sudo -u netdata less /nix/store/lj1ifxwl3cw8xg9l9a3cgmxip59im26a-netdata-1.11.0/share/netdata/web//index.html

[root@nas:~]# echo $?
0
```

A similar patch was removed here and a test was added, that might not have detected this problem.

https://github.com/NixOS/nixpkgs/commit/0254ae4e80f9bf659430d2ec3e452ccb049ce2fb#diff-c080a3ec04b35f95254741800e1a3697

This test should also have failed:

```
curl -s http://localhost:19999/api/v1/data\?chart=users.pwrites | \
...
```

Response for http://nas.lan:19999/api/v1/data/?chart=users.pwrites on my system is:

`Chart is not found: users.pwrites` (HTTP Status Code 404)

I can reproduce this on 2 separate systems.

cc @lethalman

### Steps to reproduce

1. have netdata enabled
2. try to access it with browser

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.83, NixOS, 18.09.1446.db561c90ef3 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1446.db561c90ef3, nixos-unstable-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by Zer0-** [comment]
I am having the same problem. I've had netdata installed for a while and now I'm getting

```Access to file is not permitted: /nix/store/lj1ifxwl3cw8xg9l9a3cgmxip59im26a-netdata-1.11.0/share/netdata/web//index.html```

Stat gives me
```
  File: /nix/store/lj1ifxwl3cw8xg9l9a3cgmxip59im26a-netdata-1.11.0/share/netdata/web//index.html
  Size: 328676    	Blocks: 648        IO Block: 4096   regular file
Device: 1ah/26d	Inode: 78177322    Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-11-19 04:42:08.000000000 +0000
Modify: 1970-01-01 00:00:01.000000000 +0000
Change: 2018-11-19 04:42:08.381484497 +0000
 Birth: -
```

**Comment by Zer0-** [comment]
I just took another look at this and it occurred to me that [because of this line](https://github.com/NixOS/nixpkgs/blob/0254ae4e80f9bf659430d2ec3e452ccb049ce2fb/nixos/modules/services/monitoring/netdata.nix#L23) the config file never gets populated with `"web files owner" = "root";` in the case of using the `configText` option, which I was. If those aren't set netdata checks the file permissions and gets something unexpected. So prefer using `config` instead, or set those options manually.

I think we can close this issue, but this behaviour is weird - it is netdata checking file permissions manually (for reasons I don't really understand), and it's not the case that the `netdata` user cannot read the files as demonstrated above.

**Comment by davidak** [comment]
I'm also using `configText` https://github.com/davidak/nixos-config/blob/e14c37caefa2c1400d2b73e49f2d718140caf7cc/machines/atomic/configuration.nix#L70
