### ISSUE TITLE
CLASSPATH warning in leiningen

### ISSUE THREAD

**Issue by winks** [NixOS/nixpkgs#51448]
## Issue description
Problem: CLASSPATH warning when using `lein repl` in nix-shell

This is not advisable for leiningen usage, as can be seen from the warning :)

I'm not a nix expert, but we discussed this on #leiningen /freenode, here's a small chat log:
```
>> Nix operates with things in unconventional places (which allows it to do all that it does). In this case, my CLASSPATH gets set to: /nix/store/rs5d0hp4idpkhs0gcvl0s3imy3s5pzmm-leiningen-2.8.1/share/java/leiningen-2.8.1-standalone.jar
> the lein warning is correct
> if you export CLASSPATH that'll infect all your lein invocations
> rather than finding lein that way, I suggest you patch the lein location in the bin/lein script instead
> (not to mention other things that care about exported CLASSPATHs)
> https://salsa.debian.org/clojure-team/leiningen-clojure/blob/master/debian/patches/0003-Update-LEIN_JAR-location-to-match-installed-jar.patch
> I think what you probably want is to template that value out and set it at install time
```

As far as I can see the relevant file is
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/leiningen/default.nix but if I got this right this won't actually help here as CLASSPATH is not set by the wrapper script, but by nix-shell or the jdk package? So not sure how to proceed here, except maybe `unset CLASSPATH` in that wrapper script? 

Tagging @bendlas for having touched the lein nix expression last, sorry :)

### Steps to reproduce
```
$ cat test.nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.stdenv.mkDerivation
{
  name = "asdf";
  buildInputs = with pkgs;
  [
    # Clojure
    jdk8
    leiningen
  ];
}
$ nix-shell test.nix
##############
[nix-shell:~/tmp]$ lein version
WARNING: You have $CLASSPATH set, probably by accident.
It is strongly recommended to unset this before proceeding.
Leiningen 2.8.1 on Java 1.8.0_192 OpenJDK 64-Bit Server VM
```
## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/wsqynhnll3nybp9wn02j66qd5x9xvxsx-nix-info
copying path '/nix/store/wsqynhnll3nybp9wn02j66qd5x9xvxsx-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-39-generic, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(florian): `"nixpkgs-19.03pre160658.1bf18e4c852"`
 - nixpkgs: `/home/florian/.nix-defexpr/channels/nixpkgs`
```

**Comment by bendlas** [comment]
> > rather than finding lein that way, I suggest you patch the lein location in the bin/lein script instead

that's actually what we do https://github.com/NixOS/nixpkgs/blob/e42d10957d87a5837085cd3273f97e50b67e987d/pkgs/development/tools/build-managers/leiningen/default.nix#L39

`CLASSPATH` is set as a side effect of the java setup hook https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/set-java-classpath.sh

There is an argument to be had on whether it's more correct to unset CLASSPATH in the wrapper script or leave it.

Depending on how leiningen constructs its classloaders, leaving in the CLASSPATH should make leiningen use Nix' dependencies instead of its own, which, in a nix-shell, is arguably the desired behavior. Also the 'infectious' behavior is part of the expectation in a nix-shell.

**Comment by winks** [comment]
So I guess what you're saying that it would be expected behaviour for regular nix-shell users, while being unexpected for leiningen users.

So maybe it would be best to patch out the warning in nix then?

**Comment by bendlas** [comment]
> So I guess what you're saying that it would be expected behaviour for regular nix-shell users, while being unexpected for leiningen users.

I would say so.

> So maybe it would be best to patch out the warning in nix then?

That would be to the detriment of Nix users not in a nix-shell, which could not benefit from the warning any more.

Thinking about it again, the best course of action would be to move the leiningen jar from `share/java` to a place where it's not picked up by `set-java-classpath.sh`.
Its proper place isn't in `share/java` anyway, since it's an uberjar containing all its dependencies.

In all the remaining cases, where you actually compose your classpath via nix, but then still run leiningen, the warning is appropriate.
