### ISSUE TITLE
monero compiled without hidapi breaks ledger nano s connection

### ISSUE THREAD

**Issue by thedavidmeister** [NixOS/nixpkgs#51726]
## Issue description

ledger nano s cannot connect to monero wallet due to missing hidapi lib

### Steps to reproduce

lots of debug info and eventual solution here:

https://www.reddit.com/r/Monero/comments/a3jxin/nixos_cant_connect_ledger_nano_s_to_monero_cligui/ebaavc4/?context=3

## Technical details

see link above, solution is to add `-p hidapi` when compiling monero

**Comment by rnhmjoj** [comment]
I'm not sure how this works because I don't have one to test with. monero-gui is built with hidapi already, does monero (the daemon) has to be compiled against it too?

Anyway, the method you are using to get the latest package is not right. You are only overriding the source attribute so any change to the dependencies or build instruction between your version and the latest could potentially cause it to produce a broken package or fail to build entirely.
You should instead set up the unstable channel

    nix-channel --add https://nixos.org/channels/nixos-unstable unstable

then install the package like
```nix
let
  unstable = import <unstable> { };
in
stdenv.mkDerivation {
  name = "monero-environment";
  buildInputs = [ unstable.monero ];
}

```

**Comment by thedavidmeister** [comment]
ok interesting

well i did it wrong, so take this with a grain of salt, but the gui did not work either for me

i'll try what you're suggesting now

**Comment by rnhmjoj** [comment]
Ok, monerod *does* need hidapi. I've opened a PR to fix this.
