### ISSUE TITLE
Segmentation fault when launching gnome-boxes

### ISSUE THREAD

**Issue by wigneyliam** [NixOS/nixpkgs#52611]
## Issue description

When trying to launch gnome-boxes from the launcher nothing happens. However launching from the command line gives the error saying a seg fault has occurred.

### Steps to reproduce
Install gnome3.gnome-boxes 
Run it from the commandline or launcher

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.88, NixOS, 19.03pre162671.44b02b52ea6 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre162671.44b02b52ea6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by hedning** [comment]
I'm unable to reproduce this on b0ccd8be8e4. Ran a nix-diff and got these changes:
```
    - freerdp-2.0.0-rc3
    - libvirt-4.7.0
    - qemu-3.0.0
    - webkitgtk-2.22.4
    + freerdp-2.0.0-rc4
    + libvirt-4.10.0
    + qemu-3.1.0
    + webkitgtk-2.22.5
```
So one of these probably fixed the issue.

**Comment by wigneyliam** [comment]
Ah sweet thanks, unstable's a week behind at the moment and that commit is 4 days old so hopefully when it updates I'll get the fix! I'd test it by compiling nixpkgs but this machine only has 2gb of ram so it'd take way to long.

Should I close this and just wait until I can test/the fix comes? Or leave it open until then? I'm not quite sure the etiquette.

**Comment by hedning** [comment]
b0ccd8b is cached, it failed a test randomly (the installer tests are being a pain at moment :(), but it's safe to use.

In general looking at [how many builds have failed/completed](https://hydra.nixos.org/jobset/nixos/trunk-combined) and [how many tests are sucessful](https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents) can give you a pretty good idea if a given commit is cached and usable. Then you do this:
```
cd path/to/nixpkgs/
git checkout <commit that looks>
nixos-rebuild boot/switch -I nixpkgs=.
```
This is a bit clunky, but at least workable if the channels are being pain (eg. due to random test failures).

**Comment by hedning** [comment]
It's fine leaving it open until you've confirmed things work.

**Comment by wigneyliam** [comment]
Hey all good now, looks like I got the update. Thanks!
