### ISSUE TITLE
 Django 1.8 is EOL 

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#52679]
## Issue description
Django version 1.8 has reached EOL in april 1, 2018 https://www.djangoproject.com/download/

modules affected:
+ graphite
https://github.com/nixos/nixpkgs/blob/d60f6d2d5d2c6f4774a4558221da6ba93bb37956/nixos/modules/services/monitoring/graphite.nix#L463-L468
graphite-web already supports django_2_0 https://github.com/graphite-project/graphite-web/pull/2278

**Comment by dotlambda** [comment]
It's also insecure since we didn't update it to 1.8.19:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-7536
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-7537

cc @basvandijk

**Comment by dotlambda** [comment]
I pushed commits that update django_1_8 to 1.8.19 to master as well as release-18.09.

@rickynils @offlinehacker @basvandijk Could you please update `graphite-web` to use a newer version of Django?

**Comment by basvandijk** [comment]
@dotlambda I started to work on this in https://github.com/NixOS/nixpkgs/pull/52799. Not sure when I'll be able to finish that...

**Comment by danderson** [comment]
Taking a look at this as I work through bugs tagged security.

Django 1.8 is EOL, and has multiple known CVEs. It's already marked insecure in nixpkgs, and has been for 12 months (2019-01-30).

The only reason 1.8 is still in nixpkgs is because of the Graphite NixOS module. Graphite is still being updated upstream, and now works with more recent Django versions. However, nobody has updated the NixOS module.

Given that installing Graphite has generate knownVulnerabilities errors for >1 year, I propose to simply delete the Graphite NixOS module, and the closure of insecure packages that it depends on.
