### ISSUE TITLE
Application no longer in PATH, worked previously though?

### ISSUE THREAD

**Issue by chrissound** [NixOS/nixpkgs#52731]
## Issue description

command not found but it worked previously?

### Steps to reproduce
Addition of `sox` to `environment.systemPackages`.

```
sox
zsh: command not found: sox
```

## Technical details

- system: `"x86_64-linux"`
 - host os: `Linux 4.14.83, NixOS, 18.03.133381.a18112a7e8f (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(chris): `"unstable-19.03pre161545.7c73f53d836"`
 - channels(root): `"nixos-18.03.133381.a18112a7e8f, unstable-19.03pre161545.7c73f53d836"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```
echo $PATH
/home/chris/.local/bin/:/home/chris/bin:/run/wrappers/bin:/etc/profiles/per-user/chris/bin:/home/chris/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
```

```
nix-store --query --requisites /run/current-system | rg sox              
/nix/store/c22asc0mi514idn5g66bgnzl9krd6wjf-soxr-0.1.2
```

**Comment by lheckemann** [comment]
This should work. Apologies for the maybe silly questions, but did you maybe put soxr in systemPackages instead of sox?

For your nix-env issue — you must have removed ~/.nix-profile at some point. Run `ln -s /nix/var/nix/profiles/per-user/$(whoami)/profile ~/.nix-profile` to fix that.

And finally, your system is on 18.03 which is no longer updated. I strongly recommend upgrading to 18.09.

**Comment by chrissound** [comment]
Ah the actual issue was I installed a package that  resulted in  `nixos-rebuild switch` failing, which in turn resulted in missing executable in the PATH somehow. Not sure if this is expected behavior? But none the less easy enough to resolve by removing the package I added and rebuilding.

Thanks for the notice about 18.03 - I'll look into this.
