### ISSUE TITLE
Declarative cups configuration

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#52776]
## Issue description
Allow configuration of a cups printer by pointing at a ppd file and specifying a single URL in configuration.nix.

Currently, such configuration requires clicking through a web-interface.

## Technical details
18.09

**Comment by makefu** [comment]
I actually ran into problems with the imperative configuration. I configured my printer (samsung scx3200) and after a system upgrade i was unable to print anymore. An error was shown in the cups web interface for the printer: "unable to load PPD, /nix/store/.... no such file or directory". It looks like the driver i used was garbage-collected.
That would not happen with a declarative configuration. However i am certain that this module is no easy piece of work because it requires deep insight into how cups works.

**Comment by Mic92** [comment]
Interestingly for my driver it just copy them to `/etc/cups/ppd`. Does the files within this directory has references to the nix store?

**Comment by florianjacob** [comment]
I created a half-stateful solution similar to `mysql.ensureDatabases`, which uses `lpadmin` etc. to create the configured printers and force them in the right configuration, without having to touch the deep parts of cups. Works quite well, still have to see how it works on printer driver updates, though. Will pose a PR when that succeeds.

**Comment by florianjacob** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/55510 please go and test it. :)

**Comment by avnik** [comment]
Upvote this! Will test 55510 on weekend. (looks better, than my own unconditional injection of ppd into /var/.../cups)

**Comment by Yarny0** [comment]
Hi, I just stumbled over this issue by accident and realized I'm using something similar in my machines own printing config. So I'm thinking it might help you if I'd share this code with you.

[printing.nix.txt](https://github.com/NixOS/nixpkgs/files/3026683/printing.nix.txt)

Sorry for just dumping this file here. I've been planning to clean it up and suggest my module via a pull-request on its own, but I haven't found the time to do so yet. Still, I hope my module contains some usable ideas towards declarative printer config (e.g. set options, and check that each declared printer has its backend and ppd file installed).
