### ISSUE TITLE
qrencode is packaged twice

### ISSUE THREAD

**Issue by jameysharp** [NixOS/nixpkgs#53133]
Two different packages build the same source in basically the same way. I think only one of them should exist.

- libqrencode: `pkgs/development/libraries/libqrencode/`
- qrencode: `pkgs/tools/graphics/qrencode/`

Both packages use `https://fukuchi.org/works/qrencode/qrencode-${version}.tar.gz` as their `src`. `libqrencode` sets `doCheck = true` but otherwise neither package overrides any of the build phases. They have somewhat different `buildInputs` but I'm not sure the differences change the way the package builds.

I'm not sure which one to suggest keeping but I'm pretty sure these packages should be merged somehow.

**Comment by jtojnar** [comment]
It is primarily a library so I would keep it in libraries directory, but it is [commonly packaged](https://repology.org/metapackage/qrencode/versions) without the `lib` prefix so I would drop that.

`autoconf automake libtool` should not be necessary, since the tarball contains pregenerated `configure` script.

libpng is only used for the binary, we split it out into a separate output. SDL is only used for the tests. Neither should be propagated.
