### ISSUE TITLE
Make fish easily configurable as a default shell

### ISSUE THREAD

**Issue by rushmorem** [NixOS/nixpkgs#5331]
This is a feature request. May you please make `fish` shell easily configurable as a default shell. With `zsh`, for example, I can simply enable it like so `programs.zsh.enable = true;` and set `users.defaultUserShell = "/run/current-system/sw/bin/zsh";`.

cc @ocharles

**Comment by lethalman** [comment]
Closed by #5626

**Comment by henrytill** [comment]
I'm not sure that #5626 actually closes this. 

 See https://github.com/NixOS/nixpkgs/pull/5626#issuecomment-73916475

**Comment by lethalman** [comment]
How not? He only asked for being able to put fish in current-system/sw so that he could use it as shell.

**Comment by henrytill** [comment]
Setting up fish shell to be the default shell with the new module would result in a shell that doesn't inherit any environment from `${config.system.build.setEnvironment}`, as bash and zsh do.

**Comment by lethalman** [comment]
It's really so incompatible to not being able to set a couple of variables? In which case I can revert.

**Comment by henrytill** [comment]
```
[ht@nereus:~]$ nix-shell -p fish --command fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
ht@nereus ~> export FOO="BAR"
fish: Unknown command 'export'
ht@nereus ~> FOO="BAR"
fish: Unknown command 'FOO=BAR'. Did you mean 'set FOO BAR'? See the help section on the set command by typing 'help set'.
ht@nereus ~> 
```

And even it if it were compatible, the module doesn't even correctly set up an initialization from which to source `${config.system.build.setEnvironment}`.

**Comment by lethalman** [comment]
Impressive. Reverting, thanks.

**Comment by elasticdog** [comment]
The syntax for fish is different, so instead of using `export`, you use `set -x <var-name> <value>` (with no = sign in there). I've been poking around and will try and come up with a reasonable fish script to set up the environment.

**Comment by obadz** [comment]
Could we get away with a wrapper that sets up the environment and then invokes fish?

**Comment by jhenahan** [comment]
For anyone else who gets here from Google, I rewrote a version of `nix.sh` in `fish` as a stopgap.

https://gist.github.com/jhenahan/ab4dbdce6c431f671929

**Comment by obadz** [comment]
@jhenahan, do you think this can this be integrated to nixpkgs to provide a somewhat seamless experience for those who want to use fish as their default shell?

**Comment by jhenahan** [comment]
I'll look into how nix.sh gets written and such after work today. I wouldn't expect it to be too labor-intensive.

**Comment by srid** [comment]
FWIW trying to set fish as the default shell (though it works when manually running) leads to all sorts of trouble:

![screen shot 2015-07-31 at 12 06 58 pm](https://cloud.githubusercontent.com/assets/3998/9015291/bf7f56f2-377c-11e5-9266-bf88088526c3.png)

**Comment by therealpxc** [comment]
One hacky, but possibly easy way to do this is with 'fenv', a fish function defined in the plugin-foreign-env package for Oh My Fish: https://github.com/oh-my-fish/plugin-foreign-env

The fenv function takes a bash command or a path to a bash script, runs it under bash, and then modifies the fish environment appropriately to match any environment variables that were set in the bash environment.

Fish also automatically escapes the output of subcommands in the appropriate way, so if we want to use the output of a command, as we would with ssh-agent, for example, without modifying anything to get fish code, we can do

``eval fenv (ssh-agent)``

or

``fenv 'eval $(ssh-agent)'``

or

``fenv eval `ssh-agent` ``

and so on. I think leveraging this function would be a good idea, but what's the best way to go about it? Should we arrange things so that "programs.fish.enable = true;" also installs oh-my-fish as well as the plugin for omf in a nixy way? Should we rip out the code from the package? Or maybe, should we just write a nix expression that installs the files for the functions, ripping them directly from git but arranging them in a different location (maybe globally)?

**Comment by gpyh** [comment]
@therealpxc Using the `export` function would make it accessible to the user, which she may not want. Plus, if the script one day uses a bash-specific feature, it would raise an error difficult to pin down.
IMHO, we should just replicate fenv as a compatibility hook.

**Comment by therealpxc** [comment]
Do you have any preference as to how it's done? I'm willing to do it, but
idk what I'm doing, really. If you want to gesture in some direction I'd be
happy to iterate through a few attempts.

**Comment by jgillich** [comment]
I'd love to see this fixed, but I'm kinda in the same boat, don't really know how to approach this.

**Comment by jgillich** [comment]
Would appreciate some feedback for the above PR.

**Comment by Profpatsch** [comment]
@jgillich Does it work in your system?

As I instected the viability some time ago, I found some nixpkgs modules explicitly build array environment variables by concatenating with `:`s, I think `NIX_PATH` does it that way. afaik `fish` automatically converts only some few explicit envvars to fish-arrays, e.g. `PATH`.
I suspect those explicit string concatenations need to be abstracted for POSIX-like shells and fish-like shells first.

**Comment by jgillich** [comment]
@Profpatsch Of course it works on my system. I've been using it for the last two weeks without any issues (other than #12162. but that was an issue in the package).

Just look at the source, it completely bypasses any compatibility issues by importing the environment using fish-foreign-env. Making NixOS fish-compatible is just not possible because we have things like `environment.shellInit`:
> Shell script code called during shell initialisation. This code is asumed to be shell-independent, which means you should stick to pure sh without sh word split.

**Comment by Profpatsch** [comment]
That’s nice! I will try to use it.

**Comment by therealpxc** [comment]
Thanks for taking care of this, @jgillich . I'm glad to see this closed. :-)

**Comment by andrewrk** [comment]
Can anyone who got this working update the wiki?

https://nixos.org/wiki/Fish

Currently says

> At the moment it’s not possible to use fish as login shell. But you can always start it as default shell of your terminal emulator.


Is this still true? What do I do in my config file if I want to use fish as my shell?

**Comment by andrewrk** [comment]
Never mind, I figured it out and I will update the wiki myself :+1:

**Comment by andrewrk** [comment]
Just saw this:

> The NixOS wiki is outdated and is being shut down. If you wish to add or improve NixOS documentation, please grab a ticket from the Move the wiki! milestone.

Anyway the answer is:

```
programs.fish.enable = true;
users.defaultUserShell = "/run/current-system/sw/bin/fish";
```

Easy!

**Comment by Profpatsch** [comment]
@andrewrk It might make sense to document changing the default shell in the nixos manual, with examples for fish & zsh. Do you want to do that?
