### ISSUE TITLE
Move wayland compositors in a separate module

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#53394]
For example, `services.wayland.*`. Right now they all live in `programs.*` and thus are harder to discover.

**Comment by jtojnar** [comment]
I think it might make sense to use

- `services.xserver.displayManager.gdm` → `services.desktop.displayManager.gdm`
- `services.xserver.desktopManager.gnome3` → `services.desktop.desktopEnvironment.gnome3`

The display server the DM or DE is running is just an implementation detail.

Not sure where to fit the slim WMs like Sway or OpenBox into this, since I would expect `desktopEnvironment` to handle things like XDG modules as well — my uncertainty probably stems from the lack of composability of modules.

**Comment by suhr** [comment]
This is still relevant.

**Comment by doronbehar** [comment]
Is it possible to run gdm and Gnome without X on the system at all? I mean, does setting `services.xserver.displayManager.gdm.enable = true` runs gdm in Xorg?

**Comment by primeos** [comment]
> Is it possible to run gdm and Gnome without X on the system at all?

Didn't check, but likely not yet.

> For example, services.wayland.*. Right now they all live in programs.* and thus are harder to discover.

I'd also appreciate having something like `services.wayland.*`. Or rather something like `nixos/modules/services/x11/display-managers/default.nix` (`xsessionWrapper`) that each Wayland compositor module can reuse.

**Comment by suhr** [comment]
Still relevant.

**Comment by suhr** [comment]
And relevant still.

**Comment by doronbehar** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/102542
