### ISSUE TITLE
[Package Request] nodePackages.textlint

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#53781]
## Issue description

[textlint](https://www.npmjs.com/package/textlint) "is an open source pluggable linting tool for natural language text".

Given the difficulty of installing npm packages on NixOS systems, it would be great to have this provided under `nodePackages.textlint`.

**Comment by 6AA4FD** [comment]
[Check here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/generate.sh) for documentation about how the nix expressions are generated, [and here](https://github.com/svanderburg/node2nix) is the repo for the tool that's actually used (though the script should install it for you with nix-shell). it looks like there's a generic tool for compiling desired node packages into nix expressions, and that's run on lists you provide, so you're probably going to want to add your entry to one of the three json files, and run the update script.
Since you're okay with trying to do it yourself, I'll leave it to you, but feel free to ping me if you need some help.

**Comment by matthew-piziak** [comment]
@6AA4FD Thanks Quinn! Alrighty, [first contribution](https://github.com/NixOS/nixpkgs/pull/53981).

Lemme know if I screwed that up. In the meantime I'll work through the checklist.

**Comment by matthew-piziak** [comment]
Merged! Thanks for the help!
