### ISSUE TITLE
geary fails to build on master

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#53864]
## Issue description
See: https://hydra.nixos.org/build/87269515

**Comment by hedning** [comment]
Looks like it [first broke](https://hydra.nixos.org/job/nixpkgs/trunk/gnome3.geary.x86_64-linux) the last staging-next merge (not the one today), in particular `vala` was upgraded, so I suspect that's the root cause. The [changes from the first breakage on trunk](https://hydra.nixos.org/api/scmdiff?type=git&rev1=7d864c6bd6391baa516118051ec5fb7e9836280e&rev2=5489e49ebb5cb9b973133fcd70d3196fb12acc0b&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&branch=).

**Comment by jtojnar** [comment]
Most likely the following change from Vala 0.42.4:

>  + Type check for errors require an error expression [[#362](https://gitlab.gnome.org/GNOME/vala/issues/362)]
