### ISSUE TITLE
findutils locate is installed by default

### ISSUE THREAD

**Issue by xzfc** [NixOS/nixpkgs#53925]
I'm using `locate`/`updatedb` and just noticed that these come from `findutils` and not from `mlocate`.
It either should not be a part of default installation or should be replaced by `mlocate` which is more secure.
The issue is that running `updatedb` as root leaks private paths to the world:
```
$ ls /root
ls: cannot open directory '/root': Permission denied
$ locate -r ^/root/
/root/.android
/root/.android/adbkey
/root/.android/adbkey.pub
/root/.bash_history
/root/.cache
/root/.cache/fontconfig
...
```

---

In [Debian], `locate` is not a part of `findutils` (it's moved to it's own package).
[Fedora], [Gentoo], and [Arch] don't even build `locate` from `findutils`.

[Debian]: https://packages.debian.org/source/stretch/findutils
[Fedora]: https://src.fedoraproject.org/rpms/findutils/blob/a6f38a9e3d68e089c61ffea3c3e8001e9b4facfe/f/findutils.spec#_14
[Gentoo]: https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/findutils/findutils-4.6.0-r1.ebuild?id=c23d497c3fbdadf86cdc785f5806a36116101e5e#n30
[Arch]: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/findutils&id=18e2356820503724ddabe16e3142d8ad4a33ad17#n29

**Comment by vcunat** [comment]
To be clear, it shouldn't "get ran" by default, so you won't get any database without root's action.

**Comment by herrwiese** [comment]
You can tell nixpkgs (resp. `nix-env`) to prefer the binaries of one package over another's by altering the package's priority.  Simply put the following snippet either in your `~/.config/nixpkgs/config.nix` or beneath `nixpkgs.config` in NixOS's `configuration.nix`:

    […]
    packageOverrides = pkgs: {
      mlocate = pkgs.lib.hiPrio pkgs.mlocate;
    };
    […]

**Comment by xzfc** [comment]
My point that this is unexpected for default installation.

**Comment by matthewbauer** [comment]
Does mlocate require setuid? That may be one reason why mlocate is not preferred here.

You can make NixOS use mlocate with:

```
services.locate.locate = pkgs.mlocate;
```

**Comment by league** [comment]
The issue of `mlocate` vs `findutils` is still biting me in a particular way. On NixOS, I set:
```
    services.locate = {
      enable = true;
      locate = pkgs.mlocate;
      localuser = null;
    };
    users.groups.mlocate.members = [ "MYNAME" ];
```
and I force `pkgs.mlocate` to override `pkgs.findutils` in `environment.systemPackages`, and that's all good... **except...**

Whenever I enter a `nix-shell` or `nix develop` (and because I use `direnv`, that's fairly often and happens just by changing into particular directories)... it seems that `pkgs.mkShell` drags in its own reference to `findutils` (I guess via `stdenv`) that then overrides `mlocate`. So the effect is:

```
$ cd ~
$ locate whatever
[shows me whatever]
$ cd ~/projects/foo
[activates direnv]
$ locate whatever
locate: locate.c:485: visit_old_format: Assertion `procdata->count >= 0' failed.
[2]    30134 abort (core dumped)
```
(That assertion failure is the symptom that occurs when we're using `findutils` locate to read a database created by `mlocate`.)

I think one avenue to a solution is to use a minimal variant of `mkShell` that doesn't drag in `stdenv`, as described in #147060.
Or I could overlay `findutils` to delete its copy of `locate` and `updatedb` but then (IIUC) I'd have to rebuild much of `stdenv` (and thus the whole world) whenever I update. The binary cache basically would become useless.

As Debian and other distributions have determined, the `locate` and `updatedb` within `findutils` are not part of its core functionality. They're not the parts being used in build scripts everywhere: `stdenv` depending on `findutils` is really for the commands `find` and `xargs`. So I think it makes all the sense in the world for `locate`/`updatedb` to be in a separate package from `find`/`xargs`. IMO, if there's actually a build step out there in some package that relies on having `locate` or `updatedb` in the path, they should specify that dependency explicitly, not get it automatically through `stdenv`.
