### ISSUE TITLE
Invalid installation instructions

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#54181]
## Issue description
`sudo dd bs=1m if=nix.iso of=/dev/rdiskN` is not valid. 

The `m` needs to be `M`. 

```
 N and BYTES may be followed by the following multiplicative suffixes: c =1, w =2, b =512, kB =1000, K =1024, MB =1000*1000,  M  =1024*1024,  xM
       =M, GB =1000*1000*1000, G =1024*1024*1024, and so on for T, P, E, Z, Y.
```

**Comment by matthewbauer** [comment]
Thanks for opening this! I noticed this too but forgot to make an issue.

So this is part of the macOS section? I think the issue is whether you are using GNU coreutils or Apple's file_cmds. Apple's file_cmds needs the lower case:

https://opensource.apple.com/source/file_cmds/file_cmds-272.220.1/dd/args.c.auto.html

while GNU's coreutils needs the upper case.

I propose just rewriting the instructions so that it reads:

```
sudo /usr/bin/dd bs=1m if=nix.iso of=/dev/rdiskN
```

To require the least assumptions.

**Comment by memberbetty** [comment]
That's exactly the same?

I'd try to detect the operating system and based on that render the version of interest with a link to other operating systems and show the operating system dependent version. 

Or, simpler:  `dd bs=1000000 if=nix.iso of=/dev/rdiskN`. Additionally, I would display the version of the command pointing at the latest graphical stable iso.

**Comment by vcunat** [comment]
> That's exactly the same?

I guess the intention is to avoid using nix-installed `dd`, as that would be GNU one even if on macOS.

> I'd try to detect the operating system and based on that render the version of interest with a link to other operating systems and show the operating system dependent version.

I'm against that approach.  Detection like this is bad for "portability".  It's better to be explicit and provide system-specific section like we do now.  The line you refer to is in sub-section titled "On macOS".

**Comment by matthewbauer** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/54280
