### ISSUE TITLE
Powertop doesn't work out of the box

### ISSUE THREAD

**Issue by geerds** [NixOS/nixpkgs#5424]
Powertop doesn't work on my new Thinkpad T440s:
```
  unknown op '{'
  Model-specific registers (MSR) 
  not found (try enabling CONFIG_X86_MSR).
  read_msr cpu0 0xe8 : No such file or directory
```
I had to load the *msr* kernel module (```modprobe msr```) first to fix powertop. Now it works without issues. I don't know what to do. Is this a bug? Should *msr* loaded on all systems? or just thinkpads? or maybe just in the case of using powertop?

**Comment by axfelix** [comment]
I'm having the same issue on my new Dell Venue 11 Pro -- it completes the calibration run but it doesn't seem to actually save anything to the saved_parameters.powertop file, probably because when I try to exit I get the same corrupted double-linked list error (I get a different memory address after enabling msr but that doesn't fix it) and I have to close the terminal window as it won't respond to ^C. Would love to see this fixed since powertop is by far the most painless way to set up good battery settings on Linux nowadays!

**Comment by vcunat** [comment]
That linked-list corruption is most likely an upstream issue. I tried to find a place to report upstream, but I found none; I thought about writing to their mailing-list, but my Firefox will completely refuse to display the [link target](https://lists.01.org/mailman/listinfo/powertop) due to them using SSLv3. (And it's error during glibc finishing code, so backtrace won't say what corrupted the list.)

**Comment by catalin-hritcu** [comment]
Same problem as in the original post on a Thinkpad 440p running Arch Linux. Output looks a bit strange too:
```
  unknown op '{'
                Model-specific registers (MSR)			 not found (try enabling CONFIG_X86_MSR).
                                                                                                         read_msr cpu0 0xe8 : No such file or directory
```

**Comment by 7c6f434c** [comment]
Maybe ```modprobe msr``` would help?

**Comment by vcunat** [comment]
AFAIK this issue is only about whether that modprobe should be "automated" or not.

**Comment by andrewrk** [comment]
When I run `sudo powertop`, I get this broken output:

```
  unknown op '{'
                Model-specific registers (MSR)			 not found (try enabling CONFIG_X86_MSR).
                         read_msr cpu0 0xe8 : No such file or directory
```

And then it's back to the bash prompt but my terminal is all weird and scrolling just activates up and down key presses, like it does in `screen`.

nixos-version: 15.06pre64423.4e5e441 (Dingo)

[/etc/nixos/configuration.nix](https://github.com/andrewrk/dotfiles/blob/2388ce609d5b3d2a85fa18c2a3b9c4e664a678a5/nixconfigs/configuration.nix) (add powertop to the packages installed)

**Comment by dezgeg** [comment]
Powertop actually tries to load the module - via `/sbin/modprobe msr`, which doesn't work because there's no `/sbin/` on NixOS. We just need to patch the path to `modprobe`, which https://github.com/NixOS/nixpkgs/pull/8702 does.

**Comment by vcunat** [comment]
That corruption on exit still happens for me, but that wasn't the point of this ticket.

**Comment by nico202** [comment]
Should this be fixed? Because I`m experiencing it, and manually running modprobe works (nixos)

**Comment by vcunat** [comment]
@nico202: what nixpkgs/nixos version? (``$ nixos-version``) The fixing PR is contained in both 15.09 and unstable. I just retested that it loads the module automatically on 15.09.

**Comment by nico202** [comment]
nixos-version: 15.09.606.8dc5a16 (Dingo)
(upgraded from 14.09)

I tested it on another machine (same version) and it works.
