### ISSUE TITLE
Darwin llvm failure on staging-next 

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#54370]
## Issue description

cargo-release on hydra: https://hydra.nixos.org/build/87632918. The error from the llvm build:
> [ 88%] Building CXX object unittests/ADT/CMakeFiles/ADTTests.dir/OptionalTest.cpp.o
/tmp/nix-build-llvm-7.0.1.drv-0/llvm/unittests/ADT/OptionalTest.cpp:522:1: error: static_assert failed "Should be trivially copyable"
static_assert(std::is_trivially_copyable<Optional<int>>::value,
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

> ❯ git log --format=%H origin/master..origin/staging-next --grep llvm 
6d3ed732f8b7f712766a0dcb66ffa3cc2842a090
946be0ed9943c31071e84f657f1515ae63389d23
d6f401e132ebc9083c64dc2d7a7574344c49a9c9
f64843f0f7c0f90396a4d2794050dbd342a40358
5e2ac7e5fd246dfca0ec403617f27ec68a4a24ac
3054cbd3f2d80ba04bd7142bbff122d314c8c167

cc @NixOS/darwin-maintainers 

ping https://github.com/NixOS/nixpkgs/pull/54306

**Comment by dtzWill** [comment]
Maybe if Darwin used a newer toolchain this wouldn't be a problem? :yum: 

See #49402 for some discussion re:why that hasn't happened yet-- seems easy fodder for anyone with a Darwin builder... :innocent:

But yeah this can't stand obviously :).

-----

FWIW anyone using a clang/libcxx stdenv and upgrades past LLVM 5 will no longer be able to build Nix itself-- due to its use of Optional and libcxx's stance on what "experimental" means.  Long known issue but hasn't been causing enough problems to motivate fixing just yet I think :).

**Comment by dtzWill** [comment]
Speaking of Optional, that's the cause of this failure (not for the reasons I mentioned re:Nix, that's something probably best "fixed" in Nix itself)-- and haven't checked but since the fix for crashery (#54122) patches LLVM's Optional header ... that sure seems like the culprit.  Since this was the patch proposed by upstream for use I wonder what's wrong? And sorry for the breakage! :3
