### ISSUE TITLE
Stripping in stdenv should not ignore errors

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#5447]
Ignoring errors is a source of non-determinism. E.g. if the disk is full:

```
strip:/nix/store/8zwj00xk91rl30g532pq00xvvnkvm58d-opencollada-1.3-18da7f4109a8eafaa290a33f5550501cc4c8bae8/lib/opencollada/steBji1n: No space left on device
strip: cannot create tempdir for archive copying (error: No space left on device)
```

after which the build succeeds, but with a different result than if the disk had not been full.

**Comment by zimbatm** [comment]
I guess the issue here is that it would also add a lot of work for the packager to specify which programs should be strippable or not right ? I'm not even sure if we have a framework to list all the executables and libraries that a package is supposed to produce.

Stopping to ignore failures on strip is just a matter of removing `|| true` at the end of that line: https://github.com/NixOS/nixpkgs/blob/2def8e74990d89bd91b8943c00110027a1f5fafa/pkgs/build-support/setup-hooks/strip.sh#L33

**Comment by Profpatsch** [comment]
triage: it looks like this hasn’t been fixed yet?
