### ISSUE TITLE
aws-sdk-cpp is out of date in master

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#54546]
## Issue description

`1.7.39` is the newest available. Master is some `1.6.x`. 

If this could be added to the packages that are automatically updated by the semi-automated system of someone named Ryan that would be better.

**Comment by memberbetty** [comment]
@orivej-nixos Can this also be cherry picked to 18.09, because the version in 18.09 fails to build from source?

**Comment by orivej** [comment]
> If this could be added to the packages that are automatically updated by the semi-automated system of someone named Ryan that would be better.

It updates all packages in repology.org as long as the update can be built. It could not update aws-sdk-cpp from 1.6 to 1.7 because this required manual changes, but it should be able to update it going forward: https://repology.org/project/aws-sdk-cpp/versions

> Can this also be cherry picked to 18.09, because the version in 18.09 fails to build from source?

It seems that aws-sdk-cpp in release-18.09 does build: https://hydra.nixos.org/job/nixos/release-18.09/nixpkgs.aws-sdk-cpp.x86_64-linux, and I have confirmed this by rebuilding it. `aws-sdk-cpp` is a dependency of `nix` so I'm reluctant to update it without a good reason.

**Comment by memberbetty** [comment]
@orivej It doesn't build in a Nix container.

**Comment by orivej** [comment]
Could you show the error, and preferably describe how to reproduce it?
