### ISSUE TITLE
VM tests broken with 4.14 kernel on host

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#54876]
## Issue description

This weekend I upgraded some hydra.nixos.org machines (`t4a`, `t4b`) after a longer time to fresh 18.09 749a3a0d00b (kernel 4.14.95), and almost all VM tests running on them got broken by this.  Switching to 4.19 kernel resolved the problems.

The problems themselves were random errors appearing quickly anywhere: assertions, loader errors, kernel traces, etc. (different on each run) leading to the VM test failing or hanging.

**Comment by vcunat** [comment]
I'm not sure I'll put much work into this, but let me at least post it.  In case it was HW-related, the CPUs are Intel Ivy Bridge series.

**Comment by tfc** [comment]
Had the same problem on two NixOS 18.09 machines. 

This indeed appears to work again with `boot.kernelPackages = pkgs.linuxPackages_4_19;`, thx!

**Comment by Baughn** [comment]
4.14.97 may also be fixed; I see a lot of KVM bugfixes in the changelog.

**Comment by b333z** [comment]
Also experiencing boot failures & blue screens on some win vm's, our last known good is nixos/nixpkgs-channels@97e0d53d669, but think its just down to 4.14.93 is ok but .94 & .95 (and think we tried .96?) shows the issue for us.

Looking at the [v4.14.94 changelog](https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.94) I've wondered if https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=4124a4cff344abbf8187775eb643d9827830e715 might be the one (just because its the only non-arm, kvm related commit from a quick look), but been unable to test a revert on an effected system as yet to confirm.

**Comment by vcunat** [comment]
Both channels are at .97 ATM (with .98 in queue).  I can't reproduce the problem with .97, so I'll assume it was something broken and fixed upstream.
