### ISSUE TITLE
Package typora in nixpkgs is broken now

### ISSUE THREAD

**Issue by SchrodingerZhu** [NixOS/nixpkgs#55045]
## Issue description
Typora has updated its download info. Therefore, we need to update typora package now.

## Technical details
The new download address should be `https://typora.io/linux/Typora-linux-x64.tar.gz`. However, I haven't tested whether other configurations is still functioning.

**Comment by dotlambda** [comment]
cc @worldofpeace who last touched the expression

**Comment by worldofpeace** [comment]
`https://typora.io/linux/Typora-linux-x64.tar.gz` has no version in the url so it isn't stable.
The current url that is in use is `https://www.typora.io/linux/typora_${version}_amd64.deb` and the latest archive is fine.

In #54848 I noted that the current build was failing with 404 because they removed the old archive.

Perhaps we need to backport because that archive is gone.

**Comment by worldofpeace** [comment]
Backported the update in 7e15417e42319563528b73063af45e59236f33d3.
