### ISSUE TITLE
cmake is outdated

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#55060]
## Issue description

The current version of `cmake` in `nixpkgs` is 3.12.1 (and there's a PR to bump this to 3.12.2 - https://github.com/NixOS/nixpkgs/pull/54836) but the current version of CMake is 3.13.3. In fact, CMake 3.13.0 came out over 2 months ago. I skimmed the 3.13.0 release notes and nothing jumps out at me as being backwards-incompatible (though I barely know CMake so I could be missing something).

CC @ttuegel @lnl7

**Comment by luzpaz** [comment]
3.13.4 is actually the current version  
https://cmake.org/cmake/help/v3.13/release/3.13.html#id19

**Comment by stites** [comment]
I don't mind bumping #54836 to 3.13.4. I'm primarily interested in fixing my libtorch build on nixos, but I can't yet confirm that everything builds correctly on 3.13 (in fact I'm getting the same error as referenced before when moving back to Ubuntu with an updated cmake). I'm doing some rebuilds this week and I'll doublecheck bumping to the latest current cmake (since I have everything set up already).

**Comment by stites** [comment]
`3.13.4` is now in staging! I think this means we can close this issue.
