### ISSUE TITLE
 steam "browse local files" won't work

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#55128]
## Issue description

In my case, steam stdout/err displays
```
/usr/bin/xdg-open: line 810: : command not found
/usr/bin/xdg-open: line 880: qutebrowser: command not found
/usr/bin/xdg-open: line 880: qutebrowser: command not found
xdg-open: no method available for opening '/home/teto/.local/share/Steam/steamapps/common/Into the Breach'

```

### Steps to reproduce
in steam. right click "properties" on a game, then select the "Local files" tab and finally click on "browse local files". 

## Technical details
nixos-unstable

**Comment by davidak** [comment]
In my case (Pantheon desktop), i see this error in terminal:

```
/run/current-system/sw/bin/io.elementary.files: /steamrt/amd64/usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0: no version information available (required by /nix/store/yv1pq8q93bamcrgddl35ps26n7kd0jzn-tracker-3.1.1/lib/libtracker-sparql-3.0.so.0)
/run/current-system/sw/bin/io.elementary.files: symbol lookup error: /nix/store/yv1pq8q93bamcrgddl35ps26n7kd0jzn-tracker-3.1.1/lib/libtracker-sparql-3.0.so.0: undefined symbol: json_generator_to_gstring, version libjson-glib-1.0.so.0
```

Linux 5.12.2, NixOS, 21.05.git.db0294aa60c (Okapi)

**Comment by davidak** [comment]
I now see this issue, but i don't have the latest unstable version.

`/run/current-system/sw/bin/io.elementary.videos: /steamrt/amd64/usr/lib/x86_64-linux-gnu/libelf.so.1: version 'ELFUTILS_1.7' not found (required by /nix/store/i6h39r49c14c0g2sahs3wngnxxqqaa0a-elfutils-0.182/lib/libdw.so.1)`

Is it fixed in the latest version?
