### ISSUE TITLE
Infinite recursion on "pkgs" caused by hardware/video/amdgpu-pro.nix and hardware/video/ati.nix

### ISSUE THREAD

**Issue by johanot** [NixOS/nixpkgs#55199]
## Issue description
Both of the below example gists causes `infinite recursion encountered, at nixpkgs/lib/modules.nix:336:9`

https://gist.github.com/srhb/56f8efa1798ae25be3ae7f41432427e3
https://gist.github.com/johanot/6df3e8a4028766ccd19b6a6f3874e426

The `vmware-guest` module sets `xserver.videoDrivers` and `xserver.videoDrivers` is queried by video driver modules.

The root cause seems to be that modules: `hardware/video/ati.nix` and `hardware/video/amdgpu-pro.nix` modifies `nixpkgs.config.xorg.abiCompat` and thus causes recursion on `pkgs`. (thanks to @srhb)

It seems wrong that these modules can cause those failures at such very unrelated locations, but I don't know enough about the module system nor the mentioned modules in particular to suggest how to fix the issues - or whether they are even fixable.

### Steps to reproduce

`nix-instantiate` the gists mentioned above. 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.81, NixOS, 18.09.1373.50fb6820759 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`

**Comment by adamtulinius** [comment]
The same appears to happen just by setting `services.xserver.enabled = true`:
https://gist.github.com/adamtulinius/98cc6dd4018bdf82e7302135f9a2b5c3

the `xserver`-module also modifies `nixpkgs.config.xorg.abiCompat`, among others.

**Comment by Infinisil** [comment]
Doesn't seem to be a problem anymore, I'm not getting infinite recursion with @johanot's or @adamtulinius's gists (though I do with @srhb's, but that's due to https://github.com/NixOS/nixpkgs/issues/19899).

I suspect that at that time, `nix-instantiate` evaluated attribute sets recursively, which it might not do anymore. I've been using `nix-instantiate <file> -A config.system.build.toplevel` to test, setting
```nix
{
    fileSystems."/".device = "test";
    boot.loader.grub.device = "nodev";
}
```

to fix the assertions.

Feel free to say so if this is still a problem (but this needs a better repro then). For now I'll close this
