### ISSUE TITLE
API_ID_PUBLISHED_FLOOD at Telegram Desktop (api_id override?)

### ISSUE THREAD

**Issue by chekoopa** [NixOS/nixpkgs#55271]
## Issue description

The issue and not nixos-related solution are described here in detail: https://github.com/telegramdesktop/tdesktop/issues/4717

The problem is an `API_ID_PUBLISHED_FLOOD` error on any login, which is caused by 'compromised' `api_id`, which AFAIK is being produced at per-user basis and not intended to be used by distro maintainers.

There's not much disk space and confidence to keep unstable channel constantly upgraded just because of one particular parameter.

I suggest implementing an override for the `tdesktop` package, which enables for users to provide their own `api_id` and `api_hash` just to comply with Telegram's terms of use.

### Steps to reproduce

- install `tdesktop` from stable or unstable channel
- try logging in with your phone number

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.14, NixOS, 19.03pre166331.f9bd1533773 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-18.09.1922.97e0d53d669, nixpkgs-19.03pre166331.f9bd1533773"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
cc @primeos @abbradar @garbas

**Comment by primeos** [comment]
Thanks for bringing this up. I was hoping this would be fine for now and it's good to know that it causes some problems (again...).

### Regarding the current situation

Unfortunately, the current way of obtaining an API ID doesn't work well for Linux distributions:
1) The API ID must be tied to a personal account (phone number) and we cannot request one for NixOS (I've tried to contact the Telegram team via multiple channels without any success so far...).
2) https://my.telegram.org/apps states: "It is forbidden to pass this value to third parties." which would obviously be a requirement for us (to put it into `nixpkgs`).

The following options would be available:
1) We use the extracted API ID from Telegram Desktop: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/telegram-desktop&id=c60c8767fdc5876b4a990bac80404e88fd9b52c4
2) We use the API ID from Debian (wouldn't do that without their approval): https://salsa.debian.org/debian/telegram-desktop/commit/fc149cad60ffdd5475290520f29b02fdcebc2480
3) Someone (community member) provides an API ID for NixOS.

But since none of the above options is really satisfying / legally correct I decided to kept the default API ID for now.

### Regarding your comment

> There's not much disk space and confidence to keep unstable channel constantly upgraded just because of one particular parameter.

Not sure what you mean by that.

> I suggest implementing an override for the `tdesktop` package, which enables for users to provide their own `api_id` and `api_hash` just to comply with Telegram's terms of use.

That would certainly be possible (no objections), but (IIRC) the `api_id` and `api_hash` are currently always statically compiled into Telegram Desktop, which can easily take 30-60 minutes to compile (depending on the machine). To make this a viable option we'd have to write a custom patch to e.g. read these parameters at run-time from a file (and use a wrapper to avoid having to recompile everything).

**Comment by veprbl** [comment]
> 2\. https://my.telegram.org/apps states: "It is forbidden to pass this value to third parties." which would obviously be a requirement for us (to put it into `nixpkgs`).

I don't think they meant it that way. It would make all unofficial clients non-redistributable (it is guaranteed that the user can always fish out a key from a binary). We can't make keys to give out to third parties, but we should be able to keys for ourselves.

**Comment by primeos** [comment]
I'll try to find a solution that works well for NixOS and other Linux distributions in general.

**Comment by ilya-fedin** [comment]
There are also snap/flatpak API_ID
https://github.com/telegramdesktop/tdesktop/blob/8fab9167beb2407c1153930ed03a4badd0c2b59f/snap/snapcraft.yaml#L87-L88
https://github.com/flathub/org.telegram.desktop/blob/06964246f7a7678a421753b6639523ddb5ef650f/org.telegram.desktop.json#L161-L162

**Comment by primeos** [comment]
@ilya-fedin thanks, I've added both links to my list for completeness :)

Regarding this issue: I've unassigned myself as unfortunately I don't see a nice way forward. "Telegram" doesn't seem open at all to communicate with Linux distributions, which is sad...

I'm open for suggestions, PRs, etc. if someone has an idea, but personally I'm out of good ideas (and I'd like to avoid using a personal API ID, at least my own one). I guess one could also ask the maintainers of other distributions if they're using a personal API ID (linked to their phone number) or managed to request one for their Linux distribution.

**Comment by kipcd** [comment]
Still the same issue on Arch linux and package community/telegram-desktop 2.2.0-2

**Comment by Sanaebadi97** [comment]
Using Telegram's open source code
Everyone is welcome to use our open source code. We have included a sample API id with the code. This API id is limited on the server side and is not suitable for apps released to end-users — using it for anything but testing purposes will result in the API_ID_PUBLISHED_FLOOD error for your users. It is necessary that you obtain your own API id before you publish your app.


https://core.telegram.org/api/obtaining_api_id
