### ISSUE TITLE
NixOS Manual is wrong. How to install?

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55332]
## Issue description

My motherboard uses UEFI, not BIOS, but the NixOS installer gives this error:
```
[root@nixos:~]# nixos-install
building the configuration in /mnt/etc/nixos/configuration.nix...
error: 
Failed assertions:
- You must set the option ‘boot.loader.grub.devices’ or 'boot.loader.grub.mirroredBoots' to make the system bootable.
(use '--show-trace' to show detailed location information)
```

Following the instructions [here](https://itsfoss.com/check-uefi-or-bios/) to see if the system is UEFI or BIOS , there is no such folder as "/sys/firmware/efi" . How is this possible?

> Check if you are using UEFI or BIOS on Linux
>
> The easiest way to find out if you are running UEFI or BIOS is to look for a folder /sys/firmware/efi. The folder will be missing if your system is using BIOS.

After doing what the error message tells me, it tries to install NixOS, but fails a different way:

```
[root@nixos:~]# nixos-install                        
building the configuration in /mnt/etc/nixos/configuration.nix...
[168 built, 375 copied (1556.3 MiB), 7.5 MiB DL]
copying channel...
installing the boot loader...
setting up /etc...
Initializing machine ID from random generator.
updating GRUB 2 menu...
mktemp: failed to create directory via template ‘/tmp/os-prober.XXXXXX’: No such file or directory
grub-probe: error: cannot find a GRUB drive for /dev/sda1.  Check your device.map.
mktemp: failed to create directory via template ‘/tmp/os-prober.XXXXXX’: No such file or directory
Found Windows 10 on /dev/sdc1
installing the GRUB 2 boot loader on /dev/nvme0n1...
Installing for i386-pc platform.
/nix/store/zgcj53sxwri8wjm7zxw82c8cv67qjwfn-grub-2.02/sbin/grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
/nix/store/zgcj53sxwri8wjm7zxw82c8cv67qjwfn-grub-2.02/sbin/grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
/nix/store/zgcj53sxwri8wjm7zxw82c8cv67qjwfn-grub-2.02/sbin/grub-install: error: will not proceed with blocklists.
/nix/store/qn1321bzrc0v9pzyznmhw0zvj8p8dnyi-install-grub.pl: installation of GRUB on /dev/nvme0n1 failed
```

## Technical details

I have ASrock Z170m Pro4s motherboard
https://www.asrock.com/mb/Intel/Z170M%20Pro4S/

**Comment by orivej** [comment]
I think you need:
```
boot.loader.grub.devices = [ "/dev/nvme0n1" ];
boot.loader.grub.efiSupport = true;
```

**Comment by AMDphreak** [comment]
> I think you need:
> 
> ```
> boot.loader.grub.devices = [ "/dev/nvme0n1" ];
> boot.loader.grub.efiSupport = true;
> ```

OK I tried this and got:
```
[root@nixos:~]# nixos-install
building the configuration in /mnt/etc/nixos/configuration.nix...
[3 built, 3 copied (27.8 MiB), 0.0 MiB DL]
copying channel...
installing the boot loader...
setting up /etc...
updating GRUB 2 menu...
mktemp: failed to create directory via template ‘/tmp/os-prober.XXXXXX’: No such file or directory
grub-probe: error: cannot find a GRUB drive for /dev/sda1.  Check your device.map.
installing the GRUB 2 boot loader on /dev/nvme0n1...
Installing for i386-pc platform.
/nix/store/zgcj53sxwri8wjm7zxw82c8cv67qjwfn-grub-2.02/sbin/grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
/nix/store/zgcj53sxwri8wjm7zxw82c8cv67qjwfn-grub-2.02/sbin/grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
/nix/store/zgcj53sxwri8wjm7zxw82c8cv67qjwfn-grub-2.02/sbin/grub-install: error: will not proceed with blocklists.
/nix/store/qn1321bzrc0v9pzyznmhw0zvj8p8dnyi-install-grub.pl: installation of GRUB on /dev/nvme0n1 failed
```
I have to mention, I have the OS prober activated in the config file:
```
boot.loader.grub.useOSProber = true;
```

**Comment by AMDphreak** [comment]
I got it to work by setting 
```
  boot.loader.grub.device = "nodev";
```

This is obnoxiously inconsistent with what the manual dictates. This exception needs to be explained in the manual. In fact I have zero clue what it really does and why to use it. The auto-generated configuration.nix file has it in the same line as the setting:
```
  boot.loader.grub.device = "nodev"; # or "nodev" for efi only
```

**Comment by AMDphreak** [comment]
Reopening the issue because this needs to be updated in the NixOS Manual

**Comment by orivej** [comment]
If there is no `/sys/firmware/efi` and `boot.loader.systemd-boot.enable` was not generated, then you have probably booted the installer in BIOS mode. `boot.loader.efi.canTouchEfiVariables` will have no effect because EFI variables do not exist in this mode. To boot in EFI mode, you can try one of these:
- after powering on, press a key to choose the boot device (some motherboards show two entries for the installer, one BIOS and one EFI)
- enter system setup and disable BIOS boot, legacy boot, legacy boot compatibility etc.
- wipe BIOS boot record on the installer: ` dd if=/dev/zero of=/dev/_?_ bs=446 count=1`: https://unix.stackexchange.com/a/71390/182445

**Comment by AMDphreak** [comment]
What *is* BIOS mode on a UEFI machine, anyway, and *how* does it get invoked?

**Comment by orivej** [comment]
> What is BIOS mode on a UEFI machine, anyway, and how does it get invoked?

EFI computers support booting BIOS operating systems by providing BIOS services to the OS. They choose which services to provide, BIOS or EFI, based on the following considerations:
- if the last two bytes of the MBR, which is the first 512 bytes of the disk, are 0x55 0xAA, then it is considered BIOS-bootable
- if the partition table of the disk contains a partition of type EFI System, then it is considered EFI-bootable

The NixOS installer meets both criteria to support both types of boot.

> The installer's boot menu only shows these options

I meant the boot disk selection menu. On the third screenshot [here](https://www.asus.com/support/FAQ/1030858/), the motherboard offers EFI boot of the ST2000DX01 disk as the first option, and BIOS boot of the same disk as the third option.

> The manual mentions CSM (Compatibility Support Module), but this option was removed in the updated UEFI.

[Here](http://forum.asrock.com/forum_posts.asp?TID=3096&title=no-csm-option-extreme7) a user reports that they did not have the CSM option until they updated the firmware.

So, you can try any of these options:
- use the EFI entry in the boot disk selection menu if it presents two entries for the installer; your motherboard manual does not mention how to enter this menu, but you could try enabling Boot Manager, or disabling Full Screen Logo, since it may obscure the key to enter the menu
- boot the installer in BIOS mode, wipe the BIOS support indicator from the disk with the installer with `dd bs=1 count=2 seek=510 if=/dev/zero of=/dev/?` (where `?` is `sd?` or `nvme?n?`; look at the output of `mount` or `blkid `), then boot the installer again
- update firmware, disable CSM, then install (after installation you can probably enable CSM back, it won't matter)
- just install in the BIOS mode by following the manual for BIOS systems (then it will not boot if you later disable CSM)

**Comment by AMDphreak** [comment]
Thank you @orivej

**Comment by luisnquin** [comment]
> I got it to work by setting
> 
> ```
>   boot.loader.grub.device = "nodev";
> ```
> 
> This is obnoxiously inconsistent with what the manual dictates. This exception needs to be explained in the manual. In fact I have zero clue what it really does and why to use it. The auto-generated configuration.nix file has it in the same line as the setting:
> 
> ```
>   boot.loader.grub.device = "nodev"; # or "nodev" for efi only
> ```

Thank you very much!

**Comment by aboode95** [comment]
> boot.loader.efi.canTouchEfiVariables = true;

Thank you! This solved an issue that I was having regarding new generations not being added to GRUB menu or new generations not being booted into. I had posted about this issue on [NixOS discourse here](https://discourse.nixos.org/t/nixos-rebuild-switch-isnt-updating-the-grub-menu-with-new-generations/49650?u=aboode95).
