### ISSUE TITLE
lua51Packages builds failing on macOS

### ISSUE THREAD

**Issue by n4074** [NixOS/nixpkgs#55553]
## Issue description

I am unable to build a number of lua51Packages derivations from nixpkgs, on my macOS Mojave machine. I am encountering this issue trying to build _neovim_, where building the dependency _lua51Packages.mpack_ fails with the following output:

```
building '/nix/store/j3kxs4milv1h3dbihicw290lbqgbdyq6-lua5.1-mpack-1.0.7-0.drv'...
unpacking sources
unpacking source archive /nix/store/w1xca9032cbmmmq9437bsg6kh0l6k184-mpack-1.0.7-0.src.rock
sh: sw_vers: command not found
Warning: The directory '/homeless-shelter/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /nix/store/nsv1ary2r6g3m0sbi7zfxhnqp5mg986m-luarocks-2.4.4/bin/.luarocks-wrapped with sudo, you may want sudo's -H flag.

Done. You may now enter directory
mpack-1.0.7-0/libmpack-lua-1.0.7
and type 'luarocks make' to build.
source root is ./mpack-1.0.7-0/libmpack-lua-1.0.7
chmod: --: No such file or directory
builder for '/nix/store/j3kxs4milv1h3dbihicw290lbqgbdyq6-lua5.1-mpack-1.0.7-0.drv' failed with exit code 1
error: build of '/nix/store/j3kxs4milv1h3dbihicw290lbqgbdyq6-lua5.1-mpack-1.0.7-0.drv' failed
```

The issue starts to occur from commit 2ba891788bacfb2c52f25a7a119b88c6cc298e35. I encounter the same error with other packages such as _lua51Packages.ansicolor_ and _lua51Packages.argparse_.

### Steps to reproduce

`nix-env -f "<nixpkgs>" -iA lua51Packages.mpack`

## Technical details

```
➜ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(user): `"nixpkgs-19.03pre168808.b8d7c0cab5e, nixos-17.09-17.09.3269.14f9ee66e63"`
 - nixpkgs: `/Users/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by teto** [comment]
There are now 2 versions of lua mpack in nixpkgs, the one from luarocks and the old one. In principle, I shouldn't have added the new one but seems like I made a mistake. If you remove the mpack derivaiton in pkgs/development/lua-modules/generated-packages.nix, it should fix your problem.

 am not familiar with macOS so I could use some help. Luarocks runs this command on macos
```
   if cfg.is_platform("macosx") and rockspec:format_is_at_least("3.0") and target then
      local version = util.popen_read("sw_vers -productVersion")
```
and sw_vers is not in PATH, It should be added for the macOS platform (not sure how). Seems like it is replaced in other packages by:
 ` substituteInPlace certbot/util.py --replace "sw_vers" "/usr/bin/sw_vers"`


Then there is the bad chmod which might be fixed by solving the first problem. 
```
source root is ./mpack-1.0.7-0/libmpack-lua-1.0.7
chmod: --: No such file or directory
```
If not, might be interesting to add a `set -x` or set NIX_DEBUG=8 in the mpack derivation to see where it happens.

**Comment by LnL7** [comment]
We have sw_vers in nixpkgs, but we shouldn't use it. Since we want to keep builds stable across macOS releases we generally replace these calls with a constant instead.
