### ISSUE TITLE
tarball job broken

### ISSUE THREAD

**Issue by iElectric** [NixOS/nixpkgs#5559]
See travis: https://travis-ci.org/NixOS/nixpkgs/builds/45786579

cc maintainers @madjar @cstrahan @wizeman

**Comment by madjar** [comment]
Another ``stdenv.gcc`` problem, or maybe ``stdenv.gcc.binutils`` in that case. Why did all those problems start appearing suddently?

**Comment by iElectric** [comment]
It should be `${stdenv.cc.gcc}` for linux

**Comment by vcunat** [comment]
@madjar: these are after #5392.

**Comment by madjar** [comment]
Mmm, I somehow linked to an older version of the file. This is indeed `${stdenv.cc.gcc}` (https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/rustc/head.nix#L70).

**Comment by madjar** [comment]
So, the problem comes from `stdenv.cc.binutils`, but rust isn't meant to work on i686-freebsd anyway (there is no snapshot to bootstrap from). When I solve the first problem, evalution fails on an abort.

I'm kind of lost. What would be the right way to make it not work on i686-freebsd without breaking the evaluation?

**Comment by iElectric** [comment]
Done, thanks!

**Comment by madjar** [comment]
Oh, so assert is not equivalent to a conditional abort. Thanks!
