### ISSUE TITLE
Set `allowUnfree = true` by default and change name

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55616]
## Issue description

Users should be allowed to lock themselves down if they feel vulnerable but this should not be imposed by default. Users decide who they trust.

**Naming**
The naming is inconsistent with the attitude of users when deciding to lock themselves down. Rename this to `restrictUnfree` or `disallowUnfree`.

`restrictUnfree = false;`

Psychologically, imposing `allowUnfree = false` by default is a negative experience, locking the user down, much like Apple locks users' into their App Store and prevents them from using unapproved sources.

**A more accurate approach**
It would be more accurate to have this as a function call, `restrictUnfree` or `restrictUnfree()`. A lisp-like syntax would make sense in this context: `(restrictUnfree)`. Not an easy change, but could be an idea.

**Comment by AMDphreak** [comment]
Unfree software is unintuitively hidden for new users #17126

**Comment by 7c6f434c** [comment]
The problem is that there are different contexts that use different configurations. Making sure you enabled unfree software in the correct context is easy — installation works. Making sure you have disabled unfree software in all contexts is more complicated.

(Search not working by default is indeed a legitimate bug)

**Comment by AMDphreak** [comment]
> The problem is that there are different contexts that use different configurations. Making sure you enabled unfree software in the correct context is easy — installation works. Making sure you have disabled unfree software in all contexts is more complicated.
> 
> (Search not working by default is indeed a legitimate bug)

Really I have no idea what your'e trying to say. If you are trying to say that the defaults are easier to program, and you say that making sure you have disabled unfree software in all contexts is more complicated, then you have contradicted your own argument.

Free software is a subset of all software. This is about getting out of the way of the user so the user can access what they need when they need it without undue process. `allowUnfree` is a twisted version of a security feature. If you don't like unfree software, then don't use it, but don't push that decision onto every other user.

**Comment by CrazedProgrammer** [comment]
I agree that searching for unfree software should work without issue.  
However, I strongly disagree with setting allowUnfree = true by default, because that makes NixOS unsafe to use in commercial installations if users don't pay attention to this option. It would be easy to violate an unfree license by installing unfree software in this scenario.

**Comment by 7c6f434c** [comment]
Are there any arguments why this issue should not be closed as the main discussion is in #17126 ?

I forecast that the changes requested in the present issue will not happen as decribed at least in the next year (by March 2020) without an RFC. (I also find it more probable that such an RFC will get rejected than accepted, but with slightly less confidence)

Maybe some request about discoverability of #17126 should be made there — not sure what kind of request

**Comment by grahamc** [comment]
I think I can conclusively say we will not simply allowUnfree = true by default. Probably should continue discussion on the thread this PR came from.

**Comment by AMDphreak** [comment]
> However, I strongly disagree with setting allowUnfree = true by default, because that makes NixOS unsafe to use in commercial installations if users don't pay attention to this option. It would be easy to violate an unfree license by installing unfree software in this scenario.

This is partly true, but you forget that every person deploying this for business purposes will already be familiar with NixOS, and will go looking for this setting to avoid patent violations. You're putting the burden of research on new users, to whom this feature is an annoyance. Like I've said before, the feature is there for those who need it, but should not be forced on those who don't. I repeat: it is a *feature* for a few but an annoyance for *everybody* else. If you truly want NixOS to thrive, you need to make it hospitable for new users, not developers who are already familiar with NixOS. If this were a docker deployment, then, sure, you could have it on by default when the docker build is made (granted, I don't know much about docker). If this is a host operating system in a server environment, then the administrator should have used this OS on a personal basis and become familiar with its main concepts and can look for useful features. But in order for NixOS to attract new talent, you've stepped squarely out of the realm of deployment and squarely into the realm of marketing. NixOS must be marketed as a personal asset, not just some digital industrial machinery. That is a huge mistake that Unix/Linux developers rarely get through their heads. Do you want to know why Ubuntu is so popular and has so much funding and is the de-facto recommendation for new users? Because they finally made it an asset to a new user. NixOS is not a niche product. It is a fundamental rewrite of the existing way that things are done. It is a competitor, not a complementary piece of software, so it must steal competition in order to stay alive. In order to steal competition, you have to do two things:

1. provide an advantage (the package manager) and 
2. make it accessible to new-comers

Unix/Linux people have always had trouble grasping the concept of accessibility as the life-blood of software. (This is why the legendary LaTeX project is effectively dead, and why Firefox is not). Go read any research article on market competition and it shows that for the vast majority of users, point number 2 above, which is termed marketing and ease-of-use in the context of most products, is the critical decider in a product's longevity. It is the decider because it is consistent with human psychology: Intuition is the easy answer, while thinking is the hard answer. Read Daniel Kahneman's book, *Thinking, Fast and Slow* or just look at any behavioral economics resource online, including Wikipedia; you will find Kahneman and Tversky cited all over the place. There are only a small subset of people that actively fight against the intuitive easy answer to find an advantage. You can even tell how productive someone is at work, if you know whether they kept their OS's default browser or installed a 3rd party browser (source: https://www.ted.com/talks/adam_grant_the_surprising_habits_of_original_thinkers/transcript?language=en skip to 9:50). This effect is the same one driving product adoption. You have to fight to make yourself easy to use, in order to gain adoption.

Psychology of early adopters:
https://www.psychologytoday.com/us/blog/communication-central/201012/spreading-ideas-what-role-do-you-play

**Comment by 7c6f434c** [comment]
> the legendary LaTeX project is effectively dead

If being «dead» includes «very well-reputed person starts the list of reasons to suspect someone is wrong with ‘not using the product in question’» (speaking about the area where target audience works, of course, in case of TeX/LaTeX I mean https://www.scottaaronson.com/blog/?p=304 speaking about mathematics and theoretical computer science), maybe this is an OK state to target.

> Ubuntu has so much funding

… and net losses.

Profits seem to lie in having a desktop distro for advanced users, and doing business about server-based commercial services. I think Canonical also plans to go this way now.

> You can even tell how productive someone is at work, if you know whether they kept their OS's default browser or installed a 3rd party browser

So, you say that Nixpkgs is still in the stage where we can only attract some of the productive people, but not unproductive ones?

> Ubuntu is so popular

Because they actually invested in user support. In various expensive ways that do not scale well without huge effort. Also, one can safely assume that an internal software development project started by Ubuntu will end up replaced with a project they were initially competing with. See Upstart, Mir, Unity.

Almost as if these were different sets of competences.

**Comment by alexeymuranov** [comment]
> This is why the legendary LaTeX project is effectively dead [...]

???
