### ISSUE TITLE
Package wants to write in home directory of wwwrun user

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#5575]
The home directory of the `wwwrun` user is /var/empty, which likely means that it has been designed to be empty.

I have a subservice (of apache) defined  which needs to be able to write its files in the home directory of the apache user (so, wwwrun), but I am not sure how that's supposed to be done in NixOS. That is, either I should modify the package to write somewhere else (I don't know whether this is feasible), or there is some standard NixOS method of dealing with this. So, I need a little advice on the right path to take. 

I also think this know-how should be documented in the nixpkgs contributors guide.

**Comment by bjornfor** [comment]
In the case of apache, you can set "services.httpd.user = ...".

Another option is to modify the subservice to write somewhere else. /var/lib/\<service\> or /run/\<service\> are typical places to write stuff.

Which sub-service are you running?

Documentation improvements are welcome :-)

**Comment by wwat** [comment]
I am trying to get Zoneminder to run, but I think it's rather difficult (having to patch various paths in zoneminder, initialising databases correctly, creating users, patching perl libraries, patching VLC, having to deal with undocumented NixOS parts, having to deal with bad error messages coming from Zoneminder, ... ). All in all a ridiculous amount of work, and I am beginning to consider to just bail. 

Speaking of which .... BedrockLinux appears to provide a really practical Linux experience, and then if NixOS could run below it, you wouldn't have to tell people that there are a limited amount of packages. I don't know whether BedrockLinux actually works, but if it does, it would be a great way to get rid of the "operating system X doesn't have version Y yet"-problem.

**Comment by paradigm** [comment]
NixOS technically works with Bedrock Linux, but it requires some additional
setup work compared to something like Debian or Arch with Bedrock Linux.  This
additional work is not documented, and support/testing of such a setup is very
limited at the moment.  More popular distros such as Debian and Arch are much
better documented and supported.  There is definitely interest in changing this
in the future (there's a good chance GoboLinux and NixOS may be added to the
Bedrock Linux documentation and QA cycle two Bedrock Linux releases
down-the-line) but it's not there yet.  Bedrock Linux developer man-hours are
aimed elsewhere at the moment.

Even when NixOS running in Bedrock Linux is ready for mass consumption, any
packages acquired from other distros would not have the slick Nix features.
For the end-users who are looking for Nix's strengths, a native Nix package
would be strongly preferable.  It'd also help strengthen and grow the Nix
community.  I expect it'd be better for the NixOS folks to encourage people to
make Nix packages and submit documentation improvements rather than redirect
them elsewhere.

I'm sure the Bedrock Linux community would love assistance figuring out the
necessary changes to ensure NixOS is well supported, documenting them, and
regularly testing them.  If you want to give that a try I certainly don't want
to discourage you.  However, that'd only help the Bedrock Linux community.
Improving documentation for NixOS and making Nix packages would help *both* the
Nix community and the Bedrock Linux community.  It sounds like the issues
you've raised here would be best remedied here.

**Comment by bjornfor** [comment]
@wwat: Which version did you try? I have attempted to package zoneminder before, but didn't finish it (too many issues). Now I downloaded the latest release (1.28.0) and updated my nix expression, but it tries to install stuff into polkit store path :-(

Anyway, I think this issue should be closed and we can discuss zoneminder in this existing issue: https://github.com/NixOS/nixpkgs/issues/5005

**Comment by wwat** [comment]
@bjornfor 1.28.0 and I already fixed that polkit store path issue on one of my systems. My latest issue is that zoneminder returns for `zmc -m 1` the exit status 11 (and I haven't looked at what it means yet). I do think it's rather bad for an application to exit without a good reason (and listing that reason).

**Comment by bjornfor** [comment]
Moving discussion to #5005, closing this.
