### ISSUE TITLE
Brackets will not run

### ISSUE THREAD

**Issue by AMDphreak** [NixOS/nixpkgs#55810]
## Issue description

installed with `nixos-rebuild test`

Error at runtime:
```
[root@nixos:/etc/nixos]# brackets
/run/current-system/sw/bin/brackets: error while loading shared libraries: libXdamage.so.1: cannot open shared object file: No such file or directory
```

## Technical details

```
[root@nixos:/drives]# nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev
copying path '/nix/store/ial8a56ys2rswfq4j2abm3cl99li5b6p-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.97, NixOS, 18.09.2108.8008d0bbc69 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2108.8008d0bbc69"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by peterhoeg** [comment]
It's a matter of adding the missing librar(y|ies) to ```bracketLibs```. Do you want to try a PR?

**Comment by AMDphreak** [comment]
> It's a matter of adding the missing librar(y|ies) to `bracketLibs`. Do you want to try a PR?

Yes! I know how to do git fork/PR, but I don't know the process for including a missing library. Can you teach me? I can sign up for a chat forum/slack/mattermost/Zulip/IRC. Btw Zulip is the best.

**Comment by peterhoeg** [comment]
Due to the time difference, it might be a bit difficult to find a time where we are both online but it basically boils down to:

1. find the relevant missing libraries (ldd on the binary is the easiest to get an overview)
2. find the corresponding derivation name in nixpkgs (in case of libxdamage it's ```xorg.libXdamage```)
3. add that to the ```bracketLibs``` list
4. build and see if it runs. If not, rinse and repeat until it does.
