### ISSUE TITLE
texLive: use more system packages

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#5586]
Watching the configure script scroll by, I noticed `checking for generic libraries to build... lua52 luajit libpng gd cairo teckit`. And sure enough, the bundle contains source for all those libraries (and more!), and the build proceeded to build all of those things, even though many of them already exist in nixpkgs. Is there a reason for this? What a terrifying build process!

**Comment by 7c6f434c** [comment]
>Watching the configure script scroll by, I noticed `checking for generic libraries to build... lua52 luajit libpng gd cairo teckit`. 

I am not sure I have watched this since I have written the expression
initially. There was enough to catch for this to slip by...

I guess you are right, it should be worth it to try passing these to
TeXLive build, I hope the build wouldn't fail as a few others where 
passing NixPkgs versions doesn't always work.

Are you willing to test-run a fixed build or will you wait until I get
to running this test?

**Comment by puffnfresh** [comment]
Wow :ghost:

**Comment by Mathnerd314** [comment]
This looks like it's been fixed in [texlive-new](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/bin.nix).

**Comment by vcunat** [comment]
Yes, I think so. I haven't re-used lua stuff, but it doesn't seem like it's recommended anyway. The rest should be system libs only now.
