### ISSUE TITLE
haskellPackages.djinn fails to build

### ISSUE THREAD

**Issue by cvoges12** [NixOS/nixpkgs#56024]
## Issue description

Both packages, `haskellPackages.djinn` and `djinn`, fails to build. 

### Steps to reproduce

Include package in `environment.systemPackages`.

## Technical details

* System: NixOS 18.09.1853.c2950341d03 (Jellyfish)
* Nix version: nix-env 2.1.3
* Nixpkgs version: 18.09.1853.c2950341d03
* Build error: [https://0x0.st/ziBd.txt](https://0x0.st/ziBd.txt)

**Comment by xaverdh** [comment]
There is an upstream [pull request](https://github.com/augustss/djinn/pull/8) that should fix this.
You can try compiling with different ghc versions (both ghc822 and ghc863 work for me).

**Comment by cvoges12** [comment]
@xaverdh How could I build djinn in the meantime with ghc863 and ghc822 not being part of the nixos 18.09 channel afaik?

**Comment by xaverdh** [comment]
You are sure, they are not available?
I didn't know that (I am on unstable).
So pkgs.haskell.ghc822 does not exist at all?

**Comment by cvoges12** [comment]
@xaverdh I just tried to include `haskell.ghc822` in my environment.systemPackages and the build error says `attibute 'ghc822' is missing`. I also checked the `nix search` for a similar name and did not find it there either.

**Comment by xaverdh** [comment]
Ah sorry it should be `pkgs.haskell.packages.ghc822` for the package set
and `pkgs.haskell.packages.ghc822.ghc` for the compiler.
So you can include `pkgs.haskell.packages.ghc822.ghc` in your systemPackages for example.
Also to get a shell with djinn you would use `pkgs.haskell.packages.ghc822.ghcWithPackages (ps: [ps.djinn])`

**Comment by xaverdh** [comment]
By the way, a convenient way to experiment with this stuff is `nix repl`.

**Comment by cvoges12** [comment]
@xaverdh 
I get this when including djinn and `pkgs.haskell.packages.ghc822` and `pkgs.haskell.packages.ghc822.ghc` in my systemPackages: [https://0x0.st/z-LG.txt](https://0x0.st/z-LG.txt). 

Here is the `--show-trace` as well: [https://0x0.st/z-Lk.txt](https://0x0.st/z-Lk.txt).

I am also curious as to why theses packages did not appear in `nix search ghc`.

**Comment by peti** [comment]
@cvoges12, have you read https://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure?

**Comment by cvoges12** [comment]
@peti Ah, I just noticed the, "but strangely enough normal Nix package lookups don’t seem to discover any of them, except for the default version of ghc."

**Comment by cvoges12** [comment]
@xaverdh I do not understand why I am receiving the error `[definition 3-entry 17]` when the 17th entry is `haskell.packages.ghc822` itself. When I remove the package (only including `haskell.packages.ghc822.ghc`) and try to rebuild (with collected garabage) I receive the following: [https://0x0.st/z-vn.txt](https://0x0.st/z-vn.txt).

**Comment by xaverdh** [comment]
I think thats due to missing brackets around an expression.

So let me clarifiy what I wrote up there:
If you want just the compiler ghc822 itself (as a binary), you can include haskell.packages.ghc822.ghc in your environment.systemPackages. If you want djinn (built with ghc822) in your path, add  haskell.packages.ghc822.djinn to environment.systemPackages.
If you want a temporary shell with djinn registered with ghc, you can use
nix-shell -p "haskell.packages.ghc822.ghcWithPackages (ps: [ ps.djinn ])".

The same should work with ghc863 instead of ghc822.

If I am not mistaken, you tried to include haskell.packages.ghc822.ghcWithPackages (ps: [ ps.djinn ]) in your environement.systemPackage, which needs to be put in brackets there (for syntactic reasons), like this :
(haskell.packages.ghc822.ghcWithPackages (ps: [ ps.djinn ]))

Doing that should be fine, and will give you a ghc822 binary in your path with the djinn package registered with ghc.

**Comment by xaverdh** [comment]
PS: Sorry about the confusion. I assumed more familiarity from your side with this stuff than I should have.

**Comment by cvoges12** [comment]
Thank you! It worked. Yes, I was confused and did not know to include `haskell.packages.ghc822.djinn`. Sorry for being not as knowledgeable as a should.
