### ISSUE TITLE
"src" does not accept option path variables as a parameter

### ISSUE THREAD

**Issue by neirenoir** [NixOS/nixpkgs#56023]
## Issue description
When attempting to set the src of a package to a non-literal path (say, a types.path option in a module config), Nix won't attempt to import the path the variable in src is pointing to into the Nix store. Mock example:
```
let cfg = config.programs.my-module;
in {
    pkgs.stdenv.mkDerivation rec {
        name = "my-package";
        src = cfg.customProfiles;
        buildCommand = ''cp -r $src/* $out/'';
    }

    options.programs.my-module = {
        my-option = mkOption {
            type = types.path;
            default = /etc/nixos/my-path; # Default or set, it is enough to fail 
        }
    }
}
```
The `cp -r` command will fail due to not being able to find /etc/nixos/my-path, because it has not been able to import it into the Nix store, and thus, it is not one of the inputs.

I guess this may be somewhat intended behaviour, but having an alternative for this would be very nice for some custom configs for certain programs (like firejail wrappers, which are useless for some programs since the last update, due to some default profiles being unsuitable). Maybe a builtin like fetchurl, but for paths (fetchpath?)?

**Comment by timor** [comment]
Nix behaves differently depending on whether `src` is a string (it will convert to path and copy to store) or a path (it will set `$src` to that external path, no importing). See this slightly dated but much more detailed and correct answer: https://stackoverflow.com/questions/43850371/when-does-a-nix-path-type-make-it-into-the-nix-store-and-when-not.

Maybe this here is related to what you are trying to achieve: https://github.com/NixOS/nix/issues/1528 ?

If you can provide a hash to your source, `requireFile` may be of help.

**Comment by shirona** [comment]
@timor It's not quite the same situation. I will explain my usecase more in depth:
- firejail is a sandboxing program that requires profiles or parameters to apply its sandboxing capabilities accordingly to the program at hand
- While this can all be done via parameters, the best way to do it is by writing profile files, that are pretty much equivalent to the parameters, but without the need of writing several hundred characters long commands
- These profiles are then loaded via `firejail --profile="/path/to/my/profile.profile" some-command`
- When loaded without the `--profile` option, firejail will attempt to find a suitable profile. This is usually /etc/firejail (it obeys the configure prefix, though, so in this case, it would be /nix/store/hash-firejail-version/etc/firejail/), where all the default profile files are saved. There, it tries to match any existing profile file with the passed command name (that would be: if we are executing `firejail firefox`, it would attempt to search for `$prefix/etc/firejail/firefox.profile`).
- However, not all default profiles are suitable. Your specific configuration may need extra or fewer parameters (in my case, I have some files in /media/data, which requires disabling the parameter `private-dev`), or you may need to configure `private-homes`(mounts a given directory as your $HOME directory, ideal for complete isolation), or it may be the case that the default profile doesn't work at all or breaks stuff (like is the case with Steam), thus, a way to modify profiles is required.
- Due to the way NixOS' firejail module (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/firejail.nix) generates the wrappers for the listed binaries (that is, without a way to configure a `--profile` option), it always attempts to load the default profiles, which means, for example, that wrapped Steam will never ever work.
- Thus, a functional, pure way of defining firejail profiles is needed (specially with how often Firejail profiles tend to break).

Now for the actual issue:
- I'm attempting to rewrite the module to allow user-defined profiles to be loaded.
- The way I want to do it is: the user lists the directory where they have custom profile files in `options.programs.firejail.customProfiles`. This is (hopefully) a directory full of firejail config files, named as `${command}.profile`. This is something probably every firejail user needs.
- I set up `options.programs.firejail.customProfiles` as `firejail-wrapped-binaries`' `src`, to import this user-defined, user-specific path into the store, to be able to build the package correctly.
- I then modified the buildCommand to copy the given `$src` into `$out/etc`, then generate the wrapper scripts accordingly by checking whether `${command}.profile` exists inside `$out/etc`. If it does, generate the wrapper script as `firejail --profile=$out/${command}.profile ${binary}`, rather than just `firejail ${binary}`.
- Upon building, I get that the route specified in `options.programs.firejail.customProfiles` (in my case, /etc/nixos/firejail-profiles/) was not found. This is because the route wasn't copied into the store, probably because the path is an option.
- The same script works if I replace `src = cfg.customProfiles` with anything else, even `src = let path = "/etc/nixos/firejail-profiles"; in path`, so the issue is being caused by the Option, I think. It's what I am using right now, which does the trick, except I have to maintain the whole derivation myself right now.

Declaratively loading user-defined config files into the Nix store without having to make them write their own derivation (or setting up their own webserver) is, I believe, a realistic usecase, which is why I tried to open this issue as generically as possible. I guess The Nix Way of solving this issue would be by writing a DSL for Nix which can generate program-specific config files, but alas, I am far from being Nix virtuoso yet to fork the module that way (although I admit it would be pretty cool).

**Comment by timor** [comment]
Thanks for the detailed explanation.

> Now for the actual issue:
> 
>     * I'm attempting to rewrite the module to allow user-defined profiles to be loaded.
> 
>     * The way I want to do it is: the user lists the directory where they have custom profile files in `options.programs.firejail.customProfiles`. This is (hopefully) a directory full of firejail config files, named as `${command}.profile`. This is something probably every firejail user needs.
>     * I set up `options.programs.firejail.customProfiles` as `firejail-wrapped-binaries`' `src`, to import this user-defined, user-specific path into the store, to be able to build the package correctly.

This is exactly the point.  Every source file which makes it into the store in in nixpkgs needs to have an associated hash which can be checked at evaluation time.  This has to hold for everything that is imported into the store, otherwise it would not be possible to get a reproducible build.  Someone correct me if I'm wrong, but that should also apply to nixos (the derivation).
 
>     * Upon building, I get that the route specified in `options.programs.firejail.customProfiles` (in my case, /etc/nixos/firejail-profiles/) was not found. This is because the route wasn't copied into the store, probably because the path is an option.
I think that has to do with how sandboxing is done during building.

> 
>     * The same script works if I replace `src = cfg.customProfiles` with anything else, even `src = let path = "/etc/nixos/firejail-profiles"; in path`, so the issue is being caused by the Option, I think. It's what I am using right now, which does the trick, except I have to maintain the whole derivation myself right now.
I still do think that this is related to the datatype (path vs. string).

>
> Declaratively loading user-defined config files into the Nix store without having to make them write their own derivation (or setting up their own webserver) is, I believe, a realistic usecase, which is why I tried to open this issue as generically as possible. I guess The Nix Way of solving this issue would be by writing a DSL for Nix which can generate program-specific config files, but alas, I am far from being Nix virtuoso yet to fork the module that way (although I admit it would be pretty cool).

Well, that DSL can be as simple as having the user specify an attribute set like
```nix
{
  program1 = ''
config here
 '';
  program2 = ''
config also here
 '';
}
```
iterating over that with `mapAttrs` and writing out the files with `writeTextFile` or something.

Note, however, that this is a common problem when you want to influence per-user config from the nixpkgs derivation.  Usually, people use something like home-manager to generate declarative per-user configurations.  So I guess it also depends on whether these profiles are something which is considered part of the system, or part of a user's profile.
