### ISSUE TITLE
Using connman with iwd is impossible due to incorrect assertion

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#56125]
## Issue description

connman built with iwd: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/connman/default.nix#L47
But module contains assertion that returns error when wpa_supplicant is disabled (enabling iwd disables wpa_supplicant): https://github.com/NixOS/nixpkgs/blob/63a09881b674e35a7e7a64951cd4b0f7e58be685/nixos/modules/services/networking/connman.nix#L76

**Comment by eadwu** [comment]
In `master`, the only supported way to use `iwd` is to use it as a standalone wireless daemon. Even if you assertion was disabled, it wouldn't make a difference, since the configurations don't allow for `iwd` to connect to `connman`. The default `iwd.service` is setup for `dbus` which differs from the one that is required [1]. Though it does look like it's relatively easy to enable `iwd` integration with the addition of two services, for now it might be better to just override the module manually on your local configuration.

[1] https://wiki.archlinux.org/index.php/ConnMan#Using_iwd_instead_of_wpa_supplicant

**Comment by dtzWill** [comment]
If someone ends up putting together the needed bits, please share (probably as a PR)!

Ive kludged network-manager into using iwd (kludge is needed for similar assertion and to not run iwd standalone, IIRC) but I'm keen to give connman a try :).

**Comment by stellarhoof** [comment]
FYI guys, ConnMan doesn't really keep up to date with iwd and integration between the two might lead to frustration. See
- [No iwd scan integration](https://lists.01.org/pipermail/iwd/2018-August/004717.html) and https://wiki.archlinux.org/index.php/ConnMan#Error_/net/connman/technology/wifi:_Not_supported
- [iwd issues in connman bug tracker](https://01.org/jira/browse/CM-693?jql=project%20%3D%20CM%20AND%20text%20~%20%22iwd%22%20ORDER%20BY%20created%20DESC)

**Comment by ilya-fedin** [comment]
NetworkManager is ugly and buggy

**Comment by stellarhoof** [comment]
I've been also using iwd without network manager just fine.

**Comment by ilya-fedin** [comment]
I'm thinking of writing a GUI for iwd - to use iwd + dhcpcd

**Comment by doronbehar** [comment]
Heads up for anyone interested iwd 1.0 was released with breaking changes, refs:

- https://github.com/NixOS/nixpkgs/pull/72321
- https://lists.01.org/hyperkitty/list/connman@lists.01.org/thread/OHP4UPBDN7LJ7MVUETL4DVM776YFFGLD/
