### ISSUE TITLE
Delete obsolete and/or broken GHC versions

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#5630]
The following GHC versions are unused and/or broken and should be deleted:

- pkgs/development/compilers/ghc/6.10.1-binary.nix
- pkgs/development/compilers/ghc/6.10.1.nix
- pkgs/development/compilers/ghc/6.10.2.nix
- pkgs/development/compilers/ghc/6.10.3.nix
- pkgs/development/compilers/ghc/6.11.nix
- pkgs/development/compilers/ghc/6.12.1-binary.nix
- pkgs/development/compilers/ghc/6.12.1.nix
- pkgs/development/compilers/ghc/6.12.2.nix
- pkgs/development/compilers/ghc/6.4.2-binary.nix
- pkgs/development/compilers/ghc/6.4.2.nix
- pkgs/development/compilers/ghc/6.6.1.nix
- pkgs/development/compilers/ghc/6.8.2.nix
- pkgs/development/compilers/ghc/6.8.3.nix
- pkgs/development/compilers/ghc/7.0.1.nix
- pkgs/development/compilers/ghc/7.0.2.nix
- pkgs/development/compilers/ghc/7.0.3.nix
- pkgs/development/compilers/ghc/7.2.1.nix
- pkgs/development/compilers/ghc/7.4.1.nix
- pkgs/development/compilers/ghc/7.6.1.nix
- pkgs/development/compilers/ghc/7.6.2.nix
- pkgs/development/compilers/ghc/7.8.3-binary.nix

**Comment by puffnfresh** [comment]
We should also add 7.10-RC1

**Comment by copumpkin** [comment]
@peti mind if we revive 7.8.3-binary? @joelteon and I are using it for bootstrapping 7.8.4 in our pure-darwin branch, which we'll soon be starting to merge back to master. 7.8.3-binary is a lot friendlier to us because it supports a clang backend, which happens to be all we can provide. The 7.4-based bootstrap would involve a bunch of shims to pretend clang is gcc again, and that sounds painful. 

We don't necessarily need it in master right now, but we'll likely want to revive it when we merge back from pure-darwin unless you have better suggestions.

**Comment by peti** [comment]
@copumpkin, according to @gridaphobe's comments in https://github.com/NixOS/nixpkgs/pull/5792 and https://github.com/NixOS/nixpkgs/pull/5746, we can build GHC 7.8.4 with Clang just fine in `master` already with 7.4.2-binary.

**Comment by copumpkin** [comment]
Okay, will talk with @gridaphobe, since I was under the impression that it'd be more painful. Thanks for the pointers!
