### ISSUE TITLE
Use a newer transformers/mtl than the one bundled with GHC

### ISSUE THREAD

**Issue by k0ral** [NixOS/nixpkgs#5649]
The latest GHC (7.8.4) is bundled with `transformers-0.3`, while `transformers-0.4` has been out for a while.
As a consequence, by default, all haskell packages are built with an old `transformers`, notably the binaries provided by hydra. It makes your life difficult when you want to build a package with a newer `transformers`/`mtl`, since all its dependencies will be built with the old one, resulting in a message like this (from cabal):

```
Warning: This package indirectly depends on multiple versions of the same
package. This is highly likely to cause a compile failure.
package my-package-x.y requires mtl-2.2.1
package a-dependency-of-my-package-x.y requires mtl-2.1.3.1
```

I suppose I should override the `ghcPrefs` in `haskell-defaults.nix` to point to the latest `mtl`/`transformers`, but it feels really wrong. It seems like a regression compared to my old `cabal-install`-based workflow, where I always got the latest `mtl`/`transformers` for free.

Is there a trick I have missed to fix that ?

**Comment by peti** [comment]
`transformers` is a core package of GHC, and other GHC core packages are linked to it. This means that you cannot compile any non-trivial binary with a version of transformers other than the one shipped with GHC, because if you do, you end up pulling in two distinct versions of transformers into the same binary. The `ghc` refers to practically every other core package, for example, and almost all test suites need that library these days to run `doctest` and the like.

Note that this is not a Nix-specific issue. You'll have the exact same problem if you're compiling with `cabal-install`. Everyone has that problem, and the people who publish packages that require mtl 2.2.x these days publish software that no released Haskell compiler can reliably compile (until 7.10.x)  comes out.

**Comment by shlevy** [comment]
@peti FWIW, I'm not sure your analysis is fully correct here. Overriding core packages seems to work just fine for `cabal-install`, especially for "sandboxed" environments. And FWIW, it seems like even we can do it now with haskellng.

**Comment by peti** [comment]
If overriding core packages works fine, then why does your amazonka environment specify `doCheck = false`?

**Comment by shlevy** [comment]
I just copied that over from the previous attempt, and then never removed it due to not wanting to rebuild everything all over again. I'll give removing that and the hyperlinkSource stuff a shot.

**Comment by peti** [comment]
It's worth a shot, but my guess is that you'll run into a package like `doctest` that links the `ghc` library. At that point, it's over. You can't override that. :-)

Overrides work quite well in the new code. It's surprising how far you can get! Still, you can get only so far.

**Comment by shlevy** [comment]
Ah, yes, that's exactly where it failed :grinning:

@thoughtpolice Any chance this can be improved in the future? It seems like having *either* an unoverridable core `ghc` library that doesn't depend on anything else (i.e. is just primitives) or an overridable `ghc` library that depends on core packages but can be rebuilt against newer version of them would solve our problem, it's just the combination that bites us. Could `ghc` be broken up into overridable and non-overridable parts?

**Comment by Ericson2314** [comment]
Cabal isn't yet smart enough to express this, but doctest ought to be built with the package set used to build ghc, not the package set for the package being tested. [Imagine a future using it with ghcjsi--we don't want to build a doctest web app.] So there is no need to split `ghc`, just a need to speak of the booting package sets.
