### ISSUE TITLE
Python switch from gcc to cc cause distutils to fail compilation of C code

### ISSUE THREAD

**Issue by rycee** [NixOS/nixpkgs#5655]
The commits 28b6fb61e651a3e2cca57d087781e7ba6ab45e7c and 05edd656f6bdecde31eb0270209cfc7e2320caad seems to have exposed a weakness in Python distutils. An abbreviated diff of `diff -u rhghn8brqrz4j5ndkhwnm4afqjvk7zi8-python-2.7.9/lib/python2.7/_sysconfigdata.py w5jgkh7p4ywvirrad3bj9c6a0n3f9m6c-python-2.7.9/lib/python2.7/_sysconfigdata.py` reveals the following changes I believe are caused by those commits:
```diff
@@ -23 +23 @@
- 'CC': 'gcc -pthread',
+ 'CC': 'cc -pthread',
@@ -33 +33 @@
- 'CXX': 'g++ -pthread',
+ 'CXX': 'c++ -pthread',
@@ -370 +370 @@
- 'LDSHARED': 'gcc -pthread -shared -lgcc_s',
+ 'LDSHARED': 'cc -pthread -shared -lgcc_s',
@@ -365 +365 @@
- 'LDCXXSHARED': 'g++ -pthread -shared',
+ 'LDCXXSHARED': 'c++ -pthread -shared',
@@ -370 +370 @@
- 'LDSHARED': 'gcc -pthread -shared -lgcc_s',
+ 'LDSHARED': 'cc -pthread -shared -lgcc_s',
```
Unfortunately these mix poorly with distutils' simple [gcc/g++ detection](https://hg.python.org/cpython/file/1c3f8d044589/Lib/distutils/unixccompiler.py#l211):
```python
    def _is_gcc(self, compiler_name):
        return "gcc" in compiler_name or "g++" in compiler_name
```
which in turn causes distutils to use compiler flags that will fail to compile/link C (and presumably C++) code. Relevant extract from the [distutils code](https://hg.python.org/cpython/file/1c3f8d044589/Lib/distutils/unixccompiler.py#l214):
```python
        compiler = os.path.basename(sysconfig.get_config_var("CC"))
        …
        elif self._is_gcc(compiler):
            return "-Wl,-R" + dir
        else:
            return "-R" + dir
```
This issue appear to affect at least the Python modules [ldap](http://hydra.nixos.org/build/18552425/log#line-92) and [pycdio](http://hydra.nixos.org/build/18565562/log#line-39).

**Comment by peti** [comment]
Yes, I've run into the same issue. We should simply pass a compiler that's called `gcc`.

**Comment by lethalman** [comment]
cc @iElectric

**Comment by lethalman** [comment]
It's so obvious why this gcc -> cc is broken... build systems may want to tweak options based on the compiler being used, and even optimization flags. I think using "cc" instead of the real name of the compiler is bad design in our repository in general.

**Comment by vcunat** [comment]
I think it's just the two lines of 3e1fdb7. CC @shlevy. Sure, we can work around it just in distutils, but I think it will be safer to have that nixpkgs-wide.

**Comment by peti** [comment]
> I think it's just the two lines of 3e1fdb7.

This change has caused us a lot of trouble, really, but what are the benefits? I have a hard time seeing what we've gained by switching to `cc` instead of `gcc`.

**Comment by shlevy** [comment]
The change was done to prepare the way for the nix-darwin work, which uses clang as the platform compiler. The options were:

* Calling the compiler gcc even when it's not
* Having an entirely separate package set for darwin
* Generalizing gcc to cc

We chose the third. Note that https://github.com/NixOS/nixpkgs/pull/5676 includes a patch that allows you to check `stdenv.cc.cc.isGNU or false` if you actually *need* a GNU compiler (rather than just needing a compiler that matches the cc command line interface)

**Comment by shlevy** [comment]
Ah I read a bit more up in the issue, if we just want to ensure `CC=gcc` on linux and `CC=clang` on darwin that's something we can change without undermining the goal.

**Comment by shlevy** [comment]
If that's desirable (I don't have time right now to dig into this specific issue), please open up an issue for that and ping me.

**Comment by lethalman** [comment]
Yes, instead of using an hardcoded gcc or cc, simply use a variable somewhere in nix or an env variable.

**Comment by vcunat** [comment]
I'll look into how to best handle these ``CC`` and ``CXX`` vars, and probably file a PR (against staging).

**Comment by shlevy** [comment]
@vcunat See https://github.com/gridaphobe/nixpkgs/commit/7dc57a389e3d3eb5b5e8de3b02dfe469496fad1a (part of #5676)

**Comment by vcunat** [comment]
Thanks for ping. I got delayed with this, and github doesn't notify of new commits in PRs.

**Comment by iElectric** [comment]
Lots of python packages fail to build because of this, @vcunat do you need help?

**Comment by vcunat** [comment]
I did check that ldap and pycdio do build with #5676 applied (7dc57a389 is the relevant commit). We'll see more after Hydra finishes building everything. My whole system did build fine days ago, so there should be no huge problems anymore.

**Comment by iElectric** [comment]
(y)

**Comment by vcunat** [comment]
The mentioned packages build fine on master now.

**Comment by gwhowell** [comment]
Python build finished, but the necessary bits to build these modules were not found:
_sqlite3           _ssl               bsddb185
bz2                dl                 imageop
sunaudiodev
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_tkinter

After playing with it a while, the first list of uncompiled modules is a failure of the configure script.  Even if the needed libraries are in default locations, the configure script does not check for them
(apparently python guys are not good at autoconf).  I got the extra modules to work by editing the Makefile by hand, verifying myself where the needed libaries were,  making sure they are were in the correct paths.  The Makefile edit consisted of adding lines similar to lines in the Makefile for modules that did compile.  Of course the Makefile will be wiped out when you run configure again. 

The second line (here _tkinter) of uncompiled modules could be fixed by editing setup.py.  A trick was to be sure that when python checked internally, that it could find the libraries required for the module
(need to reset LD_LIBRARY_PATH for example).

This was for 2.7.9.  Perhaps compiling it is not of much current interest to python developers ("let them them grab the binaries" to paraphrase Marie Antoinette).

**Comment by domenkozar** [comment]
This is fixed in master. Not sure it already propagated to channels

**Comment by gwhowell** [comment]
Logically, the modules for which bits are not found would be announced at
the end of

config.log

(and the screen output from the configure command)

Some advice on run time load paths would also be helpful.

Hopefully, these features are included in your fix.

Thanks,
Gary Howell
