### ISSUE TITLE
package request: VMWare Workstation

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nixpkgs#56814]
## Issue description

It looks like Nix now has VMWare support on the guest side, but not yet on the host side. afaik VMWare is supposed to be more performant than its alternative VirtualBox.
VMWare Workstation has [free](https://www.vmware.com/products/workstation-player.html) and [premium](https://www.vmware.com/products/workstation-pro.html) versions.

**Comment by Sathish-n** [comment]
I am looking forward to this. As currently iGVT-g isn't fully supported on qemu.

**Comment by justin-gerhardt** [comment]
This would still be useful for me

**Comment by Enteee** [comment]
Somebody already had a go at but didn't manage to finish the derivation: https://discourse.nixos.org/t/porting-vmware-workstation-to-nixos/5122

**Comment by ztmr** [comment]
Do we have any news on this topic? Is there any workaround for this?

**Comment by WolfangAukang** [comment]
I'm still interested in this. Please don't mark it as stale.

**Comment by cawilliamson** [comment]
The only attempt I'm aware of at this was by me! (I'm the guy who was linked to in the Discourse link above.)

I've just posted an update on that page but I'm afraid it still doesn't work. I've packaged up the latest installer, it does install and you can run "vmware-workstation" to start it BUT it just complains about missing kernel headers because I'm not currently building and installing the kernel modules.

I'm 99.99% certain once I do add the code to build and install the kernel modules it will then fail on the same thing it did before - lacking sudo access. I'll give it a shot as time permits though.

If anyone else wants to jump in though and help me with this - I would REALLY appreciate the help! I know porting proprietary apps isn't the most popular thing and I know VirtualBox is already ported to NixOS so it's not urgent but it would be nice to have the option and once it's in nixpkgs - it should be very easy to keep up-to-date.

**Comment by WolfangAukang** [comment]
@cawilliamson First, thank you very much!

Second, I might be making a very stupid question, but for what I saw on the way Virtualbox is built, I believe the headers are on separate packages (like [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/virtualbox/default.nix)). Are you doing the same strategy or are you trying something else?

**Comment by WolfangAukang** [comment]
This has been merged. Closing.
