### ISSUE TITLE
kdepim requires gnupg at runtime

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#5709]
If gnupg is not installed, kmail will crash when viewing a mail with a pgp signature.
This can be confirmed with

kmail --view $PWD/mailwithpgpsignature

**Comment by joachifm** [comment]
I think it's okay for programs to crash due to missing optional runtime dependencies. IMO, this indicates a problem with the original application.

**Comment by vandenoever** [comment]
In the current version of kmail, gnupg is not optional, because the application can crash without it.

**Comment by joachifm** [comment]
As long as the program can run without gnupg, it's an optional dependency. That KMail crashes upon use of an optional feature because of a missing binary, is an upstream bug.

All the distributions I've looked at treat gnupg as an optional/recommended dependency, I see no reason why nixpkgs should be different.

Does installing gnupg into the environment not fix the problem? If it does, there's nothing more to be done here.

**Comment by vandenoever** [comment]
KMail will crash when you *receive* a signed mail and dont have gnupg installed. The user has no idea why the crash happens, so the average user cannot fix it. The user does not consciously choose to use gnpgp. KMail is hardcoded to use it when there is a signed mail.
 I'm a long time kmail user and it took me half an hour to figure out that installing gnupg would fix the issue. You get a mail and when you click on it, kmail crashes.

**Comment by joachifm** [comment]
I don't dispute that KMail is poorly programmed. What is at issue is whether the problem is with nixpkgs or with upstream.  Anyway, it seems we have reached an impasse. @ttuegel is the maintainer, I think.

**Comment by vandenoever** [comment]
Right. I think the options are:
 1) ship code that crashes reproducibly for very normal mail (if you have one signed mail, kmail will always crash on it)
 2) make gnupg a required dep, is there othere pgp software or is pgp still considered an optional feature for mail clients?
 3) add a patch that stops the crash in the nix package
 4) stop shipping kmail

**Comment by ttuegel** [comment]
I am not the maintainer, but I will comment briefly on KDE and Nixpkgs policies. KDE expects downstream distributions to do any integration that is required. In Nixpkgs, we try to provide the best experience for our users by default. In many cases, that means enabling "optional" dependencies by default. The correct solution in this case is to wrap KMail, setting PATH so that it can find gnupg.
