### ISSUE TITLE
gnome-boxes: can't start vms created in different versions

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#57931]
### GNOME Boxes can't start vms created in different versions
Different versions of gnome-boxes cannot start vms created in other versions.
Specifically when the path to `qemu` in its [wrapper](https://github.com/NixOS/nixpkgs/blob/2fcb11a2442b27834db87b2f62511037c31b5e36/pkgs/desktops/gnome-3/apps/gnome-boxes/default.nix#L39) changes.

### Steps to reproduce
1. Start gnome-boxes
2. Create a vm
3. Close gnome-boxes
4. Start a different version of gnome boxes that changes the path to `qemu` in it's wrapper
5. Try to start vm
6. Fails with error

```
libvirt-broker.vala:66: Failed to update domain 'boxes-unknown': Failed to set domain configuration: Cannot check QEMU binary /nix/store/ian3p070vi59ikljv6a1pb8sa8k75dz8-qemu-3.1.0/bin/qemu-system-x86_64: No such file or directory
```

### Notes
I think this sounds more like a  bug in `gnome-boxes` if anything.

**Comment by romildo** [comment]
It writes the full path of `qemu-system-x86_64` in the configuration file (for instance `/nix/store/5a2gv548h6wlsb96w2w07h69z0gjccbj-qemu-3.1.0/bin/qemu-system-x86_64`) and obviously that stops working when `qemu` is rebuild and stored in a different sub directory in `/nix/store`.

Every time this happens I edit the configuration files to update the path. It is a nuisance.

**Comment by sersorrel** [comment]
This is a problem again since #136789 added `qemu` back into $PATH.

libvirt [appears to require](https://libvirt.org/formatdomain.html#devices) that the path in `<emulator>` is absolute:

> The contents of the `emulator` element specify the fully qualified path to the device model emulator binary. The [capabilities XML](https://libvirt.org/formatcaps.html) specifies the recommended default emulator to use for each particular domain type / architecture combination.

so just putting `qemu` in there is unfortunately probably not going to work (if anyone can even work out which bit of software is responsible for generating that path; I couldn't find anything relevant in Boxes, but I was also relying entirely on grep so it's very possible I missed it).

I can't see a way of fixing this apart from removing qemu from $PATH again and requiring that qemu be installed alongside Boxes.
