### ISSUE TITLE
ldc testsuite fails on hydra

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#58112]
## ldc testsuite fails on hydra
See: https://hydra.nixos.org/build/91033190

[Raw output](https://nix-cache.s3.amazonaws.com/log/56ks2nd3zbx1rq8fsc46aqm1dqjaj4z2-ldc-1.14.0.drv)

Unfortunately it was unable to reproduce this locally, so this is just for investigation.

---
cc @ThomasMader

**Comment by ThomasMader** [comment]
Two tests fail.

First problem:

```
 ... runnable/testmmfile.d          -g -link-defaultlib-debug ()
Test runnable/testmmfile.d failed.  The logged output:
/build/ldc-1.14.0-src/build/bin/ldmd2 -conf= -m64 -Irunnable -g -link-defaultlib-debug  -od../../../build/dmd-testsuite-debug/runnable -of../../../build/dmd-testsuite-debug/runnable/testmmfile_0  runnable/testmmfile.d 
../../../build/dmd-testsuite-debug/runnable/testmmfile_0
std.file.FileException@std/file.d(364): test.tmp: No such file or directory
----------------
runtime.d:781 [0x484a58]
runtime.d:1064 [0x484398]
dmain2.d:296 [0x4695e0]
deh.d:24 [0x494cae]
dwarfeh.d:324 [0x46a202]
file.d:240 [0x4196ef]
file.d:364 [0x418ff3]
file.d:313 [0x405ee2]
testmmfile.d:65 [0x405283]
dmain2.d:518 [0x469d2c]
dmain2.d:479 [0x469b32]
dmain2.d:518 [0x469c36]
dmain2.d:479 [0x469b32]
dmain2.d:538 [0x4699e5]
__entrypoint.d:8 [0x406b54]
??:? __libc_start_main [0x7ffff78d3b8d]
start.S:120 [0x404649]


==============================
Test runnable/testmmfile.d failed: expected rc == 0, exited with rc == 1

make[2]: *** [Makefile:347: ../../../build/dmd-testsuite-debug/runnable/testmmfile.d.out] Error 1
```
Failure location: https://github.com/ldc-developers/dmd-testsuite/blob/2433d482b1004934f0904ff93b4f3d7be31c6664/runnable/testmmfile.d#L65

Second problem:

```
==============================
Test compilable/test6461.sh failed. The logged output:
llvm-ar: a.o: No such file or directory.
Error: llvm-ar failed with status: 1
==============================
Test compilable/test6461.sh failed. The xtrace output:
+ source compilable/test6461.sh
++ src=compilable/extra-files/test6461
++ /build/ldc-1.14.0-src/build/bin/ldmd2 -lib -m64 -of../../../build/dmd-testsuite/compilable/test6461a.a -Icompilable/extra-files/test6461 compilable/extra-files/test6461/a.d
+ finish 1
+ set +x
make[2]: *** [Makefile:347: ../../../build/dmd-testsuite/compilable/test6461.sh.out] Error 1
```
Failure location: https://github.com/ldc-developers/dmd-testsuite/blob/2433d482b1004934f0904ff93b4f3d7be31c6664/compilable/test6461.sh#L7

**Comment by ThomasMader** [comment]
I think the problem is the update to the new hydra version: https://github.com/NixOS/nixpkgs/pull/57849

I looked into the first problem a little more.
It fails at https://github.com/ldc-developers/phobos/blob/d50920cb2c59ae27fac0c77fa9f91e2414bddd80/std/file.d#L364 which is strange because this is called from https://github.com/ldc-developers/dmd-testsuite/blob/2433d482b1004934f0904ff93b4f3d7be31c6664/runnable/testmmfile.d#L65 but the very same call was already successfully made at https://github.com/ldc-developers/dmd-testsuite/blob/2433d482b1004934f0904ff93b4f3d7be31c6664/runnable/testmmfile.d#L49 .

The failing open call at https://github.com/ldc-developers/phobos/blob/d50920cb2c59ae27fac0c77fa9f91e2414bddd80/std/file.d#L362 is just calling open from the libc (https://linux.die.net/man/3/open).
Maybe the issue can be reproduced by a simple C program trying to open test.tmp in read only mode two times and checking for a positive fd return value both times.
But I don't want to set up hydra. Probably it's better if some hydra developers look into this.

@Ma27 Could you maybe try to reproduce it?

**Comment by Ma27** [comment]
I'm rather certain that it's not directly related to my bump. The `hydra.nixos.org` instance [uses the package and module from `nixos/hydra` directly](https://github.com/NixOS/nixos-org-configurations/blob/f876f4f92a7d9fe6d65f77638c11350f541955e0/delft/hydra.nix#L6-L8).

However there's still the possibility of a Hydra bug. I'll run this on my own Hydra later that afternoon.

**Comment by Ma27** [comment]
So, I just cherry-picked 341aeb8cf3d295342276fdc8e93ff77761b2dcb8 onto one of my `release-19.03` tracking branches and deployed my personal Hydra with it and the build [seems fine](https://hydra.mbosch.me/build/1063).

Also, the [latest ldc build on master](https://hydra.nixos.org/build/91118277) seems to [pass again](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.ldc.x86_64-linux). I assume that the broken test is somehow related to one of the Hydra builders (had a similar issue when debugging broken `dlib` builds that weren't reproducible locally) such as a missing hardware feature.

**Comment by ThomasMader** [comment]
It's not satisfying to not know exactly what's going on but if we are not able to reproduce it anymore I don't see a way to figure the problem out and to fix anything.

@worldofpeace So I think we can close this for now.

**Comment by worldofpeace** [comment]
I agree, if it becomes worse we have this for reference. That's why I opened it anyway.

**Comment by worldofpeace** [comment]
@Ma27 Thank you for your investigation :+1:
