### ISSUE TITLE
Jekyll: "jekyll new" does not work

### ISSUE THREAD

**Issue by iblech** [NixOS/nixpkgs#58126]
## Issue description

Jekyll, the static website generator, is broken on current master, current unstable-small and on 18.09. There are two unrelated issues. If you give me a little guidance, then I might be able to compile a pull request. :-)

### Steps to reproduce

Here is the first problem:

    $ nix-shell -p jekyll
    [nix-shell:/tmp]$ jekyll new foo
    Running bundle install in /tmp/foo...
    jekyll 3.8.4 | Error:  No such file or directory - ruby

The problem is that `jekyll` calls `ruby`, but `ruby` is not in the PATH. A workaround is to pull `ruby` into the scope of the shell. But then a different issue arises:

    $ nix-shell -p jekyll -p ruby
    [nix-shell:/tmp]$ jekyll new foo
    Running bundle install in /tmp/foo...
      Bundler: There was an error accessing `/nix/store/6ciijc5zqlj63fk6vf9h677l8z9rwchb-gemfile-and-lockfile/.bundle/config`.
      Bundler: The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir -
      Bundler: /nix/store/6ciijc5zqlj63fk6vf9h677l8z9rwchb-gemfile-and-lockfile/.bundle

This seems to be resurfacement of the bug fixed in [closed issue 18784](https://github.com/NixOS/nixpkgs/issues/18784).

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.0, NixOS, 19.09pre172038.5d3fd3674a6 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-19.09pre172038.5d3fd3674a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by primeos** [comment]
> Jekyll, the static website generator, is broken on current master, current unstable-small and on 18.09.

This is a bit unfortunate - basically `jekyll serve` (etc.) should work but `jekyll new` is broken due to the problems with Bundler. See https://github.com/NixOS/nixpkgs/issues/42116#issuecomment-398883794 for my last investigation (unfortunately I didn't get around to find a solution).

At that time my main problem was the following:
> I'm actually not sure what to do here because running bundler install doesn't make much sense (IMO) with Nix(OS).

But in the case of Jekyll running `bundler install` probably makes sense (due to different themes, plugins, etc.).

> If you give me a little guidance, then I might be able to compile a pull request. :-)

I can try but the solution will probably be a bit tricky. I can also have a look at this if you want - just let me know ;)

### Fixing the first problem

This should be easy to fix with `makeWrapper` ([example](https://github.com/NixOS/nixpkgs/blob/afb6a7fe00a5ff81dee5deb78c2d189ee96a32fa/pkgs/applications/version-management/git-repo/default.nix#L32)).
But since `jekyll` is already a wrapper we should extend the current one instead of using `makeWrapper` if possible. Another alternative would be to patch the source-code but because `ruby` is called without an absolute path this would be tricky to get right (e.g. if there are multiple locations).

### Fixing the second problem

This will be a bit tricky. According to `strace` Jekyll is using executing Bundler like this:
```
[pid 23538] execve("/nix/store/ircjrhgliaq9r64jzk7gi2xi881521km-ruby-2.5.3/bin/ruby", ["ruby", "/nix/store/1hkqmw73xzj8c4ihg8a138z8qi7qczr6-jekyll-3.8.5/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle", "install"], 0x1dce560 /* 121 vars */ <unfinished ...>
```

Looking at the [documentation](https://bundler.io/v1.2/bundle_install.html) the following is the default:
> The --system option is the default. Pass it to switch back after using the --path option as described below.
which will cause these problems (installing to `/nix/store/`).

It should be possible to override the location with `$BUNDLE_PATH` or `$GEM_HOME`:
> --system: Install to the system location ($BUNDLE_PATH or $GEM_HOME) even if the bundle was previously installed somewhere else for this application

~~But that didn't work because `bundler` is a wrapper in `nixpkgs`.~~
The problem seems to be Jekyll's wrapper:
```
#!/nix/store/ircjrhgliaq9r64jzk7gi2xi881521km-ruby-2.5.3/bin/ruby
#
# This file was generated by Nix.
#
# The application 'jekyll' is installed as part of a gem, and
# this file is here to facilitate running it.
#

ENV["BUNDLE_GEMFILE"] = "/nix/store/ypc51hgyjygp7p8j66x268m8czcdjsad-gemfile-and-lockfile/Gemfile"
ENV["BUNDLE_PATH"] = "/nix/store/1hkqmw73xzj8c4ihg8a138z8qi7qczr6-jekyll-3.8.5/lib/ruby/gems/2.5.0"
ENV['BUNDLE_FROZEN'] = '1'

Gem.use_paths("/nix/store/8k2psckrrilad6s41n4f43cjsbjnza7m-bundler-1.17.2/lib/ruby/gems/2.5.0", ENV["GEM_PATH"])

require 'bundler'
Bundler.setup("default")

load Gem.bin_path("jekyll", "jekyll")
```

which sets `BUNDLE_GEMFILE` because I'm getting the following error message:
```
Running bundle install in /home/nix-review/jekyll/tmp... 
  Bundler: There was an error accessing `/nix/store/ypc51hgyjygp7p8j66x268m8czcdjsad-gemfile-and-lockfile/.bundle/config`.
  Bundler: The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir - /nix/store/ypc51hgyjygp7p8j66x268m8czcdjsad-gemfile-and-lockfile/.bundle
```

The [more recent documentation for Bundler v2.0](https://bundler.io/man/bundle-install.1.html) states the following:
> --gemfile=<gemfile>
The location of the Gemfile(5) which Bundler should use. This defaults to a Gemfile(5) in the current working directory. In general, Bundler will assume that the location of the Gemfile(5) is also the project's root and will try to find Gemfile.lock and vendor/cache relative to this location.

Hope that helps.

**Comment by primeos** [comment]
> If you give me a little guidance, then I might be able to compile a pull request. :-)

@iblech Are you working on it or should I add it to my TODO list? I wouldn't mind (though it might have to wait for a bit) but I wasn't sure if you'd like to give it a try and make a PR or if that's just meant as a last resort if no one else has time for it.

**Comment by iblech** [comment]
I am very sorry for ghosting you. Thank you for the insightful reply! This makes it clear what the issues really are.

Unfortunately, I got swamped with other things. I can offer to dig into this, based on your instructions, but won't be able to do it in the forseeable future. So in case the issue bothers you, feel free to not wait for me and tackle it when it suits you.

But I should also add that right now the issue is not that important for me, because for unrelated reasons I switched to Hakyll. So some random stranger on the internet, me, should not be the reason for you to invest time into this issue!

**Comment by primeos** [comment]
@iblech thanks for the quick reply, that's perfectly fine and understandable. If you don't use Jekyll anymore I wouldn't recommend digging into it, feel free to ignore the rest of this issue. I'll leave it open though as it is still a relevant problem (I looked into it but didn't find an easy solution).

#### Current state (to document my findings)

I gave it a quick shot but it seems that there isn't any easy solution because the current wrapper is not very customizable.

A quick overview of my findings in case anyone finds this issue and wants to give it another shot:

The relevant files in `nixpkgs` (read it like a stack trace):
- `bundlerApp`: pkgs/development/ruby-modules/bundler-app/default.nix
- `basicEnv`: pkgs/development/ruby-modules/bundled-common/default.nix
- `postBuild`: pkgs/development/ruby-modules/bundled-common/functions.nix
- `genStubsScript`: pkgs/development/ruby-modules/bundled-common/gen-bin-stubs.rb

The last file is the one that actually generates the wrapper. We would probably need to change all of these files to pass an argument from `bundlerApp` all the way down to `genStubsScript` to change the behaviour and I'm also not sure if there will be any problems when `BUNDLE_GEMFILE` and/or `BUNDLE_GEMFILE` are not set. The first problem (`ruby` not in `$PATH`) could be solved in the same way (passing an attribute for `PATH` down to `genStubsScript`) or by adding yet another wrapper (not as nice but easier).

**Another viable (and maybe even better?) alternative would be to change Jekyll**. If Jekyll calls `bundler` with the correct `--path` and/or `--gemfile` options these problems should go away as well. One could look into opening an issue or making a PR.

**Comment by raboof** [comment]
This seems to work now:

```
$ nix-shell -p jekyll
(...)
$ jekyll new my-awesome-site
Running bundle install in /tmp/asdf/my-awesome-site... 
  Bundler: Skipping "bundle install" as it fails due to the Nix wrapper.
  Bundler: Please enter the new directory and run the following commands to serve the page:
  Bundler: nix-shell -p bundler --run "bundle install --gemfile=Gemfile --path vendor/cache"
  Bundler: nix-shell -p bundler --run "bundle exec jekyll serve"
New jekyll site installed in /tmp/asdf/my-awesome-site. 
```

So I think this is fixed (I don't have ruby or bundler installed globally). Closing, feel free to comment if it still happens for you though.

**Comment by iblech** [comment]
Awesome! Thank you for triaging this issue!
