### ISSUE TITLE
terraform-provider-aws 1.60.0

### ISSUE THREAD

**Issue by memberbetty** [NixOS/nixpkgs#58364]
## Issue description
https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#provider-version-configuration requires version `1.60.0`, which is not packaged anywhere in nixpkgs, but is recommended for an upgrade process.

## Technical details
I am reporting this for 18.09, and master in that order of preference.

**Comment by wkral** [comment]
If you set the value of version you want to in `providers.tf` in your project, when you run `terraform init` it will download that version into the local `.terraform` directory independent of the version that is supplied by NixOS. I think the versions provided in the store are useful as a default if you don't explicitly set the version number.

**Comment by angristan** [comment]
I agree, this issue should also be renamed since it's about the AWS provider, not TF itself

**Comment by flokli** [comment]
This issue is about migrating deployment state from `terraform-provider-aws-1.x` to `2.x`.

nixpkgs is now at `2.65.0`, and the tooling doesn't really allow multiple versions.

You're probably much better helped with temporarily downloading an old version of the provider as described in https://github.com/NixOS/nixpkgs/issues/58364#issuecomment-484214485, and then migrate to one provided via nixpkgs.
