### ISSUE TITLE
nixos-rebuild: detect when nixpkgs needs newer Nix

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#5883]
See: https://twitter.com/theuni/status/557705827994566658

It would be nice if nixos-rebuild would detect that newer Nix is needed and would upgrade automatically.

**Comment by copumpkin** [comment]
Can we make nixpkgs depend on nix in a sensible way? :smile: some sort of meta-layer that handles the various nix install scripts stored in a canonical location on nixos.org?

**Comment by copumpkin** [comment]
Perhaps a very simple "primop" for referring to a nix package, much like `nix-install-package`. I was stuck on an old version yesterday, which was a little painful (following https://nixos.org/wiki/How_to_update_when_nix_is_too_old_to_evaluate_nixpkgs#Installing_via_Command_Line).

Then nixpkgs would have a default.nix that says something like:

```nix
let 
  nix = builtins.fetchNixPackage {
    url         = "http://nixos.org/some/canonical/path/to/1.8/";
    sha256 = "blablablablabalbalbalbabobloblaw";
  };
  # Could also have a builtins.hostNix, if you want a handle to the parent nix
  # for the purposes of testing a prerelease version, etc.
in builtins.evaluateWithNix nix ./pkgs/top-level/all-packages.nix
```

Then everything is fully self-describing. If you want to run/test a prerelease version, you have a flag that 

Is this too weird? Flawed somehow?

**Comment by edolstra** [comment]
`nixos-rebuild` already installs the latest Nix (and has done so for a long time).

**Comment by nbp** [comment]
`nixos-rebuild` evaluate & realize the expression to install the latest Nix, but if it fails to evaluate then we are stuck do have some manual procedure.  Hopefully it is quite simple, but I think it would be nice to have a fallback if an expression cannot be evaluated with the current version of Nix.

I guess we don't have to make a generic solution at the moment, and can have a `<nixpkgs/pkgs/top-level/latestNix.drv>` which is used by `nixos-rebuild`.

The problem might be, how to distinguish between a failure caused by a typo, and an updated syntax.  I guess we could use `nix-build --version`.

**Comment by edolstra** [comment]
@nbp There are several fallbacks, see https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/tools/nixos-rebuild.sh#L155.

**Comment by domenkozar** [comment]
Aha fallback needs to be updates, this is now documented as part of release process
