### ISSUE TITLE
buildFHSUserEnv dns broken when hosts resolv.conf is a symlink

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nixpkgs#59086]
## Issue description

Using buildFHSUserEnv in a (unprivileged) nix installation on a debian host system generates the following sequences of symlinks (in the fhs environment) for me:
`/etc/resolv.conf
-> /nix/store/[...]-usr-target/etc/resolv.conf
-> /nix/store/[...]-chrootenv-etc/etc/resolv.conf
-> /host/etc/resolv.conf
-> /etc/resolvconf/run/resolv.conf`
The last one comes from the host system and is invalid inside the sandbox (it should now point to /host/etc/resolvconf/run/resolv.conf).

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.0-8-amd64, Debian GNU/Linux, 9 (stretch)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`

on nixpkgs-19.09pre173080.1222e289b50

**Comment by xaverdh** [comment]
The code [here](https://github.com/NixOS/nixpkgs/blob/5e5e57c5728722450091160b2b0dbf53a311b230/pkgs/build-support/build-fhs-userenv/env.nix#L87) assumes that all files referenced are _not_ symlinks. Its not trivial to fix however, because the paths the links refer to don't exist at the time the etcPkg derivation is build, so it can't just look up the real paths.

**Comment by jameysharp** [comment]
I was looking for something else and found this issue.

Huh, that is painful, and doesn't seem like it should be reliable on NixOS either. I guess this explains why `systemd-nspawn` either bind-mounts or copies `resolv.conf` into the container.

I bet /etc/zoneinfo and /etc/localtime are broken for you as well, right? Those point into the Nix store on NixOS but IIRC they point into /usr somewhere on most distros, and that directory is not bind-mounted because it's what's supposed to be built for the chroot...

I see there's been a fair bit of commit activity on the whole build-fhs-userenv directory since the version you linked to. I haven't checked whether any of it is relevant to your issue but you might want to take a look at nixpkgs master.

I think the quick workaround for you, if you're using the version you linked to, is to remove `${env}/*` from this line: https://github.com/NixOS/nixpkgs/blob/5e5e57c5728722450091160b2b0dbf53a311b230/pkgs/build-support/build-fhs-userenv/default.nix#L14

Then it should just symlink /host/etc to /etc and your symlink to /etc/resolvconf will work fine.

I'm not sure what a good long-term fix is though.

**Comment by xaverdh** [comment]
Yes, `/etc/zoneinfo` and `/etc/localtime` are broken as well, though less critical for my purposes.

My stop-gap solution was/is to change this https://github.com/NixOS/nixpkgs/blob/5e5e57c5728722450091160b2b0dbf53a311b230/pkgs/build-support/build-fhs-userenv/env.nix#L87 line and hard code the correct (as in correct on my system) path there.
Obviously not a good solution to the general problem.

**Comment by xaverdh** [comment]
> I see there's been a fair bit of commit activity on the whole build-fhs-userenv directory since the version you linked to. I haven't checked whether any of it is relevant to your issue but you might want to take a look at nixpkgs master.
Nope, sadly no change  for me.

**Comment by xaverdh** [comment]
Well a low tech solution might be to just add some options to `buidFHSUserEnv` which allow to conveniently specify the right paths on the host system. That would sort of document, that there might be a problem, and the user will usually know what the correct paths ought to be.

**Comment by xaverdh** [comment]
This is probably resolved by using `buildFHSUserEnvBubblewrap` from #94442, but I no longer have this setup, so can't confirm.
Still I guess if people have issues like this with the new  `bubblewrap` based infrastructure, they can open a new issue.
