### ISSUE TITLE
Darwin Mojave: request to backport #59278

### ISSUE THREAD

**Issue by dhruvio** [NixOS/nixpkgs#59341]
A [recent PR](https://github.com/NixOS/nixpkgs/pull/59278) fixed a regression on macOS Mojave that caused certain package builds to fail. The fix is available on master, but should (IMO) also be applied to previous versions of nixpkgs (e.g. 18.09, 18.03, etc), so users that depend on pinning those versions can continue to do so on Mojave.

For example, I need to use Elm 0.18, and the only way to do this is to pin to `nixos/nixpkgs#18.03`. This doesn't work on Mojave, as I get an error message described by [this ticket](https://github.com/obsidiansystems/obelisk/issues/183).

I would offer a PR myself, but I think the work required is beyond my skill-set. Is someone able to do this? Or, weigh in whether this is a viable solution?

**Comment by veprbl** [comment]
#59278 doesn't have anything to do with Mojave. I just checked for release-18.09 and release-19.03 and it's not needed there. Perhaps you meant some other PR. In any case you should describe what the issue is in the first place, e.g. provide a steps to reproduce and show in what way does it fail.

**Comment by LnL7** [comment]
I have been backporting darwin compatibility fixes to both the current and previous release where possible since the first nixpkgs-*-darwin channel was introduced. As far as I can tell both 18.09 and 18.03 work fine on macOS 10.14, only 17.09 and older where not updated.

From the description I have a suspicion that you are not using the latest version of 18.03, but a very old commit from before the fixes where applied.

**Comment by dhruvio** [comment]
Just had the opportunity to test this locally. Elm 0.18 is now working again as of `c8c521f0c03189fd604247e2b2bbe4ab7081968f`. Thank you!
