### ISSUE TITLE
"unpacking source archive" failures

### ISSUE THREAD

**Issue by robberer** [NixOS/nixpkgs#5954]
With nixos-rebuild on top of master I'm getting failures like this:

```
unpacking source archive /tmp/nix-build-Recode-2fd8385658e5a08700e3b916053f6680ff85fdbd-src.drv-0/Recode-2fd8385658e5a08700e3b916053f6680ff85fdbd-src
do not know how to unpack source archive /tmp/nix-build-Recode-2fd8385658e5a08700e3b916053f6680ff85fdbd-src.drv-0/Recode-2fd8385658e5a08700e3b916053f6680ff85fdbd-src
builder for ‘/nix/store/7j3w4a07151m2d4y9y6qy57i1szsbphc-Recode-2fd8385658e5a08700e3b916053f6680ff85fdbd-src.drv’ failed with exit code 1
```

Maybe a problem with fetchzip ? @cstrahan

**Comment by cstrahan** [comment]
Here's the commit for reference:

https://github.com/NixOS/nixpkgs/commit/fc01353703426458d6990239936659ed3130d294


Here's where the problem lies:

```diff
-      renamed="$TMPDIR/${baseNameOf url}"
+      renamed="$TMPDIR/$name"
```

I made that change because I thought it would make sense to allow for supplying a file extension for urls that do not have one (or have parameters or other nonsense at the end). I'll revert that change for now. The problem is that `fetchFromGithub` supplies its own name, and does not provide an extension.

Thank you for bringing this to my attention. I'll revert that part of the change, and hope that we can come up with a satisfying solution to that problem that I was trying solve at a later time - without breaking backwards compatibility.
