### ISSUE TITLE
NetworkManager-wait-online.service is broken

### ISSUE THREAD

**Issue by M-Gregoire** [NixOS/nixpkgs#59603]
## Issue description

NetworkManager service has been renamed recently but it seems `NetworkManager-wait-online.service` hasn't been updated so it tries to uses `NetworkManager.service` instead of  `network-manager.service`.

### Steps to reproduce

1. Install network-manager
2. Run `sudo systemctl start NetworkManager-wait-online.service`
3. Watch it fail with:
```
Failed to start NetworkManager-wait-online.service: Unit NetworkManager.service not found.
```
## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.7, NixOS, 19.03.git.ea497998e4b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-18.09.2505.46d3867a08a"`
 - nixpkgs: `<config-path>/vendor/nixpkgs-release`
```

**Comment by hedning** [comment]
The service was renamed to `NetworkManager.service` which is what upstream expects, but the change isn't in 19.03, we should probably backport it.

We don't modify `NetworkManager-wait-online.service` in NixOS so it looks for the standard service name (`NetworkManager`). I'm guessing this was always broken.

**Comment by worldofpeace** [comment]
Backport already would feel weird with https://github.com/NixOS/nixpkgs/pull/57938

**Comment by flokli** [comment]
Yeah, #51382 wasn't really tested sufficiently enough to backport it to 19.03.

We could fix `NetworkManager-wait-online.service` by changing the unit name it looks for in `nm-online` for 19.03, though (without changing anything in master)

**Comment by fricklerhandwerk** [comment]
This is fixed on master: https://github.com/NixOS/nixpkgs/commit/45886612f0c2292463509c48c01369268d939f1f

**Comment by M-Gregoire** [comment]
Thank you for the heads up!

**Comment by sgraf812** [comment]
I've recently had some trouble with `NetworkManager-wait-online.service` timing out after a `nixos-rebuild switch`.

It turns out that NM was enabled by Gnome for me, so I didn't bother to enable it explicitly in my configuration.nix. After I added `networking.networkmanager.enable = true;`, the issue went away. 

I know that is not strictly the topic of the OP, but the first google result for `nixos "Failed to start NetworkManager-wait-online.service"` leads here, so I guess it's a good place to share my fix in case anyone else has noticed.

**Comment by blaggacao** [comment]
`networking.networkmanager.enable = true` is what [_enables_ collaterally](https://github.com/NixOS/nixpkgs/blob/68c387c29857e1a3d04b493a15e51f32465424a4/nixos/modules/services/networking/networkmanager.nix#L403) `NetworkManager-wait-online.service`. So what might have looked like causality appears to be just correlation.

`systemd.services.NetworkManager-wait-online.enable = false` would disable waiting for a network available during boot. Besides that waiting should probably [have a timeout](https://github.com/NixOS/nixpkgs/pull/199885)...

**Comment by sgraf812** [comment]
I think since about 22.11 my accidental fix in https://github.com/NixOS/nixpkgs/issues/59603#issuecomment-1242785385 doesn't work anymore. `systemd.services.NetworkManager-wait-online.enable = false` as suggested in https://github.com/NixOS/nixpkgs/issues/59603#issuecomment-1304869994 does work around the bug, though it's probably not a satisying solution either. Perhaps it helps until https://github.com/NixOS/nixpkgs/issues/180175 is fixed, which appears to be caused upstream in systemd. I'll continue discussion over there as it seems like the more appropriate place compared to a closed issue.
