### ISSUE TITLE
mysql-workbench complains about missing org.freedesktop.secrets service

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#59833]
I need to come back and elaborate on this later but a workaround seems to be to also get gnome3.gnome-keyring and run the daemon (in the foreground?) with `-s -f`. 

Unrelated issue?: later when actually trying to connect to a MariaDB 10 the whole thing segfaults for me. A further possible workaround seems to be to try using something like dbeaver or squirrel-sql.

**Comment by mixmixmix** [comment]
still important to me

**Comment by jtojnar** [comment]
You need to run some secret service implementation like `services.gnome3.gnome-keyring.enable` or KeePassXC. KDE should have [ksecrets](https://github.com/KDE/ksecrets) but that does not appear to be packaged.

There is not really a way to solve this in Nix since we do not know which implementation does user want to use and D-Bus and systemd services need to be enabled globally 😿

**Comment by mixmixmix** [comment]
Thanks! Isn't it possible for package to request some services to be set up? This problem surely must come up in other more serious contexts?

**Comment by jtojnar** [comment]
Yeah, the issue comes up regularly – just search for dconf in the issue tracker :neutral_face: But there is currently no solution.

The problem is that services need to be installed globally, which is not really compatible with Nix philosophy. — Well, we could build apps wrapped in a container with all its service dependencies but there are downsides to that, see https://github.com/NixOS/nixpkgs/issues/73880#issuecomment-557490704. Or we could have packages declare the service dependencies and than have NixOS check that the services are installed, see https://github.com/NixOS/nixpkgs/issues/52777#issuecomment-449866799

I am not aware of any discussion of this problem. Maybe people just do not consider the added complexity worth the effort, given that it mainly afflicts desktop installations. Or maybe it was discussed before my time or I just missed it. It would be good to (re-)open the discussion, would you like to start a discourse thread?

**Comment by deliciouslytyped** [comment]
I just had the thought that one way to...sort of packagify this stuff might be to use containers? Probably off topic for or this thread though.
