### ISSUE TITLE
help2man seems to be broken

### ISSUE THREAD

**Issue by victoredwardocallaghan** [NixOS/nixpkgs#5988]
help2man seems to be stopping my package from building its man pages.
See:
https://github.com/NixOS/nixpkgs/pull/5962

**Comment by pSub** [comment]
The error `help2man: can't get `--help' info from ./bladeRF-cli` doesn't look like an error in help2man to me. It rather looks like a bug in the build system of libbladeRF. But I have just glanced at it and its hard to build locally, as your branch for PR #5962 has disappeared.

**Comment by pSub** [comment]
The new PR for #5962 is #6043 and builds fine. Closing, please reopen if problems reappear.

**Comment by victoredwardocallaghan** [comment]
pSub, the issue of help2man still remains. I just worked around the issue in 6043 by doing
sed -i 's/ --no-info/ --no-info --no-discard-stderr/' host/utilities/bladeRF-cli/CMakeLists.txt

**Comment by pSub** [comment]
Ok, I'll try to have a deeper look into it at the weekend, but from your fix it seems to me like `--help` is printed to stderr and therefore help2man fails.

**Comment by pSub** [comment]
This is no bug in help2man (see e.g. https://lists.debian.org/debian-mentors/2012/04/msg00031.html). Document generation of libbladeRF was fixed in https://github.com/Nuand/bladeRF/commit/39cd5de28030ad8af2777a9b6fa88da23c2f442b. I have updated libbladeRF in a5360c5b6edd150673b29b90f95e0eee840d6766.
