### ISSUE TITLE
coreutils-8.31 is broken on musl

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#59934]
## Issue description

/cc @dtzWill 

This appears to be some issue introduced in coreutils 8.31. The log result is:

```
/nix/store/3gpwl9qq007w9dxn09nw9rj0jwpywp50-aarch64-unknown-linux-musl-binutils-2.31.1/bin/aarch64-unknown-linux-musl-ld: lib/libcoreutils.a(strtold.o):/build/coreutils-8.31/lib/strtod.c:305: multiple definition of `minus_zero'; lib/libcoreutils.a(strtod.o):/build/coreutils-8.31/lib/strtod.c:305: first defined here
```

Job is here:

https://hydra.nixos.org/job/nixpkgs/cross-trunk/aarch64-musl.coreutils.x86_64-linux

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by dtzWill** [comment]
Maybe change title to indicate broken for aarch64-musl (or however the platform is best described), not sure which work and don't but at least `pkgsMusl.coreutils` seems to work :).

Checking cross now...

**Comment by dtzWill** [comment]
On Sat, 20 Apr 2019 14:08:46 -0700, Matthew Bauer <notifications@github.com> wrote:
> ## Issue description
> 
> /cc @dtzWill 
> 
> This appears to be some issue introduced in coreutils 8.31. The log result is:

I looked into this a bit yesterday.

As I recall, it impacts all cross-compilation with musl.

Recent gnulib has commits for cross-compiling musl, including specifying
proper results for `strtod` and many others.

The commit date is 2019-03-23 (!), which makes me wonder why this hasn't
caused more problems in the past.

Commit: 453ff940449bbbde9ec00f0bbf82a359c5598fc7

http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commit;h=453ff940449bbbde9ec00f0bbf82a359c5598fc7

----

Fixing this:

* coreutils' latest git has updated to a version of gnulib containing the above
  commit, but this can't be trivially used as a patch since the
  tarball doesn't actually contain gnulib but is generated from such
  (a process I'm unfamiliar with, or might as well be since I've
  forgotten :)).
  This might be easy to regenerate and patch or something, don't know.

* We could force the correct value for the configure test here,
  but I think this is asking for trouble if we don't also go through
  all of the other values/tests to ensure they are as they should be--
  having wrong values for these may not break the build but behave
  incorrectly at runtime.  This doesn't seem like a trivial task,
  nor is it one we want to maintain in the future.

Hope this helps, apologies that I can't look into this further in the
near future.

**Comment by nh2** [comment]
I suffer from this; I can't build static `stack` with `static-haskell-nix` with latest nixpkgs master because of the `stack -> git -> coreutils` dependency.

**Comment by nh2** [comment]
@matthewbauer Is this still a problem? I'm quite sure I'm building the latest `coreutils` successfully with musl currently.

**Comment by matthewbauer** [comment]
Yes, this was fixed in https://github.com/NixOS/nixpkgs/pull/61250
