### ISSUE TITLE
pulseeffects lacks icons

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#60253]
I've just run a recent version of `pulseeffects` from Nixpkgs `master` and although the tool works fine, I can't help but notice that all icons are missing, i.e. every button is replaced by some standard "missing" icon. Is that to be expected?

**Comment by worldofpeace** [comment]
Looking at pulseeffects wrapper, it doesn't have any icon themes (aside from hicolor which has none) in `XDG_DATA_DIRS`.

Because you aren't seeing any, I'm assuming you don't have an icon themes in your global environment for the application to use. You should probably just add `gnome3.adwaita-icon-theme` to `environment.systemPackages`.

See discussion at https://github.com/NixOS/nixpkgs/pull/43150#issuecomment-450060363

**Comment by peti** [comment]
Thank you very much for the suggestion! With `gnome3.adwaita-icon-them` in `environment.systemPackages` the icons now work fine.
