### ISSUE TITLE
Running latest TextAdept gives "seg fault".

### ISSUE THREAD

**Issue by JonathanILevi** [NixOS/nixpkgs#60299]
## Issue description
When running the textadept in `nixos-unstable` or `nixos-19.03` the only output is "Segmentation fault".  With `nixos-18.9` it works but is an old version.

### Steps to reproduce
Install textadept from either unstable or 19.3 and execute it with `textadept` in a terminal.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.113, HixOS, 18.09.2532.571b40d3f50 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix 2.1.3)`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by 7c6f434c** [comment]
Hm, could not reproduce.

Does `textadept-curses` start? Does the crash happen if you create a fresh user? What GPU and what GPU driver do you use?

**Comment by 7c6f434c** [comment]
And about the nightly — I think the library directories have to be added to `LD_LIBRARY_PATH` environment  variable, and you might need to use `patchelf` to set the binary interpreter which is not in `/lib/ld-linux.*` but inside `glibc` in case of NixOS.

**Comment by JonathanILevi** [comment]
Okay.  I just updated to 19.03 and discovered the TextAdept now works!  I had installed my system very shortly before its release so I was still on 18.09.

I had tried the TextAdept in the 19.03 and the latest but both on a 18.09 system.

Is there a proper way to handle this?
Is it worth trying to fix the 19.03 TextAdept to run on a 18.09 system?  Or is there a way to mark or flag a warning when installing the 19.03 TextAdept on 18.03?

**Comment by 7c6f434c** [comment]
Hmm. There are multiple possible causes and they are all a bit complicated (and so workarounds are not applied by default or do not even exist in an automatic form).

It might be OpenGL driver issue (general case of that is being discussed on its own… approximately all the time… and it's complicated because of dependence on hardware).

It might be locale-related (which also has its own discussion from time to time… there is a nice solution that adds triple-digit number of megabytes to closure size which is not nice for containers, so it's all complicated)

It might be something else entirely, of course.

**Comment by abathur** [comment]
Closing since it sounds like the immediate problem was resolved, but I'm happy to reopen if anyone thinks there's an unresolved-but-actionable underlying issue.
