### ISSUE TITLE
Broken haskellng pkg

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#6038]
Hi! What should we do now, if pkg from `haskellng` is broken?
Same as we did - set `broken = true;`?
For example `lushtags` is based on old libs and can't be built.
cc @peti 
Sorry if it is a stupid question, but I have to know the right rules :)

**Comment by peti** [comment]
If a package is broken, then you can mark it so in `configuration-common.nix` using the `markBroken` or `markBrokenVersion` functions. A good example is at https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix#L110. Does that help?

**Comment by jagajaga** [comment]
@peti just this?
```
lushtags = markBroken super.lushtags;
```

**Comment by peti** [comment]
Yes, that would do it. Personally, I like the `markBrokenVersion` function, too, because it will throw an assertion error every time an update to the package arrives, i.e. if someone were to publish an update to `lushtags`, then we'd notice that the "broken" mark needs to be checked whether it still applies. The `markBroken` function won't do that; if an update of `lushtags` arrives, it will be marked broken and no-one will notice. Not sure what's more appropriate for `lushtags`.

**Comment by jagajaga** [comment]
Thank you.
