### ISSUE TITLE
Sway 1.1 and swaybg

### ISSUE THREAD

**Issue by alexarice** [NixOS/nixpkgs#60434]
According to this thread https://github.com/swaywm/sway/issues/3861, sway 1.1 will be messaging soon. One of the changes has been that swaybg will now be a standalone project but they have specified that unlike the other standalone projects, sway will depend upon swaybg.
I have attempted to package swaybg on the nixpkgs-wayland overlay (https://github.com/colemickens/nixpkgs-wayland/pull/142) though we are wondering what the best way to package the dependency relation between the projects is. 
Would be good to see if anyone has any ideas.

@primeos @colemickens

**Comment by primeos** [comment]
That's a good question - I haven't looked into it too much yet, as there is no tagged release for `nixpkgs` yet, but I had a quick look at the source code.

The current situation seems to be that `swaybg` is only a run-time dependency (shouldn't be required during the build) and is configurable through `swaybg_command`:
```
*swaybg_command* <command>
	Executes custom background _command_. Default is _swaybg_. Refer to
	*sway-output*(5) for more information.

	It can be disabled by setting the command to a single dash:
	_swaybg\_command -_
```
Since there might be alternatives available and it can also be disabled, I wouldn't consider it a hard requirement (it should be available for the full functionality but Sway should also work without it).

Regarding the implementation of the dependency in `nixpkgs` I currently see at least the following three possibilities:
1) Add a wrapper for Sway to prefix `$PATH` with `${swaybg}/bin`. This is probably the most common solution for such problems in `nixpkgs` and works on non-NixOS systems, but then we have two wrappers on NixOS (due to the module) and it is difficult to customize (+ would require recompiling Sway).
2) Add `swaybg` to `programs.sway.extraPackages`. Easy to implement and customize but only works on NixOS and will become a problem for existing users that already override the default values (we could print a warning if `swaybg` is not in the list).
3) Add `swaybg` always to `environment.systemPackages` if the Sway module is enabled. Easy to implement but only works on NixOS and is difficult to customize.

But unfortunately I'm also not sure what the best approach is...
Currently `programs.sway.extraPackages` (maybe with the warning) seems like a good idea, since non-NixOS users already have to install `swaylock swayidle xwayland rxvt_unicode dmenu` on their own (to be honest, I haven't thought about that until now...) and it is easy to implement and customize but I would be interested what others think (there's probably no right or wrong, just different trade-offs).

**Comment by alexarice** [comment]
What are the advantages of option 2 over 3? Unless I'm missing something aren't programs.sway.extraPackages just added to environment.systemPackages anyway at the moment?

**Comment by alexarice** [comment]
Could have something along the lines of `programs.sway.bgPackage` which defaults to swaybg

**Comment by primeos** [comment]
> Edit: I'm guessing the advantage is that it could be overriden, and the problem is that people already overriding will just wonder why their background broke

Yes, exactly :)

> Could have something along the lines of programs.sway.bgPackage which defaults to swaybg

Thanks, I've added it to the list :) Knew I forgot something...

**Comment by colemickens** [comment]
Combining 1+4 gets us closer to ideal, right? Introduce an option, and use a wrapper in the package. Should work out of the box, even without NixOS. Any reason not to do that?

**Comment by alexarice** [comment]
Would it still be possible to override the option on non nixos with 1+4?

**Comment by primeos** [comment]
> Combining 1+4 gets us closer to ideal, right? Introduce an option, and use a wrapper in the package. Should work out of the box, even without NixOS. Any reason not to do that?

Not sure if it would be much better. If we implement `bgPackage` via the wrapper (vs. `environment.systemPackages`) NixOS users have to recompile Sway if they change it and the only advantage on NixOS is that `programs.sway.bgPackage` is easier to discover (vs. overriding the Sway derivation). Or am I missing something?

> Would it still be possible to override the option on non nixos with 1+4?

Yes, by overriding the derivation for Sway, but that would also require recompiling Sway (or if we suffix $PATH (instead of prefixing it) users could manually install another `swaybg` package that would be preferred). Or they could set `swaybg_command` to use another command.

Compiling Sway doesn't take very long but it's probably still undesirable.
(But again, since we already use option 2 for `swaylock swayidle xwayland rxvt_unicode dmenu` (`dmenu` and `rxvt_unicode` are also required by the default configuration) that actually seems like a good idea. At least if there wouldn't be the problem for existing users that override `programs.sway.extraPackages`.)

**Comment by alexarice** [comment]
Couldn't it be set up so that only the wrapper needs to be rebuild and not the unwrapped sway package

**Comment by primeos** [comment]
> Couldn't it be set up so that only the wrapper needs to be rebuild and not the unwrapped sway package

Ah, yes, that would be possible (and I probably should've clarified that I only meant using `wrapProgram` instead of a real wrapper, i.e. another derivation).

**Comment by alexarice** [comment]
> Ah, yes, that would be possible (and I probably should've clarified that I only meant using `wrapProgram` instead of a real wrapper, i.e. another derivation).

It was probably clear, I don't have a clue how wrappers (or most of nixpkgs) work

**Comment by Synthetica9** [comment]
Can this be closed now?

**Comment by alexarice** [comment]
I'll close it for now, can revisit if it becomes a problem in future releases

**Comment by xunam** [comment]
Coming from #57602, I drop a little comment on this issue:

Firstly, I am not sure I understand why something particular should be done regarding the location of `swaybg`. Sway effectively runs fine even without `swaybg`, one just loses the ability to set backgrounds. Besides, the default configuration contains references to other tools that do not get similar treatment (`alacritty`, `dmenu`, `swaymsg`, `swaynag`).

Assuming one wants to provide a path for `swaybg`, I don't think the trick with `PATH` is appropriate in this context. The main reason is that is it leaks through sway to anything that it launches, and that makes no sense because it pollutes the environment of other programs.

It there has to be a link to an explicit version of `swaybg`, maybe a better option would be to provide a basic configuration file for that and make the wrapper call sway with that configuration explicitly ?

**Comment by deviant** [comment]
@xunam It just so happens I had a patch lying around for exactly this, dating back to August. Submitted as #109647. Thanks for prompting me to finally get around to cleaning it up!

**Comment by primeos** [comment]
#109647 switches from prefixing `$PATH` with `${swaybg}/bin` to patching Sway (i.e. setting the background via Sway's configuration still works as expected but `swaybg` won't be in `$PATH` by default anymore; with the default setup this could theoretically cause regressions, e.g. with custom scripts). If anyone has concerns regarding #109647 please raise them now as otherwise we'll probably merge it soon. Thanks!

**Comment by xunam** [comment]
I certainly do not have any concern with this solution. This seems to be the best way to fix the PATH leakage issue while keeping the link to `swaybg` explicit.
