### ISSUE TITLE
Change default date of nix store to increase compatibility?

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#60446]
## Issue description
I often see problems like `https://nixos.org/nixpkgs/manual/#python-setup.py-bdist_wheel-cannot-create-.whl` due to the default timestamp on NixOS. It seems that dates after 1980 are widely supported across UNIX and DOS, whereas prior to 1980 is often not supported by DOS programs that are later ported to UNIX.

Given that Jan 1, 1970 is completely arbitrary and made up, can we change to the DOS date for nix store to increase compatibility? eg SOURCE_DATE_EPOCH=315532800 instead of 1.

**Comment by vcunat** [comment]
We use this hook by default: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/set-source-date-epoch-to-latest.sh

**Comment by volth** [comment]
I understood it as the issue with ```1970-01-01 00:00:00``` timestamp which is fixed by many hacks across nixpkgs:

https://github.com/NixOS/nixpkgs/blob/526c4292ae62e63b5711f8d112290fcd2613d8b3/pkgs/top-level/all-packages.nix#L120-L131

https://github.com/NixOS/nixpkgs/blob/92a047a6c4d46a222e9c323ea85882d0a7a13af8/pkgs/development/libraries/opae/default.nix#L26-L32

https://github.com/NixOS/nixpkgs/blob/786cbba7be276bc1f2a5580e3c83b17f8ab6e508/pkgs/build-support/release/functions.sh#L27-L28

https://github.com/NixOS/nixpkgs/blob/44aca430c3745c8a5de75afc7b170f5dc0e21bd0/pkgs/development/python-modules/cx_freeze/default.nix#L15-L18

https://github.com/NixOS/nixpkgs/blob/44aca430c3745c8a5de75afc7b170f5dc0e21bd0/pkgs/development/python-modules/pycrypto/default.nix#L10-L11

https://github.com/NixOS/nixpkgs/blob/ba34ffc6657d502322733837695d0b5b1ce87202/pkgs/tools/filesystems/ceph/generic.nix#L113

https://github.com/NixOS/nixpkgs/blob/2c5f92a7238cbc8241c936fbc70194a2936a23ca/pkgs/development/compilers/graalvm/default.nix#L86-L89

setting ```$SOURCE_DATE_EPOCH``` to the latest mtime does not help in many cases (when the timestamped files are inside a zip-archive, etc)

But changing ```1970-01-01 00:00:00``` to, say, ```2000-01-01 00:00:00``` would fix the 1980-issue as well as other vague issues (overflow/underflow of timestamp arithmetics, ...)

**Comment by vcunat** [comment]
It's just switching from one arbitrary date to another.  When doing this, I'd anticipate that some "new modern framework" will come that will assume that anything before 2010 can be ignored.  The shift might help in practice, though... but I suspect nixpkgs/stdenv won't be enough and we'd need to shift _nix store_ dates as well, i.e. break its compatibility.

**Comment by tbenst** [comment]
Yes, thanks @volth. @vcunat you are right that  developers are free to hardcode other date assumptions and the problem often happens with nix store dates

**Comment by FRidh** [comment]
I don't see this happening so closing.

**Comment by volth** [comment]
> It's just switching from one arbitrary date to another. When doing this, I'd anticipate that some "new modern framework" will come that will assume that anything before 2010 can be ignored. 

The date could be the ```nixpkgs``` version, `2019-03-01 00:00:00` for `19.03`

**Comment by twhitehead** [comment]
Just a note that you can't build epub documents using sphinx due to this. Further, it seems to be choking on pulling a `mimetypes` file from the store (as predicted would happen)... :grin: 
```
$ make epub
...
Traceback (most recent call last):
  File "/nix/store/aar6diwl9bw72bckp21zpiclmcpyg9hr-python3.8-sphinx-3.0.3/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/nix/store/aar6diwl9bw72bckp21zpiclmcpyg9hr-python3.8-sphinx-3.0.3/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/nix/store/aar6diwl9bw72bckp21zpiclmcpyg9hr-python3.8-sphinx-3.0.3/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/nix/store/aar6diwl9bw72bckp21zpiclmcpyg9hr-python3.8-sphinx-3.0.3/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 364, in build
    self.finish()
  File "/nix/store/aar6diwl9bw72bckp21zpiclmcpyg9hr-python3.8-sphinx-3.0.3/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 623, in finish
    self.handle_finish()
  File "/nix/store/aar6diwl9bw72bckp21zpiclmcpyg9hr-python3.8-sphinx-3.0.3/lib/python3.8/site-packages/sphinx/builders/epub3.py", line 82, in handle_finish
    self.build_epub()
  File "/nix/store/aar6diwl9bw72bckp21zpiclmcpyg9hr-python3.8-sphinx-3.0.3/lib/python3.8/site-packages/sphinx/builders/_epub_base.py", line 730, in build_epub
    epub.write(path.join(outdir, 'mimetype'), 'mimetype', ZIP_STORED)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/zipfile.py", line 1741, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/zipfile.py", line 539, in from_file
    zinfo = cls(arcname, date_time)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/zipfile.py", line 362, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
```

Was looking through the `zipfile.py` [source code](https://github.com/python/cpython/blob/main/Lib/zipfile.py) though, and happened to notice this
```
        if not strict_timestamps and date_time[0] < 1980:
            date_time = (1980, 1, 1, 0, 0, 0)
        elif not strict_timestamps and date_time[0] > 2107:
            date_time = (2107, 12, 31, 23, 59, 59)
```

Looks like the default is `strict_timestamps=True`, could be a reasonable point to apply a patch
```
    def from_file(cls, filename, arcname=None, *, strict_timestamps=True):
```

**Comment by FRidh** [comment]
stdenv was changed in https://github.com/NixOS/nixpkgs/pull/89794
