### ISSUE TITLE
py: Could not find a version that satisfies the requirement pluggy

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#60684]
I'm new to packaging python on nix and have a WIP here: https://github.com/tbenst/nixpkgs/blob/01d32d962f25b0b7f6751c81eab819f0ed0bcbdc/pkgs/development/python-modules/deeplabcut/default.nix. The problem I'm seeing is, 

```
Collecting pluggy<0.7,>=0.5 (from pytest==3.3.1)
  Could not find a version that satisfies the requirement pluggy<0.7,>=0.5 (from pytest==3.3.1) (from versions: )
No matching distribution found for pluggy<0.7,>=0.5 (from pytest==3.3.1)
```

Any tips on how in general to handle such restrictive version requirements on Nix? Thanks!

**Comment by tbenst** [comment]
Simpson on IRC suggested using `sed -i "s/odfpy>=0.9, <0.10/odfpy/" setup.py` in postPatch to fix this type of problem

**Comment by JohnAZoidberg** [comment]
Yeah, but that isn't really practical on a large scale.
Sometimes you have tens of dependencies which all don't exactly match the versions in nixpkgs.
If there isn't already, we should have something like what `doJailbreak` does for Haskell packages. (Strip dependency version requirements).

**Comment by tbenst** [comment]
@JohnAZoidberg grea

**Comment by JohnAZoidberg** [comment]
I tried to implement it a while back, but it turned out to be quite challenging to have a function that does this for all kinds of Python packages.

At least we should have consensus on how to generally do it.
Just today, I added a patch to remove constraints: https://github.com/NixOS/nixpkgs/pull/72886/files#diff-7e6548170f2f342c457792016f161fd1
