### ISSUE TITLE
UIDs are not assigned for all service module users

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#60732]
Same issue as https://github.com/NixOS/nixpkgs/issues/11317 

List of services with users without assigned UIDs:
- [ ] matterbridge
- [ ] gitea

**Comment by sbourdeauducq** [comment]
Also, would there be a way for ``enforceIdUniqueness`` to work even when ``uid`` is ``null``? This way such problems would be detected before systems get messed up.

**Comment by sbourdeauducq** [comment]
Not checking when ``uid`` is ``null`` causes this problem:

* add user1 with ``uid=null``
* rebuild the system
* add user2 with ``uid`` set to the UID of user1
* rebuild the system
* you now have conflicting UIDs

**Comment by aanderse** [comment]
ping @ryantm @ehmry @disassembler @etu as maintainers of these packages, simply so they are aware of the issue.

**Comment by ryantm** [comment]
This has nothing specific to do with gitea or matterbridge, this is a generic problem with automatic assignment of UIDs over multiple NixOS generations. The long-term fix is to determine which modules have users without UID assignments and either remove their need for a user, or assign the user a uid. An alternative solution could be to augment the automatic uid assignment system to not reuse IDs.

**Comment by sbourdeauducq** [comment]
> The long-term fix is to determine which modules have users without UID assignments and either remove their need for a user, or assign the user a uid.

Well, then those two packages are currently not compliant.

> An alternative solution could be to augment the automatic uid assignment system to not reuse IDs.

Would that include a solution for this problem? https://github.com/NixOS/nixpkgs/issues/60732#issuecomment-488606670

**Comment by ryantm** [comment]
> Well, then those two packages are currently not compliant.

Yes, we should make a list of the modules with this issue!

> Would that include a solution for this problem? [#60732 (comment)](https://github.com/NixOS/nixpkgs/issues/60732#issuecomment-488606670)

Seems like it would to me. I'm imagining the rule could be something like don't reuse an ID unless it is for the same user name.

**Comment by ryantm** [comment]
I edited your first post to start a list of services with users but no UIDs.

**Comment by aanderse** [comment]
> The long-term fix is to determine which modules have users without UID assignments and either remove their need for a user, or assign the user a uid.

ping @Infinisil as someone who would be interested in this conversation.

**Comment by Infinisil** [comment]
For some time now I've started telling people to stop giving static uid's to users, because it's not needed anymore. NixOS can choose uid's on its own, while reusing previously deleted users uid's since https://github.com/NixOS/nixpkgs/commit/a57bcd38b49. There are only very few cases where it makes sense for a service to have a static uid, such as in multi-machine services that need matching uid's on their files or whatever.

If you look at the file that assigns static uid, you'll notice this comment here: https://github.com/NixOS/nixpkgs/blob/bd941433d052f336ccde6b20c8a722abda3fb78f/nixos/modules/misc/ids.nix#L340-L343

This means, we have about 85 uid's left in that range! Over the past years, people have been adding static uid's in this file, almost completely filling up our reserved range from 0-400, see https://github.com/NixOS/nixpkgs/blob/bd941433d052f336ccde6b20c8a722abda3fb78f/nixos/modules/programs/shadow.nix#L13-L16

Yes, we might be able to extend the ranges, but that's ugly and only temporarily solves the problem.

I think there's two things we could do improve this situation:
- Make the user/group modification script error out when there's a conflict.
- Reserve different ranges of uid's for `uid = null` and `uid = <number>` in non-nixpkgs code. So perhaps uid's in the range 1000-20000 could be used by `uid = <number>`, so the user is free to choose any of those without fear of conflict, because `uid = null` will only give out uid's above 20000.

**Comment by Infinisil** [comment]
Hold on I wrote that a bit confusingly. Let me retry.

### What problems do we have regarding id's
1. There's nothing that checks conflicts between id's given out with `= null` and `= <number>` (this issue)
    Solutions include:
    1. Make the script that assigns id's check that there are no conflicts or error out otherwise
    2. Reserve different ranges for `= null` and `= <number>`
    3. (partial) Only use `= <number>` in nixpkgs (with number < 400), this would only solve the problem for `= null` in nixpkgs and `= <number>` outside nixpkgs, but the problem is still there for both outside nixpkgs
2. Without changing our approach, we can only give out about 85 more `= <number>` id's in nixpkgs (because number < 400)
    Solutions include:
    1. Use `= null` instead, which is in conflict with 1.iii
    2. Extend the id range to go beyond 400, this is ugly and probably only a temporary solution

Because 1.iii stands in conflict with the best solution for 2 (2.i), I think we should use 1.i, and optimally 1.ii as well.

**Comment by etu** [comment]
Not a solution in any way, but just adding to the list of modules that would benefit from having a static user id is `sks`.

**Comment by sbourdeauducq** [comment]
> Yes, we might be able to extend the ranges, but that's ugly and only temporarily solves the problem.

Another issue with this static nixpkgs system UID list is that are modules distributed outside nixpkgs cannot register UIDs for their services there.

**Comment by Infinisil** [comment]
So something I haven't considered yet is the use of `isSystemUser` for services. Then they can have a non-static uid in the range 400-499. 100 uid's is not a lot, but since this will only be used by services enabled by the user, this *might* be enough, but it's too close for comfort to me. A long running NixOS machine might have 100 services enabled over its years.

This was brought to my attention in https://github.com/NixOS/nixpkgs/pull/51947#discussion_r301742629

**Comment by Infinisil** [comment]
Yeah so after some more thought, using system users should really be the way forward for all services. This means *not* setting a static uid, and using `isSystemUser = true`, which will automatically allocate an id between `SYS_UID_MIN` and `SYS_UID_MAX` (see https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/shadow.nix) if and only if the user enables the service.

As a consequence, the number of id's we need doesn't depend on the number of services we have in nixpkgs anymore (as it would with the assigning-static-ids approach), but on the number of services the user has enabled, which won't really grow over time.

The only problem as mentioned already is that the current system user range of 400-499 is a bit on the small side, so this should be extended. And the obvious way to extend this is to go up, increasing `SYS_UID_MAX` to 999 (=`UID_MIN-1`), which is actually the default (see `man login.defs`). This way the range 400-999 can be used.

Are there any migration problems? I don't think so, because first of all, the new range 500-999 is supposed to be unused. The only way to get such uid's was by statically setting them. And even *if* people got uid's in that range with static uid's, it would not be a problem, because the automatic uid selection will only choose an unused uid in the range, which can't be a statically assigned one.

Does anybody have any concerns with this? Ping @edolstra @ryantm 

Implementation notes: The range also needs to be extended in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/update-users-groups.pl

**Comment by ryantm** [comment]
@Infinisil That sounds good to me, but I don't know the reasons behind the unallocated user id ranges (101-399, and 500-999).

I guess a problem would still exist if someone tried to statically assign a system user id that had already been automatically assigned. It seems likely that case can be an error during the nixos-rebuild.

**Comment by ryantm** [comment]
Ah, 1-399 are the IDs that are statically assigned in nixos/modules/misc/ids.nix.

**Comment by arianvp** [comment]
@Infinisil I'd actually personally prefer if we could use  systemd's `DynamicUser` feature for this kind of stuff. It does The Right Thing concerning keeping track of the right owner And means we don't need to allocate uids ourselves at all.

(See http://0pointer.net/blog/dynamic-users-with-systemd.html for more info)

**Comment by Infinisil** [comment]
@arianvp Ah yes, very much agreed, `DynamicUser` should always be preferred if possible. Only if `DynamicUser` can't be used for some reason (which I think is often the case when the service has to interact with other services or users), we should let NixOS assign a uid.

**Comment by Infinisil** [comment]
Something I just noticed: Due to dynamically allocated uids/gids persisting, even when the corresponding service is disabled again, the limit won't be 500 services *enabled* at a time, but 500 services *ever used*.

While it would be really hard to trigger this limit, the number of services ever used *does* continually increase over the lifetime of a NixOS system.

Because this is really hard to do (hell, we don't even have that many services in NixOS), I think it's safe to ignore.

**Comment by edolstra** [comment]
I think we should avoid static ID assignments except for services with data likely to be shared over network filesystems.  BTW I have some vague recollection that the UID range 500-999 was intended for manual user assignments. (So neither `useradd` or system accounts would use that space.) My user account on my desktop NixOS machine was uid 500 until recently...

**Comment by Infinisil** [comment]
Just opened above PR for a move in this direction

**Comment by Infinisil** [comment]
With the acceptance of https://github.com/NixOS/rfcs/pull/52, this isn't a problem anymore, dynamic uids are encouraged.
