### ISSUE TITLE
gimp: bad interpreter

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#60937]
## Issue description

I see the following warnings when running gimp:

```
$ gimp
GIMP-Warning: Bad interpreter referenced in interpreter file /nix/store/0hsy78qmsclkks0v9ykcmvx0wsllwyw8-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp: python2

GIMP-Warning: Bad binary format string in interpreter file /nix/store/0hsy78qmsclkks0v9ykcmvx0wsllwyw8-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp
```

Not sure if they are critical or not. I do have problems with one Python plugin, not sure if this could be related.

### Steps to reproduce

Run gimp from the terminal. I'm running it from i3+none desktop environment, if that matters.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.36, NixOS, 19.09.git.3d081ed (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by jtojnar** [comment]
This is what the file looks like on Arch:

```
python=/usr/bin/python2
python2=/usr/bin/python2
/usr/bin/python=/usr/bin/python2
:Python:E::py::python2:
```

nothing special compared to ours:

```
python=/nix/store/mb307xgf3x2z6111fkrsqdvh3gf9bk19-python-2.7.16/bin/python2
python2=/nix/store/mb307xgf3x2z6111fkrsqdvh3gf9bk19-python-2.7.16/bin/python2
/usr/bin/python=/nix/store/mb307xgf3x2z6111fkrsqdvh3gf9bk19-python-2.7.16/bin/python2
:Python:E::py::python2:
```

The file exists and is executable

```ShellSession
$ file /nix/store/mb307xgf3x2z6111fkrsqdvh3gf9bk19-python-2.7.16/bin/python2
/nix/store/mb307xgf3x2z6111fkrsqdvh3gf9bk19-python-2.7.16/bin/python2: symbolic link to python2.7
$ file --dereference /nix/store/mb307xgf3x2z6111fkrsqdvh3gf9bk19-python-2.7.16/bin/python2
/nix/store/mb307xgf3x2z6111fkrsqdvh3gf9bk19-python-2.7.16/bin/python2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/siks2gcfwx6qwh27m7c5r5lixcr621bd-glibc-2.27/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```

Not really sure what is wrong. Also the Python scripts seem to work, at least `resynthesizer2` does.

**Comment by jluttine** [comment]
For me, resynthesizer runs but it doesn't produce correct results: https://github.com/bootchk/resynthesizer/issues/63

**Comment by jluttine** [comment]
Still important to me. This is the current console output:
```
GIMP-Warning: Bad interpreter referenced in interpreter file /nix/store/5c91dah385gn70blsn6i5rzncqj3ks0y-gimp-with-plugins-2.10.18/lib/gimp/2.0/interpreters/pygimp.interp: python2

GIMP-Warning: Bad binary format string in interpreter file /nix/store/5c91dah385gn70blsn6i5rzncqj3ks0y-gimp-with-plugins-2.10.18/lib/gimp/2.0/interpreters/pygimp.interp

Traceback (most recent call last):
  File "/nix/store/3hsppxikcvwhwq1z3bjfjkmjxv97qy91-gimp-2.10.18/lib/gimp/2.0/plug-ins/spyro_plus/.spyro_plus.py-wrapped", line 23, in <module>
    import gimpui
  File "/nix/store/5c91dah385gn70blsn6i5rzncqj3ks0y-gimp-with-plugins-2.10.18/lib/gimp/2.0/python/gimpui.py", line 33, in <module>
    import gtk, gobject, gimp, gimpcolor
ImportError: No module named gtk
/nix/store/5c91dah385gn70blsn6i5rzncqj3ks0y-gimp-with-plugins-2.10.18/bin/.gimp-2.10-wrapped_: LibGimpBase-WARNING: .gimp-2.10-wrapped_: gimp_wire_read(): error
Plug-in "script-fu"
(/nix/store/5c91dah385gn70blsn6i5rzncqj3ks0y-gimp-with-plugins-2.10.18/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-anim-lightning" with a full menu path "<Toolbox>/Xtns/Anim/Lightning" as menu label, this deprecated and will be an error in GIMP 3.0
Plug-in "script-fu"
(/nix/store/5c91dah385gn70blsn6i5rzncqj3ks0y-gimp-with-plugins-2.10.18/lib/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-lightning" with a full menu path "<Toolbox>/Xtns/Patterns/Lightning" as menu label, this deprecated and will be an error in GIMP 3.0
```

**Comment by shirona** [comment]
I have found this issue can be fixed by installing the python package by yourself (which is weird: it looks like GIMP may be trying to use the `python2` command from your `$PATH`). I have it in my systemPackages and I got past that stage. However, #87883 is still blocking the usage of some plugins.

**Comment by jtojnar** [comment]
From some time spent in `gdb`, it looks like the extension mapping from `pygimp.interp` file only searches `python2` in path, not in the mapping described on previous lines and registered in 

* `pygimp.interp`: https://gitlab.gnome.org/GNOME/gimp/-/blob/GIMP_2_10_20/plug-ins/pygimp/Makefile.am#L156-160
* `gimp_interpreter_db_add_program`: https://gitlab.gnome.org/GNOME/gimp/-/blob/df5b363a9606fb7897b6a288ba24a05517219f54/app/plug-in/gimpinterpreterdb.c#L315
* `gimp_interpreter_db_add_extension` https://gitlab.gnome.org/GNOME/gimp/-/blob/df5b363a9606fb7897b6a288ba24a05517219f54/app/plug-in/gimpinterpreterdb.c#L394-398

~~But it looks like the check is only a warning and has no bearing on later execution since at the [end of `gimp_interpreter_db_load`](https://gitlab.gnome.org/GNOME/gimp/-/blob/df5b363a9606fb7897b6a288ba24a05517219f54/app/plug-in/gimpinterpreterdb.c#L183), the programs not matched in `PATH` are resolved in the program mapping database.~~ The extension is [not actually inserted to the database](https://gitlab.gnome.org/GNOME/gimp/-/blob/df5b363a9606fb7897b6a288ba24a05517219f54/app/plug-in/gimpinterpreterdb.c#L404-411) so some other mechanism than extension matching must be involved – perhaps shebangs are applied.

We will still want to hardcode the path to ensure purity.
