### ISSUE TITLE
libglvnd broken on darwin

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#61921]
## Issue description

`libglvnd` broken on darwin 
```
$ nix-build -A libglvnd
...
...
Patching '/nix/store/2b6vjnx5j11lbn1qn1c7lljx05igwb4x-libglvnd-1.0.0-dev/lib/pkgconfig/libglvnd.pc' includedir to output /nix/store/2b6vjnx5j11lbn1qn1c7lljx05igwb4x-libglvnd-1.0.0-dev
strip is /nix/store/dvpgjv19mqjkpb144p08350ynx12ww36-cctools-binutils-darwin/bin/strip
stripping (with command strip and flags -S) in /nix/store/akvdrvqspfnfnsb1604ihknx5l47nk88-libglvnd-1.0.0/lib
patching script interpreter paths in /nix/store/akvdrvqspfnfnsb1604ihknx5l47nk88-libglvnd-1.0.0
strip is /nix/store/dvpgjv19mqjkpb144p08350ynx12ww36-cctools-binutils-darwin/bin/strip
stripping (with command strip and flags -S) in /nix/store/2b6vjnx5j11lbn1qn1c7lljx05igwb4x-libglvnd-1.0.0-dev/lib
patching script interpreter paths in /nix/store/2b6vjnx5j11lbn1qn1c7lljx05igwb4x-libglvnd-1.0.0-dev
/nix/store/s1yj8znw2qwlswy25h154ij17mm3q5fj-add-opengl-runpath/nix-support/setup-hook: line 24: patchelf: command not found
/nix/store/s1yj8znw2qwlswy25h154ij17mm3q5fj-add-opengl-runpath/nix-support/setup-hook: line 25: patchelf: command not found
builder for '/nix/store/i43ia8hkzykx1q0ziv5hspv2hr6mz4ik-libglvnd-1.0.0.drv' failed with exit code 127
error: build of '/nix/store/i43ia8hkzykx1q0ziv5hspv2hr6mz4ik-libglvnd-1.0.0.drv' failed
```
Related to https://github.com/NixOS/nixpkgs/pull/60985 
cc: @ambrop72
### Steps to reproduce
try to build libglvnd in https://github.com/NixOS/nixpkgs/commit/5b7dea196261231f29ff3e4f7eefb8b937915617

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by matthewbauer** [comment]
Probably can just make addOpenGLRunpath only run on Linux systems.

**Comment by flokli** [comment]
Sorry, I wasn't aware darwin was using libglvnd at all!

Making `addOpenGLRunpath` a no-op on darwin as suggested in https://github.com/NixOS/nixpkgs/pull/60985#discussion_r286762496 won't work, as we explicitly call `addOpenGLRunpath` on certain binaries and `.so` files, which likely don't even exist on darwin, so the calls to `addOpenGLRunpath` itself would need to be made conditional.

Is darwin using more mesa drivers than the swrast? Do we have the same problems as in https://github.com/NixOS/nixpkgs/pull/60985 there, too? If we do, is there something analogous we can do on darwin (call `install_name_tool` in `addOpenGLRunpath` if it's a dylib)?

Unfortunately, due to lack of hardware, I can't test this myself. I could make a PR calling `addOpenGLRunpath` only on darwin, though.

**Comment by ambrop72** [comment]
There's also the minor problem that we would be adding `addOpenGLRunpath` to `nativeBuildInputs` or have boilerplate conditionals there as well. Could we make this less boilerplatey and more declarative Something like:
```
postFixup = ''
  ${addOpenGLRunpath "lib/*.so"}
'';
```
where this expands to `(true)` on Darwin and this on Linux:
```
(source <shell_file> && addOpenGLRunpath lib/*.so)
```

**Comment by matthewbauer** [comment]
I think putting something like ```isDarwin``` or ```isELF``` in the bash function itself would be preferred

**Comment by ambrop72** [comment]
It can be more complicated, maybe you want to do a for loop to look for files to patch, and you don't want to do any of that on Darwin. Could we have a bool variable within the `addOpenGLRunpath` package like `.needed`?
