### ISSUE TITLE
wireshark is not usable

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#6235]
NixOS does not implement any of the methods described here to run `wireshark` in any sane way http://wiki.wireshark.org/CaptureSetup/CapturePrivileges. 

Running it as root results in a bunch of warnings, and `man configuration.nix` does not document any options for wireshark (which has been done for other operating systems (like Debian, etc.)). 

For an operating system which is keen on its configuration management capabilities, it's working much, much worse than an imperatively managed ancient system like Debian. 

What is the rationale for including such badly packaged systems in NixOS (especially in the "stable" distribution)? If you absolutely want to include such broken code, can you at least mark the stuff you do not think is broken in some way, to give people the option to avoid it? 

Why don't you have rules which simply say "if it doesn't easily work, we do not include it."? There are many more programs in NixOS for which this currently holds. It seems like the only consideration is "if it compiles, ship it.".

**Comment by 7c6f434c** [comment]
>Why don't you have rules which simply say "if it doesn't easily work, we do not include it."? There are many more programs in NixOS for which this currently holds. It seems like the only consideration is "if it compiles, ship it.". 

Because Wireshark is useful to some NixOS users who capture with tcpdump
and use Wireshark to browse the capture comfortably. I, for one, do just
that (I browse captures from servers often enough to consider browsing
tcpdump captures the natural way of using Wireshark).

**Comment by peti** [comment]
I also use `wireshark`, and I simply run it as `root`. It's not ideal, but it doesn't bother me enough to sit down and figure out an advanced setup. If you, @wwat, know of superior ways to run `wireshark` without requiring super user privileges, then we why don't you make a concrete suggestions and/or submit a PR that improves the situation?

**Comment by bjornfor** [comment]
Add ```security.setuidPrograms = [ dumpcap ];```. If you want to limit access to certain user/group, use ```security.setuidOwners```.

**Comment by bluescreen303** [comment]
I also just use wireshark as analysis program. Capturing is better left to netsniff-ng or tcpdump

**Comment by bjornfor** [comment]
Installing dumpcap setuid *is* one of the options listed in http://wiki.wireshark.org/CaptureSetup/CapturePrivileges. So this issue is invalid. (See my comment above.)

One could argue that there should be a specific programs.wireshark.enableSetuidDumpcap option though. But if you want more control over who gets access to this dumpcap, you have to use security.setuidOwners anyway.

**Comment by wwat** [comment]
@bjornfor  No, there should be a list of users configurable in wireshark's configuration, that is a wireshark service module in NixOS parlance. Then *that* would merge with security.setuidOwners. Then the security mechanism is hidden as an implementation detail.

**Comment by bjornfor** [comment]
I can somewhat agree to that. (I don't have strong opinions.)

Btw, this issue is still invalid. "wireshark is not useable" is simply false. What you are (now) arguing about is that you don't like the existing config options (setuidPrograms, setuidOwners). You want a programs.wireshark.\<something\> option.

**Comment by wwat** [comment]
@bjornfor I don't care one bit about whether a particular subset of features is available in a well considered way. There is only one decent design put forward (the one I outlined) and that has not been implemented. Anyone who has any experience in properly packaging something for NixOS should have done that, and not do some half-assed job (which is what it is now). 

Just because there are also people who use workarounds (the vast majority who responds here), doesn't mean that e.g. a Debian or Redhat user would not laugh you out of the room, because again, the wireshark 'feature' is just broken.  

It also annoys me that you misquote me, since I didn't misspell the word "usable" like "useable", like you did, which makes me look like an idiot to others, while in fact you are the one who made a mistake. 

In general, the only right response to what I said is "Yes, that would be better", but defending the current state is irrational at best.

Really, why is *anyone* defending the *undocumented* method for configuring wireshark in NixOS here? What do you imagine is going to happen when a random new security mechanism is introduced in Linux? Do you expect all the people who "just want to run wireshark as user X (with additional rights)" to keep track of such details? Why?! That only annoys users and lack of stability scares away a huge class of users who actually have the funds to make NixOS a success. If the goal is to annoy users, then please state that on the NixOS website, if not, stop arguing, and just say "yes, this is a good idea.". 

Quoting from the website:
```NixOS is a Linux distribution with a unique approach to package and configuration management. Built on top of the Nix package manager, it is completely declarative, makes upgrading systems reliable, and has many other advantages.```
I think this is a complete lie (see my theoretical example about wireshark (for which I am sure practical examples can also be found), lack of backwards compatibility, and other misfeatures). NixOS might have as a goal to become "better", but back in the real world, when real engineers need to do something in a limited time, it's not actually 'better', because it is not documented. If it's not documented, _it_does_not_exist_. An interface which can disappear tomorrow again, is *not* worth our time. 

NixOS, as an operating system community, has almost no tools (compare with the Debian community or the many, many tools which Red Hat has internally), which means there is no timely updates of security issues, or new releases; it all depends on some human to take the time to do an upload (in other words, a completely flawed approach, which doesn't scale). 

One simple program (less than 1,000 lines) can be used to build almost arbitrary programs with the most broken build systems, but yet for NixOS the simplest of automation procedures "genericBuild" is being used. Additionally, a complete ingestion procedure is missing where global release directories from major repositories are being tracked to automatically package them for NixOS use (including digital signatures, etc.). This gives the feeling of a system which is dependent on a small self-selected(?) bunch of people in order to create the next release, which in turn increases risk. As long as that risk is there, that is, it is not possible to push a button and deploy a complete NixOS project infrastructure in-house, there is a lot of reason to doubt the intentions of the people in the NixOS project. What exactly are we here for then? Free testing? I don't think so.  

Similarly, why does someone have to manually partition a system in order to install NixOS? That's just begging people to not use NixOS. 

Let me restate it again; There is absolutely *no* point in manually packaging software. Basically, everything which is done manually sucks. There should be a ton of automated commits happening in a project like NixOS, but what appears to be happening is that there are some users who have their own scripts to maintain parts of the system in a semi-distributed, unprofessional matter.  And to be clear, if you are going to play the 'volunteer card', please understand that in the real world there *are* minimum requirements for volunteers.   
/end of rant

**Comment by spwhitt** [comment]
@wwat, please consider your tone.

RedHat and Debian have both been around for over 21 years. RedHat has the backing of a billion dollar corporation with 6,500 employees. Debian has over 1000 active developers.

By comparison nixpkgs+nixos combined have had very few (<20) contributors until just recently. Just look at these graphs: https://www.openhub.net/p/nixos . Additionally, NixOS is an attempt to do things differently, which takes additional development effort. Debian and RedHat need merely to maintain the status quo.

With such a tiny team the developers have naturally had to prioritize. Besides, they are volunteers, many of them working in their spare time. They have given all this to you, free. And yet despite their practically heroic effort in creating an absolutely amazing distro you have the gall to be upset over some comparatively minor deficiency in the 500k lines of code they have written. Do you think they contribute their time for free because they want to be scolded by GitHub ignoramuses all day?

Also, you're completely wrong on most your points, and entirely ignorant on the others. 

> In general, the only right response to what I said is "Yes, that would be better", but defending the current state is irrational at best.

I haven't seen anyone defend the current state of things.

> has almost no tools (compare with the Debian community or the many, many tools which Red Hat has internally), which means there is no timely updates of security issues, or new releases; it all depends on some human to take the time to do an upload

We do have a tool for this, but it's not fully automated and I can guarantee you Debian's isn't either. That would be a recipe for bugs.

> There should be a ton of automated commits happening in a project like NixOS

There are. Many thousands of packages were automated this way.

**Comment by 7c6f434c** [comment]
>@bjornfor I don't care one bit about whether a particular subset of features is available in a well considered way. There is only one decent design put forward (the one I outlined) and that has not been implemented. Anyone who has any experience in properly packaging something for NixOS should have done that, and not do some half-assed job (which is what it is now). 
At some point you started wondering why Wireshark is not removed.

It is not removed because _NixPkgs_ part is packaged as it should, and 
noone cared about _NixOS_ part, which may be unfortunate but is 
a separate concern.

>In general, the only right response to what I said is "Yes, that would be better", but defending the current state is irrational at best.
>
>Really, why is *anyone* defending the *undocumented* method for configuring wireshark in NixOS here? What do you imagine is going to happen when a random new security mechanism is introduced in Linux? Do you expect all the people who "just want to run wireshark as user X (with additional rights)" to keep track of such details? Why?! That only annoys users and lack of stability scares away a huge class of users who actually have the funds to make NixOS a success. If the goal is to annoy users, then please state that on the NixOS website, if not, stop arguing, and just say "yes, this is a good idea.". 

Apparently you are talking to a number of people who are constantly
annoyed by friendly low-level hiding features. I am among them.

I want to know what are the low-level requirements behind the packages
I use and I want to know how to implement low-level requirements that 
I already know. If a person has a problem and asks, I prefer to give 
that information because it would be helpful to a person like me who
will be likely to provide some interesting (to me) information later.

>Quoting from the website:
>```NixOS is a Linux distribution with a unique approach to package and configuration management. Built on top of the Nix package manager, it is completely declarative, makes upgrading systems reliable, and has many other advantages.```
>I think this is a complete lie (see my theoretical example about wireshark (for which I am sure practical examples can also be found), lack of backwards compatibility, and other misfeatures). NixOS might have as a goal to become "better", but back in the real world, when real engineers need to do something in a limited time, it's not actually 'better', because it is not documented. If it's not documented, _it_does_not_exist_. An interface which can disappear tomorrow again, is *not* worth our time. 

NixOS project is a 90% solution for people who were using their own 80%
solutions anyway to pool their efforts.

It actually does remove some problems that have bitten the real people
working on NixPkgs. Maybe these are non-problems for you.

>Similarly, why does someone have to manually partition a system in order to install NixOS? That's just begging people to not use NixOS. 

I manually partition disks even when I install Fedora because it ships
sane tools and a fragile UI around them. I would say we lack resources
to provide meaningful support to people who find partitioning disks an
action requiring an effort. You noticed the same fact, actually. But 
there are people for whom this is not a problem, some of them find Nix
package manager and NixPkgs useful.

>Let me restate it again; There is absolutely *no* point in manually packaging software. Basically, everything which is done manually sucks. There should be a ton of automated commits happening in a project like NixOS, but what appears to be happening is that there are some users who have their own scripts to maintain parts of the system in a semi-distributed, unprofessional matter.  And to be clear, if you are going to play the 'volunteer card', please understand that in the real world there *are* minimum requirements for volunteers.   

In the real work there are communities of people who use each other's
work. The minimum requirement for community members is to find each 
other's work useful and not split because of interpersonal tensions.

**Comment by goodwillcoding** [comment]
To note, after looking over all @wwat comment I can pretty much say @wwat is a troll, likely just @aragnon again.

Feed trolls with care, for the will make this a home.

**Comment by wwat** [comment]
@goodwillcoding You are a necroposter. Additionally, I have written some code, so fuck off.

**Comment by wwat** [comment]
The issue was about having a more properly managed wireshark installation. That has not been resolved, obviously. Just the fact that some people like to annoy other people (@goodwillcoding) in this case, doesn't change that.

**Comment by bjornfor** [comment]
@wwat: The issue of having more user friendly NixOS API for wireshark is a different topic, and you may of course open an issue about that. (Maybe by using ACLs, we can get something quite nice under programs.wireshark.*, that allows specifying access for single users, as well as (multiple) groups.)

But *this issue* is is titled "wireshark is not usable", and claims that

```
NixOS does not implement any of the methods described here to run wireshark
in any sane way http://wiki.wireshark.org/CaptureSetup/CapturePrivileges.
```

which is incorrect. As explained in comment above (https://github.com/NixOS/nixpkgs/issues/6235#issuecomment-73471886).

**Comment by wwat** [comment]
@bjornfor Fair enough. https://github.com/NixOS/nixpkgs/issues/6716
