### ISSUE TITLE
extras_require in python packages

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#62833]
## Issue description
Certain packages will have a [`extras_require`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras) in `setup.py`.

Currently I've advised people to follow the convention of adding an option like
`with$extra_name` following the name used for the feature in `setup.py`.

See [mailman-rss](https://github.com/NixOS/nixpkgs/blob/b5f3b7db524788400de609e45fc150b941c501f7/pkgs/development/python-modules/mailman-rss/default.nix#L1) for example. (https://github.com/kyamagu/mailman-rss/blob/master/setup.py#L45).

Is this something to document specifically for Python in nixpkgs?

**Comment by FRidh** [comment]
What to do with `extras_require` is up to the maintainer of a package. I recommend not adding these packages, because users can easily create an environment that includes those additional packages. We should not use options because that requires a rebuild of a package. One could make an exception in the case of applications, though again, composition is better done with a wrapper than through a rebuild.

**Comment by FRidh** [comment]
I've seen some bad things happening because we don't have a good way for this right now (example https://github.com/NixOS/nixpkgs/pull/115360).

Possible solution is one defines a `passthru.extras.${extra} = packages;`. A dependent could then do something like `propagatedBuildInputs = [ ... pkg ] ++ pkg.extras.${extra};`. Alternatively, the Python builder would provide a minimal derivation for each extra containing the `propagated-build-inputs` file.
