### ISSUE TITLE
SSHGuard shows could not initialize firewall

### ISSUE THREAD

**Issue by R-VdP** [NixOS/nixpkgs#62874]
## Issue description
When the service starts, the following message is printed to the logs:

sshguard[13576]: sshg-fw-ipset: Could not initialize firewall

Blocking does not actually work. Blocked hosts can still initialize ssh connections.

### Steps to reproduce
Default sshguard config.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.47, NixOS, 19.03.172786.606306e0eaa (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172786.606306e0eaa"`
 - channels(XXXX): `"nixpkgs-18.03.132444.9062afb7cb7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by wahjava** [comment]
It seems like that is due to `sshguard*` ipsets being created of different types than intended. I'm not sure where it's getting created with that though:

    # ipset -L
    Name: sshguard4
    Type: hash:ip
    Revision: 4
    Header: family inet hashsize 1024 maxelem 65536
    Size in memory: 88
    References: 1
    Number of entries: 0
    Members:
    
    Name: sshguard6
    Type: hash:ip
    Revision: 4
    Header: family inet6 hashsize 1024 maxelem 65536
    Size in memory: 104
    References: 2
    Number of entries: 0
    Members:

Whereas the script intends to create `hash:net` types which is why it returns with an error. I do not see where in the sshguard is `hash:ip` type of ipset getting created. I came across [this commit](https://bitbucket.org/sshguard/sshguard/commits/df73c1ab50be90466e25f42556cf75ca9fda4f07) though.
