### ISSUE TITLE
No haddock manpage

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#63026]
## Issue description

I develop a package using `shellFor { withHoogle = true; }`. I can start haddock but ` man haddock` fails.

On nixos-unstable.

**Comment by matthewbauer** [comment]
I don't think ghc provides a manpage for haddock. All of the documentation is in html:

https://haskell-haddock.readthedocs.io/en/latest/invoking.html

Since its Sphinx, it shouldn't be too hard to make it, but that should probably be brought up as a GHC ticket:

https://gitlab.haskell.org/ghc/ghc/blob/master/docs/users_guide/ghc.mk#L24

**Comment by teto** [comment]
I don't have a good understanding how ghc and haskell are linked.
Haddock has its own repository https://github.com/haskell/haddock but I couldn't find the manpage there.
I think haddock has a manpage because of http://manpages.ubuntu.com/manpages/bionic/man1/haddock.1.html .

**Comment by matthewbauer** [comment]
The debian man pages is quite out of date (2.6.1 vs. 2.22.0). It looks like it's hosted here:

https://salsa.debian.org/haskell-team/DHG_packages/blob/master/p/ghc/debian/haddock.man

but not maintained by ghc

**Comment by teto** [comment]
closing it since upstream doesn't seem to maintain it
