### ISSUE TITLE
sd-image-aarch64 shouldn't import profiles/installation-device.nix

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#63576]
## Issue description
When downloading the aarch64 sdcard image, the `/etc/nixos/configuration.nix` provided there imports `nixos/modules/installer/cd-dvd/sd-image-aarch64.nix`, which imports `nixos/modules/profiles/installation-device.nix`, which (among others) enables the nixos manual on tty8, force-enables the documentation, disabes sudo and udisks, disables sshd on bootup and enables automatic login as root without password.

We probably want to provide a different configuration.nix in `/etc/nixos/configuration.nix` not importing installer-related things (or at least make it easy to disable them). 

### Steps to reproduce
 - Download the aarch64 sdcard image
 - flash it to a raspberry pi3
 - edit /etc/nixos/configuration.nix (add `services.openssh.enable = true` for example)
 - call `nixos-rebuild switch`
 - wonder why it's not started

## Technical details
`nixos-sd-image-19.09pre183392.83ba5afcc96-aarch64-linux.img`

cc @NinjaTrappeur

**Comment by samueldr** [comment]
The idea here is that a `nixos-rebuild switch` using that `/etc/nixos/configuration.nix` would be identical from the first generation, since it's expected that a system is installed in-place.

The end-user *should* `nixos-generate-config` as one would from the installation media.

Though, I guess that shipping *no configuration* might be better in that optic; would not make it likely that users consider that line as being needed for their system to work.

Probably, also, the motd should better explain that `sshd` is already installed, merely disabled by default. That would be an improvement for the installer iso too.

**Comment by flokli** [comment]
I agree not shipping the configuration in that case might be better, if `nixos-generate-config` is sufficient. Is it for aarch64 already, and generates all the magic options properly, like extlinux etc.?

Motd can be a bit more helpful, yeah. Also, we should probably add the information about the manual on tty8, if we don't already do.

**Comment by samueldr** [comment]
[`nixos-generate-config` seems sufficient](https://github.com/NixOS/nixpkgs/blob/e0a1c8f003e294cc096de3cd3a0bc52c28204d32/nixos/modules/installer/tools/nixos-generate-config.pl#L589-L595).

The [manual is mentioned in the helpLine](https://github.com/NixOS/nixpkgs/blob/282041fb7b2cc0fcc031cedfd66b2fbf880fa6ee/nixos/modules/misc/documentation.nix#L204-L207) just as [is the fact that the root account has an empty password](https://github.com/NixOS/nixpkgs/blob/282041fb7b2cc0fcc031cedfd66b2fbf880fa6ee/nixos/modules/profiles/installation-device.nix#L41-L48).

Looks like we're not far off :).
