### ISSUE TITLE
Package `guardian-agent`

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#63834]
**Package Request**: [guardian-agent](https://github.com/StanfordSNR/guardian-agent)

`guardian-agent` is a way of being able to do agent forwarding when using mosh. It also allows verifying commands being executed. I don't fully understand how it works, but it seems valuable, especially as I shift back to using `mosh` on high-latency links.

**Comment by mmahut** [comment]
This project looks abandoned, it has been released as as beta in 2017.

**Comment by colemickens** [comment]
Hm, disappointing, but good point. I opened this to confirm: https://github.com/StanfordSNR/guardian-agent/issues/24

**Comment by colemickens** [comment]
@mmahut I'm not really sure if we should proceed. I was going to close it, based on the response to the issue I filed on the guardian-agent repo, but I see you have a PR open now...

**Comment by mmahut** [comment]
@colemickens while I thought the same, I changed my mind because of two things. First of all there is sadly no alternative to this and mosh won't implement one, they own recommendation is actually using guardian-agent (as per https://github.com/mobile-shell/mosh/issues/120#issuecomment-418008147). And in the second place, the author of the project, Dima Kogan, did reply to my mail almost instantly, so while this is marked as beta, I think we should ship it with NixOS and help catch any outstanding bugs/problems with it.
