### ISSUE TITLE
Build haskell-hmatrix with OpenBLAS instead of ATLAS/liblapack

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#6392]
See https://github.com/NixOS/nixpkgs/commit/380bd3f48aa47d91f4a67c8cf8e17d1ade121c92 as a reference.

**Comment by peti** [comment]
OpenBLAS doesn't work on `i686-linux` yet. :-(

**Comment by peti** [comment]
https://github.com/NixOS/nixpkgs/commit/380bd3f48aa47d91f4a67c8cf8e17d1ade121c92 contains further details.

**Comment by peti** [comment]
@ttuegel, I contemplate switching `haskell-hmatrix` and `R` (https://github.com/NixOS/nixpkgs/issues/6393) to OpenBLAS as well. Do you think that makes sense, or is there a compelling reason to stick to ATLAS/liblapack?

**Comment by ttuegel** [comment]
I can't think of a reason to stick with ATLAS. The Hydra builds of ATLAS and OpenBLAS both have poor performance, but OpenBLAS is easier for users to build locally.

**Comment by ttuegel** [comment]
`haskell-hmatrix` segfaults when compiled with OpenBLAS. I've been investigating the issue for several months without success.

**Comment by ttuegel** [comment]
Ah, I've discovered it's actually because our build of OpenBLAS enables 64-bit integers in the interface. Traditionally, BLAS and LAPACK use only 32-bit integers even on 64-bit platforms. Looking around at other packages in Nixpkgs, it seems like packages which depend on OpenBLAS specifically expect the integer width to match the platform pointer width, but packages that depend on a generic BLAS or LAPACK implementation want 32-bit only. I'm in the process of fixing our OpenBLAS thus. I'll open a PR to switch `haskell-hmatrix` soon.

By the way, this comment:

> The Hydra builds of ATLAS and OpenBLAS both have poor performance, but OpenBLAS is easier for users to build locally.

is no longer true! Following Debian's example, I have enabled dynamic architecture detection in our OpenBLAS build. The Hydra-built binaries should be equal in performance to any local build. The build does take slightly longer because it builds every microarchitecture-specific kernel, but the compatibility and performance improvements greatly outweigh the build time increase.
