### ISSUE TITLE
Nix doesn't like the hardened profile

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#64078]
## Issue description
While trying the `<nixos/profiles/hardened.nix>`,I've found that using the 
graphene-hardened allocator will make nix `error:out of memory` if the evaluated expression is big enough.

### Steps to reproduce
- Add `environment.memoryAllocator.provider="graphene-hardened";` to `configuration.nix`
-`nixos-rebuild switch&&reboot`
- Following `nixos-rebuild` will fail with `error:out of memory`

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by eadwu** [comment]
Switch to `scudo` (nix at least works, but manpages are shot for me) or back to `libc`. Related, #60187 and #61489.

**Comment by pasqui23** [comment]
I forgot to mention that ` security.allowUserNamespaces = mkDefault false;` is incompatible with nix sandboxing(also why?)

**Comment by joachifm** [comment]
@pasqui23 do you mean why it's incompatible or why its disabled? The former is because Nix relies on user namespacing for its sandbox; the latter is because unprivileged userns has been used for exploits in the past and so paranoia suggests disabling it by default in a hardened deployment.  Hardened deployments are routers and the like which should not be running arbitrary build instructions anyway. The idea is that if you want to build stuff, you actively relax the default.

**Comment by joachifm** [comment]
I think the issues referred to by @eadwu are already sufficient, so I'm closing this one. Please add any supplementary info regarding the hardened malloc on those issues.
