### ISSUE TITLE
ghc-pkg: you don't have permissions to modify this file.

### ISSUE THREAD

**Issue by meditans** [NixOS/nixpkgs#6419]
Hi, I'm using nix in fedora, with the nixpkgs-unstable channel.
Among the other things in my `config.nix`, I defined:

    haskellDevEnv = self.haskellngPackages.ghcWithPackages (p: with p; [
      cabal-install
      structured-haskell-mode
    ]);

when I try `nix-env -iA nixpkgs.haskellDevEnv` i get this error towards the end of the installation:

    ghc-pkg: /nix/store/s6c7wgcia36mwwq4q0k1manzi3x9ni7a-ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/package.cache: you don't have permission to modify this file
    builder for ‘/nix/store/xwy2dbirvjacfyb6gcbpskzyrx01mcdp-ghc-7.8.4.drv’ failed with exit code 1
    error: build of ‘/nix/store/xwy2dbirvjacfyb6gcbpskzyrx01mcdp-ghc-7.8.4.drv’ failed

Any ideas on why this happens?

**Comment by peti** [comment]
This is a bug in the `ghcWithLibraries` function I've been meaning to fix but haven't gotten around to yet. The problem is that you have only *one* library in that packet list (`cabal-install` is a tool but no library), and the wrapper function doesn't deal gracefully with that case. It sounds silly, I know, but you can remedy that issue by (a) adding a second library to the environment, say `ghc-paths`, or by (b) removing `cabal-install`.

**Comment by meditans** [comment]
Got it, thanks for the quick reply :)

2015-02-18 20:42 GMT+01:00 Peter Simons <notifications@github.com>:
