### ISSUE TITLE
Git and SSL do not work in nix-shell 

### ISSUE THREAD

**Issue by josephsdavid** [NixOS/nixpkgs#64212]
## Issue description
`git` and all `ssl` related operations in nix-shell

### Steps to reproduce
`git clone https://github.com/josephsdavid/forecastR.git`

## Technical details

``` - system: `"x86_64-linux"`
 - host os: `Linux 5.1.15, NixOS, 19.09pre184452.5a7ab1963a9 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(dj): `"home-manager, nixpkgs-19.09pre174594.0c0954781e2"`
 - channels(root): `"nixos-19.09pre184452.5a7ab1963a9, nixpkgs-19.09pre178895.9ebc6ad944c"`
 - channels(david): `"home-manager, nixpkgs-19.09pre184398.d98a165de78"`
 - nixpkgs: `/home/david/.nix-defexpr/channels/nixpkgs`
```

**Comment by josephsdavid** [comment]
Tried all fixes mentioned in #16031 and related issues no luck

**Comment by jonringer** [comment]
I'm only able to reproduce this if i add `--pure` to the command

```
$ nix-shell -p git --pure

[nix-shell:~/projects/nixpkgs]$ git fetch
fatal: unable to access 'https://github.com/NixOS/nixpkgs.git/': SSL certificate problem: unable to get local issuer certificate
```
```
$ nix-shell -p git

[nix-shell:~/projects/nixpkgs]$ git fetch

[nix-shell:~/projects/nixpkgs]$
```

**Comment by josephsdavid** [comment]
Ah this makes some sense, the issue is I am using lorri for my project, which I am guessing was updated to do pure nix shells today or something.

**Comment by josephsdavid** [comment]
ah yep: https://github.com/target/lorri/issues/98

**Comment by matta** [comment]
Since I landed here first via websearch I thought I'd leave some links to more detailed discussions of this issue. Seems like making things work in `--pure` shells is a good idea, no? How else can I tell if the shell's closure is complete?

Related issues: https://github.com/NixOS/nix/issues/795, https://github.com/NixOS/nixpkgs/issues/3382 (especially https://github.com/NixOS/nixpkgs/issues/3382#issuecomment-513596055).
