### ISSUE TITLE
NetworkManager: Can't connect to VPN

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#64259]
## Issue description

When i try to connect to a VPN, just a red (!) appears. In the syslog, i see this messages:

```
Jul 03 20:35:15 ethmoid .wingpanel-wrap[14609]: VpnMenuItem.vala:93: An VPN is being connected but not active.
Jul 03 20:35:15 ethmoid NetworkManager[961]: <error> [1562178915.1812] vpn-connection[0xf9e0b0,770884c2-9503-45eb-9a05-f0e30d5a31c1,"CyberGhost",0]: Failed to request VPN secrets #3: No agents were available for this request.
Jul 03 20:35:15 ethmoid .wingpanel-wrap[14609]: VpnMenuItem.vala:93: An VPN is being connected but not active.
```

I tried 2 OpenVPN VPNs that worked in the past on Mac OS X (as it was named so) and elementary OS and also one vpnc.

Not sure if the problem is related to Pantheon desktop or NetworkManager. Do VPNs work on GNOME?

cc @worldofpeace 

### Steps to reproduce

My config: https://github.com/davidak/nixos-config/tree/master/machines/ethmoid

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.49, NixOS, 19.03.172866.4649b6ef4b5 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172979.8634c3b6199, nixos-hardware, nixos-unstable-19.09pre183392.83ba5afcc96"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by angristan** [comment]
I'm using GNOME, OpenVPN + NetworkManager works fine.

**Comment by worldofpeace** [comment]
Did you use `Store the password for all users`? @davidak 
![Screenshot from 2019-07-03 21 06 12](https://user-images.githubusercontent.com/28888242/60632948-6d127880-9dd6-11e9-9821-2aa08a639740.png)

Otherwise I wouldn't work for me. I believe this is because `gnome-keyring` isn't functioning in Pantheon.

@angristan Does it work for you if you don't use `Store the password for all users`?

**Comment by davidak** [comment]
@worldofpeace i used "store only for this user". the password is not visible anymore when i save and reopen. maybe it disappears.

But i have this issue also when just using certificates with OpenVPN.

**Comment by angristan** [comment]
I also use "Store the password only for this user"

**Comment by worldofpeace** [comment]
Yeah so this is because `gnome-keyring` is improperly configured for Pantheon and LightDM.
Specifically a keyring isn't created on Login or unlocked.

Quoting Arch Wiki on NetworkManager and GNOME Keyring
> The keyring daemon has to be started and the keyring needs to be unlocked for the following to work.
> Furthermore, NetworkManager needs to be configured not to store the password for all users. Using GNOME nm-applet, run nm-connection-editor from a terminal, select a network connection, click Edit, select the Wifi-Security tab and click on the right icon of password and check Store the password only for this user.

Pretty sure both Pantheon and GNOME3 are using `nm-connection-editor` and this applies to storing any secret. So for any connection to work you have to use `Store the password for all users` or enter it manually every time.

To fix this we need something like https://github.com/NixOS/nixpkgs/commit/5b9895b1a077c5c431b08a88749a4958472cab3c

Additionally `switchboard-plug-network` isn't handling this failure for VPN connection as gracefully as it could.
(nmtui would just have you enter the password manually)

**Comment by davidak** [comment]
>So for any connection to work you have to use Store the password for all users or enter it manually every time.

It works for the vpnc connection, but i still have issues with OpenVPN.

My home vpn uses certificates without password. But when i have no password set, i still get this error. When i set "1" as password, it tries to connect, but fails. I could configure a password, but i'm not at home the next days and it's also just a workaround.

I'm also not able to save an empty password field. It was possible in 2 cases out of about 50!

**Comment by worldofpeace** [comment]
I think that might be https://gitlab.gnome.org/GNOME/network-manager-applet/issues/59 then.
(different from just username and password)

**Comment by worldofpeace** [comment]
I can confirm that fixing `gnome-keyring` for Pantheon and enabling `programs.nm-applet.enable` allows me to use `Store the password only for this user` for wifi connections and for OpenVPN username password.

https://github.com/worldofpeace/nixpkgs/commit/fea0522c0dce9dc155f4321b010692d9b2f12634 and https://github.com/worldofpeace/nixpkgs/commit/14c6133d7eeccceec5e4d17b985ba1ec93fe32ba.
Though I'm not so confidant in the correctness of https://github.com/worldofpeace/nixpkgs/commit/fea0522c0dce9dc155f4321b010692d9b2f12634.
