### ISSUE TITLE
nomad: "Nomad UI is not available in this binary."

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#64410]
## Issue description

nomad appears to be built without the UI.

### Steps to reproduce

On nixpkgs master:

```
nomad agent -dev
nomad ui
```

and observe your browser opening a page showing:

```
Nomad UI is not available in this binary. To get Nomad UI do one of the following:

Download an official release

Run
make release
to create your own release binaries.

Run
make dev-ui
to create a development binary with the UI.
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.57-hardened, NixOS, 19.09.git.a3a9b08 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `""`
 - nixpkgs: `/var/nixpkgs`

**Comment by arianvp** [comment]
This is correct. We do not ship the Nomad UI because we would have to vendor all the javascript dependencies which amounts to a few-thousand extra packages in the package set just for Vault/Nomad which is really difficult to get working on nixpkgs and increases the source code size by quite a bit .  We have the same problem with Vault on which I gave up trying to get it to work. The PR for that is here: https://github.com/NixOS/nixpkgs/pull/49082  which might help you get it working for Nomad.    If you have ideas on how to get this into nixpkgs elegantly without it getting in the way, i'm happy to hear about it. Otherwise I think it might be more suitable to put nomad and vault UI in some outside package repository like  https://github.com/nix-community/NUR

Consul UI works because the authors commit the resulting _compiled_ javascript to their github repository. This means we don't have to install all the npm packages ourselves.    I asked hashicorp if they were interested to do the same with nomad and vault, but they were not open to this idea. Hence we're shipping without UI.

**Comment by arianvp** [comment]
Still relevant.

How I suggest to solve this ticket:

include a `nomad-bin` package just like we have `vault-bin`; that does ship the UI but isn't built from source

**Comment by jktr** [comment]
The nomad package for nix includes the UI since f6c47d01a4900312ac5b84f1ccc0010bed29bfd2 (v0.9.5, 2019-08-31).

Upstream includes the precompiled UI for its release commits, so unless you're planning on running a non-release commit / doing development this issue seems solved. A `nomad-bin` is thus probably not necessary, as the only releases for which we could build such a package already have the UI included in their nixpkgs version.
