### ISSUE TITLE
audio-recorder: Gstreamer-plugins not available

### ISSUE THREAD

**Issue by GRBurst** [NixOS/nixpkgs#64456]
## Issue description
audio-recorder does not recognize gstreamer-plugins. manually installing them do not solve the problem. 

```sh
$ audio-recorder
(audio-recorder:5209): GStreamer-CRITICAL **: 21:18:54.090: gst_object_unref: assertion 'object != NULL' failed
Error:To support m4a format you should install Gstreamer-plugins for .
Error:Installation of Gstreamer-plugins failed (GST_INSTALL_PLUGINS_HELPER_MISSING).
Error:
(audio-recorder:5209): Gtk-WARNING **: 21:18:54.213: Could not find the icon 'audio-recorder-off-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(audio-recorder:5209): Gdk-CRITICAL **: 21:18:54.231: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(audio-recorder:5209): GStreamer-CRITICAL **: 21:18:58.117: gst_object_unref: assertion 'object != NULL' failed
Error:To support m4a format you should install Gstreamer-plugins for .
Error:Installation of Gstreamer-plugins failed (GST_INSTALL_PLUGINS_HELPER_MISSING).
Error:
```

### Steps to reproduce
Start audio-recorder (preferable from command-line) and try to record using `M4A` format.
The cmd-line produces the error mentioned above.
Tried it on different NixOS installations.

## Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.57, NixOS, 19.03.173054.754763ff4ba (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(user): `"nixos-unstable-19.09pre184359.73392e79aa6"`
 - channels(root): `"nixos-19.03.173054.754763ff4ba, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by milahu** [comment]
similar to https://github.com/NixOS/nixpkgs/pull/94067

should be fixed by adding this to `pkgs/top-level/all-packages.nix`
```nix
{
  audio-recorder = callPackage ../applications/INSERT/PATH/TO/audio-recorder.nix {
    inherit (gst_all_1) gstreamer gst-plugins-base;
  };
}
```

**Comment by xuancong84** [comment]
The reason is not because audio-recorder cannot recognize Gstreamer-plugins, or Gstreamer-plugins are not installed, rather it is because Gstreamer has updated their plugins' calling format, but audio-recorder has not updated its default calling profile (see https://bugs.launchpad.net/audio-recorder/+bug/1912876).

The solutions are very simple, either:
A) modify audio-recorder source code, in media-profiles.c, change the following line:
`{"CD Quality, AAC 44KHz", "m4a", "", "audio/x-raw,rate=44100,channels=2 ! avenc_aac compliance=-2 ! avmux_mp4"}`
into:
`{"CD Quality, AAC 44KHz", "m4a", "", "audio/x-raw,rate=44100,channels=2 ! avenc_aac ! mp4mux"}`
and recompile audio-recorder, or

B) change audio-recorder settings, in "Additional settings" => "recording commands" => "AAC ...",
change the command from:
`"audio/x-raw,rate=44100,channels=2 ! avenc_aac compliance=-2 ! avmux_mp4"`
to:
`"audio/x-raw,rate=44100,channels=2 ! avenc_aac ! mp4mux"`
Since audio-recorder saves profile settings in _dconf_ registry, these settings persist even if you upgrade audio-recorder or uninstall/reinstall it.

**Comment by GRBurst** [comment]
This seems to be fixed. Closing it now.
