### ISSUE TITLE
Add network-manager to minimal installation

### ISSUE THREAD

**Issue by SomeDer** [NixOS/nixpkgs#64700]
I find network-manager easier to use than wpa_supplicant, but network-manager doesn't seem to be present in the installer.

**Comment by lheckemann** [comment]
network-manager is not suitable for the minimal image, because it's a lot bigger and more complex, increasing the size of the image by >50M. You can use the graphical installer image if you want network-manager (and it doesn't start the graphical desktop automatically, so that won't be a problem if e.g. you have graphics issues with X).
