### ISSUE TITLE
bzip2: 1.0.7

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#64817]
The package has a new maintainer and upstream:

https://people.gnome.org/~federico/blog/bzip2-107-is-released.html

**Comment by dtzWill** [comment]
Looks like they're up to 1.0.8 now, FWIW: https://www.sourceware.org/bzip2/downloads.html

**Comment by gloaming** [comment]
ping @vcunat @copumpkin 

What's up with the "libtoolized" SUSE patch? AFAICT all it does it produce a useless `.la` file. Both the `.so` and the `.a` build without it; I rebuilt it with the stock tarball and and shared-object Makefile and it seems to be fine.

Hardly any packages even depend on `bzip2.out` anyway; `sublime3` mentions it in a weird `postFixup`, but that `postFixup` seems to break things rather than fix them, so I can't really test anything.

The other one is `bitwig-studio1` which explicitly references `${bzip2.out}/lib/libbz2.so.1.0.6` for some insane reason. It's dynamically loaded though, and I don't care enough to try and find what feature uses it.

Perl also mentions `bzip2.out`. Not sure what to make of that.

**Comment by vcunat** [comment]
The patch was useful *before* the recent maintenance pick-up upstream.  I don't expect it will be useful anymore.

**Comment by jtojnar** [comment]
.

**Comment by mschwaig** [comment]
What @tpwrules mentions is still an issue. I mentioned that just now on the closed PR to merge 1.0.8: https://github.com/NixOS/nixpkgs/pull/65029

**Comment by smancill** [comment]
Fixed by #181198
