### ISSUE TITLE
bzip2 package doesn't produce libbz2.dylib on darwin

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#6504]
This seems fairly easy to fix, but I noticed that bzip2 has some unusual custom builder stuff going on and I wanted to see if anyone knew what was going on there before I went and changed it. Is there a reason we don't go with the usual `configure && make && make install` in that package?

**Comment by dezgeg** [comment]
That's because bzip2 doesn't use autoconf/automake but has it's custom makefiles (which only knows to build dynamic libs on ELF systems).

It'd be nice to get this fixed since bzip2 is currently blocking the multiple-outputs branch on Darwin (https://github.com/NixOS/nixpkgs/commit/5df65579ce44a30addf8bc3812b959d198bf4fcd for discussion). What'd need to be done is to patch `Makefile-libbz2_so` in the bzip2 source tree (https://gist.github.com/dezgeg/444ae4e59f04ec04574f) to work on Darwin.

**Comment by vcunat** [comment]
I don't know... perhaps the best one can do is to add a few commands by hand https://trac.macports.org/browser/trunk/dports/archivers/bzip2/files/patch-Makefile-dylib.diff

**Comment by vcunat** [comment]
Ah, Gentoo is probably the best shot: https://gitweb.gentoo.org/repo/proj/prefix.git/tree/app-arch/bzip2/files/bzip2-1.0.6-Makefile-libbz2_dylib

**Comment by dezgeg** [comment]
Yeah, the Gentoo one looks good.

**Comment by copumpkin** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/31ab7d38f23e556fd4e25508bed02455474b6c97

**Comment by copumpkin** [comment]
Also, this affects nothing, but I'm confused as to why Gentoo would be hosting a darwin-specific makefile. @vcunat @dezgeg any ideas?

**Comment by vcunat** [comment]
Gentoo has all kinds of things... also some FreeBSD stuff IIRC.

**Comment by copumpkin** [comment]
Now I'm even more confused :)

**Comment by vcunat** [comment]
I expect it's just like NixOS.org having darwin-specific stuff ;-) (besides BSD, solaris, windows and others)
