### ISSUE TITLE
Typo in configuration option security.virtualization.flushL1DataCache

### ISSUE THREAD

**Issue by praduca** [NixOS/nixpkgs#65044]
## Issue description
The option `security.virtualization.flushL1DataCache`  is the only one written with the spell "virtualization". For consistency, it shoud be renamed to `security.virtualisation.flushL1DataCache` .

As a side note, searching for "virtualization" brings `security.allowSimultaneousMultithreading` as a result. and the word virtualization doesn't appear anywhere in the description.

### Steps to reproduce
Not applicable

## Technical details
Not applicable

**Comment by joachifm** [comment]
I'd accept a PR to fix the spelling issue. I suppose the reason why the latter option shows up is that the description refers to the former. The relationship is that disabling SMT is required to fully mitigate the concerns over data leaks to/from malicious guests (that is leaks between hyperthreads on the same physical core, due to shared caches and whatnot).
