### ISSUE TITLE
PAM nodelay option

### ISSUE THREAD

**Issue by Alkeryn** [NixOS/nixpkgs#65551]
I know there is a PAM nodelay option that allow to set the sudo repeat delay (when typing a wrong password to 0) i know how to change that on regular distro (by editing a file in /etc/pam.d)
but i'm not quite sure how to do that in nixos, any ideas ?

**Comment by worldofpeace** [comment]
We should probably add an option somewhere in the correct section here
* https://github.com/NixOS/nixpkgs/blob/61c945ae2566ec0d2ded709b6b8fde5b56c0bb6d/nixos/modules/security/pam.nix#L317

**Comment by Alkeryn** [comment]
Here is an example of how to do it in a regular distro
![image](https://user-images.githubusercontent.com/11599075/62045974-23ffe980-b207-11e9-8c27-4e4682739d7b.png)
Source :
https://unix.stackexchange.com/questions/40954/how-does-one-change-the-delay-that-occurs-after-entering-an-incorrect-password

**Comment by Aptrug** [comment]
I'm also interested in setting `su`'s delay to 0 just like OP. Any way to do it?

**Comment by Alkeryn** [comment]
> I'm also interested in setting `su`'s delay to 0 just like OP. Any way to do it?
you can see that the issue has been closed and the option nodelay has been added in that merge : https://github.com/NixOS/nixpkgs/pull/80896/files/dc1efa99a08eec9d56fcd55b2a182a601ab7608e#diff-a978e1441b38e12f4d684ab4f8cf2f1cbf5836629de4d41e30d0d5335adcde2e

**Comment by Aptrug** [comment]
@Alkeryn I should have mentionned that I already tried that options — I added `security.pam.services.su.nodelay = true;`  to `/etc/nixos/configuration.nix` and it doesn't seem to have any effect (Yes, I did reboot), and just to be sure I just added the whole output of `find /etc/pam.d/ -type l -printf 'security.pam.services.%f.nodelay = true;\n'` to `/etc/nixos/configuration.nix` and yet `su` still has a delay when entering the wrong password (unlike sudo).
I'm asking because I don't know whether this is an issue on its own or I'm doing something wrong.

**Comment by Alkeryn** [comment]
@Aptrug odd, ik that you did reboot but did you rebuild the configuration ?
idk, haven't been using nix in a good while but maybe someone can help you better than i can.
it is definitely weird though.

**Comment by Alkeryn** [comment]
@Aptrug just looked it up, it seems that the delay of su is builtin, so not caused by PAM whereas sudo's is.
so you'd probably need to patch "su" itself, you maybe could do a nix overlay over the package or something.
