### ISSUE TITLE
profile-sync-daemon: New version available and useOverlayFS?

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#6576]
Hereby pinging @prikhi,

While searching for my original issue (which was finding the `clean` option for `psd`; which was implemented in a later version than we are shipping) I stumbled upon the following:

I've noticed that there is an oddity with the github page for profile-sync-daemon. Specifically the [README.md](https://github.com/graysky2/profile-sync-daemon/blob/master/README.md) mentions that we supposedly have `useOverlayFS = true/false`, however, I was not able to find that to be the case.

Also, it seems that the author has implemented some NixOS specific modifications in the meantime.

Thanks!

**Comment by devhell** [comment]
@prikhi ping? :)

**Comment by devhell** [comment]
@prikhi bamp

**Comment by prikhi** [comment]
Woo, you bumped this while I had free time so I actually worked on it - thanks :P

psd had an overhaul where the configuration and services were moved to the user instead of the system(`~/.config/psd/psd.conf` and `systemctl --user`). Should NixOS still handle the configuration and services?

I've got the latest package built, but haven't messed with nixos modules in a while so not sure what the best way to handle user services and config files is.

**Comment by prikhi** [comment]
Oh and it seems the overhaul removed the nixos specifics - was just a modified man page I believe.

**Comment by prikhi** [comment]
https://github.com/prikhi/nixpkgs/tree/update-psd

**Comment by devhell** [comment]
Hey! Cool! I was already worried that you vanished off the face of the earth. :-)
For a user module, have a look at [canto-daemon](https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/nixos/modules/services/misc/canto-daemon.nix) for example. I guess the configuration could be done in a similar way to how it is done now?

**Comment by osener** [comment]
https://github.com/graysky2/anything-sync-daemon by the same author would also be an useful addition

**Comment by prikhi** [comment]
I have again ran out of time, did not get to making a user module. I can quickly update it again if we want to update the package w/o a user module for now.

**Comment by devhell** [comment]
@prikhi Sounds good to me, at least an updated version would be much appreciated. :)

**Comment by Profpatsch** [comment]
triage: done?

**Comment by johnalotoski** [comment]
Hi @prikhi.  The current profile-sync-daemon-v5.53 NixOS package does not work on NixOS version 18.03 with the default bash version (4.4.12 on kernel 4.14.56).  A post installation review of the psd service status or `psd preview` command shows the following type of error:

`/run/current-system/sw/bin/psd: line 395: ${#DIRArr[@]##*/}: bad substitution`

This error has been noted in the upstream as occurring starting with Bash 4.4.  It has been fixed in a newer psd version.  Relevant links are:

[https://github.com/graysky2/profile-sync-daemon/issues/182](url)

and

[https://github.com/graysky2/profile-sync-daemon/pull/185](url)

It looks like psd v6.26 is the first version to contain the fix with the most recent tagged version of psd being at v6.33.

John

**Comment by prikhi** [comment]
I no longer have time to maintain the psd package - sorry.

**Comment by devhell** [comment]
I don't think there is much point in keeping this issue open. Closing.
