### ISSUE TITLE
fractal panics at runtime

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#65843]
```
[cole@xeep:~]$ fractal
thread 'main' panicked at 'libgtk-3 was configured with `--enable-debug=no`. See https://github.com/gtk-rs/gtk/issues/270 for details', /build/fractal-4.0.0-vendor/gtk/src/rt.rs:137:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by colemickens** [comment]
see: https://github.com/gtk-rs/gtk/issues/270 per the message.

**Comment by worldofpeace** [comment]
https://github.com/gtk-rs/gtk/pull/296#issue-65709442 I guess we have to change how we build things to accommodate this.

I must mention I don't think I encountered this.

**Comment by worldofpeace** [comment]
Ok so we need to manually add
* https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/configure.ac#L522


to the `CFLAGS` because you can't do this in meson.

For glib we should also do
* https://gitlab.gnome.org/GNOME/glib/blob/master/meson.build#L217

I guess it makes sense that this won't happen since we've switched to `plain` buildtype.
That's for when you want the most control over these types of things.

**Comment by worldofpeace** [comment]
@colemickens This check was actually removed from gtk-rs
* https://github.com/gtk-rs/gtk/pull/822

And that's present in the 0.7.0 release which is used in the latest version of the application.
* https://gitlab.gnome.org/GNOME/fractal/blob/master/Cargo.lock#L1027

So this shouldn't be an issue for `fractal` anymore but we should still fix gtk and glib.

**Comment by colemickens** [comment]
Hi @worldofpeace, I did get confused, mostly how you didn't see it. But maybe we were on slightly different snapshots of the channel and you landed on both sides of it? Fractal is launching for me again (albeit I'm signed out?)

I was going to ask if we should open a separate issue or leave this to track, but it sort of seems like you may have already sent a fix for it? Can you confirm or go ahead and close this if there's no further action? Thanks!

**Comment by worldofpeace** [comment]
As per https://github.com/NixOS/nixpkgs/issues/65843#issuecomment-517929514 the code that causes the panic is gone,
 but until https://github.com/NixOS/nixpkgs/pull/65850 hits master there will be issues with memory unsafety
as there's no pre-condition checks and assertions.

But yes, this issue is fixed. Thanks for responding @colemickens.
