### ISSUE TITLE
Rename several GNOME3 options

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#66302]
Currently these options, after reflection, are named confusingly because they're aren't useful as a standalone "service" and are better recognized as programs/applications.

* `services.gnome3.file-roller.enable` -> `programs.file-roller.enable`
* `services.gpaste.enable` -> `programs.gpaste.enable`
* `services.evince.enable` -> `programs.evince.enable`
* `services.gnome3.gnome-disks.enable` -> `programs.gnome-disks.enable`
* `services.gnome3.gnome-documents` -> `programs.gnome-documents`

Not sure if `services.gnome3.sushi` should be a `programs`.

---

Do you think it's worth it to rename these like this?
It's already confusing that you have to use a NixOS module
to use certain packages. Could we devise something better here?

**Comment by worldofpeace** [comment]
cc @hedning @jtojnar

**Comment by jtojnar** [comment]
Agree that `programs.` namespace makes more sense for these options. I would keep sushi in services since it is not really usable on its own.

Renaming options is actually less intrusive than the package renames since we have `mkRenamedOptionModule` so I would not fear it.

We could make automatic service registration for all packages installed to one of `NIX_PROFILES` but for packages run directly from result directory, we would need some sort of daemon watching profiles. We were [talking](https://logs.nix.samueldr.com/nixos/2019-08-05#2456128) about it on IRC few days ago.

**Comment by worldofpeace** [comment]
Actually, why do these modules need `services.dbus.packages` when `config.system.path` is already added already?
* https://github.com/NixOS/nixpkgs/blob/47b551c6a854a049045455f8ab1b8750e7b00625/nixos/modules/services/system/dbus.nix#L96

> We could make automatic service registration for all packages installed to one of NIX_PROFILES but for packages run directly from result directory, we would need some sort of daemon watching profiles. We were talking about it on IRC few days ago.

That would be much more intuitive.

**Comment by jtojnar** [comment]
> Actually, why do these modules need `services.dbus.packages` when `config.system.path` is already added already?

I do not think they need it. Remember that dconf service worked even when it was in `environment.systemPackages` (or when it got into environment from `propagatedUserEnvPkgs`).

**Comment by jtojnar** [comment]
I would guess we use `services.dbus.packages` in order not to link the package tree into a profile when it is not necessary.

**Comment by worldofpeace** [comment]
Right, and that's only needed for when it's explicitly a service and these modules are not :+1:
