### ISSUE TITLE
krdc is broken in !NixOS (Ubuntu)

### ISSUE THREAD

**Issue by wwat** [NixOS/nixpkgs#6646]
There is no dropdown with the protocols available (like rdp/vnc): 

![bugkrdc](https://cloud.githubusercontent.com/assets/10177188/6464903/bd4ef0b6-c1bd-11e4-9faa-fa5e6fcc7c80.jpg)

This works fine on /usr/bin/kdrc from Ubuntu 14.10. 

I tried with Nix packages `krdc-14.12.1` and `krdc-4.14.3`.

**Comment by ttuegel** [comment]
@wwat This is probably an environment issue. What is your `QT_PLUGIN_PATH` set to?

**Comment by wwat** [comment]
The existence of those drop downs should not depend on that. If it does, the program (or the packaging) is flawed. 
```
/home/wwat/.kde/lib/kde4/plugins/:/usr/lib/kde4/plugins/
```

**Comment by ttuegel** [comment]
Many KDE programs detect their components at runtime through the paths in `QT_PLUGIN_PATH`, so it certainly can depend on that. Arguably, that's a bad decision by upstream, but that's how it is. I will check what plugins are needed; we can modify `QT_PLUGIN_PATH` at runtime as necessary. Unfortunately, we have to do that on a case-by-case basis as we discover broken programs.

**Comment by ttuegel** [comment]
I cannot fix this by wrapping `krdc` itself because it does not look for plugins at runtime, it installs protocol handlers that must be registered by `kbuildsycoca4` at startup. As you are not on NixOS, you will need to set some environment variables yourself; I made a list of the required settings on the [wiki](https://nixos.org/wiki/KDE#Using_KDE_outside_NixOS). I realize this is not the desired resolution, but until something like #1750 is implemented, there is no way for me to affect the required settings outside of NixOS.
