### ISSUE TITLE
systemd: update to 227

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#6671]
@vito already updated our systemd patches to 219: https://github.com/edolstra/systemd/issues/3

**Comment by vito** [comment]
fyi, I ran into a few problems when upgrading the nixpkgs package itself. the feedback loop was slow (rebuilding systemd triggers a bunch of things to rebuild) so I only go so far.

My branch is [here](https://github.com/vito/nixpkgs/commits/systemd-v219).

* Many unrelated packages started failing while being rebuilt, as they couldn't find `-lcap`. Some were fixed by propagating the input, but some weren't. I confess I have no idea what I'm doing there.

* More dependencies are needed for `importd`, which is used by `machinectl pull-X`. I got this partially working, but could not get `pull-dkr` to work as it couldn't validate the `https` certs. May also be true for other things that pull from https URIs.

Unfortunately it looks like I never got to pushing the added dependencies for `importd`; I think it was `bzip2`, `curl`, and a few others. I found them listed in `systemd`'s build scripts somewhere.

Hope this helps.

**Comment by domenkozar** [comment]
@edolstra do you plan to tackle this one?

**Comment by wkennington** [comment]
Https://github.com/wkennington/systemd has all of his needed patches
forward ported for systemd 220 (unreleased but should be soon).

**Comment by edolstra** [comment]
@domenkozar Yeah, I was actually looking at this yesterday. But if 220 is due soon, I'll wait for that.

**Comment by edolstra** [comment]
220 was just released. I've updated the 219 branch to 220, since the changes don't look too dramatic. The 219 -> 220 upgrade went flawless in a container.

**Comment by dezgeg** [comment]
I tried this (on an ARM board) and udev on stage-1 crashes. It still boots successfully, though.

````
starting version 220
Assertion 'manager->pid == getpid()' failed at src/udev/udevd.c:568, function event_queue_insert(). Aborting.
starting device mapper and LVM...
````

**Comment by thoughtpolice** [comment]
Looks like this patch is needed (available in the git repository): http://permalink.gmane.org/gmane.linux.redhat.fedora.extras.cvs/1571847

**Comment by edolstra** [comment]
I'll apply that, thanks!

**Comment by dezgeg** [comment]
Yup, can confirm that the issue doesn't exist anymore on the latest systemd-219 branch.

**Comment by vcunat** [comment]
Is there something that the branch needs to wait for? Any reason not to merge it into staging? If we want such nontrivial changes in 15.06... IMO we should have it in a channel two weeks before release at least.

**Comment by edolstra** [comment]
Hopefully I'll have some time for it tomorrow.

**Comment by vcunat** [comment]
Ping. Still seems to be in the same state, and the release would've been shipped by now if we went on schedule...

**Comment by vcunat** [comment]
BTW, the WIP seems to be in the branch [systemd-219](https://github.com/NixOS/nixpkgs/compare/systemd-219).

**Comment by copumpkin** [comment]
@thoughtpolice says he's also rebased all changes onto 224

**Comment by edolstra** [comment]
Updated: http://hydra.nixos.org/jobset/nixos/systemd-226

**Comment by domenkozar** [comment]
@edolstra status on this? Would be nice to get it merged early

**Comment by vcunat** [comment]
Note: I'm currently working with #7701 merged atop this (and staging), as I *expect* this to hit staging soon and udev stuff needs fixing in #7701 (I'll probably unsplit systemd).

**Comment by vcunat** [comment]
Hmm, now there's 227 with *lot's of new awesomeness, and many bugfixes!* Lennart is just too fast for us.

**Comment by steveeJ** [comment]
The current nixpkgs/master systemd version is 217 which has been released over a year ago. Especially machinectl and systemd-nspawn are moving very fast and had tons of updates since 217. Therefore, I kindly ask you merge whatever version is ready so we'll eventually have it in unstable or the staging branch.

**Comment by copumpkin** [comment]
What is the actual blocker to merging here? Are things going to break and we need some sort of upgrade path? Just trying to understand why this is on a separate branch to begin with.

**Comment by edolstra** [comment]
There are still some failing builds: http://hydra.nixos.org/jobset/nixos/systemd-227

The build failures have been mostly due to libgudev becoming a separate package.

**Comment by vcunat** [comment]
Hmm, Hydra seems stuck now: large queue but all machines are idle.

**Comment by edolstra** [comment]
Systemd 227 is now in staging. This will probably break some packages that need libgudev, but the fix is trivial (add `libgudev` to `buildInputs`).

**Comment by copumpkin** [comment]
:beers: to all involved, thanks!

**Comment by thoughtpolice** [comment]
Boom:

```
a@otacon> systemctl --version
systemd 227
+PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN

a@otacon> cat /etc/issue

<<< Welcome to NixOS 16.03.git.882344e (\m) - \l >>>

a@otacon>
```

Many thanks to @edolstra - closing this now...
