### ISSUE TITLE
support phases with buildCommand?

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#66826]
Using `buildCommand` means no phases are run, because it returns immediately: https://github.com/NixOS/nixpkgs/blob/f2c619fae8e2b82cde03c91bad45cf7f30b4841a/pkgs/stdenv/generic/setup.sh#L1270-L1283

This looks deliberate, but why? / would it be unreasonable to support either mode of usage?

My use case would be using `.overrideAttrs` with a phase, on the result of a trivial-builders.nix builder that's based on runCommand. 

(I'm using `writeShellScriptBin` and want to use `wrapGAppsHook`)

**Comment by FRidh** [comment]
Where would you draw the line for `buildCommand`? What parts of `mkDerivation` would you include and what not.

**Comment by deliciouslytyped** [comment]
I don't follow. This may be incoherent (?) but I just figured making the return optional.

**Comment by deliciouslytyped** [comment]
I did peek around for documentation, maybe the intended use mode of `buildCommand` is just unclear to me.

**Comment by deliciouslytyped** [comment]
I think this is pretty ugly, any suggestions?:
```nix
rec {
    runner' = writeShellScriptBin "wikidpad" ''
      cd ${src}
      ${python}/bin/python ${src}/WikidPad.py
      '';

    runner = stdenv.mkDerivation {
      name = "wikidpad";
      unpackPhase = ":";
      installPhase = ''
        mkdir -p "$out"
        cp -r "${runner}/bin" "$out"
        '';
      nativeBuildInputs = [ wrapGAppsHook ];
      buildInputs = [ wxGTK.gtk ];      
      };
}
```

Hm. Ok, so the phase overrides would still be necessary.
If phases worked one could do:
```nix
{
    runner = writeShellScriptBin "wikidpad" ''
      cd ${src}
      ${python}/bin/python ${src}/WikidPad.py
      ''.overrideAttrs (a: {
        unpackPhase = ":";
        installPhase = ''
          mkdir -p "$out"
          cp -r "${runner}/bin" "$out"
          '';
        nativeBuildInputs = [ wrapGAppsHook ];
        buildInputs = [ wxGTK.gtk ];      
        });
}
```

An alternative _for this specific case_ would be if trivial builders took a `...` argument which they passed on to `runCommand`. Looks like I forgot to open an issue for that.

**Comment by alexarice** [comment]
It seems that there would be not many use cases with this and perhaps changing/ adding a new trivial builder would be a better idea than causing a mass rebuild.

Further my understanding was that `buildCommand` was to be used to override the entire build process, hence why it ignores phases

**Comment by lheckemann** [comment]
Maybe you want to set `buildPhase` instead?

**Comment by FRidh** [comment]
`buildCommand` was originally added for functions such as `runCommand`. If you need more than what that offers, just use `stdenv.mkDerivation`. I don't see this change happening so closing.

**Comment by aidanhs** [comment]
Just to want to add some keywords to this issue for future searchers since I spent two days on this.

buildCommand disabling phases neuters overrideAttrs in a number of ways, including disabling fixupPhase entirely. Because fixupPhase installs setup hooks, you cannot use overrideAttrs to add a setup hook on another package that makes use of buildCommand. This behavior also applies packages that make use of trivial builders like `symlinkJoin`, which nixpkgs-mozilla uses for Rust.

In my case, this means I cannot work around https://github.com/NixOS/nixpkgs/issues/217835 with overrideAttrs of setupHook to set `SYSROOT` explicitly. Instead I have to overrideAttrs on `buildCommand` to manually install the setup hook.

Bits of documentation that could have hypothetically helped on https://nixos.org/manual/nixpkgs/stable/
 - buildCommand as an argument to mkDerivation is not mentioned at all (basically https://github.com/NixOS/nixpkgs/issues/18678), and therefore doesn't mention it disables phases
 - the assorted trivial builders that use `buildCommand` also do not mention they will therefore ignore phases
 - the phases section does not mention that `buildCommand` will disable it all
 - given that the fixup phase is called out as having nix-specific post-processing, I would have also expected a note in that section that `buildCommand` and friends will disable it (since people will have to do post-processing themselves)
 - the top level of the fixup phase section doesn't mention it does anything with setup hooks
 - it's extremely difficult on that page to get a grasp of the title hierarchy when searching through it - a sidebar would have helped me see that `setupHook` is under `fixupPhase` and make the previous point less important
