### ISSUE TITLE
atom: build from source

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#6689]
Why is atom (the editor) installed from .deb instead of being built form source?
Are there any known technical difficulties?

**Comment by codyopel** [comment]
I don't think there are any reasons for it to use the deb.   I have come across several packages lately that do this and need to be rewritten.

@offlinehacker

**Comment by domenkozar** [comment]
it's mostly because it's easier, but that shouldn't be a good reason.

**Comment by rakshazi** [comment]
any update on this?

**Comment by offlinehacker** [comment]
Because, building atom deterministically from source on nix is hard(or at
least it used to be) and not worth it.

If nix losens constraints to not have fully deterministic inputs for cases
where this is insane from standpoint of the package, would help a lot, but
until then I rather have simple packages created from binary releases, as
completly magical mess that somehow tries to handle all the involved
non-determinism and then breaks with each release...

V sre., 9. mar. 2016 9:59 dop. je oseba Nikita Chernyi <
notifications@github.com> napisala:

**Comment by jgillich** [comment]
I could go on for hours about how bad Bracket's build process is for packaging, sounds like it's the same for Atom. :disappointed:
