### ISSUE TITLE
/dev/ptp0 does not work in NixOS

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#67595]
**Describe the bug**
I was trying to setup time synchronisation of KVM guest and host following the nixos/tests/cocroachdb example:
https://github.com/NixOS/nixpkgs/blob/4226ddc0340cd492ee46f840c21b407bc229cadb/nixos/tests/cockroachdb.nix#L60-L73

`ptp_kvm` works with Debian guests but does not work with NixOS

**To Reproduce**
```
# modprobe ptp_kvm
modprobe: ERROR: could not insert 'ptp_kvm': No such device
```

**Expected behavior**
`ptp_kvm` loaded without error

**Additional context**
I compared `/proc/config.gz`, the only relevant line which was present in Debian and absent in NixOS is:
`CONFIG_PTP_1588_CLOCK_KVM=m`
Adding it to NixOS kernel did not help.
Both kernels are `4.19.x`

Probably the problem is with `udev` or `systemd` settings

cc @jbboehr and @thoughtpolice

**Comment by volth** [comment]
```
services.udev.extraRules = ''
  SUBSYSTEM=="ptp", ATTR{clock_name}=="KVM virtual PTP", SYMLINK += "ptp_kvm"
'';
```
does not help either (this line is present in Debian's `/usr/lib/udev/rules.d/50-udev-default.rules`)

**Comment by markuskowa** [comment]
I can manually load the `ptp_kvm` module in an AWS instance that runs on NixOS 19.03 (no special config required).

**Comment by volth** [comment]
> I can manually load the `ptp_kvm` module in an AWS instance that runs on NixOS 19.03 (no special config required).

Hm, Interesting.
I was trying on local libvirt and on DigitalOcean and got the error in both cases.
The information that a stock NixOS DVD might work is userul, it should make easier comparing it to what I run

**Comment by volth** [comment]
Reproducible with 19.03 LiveCD:
```
wget https://releases.nixos.org/nixos/19.03/nixos-19.03.173387.3c83ad6ac13/nixos-minimal-19.03.173387.3c83ad6ac13-x86_64-linux.iso
qemu-kvm -m 2000 -cdrom nixos-minimal-19.03.173387.3c83ad6ac13-x86_64-linux.iso
```
then `modprobe ptp_kvm` in the guest consone

**Comment by volth** [comment]
AWS does not work too (I tried `ami-0022b8ea9efde5de4` from https://nixos.org/nixos/download.html):

![](https://i.imgur.com/IA2IOjB.png)

@markuskowa could you tell which minor/git version of 19.03 did work on AWS?

**Comment by markuskowa** [comment]
That is my nix-info version string: `Linux 4.19.63, NixOS, 19.03.173222.fb354a0ac87`.
I can't remember which ami id it was exactly. I had to copy a snapshot from Ireland to EU north in Stockholm (which does not have an ami) and I did 'nixos-rebuild --upgrade' more than once since then.

**Comment by volth** [comment]
`nixos-minimal-19.03.173222.fb354a0ac87-x86_64-linux.iso` does not work too :(

**Comment by markuskowa** [comment]
I am not sure how exactly that driver works exactly but it sounds like that the host needs to provide some part of it. Maybe those data points help: the instance I am running is a `t3.micro` in `eu-north-1c`. Amazon does provide hardware virtual machine (HVM) and paravirtual (PV) instances. Could that be a source of trouble?

**Comment by volth** [comment]
It requires kernel **on host machine** to be `4.14` or newer (on my machines it is older, on DigitalOcean it is random)

**Comment by thoughtpolice** [comment]
To be clear, the `ptp_kvm` driver requires several things:

1) It must be loaded into a GUEST MACHINE on some virtualized infrastructure

2) It requires a host machine running that VM to have a proper TSC clock source. (This means it must be x86_64 linux, basically). As noted, not all AWS machine types support this, because some are bare metal and others are virtualized.

3) It probably requires specific kernel version/configuration to work (as noted)

This test was never enabled on upstream Hydra evaluations precisely because of this platform dependence -- for example, it would not work on aarch64 machines, and it would not work on Hydra builders that are running on EC2 virtual instances.

---

BTW (and this is in the comments, but just for bystanders/other readers) The motivation for doing things this way is *not* because the guest VMs, for this test, need to be synchronized to the host. It is because they need to be synchronized *with each other*, which is subtly different. The test doesn't care if the guest clock sources are off by 5 minutes from the real host clock, but it *does* care if the guests themselves are off by ~500ms from *each other* at any time.

Unfortunately, I know of no other way to easily and reliably synchronize a host clock and a guest clock when the guest does not have any networking support; this PTP source was the best available.

In the future, once I get back around to finishing #51306, this driver will not be needed for this test; instead we will spin up a *fourth* virtual machine for this test, which is only designed to provide a fake NTP source, which the other three guests synchronize to (since, as noted, being synchronized with the host machine is not important.)
