### ISSUE TITLE
[feature request] render additional grub loopback.cfg on live ISO

### ISSUE THREAD

**Issue by pille** [NixOS/nixpkgs#67627]
## Issue description
loopback.cfg is a "standard", that suggests ISO media having a special file embedded, that is a snippet of a grub config, which can be included by the grub.cfg running on the host.

that way you can put ISO images on your boot partition and boot them without having to figure out the details like where the kernel  or initramfs is inside the ISO.

it's documented here: http://www.supergrubdisk.org/wiki/Loopback.cfg

## Motivation ##
* easy mode to try out NixOS without handling external media (DVD/USB)
* my usecase is handing my crypted device to other people (unencrypted boot part with ISOs)
  * they can't access my data
  * they are not persistent on my system
* just add a file: (nearly) no chances to break something
* easy to implement: you generate your bootloader config already. just add another one.

for reference, here's my post from the mailing-list, a couple of years ago: https://nixos.org/nix-dev/2015-December/018939.html
hoping @Lassulus will pick it up, as we talked yesterday.

**Comment by Lassulus** [comment]
A little update: 
I now have a sufficient test environment
booting the default grub config from the iso with just loading /EFI/boot/grub.cfg brings me successfully to stage-1 of the init process. then it fails because it can't find the root device.
Next step is to implement something like the `findiso=/path/to/iso` parameter in the stage-1 of nixos

**Comment by Lassulus** [comment]
so, this is now on master, we just have to wait for 20.03 to have it on the official iso
