### ISSUE TITLE
increase the size of efi-image where needed

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nixpkgs#6796]
As mentioned by @vcunat [here](https://github.com/NixOS/nixpkgs/pull/4678/files#r26398199) it would be nice to change the size of efi-image based on its contents. At the moment ISO builds may fail when a custom configuration results in > 15M of efi files.

https://github.com/bobvanderlinden/nixpkgs/blob/dbf74363f55682d5bc23e34a0c97a517c0c4ae5c/nixos/modules/installer/cd-dvd/iso-image.nix#L74 needs to change. Probably best to do this after #4678 is merged.

**Comment by kylescottmcgill** [comment]
Yeah to be honest, i dont know if this would actually be needed (using a 512MB parition for EFI). Its just on some sticks (albeit older sticks) we may run into compatibility issues with aligned sectors. However, I do personally like the auto size detection, makes things compact. Maybe its better leaving it at, "if this happens in the future, then increase it, otherwise its not needed." On sticks produced these days the limit has been dropped to 32MB worth of aligned sectors (more advance or something). This is according to the Archlinux Wiki on UEFI.

**Comment by vcunat** [comment]
Commit I was testing: vcunat@72cd14b. Do you know if there are some size/alignment restrictions? I just rounded to megabytes.

**Comment by bobvanderlinden** [comment]
I'm not 100% sure on this, but it fits the cluster sizes that are used for FAT, so I guess it's alright.

**Comment by domenkozar** [comment]
Current master branch tests fail because of the limit: http://hydra.nixos.org/build/20874309/nixlog/1/raw

**Comment by vcunat** [comment]
The commit e19ac248ae59 should be cherry-pickable (probably with a simple conflict). I suppose it's safe, if someone tests a system booting from it (VM-only tests might be good enough).

**Comment by bobvanderlinden** [comment]
The fix was already applied. See https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/iso-image.nix#L97-L98
Closing this issue.
