### ISSUE TITLE
nix-env -u fails due to haskell-mtl

### ISSUE THREAD

**Issue by jmcloughlin** [NixOS/nixpkgs#6840]
I have a handful of haskell packages installed (in my user environment, not in an isolated sandbox).

I'm on the binary channel http://nixos.org/channels/nixpkgs-unstable, and when I update (via nix-env -u), I get the following error related to haskell-mtl (ignore most of the derivations, they are related to julia).  I get the same error if I instead use source builds via git checkout.  

I notice there are three .nix expressions in the repository: 2.1.3.1 (my successfully installed version), 2.2.0.1 (which doesn't show up in a nix-env package search), and 2.2.2.1 (which my system is trying to upgrade to).

If this all works in isolated sandboxes, I will switch to those, but thought I should flag it.

upgrading ‘haskell-mtl-ghc7.8.4-2.1.3.1-shared’ to ‘haskell-mtl-ghc7.8.4-2.2.1-shared’
upgrading ‘julia-0.3.5’ to ‘julia-0.3.6’
these derivations will be built:
  /nix/store/g91psawjphk9w2yqjhwl26zymr83xkq9-openblas-v0.2.13.tar.gz.drv
  /nix/store/kfgv52ka6cxr602j873qha29fscgc36i-haskell-mtl-ghc7.8.4-2.2.1-shared.drv
  /nix/store/nsdlw2fn1w9ki90yb8zl64gksb5h7c31-patchelf-0.8.tar.bz2.drv
  /nix/store/w74hngbqm928hcanzg8fjq61b5q30x5c-suitesparse-4.2.1.drv
  /nix/store/xr0d1cqlbn8w6pcqi93jhqk3na58b6aj-pcre-8.36.tar.bz2.drv
  /nix/store/zv8kfhnqazwla3nwymb233n7y2anqr3h-utf8proc-v1.1.6.tar.gz.drv
  /nix/store/l811wvxyfvyyfab5ghddy1rk2jc5xyr0-julia-0.3.6.drv
building path(s) ‘/nix/store/w76zzv9v2pcarkc9n9vlaqqzl0r4ld49-haskell-mtl-ghc7.8.4-2.2.1-shared’
unpacking sources
unpacking source archive /nix/store/i9nw1ykj1l22fv0dcf7539dsz9a289rd-mtl-2.2.1.tar.gz
source root is mtl-2.2.1
patching sources
configuring
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-haskell-mtl-ghc7.8.4-2.2.1-shared.drv-0/Main.o )
Linking Setup ...
configure flags: --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests  --with-gcc=gcc --ghc-option=-optl=-Wl,-rpath=/nix/store/w76zzv9v2pcarkc9n9vlaqqzl0r4ld49-haskell-mtl-ghc7.8.4-2.2.1-shared/lib/ghc-7.8.4/mtl-2.2.1
Configuring mtl-2.2.1...
Setup: At least the following dependencies are missing:
transformers ==0.4.*
builder for ‘/nix/store/kfgv52ka6cxr602j873qha29fscgc36i-haskell-mtl-ghc7.8.4-2.2.1-shared.drv’ failed with exit code 1
error: build of ‘/nix/store/kfgv52ka6cxr602j873qha29fscgc36i-haskell-mtl-ghc7.8.4-2.2.1-shared.drv’ failed

**Comment by vcunat** [comment]
The failure is in the building stage, before considering any environment issues (thus independent of that). I confirm the problem persists even on recent master (channel is a few weeks behind, currently). /cc @peti.

**Comment by peti** [comment]
It's not possible to install mtl 2.2.x with GHC 7http://stackoverflow.com/questions/29033580/how-do-i-use-the-new-haskell-ng-infrastructure-on-nixos.8.4. because the library depends on the core library transformers 0.4.x, which GHC 7.8.x does not have. There is not much we can do about that; I'm afraid.

Generally speaking, it's almost certainly a bad idea to install Haskell packages directly into your user profile. You should consider migrating to the environment ghttp://stackoverflow.com/questions/29033580/how-do-i-use-the-new-haskell-ng-infrastructure-on-nixos generated by `haskellngPackages.ghcWithPackages` instead. http://stackoverflow.com/questions/29033580/how-do-i-use-the-new-haskell-ng-infrastructure-on-nixos provides some helpful information to get you started. The posting http://lists.science.uu.nl/pipermail/nix-dev/2015-January/015591.html has some additional background information.

I hope this helps.

**Comment by peti** [comment]
It's not possible to install mtl 2.2.x with GHC 7.8.4. because the library depends on the core library transformers 0.4.x, which GHC 7.8.x does not have. There is not much we can do about that; I'm afraid.

Generally speaking, it's almost certainly a bad idea to install Haskell packages directly into your user profile. You should consider migrating to the environment generated by `haskellngPackages.ghcWithPackages` instead. http://stackoverflow.com/questions/29033580/how-do-i-use-the-new-haskell-ng-infrastructure-on-nixos provides some helpful information to get you started. The posting http://lists.science.uu.nl/pipermail/nix-dev/2015-January/015591.html has some additional background information.

I hope this helps.

**Comment by vcunat** [comment]
Maybe we should have a way to make such combinations fail during evaluation.

**Comment by peti** [comment]
It's hard to implement that properly, because mtl-2.2.x is broken when compiled with GHC 7.8.x, but paradoxically it works fine with older compilers, because transformers was not a core library back then. It also works fine with GHC 7.10.x, because that ships transformers 0.4.x. To express those pre-conditions, we'd have to figure out exactly under exactly which circumstances a package can be built and add an appropriate meta.broken attribute. Now, I could do this manually for mtl, I suppose, but there's dozens of packages that run into these kinds of problems. There's no way to maintain all that information manually.

Anyway, I can commit a fix that solves this particular issue with `mtl` to help out @jmcloughlin. My recommendation is, though. to migrate to `ghcWithPackges` instead of relying on `ghc-wrapper`.

**Comment by vcunat** [comment]
Hmm, it seems possible to infer the conflict from the *.cabal file, but it's probably hard to get all the information.

**Comment by peti** [comment]
We do that in Haskell NG. :smiley:

**Comment by vcunat** [comment]
Ah, I see :-) I didn't follow the NG progress.

**Comment by jmcloughlin** [comment]
Thanks for the reply @peti.  No need to commit a fix on my behalf if I should be setting up my Haskell env a different way (ghc wrapper was the easiest, path of least resistance).  I'll try to get up to speed on Haskell NG ASAP.  thanks.
