### ISSUE TITLE
Package request: LAPACKE

### ISSUE THREAD

**Issue by rht** [NixOS/nixpkgs#68811]
It is strange that this is not packaged yet (!). There is a haskell version called jalla which has a description of

```
       description = "Higher level functions for linear algebra. Wraps BLAS and LAPACKE.";
```

but the LAPACKE itself doesn't have a package, while it is present in Ubuntu as `liblapacke-dev`.

**Comment by veprbl** [comment]
We already have the LAPACK
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/science/math/liblapack/default.nix
The "lapacke" must be some sort of quirk of debian packaging and not a different software.
https://packages.debian.org/sid/liblapacke-dev

**Comment by markuskowa** [comment]
LAPACKE provides the C library version of LAPACK. I would recommend taking look at `openblas` first, which comes with a C interface per default. Morever, `openblas` is highly optimized  for performance the preferred choice the days.
However, if you want LAPACKE specifically you can just use a override of lapack which enables LAPACKE:
```
liblapacke = liblapack.overrrideAttrs(x: { cmakeFlags = x.cmakeFlags ++ [ "-DLAPACKE=on" ]; })
```


I am not sure why debian creates a seperate package for it since it looks like lapacke just creates an additional library and some C header files. We could  just add the cmake flag to liblapack in nixpkgs.

**Comment by rht** [comment]
Thanks for solving this @markuskowa !
