### ISSUE TITLE
haskell.packages.ghc844.Diff: build failed

### ISSUE THREAD

**Issue by wizzup** [NixOS/nixpkgs#70961]
**Describe the bug**
```
$ nix-build '<nixpkgs>' -A haskell.packages.ghc844.Diff -I nixpkgs=https://github.com/NixOS/nixpkgs/tarball/master
these derivations will be built:
  /nix/store/kc94k53cnhd0mrzj5r6616br68caff1i-Diff-0.3.4.drv

.......

test/Test.hs:137:16: error:
    • Couldn't match expected type ‘Double’ with actual type ‘Bool’
    • In the first argument of ‘cover’, namely ‘(haskDiff == utilDiff)’
      In the expression: cover (haskDiff == utilDiff) 90 "exact match"
      In the expression:
        cover (haskDiff == utilDiff) 90 "exact match"
          $ classify
              (haskDiff == utilDiff)
              "exact match"
              (div ((length haskDiff) * 100) (length utilDiff) < 110)
    |
137 |     in  cover (haskDiff == utilDiff) 90 "exact match" $
    |                ^^^^^^^^^^^^^^^^^^^^

builder for '/nix/store/kc94k53cnhd0mrzj5r6616br68caff1i-Diff-0.3.4.drv' failed with exit code 1
error: build of '/nix/store/kc94k53cnhd0mrzj5r6616br68caff1i-Diff-0.3.4.drv' failed

```

My current workaround is `overrideCabal` with `doCheck = false` but this mean no binary cached, I have to rebuild lot's of haskell package dependencies (`hlint`, for example, take a very long time to build)

Please run `nix run nixpkgs.nix-info -c nix-info -m` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.78, NixOS, 20.03pre-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by cdepillabout** [comment]
@wizzup Is there a reason you're trying to get `hlint` from ghc844 (instead of ghc865)?

I think the correct fix here would be to disable the tests for just `Diff` in `configuration-ghc-8.4.x.nix`.

**Comment by wizzup** [comment]
> Is there a reason you're trying to get `hlint` from ghc844 (instead of ghc865)?

Maybe not , I just don't really sure about compatibly of using tools from different version (`hie` and `ghcide`, for example provided version specific tool instead of generic one; so I assume version matched would be better)

Alternate to disabling the check, I've found related [issue]](https://github.com/commercialhaskell/stackage/issues/4289) that mention a patch.

**Comment by cdepillabout** [comment]
@wizzup 

As far as I know, there are some Haskell tools that need to be compiled with the same version of GHC you are using to compile your actual Haskell project.  There is another type of Haskell tools that don't need to be compiled with the same version of GHC you are using to compile your actual Haskell project.  Let me describe these two different sets of tools.

### Tools that _do_ need to be compiled with the same version of GHC you are using to compile your Haskell project

These are tools that use the GHC API to load, compile, or type-check your actual Haskell code.

Examples:

- `hie`
- `ghcide`
- `ghcmod`
- `intero`

Since these types of tools directly use the GHC API to compile your code, they _must_ be using the same GHC version your code is using.  You often get these types of tools with `nix-shell` using a `shell.nix` specific to your project.

### Tools that _do not_ need to be compiled with the same version of GHC you are using to compile your Haskell project

These types of tools don't actually load, compile, or type check your code with the GHC API, so they don't need to be built with the same version of GHC you are using for your Haskell project.

Examples:

- `hlint`
- `weeder`
- `brittany`
- `hindent`

Because these tools don't need to be built with a specific version of GHC, they can normally be installed globally.  It is usually fine to just get them from `haskellPackages`, and install them with `nix-env` or `/etc/nix/configuration.nix` in `environment.systemPackages`.

--------------------------------------------------------------------------------------------------

So to answer your question, it should be fine to get `hlint` from `haskellPackages`.

However, if there are other packages that depend on `Diff` you need specifically from `ghc844`, then I think the easiest fix would be to just disable the tests for `Diff` in `configuration-ghc-8.4.x.nix`.

**Comment by cdepillabout** [comment]
We've moved past ghc844 (we're now currently on ghc883), so I don't think anyone is checking to make sure the packages from ghc844 still build.

Most people get these types of tools from the normal `haskellPackages`, so I will go ahead and close this.
