### ISSUE TITLE
nixos testing for NetworkManager

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#71151]
**Describe the bug**
NetworkManager is a particularly important component and we don't have any tests for it that could block a channel advance.  

In particular, a change can happen on nixos-unstable leaving users without functioning networking, and while rollbacks are possible it isn't an excuse to allow that to reach production systems. NixOS doesn't produce [a failsafe generation](https://github.com/cleverca22/nixos-configs/blob/5a52e0f94081361fa9d2cbfcd4f7722d442486c7/rescue_boot.nix) either.

Manual testing is also cumbersome if we want to make a new stable release.

Upstream NetworkManager does have some integration testing
* https://github.com/NetworkManager/NetworkManager-ci

but obviously not useful to us.

I think to start, if we at least had a test that verifies the services start without issues would be great.

**Comment by teto** [comment]
Agreed. While developing tests for the multipath TCP module https://github.com/NixOS/nixpkgs/pull/59342 I was surprised to see no networkmanager module.
I had some difficulties with the nixos test infrastructure at first because the test infra will by default install a slirp interface (config.virtualisation.qemu.networkingOptions) and it messed up the interface naming. Like I would clear config.virtualisation.qemu.networkingOptions but interfaces would still be named starting from `eth1` instead of `eth0`.

**Comment by jtojnar** [comment]
Bleh.

**Comment by lf-** [comment]
consequences of our inactions https://github.com/NixOS/nixpkgs/issues/283717
