### ISSUE TITLE
Make virtualenv use pythonFull, not python

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#7134]
See https://github.com/AndersonTorres/nixpkgs/commit/d6feeeaab18cdc9d9942aec8c890f9c8799fa382

**Comment by Profpatsch** [comment]
(triage) @domenkozar is that solved yet?

**Comment by domenkozar** [comment]
Nope.

**Comment by FRidh** [comment]
I never really use `virtualenv` so I got curious what the issues really are about.
```
nix-shell -p python35Packages.virtuallenv python35Packages.toolz

[nix-shell:] virtualenv testenv
Using base prefix '/nix/store/ln2cn6g6rf116vaq1fgngaqzpzfq495x-python3-3.5.1'
New python executable in testenv/bin/python3.5m
Also creating executable in testenv/bin/python
Installing setuptools, pip, wheel...done.

[nix-shell:] source test/bin/activate

(testenv)[nix-shell:] python3 -c "import toolz; print(toolz.__version__)"
0.7.4
```
Clearly, the `testenv` is not entirely separated from the `nix-shell` and it's easy to understand why: we've added the package to `$PYTHONPATH`.

The question is now whether this is an issue. To me it seems more like a feature; `nix-shell` can already be used to obtain isolation. This gives us instead the possibility to add already packaged packages to an environment, although, of course, this won't work with a `requirements.txt` or so.

To get back to the issue here. We can use `pythonFull`, e.g. by just adding all the modules as `propagatedBuildInputs` to `pythonPackages.virtualenv`. It seems like an easy fix to me. What do you say?

**Comment by domenkozar** [comment]
The issue is mostly about UX. `python` doesn't have readline or sqlite3, which is very annoying in virtualenv. I've been thinking we'd just include both by default since they're light and convenient.

**Comment by Profpatsch** [comment]
I’d love that!

**Comment by FRidh** [comment]
Since #19309 we don't have separate modules anymore except tkinter, which is like a 'normal' Python package: pythonPackages.tkinter.

I will soon write some docs on how `virtualenv` can be used with Nix and what to be wary of.
