### ISSUE TITLE
sage: use python3

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#71742]
python2Packages.twisted is broken, and there's likely no remedy. Disabling it here #71741

Not to mention that python2 will be EOL in ~9 weeks.

**Comment by FRidh** [comment]
Sage is still being ported to Python 3. While parts of it work, not everything functions. If at this point Twisted is what is breaking Sage, then I think we can try and enable it again for Python 2.

cc @timokau

**Comment by FRidh** [comment]
Regarding python 2 twisted, see https://github.com/NixOS/nixpkgs/pull/71101#issuecomment-545095976.

**Comment by timokau** [comment]
Right, the upstream effort has been going on for some time (since sage is big and has many python dependencies). At this point sage is mostly usable with py3, but there are a handful of remaining issues and the officially supported version is still py2. There is good progress, the switch to py3  is likely to happen in one of the next two releases. I don't think we should switch before that.

If you're interested, here's the upstream metaticket: https://trac.sagemath.org/ticket/15530

**Comment by jonringer** [comment]
my issue was more with twisted not being able to be built, so it would always cause a rebuild :(, but it's fixed now, so :)

**Comment by Synthetica9** [comment]
Sage 9.0 is on python3 by default! https://wiki.sagemath.org/Python3-Switch

Sadly, this update has not been included in nixpkgs yet. I will give this update a shot, but it seems to be a pretty big one, so I'm not sure I'll succeed.

**Comment by timokau** [comment]
Yes, it's a big one. This is already work-in-progress in https://github.com/NixOS/nixpkgs/pull/70474. Help is welcome of course, especially if you want to look into the sphinx issue. I'm thinking about just disabling the docbuild for now, but even if I do that there still might be other problems (see the mailing list thread linked in #70474) and it would be nice to keep the docs.
