### ISSUE TITLE
Failing VM Installer Tests

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#7252]
When building the i686 iso, the nixos-manual that is generated by the machines is different than the nixos-manual that is generated during the install process even though the input nixpkgs is the same. This causes the installer tests to fail as the iso doesn't have the needed dependencies to rebuild the manuals (in this case libxslt).

This is problematic because the reference to the default value for nixpkgs.system defaults to the system which is building the manual. In our case, an x86_64-linux machine in the hydra pool builds the manual which goes into the iso, and then during the install process the i686-machine builds the manual causing the default value to change. This was introduced by #6794 which began using builtins.currentSystem for the default value. Reverting this change fixes the issue. Ideally the manual should be the same no matter what the host architecture is.

@nbp @domenkozar @edolstra

**Comment by wkennington** [comment]
Reverting completely fixes the issue but obviously this is undesirable.

**Comment by nbp** [comment]
ok, so the problem is that we have a default value which is different in function of the architecture that we are targeting.

So, I guess the simple solution is to move the `default = builtins.currentSystem;` to the config part as a `mkDefault builtins.currentSystem`.  Still note that both might still differ if we do not remove the hashes of packages when generating the documentation.

**Comment by edolstra** [comment]
Can't we remove the default altogether? I don't think it's needed, since `nixos/lib/eval-config.nix` always passes a system value.

**Comment by jagajaga** [comment]
Maybe my issue is related? https://github.com/NixOS/nixpkgs/issues/7059

**Comment by domenkozar** [comment]
Just a headsup: this is blocking channel update now.
