### ISSUE TITLE
Travis-CI generates false-positives for Haskell packages

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7304]
The patch from https://github.com/NixOS/nixpkgs/pull/7288 was reported as testing [_successful_](https://travis-ci.org/NixOS/nixpkgs/builds/57797085), but in fact no test build was ever run -- and if it had been, it would have failed.

**Comment by peti** [comment]
Ping @madjar.

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by tadfisher** [comment]
(triage) Recommend closing; this doesn't seem Haskell-related.

**Comment by peti** [comment]
I don't believe that this issue has been fixed. Or has it?

**Comment by Profpatsch** [comment]
Maybe not, no. I’m still hoping for hydra Github integration. ;)

**Comment by matthewbauer** [comment]
So here's some explanation for what's going on:

nox-review runs ```nix-env -qa --out-path``` to compare the PR git tree to the base version of nixpkgs. This list will only include the output of the top level pkgs.* attributes unless something like recurseIntoAttrs is used. That means that nox-review will only register a change if it is listed ```nix-env -qa``` or it is a dependency of something listed in ```nix-env -qa```. For example, the python packages seem to not have this issue because of the use of recurseIntoAttrs.

**Comment by matthewbauer** [comment]
@peti Would it be possible to use recurseIntoAttrs for haskell or is the package set too large?

**Comment by Profpatsch** [comment]
Packages for the newest compiler are always built by Hydra.

**Comment by peti** [comment]
Recursing into the `haskellPackages` is undesirable, IMHO, and I'd rather not do that. We could enable a `recurseIntoAttrs` in the context of `nox` though, i.e. by letting the tool evaluate Nixpkgs with an appropriate override configured.

**Comment by c0bw3b** [comment]
Closing this issue after #31605
