### ISSUE TITLE
Geary got rebuilt after each system upgrade

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#73708]
Why geary builds on my machine and there is no binary cache on Hydra on nixos-unstable?

**Comment by gnidorah** [comment]
cc @jtojnar

**Comment by worldofpeace** [comment]
@gnidorah Sometimes the tests timeout. I haven't checked yet if a patch we've fetched helped this much, but I assumed it did since it actually succeeded on ofborg. Do you have the revisions you upgraded from?

For example:
```
Geary was built from source from:
`nixos-version` -> `nixos-version`

Geary was cached:
`nixos-version` `nixos-version`
```

I'm also assuming these were all revs that are tested on the channel. Meaning you weren't building your system from git.

**Comment by worldofpeace** [comment]
This graph shows there hasn't been issues with geary building
* https://hydra.nixos.org/job/nixpkgs/trunk/gnome3.geary.x86_64-linux/all

are you x86_64-linux?

**Comment by gnidorah** [comment]
@worldofpeace I'm on x86_64-linux. I will track it and write down the versions on next nixos-unstable channel update

**Comment by gnidorah** [comment]
Can't reproduce it anymore
