### ISSUE TITLE
check-meta.nix doesn't work with insecure packages

### ISSUE THREAD

**Issue by ChengCat** [NixOS/nixpkgs#73737]
**Describe the bug**
`check-meta.nix` would raise an unrelated error when trying to use an insecure package:
```
error: attribute 'name' missing, at /nix/store/***/nixos/pkgs/stdenv/generic/check-meta.nix:70:52
```

**To Reproduce**
1. put any package marked with `knownVulnerabilities` in system.packages (e.g. evilvte); 
2. run `nixos-rebuild switch`

**Expected behavior**
An error stating the package is insecure, or allows the package to be used if it is in `nixpkgs.config.permittedInsecurePackages`.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.59, NixOS, 19.03.173147.77295b0bd26 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09.1282.e6d584f6dd2"`
 - channels(cheng): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by manishjhawar** [comment]
I stumbled upon this too while upgrading from 19.03 today. For me it was due to the `polipo` package.

Diabling the `nixpkgs.config.permittedInsecurePackages` resolved the issue for now.

#### Metadata

* system: `x86_64-linux`
* host os: `Linux 5.2.1, NixOS, 19.03.173624.b6cfdceb7f9`
* multi-user?: `yes`
* sandbox: `yes`
* version: `nix (Nix) 2.2.2`
* channels(root): `nixos-19.09.1320.4ad6f1404a8`
* channels(cheng): `""`
* nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by risicle** [comment]
Packages used to have to specify a `name = ` attribute to `stdenv.mkDerivation`, more recently `mkDerivation` seems to have developed the ability to assemble one from the `pname` and `version` attributes, so many packages now don't specify `name` directly.

It _appears_ that `allowInsecureDefaultPredicate` in `check-meta.nix` hasn't yet grown the ability to handle these packages and instead operates on a copy of this attr from before its `name` has been generated.

**Comment by tilpner** [comment]
@dtzWill Should this be closed? Your commit message seems like it, but doesn't use one of Githubs key words.

**Comment by ChengCat** [comment]
I can confirm this issue has been resolved
