### ISSUE TITLE
Backport hedgewars 1.0.0 to 19.09?

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#73829]
I was chatting with one of hedgewars developers and they said:

> I'm surprised that someone thought our beta/rc was a good idea for your stable branch though
> basically, it means your stable has no one to play with online, since they aren't on our latest release or current release
> (the betas have a different protocol revnum to avoid desyncs)

https://github.com/NixOS/nixpkgs/pull/71880 was merged shortly after cut off.

cc @rardiol @kragniz @fpletz

**Comment by kragniz** [comment]
+1, there's no point in having the beta version in a release

**Comment by fpletz** [comment]
Makes sense, thanks! Backported: 9ed32341c7b7a4671fc7d736ca3cd5bc54d3e297

**Comment by eoli3n** [comment]
The package is not working

http://ix.io/2dwd

**Comment by jtojnar** [comment]
@eoli3n Looks like the latest version does not have properly set up version bounds, see https://github.com/hedgewars/hw/commit/ab3c382e67addca38cd6b22df7507729ac098134. You will need to override `hedgewars`’s `network` dependency to `network_2_6_3_1` in `haskell-modules/configuration-common.nix` for now.

Also please open a next issue next time, unless the problem is directly caused by this.

**Comment by schmittlauch** [comment]
Just as an explanation: Packaging the beta was my fault. Before, hedgewars was completely broken because its haskell dependencies didn't build anymore, so my take was that a compiling beta is still better than a broken stable release.
Also, both their blog post and their forums said that the beta was already quite usable.

It's just that I didn't stay put on it to also package the 1.0.0 after release, so sorry about that.
