### ISSUE TITLE
ihaskell doesn't build on current nixpkgs

### ISSUE THREAD

**Issue by karshan** [NixOS/nixpkgs#7386]
(tested on this tree: fe6ec3d13a1554458e647511fb364b65572b363a)

It looks like the nix expressions for building ihaskell expect http://hackage.haskell.org/package/ihaskell-0.6.0.0.tar.gz to have profile.tar inside it, which it doesn't have.

```
tar: ihaskell-0.6.0.0/profile/profile.tar: Not found in archive
tar: Exiting with failure status due to previous errors
builder for ‘/nix/store/8mdciyfi03ds7vwghpawzmbg61rkaayr-ihaskell-with-packages.drv’ failed with exit code 2
```

Looking at the ihaskell github project, it looks like profile.tar is generated by Setup.hs, I haven't been able to follow how that should end up at http://hackage.haskell.org/package/ihaskell-0.6.0.0.tar.gz

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/pull/7314 There was a work on this pkg (maybe not this problem). It didn't help?

**Comment by edwtjo** [comment]
I'll look into it

**Comment by utdemir** [comment]
I managed to run IHaskell after this pull-request: #7380.

I use this `default.nix`:

```
let
  pkgs = import /home/utdemir/nixpkgs {};
in
  pkgs.stdenv.mkDerivation {
    name = "python-nix";
    version = "0.1.0.0";
    src = ./.;
    buildInputs = [ pkgs.python34Packages.ipython
                    (pkgs.haskellngPackages.ghcWithPackages (p: with p; [
                      ihaskell 
                    ]))
                  ];
  }
```

And run IHaskell notebook with:

    ihaskell install -l $(ghc --print-libdir) && ipython notebook --kernel=haskell

**Comment by edwtjo** [comment]
@karshan can you confirm that the profile error goes away using @utdemir PR? I'm afk.

**Comment by edwtjo** [comment]
Also; @utdemir you're using `ihaskell` which implies the old wrapper. Can you check that everything is fine using the  `IHaskell` wrapper.

**Comment by karshan** [comment]
I am able to produce a working ihaskell invironment using @utdemir's default.nix however the ipython upgrade PR doesn't fix the problem with the IHaskell wrapper

**Comment by edwtjo** [comment]
Great! AFAICT IHaskell v0.6 removed the profile from the source distribution in favor of jupyter(requires ipython3) and letting ihaskell(lower case) intialize the profile. So IHaskell both as a wrapper and binary is deprecated. I've updated the wrapper to just export a shell script `ihaskell-notebook` in dfc8e5ab05e5bb555000f9af0d58309671dccf4f

**Comment by karshan** [comment]
Yup. ihaskell-notebook works as expected.

**Comment by utdemir** [comment]
@edwtjo Thank you for your work on ihaskell on nixos!

I just have one question, when using the wrapper, how can I extend its ghcWithPackages so that I can play with some of the packages I like?

**Comment by edwtjo** [comment]
The general idea is that you use something like `ihaskell.packages = self : with self; [ wreq ];` in your `~/.nixpkgs/config.nix`, or `nixpkgs.config.ihaskell.packages = self: with self; [ wreq ];` in `configuration.nix` to override the global `ihaskell` systemPackage, in order to extend the ihaskell package set. Note that you cannot change from the default package set `haskellngPackages`, an alias to `haskell-ng.packages.ghc784`. If you want to use another package set like `haskell-ng.packages.ghc7101` you need to create your own environment wrapper, as you did, or run the nixos service. I was thinking about adding the possibility to override the package set for regular nixpkgs users but was distracted by something shiny. the nixos service configuration would look something like: `services.ihaskell = { enable = true; haskellPackages = pkgs.haskell-ng.ghc7101; extraPackages = self: with self; [ wreq ]}`

@karshan @utdemir thank you guys for the issue and PR! nixpkgs is like an unruly child which needs constant attention :)
