### ISSUE TITLE
grub2: Auto-detect other Linux and Windows installations?

### ISSUE THREAD

**Issue by MP2E** [NixOS/nixpkgs#7406]
This is a commonly asked for feature in #nixos and I'd be interested in seeing this as well! I'm thinking of something similar to os-prober on Arch Linux.

I'm just not sure where to begin implementing such a thing. Should I attempt to integrate os-prober? Is there some obvious solution I am missing? Any feedback would be appreciated!

**Comment by dezgeg** [comment]
The usual os-prober-based grub generator comes from grub itself. In fact, the current NixOS package includes it:

````
tmtynkky@nixvm:~]$ find /nix/store/ -iname 30_os-prober
/nix/store/b9d48fbq9g9nfk7cz0bddlff1icbh9al-grub-2.02-git-2ae9457/etc/grub.d/30_os-prober
````

I suppose getting the grub scripts to work on NixOS would be a logical first step. FWIW on Arch it looks like it can be simply executed:

````
0 thinkpad ~ » sudo /etc/grub.d/30_os-prober 2>/dev/null                                                                                                                                                                 09:13:42
menuentry 'Windows Vista (loader) (on /dev/sda1)' --class windows --class os $menuentry_id_option 'osprober-chain-16CA2533CA251093' {
	insmod part_msdos 
	insmod ntfs
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1  16CA2533CA251093
	else
	  search --no-floppy --fs-uuid --set=root 16CA2533CA251093
	fi
	chainloader +1
}
````

**Comment by vcunat** [comment]
The problem is that our grub config is (and should be) generated just from the expressions, i.e. independently of the machine it will be run on. We still might integrate such behavior e.g. into ``nixos-rebuild switch``; or if something like the above script can work generically, detecting *during boot-time*...

**Comment by lethalman** [comment]
@vcunat the grub configuration is actually generated not by nix expressions, because it has to iterate through all the system generations.

**Comment by vcunat** [comment]
Yes, I was inexact, edited above: the grub menu items are (and probably should be) machine-independent, but composing the list is done during ``nixos-rebuild switch``, which seems the easiest place to extend with detection and adding other systems. Perhaps configuration.nix could allow some further customization of this phase (we have ``boot.loader.grub.configurationLimit`` already), but detecting other systems and adding them somewhere *by default* seems fine to me.

**Comment by lethalman** [comment]
Sorry but the grub config is not independent of the machine. It depends on the generations of the system profile of that machine. There's really no problem in adding the os probing.

**Comment by vcunat** [comment]
Note: in the last comment I didn't (mean to) say there's a problem in it, on the contrary.

**Comment by vcunat** [comment]
The relevant file is https://github.com/NixOS/nixpkgs/tree/master/nixos/modules/system/boot/loader/grub/install-grub.pl.

**Comment by MP2E** [comment]
Thanks for the feedback! I'll take a look at this and report back with progress/questions.

**Comment by therealpxc** [comment]
Sorry if this comment is spammy, but I want to register my gratitude that you're working on this issue. I just installed NixOS on my laptop yesterday and so far I feel at once impressed and clumsy (kind of like learning Haskell, lol). One slightly irritating thing for me is that Ubuntu's os-probe function for some reason fails to detect NixOS, even though I have the partition mounted on Ubuntu under /media/NixOS. Since NixOS doesn't have a comparable feature yet, I've had to manually copy parts of my NixOS grub.cfg into my Ubuntu one, but that will get overwritten every time my Ubuntu instance gets a new kernel, and it's not automatically updated to respect NixOS' rollback features.

I'll probably eventually just write a script that dumps the $drive1, $drive2 assignments and menu entries from NixOS' grub.cfg and leaves out everything else, but an os-probe feature would be very, very welcome. I'm glad you're already working on it and feel lucky that you started looking at this just days before I started playing with the project. Thanks, folks! :-)

**Comment by wkennington** [comment]
It would be possible to break the grub.cfg into multiple files so that
other distros could at least pull in a list of menu entries. I'm sure
os-probing support would also make life easier.

**Comment by lethalman** [comment]
@therealpxc  You can add persistent ubuntu config: https://help.ubuntu.com/community/Grub2#Custom_Menu_Entries

And in particular it suffices to just "import" the nixos config, you don't have to manually copy-paste the contents: http://www.gnu.org/software/grub/manual/grub.html#configfile

**Comment by dezgeg** [comment]
It seems that simply having a `/etc/lsb-release` placed on the NixOS partition is needed for `grub-mkconfig` of other distros to recognize the partition as another Linux installation.

**Comment by therealpxc** [comment]
@dezgeg It just happens when grub configs are updated. There is no runtime autodetection for grub, afaik.

@lethalman I was worried that the redundant entries defining menu items, graphics settings, etc. would cause problems.

For now, I've just got each chainloading the other, so it doesn't matter which is installed to the MBR of /dev/sda. At first I thought I couldn't do this, because grub complained, I guess about using GPT partitions on a BIOS system. But all I needed to do was use grub-install --force. So far the 'less reliable' method grub cried about hasn't given me any trouble. What I've manually installed grub to /dev/sda2 on NixOS and to /dev/sda4 for Ubuntu, and configured each system to install to the MBR of /dev/sda. Since grub-install really only needs to be run once, and doesn't need to change when grub configs are changed, I now just let whichever system wants to overwrite the MBR whenever its grub config changes. This happens every time I run nixos-rebuild, afaict, which seems right, and whenever an Ubuntu kernel gets updated. This solution is a bit gross, but since I can still boot either system with the latest kernels available no matter what, I don't really care.

Here's the grub section of my configuration.nix file:
````nix
  boot.loader.grub = {
    enable = true;
    version = 2;
    copyKernels = true; # copy kernels to /boot so hopefully other linuxes
                        # can detect them
    # Define on which hard drive you want to install Grub.
      device = "/dev/sda";
      extraEntries = ''
        menuentry 'Ubuntu' {
          insmod ext2
          set root='(hd0,4)'   # sda4. y u got dumb nums, grub?
        chainloader +1
      }  
    '';
  };
````

**Comment by lethalman** [comment]
@therealpxc I do what I suggested you on my own, I have a debian and installer nixos in a subdirectory. Just works. You are overcomplicating it.

**Comment by Profpatsch** [comment]
Adding other extra systems is very simple, so unless someone comes up with a good implementation (proposal), I suggest we close. cc @vcunat @lethalman

**Comment by vcunat** [comment]
Well, I don't know if such enhancement "issues" should be closed or not &ndash; it's always questionable whether someone will pick them up. `nixos-generate-config` *might* be extended to do something about this automatically, but it doesn't seem a high-priority thing to me personally.

**Comment by palmeida** [comment]
(This issue was solved by adding the grub.useOsProber option, but this page was one of the first Google hits when I was looking for information on how to do it from the other OS, so I'll leave this here in case it's useful. )

In Debian, none of the os-prober tests detect NixOS, but linux-boot-prober works fine (version 1.76 of the os-prober package on Debian Stretch). To make os-prober detect NixOS and get the short and long name, I dropped an 85nixos file in /usr/lib/os-probes/mounted/ , with the following contents:
```
#!/bin/sh
# Test for NixOS Linux distribution.
set -e

. /usr/share/os-prober/common.sh

partition="$1"
dir="$2"
type="$3"

file="$dir/etc/nixos/configuration.nix"
if [ ! -e "$file" ]; then
        exit 1
fi

version=$(awk '/system.stateVersion/{print $2}' FS=\" "$file") 
if [ -z "$version" ]; then
        version="Unknown version"
fi
short="NixOS"
long="$(printf "NixOS (%s)\n" "$version")"
label="$(count_next_label "$short")"
result "$partition:$long:$label:linux"
exit 0
```
Afterwards, `update-grub` and `grub-install` created the NixOS entries.
