### ISSUE TITLE
Find a better pattern for using Nixpkgs config

### ISSUE THREAD

**Issue by ehmry** [NixOS/nixpkgs#7446]
I think the config argument to nixpkgs is underutilized, and where it is in use, its kind of messy, so I'd like to see some documention for consistent use and more customibility in packages.

Starting with the MPD package, here is how its done and two ways I think it could be improved

##### all-packages.nix
```nix
{
  mpd = callPackage ../servers/mpd {
    aacSupport    = config.mpd.aacSupport or true;
    ffmpegSupport = config.mpd.ffmpegSupport or true;
  };
}
```
##### mpd/default.nix
```nix
{ stdenv, fetchurl, pkgconfig, glib, systemd, boost
, alsaSupport ? true, alsaLib
, flacSupport ? true, flac
, vorbisSupport ? true, libvorbis
, madSupport ? true, libmad
, id3tagSupport ? true, libid3tag
, mikmodSupport ? true, libmikmod
, shoutSupport ? true, libshout
, sqliteSupport ? true, sqlite
, curlSupport ? true, curl
, audiofileSupport ? true, audiofile
, bzip2Support ? true, bzip2
, ffmpegSupport ? true, ffmpeg
, fluidsynthSupport ? true, fluidsynth
, zipSupport ? true, zziplib
, samplerateSupport ? true, libsamplerate
, mmsSupport ? true, libmms
, mpg123Support ? true, mpg123
, aacSupport ? true, faad2
, pulseaudioSupport ? true, pulseaudio
, jackSupport ? true, jack2
, gmeSupport ? true, game-music-emu
, icuSupport ? true, icu
}:
```

##### all-packages.nix
```nix
{
    findOpts = pkgName: opts: with builtins;
    let
      pkgConfig =
        if hasAttr pkgName config
        then getAttr pkgName config
        else { };
    in
    listToAttrs (map
      (name:
        { inherit name;
          value =
            if hasAttr name pkgConfig
            then getAttr name pkgConfig
            else getAttr name opts;
        }
      ) (attrNames opts));

  mpd = callPackage ../servers/mpd (findOpts "mpd" {
    aacSupport        = true;
    alsaSupport       = true;
    bzip2Support      = true;
    audiofileSupport  = true;
    clientSupport     = false; # Act as a proxy to another MPD instance.
    curlSupport       = true;
    ffmpegSupport     = true;
    fluidsynthSupport = true;
    flacSupport       = true;
    gmeSupport        = true;
    icuSupport        = true;
    id3tagSupport     = true;
    jackSupport       = config.jack or false;
    madSupport        = true;
    mikmodSupport     = true;
    mmsSupport        = true;
    mpg123Support     = true;
    opusSupport       = true;
    pulseaudioSupport = config.pulseaudio or true;
    samplerateSupport = true;
    shoutSupport      = true;
    sqliteSupport     = true;
    vorbisSupport     = true;
    zipSupport        = true;
  });
}
```
##### mpd/default.nix
```nix
{ stdenv, fetchurl, pkgconfig, glib, systemd, boost
, alsaSupport, alsaLib
, flacSupport, flac
, vorbisSupport, libvorbis
, madSupport, libmad
, id3tagSupport, libid3tag
, mikmodSupport, libmikmod
, shoutSupport, libshout
, sqliteSupport, sqlite
, curlSupport, curl
, audiofileSupport, audiofile
, bzip2Support, bzip2
, ffmpegSupport, ffmpeg
, fluidsynthSupport, fluidsynth
, zipSupport, zziplib
, samplerateSupport, libsamplerate
, mmsSupport, libmms
, mpg123Support, mpg123
, aacSupport, faad2
, pulseaudioSupport, pulseaudio
, jackSupport, jack2
, gmeSupport, game-music-emu
, icuSupport, icu
, clientSupport, mpd_clientlib
, opusSupport, libopus
}:
```
##### all-packages.nix
```nix
{
  config' = config // {
    findOpts = pkgName: opts: with builtins;
    let
      pkgConfig =
        if hasAttr pkgName config
        then getAttr pkgName config
        else { };
    in
    listToAttrs (map
      (name:
        { inherit name;
          value =
            if hasAttr name pkgConfig
            then getAttr name pkgConfig
            else getAttr name opts;
        }
      ) (attrNames opts));
  };

  mpd = callPackage ../servers/mpd { };
}
```
##### mpd/default.nix
```nix
{ stdenv, config'
, fetchurl, pkgconfig, glib, systemd, boost
, alsaLib
, flac
, libvorbis
, libmad
, libid3tag
, libmikmod
, libshout
, sqlite
, curl
, audiofile
, bzip2
, ffmpeg
, fluidsynth
, zziplib
, libsamplerate
, libmms
, mpg123
, faad2
, pulseaudio
, jack2
, game-music-emu
, icu
}:

let
  opts = config'.findOpts "mpd" {
    aacSupport        = true;
    alsaSupport       = true;
    bzip2Support      = true;
    audiofileSupport  = true;
    clientSupport     = false; # Act as a proxy to another MPD instance.
    curlSupport       = true;
    ffmpegSupport     = true;
    fluidsynthSupport = true;
    flacSupport       = true;
    gmeSupport        = true;
    icuSupport        = true;
    id3tagSupport     = true;
    jackSupport       = config'.jack or false;
    madSupport        = true;
    mikmodSupport     = true;
    mmsSupport        = true;
    mpg123Support     = true;
    opusSupport       = true;
    pulseaudioSupport = config'.pulseaudio or true;
    samplerateSupport = true;
    shoutSupport      = true;
    sqliteSupport     = true;
    vorbisSupport     = true;
    zipSupport        = true;
  };

in with opts; stdenv.mkDerivation rec {
...
}
```

Anyone have other patterns that would work better?

**Comment by ehmry** [comment]
There is probably some way to put option defaults and documention in meta and make a tool to parse and print them...

**Comment by edwtjo** [comment]
I would favour the middle idiom since there is one place, `all-packages.nix`, to look for all config options; the same idiom is used when we pass individual dependencies to the build expression and not just `pkgs`. I also however like the last one since it is more convenient from a package authoring viewpoint.

**Comment by Phreedom** [comment]
You can easily set default configs like this:

# all-packages.nix
{
   aacSupport = true;
   mpd = callPackage ../servers/mpd {};
}

This assumes of course that mpd has this config option:

# mpd/default.nix
, aacSupport ? true, faad2

You can then trivially do a global and per-package override of the config 
value. Setting global aacSupport to null also should work to let packages pick 
their preferred local default(need to test to make sure).

Problems with this approach are:
* It's convention-based. There's no way to tell if something is a config 
option, not even by its data type if its default is null. Thus, it's hard to 
force people to document their options in a structured way

* Binary packages. Or rather, lack of them. Lots of people from Gentoo 
initially crave use flags. Especially since they are effectively free unlike in 
NixOS. But eventually convenience wins.

* Maintenance overhead. Correctly identifying all optional dependencies, 
putting this knowledge into the derivation, adding asserts, testing at least 
common option combinations takes quite some effort.

The first step could be finding out what config values are actually in use eg by 
grepping typical patterns like with* or *support and trying to get rid of 
duplicates, introduce some config naming guidelines etc etc.

Documenting this would be nice too.

If you don't get tired of it by then... the sky is the limit ;)

**Comment by ehmry** [comment]
I came from Gentoo, and NixOS seems to be better in everyway except this one (but atleast we don't have package block hell).

It sounds like the issue of options and dependencies would imply that options that are applied should be passthrough attributes.

**Comment by codyopel** [comment]
Expanding on what @Phreedom said...

It should be noted that the ```config``` method is discouraged.  Using the ```config``` method doesn't allow overriding specific derivations (typically in cases where there are multiple versions of a package).  The ```config``` method should typically only be used for global configuration options, not per package configuration options.

**Comment by Phreedom** [comment]
it is also possible to inherit flags from dep passthru if that's what you want, 
but there's no general solution since package dependencies can come with 
different values of the same flag and it's up to you to decide if you want to 
throw an exception, fold it with and/or etc.

I was under impression that gentoo doesn't let you inherit flags, only set them 
based on package name regexp, probably because of exactly this problem.

**Comment by ehmry** [comment]
Well, we do have the regexp primop now, but I worry that it would hurt evualation time to run through a lot of options.

**Comment by lethalman** [comment]
What we can do here is changing callPackage slightly, which is doable. Instead of looking up only in `pkgs` it would look up also `config`.

**Implementation**

1. All the packages would have non-optional config flags, like `{ ..., fooSupport, .. }`
2. There must be a default nixpkgs config with `fooSupport = true/false;`. That not only helps document config flags, but also have a consistent choice across all packages by default.
3. Then callPackage would first look into pkgs for feeding inputs, of course, and then also config. The `newScope` calls would retain config.

**Usage**

In top-level you'd have `config.fooSupport = true; pkg = callPackage ./mypkg.nix { };`.

In mypkg.nix you'd have `{ ..., fooSupport, ... }`.

**Comment by ehmry** [comment]
Thats sounds good to me, but I would add that we could define config in a seperate file along with documentation strings, something like
```nix
{
  pulseaudioSupport =
    { value = true;
      description = "Pulseaudio support.";
    };

  aesniSupport =
    { value = false;
      description = "Use AES-NI instructions.";
    };
}
```

The benefit being the docstrings could be regexed by helpers inside nix-repl or dumped to json for external tools.

**Comment by Phreedom** [comment]
On Tuesday, April 21, 2015 07:19:58 lethalman wrote:
> 1. All the packages would have non-optional config flags, like `{ ...,
> fooSupport, .. }` 2. There must be a default nixpkgs config with
> `fooSupport = true/false;`. That not only helps document config flags, but
> also have a consistent choice across all packages by default. 3. Then
> callPackage would first look into pkgs for feeding inputs, of course, and
> then also config. The `newScope` calls would retain config.

Not a bad idea, although I'd go for tri-state flags. Imagine a package with a 
gtk- and qt-based gui, once of which is production-grade and another is 
experimental. It would be nice for package to provide sane defaults while 
letting purists get what they want/deserve :) Another example: package hides  
behind default=false flag a non-essential dependency which greatly increases 
build time/closure size or causes potential instability or vulnerabilities. I 
was under impression this is what gentoo does.

Also, while I didn't look at the code, you probably don't need to modify 
callPackage and instead in pkgsFun you can do a trivial pkgs // attrMap over 
the config argument which would translate fancy config definitions into plain 
absent/true/false flags.

If you don't get tired of this, you can also add meta.flags.$flag_name = 
$description support and provide a nice way to query this for users along with 
global flag descriptions.

But again, before you do this, you need to sort out the mess we have with the 
existing flags: come up with a naming scheme, fix the offending packages and only 
then it makes sense to add this global config handling and auto-generated 
documentation.

**Comment by lethalman** [comment]
@Phreedom somewhat I agree that packages should have a degree of freedom on what flags should be enabled or not, it's a little hard to decide though. A tri-state might be a solution.

Yeah whatever, bringing config in the scope works too, it was just to say we can do this directly at callPackage level without further magic.

The meta for flags might be acceptable, not sure. Given all the examples we have of flags usage, I believe a meta description of flags wouldn't hurt.

About fixing the naming ecc., that's the last problem, really. It will be done, step by step, as packages break, ecc.. I don't even think about it.

**Comment by Phreedom** [comment]
On Wednesday, April 22, 2015 01:26:23 lethalman wrote:
> About fixing the naming ecc., that's the last problem, really. It will be
> done, step by step, as packages break, ecc.. I don't even think about it.

Packages won't break, they simply won't use the global flag values unless you 
unify the flag names. And local flags already work just fine.

**Comment by wkennington** [comment]
@Phreedom You wouldn't need a tri-state for the case of a solid qt gui and experimental gtk gui. If a user has both gtk & qt support enabled it would pick the qt gui unless they did a forceful override of the package. In the case where they want gtk only, it might even be nice if packagers added warnings about certain features being experimental / scary. Then the end user would get the idea that maybe they should enable qt or they can stick with experimental.

**Comment by Phreedom** [comment]
On Sunday, April 26, 2015 10:54:45 William A. Kennington III wrote:
> @Phreedom You wouldn't need a tri-state for the case of a solid qt gui and
> experimental gtk gui. If a user has both gtk & qt support enabled it would
> pick the qt gui unless they did a forceful override of the package. In the
> case where they want gtk only, it might even be nice if packagers added
> warnings about certain features being experimental / scary. Then the end
> user would get the idea that maybe they should enable qt or they can stick
> with experimental.


You are describing a situation where the package has both usegtk and useqt 
flags and they are both enabled. I'm taking about eg experimental gtk gui, 
useqt = false, usegtk = true.

In general I find flags for a specific dependency package(s) a bit too low-level, 
especially for global flags.

And while I don't mind having global flags also for this if can get them 
effectively for free, the real use case is something like withXorg/withGUI = 
false to build a headless machine.  The key difference here is that withGUI 
describes a feature, not a specific lib/dependency. To set withJava=false 
globally, you have to review all the packages in the system closure to see if 
you are dropping something very useful or not because there's no way to tell 
if java is used to eg generate some docs or run tests or it is used to provide 
a major feature.

**Comment by wkennington** [comment]
I addressed the useqt = false and usegtk = true case:
"In the case where they want gtk only, it might even be nice if packagers added warnings about certain features being experimental / scary. Then the end user would get the idea that maybe they should enable qt or they can stick with experimental."

And sure, feature flags often remove some very indirect features that you may not have known about.

**Comment by Phreedom** [comment]
Ah you mean writing something to console while the derivation is being 
evaluated. That's certainly possible, although nixpkgs users aren't used to 
looking at build logs. Either way, if you implement feature flags, you 
automatically implement dependency flags, so noone's stopping you. I still 
doubt depencency flags will be used much in practice.

**Comment by vcunat** [comment]
Reading all this, IMHO ``packageOverrides`` already provides all the power we need for per-package overrides. It does require a little much typing for the usual simple overrides; if need be, that could be extended e.g. by also having some simpler variant (example below), implemented via a transformation into ``packageOverrides``. Personally I like that ``packageOverrides`` allows to uniformly express *exactly* what one wants.

```nix
simpleOverrides = {
  mpd.aacSupport = true;
  mpd.ffmpeg = ffmpeg-full;
  /*...*/
};
```

As for global overrides, IMO that's a bit deceiving thing, as people rarely truly want to enable e.g. aacSupport for *every* package in the closure, as such changes come with a large cost of rebuilding most packages due to less-expected transitive dependencies (and repeating this after most channel bumps).

**Comment by Profpatsch** [comment]
Agree with @vcunat that everything can be done with `packageOverrides` and the default override functionality right now, so no reason to add boilerplate to the already gigantic all-packages.nix (also one that is entirely conventional!).

Fabian Schmitthenner has recently posted a WIP of displaying existing optional package options on the package site, which is a solution to the discovery problem, see http://lists.science.uu.nl/pipermail/nix-dev/2016-February/019792.html

I suggest we close this.
