### ISSUE TITLE
Document Postgresql upgrade

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#7454]
1. set `services.postgresql.package` to newer version
2. change `services.postgresql.dataDir` to different directory as `/var/db/postgresql/9.4/`
3. run `pg_upgrade -b /nix/store/5b319y5k0p270a0mq16s6gl7jq5kgmjx-postgresql-9.2.9/bin -B /nix/store/47i5wmdyqjjxc6cj6g6mhsrg0ywzynl6-postgresql-9.4beta3/bin -d /var/db/postgresql/ -D /var/db/postgresql/9.4` under postgresql user

Output I get:

```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok

connection to database failed: FATAL:  role "postgres" does not exist
```

**Comment by Shados** [comment]
The NixOS service module for PostgreSQL, for some unfathomable reason, initializes new databases using a non-standard superuser role name (`root` instead of `postgres`). This makes it a nightmare to get `pg_upgrade` to work right, so forget that. Instead:

1. Swap back to your old version of postgresql
2. As root, dump your entire database to a file somewhere: `pg_dumpall > db_dump.out`
3. Swap to the new version of postgresql
4. As root, read in the database dump: `psql -f db_dump.out postgres` (you'll likely see an error go by about the `root` role already existing, you can ignore this)

For good measure I went and tested this upgrading a 9.2 database to 9.4 under NixOS, worked fine, the applications using it continued on as normal after the import.

----------

That said, the real issue here is: why are we initializing databases using a non-standard install  / superuser role name?

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by edolstra** [comment]
See https://github.com/NixOS/nixpkgs/issues/2097 regarding the superuser role name.

**Comment by zimbatm** [comment]
Shouldn't we switch the default user to "postgres" on new databases and keep the "root" account around for existing-ones ?

**Comment by wizeman** [comment]
I strongly agree we should switch the default user to `postgres`.

Currently, it seems impossible to use `pg_upgrade` to upgrade postgresql databases due to NixOS using the `root` superuser: `pg_upgrade` simply refuses to run as root.

**Comment by wizeman** [comment]
The `pg_dumpall` approach given by @Shados above doesn't work for me:
```
# pg_dumpall > /tmp/root/db.out
pg_dump: [archiver (db)] connection to database "hydra" failed: FATAL:  Peer authentication failed for user "root"
pg_dumpall: pg_dump failed on database "hydra", exiting
```

**Comment by zimbatm** [comment]
I can submit the change as a PR but don't use postgresql and it needs testing

**Comment by FlorianHeigl** [comment]
pg_dumpall tends to e pretty useless if you database isn't _tiny_ :(

**Comment by domenkozar** [comment]
@zimbatm that would be a good start :)

**Comment by zimbatm** [comment]
@domenkozar there you go :)

**Comment by domenkozar** [comment]
FYI: I've just tested migrating 9.2 to 9.6 using https://github.com/NixOS/nixpkgs/issues/7454#issuecomment-133808400 and it works flawlessly.

**Comment by wizeman** [comment]
Ok, I think I found out why `pg_dumpall` wasn't working for me, like I mentioned in https://github.com/NixOS/nixpkgs/issues/7454#issuecomment-190701873.

It seems to be due to this line in the Hydra module:

https://github.com/NixOS/nixpkgs/blob/54a4b77caa17113f317c76984434c3545cf7e741/nixos/modules/services/continuous-integration/hydra/default.nix#L417

If I change the mapping to `hydra-users root root` then the `pg_dumpall` command works fine.

But I'm not exactly sure what are the implications of doing this, or why `root` was mapped to `hydra` in the first place...

**Comment by wizeman** [comment]
In case someone runs into the same issue as me, I am documenting the procedure I used to upgrade a PostgreSQL database that was being used (only) for Hydra.

I tried to follow @Shados's procedure above, but as I mentioned before, to use `pg_dumpall` as @Shados suggested I needed to change the PostgreSQL user mapping in the Hydra module as specified in my comment just above this one, otherwise I would get a `Peer authentication failed for user "root"` message.

However, to read the database dump back into the new PostgreSQL database I had to change the user mapping as follows:
```diff
-        hydra-users root hydra
+        hydra-users root postgres
+        hydra-users postgres postgres
```
... and then, after activating the configuration, I needed to run the `psql` command in the following way (as root): `sudo -u postgres psql -f db_dump.out postgres`

After doing this, the upgrade from PostgreSQL 9.4 to 9.6 seems to have completed successfully.

**Comment by danbst** [comment]
Related https://discourse.nixos.org/t/nix-env-how-i-can-install-two-differents-versions-of-the-same-software-inside-a-user/3490

**Comment by martinetd** [comment]
If anyone else stumbles on this, pg_upgrade seems to work now.

I realized after upgrade that my db got reinitialized, so steps for me were much more brutish than that post, but in a nutshell:
 * with new postgresql running, clear whatever got reinitialized (pg_upgrade won't run if there are data around, but won't tell you what to remove... `\l` lists databases, don't know how to list users, I guessed)
   * drop database whatever;
   * drop user whatever;
 * stop postgresql.service
 * figure path for old binaries, e.g. `ls /nix/store/*postgresql-<oldversion>*/bin/psql` and copy it somewhere.
 * run the actual pg_upgrade as `postgres` user: `pg_upgrade -b /nix/store/j6maph2088c5bzrmzi30d6wp080y3avi-postgresql-9.6.15/bin/ -B /nix/store/vnbch669p9h6ydyy98cd2r1clmv^Cx5r-postgresql-11.7/bin/ -d /var/lib/postgresql/9.6/ -D /var/lib/postgresql/11.1/`
 * restart the postgresql service

if all went well after some testing pg_upgrade suggests removing the old db with `./delete_old_cluster.sh`


(disclaimer: Don't blame me if that eats your data)
