### ISSUE TITLE
aarch64-linux ghostscript-9.50 broken on hydra

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#76051]
example build:
https://hydra.nixos.org/build/108506145

holding up ~530 packages

**Comment by worldofpeace** [comment]
I just got nixpkgs-master on the aarch64-linux community builder, and doing `nix-build -A ghostscript` or `ghostscriptX` has it copy from cache.nixos.org. And doing `--check` results in a successful builds.

Perhaps under a great load this fails due to timing related issues :grey_question: 
Still seeing a cached failure https://hydra.nixos.org/build/109693062, but from looking in history it has since been successful https://hydra.nixos.org/build/109469256.
It doesn't even take long to build on the builder (around 1m 52 seconds).

**Comment by jonringer** [comment]
no longer relevant

**Comment by worldofpeace** [comment]
I still see this failure all the time on hydra though. And for sure on release 20.03.

**Comment by jonringer** [comment]
It's be fixed, (and then broken again), and having an issue open doesn't seem to improve the situation :/
