### ISSUE TITLE
Steam fails to launch

### ISSUE THREAD

**Issue by Fuzen-py** [NixOS/nixpkgs#76085]
**Describe the bug**
Steam fails to launch

**To Reproduce**
1. ... launch steam

**Expected behavior**
Steam opens

**Additional context**
Strace [here](https://gist.github.com/Fuzen-py/e349e90454746990329351fdce0855a2)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.5-zen1, NixOS, 20.03pre205780.d942688fc13 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(aizuzu): `""`
 - channels(root): `"nixos-20.03pre205780.d942688fc13"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
steam runs fine for me on unstable. is this still an issue?

**Comment by mcoleman-sain** [comment]
I've been having this problem for a few days now also so I guess it's still an issue.
Rolling channels back and forward, or nix-building steam from various tags including master, stable, unstable, makes no difference - I still get that failure with near-identical strace.

In fact it seems like steam isn't actually the problem, since no matter what target(s) I manually give chrootenv the same issue occurs - but chrootenv with no target doesn't completely fail. So steam isn't alone in causing this.

```
$ /nix/store/ap71q9vjw1g63l7rq2y9m5psq5pf5p8g-chrootenv/bin/chrootenv
** Message: 21:20:07.622: /nix/store/ap71q9vjw1g63l7rq2y9m5psq5pf5p8g-chrootenv/bin/chrootenv command [arguments...]


$ /nix/store/ap71q9vjw1g63l7rq2y9m5psq5pf5p8g-chrootenv/bin/chrootenv /nix/store/lb3hli8d9536g45mndwfwyi6fpny0blh-bash-interactive-4.4-p23/bin/bash
** (process:2594): ERROR **: 21:20:12.264: main: execvp(*argv, argv): No such file or directory
[1]    2593 trace trap (core dumped)  /nix/store/ap71q9vjw1g63l7rq2y9m5psq5pf5p8g-chrootenv/bin/chrootenv```

The error even occurs in a `--pure` nix-shell, or when using a profile in which it didn't previously fail, which should be impossible. It still happens when I clear my entire configuration.nix, except for steam. It has to be caused by something which persists between rebuilds and old/new profiles. 

I'm thinking some kind of permissions error, maybe..? Or a corrupted database? I'm familiar enough with NixOS to know that this error shouldn't occur, but not familiar enough to be able to debug it! Maddening.

**Comment by jonringer** [comment]
my assumption is that `/nix/store/lb3hli8d9536g45mndwfwyi6fpny0blh-bash-interactive-4.4-p23/bin/bash` doesn't actually exist

**Comment by FliegendeWurst** [comment]
Not an issue anymore. If it occurs again a new issue should be opened.
