### ISSUE TITLE
package request: TiLP 

### ISSUE THREAD

**Issue by mehlon** [NixOS/nixpkgs#76098]
**Project description**
TiLP is a program for transferring files to Texas Intruments calculators.

**Metadata**

* homepage URL: http://lpg.ticalc.org/prj_tilp/
* source URL: https://sourceforge.net/projects/tilp/files/
* license: GPL2
* platforms: unix, linux, darwin, windows ...

**Comment by mehlon** [comment]
AUR package: https://aur.archlinux.org/packages/tilp/
AUR PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tilp
Void Linux package: https://github.com/void-linux/void-packages/blob/master/srcpkgs/tilp2/template

**Comment by luc65r** [comment]
I've tried some time ago: https://github.com/luc65r/nixpkgs/commit/1091e64c8e91330b209810190781702ff5591120, but I didn't succeed.
I might try again now that I know more about Nix.

**Comment by myclevorname** [comment]
I would like to see this re-added into NixOS.

**Comment by caseyavila** [comment]
@myclevorname I threw [this](https://gist.github.com/caseyavila/05862db1fcc8b4544bd9dcc9ecc444b9) together if you want to use it for now.

**Comment by rickalex21** [comment]
Strangely enough all the library packages for it are available but the program itself is not? 

![image](https://github.com/user-attachments/assets/701f88cc-7ace-4e60-98c3-5e534c5787a0)

**Comment by myclevorname** [comment]
libglade had been [removed](https://github.com/NixOS/nixpkgs/pull/155061) from Nixpkgs partially due to its dependency on Python 2. The libti* dependencies stayed because they are not affected by that change, despite tilp2 getting dropped. The workaround on my system uses the 21.11 channel, the last to contain it. If you wanted it re-added into Nixpkgs, you would have to rewrite a large portion of TILP to not use libglade.

**Comment by debrouxl** [comment]
libti*/gfm/tilp upstream here. TILP was rewritten to use GTK+Builder over a decade ago :)

You might be mixing up TILP with the much smaller GFM, which keeps using libglade because nobody spent time converting it to GTK+Builder, or the fact that old versions of the Windows installer for TILP depended on the gladewin32 GTK+ runtime flavor.
