### ISSUE TITLE
nixos-rebuild fails, when xserver.videoDrivers is set to [ "amdgpu-pro" ]

### ISSUE THREAD

**Issue by thilobillerbeck** [NixOS/nixpkgs#78031]
**Describe the bug**
When I switch my video drivers to "amdgpu-pro", my rebuild fails with the error message: 
```
error: unsupported xorg abiCompat 1.19 for xorg-server-1.20.5
(use '--show-trace' to show detailed location information)
```
Additionally, when I use `boot.kernelPackages = pkgs.linuxPackages_latest;`, it has a conflict with a `boot.kernelPackages` in the amdgpu_pro module.
```
The option `boot.kernelPackages' has conflicting definitions, in `/path/to/my/config/hardware.nix' and `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/hardware/video/amdgpu-pro.nix'.
```
**To Reproduce**
1. set `services.xserver.videoDrivers` to `[ "amdgpu-pro" ];`
2. `nixos-rebuild switch`
3. To reproduce the secound error: set `boot.kernelPackages` to `pkgs.linuxPackages_latest;`

**Expected behavior**
The rebuild should run without errors, and X should use the amdgpu-pro drivers after a reboot.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.13, NixOS, 19.09.1912.5b9eee22acf (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(thilo): `""`
 - channels(root): `"nixos-19.09.1912.5b9eee22acf, nixos-unstable-20.03pre209690.c438ce12a85"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- services.xserver.videoDrivers
module:
- /modules/hardware/video/amdgpu-pro.nix
```

**Comment by DieGoldeneEnte** [comment]
I have the same problem.
I suspect the abiCompat problem is the result of nixos-19.09 using xorg-server 1.20.* instead of 1.19.* .
Regarding the second (kernelPackages) problem: I don't think this is a bug, but the result of amdgpu-pro containing closed-source components, which requires a specific kernel.

I don't have time at the moment, but will try to have a look in a week or so.

**Comment by DieGoldeneEnte** [comment]
I can't debug this, because I need a newer kernel than amdgpu-pro supports :/ (I will look into that, but that is not a high priority for me at the moment)
At the moment the newest release of amdgpu-pro seems to require something around kernel 4.16 (I could only find the supported Distributions), the build using 5.4 failed for me, but I can't say I fully understand the video-driver setup.

Maybe @corngood could take a look at it? The main problem in this issue is the xorg-version expected by amdgpu-pro (as set in the package) and the xorg version in nixpkgs.

There also is a new version [19.50](https://www.amd.com/en/support/kb/release-notes/rn-rad-lin-19-50-unified).

If someone gets it working on a newer kernel I would gladly help testing.

**Comment by scalavision** [comment]
The new version you point to seems to support kernel v 5, since it supports ubuntu 18.03 which has kernel v 5 ..

**Comment by DieGoldeneEnte** [comment]
I didn't look up the versions at that point, since I find it is quite cumbersome to find the kernel being used in the distribution (maybe I just look in the wrong places?).
There is also #79562 (and #46765 with 18.03), with version 20.10, (Used in Ubuntu 18.04.4). I had a short look, but didn't get to much done yet. In that issue @killercup also started on updating it.
I use [rocm](https://github.com/nixos-rocm/nixos-rocm), which I use for at the moment to get OpenCL.

**Comment by davidak** [comment]
>I didn't look up the versions at that point, since I find it is quite cumbersome to find the kernel being used in the distribution (maybe I just look in the wrong places?).

You can find versions of ubuntu packages here: https://packages.ubuntu.com/bionic/kernel-image

I also found this page: https://ubuntu.com/kernel/lifecycle

Here are also information: https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_18.04_LTS_(Bionic_Beaver)

So the initial release of Ubuntu 18.04 seem to has kernel 4.15 and later had 5.3.

>I use rocm, which I use for at the moment to get OpenCL.

OpenCL works with amdgpu in this PR: https://github.com/NixOS/nixpkgs/issues/87990

**Comment by killercup** [comment]
Version 20.20 is out now: https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-20

**Comment by 6AA4FD** [comment]
@corngood do you have any plans to work on this?

**Comment by corngood** [comment]
I haven't had a use for it in a while, so probably not any time soon.

**Comment by Jiehong** [comment]
I confirm this issue is still unresolved.

**Comment by Jiehong** [comment]
Version 4.0.1 is out, but supported kernels are 5.4 and 5.6: https://raw.githubusercontent.com/RadeonOpenCompute/ROCm/master/AMD_ROCm_Release_Notes_v4.0.pdf

Releases can now be seen in https://github.com/RadeonOpenCompute/ROCm/releases.

**Comment by tklitschi** [comment]
can also replicate this issue on 20.09

**Comment by TheOddler** [comment]
I now have the same issue on 21.05.

**Comment by Globabee** [comment]
Same issue, I can rebuild if I remove this from my config
`kernelPackages = pkgs.linuxPackages_latest;`

**Comment by davidak** [comment]
This is fixed on unstable. The pinned kernel version has a dedicated issue.

**Comment by ezracelli** [comment]
Looks like this may have cropped up again? I'm on unstable (5a1dc8acd977ff3dccd1328b7c4a6995429a656b), and getting the following:

```console
$ cat /etc/nixos/configuration.nix | grep "amdgpu"
  services.xserver.videoDrivers = [ "amdgpu-pro" ];
```

```console
# nixos-rebuild switch --flake /etc/nixos#nixos
building the system configuration...
error: attribute 'name' missing

       at /nix/store/nbp8axqsz7zbkd03zia0v60jhi382ly9-source/pkgs/servers/x11/xorg/overrides.nix:653:67:

          652|           }
          653|         else throw "unsupported xorg abiCompat ${abiCompat} for ${attrs_passed.name}";
             |                                                                   ^
          654|
       Did you mean pname?
(use '--show-trace' to show detailed location information)
```

The error message seems to be due to #167893, but looks like it's _trying_ to throw this error.

- `amdgpu-pro` has version `21.30` (note, there is actually a new version `22.40` out)
- `"amdgpu-pro"` driver sets `abiCompat = "1.20"`
- `xorg-server` has version `21.1.7`

#### Metadata

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.18, NixOS, 23.05 (Stoat), 23.05.20230312.5a1dc8a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
