### ISSUE TITLE
node-gyp requires python(2) to be installed

### ISSUE THREAD

**Issue by fctorial** [NixOS/nixpkgs#78205]
**To Reproduce**
1. Run these commands:
```
nix-shell -p nodejs nodePackages.node-gyp --pure
mkdir tmp
cd tmp
npm init -y
npm i piface
```
Last command will fail with an error saying `python executable not found`. It will fail even if you have `python3` installed.

**Expected behavior**
`node-gyp` package should be linked to `python2`.

**Metadata**
 - system: `0`
 - host os: `Linux 4.19.80, NixOS, 19.09.976.c75de8bc12c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(saga): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by doronbehar** [comment]
@fctorial node js doesn't enforce you to have python installed in order to perform most of what it can do (see [this](https://stackoverflow.com/questions/23709739/why-does-node-js-need-python)) . I think this behavior is justified. You should add a python package to that `nix-shell` environment if you want to perform `piface` related stuff. 

As for the python2/3 issue in node-gyp, Currently only the most latest version of nodejs (13_x) can work with python3 as well as python3. As part of the migration to python3 in nodejs 13_x that supports it, see https://github.com/NixOS/nixpkgs/pull/84599 .
