### ISSUE TITLE
Deno

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#78461]
**Project description**
Deno - A secure JavaScript and TypeScript runtime

**Metadata**

* homepage URL: https://deno.land/
* source URL: https://github.com/denoland/deno
* license: mit
* platforms: unix, linux, darwin

**Comment by kolbycrouch** [comment]
I have it building on nix. However it needs modifications to rusty_v8 so we can use our llvm9 instead of the llvm10 that ships with it. It also needs modification to use libstdc++ instead of custom libc++ incase you want to build against musl.

**Comment by kiloreux** [comment]
@kolbycrouch Do you have it anywhere in the open? I want to continue working on it from there. I couldn't get it to work initially.

**Comment by kolbycrouch** [comment]
@kiloreux I don't have a nix expression to build it as a derivation, I just made a shell.nix with the dependencies and manually edited the files in the cargo cache. give me a few days and I'll push what I've done to get it to work at the very least.

**Comment by JLarky** [comment]
I'm extremely sorry, this is first few lines of code I ever have written in nix (and I feel like it could be my last) but I want to share it anyway https://gist.github.com/JLarky/09a8622dad083573222173abb2e17238

p.s. I don't even know how to provide some examples of using this since it only works in one particular project and fails with example code I got online, I hope someone can use it anyway

**Comment by johnpyp** [comment]
@JLarky I tested your build, and it doesn't seem to work due to linking issues that I've noticed just using the binary on its own. I'm not sure how to solve them though.
