### ISSUE TITLE
Discord can't open links in Firefox

### ISSUE THREAD

**Issue by deingithub** [NixOS/nixpkgs#78961]
## Issue description
When using current NixOS 19.09 versions for Discord and Firefox, you cannot open links by clicking on them in Discord anymore. 

### Steps to reproduce

Run `nix-shell -p discord --run Discord` while having firefox open.
Log in and attempt to open any link, or perform any interaction that would open a website in firefox. It will fail silently. 
For an error message, press ctrl-shift-i to bring up the inspector and type the following into the console:
```js
child_process = require("child_process")
child_process.execSync("firefox https://example.com")
```
This will fail with an error message like
```
Uncaught Error: Command failed: firefox example.com
XPCOMGlueLoad error for file /nix/store/bzr1jrf17ypd6l1rhxi4zn572sa0288b-firefox-unwrapped-72.0.2/lib/firefox/libxul.so:
/nix/store/002anz2c55ml3hwf2niz42541iwq96gh-nss-3.46.1/lib/libnss3.so: version `NSS_3.47' not found (required by /nix/store/bzr1jrf17ypd6l1rhxi4zn572sa0288b-firefox-unwrapped-72.0.2/lib/firefox/libxul.so)
Couldn't load XPCOM.
```
This error message lead me to the assumption that a libnss version mismatch between Firefox and Discord is to blame, and indeed overriding the libnss version of the discord package to a newer one fixes the problem, so that a derivation built from the expression below can normally open links. 
```nix
with import <nixpkgs> {};

pkgs.discord.override {
    nss = pkgs.nss_3_49_2;
}
```
This fix doesn't seem to have had any negative impact after a few days of running with it.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.98, NixOS, 19.09.1965.274e095f761 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.1965.274e095f761"`
 - channels(cassidy): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
I believe, this has to do with how we are backporting the updates to non-ESR versions of the firefox.

cc @andir @eelco @taku0 @fpletz

**Comment by jtojnar** [comment]
Well, Firefox usually requires latest NSS on every update so we cannot really fix that.

The issue is that [`LD_LIBRARY_PATH`](https://github.com/NixOS/nixpkgs/blob/769928e2138ce314e52423a6b6a72848d303281e/pkgs/applications/networking/instant-messengers/discord/base.nix#L36) gets inherited by child processes like firefox. I do not see other solution than adding the libraries to every ELF executable using `patchelf --add-needed` after stripping.

**Comment by pbogdan** [comment]
I don't know much about Discord's packaging but perhaps it would be possible to use `autoPatchelfHook` instead of setting `LD_LIBRARY_PATH`?

**Comment by jtojnar** [comment]
`autoPatchelfHook` will not work for `dlopen`ed libraries. Not sure what the ratio of linked/loaded libraries is.

**Comment by matthewess** [comment]
The workaround above stopped working for me when Discord forced me to update the client to the latest version. I have tried plugging in various different nss pkgs, but none seem to make links work in the newest version. I also can't issue the commands from the OP to get an error message, when I open the inspector (in Discord?) I am unable to use `require()` in the console.

**Comment by deingithub** [comment]
@matthewess Huh, `require()` not working anymore seems to be related to the update. I updated Discord by waiting for nixpkgs to catch up and it still works fine for me, did you update by installing the tar.gz offered by the forced-update dialogue?

**Comment by matthewess** [comment]
After updating my nix channels and using `discord` and `nss_3_51` from nixos-19.09, I can confirm the workaround is still good.

**Comment by zimbatm** [comment]
I just opened a link from Discord with Firefox, in KDE. nixos-unstable.

**Comment by Ralith** [comment]
This is still affecting 20.09; `(discord.override { nss = nss_latest; })` is necessary to get working links.

**Comment by theduke** [comment]
Seeing the same issue in `element`, which is also Eletron

**Comment by ncfavier** [comment]
Why not just add the correct nss to firefox's LD_LIBRARY_PATH so that it overrides the one from the environment? I did that in https://github.com/NixOS/nixpkgs/pull/182069

**Comment by evenbrenden** [comment]
Seeing this with `appgate-sdp` too. I guess it's a potential issue for all applications with an `nss` dependency trying to open Firefox.

**Comment by LunNova** [comment]
Have two open PRs trying to fix this in general (not just fixing firefox -> discord), with slightly different approaches.

Help making progress would be appreciated.

* #187293 - generic approach to swapping out xdg-open with something else, relies on programs picking it up from PATH or using an overlay and causing a lot of rebuilds
* #197118 - adds env var to xdg-open telling it to use the portal, and a config option to set it. Works for everything but needs to go via staging since it's a mass rebuild and doesn't help users who in general want to swap out xdg-open for something else, which is maybe less important. Does not help for opening files, only URLs.

**Comment by bittner** [comment]
This issue is still a problem (on current unstable) when using Discord and GNOME Web as a default browser: When clicking on links in Discord they don't open in Web. As soon as I change the default browser, say, to Brave in the GNOME settings then clicking on links in Discord immediately starts working.
