### ISSUE TITLE
ghc-mod: "Unrecognized option --help, try --help"

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#7926]
All I know:

```
$ ./result/sw/bin/ghc-mod 
.ghc-mod-wrapped: No command given (try --help)
$ ./result/sw/bin/ghc-mod  --help
.ghc-mod-wrapped: Parsing command line options failed: unrecognized option `--help'
```

(Haskell package)

**Comment by peti** [comment]
@matthiasbeyer, which branch / channel are you on?

**Comment by matthiasbeyer** [comment]
unstable

**Comment by peti** [comment]
How did you install `ghc-mod` from the unstable channel? The package has been marked as "broken" there since 3508e627408355a4a32f7dd90726b86b91f84f3d from April 17th.

**Comment by matthiasbeyer** [comment]
I installed it via the `configuration.nix` file.

**Comment by peti** [comment]
I don't see how that could be possible: the package is marked broken. Any attempt to install it fives the following result:

~~~~~~~~~~~
$ nix-env -iA haskellPackages.ghc-mod
error: Package ‘haskell-ghc-mod-5.2.1.2’ in ‘/home/simons/.nix-defexpr/pkgs/development/haskell-modules/hackage-packages.nix:52243’ is marked as broken, refusing to evaluate.
For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.
For `nix-env` you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.
~~~~~~~~~~~~

**Comment by matthiasbeyer** [comment]
```
$ nix-env -iA nixpkgs.haskellPackages.ghcMod 
```

works for me.

**Comment by peti** [comment]
You are definitely not on (a recent version of) nixos-unstable. The attribute you installed, `ghcMod`, doesn't even exist anymore:

~~~~~~~~~~ sh
$ nix-env -iA haskellPackages.ghcMod 
error: attribute ‘ghcMod’ in selection path ‘haskellPackages.ghcMod’ not found
~~~~~~~~~~

Anyway, I guess the point is that `ghc-mod` is currently broken because of https://github.com/kazu-yamamoto/ghc-mod/issues/467, and the maintainers seems to be in no hurry releasing a fixed version. As of now, there is no way to use `ghc-mod` in Nix. People have apparently had success installing a current snapshot directly from the git repository, but there's no official release available that even compiles.

**Comment by matthiasbeyer** [comment]
Jup. Just updated my channels and you're right.

I guess this can be closed now?

**Comment by peti** [comment]
I'm afraid so. There's not much we can do at the moment. When the new version comes out, we'll re-enable the build ASAP.
