### ISSUE TITLE
`rustPlatform` builds Rust Twice at different versions

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#7969]
Building rustPlatform on my single core virtual machine took five and a half hours. Building the biggest part (rustc) took ~2 hours when I did it a couple weeks ago, so something seems off here. I actually built it twice since I created a new VM because I ran out of space - the second time I logged the output to a file:

https://gist.githubusercontent.com/Havvy/ea5b5c0000fff89f487f/raw/build-rust-platform.log

If you search for `Compiling AArch64RegisterInfo.cpp for Release build`, you'll find it's in the log twice. That file is from LLVM.

The first one is followed shortly by:

`make[5]: Entering directory '/tmp/nix-build-rustc-1.0.0-dev-g67433c1.drv-0/rust-67433c1/x86_64-unknown-linux-gnu/llvm/lib/Target/AArch64/TargetInfo'`.

The second one is followed shortly by:

`Entering directory '/tmp/nix-build-rustc-1.0.0.drv-0/rustc-1.0.0/x86_64-unknown-linux-gnu/llvm/lib/Target/AArch64/TargetInfo'`.

This tells me that rustc is being built twice - Once the official 1.0.0 release as requested, and once a random nightly that the Cargo package is tied to. This *really* needs to be fixed, since it's doubling the time to build the package.

I did check to see if `cargo` is building under Release or Debug mode, and it is building under Release mode, so I'm assuming that it's using the official 1.0.0 release built Rust to compile, so that's not an issue, thankfully.

**Comment by Havvy** [comment]
CC @wizeman

**Comment by wizeman** [comment]
Hi @Havvy,

The default `rustPlatform` includes `rustc-1.0.0` (the stable rust compiler) and `cargo`.

However, if you use the default platform then Nix needs to build or fetch two versions of `rustc` because `cargo`, which is also written in rust, cannot be built with the stable rust compiler: it needs to be built with `rustcMaster` instead.

Notice how in your log, one of the derivations that is going to be built is `rustc-1.0.0.drv` (the stable rust), while the other one is `rustc-1.0.0-dev-g67433c1.drv` (the `-dev` version, from git commit `67433c1`). There aren't two `rustc-1.0.0` derivations nor two `rustc-1.0.0-dev-*` derivations, just one of each.

If you really want to compile only 1 version of Rust, then you can use the unstable rust platform instead: in this case, only the unstable rust (i.e. `rustcMaster` aka `rust-1.0.0-dev-*`) will be built.

The attribute name of the unstable rust platform is `rustUnstable`, so you can just use that name instead of `rustPlatform`, or you can do something like:

```nix
myPackage = callPackage ../xxx/myPackage {
  rustPlatform = rustUnstable;
}
```
... and then use `rustPlatform` as usual in your package.

Or, if you are using a `.nix` file in your project, you can do something like:
```nix
let

  pkgs = import <nixpkgs> {}; 

  rustPlatform = pkgs.rustUnstable;

in

with pkgs;

rustPlatform.buildRustPackage {
  name = "xxx";

  src = ...;

  depsSha256 = "yyy";

  ...
}
```

**Comment by wizeman** [comment]
Having re-read your comment, just to make it clear: `cargo` *really* needs to be built with a nightly version of `rust`, as it will fail to build otherwise.

I don't think we can fix this on our side, you'd have to talk with the `cargo` developers to fix that issue...

**Comment by wizeman** [comment]
Also, assuming you haven't modified any derivation that `rustc` depends on, eventually `hydra.nixos.org` will catch up and Nix will be able to transparently download pre-built `rustc`binaries, so you won't have to build them yourself...

**Comment by Havvy** [comment]
Ah, very well. So there's an upstream issue here. Great. :S

**Comment by wizeman** [comment]
FYI: Once Rust 1.1 is released, Cargo will support the stable version so we'll be able to fix this.
See rust-lang/cargo#1712
