### ISSUE TITLE
Xephyr is broken

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#7971]
When I do:
Xephyr :42 &
I get:
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
(EE) 
Fatal server error:
(EE) Failed to activate core devices.(EE) 

[1]  + 3784 exit 1     Xephyr :42

**Comment by bjornfor** [comment]
Sounds like the same error that caused xpra to be broken for a while (or since ever?). xpra was fixed by some patching/wrapping in the nix expression. But the real cause is deeper within some xorg nix expression I think.

I once tried to figure it out, and AFAICT there is a cyclic build dependency between some xorg modules which is currently solved by wrapping the "further out" deps (like xpra), instead of fixing the initial build cycle in a pure manner. I'm no xorg build expert, so in the end I didn't solve it :-(

**Comment by domenkozar** [comment]
Somewhat related to https://github.com/NixOS/nixpkgs/pull/7316?

**Comment by magnetophon** [comment]
Fixed in e1af50c
Thanks!

**Comment by vcunat** [comment]
@magnetophon: how does that commit relate to this issue?

**Comment by magnetophon** [comment]
@vcunat oh, sorry, I mean: fixed somewhere before that commit.

**Comment by vcunat** [comment]
Aha, I see :-)
