### ISSUE TITLE
libstdc++ fails to build on master

### ISSUE THREAD

**Issue by smgb66** [NixOS/nixpkgs#79761]
**Describe the bug**
When trying to build libstdc++ from nixpkgs master the build fails with the following error messages:

`/nix/store/0n7bssaiibw6zagg9m2p04994rzjab4m-bash-4.4-p23/bin/bash: -c: line 5: unexpected EOF while looking for matching ``'`
`/nix/store/0n7bssaiibw6zagg9m2p04994rzjab4m-bash-4.4-p23/bin/bash: -c: line 6: syntax error: unexpected end of file`
`make: *** [Makefile:1293: all-ash] Error 1`

I have uploaded the full build log to [Gist](https://gist.github.com/smgb66/5e72272f0d3a404c56ef8b4d2f760606).

**To Reproduce**
1. Clone the nixpkgs repository into a folder 
2. Try to build the `libstdcxx5` package from that folder using `nix-build`

**Expected behavior**
The package builds without errors.

**Additional context**
By running git bisect I narrowed the bug down to commit 162a935d3cc. Builds work after checking out the commit right before that.
This issue is unrelated to #41585 which seems to have already been fixed, since it was opened in 2018 and the last successful build was in 2019.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.101, NixOS, 19.09.2036.c49da6435f3 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-19.09.2036.c49da6435f3, nixos-unstable-20.03pre211015.8539d5f48f9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libstdcxx5
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
cc @abbradar

**Comment by clkamp** [comment]
I tracked this down to the fact, that in the mentioned commit, the libc-cflags file became multi line and somehow giving the resulting multi line flag to make breaks.

There are two ways how this could be fixed, either directly here, by adding a tr after the cut`ing of the libc-cflags file or in the cc-wrapper by doing the same there. 

I would prefer to do the second one and will prepare a PR for this to staging (because is leads to nearly everything being rebuild).

cc @Ericson2314 @orivej
