### ISSUE TITLE
Package request: Cozette font

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#80267]
**Project description**
A bitmap font optimized for coziness.

**Metadata**

* homepage URL: https://github.com/slavfox/Cozette
* source URL: https://github.com/slavfox/Cozette
* license: MIT
* platforms: Linux

**Comment by rnhmjoj** [comment]
If you have never contributed to nixpkgs, a font package would be a good start.
This one specifically provides all the formats you may ever need, so no conversion/build is needed at all: just copying files.
If you want to try I can help you, otherwise you'll probably have to wait until I'm done with issue #75160.
