### ISSUE TITLE
Plasma-desktop/latte-dock Error loading OMI file

### ISSUE THREAD

**Issue by mjlbach** [NixOS/nixpkgs#80653]
**Describe the bug**
On latest nixpkgs-unstable, kde-plasma and latte-dock fail to start. Instead, each widget displays:

```
Error loading OMI file: file///nix/store/****latte-dock-0.9.7/share/plasma/plamoids/org.kde.latte.containment/contents/ui.qml:1627:9: Type applet AppletItem unavailable.
```

**To Reproduce**
1. add nixpkgs-unstable channel
2. sddm/kde enable
3. add latte-dock

This is fixed by running latte-dock replace which makes me think it might be related to the KDE startup issue in  #79707 and issue #80550 
**Screenshots**
**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.20, NixOS, 20.09pre213994.e2b4abe3c8f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre213994.e2b4abe3c8f"`
 - channels(mjlbach): `"home-manager, nixpkgs-20.09pre213040.f77e057cda6"`
 - nixpkgs: `/home/mjlbach/.nix-defexpr/channels/nixpkgs`

```

**Comment by mjlbach** [comment]
Fixed on master

**Comment by duckfullstop** [comment]
This doesn't appear to have been fixed by any codebase changes; I've been stuck with an identically broken installation for the past few weeks on nixos-unstable. Interestingly, however, running ``--replace`` does not fix my installation, so I'm not 100% sure this is the exact same bug, but it seems a strange coincidence considering ye ol' google provides literally only this issue when searching for an appletItem error.

Are you sure you didn't do something external to a `switch --upgrade` to fix this?

**Comment by duckfullstop** [comment]
Disregard, I am monumentally stupid and it only occurred to me after posting: my `latte-dock` was installed in my user environment, so `nix-env -u` pulled the latest version which, indeed, works fine. 🙃

Check your user environments, y'all.

**Comment by cesarvspr** [comment]
latte-dock -cc worked for me 

This clears the cache folder.

**Comment by IgorRubinovich** [comment]
It's `latte-dock --cc` (double dash)
