### ISSUE TITLE
neovim fails to build in latest nixos-unstable

### ISSUE THREAD

**Issue by mdedetrich** [NixOS/nixpkgs#80750]
**Describe the bug**
`neovim` is failing to build in latest nixos-unstable due to a lua-rocks dependency

**To Reproduce**
1.Install neovim in the nixos-unstable channel

**Expected behavior**
Builds properly

**Additional context**
Build log is here https://gist.github.com/mdedetrich/83badb15f5ca142e16ccdb560d34e602

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.0, NixOS, 20.03pre211190.a21c2fa3ea2 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.2`
 - channels(root): `"nixos-20.09pre213994.e2b4abe3c8f, nixpkgs-unstable-20.09pre214209.f098b0dd2cd"`
 - channels(mdedetrich): `"nixpkgs-20.09pre214168.686274ea62c"`
 - nixpkgs: `/home/mdedetrich/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: neovim
# a list of nixos modules affected by the problem
```

**Comment by primeos** [comment]
Thanks for the report, but this should already be fixed on master, see https://github.com/NixOS/nixpkgs/issues/80704 and https://github.com/NixOS/nixpkgs/issues/79870.

**Comment by alexameen** [comment]
Mine is still failing on master. FWIW.

**Comment by primeos** [comment]
@alexameen master or nixos-unstable (the latter only works since https://hydra.nixos.org/build/113377581)? Anyway, I just tested it on nixos-unstable and it does now build on my NixOS setup. If it still fails on yours that's probably due to something else (overlays, overrides, etc.). Feel free to open a new issue with additional information if it's still a problem.
