### ISSUE TITLE
Rename doc → docs

### ISSUE THREAD

**Issue by alexherbo2** [NixOS/nixpkgs#81656]
The rationale is that `docs` is much more common than `doc`.

**Comment by alexherbo2** [comment]
I opened as a bug, but it is not a bug – I cannot remove the label.

**Comment by Ma27** [comment]
Not sure if that's worth the effort. People can access our `doc` dirs via `<nixpkgs/doc>` or `<nixpkgs/nixos/doc>` and renaming those may cause unnecessary breakage.

**Comment by Ekleog** [comment]
Agreeing with @Ma27 here -- this would cause lots of breakage, for little benefit. Were someone to have easily verifiable statistics that show that 99.99% of the projects use `docs` instead of `doc` maybe it would make sense to consider the idea, but as things are I can't see the pro/con ratio as being in favor of such a change.
