### ISSUE TITLE
ZFS calls rm with wrong path

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#8171]
Seen while booting the NixOS installer:
```
machine# [    7.569436] systemd[513]: Failed at step EXEC spawning /nix/store/70cfx8gbw3hb6fix1x8gynn71dqinli5-zfs-user-0.6.4.1/bin/rm: No such file or directory
```

**Comment by edolstra** [comment]
@wizeman

**Comment by wizeman** [comment]
Ok, this seems to come from `zfs-share.service`. This file, which is included in the ZFS sources, contains the following:
```
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=-@bindir@/rm /etc/dfs/sharetab
ExecStart=@sbindir@/zfs share -a
```

I guess the problem is that `@bindir@` is pointing to ZFS's bin directory.
I really have to leave my computer right now, but I will try to fix this in a few hours when I come back.
