### ISSUE TITLE
R arrow package

### ISSUE THREAD

**Issue by jtrakk** [NixOS/nixpkgs#81761]
**Project description**

The Apache Arrow serialization library for R.

**Metadata**

* homepage URL: https://arrow.apache.org/docs/r/
* source URL: https://github.com/apache/arrow
* license: apache2
* platforms: unix, linux, darwin, ...

There is already `rPackages.arrow` but it's missing runtime libraries. Attempting to use it gives an error:

```
> arrow::read_feather('my.feather')
Error in io___MemoryMappedFile__Open(path, mode) : 
  Cannot call io___MemoryMappedFile__Open(). Please use arrow::install_arrow() to install required runtime libraries. 
```

**Comment by Zhen-hao** [comment]
I encountered the same issue. I think the first thing to check is how the R library finds the C++ library.
I asked for help on the arrow project: https://github.com/apache/arrow/issues/7034

**Comment by Zhen-hao** [comment]
reading https://arrow.apache.org/docs/r/articles/install.html#how-dependencies-are-resolved, I don't think it is possible to build `rPackages.arrow` in such a way that it always finds the `arrow-cpp` installation. 

I have a workaround now. https://gist.github.com/Zhen-hao/8bdc7b2afe10f270f3f7e280a89c5ef0
if the arrow library is not working in the shell, just manually install the same version one more time.

**Comment by TikhonJelvis** [comment]
Is anyone actively looking at this? If not, I can try putting together a PR fixing this—I got an override working on my local machine on both NixOS and macOS.

**Comment by jtrakk** [comment]
Still have this issue on NixOS unstable.

**Comment by TikhonJelvis** [comment]
Okay. I am trying to fix this.

Last time I tried, I was held up because the R library was at version 1.0.0, but the Arrow C++ library in Nixpkgs was 2.0.0. To fix that, I opened #108268 so that the R Arrow package was brought up to 2.0.0. I had to focus on other things after that got merged; in the meantime, the Arrow C++ library in Nixpkgs got upgraded to 3.0.0.

I had a fix working locally based on @Zhen-hao's examples, but it fails to build now. I'm pretty sure it's because of the 2.0.0 vs 3.0.0 version mismatch.

What's the best way to proceed? Should I do another CRAN/etc version bump? Is there some lighter-weight way to only upgrade the R Arrow package? Is there a way to point the R package at an older version of the Arrow C++ library? Going forwards, if the C++ library has breaking releases relatively often, would we need to bump the entire R package set often to keep them in sync? Does bumping the R package set more often create an undue maintenance or testing burden?

Would love some advice from somebody more experienced with Nixpkgs and the R package system in particular. @peti or @SuperSandro2000?

**Comment by SuperSandro2000** [comment]
I have no idea about R.

**Comment by jtrakk** [comment]
@TikhonJelvis  I'm guessing this GitHub issue has a small viewership; maybe some people who know the answer follow the Discourse forum.

**Comment by peti** [comment]
`rPackages.arrow` should work fine in `master` starting after 64b5504939f37e608b3e894287abf9890a6fcc79 and c4d8bd324f2733d8706e932052bb3f2e50d64ed4.

To answer @TikhonJelvis's questions:

> What's the best way to proceed? Should I do another CRAN/etc version bump? Is there some lighter-weight way to only upgrade the R Arrow package?

I have updated only the `arrow` package now because I didn't have much time and I just wanted to get results as quickly as possible, but updating the package set in its entirety would be the better solution here, even if it is more effort. Our package set is pretty old already. Anyhow, it *is* possible to cherry-pick certain updates for R if a complete update is undesirable for some reason.

> Is there a way to point the R package at an older version of the Arrow C++ library?

If we would have an older version around, then it would be possible to point the R build to it by adding an appropriate override: https://github.com/NixOS/nixpkgs/blob/c4d8bd324f2733d8706e932052bb3f2e50d64ed4/pkgs/development/r-modules/default.nix#L234

> Going forwards, if the C++ library has breaking releases relatively often, would we need to bump the entire R package set often to keep them in sync? 

That would be the best solution, IMHO. Updating `arrow` comes with the risk that dependencies or `arrow` become outdated and we end up losing features or performance or maybe even introducing bugs. It's not a major risk, I suppose, but still updating the package set would be preferable. The maintenance effort involved in such an update is moderate, IMHO.
