### ISSUE TITLE
buildRustPackage fetch-builder.sh fails if package doesn't contain Cargo.lock

### ISSUE THREAD

**Issue by unjordy** [NixOS/nixpkgs#8186]
The buildRustPackage builder script fetch-builder.sh fails with `rm: cannot remove 'Cargo.lock': No such file or directory` if the package it's building doesn't include a Cargo.lock file. According to the Cargo documentation, this file is usually included in source trees for executables, but not for libraries. It looks like right now we depend on rewriting the Cargo.lock file for deterministic builds. As a workaround when Cargo.lock is absent, would it make sense to have the builder run `cargo update` against the local rustRegistry and use the generated Cargo.lock file in the build?

**Comment by wizeman** [comment]
@unjordy That would mean that whenever `rustRegistry` is updated, we would also have to change all the `depsSha256` hashes of all the packages that don't have a `Cargo.lock`, because `cargo update` may now decide to use a newer version of a library.

Can you give an example of a program that doesn't have `Cargo.lock`? It may be better to convince upstream to include `Cargo.lock` than for us to support programs that don't have it (unless there is a good reason for it).

Note that it shouldn't be necessary for libraries to have `Cargo.lock` because neither we nor `cargo` currently support building programs that link to libraries built in a separate package / derivation.

Instead, libraries are always built from scratch when we build the program that includes the library. In this case, the `Cargo.lock` of the program includes the locked versions of the libraries that the program uses.

**Comment by wizeman** [comment]
Regardless of what I said, there was supposed to be a better error message than what you mentioned... so at least, we have to fix that.

**Comment by wizeman** [comment]
Ok, I just checked that with a recent version of `nixpkgs` (where `fetch-builder.sh` doesn't even exist anymore), there is a more user-friendly error message shown when a package doesn't include `Cargo.lock` (explaining why it is needed):
```
Using rust registry from /nix/store/2fd4haxsw3j7d1gjbqn6p3x3vq8jp6mg-rustRegistry-2015-05-19-6280837
ERROR: The Cargo.lock file doesn't exist

Cargo.lock is needed to make sure that depsSha256 doesn't change
when the registry is updated.
```

**Comment by wizeman** [comment]
BTW, if upstream refuses to include `Cargo.lock`, we can always generate the file ourselves and add it to `nixpkgs`, and then copy it into the output of `src` attribute.

Or even simpler, we could just create a patch that simply creates `Cargo.lock`, and then just apply it to the sources like any other patch. However, this may need further changes to `buildRustPackage`, to make sure that it applies all patches before downloading dependencies (probably we just need to add `patchPhase` to the list of phases in `fetchcargo.nix`).

**Comment by unjordy** [comment]
@wizeman Excellent point about `depssha256` potentially changing with a `cargo update`, and I hadn't realized Cargo builds don't allow linking in dependencies in external packages. As for crates that exclude a `Cargo.lock` (and now disregarding most libraries for the reason you gave), I can come up with two legitimate instances where `Cargo.lock` would be excluded.

The first instance is bare metal development projects like [zinc.rs](https://github.com/hackndev/zinc), which use Cargo to pull in dependencies and a separate build system to compile a binary. But the bare metal projects are a poor fit for packaging of any kind right now.

The second instance is a library which exposes a C ABI interface and outputs a library that can be used by gcc or clang. In this case, it's correct for them to exclude `Cargo.lock` and for us to include the package in nixpkgs with the C ABI libraries as the build output. I was actually looking at a popular Rust library that does this last week, but I'm drawing a blank on which one it was right now. This will certainly be a popular use case in the future, but it's a bit of an edge case at the moment. If someone runs into `Cargo.lock` issues packaging one of these libraries for nixpkgs, your notes about patching `Cargo.lock` into the sources should be very useful.

For reference (and since this may come in handy for Rust devenvs), what is the procedure to run `cargo update` against the system rustRegistry instead of crates.io?

**Comment by wizeman** [comment]
@unjordy Good point about the Rust library exposing a C ABI, I hadn't thought of that use case. I'm hoping that people who create Nix derivations could patch in a `Cargo.lock` themselves at the moment they create the derivation, to make sure that we download dependencies deterministically, but I don't know if `cargo` would use it or if it would just ignore it...

To answer your question, I think that currently there is no easy way to run `cargo update` against the system `rustRegistry` instead of `crates.io`. It would be great if there was some kind of script we could run to make this easy (some kind of `nix-prefetch-cargo` maybe?).

What I currently do instead (for my personal projects) is the following:
1. I run `cargo update` against `crates.io`
2. I update `rustRegistry` locally (and soon afterwards I push it to `nixpkgs`)

As long as I update `rustRegistry` *after* I run `cargo update`, then the system `rustRegistry` will always have information about the package versions in my `Cargo.lock` files...
I know this is not ideal, but step 2 can be automated and at least, it works for my limited use cases. However, it would be great if we could improve it...

**Comment by unjordy** [comment]
@wizeman Hmm, `cargo fetch` should definitely pick up on a patched in `Cargo.lock`. But the `cargo update` process definitely isn't ideal at the moment. Better support for repositories that aren't crates.io would be great both for us and for Rust in the enterprise; I might be submitting some pull requests to Cargo when I get the chance if there are no (perhaps undocumented) existing options for our Cargo use case.

**Comment by sjmackenzie** [comment]
Okay, so I forked `capnpc-rust` to `fractalide/capnpc-rust`, added the `Cargo.lock` and I still get the error. (https://github.com/fractalide/capnpc-rust/blob/master/Cargo.lock). What gives?

**Comment by wizeman** [comment]
@sjmackenzie Can you show me how your derivation looks like, so that I can try to reproduce?

I'm wondering if you simply forgot to point your derivation to your new project... otherwise it would be weird that you saw the error "`Cargo.lock` is missing" if the file is really there...

**Comment by sjmackenzie** [comment]
@wizeman sure!

this is the bit I include it: https://github.com/fractalide/nixos-infrastructure/blob/master/profiles/development.nix#L8

this is expression: https://github.com/fractalide/nixos-infrastructure/blob/master/pkgs/capnpc-rust.nix

Much appreciated!

**Comment by sjmackenzie** [comment]
@wizeman (comment updated)

**Comment by wizeman** [comment]
@sjmackenzie You are getting the error because your derivation is pointing to a git revision that does not contain `Cargo.lock`. You should update the `rev` attribute in the `fetchFromGitHub` derivation from `727ab28fb9f335a16a383e54f3acbbef0cea5b15` to `55464a598d1a2e9efc10dd6eacc21f9fb153c9c7`, the latter being the commit where you added `Cargo.lock` to your repository.

Also, this is unrelated but unless you are having problems, you should be using `rustUnstable` in your derivation instead of `rustUnstableCargoPlatform`. The latter should only be used to build cargo itself (as the comment in `all-packages.nix` alludes to, but not very clearly).

**Comment by sjmackenzie** [comment]
I feel like kicking myself! :-) Thanks so much for this, along with the `rustUnstable` information.

**Comment by sjmackenzie** [comment]
```
unpacking sources
unpacking source archive /nix/store/r4rxqx4x0w8z4vbwgbqbcbsp03s45m3r-capnpc-rust-55464a598d1a2e9efc10dd6eacc21f9fb153c9c7-src
source root is capnpc-rust-55464a598d1a2e9efc10dd6eacc21f9fb153c9c7-src
installing
Fetching /tmp/nix-build-capnpc-rust-2015-12-07-fetch.drv-0/capnpc-rust-55464a598d1a2e9efc10dd6eacc21f9fb153c9c7-src to /nix/store/np6lscwhvrzpq1i85r32hd9121vgi717-capnpc-rust-2015-12-07-fetch
Using rust registry from /nix/store/10xg2m3cqg68rdx9g4ms5gq5rbyxxj92-rustRegistry-2015-11-01-a0534d1
    Updating registry `file:///nix/store/10xg2m3cqg68rdx9g4ms5gq5rbyxxj92-rustRegistry-2015-11-01-a0534d1`
no matching package named `capnp` found (required by `capnpc`)
location searched: registry file:///nix/store/10xg2m3cqg68rdx9g4ms5gq5rbyxxj92-rustRegistry-2015-11-01-a0534d1
version required: = 0.5.2
versions found: 0.5.0, 0.4.4, 0.4.3, ...
```
So the next step is to bump the rust registry right? This is done by editing this line https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/rust-packages.nix#L10 (+ adjusting the sha256) then pushing it soon afterwards? correct?

**Comment by wizeman** [comment]
@sjmackenzie That's correct. You can also submit that as a pull request, so that everyone can benefit from access to updated packages :-)

**Comment by wizeman** [comment]
@sjmackenzie Also, I forgot to mention you also need to update the `rev` attribute to point to a commit from that date (today's date, preferably).

**Comment by sjmackenzie** [comment]
Ah, sorry I was absent minded, I meant `rev` when I said `sha256`. Thanks for this work, really makes life much easier for us :-)

**Comment by sjmackenzie** [comment]
Ah I see you (@wizeman) bumped the rust registry. Thanks! I didn't push my changes because I'm still getting this error:

```
 $ nix-build
these derivations will be built:
  /nix/store/irh1bzs62nl1945r2s0qhincqxxy0v0n-capnpc-rust-2015-12-07-fetch.drv
  /nix/store/qb82bk1afwk4nw246b8al9wqz8960gjm-capnpc-rust-2015-12-07.drv
building path(s) ‘/nix/store/np6lscwhvrzpq1i85r32hd9121vgi717-capnpc-rust-2015-12-07-fetch’
unpacking sources
unpacking source archive /nix/store/ajg9bss9rnh8xip6rngih5xlvs1h5ph8-capnpc-rust-1123a4f5de32f0300f1a6b8014b6c3525e170fa9-src
source root is capnpc-rust-1123a4f5de32f0300f1a6b8014b6c3525e170fa9-src
installing
Fetching /tmp/nix-build-capnpc-rust-2015-12-07-fetch.drv-0/capnpc-rust-1123a4f5de32f0300f1a6b8014b6c3525e170fa9-src to /nix/store/np6lscwhvrzpq1i85r32hd9121vgi717-capnpc-rust-2015-12-07-fetch
Using rust registry from /nix/store/10xg2m3cqg68rdx9g4ms5gq5rbyxxj92-rustRegistry-2015-11-01-a0534d1
    Updating registry `file:///nix/store/10xg2m3cqg68rdx9g4ms5gq5rbyxxj92-rustRegistry-2015-11-01-a0534d1`
no matching package named `capnp` found (required by `capnpc`)
location searched: registry file:///nix/store/10xg2m3cqg68rdx9g4ms5gq5rbyxxj92-rustRegistry-2015-11-01-a0534d1
version required: = 0.5.3
versions found: 0.5.0, 0.4.4, 0.4.3, ...
/nix/store/h84kc62s87mknjrln5rd6s332zfxfrk5-stdenv/setup: line 124: showBuildStats: unbound variable
builder for ‘/nix/store/irh1bzs62nl1945r2s0qhincqxxy0v0n-capnpc-rust-2015-12-07-fetch.drv’ failed with exit code 101
cannot build derivation ‘/nix/store/qb82bk1afwk4nw246b8al9wqz8960gjm-capnpc-rust-2015-12-07.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/qb82bk1afwk4nw246b8al9wqz8960gjm-capnpc-rust-2015-12-07.drv’ failed

```

If the registry is bumped why does it print this line: `Using rust registry from /nix/store/10xg2m3cqg68rdx9g4ms5gq5rbyxxj92-rustRegistry-2015-11-01...`?

**Comment by sjmackenzie** [comment]
I managed to create a `buildRustPackage` against an executable (sokoban-rs) which has a `Cargo.lock`, but it would seem anything that is a rust library doesn't build and thus cannot be packaged due to the above error. Is this expected behaviour?

**Comment by sjmackenzie** [comment]
Okay we've run smack into @unjordy second use case. The idea is we'll have many rust implemented Flow-based Programming C ABI compatible dynamic libs, they will be composed together at runtime to form a graph of components forming an application (or subnet). The FBP virtual machine (fvm) is the executable and it'll dynamically include all of these dependencies. We'd like to get these C ABI components by whatever means, most likely it'll be a Named Data Network. Hence it would be superb if we could write `buildRustPackage` expressions to package up these fbp components. The second instance of this class of error we're experiencing is `capnpc-rust` which is a C ABI library that plugs into `capnp`. This generates a rust src file from https://capnproto.org/language.html files. What needs to be done to get `buildRustPackage` to support packaging rust libraries?

**Comment by wizeman** [comment]
@sjmackenzie In the case of Rust libraries that need to be a build product by themselves, because they expose a C-compatible ABI and are meant to be used by a non-Rust program, this currently presents a bit of a problem because Cargo recommends **not** to include a `Cargo.lock`, but we need it in order to provide a reproducible build.

My suggestion is that you create a `Cargo.lock` file yourself, add it to the same directory as the Nix file containing your `buildRustPackage` expression, and then include something like this in your `buildRustPackage` derivation:

```nix
  buildRustPackage {
#   (...)
    postPatch = "cp ${./Cargo.lock} $sourceRoot/";
#   (...)
  }
```

Please note that I haven't tested this so I might have made a mistake.

Also, a few more details: note that the above won't work if you put the `cp` command in the `prePatch` hook because `buildRustPackage` overrides it for other purposes. You could use instead the `patchPhase` hook, but I don't recommend it because if you later add a patch to the `patches` attribute, it won't do anything (because you've overriden the `patchPhase`).

**Comment by sjmackenzie** [comment]
Thanks!

Given that every component is a library would it not be safe just to do this:

https://github.com/sjmackenzie/components/commit/9a57471d679f9cb670d4d5b85055d559c3e24627

(Basically I've copied out the Rust specific stuff into a separate repo so that we can quickly bump the `rustRegistry` if we need to. (and do things like the above commit))

**Comment by wizeman** [comment]
@sjmackenzie No, because then if you update `rustRegistry`, then most Rust packages that don't have `Cargo.lock` will likely break because `depsSha256` will likely have changed (because `cargo fetch` might have downloaded an updated version of a library dependency).

**Comment by sjmackenzie** [comment]
Cheers! Understood. I'll look into your solution. Appreciated.

**Comment by sjmackenzie** [comment]
Also it would seem if there are no `[dependencies]` in the `Cargo.toml` file the script falls over.
