### ISSUE TITLE
Explicit version attributes

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#8214]
Tons of packages already do something along the lines of

``` nix
zomgPackage rec {
  version = "1.4.5";
  name = "foo-${version}';
}
```

Unfortunately, `nix-env` and friends are jumping through hoops with poor heuristics for what makes a package name and what's a version. Can we just make `version` into an optional field that `nix-env` will pay attention to if present? Then we can slowly start transitioning all packages to the new system and eventually stop telling people not to put hyphens in their versions.

**Comment by lethalman** [comment]
There's no "poor heuristics", it's well defined what's the version in a derivation name. I don't see much benefits from this.

**Comment by vcunat** [comment]
Note that nix-env can't see any attributes from the expression that generated the store path. It just sees that directory in nix store.

**Comment by edolstra** [comment]
No, `nix-env` can see derivation attributes just fine, except when you install a package via `nix-env -i /nix/store/...`.

**Comment by peti** [comment]
The definition says:

> The version part starts after the first dash not following [sic] by a  letter.

That's a reasonable definition, IMHO, and we have `builtins.parseDrvName` to do the parsing within Nix, so it's easy to work with that definition, too.

Adding an explicit `version` attribute only makes sense if that attribute allowed us to specify name/version pairs that would be illegal otherwise, because if it doesn't then I don't see what we gain from having it. Violating the definition cited above, however, doesn't seem like such a good idea. What is the point? What do we gain? What problem does this solve?

Besides, having an explicit `version` attribute that's *repeated* inside of `name` seems dubious, too.

**Comment by Profpatsch** [comment]
(triage) Agree that it’s reasonably well defined, but does it make sense to change that at the current state?

**Comment by Profpatsch** [comment]
(triage) This seems stuck on various opinions, does it make sense to keep this open if nobody wants to implement a proof-of-concept?
