### ISSUE TITLE
vscode 1.43 breaks default extensions

### ISSUE THREAD

**Issue by Zhen-hao** [NixOS/nixpkgs#83288]
tested via home-manager.
my channels are as follows.
```
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

This won't install the extensions:

```
  programs.vscode = {
    enable = true;
    extensions = with pkgs.vscode-extensions; [
      bbenoist.Nix
      scalameta.metals
    ] 
  };

```

This will install the extensions:
```
  programs.vscode = {
    enable = true;
    extensions = with pkgs.vscode-extensions; [
    ] ++ pkgs.vscode-utils.extensionsFromVscodeMarketplace [
        {
          name = "Nix";
          publisher = "bbenoist";
          version = "1.0.1";
          sha256 = "0zd0n9f5z1f0ckzfjr38xw2zzmcxg1gjrava7yahg5cvdcw6l35b";
        }
        {
          name = "metals";
          publisher = "scalameta";
          version = "1.8.4";
          sha256 = "0j64hpbll0mqspvikgg54lh279z1xmvdmmxjy0cf20az8cz19fwf";
        }
        {
          name = "scala";
          publisher = "scala-lang";
          version = "0.3.9";
          sha256 = "0l6zrpp2klqdym977zygmbzf0478lbqmivcxa2xmqyi34c9vwli7";
        }
      ];
  };
```

**Comment by ixxie** [comment]
I experienced the same issue, and used the same workaround, except now even the workaround is not working.

It raises errors such as:

```
error: opening directory '/nix/store/51xyzwi3b7s4nwrsawnqvbz9yaa94bhm-vscode-extension-brettm12345-nixfmt-vscode-0.0.1/share/vscode/extensions': No such file or directory
(use '--show-trace' to show detailed location information)
```

**Comment by wmertens** [comment]
I must have accidentally assigned this, I don't know anything about the VSCode wrapper :( I unassigned myself.

I found https://github.com/nix-community/home-manager/issues/1260, which seems likely to be the same issue. Since that place is for home-manager, it seems likely to need solving there, unless the [vscode-with-extensions package here](https://github.com/NixOS/nixpkgs/blob/a8040c700ab2c08b2437d65dac7dbabc77f6b014/pkgs/applications/editors/vscode/with-extensions.nix#L72-L74) no longer works with the [configuration setup in home-manager](https://github.com/nix-community/home-manager/blob/7e5fee4268f53be8758598b7634dff8b3ad8a22b/modules/programs/vscode.nix#L120-L143).

**Comment by ixxie** [comment]
In my system at least, the latest builds work, so maybe we can close this issue?

**Comment by Zhen-hao** [comment]
I think we can close it since it is outdated. new versions might have resolved it already.
