### ISSUE TITLE
pango-querymodules > '/etc/pango/pango.modules'

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#83298]
**Describe the bug**
While trying to install a gog program via `steam-run ./gog_hyper_light_drifter_2.8.0.9.sh`, I got:
```
(mojosetup:7374): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(mojosetup:7374): Gtk-WARNING **: Could not find the icon 'system-software-installer'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(mojosetup:7374): Pango-CRITICAL **: No modules found:
No builtin or dynamically loaded modules were found.
PangoFc will not work correctly.
This probably means there was an error in the creation of:
  '/etc/pango/pango.modules'
You should create this file by running:
  pango-querymodules > '/etc/pango/pango.modules'

(mojosetup:7374): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='latin'

(mojosetup:7374): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='common'

```

The installer runs fine but shows squares instead of proper characters.

This is on nixos-unstable. I tried to nix-locate a pango-querymodules zihtout success. I might look into it later but post his in case someone already has a solution.

**Comment by jtojnar** [comment]
https://github.com/GNOME/pango/commit/fa6dfc688c293fa02c36ee89ac5611fd5e0131a5

**Comment by teto** [comment]
thus in absence of this pango-querymodules, how can I work around the error ?

**Comment by jtojnar** [comment]
It must be using a pango shipped with the game because pango in Nixpkgs does not even have the code for loading the modules: https://github.com/GNOME/pango/commit/7d30b3f91958a3ff45ee2b8e5de2b6186cadfb72 So hopefully, it would also contain `pango-querymodules` or something.

I would try extracting the archive and looking how pango is linked (and trying to replace it with system one if it is dynamically linked, hoping ABI did not change).

But I doubt it will work on any other distro without work.

**Comment by jtojnar** [comment]
Here I found a mention of this issue in IRC logs: https://logs.nix.samueldr.com/nixos/2018-02-03#884288;

**Comment by teto** [comment]
thanks ! dont have time to test now but sounds promising !
