### ISSUE TITLE
Find a solution to distribute `mongodb` despite its license restrictions

### ISSUE THREAD

**Issue by Ma27** [NixOS/nixpkgs#83433]
In #40082, `mongodb` has been updated to its latest versions (3.4.24, 3.6.13, 4.0.12). Those are relicensed under MongoDB's [`sspl`](https://www.mongodb.com/licensing/server-side-public-license/faq)-license.

This license is not OSI-approved, but still allows redistribution and modification. However there are some restrictions e.g. for SaaS providers (see section 13 of the license). Because of that, it's currently marked as unfree in our `license`-attrset.

However, this has the downside that everyone has to compile their own `mongodb` which takes some time and resources since Hydra doesn't build unfree software. In [`#nixos-dev`](https://logs.nix.samueldr.com/nixos-dev/2020-03-26#3227422;) it has been suggested to update the licensing system to add a third category (e.g. `redistributable`) for packages that are actually unfree, but can be redistributed by Hydra (see also #47237 for that).

cc @worldofpeace @Drakonis @aanderse

**Comment by WithoutCaps** [comment]
Temp workaround:
have docker autostart MongoDB container

**Comment by Ma27** [comment]
@grahamc @worldofpeace just to avoid some misunderstandings: the actual blocker was the backport PR (due it's security implications) and the license thing is something to be discussed, right? So, this is something that isn't blocking the release anymore and we could remove the blocker label now, right? (as far as I can tell after re-watching our discussion from last Friday).

**Comment by worldofpeace** [comment]
> @grahamc @worldofpeace just to avoid some misunderstandings: the actual blocker was the backport PR (due it's security implications) and the license thing is something to be discussed, right? So, this is something that isn't blocking the release anymore and we could remove the blocker label now, right? (as far as I can tell after re-watching our discussion from last Friday).

Yep. I believe that was it.

**Comment by JamieMagee** [comment]
I am a little unclear on the licensing of `mongodb` 3.4.24. I downloaded the sources from https://fastdl.mongodb.org/src/mongodb-src-r3.4.24.tar.gz, and looking at the `README` it states:

>LICENSE
>
> Most MongoDB source files (src/mongo folder and below) are made available
> under the terms of the GNU Affero General Public License (GNU AGPLv3). See
> individual files for details.

compared to 3.6.13:

>LICENSE
>
> MongoDB is free and open-source. Versions released prior to October 16,
> 2018 are published under the AGPL. All versions released after October
> 16, 2018, including patch fixes for prior versions, are published under
> the Server Side Public License (SSPL) v1. See individual files for
> details.

These seem to contradict each other?

Also, when looking at individual files, the license header comment states AGPLv3 in version 3.4.24 and SSPLv1 in version 3.6.13. Does the statement "See individual files for details." give more weight to the license in each individual file?

**Comment by Ma27** [comment]
Apparently this has been "fixed" in https://github.com/mongodb/mongo/commit/a66a5578d5b006cef85b16eac05c96b58c877ebe.

To quote https://www.mongodb.com/licensing/server-side-public-license/faq:

> All versions of MongoDB Community Server released prior to October 16, 2018 will continue to be licensed under the Free Software Foundation's GNU AGPL v3.0.

However I realize that this sentence is slightly ambiguous: while I interpreted it as "every release after this date is published under a new license", it seems to refer to release branches (so 3.4 would be free, but 3.6 isn't) though.

@jarjee since you authored that change (and judging from your email you seem to work for mongodb), can you clarify whether 3.4 can be considered free? In that case, the issue could be solved for now I think.

**Comment by jarjee** [comment]
I had to check, but yes, 3.4 is still licensed under AGPL. I'm going off the license bundled with the latest source code and double checked with a coworker.

**Comment by Ma27** [comment]
Updated the license accordingly. Will push this to `release-20.03` as well. I'll leave the ticket open for now since this issue still exists and will become a problem again when MongoDB 3.4 is end of life.

**Comment by ThibaultLemaire** [comment]
Hi, thanks for the work on this guys.

We're using MongoDB 4.2 where I currently work, and we'd like to use nix to manage dev environments and CI pipelines. I understand the issue with this new license, but building from source takes a full hour on my machine, which is less than ideal and will become a real pain for CI.

Can we somehow easily setup our own cache?

**Comment by Ma27** [comment]
@ThibaultLemaire we discussed the issue in a videocall about the 20.03 release and it has been made clear that we don't want to build/distribute packages with an "unfree" license[1].

> Can we somehow easily setup our own cache?

A tutorial (not tried it out though) on how to setup a small binary cache can be found here: https://fmnxl.com/blog/setting-up-nix-binary-cache/

Alternatively, you can also self-host your own [Hydra](https://github.com/nixos/hydra) or use [Cachix](https://cachix.org/).

[1] https://youtu.be/7h-1jeLPHQU?t=1068

**Comment by Ekleog** [comment]
As per @grahamc and @Ma27's comments, this issue is currently, unfortunately, non-actionable.

As such, I am going to close this for now. Changing the policy for hydra to also build some unfree licenses would have to happen [as an RFC](https://github.com/NixOS/rfcs/). If you think hydra should build (some) unfree software, feel free to submit one.

Thank you everyone for your input!

**Comment by domenkozar** [comment]
> We decided Hydra should not build unfree, redistributable software in Hydra at this point, with very few exceptions. The only exception at this point is unfree redistributable firmware.

Can I ask, who is "we" and when was that decision made?

We are leaving behind a lot of users in scientific world, which I would also prefer if everything was OSS, but it's not. Not building such software means we're missing out on an important part of the ecosystem.

I don't understand, who benefits from this?

**Comment by Ma27** [comment]
> Can I ask, who is "we" and when/where was that decision made?

@domenkozar The decision was made at the go/nogo meeting on 20.03. I don't remember the details, but you can view the discussion here: https://youtu.be/7h-1jeLPHQU?t=1064

**Comment by domenkozar** [comment]
This will incentivize unfree packages to always come in binary form to save compilation time, which makes things worse for software freedom, not better. 

Something to think about - as license is about the source.

**Comment by Atemu** [comment]
Why is the SSPL considered unfree?

[It's the AGPL with one extra/modified term](https://webassets.mongodb.com/_com_assets/legal/SSPL-compared-to-AGPL.pdf) which forces a hoster of the licensed software to make their modifications available.

Offering a service is the SaaS equivalent of providing a binary for locally-run software; all this does is bring being offered the software as a service on the same level as being offered the software as a binary.

It's *more* copyleft than the GPL.

The only worrying bit from my non-legal-expert perspective is that it also demands making the source code of *all* other software needed to offer the service available which seems a bit too far reaching but, again, if anything, this is only an expansion of the GPL's infectiousness.

Heck, it should even be GPL compatible since all it does is give the user additional permissions which is explicitly allowed by the GPL. IANAL though.

**Comment by Ekleog** [comment]
What is marked “unfree” does not necessarily match any specific definition of “unfree” (in particular, unfree redistribuable firmware is currently marked “free” so it's on hydra, so this really makes little sense).

That being said, the reason why the SSPL is currently marked “unfree” in nixpkgs is that the OSI, who are legal experts, said it's not open-source ([source](https://opensource.org/node/1099)) — I'm not sure whether the FSF ever took position on that matter, but I wouldn't be surprised if it were declared unfree by them too.

**Comment by Atemu** [comment]
I'm surprised by this aswell but I'm not seeing any legal expertise in that article. Having read the SSPL's (rather small) modification to the AGPL, the article reads like your typical intentionally misleading/borderline factually wrong political garbage honestly.  

No service provider is restricted by the SSPL. They can offer the service as much as they want with any modifications they like as long as they make the source available to their users.  
Claiming this violates the OSD6 is the same as claiming that not being able to distribute a GPL'd binary without offering the source violates it in my eyes.

The purpose of the SSPL actually is not to place these "restrictions" but to make the freedoms already given to MongoDB licensees by the AGPL clearer so that MongoDB doesn't have to sue the violators.    
The AGPL already places the same kind of "restriction" (a stronger one actually); if the SSPL is considered "proprietary", the AGPL would have to be too ...but it's OSI-approved?

The only actual potential violation of their Open Source definition is the requirement would be OSD9 as the SSPL requires a lot of other software to be source-available which even I think is overstepping it but the article doesn't even even mention that. A legal expert should've picked up on that immediately.

This is saddening because I thought the OSI was trustable and fighting for a good cause but this makes me consider otherwise and, given that, I don't think we should base our definition of FOSS on theirs.

To be clear, I don't think the SSPL is a great license (especially because of the potential OSD9 violation) but it's certainly not unfree or anywhere close to proprietary.

**Comment by Ekleog** [comment]
Well, as things are there are AFAIK no legal experts with knowledge of FOSS who have weighed in here, so currently there is nothing better than send your complaints to the OSI I think, and/or submit the SSPL for consideration by another body with more legal knowledge than we have :)

For the record, I don't even find the SSPL [on wikipedia's list of FOSS licenses](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences), which sounds to me like it got approval of none of FSF/OSI/Fedora/Debian. I think that, to make NixOS mark the SSPL as free, it'd at least have to gather approval of one of these boards.

(As a side-note, I personally think that we should stop declaring licenses as free/unfree, and rather have a list of attributes like fsfApproved, osiApproved, etc.; and then instead of allowUnfree have allowLicensePredicate that'd default to something like osiApproved||fsfApproved||debianApproved||fedoraApproved, and that we should have hydra builds for all the redistributable things, so that we can stop having these discussions about which licenses should be “free” or “unfree”; but that is a different matter ^^')

**Comment by mohe2015** [comment]
Yeah I agree if you would assume they OSI etc. have malice intentions (or companies influenced them) you could argue that they declared the licenses as unfree on purpose to prevent their widespread use and acceptance in the open source community which would sooner or later likely either make the cloud providers in their current form obsolete or force them to publish their whole infrastructure's code.

**Comment by zimbatm** [comment]
FYI: unfree packages are available today in the https://nix-community.cachix.org cache. For more context see https://nix-community.org/package-sets/

**Comment by leo60228** [comment]
@zimbatm This seems to have broken? https://hydra.nix-community.org/zkv8wrbiz6r8q4pvs0z95wrw3kaw2y49.narinfo is present, but https://nix-community.cachix.org/zkv8wrbiz6r8q4pvs0z95wrw3kaw2y49.narinfo isn't.

**Comment by kira-bruneau** [comment]
> Why is the SSPL considered unfree?
>
> [It's the AGPL with one extra/modified term](https://webassets.mongodb.com/_com_assets/legal/SSPL-compared-to-AGPL.pdf) which forces a hoster of the licensed software to make their modifications available.

I was just looking into this license and it sounds like scope of what needs to be made source-available is much larger than what the GPL/AGPL require.

Specifically, it sounds like you would also need to publish the source of your NixOS config (not just modifications to `mongodb-ce`). Also, you couldn't have any proprietary software be involved in hosting the service (eg. a proprietary load balancer, backup tool...):

> “Service Source Code” means the Corresponding Source for the Program or the modified version, and the Corresponding Source for all programs that you use to make the Program or modified version available as a service, including, without limitation, management software, user interfaces, application program interfaces, automation software, monitoring software, backup software, storage software and hosting software, all such that a user could run an instance of the service using the Service Source Code you make available.

I was also thinking it was weird this was marked as "unfree" until I realized that (but I'm not a lawyer so 🤷‍♀️).
