### ISSUE TITLE
phototonic: qt plugin xcb / qt wrapping broken

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#83493]
**Describe the bug**
The next (of the many packages), which was broken by the Qt-wrapper-changes:

phototonic does not work, due to the Qt-wrapper-changes:

**To Reproduce**
```
$ phototonic 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Solution**
Check/fix all packages, which were affected by the Qt-wrapper-change.
Otherwise, many more such bugs will linger around... :(

**Comment by doronbehar** [comment]
@rkoe I saw your post [here](https://discourse.nixos.org/t/please-fix-all-packages-which-were-broken-by-the-qt-wrapping-changes/6444). And I just wanted to let you know that the fix for this issue is super simple to fix and I'd like to encourage to take part in fixing it yourself. For example, for phototonic, you can create a PR with this simple patch:

```patch
diff --git i/pkgs/applications/graphics/phototonic/default.nix w/pkgs/applications/graphics/phototonic/default.nix
index 5e7fb5cf7a0..8d7d6f13889 100644
--- i/pkgs/applications/graphics/phototonic/default.nix
+++ w/pkgs/applications/graphics/phototonic/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchFromGitHub, qtbase, qmake, exiv2 }:
+{ stdenv, fetchFromGitHub, qtbase, qmake, wrapQtAppsHook, exiv2 }:
 
 stdenv.mkDerivation rec {
   pname = "phototonic";
@@ -12,7 +12,7 @@ stdenv.mkDerivation rec {
   };
 
   buildInputs = [ qtbase exiv2 ];
-  nativeBuildInputs = [ qmake ];
+  nativeBuildInputs = [ qmake wrapQtAppsHook ];
 
   preConfigure = ''
     sed -i 's;/usr;$$PREFIX/;g' phototonic.pro
```

I tested this one, but it should be fairly easy for you to do it as well. If you need guidance for what commands to run, use:

 - https://nixos.org/nixos/manual/index.html#ch-development
- https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages

You _will_ need to be somewhat familiar with Git & GitHub. I personally have learned with [this free course](https://www.udacity.com/course/version-control-with-git--ud123) back when I was a complete Noob, as everybody were once :).

**Comment by doronbehar** [comment]
It is supposed to be fixed, ever since https://github.com/NixOS/nixpkgs/commit/606a15d9d8d3fb9239396f093ed1b2e196c92376 .
