### ISSUE TITLE
Failing grub1 installer tests block channel update

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#8355]
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.installer.grub1.x86_64-linux

@wkennington, I believe you've committed a change recently that affected grub1? Is that true? Could that be related to this issue?

**Comment by wkennington** [comment]
Yeah, im pretty sure i have a fix for it but I haven't committed it yet.

**Comment by peti** [comment]
Can you please revert the breaking change until you have a fix and are ready to commit it?

**Comment by domenkozar** [comment]
I think @edolstra enabled that test to be part of the blocking suite. We can remove it again until it passes

**Comment by edolstra** [comment]
I actually also broke something in the GRUB 1 test, but that's fixed now (f93d842). Now it's failing again on @wkennington's changes:
```
machine# finalising the installation...
machine# updating GRUB 1 menu...
machine# installing the GRUB 1 boot loader on /dev/sda...
machine# Unrecognized option `--boot-directory=/boot'
machine# Usage: grub-install [OPTION] install_device
```

Note that GRUB 1 is still pretty important because e.g. EC2 deployments require it. So we shouldn't disable the test. It's probably better to revert fd5b273e82cf7e78a94479730cf1f51d3a19c637 and subsequent changes at this point.

**Comment by wkennington** [comment]
This is fixed so grub1 installs and is booting but the installer tests are
overall still failing due to nix-env -I coreutils hitting some poorly
constructed expressions.

**Comment by vcunat** [comment]
The tests seem fine now, e.g. see http://hydra.nixos.org/build/23333477
