### ISSUE TITLE
avldrums is packaged twice

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#83649]
Recently a second version of avldrums got merged:  https://github.com/NixOS/nixpkgs/commit/8a43a2818a826081956ad91426a15cd527bbdf87
We already had https://github.com/NixOS/nixpkgs/commit/82ed6bded2ad2df99a5ceff736949e91e0da217f#diff-0d9cd8012e6bf6f2c0f6a44e1c1b1e50

**Comment by veprbl** [comment]
cc @orivej

**Comment by FRidh** [comment]
How many of these kind of plugins do we have? Does it make sense to put them in a package set?

**Comment by magnetophon** [comment]
@FRidh 
What do you mean by these kind of plugins?
LV2 in general? Might make sense. Not sure what the advantages and disadvantages are.
avldrums?  There is only one, but it's packaged twice. (just in case you missed that). :)

**Comment by FRidh** [comment]
Yes, lv2 in general. We should do this
```
pkgs/top-level/all-packages.nix:  avldrums-lv2 = callPackage ../applications/audio/avldrums-lv2 { };
pkgs/top-level/all-packages.nix:  rkrlv2 = callPackage ../applications/audio/rkrlv2 {};
pkgs/top-level/all-packages.nix:  sisco.lv2 = callPackage ../applications/audio/sisco.lv2 { };
pkgs/top-level/all-packages.nix:  lv2 = callPackage ../development/libraries/audio/lv2 { };
pkgs/top-level/all-packages.nix:  ams-lv2 = callPackage ../applications/audio/ams-lv2 { };
pkgs/top-level/all-packages.nix:  eteroj.lv2 = libsForQt5.callPackage ../applications/audio/eteroj.lv2 { };
pkgs/top-level/all-packages.nix:  gxmatcheq-lv2 = callPackage ../applications/audio/gxmatcheq-lv2 { };
pkgs/top-level/all-packages.nix:  gxplugins-lv2 = callPackage ../applications/audio/gxplugins-lv2 { };
pkgs/top-level/all-packages.nix:  ir.lv2 = callPackage ../applications/audio/ir.lv2 { };
pkgs/top-level/all-packages.nix:  lv2bm = callPackage ../applications/audio/lv2bm { };
pkgs/top-level/all-packages.nix:  mda_lv2 = callPackage ../applications/audio/mda-lv2 { };
pkgs/top-level/all-packages.nix:  metersLv2 = callPackage ../applications/audio/meters_lv2 { };
pkgs/top-level/all-packages.nix:  swh_lv2 = callPackage ../applications/audio/swh-lv2 { };
pkgs/top-level/all-packages.nix:  faust2lv2 = callPackage ../applications/audio/faust/faust2lv2.nix { };
```

**Comment by magnetophon** [comment]
@FRidh So by package set you mean just move them next to each other in all-packages?

Not all of the above are plugins:
lv2: the library
lv2bm: an lv2 benchmarker
faust2lv2: a compiler to make lv2s with

There are also more lv2 plugins in nixpkgs.

**Comment by orivej** [comment]
Unfortunately x42 stuff has two names, sometimes distantly related (x42-autotune is aka fat1.lv2). It seems that x42 names are better because they are more recognizable (as a part of x42-plugins.com), they are used in URLs (https://x42-plugins.com/x42/x42-avldrums) and as the names of packages (https://x42-plugins.com/x42/linux/).

---

It would be useful to be able to find all packaged lv2 plugins at a glance. However, since some lv2 plugins come with a standalone application, sometimes it will be difficult to decide whether a package should be classified as a plugin or not. (I would classify x42-plugins as plugins despite their programs in bin/, but qmidiarp as a non-plugin despite its lib/lv2/.)

**Comment by FRidh** [comment]
I propose the same approach as in Python. In case its plugins, put them in the plugin set. In case its only application, put them in top-level, if both, put them in plugins and offer a top-level reference.

**Comment by magnetophon** [comment]
I agree it would be useful to be able to find all packaged lv2 plugins at a glance.

**Comment by orivej** [comment]
OK. I would propose to name the package set audioPlugins and put the definitions in applications/audio/plugins/ . They should comprise DAW plugins (lv2, ladspa, dssi, vst), but not e.g. media player plugins (gst-plugins-good). It does not seem useful to subdivide plugins further, because audio hosts support many types of plugins (Ardour and Carla support lv2, ladspa, vst) and some packages provide many types of plugins at once (zam-plugins has lv2, ladspa, vst; wolf-shaper has lv2, dssi, vst).

**Comment by FRidh** [comment]
I'm not familiar with DAWs but that sounds reasonable! Maybe `dawPlugins` then so its clear its not about `gst` and such?
