### ISSUE TITLE
cannot use fail2ban out of the box

### ISSUE THREAD

**Issue by travisbhartwell** [NixOS/nixpkgs#8437]
Even though fail2ban ships with a ssh jail configured, there is no way to enable it, at least that I could figure out.  I had to add the following to my configuration.nix to get it working:

```Nix
     services.fail2ban.jails.ssh-iptables =
      ''
        enabled  = true
        filter   = sshd
        action   = iptables[name=SSH, port=ssh, protocol=tcp]
        maxretry = 5
      '';
```

The only difference between this and what is shipped is the `enabled = true` line.  It would be awesome to add a configuration option to enable this, perhaps something like `services.fail2ban.jails.ssh-iptables.enable = true` that would add that line for you.

It seems pointless to ship it as is, if what you have to do to use a configuration for ssh is to repeat what is already being put in the jails.conf file.

**Comment by coreyoconnor** [comment]
There is a shorter method to enable the jail. This is definitely non-obvious tho. The module I use to enable fail2ban and the ssh-iptables jail contains

~~~
services.fail2ban.enable = true;
services.fail2ban.jails.ssh-iptables = "enabled = true";
~~~

The configuration option for jails uses the lines type. This will append, with a newline, the values all modules add to the same config. In this case the "enabled = true" config lines for ssh-iptables jail will be appended to the ssh-iptables jail config defined within the fail2ban module. This will result in the jail config:

~~~
[ssh-iptables]
enabled = true
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
maxretry = 5
~~~

If this method makes sense and sounds reasonable then I think updating the docs would suffice. Otherwise I think the "enable" config option of a jail should be partitioned from the config option for the configuration text of the jail.

**Comment by travisbhartwell** [comment]
When I filed the bug, I was new to NixOS and didn't realize the append nature of lines types.  I just tried this and it works great.  Perhaps some indication of this in the documentation would then be sufficient.

**Comment by jeaye** [comment]
This is still not clear and should be documented or enabled by default. Glad I found this ticket though.

**Comment by jeaye** [comment]
In fact, if you search around Github for `services.fail2ban.enable = true;`, you'll find that just about everyone is assuming that fail2ban is actually working with just that.

**Comment by tvon** [comment]
Is this fixed by https://github.com/NixOS/nixpkgs/pull/11958 ?

**Comment by joachifm** [comment]
Yes, it appears so
