### ISSUE TITLE
virtscreen broken by qt wrapper changes

### ISSUE THREAD

**Issue by benley** [NixOS/nixpkgs#84511]
**Describe the bug**
Related to #65399, virtscreen needs to be updated to work with `wrapQtAppsHook`.  I've tried to do it myself based on the qutebrowser derivation but haven't been able to figure it out.

**To Reproduce**

```console
benley@mintaka:~/p/nixpkgs $ $(nix-build -A virtscreen)/bin/virtscreen 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

I've attempted to fix it like so:
```diff
diff --git a/pkgs/tools/admin/virtscreen/default.nix b/pkgs/tools/admin/virtscreen/default.nix
index 73a81fcff87..92760c2d112 100644
--- a/pkgs/tools/admin/virtscreen/default.nix
+++ b/pkgs/tools/admin/virtscreen/default.nix
@@ -1,6 +1,6 @@
-{ stdenv, fetchFromGitHub, python3Packages, x11vnc, xrandr, libGL }:
+{ mkDerivationWith, stdenv, fetchFromGitHub, python3Packages, x11vnc, xrandr, libGL, wrapQtAppsHook }:
 
-python3Packages.buildPythonApplication rec {
+mkDerivationWith python3Packages.buildPythonApplication rec {
   pname = "virtscreen";
   version = "0.3.1";
 
@@ -16,6 +16,12 @@ python3Packages.buildPythonApplication rec {
     sha256 = "005qach6phz8w17k8kqmyd647c6jkfybczybxq0yxi5ik0s91a08";
   };
 
+  nativeBuildInputs = [
+    wrapQtAppsHook
+  ];
+
+  dontWrapQtApps = true;
+
   propagatedBuildInputs = with python3Packages; [
     netifaces
     pyqt5
@@ -30,6 +36,10 @@ python3Packages.buildPythonApplication rec {
       --replace "'GL'" "'${libGL}/lib/libGL${ext}'" \
   '';
 
+  postFixup = ''
+    wrapQtApp $out/bin/virtscreen "''${qtWrapperArgs[@]}"
+  '';
+
   meta = with stdenv.lib; {
     description = "Make your iPad/tablet/computer as a secondary monitor on Linux";
     homepage = https://github.com/kbumsik/VirtScreen;
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 141ebac5f3b..ba2b64051a6 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -21952,7 +21952,7 @@ in
 
   virtinst = callPackage ../applications/virtualization/virtinst {};
 
-  virtscreen = callPackage ../tools/admin/virtscreen {};
+  virtscreen = libsForQt5.callPackage ../tools/admin/virtscreen {};
 
   virtualbox = libsForQt5.callPackage ../applications/virtualization/virtualbox {
     stdenv = stdenv_32bit;
```

with the above patch applied it seems to get further but still doesn't quite work:

```console
benley@mintaka:~/p/nixpkgs $ $(nix-build -A virtscreen)/bin/virtscreen 
QQmlApplicationEngine failed to load component
file:///nix/store/xrjsj82hpnfbshy6k6br9jyvxbik82vc-virtscreen-0.3.1/lib/python3.7/site-packages/virtscreen/assets/main.qml:3 module "Qt.labs.platform" is not installed
```

along with those messages I get a dialog box that says "Failed to load QML":

![Screenshot from 2020-04-06 16-55-54](https://user-images.githubusercontent.com/1432730/78604246-7e862680-7827-11ea-9cde-5e5af79c3628.png)

I must be missing something here; can someone help me out?

**Comment by jorsn** [comment]
I haven't tested wether this works but I have some tips:

1. Have a look at `pkgs/development/libraries/qt-5/mkDerivation.nix`. That's most of the definition of `mkDerivationWith`. You can see, e.g., that `wrapQtAppsHook` is already in `nativeBuildInputs`.
2. `dontWrapQtApps = true` is appropriate here, because Python executables get already wrapped if using `buildPythonApplication`.
3. But using `wrapQtApp` manually then is probably mainly for controlling exactly when something is wrapped. Python apps are already wrapped, and you probably don't want to wrap the wrapper. You rather amend them by adding `"\${qtWrapperArgs[@]}"` to `makeWrapperArgs`. Have a look at the reference for `buildPythonPackage` in the [python section](https://nixos.org/manual/nixpkgs/stable/#reference) of the manual and at the [discussion](https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-common-issues) of simultaneous gnome, qt and python wrappers. An example is [in a PR of mine](https://github.com/NixOS/nixpkgs/pull/91291/files).
3. The global nipkgs scope uses qt-5.15 by default while python3Packages use qt-5.14.  Therefore you either need to use `libsForQt14.callPackage`, or you use `python3Packages.callPackage` and use `qt5`/`libsForQt5` as a package input.  The second method ensures that you always get the same `qt5` the current `python*Packages` are using.

If you then still have problems, feel free to ask again.

**Comment by dsyer** [comment]
Bump: virtscreen seems quite useful and currently broken.
