### ISSUE TITLE
Python 3 support for Hy

### ISSUE THREAD

**Issue by ratsclub** [NixOS/nixpkgs#84510]
**Project description**
Hy is a Lisp dialect that’s embedded in Python. Since Hy transforms its Lisp code into Python abstract syntax tree (AST) objects, you have the whole beautiful world of Python at your fingertips, in Lisp form.

**Description**
The current Hy interpreter only supports the deprecated Python 2 interpreter. As you can see in the following [commit](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/hy/default.nix)

**Metadata**

* homepage URL: https://docs.hylang.org/en/stable/
* source URL: https://github.com/hylang/hy
* license: mit
* platforms: all platforms that run python3

**Comment by jjwatt** [comment]
I've got this working, but I had to set `doCheck = false` I figured out that I should set `checkPhase` to use pytest, but then It's like the `tests` directory isn't there I'll submit a PR with what I have.

**Comment by jjwatt** [comment]
Oh wow. I feel dumb. I just had a thought that maybe the tests weren't there in the source distribution from PyPI, and so I downloaded the actuall tar.gz and looked inside it. Sure enough, no tests! I'm not sure if in this situation it would be better to build from git instead of PyPI in order to get the tests or if we should prefer the PyPI source.

**Comment by jjwatt** [comment]
PR has been approved: #84661. This should get pulled in sometime in the near future, and that should resolve this issue.
