### ISSUE TITLE
Too many Lutris packages

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NixOS/nixpkgs#84647]
**Describe the bug**
Not really the bug, but it is still an issue. There are a lot of Lutris packages in nixpkgs/nix for no reason. Not really sure which one to choose.

**To Reproduce**
1. Execute `nix search lutris`.

**Expected behavior**
It should just have one Lutris package.

**Screenshots**

![image](https://user-images.githubusercontent.com/50847364/78706863-4eaa5200-78ff-11ea-98ec-03cc24ab4337.png)

**Additional context**
It is a bit frustrating how I want to game, but I am unable to do so because there different versions of Lutris, and do not know which one to choose. I know I can just try all of them, but it is still an issue altogether.

**Comment by DIzFer** [comment]
I'm just a random passersby looking for a different bug, but this caught my eye.

There are several different things going on here:

 - It's a common pattern on certain distributions which try to make a Free-software environment possible (even if optional) to offer duplicated packages with a `-free` suffix without proprietary dependencies or features. Which should explain the difference between `lutris` and `lutris-free`
 - In nixpkgs in particular, it's also a frequent pattern to "wrap" software which won't play nice on an environment which doesn't respect the FHS (such as a Nix environment). This results in a `lutris` package, which is what users are normally expected to use, and the `lutris-unwrapped` package that really contains the program data and is actually pulled in as a dependency for `lutris`.
 - You, intentionally or otherwise, seem to have two different channels available for your user, one under the `nixos` namespace and other under `nixpkgs`. This results on you seeing six packages, instead of the real three.

I'd say this issue is, in fact, two different documentation bugs.

 1. Surely if only one of the variants can get a description, the `-unwrapped` one is the least worthy of it? In any case, it wouldn't be a stretch to ask for shortdescs in each variant for this exact usecase :)
 2. The dual channel thing is looking like a misunderstood manual. Maybe the language could be revised.

I don't really have the time, nor probably the knowledge, to fix the descriptions for variants (as in, I don't even know if it's possible to have different descriptions for each).

I'd be interested on fixing 2 though, if it's at all what's going on here. @TheEvilSkeleton, are you aware of this duplication? Is it intentional? If it is, what was your reasoning to have two channels instead of using the `nixos` one directly? Remember I don't know how much you know, I'm looking to understand your reasoning to see if this kind of confusion can be avoided without resorting to RTFM in the future. Maybe you knew exactly what you were doing and my questions are bogus after all ¯\\_(ツ)_/¯

On a related note: could `nix search` be taught that `pname`, `pname-free` and `pname-wrapped` are the same thing, and somehow conflate the three? If not because they have the same source file, just assuming the naming convention stands.  I don't think that last part resembles a good idea, but, as I said, I believe a better job could be done in a supposedly user-friendly tool :/

If it helps, what I'm imagining looks kind of like this, with a slightly more interesting example:
```
$ nix search firefox
* nixpkgs.firefox (firefox, firefox-bin, firefox-unwrapped, firefox-bin-unwrapped, firefox-esr, firefox-esr-52, firefox-esr-60)
 Mozilla Firefox packages
  * Wrapped program: see linktomanual to learn more
  Variants: (or whatever we actually call these)
  - firefox: Latest public stable version, compiled from source. 74.0.1
  - firefox-bin: Latest public stable version, downloaded from official binaries.  74.0.1
  - firefox-esr: Rolling ESR version for your nixpkgs version. 60.9.0esr
  - firefox-esr-52: Pinned ESR. 52.9.0esr
  - firefox-esr-60: Pinned ESR at version 60.9.0esr
```

With relevant shiny/bold colours so the search term is highlighted, as currently. I'm just terrible at markdowning. Add aliases handling (not pictured out of not knowing how to present `esr` as an alias of `esr-60` without the "rolling" nature of that particular one) and I could actually feel motivated to find why my `nix-search` hasn't returned a single result for any query in probably forever.

**Comment by TheEvilSkeleton** [comment]
> I'd be interested on fixing 2 though, if it's at all what's going on here. @TheEvilSkeleton, are you aware of this duplication?

Since I have discovered it, then I guess yes?

> Is it intentional? If it is, what was your reasoning to have two channels instead of using the nixos one directly?

It wasn't intentional, and I am only using one channel

```
# nix-channel --list                                               
nixos https://nixos.org/channels/nixos-unstable

```

> Remember I don't know how much you know, I'm looking to understand your reasoning to see if this kind of confusion can be avoided without resorting to RTFM in the future. Maybe you knew exactly what you were doing and my questions are bogus after all ¯\(ツ)/¯

I can't tell if I know what I am doing. All I did was try to install Lutris from when using the `nixos-unstable` channel.

> On a related note: could nix search be taught that `pname`, `pname-free` and `pname-wrapped` are the same thing, and somehow conflate the three? If not because they have the same source file, just assuming the naming convention stands. I don't think that last part resembles a good idea, but, as I said, I believe a better job could be done in a supposedly user-friendly tool :/

Sorry, you're asking this to a person that has recently got into NixOS lol. I'm guessing this will be a question you should ask to the maintainers, or to people that know how nix works.

**Comment by DIzFer** [comment]
On 08/04/2020 22:15, TheMainOne wrote:
> It wasn't intentional, and I am only using one channel
>
> ```
> # nix-channel --list
> nixos https://nixos.org/channels/nixos-unstable
>
> ```

Does `nix-channel --list` output anything different if ran as root? That 
may be the reason :/


If you don't mind, may we take the discussion somewhere else? For the 
sake of keeping the issue from stockpiling irrelevant/tangent info.


Since we're discussing several [Learn]ing topics, I suggest getting to 
discourse.nixos.org, you can use your github credentials there. I 
believe between one of our bots that links forum topics and issues, and 
the forum notifying me if you tag me, I should get the memo if you open 
a topic there. Hopefully we can distill a possible to-do list after that 
to put back here. Apparently my username is `Zurdo` over there.

Sorry for the friction with this!

**Comment by TheEvilSkeleton** [comment]
> Does `nix-channel --list` output anything different if ran as root? That
may be the reason :/

Same output both as root and user.

> If you don't mind, may we take the discussion somewhere else? For the sake of keeping the issue from stockpiling irrelevant/tangent info.

Sure, I have created an account. You can just send me the link of the chat you have created.

**Comment by Atemu** [comment]
As explained by @DIzFer, all three of these have good reason to exist.

The lack of descriptions on the variants is bad and confused me too when I was starting out (especially "unwrapped") but that's a separate issue.

> Same output both as root and user.

Your regular user's channels should be empty on NixOS but I'm getting the same issue.
