### ISSUE TITLE
MangoHud

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NixOS/nixpkgs#84686]
**Project description**

A modification of the Mesa Vulkan overlay. Including GUI improvements, temperature reporting, and logging capabilities.

**Metadata**

* homepage URL: https://github.com/flightlessmango
* source URL: https://github.com/flightlessmango/MangoHud
* license: gpl3
* platforms: linux

**Comment by ZerataX** [comment]
I tried myself at this and have a working package now for NUR https://github.com/ZerataX/nur-packages/blob/master/pkgs/MangoHud/default.nix based on https://github.com/nix-community/nur-combined/blob/master/repos/dandellion/pkgs/MangoHUD/default.nix

But I haven't yet figured out how to create a 32 and 64-bit version. Depending on the game both are necessary.

To just get a 32bit version I currently just change:

```nix
{ pkgs ? import <nixpkgs> {} }:

{
  # The `lib`, `modules`, and `overlay` names are special
  lib = import ./lib { inherit pkgs; }; # functions
  modules = import ./modules; # NixOS modules
  overlays = import ./overlays; # nixpkgs overlays

  mangohud = pkgs.pkgsi686Linux.callPackage ./pkgs/MangoHud { };
}
```
instead of just `mangohud = pkgs.callPackage ./pkgs/MangoHud { };`

**Comment by MetaDark** [comment]
@ZerataX It might make sense to just build the 32bit and 64bit packages separately and then merge them together in a wrapper.

**Comment by ZerataX** [comment]
@MetaDark okay I did something similar, though not with a wrapper with is probably a little hackish I am not sure:
https://github.com/ZerataX/nur-packages/blob/master/pkgs/MangoHud/combined.nix
```nix
{ pkgs, lib }:

let

  mangohud_64 = pkgs.callPackage ./default.nix { };
  mangohud_32 = pkgs.pkgsi686Linux.callPackage ./default.nix { libprefix="lib32"; };

in

pkgs.buildEnv rec {
  name = "mangohud";

  paths = [
    mangohud_64
    mangohud_32
  ];

  # ignoreCollisions = true;

  meta = with lib; {
    description = "A Vulkan and OpenGL overlay for monitoring FPS, temperatures, CPU/GPU load and more.";
    homepage = "https://github.com/flightlessmango/MangoHud";
    # maintainers = with maintainers; [ zeratax ];
  };
```

but this allows me now to use mangohud with 64 and 32 bit applications

**Comment by MetaDark** [comment]
@ZerataX That seems like a reasonable solution, however it is a little bit hackish. I'm running into a similar issue with [vkBasalt](https://github.com/NixOS/nixpkgs/pull/92401), and it's not really clear what the best approach would be.

@jtojnar recommended keeping the two builds separate for vkBasalt. But to ensure we can install both builds we would have to do extra patching, and use separate names for the 32bit and 64bit build.

I'm leaning towards something like this or like what I've done in my [NUR repo for vkBasalt](https://github.com/MetaDark/nur-packages/blob/fbaebd0f88c265de8d6a4d9aa4163a0d4cb7e4f7/pkgs/tools/graphics/vkBasalt/default.nix).

**Comment by ZerataX** [comment]
[Version 0.5.1](https://github.com/flightlessmango/MangoHud/releases/tag/v0.5.1) was just released but that changed quite a few things around. 
instead of using two different binaries it now uses [`$lib`](https://man7.org/linux/man-pages/man8/ld.so.8.html) to decide where the 32/64bit libaries are, but it seems to me that this always expands to 'lib' on NixOS
https://github.com/flightlessmango/MangoHud/blob/e56b7ded15b7cdaafc0bdb3c41961057eff44b97/src/meson.build#L9

This is what I have so far. The multiple substitutions are needed since \$ isn't valid json :/
Having to ignore collisions is also not really that cool.
```nix
{ stdenv, pkgs, lib
, libXNVCtrl, jq
}:
let
  mangohud_64 = pkgs.callPackage ./default.nix { libXNVCtrl = libXNVCtrl; };
  mangohud_32 = pkgs.pkgsi686Linux.callPackage ./default.nix { libXNVCtrl = libXNVCtrl; };
in
pkgs.buildEnv rec {
  name = "mangohud-${mangohud_64.version}";

  paths = [
    mangohud_32
  ] ++
  lib.lists.optionals
    stdenv.is64bit
    [ mangohud_64 ]
  ;

  buildInputs = [ jq ];

  postBuild = ''
    cd "$out/share/vulkan/implicit_layer.d/"
    substitute ./MangoHud.json ./MangoHud.json.new1 \
      --replace "\\$LIB" "\$LIB"
    jq '.layer.library_path = $s' \
      --arg s "$out/\$LIB/libMangoHud.so" \
      MangoHud.json.new1 >MangoHud.json.new2
    substitute ./MangoHud.json.new2 ./MangoHud.json.new3 \
      --replace "\$LIB" "\\\$LIB"
    mv MangoHud.json.new3 MangoHud.json
    rm MangoHud.json.new1 MangoHud.json.new2
  '';

  ignoreCollisions = true;

  meta = mangohud_64.meta;
}
```

Well having a running 0.4.1 version would be nice enough, just thought I write about this somewhere

**Comment by jtojnar** [comment]
The commit in question:
https://github.com/flightlessmango/MangoHud/commit/d712d35aaf5d548f23cc1e1596646cbafc4004a3

**Comment by Atemu** [comment]
#101597

**Comment by Atemu** [comment]
Still important to me.
