### ISSUE TITLE
Hotfixes for nixos-unstable

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#8480]
Sometimes changes like https://github.com/NixOS/nixpkgs/issues/7669 or https://github.com/NixOS/nixpkgs/issues/7859 break unstable.

This is a common problem with nixos-unstable, there are no hotfixes and it is not updated until all tests pass. That took more than a month last time.
Shouldn’t it be easy to do hotfixes on unstable by simply cherry-picking commits like NixOS/nix@c486176?

My problem here is that oftentimes there are breaking changes on unstable, which stay there for a long time. At least on master I get the fixes immediately (at the cost of having to rebuild the whole world every time).

**Comment by edolstra** [comment]
Well, it's called unstable for a reason. The alternative is to use one of the stable channels, which are much less likely to have such regressions.

And where would we cherry-pick commits to? The unstable channel is built from the master branch, which presumably already has the fixes you want to cherry-pick... Of course, you *can* create a local branch, based on the current channel Git version, and cherry-pick any desired commits (as described here: http://hydra.nixos.org/job/nixos/trunk-combined/nixos.manual.x86_64-linux/latest/download-by-type/doc/manual/sec-getting-sources.html).

**Comment by Profpatsch** [comment]
Depends on how unstable is represented. If it’s a tag it could simple be moved manually to cherry-picked hotfixes and automatically to master when the tests pass.

**Comment by vcunat** [comment]
Well, if we use staging as announced, we will never have to rebuild the world while on master.

**Comment by matthiasbeyer** [comment]
I don't think that the breakage in unstable is the real issue, the real issue is that you cannot downgrade the unstable branch that easily. One way would be to do a `nix-channel --rollback` but that kinda sucks, as sometimes a simple `cherry-pick` could save you.

So what I'd like to propose is that each time the channel gets updated to a certain commit, the update script should also add a tag in the branch: `unstable-<date>` or something. This way, one could simply build with the nixpkgs repo clone by checking out a certain commit and cherry-picking the appropriate fix.

---

That's actually what I do if I experience breakage, but I have to manually find out which commit was the last unstable channel update, which is a really long process (or involves a reboot or figgeling around with the store manually - I didn't find an alternative for this by now).

**Comment by vcunat** [comment]
Finding the revision isn't difficult, e.g. just read ``/nix/var/nix/profiles/per-user/admin/channels-115-link/nixpkgs-unstable/svn-revision``, moreover those ``channels-*-link`` symlinks are timestamped.

I guess you did notice that with nix-1.9 one can then do stuff like ``$ nix-env -iA firefox -f https://github.com/NixOS/nixpkgs-channels/archive/8a3eea054838b55aca962c3fbde9c83c102b8bf2.tar.gz``.

**Comment by matthiasbeyer** [comment]
> Just read [...]svn-revision

Lol? svn revision?

> one can then do stuff like `$ nix-env -iA firefox -f `

Yes, but you can't do a `nixos-rebuild switch` with this scheme, so you need a clone of the packages (to rebuild services, for example).

**Comment by vcunat** [comment]
The structure of channels comes from our pre-git days, but it contains git short hash now. And you *can* do a nixos-rebuild switch with that scheme, as that command also supports nixpkgs from an URL.

**Comment by matthiasbeyer** [comment]
Is this still an issue? I'd like to propose to close this issue, as we discussion has stalled anyways... @vcunat

**Comment by vcunat** [comment]
Yes, I suppose.
