### ISSUE TITLE
The setup-hook of Qt5 add unwanted dependencies to packages.

### ISSUE THREAD

**Issue by iyzsong** [NixOS/nixpkgs#8483]
`setup-hook.sh` from `qtbase` package will add qt packages
used to `propagatedBuildInputs` and `propagatedUserEnvPkgs`.
This bloat the package closure expecially when `qt5.tools` is used, which
will add qtwebkit, qtsvg, etc. 
Examples are `tiled` and `photoqt`.

@ttuegel , I think those two lines could be removed, and packages
need propagations can do it explicitly?

**Comment by ttuegel** [comment]
As I indicated on your pull request, we should not remove those lines. That the dependencies are unwanted does not mean they are unneeded. In particular:

* Removing `propagatedBuildInputs` will break every library that depends on Qt because qmake always wants all transitive dependencies to be available.
* Removing `propagatedUserEnvPkgs` will break packages at runtime if they use Qt plugins or anything they transitively depend on uses Qt plugins.

I think this is too burdensome to put on package maintainers. Instead, I will add a flag `qt5DontPropagate` which you can set to turn off `propagatedBuildInputs` and `propagatedUserEnvPkgs` on a per-package basis.

**Comment by edolstra** [comment]
I disagree. If `propagated*` introduces dependency bloat, then it should not be used. Depending on (say) `qtwebkit` when you don't use it sounds pretty bad.

**Comment by ttuegel** [comment]
What we're talking about is depending on `qtwebkit` indirectly, through a transitive dependency. The setup-hook isn't creating new dependencies.

**Comment by iyzsong** [comment]
For `tiled`,  I believe `qttools` is only used at build time, if it was not propagated, these is no
install time dependency on it.

**Comment by ttuegel** [comment]
Very well, I will do as @edolstra asked. It will take me ~ 1 day to complete this; I want to merge it at the same time as my fix for the KDE performance regression. (It doesn't make much sense to me to rebuild almost everything that depends on Qt 5 twice.)
