### ISSUE TITLE
Terminus is too old

### ISSUE THREAD

**Issue by gigi206** [NixOS/nixpkgs#85179]
**Project description**
[The actual package version (alpha-42)](https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/applications/misc/terminus/default.nix) seems very old, please update to the last (alpha-106 or more recent)

**Metadata**

* homepage URL: https://eugeny.github.io/terminus/
* source URL: https://github.com/Eugeny/terminus/releases
* license: mit,
* platforms: unix, linux, darwin

**Comment by worldofpeace** [comment]
cc @jlesquembre  (maintainer)

**Comment by gigi206** [comment]
Any news ? :)

**Comment by gigi206** [comment]
Any news ? :)

**Comment by jlesquembre** [comment]
@gigi206 as mention in the links, I tried to updated it, but got some errors. Since I don't use terminus any more, and I don't have time to work on this, I hope that someone else jumps in and fix it.  If orphaned long enough without its needed update, it should be removed. (since it won't continue to work eventually)

**Comment by ModdedGamers** [comment]
Closing since this package was removed from nixpkgs. See #134974.
