### ISSUE TITLE
ping6: raw socket: Operation not permitted

### ISSUE THREAD

**Issue by est31** [NixOS/nixpkgs#85345]
I've added the `inetutils` package to configuration.nix which includes the `ping6` utility. Trying to run `ping6 google.com` as an unprivileged user gives me the error: "ping6: raw socket: Operation not permitted". It only works once I'm running it through `sudo`. `ping` works just fine as unprivileged user. The issue is with `ping6` only.

I guess it has to be setuid. On ubuntu it works just fine.

**Notify maintainers**

@matthewbauer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.5.16, NixOS, 20.03beta1324.21750051b26 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03beta1324.21750051b26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment]
I think we need to add it to the apparmor profile here:

https://github.com/NixOS/nixpkgs/blob/ae94e8923240f7ff7e82abf4783ef4318b8c4464/nixos/modules/security/apparmor-suid.nix

**Comment by primeos** [comment]
@est31 do you need the ping binary from `inetutils`? If not you could use `ping -6 google.com` (from `iputils`, which we install with the necessary capabilities by default - see `nixos/modules/security/wrappers/default.nix`).

For `inetutils` we'd have to e.g. add a module (`programs.inetutils.enable`) that provides such a wrapper. But since that usage is rare it might be better to just add it to one's local configuration.

@matthewbauer this reminds me that I was wondering if we should maybe stop shipping the binaries `ping` and `ping6` form `inetutils` by default (e.g. something like `withPing ? false`). The problem is that if a user installs `inetutils` only `ping6` will be from `inetutils` while `ping` will still be from `iputils` due to the wrapper (earlier in `$PATH`). What do you think?

Additionally I just noticed that `man ping` shows the manual page from `inetutils`. I guess we should at least reduce the meta priority to avoid this incorrect conflict resolution (differing binary and man page).

**Comment by est31** [comment]
@primeos of course I could use `ping -6` but ping6 works fine on other distros like Ubuntu. Which kind of impression would nix os make if even such basic CLI programs don't work? Why can't the wrapper just be added to the package?

**Comment by primeos** [comment]
@est31 `ping6` should work perfectly fine on NixOS as well, we just ship it without setuid/capabilities.

> Why can't the wrapper just be added to the package?

This requires a module for technical reasons (e.g. to avoid security issues).

**Comment by 8573** [comment]
I'm not one to expect NixOS to work like other distros, but maybe the `iputils` package could provide a `ping6` that's just a shell script wrapping its `ping -6`?

**Comment by primeos** [comment]
@8573 I wouldn't really mind as at least it makes `ping` and `ping6` consistent if `inetutils` is also installed. Though there are some drawbacks (at least the fact that we derive from upstream and it could cause unwanted dependencies on `ping6` as well as wrong assumptions and a bit of confusion).

There used to be a `ping6` binary in `iputils` but it was dropped after the functionality was merged into `ping`. There is some discussion about this in #22822. I guess we could evaluate this again.

**Comment by 8573** [comment]
> it could cause unwanted dependencies on `ping6` as well as wrong assumptions and a bit of confusion

Maybe then `ping6` could be a script that just tells people to use `ping -6` instead?  I suppose that's too weird though.

**Comment by est31** [comment]
bump

**Comment by est31** [comment]
bump

**Comment by est31** [comment]
bump

**Comment by primeos** [comment]
@est31 I don't see anything happening here unless you cc additional people (but not randomly and not too many!). It might also help to research what other distros are doing (maybe there's a dominant pattern?).

Maybe cc @flokli @Mic92? If you have time and interest the current status/questions should be (IIRC):
- Should we suid `ping6` from `inetutils` (we currently only suid `ping` which comes from `iputils` and supports IPv6)?
  - Personally I'm not too keen on this option as `ping6` comes from a different package than `ping` which makes things inconsistent.
- Should the `iputils` package provide `ping6`?
- Should we just do nothing here (technically everything is fine / works as expected)?
- Should we stop providing `ping` and `ping6` via `inetutils` (since `iputils` provides more modern variants)?
  - (Personal note: I'm not sure if there's really a big need for `ping6` (there's no `ping4` for legacy IP either).)

**Comment by flokli** [comment]
suid'ing binaries only works via the module system, and `security.wrappers`. Just adding them to `environment.systemPackages` doesn't create the wrappers.

For `ping`, this is done in `nixos/modules/tasks/network-interfaces.nix` (using `iputils`).

If `iputils` would have provided a `ping6`, the answer would be very easy - just add it to the wrappers.

It doesn't, and I'm no fan of writing (and maintaining) our own wrapper.

Considering `inetutils` isn't part of a NixOS system, the `ping6` binary isn't available in `$PATH` - So I'd personally be inclined to say whoever adds `inetutils` to their system also needs to take care of registering the suid wrapper. This isn't any different from other binaries requiring suid bits to run as non-root.

**Comment by est31** [comment]
Since filing the bug I've started using `ping -6` but that doesn't solve the problem for the ping6 command. It is I think the more popular command so many people coming from other distros will be surprised that it doesn't work. I filed this issue because I felt it made the transition to nix os harder.

**Comment by flokli** [comment]
`ping6` doesn't exist on the base system at all, while `ping` does, so people already made the exercise of bringing `inetutils` in `$PATH`.

I think the problem here is that our whole suid wrapper situation isn't properly documented.

I opened https://github.com/NixOS/nixpkgs/issues/154128 for that, but I don't think we should also start shipping the (more outdated) `inetutils` command by default.

**Comment by primeos** [comment]
Thanks @flokli. Just for the record: I fully agree with your view here (I just wasn't sure if others felt the same and didn't want to close this without at least a second opinion).

**Comment by winny-** [comment]
Given ping6 doesn't work on nixos anyways, is there a way to fixup the package so ping6 simply doesn't exist without an extra knob?

**Comment by flokli** [comment]
@winny- `ping6` does work, when run as root.

**Comment by winny-** [comment]
Yep I agree it works as root, however, we have knowledge that most users won't have until they find this github issue...

**Comment by flokli** [comment]
That's why https://github.com/NixOS/nixpkgs/issues/154128 was opened to track better documentation on these cases.
