### ISSUE TITLE
Missing PHP extensions in httpd module

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#85401]
**Describe the bug**
When I enable PHP in httpd using `services.httpd.enablePHP = true`, the file

```php
<?php
var_dump(get_loaded_extensions());
```

when visited can only see 11 extensions

```php
array(11) { [0]=> string(4) "Core" [1]=> string(4) "date" [2]=> string(6) "libxml" [3]=> string(4) "pcre" [4]=> string(4) "hash" [5]=> string(3) "SPL" [6]=> string(8) "standard" [7]=> string(10) "Reflection" [8]=> string(4) "Phar" [9]=> string(3) "xml" [10]=> string(14) "apache2handler" } 
```

instead of the 52 I get when I run it through php CLI command.

**To Reproduce**
A failing NixOS test: https://github.com/NixOS/nixpkgs/pull/85402

**Additional context**
Likely caused by the great refactor: https://github.com/NixOS/nixpkgs/pull/83896

**Notify maintainers**
@etu, @talyz

**Comment by talyz** [comment]
Yep, the refactor relies on a configuration file with all the extensions to load being present and specified. For the binary, we have a wrapper that just tells PHP to look in the right folder for the config, but with the `httpd` module, it looks like that's not used, since it loads PHP as an `apxs2` extension.

The solution would probably be to inherit the config from the `php` package as the first thing put into the `php.ini` it already generates; it should be accessible as `${php}/lib/custom-php.ini`.
