### ISSUE TITLE
AWS AMI for 20.03

### ISSUE THREAD

**Issue by DzmitrySudnik** [NixOS/nixpkgs#85857]
Describe the bug
There is no AWS AMI for NixOS 20.03

To Reproduce

Check https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix
or
Try find it in AWS AMI console
Expected behavior
20.03 is created and uploaded to AWS

**Comment by bhipple** [comment]
CC @worldofpeace @disassembler, I think @grahamc knows how to do this part.

**Comment by worldofpeace** [comment]
Yep, I have no idea how to do this for NixOS, so I'd need someone in the know with AWS AMI for 20.03. This actually was one of my concerns for 20.03.

**Comment by bhipple** [comment]
I know how to build the release AMI and put it on a personal AWS S3 bucket (I'm using one now for my NixOps AWS cluster), but do not have the permissions to upload it on the official account.

@DzmitrySudnik about 2 months ago I followed this process, which you can use if you're looking to unblock yourself:

```console
# Create the actual AMI
$ nix-build nixos/release.nix -vA amazonImage.x86_64-linux
```
then follow these instructions to upload using `aws s3 cp`:
https://github.com/NixOS/nixpkgs/blob/master/nixos/maintainers/scripts/ec2/create-amis.sh

Then on NixOps you set `deployment.ec2.ami` to your custom AMI.  You can also use this to bake in pkgs to the AMI so there's less startup time if you know you'll be downloading specific things on provisioning startup otherwise.
