### ISSUE TITLE
calibre: No module named unrardll

### ISSUE THREAD

**Issue by aciceri** [NixOS/nixpkgs#86152]
I'm unable to view cbr files (for example), I get the following Python error:
```
ImportError: No module named unrardll
```

I installed the package with the flag `unrarSupport = true`, I'm using Nixos 20.03 on nixpkgs-unstable. 

@domenkozar @pSub @AndersonTorres 

Maybe I didn't install the package correctly, I'm using a custom overlay where I overrided the `super.calibre`, it seems legit to me.

**Comment by doronbehar** [comment]
Sounds legit to me as well. Though that would make sense if https://github.com/kovidgoyal/unrardll was even packaged in NixOS ! You can try to fix it @andrea96 by adding this package to `python-packages.nix` and add this as a dependency to calibre

**Comment by andrea96** [comment]
@doronbehar Setting `unrarSupport = true` disables [this patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/calibre/dont_build_unrar_plugin.patch) which otherwise removes the rar support directly from the python code.
The `unrardll` library should be distrubuted directly with Calibre, @gebner opened [an issue](https://github.com/NixOS/nixpkgs/pull/12098) years ago where this was discussed.
