### ISSUE TITLE
/run/cryptsetup is missing! 

### ISSUE THREAD

**Issue by Xel** [NixOS/nixpkgs#86248]
**Describe the bug**
Seemingly harmless warning being displayed.  
WARNING: Locking directory /run/cryptsetup is missing!

I first noticed this on unstable while doing a clean install for a new machine. Tested again on
 the 20.03 graphical installer live system just to make sure it wasn't an isolated case on the unstable. 

I haven't tested this fully 
**To Reproduce** 
1. Run any of the installers
2. Run cryptsetup on a fresh partition
3. Complete the password prompt phase

**Expected behavior**
There should be no warning after the password prompt.

**Screenshots**
![screenie](https://user-images.githubusercontent.com/886449/80528722-ebec2980-8985-11ea-9504-c163bfe842b2.png)

**Notify maintainers**

**Metadata**

- system: `"x86_64-linux"`
 - host os: `Linux 5.4.35, NixOS, 20.03.1577.74a80c5a9ab (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1577.74a80c5a9ab"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by eadwu** [comment]
This occurred in the past and was resolved for a period of months through https://github.com/NixOS/nixpkgs/pull/60235. I have also seen this a few times the past month during some re installations.

Though it's pretty much harmless, since the directory is created after the use usage of the command (at least from when I created that PR).
