### ISSUE TITLE
cachix: fails to build on master blocking nixpkgs-unstable

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#86263]
**Describe the bug**
https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents
https://hydra.nixos.org/job/nixpkgs/trunk/cachix.x86_64-linux
https://hydra.nixos.org/build/117813858

It seems servant-client is timing out to build for hours https://hydra.nixos.org/build/117846655.

cc @domenkozar

**Comment by cdepillabout** [comment]
@worldofpeace I tried building `cachix` (and `servant-client`) locally with the following command:

```console
$ cd /some/path/to/nixpkgs
$ nix-build -A cachix
...
/nix/store/d1qv22mbccvaiczvmmccr5cqwn30ymxz-cachix-0.3.7
```

It looks like it succeeded building.  This is on commit b7f80f00ef.

I'm not sure why Hydra would be having a problem with this.  Looking through the output of the build of `servant-client`, I don't see anything particularly strange (both my local build and https://hydra.nixos.org/build/117846655/nixlog/1).

Here's what I suggest we do about this:

- Try restarting the build on Hydra.  @worldofpeace Could you do this?
- If restarting the build fails, we can probably just disable the tests for `servant-client`, since it appears that is where it is hanging.
- We could also remove `cachix` from the list of required jobs, but I'm pretty sure @domenkozar wants it there.

**Comment by cdepillabout** [comment]
Also ping @peti so he is aware of this.

**Comment by domenkozar** [comment]
Restarted the builds.

**Comment by peti** [comment]
The servant error looks like a system-level problem. The build has succeeded, but for the part where the build result is copied back to the Hydra master (or the cache, or whatever). Maybe the LAN was down at that time? I think there's a good chance that the restarted build will succeed.

**Comment by vcunat** [comment]
Succeeded.  I assume it was a rare error that isn't worth attempting to mitigate in some other way?

**Comment by domenkozar** [comment]
It seems like and error in the infrastructure rather than in the build to me.
