### ISSUE TITLE
Package request: JabRef 5

### ISSUE THREAD

**Issue by luxferresum** [NixOS/nixpkgs#86331]
**JabRef 5**
JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format. JabRef is a desktop application and works equally well on Windows, Linux, and Mac OS X.

While there is a JabRef Package it is the outdated Version 3.

**Metadata**

* homepage URL: https://www.jabref.org/
* source URL: https://github.com/JabRef/jabref
* license: MIT
* platforms: unix, linux, darwin

**Comment by wamserma** [comment]
We are still at the last 3 because JabRef 4 introduced some breaking changes that were not compatible with the state of Nixpkgs at that time, see https://github.com/NixOS/nixpkgs/pull/72423.
Things are looking better with JabRef, but the `.jar` is no longer shipped standalone. So downloading huge blob just to throw away much of it would be needed.
This is discussed upstream at https://github.com/JabRef/jabref/issues/6340 and https://github.com/JabRef/jabref/issues/5771 - so feel free to ask for the bare `.jar` in these threads or find someone to change the nix expression to build Jabref from source.

**Comment by tobiasdiez** [comment]
The JabRef team will not and cannot provide `jar` files anymore since this is no longer a supported distribution form in recent Java versions. Instead, we use jlink + jpackpage to package JabRef in form that includes all of the runtime dependencies (including the jre). We now also provide a deb package, so maybe this can be easily reused for nix as well. 

(The linked issue concern a bug in our development workflow where unnecessary files are included in the build version, but this shouldn't be of any concern for further distribution for nix.)

**Comment by wamserma** [comment]
@tobiasdiez Thanks for the feedback. I had an attempt at building the latest release from source, but hit an issue with jlink, see here: https://github.com/JabRef/jabref/issues/6378
I did not retry yet with master and OpenJDK 14. Any ideas what causes this collision?

**Comment by tobiasdiez** [comment]
This looks to me indeed like a problem with JDK 13. Does it work with 14?

**Comment by wamserma** [comment]
Building tag v5.0 with Java14 fails due to this issue: https://github.com/gradle/gradle/issues/10248
(I did not yet try to bump Groovy to 2.5.9 on this tag.)

Building `jabref/master` with OpenJDK14 also fails with
```
> ./gradlew jlink
[...]
Error: Modules javafx.graphics and org.jabref.merged.module export package javafx.scene.layout to module org.jabref
```

**Comment by tobiasdiez** [comment]
Strange. The current master does compile on Linux as verified by our github build workflow...

Why do you need to compile JabRef yourself?

**Comment by wamserma** [comment]
> Why do you need to compile JabRef yourself?

It is the preferred way of packaging in nixpkgs.

**Comment by tyrion** [comment]
I also failed to compile JabRef from source under nixos (not sure if I did something wrong as I am no java expert). Anyway here is how I packaged JabRef 5, using the deb: https://gist.github.com/tyrion/7be8fec894181e881b7b6803d5772b76

I am not sure if this is good enough to be included in nixpkgs. Let me know if you want me to open a PR with this.

**Comment by Siedlerchr** [comment]
Can you plaese try with  using the AdoptOpenJDK jdk?
