### ISSUE TITLE
add huggingface's tokenizers Python library

### ISSUE THREAD

**Issue by Zhen-hao** [NixOS/nixpkgs#87059]
**Project description**
Provides an implementation of today's most used tokenizers, with a focus on performance and versatility.

**Metadata**

* homepage URL: https://github.com/huggingface/tokenizers
* source URL: https://github.com/huggingface/tokenizers
* license: Apache License 2.0
* platforms: linux

**Comment by mstone** [comment]
Although the build is failing right now due to a problem with a dependency/platform interaction, -- please see #94682 for some partial diagnosis -- I believe `tokenizers`' python binding is already packaged as, e.g., `python38Packages.tokenizers`.  If I am right about what you are looking for, [python-modules/tokenizers/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/tokenizers/default.nix) may be of interest.

**Comment by Zhen-hao** [comment]
@mstone thanks! 
I am using this workaround in my overlay.

```
tokenizers = self.callPackage ({ buildPythonPackage, fetchurl }:
        buildPythonPackage rec {
          pname = "tokenizers";
          version = "0.8.1";

          format = "wheel";

          src = fetchurl {
            url =
  "https://files.pythonhosted.org/packages/25/fc/775a802d0d59707a0a6448b0457c7222bd3d65a8232fbd02d904bae255b5/tokenizers-0.8.1-cp37-cp37m-manylinux1_x86_64.whl";
            sha256 = "1h0hqqn7fm596w235z7vra4jlvlb7bgsdfcw9fccyj24b3ln220g";
          };
        }) { };
```
