### ISSUE TITLE
cannot boot linux_latest_hardened on lvm-on-luks anymore

### ISSUE THREAD

**Issue by cyplo** [NixOS/nixpkgs#87260]
**Describe the bug**
Since switching from `19.09` to `20.03` I needed to switch from `pkgs.linuxPackages_latest_hardened` to `pkgs.linuxPackages_latest`, otherwise the system does not boot anymore.

**To Reproduce**
1. Install system on lvm-inside-luks using either `20.03` or `unstable` channel
2. use `pkgs.linuxPackages_latest_hardened`
3. `sudo nixos-rebuild switch --upgrade`
4. `reboot`
5. enter password - gets accepted correctly - LUKS seems to be working
6. system does not boot - complains about missing root device

**Expected behavior**
Would boot :)

**Screenshots**
`latest_hardened`:
![IMG_20200508_124145](https://user-images.githubusercontent.com/217899/81402597-a0761000-9129-11ea-9300-6c90dde6dc1d.jpg)
`latest`:
![IMG_20200508_124257](https://user-images.githubusercontent.com/217899/81402635-b2f04980-9129-11ea-89a5-6aecc85aa0e8.jpg)

**Additional context**
All my config for this machine starts from [here](https://github.com/cyplo/dotfiles/blob/master/nixos/boxes/foureighty.nix) - I link this file in place of `/etc/nixos/configuration.nix` 

**Notify maintainers**
@thoughtpolice maybe ?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.7, NixOS, 20.09pre223023.fce7562cf46 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(cyryl): `"home-manager, unstable-20.09pre223023.fce7562cf46"`
 - channels(root): `"nixos-20.09pre223023.fce7562cf46"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
^ using `unstable` channel with `latest` kernel right now

Happy to help debug this if needed :)

**Comment by eadwu** [comment]
What filesystem are you using

**Comment by cyplo** [comment]
Thanks so much for the reponse :)

It's `ext4 on lvm on luks` for `/`, hopefully still mainlined ? ;) 
I can try to compile the kernel with `CONFIG_AIO` set but otherwise with hardened settings enabled and see if it helps ?

**Comment by emilazy** [comment]
Sorry, this is my fault!

Yeah, my guess is that we need to re-enable AIO. I did notice some additional harmless-seeming warnings at boot that seemed AIO-related when writing #84522 (which switched to a patchset that disables AIO by default), but I guess it didn't affect any of my systems because they use ZFS.

I was hoping AIO was only required by marginal things (like Oracle...), but LVM is pretty important. Given that nginx also uses AIO per https://github.com/NixOS/nixpkgs/pull/84522#issuecomment-616307897, it might be worth explicitly turning it on in the default shared Kconfig (as I did for System V IPC in the original PR). I'm not sure if the AIO code is known to be particularly crufty by Linux standards or if it's just a general attack surface reduction thing; a few of the linux-hardened defaults are a bit better-suited to the Android environment than a desktop Linux distro. [kconfig-hardened-check](https://github.com/a13xp0p0v/kconfig-hardened-check) credits `CONFIG_AIO=n` to the original linux-hardened author's Android-based [GrapheneOS](https://grapheneos.org/) which makes me suspect this might be the case here.

@cyplo Here's a nixpkgs diff to re-enable AIO:

```diff
diff --git a/pkgs/os-specific/linux/kernel/common-config.nix b/pkgs/os-specific/linux/kernel/common-config.nix
index 0a58ed87e6c..06fd21bb87b 100644
--- a/pkgs/os-specific/linux/kernel/common-config.nix
+++ b/pkgs/os-specific/linux/kernel/common-config.nix
@@ -615,6 +615,8 @@ let
 
       SYSVIPC            = yes;  # System-V IPC
 
+      AIO                = yes;  # POSIX asynchronous I/O
+
       UNIX               = yes;  # Unix domain sockets.
 
       MD                 = yes;     # Device mapper (RAID, LVM, etc.)
```

It'd definitely be good to know if this fixes things for you. `nixos-rebuild -I nixpkgs=/path/to/patched/nixpkgs` should be enough to test this. If you don't want to use a custom nixpkgs then you can do a fiddly `linuxPackagesFor (linux_latest_hardened.override { ... })` thing like the definition of [`hardenedLinuxPackagesFor`](https://github.com/NixOS/nixpkgs/blob/99847a4e9dc466ca51954dcf881aac8dd5f4df77/pkgs/top-level/all-packages.nix#L17065-L17075) in `all-packages.nix`.

**Comment by emilazy** [comment]
Also, this would be pretty easy to test for, so if this change fixes it then we should also update the hardened test to use LVM.

**Comment by cyplo** [comment]
Heya, good news ! One kernel compilation later - I'm back to running `hardened` thanks to you :)
I tried the `sudo nixos-rebuild switch -I nixpkgs=/path` route and indeed it worked.

For the test - I think that would be awesome, to catch things like this in the future :)
