### ISSUE TITLE
nvidia.nix provides wrong udev when nvidia is card1

### ISSUE THREAD

**Issue by uzytkownik** [NixOS/nixpkgs#87788]
**Describe the bug**
On my system the nvidia card is `/dev/dri/card1`. However the udev rules create `/dev/nvidia1` and `/dev/nvidia1`. 

**To Reproduce**
1. Have system where nvidia is card1
2. Enable nvidia configuration.nix
3. Reboot system and try to use card (e.g. run nvidia-smi)

**Expected behavior**
`/dev/nvidia0` is created

**Screenshots**
```
$ nvidia-smi 
No devices were found
$ ls /dev/nvidia*
/dev/nvidia1  /dev/nvidiactl       /dev/nvidia-uvm
/dev/nvidia2  /dev/nvidia-modeset  /dev/nvidia-uvm-tools
```

**Additional context**

**Notify maintainers**
@baracoder @matthewbauer 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.39, NixOS, 20.03.1822.5adf2a6c116 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixos-20.03.1822.5adf2a6c116"`
 - channels(mpiechotka): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```
```yaml
attribute: pkgs.linuxPackages.nvidia_x11
module: hardware.nvidia
```

**Comment by baracoder** [comment]
That is the line, where the nvidiaX file is created.
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/video/nvidia.nix#L298

Ubuntu is calling nvidia-smi to create the node files
https://github.com/tseliot/nvidia-graphics-drivers/blob/435/debian/71-nvidia.rules#L22
But there is a pull request to stop doing it, because it is a workaround https://github.com/tseliot/nvidia-graphics-drivers/pull/35
see https://bugs.launchpad.net/nvidia-drivers-ubuntu/+bug/1839309

**Comment by mvnetbiz** [comment]
I think I might have just had this issue. I reset my bios settings and it took me a while to realize it had re-enabled the Intel iGPU, and the display manager was failing to show up. I didn't realize until I saw 2 nodes in /dev/dri. It was working some of the time, I think it could be due to random module loading order? I think https://github.com/NixOS/nixpkgs/issues/128591 could be a related issue too.

**Comment by byrongibson** [comment]
> I think #128591 could be a related issue too.

Thanks for the ping.  On workstation with Nvidia cards (dual Xeon, dual Nvidia 1070s), I'm using the Nouveau driver, and have the following /dev entries:

`$> ls /dev/|grep nv                                                        
crw-------   250,0 root    root    2021-11-24 19:34 nvme0
crw-------  10,144 root    root    2021-10-17 22:15 nvram
brw-rw----     3,0 root    disk    2021-11-24 19:34 nvme0n1
brw-rw----     3,1 root    disk    2021-11-24 19:34 nvme0n1p1
brw-rw----     3,2 root    disk    2021-11-24 19:34 nvme0n1p2

$> ls /dev/dri                                                             
Permissions    Size User Group  Date Modified    Name
drwxr-xr-x        - root root   2021-10-17 22:15 by-path/
crw-rw----@   226,0 root video  2021-11-24 19:34 card0
crw-rw----@   226,1 root video  2021-11-24 19:34 card1
crw-rw----@   226,2 root video  2021-11-24 19:34 card2
crw-rw-rw-  226,128 root render 2021-11-24 19:34 renderD128
crw-rw-rw-  226,129 root render 2021-11-24 19:34 renderD129
`

I'm not sure how to see what this looks like using the Nvidia driver, since it can't boot into a usable state.

**Comment by mvnetbiz** [comment]
I think you would have a 3rd render node if you had the Intel driver loading like I had, but maybe there is an issue in general with Nvidia and multiple GPUs.

**Comment by dpaetzel** [comment]
#126604 might be related, too? (I may be wrong since I'm just starting to dig into this because I think I'm having a very similar problem with one GPU not being accessible after boot.)
