### ISSUE TITLE
The generated wpa_supplicant.conf should not be world-readable

### ISSUE THREAD

**Issue by sgrb** [NixOS/nixpkgs#87829]
**Describe the bug**
If I specify my wireless networks configuration in networking.wireless.networks, the generated wpa_supplicant.conf has mode 0444 (i.e. it is world-readable). It is bad idea, because it contains potentially sensitive data, such as AP pre-shared keys, private key passwords ets. It shold be readable only by root

**To Reproduce**
Write in configuration.nix:
```
  networking.wireless.enable = true;
  networking.wireless.networks = { 
     "example" = { psk = "example"; };
 };
```
Look at the generated wpa_supplicant.conf mode - it is 0444

**Expected behavior**
It should be 0440 or  0400 (not world-readable)

**Notify maintainers**
@globin

**Comment by emilazy** [comment]
Per the [option documentation](https://nixos.org/nixos/manual/options.html#opt-networking.wireless.networks._name_.psk), anything you set `psk` to will already end up in the Nix store, which is inherently world-readable, so you need to configure your network secrets in another way if you want to avoid exposing them to ordinary users. In general, any string you set in your NixOS configuration can't possibly be secret; many services support options like `passwordFile` which can be set to a path to a non-Nix-managed secret to avoid this, but not `networking.wireless.*`.

**Comment by primeos** [comment]
Yes, this is unfortunately a known issue and not avoidable as @emilazy explained very well.

Regarding the option documentation: I think it would be a good idea to document this a bit better:
- Add an additional warning to `networking.wireless.networks` (since there is already an example with `psk`)
- For `networking.wireless.networks.<name>.psk` mention that the file with the plaintext password is also world-readable.
- Add the warning also to `networking.wireless.networks.<name>.pskRaw` (the hashes are still a secret and IIRC also very insecure)

AFAIK a secure alternative is `networking.supplicant.<name>.configFile.path` (but make sure that the value is quoted to avoid copying the configuration file to the Nix store). Personally I use
```nix
system.activationScripts."wpa_supplicant" = ''
  ln -sfn /etc/nixos/wpa_supplicant.conf /etc/wpa_supplicant.conf
'';
```
but probably only for legacy reasons.

**Comment by rnhmjoj** [comment]
> I think this works fine for pskRaw, but we'll likely run into escaping issues for the plaintext psk. I'm not sure how to deal with this.

Using sed to avoid empty variable expansion should be pretty safe.

**Comment by rnhmjoj** [comment]
#134618 now provides a way to avoid leaking secrets to all local users.
Essentially the real `wpa_supplicant.conf` (the one including secrets and used by the daemon) will be protected by requiring root for read access, while the generated one (which shouldn't contain sensitive information) will remain world-readable.
