### ISSUE TITLE
console.extraTTYs has no effect 

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#88085]
82e1d0c8b1b removes any effects of `console.extraTTYs`, so it now has no effect. We should just remove this option, or replace it with a warning.

/cc @rnhmjoj @edolstra

**Comment by rnhmjoj** [comment]
Uhm, I have never used this option so I didn't notice it had no effect.
I'm not sure I understand what's supposed to do: I guess it was used to add more ttys before logind started to automatically spawn them on demand. If this is correct then yes, it should be removed.

**Comment by p4block** [comment]
I used this option to spawn getty on a serial port so I could control access NixOS from my server's BMC. I can confirm it seems like it stopped working some time ago (it doesn't work now on a 1month old 20.03) and I just _noticed_ because a machine I have on unstable told me that the option was removed. 

Enabling getty@ttyS0 should be enough to get the same result as what the option did in the past, afaik.

**Comment by rnhmjoj** [comment]
Uhm, how long ago? Looking at the history of `console.nix` (previously `i18n.nix` and `kbd.nix`) the options stopped being used since 2011.

**Comment by p4block** [comment]
All I really know is that it used to work around last year. Sorry for the loose timeframe but this server's BMC is not usually accessed unless there's an emergency.  I looked more into it and I actually have a service unit for getty enabled on that serial port, except it doesn't  start for some reason on reboots (and nothing on the logs either). I could probably fix that by adding conditions to the service but it used to work and I think it was related to extraTTYs.

But if that was completely useless, well, then I don't really know anything. I'll report if I find out exactly what happened, and may random people searching for the problem find this if it's more widespread.
