### ISSUE TITLE
Switch p7zip to actively maintained fork

### ISSUE THREAD

**Issue by petersjt014** [NixOS/nixpkgs#88147]
## Issue description

The original P7zip was last updated over [3 years ago](https://sourceforge.net/projects/p7zip) and has accrued security vulns in the meantime. It has been (correctly) marked as insecure in [the package definition](https://github.com/NixOS/nixpkgs/blob/38d043b116478af3e31d1f7089b351754e4c6226/pkgs/tools/archivers/p7zip/default.nix), but it would be of more use if it were replaced by a fork that fixed these problems. I suggest [this one](https://github.com/szcnick/p7zip), as it seems to be the most actively maintained.

**Comment by emilazy** [comment]
Here's [a diff between the latest release of p7zip and this fork](https://gist.github.com/emilazy/90cc13ad4175f79f098bf5f606649181), excluding the new bundled libraries (`C/{fast-lzma2,lz4,zstd,zstdmt}`), if anyone would like to take a look. I haven't pored over it in detail, but some notes:

* This fork is linked from the [7-Zip site](https://www.7-zip.org/links.html), so it's probably a reasonable canonical choice.

* The bulk of the changes seem to be feature and documentation additions rather than refactors or security fixes.

* It seems that the repository has commits identified as fixing CVE-2016-9296 and CVE-2018-5996, but nothing clearly marked for other vulnerabilities we have patches for. We should make sure it incorporates fixes for these before switching to it as a presumed-secure upstream; we can't stay on top of fixing and patching every single vulnerability that comes up ourselves, so having the known CVE patches incorporated seems like a reasonable baseline expectation.

* The README doesn't mention the non-free licensing of the RAR code. Not really a big deal since this is a mess upstream too, just noting it.

* I feel like the really big task in keeping p7zip updated will be keeping it up to date with 7-Zip upstream, which I assume it shares a lot of code with. It's not clear if there's been much thought put into that here; there have been 10 upstream 7-Zip releases since the last p7zip release so there's probably a significant amount of divergence already (3 years of work, probably including a lot of security fixes, compared to the ~month this fork has existed). Discussion in [the thread about p7zip's fate](https://sourceforge.net/p/p7zip/discussion/383043/thread/fa143cf2/) seems to imply that the divergence is significant enough that it might be better to base a new p7zip on 7-Zip proper rather than the existing port.

Sorry for the negativity; these aren't intended to block this, just note down the concerns I'd have before committing to a fork. It would be great if we had a secure, updated p7zip package, since a lot of people are used to the interface, it has wide format support, and some software uses it internally. But from having skimmed over the code a bit and seen the existing vulnerabilities I know it'll be a big task to keep it updated and free of holes, and I think we should apply due diligence here given the liability it's been. I'd feel more comfortable re-enabling it once it's removed from builds (see e.g. #87837) and runtime dependencies where possible to reduce the general exposure.

**Comment by petersjt014** [comment]
> Sorry for the negativity

No problem, this was going to be messy no matter what.

I'd agree that upstreaming the nixpkgs fixes should be first priority, and that a big 7zip --> p7zip refactor should be farther down the road. In the meantime, do you think we could simply switch to the new fork while keeping the patches in the build process? It look like that we'd have at least a few less vulns, which would be useful even if it's still marked as insecure since some people/processes are still using it anyway.

Do you think that can that be done now, or does it need to wait for #87837?

also: cc @7c6f434c (Michael Raskin), the maintainer.

**Comment by 7c6f434c** [comment]
We have 4 CVE patches. There is a changelog that claims to apply some patches for 3 CVEs, and the last patch is defacto applied. Are there any more CVE patches we know of?

**Comment by petersjt014** [comment]
Here are CVE lists for [7zip](https://www.cvedetails.com/vulnerability-list.php?vendor_id=9220&product_id=0) and [pzip](https://www.cvedetails.com/vulnerability-list.php?vendor_id=9220&product_id=30936).

The nixfile's four patches are:
- CVE-2016-9296
- CVE-2017-17969
- CVE-2018-5996
- CVE-2018-10115

Szcnick's fork [seems to have all 4](https://github.com/szcnick/p7zip/blob/036f733357910649bfbcd1af8b7f2bee3df05b18/ChangeLog), although 2018-10115 is only noted [here](https://github.com/szcnick/p7zip/pull/11) (also CVE-2015-1038 is listed under 15.14 in the changelog).

Assuming Szcnick's fixes are good (and that 2015-1038 is a non-issue, which I think it is), switching now would provide equal security plus zstd support and the other new features.

Going off the [7zip](https://www.cvedetails.com/vulnerability-list.php?vendor_id=9220&product_id=0) list, I _think_ this is what we got so far:

CVE | has patch | last vuln | note
--|--|--|--
CVE-2008-6536 | | 4.5.7
CVE-2015-1038 | y
CVE-2016-2334 | | 16.00
CVE-2016-2335 | | 15.05
CVE-2016-7804 | | | windows-only
CVE-2016-9296 | y
CVE-2017-17969 | y
CVE-2018-5996 | y
CVE-2018-10115 | y
CVE-2018-10172 | | | windows-only

**Comment by 7c6f434c** [comment]
Let's hope everything goes well…

**Comment by rht** [comment]
What about the official release of 7zip itself? https://news.ycombinator.com/item?id=26438921
