### ISSUE TITLE
sublime-merge cannot push to remote

### ISSUE THREAD

**Issue by Derpford** [NixOS/nixpkgs#88600]
**Describe the bug**
When using Sublime-Merge, pushing to remote results in an error message: `.git doesn't look like a git repository.`

**To Reproduce**
1. Install both sublime-merge and git.
2. Open a repository.
3. Commit something, so that the local master is ahead of the remote.
4. Attempt a push.

**Expected behavior**
A password prompt appears, and the push continues as normal.

**Additional context**
Some earlier discussion occurred in [this issue](https://github.com/sublimehq/sublime_merge/issues/742) on the Sublime team's own github. We eventually found that the default.nix for sublime-merge seems to build, patch, and then discard a copy of `ssh-askpass`. This may be the source of the issue.

**Notify maintainers**

@zookatron 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
Output:
```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/hzrq5ccamfkwdkl9gqqsh3ryprzvs044-bash-interactive-4.4-p23-dev
copying path '/nix/store/hzrq5ccamfkwdkl9gqqsh3ryprzvs044-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.41, NixOS, 20.03.1866.a7c70f2e10b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sublime-merge
# a list of nixos modules affected by the problem
module:
```

**Comment by zookatron** [comment]
Hi @Derpford,

Thanks for letting me know, I've never tried entering a SSH passphrase directly through Sublime Merge before so I've never run into it, my ssh-agent just always handles it.

I can say that the `ssh-askpass-sublime` binary IS being included by the nix package and that the `sublime_merge` executable is finding and executing it properly (I confirmed this with strace), however for whatever reason the `ssh-askpass-sublime` is just not creating the popup to ask for the passphrase and I don't understand why. I've followed up with the Sublime Merge team in [the issue you created on their Github](https://github.com/sublimehq/sublime_merge/issues/742), hopefully they will get back to me with some context about what the `ssh-askpass-sublime` executable is looking for so that we can update the package to provide that.

**Comment by zookatron** [comment]
So after discussing this with the helpful folks on the Sublime Merge repository, I was able to figure out what the problem is, it is happening because the `ssh-askpass-sublime` functionality for `sublime_merge` actually depends on passing a special value as the `argv[0]` to the `sublime_merge` executable. However the `sublime_merge` file that `ssh-askpass-sublime` is trying to pass the `argv[0]` to is actually a wrapper script that calls `exec` to run the actual binary after setting up the proper environment variables. There doesn't appear to be any way for the bash script to detect the argv[0] that was passed to bash as $0 is overwritten with the path to the bash script. I'm not sure how we will resolve this issue but at least we know what is causing it now. Maybe we can create a wrapper for the `ssh-askpass-sublime` script that helps it execute the call properly against the un-wrapped binary or something.

**Comment by zookatron** [comment]
Howdy @Derpford , I created [a patch on this branch](https://github.com/zookatron/nixpkgs/tree/sublime-merge) that should fix this issue. Would you be able to try this fix out yourself to see if it works for you?
