### ISSUE TITLE
haskell: doJailbreak pulls in GHC 7.8.x

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#8901]
I have a project here where I'm using 7.10 Haskell package set but I have to manually jailbreak the package. This causes Cabal-1.20.x being pulled in which causes GHC 7.8.4 to be pulled in, at least if I'm reading the dependency graph correctly.

It'd be great if it could just use 7.10 instead of pulling a second compiler just to perform a jailbreak.

cc @peti

**Comment by puffnfresh** [comment]
:+1: to using 7.10

**Comment by peti** [comment]
Using the 7.8.x-built version of `jailbreak-cabal` in the 7.10.x package set was a workaround for https://github.com/peti/jailbreak-cabal/issues/9. I believe the issues we've had have been fixed with the latest Cabal release, so maybe we can get rid of that dependency now.

**Comment by peti** [comment]
ed739e3 improves the situation somewhat by removing the run-time dependency on `ghc`. A real fix will come a little later.

**Comment by peti** [comment]
The "real fix" is not possible right now. The only version of Cabal that doesn't break Cabal files during pretty-printing is 1.20.x, but that version cannot be built with GHC 7.10.2 because it requires certain core libraries that this compiler doesn't have (`deepseq ==1.3.*, filepath >=1 && <1.4, time >=1.1 && <1.5`). We have no choice but to use a binary compiled with GHC 7.8.4 at the moment.

**Comment by Fuuzetsu** [comment]
is there an upstream Cabal ticket?
