### ISSUE TITLE
openssh is broken on pkgsMusl

### ISSUE THREAD

**Issue by utdemir** [NixOS/nixpkgs#89246]
**Describe the bug**

After the PR https://github.com/NixOS/nixpkgs/pull/80196 is merged, as @dtzWill  
[mentioned on the same thread](https://github.com/NixOS/nixpkgs/pull/80196#issuecomment-590474909), `openssh` fails to evaluate on `pkgsMusl`.

This is quite annoying because `openssh` is a dependency of `fetchgit`, which makes a sizable chunk of `nixpkgs` fail to evaluate on `pkgsMusl`. I encountered this issue when trying to build `pkgsMusl.haskell.packages.ghc8101.cabal-install`.

**To Reproduce**
```
❯ nix-instantiate -E '(import ./. {}).pkgsMusl.openssh' --show-trace
error: while evaluating the attribute 'buildInputs' of the derivation 'openssh-8.2p1' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'libfido2-1.4.0' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'hidapi-0.9.0' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'preFixup' of the derivation 'libusb-1.0.23' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating 'optionalString' at /home/utdemir/workspace/github.com/nixos/nixpkgs/lib/strings.nix:180:5, called from /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/development/libraries/libusb1/default.nix:36:14:
while evaluating the attribute 'buildInputs' of the derivation 'systemd-245.5' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'glib-2.64.1' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'libselinux-2.9' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'fts-netbsd-8.0' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/os-specific/bsd/netbsd/default.nix:28:5:
while evaluating the attribute 'extraPaths' of the derivation 'compat-netbsd-8.0' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/os-specific/bsd/netbsd/default.nix:28:5:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'cvs-export' at /home/utdemir/workspace/github.com/nixos/nixpkgs/pkgs/build-support/fetchcvs/default.nix:11:3:
infinite recursion encountered, at undefined position
```

**Expected behavior**
`openssh`, therefore `fetchgit` to evaluate and run successfully on `pkgsMusl`.

cc @FRidh @dtzWill

**Comment by Aver1y** [comment]
I believe #88692 should change the error message, but not fix the problem. Now the trace should go like hidapi -> systemd, instead of hidapi -> libusb -> systemd. I don't really know where the infinite recursion comes from as that doesn't happen with nixos-19.09, however even if that didn't happen it wouldn't matter because systemd doesn't work with musl. If you want to fix this you'd have to look into getting the systemd dependency out of the hidapi nix expression. I'm not really sure why it's there in the first place, glancing at the hidapi [README](https://github.com/libusb/hidapi#linux), it seems like it depends on udev, which depends on util-linux which depends on systemd, but not on systemd directly and util-linux can be build without systemd. The utillinux nix expression already accounts for that possibility, you'd just have to make it actually do that for pkgsMusl. You could take the libusb nix expression as a template on how to achieve this.

*Disclaimer: I have virtually no experience with these low-level things, so I may be wrong.*
