### ISSUE TITLE
Cargo Build is broken

### ISSUE THREAD

**Issue by globin** [NixOS/nixpkgs#8966]
@wizeman 

~~Could you clarify the steps for building a rust package?
I'd expect the following to work with nix-build, but I don't know how to find out the correct depsSha255 and specifying a wrong produces an error.~~
```
with import <nixpkgs> {};

rustPlatform.buildRustPackage {
  name = "duck";
  buildInputs = [
    cargoSnapshot.cargo
    rustPlatform.rustc
    openssl
    cmake
    zlibStatic
  ];
  depsSha256 = "0g420cbqpknhl61a4mpk3bbia8agf657d9vzzcqr338lmni80qzx";
}
```

EDIT:
oh I just noticed that it's actually cargo failing (http://hydra.nixos.org/build/23927558)
~~I guess this is caused by removing leaveDotGit from cargo~~

Nope, failing with that, too, in:
https://github.com/NixOS/nixpkgs/blob/142400b8d5f2d05506df38d9212d91ab0eca8fc5/pkgs/build-support/rust/default.nix#L47

**Comment by wizeman** [comment]
Your code is almost correct. You need to remove `cargoSnapshot.cargo` and `rustPlatform.rustc` from `buildInputs`, because `buildRustPackage` already does that implicitly.

Regarding `depsSha256`, currently there isn't a good way to calculate it. What I do is to just put a valid but incorrect hash there (for example, taking an existing hash and replacing the last character with a zero), and then try to build. Nix will then tell you that your hash is incorrect, and it will tell you the correct one.

I will look into the `cargo` build failure.

**Comment by wizeman** [comment]
This should be fixed now.
If you have any issues, let me know. Thanks!

**Comment by hiberno** [comment]
@wizeman Fixed for me, thanks!

**Comment by globin** [comment]
:+1:
