### ISSUE TITLE
Package request: itch.io app

### ISSUE THREAD

**Issue by felschr** [NixOS/nixpkgs#90233]
**Project description**
The itch.io app is a client for the indie game store itch.io.

**Metadata**

* homepage URL: https://itch.io/app
* source URL: https://github.com/itchio/itch
* license: mit
* platforms: linux, darwin

**Comment by manveru** [comment]
Maybe helpful: https://github.com/openlab-aux/vuizvui/tree/master/pkgs/games/itch
Also pinging @aszlig since he worked on that if i remember right.

**Comment by TomSmeets** [comment]
@manveru I think that one just downloads a precompiled release from itch.io

My first attempt of packaging this was by following https://nixos.org/nixpkgs/manual/#node.js and just add `itch` to `pkgs/development/node-packages/node-packages.json`. That did not work however because the app does not exist on npmjs as far as I can see.

According to https://itch.io/docs/itch/developing/getting-started.html it should just be installed by a `git clone` and `npm install`. But I cannot find any documentation about what the nixpkgs approach would be for this.

**Comment by aszlig** [comment]
> @manveru I think that one just downloads a precompiled release from itch.io

Correct, it's basically just two itch.io games along with [a helper](https://github.com/openlab-aux/vuizvui/blob/3100ae7cd245cd2de413e4d4159a90bb52f4ead0/pkgs/games/itch/fetch-itch/default.nix) that fetches itch.io releases, so it's unrelated to this packaging request.

**Comment by fndov** [comment]
Having the itch game launcher on nix would be a huge win, hope this thread gets more attention
