### ISSUE TITLE
elixir-1.0.5 doesn't work on OS X

### ISSUE THREAD

**Issue by jkakar** [NixOS/nixpkgs#9050]
I'm using Nix 1.9 on OS X 10.10.4 (Yosemite) with the `elixir-1.0.5` package.  It installs without issues, but when I try to use the `mix` tool I get this error:

```
$ mix
/Users/jkakar/.nix-profile/bin/mix: line 3: Mix.start: command not found
/Users/jkakar/.nix-profile/bin/mix: line 4: Mix.CLI.main: command not found
```

I'm using the unstable channel:

```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

**Comment by gridaphobe** [comment]
Hrm, I get (also Nix 1.9 and OS X 10.10.4)

```
$ mix
Failed to execute process '/Users/gridaphobe/.nix-profile/bin/mix'. Reason:
exec: Exec format error
The file '/Users/gridaphobe/.nix-profile/bin/mix' is marked as an executable but could not be run by the operating system.
```

It seems to be an issue with the shebang in `~/.nix-profile/bin/mix` as

```
$ elixir ~/.nix-profile/bin/mix
** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available
```

seems to work just fine.

I don't see anything obviously wrong with

```
$ cat ~/.nix-profile/bin/mix
#!/nix/store/3vl3kb4r8h6abzsl46gg1nhz7ip3s1x2-elixir-1.0.5/bin/elixir
# Reminder: apply any changes in this file to bin\mix.bat
Mix.start
Mix.CLI.main
```

though...

(PS hi @jkakar, long time no see :)

**Comment by ryanartecona** [comment]
I just hit this issue too. Weirdly, just running `mix` from different shells would give different errors (I use fish normally, so it's always an early suspect around problems like this). I would get an error like @jkakar got from `bash`, and an error like @gridaphobe from `fish`.

When I change my `~/.nix-profile/bin/mix` to this:

```bash
#!/nix/store/dg8absgv0q0ri929wnzmbn64n5ni0ami-bash-4.3-p39/bin/bash -e
/nix/store/9yd1vqlyw5rdr0mj2xcbl08fllkx8dgg-elixir-1.0.5/bin/elixir -e "Mix.start; Mix.CLI.main"
```

Everything works, and in all shells the same way. Is this a valid fix?

(By "works", I mean I get `** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available`, but maybe that's a separate issue, or due to a lack of familiarity with Elixir/Erlang...)

**Comment by jkakar** [comment]
@ryanartecona Nice catch.  Doing `mix new myapp` will generate a new
app skeleton if everything is working as it should.

**Comment by ryanartecona** [comment]
@jkakar Turns out I just forgot to put the `"$@"` at the end of my fixed version, so no args were getting through :P 

Is what I mentioned above an acceptable fix? If so, I can submit a PR.
