### ISSUE TITLE
systemd-homed support

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [NixOS/nixpkgs#91243]
**Project description**
One of many systemd utilities that improve home directories management
**Metadata**
https://wiki.archlinux.org/index.php/Systemd-homed
https://systemd.io/HOME_DIRECTORY/

* homepage URL: https://systemd.io/HOME_DIRECTORY/
* source URL: https://github.com/systemd/systemd
* license: GPL-2.0
* platforms:  linux

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/72802#issuecomment-632660084

**Comment by bbigras** [comment]
Can this be closed since #98299 is merged?

**Comment by Atemu** [comment]
It's not enabled by default and there's no NixOS module for it either.

**Comment by bbigras** [comment]
still important

**Comment by Atemu** [comment]
Still important to me.

**Comment by TLATER** [comment]
Reading the docs on this, it seems like a necessity for single-password logins, and quite possibly the future of booting encrypted Linux installations, but I struggle to see how it would be reconciled with the concept of declarative user management.

This seems to have a concept of "updating" users according to what information about them changed since the last time we decrypted their home directory. The records are also encrypted via `homectl`, which only appears to have an imperative interface. Is this not inherently incompatible with declarative management in NixOS?

**Comment by VTimofeenko** [comment]
> Is this not inherently incompatible with declarative management in NixOS?

If I understand correctly, users.mutableUsers can already be set to allow non-declarative user management. Perhaps it would be possible to declare that a specific user is being managed through homed.

**Comment by alexshpilkin** [comment]
Bad bot.

**Comment by abathur** [comment]
Seems to have been satisfied by https://github.com/NixOS/nixpkgs/pull/205121
