### ISSUE TITLE
Can't compile gtk2hs-buildtools with GHCJS 

### ISSUE THREAD

**Issue by utdemir** [NixOS/nixpkgs#9175]
$ nix-shell -p haskell.packages.ghcjs.gtk2hs-buildtools
    these derivations will be built:
    /nix/store/kqvh2f16kyhj3gda7ylrd6zfc6hjxyy6-gtk2hs-buildtools-0.13.0.4.drv
    building path(s) ‘/nix/store/2b37yylh64alvpw43wb2xln688qkmq3s-gtk2hs-buildtools-0.13.0.4’
    ...
    ...
    ...
    Linking dist/build/gtk2hsHookGenerator/gtk2hsHookGenerator.jsexe (Main,Paths_gtk2hs_buildtools)
    Preprocessing executable 'gtk2hsC2hs' for gtk2hs-buildtools-0.13.0.4...

    c2hs/base/general/Binary.hs:408:2:
         error: #error "unsupported sizeof(HsInt)"
         #error "unsupported sizeof(HsInt)"
          ^
    builder for ‘/nix/store/kqvh2f16kyhj3gda7ylrd6zfc6hjxyy6-gtk2hs-buildtools-0.13.0.4.drv’ failed with exit code 1
    error: build of ‘/nix/store/kqvh2f16kyhj3gda7ylrd6zfc6hjxyy6-gtk2hs-buildtools-0.13.0.4.drv’ failed
    /run/current-system/sw/bin/nix-shell: failed to build all dependencies

The same package can be compiled with `ghc7102`. 

I'm using nixpkgs master(`715e77`). This problem makes GHCJS pretty much unusable since it's a dependency of `ghcjs-dom`.

I'm not sure that it's a bug on `nixpkgs` or `gtk2hs-buildtools` or `ghcjs`. Will move the issue if necessary.

**Comment by peti** [comment]
Cc: @cstrahan

**Comment by k0001** [comment]
The problem seems to be that `/nix/store/*-ghcjs-0.1.0/lib/ghcjs-0.1.0/include_native` is not included in the header search path for the C preprocessor, which is referred to by the included `/nix/store/*-ghcjs-0.1.0/lib/ghcjs-0.1.0/include/ghcconfig.h`.

**Comment by utdemir** [comment]
Hi,

@cstrahan , did you have time to look at the bug? Does it look doable?

**Comment by mschristiansen** [comment]
+1 same problem here :-(

**Comment by mayhewluke** [comment]
+1 - I'm stuck on this as well. Any chance we could get some info on the status of this?

**Comment by mayhewluke** [comment]
Correct me if I'm wrong, but this does not actually appear to be an issue with Nix. I installed GHCJS manually (following the [Quick Start](https://github.com/ghcjs/ghcjs/tree/8c35cc8631dda184bcbf29ee34bfc7cd1b656edd#quick-start) instructions) on a fresh VM and it still threw this error. I've reported it at ghcjs/ghcjs#395.

**Comment by peti** [comment]
6be6397aa1affa14ad95af5c35c3456cc1a6e2a8 should fix this issue. I'd be grateful if someone can confirm this.

**Comment by mayhewluke** [comment]
@peti I'm still waiting for everything to finish compiling but I'll hopefully be able to confirm once it's done.

**Comment by mayhewluke** [comment]
Finally finished compiling, and there is good news and bad news.

The good news is that 6be6397 solves the issue with `gtk2hs-buildtools`. The bad news is that this reveals a bunch of new problems now:

- Installing `ghcjs-dom` breaks because it still has `ghc` library dependencies in its `libraryHaskellDepends` field. The `ghcjs`-specific fix in [pkgs/development/haskell-modules/configuration-ghcjs.nix#L80](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-ghcjs.nix#L80) adds the `ghcjs` dependencies via the `buildDepends` field but does not remove the incompatible `ghc` libraries from the `libraryHaskellDepends` field. Changing this line from `buildDepends = [ ... ];` to `libraryHaskellDepends = [ ... ];` appears to solve this for me.
- `reflex-dom` has the same problem ([pkgs/development/haskell-modules/configuration-ghcjs.nix#L88](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-ghcjs.nix#L88))
- nixpkgs is currently using the `master` branch of `ghcjs`. This is a problem since nixpkgs is also using `ghcjs-dom-0.2.1.0` which is only compatible with the `improved-base` branch of `ghcjs`. Forcing nixpkgs to use `ghcjs-dom-0.1.1.3` allowed me to get past this, revealing the next problem:
- Installing `reflex` fails with numerous errors all along the lines of `Expecting one more argument to ‘DMap (WrapArg f k)’`. Installing it with a manually installed `improved-base` version of GHCJS/cabal-install seemed to work. However, I've gone and messed up my system trying to install a non-`improved-base` version and vagrant/VirtualBox are giving me troubles so I can't say for sure right now whether the problem seems to just be in Nix.

**Comment by k0001** [comment]
GHCJS's `improved-base` branch has been recommended over `master` for a while now, and it is actively maintained. Maybe we should switch to using that branch?

**Comment by peti** [comment]
I'm not quite sure how to proceed. I don't know much about `ghcjs`, so I'd like to leave this issue for someone else who is more qualified to handle this topic.

**Comment by k0001** [comment]
The `improved-base` branch on GHCJS has been merged to its `master` branch. I'm now trying to make the necessary upgrades to nixpkgs locally, and if I succeed in building it I'll send a pull-request later with said changes.

**Comment by k0001** [comment]
#10011 adds support for a more recent GHCJS suite (what used to be called `improved-base`, which just got renamed to `master` upstream). That doesn't fix the issue with `ghcjs-dom`, I'll send another pull-request for that later.

**Comment by k0001** [comment]
#10012 fixes `ghcjs-dom`. Thanks @mayhewluke

**Comment by mayhewluke** [comment]
As far as I can tell, everything mentioned in this thread has been resolved thanks to @peti's 6be6397 and @k0001's #10011, #10012, and #10044. Looks like this can be closed now.
