### ISSUE TITLE
Too many old Julia versions, 1.5 is not packaged, and all versions fail in tests

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#91930]
Julia 1.5 is out, see: https://docs.julialang.org/en/v1/NEWS/ and we don't have it packaged. More over, see how `all-packages.nix` defines our other Julias:

https://github.com/NixOS/nixpkgs/blob/fdfa609ae995e3bbf1f36a4850910ad116ff221d/pkgs/top-level/all-packages.nix#L8935-L8956

Several issues: `julia` is pointing to a TLS version which is old IMO. Certainly there are breaking changes seen in [their NEWS pages](https://docs.julialang.org/en/v1.1/NEWS/#Deprecated-or-removed-1), but since Nixpkgs is a somewhat rolling release distro, are we going to keep these older versions and default to them for ever? I've once tried to reach for the community to hear if there's a strict policy regarding such scenarios, but [I think the answer is no](https://discourse.nixos.org/t/nixpkgs-policy-regarding-libraries-available-in-multiple-versions/7026)

Anyway, I'd like to propose a change that will keep only the LTS version and the latest - currently 1.4, and perhaps make the attribute `julia`, point to the latest.

Any thoughts from maintainers or users?

cc @raskin @rob @garrison

**Comment by doronbehar** [comment]
Also, now I noticed julia_13 fails to build: https://hydra.nixos.org/build/123240981/nixlog/1

**Comment by garrison** [comment]
> Anyway, I'd like to propose a change that will keep only the LTS version and the latest - currently 1.4, and perhaps make the attribute `julia`, point to the latest.

I agree.  And the 1.5 release candidates are out, so this will become the latest version in the near future.

Last time I looked, the package built the same deps for all versions, including 0.7.  In versions 1.0 and later, there are actually fewer dependencies (e.g. arpack and fftw have been dropped), so the package should be cleaned up to not include these unnecessary libraries in the build.

I also think the default version should be the latest version (i.e., unless somebody explicitly installs julia-1-lts, they should get the latest).

**Comment by doronbehar** [comment]
> I also think the default version should be the latest version (i.e., unless somebody explicitly installs julia-1-lts, they should get the latest).

OK I'm glad I have your support. I'll let this issue stay open for a while and hopefully I'll be able to take care of this a month or so from now.

**Comment by veprbl** [comment]
cc @7c6f434c

**Comment by 7c6f434c** [comment]
Back when Julia tests were not so messed up, I think there was often 1 previous version.

I guess with 1.3 needing overriding to no tests, it is fine to just have julia-1-lts and Julia 1.4 as julia once Julia 1.4 gets built fine with some tests.

**Comment by rbvermaa** [comment]
Haven't had a lot of time to work on julia in nixpkgs, so just posting this as a FYI.

We used multiple versions of julia at work, but we use a custom derivation, similar to this: https://gist.github.com/rbvermaa/08f916a63ba4f3f6123f97478309dfa0

We also do not run the tests, but in general it has been working great.

Previously we also used the binary builds patched with patchelf, as there were some differences in the structure of the results of the vanilla binary build provided by julia and what we got when building from source. We gave up on using 'system' libraries, and build the `-full.tar.gz` releases that julia provides, as julia is very specific in the versions for its dependencies (LLVM patches mostly).

**Comment by doronbehar** [comment]
@rbvermaa I tried to use that `-full.tar.gz` tarball in order to write a derivation from scratch. Here's my attempt:

https://github.com/doronbehar/nixpkgs/blob/julia-latest/pkgs/development/compilers/julia/default.nix

It fails with:

```
Could not find working curl, wget, or fetch.
You need to install one of these to download dependencies.
make[1]: *** [/build/julia-1.4.2/deps/suitesparse.mk:144: /build/julia-1.4.2/deps/srccache/SuiteSparse.v5.4.0-2.x86_64-linux-gnu.tar.gz] Error 1
make: *** [Makefile:60: julia-deps] Error 2
```

Naturally I didn't further attempt to add curl or wget to the inputs, as that would fail in a sandbox as well. I've opened an issue upstream: https://github.com/JuliaLang/julia/issues/36604 complaining that that `-full.tar.gz` tarball doesn't really contain all dependencies.

**Comment by rbvermaa** [comment]
@doronbehar I ran with sandbox enabled, and the expression I linked with works for me.

**Comment by rht** [comment]
There is another approach to avoid running tests: using precompiled binary. I tried downloading the 1.4.2 binary from https://julialang.org/downloads/ and then afterward ran `patchelf` on the binary, then I got a running Julia interpreter just like that.

**Comment by rbvermaa** [comment]
We did the same for a while using code similar to this:
```
  patchJuliaBinaryLinux = args:
    stdenv.mkDerivation ({
      installPhase = ''
        cp -R . $out
        if [[ ! -e $out/lib/julia/libz.so.1 ]]; then
          ln -s ${zlib}/lib/libz.so.1 $out/lib/julia/libz.so.1
          ln -s ${zlib}/lib/libz.so $out/lib/julia/libz.so
        fi
        for i in $out/bin/*; do
          patchelf --set-interpreter $(cat $NIX_CC/nix-support/dynamic-linker) \
                   $i
          done
        '';
        dontStrip = true;
      } // args);

....

     julia_14_binary =
       patchJuliaBinaryLinux rec {
         version = "1.4.2";
         name = "julia-${version}";
         src = fetchJulia
           "https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-${version}-linux-x86_64.tar.gz"
           "https://julialang-s3.julialang.org/bin/mac/x64/1.4/julia-${version}-mac64.dmg";
       };

```

Unfortunately, we actually sometimes need to patch Julia, so we switched to the julia expressions from source, that I posted earlier.

**Comment by doronbehar** [comment]
Thanks @rbvermaa that expression works well thanks to `"USE_BINARYBUILDER=0"`. I'm testing it now.

**Comment by doronbehar** [comment]
OK so after a long build, I got a working Julia derivation with these references:

```
/nix/store/y8n2b9nwjrgfx3kvi3vywvfib2cw5xa6-libunistring-0.9.10
/nix/store/fhg84pzckx2igmcsvg92x1wpvl1dmybf-libidn2-2.3.0
/nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30
/nix/store/858a98xy9lxm322wjgsw150clmi8zf2h-gfortran-9.3.0-lib
```

And this closure size:

```
/nix/store/d13gkgdl809rm2xdwscqjqhvhwpy47w2-julia-1.4.2	 298.1M
```

Which I must say it is satisfying. The question is, is this how we'd want it to be built? Using all of their dependencies and practically non of ours? Some of their dependencies are required to be patched, according to [their docs](https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#build-dependencies) and they also specify that using the OS' libraries is not officially supported? Anyway I'd happy to get help on deciding this.

**Comment by 7c6f434c** [comment]
@doronbehar does this lead to Julia tests passing?

I think for every dependency they patch, it is OK to just use their patched version. I guess it could be nice to use a separate build unpatched (but using the exact same version sounds like a likely restriction), but whatever dependency does not work right away can be switched to bundled.

**Comment by doronbehar** [comment]
> @doronbehar does this lead to Julia tests passing?

I think it did, I've set `doCheck = true;` and the build passed but I haven't inspected the log much, but here it is:

https://gist.github.com/f11b21fb53984d481d5d5480ec0dc179

Currently [the expression at my branch](https://github.com/doronbehar/nixpkgs/blob/julia-latest/pkgs/development/compilers/julia/default.nix) produces this log but there's no PR yet as I think there are many makeFlags that should probably be set as well. If anyone feels confident to open a PR with this feel free to ping me for a review.

> I think for every dependency they patch, it is OK to just use their patched version.

I agree with the idea, but what's bothering me is that it's not absolutely clear what versions are patched and which are not - the docs vs what's actually found in [their patches directory](https://github.com/JuliaLang/julia/tree/v1.4.2/deps/patches) is not totally inline. Also, it seems that some of the patches are old, and were suggested upstream (to the libraries) but they weren't merged there for some reason. I'm still investigating, See https://github.com/JuliaLang/julia/pull/31215#issuecomment-662074132

My current target is to decide what libraries to use our version vs their version, with the preference to use our version, in order to hopefully reduce closure size due to sharing shared libraries. The idea is to decide this by checking whether the libraries have included the patch Julia suggests, and then whether the library's maintainer has released a new version that includes Julia's maintainers' patch, and whether we ship that new version.

**Comment by 7c6f434c** [comment]
>> @doronbehar does this lead to Julia tests passing?
>
>I think it did, I've set `doCheck = true;` and the build passed but I haven't inspected the log much, but here it is:
>
>https://gist.github.com/f11b21fb53984d481d5d5480ec0dc179

I think this log is cut short before the interesting part…

**Comment by doronbehar** [comment]
I've uploaded it here:

[julia.log](https://github.com/NixOS/nixpkgs/files/4959126/julia.log)

**Comment by 7c6f434c** [comment]
Hmmm. Reading the log does not convince me the tests were run… Pity.

**Comment by rht** [comment]
Since 1.5 was just released, the title should probably be updated to be 1.5.

**Comment by tbenst** [comment]
Downside with the patching approach, is users lose the ability to compile against MKL, which has HUGE performance increase (last [benchmark](https://discourse.julialang.org/t/openblas-vs-mkl/17362/4) I saw showed that MKL was ~4x faster at matrix multiplication!!). Would need to also package JuliaPro to get MKL. Of course, anything working > nothing working, although would be a shame to lose compilation options.

**Comment by garrison** [comment]
> lose the ability to compile against MKL

Says https://github.com/JuliaLang/julia/blob/master/doc/build/build.md:

> If you are building Julia for the sole purpose of incorporating Intel MKL, it may be beneficial to first try [MKL.jl](https://github.com/JuliaComputing/MKL.jl). This package will automatically download MKL and rebuild Julia's system image against it, sidestepping the need to set up a working build environment just to add MKL functionality.

**Comment by tbenst** [comment]
Thanks garrison, I saw that, but I have a feeling it won't play nicely with Nix...although if we go patching route, perhaps could do that during buildPhase

**Comment by garrison** [comment]
> I have a feeling it won't play nicely with Nix

Are you concerned about MKL.jl specifically or all packages that use BinaryBuilder?  There are a lot of them.  More on this at https://julialang.org/blog/2019/11/artifacts/

**Comment by tbenst** [comment]
As I understand binary builder, that all happens in userspace, but MKL.jl modifies [sysimage](https://julialang.github.io/PackageCompiler.jl/dev/devdocs/sysimages_part_1/#.-Creating-the-sysimage-shared-library-from-the-object-file-1), which is in /nix/store

**Comment by garrison** [comment]
> MKL.jl modifies [sysimage](https://julialang.github.io/PackageCompiler.jl/dev/devdocs/sysimages_part_1/#.-Creating-the-sysimage-shared-library-from-the-object-file-1), which is in /nix/store

The installation instructions for MKL.jl do not seem to require root.  My guess is that it stores the modified sysimage somewhere in `~/.julia/`.  Am I wrong?

**Comment by tbenst** [comment]
I just tried it with Julia 1.4 installed with Nix, and as I suspected MKL.jl fails to build due to `ERROR: LoadError: SystemError: opening file "/nix/store/x7jiz74grqbygrpakyznw6piywzgg50l-julia-1.4.1/bin/../share/julia/base/sysimg.jl": Read-only file system`

**Comment by doronbehar** [comment]
We need to have a `julia.withPackages` interface - that would support building binary packages, and make the interpreter aware of them. I wish I was a bit more motivated to do this, but upstream disappoints me regarding the humble task of compiling Julia as is, with the right selection of a few system dependencies - no response at all at https://github.com/JuliaLang/julia/issues/36604 & https://github.com/JuliaLang/julia/pull/31215#issuecomment-662074132 . I'm also dis-motivated to explore this aspect, since their build system is of plain makefiles, and they keep patches of dependencies from so long ago, without documenting whether they are needed / used or not...

**Comment by garrison** [comment]
> no response at all

Nix was cited as one of the inspirations behind Pkg.jl.  It is a shame to see its support in NixOS languish.

> I'm also dis-motivated to explore this aspect, since their build system is of plain makefiles, and they keep patches of dependencies from so long ago, without documenting whether they are needed / used or not...

It seems pretty clear to me that upstream is only interested in supporting the configuration obtained by cloning their repository and typing `make` on a stock Linux distribution.  I understand their perspective in many ways, as having julia and all of its packages "just work" requires a lot of care, and building with unsupported configurations is very likely to result in brokenness somewhere in the package ecosystem if not in julia itself.  Julia is a bit special in this regard because of its emphasis on performance and also its need to support interfaces to other languages/frameworks that often have weird requirements.  I have found that typically, there is very good reason for these patches, even though at times they may not be documented except in git and github history.  (Admittedly, I am less involved in upstream than I used to be.)

**Comment by tbenst** [comment]
I think Julia team initially evaluated Nix as their binary distributor (https://github.com/JuliaPackaging/Nix.jl) but decided against it—there was a discussion somewhere but can’t find it. IIRC lack of Windows / desire to tie into native pkg management systems were factors.

> We need to have a `julia.withPackages` interface
Julia’s Pkg.jl does a pretty great job, and uses a solver to properly resolve dependency versions based on constraints. I’ve been incredibly frustrated by the withPackages pattern, at least in python. I constantly run into problems due to nixpkgs ignoring version constraints. There are some other nice advantages to nix of course: binary dependencies are shared across language ecosystems for example, and there are lots of supremely annoying packages (I’m looking at you CUDA...) that Nix makes delightfully easy to install, use, and maintain parallel versions. But until Nixpkgs supports multiple versions across the board, and has a solver baked in, I’m honestly not sure Nix brings enough advantages to bail on Pkg.jl.

**Comment by rht** [comment]
Maybe it is worth to reaching out to Julia Computing folks at https://julialang.slack.com/ to get their attention on https://github.com/JuliaLang/julia/issues/36604 ?

**Comment by doronbehar** [comment]
> Julia’s Pkg.jl does a pretty great job, and uses a solver to properly resolve dependency versions based on constraints

We'd probably need to put this information in our attribute sets, just like our Python packages know what deps they need.

> I constantly run into problems due to nixpkgs ignoring version constraints

Hmm that's a bit surprising to hear as the Python ecosystem seems most well organized. Have you ever encountered a real bug with a mismatched version of a dependency with a specific version specified in a package's `setup.py`? IIRC `python setup.py` fails if a `==` version is used and it's not exactly what's available. If you've ever felt there's a certain python package of a certain version missing, have you considered contributing it? Even if not, was it too hard to override it?

> But until Nixpkgs supports multiple versions across the board

What do you mean "across the board"?

> and has a solver baked

That might be much more harder then it sounds, due to the constraints of Nix it self when being evaluated everytime you run `nix-build` and friends, see https://discourse.nixos.org/t/creating-vendor-directories-directly-in-srcs-of-go-and-rust-packages-so-fixed-output-derivations-wont-be-needed/7367

> I’m honestly not sure Nix brings enough advantages to bail on Pkg.jl.

It's not a question of whether Nix brings an advantage or not, it's a question of whether there are any Julia packages that are built at other distros imperatively with a `Pkg.add()`, and this produces (or even worse, downloads) shared objects or executables into `~/.julia` (not in `/nix/store`), **linked** to Julia or other Nix deps that _do_ reside in `/nix/store`. If the answer is yes, than every Nix user will experience breakage after Julia is updated in his `/nix/store` - not necessarily if it's a version bump of Julia, it could be a mere rebuild of Julia by hydra.

> I think the approach done by poetry2nix and Mach-nix are the way to go for Julia packages + nix

Yea Mach-nix is an awesome idea well implemented (@DavHau thanks for the inspiration :heart:). I've also reached a similar conclusion at [that discourse thread](https://discourse.nixos.org/t/creating-vendor-directories-directly-in-srcs-of-go-and-rust-packages-so-fixed-output-derivations-wont-be-needed/7367/17?u=doronbehar).

However, this is my opinion for Rust and Go, and I tend to think that for a small ecosystem like Julia, perhaps it'll be too much - it shouldn't be that hard to manage all of these pacakges like Python is managed in Nixpkgs.

**Comment by doronbehar** [comment]
> Maybe it is worth to reaching out to Julia Computing folks at https://julialang.slack.com/ to get their attention on JuliaLang/julia#36604 ?

I opened https://discourse.julialang.org/t/no-documentation-for-the-state-of-patches-for-dependencies-of-julia/44735

**Comment by tbenst** [comment]
> Have you ever encountered a real bug with a mismatched version of a dependency with a specific version specified in a package's `setup.py`?

Frequently. Especially with Scipy, matplotlib, bokeh, sklearn, tensorflow, pytorch, etc...

.> If you've ever felt there's a certain python package of a certain version missing, have you considered contributing it? Even if not, was it too hard to override it?

Often, nixpkgs used to have it until it was updated. Except in very rare circumstances, we do not keep more than one version of a python package around. I have no interest wasting time working around bugs that authors tried to spare me by specifying precise versions. It seems a sort of cognitive dissonance in our next community that we all care so deeply about reproducible builds, but for convenience often disregard the officially supported dependencies. As a result, there are often subtle bugs in software on NixOS that do not appear on other platforms. (Eg x11vnc crashes, shared memory problems, etc).
 
> > But until Nixpkgs supports multiple versions across the board
> 
> What do you mean "across the board"?

Nix supports crazy high specificity in versioning, well we past semantic versioning down the the bit in many cases. And yet in nixpkgs, by convention, we remove the old version anytime we update. It’s understandable that Hydra cannot build everything, but it’s always bothered me that I have to pin nixpkgs if I want a build to stay functional over 1+ years.

> It's not a question of whether Nix brings an advantage or not, it's a question of whether there are any Julia packages that are built at other distros imperatively with a `Pkg.add()`, and this produces (or even worse, downloads) shared objects or executables into `~/.julia` (not in `/nix/store`), **linked** to Julia or other Nix deps that _do_ reside in `/nix/store`. If the answer is yes, than every Nix user will experience breakage after Julia is updated in his `/nix/store` - not necessarily if it's a version bump of Julia, it could be a mere rebuild of Julia by hydra.

Pkg.add is *mostly* declarative. Of course, Julia is constantly re-compiling code, and until there is true support for precompilation, I don’t see how it’s possible to use nix store. 

This is due to multiple dispatch. Suppose I wrote a library to do an efficient k-nearest-neighbor query using some fancy free structure. Perhaps the core algorithms simply require a `distance(a,b)` function for your types. When you write this new function, Julia has to compile all the code in the k-nearest neighbor library for this new type. Thus, it is not possible right now to compile a package on its own as the core pattern in Julia involves extending the function of other packages via multiple dispatch. You can only compile a package in context of the code that is running. Therefore, the Nix store approach is not appropriate. See  https://hub.packtpub.com/julia-co-creator-jeff-bezanson-on-whats-wrong-with-julialang-and-how-to-tackle-issues-like-modularity-and-extension/

**Comment by doronbehar** [comment]
> I have no interest wasting time working around bugs that authors tried to spare me by specifying precise versions.

I see. You are talking about "authors" of Nixpkgs' expressions? I'm still a bit perplexed, as I earlier said, and correct me if I'm wrong: `python setup.py` should fail if `==` is used in `setup.py`, and the exact version is not available. Sometimes ([e.g](https://github.com/ju1m/nixpkgs/blob/d8f46b9da0cb9a08e0b278b8e77f327dce7cdb77/pkgs/applications/networking/p2p/stig/default.nix#L19-L27)), we do hardcode such version requirement changes in our expressions, but hopefully that's done only when it's justified.

> It seems a sort of cognitive dissonance in our next community that we all care so deeply about reproducible builds, but for convenience often disregard the officially supported dependencies.

I agree (maybe a bit [related](https://github.com/NixOS/rfcs/pull/74)). Generally I think, every dep's version related issue should be handled by someone like you, who's familiar with python packages you use. I'd at least (open PRs) to fix the issues I encounter :).

> Pkg.add is mostly declarative. Of course, Julia is constantly re-compiling code, and until there is true support for precompilation, I don’t see how it’s possible to use nix store.

I see. I guess the situation is more complex than I thought, but I don't think I'd be able to form a strong opinion until I'll get a Julia interpreter from an expression I'm satisfied with.

> hub.packtpub.com/julia-co-creator-jeff-bezanson-on-whats-wrong-with-julialang-and-how-to-tackle-issues-like-modularity-and-extension

Thanks for the link :).

**Comment by tbenst** [comment]
> Sometimes (e.g), we do hardcode such version requirement changes in our expressions, but hopefully that's done only when it's justified.

Unfortunately, this pattern is done constantly (including in my own contributions!). The problem is that, except an extremely rare cases like tensorflow, nixpkgs does not allow multiple versions of same python package to co-exist. Every time we update a package, we remove the previous version from nixpkgs.

Confounding this issue, we often disable tests because sometimes the effort is just too high when developers bake in assumptions that aren’t compatible with the Nix ethos (for some reason this seems to happen more with tests then source code...). The most frequent cause of failure is the code needs to download something to run the test. (I’ve tried to lobby in the past that the test phase should be permitted to have Internet access as long as it doesn’t modify /nix/store, but I digress).

In any case, the end result is that using a python package on Nix typically means you aren’t using the exact dependencies that upstream declared, and you’re more likely to have a package that despite having changes in dependencies has never had the test run.

Thus, amazingly, I’ve had more luck with Julia packages working on NixOS than Python when all other binaries are present in environment.

**Comment by doronbehar** [comment]
> except an extremely rare cases like tensorflow, nixpkgs does not allow multiple versions of same python package to co-exist.

@tbenst I don't think there's a strong policy in our Python ecosystem against multiple versions of packages - if this is what upstream recommends. Anyway, the whole topic is out of scope for this issue. Feel free to open a new issue and cc me and `@jonringer` who's working hard to ship a 20.09 release.

**Comment by tbenst** [comment]
Yes, sorry getting a little off topic here. I mainly mention it to suggest that our efforts in Julia that start from scratch Can learn from these issues. I’m not too familiar with the new binary builder, but BinDeps.jl was quite nice in that it would first search for libraries before attempting to install. See this issue for some context: https://github.com/JuliaPackaging/BinDeps.jl/pull/115. Note that a core Julia dev gave a pretty great endorsement on Nix (albeit back in 2014): https://github.com/JuliaPackaging/BinDeps.jl/pull/115#issuecomment-63059480.

I think it might be most productive to do this development outside of nixpkgs, and do it in Julia to hook in with nixpkgs as needed. That way users could seamlessly use Pkg in Julia. I’d love to `]add Flux` and have it just work instead of the current hack that I wrote that a lot of people seem to be using (https://github.com/NixOS/nixpkgs/issues/70536#issuecomment-539146690)

**Comment by garrison** [comment]
Short summary of the Discourse thread: for LLVM and libuv it is essential to use the patches/forks.  For other packages it is probably unnecessary to use the exact version specified by upstream.

**Comment by doronbehar** [comment]
Thanks @garrison for being there with me :). I think I'm gonna work on this once we are through with https://github.com/NixOS/nixpkgs/pull/93333, to avoid merge conflicts.

**Comment by doronbehar** [comment]
TIL Guix manages to package Julia 1.4.1:

https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/julia.scm?id=master

What's interesting, is that they `USE_SYSTEM_LLVM` but they build it with Julia's LLVM patches fetched from the internet - they don't rely on Julia's build system to build it's own LLVM. For similar dependencies which the real system's version can't be used, they do the same.

I think we should copy this approach.

**Comment by nalimilan** [comment]
FWIW I did that in Fedora originally, but since LLVM makes breaking releases very quickly, you'll probably want to move to a new version that Julia doesn't support quite soon.

**Comment by doronbehar** [comment]
> you'll probably want to move to a new version that Julia doesn't support quite soon.

Maybe I don't understand, but why should I move to an LLVM version that julia _doesn't_ support? Also, aren't the `llvm_7` and `llvm_8` versions don't introduce breaking changes between minor releases? We could stick to `llvm_8` since that's what Guix does and I think Julia uses this version as a base too.

**Comment by nalimilan** [comment]
I don't really know how NixOS works, hence the "FWIW". If you used versioned LLVM packages and keep older major versions then it's probably OK.

**Comment by cmcaine** [comment]
Just offering a user perspective:

Julia provides a package manager that provides mostly reproducible (in a practical/scientific reproducibility sense rather than a bit-identical sense) environments easily from manifests. Increasingly, these environments are isolated from the host OS by binary packages for dependencies being served by Julia.

I don't want Nix to manage dependencies that Julia/Pkg.jl can handle for me: Julia already handles those excellently and conveniently. I just want Nix to handle the (usually few) system dependencies.

What I would like as a NixOS user is for Nix to provide me with a working Julia 1.5 derivation that provides: julia, a FHS wrapper or something providing compatible versions of the few things that Julia's binary packages need (just libc, libstdc++, libgfortran; I think. [see BinaryBuilder.jl docs](https://github.com/JuliaPackaging/Yggdrasil/blob/master/RootFS.md)).

When I say "compatible", I mean that these libraries should work with the BinaryBuilder.jl binaries and with the julia binary provided by Nix.

Not all Julia packages are BinaryBuilder-ised yet, so I'd also want an easy way to specify that I want compatible versions of other packages installed (e.g. Qt, cairo, etc). For packages that need python, I don't know if I'd like Julia or Nix to handle installing and managing that. The simplest approach would be to tell Julia to do it (there is pretty good support in Julia for distributing isolated environments of python + packages + dependencies; better than in `pip`, imo).

I don't know how doable any of that is in Nix, just describing what a good outcome would like to me.

**Comment by tbenst** [comment]
@cmcaine I think this is quite doable. I would propose that we add a new package, [`julia-env` or similar](https://github.com/NixOS/nixpkgs/issues/70536#issuecomment-539146690), that is a "batteries included" build that contains system libraries for all common Julia packages. Would this approach work for BinaryBuilder? I haven't used this yet. If not, we could fall back to a FHSuserenv, but I'm reluctant to do so if at all avoidable as there are outstanding nix bugs ([ie this](https://github.com/NixOS/nix/issues/3597)) that create seg faults in some heavy data processing workflows.

**Comment by cmcaine** [comment]
@tbenst I think that is a good proposal and I think it will work with BinaryBuilder packages (e.g. SDL_jll). In any case, some approach that works with BinaryBuilder packages should be found because those are a critical part of the Julia environment now :)

Some important packages (e.g. GR) still want to build and install their own software dynamically, and that doesn't work well in Nix, but most of those can plausibly move to the BinaryBuilder system (PR for GR [here](https://github.com/jheinen/GR.jl/pull/339)), so I think letting those be broken would be tolerable (and a big improvement over the status quo of Julia on nix).

Perhaps we can get something working quickly by just patchelf'ing the official Julia builds for now? (I don't understand how all of this stuff works!)

**Comment by samuela** [comment]
Is there anything presently blocking just getting julia 1.5 into nixpkgs? I don't care about BinaryBuilder.jl/the Pkg.jl ecosystem working with nixpkgs, just a good ol' fashioned julia install.

**Comment by tbenst** [comment]
@samuela yes, see https://github.com/NixOS/nixpkgs/pull/98043

**Comment by cmcaine** [comment]
If you just want Julia and don't mind about binary packages breaking you
can just download Julia from the official site and patchelf it.

**Comment by cstich** [comment]
> @cmcaine I think this is quite doable. I would propose that we add a new package, [`julia-env` or similar](https://github.com/NixOS/nixpkgs/issues/70536#issuecomment-539146690), that is a "batteries included" build that contains system libraries for all common Julia packages. Would this approach work for BinaryBuilder? I haven't used this yet. If not, we could fall back to a FHSuserenv, but I'm reluctant to do so if at all avoidable as there are outstanding nix bugs ([ie this](https://github.com/NixOS/nix/issues/3597)) that create seg faults in some heavy data processing workflows.

On the [julia discourse](https://discourse.julialang.org/t/using-julia-with-nixos/35129/32) there was also the idea floated to patch `Artifact.jl` to patchelf dynamically loaded binary dependencies.

**Comment by solna86** [comment]
Guix has a Julia package and it works quite well. Perhaps some ideas can be borrowed from there: https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/julia.scm

It'd be really useful to get Julia working on Nix. It's the only big outstanding thing that doesn't work and prevents me from migrating some servers in my organization.

**Comment by doronbehar** [comment]
> Guix has a Julia package and it works quite well. Perhaps some ideas can be borrowed from there: [git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/julia.scm](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/julia.scm)

I tried to copy their expressions in https://github.com/NixOS/nixpkgs/pull/98043 and it doesn't work yet, but there's also another seemingly working attempt by @cstich at https://github.com/NixOS/nixpkgs/pull/101933 .

**Comment by doronbehar** [comment]
So, do we want anything else now that 1.5.3 is packaged (:green_heart: @cstich) ? I think we:

1. Don't need `julia_13`
2. Can clean up the expressions a bit - not use the `shared.nix` file if it's not shared.

I did (2) along with the julia_10 fix in https://github.com/NixOS/nixpkgs/pull/103783. As for (1) I will need a bit of feedback.

**Comment by 7c6f434c** [comment]
I guess some people like me still use julia_13 via test-disabling overrides, so a bit of time after 1.5 reaches channels for smooth transition could make sense?

**Comment by tbenst** [comment]
Maybe backport 1.5 to 20.03?

**Comment by doronbehar** [comment]
OK so I disabled the tests for julia_13 in https://github.com/NixOS/nixpkgs/pull/104166 and made `julia_15` the default `julia` there as well. All merged pull requests referenced here should be backported.
