### ISSUE TITLE
Splitting Calligra Suite into multiple packages

### ISSUE THREAD

**Issue by Epitrochoid** [NixOS/nixpkgs#9238]
Currently the Calligra suite is a single package containing all ten programs that make it up. For many users (including me) it would be more convenient and save disk space to have individual packages for each program in the suite.

Are there other users who would prefer individual packages for each program? If so what would be the best way to implement this? A multiple outputs package was suggested on IRC which would have the benefit of not massively increasing build times for users of the entire suite.

cc (current maintainers) @urkud  @Phreedom

**Comment by vcunat** [comment]
Noone can mind such a change. We could then even easily provide a meta-package containing all. However, achieving it can get tricky...

**Comment by Epitrochoid** [comment]
I'd be happy to put some time towards achieving it. Does anyone know of some packages doing something similar that I can look at?

**Comment by vcunat** [comment]
The mechanism for producing multiple outputs is relatively simple: you define `outputs = [ "foo" "bar" ];` and then you put stuff into `$foo` and `$bar` directories. You can have a look at `mesa_noglu`, for example.

**Comment by Phreedom** [comment]
Separating packages by hand like that could be 
tricky. KDE guys love frameworks, and your splitting 
code could break newer releases. However, if the 
build system itself lets you build applications 
separately, then it makes sense to rely on upstream 
for splitting the package.

I wouldn't do it as a multiple-output derivation 
though. Just make the meta-package propagate all 
the separate calligra application packages.

**Comment by vcunat** [comment]
Yeah, I suppose the packaging is similar to KDE &ndash; @ttuegel probably has the most knowledge about that around here, so he may have some advice.

**Comment by ttuegel** [comment]
It really all depends on Calligra's build system. If it supports building the programs separately, it should be easy. If it doesn't support building them separately, but it will install them to different locations, you can use multiple outputs. If it doesn't support either mode, you'll have to resort to patching the build system. If the build system is CMake, you can try building subdirectories of the whole package by giving an explicit target to the `cmake` command; I have had (limited) success with that approach.

**Comment by Epitrochoid** [comment]
I just sent out a pull request that builds Krita as a standalone package using the built in cmake option. If this works for everyone I can do the same for the rest of the suite (it will take a few days, the source builds take forever).

**Comment by vcunat** [comment]
The calligra apps share various libs and other stuff. If we just build apps one by one like this, the libs will be re-built (and take space) for each separately. It would be better to split away the shared dependencies into other separate derivations; an example of factoring the suite can be [seen in Debian](https://packages.debian.org/source/stretch/calligra).

I understand such splitting might take quite some work, depending on whether these shared libs will be detected when added into build inputs, so that step can be done later if you prefer. Just note that for someone using may calligra parts the solution-in-progress might be significantly worse than the current one. In Debian the shared calligra-libs take ~25 MB and calligra-data ~4 MB.

The internal dependencies seem relatively readable in `<source root>/CalligraProducts.cmake`.
