### ISSUE TITLE
vscode insiders is not actually insiders version.

### ISSUE THREAD

**Issue by tcztzy** [NixOS/nixpkgs#92565]
**Project description**
https://github.com/NixOS/nixpkgs/blob/fc553c0bc5411478e2448a707f74369ae9351e96/pkgs/applications/editors/vscode/vscode.nix#L27-L35

**Metadata**

* homepage URL: https://code.visualstudio.com/
* source URL: https://vscode-update.azurewebsites.net/${version}/${plat}/insiders
* license: nofree
* platforms: unix, linux, darwin, windows

**Comment by eadwu** [comment]
It isn't suppose to be, afaik, the source url you provided links to the latest insiders build (I believe), which can change on as often as 2-4 times a day (depending on releases).

The `isInsiders` is suppose to provide compatibility for a source that is of an insiders build, thus why it's called "is insiders" and not "insiders" or "to insiders". Though it is a problem in part because I never really documented it since I didn't see anyone using the insiders build when I made the change.
