### ISSUE TITLE
xdg-desktop-portal-gtk breaks font hinting

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#93199]
**Describe the bug**
I noticed that enabling some XDG options, it breaks my GTK fonts:

```
    # disable, making fonts look terrible in wofi/termite
    #xdg.portal.enable = true;
    #xdg.portal.gtkUsePortal = true;
```

Then when working on firefox and pipewire-0.3 patching today, I noticed this in @calbrecht's repo: https://github.com/calbrecht/nixpkgs-overlays/blob/11e28f1b10e48446811839680dec66691b57667b/nixpkgs/pkgs-overlays/xdg-desktop-portal-gtk/default.nix

```nix
self: pkgs:
pkgs.xdg-desktop-portal-gtk.overrideAttrs (old: {
  buildInputs = old.buildInputs ++ [
    # portal needs schema org.gnome.settings-daemon.plugins.xsettings
    # else it will not hint the fonts
    pkgs.gnome3.gnome-settings-daemon
  ];
})
```

It looks like we might want to fix this in nixpkgs.

**Comment by jtojnar** [comment]
Right, looks like it is required since at least 1.5.0:

https://github.com/flatpak/xdg-desktop-portal-gtk/commit/0aa1006e355e2ad6bc57ea7d49ebf7e239af7c2e

**Comment by mweinelt** [comment]
I still experience font hinting issues when enabling `gtkUsePortal` on 98d2d8cfbed. I'm using sway. Is the option only supported when actually running a GNOME environment?

**Comment by colemickens** [comment]
I haven't had issues in Sway since this was merged: https://github.com/NixOS/nixpkgs/pull/93307

**Comment by mweinelt** [comment]
Ah, I was missing `xdg-desktop-portal-gtk` in extraPortals, after I added that the hinting went back to being fine. Screensharing also work now \o/

**Comment by layus** [comment]
I do not know if my config has anything special, but with current nixos-unstable (21.03pre259928.2f47650c2f2 (Okapi)) I do experience the issue.

```nix
{
  xdg = {
    icons.enable = true;
    portal = {
      enable = true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
        xdg-desktop-portal-wlr
      ];
      gtkUsePortal = true;
    };
  };
}
```

Even stranger: `ps axu | grep portal` show no `-gtk` nor `-wlr` portal running, only plain `xdg-desktop-portal` processes.

I am a bit lost here. Just reverted for now, but I am far from making https://github.com/calbrecht/nixpkgs-overlays work.

**Comment by calbrecht** [comment]
Sorry to read that @layus. Since September 2020 the overlay is obsolete, that is, all patches that i had copied in there, are present and meanwhile updated/outdated in `nixpkgs` master. I updated the [Readme](https://github.com/calbrecht/nixpkgs-overlays/blob/master/Readme.md) to reflect that, also added links to the resources i use to debug problems with the setup.

Also, it [seems to be mandatory](https://github.com/NixOS/nixpkgs/pull/106815#issuecomment-751231083) to add to `~/.config/sway/config`
```
exec systemctl --user import-environment
```

**Comment by layus** [comment]
Investigating further. It seems that if I `systemctl --user import-environment` and restart dbus afterwards it works correctly.

AFAIU the challenge is to get xdg-desktop-portal and co. to have access to env vars defined by sway.
Adding `systemctl --user import-environment` does not work because at that time dbus is already started when sway starts.
My workflow is 
1. login to tty and get a zsh login shell
2. type `sway` in that shell.
logind starts dbus on login. Too early for me.

Another option seems to use `dbus-update-activation-environment --systemd --all`. This should work for the portals that have not yet been activated. But if your sway config starts applications (mine starts firefox and waybar) then it gets racy. Will report here my attempts.

@calbrecht Could you explain how you are running sway ? I cannot believe it only fails for me.

**Comment by calbrecht** [comment]
@layus sure. It is nearly the same as you do manually, with the difference that i do `exec sway` and so replace the shell, if i understand correctly.

```nix
{
environment.interactiveShellInit = ''
    if test `tty` = /dev/tty1; then
       exec sway
    fi
  '';
}
```

**Comment by layus** [comment]
Hmmm. I do not see what it could possibly change. Still, yet another thing to test :-D

**Comment by calbrecht** [comment]
I don't know maybe you need both of those at the end of your `~/.config/sway/config`

```
exec systemctl --user import-environment
exec systemctl --user start graphical-session.target
```
like stated in https://github.com/NixOS/nixpkgs/pull/106815#issuecomment-751129627. I just did not mention it because for @fadenb it did not seem to be required.

**Comment by layus** [comment]
Well, I have discovered that my setup was "polluted" by the gdm display-manager that I kept in another tty for easy switching to X11 when I needed advanced screencasting in Teams :-).

This gdm spawned its own dbus, and mingled in various ways with nixos config. I have to test again everything. I guess it was also responsible for starting the graphical-session.target

I wonder who is responsible for starting dbus in your setup. I guess it is socket-activated. Just checked. It is indeed. That also explains why exec systemctl --user import-environment works.

It is a bit unfortunate that you cannot start gdm besides sway. I will have to figure out how to install it without starting it at boot. Or just make screencasting work in sway and forget X11 forever :tada:
