### ISSUE TITLE
Shouldn't environment.homeBinInPath put ~/bin at the end of $PATH instead?

### ISSUE THREAD

**Issue by egasimus** [NixOS/nixpkgs#93723]
I like the idea of having a a system-sanctioned user-writable `bin` directory a lot, because it really lowers the barrier to entry for user scripting, and giving users somewhere to collect the entry points for their custom programs is good UX.

However, as it stands right now, I would definitely *not* toggle that feature on my system, and here's why:

https://github.com/NixOS/nixpkgs/blob/69af91469be26a8d28052f3d8de6d48c0b5e05bc/nixos/modules/config/shells-environment.nix#L198

Putting `~/bin` at the very beginning of the system `PATH` leaves the door open for a malicious script dropped in there to silently override any program - e.g. a fake `ls` wrapper can trivially `curl -X POST` a SSH private key, then delete itself, leaving no trace that the user has just been compromised without even having to elevate privileges. (Of course, how that script would end up there is a different part of the story.)

Sandboxing tools like Firejail or AppArmor are meant to mitigate exactly such scenarios - but those aren't enabled by default, either. So, should this setting be changed (or an alternative one added) to append `~/bin` to the end of the path instead (maybe also allow for a custom directory such as `~/Scripts` to be specified?) Any thoughts?

**Comment by 8573** [comment]
While I too would appreciate protection against such an attack, I don't think moving `~/bin` to the end of `PATH` is enough:  any program with write access to `~/bin` presumably also has write access to, e.g., `~/.bashrc`, so it could put `~/bin` at the start of `PATH` in `~/.bashrc` (and other shells' equivalents) and then install in `~/bin` a malicious `ls` that undoes the edit to `PATH` before deleting itself.

Moving `~/bin` to the end of `PATH` *could* help prevent people from *accidentally* breaking things by writing a script that happens to have the same name as a system program, although this is maybe less of a problem in NixOS because (as I understand it) NixOS-packaged programs generally should call other programs by the latter's store paths rather than by `PATH`.

If I *want* to override some system package's program, I find it easy enough to do so in my NixOS configuration.  I expect some people would insist on not being forced to take the time to `nixos-rebuild` to do so, but then one can always change `PATH` in one's shell rc script.

**Comment by Infinisil** [comment]
And also, if some program can write to `~/.bin`, it can also just read `~/.ssh` directly, no need to mess with overriding binaries. As soon as you run malicious code with full user permissions, it's game over, unless you protect against that with apparmor or so.

**Comment by abathur** [comment]
I am not really _a decider_, but I'm closing since it sounds like there's some agreement that this is a ~wontfix. Happy to reopen if you disagree. 

(I guess one way to pursue this might be to add config that governs where this and the localbin equivalent get added to the PATH, and hash this out in the context of what the best default is.)
