### ISSUE TITLE
Customizing vim breaks remembering last file position

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#94350]
On 20.03, when I use 

```nix
{
  environment.systemPackages = with pkgs; [
    vim
  ];
}
```

vim remembers the last file position when re-opening a file, but when using `vim_configurable.customize { ... }`, it no longer remembers it and upon each file open sets it to the beginning of the file (quite annoying).

Example such configuration from https://nixos.wiki/wiki/Editor_Modes_for_Nix_Files#vim-nix:

```nix
{
  environment.systemPackages = with pkgs; [
    (vim_configurable.customize {
      name = "vim";
      vimrcConfig.packages.mypackage = with pkgs.vimPlugins; {
        start = [ vim-nix ]; # load plugin on startup
      };
    })
  ];
}
```

Similar to #25970, using just `vim_configurable` without `.customize` does not have the issue.

**Comment by doronbehar** [comment]
Why _should_ Vim remember the last file position? I use https://github.com/zhimsel/vim-stay .

**Comment by teto** [comment]
when you use vim_configurable, vim stops reading your user configuration since it creates a wrapper that starts vim with `-u /nix/store/generate-vimrc`. Remembering cursor position is not a native feature so you lose the ability unless you copy the necessary config in vim_configurable with customRC for instance.
