### ISSUE TITLE
texlive.combined: toward less derivation references

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#94384]
```
nix path-info --store https://cache.nixos.org -rsS /nix/store/0d0p2m27smgbhcj5zsf8hx9s6lcxvxwk-texlive-combined-full-2019
```
Indicates there are about 3,700 references that have to be downloaded to realize the `texlive.combined.scheme-full` attribute. Most of these packages are pretty small, so I believe we are running into significant overhead from there being this many references.

@Infinisil suggested maybe we could incorporate `allowSubstitues = false;` to limit the number of references in the combined derivation.

cc @veprbl

**Comment by veprbl** [comment]
As far as I understand, disabling substitutes will completely disable Hydra caching. This is not expected to improve the download speeds.

If the number of references is too big, we could make full copies of the files instead of symlinks. But I'm not sure if Hydra is able to serve the big NAR's (#88045).

**Comment by ryantm** [comment]
I'm going to close this for now, since I don't plan on working on it soon.
