### ISSUE TITLE
Rename `inotifyTools` to `inotify-tools`

### ISSUE THREAD

**Issue by Havvy** [NixOS/nixpkgs#9456]
The pakage `inotifyTools` should be called `inotify-tools`, no?

**Comment by edolstra** [comment]
Yes.

**Comment by vcunat** [comment]
A mass rename of `camelCase` attributes to `dashed-style`?

We don't have a nixpkgs equivalent of nixos/modules/rename.nix, do we?

**Comment by edolstra** [comment]
At the bottom of `all-packages.nix` there is a section for aliases:
```
  # Attributes for backward compatibility.
  adobeReader = adobe-reader;
  ...
```

**Comment by vcunat** [comment]
Yes, but it would be nice if using deprecated aliases would print a warning during evaluation.

**Comment by copumpkin** [comment]
```nix
{
  adobeReader = builtins.trace "get yo act together" adobe-reader;
}
```

**Comment by vcunat** [comment]
Hmm, perhaps, we can save some typing by:
```nix
{
   # usual package definitions
  foo = bar;
} // lib.mapAttrs (name: builtins.trace "Warning: using a deprecated attribute '${name}'") {
  # Attributes for backward compatibility.
  adobeReader = adobe-reader;
  # ...
}
```

I tested this, and it looks good IMHO. Any reason not to have this change, even in 15.09?

**Comment by copumpkin** [comment]
I like it!

**Comment by Havvy** [comment]
The warning should be more specific.

`Warning: using a deprecated attribute '${name}'. Camel-case attributes have been switched out with dashes. For instance, instead of using 'inotifyTools', use 'inotify-tools'`

Note: If there's a more popular (and open) package, use that for the example than just inotifyTools.

**Comment by vcunat** [comment]
@Havvy: the deprecation of a name might be for different reasons, such us upstream renaming (cool-old-term -> cool-retro-term). We would have to split away this specific naming-unification group, which does make most of all deprecations ATM.

**Comment by vcunat** [comment]
Pushed adding the warnings. I'm not sure if the mass-replace should be in 15.09. It would perhaps be better to have more consistent naming between master and 15.09, as we could have some cherry-picking problems later.

**Comment by Mayeu** [comment]
Hello, I'm commenting here since I just saw those warning messages in my shell.

```
trace: Warning: using a deprecated attribute 'clangAnalyzer'. CamelCase and under_scores are replaced by dashed-names to match the nix-env names better.
trace: Warning: using a deprecated attribute 'cool-old-term'
```

From a user perspective, I have no clue what to do to deal with those messages/packages:
- Should I reinstall the package manually?
- Will nix take care of everything by itself now or in the future?
- If I should manually change the package, how do I find the new package name? And should I remove the old one? (for example in the case of 'cool-old-term', there is no info on why it is deprecated, and what is its new name)

I think there should be some kind of direction in this message, either pointing to an how-to URL, or even giving command to copy/paste to fix the issue.

And by the way, I **actually** have no clue of what would be the clean way to switch to the new package name ^^

**Comment by vcunat** [comment]
@Mayeu: if you are using the identifier `cool-old-term` (for example), how did you find out about it in the first place? Surely not by guessing. Most of the deprecated names are just aliases &ndash; if you use the new names, *nothing* changes except that the warning will disappear.

The message could explain all that, and it could also print the new attribute path, with some refactoring, but there is a more serious problem: ATM it throws this trace for **all** deprecated attributes when doing `nix-env -qa`, see comments on 8e8e23d.

**Comment by vcunat** [comment]
@Mayeu: anyway, the warnings are reverted for now.

**Comment by Mayeu** [comment]
@vcunat Thank for your response. Some packages are the one that I explicitly installed, and as you said, I did not guess them out of luck.  But other are just dependencies that I have no idea were installed. Thus questions ensue.

I really think NixOS is a great OS and is the right way of doing package management, and as a recent user I also see all the roughness it has right now. That's why I wanted to jump in to give some input from the *«common user»* point of view :)

**Comment by vcunat** [comment]
Feedback is welcome.

**Comment by vcunat** [comment]
For followup discussion see commit 8e8e23de337.
