### ISSUE TITLE
xdg user directories not working by default

### ISSUE THREAD

**Issue by jD91mZM2** [NixOS/nixpkgs#95276]
**Describe the bug**

When trying to share an XDG directory with flatpak, most of them don't work. Running `--filesystem=xdg-documents` has no effect on my system.

I traced it back to their code, and they use the function `g_get_user_special_dir` which does not work on a NixOS system.

**To Reproduce**

Try running the following rust code:

```rust
fn main() {
    println!("{:?}", glib::get_user_special_dir(glib::UserDirectory::Documents));
}
```

it should print `Some("/home/user/Documents")` or wherever your documents directory is, but it prints `None`.

Quick and dirty fix:

```nix
services.xserver.displayManager.sessionCommands = ''
  // Makes glib function `g_get_user_special_dir` work
  ${pkgs.xdg-user-dirs}/bin/xdg-user-dirs-update
'';
```

**Expected behavior**

I'd expect NixOS to run `xdg-user-dirs-update` out of the box, or at least have some option for it.

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10, NixOS, 20.09.20200725.ecafef0 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200721_ff314f1`
 - channels(user): `""`
 - channels(root): `"nixos-20.09pre236721.840c782d507"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

## Feature or bug?

I noticed that home-manager has `xdg.userDirs.enable` in their configuration. Is this not a bug in nixpkgs, perhaps, but rather left to the user's home management system?

**Comment by worldofpeace** [comment]
The xdg autostart in xdg-user-dirs runs it
```
[Desktop Entry]
Type=Application
Name=User folders update
TryExec=xdg-user-dirs-update
Exec=xdg-user-dirs-update
StartupNotify=false
NoDisplay=true

X-GNOME-Autostart-Phase=Initialization
X-KDE-autostart-phase=1
```

**Comment by jD91mZM2** [comment]
Ah, so it works in GNOME and KDE but no other session? (except for enlightenment which manually runs the binary)

**Comment by worldofpeace** [comment]
> Ah, so it works in GNOME and KDE but no other session? (except for enlightenment which manually runs the binary)

The two keys at the bottom for gnome and kde are directives to their session managers of when this autostart should be ran (at the very beginning). This autostart doesn't have like an `OnlyShowIn` which would prevent it from starting outside certain DE either. So I believe if this is installed and the DE supports the xdg autostart spec it will be ran.


By looking through nixpkgs https://github.com/NixOS/nixpkgs/search?q=xdg-user-dirs&unscoped_q=xdg-user-dirs I've added it in desktop environments that support it.

I think a similar situation came up in https://github.com/NixOS/nixpkgs/issues/61539 where people are using no desktop manager but a window manager. The solution for that issue was using the home-manager module which uses systemd services (while gnome-keyring doesn't have systemd services yet, and they'd probably depend on gnome session anyways).

We actually use this type of solution for nm-applet https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/nm-applet.nix#L11 (which I didn't exactly sign off on) because it's a popular program for those aforementioned users. I think it would be possible to do the same with xdg-user-dirs-update. Arch linux does this with a user service https://github.com/archlinux/svntogit-packages/blob/packages/xdg-user-dirs/trunk/xdg-user-dirs-update.service.
Though, we would lose the directives to gnome and plasma's session managers. 

cc @jtojnar

**Comment by jtojnar** [comment]
Hmm, I would expect GLib to return some default value when xdg-user-dirs are not set but there does not seem to be a spec and GLib only does so for Desktop:

https://gitlab.gnome.org/GNOME/glib/-/blob/83a59e99ff816c1f3d7f92e7580d80b392883e49/glib/gutils.c#L2265-2278

Unlike xdg-user-dir, which falls back to home directory:

https://gitlab.freedesktop.org/xdg/xdg-user-dirs/-/blob/97ff189affdbf0d33c0f8e91d3fd5608f425ef96/xdg-user-dir-lookup.c#L181-185

**Comment by jtojnar** [comment]
I think WM users should make sure their sessions support XDG autostart as described in https://wiki.archlinux.org/index.php/XDG_Autostart. I would rather not add custom services as to not increase maintenance costs and avoid possible conflict with autostart file.

**Comment by jD91mZM2** [comment]
Wait, I can't seem to find such a desktop file... `dex -ad` returns an empty directory, seems to not be in any `$XDG_CONFIG_DIRS/etc/xdg` directory either
