### ISSUE TITLE
Firewall blocks ICMP requests by default

### ISSUE THREAD

**Issue by xfix** [NixOS/nixpkgs#95795]
**Describe the bug**
Firewall blocks ICMP requests (other than ping) by default. This breaks Path MTU Discovery causing tricky to debug network issues (especially when using VPNs). Either way, the way firewall is configured it blocks ICMP requests other than ping. See http://shouldiblockicmp.com/.

**To Reproduce**
Unfortunately, I don't know how to reproduce the issue. Trying to use VPN with a router may cause black holed connection, but it's not guarantee. You may want to modify router MTU settings.

**Expected behavior**
ICMP requests shouldn't be blocked by default.

**Screenshots**

**Additional context**

**Notify maintainers**

I don't know who mantains this module. @edolstra?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.03.2819.f0924dbf552 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(xfix): `""`
 - channels(root): `"nixos-20.03.2819.f0924dbf552, home-manager-19.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment]
Our firewall shouldn't block any ICMP responses due to the following rule:
```
-A nixos-fw -m conntrack --ctstate RELATED,ESTABLISHED -j nixos-fw-accept
```

That's e.g. why the following works:
```console
$ michael@jarvis> ping -c1 -t4 google.de
PING google.de (216.58.212.163) 56(84) bytes of data.
From de-fra01b-rc1-ae-53-137.aorta.net (84.116.191.173) icmp_seq=1 Time to live exceeded
```

I didn't have a good test setup for PMTUD at hand but it should work the same way.

Could you check if there's maybe something else going wrong? Or verify that the problem is indeed that the firewall drops the packets (e.g. if it only works once you add a rule to accept ICMP packets)?

If it's indeed due to the firewall then it's probably due to the VPN tunneling (or the VPN provider). In theory our setup only works if the ICMP response can be matched to an existing connection (which is IIRC done by looking at the ICMP data which "includes a copy of the entire IPv4 header, plus at least the first eight bytes of data from the IPv4 packet that caused the error message").

**Comment by xfix** [comment]
Yeah, that looks fair. Nevermind.

**Comment by vcunat** [comment]
IPv4 ping used to be disabled by default, but that was years ago: #12927.
