### ISSUE TITLE
Toolbox

### ISSUE THREAD

**Issue by tijolao** [NixOS/nixpkgs#96115]
**Project description**

It's a tool to create pet-container using Podman. The container is fully mutable and maps your user home to the container. 

**Metadata**

* homepage URL: https://github.com/containers/toolbox
* source URL: https://github.com/containers/toolbox
* license: Apache-2.0
* platforms: Linux

**Comment by zowoq** [comment]
I took a brief look at this a couple of months after it was rewritten in go. I'll post what I had if I can find it.

It uses meson/ninja as a build system which makes it kind of non-standard and a bit awkward to package compared to other go projects, might be easier to skip it and specify the build/install phases manually.

IIRC it also needed completion/profile.d paths to be patched in, had issues trying to mount other paths on NixOS and it wanted flatpak for some reason.

**Comment by mt-caret** [comment]
I also took a look at trying to get toolbox working a while back, and wrote a nix expression for building the package, but decided to try it out when podman is rolled out in a stable NixOS channel. Now that 20.09 is released, but I get cryptic errors like the following:

```
$ toolbox enter -v
level=debug msg="Running as real user ID 1000"
level=debug msg="Resolved absolute path to the executable as /nix/store/cnddgykvpjnh8a742vl8hcqr459ji0s6-toolbox-0.0.97/bin/toolbox"
level=debug msg="Running on a cgroups v1 host"
level=debug msg="Checking if /etc/subgid and /etc/subuid have entries for user delta"
level=debug msg="TOOLBOX_PATH is /nix/store/cnddgykvpjnh8a742vl8hcqr459ji0s6-toolbox-0.0.97/bin/toolbox"
level=debug msg="Toolbox config directory is /home/delta/.config/toolbox"
level=debug msg="Current Podman version is 2.1.1"
level=debug msg="Old Podman version is 2.1.1"
level=debug msg="Migration not needed: Podman version 2.1.1 is unchanged"
level=debug msg="Resolving container and image names"
level=debug msg="Container: ''"
level=debug msg="Image: ''"
level=debug msg="Release: ''"
level=debug msg="Resolved container and image names"
level=debug msg="Container: 'fedora-toolbox-31'"
level=debug msg="Image: 'fedora-toolbox:31'"
level=debug msg="Release: '31'"
level=debug msg="Checking if container fedora-toolbox-31 exists"
level=debug msg="Container fedora-toolbox-31 not found"
level=debug msg="Fetching containers with label=com.redhat.component=fedora-toolbox"
level=debug msg="Fetching containers with label=com.github.debarshiray.toolbox=true"
level=debug msg="Found 1 containers"
Error: container fedora-toolbox-31 not found
Entering container fedora-toolbox-30 instead.
Use the 'create' command to create a different toolbox.
Run 'toolbox --help' for usage.
level=debug msg="Inspecting mounts of container fedora-toolbox-30"
level=debug msg="Requires org.freedesktop.Flatpak.SessionHelper"
level=debug msg="Calling org.freedesktop.Flatpak.SessionHelper.RequestSession"
level=debug msg="Starting container fedora-toolbox-30"
level=debug msg="Inspecting entry point of container fedora-toolbox-30"
level=debug msg="Entry point PID is a float64"
level=debug msg="Entry point of container fedora-toolbox-30 is toolbox (PID=0)"
Error: invalid entry point PID of container fedora-toolbox-30
```

I might look into this further when I get the time, but people are welcome to look into this issue to try and fix it. Meanwhile, here's the nix expression to build it: https://github.com/mt-caret/nix-config/blob/55ca5a343feec9c0cdef9d6a035ac9e99d1d0208/packages/toolbox.nix
Note that in order to use toolbox on NixOS, you seem to need the following config:
```nix
{
  virtualisation.podman.enable = true;
  services.flatpak.enable = true;
  xdg.portal.enable = true;
}
```

People seem to be against usage of buildGoModule (see https://github.com/NixOS/nixpkgs/issues/84826), so if people are interested in seeing this in nixpkgs, someone probably needs to port this to buildGoPackage.

**Comment by tfmoraes** [comment]
Hi @mt-caret ,

I modified a little your nix expression https://github.com/tfmoraes/nixoscfg/blob/main/overlays/pkgs/toolbox/default.nix

I added a patch to check if `/mtn` exists (it not exists in my system for instance). I also changed to copy `profile.d/toolbox.sh` to `$out/share/profile.d/toolbox.sh` and it's mapping this file inside the container.

I'm having the same error. So I tried to start the container using podman, this way:

```
❯ podman start  --interactive  -a  fedora-toolbox-33                                                                                                                                                        
WARN[0000] cannot toggle freezer: cgroups not configured for container 
WARN[0000] lstat : no such file or directory            
standard_init_linux.go:219: exec user process caused: no such file or directory
```

Maybe the problem now is because o cgroups. I don't now.

**Comment by mjlbach** [comment]
I had to submit an upstream patch to fix an error introduced in newer builds with ownership of the toolboxRuntimeDirectory. I think this would be good to have, so I'm interested in carrying on the work. I was able to build toolbox (thanks for the derivation). The biggest issue seems to be this. Trying to start a container with `toolbox enter` yields:

```
DEBU[0000] Called inspect.PersistentPostRunE(/nix/store/h9was55f3ir6b2sq5vc96cpgns3qbfz0-podman-2.2.1/bin/podman --log-level debug inspect --format json --type container fedora-toolbox-32)
DEBU Entry point PID is a float64
DEBU Entry point of container fedora-toolbox-32 is toolbox (PID=0)
Error: invalid entry point PID of container fedora-toolbox-32
``

If you manually try to start this container:

```
❯ podman start  --interactive  -a  fedora-toolbox-32
{"msg":"exec container process (missing dynamic library?) `/usr/bin/toolbox`: No such file or directory","level":"error","time":"2021-01-22T11:20:35.000255349Z"}
```

You'll see the error. Looking through the source, it seems there are a lot of hardcoded paths we will need to substitute.

**Comment by mjlbach** [comment]
I have it running! Hello from vim installed via dnf. It's blocked by my upstream patch which you can follow here: https://github.com/containers/toolbox/pull/675
<img width="1278" alt="Screen Shot 2021-01-22 at 4 20 05 AM" src="https://user-images.githubusercontent.com/13316262/105490213-4db59780-5c69-11eb-9b8b-651743973138.png">
<img width="634" alt="Screen Shot 2021-01-22 at 4 21 13 AM" src="https://user-images.githubusercontent.com/13316262/105490227-5017f180-5c69-11eb-8a53-e81e4f06bc10.png">

**Comment by tfmoraes** [comment]
That's great @mjlbach!!! I think toolbox is a great tool to have in NixOS.

**Comment by mjlbach** [comment]
Agreed! Please test the PR if you have time :) Thanks for your work!

https://github.com/NixOS/nixpkgs/pull/110473

**Comment by debarshiray** [comment]
Very happy to see your interest in Toolbox!

> it wanted flatpak for some reason.

I just wanted to point out that Toolbox doesn't actually need Flatpak proper. It's just the `flatpak-session-helper` daemon which is a D-Bus session service that comes from `flatpak.git` but is completely separate from the rest of Flatpak. In fact, in Fedora, we ship it is a separate isolated sub-package. The purpose behind this daemon is to keep certain configuration files in the container's `/etc` synchronized with their counterparts in the host. eg., `/etc/resolv.conf`, `/etc/localtime`, etc..

Anyway, good news is that these days, since Toolbox 0.0.97, the `flatpak-session-helper` daemon is no longer used for newly created containers, because the functionality has been absorbed into Toolbox itself. One big reason was to enable rootful Toolbox containers (ie., `sudo toolbox create ...`). Older, preexisting containers will continue to use the daemon, though.

**Comment by debarshiray** [comment]
> See this [issue](https://github.com/containers/toolbox/issues/669). Seems
> that the reported issue occured when host and container
> glibc don't match. The toolbox binary gets bind-mounted
> into the fedora container, which may cause issues without
> the requisite store paths also being mounted.

Just a minor note. The actual issue is https://github.com/containers/toolbox/issues/529 See the related [commit](https://github.com/containers/toolbox/commit/6ad9c631806961f3382646e2a3529ddd00967971) for an explanation on how we solved it.

Ideas for better solutions welcome. :)

**Comment by tgharib** [comment]
This issue is important to me.

**Comment by i2** [comment]
Any update on this? Can this be merged to upstream and closed?

**Comment by debarshiray** [comment]
Is there anything that you need from the Toolbx project?

**Comment by mjlbach** [comment]
There are two remaining roadblocks. To clarify, I no longer use nixos and will probably not work on this (I still am an active toolbox user, just on Fedora :))

1. Handling glibc updates. Any time the hash of glibc changes in the nix store, all toolbox containers will break (and need to be recreated). I'm sure there is a clever way around this, either a service that runs after a nix-rebuild that updates the bind mounts, or patching toolbox to update the bind mount on each toolbox enter. These seem very nix (or guix) specific)

2. The SDDM issue, there's nothing I think toolbox should do about this. Nixpkgs could consider carrying the sddm patches until merged upstream.

Anyone is free to takeover https://github.com/NixOS/nixpkgs/pull/110473, I won't be continuing it. The PR "works" with the caveat of point 1 not being handled, so you'll have to periodically recreate toolboxes.

**Comment by tfmoraes** [comment]
@debarshiray after the container creation, it's possible to change the bind mounts and ports? Is there a file to edit?

**Comment by tfmoraes** [comment]
I found this alternative to toolbox https://github.com/89luca89/distrobox

**Comment by debarshiray** [comment]
> @debarshiray after the container creation, it's possible to change the bind
> mounts and ports? Is there a file to edit?

There's no support for doing it easily through a Toolbx-specific configuration file at the moment.

However, you can script something through one of the shell start-up scripts.
