### ISSUE TITLE
Newly introduced YAML formatter does not allow hexadecimal escapes (or other escapes) in strings

### ISSUE THREAD

**Issue by berbiche** [NixOS/nixpkgs#97310]
**Describe the bug**
YAML allows for hexadecimal escapes in strings and other escapes. The current `pkgs.formats.yaml` does not allow representing such escapes with its `generate` function.

Every escaped slash is doubled in a string which makes it impossible to represent `"\x0A"` (a valid hexadecimal escape sequence in YAML).

**To Reproduce**

``` nix
nix-repl> builtins.readFile "${(pkgs.formats.yaml { }).generate "test" "\\x0A"}" == "\"\\x0A\""
false
```

**Expected behavior**

I would expect the formatter to apply the same logic as home-manager's alacritty module does

``` nix
nix-repl> builtins.replaceStrings ["\\\\"] ["\\"] (builtins.toJSON "\\x0A")
"\"\\x0A\""
```

**Notify maintainers**

@rycee @Infinisil

**Additional context**

I am currently converting modules definitions in home-manager to use the appropriate `pkgs.formats.{json,yaml,ini}` and I encountered this issue when converting home-manager's alacritty definition to use `pkgs.formats.yaml`'s `generate` function.

**Comment by berbiche** [comment]
Relevant section of the spec https://yaml.org/spec/1.2/spec.html#id2776092

**Comment by Infinisil** [comment]
The real problem is that YAML supports hex escapes while Nix (and JSON) doesn't. So the Nix expression `"\\x0A"` means the literal string `\x0A` and not something else. So if the generator were changed to interpret this as a Hex escape with the suggested `replaceStrings`, you couldn't convert the literal string `\x0A` to YAML anymore.

So if you want to translate alacritty's YAML to the equivalent Nix, you need to insert the bytes themselves into the Nix file. `0x0A` is a newline, so that would be
```nix
{
  theValue = "\n";
}
```

So there's nothing to fix here, but what we could do is add something like `lib.hexByte` to nixpkgs, which could translate `"0a"` to the byte it represents.

**Comment by berbiche** [comment]
Would `lib.hexByte` work even if the user does not control the resulting string (in the case of `(pkgs.formats.yaml {}).generate`)?

**Comment by Infinisil** [comment]
`lib.hexByte` would work anywhere in Nix, independent of the generator.

Nix also doesn't have a way to escape unicode with some `\u`, so you can again just insert the unicode character literally.
