### ISSUE TITLE
Help with creating a ZFS-root ARMv7 image

### ISSUE THREAD

**Issue by shadowrylander** [NixOS/nixpkgs#97639]
Hello!

What the title says; could anyone help me create, or create for me, the most basic ZFS-root ARMv7 image possible, using the zfsUnstable package? I'm having a lot of trouble installing through cross-compiling to an SD Card, with both the ARMv7 and Aarch64 architectures.

Thank you kindly for the help!

**Comment by Atemu** [comment]
You should put support requests on the Discourse, subreddit, IRC/Matrix or similar, it'll get drowned here. Even I just happened to find this by chance.

I'd recommend you to flash the official aarch64 sd_image onto one storage device, boot it on your device and, from the booted device, format another storage device to your liking and install NixOS just like on an x86 desktop.

Armv7l doesn't have an official binary cache and the inofficial one I know of stopped working 2mon ago, you'd have to build everything.  
Cross compilating NixOS is broken currently, so your options are to either cross compile an older NixOS (probably >6 months, no idea when exactly it broke this year) or build it natively.
Since you've got an aarch64 device, I'd go with the latter; it should be able to run armv7l instructions.
Absolute minimum for RAM is 1GB and that needs lots of zram and even single core builds at some points. It should preferably have >=2GB. It'll be slow (as in, days for a full rebuild) but shouldn't be too horrible as a full rebuild should only be necessary a couple times per month.

Hope that helps.

**Comment by shadowrylander** [comment]
It does indeed! Although, I think I'll use `binfmt` instead, though; my systems may be considerably faster in this case. Thank you kindly for the information!

**Comment by Atemu** [comment]
It makes my Ryzen 3600 so slow, it's probably slower than natively building on my RPI2. Don't bother with binfmt unless you need the RAM.

Qemu-user/binfmt is also not perfect, it breaks at least one build.

**Comment by Atemu** [comment]
Also FYI: https://github.com/NixOS/nixpkgs/issues/106759

**Comment by shadowrylander** [comment]
Hmm... I guess I'll try building the config on my RPi3, then.
