### ISSUE TITLE
k3s: package k3s-killall.sh script

### ISSUE THREAD

**Issue by theduke** [NixOS/nixpkgs#98090]
**Describe the bug**

`k3s` provides a a `k3s-killall.sh` script that is required for orderly shutdown. (remove iptables rules, stop running containers, ...). Also `k3s-uninstall.sh` which cleans up all related directories.

Those is currently not included in the `k3s` package.

While not very complicated scripts, it would be nice to have them. (And track upstream changes)

**Notify maintainers**

@euank

**Comment by theduke** [comment]
Note that the scripts are created inside install.sh: https://github.com/rancher/k3s/blob/7ca50efb8b6c5218690e3f1a0a8df4b9843bb3e1/install.sh#L351

**Comment by euank** [comment]
I agree those are handy scripts to have around.
I think we may end up just wanting to fork em since the `systemd` related stuff won't work on nixos I think.

In a normal k3s installation, the systemd unit files are dropped in etc by `install.sh` and can be deleted / stopped reasonably.
On nixos, those systemd unit files are created / started / managed by the nixos module and nixos-rebuild, so having those scripts stop/remove them doesn't seem right.

For the other state nixos doesn't manage (the stuff in /var/lib*, running containers, etc), having those makes sense.

**Comment by euank** [comment]
There's a few additional choices here which add complexity.

It's sometimes desirable for resources to keep running when k3s is stopped, most notably it's usually desirable for kubernetes pods and networking to keep working during a k3s upgrade, during which the service is stopped and started.

The killall script expresses the intent that it's desired for all that stuff to go away, but `systemctl stop k3s` doesn't by itself.

**Comment by euank** [comment]
Still an issue, we just haven't gotten to it yet. Un-stale, stalebot

**Comment by jceb** [comment]
A partial workaround is to change k3s' service configuration to use `KillMode=mixed` as suggested here: https://github.com/k3s-io/k3s/issues/2400#issuecomment-711065914

```nix
systemd.services.k3s.serviceConfig.KillMode = mkForce "mixed";
```

Running `k3s-killall.sh` is still required + even after running it I still find a ton of active containerd units:

```bash
systemctl list-units|grep -i containerd
  cri-containerd-a65c2668f36e2a1eaf27f86440d3fcbede3c408ce7148b735f0818d670c3e6ff.scope
loaded active running   libcontainer container a65c2668f36e2a1eaf27f86440d3fcbede3c408ce7148b735f0818d670c3e6ff
cri-containerd-a6e5c4e8e0bce2088b59d26967031733b029e82fa6a168ed55e4add8a72c3555.scope
...
```

These remaining using can be easily because the processes have been properly killed by systemd, e.g. with `systemctl list-units|grep -i cri-containerd-|awk '{print $1}'|grep -v ●|xargs -r -P 10 -I {} bash -c "echo systemctl stop {}; systemctl stop {};"`

**Comment by yajo** [comment]
Isn't there a way to hook it automatically to shutdowns? Like adding it to `WantedBy=shutdown.target`?
