### ISSUE TITLE
15.09 UEFI install fails to boot with Nvidia (nouveau)

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#9893]
I just did a new UEFI installation of 15.09 on my desktop featuring an Nvidia graphics card. The installation succeeded however, when booting the system it got stuck. I guess it uses the nouveau driver by default. I solved it by using the proprietary nvidia driver 
```
services.xserver.videoDrivers = [ nvidia ];
```
and of course enabling the non-free packages
```
nixpkgs.config.allowUnfree = true;
```

Anyway, I thought it be good to add this here in case others get stuck with the same issue.

**Comment by vcunat** [comment]
The installer itself boots fine, right?

Nouveau might be chosen as the default by X, but it doesn't work everywhere IIRC. On Maxwell cards, "modesetting" driver [seems preferred](http://www.phoronix.com/scan.php?page=news_item&px=nouveau-drop-glamor-max). `/var/log/X.0.log.old` should show more details (unless you restarted X multiple times since then).

**Comment by vcunat** [comment]
Actually, our default `videoDrivers` is `[ "ati" "cirrus" "intel" "vesa" "vmware" "modesetting" ]`, so likely no nouveau would be tried.

**Comment by wkennington** [comment]
Afaik that doesn't prevent the kernel from loading the nouveau module and
breaking on newer cards when trying to modeset for the kernel terminal
buffer.

**Comment by vcunat** [comment]
No, but I don't see how else would X find the nouveau module; perhaps we should provide it to better handle X on nvidia without specifying `videoDrivers`.

This is likely completely separate thing from console breaking due to KMS (which is what the report looks like).

**Comment by wkennington** [comment]
Well, he says it got stuck booting the system but doesn't say where. My
guess is that it is the same issue with the kernel driver putting nouveau
in an unusable state for the iso when used with new cards. The reason
everything is fine when you enable the proprietary driver is because it
blacklists the kernel modules which cause it to normally fail. It may not
actually be an issue of xorg, but a side effect of enabling the proprietary
driver there.

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/video/nvidia.nix

**Comment by vcunat** [comment]
Yes, those were my thoughts as well.

**Comment by FRidh** [comment]
The installer booted indeed just fine.

I was using a `configuration.nix` generated by `nixos-generate_config` and did not modify it. Therefore, if I am correct, it shouldn't even have installed X at that point. It seems plausible that indeed some other kernel module is blacklisted in the case of the proprietary driver.

Tonight I'll boot into the old configuration and have a look afterwards at the logs.

**Comment by FRidh** [comment]
It was indeed a nouveau issue.
```
Sep 17 18:56:49 nixos kernel: nouveau E[  DEVICE][0000:01:00.0] unknown chipset, 0x124020a1
Sep 17 18:56:49 nixos kernel: nouveau E[     DRM] failed to create 0x00000080, -22
Sep 17 18:56:49 nixos kernel: nouveau: probe of 0000:01:00.0 failed with error -22
```
I have a GTX 970 'Maxwell' which isn't supported until Linux 3.19 whereas I'm running 3.18.21.
http://www.phoronix.com/scan.php?page=news_item&px=MTg4NTg

**Comment by FRidh** [comment]
@vcunat the order you refer to is the one specified in here, right?
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/xserver.nix

But I hadn't enabled X yet, and therefore that expression isn't taken into account. I believe that because of that, nouveau is still loaded automatically on machines which haven't enabled `xserver`.
I had X still disabled,

**Comment by vcunat** [comment]
I was listing stuff around X modules, but your "nouveau" is the kernel module which is useful without X as well (high-resolution console mainly, I suppose).

**Comment by ttuegel** [comment]
Please open an issue for 16.03 if this persists.
