### ISSUE TITLE
lensfun can't update lens database

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#99009]
**Describe the bug**

`lensfun-update-data` fails requiring `python3` installed, and even then fails to load a necessary python module 

```
$ lensfun-update-data
/usr/bin/env: ‘python3’: No such file or directory
```

```
$ nix-shell -p python3 --run lensfun-update-data
Traceback (most recent call last):
  File "/nix/store/cgcad5zjda9zpn0vlb30rbzpvd6cpcfr-lensfun-2020-09-25/bin/lensfun-update-data", line 46, in <module>
    import lensfun
ModuleNotFoundError: No module named 'lensfun'
```

**To Reproduce**

- Enter a shell with `lensfun` installed
- run `lensfun-update-data` 
- Observe the above error

**Expected behavior**

The database in `.local/share/lensfun` is updated

**Additional context**

The lensfun derivation needs to install the generated python modules, and wrap the `lensfun-update-data` executable with a wrapper which provides `python3` and an appropriate `PYTHONPATH`

**Notify maintainers**

@enzime

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.62, NixOS, 20.09.git.4a755116d57 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/home/j/src/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - lensfun
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
I took a quick look at the script - it apparently expects stuff to be in `/usr/{local/}share/lensfun` - which won't work on NixOS.

Also, both "update servers" (`http://lensfun.sourceforge.net/db/` and `http://wilson.bronger.org/lensfun-db/`) seem to be offline, and https://lensfun.github.io/ has a blog post from early 2019 searching for new maintainers.

There seem to be some updates in their git repo - instead of trying to hack the updater into some working state, we should probably just *not* ship the lensfun updater scripts at all, and replace `$out/share/lensfun/version_2` should contain a more recent snapshot of the database - either by doing this in nixpkgs, from a snapshot, or by helping out upstream with a new release ;-)

**Comment by flokli** [comment]
Highlighting darktable nixpkgs maintainers and editors: @cillianderoiste @flosse @mrVanDalo @danieldk @adisbladis

**Comment by flokli** [comment]
I opened https://github.com/NixOS/nixpkgs/pull/108991 which should ship a more recent lensfun database.

**Comment by expipiplus1** [comment]
Thanks!
