### ISSUE TITLE
xorg.fontbhlucidatypewriter100dpi: gentoo says it's public domain, nixpkgs says it's unfree - who's right?

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#99014]
Getting the following error

```
error: Package ‘font-bh-lucidatypewriter-100dpi-1.0.3’ in /home/maciej/Projekte/nixpkgsv/pkgs/servers/x11/xorg/default.nix:241 has an unfree license (‘unfree’), refusing to evaluate.
```

xorg/overrides.nix says it's unfree

```
    # unfree, possibly not redistributable
    unfree = [
      # no license, just a copyright notice
      "fontbhlucidatypewriter100dpi"
      "fontbhlucidatypewriter75dpi"
      "fontdaewoomisc"

      # unclear license, "permission to use"?
      "fontjismisc"
    ];
```

gentoo package says it's public domain

https://packages.gentoo.org/packages/media-fonts/font-bh-lucidatypewriter-100dpi

Now the question is: Which one is correct? Should we just "go with the flow"?

**Comment by jonringer** [comment]
related: #99136

**Comment by rnhmjoj** [comment]
This came up while I was working on converting core X11 fonts to newer formats.
Before distributing modifications which we are not allowed to make I checked what the actual license was and discovered many fonts were actually proprietary with only a permission to "use" or "display" and distribution given to the X.org.

Regarding lucidatypewriter, the [source code](https://gitlab.freedesktop.org/xorg/font/bh-lucidatypewriter-75dpi/-/blob/master/COPYING) doesn't contain any license information except a copyright notice, from which I assumed the author reserver all their rights. I don't known where gentoo is getting that information. I'll try asking around.

**Comment by rnhmjoj** [comment]
So, I asked at #xorg and they have no idea. 
I've found this [document](https://www.x.org/releases/X11R7.7/doc/xorg-docs/License.html) which contains a license agreement with B&H (the designers) for the use of the Luxi fonts but there is no mention of other B&H fonts.
My theory is that this agreement is included here because it was made directly with the (defunct) X Consortium in 2001 when Luxi was released but the Lucida fonts are much older (1984) so the agreement must have been with an older organization (MIT, [OSF](https://en.wikipedia.org/wiki/Open_Software_Foundation), whatever) and someone never bother to copy the legal notice when the font was included into X.

In any case, since licenses for Lucida are being sold by Linotype, I doubt that it's in the public domain and can be considered free, by the FSF definition of it.

**Comment by rnhmjoj** [comment]
Unless someone hires a lawyer or manages to contact the copyright holders, I don't think there's much to do here. I'm closing the issue.

**Comment by deviant** [comment]
@rnhmjoj AFAICT the license for the Lucida Typewriter fonts are supposed to be the same as those for the plain Lucida fonts. Note that the Lucida Typewriter copyright lines are found in the license text of the latter. I'm not really sure why these are in different repositories, nor how this was laid out when they were in previous version control systems.

[gitlab.fd.o/xorg/font/bh-lucidatypewriter-75dpi@master/COPYING](https://gitlab.freedesktop.org/xorg/font/bh-lucidatypewriter-75dpi/-/blob/master/COPYING)
[gitlab.fd.o/xorg/font/bh-lucidatypewriter-100dpi@master/COPYING](https://gitlab.freedesktop.org/xorg/font/bh-lucidatypewriter-100dpi/-/blob/master/COPYING)
[gitlab.fd.o/xorg/font/bh-75dpi@master/COPYING](https://gitlab.freedesktop.org/xorg/font/bh-75dpi/-/blob/master/COPYING)
[gitlab.fd.o/xorg/font/bh-100dpi@master/COPYING](https://gitlab.freedesktop.org/xorg/font/bh-100dpi/-/blob/master/COPYING)

I would also note that the Debian package for these isn't marked as non-free: [[package]](https://packages.debian.org/sid/xfonts-75dpi) [[copyright]](https://metadata.ftp-master.debian.org/changelogs//main/x/xfonts-75dpi/xfonts-75dpi_1.0.4+nmu1.1_copyright)

I found a mailing list entry from the package maintainer: https://lists.debian.org/debian-x/2017/03/msg00145.html

Specifically the argument is that since these are bitmap fonts, they're not copyrightable anyway. I would probably trust Debian on this, since they have one of the most hardcore positions on licensing.

I also found [RH#317641](https://bugzilla.redhat.com/show_bug.cgi?id=317641) where Red Hat audited the licenses of all the X.org/X11 fonts they were packaging. Lucida Typewriter was not removed, even though Luxi (also made by B&H, and the successor to Lucida) was. The distinction here is that Luxi are TTF, not bitmap fonts, and thus count as code, which is copyrightable. I ANAL, but this matches up with my understanding of US copyright law and typefaces. As such, I'm going to create a PR to change this. I would also note that `xorg.fontbhlucidatypewriter75dpi` being marked as unfree breaks tightvnc, tigervnc, and possibly some other packages depending on it, which is how I came across this issue in the first place.

**Comment by rnhmjoj** [comment]
> the license for the Lucida Typewriter fonts are supposed to be the same as those for the plain Lucida fonts

It makes sense, but the COPYING file only mention "Lucida". I may be dense here but "Lucida Typewriter" could be regarded as a different font for all I know.
If the license applies, the font would at best be `unfreeRedistributable`, how can it be free with the non-modifiable clause?

I'm also not convinced by the argument that bitmaps can't be copyrighted because they're not the "font" (in the french sense): there are plenty of bitmap fonts that are not derived from a vector specification and surely the authors claim copyright on them. Moreover, the COPYING file is claiming copyrights on the "bit-mapped images".
