### ISSUE TITLE
doas: fails with a "doas: not installed setuid" error

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#99101]
**Describe the bug**
Running `doas ${command}` fails with a message "doas: not installed setuid" displayed on terminal. The error message means that [the effective UID obtained by `geteuid` is not 0 (root)](https://github.com/Duncaen/OpenDoas/blob/v6.6.1/doas.c#L325-L326), which indicates that the executable is intended to be installed with the setuid bit set.

I have confirmed that `doas -C /etc/doas.conf` works as expected as the command checks the configuration file and exits before the `if (geteuid())` statement.

**To Reproduce**
1. Run `echo permit nopass :wheel | sudo tee -a /etc/doas.conf`.
2. Run `nix-shell -p doas --run "doas -C /etc/doas.conf"`.
3. Run `nix-shell -p doas --run "doas true"`.

**Expected behavior**
The `nix-shell` commands in 2. and 3. exits with no output.

**Screenshots**
![image](https://user-images.githubusercontent.com/167209/94565481-3ca0df00-02a4-11eb-83c7-e036b80885d6.png)

**Notify maintainers**
@cole-h and @cstrahan 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.12, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre-git"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - doas
# a list of nixos modules affected by the problem
module:
```

**Comment by cole-h** [comment]
This is because we can only suid the doas binary declaratively using `security.wrappers` -- you cannot use doas (or even sudo) from a nix-shell if they have not been wrapped by that NixOS module.

It is not possible (AFAIK) to install a suid binary to the store, which is why `security.wrappers` is necessary. To use doas, you need to enable the module, which sets up the wrapper for you.

Unfortunately, to the best of my knowledge, there's nothing that can be done to get a suid binary inside a nix-shell.

**Comment by cole-h** [comment]
Closing this, as there's nothing that can be done that wouldn't have far-reaching security implications (like the ability to store suid binaries in the store). Sorry about that :(

**Comment by omasanori** [comment]
@cole-h Thank you for your kind and detailed explanation!
