### ISSUE TITLE
Pantheon: can't login after suspend/resume

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nixpkgs#99668]
**Describe the bug**

Using nixos-unstable channel, I can't log back into my pantheon session after a suspend/resume.
I can reproduce this on 3 laptops.

**To Reproduce**

Define pantheon as the default desktop manager, don't enable lightdm or sddm (it's implied by pantheon)
`services.xserver.desktopManager.pantheon.enable = true;`

Log in your session, suspend computer and resume. On the login screen, when you type your password you get an error "Unable to Log In, starting the session has failed" with details "Session returned error code 1"

**Expected behavior**

User log back into their session

**Screenshots**

Can't take a picture because I can't log back.

**Notify maintainers**
@worldofpeace 

**Metadata**

- system: `"x86_64-linux"`
- host os: `Linux 5.4.67, NixOS, 21.03pre244932.84d74ae9c9c (Okapi)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.7`
- channels(root): `"nixos-21.03pre244932.84d74ae9c9c"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Thanks for reporting. This is really interesting because I've suspended and resumed loads of times on nixos-unstable with pantheon. I'm going to check if that is still the case tomorrow :+1:

**Comment by rapenne-s** [comment]
Even easier to reproduce, Using "Lock" in the lock/logout/shutdown menu produce the same issue. No need to suspend/resume (which was locking the session before suspending I guess).

**Comment by rapenne-s** [comment]
> Even easier to reproduce, Using "Lock" in the lock/logout/shutdown menu produce the same issue. No need to suspend/resume (which was locking the session before suspending I guess).

Even even easier to reproduce. If I logout or that I don't use autologin I can't log myself in Pantheon from the display manager.

**Comment by DavidOliver** [comment]
New NixOS user here, with this issue on a couple of machines in 22.11 stable. @rapenne-s, I see you closed this issue in September - do you know if it's somehow solved/fixable?

Anyway, if I remember correctly, I read that at some stage Pantheon's own greeter was retired from use as it caused too many issues. However, the lock screen looks very Pantheon'esque, and the current documentation says that Pantheon's greeter is used by default.

I have logs for locking and trying to unlock from journalctl for both machines, in case that would be useful.

`/var/log/lightdm/seat0-greeter.log`:

> (io.elementary.greeter:3551): Handy-WARNING **: 22:33:02.894: Failed to load icon: Error opening file /home/david/.face: Permission denied
> 
> ** (io.elementary.greeter:3551): CRITICAL **: 22:33:02.919: MainWindow.vala:358: prompt: `Password: ' (1)
> 
> ** (io.elementary.greeter:3551): CRITICAL **: 22:33:03.132: MainWindow.vala:358: prompt: `Password: ' (1)


My `configuration.nix`:

```nix
  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the Pantheon Desktop Environment.
  services.xserver.desktopManager.pantheon.enable = true;
```

Mentions of a couple of people I've seen involved in this and other Pantheon issues: @worldofpeace , @davidak .

---

I've just found that I can use another greeter (gtk) to successfully log back in after either locking and suspending, so that's good.

```nix
  # Enable the Pantheon Desktop Environment.
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.displayManager.lightdm.greeters.pantheon.enable = false;
  services.xserver.displayManager.lightdm.greeters.gtk.enable = true;
  services.xserver.desktopManager.pantheon.enable = true;
```

---

And now I've found that on my desktop, shortly after resuming, both Firefox and the default web browser can't successfully load TLS/https webpages. That seems non-greeter related, and I'll try on my laptop and perhaps make a new issue.
