### ISSUE TITLE
ghc-android

### ISSUE THREAD

**Issue by wavewave** [NixOS/nixpkgs#9973]
I succeeded in making ghc a cross compiler for android using nix: https://github.com/wavewave/nix-build-ghc-android  
Note that this uses ghc-7.10.2 and android ndk r10c, very up-to-date. Tested with LG G4 phone.
It will be great if ghc-android is well-supported in the official nixpkgs. This issue is a reincarnation of issue #6582

**Comment by copumpkin** [comment]
What will nixpkgs integration and good support look like?

**Comment by wavewave** [comment]
I am thinking of ghcjs-like support by putting `configuration-ghc-android.nix` in `pkgs/development/haskell-modules`. Ideally, we can also provide binary files for haskell packages for android. I found that building ghc and haskell packages with ghc cross compiler and cabal for android is not very different from ordinary haskell build on linux. Hopefully, it would not take much effort.

**Comment by wavewave** [comment]
Success in making an android app with haskell!  See [haskell-android-example](https://github.com/wavewave/haskell-android-example). I built this on `adb-fhs-shell.nix` in [nix-build-ghc-android](https://github.com/wavewave/nix-build-ghc-android) (FHS environment built by `buildFHSUserEnv`). Currently, the sample app shows number of available CPUs from haskell on GUI `TextView`.

**Comment by wavewave** [comment]
I've succeeded in incorporating ghc-android with current haskell-module system in nixpkgs. So one can use ghc-android like this:  
https://github.com/wavewave/nix-build-ghc-android/blob/3d8169d79cab8a28d4325677ecb8929c5a06ff73/shell.nix#L9

Changes that I did in nixpkgs is presented in this directory: https://github.com/wavewave/nix-build-ghc-android/tree/3d8169d79cab8a28d4325677ecb8929c5a06ff73/nixpkgs

It's fairly similar to how to handle ghcjs. Now we can start patch cabal packages regarding arm android specific issues using configuration-ghc-android.nix.

**Comment by geraldus** [comment]
@wavewave hi, I would be happy to chat with you about Android with GHC development, is it possible (and how)?

**Comment by wavewave** [comment]
@geraldus Sure. I love to discuss about it. Currently, ghc-android environment is well integrated with nixpkgs (in haskell-ng way.) 

Currently nix-build-ghc-android has a copy of haskell-modules from nixpkgs not to mess up nixpkgs main trunk, but I think it's quite possible to be included in nixpkgs although we need to make some standardization in naming etc. One issue is all native dependencies must be cross-compiled, so how to systematically name them in the current nixpkgs.

**Comment by geraldus** [comment]
@wavewave have a nice holidays!
Sorry for delayed answer.  My Android experience is in very early stage, and I have some simple (or even silly) questions.  I want to play with Android and write few apps, initially I decided to use Android Studio and learn Android basics, in other words learn some basic Java and Android SDK.  I'm interested in OpenGL ES in my future Android apps.

I love Haskell, so if there is a possibility to write Android apps using it, than I'd better go hard and write Haskell code rather than write Java code.  So, the first question: can I use Haskell for GUI and graphics?

The second question is related to IDE.  Initially I wanted to use Android Studio, but editor of my choice is Emacs and it seems that it is possible to write Android app using Emacs and even have emulation too.  I know `Emacs + Haskell -> Android` sounds crazy, so I want to hear what you think about this?

As for NixOS, I love it too, but unfortunately I still can't find a time to learn it deeper and most things such wrappers and derivations are unclear for me (at least now).

**Comment by wavewave** [comment]
@geraldus Hi. Happy new year! I am currently developing android app using Haskell (not entirely Haskell, using both Java and Haskell). So yes, it's possible to make GUI program. How to do that is a matter of calling Java function and passing data structure through Java Native Interface. It involves a significant writing of some infrastructure. There are some hiccups due to the peculiarity of Android system (especially stack frame related to a thread), so I had to make a bridge runtime (written in C++) for smoothing some bad behavior when communicating and also improved haskell protocol buffer library to support sum types. 

As for Android Studio, I do not think that it is impossible in principle, but I guess there are lots of difficulties. I am just working with emacs and CLI only. But my build system on Java side is to use Gradle, so it should be compatible with the current version of Android Studio. BTW, I am rather anti-IDE (this is purely personal preference. I am optimizing myself to all command line mode tools except web browser. :-) )  so on my side, I would not pursue for that direction much.

p.s. If you try to make android game thing, then there's completely different path by using NativeActivity. In this approach, Java is not needed at all, but then all the GUI components must be provided from developer side. [Keera Studio](http://keera.co.uk/blog/) is one of the state-of-the-arts leader for Android game making. They use SDL for GUI AFAIK.

**Comment by geraldus** [comment]
@wavewave thank you very much for such detailed answer.  I had similar thoughts about some wrappers or shims (and guessed that this will take much effort because the early stage of Haskell-to-Android-workflow).  Yeah, I've seen MagicCookies announcement in Cafe, thank you for link, game development is a dream for now, but in future I hope to put my hands on that direction.  Is it possible to chat with you some other place rather that GitHub?

**Comment by garbas** [comment]
@wavewave would you consider making a PR with changes to nixpkgs?

**Comment by peti** [comment]
Closing since this seems to be stalled / dead.
